### ISSUE TITLE
docker client trying to access useradd

### ISSUE THREAD

**Issue by fbe** [docker/docker#26560]
Docker version: 1.11.0 on Gentoo x86_64

**docker client trying to access useradd / adduser**

I saw that a simple docker ps tries to access useradd / adduser binaries. That doesn't make sense / causes security alerts on my system.

**Steps to reproduce the issue:**
1. strace docker ps

**Describe the results you received:**
https://gist.github.com/fbe/0d8b2c63520a4ff37f2d6397a75df509#file-what-the-f-is-docker-client-doing-strace-L291 till line 310 - docker client trying to access adduser / useradd

**Describe the results you expected:**
Simple communication with the docker.sock but not calling useradd / adduser

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.6.1
 Git commit:   4dc5990
 Built:        
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 178
Server Version: 1.11.0
Storage Driver: devicemapper
 Pool Name: docker-253:4-131073-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.319 GB
 Data Space Total: 107.4 GB
 Data Space Available: 45.68 GB
 Metadata Space Used: 10.71 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: host bridge null
Kernel Version: 4.7.1-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.34 GiB
Name: gewuerzgurke
ID: WURD:3R62:6O2P:POHA:B2KY:3MOD:OJ2X:AOQN:4R2R:FSCN:XODK:DJ2M
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
localhost.

**Comment by justincormack** [comment]
Are you using user namespaces? These do try to do this if you do not create the default remap user. I wasnt aware of any other use cases but can check if you are not.

**Comment by justincormack** [comment]
I don't see this in my strace for 1.12.1. I can install a 1.11.x machine to test, but it looks like this may be fixed now.

**Comment by fbe** [comment]
Hi @justincormack,

i'm currently not using user namespaces (and they shouldn't affect the client, too?)

**Comment by fbe** [comment]
docker run -t -i --privileged docker:1.11 sh -c 'apk update && apk add strace && strace docker'

is the proper way to reproduce the issue in 1.11

**Comment by vdemeester** [comment]
The only part I think of that is calling `useradd`/`adduser` is https://github.com/docker/docker/blob/07f580489908bf6a3373daac1473045406e1130d/pkg/idtools/usergroupadd_linux.go#L89 — but pretty sure it's only on deamon side, and when userns is enabled :sweat_smile:

**Comment by justincormack** [comment]
It was this https://github.com/docker/docker/pull/21820 ie it was accidentally testing for the location of the `useradd` binary, which is used in the userns case, but it was happening on all `docker` invocations by mistake...

Going to close as fixed in current releases.
