### ISSUE TITLE
Docker-compose dns linking working not

### ISSUE THREAD

**Issue by majuansari** [docker/docker#26571]
Hi ,

Please see the the following compose file

version: '2'

services:

### core Utilities Container ###########################

    core:
        build:
            context: ./docker/core
        volumes_from:
            - volumes_source
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        ports:
           - "22:22"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./docker/php-fpm/php7
        volumes_from:
            - volumes_source
        expose:
            - "9000"
        links:
            - core
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:10.0.75.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
            - PHP_IDE_CONFIG="serverName=laravel"

### Apache Server Container ##################################

    apache2:
        build:
            context: ./docker/apache2
            args:
                - PHP_SOCKET="php-fpm:9000"
                - WEB_DOCUMENT_ROOT="/var/www/"
        volumes_from:
            - volumes_source
        volumes:
            - ./logs/apache2:/var/log/apache2
        ports:
            - "8080:80"
            - "443:443"
        links:
            - php-fpm

### MySQL Container #########################################

    mysql:
        build:
            context: ./docker/mysql/5.6
        volumes_from:
            - volumes_data
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root

### Laravel Application Code Container ######################

    volumes_source:
        image: tianon/true
        volumes:
            - ../:/var/www/laravel
            # Demonstration of how to mount multiple sites
            # - ../../site_a/:/var/www/site_a
            # - ../../site_b/:/var/www/site_b

### Databases Data Container ################################

    volumes_data:
        image: tianon/true
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./data/postgres:/var/lib/postgresql/data
            - ./data/memcached:/var/lib/memcached
            - ./data/redis:/data
            - ./data/neo4j:/var/lib/neo4j/data
            - ./data/mongo:/data/db
            - ./data/aerospike:/opt/aerospike/data
            - ./data/sessions:/sessions
            - ./data/elasticsearch/data:/usr/share/elasticsearch/data

Not sure what is wrong with above composer file. But I cannot connect from apache server using "php-fpm" key to php-fpm.

Can any one help me please ?

**Comment by mlaventure** [comment]
@majuansari Could you provide your `docker version` and `docker info` please?

**Comment by majuansari** [comment]
Thanks . Got it fixed . php-fpm container had some issues
