### ISSUE TITLE
Minor: Provide "Stop/Start Docker" option for Docker for Mac / Win

### ISSUE THREAD

**Issue by FuriouslyCurious** [docker/docker#26587]
Docker for Mac daemon has two options for "Quit Docker" and "Restart Docker".

When I need to free up some memory, it will be super to have "Stop/Start Docker" option too.  If there is agreement for this feature request, I can submit a pull request for it.

**Comment by mlaventure** [comment]
ping @justincormack

**Comment by justincormack** [comment]
Docker for Mac is not an open source project so you cannot create a PR; feature requests are best addressed in https://github.com/docker/for-mac/issues rather than here.

**Comment by mlaventure** [comment]
@FuriouslyCurious given @justincormack answer, could you open an issue on https://github.com/docker/for-mac instead?

I'll be closing this one meanwhile.

Thanks!

**Comment by FuriouslyCurious** [comment]
Woops - my bad I missed the mac repository.  I will resubmit the issue to correct repository.   Thank you!

**Comment by thaJeztah** [comment]
No worries! That issue tracker was only opened recently :smile:
