### ISSUE TITLE
Docker.com's home page should also include linux

### ISSUE THREAD

**Issue by musaffa** [docker/docker#26600]
Currently Docker's [home page](https://www.docker.com/) shows only `Get docker for Mac` and `Get docker for Windows`. I cannot find any reference to Linux in the home page. For newcomers to docker, they would falsely assume that Linux isn't supported by docker. Shouldn't `Get docker for Linux` be in the home page as well?

**Comment by estesp** [comment]
The Docker open source project doesn't maintain docker.com, so maybe further discussion will have to be funneled to whatever team is appropriate.

However, the largest button at the top of docker.com (labeled "Getting Started With Docker") goes to the following page, which clearly lists all platforms, including Linux:
<img width="698" alt="docker com-platforms" src="https://cloud.githubusercontent.com/assets/1397980/18566668/9ef94548-7b49-11e6-8afb-adf2eb81f64f.png">

The docker.com direct links that I assume you are referring to are in a section of the page highlighting DockerCon Seattle 2016, at which those 2 products (Mac and Windows) were announced publicly, so I assume the links to download them there is strongly associated with that DockerCon call-out and will probably be replaced by something else in the future.

**Comment by musaffa** [comment]
It may take almost a year for that section highlighting DockerCon Seattle 2016 to change. Better if all the supported OSs get fair treatment in the home page.

**Comment by thaJeztah** [comment]
This was forwarded to the team managing the docker.com website earlier today, so I guess they'll work on it

/cc @hansfrederickbrown want this issue to be kept open for tracking?

**Comment by unclejack** [comment]
Folks, I'll close this issue now as it's not related to the open source project. This issue can be opened again if someone decides it needs to be kept open.
