### ISSUE TITLE
Specify network subnet/iprange when using deploy

### ISSUE THREAD

**Issue by chernals** [docker/docker#26621]
**Description**

`docker deploy` will attempt to create a new overlay network. My problem is that the default settings use the same subnet than my hosts subnet, hence a lot of issues from that side.

One workaround I tried was to create the network with 'docker network create --driver overlay --subnet x.x.x.x/16 my_network' but then deploy complains that the network can't be created because it already exists.

I'm not able to to find information on how to specify network options.

I'm using this version:

# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Comment by dnephin** [comment]
Related to #26327

Network settings are not portable, so they will not be part of the "bundle" (dab).  

We don't yet have a solution for non-portable options. My opinion is that we need a separate config for them.

Allowing `deploy` to use an existing network sounds like a good idea as well.

**Comment by thaJeztah** [comment]
Let me close this issue for now, as https://github.com/docker/docker/issues/26327 is tracking this
