### ISSUE TITLE
docker service is running but it says not running

### ISSUE THREAD

**Issue by mafiya69** [docker/docker#26626]
**Description**

**Steps to reproduce the issue:**
1. `sudo systemctl status docker`shows `docker` is running.
2. `docker ps` shows `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Describe the results you received:**
![screenshot from 2016-09-16 17-40-57](https://cloud.githubusercontent.com/assets/7235212/18585526/0d4cd7b2-7c35-11e6-8955-fa8b606c2cae.png)

**Describe the results you expected:**
`docker ps` is to list containers.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
uname -a 
Linux mnciitbhu 4.7.3-2-ARCH #1 SMP PREEMPT Thu Sep 8 09:44:02 CEST 2016 x86_64 GNU/Linux
```

**Comment by justincormack** [comment]
does it work if you do `sudo docker ps`? If so, you have not added your user to the `docker` group allowing you to access the docker socket.

**Comment by cpuguy83** [comment]
Closing since this is not likely a docker issue. Feel free to discuss here... but preferably it would be easier to help on #docker on IRC or in the community slack channel.

**Comment by mafiya69** [comment]
Though I am now able to use `docker`. I am getting Network Related issues while doing a `pull`.
```
$ docker pull ubuntu:lastest
Pulling repository docker.io/library/ubuntu
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/ubuntu/images. You may want to check your internet connection or if you are behind a proxy.
```
Though I am behind a proxy server, I am using VPN and everyting on my system works perfectly with that.
