### ISSUE TITLE
error starting docker container in a 3.8 kernel  

### ISSUE THREAD

**Issue by laithrafid** [docker/docker#26630]
error starting docker container in a 3.8 kernel 

**Steps to reproduce the issue:**
1. have the same kernel and run hello world 

## here's the error i'm getting : 

sudo docker run hello-world
runtime/cgo: pthread_create failed: Invalid argument
SIGABRT: abort
PC=0x7fb25e2755f7 m=0

goroutine 0 [idle]:

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/lib/golang/src/runtime/asm_amd64.s:245 fp=0xc82005e770 sp=0xc82005e768
runtime.main()
        /usr/lib/golang/src/runtime/proc.go:126 +0x62 fp=0xc82005e7c0 sp=0xc82005e770
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82005e7c8 sp=0xc82005e7c0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1998 +0x1

rax    0x0
rbx    0x7fb25e5fc868
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x58a0
rsi    0x58a0
rbp    0x1a65092
rsp    0x7fff7bab78d8
r8     0xa
r9     0x7fb25f28f880
r10    0x8
r11    0x206
r12    0x24e90a0
r13    0x1a114b0
r14    0x0
r15    0x8
rip    0x7fb25e2755f7
rflags 0x206
cs     0x33
fs     0x0
gs     0x0
docker: Error response from daemon: Cannot start container acece46a8455e80a37952f4df0594073c9b11bdcc1a673528480bff12246c42c: [9] System error: read parent: connection reset by peer.

## docker info
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-204087648-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 310.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 23.19 GB
 Metadata Space Used: 1.159 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.18.35+dmx.2.2.0.6-ga2b05ec
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 56
Total Memory: 123.8 GiB
Name: dhcp-10-17-17-40.diablo.lan
ID: 6HXL:GNX2:IX3Z:IQTT:JVKF:KA2I:SMKP:N5AU:TTKZ:K62V:NC5W:4ZVQ
Registries: docker.io (secure)

## docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

**Comment by thaJeztah** [comment]
The minimum required kernel version for docker is 3.10. According to the information above, however, you're running on kernel 3.18? Kernel 3.18 is *not* a standard kernel for CentOS 7 (which runs on kernel 3.10), and you're running custom build of docker from modified sources (d381c64-unsupported). This setup is not supported, so I don't think we can help you resolve this
