### ISSUE TITLE
A shared volume cannot be created if same-name volume has already existed and been removed by another host

### ISSUE THREAD

**Issue by Anvil** [docker/docker#26636]
I'm currently developing a (unfortunately proprietary) Ceph Docker volume driver for a swarm (not swarm-mode) cluster. Under some circumstances a node is no longer able to create a volume if it has already existed and been deleted before.

The setup:
We have a some Ubuntu 14.04 servers running docker-engine 1.12.1. All docker engines are configured to use the Ceph plugin. All docker engines can access any Ceph volume they want. A `docker volume ls` on any node shows all volumes created on Ceph by all nodes.

Here is my 100% reproducible way for this issue:
1. On node1, a `docker volume create -d mydriver --name volume1` command is ran. As expected, the docker engine issues a `/VolumeDriver.Create` to the plugin and the volume is successfully created. 
2. Still on node1, the output of a `docker volume ls` reports indeed a `mydriver volume1` line.
3. On node2, a `docker volume ls` reports the same `mydriver volume1` line. 
4. Still on node2, a `docker volume rm volume1` command is ran. The docker engine issues a `/VolumeDriver.Remove` to the Ceph plugin. The volume is successfully removed by the 
5. On node2, a `docker volume ls` no longer reports the `mydriver volume1`. 
6. Same on node1.
7. Still on node1, a  `docker volume create -d mydriver --name volume1` command is ran. 

**Describe the results you received:**
A  `/VolumeDriver.Create` request is **NOT** sent to the plugin. The volume is not created, but docker reports no error. `docker volume ls` on any node does not show the `mydriver volume1` line.

**Describe the results you expected:**
I would expect the docker engine to rely on the volume plugin to learn/know if the volume exists or not and, if not, create it.

**Additional information you deem important (e.g. issue happens only occasionally):**
After this procedure, a `docker volume create -d mydriver --name volume1` on node2 (the node we removed on the volume on) will work.

**Output of `docker version`:** 

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 147
Server Version: 1.12.1
Storage Driver: btrfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local ceph
 Network: null bridge host overlay
 Authorization: ceph-auth
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-24-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.81 GiB
Name: ***censored for internal security reasons***
ID: VOMS:2IV2:PUXI:6RGP:N2OF:BWYT:7AXK:ZJOK:QUI3:JC5G:UVZA:A4JJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 com.orange.vdc.swarm.site='sph'
 com.orange.vdc.swarm.env='prod'
 com.orange.vdc.swarm.hosttype='hardware'
Cluster Store: consul://***censored for internal security reasons***
Cluster Advertise: <some ip>:<some port>
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):** all servers physical.

**Comment by thaJeztah** [comment]
ping @cpuguy83 I _think_ this may be a duplicate; didn't we have a PR to fix/change that behavior?

**Comment by cpuguy83** [comment]
Yes. We now support `docker volume rm -f` for this case.

**Comment by Anvil** [comment]
As far as I appreciate the advise, which does not work here (`unknown shorthand flag: 'f' in -f`), is there any documentation somewhere that will warn people about this behavior / this root cause ?
A prevention mechanism instead of working around the consequences would be better, IMVHO.

**Comment by cpuguy83** [comment]
It doesn't work because it is new and will be in 1.13.

The issue is the volume was deleted "out-of-band", or at least as far as a particular engine is aware.

**Comment by thaJeztah** [comment]
related discussion https://github.com/docker/docker/pull/24205

**Comment by cpuguy83** [comment]
Thanks @thaJeztah I knew we had it somewhere.
I think we have a bad mix of a single-host only aware volume subsystem mixed with external cluster state. Networks don't have this problem since they use a K/V store for this, which we don't do in volumes...
I think we should push more towards enabling this at the swarm level (ie, metadata stored in the swarm state for non-local storage).
