### ISSUE TITLE
Docker not freeing up diskspace even after deleting images (macosx)

### ISSUE THREAD

**Issue by majuansari** [docker/docker#26635]
I did the following to delete images and reclaim disk space. But unfortunately its not working

```
$ df -h
Filesystem      Size   Used  Avail Capacity  iused ifree %iused  Mounted on
/dev/disk1     112Gi  111Gi  330Mi   100% 29237368 84358  100%   /

```
Then:
```

$ docker rm $(docker ps -aq)
$ docker rmi $(docker images -q)

```
But still it does not free up the disk space . 

```
$ df -h
Filesystem      Size   Used  Avail Capacity  iused ifree %iused  Mounted on
/dev/disk1     112Gi  111Gi  329Mi   100% 29237470 84256  100%   /
```

**Comment by justincormack** [comment]
Yes, we are planning to work on this, hoping to get it working for 1.13. A factory reset will free up the space, but obviously loses everything.

**Comment by justincormack** [comment]
We have a tracking issue here https://github.com/docker/for-mac/issues/371, so I am going to close this here as it is specific to the Mac not a general Docker issue.
