### ISSUE TITLE
Docker service restart and exec

### ISSUE THREAD

**Issue by frimdo** [docker/docker#26631]
### Feature idea
I belive docker service is missing a way to restart all replicas of service and way to exec on all replicas of service. Also logs available on one place would be great.

The reason is, that if you want to for example reload config file you updated in volume, you have to restart service inside container (reason of exec) or restart whole container (reason of restart). Without this features you have to remove the service and create new, which cause downtime...
The reason why logs would be great is obvious...

**Steps to reproduce the issue:**
1. docker service update --restart ...
This command would send HUP command to all replicas of service. `--update-parallelism` and `update-delay` would affect parallelism and delay of this action 
2. docker service update --exec ...
This command would exec command on all replicas of service. `--update-parallelism` and `update-delay` would affect parallelism and delay of this action 
3. docker service logs ...
This would show logs, same way as [docker-cloud](https://docs.docker.com/docker-cloud/getting-started/deploy-app/8_view_logs/) does.

**Comment by justincormack** [comment]
logs support is already planned for 1.13

**Comment by mrusme** [comment]
@frimdo I'm voting for this, although I would either stick to the `kill -s` command – as described in #27081 – in order for it to be consistent across all the Engine, Compose and Swarm/Service. Nevertheless, the `parallelism`/`update` option would definitely be useful there as well!

**Comment by alexamirante** [comment]
+1. Currently the only way to reload a configuration file you changed in a volume on all replicas, is to issue a `docker service update`, which would discontinue the service...

**Comment by mrusme** [comment]
Workaround until this has been implemented:

Create a script on the Docker hosts:

```
#!/bin/bash

inotifywait -m -e create,move,delete /the/directory/to/watch/for/changes/ | while read watchline
do
	echo $watchline

	CONTAINER_ID=$(docker ps | grep -i MYCONTAINER | awk '{ print $1 }')

	if [[ -n $CONTAINER_ID ]]
	then
		docker kill -s HUP $CONTAINER_ID
	fi
done
```

Be sure to have it run through an `init.d` script (or however), as soon as the system/Docker boots. In a swarm cluster, this needs to be done on every host, of course.

**Comment by stevvooe** [comment]
@mrusme It sounds like there are three features requested here:

1. Restarting all tasks. This will spawn new container tasks for all existing tasks, honoring rolling update parameters. (@thaJeztah, do we have an issue for this?)
2. Task signaling (sending a HUP to replicas of a service) (see #27081).
3. Task exec. This is more involved. You can already do this by execing on the task host, but we don't autoroute this in swarm.

These are all orthogonal issues. I'd recommend resubmitting these as separate issues to we can focus on the individual users.

**Comment by frimdo** [comment]
Issues [#27551](https://github.com/docker/docker/issues/27551), [#27552](https://github.com/docker/docker/issues/27552), [#27553](https://github.com/docker/docker/issues/27553) created. This issue can be closed now.

**Comment by stevvooe** [comment]
@frimdo Thank you!
