### ISSUE TITLE
Allow user-generation of swarm join tokens

### ISSUE THREAD

**Issue by mboggess** [docker/docker#26632]
I've read through the docs, and it seems that there's no way for a user to generate their own token to give to `swarm init` and then `swarm join` commands. The docs use case is with all docker machines running on one system, and for that use case, it is practical to run `TOKEN=$(docker swarm join-token -q worker)`. However, given a more distributed use case, this workflow doesn't scale. For example, when automating the building and provisioning of Vagrant virtual machines with Ansible, unless the token is known ahead of time, the process for initializing swarm mode can't be part of that automated process.

Thanks!

**Comment by justincormack** [comment]
I think this is a duplicate issue, but I can't find the original at the minute - there was a fair amount of discussion.

**Comment by mboggess** [comment]
Yeah, that's why I created this issue, because I couldn't find one either. I couldn't imagine that no one had talked about this. I'll look harder, but if you spot it, ping me. Thanks!

**Comment by mboggess** [comment]
Yep, that would be it. I'm assuming there's still no plans to give users control over generating the tokens?

**Comment by justincormack** [comment]
There is definitely a plan to make it easier to do scripted setup of a cluster, as it is quite difficult. I don't think that it will necessarily be by allowing the user to set the join tokens though.

**Comment by mboggess** [comment]
Okay, cool. I'll be looking for that. Thanks for you help, @justincormack! 

Closing this out.
