### ISSUE TITLE
Docker does not start - Unit docker.socket failed to load

### ISSUE THREAD

**Issue by dbabits** [docker/docker#26648]
This is the same issue specified in the  issue #2598, which seems to be prematurely closed.

Workarounds suggested there do no work for me.
RedHat 7 3.10.0-229.el7.x86_64
Docker version 1.12.1

**Comment by cpuguy83** [comment]
The linked issue is surely not the one you wanted.

Can you provide more details please? Specifically the ones from the issue template: `docker info`, and `docker version` (I realize you may not be able to grab all of this if Docker is not starting), as well as the daemon logs.

A copy of your unit file may also help.

**Comment by dls314** [comment]
@dbabits IIRC, that symptom was what happened when I had a dockerd -H fd:// specified for startup.

**Comment by dbabits** [comment]
My issue matches exactly the one I linked to and I tried all the
workarounds.

I'm not able to login to github from behind my corporate firewall (can read
though), so cannot post any output easily.

Plus, like you noted, there's no output to paste since docker is not
starting.

I tried the latest available version at the time of this writing (1.12?)
and one before that(1.11 I believe).

Right now I'm running on 1.10.

El sept. 18, 2016 9:54 AM, "Brian Goff" <notifications@github.com> escribió:

The linked issue is surely not the one you wanted.

Can you provide more details please? Specifically the ones from the issue
template: docker info, and docker version (I realize you may not be able to
grab all of this if Docker is not starting), as well as the daemon logs.

A copy of your unit file may also help.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/26648#issuecomment-247848932>, or mute
the thread

**Comment by programmerq** [comment]
The issue you linked, #2598 is a _very old_ issue, and has nothing to do with systemd. It looks more like you accidentally left out a digit at the end perhaps?

**Comment by thaJeztah** [comment]
Based on the information above, it looks like you have a systemd unit file that still contains `fd://`, and tries to use socket activation. This changed in docker 1.12; see the warning at the start of the release notes; https://github.com/docker/docker/releases/tag/v1.12.1

**Comment by thaJeztah** [comment]
Closing as I don't think there's a bug here (see my comment above), but feel free to comment if you think I closed by mistake
