### ISSUE TITLE
Question : Is this the right way?

### ISSUE THREAD

**Issue by majuansari** [docker/docker#26657]
Hi, 

I have a docker-compose file which includes following services

mysql
php
apache2
nginx

I want to start a lamp or lemp environment using following commands instead of entering each service name
docker-compose up lamp
or
docker-compose up lemp

so for that I created 2 more services 

lamp:
        image: tianon/true
        depends_on:
            - php-fpm
            - apache2
            - mysql

lemp:
        image: tianon/true
        depends_on:
            - php-fpm
            - nginx
            - mysql

Is this fine ? Or is there any better way ?

**Comment by michelvocks** [comment]
Hello @majuansari 
Your question is not related to docker nor an issue related to docker. I think this kind of questions should go into [IRC or Community Forums](https://github.com/docker/docker#talking-to-other-docker-users-and-contributors).

To answer your question. I would use [multiple compose files](https://docs.docker.com/compose/extends/) to have one which defines the default services (php/mysql) and two other for nginx and apache2.

**Comment by majuansari** [comment]
Sorry , But my question was regarding docker composer.

Is there any way to start  services using another service with docker-compose up?

**Comment by cpuguy83** [comment]
Closing since this isn't really a Docker issue.

If you have questions, feel free to hop on #docker on IRC, forums.docker.com, or the community slack channel with lots of people happy to help.

It also may help to just try the thing you are asking about to see if it works?
