### ISSUE TITLE
Golang client API - client.CopyToContainer doesn't work

### ISSUE THREAD

**Issue by fasthall** [docker/docker#26652]
**Description**
Using golang client package to implement copying host file to container. The following lines are the codes:
```
file, err := os.Open("HOST_FILE_TO_BE_COPIED")
err = cli.CopyToContainer(context.Background(), CONTAINER_ID, "/testfile", bufio.NewReader(file), types.CopyToContainerOptions{
    AllowOverwriteDirWithFile: true,
}) 
```
It throws error. `docker cp HOST_FILE_TO_BE_COPIED CONTAINER_ID:/testfile` works however.

**Steps to reproduce the issue:**
1. Run a container with ID `CONTAINER_ID`
2. Prepare the host file and run the above code.

**Describe the results you received:**
```
Error response from daemon: lstat /var/lib/docker/aufs/mnt/20dc4775a22f47ca73b55353ccbfe528b21430934f449172f0e72cf08dd514cb/testfile: no such file or directory
```
20dc4775a22f47ca73b55353ccbfe528b21430934f449172f0e72cf08dd514cb is the CONTAINER_ID.

**Describe the results you expected:**
Having a file in the container with the same content of host file.

**Additional information you deem important (e.g. issue happens only occasionally):**
CopyFromContainer works. I verified `file` is a legit `Reader`.

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:30:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 33
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.792 GiB
Name: erlang
ID: PS5B:IWXO:AQTP:GBNU:2WXE:623Z:2XCH:HQSW:VBJJ:RYPQ:O33O:EZZX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: fasthall
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running Docker daemon on ubuntu 14.04.
Docker golang client is up-to-date.

**Comment by cpuguy83** [comment]
This is the same function the CLI uses.
Please see https://github.com/docker/docker/blob/master/cli/command/container/cp.go#L271 for how the CLI uses it.

If you find what's wrong maybe you can update the code doc string?

Closing since this isn't really an issue.

**Comment by TimSatke** [comment]
https://github.com/docker/docker/blob/master/cli/command/container/cp.go#L271

Link is broken, maybe https://github.com/moby/moby/blob/master/client/container_copy.go ?

**Comment by vrongmeal** [comment]
@fasthall Did you solve this issue? I am facing the same problems...

**Comment by djherbis** [comment]
I was also looking into this, got it to work by doing looking it up in the cli as suggested:
https://github.com/docker/cli/blob/b1d27091e50595fecd8a2a4429557b70681395b2/cli/command/container/cp.go#L249

Which points to [archive](https://godoc.org/github.com/docker/docker/pkg/archive), simplest example was archive.Generate's code: https://github.com/moby/moby/blob/master/pkg/archive/wrap.go#L25

Which shows you just want to use the std. libs tar.Writer to write a bytes that should be read by the reader you hand to CopyToContainer (ex. they use bytes.Buffer).

**Comment by vrongmeal** [comment]
Okay, so here's a snippet of the code I used to create a Tar archive (faced a similar problem and this is probably the only part that goes wrong).

```golang
func NewTarArchiveFromPath(path string) (io.Reader, error) {
	var buf bytes.Buffer
	tw := tar.NewWriter(&buf)

	ok := filepath.Walk(path, func(file string, fi os.FileInfo, err error) error {
		if err != nil {
			return err
		}

		header, err := tar.FileInfoHeader(fi, fi.Name())
		if err != nil {
			return err
		}
		header.Name = strings.TrimPrefix(strings.Replace(file, path, "", -1), string(filepath.Separator))
		err = tw.WriteHeader(header)
		if err != nil {
			return err
		}

		f, err := os.Open(file)
		if err != nil {
			return err
		}

		if fi.IsDir() {
			return nil
		}

		_, err = io.Copy(tw, f)
		if err != nil {
			return err
		}

		err = f.Close()
		if err != nil {
			return err
		}
		return nil
	})

	if ok != nil {
		return nil, ok
	}
	ok = tw.Close()
	if ok != nil {
		return nil, ok
	}
	return bufio.NewReader(&buf), nil
}
```

**Comment by djherbis** [comment]
Have you tried a minimal header instead of FileInfoHeader?

I'm just using tar.Header{Name: "name", Size: size}.

Also, how are you calling CopyToContainer (what args, how is the returned reader passed)?

Any calling bufio.NewReader on a bytes.Buffer is probably redundant since the data is already buffered (in the bytes.Buffer).

**Comment by vrongmeal** [comment]
> Also calling bufio.NewReader on a bytes.Buffer is probably redundant since the data is already buffered (in the bytes.Buffer).

@djherbis Thanks for pointing this out

> Have you tried a minimal header instead of FileInfoHeader?

I actually haven't given any thought on this but looking at https://github.com/moby/moby/blob/master/pkg/archive/wrap.go#L31-L34 using `tar.Header` would be just fine.

> how are you calling CopyToContainer (what args, how is the returned reader passed)?

So this is the function that takes the tar archive as a parameter and copies it to the container:

```golang
func CopyToContainer(ctx context.Context, cli *client.Client, containerID, destination string, reader io.Reader) error {
	config := types.CopyToContainerOptions{
		AllowOverwriteDirWithFile: true,
	}
	err := cli.CopyToContainer(ctx, containerID, destination, reader, config)
	if err != nil {
		return err
	}
	return nil
}
```

_You can ofcourse set custom copy options (I didn't need those)_

What you can simply do is this:

```golang
ctx := context.Background()
cli, err := client.NewEnvClient()
if err != nil {
	panic(err)
}

archive, err := NewTarArchiveFromPath("/some/path/here")
if err != nil {
	panic(err)
}

err = CopyToContainer(ctx, cli, "container-id-here", "/path/in/container", archive)
if err != nil {
	panic(err)
}
```

**Comment by djherbis** [comment]
Another sidenote, I believe:
```go
header.Name = strings.TrimPrefix(strings.Replace(file, path, "", -1), string(filepath.Separator))
```
can be replaced with:
```go 
header.Name = filepath.Rel(path, file)
```

**Comment by djherbis** [comment]
You can probably try reducing to just using the tar.Header and see if that helps, I don't see anything wrong with how you cal CopyToContainer, you might also try just calling this:
https://godoc.org/github.com/docker/docker/pkg/archive#Tar

In place of your NewTarArchiveFromPath call, it looks equiv. to me.

**Comment by vrongmeal** [comment]
@djherbis just to clearify, the code works fine (i faced problem some time back, just thought that i'd add what i did here to solve the problem)

Also, I am unable use package `"github.com/docker/docker/pkg/archive"` with go modules (there's this another huge issue that i haven't figured out how to solve).

**Comment by rohit7ce** [comment]
I am facing the issue 
Error: No such container:path: 2aa3e0826e80e1ccd050b3640aaf58539f973bd499b8758f8cabe4672a6b2b8b:/keys

It works fine with docker cp.

**Comment by kyle-aoki** [comment]
Had issues with this as well. It looks like it silently fails if you don't set up the TAR file correctly.

I used this to fix the issue: `archive.Tar(file.Name(), archive.Gzip)`

Had to add this dependency to use `archive.Tar`: `github.com/docker/docker/pkg/archive`
