### ISSUE TITLE
more than one --constraint per service create

### ISSUE THREAD

**Issue by alirezaDavid** [docker/docker#26660]
Hi
Can i have more than one --constraint per service create ?
```
docker service create \
--constraint 'node.hostname == foo' \
--constraint 'node.hostname == boo'
```

**Comment by allencloud** [comment]
@alirezaDavid 
Yes, of course. You can try with two constraints like:
```
root@ubuntu:~# docker service create --constraint "node.role == manager" --constraint "node.hostname != node-2" ubuntu:14.04 sleep 10000
8x298tq79upqw9kmmo55rp1m1
root@ubuntu:~#
```

**Comment by thaJeztah** [comment]
Thanks for answering @allencloud 

Looks like the docs are not very clear on this, and could use another example; https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints-constraint

I've assigned myself, I'll create a PR to improve this

**Comment by alirezaDavid** [comment]
@allencloud Thanks a , my problem solved.
