### ISSUE TITLE
Docker 1.12 Swarm Mode Persistent data

### ISSUE THREAD

**Issue by FarhadF** [docker/docker#26663]
Question: How to manage data volumes in swarm mode?(Pretty Awesome Feature, Good job guys), (I'm sure it will be a popular question)
Managing volumes on single docker host via local driver is pretty straight forward.
Now with swarm mode , I couldn't find enough documentation to demystify the issue.
So the case: I'm running swarm mode, got some containers that require persistent data. I'm running swarm mode in production so performance is a factor. Because of that I already invested in some SAN storage devices that are block storage. Lets say I'm Using some Virtualization technology to host my swarm docker-engines in VMs. I created a LUN for storing my docker volumes.
To do:
Instruct Docker to create and store required volumes on that LUN. Probably expose it to the underlying operating system first (lets say we're using debian)
Requirements:
Using swarm mode for high availability I expect if one docker engine system fails containers will start on other nodes with  persistent data attached. 
P.S I don't want to use flocker to copy the stuff around, thats why I got my shared storage (SAN).

**Comment by cpuguy83** [comment]
@FarhadF See https://github.com/docker/docker/pull/25776
If you have questions feel free to hop on #docekr on IRC or the community slack and ping me.
