### ISSUE TITLE
Gelf logging driver never passes newlines ('\n)

### ISSUE THREAD

**Issue by itai-codefresh** [docker/docker#26670]
**Description**

In case of using gelf as the logging driver, it will never get newlines which makes it not usable because you can't show the logs formatted correctly to users.

**Steps to reproduce the issue:**

I am using this as my gelf server: https://github.com/wavded/graygelf 
```
var gelfserver = require('graygelf/server');
var gelfServer = gelfserver();
gelfServer.on('message', (gelf) => {
    console.log('received message', gelf.short_message);
});
gelfServer.listen(5001);

```

1. Run this on your localhost
2. Create a new container and attach the gelf server above as the logging driver: 
`docker run --log-driver=gelf --log-opt gelf-address=udp://localhost:5001 ubuntu bash`
3. Run a command that generates multiple lines: 
`bash -c "for i in {1..5}; do echo hello; done"`
4. Debug the gelf server and see that every short_message will only contain \r but never a \n.
for example: "hello\r".

**Output of `docker version`:**
```
Client:
 Version:      1.12.0
 API version:  1.24
```

**Comment by thaJeztah** [comment]
This is because a log entry is generated for each line, delimited by `\n`. The `\n` is stripped when sending those log entries. You can get the original output back again by joining the log entries with a `\n`

**Comment by itai-codefresh** [comment]
You are right. Every time a message is received i should address is as a newline.
The other problem this generates is that i don't receive anything until a newline is reached.
For example if i do 'docker pull' then i will only get an event to the gelf server after the layer has finished. This means that gelf is not a good choice if you want to live stream the output from your containers.

**Comment by thaJeztah** [comment]
The same applies to all logging drivers in Docker. There's no way for docker to decide when to send a new log entry, other than using a newline for that. Afaik, that's how most logging systems work, but perhaps @cpuguy83 can fill me in on that one

**Comment by itai-codefresh** [comment]
If that's how all the logging drivers work, than how does the cli knows how to show a docker pull command correctly?
It must read the messages from the json driver, this means that messages that only contain '\r' must be in the file before an end of a line.
Am i wrong?

**Comment by thaJeztah** [comment]
Docker pull is not sent over the logging driver (unless you're running docker-in-docker); the logging drivers only send stderr/stdout from the container's process. Docker pull information is sent back to the client through the remote API

To get "real time" output  from a container, you can always run the container in the foreground, and attach to it.

**Comment by thaJeztah** [comment]
See this endpoint for pulling an image: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-an-image

**Comment by itai-codefresh** [comment]
You are right @thaJeztah.
Thanks a lot for clarifying this for me.
I am closing this.

**Comment by thaJeztah** [comment]
You're welcome!
