### ISSUE TITLE
ubuntu-xenial armhf deb archives not trusted

### ISSUE THREAD

**Issue by luxas** [docker/docker#26688]
**Description**
I'm trying to install docker on scaleway on an **armhf ubuntu xenial** node.

**Steps to reproduce the issue:**
1. `curl get.docker.com | bash`

**Describe the results you received:**
```
Get:4 https://apt.dockerproject.org/repo ubuntu-xenial InRelease [30.2 kB]
Get:5 https://apt.dockerproject.org/repo ubuntu-xenial/main armhf Packages [931 B]
Err:5 https://apt.dockerproject.org/repo ubuntu-xenial/main armhf Packages
  Hash Sum mismatch
Fetched 31.2 kB in 2s (12.8 kB/s)
Reading package lists... Done
E: Failed to fetch store:/var/lib/apt/lists/partial/apt.dockerproject.org_repo_dists_ubuntu-xenial_main_binary-armhf_Packages.bz2  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Describe the results you expected:**
Docker should install properly

cc @DieterReuter @Govinda-Fichtner @tianon @StefanScherer @moul

**Comment by thaJeztah** [comment]
Afaik, we currently only ship arm packages for raspbian. _However_ there looks to be a directory in the repository, with an empty packages list; http://apt.dockerproject.org/repo/dists/ubuntu-xenial/main/binary-armhf/

ping @mlaventure could you take a look? I think that needs to be removed?

**Comment by luxas** [comment]
Another great feature for the get.docker.com script would be the possibility to override the distro, so I could run `curl get.docker.com | distro="raspbian-jessie" bash` or something.

That would fix this issue

**Comment by thaJeztah** [comment]
@luxas we try to keep the script "simple", as it should only be used to quickly bootstrap/setup a docker machine. For more advanced things (and for production use), it's better to manually set up.

**Comment by mlaventure** [comment]
The checksum mismatch should be fixed now.

However, if using the script you would have to update it manually to force the use of `raspbian-jessie` for the flavor.

Thanks for the report :)
