### ISSUE TITLE
Application callbacks for docker start/stop/checkpoint/restore

### ISSUE THREAD

**Issue by hkvemuri** [docker/docker#26694]
**Description**

Now that the pull request for checkpoint/restore https://github.com/docker/docker/pull/22049 has been merged, I am creating a new issue as state in the pull request for additional functionality.

We could perhaps introduce callbacks into the container for each of these actions performed from the docker CLI / API

    docker start
    docker stop
    docker checkpoint
    docker restore

These could as simple as the entry point executable, like the one specified in the compose file. This can aid in the application within the container do some pre/post processing before the docker management layers perform operations on the container. For e.g. prior to a checkpoint the application can perhaps do a sync of its in memory data structures to persistent storage. Similarly a restore could load back the stuff into memory.

**Comment by thaJeztah** [comment]
This feels similar to https://github.com/docker/docker/pull/17021

ping @crosbymichael @jfrazelle @mlaventure PTAL

**Comment by mlaventure** [comment]
I think this is actually a different scenario.

If I'm reading the description right, the goal here would be to have a process be ran from "inside the container" I'm guessing  to signal the main application of the changed state in case it needs special processing.

I personally think that this isn't needed. The changes being made by `docker` (i.e `pause`, `resume`, `checkpoint`) shouldn't affect the application in any unconventional way. If it does, I'd rather we try to fix that in the way docker apply those changes.

@hkvemuri do you have a concrete example in mind that you could share?

**Comment by hkvemuri** [comment]
@mlaventure The use case I have in mind is similar to that of a Virtual machine snapshot. When the VM snapshot is initiated, the application within the VM needs to be moved to a consistent state (such as no database transactions in progress) so that the virtual machine management software can obtain a consistent snapshot of the VM. Otherwise the snapshot cannot be used.

**Comment by mlaventure** [comment]
@hkvemuri the process is first stopped/paused then a snapshot is made. On restore the transaction should resume exactly where it was or fail transparently if it depends on a resource that's no longer ready/available for this transaction.

This should be seamless as it should be a kind of error the application should already have been written  to support.

**Comment by hkvemuri** [comment]
Thanks @mlaventure 
Then pause/resume should work seamlessly. I shall need to try it out using the new bits that have the checkpoint/restore facility.

The last thing is about stopping the container, can a cleanup script be executed, just like the startup script. This would help in case of privileged containers that need to unload kernel modules or make API close calls to exit gracefully.

**Comment by mlaventure** [comment]
@hkvemuri the application should do so when it receives a `SIGTERM`. `docker` also let you define which stop  signal to be sent to the container PID 1 when calling `docker stop`

The stop signal can be defined both in the `Dockerfile` (see [here](https://docs.docker.com/engine/reference/builder/#stopsignal)) and when creating/running a container (see [here](https://docs.docker.com/engine/reference/commandline/run/#stop-container-with-signal-stop-signal))

When stopping a container, you may want to give it more time than the standard 10 secs too via the `--time-limit` flag of `docker stop`

**Comment by hkvemuri** [comment]
Thanks @mlaventure
