### ISSUE TITLE
Docker for windows - non-zero code: 255 - After installing updates (Win Server 2016)

### ISSUE THREAD

**Issue by rpong79** [docker/docker#26693]
**Description**

Getting non-zero code: 255 when building an image after installing Windows 2016 server Updates. 
(KB3188966,KB890830,KB3188128,KB3172729,KB3173423,KB3172989)

Before installing the mandatory Windows Server 2016 updates, building images works fine.
After installing the updates the first command in the build file executes succesfully, but the command after that fails. To get the image build you have to reboot everytime you get the error so you can execute one more command. Then repeat this till image is build.

**Steps to reproduce the issue:**
1. Install Windows Server 2016 tp5 (On Hyper-V or physical server)
2. Install the windows updates and reboot
3. Install windows feature Containers and docker 1.12.0 (or docker 1.12.1). Followed the guide [here](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server)
4. Get the latest Windows 2016 Server Core image (docker pull microsoft/windowsservercore:latest)
5. Build image with below dockerfile (remove .txt as extention).
   [Dockerfile.txt](https://github.com/docker/docker/files/479416/Dockerfile.txt)
6. The first RUN command will execute successfully
7. The second RUN command will fail with:
   _docker : The command 'cmd /S /C powershell -Command Add-WindowsFeature Web-Mgmt-Tools' returned a non-zero code: 255_

**Describe the results you received:**
docker : The command 'cmd /S /C powershell -Command Add-WindowsFeature Web-Mgmt-Tools' returned a non-zero code: 255

**Describe the results you expected:**
No error, but a successfully installed feature

**Additional information you deem important (e.g. issue happens only occasionally):**
I can resolve above by uninstalling the updates KB3172989 and KB3188966.
This works till next reboot. After that the removal has to be done again.

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 4
Server Version: 1.12.0
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1061.amd64fre.rs1_release_svc.160907-0755)
Operating System: Windows Server 2016 Standard Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 1.519 GiB
Name: WIN-5NBDQ1TSB7H
ID: 4OKF:MMVS:X47C:SNF6:N2CQ:LVK4:5QXH:6MOA:Y2EC:J4VL:PMPI:4DRI
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested it on physical Windows 2016 TP5 server and on VM through Hyper-V. 
Both situations give same result.

**Comment by thaJeztah** [comment]
Ping @friism @jhowardmsft

**Comment by friism** [comment]
also checking with @PatrickLang

**Comment by johnstep** [comment]
It works for me on Windows Server 2016 GA with its latest updates (KB3176936, KB3192137, and KB3194798), and Docker 1.12.2-cs2-ws-beta, installed per the following page:

https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

Please give it a try and let me know if it works. Thanks!

**Comment by rpong79** [comment]
It seems to be resolved now with the latest version.
