### ISSUE TITLE
COPY or ADD to Root in Debian AUFS Kernal

### ISSUE THREAD

**Issue by zmetcalf** [docker/docker#26703]
When running a similar command to this on an AUFS enabled kernal:

`COPY ["./scripts/script.sh","/"]`

it produces this error:

`/var/lib/docker/aufs/mnt/0ccc1fc1ba2187577d312a22cfecb2f206f1acfc8afe2b015aa4e82d6f527a49/script.sh: no such file or directory`

This has worked on previous versions of docker and this kernal. I was able to get this to work on a non-aufs machine. 

On the AUFS Machine:
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 750
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 516
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.871 GiB
Name: debian
ID: D42R:ER6V:AGT6:D3VA:AGLH:FHIV:RUR3:VSD3:JPHC:I3TN:2QDI:46P2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8

The AUFS is a VirtualBox Debian image.

The non-AUFS machine (physical)
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 36
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:2-1967667-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.022 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.68 GB
 Metadata Space Used: 7.27 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.134 (2016-09-07)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.4-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.63 GiB
ID: IUEU:W2YB:WCJ2:AGSF:CZIC:EK3O:M2HG:SB43:B2M3:ZNRJ:HRJZ:ZTYX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Insecure Registries:
 127.0.0.0/8

**Comment by thaJeztah** [comment]
I'm not able to reproduce, running on Debian Jessie 8.6 / Kernel 3.16.0-4-amd64


Contents of scripts/script.sh:

```
#!/bin/sh
echo hello
```

Contents of Dockerfile:

```Dockerfile
FROM alpine:latest
COPY ["./scripts/script.sh","/"]
CMD /script.sh
```

```console
chmod +x scripts/script.sh
docker build -t repro-26703 .

Sending build context to Docker daemon 3.584 kB
Step 1 : FROM alpine:latest
 ---> 4e38e38c8ce0
Step 2 : COPY ./scripts/script.sh /
 ---> 5a5e94d971a1
Removing intermediate container eaa2469f6d6d
Step 3 : CMD /script.sh
 ---> Running in 74e4c5974373
 ---> 54657d63a4b9
Removing intermediate container 74e4c5974373
Successfully built 54657d63a4b9
```

Start the image:

```console
$ docker run --rm repro-26703
hello
```

At what stage do you get the "no such file or directory" error? Is that during build, or when starting a container?

**Comment by zmetcalf** [comment]
Sorry, about this. Somewhere with the Debian minor release it created an error. A quick restart cleared up the issue. Sorry again; and thank you for your work on the project!

**Comment by thaJeztah** [comment]
You're welcome! Glad it's resolved

**Comment by rysiekpl** [comment]
We are experiencing this on two servers, both running Debian 8.x and `docker-engine` 1.12.0. This I can also confirm this is not happening on another host running Debian 8.x and `docker-engine` 1.11.x, and that:
 - both `COPY` and `ADD` are affected
 - changing the target directory to anything other than rood directory works

Not sure what might be an issue here, but since these are both production servers running a lot of containers, we'd rather not restart `docker-engine` on them.

**Comment by thaJeztah** [comment]
@rysiekpl would be worth comparing exact kernel versions, and the version of aufs installed, possibly the issue is related to those (and would explain that I could not reproduce)

**Comment by rysiekpl** [comment]
```
# uname -a
Linux hostname 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux
# apt show aufs-tools
Package: aufs-tools
Version: 1:3.2+20130722-1.1
```

**Comment by thaJeztah** [comment]
```
# uname -a
Linux debian-2gb-ams3-01 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux

# apt show auks-tools
Package: aufs-tools
Version: 1:3.2+20130722-1.1
```

Aufs is same version, kernel is more recent. Running `docker-engine 1.12.1`

**Comment by rysiekpl** [comment]
Ok, I'll just have to upgrade docker-engine, reboot into the newest kernel, and see what happens

**Comment by rysiekpl** [comment]
Upgrade fixed the issue. Running 1.12.1 and all seems fine.

**Comment by thaJeztah** [comment]
That's good news! Thanks for reporting back @rysiekpl
