### ISSUE TITLE
Proposal: allow `docker attach` for non-running containers

### ISSUE THREAD

**Issue by aanand** [docker/docker#26705]
In Compose (specifically `docker-compose run`), instead of duplicating all of Docker's considerable client-side attach logic, we'd like to start [shelling out to `docker attach`](https://github.com/docker/compose/issues/3194#issuecomment-220292194) instead, so we have better parity across all platforms (especially Windows).

However, there's currently [client-side code](https://github.com/docker/docker/blob/0640a14b4fcba3715f7cc3bc9444f3c7f4827edd/cli/command/container/attach.go#L56-L58) which prohibits a user from `docker attach`-ing to a non-running container. This is a showstopper: to avoid race conditions, the order of operations must be *create, attach, start*.

I'd like to either remove this logic or add a flag to skip it.

**Comment by tonistiigi** [comment]
Switched labels as this is allowed in API already. Does this have to be cli flag or can't you use the client API? Public `client.ContainerAttach()` method doesn't have this limitation.

**Comment by aanand** [comment]
@tonistiigi We can't use the Go API, because Compose is written in Python! Shelling out to `docker attach` is the only way I can see to re-use Engine's client-side attach code from Compose.

**Comment by thaJeztah** [comment]
Perhaps @tonistiigi meant the `/container/(id or name)/attach/` endpoint, which is used by `client.ContainerAttach()`? https://github.com/docker/docker/blob/3ea762b9f6ba256cf51bd2c35988f0c48bccf0b0/client/container_attach.go#L14-L34, there's also a web socket endpoint; https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/attach-to-a-container-websocket

**Comment by aanand** [comment]
Well, those API endpoints are what we're using right now. The problem is that replicating all of the interactive functionality of `docker run/attach/exec` still involves a great deal of client-side logic (some of which is [detailed here](https://github.com/docker/compose/issues/3194#issuecomment-220292194)).

All of that logic has been [reimplemented in Python](https://github.com/d11wtq/dockerpty), which has inevitably become a huge time sink and a source of many bugs over the years. It's also currently POSIX-only, because attaching interactively on Windows involves a completely different set of system calls.

Accordingly, over time, we'd like to remove it and rely on the Docker client binary instead.

**Comment by thaJeztah** [comment]
Ah, clear. (I think ideally, we should have an improved API to make it easier to use)

**Comment by tonistiigi** [comment]
@aanand How about `docker start -a`, wouldn't that work for you?

**Comment by aanand** [comment]
@tonistiigi I didn't know about `docker start -a`! That will probably work, yes. I'll close this and reopen if it turns out it doesn't work for any reason. Thanks.
