### ISSUE TITLE
Changing the definition of experimental

### ISSUE THREAD

**Issue by icecrime** [docker/docker#26713]
Since 1.12.0, experimental is not a nightly build anymore but is a different channel that follows the same release scheduled than stable. As it stands now, experimental is just a super-set of the stable release, and should not be considered "beta".

**TL;DR:** experimental _is_ a stable release, with a couple features which API stability we don't guarantee.

## Proposal

- [x] Change experimental to be a runtime flag (daemon configuration, environment variable, ...?) rather than a compile-time build tag.
- [ ] Allow the client to discover whether the daemon it's talking to has experimental enabled, and display the extra experimental commands/flags accordingly. Note that this extra round-trip will likely be required to solve #25498 anyways.
- [x] Remove traces of experimental in build scripts (e.g., `DOCKER_EXPERIMENTAL` environment variable).
- [ ] Find a transition path for https://experimental.docker.com (e.g., should it install a regular daemon with the experimental flag enabled?).

**Comment by icecrime** [comment]
Ping @justincormack @vdemeester @tiborvass: WDYT?

**Comment by AkihiroSuda** [comment]
I think it'd be great if there is `https://master.docker.com` (or `https://nightly.docker.com`?) that installs the nightly binaries from https://master.dockerproject.org/ 😃 
Maybe `https://experimental.docker.com` should redirect to that?

**Comment by vdemeester** [comment]
> Change experimental to be a runtime flag (daemon configuration, environment variable, ...?) rather than a compile-time build tag.

Hum, I lean toward to still clearly separate the experimental vs stable binaries (and thus keeping it build-time). Otherwise there is *less* guarantees that a bug in the experimental part is not affecting the stable part of docker. I'm not 100% against having only a flag to switch from stable to experimental but, thinking out loud :angel:.

 >  Allow the client to discover whether the daemon it's talking to has experimental enabled, and display the extra experimental commands/flags accordingly. Note that this extra round-trip will likely be required to solve #25498 anyways.

Definitely :heart_eyes: 

> Find a transition path for https://experimental.docker.com (e.g., should it install a regular daemon with the experimental flag enabled?).

Good point / question. I'm also sharing @AkihiroSuda though on having nightly build available to (for those who really want to live on the edge :sweat_smile:)

**Comment by mlaventure** [comment]
If we introduce a nightly build install script, it'd be better to use a different URL to avoid confusing use of the word `experimental`

**Comment by vdemeester** [comment]
@mlaventure definitely (nightly.docker.com feels good to me :angel:)

**Comment by justincormack** [comment]
Having a single build would be much better. It is really inconvenient at present trying to decide which product to ship (Docker for Mac and Windows channels ship different versions). Letting people try unstable features if they want to is great.

Just drop `experimental.docker.com` - just have a `daemon.json` config option. Nightlies are an independent thing.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/25183

**Comment by icecrime** [comment]
> Hum, I lean toward to still clearly separate the experimental vs stable binaries (and thus keeping it build-time). Otherwise there is less guarantees that a bug in the experimental part is not affecting the stable part of docker. I'm not 100% against having only a flag to switch from stable to experimental but, thinking out loud :angel:.

Several points to that:
- If it's part of the same channel, then a bug in experimental will indeed affect the stable part. And that's good! Because it means that the whole thing needs to be stable :-) The only unstable thing is the interface of the experimental feature.
- To be honest, it's already the case today, where experimental feature are usually fully part of the stable release, with specifically the user interface (CLI and/or API) being hidden behind the `experimental` build tag.

> I think it'd be great if there is https://master.docker.com (or https://nightly.docker.com?) that installs the nightly binaries from https://master.dockerproject.org/ :smiley: 
> Maybe https://experimental.docker.com should redirect to that?

I agree it would be great to have an easy way to install nightly builds, but this is different than experimental. If we consider "experimental" to be a runtime configuration of any stable release, than a nightly build would be closer to a "beta" channel.

**Comment by albers** [comment]
Thinking of how this could affect bash completion. 
So far, experimental features have been ignored in bash completion. 
With this change, I could include and selectively enable experimental featrues.
For my POV, an environment variable would be the best way to trigger experimental mode.

**Comment by tiborvass** [comment]
I agree with https://github.com/docker/docker/issues/26713#issuecomment-248087475

I generally would prefer a config (in daemon.json and flag) without an envvar, but @albers has a good argument.

**Comment by thaJeztah** [comment]
Do you think _all_ experimental features should be enabled/disabled with a single flag, or per-feature? (thinking of the way e.g. Chrome and Firefox allow you to enable individual features)

**Comment by mlaventure** [comment]
I think we already have a flags overload in our binaries :). I prefer having one single flag at least for now. It also would mimic the current behavior with have between the 2 builds (stable and experimental).

@albers I do not mind adding the a ENV variable as an extra vector to the daemon, but I feel that a flag is more natural/convenient. Also note that the decision to enable experimental feature is my current implementation is done by the daemon, not the client

**Comment by justincormack** [comment]
I think a daemon flag is best for now. Completions is an issue, but it needs to be enabled when the daemon starts so I don't see an environment variable is any use.

**Comment by albers** [comment]
How does the CLI detect whether the deamon is running experimental?

With shell means, I could do something like `docker info | grep '^Experimental: true'`, but I think this call ist an expensive one because the daemon has to gather a lot of information. I'd rather have a more lightweight test.

**Comment by thaJeztah** [comment]
@albers it's using a header to detect it (see https://github.com/docker/docker/pull/27223#issuecomment-255252812). Perhaps it should be visible in "docker version", would that make it easier?

**Comment by albers** [comment]
That would be perfect!

**Comment by thaJeztah** [comment]
@albers can you open an issue for that?

**Comment by mlaventure** [comment]
@thaJeztah @albers it's already part of `docker version`, it shows as `Experimental: true` under the server information (it'll show `Experimental: false` otherwise)

**Comment by thaJeztah** [comment]
@mlaventure oh! you're right, lol

**Comment by albers** [comment]
Well that's funny! Thanks @mlaventure @thaJeztah.
