### ISSUE TITLE
Use UAC or create dedicated account during installation instead of asking for administrative account password

### ISSUE THREAD

**Issue by masaeedu** [docker/docker#26728]
When using volume mounts with Docker for Windows, the UI requires the user to enter their Windows username and password:

![Shared drives setting prompts for user's password](https://zmugkg.by3302.livefilestore.com/y3m26ckOwlhjlSV11vHJ9C3YoYHRbIaq67kXeoliwtiG_rCfVTUXq9qupdGmK9I7x9hL4x3fK7BkQ8CjNAri0aewwXI-80UyLvUflCH3gclFPI-vWnBlbYUYcN2gZ6oV5IcgyOhfMyD__qyyLDm1EWgm2nOQmwv0PruxO10pCOMeYc/Docker%20for%20Windows_2016-09-19_17-42-20.png?psid=1)

This seems like the wrong approach, since it results in problems for users that do not have passwords at all (i.e. use PINs or fingerprints), or have specific organizational requirements for their password that are incompatible with what the application can handle. There is a long thread where these issues are discussed [here](https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693). See also #23992, where a number of people were having issues due to special chars in their passwords.

The experience would be better if the installer could create a "docker" user with the appropriate permissions during installation (since the installer runs in an elevated process) and use that for tasks like this later on. This way the user doesn't need to provide docker with an admin password (or even have one).

An alternative solution would be to perform tasks that require administrative privileges in elevated child processes. I'm unfamiliar with Go, but I know that when starting a process using the Windows ShellExecute API, setting the verb to "runas" will prompt the user for elevation and thereafter use an administrative user access token, allowing the new process to carry out volume mounting or user creation tasks.

The latter approach would mean the UAC prompt would appear every time administrative access is required, which is something I would personally prefer, but this might be seen as too inconvenient by others. It is possible for users to set their UAC notification level in Windows settings if they're in a sandbox environment and do not want to see every UAC prompt.

**Comment by cpuguy83** [comment]
ping @justincormack

**Comment by justincormack** [comment]
As this is specifically about Docker for Windows, could you open this in https://github.com/docker/for-win/issues as the Docker for Windows developers can respond more effectively. I know they have discussed various options with Microsoft on this, but I don;t know the specifics.

**Comment by icecrime** [comment]
Cc @dgageot!

**Comment by thaJeztah** [comment]
issue was opened in the docker for Windows tracker; closing this one https://github.com/docker/for-win/issues/94
