### ISSUE TITLE
Remote API Documentation wrong concerning MaximumIOps and MaximumIOBps

### ISSUE THREAD

**Issue by Khazrak** [docker/docker#26739]
**Description**

Docker Remote API Documentation problem concerning MaximumIOps and MaximumIOBps.
In documentation they are written as:
MaximumIOps
MaximumIOBps

But both Dockers code and recording the call (using Wiremock as a proxy between docker cli and docker daemon) says that they really are:
IOMaximumIOps
IOMaximumBandwidth

**Steps to reproduce the issue:**
1. docker -H <REMOTE_HOST> create --io-maxbandwidth=5m ubuntu:14.04
2. compare json to documentation

**Describe the results you received:**
MaximumIOps
MaximumIOBps

**Describe the results you expected:**
IOMaximumIOps
IOMaximumBandwidth

**Additional information you deem important (e.g. issue happens only occasionally):**
Concerns:
docs/reference/api/docker_remote_api.md
docs/reference/api/docker_remote_api_v1.24.md
docs/reference/api/docker_remote_api_v1.25.md

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 2
 Paused: 0
 Stopped: 7
Images: 183
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 314
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.85 GiB
Name: karl-P50
ID: ND5C:QQCW:NNJ4:QSFT:G6QP:MFJK:LDT4:VX6Q:HCSE:HVQ6:ABM6:2KVJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 docker-remote.art.local
 docker-virtual.art.local
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting! Let me open a PR to fix the docs
