### ISSUE TITLE
Windows should use microsoft/windowsservercore base image

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#26734]
**Description**

I tried to compile a Windows docker engine with the given `Dockerfile.windows`, but found out that the base image `windowsservercore` used in this Dockerfile could not be found. The official base image is `microsoft/windowsservercore`, so I think this should be used. See discussion in https://github.com/docker/docker/pull/26722 that there is more to do than just changing the `FROM` line to fix it in Docker CI.

**Steps to reproduce the issue:**
1. Boot a Windows Server 2016 TP5 machine
2. `git clone https://github.com/docker/docker`
3. `cd docker`
4. `docker build -t dockercompile -f Dockerfile.windows .`

**Describe the results you received:**

```
docker build -t dockercompile -f Dockerfile.windows .
Sending build context to Docker daemon 152.8 MB
Step 1 : FROM windowsservercore
Pulling repository docker.io/library/windowsservercore
Error: image library/windowsservercore:latest not found
```

**Describe the results you expected:**

It should build the Docker image to compile dockerd.exe and the other binaries.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1061.amd64fre.rs1_release_svc.160907-0755)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: 6VUJ:GQVY:KLTY:NJRI:UY53:TJQY:KXB4:SRM5:FBWO:OOSH:4ZDM:FACI
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: stefanscherer
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows Server 2016 TP5 running in VMware Fusion Pro 8.5

A workaround exists to build it. Just create a tag with

```
docker tag microsoft/windowsservercore:latest windowsservercore:latest
```

**Comment by thaJeztah** [comment]
Looks like this was addressed in https://github.com/docker/docker/pull/27616, so i'll close this 👍
