### ISSUE TITLE
Host multiple contaniers using same host:port. 

### ISSUE THREAD

**Issue by dhiraj-hadkar** [docker/docker#26735]
Description
Failure to loadbalance when multiple container using same external port are running on same host.

Steps/overview of issue:

We have swarm consisting of 1 manager/leader and 2 worker nodes.

Swarm status is :

```
[root@manager ~]# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
1zhq6q0vwn5qf283z5snxyjzr    worker1   Down    Active
3wod0p18btb30qxaqrsncmijz *  manager   Ready   Active        Leader
8xeil7dt3cxgi8jeu5lvwg13r    worker2   Down    Active
```

We have a service httpmyapp running on port 9002, i scaled my service to 2 which gives me 2 containers on manager:

I see the VIP, however the request only hits container 1.
Is there any config to enforce active active load balancing when the containers are running on same host.

[root@manager ~]# docker info
Containers: 74
 Running: 1
 Paused: 0
 Stopped: 73
Images: 42
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-251:1-369099008-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 10.61 GB
 Data Space Total: 107.4 GB
 Data Space Available: 38.08 GB
 Metadata Space Used: 14.9 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: active
 NodeID: 3wod0p18btb30qxaqrsncmijz
 Is Manager: true
 ClusterID: 4d9ax6f3xpodnjkngtl3w2p0s
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.100.xxx
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.1.12-37.6.3.el7uek.x86_64
Operating System: Oracle Linux Server 7.2
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.583 GiB
Name: manager
ID: H6QT:BUG5:FLFV:NRZI:KGNQ:ZVL6:DUGQ:TERC:HUS6:ZV44:QMAK:T7CD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dhirajh12
Registry: https://index.docker.io/v1/
Insecure Registries:
 172.16.100.xxx:5000
 127.0.0.0/8
 
 
 
 
 [root@manager ~]# docker version
 Client:
  Version:      1.12.1
  API version:  1.24
  Go version:   go1.6.3
  Git commit:   23cf638
  Built:
  OS/Arch:      linux/amd64
 
 Server:
  Version:      1.12.1
  API version:  1.24
  Go version:   go1.6.3
  Git commit:   23cf638
  Built:
  OS/Arch:      linux/amd64
 [root@manager ~]#

**Comment by thaJeztah** [comment]
Based on your output above, it looks like both worker nodes are `Down`, which can indicate a networking issue, and can potentially affect load balancing as well. Do your daemon logs show anything useful?

How is your swarm set up? Are you running on physical machines? Cloud? Are all machines on the same network, and are the required ports open for communicating between them ? (https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-ports-between-the-hosts)

**Comment by dongluochen** [comment]
> I see the VIP, however the request only hits container 1.

@dhiraj-hadkar From your `docker info` output there is only 1 container running. If your service was scaled to 2, one might have not been created properly. Docker swarm mode implements round robin strategy. If there are 2 active backends, both should be reachable on the published port. 

```
[root@manager ~]# docker info
Containers: 74
Running: 1
Paused: 0
Stopped: 73
```

**Comment by mostolog** [comment]
Similar scenario (LB nginx) is working for me. Shall we close this?

**Comment by dongluochen** [comment]
@dhiraj-hadkar Do you still have problem with load balancer?

**Comment by thaJeztah** [comment]
Closing as this is probably resolved, but @dhiraj-hadkar let us know if you still run into this
