### ISSUE TITLE
Flaky test: DockerSuite.TestAttachClosedOnContainerStop

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#26742]
Saw it on experimental CI:
```
12:53:56 FAIL: docker_cli_attach_unix_test.go:18: DockerSuite.TestAttachClosedOnContainerStop
12:53:56 
12:53:56 docker_cli_attach_unix_test.go:51:
12:53:56     c.Assert(err, check.IsNil)
12:53:56 ... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4205ca0a0), Stderr:[]uint8(nil)} ("exit status 1")
```

**Comment by anusha-ragunathan** [comment]
Seeing this test failure on Docker master rhel72/overlay frequently.

https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel72%20&&%20overlay/6901/consoleText
https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel72%20&&%20overlay/6894/consoleText
https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel72%20&&%20overlay/6887/consoleText

**Comment by coolljt0725** [comment]
Maybe we can print `cmd.Stderr` when `err` is not nil and see if there is some error message than can help :)

**Comment by tonistiigi** [comment]
dupe #26573
