### ISSUE TITLE
where is the github project for UCP?  Want to fix an error in the documentation...

### ISSUE THREAD

**Issue by ezeeetm** [docker/docker#26757]
Searched all over for a project page for UCP, failed.

per docs here:  https://docs.docker.com/ucp/reference/install/

`--host-address	Specify the visible IP/hostname for this node.`

however, passing an actual hostname results in the error below.  Hostnames cannot be used.

`FATA[0046] Unsupported host address (ucp.mydomain.com). Please specify an IPv4 address using the '--host-address' flag, and pass the hostname using the '--san' flag.`

I'd love to do a PR to fix this...but can't find UCP project (or the git repo for the docs) anywhere.

**Comment by thaJeztah** [comment]
Thanks for reporting @ezeeetm. UCP is a closed source project, and the docs are also in a private repository. I'll make sure to forward this to the docs team for UCP so that they can fix

**Comment by vsaraswat** [comment]
@ezeeetm that said, please feel free to report any errors on the UCP forums: https://forums.docker.com/c/docker-data-center/ucp

**Comment by joaofnfernandes** [comment]
I've created an issue so that we can track this. Thanks for reporting!

**Comment by thaJeztah** [comment]
Thanks! Let me close the issue here
