### ISSUE TITLE
Enable fluentd driver for windows

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#26754]
ping @jhowardmsft @tagomoris @darrenstahlmsft

**Comment by tagomoris** [comment]
Are there any problems? (Sorry, I didn't try it because I don't have an environment)

**Comment by LK4D4** [comment]
@tagomoris I don't see any. Pinged you just for the case if you definitely know that it won't work :)

**Comment by jhowardmsft** [comment]
#28189
