### ISSUE TITLE
Docker is not able to stop windows container forcefully

### ISSUE THREAD

**Issue by rohitjaini** [docker/docker#26755]
Attaching docker stack for reference.

**Comment by icecrime** [comment]
@rohitjaini I'm not sure if you pressed the button too fast, but we're going to need more information :-(

**Comment by jhowardmsft** [comment]
@rohitjaini - can you file an internal bug and I'll follow up. From the stack trace you emailed, it looks like an RS2 platform bug losing a notification from the short time I did spend looking at it, rather than docker itself. Thanks. We can reopen this issue if the culprit is docker.
