### ISSUE TITLE
backwards incompatible api change: container.Box

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#26758]
The following change that was merged yesterday broke some of our tests:

https://github.com/docker/docker/commit/53774423ff0db50cb0934e7b1e5ce507363e8147#diff-5251fbdfab3c1500c0c76ec0d8adf746R78

It's a backwards incompatible API change and prevents older docker clients from running containers on newer daemons. I think it should be reverted unless a compatibility layer is added for older engines.

**Comment by runcom** [comment]
There's already a PR which fixes this #26751
