### ISSUE TITLE
Move Pluginv2 out of experimental

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#26760]
Pluginv2 is currently available on experimental daemon builds only. Once the intended feature set is complete and correct, move it out of experimental into stable. This is slated for 1.13.

**Comment by bacaldwell** [comment]
Are there any reference (out of process) graphdrivers that use this pluginv2 API? I'm working on a graph driver plug-in that uses the old API: https://github.com/bacaldwell/lustre-graph-driver

**Comment by anusha-ragunathan** [comment]
@bacaldwell : There are no reference graphdrivers yet. FYI, the graphdriver plugin API (along with other subsystem plugin API) remains unchanged. What has changed is the way the plugin gets built, shipped and run.

**Comment by nishanttotla** [comment]
@anusha-ragunathan are there any updates on the timeline for this?

**Comment by anusha-ragunathan** [comment]
It'll follow 1.13 milestone, which doesnt have concrete dates yet.
