### ISSUE TITLE
bad error message when wrong permissions

### ISSUE THREAD

**Issue by mdg** [docker/docker#26761]
**Description**

The error message when running with insufficient permissions is misleading. It says it cannot connect to the Docker daemon, but then if I run it with root, it connects fine. While this error message is true, a check for file permissions could give a much more helpful error message.
```
mdg@mgraham:~$ docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
```

**Steps to reproduce the issue:**
1. Restrict permissions on /var/run/docker.sock
2. Run `sudo docker info`, see expected results
3. Run `docker info`, see the message `Cannot connect to the Docker daemon. Is the docker daemon running on this host?`

**Describe the results you received:**

I got an error message suggesting that the docker daemon is not running on this host, even though it is.

**Describe the results you expected:**

I get a message telling me that I don't have the necessary permissions.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
mdg@mgraham:~$ sudo docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
mdg@mgraham:~$ sudo docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.4.0-28-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.227 GiB
Name: mgraham
ID: GZYC:P7HQ:ZA7T:SOCK:3J26:S3JY:N4I3:I7BB:VJ7E:MXMM:YZ7X:EZA3
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Lenovo laptop with Ubuntu 16.04, using default Ubuntu install.

**Comment by cpuguy83** [comment]
We have a few special cases for not being able to connect to the socket. Could possibly add one for `EPERM` easily enough.

**Comment by srodman7689** [comment]
@thaJeztah is #26773 related to this issue? Should this issue be address through #26773 or should it be ok for me to just work on this issue specifically?

**Comment by thaJeztah** [comment]
@srodman7689 feel free to work on this issue; I was planning to work on this, an while looking at the code, I found the issues mentioned in https://github.com/docker/docker/issues/26773, so got distracted by those.

We _will_ have to improve the error handling, and fix the bug there, but I don't think adding a friendlier error message will make that much more complicated than it already is :smile:

**Comment by srodman7689** [comment]
@thaJeztah I can leave this one alone if you want to work on it. I don't mind finding another issue.

**Comment by thaJeztah** [comment]
No, please go ahead, I've got enough things to do, so please have a look at it!

**Comment by srodman7689** [comment]
@thaJeztah Will do. Looking at it now.

**Comment by srodman7689** [comment]
#dibs

**Comment by mdg** [comment]
Thanks, @srodman7689 ! As a newbie, this was super-confusing and from my googling for a solution, it appears very common. This fix will make a much better experience for those of us hitting it on our way through the introductory documentation.
