### ISSUE TITLE
Incorrect handling of "Connection" errors when checking exit code

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#26773]
While having a quick look at changes required for https://github.com/docker/docker/issues/26761, I found a bug in the way we handle "connection" errors to separate them from container exit codes.

Writing it down here, so that it doesn't get lost

Basically, [`client.ErrConnectionFailed`](https://github.com/docker/docker/blob/3ea762b9f6ba256cf51bd2c35988f0c48bccf0b0/client/errors.go#L9%29) It looks like ErrConnectionFailed was replaced by `ErrorConnectionFailed()` in https://github.com/docker/engine-api/pull/302/commits/8efb4f189d9fbda674e1df2fecd0106f322b7cd1 (vendored in https://github.com/docker/docker/commit/63a19edcb18b1bc650cc1d6eed78c2c3b376be62). 

However, the error is still used in [`getExecExitCode()`](https://github.com/docker/docker/blob/e345d67c4e2862d497ec92640fd00bf04e6b696e/cli/command/container/exec.go#L157-L168)
and [`utils.getExitCode()`](https://github.com/docker/docker/blob/c2decbe5ee9bd7677699228257db6bcd12d13b78/cli/command/container/utils.go#L80-L92)

Given that `sendClientRequest()` now returns many more types of connection errors (see [client/request.go#L117-L141](https://github.com/docker/docker/blob/7a86930c7452e19ee72557bb8264e81378ccfbb5/client/request.go#L117-L141)), we probably need to have either a utility function (similar to [`IsErrNotFound()`](https://github.com/docker/docker/blob/3ea762b9f6ba256cf51bd2c35988f0c48bccf0b0/client/errors.go#L21-L26)) or smarter error handling

Note that this issue is not present in Docker 1.12, only in master (1.13-dev)

ping @vdemeester this is what we were discussing. Also @duglin (who implemented the `getExecExitCode` originally), and @stevvooe, because I know you love discussions about error handling :smile:

Adding to the 1.13 milestone, because this is a regression

**Comment by runcom** [comment]
related to https://github.com/docker/docker/pull/26436#issuecomment-248564436?

**Comment by stevvooe** [comment]
@thaJeztah The chief issue is that we are relying on error codes deep in package code to set UI messages.

The solution here is going to be careful adoption of [`pkg/errors`](https://github.com/pkg/errors), use of `errors.Cause` and annotation of error conditions we want to differentiate.

**Comment by thaJeztah** [comment]
Fixed by https://github.com/docker/docker/issues/28659
