### ISSUE TITLE
dm.datadev and dm.metadatadev missing from bash completion 

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#26771]
see https://github.com/docker/docker/blob/master/man/dockerd.8.md#dmdatadev and https://github.com/docker/docker/blob/master/man/dockerd.8.md#dmmetadatadev

This two option is missing from cli completion.

ping @albers

**Comment by thaJeztah** [comment]
Possibly, this is on purpose, because:

> It is better to use `dm.thinpooldev` - see the documentation for it above for discussion of the advantages.

**Comment by albers** [comment]
The docs explicitly mark these options as deprecated.
I always remove / do not add deprecated options so that people are not encouraged to use them.

@coolljt0725 do you really need these options or are you just concerned about completeness?

**Comment by coolljt0725** [comment]
@thaJeztah  @albers  I didn't notice these options is already marked as deprecated.  thanks for the clarification, `I always remove / do not add deprecated options so that people are not encouraged to use them` make sense.

**Comment by thaJeztah** [comment]
Thanks!
