### ISSUE TITLE
http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by runcom** [docker/docker#26781]
**Description**

docker client totally broken on master. Hope someone can reproduce.

**Steps to reproduce the issue:**
1. build docker from master
2. `docker pull busybox` || `docker run -ti busybox sh` (both will fail)
3.

**Describe the results you received:**
```
$ docker pull busybox
Using default tag: latest
error during connect: Post https://%2Fvar%2Frun%2Fdocker.sock/v1.25/images/create?fromImage=busybox&tag=latest: http: server gave HTTP response to HTTPS client
```

**Describe the results you expected:**

pull goes through

**Additional information you deem important (e.g. issue happens only occasionally):**

Debugged a bit and:

* I'm running with the default docker cmdline, no fancy stuff

here it is:
```
$ cat /proc/`pidof docker`/cmdline
dockerd--exec-optnative.cgroupdriver=systemd--log-driver=journald-D-soverlay2--insecure-registry172.30.0.0/16
```

* the client connects by default on `/var/run/docker.sock`

This happens only on commands that do more than one API call - e.g. this is NOT failing with docker info or docker version ofc.
Instead commands like pull and run (that does first docker info, then docker pull for the pull case and create and attach for docker run) aren't affected by this.
If I debug the `http.Transport` in the client after https://github.com/docker/docker/pull/26436 which is the PR that broke this I get this transport as the first one used to make an API call:
```
&{{0 0} false map[] map[] {0 0} map[] {{0 0} 0 0 0 0} map[] <nil> 0x6c4e10 <nil> <nil> 0 false true 0 0 0 map[] {{0 0} 0} <nil>} 
```
The second request instead (/images/create or /containers/id/attach) I got the following transport:
```
&{{0 0} false map[{ http /var/run/docker.sock:80}:[0xc8203c2000]] map[] {0 0} map[] {{0 0} 0 0 0 0} map[https:{0xc82021ef50}] <nil> 0x6c4e10 <nil> 0xc82030cb40 0 false true 0 0 0 map[h2:0x670220] {{0 0} 1} 0xc82021ef50}
```
This is weird and seems the transport is modified and re-used.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   fd1037b
 Built:        Wed Sep 21 17:23:53 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.6.3
 Git commit:   fd1037b
 Built:        Wed Sep 21 17:23:53 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 38
 Running: 0
 Paused: 0
 Stopped: 38
Images: 43
Server Version: 1.13.0-dev
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.3-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.44 GiB
Name: localhost.localdomain
ID: 62I5:E7N5:VHP3:HEWA:7I2L:JLUR:JQV7:SDPV:GYHS:LFYI:QBIH:KRRV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 24
 System Time: 2016-09-21T17:34:32.647052744+02:00
 EventsListeners: 0
Username: runcom
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 172.30.0.0/16
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by runcom** [comment]
@LK4D4 @stevvooe @aaronlehmann @tonistiigi @vdemeester @thaJeztah PTAL

**Comment by justincormack** [comment]
Somehow you are running an https connection over a unix socket, which should be http...

**Comment by runcom** [comment]
> Somehow you are running an https connection over a unix socket, which should be http...

yeah, figured that - and this PR is breaking that https://github.com/docker/docker/issues/26436

**Comment by thaJeztah** [comment]
Ah, so if the same connection is reused (as you commented https://github.com/docker/docker/pull/26436#issuecomment-248649163), and that connection is setup for https, that's probably the issue?

**Comment by runcom** [comment]
> Ah, so if the same connection is reused (as you commented #26436 (comment)), and that connection is setup for https, that's probably the issue?

I don't think so, I think the issue is that the transport if badly configured to do an https connection _AFTER_ and http one.

Example:
```sh
$ docker pull busybox

# 1) first thing in pull code is a call to /info to get the serverAddress (docker.io)
#     this call is successful and it's doing an http call over the unix socket
# 2) second thing in pull code is a call to /images/create to pull the image
#     this call shows the error in this issue because the client does an https request over the unix socket
```

**Comment by stevvooe** [comment]
@runcom No good deed goes unpunished. Unfortunately, the method used to detect TLS for hijacking is _extremely_ broken. #26436 did its best to work around this and confine it. Not to mention the morass that is `sockets.ConfigureTransport`.

I don't think #26794 will fix this fully, as it is probably the caller interacting with https://github.com/docker/docker/blob/master/client/client.go#L93. Basically, we don't call `sockets.ConfigureTransport` unless that method creates the transport.

Let me see if I can get a patch.

**Comment by stevvooe** [comment]
Reproduced with client/README.md example:

```
$ DOCKER_CERT_PATH=/tmp/ go run g.go
panic: error during connect: Get https://%2Fvar%2Frun%2Fdocker.sock/v1.23/containers/json?all=1&limit=0: dial tcp: lookup /var/run/docker.sock: no such host

goroutine 1 [running]:
panic(0x27f320, 0xc4202a2240)
       	/usr/local/go/src/runtime/panic.go:500 +0x1a1
main.main()
       	/tmp/g.go:22 +0x427
exit status 2
```

The problem is that unix socket + `DOCKER_CERT_PATH` doesn't call `sockets.ConfigureTransport` because `NewClient` assumes the transport is all good to go.

**Comment by aaronlehmann** [comment]
Reopening as #26804 does not fix this yet. A followup will solve this issue.

**Comment by tpbowden** [comment]
I managed to reproduce this issue using Golang 1.6, but when I upgraded to 1.7 it was fixed. Is this related to something within the standard library?

**Comment by stevvooe** [comment]
@tpbowden Yes, as far as we can tell. We worked around it in #27306.

We failed to ascertain the root cause. If someone was willing to investigate further, it would be helpful, as the hack I've put in is not my proudest moment.
