### ISSUE TITLE
Docs not clear of intended behaviour for make shell command

### ISSUE THREAD

**Issue by terencechow** [docker/docker#26800]
Hi,

I wanted to start contributing so I went through the contributing guide. It is a bit out of date so I'm not entirely sure if the docs are out of date or if I'm doing something wrong.

Specifically the docs say the make shell command will mount my local repo to the docker container. 

This makes it sound like any changes I make on my local repo will be reflected in my docker container. Is this true? Because I am not seeing that. Rather I have to exit my container and run make shell again to have the updates reflected in that container.

So my question is, how do I get it so that changes on my local repo will be reflected in my container? I tried running `docker build   -t "docker-dev:dry-run-test" -f "Dockerfile" .` in my local repo with no luck.

Something that I also noticed was that when I ran `docker daemon -D&` the docs guide has the last line of output as:

`DEBU[0003] containerd connection state change: READY` 

whereas my last line is:

`INFO[0001] API listen on /var/run/docker.sock`

I wonder if that might be the issue? I don't see any references to containerd in my logs. 

Anyways, if you can give me guidance on how to fix this issue perhaps I can update the docs to make it more clear :)

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

Not sure of intended behaviour of make shell. Should local changes in my repo directly change files in my container?

**Steps to reproduce the issue:**
1. docker-machine start (if it isn't already started)
2. make shell (in the forked repo)
3. `hack/make.sh` (in the container)
4. `cp bundles/1.13.0-dev/binary-client/docker* /usr/bin/` (in the container)
5. `cp bundles/1.13.0-dev/binary-daemon/docker* /usr/bin/` (in the container)
6. `docker daemon -D&` (in the container)
7.  make a change to VERSION (in the local repo)
8. echo "$(cat VERSION)" (in the container)

**Describe the results you received:**

I get the version number 1.13.0-dev

**Describe the results you expected:**

I expect VERSION to spit out whatever change I made in that file. 

**Additional information you deem important (e.g. issue happens only occasionally):**

from the docker daemon command my last log is 

`INFO[0001] API listen on /var/run/docker.sock` 

but the docs last log is: 

`DEBU[0003] containerd connection state change: READY` 

**Output of `docker version`:**

in container
```
DEBU[1307] Calling GET /v1.25/version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   2a3205d-unsupported
 Built:        Wed Sep 21 23:23:21 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   2a3205d-unsupported
 Built:        Wed Sep 21 23:23:21 2016
 OS/Arch:      linux/amd64
```

in local
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

in container:
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: 6650803b2918
ID: UUWK:TNUC:LZLE:IOYA:3L6F:NXRA:HAUF:PXYK:C445:LGZZ:EXBL:675I
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 12
 Goroutines: 21
 System Time: 2016-09-21T23:49:44.597560893Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

in local
```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 64
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: TVZW:J7DK:YVI2:YAIG:MVS3:4F7G:XD3S:A7US:YVF7:UNBP:QWO5:A23H
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 37
 System Time: 2016-09-21T23:49:23.127092333Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by delcypher** [comment]
@terencechow I hit this recently. I filled a PR to fix the docs but it hasn't been merged yet.

https://github.com/docker/opensource/pull/90
https://github.com/docker/opensource/pull/89

**Comment by thaJeztah** [comment]
Thanks @delcypher, I just reviewed those PR's and merged them (sorry I missed them)

**Comment by delcypher** [comment]
@thaJeztah No problem. Thanks for merging.

**Comment by thaJeztah** [comment]
FWIW, my usual steps are;

I combine "binary" and "shell" here, not sure that works on Linux, need to check;

```bash
make BIND_DIR=. binary shell
```

Inside the container;
```bash
make install
```

(`make install` was added not too long ago, and copies the binaries to `/usr/bin` inside the container)

Run the daemon in debug mode (note that I usually don't run it daemonized (`&`)  - see next step
```bash
dockerd --debug
```
In a separate shell, open another shell in the container;

```bash
docker exec -it <container-id> bash
```

As I'm lazy, and don't want to search for the container-id, I use;

```bash
docker exec -it $(docker ps -q -n1) sh
```

(which assumes that the last container that was created, is my development container)


Note that there's also `make help`, which shows usage for the makefile :tada:

**Comment by terencechow** [comment]
Thanks! I will close this now.

**Comment by terencechow** [comment]
@thaJeztah @delcypher sorry for asking a question after closing, but this is related to the suggestions given.

I see now that my container is mounted to my local repo with changes in my local repo showing instantly in the files in the container. (I see this by running `echo $(cat file)` in the container and see changes made immediately)

However I don't actually see that change with docker. 

In the container when I run `docker attach --help` I don't see the changes that I made in the `attach.go` file.

Intuitively I believe this is because I haven't run make install. So with dockerd running in the background, I run `make install` in my container and get this error

```
Installing dockerd to /usr/local/bin/
cp: cannot create regular file '/usr/local/bin/dockerd': Text file busy
Makefile:106: recipe for target 'install' failed
```

Am I supposed to close `dockerd` before running `make install` for future builds? If so then everything is acting as normal. If not, I'll open a new issue with the error message I got. (It makes sense to me that I would need to close daemond before rerunning it with a new binary, but I was somewhat under the impression that changes would be updated without restarting). Please let me know if you can! Thanks!

**Comment by terencechow** [comment]
Answering my own question for future devs... Looks like the Text file busy error is not completely relevant. I can update the docker build in the container by running `make KEEPBUNDLE=1 binary` which will build the binary followed by `make install` which will move the copy of the binary over to the right folder.
