### ISSUE TITLE
Add service name to journald logging

### ISSUE THREAD

**Issue by docwhat** [docker/docker#26808]
> As a `docker service` user using `journald` logging
> I want to be able to look at the logs for a single service
> to be able to monitor and troubleshoot that service

If I'm using the `journald` logging it would be nice to be able to do `journalctl -xe -u docker.service SERVICE_NAME=myservice` to see what the service logging.

**Comment by npcode** [comment]
My workaround is using a label as follows:

    docker daemon --log-driver=journald --log-opt labels=com.docker.swarm.service.name

Then you can fetch logs for a specific service:

    journalctl COM_DOCKER_SWARM_SERVICE_NAME=myservice

**Comment by docwhat** [comment]
I didn't see that (or any) `log-opt` in the docs. Neat!

**Comment by thaJeztah** [comment]
There's documentation here; https://docs.docker.com/engine/admin/logging/overview/, but it may need some more examples, and a rewrite / restructure in general

**Comment by aluzzardi** [comment]
@docwhat @npcode I **think** we actually do inject a log label with the service name.

@stevvooe Can you confirm and provide guidance?

**Comment by stevvooe** [comment]
@aluzzardi We provide the `com.docker.swarm.service.name` label but it is up to the user to configure which information is mapped into the logging system. Note that you have configure this per service, as well, via `--log-opt`. We have support to configure this cluster wide built into swarmkit but haven't exposed in the cli.

As far as doing this by default, I am not sure. There are about 5 or 6 relevant labels that could be mapped but logging systems typically have a cost to this, so I am not sure what should be done by default. Looks like we currently have `CONTAINER_ID`, `CONTAINER_ID_FULL`, `CONTAINER_NAME`, and `CONTAINER_TAG` (whatever that is).

Are there any systemd experts that can comment on the cost of this? I would propose the following to be automatically mapped:

`SERVICE_ID`
`SERVICE_NAME`
`TASK_ID`
`TASK_NAME`
`TASK_SLOT`
`NODE_ID`
`NODE_NAME` (maybe)

**Comment by cpuguy83** [comment]
ping @nalind

**Comment by aluzzardi** [comment]
@stevvooe Should we do this `--log-opt labels=com.docker.swarm.service.name` thing by default in the agent?

**Comment by stevvooe** [comment]
@aluzzardi I think it would be better to map this manually, per the suggestion above.

**Comment by nalind** [comment]
In terms of estimating size costs, if I'm reading the [doc](https://www.freedesktop.org/wiki/Software/systemd/journal-files/) right, adding seven new fields to each entry would entail adding one Field object and a new item in the Field Hash Table for each new field name, in each journal file, which would be a more or less constant cost on a per-journal-file basis on the order of dozens of bytes.  Each unique field+value pair would show up as a new Data object in each journal file, each one in the low dozens of bytes in size.  Since I expect values to be heavily repeated, the number of Data objects added would be relatively low.  The cost for each Entry object, each of which corresponds to a chunk (usually a line) of output that we send to the journal, would be 16 additional bytes for each Data object that we're adding a reference to, so on average I'd estimate that 112 bytes plus some fraction of the total size of the new Field and Data objects.

The `CONTAINER_TAG` field is used to log the computed value of the "tag" log option, which defaults to `{{.ID}}` since #22911.

**Comment by aluzzardi** [comment]
@stevvooe Are you referring to @npcode's approach?

> docker daemon --log-driver=journald --log-opt labels=com.docker.swarm.service.name
> journalctl COM_DOCKER_SWARM_SERVICE_NAME=myservice

If that's the case, maybe all we need to do is document this.

/cc @mstanleyjones

**Comment by stevvooe** [comment]
@nalind Any way to reduce per entry use? For example, it would be nice to have the container id be linked to a lookup table for the other values, which may be lost to docker once emitted as a log message. Also, is any compression applied to the format?

Convenience is usually expensive, so we have to make a trade off between the users who care about log size against the ones that want to conveniently query their logs.

@aluzzardi Yes. Documentation might be the right trade off.

**Comment by nalind** [comment]
@stevvooe Individual Data objects (used to represent unique field+value pairs) can be compressed, but my expectation is that the majority of the increase in the journal's size would be in Entry objects (which refer to Data objects), which are not compressed.

An Entry object is larger if we add a reference to a Data item, whether that Data item shows the field having a non-zero-length value or not.  If we only add the variable when its value is not empty, we avoid that cost for people who aren't using those fields, with the main tradeoff being that you can't then easily search for journal entries where those fields are set to the empty value.  I guess doing that would have the effect of setting those fields unconditionally for people using Swarm functionality, and never setting them for people who don't.

**Comment by mstanleyjones** [comment]
Created https://github.com/docker/docker.github.io/issues/254 to update that content and address some of the suggestions here.

**Comment by aluzzardi** [comment]
Closing this down - we'll document `journald` integration.

Everyone happy with the outcome? /cc @docwhat @npcode @nalind

**Comment by vodolaz095** [comment]
> My workaround is using a label:
> `docker daemon --log-driver=journald --log-opt labels=com.docker.swarm.service.name`
> Then you can fetch logs for a specific service:
> `journalctl COM_DOCKER_SWARM_SERVICE_NAME=myservice`


if anybody curious how to configure it in better way:

```
[root@ivory vodolaz095]# cat /etc/docker/daemon.json 
{
    "log-driver": "journald",
    "log-opts": {
      "labels":"com.docker.swarm.service.name"
    }
}
```

**Comment by cjsfj** [comment]
@vodolaz095 Does this send all of your container logs to journald? or just focus on the daemon logs only?

**Comment by vodolaz095** [comment]
yes
