### ISSUE TITLE
Windows: Data race in restarting

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#26801]
Found running CI locally using master at c0699cd4a43ccc3b1e3624379e46e9ed94f7428c (morning of 9/21/16). @darrenstahlmsft @swernli FYI

There were several triggers - all were a combination of restart with some other condition. The restart is being called from https://github.com/docker/docker/blob/master/libcontainerd/container_windows.go#L272 (in the current codebase, L282 in the commit above).

The problem is fairly complex to explain.

During a start call from the daemon into libcontainerd (https://github.com/docker/docker/blob/master/daemon/start.go#L153), the container lock is already held at https://github.com/docker/docker/blob/master/daemon/start.go#L94.

libcontainerd calls back into the monitor with a `StateStart` from https://github.com/docker/docker/blob/master/libcontainerd/container_windows.go#L158. 

In the monitor, there is an explicit comment that for `StateStart` and `StateRestore`, the container lock is already held, so doesn't need to take it. This is true from the above set of events during a `normal` container start. Here's the monitor code in question: https://github.com/docker/docker/blob/master/daemon/monitor.go#L89-L99

The problem though is that a start on account of a restart is initiated from inside libcontainerd https://github.com/docker/docker/blob/master/libcontainerd/container_windows.go#L272, through a call to Create(), but in this case the lock in the monitor is NOT held.

I have a fix in the works and know how to solve - just opening the issue to keep track of it.

Some of the data races found, all a similar pattern:

![image](https://cloud.githubusercontent.com/assets/10522484/18732953/e0078488-801b-11e6-91df-d66cc5c805a8.png)

![image](https://cloud.githubusercontent.com/assets/10522484/18732957/e8b58f3a-801b-11e6-86c7-26f3dc7b10ef.png)

![image](https://cloud.githubusercontent.com/assets/10522484/18732959/ec9de764-801b-11e6-8402-4410d1b68080.png)

**Comment by tonistiigi** [comment]
fixed by #27169
