### ISSUE TITLE
Bad reference in docker volumes tutorial

### ISSUE THREAD

**Issue by guestisp** [docker/docker#26818]
In docker volumes tutorial there is still wrote 
```
Because of limitations in the mount function, moving subdirectories within the host’s source directory can give access from the container to the host’s file system. This requires a malicious user with access to host and its mounted directory.
```

This was fixed last year: http://www.spinics.net/lists/linux-containers/msg31063.html

**Comment by thaJeztah** [comment]
Thanks! Do you know if this has been back ported to older kernel versions?

**Comment by guestisp** [comment]
Directly from the mailinglist:

It was fixed in kernel 4.3 and backported to all longterm stable kernels

**Comment by thaJeztah** [comment]
Awesome! Would you like to contribute, and open a pull request to make the changes to that part of the docs? The Markdown file for generating that page in the documentation can be found in this repository; https://github.com/docker/docker/blob/368a27a8d80337918d465c8c98100a4e22d9ef1a/docs/tutorials/dockervolumes.md#L162

**Comment by milindchawre** [comment]
@thaJeztah Has this been fixed; can't see docs/tutorials/dockervolumes.md file in master branch.

**Comment by milindchawre** [comment]
@thaJeztah Can you take look : https://github.com/docker/docker.github.io/pull/232

**Comment by thaJeztah** [comment]
Looks like you found the new location; great! And sorry about that :smile:
