### ISSUE TITLE
apparmor: no apparmor profile when installing from 1.13 deb

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#26823]
**Description**

On a fresh x86_64 14.04 docker 1.13.0 install from upstream 'make deb', any sort of container creation throws oci runtime error: apparmor failed to apply profile: no such file or directory. This seems to be because there is no docker-default apparmor profile on the system at all. 

Note: tested a 1.12.1 deb on the same machine and it worked as expected.

**Steps to reproduce the issue:**
1. 'make deb'
2. transfer deb to a machine without docker (or without docker ever installed)
3. dpkg -i docker-engine-1.13.0.deb
4. apt-get install -yf
5. try and build a dockerfile (I pulled down source and tried building the main dockerfile)

**Describe the results you received:**
```sh
$ sudo docker build -t docker .

Sending build context to Docker daemon 150.9 MB
Step 1/51 : FROM debian:jessie
jessie: Pulling from library/debian
2f5fbf611374: Pull complete 
Digest: sha256:5ef46429b495d4dd137f6909719b8dfe3570eda3879a6e6e8be08216a047596d
Status: Downloaded newer image for debian:jessie
 ---> a24c3183e910
Step 2/51 : RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61 	|| apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys E871F18B51E0147C77796AC81196BA81F6B0FC61
 ---> Running in c38a8759f53c
oci runtime error: apparmor failed to apply profile: no such file or directory
```
**Describe the results you expected:**
dockerfile builds as normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   c0699cd-unsupported
 Built:        Wed Sep 21 15:19:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7
 Git commit:   c0699cd-unsupported
 Built:        Wed Sep 21 15:19:17 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.68 GiB
Name: tophj-VirtualBox
ID: 6RXI:QZDB:24UI:Q4JM:EK6B:ELRY:4NE7:MGXR:HFIF:RAWA:PPKB:TTDC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtualbox, but same result on a power vm as well.

**Comment by justincormack** [comment]
Can you see which directory it is missing?

**Comment by justincormack** [comment]
This is the only recent change that I can think of https://github.com/docker/docker/pull/26518

**Comment by tophj-ibm** [comment]
probably related as it's missing /etc/apparmor.d/docker (and cache).

**Comment by justincormack** [comment]
cc @cyphar

**Comment by tophj-ibm** [comment]
Definitely related to that pr. With the change, the apparmor profile is never actually loaded into the kernel, as I'm not seeing docker-default in /sys/kernel/security/apparmor/profile after I install form a recent deb, but it is there with the 1.12 one.

**Comment by cyphar** [comment]
@tophj-ibm The file isn't meant to exist in `/etc/apparmor.d/docker` or in the cache, because that PR was fixing an issue where Docker would fail to start when `/etc` was readonly (because the Docker daemon was creating that file). On the other hand, my guess is that there's something wrong with your `/tmp` that is causing this issue. Is `$TMPDIR` set to something odd on your machine?

**Comment by tophj-ibm** [comment]
@cyphar thanks for taking a look at it! I haven't messed with my $TMPDIR and I have normal write access to it, not to mention this happens on more than one machine, so I don't believe that is the case. In addition, if I remove and unload all the docker-default profiles and install 1.12, docker-default is visible as a kernel profile. However, this is not the case with 1.13.

**Comment by tophj-ibm** [comment]
nvm, I see the bug
