### ISSUE TITLE
Docker containers respond to ICMP without using host network

### ISSUE THREAD

**Issue by e2designs** [docker/docker#26838]
**Description**

After creating a new container in interactive mode. The container is responding to ICMP requests for various ip addresses. These responses still occur when the host has no physical or wireless network connections.  

**Steps to reproduce the issue:**
1. Start new container with ubuntu:trusty or centos:latest
2. Run `ping 10.0.0.0` or any other ip address you know the host is unable to reach
3. Verify ICMP responses are received and no traffic (wireshark) is transmitted over the host network connection.
4. alternatively unplug ethernet from the host and disable wireless. 
``` 
docker run -it ubuntu:trusty bash
Unable to find image 'ubuntu:trusty' locally
trusty: Pulling from library/ubuntu
71a21fdea81d: Pull complete 
cf68a3ea6e1d: Pull complete 
31cb2a4d344a: Pull complete 
0341b6fcb0fe: Pull complete 
c8777cc48364: Pull complete 
Digest: sha256:93a14ad7bd339597b91d945b097c5a7b249e33bd680159551ac5c96025da7520
Status: Downloaded newer image for ubuntu:trusty
root@6a65cb779e9d:/# ping 10.0.0.0
PING 10.0.0.0 (10.0.0.0) 56(84) bytes of data.
64 bytes from 10.0.0.0: icmp_seq=1 ttl=37 time=0.221 ms
64 bytes from 10.0.0.0: icmp_seq=2 ttl=37 time=0.224 ms
64 bytes from 10.0.0.0: icmp_seq=3 ttl=37 time=0.221 ms
64 bytes from 10.0.0.0: icmp_seq=4 ttl=37 time=0.222 ms
64 bytes from 10.0.0.0: icmp_seq=5 ttl=37 time=0.216 ms
64 bytes from 10.0.0.0: icmp_seq=6 ttl=37 time=0.207 ms
^C
--- 10.0.0.0 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 4997ms
rtt min/avg/max/mdev = 0.207/0.218/0.224/0.015 ms
root@6a65cb779e9d:/# 
```

**Describe the results you received:**
Ping responses are generated when they should not be. 

**Describe the results you expected:**
`Request timeout for icmp_seq x'

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: VPDM:GDSJ:SMX7:NUUV:JK3Z:DCD2:F6BD:4AK7:O4LX:5TMN:TEO3:OWSM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 41
 System Time: 2016-09-22T22:01:44.185577026Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Mac OS X El Capitan

This has been verified on two different systems.

**Comment by foxx** [comment]
Also confirmed, this is quite surprising behaviour, any update?

**Comment by thaJeztah** [comment]
I think this may be specific to Docker for Mac

@foxx were you running on Docker for Mac as well?

**Comment by foxx** [comment]
@thaJeztah Yup, Docker for Mac

```
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856
```

**Comment by justincormack** [comment]
Yes, it is tracked here https://github.com/docker/for-mac/issues/57

I am going to close this issue as it is already being tracked (and worked on I believe).
