### ISSUE TITLE
`Cannot connect to the Docker daemon` when inside tmux

### ISSUE THREAD

**Issue by timotheecour** [docker/docker#26841]
```
docker run hello-world
Hello from Docker!

tmux
docker run hello-world
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
```

**Comment by cpuguy83** [comment]
There are a couple of things that could be causing this:

1. No permissions to the unix socket that docker is listening on (by default need user root or group "docker")
2. Environment variables can be used to configure the client. If you are firing up a new shell (as you are with tmux) and these environment variables aren't set, the client may not be able to connect.

Ultimately this is not a Docker bug, so I'm going to go ahead and close it.
Re: potential permissions issues issue, there is a PR to improve this message: #26797

**Comment by colakong** [comment]
I've encountered the same issue. It occurs when I add an account to the `docker` group, while still having _at least one_ tmux session still open. Until I closed *all* tmux sessions owned by that user, new ones won't have the new group membership.

**Comment by wangyoucao577** [comment]
Try re-login as with your username/password after attached in tmux session.   

```
tmux
sudo su - <your username>
docker run hello-world
```

It's works for me.

**Comment by holms** [comment]
@wangyoucao577 I have to do it every time to make it work. Even been logged out from user and logged back in. Any ideas why this happens?
