### ISSUE TITLE
Bug in docker/docker/registry

### ISSUE THREAD

**Issue by xuant** [docker/docker#26845]
**Description**
Basically, you cannot import "github.com/docker/docker/registry" from your own program.

I'm trying to interact with my own docker registry using "github.com/docker/docker/registry" from the master branch. I met with the following error:
```
# github.com/docker/docker/registry
goproject/src/github.com/docker/docker/registry/registry.go:31: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
goproject/src/github.com/docker/docker/registry/registry.go:166: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
goproject/src/github.com/docker/docker/registry/service_v1.go:10: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
goproject/src/github.com/docker/docker/registry/service_v2.go:11: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
```

**Steps to reproduce the issue:**
1. Create some go program that import "github.com/docker/docker/registry", for example:
```
% cat test.go                                                                                                       ~
package main

import "fmt"
import "github.com/docker/docker/registry"

func main() {
	id := registry.ImgData{
		ID:       "id",
		Checksum: "checksum",
	}

	fmt.Printf("%v", id)
}
```
2. Run
```
 % go run test.go                                                                                                    ~
# github.com/docker/docker/registry
goproject/src/github.com/docker/docker/registry/registry.go:31: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
goproject/src/github.com/docker/docker/registry/registry.go:166: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
goproject/src/github.com/docker/docker/registry/service_v1.go:10: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
goproject/src/github.com/docker/docker/registry/service_v2.go:11: cannot call non-function tlsconfig.ServerDefault (type tls.Config)
```

**Comment by michelvocks** [comment]
I have no problems with the given example. Maybe an `go get -u github.com/docker/docker/registry` will help.

**Comment by xuant** [comment]
@michelvocks 
`go get -u github.com/docker/docker/registry` works. Thank you.
But I met with another one as below:
```
$ go get -u github.com/docker/docker/distribution
# github.com/docker/docker/distribution
gopath/src/github.com/docker/docker/distribution/push_v2.go:184: cannot use p.config.TrustKey (type "github.com/docker/libtrust".PrivateKey) as type "github.com/docker/distribution/vendor/github.com/docker/libtrust".PrivateKey in argument to schema1.NewConfigManifestBuilder:
	"github.com/docker/libtrust".PrivateKey does not implement "github.com/docker/distribution/vendor/github.com/docker/libtrust".PrivateKey (wrong type for PublicKey method)
		have PublicKey() "github.com/docker/libtrust".PublicKey
		want PublicKey() "github.com/docker/distribution/vendor/github.com/docker/libtrust".PublicKey
```
Could you take a look at this as well? Thanks.

**Comment by michelvocks** [comment]
It seems like you have a old copy of docker source code in your `$GOPATH` which is used for imports in the registry. Can you try to update the whole repo? (`go get -u github.com/docker/docker`)

**Comment by xuant** [comment]
@michelvocks 
That was what I thought as well but I actually started a new vm to test it there was no copy of docker before I did `go get -u github.com/docker/docker/distribution`.

**Comment by xuant** [comment]
@michelvocks 
It turned out to be golang search for `vendor` folder for dependencies first. But sometimes other packages might not have a `vendor` folder thus will go for `GOPATH` or `GOROOT`. This will result in the fact that even though `.go` files might have the same `import github.com/docker/libtrust`, they are actually pointing to different packages (it could be `vendor` folder or it could be `GOPATH` or `GOROOT`). 

My workaround here is for the packages that has the `vendor-GOPATH` conflict, do the following:
```
$ mv vendor/ _novendor/
```

**Comment by thaJeztah** [comment]
Looks like the problem was resolved, so I'll close this issue
