### ISSUE TITLE
Php image volumes to /var/www cause: oci runtime error: no such file or directory

### ISSUE THREAD

**Issue by schovi** [docker/docker#26855]
**Description**

Using docker-compose for running our development on OSX environment cause following error: `oci runtime error: no such file or directory`. 

**Steps to reproduce the issue:**

Error occur even when I run `docker run -v /Users/schovi/work/app:/var/www php:5.6-fpm`

But we use it with docker-compose

1)
This is minimal configuration causing problem
having `docker-compose.yml`

```
test_php:
    image: php:5.6-fpm
    volumes:
        - ANY_VALID_LOCAL_DIRECTORY:/var/www
```

ANY_VALID_LOCAL_DIRECTORY in my case is path to application. But tried lot of other directories with same result.

2) `docker-compose up`

**Describe the results you received:**

This give me error already mentioned `ERROR: for test_app  Cannot start service test_app: oci runtime error: no such file or directory`

**Describe the results you expected:**

It should works :)

**Additional information you deem important (e.g. issue happens only occasionally):**

Problem seems to be in target directory `/var/www`. When i change it to anything else like `/var/blahblah` containers starts as expected.

Weird thing is that for one colleague with osx it does same, for other it works fine and for me it worked for a week and then without any reason starts to throw this error. And for one on windows it works too.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

I had beta channel and tried to switch to normal one. Even tried to totally wipe docker from computer.

**Output of `docker info`:**

```
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 56
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 148
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 2.934 GiB
Name: moby
ID: QI7D:HMPI:L5NT:MLVN:ODUP:F3PZ:2EAT:J6NG:FHBP:WPNW:5BO6:GK6M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 48
 System Time: 2016-09-23T09:11:27.251913824Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: schovi
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Nope

**Comment by mlaventure** [comment]
ping @justincormack

**Comment by freearhey** [comment]
You can add the app name to the path, like this
```
volumes:
 - ANY_VALID_LOCAL_DIRECTORY:/var/www/APP_NAME
```
It helped me.

**Comment by schovi** [comment]
@freearhey As I wrote in Issue, this works fine. But why it worked for me for about a week and for few colleagues it still works (and for some it have never worked). It is something worth resolving to work or not work for all same :)

**Comment by justincormack** [comment]
I get `ERROR: for test_php  Cannot start service test_php: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"chdir to cwd (\\\"/var/www/html\\\") set in config.json failed: no such file or directory\"\n"
ERROR: Encountered errors while bringing up the project.`

ie the image requires that `/var/www/html` exists, and if you add your directory over that and it does not have an `html` subdirectory this will not work.

**Comment by eduardoleal** [comment]
+1

**Comment by TeNNoX** [comment]
I got the same error on Linux (elementary OS 0.4 Loki, Docker version 1.12.1, build 23cf638)

I **fixed it by adding**
`WORKDIR /var/www`
to my Dockerfile.

The actual problem was the workdir [set in php's Dockerfile](https://github.com/docker-library/php/blob/1c56325a69718a3e3cf76179e75d070b7e23da62/5.6/apache/Dockerfile#L155)

**Comment by schovi** [comment]
@TeNNoX awesome!

**Comment by lhridley** [comment]
I'm getting the same error, and adding a WORKDIR to my Dockerfile did not fix it.  It's odd, because it's intermittent.  It works fine on my local environment (OS X El Capitan, Docker 1.13.0 and Docker Compose 1.10.0) and on a test Linux box I have running Debian Jessie with Docker 1.13 and Docker Compose 1.10; however it occurs on a coworker's laptop running Ubuntu 16.04, Docker 1.13.0 and Docker Compose 1.10.0 and on Travis, which uses Ubuntu Trusty as the base build environment, running Docker 1.12.3 and whatever version of Docker Compose that Travis installs by default when you enable Docker as a service on Travis.

**Comment by d2r2net** [comment]
I had the same error using nginx and php images .Turn's out that php was unable to find the files, by default php is looking for files in /var/www/html so  I did fix the issue by using `<path_to_app>:/var/www/html/app` for both nginx and php.

**Comment by thaJeztah** [comment]
Looking at the discussion I'm closing this issue, because I don't think there's a bug at hand here.
