### ISSUE TITLE
[QUESTION] signal passing and cmd / entrypoint as a list

### ISSUE THREAD

**Issue by ketzacoatl** [docker/docker#26864]
In reading https://docs.docker.com/engine/reference/builder/#/entrypoint, I find it a bit confusing to follow and understand with confidence.

Here are a few questions which result:
* Is there any way to pass the list form of `--entrypoint`, so when using `docker run` on the cli, your command will receive `SIGTERM` or other signals?
* If you want to ensure your commands receive those signals, you _must_ use the list form for `--entrypoint` or `ENTRYPOINT`, correct?
* When no `--entrypoint` is specified, what is the behavior of docker's signal passing?
* Does the `--command` parameter (in either the list form or not) affect the behavior of signal passing?

**Comment by cpuguy83** [comment]
It has nothing to do with Docker's signal processing, it' about what is running in the container.
Docker will always pass the signals along, but the container process much handle them.
One big issue with this is C programs (and probably others) will drop default signal handlers when they are run as PID 1.

What this means is if you don't use the json list form, docker will start the container with `/bin/sh -c "<cmd>"`, where `/bin/sh` does not handle signals when it's running as PID 1.

Once enhancement to this is in 1.13 you can setup Docker so it will fire up the container with a minimal init process that will run as PID 1 instead, and will properly handle signals, reap zombies, etc.

**Comment by ketzacoatl** [comment]
Thanks for explaining, I appreciate the details. I think it's really confusing and a surprise to find that the default (non-list form) using `/bin/sh -c` where `sh` drops signals.

Can the list form for `--entrypoint` be specified on the cli with `docker run`?

**Comment by justincormack** [comment]
@ketzacoatl not as far as I know, I was thinking about this the other day, other than in 1.13 you can reset the entrypoint back to the default. As you can just specify the remaining arguments in the command it is not that useful I guess, although it does seem a little inconsistent.

**Comment by ketzacoatl** [comment]
Could the issue with `/bin/sh` blocking the signals be worked around if the `--entrypoint` is set to `/bin/bash`, and `--command` is `-c ...`? It seems like that is the only work around if you are overriding the image's `ENTRYPOINT`, right?

**Comment by justincormack** [comment]
@ketzacoatl but in your case you don't want `/bin/sh` to run I thought? As it is not passing the signals to your application, so you want  your application to be the entrypoint?

**Comment by cpuguy83** [comment]
@ketzacoatl The correct way to handle this is to use `exec` to launch your final process.

**Comment by ketzacoatl** [comment]
Thanks for the info, it has helped in debugging and resolving some issues I have been tracking.

**Comment by ketzacoatl** [comment]
Feel free to re-open if you wish to update docs. Personally, I think they ought to be updated to clarify these details.

**Comment by thaJeztah** [comment]
There's some information about signal handling in the docs; https://docs.docker.com/engine/reference/run/#/foreground and https://docs.docker.com/engine/reference/builder/#/exec-form-entrypoint-example, but let us know if you have suggestions where additional information should be added

**Comment by ketzacoatl** [comment]
Personally, I find the details about the list form of `ENTRYPOINT` and the semantics of `--entrypoint` both confusing and unexpected (oh, I must do X and Y when I want Z, even though Z should be common and expected).

**Comment by cpuguy83** [comment]
@ketzacoatl The only different between `ENTRYPOINT` and `--entrypoint` is that you can't use the list form with `--entrypoint`.

Using `/bin/sh` on the non-list form is a must otherwise many people will have a broken container and not know why... granted it's often still broken because they end up wrapped in a shell and not using `exec my_app` to actually launch their app... but having to use `exec` is pretty a pretty standard thing. If you are launching an application via a shell script, that application will be wrapped by the shell unless you use `exec`.

**Comment by ketzacoatl** [comment]
The difference you note between `ENTRYPOINT` and `--entrypoint` has surprising consequences, and is not immediately clear. 6 of my colleagues have reviewed the semantics, and we all agree the details here were not clear, and are surprising.

**Comment by thaJeztah** [comment]
If you have suggestions for what you think should be improved / written better, we welcome pull requests :heart:, sometimes we get either "blind" for omissions, or don't have time for making the actual changes.
