### ISSUE TITLE
Docker api is not listing containers

### ISSUE THREAD

**Issue by rbagul** [docker/docker#26867]
Hi,

We have installed Docker on RHEL  7 behind the firewall. Created few containers from Dockerfiles. 
I can see docker images but when I do curl -X GET http://<hostIP>:4243/images/json it is showing nothing. (i.e. [])

Basically I am trying to spin docker slave machines from Jenkins and Jenkins master is unable to find any images on Docker host. 

Information about the Docker setup. 
Docker version:
[root@XXXXXXX ~]# docker version
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      2a93377-unsupported
 Built:           Fri Jul 29 13:45:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.10.x86_64
 Go version:      go1.6.2
 Git commit:      2a93377-unsupported
 Built:           Fri Jul 29 13:45:25 2016
 OS/Arch:         linux/amd64

[root@XXXXXX ~]# docker info
Containers: 36
 Running: 6
 Paused: 0
 Stopped: 30
Images: 120
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:4-263325-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.704 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.691 GB
 Metadata Space Used: 9.654 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
 Authorization: rhel-push-plugin
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 7.64 GiB
Name: XXXXXXXXXXXXX
ID: KDAL:PQLB:TFMH:T7V2:KL3Z:AXUJ:YCD6:KUJT:CPUI:HFKW:XDH6:LMJN
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: registry.access.redhat.com (secure), docker.io (secure)

Port 4243 is listening.
[root@XXXXXX ~]# netstat -tunlp | grep 4243
tcp6       0      0 :::4243                 :::*                    LISTEN      15370/docker-curren

There are images available:
[root@XXXXXXX ~]# docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
testslave                         latest              6f516138e4d5        19 hours ago        426.1 MB
<none>                            <none>              8a09033510d5        20 hours ago        196.7 MB
<none>                            <none>              4286e0891b8b        21 hours ago        218.2 MB
build_slave                       latest              b761b6b52081        23 hours ago        635.5 MB
jenkins-1                         latest              34d24490b12b        43 hours ago        892.2 MB
new_slave                         latest              90afbeb14b24        45 hours ago        892.2 MB
<none>                            <none>              b10c60459ea3        46 hours ago        892.2 MB

Please guide me how to access these images over API. 

Thanks,
Rakesh

**Comment by rbagul** [comment]
*http://:4243/images/json is http://hostname:4243/images/json

**Comment by cpuguy83** [comment]
You are using a forked version of Docker, so I'm not sure we can provide much help.
Are you sure the docker client is talking to the engine on the TCP port? Typically unless you configure it otherwise it will connect to /var/run/docker.sock.

```
curl localhost:32769/images/json                            )git:(use_docker_mounts_api
[{"Id":"sha256:2b8fd9751c4c0f5dd266fcae00707e67a2545ef34f9a29354585f93dac906749","ParentId":"","RepoTags":["busybox:latest"],"RepoDigests":["busybox@sha256:a59906e33509d14c036c8678d687bd4eec81ed7c4b8ce907b888c607f6a1e0e6"],"Created":1466724217,"Size":1092588,"VirtualSize":1092588,"Labels":{}}]
```

Closing since this is not really a Docker issue.
