### ISSUE TITLE
Can't remove image due to error: “Error response from daemon: reference does not exist”

### ISSUE THREAD

**Issue by reypm** [docker/docker#26862]
I'm having a strange problem while trying to clear the images created by Docker. This is what I did:

 - Remove all containers

        $ docker rm $(docker ps -a -q)
        bb3927e956bf
        3e2eeb6287c4

 - Check if there is any container running or created after:

        $ docker ps -a
        CONTAINER ID    IMAGE    COMMAND    CREATED    STATUS    PORTS    NAMES

 - Remove all images: the first attempt failed because images were referenced

        $ docker rmi $(docker images -q)
        Error response from daemon: conflict: unable to delete 2f21ea981017 (must be forced) - image is referenced in one or more repositories
        Error response from daemon: conflict: unable to delete 2f21ea981017 (must be forced) - image is referenced in one or more repositories

 - Remove all images using `-f` option:

        $ docker rmi -f $(docker images -q)
        Untagged: dev-php55:latest
        Untagged: reynierpm/dev-php55:latest
        Deleted: sha256:2f21ea981017f65adcf0df3764756690adc35d80538bbb6dcada12990f589f37
        Deleted: sha256:7fbddc1aa50dca9bdf4f8c8033d20eca26ac00432f57333987c0eac3fe55fb08
        Deleted: sha256:15883aeb774feafa64328ea2e77ebbe17a91e79ca1cd8bb2eebca60802fb01f5
        Deleted: sha256:36ff96a995807763e302657eaeb671c000e58e3128a47f63bae543ba501387ed
        Deleted: sha256:053f436f01f809f60ecba9fb961dfb6404dce163f84fbd905eb47a6b436ba50d
        Deleted: sha256:b4525a37a105a199b7e7772de9e6ad86af645509c94c705bd13fbd422bf8f55d
        Deleted: sha256:228092e34fffbb9def7f883eceea9f37fce3750d7a7d5a7551ce009410567240
        Deleted: sha256:a17ed03e91cc4bef074258f731bba0945bcacc78c7ac9f00d88ca111125c94c0
        Deleted: sha256:6118ff18e2049d3e13a903c4163e4e4aceea9fdd30555bdd71a1e23e8d5aa022
        Deleted: sha256:b7347848822645efd3259a6c200a94c7bba15fc72b504c704e39f5db0cdca1a2
        Deleted: sha256:b23b831be841f1f3cececec3e52480723d8312b464d9a89957e867fa695a4eca
        Deleted: sha256:86c4c6d54d9dee52f8abe0ba8b3622b985bce68923dada61838b45860f000f44
        Deleted: sha256:f053241f28e7c62ac77b44ee2f69a7bd6d2bb2ccdd9f916e43b8af88f5865f90
        Deleted: sha256:3f36e15d9aac3c197472d66904fc59bd509ca36c8aa885165aadc6507f27126c
        Deleted: sha256:6586309b23369f2ccb067ca456ebacd1602787960215d7c2e898c28ae6a2e78d
        Deleted: sha256:43d7779d3bcd75a466df309735762f33552c2caf8f656ce1e26e1fd6b0324c49
        Deleted: sha256:9e060bbbad0c042fc45eb52d3e4c41bfd30fb620459f10c62cf7e483d514e1d8
        Deleted: sha256:9da9f4caedc27c128dc51d273f9d1411d6fce3f560c606fff0567d912d2d95e4
        Error response from daemon: No such image: 2f21ea981017:latest
        Error response from daemon: reference does not exist

Then this error: `No such image: 2f21ea981017:latest` comes up and I should ask, why? Where is such image? There is some kind of internal DB for Docker where it stores information?

After I run all the previous commands then I run the following and notice the output:

    $ docker images
    REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
    ubuntu              14.04.5             b1719e1db756        3 days ago          187.9 MB

But then I tried to remove the images again by running

    $ docker rmi b1719e1db756
    Error response from daemon: reference does not exist

And I got the same error, what I am missing here? How I can fix this?

I should add that I've run also the commands from [this post][1] but without success.

PS: I have made this question originally at [SO][2] but none answer yet so I move into here

  [1]: http://stackoverflow.com/questions/26127807/cannot-remove-docker-image-error-response-from-daemon
 [2]: http://stackoverflow.com/questions/39662746/cant-remove-image-due-to-error-error-response-from-daemon-reference-does-not

**Comment by thaJeztah** [comment]
> Then this error: No such image: 2f21ea981017:latest comes up and I should ask, why? Where is such image? There is some kind of internal DB for Docker where it stores information?

This case can probably be explained; you're using `docker images -q` as the input for `docker rmi`, which can potentially return the same image twice (as you've seen in your earlier example); in such cases, it's possible that docker _untags_ the image; the second time, removal succeeded (`Deleted: sha256:2f21ea981017f65adcf0df3764756690adc35d80538bbb6dcada12990f589f37`), however, because the `docker images -q` returned that ID _twice_, you're basically running `docker rmi 2f21ea981017 2f21ea981017`, so you're trying to remove that image _twice_. The second time, the image is already removed (so no image with that _ID_ is found), and docker tries to find an image by _name_, and appends the default (`:latest`) tag.

> But then I tried to remove the images again by running

Not sure what happened in that case. Can you provide the output of `docker info` and `docker version`?

**Comment by reypm** [comment]
@thaJeztah here you go:

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-1844828-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 253.5 MB
 Data Space Total: 107.4 GB
 Data Space Available: 44.71 GB
 Metadata Space Used: 852 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.4-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.667 GiB
Name: mmi.rperez.dev
ID: 55JR:BLZC:AN4Q:PBVU:IGTB:XJLB:UFAF:LP2J:NCQE:LDS7:OL4H:A4DN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

```
Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
ping @aaronlehmann @tonistiigi could you have a look? The "first" issue is expected (as I tried to explain in my previous comment), but not sure what could cause the second issue? (`docker rmi b1719e1db756`)

**Comment by aaronlehmann** [comment]
`docker rmi -f` will delete the image even if a tag references it. So you deleted `b1719e1db756` even though `ubuntu:14.04.5` references it. If you want to remove that tag, I believe `docker rmi ubuntu:14.04.5` will work.

I think all of this behavior is as expected, though `rmi` behavior is consistently convoluted.

**Comment by reypm** [comment]
@aaronlehmann that does not work either, see the output:

```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              14.04.5             b1719e1db756        6 days ago          187.9 MB

$ docker rmi ubuntu:14.04.5
Error response from daemon: No such image: ubuntu:14.04.5
```

**Comment by aaronlehmann** [comment]
I guess there's a problem with removing a tag when the image it points to doesn't exist. I'll take a look at this and submit a PR if it turns out to be a straightforward fix.

In general, though, I'd suggest avoiding `docker rmi -f`, because it can put you in a state like this.

**Comment by aaronlehmann** [comment]
@reypm: Could you paste your `repositories.json` file? The path is something like `/var/lib/docker/image/aufs/repositories.json` (`aufs` may be replaced with a different graph driver).

My suspicion is that the `ubuntu` reference is stored in the file in a non-canonical form. It should be stored as `docker.io/library/ubuntu`, but if it is stored as something like `ubuntu`, the image deletion code will actually try to untag `docker.io/library/ubuntu`, and fail.

If this is the case, I'm not sure how the non-canonical form would have been written to the file in the first place. Docker should only write it in the canonical form. Is this an old or recent Docker installation? Is there a possibility some other tool could have manipulated the file?

**Comment by reypm** [comment]
@aaronlehmann here ...

```
$ cat /var/lib/docker/image/devicemapper/repositories.json 
{"Repositories":{"docker.io/ubuntu":{"docker.io/ubuntu:14.04.5":"sha256:b1719e1db7562c103f300e790a6323a454877812c6103d8e5b75af536eb4f107"}}
```

**Comment by aaronlehmann** [comment]
It could be related to the older version that was installed. I wasn't aware that any version would format the repository name in this way. Any chance you could find out what you were using before?

**Comment by reypm** [comment]
@aaronlehmann yes ...

For docker:
```
$ sudo dnf info docker
Last metadata expiration check: 2:11:01 ago on Mon Sep 26 11:15:50 2016.
Available Packages
Name        : docker
Arch        : x86_64
Epoch       : 2
Version     : 1.10.3
Release     : 52.git8b7fa4a.fc24
Size        : 6.7 M
Repo        : updates
Summary     : Automates deployment of containerized applications
URL         : https://github.com/projectatomic/docker
License     : ASL 2.0
Description : Docker is an open-source engine that automates the deployment of any
            : application as a lightweight, portable, self-sufficient container that will
            : run virtually anywhere.
            : 
            : Docker containers can encapsulate any payload, and will run consistently on
            : and between virtually any server. The same container that a developer builds
            : and tests on a laptop will run at scale, in production*, on VMs, bare-metal
            : servers, OpenStack clusters, public instances, or combinations of the above.
```

For docker-engine:
```
$ sudo dnf info docker-engine
Last metadata expiration check: 2:11:33 ago on Mon Sep 26 11:15:50 2016.
Installed Packages
Name        : docker-engine
Arch        : x86_64
Epoch       : 0
Version     : 1.12.1
Release     : 1.fc24
Size        : 79 M
Repo        : @System
From repo   : dockerrepo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
Description : Docker is an open source project to build, ship and run any application as a
            : lightweight container.
            : 
            : Docker containers are both hardware-agnostic and platform-agnostic. This means
            : they can run anywhere, from your laptop to the largest EC2 compute instance and
            : everything in between - and they don't require you to use a particular
            : language, framework or packaging system. That makes them great building blocks
            : for deploying and scaling web apps, databases, and backend services without
            : depending on a particular stack or provider.

Available Packages
Name        : docker-engine
Arch        : src
Epoch       : 0
Version     : 1.12.1
Release     : 1.fc24
Size        : 26 M
Repo        : dockerrepo
Summary     : The open-source application container engine
URL         : https://dockerproject.org
License     : ASL 2.0
Description : Docker is an open source project to build, ship and run any application as a
            : lightweight container.
            : 
            : Docker containers are both hardware-agnostic and platform-agnostic. This means
            : they can run anywhere, from your laptop to the largest EC2 compute instance and
            : everything in between - and they don't require you to use a particular
            : language, framework or packaging system. That makes them great building blocks
            : for deploying and scaling web apps, databases, and backend services without
            : depending on a particular stack or provider.
```

**Comment by reypm** [comment]
@aaronlehmann maybe the solution could be:

- Remove docker-engine: `dnf remove docker-engine`
- Install docker: `dnf install docker`
- Remove the images: `docker rmi -f $(docker images -q)`
- Remove the docker: `dnf remove docker`
- Install docker-engine: `dnf install docker-engine`
- Build the images from scratch

What do you think? Maybe there is a best solution but that goes beyond my knowledge

**Comment by reypm** [comment]
@aaronlehmann ok, that works. See the following output:

```
$ sudo dnf remove docker-engine
[sudo] password for rperez: 
Dependencies resolved.
================================================================================================================================================================================
 Package                                            Arch                               Version                                    Repository                               Size
================================================================================================================================================================================
Removing:
 audit-libs-python                                  x86_64                             2.6.7-1.fc24                               @updates                                477 k
 docker-engine                                      x86_64                             1.12.1-1.fc24                              @dockerrepo                              79 M
 docker-engine-selinux                              noarch                             1.12.1-1.fc24                              @dockerrepo                              44 k
 libselinux-python                                  x86_64                             2.5-9.fc24                                 @updates                                608 k
 libsemanage-python                                 x86_64                             2.5-5.fc24                                 @updates                                379 k
 policycoreutils-python                             x86_64                             2.5-13.fc24                                @updates                                1.1 M
 python-IPy                                         noarch                             0.81-15.fc24                               @fedora                                 139 k

Transaction Summary
================================================================================================================================================================================
Remove  7 Packages

Installed size: 82 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Erasing     : docker-engine-1.12.1-1.fc24.x86_64                                                                                                                          1/7 
  Erasing     : docker-engine-selinux-1.12.1-1.fc24.noarch                                                                                                                  2/7 
  Erasing     : policycoreutils-python-2.5-13.fc24.x86_64                                                                                                                   3/7 
  Erasing     : python-IPy-0.81-15.fc24.noarch                                                                                                                              4/7 
  Erasing     : audit-libs-python-2.6.7-1.fc24.x86_64                                                                                                                       5/7 
  Erasing     : libselinux-python-2.5-9.fc24.x86_64                                                                                                                         6/7 
  Erasing     : libsemanage-python-2.5-5.fc24.x86_64                                                                                                                        7/7 
  Verifying   : policycoreutils-python-2.5-13.fc24.x86_64                                                                                                                   1/7 
  Verifying   : docker-engine-1.12.1-1.fc24.x86_64                                                                                                                          2/7 
  Verifying   : docker-engine-selinux-1.12.1-1.fc24.noarch                                                                                                                  3/7 
  Verifying   : audit-libs-python-2.6.7-1.fc24.x86_64                                                                                                                       4/7 
  Verifying   : libselinux-python-2.5-9.fc24.x86_64                                                                                                                         5/7 
  Verifying   : python-IPy-0.81-15.fc24.noarch                                                                                                                              6/7 
  Verifying   : libsemanage-python-2.5-5.fc24.x86_64                                                                                                                        7/7 

Removed:
  audit-libs-python.x86_64 2.6.7-1.fc24     docker-engine.x86_64 1.12.1-1.fc24            docker-engine-selinux.noarch 1.12.1-1.fc24     libselinux-python.x86_64 2.5-9.fc24    
  libsemanage-python.x86_64 2.5-5.fc24      policycoreutils-python.x86_64 2.5-13.fc24     python-IPy.noarch 0.81-15.fc24                

Complete!

[rperez@mmi docker-php55]$ sudo dnf install docker -y
RPM Fusion for Fedora 24 - Free - Updates                                                                                                        75 kB/s | 320 kB     00:04    
Dependencies resolved.
================================================================================================================================================================================
 Package                                         Arch                             Version                                               Repository                         Size
================================================================================================================================================================================
Installing:
 docker                                          x86_64                           2:1.10.3-52.git8b7fa4a.fc24                           updates                           6.7 M
 docker-selinux                                  x86_64                           2:1.10.3-52.git8b7fa4a.fc24                           updates                            76 k
 docker-v1.10-migrator                           x86_64                           2:1.10.3-52.git8b7fa4a.fc24                           updates                           1.9 M
 oci-register-machine                            x86_64                           0-1.1.git7d4ce65.fc24                                 fedora                            925 k
 oci-systemd-hook                                x86_64                           0.1.4-1.fc24                                          fedora                             30 k

Transaction Summary
================================================================================================================================================================================
Install  5 Packages

Total download size: 9.7 M
Installed size: 39 M
Downloading Packages:
(1/5): docker-selinux-1.10.3-52.git8b7fa4a.fc24.x86_64.rpm                                                                                       18 kB/s |  76 kB     00:04    
(2/5): docker-v1.10-migrator-1.10.3-52.git8b7fa4a.fc24.x86_64.rpm                                                                               346 kB/s | 1.9 MB     00:05    
(3/5): oci-systemd-hook-0.1.4-1.fc24.x86_64.rpm                                                                                                 7.8 kB/s |  30 kB     00:03    
(4/5): docker-1.10.3-52.git8b7fa4a.fc24.x86_64.rpm                                                                                              678 kB/s | 6.7 MB     00:10    
(5/5): oci-register-machine-0-1.1.git7d4ce65.fc24.x86_64.rpm                                                                                    148 kB/s | 925 kB     00:06    
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                           503 kB/s | 9.7 MB     00:19     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Installing  : docker-v1.10-migrator-2:1.10.3-52.git8b7fa4a.fc24.x86_64                                                                                                    1/5 
  Installing  : docker-selinux-2:1.10.3-52.git8b7fa4a.fc24.x86_64                                                                                                           2/5 
  Installing  : docker-2:1.10.3-52.git8b7fa4a.fc24.x86_64                                                                                                                   3/5 
  Installing  : oci-systemd-hook-0.1.4-1.fc24.x86_64                                                                                                                        4/5 
  Installing  : oci-register-machine-0-1.1.git7d4ce65.fc24.x86_64                                                                                                           5/5 
  Verifying   : docker-2:1.10.3-52.git8b7fa4a.fc24.x86_64                                                                                                                   1/5 
  Verifying   : docker-selinux-2:1.10.3-52.git8b7fa4a.fc24.x86_64                                                                                                           2/5 
  Verifying   : docker-v1.10-migrator-2:1.10.3-52.git8b7fa4a.fc24.x86_64                                                                                                    3/5 
  Verifying   : oci-register-machine-0-1.1.git7d4ce65.fc24.x86_64                                                                                                           4/5 
  Verifying   : oci-systemd-hook-0.1.4-1.fc24.x86_64                                                                                                                        5/5 

Installed:
  docker.x86_64 2:1.10.3-52.git8b7fa4a.fc24               docker-selinux.x86_64 2:1.10.3-52.git8b7fa4a.fc24       docker-v1.10-migrator.x86_64 2:1.10.3-52.git8b7fa4a.fc24      
  oci-register-machine.x86_64 0-1.1.git7d4ce65.fc24       oci-systemd-hook.x86_64 0.1.4-1.fc24                   

Complete!

[rperez@mmi docker-php55]$ sudo service docker start
Redirecting to /bin/systemctl start  docker.service

[rperez@mmi docker-php55]$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
docker.io/ubuntu    14.04.5             b1719e1db756        7 days ago          187.9 MB

[rperez@mmi docker-php55]$ docker rmi -f $(docker images -q)
Untagged: docker.io/ubuntu:14.04.5
Deleted: sha256:b1719e1db7562c103f300e790a6323a454877812c6103d8e5b75af536eb4f107
Deleted: sha256:8dd403bda424cf9769c4a823dc26f6341f458546020204f2678bce18ef6bba4d
Deleted: sha256:b5964a4f8d53a791d979a9b991caaeccf3222659b357b21f654d1acc9dad514d
Deleted: sha256:f03a40155449ba206eb05b5f609d105888d4b6bff766cc8e814d530193842690
Deleted: sha256:ee64cb544a6aba3b5987b558183219d077a490321781daf0fb141a5c331f53b5
Deleted: sha256:3d1126efbbe3b59aa736874d01e88676a3f054d6c9e160d9a183bbbb80ad9b33
```

**Comment by thaJeztah** [comment]
```
dnf install docker
```

Installs the Red Hat fork of Docker, which contains various modifications in this area, and would likely explain the incorrectly stored image.

Looking at the above, it looks like your issue is resolved, so I think we can close this?

**Comment by reypm** [comment]
@thaJeztah not yet, after run the commands above and after reinstall back the `docker-engine` now I am running into this issue:

```
$docker images
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```

How can I fix that?

**Comment by reypm** [comment]
@thaJeztah no, I have followed the steps above meaning I had `docker-engine` and I removed in order to install `docker`, after I cleanup the conflict image running `docker rmi` after all of that I removed again `docker` and install `docker-engine` back but now I am getting that error, something goes wrong but I don't know what

**Comment by thaJeztah** [comment]
Possibly there's two docker client binaries installed for some reason; `which docker` should show you the path that's used, but it's possible there's another version installed elsewhere

**Comment by reypm** [comment]
@thaJeztah and how can I check if I have two binaries running on the same host? The shouldn't but just to be sure

Notice this output:

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```

Only one docker running but again the same annoying message

**Comment by thaJeztah** [comment]
Only one is running probably, but there may be other binaries (check `/usr/bin`, `/usr/local/bin`, etc.

**Comment by reypm** [comment]
@thaJeztah I will need your help on this one, see what I have done so far and it's output:

```
$ sudo whereis docker
[sudo] password for rperez: 
docker: /usr/bin/docker /etc/docker /usr/share/man/man1/docker.1.gz

$ cd /usr/bin && sudo ls -la | grep docker
-rwxr-xr-x.   1 root root    13913184 Aug 18 01:32 docker
-rwxr-xr-x.   1 root root     9344704 Aug 18 01:32 docker-containerd
-rwxr-xr-x.   1 root root     8704072 Aug 18 01:32 docker-containerd-ctr
-rwxr-xr-x.   1 root root     2429040 Aug 18 01:32 docker-containerd-shim
-rwxr-xr-x.   1 root root    38614760 Aug 18 01:32 dockerd
-rwxr-xr-x.   1 root root     2670296 Aug 18 01:32 docker-proxy
-rwxr-xr-x.   1 root root     6666616 Aug 18 01:32 docker-runc

$ cd /usr/local/bin/ && sudo ls -la | grep docker => no output
```

Any other advice?

**Comment by reypm** [comment]
@thaJeztah ok, nvm, I run the following commands:

```
$sudo autoremove
$sudo clean all
```

And after that everything works fine, not sure how or why, I'll close this, thank for all

**Comment by thaJeztah** [comment]
Can you check if your client is actually talking to the local daemon? (Just to be sure); check if a `DOCKER_HOST` env var is set. May be worth restarting the docker service once more?

**Comment by thaJeztah** [comment]
Oh, cool, good to hear,  thanks!

**Comment by suminksudhi** [comment]
Hi,
had the same issue

what I did was replace docker.io/ with "" string  in /var/lib/docker/image/devicemapper/repositories.json
followed by docker rmi command and it worked.

don't have reinstall everything again.
The issue was created when I upgrade my docker client from the one provided in linux repo with the once as documented in dockerhub.

Hope this helps someone.

**Comment by sonix07** [comment]
@suminksudhi you just saved my a lot of work. I deleted the docker.io/ from the repositories.json and after that I did `systemctl restart docker` and now I can delete the old images.

**Comment by nitish-nyllabs** [comment]
I receive this error Error response from daemon: conflict: unable to delete b472d6a9286d (cannot be forced) - image is being used by running container 8c2009966994 .

If I stop all the containers built on this image and then they spin up again very fast due to my docker-compose.yml.

version: "3" services: web: # replace username/repo:tag with your name and image details image: ndabas333/hola:newtest deploy: replicas: 5 resources: limits: cpus: "0.1" memory: 50M restart_policy: condition: on-failure ports: - "80:80" networks: - webnet networks: webnet:
This image doesn't exist on my registry now so help me to delete it along with the containers.

**Comment by thaJeztah** [comment]
@nitish-nyllabs that's not a bug; the error message is quite clear what's happening: you're trying to remove an image that's being used by a container, so that fails.

You need to remove that container so that the image can be removed; if the container is part of a service (in your case: if you deployed using `docker stack deploy`), stopping a container will start a new container, because those containers are managed by docker; so to remove the container, you can `docker stack rm` the stack to remove all of its containers.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for [reporting bugs and feature requests](https://raw.githubusercontent.com/moby/moby/master/.github/ISSUE_TEMPLATE.md). For other type of questions, consider using one of;

- the Docker Support Forums - https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/) (register here: [http://dockr.ly/community](http://dockr.ly/community))
- [StackOverflow](https://stackoverflow.com)
