### ISSUE TITLE
Slow File I/O on Container VS Host (Docker 1.24, Docker for Mac)

### ISSUE THREAD

**Issue by flyandi** [docker/docker#26865]
**Description**

There seems to be another issue when running docker-compose on Docker for Mac and having a large file base mounted to the container.

Running a large PHP project inside a multi container docker-compose project (Nginx, MySQL, Redis, PHP-FPM - all separate containers running at the same time and connecting via internal backplane).

Running the boot script on the host:
``` 
real	0m0.089s
user	0m0.065s
sys	0m0.017s
```

Running the boot script in the container:
```
real	0m1.167s
user	0m0.070s
sys	0m0.130s
```

**Describe the results you received:**

Container is about 10x slower than host for all File I/O requests.

**Describe the results you expected:**

Container should the same or almost equal to host file i/o

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 70
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 96
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 5
Total Memory: 3.855 GiB
Name: moby
ID: OORF:UFGL:YOMG:HY4G:SX7M:PCW5:GPDN:XBV7:CVWE:VBNH:4DTH:VKI7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-09-23T17:43:38.899804591Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Using latest Docker For Mac

**Comment by thaJeztah** [comment]
since this is specific to docker for Mac, could you reopen this issue in the docker for Mac issue tracker? https://github.com/docker/for-mac/issues ?

**Comment by flyandi** [comment]
Done. Will close this issue.
