### ISSUE TITLE
[Question] Why --listener-addr defaults to 0.0.0.0:2377

### ISSUE THREAD

**Issue by liweinan0423** [docker/docker#26884]
According to the docker documentation, the `--listen-addr` option of `docker swarm join` defaults to 0.0.0.0:2377. When a node that has multiple network interfaces joins a swam cluster, `--listen-addr=0.0.0.0:2377' seems not working correctly. Sometimes the internal DNS name of a service does not resolve, especially when update a service and this services is moved an another node in the cluster.

**Comment by justincormack** [comment]
Can you give the information requested (which version of docker you are using, output of docker info) and some more detail about how to replicate the issue.

**Comment by xiaods** [comment]
@liweinan0423 how about give docker info update?

**Comment by liweinan0423** [comment]
````
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 142
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 9uzp9v6sj0bh40s6qwjlikka0
 Is Manager: true
 ClusterID: 3jzlu04zfas99jnild1axcyf0
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: W5XS:KGA5:AR74:OM6D:FK6X:AMCB:A4E6:UFBE:UQDY:M3FL:B3MN:NSVJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 125
 System Time: 2016-09-26T09:55:29.717642982Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
````
We have a Docker swarm cluster which is created without setting the `--listen-addr` option. We we scale a service or update a service, if the service is moved to another node in the cluster, the internal DNS records for the service name was not updated. 

Then we remove the cluster and re-create the it with `--listen-addr=<node_ip>:2377` option, the cluster is working correctly.

We guess it was because there are multiple network interfaces on our node, if we don't set the `--listen-addr` option, the node may be using a wrong network interface to communicate with other nodes in the cluster. So we are wondering if the `--listen-addr` options could be changed to a mandatory option when creating the cluster.

**Comment by thaJeztah** [comment]
> So we are wondering if the --listen-addr options could be changed to a mandatory option when creating the cluster.

If I'm not mistaken, `docker swarm init` will now output an error if it has detected multiple interfaces, and require the `--listen-addr` in that case.

@aaronlehmann am I correct, or only if the first interface has multiple IP-addresses?

**Comment by liweinan0423** [comment]
I think it's the multiple IP address case. We've never seen the error be printed without the `--listen-addr` option even there are multiple interfaces on the machine.

On the other hand, the `--listen-addr` option should be mandatory for both `docker swarm init` and `docker swarm join` commands

**Comment by aaronlehmann** [comment]
If I'm not mistaken, docker swarm init will now output an error if it has detected multiple interfaces, and require the `--listen-addr` in that case.

It requires `--advertise-addr` in this case. If the address specified is not a local address, `--listen-addr` is required as well.

The issue described here sounds like a problem with network gossip. I imagine there's a better fix than making `--listen-addr` mandatory.

**Comment by thaJeztah** [comment]
Oh, correct, I'm mistaking `--listen-addr` for `--advertise-addr`

**Comment by cmingxu** [comment]
@aaronlehmann could you please elaborate on --advertise-addr is  not a local address?

**Comment by liweinan0423** [comment]
````
[root@****** ~]# docker info
Containers: 5
 Running: 4
 Paused: 0
 Stopped: 1
Images: 70
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: active
 NodeID: 2svq4cl7yzewwayq2ycn450wu
 Is Manager: true
 ClusterID: 5rhbprwph4fg9vbv4bl0rpqh5
 Managers: 2
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.63.79.206
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.3-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.836 GiB
Name: szxtsv22457ctx
ID: CV6G:WWWF:EGAR:TDR2:HQOU:WSED:6CX5:7KBB:KN6M:JZNW:UPWD:K6GN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
````
* ip a
````
[root@******~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eno16777984: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:aa:4f:d2 brd ff:ff:ff:ff:ff:ff
    inet 10.2.143.91/24 brd 10.2.143.255 scope global eno16777984
       valid_lft forever preferred_lft forever
3: eno33557248: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:aa:52:a6 brd ff:ff:ff:ff:ff:ff
    inet 10.8.113.159/24 brd 10.8.113.255 scope global eno33557248
       valid_lft forever preferred_lft forever
4: eno50336512: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP qlen 1000
    link/ether 00:50:56:aa:45:ee brd ff:ff:ff:ff:ff:ff
    inet 10.5.34.181/24 brd 10.5.34.255 scope global eno50336512
       valid_lft forever preferred_lft forever
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:97:69:b9:09 brd ff:ff:ff:ff:ff:ff
    inet 192.168.0.1/24 scope global docker0
       valid_lft forever preferred_lft forever
1172: br-f982070f7982: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP
    link/ether 02:42:2d:d4:a8:65 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 scope global br-f982070f7982
       valid_lft forever preferred_lft forever
1178: veth22e3e97@if1177: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-f982070f7982 state UP
    link/ether 4e:c2:93:af:f2:78 brd ff:ff:ff:ff:ff:ff link-netnsid 1
1192: veth5450d9a@if1191: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether ae:32:e2:41:1e:1e brd ff:ff:ff:ff:ff:ff link-netnsid 3
11248: veth0fe6378@if11247: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-f982070f7982 state UP
    link/ether 8a:de:4c:c9:3c:bb brd ff:ff:ff:ff:ff:ff link-netnsid 2
````

We have a node which has multiple interfaces, but either `docker swarm init` nor `docker swarm join` requires the `--listen-addr` option.

**Comment by xiaods** [comment]
@liweinan0423 i have read the reference in docker/docker repo:

```
### `--listen-addr value`

The node listens for inbound swarm manager traffic on this address. The default is to listen on
0.0.0.0:2377. It is also possible to specify a network interface to listen on that interface's
address; for example `--listen-addr eth0:2377`.

Specifying a port is optional. If the value is a bare IP address or interface
name, the default port 2377 will be used.

```
so i want to ask, what concern on this issue topic? i am lost in above discussion.

**Comment by liweinan0423** [comment]
@xiaods let me ask you one question. If there are 2 network interfaces on the node and we don't specify the `--listen-addr` option, which interface will docker take for the communicate between nodes?

**Comment by aaronlehmann** [comment]
> @aaronlehmann could you please elaborate on `--advertise-addr` is not a local address?

If you specify `--advertise-addr`, and it's not one of the addresses on a network interface (for example, if you're behind NAT, so other managers connect to a different IP address than the first manage sees locally), Docker still needs to know which interface is being used, for overlay networking setup. Specifying `--listen-addr` gives it in this information. If `--advertise-addr` is one of the network interface addresses, then `--listen-addr` is not necessary, because Docker can figure out itself which network interface is involved.

> We have a node which has multiple interfaces, but neither docker swarm init nor docker swarm join requires the `--listen-addr` option.

Does it require `--advertise-addr`? `--listen-addr` isn't normally required.

If it does not, it may be because some of the interfaces aren't physical network devices (for example bridges, veth). By default these are ignored since they are unlikely to be the device used for manager-to-manager communication.

**Comment by aluzzardi** [comment]
`swarm join` will use the address you provide only during initial connection.
Once connected, the manager will give the worker the list of all managers (including itself) along with their
address (as defined in advertise address).

If a manager goes down, its workers will randomly reconnect to another manager based on that list.
When a new manager joins, its advertise address is broadcasted to all workers.

Advertise address is also used for Raft. Raft configuration has the list of all managers' advertised addresses.
When a manager joins raft, it gets the list of all other managers and connect to them to sync data.

In short, `--advertise-addr` specifies how every other nodes should connect back to me. It's the only address other peers know.

`--listen-addr` just defines where to listen (address and port, typically 0.0.0.0 with default port). You typically never change this but we had to provide it for some use cases: let's say you have two network interfaces and DO NOT want to be reachable on one of the two.

Listen and Advertise cannot be the same flag since the advertised address might not even be "visible" from the machine itself (NAT, redirection, ...). Example: You might advertise an Elastic IP or an ELB. Others will use that address to connect to you but you can't listen on it directly.

**Comment by andresmoschini** [comment]
Thanks for the detailed explanation @aluzzardi !

I have still a doubt. Is updating `advertise-addr` and `listen-addr` possible? 

I am only seeing those options in `swarm init` but not in `swarm update`. Is there any way to edit them?
