### ISSUE TITLE
Docker swarm container downgrade

### ISSUE THREAD

**Issue by kristiandrucker** [docker/docker#26887]
Hi how can I downgrade docker swarm services?

**Comment by michelvocks** [comment]
A few more information would be helpful here. Do you mean downgrading docker engine version? Or container running in a docker swarm mode cluster?

**Comment by kristiandrucker** [comment]
Hi I mean container running in swarm mode. So if a user would like to rollback they can at any time.

**Comment by michelvocks** [comment]
You can use [rolling updates functionality](https://docs.docker.com/engine/swarm/swarm-tutorial/rolling-update/#/apply-rolling-updates-to-a-service) to roll back to an old version of your image.

**Comment by kristiandrucker** [comment]
Ok

**Comment by thaJeztah** [comment]
Thanks for helping out @michelvocks
