### ISSUE TITLE
[Question] Can npipe listener creation be moved to go-connections?

### ISSUE THREAD

**Issue by mwieczorek** [docker/docker#26895]
In [listeners_windows.go](https://github.com/docker/docker/blob/master/pkg/listeners/listeners_windows.go) tcp listener is [created](https://github.com/docker/docker/blob/master/pkg/listeners/listeners_windows.go#L19) with [go-connections](https://github.com/docker/go-connections/) sockets package:
```
import (
	...
	"github.com/docker/go-connections/sockets"
)
...
l, err := sockets.NewTCPSocket(addr, tlsConfig)
```
Can we move npipe listener creation also to go-connections?
Then it could be used also in other projects, f.e. [go-plugins-helpers](https://github.com/docker/go-plugins-helpers)

**Comment by justincormack** [comment]
Note we currently have an issue to remove go-connections https://github.com/docker/docker/issues/26802

**Comment by stevvooe** [comment]
I'd prefer not. go-connections is a poor abstraction and causes more problems than it creates.

The listeners package makes the same mistake, by hiding system-specific config, deep within the function. You could try to add this to go-connections, but my guess is, something will break.

**Comment by mwieczorek** [comment]
ok, so i'll close this issue, and try to add it directly to go-plugins-helpers, thanks.

**Comment by m-kostrzewa** [comment]
@mwieczorek I have a PRs hanging for both these repos doing exactly what you want https://github.com/docker/go-plugins-helpers/pull/63 and https://github.com/docker/go-connections/pull/24

This Issue, however, makes me realize that they will probably never be merged as they are right now...
