### ISSUE TITLE
create only one task on every manager, is using global and constraint a 'undefined behavior' ?

### ISSUE THREAD

**Issue by Revolution1** [docker/docker#26903]
VERSION: Docker 1.12.1

I need to run Interlock on my cluster. Since it needs the "/service" api, it can only run on the manager node. I want only one task on every manager.

I managed to achieve this by using both `--mode=global` and `--constraint node.role=manager`

When I use `docker service ps`, docker seems still created task on every node, only the manager's is in running state. 

That is quite confusing, am I using a "undefined behavior" ?

**Comment by thaJeztah** [comment]
ping @aluzzardi @dongluochen guess this should be documented properly, as the "constraints" section does not make mention of this; https://docs.docker.com/engine/reference/commandline/service_create/#/specify-service-constraints-constraint

**Comment by aluzzardi** [comment]
Constraints prevent the container to be scheduled on the machine, however, they do not prevent the container to be "created for scheduling" in the first place - therefore you'll see the container showing up in `docker service ps` but it won't run.

There's a PR out there that would actually prevent the container to be created in the first place: docker/swarmkit#1570

/cc @aaronlehmann

**Comment by Revolution1** [comment]
Great !

**Comment by aluzzardi** [comment]
Assigning to @aaronlehmann so he can close once docker/swarmkit#1570 gets merged

**Comment by aluzzardi** [comment]
@Revolution1 This was implemented in SwarmKit and will be available in the next (1.13) Docker release
