### ISSUE TITLE
syslog log-driver RFC5424 missing structured data part

### ISSUE THREAD

**Issue by codeb2cc** [docker/docker#26937]
**Description**
The syslog log-driver with RFC5424 format outputs log without structured data part. The `rfc5424formatterWithAppNameAsTag` function format log with `msg := fmt.Sprintf("<%d>%d %s %s %s %d %s %s", p, 1, timestamp, hostname, tag, pid, tag, content)`. But https://tools.ietf.org/html/rfc5424#section-6 defines a valid syslog message as `SYSLOG-MSG      = HEADER SP STRUCTURED-DATA [SP MSG]` where `STRUCTURED-DATA` must be a nil value `-` or any valid `SD-ELEMENT`. There's a missing part between the last `tag` and `content`, causing log server like `syslog-ng` to report parsing error.

**Steps to reproduce the issue:**
`--log-driver=syslog --log-opt syslog-format=rfc5424`

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
Looks like these methods are here; https://github.com/docker/docker/blob/2c91c5fdad49ff2103ae377b5b4e1a97ebe3f402/daemon/logger/syslog/syslog.go#L65-L85

Are you interested in opening a PR with the required changes?

**Comment by codeb2cc** [comment]
Think deeper it's not all wrong. User's custom application can output the `STRUCTURED-DATA` in their log and make full use of RFC5424 to handler log data better. But for application like `nginx` and `php-fpm`, user must try to change application's log format to fix in different log-driver.
So what about a new option `--log-opt syslog-no-sd=true`? If set to true the syslog log-driver should fill the `STRUCTURED-DATA` with `-`. Otherwise we assume that user want to handle the `STRUCTURED-DATA` part themselves and the log-driver just do nothing.

**Comment by codeb2cc** [comment]
Or `--log-opt syslog-format=rfc5424nosd`?

**Comment by thaJeztah** [comment]
ping @cpuguy83 @nalind perhaps you have some suggestions?

**Comment by nalind** [comment]
@thaJeztah I haven't worked out how much it costs, but if it's cheap enough to check if the initial portion of a log message looks like an SD-ELEMENT or not, then the log driver could insert the NILVALUE itself when the initial portion doesn't look like one.
