### ISSUE TITLE
Kernel Panic caused by com.docker.hyper

### ISSUE THREAD

**Issue by cguess** [docker/docker#26958]
MacOS suffered a kernel panic while using Docker for Mac. I was doing nothing out of the ordinary.

**Steps to reproduce the issue:**
1. Run Docker for Mac
2. ```docker-compose up```
3. Kernel Panic after some time

**Describe the results you received:**

Kernel panic

**Describe the results you expected:**

Not to have the machine crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep 15 11:20:26 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true```

**Output of `docker info`:**

```
Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 110
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 147
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: TEM2:5V34:4ZBI:ZZWL:37NL:54OK:ZWR2:URFK:XCOX:PWND:CMYI:NNVB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 28
 System Time: 2016-09-27T17:58:55.284608381Z
 EventsListeners: 1
Username: *********
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Macbook Pro 13''
MacOS 10.12 (16A322)
2.9 GHz Intel Core i5
16 GB 1867 MHz DDR3

Crash Report:
Anonymous UUID:       FB5840D3-D36A-55DF-46DD-AA6A54205DC7

Tue Sep 27 19:53:58 2016

*** Panic Report ***
panic(cpu 3 caller 0xffffff8004d0f89c): "Invalid queue element linkage for 0xffffff81e22d6000: next 0xffffff8005466fb0 next->prev 0xffffff81e22c6000 prev 0xffffff800548a488 prev->next 0xffffff8005466fc0"@/Library/Caches/com.apple.xbs/Sources/xnu/xnu-3789.1.32/osfmk/kern/queue.h:245
Backtrace (CPU 3), Frame : Return Address
0xffffff91f04f3e00 : 0xffffff8004cf748c 
0xffffff91f04f3e80 : 0xffffff8004d0f89c 
0xffffff91f04f3ef0 : 0xffffff8004d0f4a6 
0xffffff91f04f3f30 : 0xffffff8004cf0ee9 
0xffffff91f04f3f60 : 0xffffff8004e0a80e 
0xffffff91f04f3f80 : 0xffffff8004ca970f 

BSD process name corresponding to current thread: com.docker.hyper

Mac OS version:
16A322

Kernel version:
Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64
Kernel UUID: 622D2470-C34D-31F9-A62B-6AA9A3C6A3CD
Kernel slide:     0x0000000004a00000
Kernel text base: 0xffffff8004c00000
__HIB  text base: 0xffffff8004b00000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 700153451766935
last loaded kext at 697332448543050: at.obdev.nke.LittleSnitch	4356 (addr 0xffffff7f87e30000, size 311296)
last unloaded kext at 697643224928035: at.obdev.nke.LittleSnitch	4356 (addr 0xffffff7f87e30000, size 303104)
loaded kexts:
org.virtualbox.kext.VBoxNetAdp	5.0.26
org.virtualbox.kext.VBoxNetFlt	5.0.26
org.virtualbox.kext.VBoxUSB	5.0.26
com.intel.kext.intelhaxm	6.0.1
org.virtualbox.kext.VBoxDrv	5.0.26
com.radiosilenceapp.nke.filter	2.0
com.globaldelight.driver.Boom2Device	1.1
com.logitech.manager.kernel.driver	6.00.1
com.apple.filesystems.smbfs	3.1
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.23.7
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleGraphicsDevicePolicy	3.13.60
com.apple.driver.AppleUpstreamUserClient	3.6.4
com.apple.driver.AppleHDA	276.26
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleSMCLMU	208
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	5.0.0f18
com.apple.driver.AppleBacklight	170.9.10
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.driver.AudioAUUC	1.70
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	5.0.0f18
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.AppleCameraInterface	5.57.0
com.apple.driver.AppleIntelBDWGraphics	10.1.8
com.apple.driver.AppleIntelBDWGraphicsFramebuffer	10.1.8
com.apple.driver.AppleUSBCardReader	404.1.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	39
com.apple.filesystems.hfs.kext	366.1.1
com.apple.iokit.IOAHCIBlockStorage	295.1.1
com.apple.driver.AppleAHCIPort	326
com.apple.driver.AppleTopCaseHIDEventDriver	102
com.apple.driver.AirPort.Brcm4360	1100.37.1a16
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	5.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	5.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	171
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.nke.ppp	1.9
com.apple.driver.usb.IOUSBHostHIDDevice	1.1
com.apple.driver.usb.AppleUSBHub	1.1
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	276.26
com.apple.kext.OSvKernDSPLib	525
com.apple.iokit.IOBluetoothHostControllerUSBTransport	5.0.0f18
com.apple.iokit.IOBluetoothHostControllerTransport	5.0.0f18
com.apple.driver.AppleGraphicsControl	3.13.60
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.driver.AppleHDAController	276.26
com.apple.iokit.IOHDAFamily	276.26
com.apple.iokit.IOAudioFamily	205.11
com.apple.vecLib.kext	1.2.0
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.iokit.IOSurface	152
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.AppleGraphicsDeviceControl	3.13.60
com.apple.iokit.IOAcceleratorFamily2	288.13
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.iokit.IOSCSIBlockCommandsDevice	394
com.apple.iokit.IOUSBMassStorageDriver	131.1.1
com.apple.iokit.IOSCSIArchitectureModelFamily	394
com.apple.driver.usb.networking	5.0.0
com.apple.driver.CoreStorage	540
com.apple.filesystems.hfs.encodings.kext	1
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleThunderboltDPInAdapter	4.5.3
com.apple.driver.AppleThunderboltDPAdapterFamily	4.5.3
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.3
com.apple.driver.AppleHIDKeyboard	197
com.apple.driver.AppleMultitouchDriver	367.6
com.apple.driver.AppleInputDeviceSupport	76.1
com.apple.driver.AppleHSSPIHIDDriver	49
com.apple.driver.AppleThunderboltNHI	4.1.3
com.apple.iokit.IOThunderboltFamily	6.2.1
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleHSSPISupport	49
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.1
com.apple.driver.usb.AppleUSBXHCI	1.1
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.driver.AppleUSBHostMergeProperties	1.1
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	444
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.IOBluetoothHIDDriver	5.0.0f18
com.apple.iokit.IOBluetoothFamily	5.0.0f18
com.apple.iokit.IOReportFamily	31
com.apple.iokit.IOUSBHIDDriver	900.4.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.1
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleACPIPlatform	5.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0
Model: MacBookPro12,1, BootROM MBP121.0167.B17, 2 processors, Intel Core i5, 2.9 GHz, 16 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E434C544D4C41522D4E5544
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E434C544D4C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.21.171.10.1a16)
Bluetooth: Version 5.0.0f18, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by thaJeztah** [comment]
Thanks for reporting; could you reopen this in the docker for mac issue tracker (as it is specific to docker for mac); https://github.com/docker/for-mac/issues

I'll close the issue here, but thanks again for reporting
