### ISSUE TITLE
takes too long to response, when creating a network using non-existing driver

### ISSUE THREAD

**Issue by allencloud** [docker/docker#26974]
**Description**

When I create a network in bridge driver, accidently I typed in the wrong bridge as `brdige`. 
As a result it takes too long for docker daemon to response, almost 20s.

Here is my test:
```
root@ubuntu:~# date
Tue Sep 27 21:14:28 SGT 2016
root@ubuntu:~# docker network create -d brdige test
Error response from daemon: plugin not found
root@ubuntu:~# date
Tue Sep 27 21:14:45 SGT 2016
```

It takes approximately 17s.

**Steps to reproduce the issue:**
1. `docker network create -d brdige test` with non-existing network driver
2. wait for docker daemon's response
3. long time unexpectedly 

**Describe the results you received:**
docker daemon returns in a unacceptable time.

**Describe the results you expected:**
docker daemon returns in an acceptable time.

**Additional information you deem important (e.g. issue happens only occasionally):**
No swarm mode opened

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 63
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 463
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-09-27T21:13:29.858167901+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aboch** [comment]
It is because when libnetwork does not know about that driver, it assumes it is plugin one and it requests the plugin infra to load it. The plugin infra tries few times with an increasing backoff time between each retry, which gets to the 15 secs, before declaring the plugin can't be found.

I do not know if this is changing with the new plugin infra which @anusha-ragunathan is adding. @anusha-ragunathan is there going to be any change in regards to this behavior ?

**Comment by thaJeztah** [comment]
I think the new plugin infra doesn't use lazy loading, so chances are it improves yes

**Comment by anusha-ragunathan** [comment]
@aboch: There is no retry and backoff loop in pluginv2 (aka the new plugin infra), In pluginv2, plugins are loaded during install (`docker plugin install`) and not during network creation.

**Comment by allencloud** [comment]
That is great. Thanks a lot @aboch @thaJeztah @anusha-ragunathan 
Closing this?
