### ISSUE TITLE
Docker pull failed :Tag latest not found in repository docker.io/library/xxxx

### ISSUE THREAD

**Issue by spoonysnail** [docker/docker#26975]
I've tried to pull r-base/nginx/fedora/mongo. All failed.
And the error message is :Tag latest not found in repository docker.io/library/xxxx
I don't know why..
What's wrong?
---------------------
Updated 10.08.2016:
I've reinstalled the system and docker2boot. 
And now I can't even pull ubuntu.
The same error still exists. 
Anyone can help me ?
---------------------

My docker info:
```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.0 (TCL 6.3); master : 7f12e95 - Tue Aug 11 17:55:16 UTC 2015
CPUs: 4
Total Memory: 1.955 GiB
Name: boot2docker
ID: PKCU:QGIF:UAUR:YVD6:JYXW:ANGO:OOET:3ANN:IGTI:MWXJ:KVRA:ARKC
Debug mode (server): true
File Descriptors: 9
Goroutines: 38
System Time: 2016-10-08T01:56:05.085603353Z
EventsListeners: 0
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
```
Docker version:
```
Client:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      darwin/amd64

Server:
 Version:      1.8.0
 API version:  1.20
 Go version:   go1.4.2
 Git commit:   0d03096
 Built:        Tue Aug 11 17:17:40 UTC 2015
 OS/Arch:      linux/amd64
```

**Comment by spoonysnail** [comment]
Help!

**Comment by nathanleclaire** [comment]
`1.8.0` Docker is pretty old.  Try updating to 1.12.1 (or 1.12.2-rc3) and see if that fixes it.  BTW, boot2docker is also deprecated, use Docker for Mac/Windows and/or Docker Machine.

**Comment by spoonysnail** [comment]
@nathanleclaire 
thanks a lot ^-^
I use Docker for Mac. However there's another problem when I tried to pull images.
The error message is :
`error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c7/c73a085dc3782b3fd4c032971c76d6afb45fa3728a048175c8c77d7403de5f21/data?Expires=1475990329&Signature=EgCf0v0mpyfBMzl95hz2LYvy4Jmrg~JCuKNcRtnig5p-DgpUHW6OqAT49r7fFVCNN6VWwaXAE45M5jMuvXmWFmijtzSKT0lOAvKXC6couM67pAZZApoI0d3PbLYyob~69hjoTMwIyTkCL2WYP~RvPE8Gph0zu7gDVHdEWxg7-VI_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout
`

**Comment by thaJeztah** [comment]
@spoonysnail you mentioned you're using Docker for Mac (https://www.docker.com/products/docker#/mac), but the `docker info` output is from a very old version of Docker on boot2docker; could it be you still had Docker Toolbox installed as well?

**Comment by spoonysnail** [comment]
@thaJeztah I used boot2docker at first. But now I'm using Docker for Mac. It's ok now~ Thank you.

**Comment by thaJeztah** [comment]
Let me close this issue then; good to hear it's resolved!
