### ISSUE TITLE
docker info should support --format

### ISSUE THREAD

**Issue by ndeloof** [docker/docker#26976]
Many docker command do support `--format` flag to pass a go template so one can filter the actual data on output. This is very efficient for shell/tooling integration as one can just dump the exact data to get consumed, and avoid doing some crappy output parsing.

`docker info` doesn't have this option :'( 
My use case is to detect if swarm mode is enable, vs docker-swarm, and change commands  accordingly to use `docker service`. I'd like to run `docker info -f {{.Swarm}}`

**Comment by AkihiroSuda** [comment]
it will be in 1.13
https://github.com/docker/docker/pull/23808

**Comment by ndeloof** [comment]
awesome !
