### ISSUE TITLE
Swarm mode container can't resolve other swarm services after being restarted

### ISSUE THREAD

**Issue by a-robinson** [docker/docker#26993]
**Description**

We're putting together instructions for running CockroachDB on Swarm, which essentially involves creating three different services with the same image but slightly different parameters (see #26826 for more detail). Towards the end of this process, we started testing killing containers and ensuring that things continued operating correctly. However, we found that after gracefully stopping one of the containers, when it gets restarted it is unable to resolve the other two services by DNS name, which breaks its ability to start back up properly.

**Steps to reproduce the issue:**

1. docker network create --driver overlay cockroachdb
2. Start up three cockroachdb services in a three node swarm cluster so that they'll end up on different machines:
  * docker service create --replicas 1 --name cockroachdb-0 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-0,target=/cockroach/cockroach-data,volume-driver=local --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure
  * docker service create --replicas 1 --name cockroachdb-1 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-1,target=/cockroach/cockroach-data,volume-driver=local --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure --join cockroachdb-0:26257
  * docker service create --replicas 1 --name cockroachdb-2 --network cockroachdb --label app=cockroachdb --mount type=volume,source=cockroachdb-2,target=/cockroach/cockroach-data,volume-driver=local --stop-grace-period 60s cockroachdb/cockroach:latest start --logtostderr --insecure --join cockroachdb-0:26257
3. Kill the cockroachdb-1 container by SSH'ing to the machine it's on, getting its container ID, and running `docker exec -it $CONTAINER_ID ./cockroach quit`. This allows the process to gracefully shut down.

**Describe the results you received:**

Shortly afterwards, the process should have exited 0 and a new container been started up in its place. This new container is unable to resolve the services cockroachdb-0 and cockroachdb-2, as can be confirmed by exec-ing into the container and running nslookup. It is still able to resolve cockroachdb-1, its own service.

The containers that haven't been recreated can resolve all three services just fine.

**Describe the results you expected:**

I would expect the container to be able to resolve the same services after being restarted as it could before.

**Additional information you deem important (e.g. issue happens only occasionally):**

If you need a tighter repro case, let me know, but this seems like the sort of thing you may already be aware of or that we might just be misunderstanding in some way.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
root@instance-2:/home/alex# docker info
Containers: 3
 Running: 1
 Paused: 0
 Stopped: 2
Images: 2
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 11
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 1zsawb5djuhiciibstpepmu9u
 Is Manager: false
 Node Address: 10.142.0.3
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.625 GiB
Name: instance-2
ID: NLON:CSCV:X6XR:VY6Y:STA3:5N6R:DSSH:OYO6:25HU:RUXE:SHKO:S5L4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running on GCE VMs.

cc @jseldess

**Comment by a-robinson** [comment]
Also, for what it's worth, I diff'ed the `docker inspect` output o the two containers and didn't see anything interesting:

```
<         "Id": "dae9209b3bf9c52898ad46519f9cef328b268f92eaa25952edf2aec90978af6c",
<         "Created": "2016-09-26T17:26:29.870036751Z",
---
>         "Id": "bf7eebb73d7a6a3a6dac982748fe6e2fb28de670a3b7f564431473154984eb4b",
>         "Created": "2016-09-26T17:30:10.350514056Z",
14,15c14,15
<             "Status": "exited",
<             "Running": false,
---
>             "Status": "running",
>             "Running": true,
20c20
<             "Pid": 0,
---
>             "Pid": 7906,
23,24c23,24
<             "StartedAt": "2016-09-26T17:26:30.344761151Z",
<             "FinishedAt": "2016-09-26T17:30:09.763020321Z"
---
>             "StartedAt": "2016-09-26T17:30:15.409992835Z",
>             "FinishedAt": "0001-01-01T00:00:00Z"
27,31c27,31
<         "ResolvConfPath": "/var/lib/docker/containers/dae9209b3bf9c52898ad46519f9cef328b268f92eaa25952edf2aec90978af6c/resolv.conf",
<         "HostnamePath": "/var/lib/docker/containers/dae9209b3bf9c52898ad46519f9cef328b268f92eaa25952edf2aec90978af6c/hostname",
<         "HostsPath": "/var/lib/docker/containers/dae9209b3bf9c52898ad46519f9cef328b268f92eaa25952edf2aec90978af6c/hosts",
<         "LogPath": "/var/lib/docker/containers/dae9209b3bf9c52898ad46519f9cef328b268f92eaa25952edf2aec90978af6c/dae9209b3bf9c52898ad46519f9cef328b268f92eaa25952edf2aec90978af6
c-json.log",
<         "Name": "/cockroachdb-2.1.5z8uglt27qzv8lmedb7jcogjj",
---
>         "ResolvConfPath": "/var/lib/docker/containers/bf7eebb73d7a6a3a6dac982748fe6e2fb28de670a3b7f564431473154984eb4b/resolv.conf",
>         "HostnamePath": "/var/lib/docker/containers/bf7eebb73d7a6a3a6dac982748fe6e2fb28de670a3b7f564431473154984eb4b/hostname",
>         "HostsPath": "/var/lib/docker/containers/bf7eebb73d7a6a3a6dac982748fe6e2fb28de670a3b7f564431473154984eb4b/hosts",
>         "LogPath": "/var/lib/docker/containers/bf7eebb73d7a6a3a6dac982748fe6e2fb28de670a3b7f564431473154984eb4b/bf7eebb73d7a6a3a6dac982748fe6e2fb28de670a3b7f564431473154984eb4
b-json.log",
>         "Name": "/cockroachdb-2.1.7jrfpws5unad0jhfgd29c4u75",
37c37,39
<         "ExecIDs": null,
---
>         "ExecIDs": [
>             "9c2685922a27b6614a7543f4c7645531b7a5a80e3ba439724d38615867169f7d"
>         ],
124c126
<             "Hostname": "dae9209b3bf9",
---
>             "Hostname": "bf7eebb73d7a",
159c161
<                 "com.docker.swarm.task.id": "5z8uglt27qzv8lmedb7jcogjj",
---
>                 "com.docker.swarm.task.id": "7jrfpws5unad0jhfgd29c4u75",
165c167
<             "SandboxID": "fd0fb6b972f557b5e5c8a6f745c056fb637349e191804969f9b688e31853ea8e",
---
>             "SandboxID": "e44d782df8842d503c43b51cf97451100ceae0509c640a5c67b4b0a9a22a8ca3",
169,170c171,175
<             "Ports": null,
<             "SandboxKey": "/var/run/docker/netns/fd0fb6b972f5",
---
>             "Ports": {
>                 "26257/tcp": null,
>                 "8080/tcp": null
>             },
>             "SandboxKey": "/var/run/docker/netns/e44d782df884",
188c193
<                         "dae9209b3bf9"
---
>                         "bf7eebb73d7a"
191c196
<                     "EndpointID": "",
---
>                     "EndpointID": "e878f16f3e41e30b3415610282bf31af6d2dfcaa9fc9d722391407f16461c4d5",
193,194c198,199
<                     "IPAddress": "",
<                     "IPPrefixLen": 0,
---
>                     "IPAddress": "10.0.0.7",
>                     "IPPrefixLen": 24,
198c203
<                     "MacAddress": ""
---
>                     "MacAddress": "02:42:0a:00:00:07"
```

**Comment by thaJeztah** [comment]
If this is a test setup; we just released a release-candidate for docker 1.12.2 for testing, which contains a number of fixes in networking in Swarm mode; it may be worth testing if your issue is resolved https://github.com/docker/docker/releases/tag/v1.12.2-rc1

/cc @mrjana

**Comment by a-robinson** [comment]
I don't know how conclusive of evidence it is, but I tried having containers exit a couple times while running on 1.12.2-rc1 and the new ones were indeed all able to resolve the other services each time.

**Comment by BlaM** [comment]
Is it possible to install 1.12.2-rc1 via Debian repository so that I don't have to figure out how to build it myself? I seem to be hitting the same issues.

**Comment by thaJeztah** [comment]
@BlaM yes (again; if it's a test setup); you can use

    curl -fsSL https://test.docker.com | sh

Which will switch apt to use the "testing" repository, and install docker from that. Once 1.12.2 is released, you should switch back to the "main" repository

**Comment by bartoszx** [comment]
I had exactly same problem and test version solved it on ubunt 16.04
Thanks

**Comment by mrjana** [comment]
Looks like this is solved in 1.12.2-rc so can we close this?

**Comment by thaJeztah** [comment]
I'll go ahead and close this, but feel free to comment if you still have this issue on 1.12.2

**Comment by BlaM** [comment]
Just to make sure I understand the concept correctly:

    master# docker swarm init --advertise-addr 192.168.99.1

    worker# docker swarm join ... token ... 192.168.99.1:2377

    master# docker node ls
    ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
    6wprcel2dn3i0full7yu3uq3r *  docker01  Ready   Active        Leader
    ez031cmkkt25s3q80h6a2gynx    docker02  Ready   Active

    master# docker service create --replicas 1 --name rabbitmq  --publish 15672:15672 --publish 15671:15671 vincent:5555/rabbitmq:latest

    ... starts rabbitmq on any server - master in my case ...

    master# docker ps
    CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                                                 NAMES
    1643549c0a4d        vincent:5555/rabbitmq:latest   "/docker-entrypoint.s"   2 minutes ago       Up 2 minutes        4369/tcp, 5671-5672/tcp, 15671-15672/tcp, 25672/tcp   rabbitmq.1.4raf26wotk6irnf1kvr1zmxrt

I should now see a hostname "rabbitmq" in all containers that I start, correct? 

* When I tried with version 1.2.1 containers running on master (i.e. same host rabbitmq was running on) were able to see "rabbitmq" and connected to it. Containers on other hosts did not see that hostname.

* Now with version 1.2.2 no other container can see the hostname. It does not matter if the container is running on the same host or on another host in the swarm

Here is what I was able to figure out:

    master# docker service create --replicas 2 --name redirector --publish 1080:80 vincent:5555/redirector:latest

    master# docker service ps redirector
    ID                         NAME              IMAGE                           NODE      DESIRED STATE  CURRENT STATE                   ERROR
    5cn3oi777x9tbtkozu53aasrp  redirector.1      vincent:5555/redirector:latest  docker02  Running        Running less than a second ago
    bwudrbolly9s4nrnfavmuwbpy   \_ redirector.1  vincent:5555/redirector:latest  docker02  Shutdown       Failed 6 seconds ago            "task: non-zero exit (8)"
    945a8biawo1y98gsk0zreq8jb   \_ redirector.1  vincent:5555/redirector:latest  docker02  Shutdown       Failed 14 seconds ago           "task: non-zero exit (8)"
    7pd061o0a1upwi3k8j7ilbqje   \_ redirector.1  vincent:5555/redirector:latest  docker02  Shutdown       Failed 21 seconds ago           "task: non-zero exit (8)"
    ac4ny998yh3tlu73wlbtcv34i   \_ redirector.1  vincent:5555/redirector:latest  docker02  Shutdown       Failed 29 seconds ago           "task: non-zero exit (8)"
    02so48kbhrf7vvhcyu94p6i3b  redirector.2      vincent:5555/redirector:latest  docker01  Ready          Ready 1 seconds ago
    01nkkkl04j8gn8sipfj3ui3sk   \_ redirector.2  vincent:5555/redirector:latest  docker01  Shutdown       Failed 1 seconds ago            "task: non-zero exit (8)"
    dvbtpxejlu5tjkmfz8vweg9l0   \_ redirector.2  vincent:5555/redirector:latest  docker01  Shutdown       Failed 9 seconds ago            "task: non-zero exit (8)"
    2swk7vdf1g08t7x0jz9yalvl3   \_ redirector.2  vincent:5555/redirector:latest  docker01  Shutdown       Failed 16 seconds ago           "task: non-zero exit (8)"
    8br23ej2lzmuyubyo0rbsbtia   \_ redirector.2  vincent:5555/redirector:latest  docker01  Shutdown       Failed 23 seconds ago           "task: non-zero exit (8)"

    master# docker logs 7493dc0f2515
    error:  code=ENOTFOUND, errno=ENOTFOUND, syscall=getaddrinfo

    /usr/src/app/app/index.js:681
                throw err;
                      ^
    Error: getaddrinfo ENOTFOUND
        at errnoException (dns.js:37:11)
        at Object.onanswer [as oncomplete] (dns.js:126:16)

I'm not quite sure how to go on from there. How do I debug this?

**Comment by thaJeztah** [comment]
@BlaM have you tried creating a custom network for your service? Service discovery only works for services on the same network (by default services are isolated);

```bash
$ docker network create -d overlay foobarnet
e8t8snrv5hbljbse0t94xod74

$ docker service create --name=foobar --network=foobarnet --publish=8080:80 --replicas=2 nginx:alpine
8x9s7qb1cv7t13edzp4wfxk2p

$ docker service ps foobar
ID                         NAME          IMAGE         NODE           DESIRED STATE  CURRENT STATE           ERROR
0zd7eethkvtvlqpiaa3on8b0k  foobar.1      nginx:alpine  swarm-test-04  Running        Running 1 seconds ago
3i12j6h7om6heurxexrnz6a2v  foobar.2      nginx:alpine  swarm-test-03  Running        Running 1 seconds ago

Opening a session on node 4;

$ docker exec -it foobar.1.0zd7eethkvtvlqpiaa3on8b0k sh
/ # apk add --no-cache curl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20160104-r4)
(2/4) Installing libssh2 (1.7.0-r0)
(3/4) Installing libcurl (7.50.3-r0)
(4/4) Installing curl (7.50.3-r0)
Executing busybox-1.24.2-r11.trigger
Executing ca-certificates-20160104-r4.trigger
OK: 55 MiB in 28 packages
/ # curl foobar
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
/ #
```

**Comment by BlaM** [comment]
Thank you. Of course I did not try that - and it fixed my issues.

I once tried to use --network=ingress, but it told me that I wasn't supposed to do that. Based on that I guess I kind of just assumed that it would automatically know what I want to do.

I've seen and read the page in the manual (https://docs.docker.com/engine/swarm/networking/), but it seems I misinterpreted it a little - so I suggest to add a little fix/additional hint to help people like me:

The manual already says that Docker supports overlay networks and if you use overlay networks you can use service discovery by hostname. Then it goes on to tell you that (and how) you CAN create a network. BUT: I suggest to add a note that you MUST create your own overlay network. My mistake was that I did not add my own network, but went to my docker master and just entered `docker network ls` - and there already was an overlay network (ingress). So I kind of just assumed that that was the default one.

**Comment by thaJeztah** [comment]
@BlaM yes, I think there's room for improvements there; could you open an issue in the documentation repository (or perhaps you're interested in opening a pull request?) the repository can be found here; https://github.com/docker/docker.github.io

**Comment by sanimej** [comment]
@thaJeztah @blam Yes, the documentation wasn't very explicit about the purpose of the `ingress` network. Updated the wording; https://github.com/docker/docker/pull/27290
