### ISSUE TITLE
/etc/default/docker file is missing in SLES12

### ISSUE THREAD

**Issue by Saravana9210** [docker/docker#27004]
**Description**
I just downloaded docker 1.12.1 build and wondering where to find the config file for docker.

**Steps to reproduce the issue:**
1. Download docker 1.12.1 build 
    wget **https://experimental.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz**
2. Extract it using 'tar -zxvf docker-1.12.1.tgz'
3. Copy all binaries(docker, docker-containerd, docker-containerd-ctr, docker-containerd-shim, docker-proxy, docker-runc, dockerd) from ./docker/ directory to /usr/bin/ and /usr/local/bin
4. Start docker daemon by '**_dockerd_**' command or '**_docker daemon_**' command

**Describe the results you received:**
1. Docker engine started successfully

**Describe the results you expected:**
1. I'm just wondering which config file the daemon used to start
2. I don't have any option to define '**DOCKER_OPTS**' in this scenario
 
**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using **SLES12 VM**.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 24
Server Version: 1.12.1
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: active
 NodeID: 0qudwynvpvzmxbrbfeskwp59a
 Is Manager: true
 ClusterID: 1rjr5qgmgypzqzwoeunl2nlt6
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 164.99.87.161
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 3.12.28-4-default
Operating System: SUSE Linux Enterprise Server 12
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.763 GiB
Name: diego-master
ID: KOIF:WXD2:BRTI:TNCL:JSXW:BPBY:N6ML:F7MS:NCCQ:2ANH:RHZG:Y736
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: saravana9210
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
`/etc/default/docker` is specific to Upstart, which was reading this file in.
The tarball does not include init scripts or anything like that, only distro packages do.
The best way to configure the daemon is to use `/etc/docker/daemon.json`, which is documented here: https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

Closing since this is not really an issue.

**Comment by Saravana9210** [comment]
Hi Brian,

Thank you for your information!

But, I could not fond /etc/docker/daemon.json either. There is only one file 'key.json' under /etc/docker/ directory. I'm still wondering which config file docker daemon uses to start. If I'm creating this file (daemon.json) manually, how should I instruct the docker daemon to make use of it. Please guide me to a appropriate link if possible.

Thanks in advance !

**Comment by cpuguy83** [comment]
@Saravana9210 Just read the docs and make the file.
Docker does not provide a default configuration in there (nor could it with the tarball you).

**Comment by Saravana9210** [comment]
Thanks Brian, got it :)
