### ISSUE TITLE
Docker daemon cannot get out of exit tty terminal

### ISSUE THREAD

**Issue by sburnwal** [docker/docker#27008]
I am facing a strange issue (using docker 1.9.1 on RHEL 7.1).
I login to the host using ssh and as root user I start the docker daemon using the command. This command works fine.

`docker daemon --bip=169.254.0.254/24 --fixed-cidr=169.254.0.0/24 --exec-root=/opt/docker/execroot --graph=/opt/docker/graph >> /var/log/docker.log 2>&1 &`

I get to see this process (process has no tty terminal)
`root      6407     1  0 00:33 ?    00:00:01 /bin/docker daemon -D --exec-root=/opt/docker/execroot --graph=/opt/docker/graph`

However, sometimes I need to start this using the same above command over a console (serial console) but that leaves the docker process with a terminal

`root      6407     1  0 00:33 **ttyS0**    00:00:01 /bin/docker daemon -D --exec-root=/opt/docker/execroot --graph=/opt/docker/graph`

Because of this, docker daemon never comes out of the terminal. I tried using nohup as well but no luck. Is this a known issue ? How can I get over this ? I start any process using the same command but unlike docker that does not end up with a tty terminal.

Appreciate respone, thanks.

**Comment by cpuguy83** [comment]
@sburnwal I'm not sure I understand the problem.

You want Docker to start as a background process? You'll need to use `&` on the end of the command.... still logs will go to the terminal, though.

**Comment by thaJeztah** [comment]
> and as root user I start the docker daemon using the command.

The regular way to start the daemon (other than for debugging purposes), is through the init system. For RHEL 7.1, this is `systemd`, and you can start it by running;

    sudo systemctl start docker

If you need to make additional configuration of daemon options (like the `--bip`, and `--fixed-cidr` options), you can either use a systemd drop-in file https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options

Or (in recent versions of docker) a daemon.json configuration file (which is more flexible, as it allows you to changes some configuration options without restarting the daemon); https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

**Comment by sburnwal** [comment]
I will try to use the systemd or systemctl commands but in the past when I tried, I was not able to send the docker daemon logs to my log file like /var/log/docker.log. Is there a way to log to a specific file rather than relying on something like journalctl ?

**Comment by sburnwal** [comment]
I tried starting the docker daemon with the command 'systemctl start docker' and it starts fine but it is still stuck on the console and unable to come out of it.

@cpuguy83 yes I did use & when using the 'docker dameon ...' command to start it but no luck yet.

What shall I do next ?

**Comment by cpuguy83** [comment]
@sburnwal I'm still not sure what you mean.

Docker sends logs to stderr and stays in the foreground unless you tell the shell to background it.
If you want docker to log to a file (or no logs) you need to do a shell redirect for stderr to the file you want (or /dev/null).

I'm going to close this because it doesn't look like a Docker issue, but feel free to keep discussing here.

**Comment by sburnwal** [comment]
I have found that instead of using 'docker daemon ...' to start the daemon, if I use the approach of systemctl start docker - terminal is not locked. I am fine for this issue to be closed.
