### ISSUE TITLE
docker pull fedora/apache

### ISSUE THREAD

**Issue by gl328518397** [docker/docker#27013]
docker pull fedora/apache

Using default tag: latest
Trying to pull repository docker.io/fedora/apache ... 
Pulling repository docker.io/fedora/apache
Error while pulling image: Get https://index.docker.io/v1/repositories/fedora/apache/images: dial tcp: lookup index.docker.io: no such host
Error while pulling image: Get https://index.docker.io/v1/repositories/fedora/apache/images: dial tcp: lookup index.docker.io: no such host

**Comment by gl328518397** [comment]
在虚拟机上执行了 docker pull fedora/apache 报了上面的错，之前是好的，后来装过一次kubernetes 的proxy,不知道是什么原因，求助大神。

**Comment by thaJeztah** [comment]
Google translate;

> In the virtual machine on the implementation of the docker pull fedora / apache reported the above error, before the good, and later installed a kubernetes proxy, do not know why, help the Great God.

**Comment by thaJeztah** [comment]
@gl328518397 this could be something in your setup, or (assuming you are behind the Great Firewall), if access to Docker Hub is blocked. Did this work without problems before you installed the Kubernetes proxy?

Could you also provide a bit more info about your setup;

- the output of `docker version`
- the output of `docker info`
- the DNS servers you use
- if you're using a proxy server

**Comment by dattatrayakumbhar04** [comment]
This usually happened in my case when nameserver is not valid.
Solution which worked for me : 
add 'nameserver <Valid IP>' in /etc/resolve.conf
e.g, nameserver 8.8.8.8 
I was also able to nslookup "index.docker.io" after adding above.

**Comment by thaJeztah** [comment]
I'm closing this issue because we don't have enough information to go on, but feel free to provide additional information

**Comment by gl328518397** [comment]
多谢，虚拟机中的/etc/resolve.conf文件中之前只有一条nameserver 192.168.48.2

后来我加了两条
 nameserver 223.5.5.5
nameserver 223.6.6.6

现在可以正常的拉镜像了，但是也很慢。
