### ISSUE TITLE
Building on aarch64 get's stuck at "Step 3/13 : RUN mkdir -p /go/src /go/bin /go/pkg" when running "make dep"

### ISSUE THREAD

**Issue by demaniak** [docker/docker#27015]
**Description**
Attempting to build docker master (currently commit 601004e1a714d77d3a43e957b8ae8adbc867b280) on an odroid C2 (aarch64).

It seems the binaries are created OK, but the `make deb` target gets stuck at `Step 3/13 : RUN mkdir -p /go/src /go/bin /go/pkg`. 
At time of writing it has been sitting there for approx 12 hours.
So I think safe to say it's hung.

CPU use is 100%, with process `docker-container`.
`ps ax | grep docker` shows docker-container as defunct: `13324 ?        Zl   680:20 [docker-containe] <defunct>`

**Steps to reproduce the issue:**
1.git clone git@github.com:docker/docker.git
2. git checkout 601004e1a714d77d3a43e957b8ae8adbc867b280
3. make binary
4. make deb

**Describe the results you received:**
After step 4, process hangs at 
```
Step 3/13 : RUN mkdir -p /go/src /go/bin /go/pkg                                                                                                                                             
--- Running in a4551dd1818b
```

**Describe the results you expected:**
Correct build process termination, with installable debian packages produced and placed under the bundles folder 

**Additional information you deem important (e.g. issue happens only occasionally):**
- issues occurs with v1.12.1 tag also (if manually fix the manpages issue for aarch64)
- a 4Gb swap file is supplied and enabled on an external usb drive (without the binary builds fail with OutOfMemory)
- docker root has been relocated to the external USB hdd (via `-g` option in `/etc/default/docker`) (only have a 8Gb SDCard in odroid at this time). Issue occurred before the relocation also.
- kernel version: `uname -r`  : 3.14.77-81

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/arm64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   b9f10c9
 Built:        Thu, 16 Jun 2016 21:17:51 +1200
 OS/Arch:      linux/arm64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 39
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /extswap/docker/aufs
 Backing Filesystem: extfs
 Dirs: 99
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.14.77-81
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: aarch64
CPUs: 4
Total Memory: 1.677 GiB
Name: rat2
ID: C4B6:EOWF:VKN5:M7Q6:C2WJ:2OOB:MBHE:IXF5:7X2F:HCRO:EG35:EQAR
Docker Root Dir: /extswap/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- [odroid C2](http://www.hardkernel.com/main/products/prdt_info.php) with [minimal image](http://odroid.in/ubuntu_16.04lts/ubuntu64-16.04-minimal-odroid-c2-20160815.img.xz) supplied by hardkernel

**Comment by thaJeztah** [comment]
AFAIK, we currently have no support for building debs for aarch64. Running `make deb` will scan the contrib/builder directory for what kind of debs to build (see https://github.com/docker/docker/blob/master/hack/make/build-deb#L40), and build those debs in containers. However, there's currently no aarch64 directory there; https://github.com/docker/docker/tree/master/contrib/builder/deb

**Comment by demaniak** [comment]
Thank you @thaJeztah , that would explain it then.

Question of protocol then - do I close this issue, keep it open, close it and create a new one for "aarch64 deb building support"?

Thanks again.

**Comment by thaJeztah** [comment]
I think it would be best to open a feature request for aarch64 deb support. Perhaps (since you have the hardware to test), you could try creating the required Dockerfiles locally (in the contrib/builder directory), and open a PR.

Ideally, the Dockerfiles should be generated by a script (see for example, the scripts in this directory https://github.com/docker/docker/tree/master/contrib/builder/deb/ppc64le), to make it easier to keep them in sync / update.

Let me close this issue

**Comment by demaniak** [comment]
Awesome sauce @thaJeztah sir, I will give that...uh...a bash...

**Comment by thaJeztah** [comment]
:joy: cool 👍
