### ISSUE TITLE
Cannot pull 'microsoft/nanoserver', 'microsoft/windowsservercore' or derived images

### ISSUE THREAD

**Issue by thomaslazar** [docker/docker#27019]
Tried following the examples from [here](http://blog.alexellis.io/run-iis-asp-net-on-windows-10-with-docker/) and [here](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10?f=255&MSPPError=-2147217396) and the docker client can't download the fs layer for said images. Keeps retrying until it gives up on it. 

**Steps to reproduce the issue:**
1. `docker pull microsoft/windowsservercore`
2. `docker pull microsoft/nanoserver`

**Describe the results you received:**
```
PS C:\Users\ich> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver

5496abde368a: Retrying in 4 seconds
PS C:\Users\ich> docker pull microsoft/windowsservercore
Using default tag: latest
latest: Pulling from microsoft/windowsservercore

9c7f9c7d9bc2: Retrying in 8 seconds
PS C:\Users\ich> docker pull microsoft/windowsservercore:TP5
TP5: Pulling from microsoft/windowsservercore

1239394e5a8a: Retrying in 3 seconds
PS C:\Users\ich> docker pull microsoft/windowsservercore:10.0.14300.1030
10.0.14300.1030: Pulling from microsoft/windowsservercore

1239394e5a8a: Retrying in 3 seconds
PS C:\Users\ich> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver

5496abde368a: Retrying in 4 seconds
PS C:\Users\ich> docker pull microsoft/nanoserver:TP5
TP5: Pulling from microsoft/nanoserver

cf62dbf6d334: Retrying in 3 seconds
PS C:\Users\ich> docker pull microsoft/nanoserver:10.0.14300.1030
10.0.14300.1030: Pulling from microsoft/nanoserver

cf62dbf6d334: Retrying in 9 seconds
PS C:\Users\ich> docker pull nginx
Using default tag: latest
latest: Pulling from library/nginx

6a5a5368e0c2: Downloading [=========>                                         ] 9.435 MB/51.35 MB
4aceccff346f: Downloading [=============================>                     ] 11.71 MB/20.09 MB
c8967f302193: Download complete
PS C:\Users\ich>
```

**Describe the results you expected:**
Expected it to download. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Is also not working on Docker for Mac. And yes i know those images wouldn't work there anyways.

Used the stable and beta version of docker for windows. 

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.92 GiB
Name: moby
ID: TMER:BLKA:QLGR:5VU5:B2F3:XJHA:6KWG:623Z:NI5S:DXTX:YCJ2:SIVO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
ping @friism 

I don't think 1.12.x is expected to work with this.

**Comment by thomaslazar** [comment]
Using the version found "here"(https://master.dockerproject.org/windows/amd64/docker-1.13.0-dev.zip), as mentioned in the microsoft msdn article, works. 

I guess this issue can be closed then. 

Still just makes me curious why it isn't able to pull the image.

**Comment by cpuguy83** [comment]
@thomaslazar The image is taking advantage of a new feature in the engine not in 1.12 where the base layer is not actually hosted on docker hub.

**Comment by thomaslazar** [comment]
@cpuguy83 ok. makes sense. 
is it worth opening up an issue for 1.12 to have it fail with a meaningful error message instead of just "trying" repeatedly to DL it and then just giving up after a while? or is 1.13 scheduled to be released soon-ish so it isn't worth the effort?

**Comment by alexellis** [comment]
The info about Docker for Windows beta was from @StefanScherer - Stefan.. maybe only 1.13 works?

**Comment by cpuguy83** [comment]
Maybe better documentation?
Honestly I'm not sure where this information or links to download lives.

**Comment by easysun** [comment]
A simple way to pull 'microsoft/nanoserver'. You can install the docker for windows[beta] 
[https://download.docker.com/win/beta/InstallDocker.msi](url)
There is an experimental feature **'Switch to Windows containers...'**
Just right click on docker icon in system tray and choose it. waiting some time for switching.
Eventually, your docker will be able to pull nanoserver.

Enjoy it 👍

**Comment by alexellis** [comment]
From what I can tell so far -

Windows Server Core on Windows 10 needs 1.13-dev

That means removing 1.12-cs completely.

I've updated the link here: 

http://blog.alexellis.io/run-iis-asp-net-on-windows-10-with-docker/

**Comment by sidshetye** [comment]
@alexellis : Do you have working instructions on getting rid of 1.12 and installing 1.13? The tools seem a bit picky at this early stage, so would like to follow what worked for you. Seems that manually installing 1.13 per MSDN required running docker inside an admin privileged powershell window, right? Thanks

**Comment by StefanScherer** [comment]
@sidshetye To allow local users access to the docker service you can create a group, eg `docker`

See my automated steps in line 24+25 of this Windows 10 [Vagrantfile](https://github.com/StefanScherer/docker-windows-box/blob/master/windows10/Vagrantfile#L24-L25).
1. [Add docker group](https://github.com/StefanScherer/docker-windows-box/blob/cc75b1a3439b272094a09faf7221c28a84fd29a9/windows10/scripts/add-docker-group.ps1) and put your user into that group (replace "vagrant" with your user name) 
2. [Install docker service](https://github.com/StefanScherer/docker-windows-box/blob/cc75b1a3439b272094a09faf7221c28a84fd29a9/windows10/scripts/install-docker.ps1#L11) with an additional argument for that docker group ( `-G docker` )
