### ISSUE TITLE
Docker inspect incorrectly shows the environment variable injected in the container

### ISSUE THREAD

**Issue by soanni** [docker/docker#27021]
Hello, Docker Team.

Docker inspect incorrectly shows environment variable with ampersand (&).

**Steps to reproduce the issue:**
1. docker run -ti --env TEST_ENV="soanni&rtr" alpine:latest sh
2. docker inspect <container_id>
3. Screenshot is attached

**Output of `docker version`:**

Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 51
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-202:2-8828904-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.301 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.405 GB
 Metadata Space Used: 9.22 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.405 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.7 MiB
Name: ip-172-31-25-213.us-west-2.compute.internal
ID: RZKH:EXW3:V7DY:HOFH:Y7BK:YMSK:OEML:AD3H:FZDO:WC2F:7GPC:BMCE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS AMI Linux

![image](https://cloud.githubusercontent.com/assets/5715840/18952955/2c1ab79a-865d-11e6-9fa2-e2fbab8878a4.png)

**Comment by thaJeztah** [comment]
I think this is the way non-ascii characters are encoded in JSON (also see http://stackoverflow.com/questions/12702249/json-converts-in-a-string-to-u0026), as explained there, it's not _needed_, but not _wrong_ either

**Comment by soanni** [comment]
yeah, i saw this thread earlier. The var itself injected correctly and inside the container it has a correct value.
Ideally would be great to see the correct value inside 'inspect'.
Thank you.

**Comment by yongtang** [comment]
The escape could be disabled in golang with `SetEscapeHTML`. Just created a PR #27060 for that.
