### ISSUE TITLE
enhance docker service output formatting

### ISSUE THREAD

**Issue by nicolaka** [docker/docker#27034]
**Description**

Some columns in docker service ps and docker service ls get truncated preventing users from seeing full field values. Adding proper formating with --no-trunc option will be useful. It will also be useful to support adding formatting config for docker service in config.json file. (similar to 	"imagesFormat"  for docker images) 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by allencloud** [comment]
I guess that you are trying docker 1.12.1 or lower. Right ? @nicolaka 
Is it already in https://github.com/docker/docker/pull/25337 ?
And this PR is merged in docker/master.

**Comment by nicolaka** [comment]
@allencloud yep that seems to solve it so closing this issue.
