### ISSUE TITLE
Cannot use quotes in label values (1.12)

### ISSUE THREAD

**Issue by berndtj** [docker/docker#27047]
**Description**

Cannot use the --label arg to the `docker build` command to add labels with double-quotes in them.

Specifying the same label in the Dockerfile works.

Additionally, the same commands appear to work in 1.11 release.

**Steps to reproduce the issue:**

```
$ docker build --label="schema.input={\"key\":\"value\"}" .
invalid argument "schema.input={\"key\":\"value\"}" for --label=schema.input={"key":"value"}: line 1, column 14: bare " in non-quoted-field
See 'docker build --help'.
```

or

```
[simple-cell ((cf5aaf0...))]$ docker build --label='schema.input={"key":"value"}' .
invalid argument "schema.input={\"key\":\"value\"}" for --label=schema.input={"key":"value"}: line 1, column 14: bare " in non-quoted-field
See 'docker build --help'.
```

**Describe the results you received:**

See the repros.  I simply get errors and cannot directly work around them.

**Describe the results you expected:**

I expect the strings to be accepted as labels.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.2-rc1, build 45bed2c, experimental
```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 466
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 312
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: LSMX:QN3I:4PLI:RL2B:AGRA:T6Y3:EQMS:6V62:WXGM:F7BR:WH5Z:AQSD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 28
 System Time: 2016-09-29T21:00:35.397311011Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
@dnephin is this a parser issue from the cli changes?

**Comment by dnephin** [comment]
Ya, we're using `StringSliceVar` for labels, which attempts to use a csv parser to find multiple strings. If we use `opts.ListOpt` it will do the right thing. I'll prepare a PR.

**Comment by yongtang** [comment]
This is similar to #26173 and https://github.com/docker/docker/pull/23309#r66296832
