### ISSUE TITLE
Install docker without internet

### ISSUE THREAD

**Issue by samerkalil** [docker/docker#27054]
i have debian operating system without internet ,please i have download and install docker  1.12.
Please Solution

**Comment by bbayani** [comment]
Hi @samerkalil, you can download the required .deb file from https://apt.dockerproject.org/repo/pool/main/d/docker-engine/ on machine which has internet access. You can then transfer (may be SCP) the downloaded package to your machine on which you want to install docker (which does not have internet access). Once you have the package there just install it with standard dpkg command.

**Comment by thaJeztah** [comment]
Looks like the question is answered; keep in mind that the GitHub issue tracker is for reporting bugs, and not intended as a general support forum. https://forums.docker.com, the #docker IRC channel, or StackOverflow are more suitable for getting support on _using_ Docker.

I'll close this issue, but feel free to continue the conversation
