### ISSUE TITLE
-v /var/log/syslog:/var/log/syslog:ro not sync between container and host after period of time.

### ISSUE THREAD

**Issue by ZhenyangZhao** [docker/docker#27053]
**Description**

I use -v /var/log/syslog:/var/log/syslog:ro to mount host syslog file.
But i found in container syslog not sync in period of time.

**Steps to reproduce the issue:**
1. docker run -v /var/log/syslog:/var/log/syslog:ro
2. period of time . contianer syslog file not sync to host syslog looks like blocked.
3. restart container it correct.but period of time it reappear.

**Describe the results you received:**
host syslog file & container syslog file both 777 permission
![image](https://cloud.githubusercontent.com/assets/7477708/18978355/0810e7b4-86f5-11e6-9587-bd28929807a9.png)

tail -f /var/log/syslog in Docker Container:
![image](https://cloud.githubusercontent.com/assets/7477708/18978879/05689940-86f9-11e6-84d2-a423bcbbbf47.png)
tail -f /var/log/syslog in Host:
![image](https://cloud.githubusercontent.com/assets/7477708/18978874/fcfc1624-86f8-11e6-9a9e-e03f0c7100d1.png)

**Describe the results you expected:**
always sync to host syslog file. not block

**Additional information you deem important (e.g. issue happens only occasionally):**cked after period of time.

**Output of `docker version`:**
docker 1.12.1
**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker in openstack vm

**Comment by justincormack** [comment]
Perhaps there is log rotation going on and the syslog file is reopened? Bind mounting a single file is very problematic for these reasons as it is the inode not the name that is mounted. You may get better results by sharing the whole of `/var/log`.

**Comment by ZhenyangZhao** [comment]
@justincormack  Thanks a lot. I will try tomorrow and  paste the result.

**Comment by ZhenyangZhao** [comment]
@justincormack Thanks a lot i have change the -v to the /var/log and it works. Thanks a lot again.
