### ISSUE TITLE
Incorrect error when using swarm-scoped network that's not in use

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#27066]
I looked into this a while back, but haven't found a good way to work around this;

With swarm mode enabled, create an overlay network (e.g. `my-multihost-network`);

```
docker network ls

NETWORK ID          NAME                   DRIVER              SCOPE
a0fae0abd843        bridge                 bridge              local
a597265888b1        docker_gwbridge        bridge              local
0d73b5c2c8bc        host                   host                local
24iv7j69gen8        ingress                overlay             swarm
1lr6ktlm1k8c        my-multihost-network   overlay             swarm
349b80d672d1        my-network             bridge              local
4c4ebfd8f8f3        none                   null                local
```

Swarm-scoped networks are _dynamically_ created, so even though the network shows up in `docker network ls`, the network isn't really there.

Because of this, trying to use a swarm-scoped network for `docker run` produces the wrong error;

```bash
$ docker run -dit --network my-multihost-network busybox

docker: Error response from daemon: network my-multihost-network not found.
```

After creating a service that uses `my-multihost-network`, the correct error is produced:

```
$ docker service create --name my-service --network my-multihost-network nginx:alpine
11iqh4apx60u1cqw720q7h6zo

$ docker run -dit --network my-multihost-network busybox

docker: Error response from daemon: swarm-scoped network (my-multihost-network) is not compatible with `docker create` or `docker run`. This network can only be used by a docker service.
See 'docker run --help'.
```

The error is produced in this part of the code;
https://github.com/docker/docker/blob/v1.12.2-rc1/daemon/container_operations.go#L350-L359

But as can be seen, if the network cannot be found (due to it not being used by a service), a "network not found" is returned, before the correct error is generated.

The difference between `docker network ls` showing the networks, but `docker run` not finding it, seems to be that `docker network ls` combines two different ways to obtain the list of networks, and merges those results;
https://github.com/docker/docker/blob/v1.12.2-rc1/api/server/router/network/network_routes.go#L29-L47

**Comment by thaJeztah** [comment]
ping @mrjana @aboch perhaps you know an easy way to check if it's a swarm-mode network if it's not in use

**Comment by aboch** [comment]
When you created the swarm network, did you specify `--attachable` ?

**Comment by thaJeztah** [comment]
@aboch no, this is on 1.12 OSS, so `--attachable` is not available yet.

**Comment by mavenugo** [comment]
@thaJeztah this has been addressed in 1.13 by the introduction of `--attachable` network and the error message is updated appropriately :

```
$ sudo docker network create -d overlay test123
66a8zm2h63ocwgrzhl956v5u6

$ sudo docker run --net=test123 busybox sh
docker: Error response from daemon: Could not attach to network test123: rpc error: code = 7 desc = network test123 not manually attachable.
```

I dont think we have to address this for 1.12 version. WDYT ?

**Comment by thaJeztah** [comment]
@mavenugo yes, I discussed this with @aboch, and fixing it for 1.12 would be big change, due to the issues mentioned; I think it's ok to keep it as a "known" issue for 1.12

**Comment by mavenugo** [comment]
@thaJeztah thanks. I will close this issue now.
