### ISSUE TITLE
Restart-condition flag should have an option "on-update"

### ISSUE THREAD

**Issue by nylon22** [docker/docker#27073]
**Description**
When creating/updating services, I believe a valid restart-condition should be "on-update". "none", "on-failure", and "any" do not work when I only want the service to restart when it is updated. 

Usefulness:

To achieve global volumes, I create a global "config" service with a volume attached to it with a restart condition of "none". I then create a replicated service that mounts the volume created by the global "config" service. When I update both services, the new volume name is reflected when I inspect both services, but because the global "config" service was never restarted on update, the changes in the volume are not reflected on the replicated service.

My current workaround is to remove and re-create the global "config" service with the new volume and update the replicated service.

**Steps to reproduce the issue:**
1. `docker service create --restart-condition "on-update"

**Describe the results you received:**

Error response from daemon: invalid RestartCondition: "on-update"

**Describe the results you expected:**

The service is created with a RestartCondition of "on-update"

**Output of `docker version`:**

-bash-4.2$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**

-bash-4.2$ docker info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 12
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-8:3-134351990-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.332 GB
 Data Space Total: 107.4 GB
 Data Space Available: 45.24 GB
 Metadata Space Used: 2.154 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: active
 NodeID: 09cnqvf34rrf8k0bzdt6mg6qw
 Is Manager: true
 ClusterID: 7b17sczyypucbhj8e4q2zr8m3
 Managers: 3
 Nodes: 5
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.82.64.53
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.703 GiB
Name: aglqpsswm01
ID: LNPV:D26H:5SFY:SWNH:WYS2:SSXO:7XPW:PKOV:NAJB:LI3P:YRIA:OHQC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by dnephin** [comment]
Services are always restarted when they are updated, so I think `on-update` would be confusing. I don't quite understand your use case.

> the changes in the volume are not reflected on the replicated service.

Any changes to the data in a volume should always be reflected immediately to all consumers of the volume. Are you changing the name of the volume or the contents? Which volume driver are you using?

**Comment by thaJeztah** [comment]
Sounds a bit like you're looking for a "batch mode" service; https://github.com/docker/docker/issues/23880

**Comment by nylon22** [comment]
@dnephin I am changing the name and the contents of the volume. My volume driver is local and my storage driver is the loop devicemapper. It seems services are only restarted when they are updated if they are already running, no?

**Comment by nylon22** [comment]
@thaJeztah Yes, I think this issue is a dupe. This comment in particular convinced me: https://github.com/docker/docker/issues/23880#issuecomment-236184953

**Comment by thaJeztah** [comment]
Thanks @nylon22, let me close this one then, so that we can have the discussion in a single place
