### ISSUE TITLE
Hyper-V nodes leave swarm when promoted or demoted

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker#27084]
When I create a bunch of nodes locally on a Windows 10 Pro machine using Docker Machine and Hyper-V, I can have a nice functioning Swarm. However, if I try to promote or demote a node they leave the swarm. They can join back in at in the new role.

**Steps to reproduce the issue:**
1. On a windows 10 pro machine follow this powershell script: https://github.com/docker/labs/blob/master/swarm-mode/beginner-tutorial/swarm-node-hyperv-setup.ps1 be sure to set it to your own local switch.
2. SSH into a manager node
3. promote one of the worker nodes or demote one of the managers

**Describe the results you received:**
promoted or demoted nodes leave the swarm.

**Describe the results you expected:**
Nodes that are promoted should be promoted, nodes that are demoted should be demoted and in neither case should they leave the swarm.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
docker@manager1:~$
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 987.2 MiB
Name: manager1
ID: SEVC:AWRL:K5VH:4TXK:BW5U:WT4N:EQFU:7HNP:HJXB:BXSC:PTA3:BIQA
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-10-01T01:17:10.762378656Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=hyperv
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Only tested on one Windows box so far, Windows 10 Pro version 1607

@tonistiigi @LK4D4 @aluzzardi

**Comment by aluzzardi** [comment]
Thanks @ManoMarks - would you be able to grab the logs of all the engines (but specifically the ones that were promoted and left the swarm)?

The root cause lies somewhere in those logs - having them will greatly help reproducing and troubleshooting the issue

**Comment by aluzzardi** [comment]
Also, by any chance, would you have the list of commands you typed after the cluster was set up through the script?

An output of `docker node ls` after each command would definitely be helpful.

**Comment by aluzzardi** [comment]
/cc @thaJeztah @vieux @icecrime 

We need to figure out what this is - no idea if it's critical enough for 1.12.2 or not.

**Comment by thaJeztah** [comment]
Let me add it to the milestone as a P1, so that we dont continue before we made that decision

**Comment by ManoMarks** [comment]
Text of running the script to create the swarm and sshing into [manager1](https://github.com/docker/docker/files/504743/manager1.txt)
Rejoining [worker2](https://github.com/docker/docker/files/504744/worker2.txt)

**Comment by aluzzardi** [comment]
Would you have the logs of worker2?

Those should contain the reason why it went down

**Comment by ManoMarks** [comment]
I can build it again and try, how do I get the logs from worker2

**Comment by tonistiigi** [comment]
I repeated the setup under linux with 1.12.1 and couldn't reproduce with multiple retries. From the last files it seems problems start before the demotion as after running `node ls` in manager1, manager3 is already unreachable for some reason.

Don't know about hyperv driver but usually you can get logs with `docker-machine ssh node cat /var/log/docker.log` . If you get the logs then please send them for all of the nodes.

**Comment by ManoMarks** [comment]
@tonistiigi I tried it multiple times, that was the only time where there a node went down before I did anything else. Might still be instructive though. I've never experienced the problem with VirtualBox driver btw, only with Hyper-V. I'm away from a Windows box for awhile so I won't be able to try it again and get logs until next week.

**Comment by thaJeztah** [comment]
ping @ManoMarks (just a friendly reminder :smile: as it's next week now)

**Comment by ManoMarks** [comment]
I wasn't able to replicate with demotion, but here's the log of a machine going down when I promote it.
[output2.txt](https://github.com/docker/docker/files/520158/output2.txt)

**Comment by ManoMarks** [comment]
Sorry I thought powershell captured the output. Here's the logfile from the worker that went down
[output3.txt](https://github.com/docker/docker/files/520179/output3.txt)

**Comment by aluzzardi** [comment]
@aaronlehmann @LK4D4 Could you take a look at the logs?

**Comment by LK4D4** [comment]
I think node can't bind its listen-addr on Hyper-V, probably Hyper-V network blocking something. I have no way to try though.

**Comment by aluzzardi** [comment]
@ManoMarks @johnstep Was it a problem with the scripts?

Is there something we could have done to make the error more obvious to spot?

**Comment by johnstep** [comment]
@aluzzardi Yes, it was a bug in the PowerShell script, not updating `$nodeip` in the loop that joins the workers to the swarm. I found it by looking at the error in the log, and then noticing that the wrong IP address was passed for `--listen-addr`.

I am not sure about making it more obvious; perhaps the `docker swarm join` command should have failed, but maybe it does not (and should not?) wait to find out. It _is_ odd that `docker node ls` reports the worker node `Ready` initially, but later it changes to `Down`, after promoting.

**Comment by ManoMarks** [comment]
I'm testing revised script now. But to be clear, all the nodes were part of the swarm. If you added a service it would spread to the node.

**Comment by ManoMarks** [comment]
@aluzzardi @johnstep Confirmed this fixed the issue. Thanks!

**Comment by thaJeztah** [comment]
> It is odd that docker node ls reports the worker node Ready initially, but later it changes to Down, after promoting.

@aluzzardi is that something to look at? ^^
