### ISSUE TITLE
Windows containers can't mount mapped drive volumes for network shares

### ISSUE THREAD

**Issue by douglaswaights** [docker/docker#27099]
Hi,

I'm using Docker for Windows 1.12.2-rc1-beta27.1 on Windows 10 anniversary addition (latest bits at the time of writing) and trying to access a mapped drive as a volume in Server Core or nanoserver windows containers.

I can mount folders from the C drive just fine in my containers using
docker run -it -v C:\somefolder:C:\availabletocontainer microsoft/nanoserver powershell

However, if i create a mapped drive to a network machine folder in the host then stop and restart the docker service i can't mount this mapped drive as a volume in the container...

For example

docker run -it -v Y:mappedfolder:C:\availabletocontainer microsoft/nanoserver powershell

fails with invalid volume specification ...bind source path doesn't exist

https://forums.docker.com/t/how-to-access-a-mapped-network-folder-or-unc-path-inside-a-windows-container/22861

Thanks
Doug

**Comment by friism** [comment]
@douglaswaights I think this is the same limitation mentioned here: https://github.com/docker/docker/issues/27100#issuecomment-251010940

**Comment by thaJeztah** [comment]
Looks like a duplicate yes. I'll go ahead and close
