### ISSUE TITLE
Error response from daemon: datastore for scope "global" is not initialized

### ISSUE THREAD

**Issue by herbrandson** [docker/docker#27098]
I am getting the following error when trying to create an overlay network on a swarm: 
`Error response from daemon: datastore for scope "global" is not initialized`

I run the following script to create a swarm

```
docker-machine create -d virtualbox local
eval "$(docker-machine env local)"
TOKEN=$(docker run swarm create)

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-master \
    --swarm-discovery token://$TOKEN \
    swarm-manager

docker-machine create \
    -d virtualbox \
    --swarm \
    --swarm-discovery token://$TOKEN \
    swarm-node-01

eval "$(docker-machine env --swarm swarm-manager)"

docker network create \
	--driver overlay \
	multi-host-network
```

The result is the following error

`Error response from daemon: Error response from daemon: datastore for scope "global" is not initialized`

Running `docker-machine ls` gives the following

```
NAME            ACTIVE      DRIVER       STATE     URL                         SWARM                    DOCKER    ERRORS
local           -           virtualbox   Running   tcp://192.168.99.100:2376                            v1.12.1   
swarm-manager   * (swarm)   virtualbox   Running   tcp://192.168.99.101:2376   swarm-manager (master)   v1.12.1   
swarm-node-01   -           virtualbox   Running   tcp://192.168.99.102:2376   swarm-manager            v1.12.1 
```

Running `docker -v` gives the following

```
Docker version 1.12.1, build 6f9534c
```

Running `docker info` gives the followng

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 2
Server Version: swarm/1.2.5
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 2
 swarm-manager: 192.168.99.101:2376
  └ ID: WRHW:3FM6:7XS6:SKRW:FVYU:B2KN:G53P:K2QJ:D6MZ:WJTU:PSDT:RFSZ
  └ Status: Healthy
  └ Containers: 2 (2 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: kernelversion=4.4.17-boot2docker, operatingsystem=Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-10-02T15:00:25Z
  └ ServerVersion: 1.12.1
 swarm-node-01: 192.168.99.102:2376
  └ ID: OHHC:62YN:TVQH:INMB:4OGY:HZRM:GVFP:5HRV:OXYE:PBTC:ULVN:ZWHD
  └ Status: Healthy
  └ Containers: 1 (1 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 1
  └ Reserved Memory: 0 B / 1.021 GiB
  └ Labels: kernelversion=4.4.17-boot2docker, operatingsystem=Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016, provider=virtualbox, storagedriver=aufs
  └ UpdatedAt: 2016-10-02T14:59:54Z
  └ ServerVersion: 1.12.1
Plugins:
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Security Options:
Kernel Version: 4.4.17-boot2docker
Operating System: linux
Architecture: amd64
CPUs: 2
Total Memory: 2.042 GiB
Name: 2135cbe8b7fe
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
```

**Comment by herbrandson** [comment]
Running `docker network ls` gives the following

```
NETWORK ID          NAME                   DRIVER              SCOPE
a2413ee050d5        swarm-manager/bridge   bridge              local               
d65ea4b919c0        swarm-manager/host     host                local               
26880aa6de54        swarm-manager/none     null                local               
0440b8b018b1        swarm-node-01/bridge   bridge              local               
464004a544bd        swarm-node-01/host     host                local               
917cc9ff66cb        swarm-node-01/none     null                local 
```

**Comment by thaJeztah** [comment]
Looks like you're running "swarm" (https://github.com/docker/swarm), not swarm _mode_ (which was introduced in docker 1.12). For swarm overlay networking, you need an external k/v store set up, otherwise overlay networking doesn't work, and you'll get this error. Read this section of the documentation https://docs.docker.com/engine/userguide/networking/get-started-overlay/#/overlay-networking-with-an-external-key-value-store

**Comment by herbrandson** [comment]
Ah, I see. This was the missing piece for me. Until your comment, I didn't understand that Swarm and Swarm Mode are separate things. Thanks!

I've done some more research with this new knowledge and found this article: https://www.infoq.com/news/2016/06/dockercon-docker-swarm. According to this link, a Swarm Mode cannot be created with docker-machine and cannot be managed with docker-compose. Am I understanding that correctly? If so, are there plans to integrate these tools at some point? If so, is there a posted timeline I can reference?

Thanks again for the help! This had me really confused.

**Comment by thaJeztah** [comment]
Yes, naming is a bit confusing :relaxed: 

> Swarm Mode cannot be created with docker-machine

You can setup the nodes with docker-machine, but to enable swarm mode and to join nodes to the swarm currently requires manual steps (`docker swarm init` for the master, and `docker swarm join` to join nodes). We _do_ want to allow this to be better automatable, but I don't have an ETA

> cannot be managed with docker-compose

That is correct; docker-compose manages individual _containers_ and doesn't create/manage swarm services. Thought behind this was (afaik) that docker-compose is primarily designed for local development, and not for actual deployment.

There is the (currently experimental, and WIP) "dab" file, that you can export from docker-compose, and that can be deployed through `docker deploy`. That file only contains the "portable" parts of your compose file. An initial roadmap on that can be found here; https://github.com/docker/docker/issues/26876

**Comment by mdaguete** [comment]
@herbrandson  the same error for me, but if you configure an external consult, and add to engine: 
    --cluster-store=consul://<consul_ip>:8500 --cluster-advertise=eth0:2375

it works.

**Comment by thaJeztah** [comment]
I'll close this issue, because I think the question was answered (and some hints provided for resolving the issue), but feel free to comment if there's still anything to be answered

**Comment by suryagaddipati** [comment]
@thaJeztah any chance of renaming swarm to 'classic swarm' . Its impossible do any sort of meaningful searches to distinguish one from the other , causing massive confusion.

**Comment by thaJeztah** [comment]
@suryagaddipati unlikely going to happen, and those decisions are out of my hand :blush: (but I can feel your pain)
