### ISSUE TITLE
Docker Remote API push and pull have different token fields

### ISSUE THREAD

**Issue by Khazrak** [docker/docker#27095]
**Description**
I noticed in the Remote API Docs that the name of the field for token-based login concerning push and pull image isn't the same.

pull calls it "registrytoken"
push calls it "identitytoken"

Both are encoded for X-Registry-Auth header. Are they different in the code?
Since they both are for auth to a registry it feels like they should be the same

**Steps to reproduce the issue:**
1. Check [https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/push-an-image-on-the-registry](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/push-an-image-on-the-registry)
2. Check [https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-an-image](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-an-image)
3. Compare the token-based login X-Registry-Auth headers

**Describe the results you received:**
The token field names are different for push and pull

**Describe the results you expected:**
That the token fields should have the same field names

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7
 Git commit:   23cf638
 Built:        Fri Aug 19 02:03:02 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-10223820-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.298 GB
 Data Space Total: 107.4 GB
 Data Space Available: 106.1 GB
 Metadata Space Used: 2.114 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135 (2016-09-26)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.5-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.49 GiB
Name: karl_rog
ID: IOCD:Y7FK:RDB6:43I7:QLCF:OBP5:LKJR:QLYD:NC6U:V7GA:ROQA:TCVE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
ping @aaronlehmann

**Comment by aaronlehmann** [comment]
Thank you for pointing this out. I believe it's an error in the document, and should be `identitytoken` in both cases. @dmcgowan do you agree?

**Comment by dmcgowan** [comment]
Correct, only the `identitytoken` should be referenced in the documents. The `registrytoken` field is deprecated by the `identitytoken` field and needs to be updated.

**Comment by milindchawre** [comment]
#dibs
