### ISSUE TITLE
Default IPv6 route missing if container added to multiple networks

### ISSUE THREAD

**Issue by peterthomassen** [docker/docker#27101]
**Description**

When a container is added to two networks, one of which is IPv6-enabled, the default IPv6 route is not added inside the container.

**Steps to reproduce the issue:**
  1. Set up two simple bridge networks:

        docker network create --subnet=172.18.0.0/24 --gateway=172.18.0.1 test4
        docker network create --subnet=172.19.0.0/24 --gateway=172.19.0.1 --ipv6 --subnet=2a01:4f8:a0:12eb:deec::/80 test6

  2. Create and run docker container with only the IPv6 network, and look at the routing table:

        $ docker create --net=test6 -it --name=test busybox
        5ee6521ec548cb7b7e4679614c0fd44795a784de6703aa3f68fdd4bad5a1b021
        $ docker start test
        test
        $ docker exec -it test /bin/sh
        / # route -A inet6
        Kernel IPv6 routing table
        Destination                                 Next Hop                                Flags Metric Ref    Use Iface
        2a01:4f8:a0:12eb:deec::/80                  ::                                      U     256    1        2 eth0    
        fe80::/64                                   ::                                      U     256    0        0 eth0    
        ::/0                                        2a01:4f8:a0:12eb:deec::1                UG    1024   0        0 eth0    
        ::/0                                        ::                                      !n    -1     1        3 lo      
        ::1/128                                     ::                                      Un    0      2        2 lo      
        2a01:4f8:a0:12eb:deec::2/128                ::                                      Un    0      1        0 lo      
        fe80::42:acff:fe13:2/128                    ::                                      Un    0      1        0 lo      
        ff00::/8                                    ::                                      U     256    1        6 eth0    
        ::/0                                        ::                                      !n    -1     1        3 lo      
        / # exit
        $ docker rm -f test
        test
        $ 

    As you can see, the default route is there (the one with the IP address in the "Next Hop" column). `ping6 google.com` works.

  3. Repeat, but add `docker network connect test4 test` before `docker start`. Output:

        $ docker exec -it test /bin/sh
        / # route -A inet6
        Kernel IPv6 routing table
        Destination                                 Next Hop                                Flags Metric Ref    Use Iface
        2a01:4f8:a0:12eb:deec::/80                  ::                                      U     256    0        0 eth1    
        fe80::/64                                   ::                                      U     256    0        0 eth0    
        fe80::/64                                   ::                                      U     256    0        0 eth1    
        ::/0                                        ::                                      !n    -1     1        1 lo      
        ::1/128                                     ::                                      Un    0      3        2 lo      
        2a01:4f8:a0:12eb:deec::2/128                ::                                      Un    0      1        0 lo      
        fe80::42:acff:fe12:2/128                    ::                                      Un    0      1        0 lo      
        fe80::42:acff:fe13:2/128                    ::                                      Un    0      1        0 lo      
        ff00::/8                                    ::                                      U     256    1        8 eth0    
        ff00::/8                                    ::                                      U     256    1        4 eth1    
        ::/0                                        ::                                      !n    -1     1        1 lo      

    As you can see, there is no default IPv6 route, and `ping6 google.com` indeed does not work.

**Describe the results you received:**
See above

**Describe the results you expected:**
Second output should contain IPv6 default route

**Output of `docker version`:**
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 265
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 241
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.736 GiB
Name: cluster.dev.desec.io
ID: BITY:LMNY:JHQD:64NW:DVT5:HUBG:BQAR:KMGI:UK53:7JUC:T7XI:YNQH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by cpuguy83** [comment]
ping @aboch

**Comment by aboch** [comment]
It is becasue of a current limitation: We do not support ipv4 and ipv6 default routes to different networks at the moment. So at any point in time, the default gw for both IPv4 and IPv6 will be provided by the same network. If more than one network can provide the external conenctivity funtionality, the first one in lexical order will be choosen. In this case it's `test4` which does not provide IPv6...

This came up before in docker/docker and docker/libnetwork, but cannot find the issues now.

libnetwork code supports an endpoint priority, where at docker network connect user could specify the `priority` of this endpoint therefore controlling which endpoint will provide the external connectivity.
But the UI does not have provide that option yet.

For now, as a workaround, you can play with the network names and have the IPv6 network's name precede the IPv4 only network name.

**Comment by peterthomassen** [comment]
@aboch The network name workaround sounds good to me. I guess once you find the previous issues, this one can be marked as a duplicate. Thanks for the explanation!

**Comment by aboch** [comment]
Thanks @peterthomassen for the feedback.
I found the existing issue: https://github.com/docker/docker/issues/20179
And the libnetwork one where this was discussed: https://github.com/docker/libnetwork/issues/1141#issuecomment-215525662

**Comment by mavenugo** [comment]
Closing the issue based on @aboch response.

**Comment by peterthomassen** [comment]
for reference, https://github.com/docker/libnetwork/pull/1609 fixes this by prioritizing the network endpoint which can provide both v4 and v6 connectivity
