### ISSUE TITLE
iptables=false flag stopped working for DOCKER_OPTS 

### ISSUE THREAD

**Issue by or-shachar** [docker/docker#27115]
**Description**
I installed docker [version 1.12.1, build 23cf638] on Ubuntu 16.04 that had UFW enabled.
On the `/etc/default/docker` I added the option:
```
DOCKER_OPTS="--iptables=false"
```
Yet whenever I bind ports of containers, docker would add iptables rules and expose it to anyone.

**Steps to reproduce the issue:**
1. make sure your firewall is on (`sudo ufw enable`) and that your default behavior is "deny" (`sudo ufw deny all`)
2. Add this to `/etc/default/docker` :   `DOCKER_OPTS="--iptables=false"`
3. Restart your docker daemon `sudo service docker restart`
4. Make sure iptables has not rule regarding port 8080: `sudo iptables-save | grep 8080` (nothing should be printed)
5. Start nginx container and bind port 8080: `docker run --name ng -d -p 8080:80 nginx`
6. Check again that iptables did not change the rules:  `sudo iptables-save | grep 8080`

**received result:**
Docker added iptables rules. Step 6 produced output:
```
-A DOCKER ! -i docker0 -p tcp -m tcp --dport 8080 -j DNAT --to-destination 172.17.0.2:80
```
I could reach nginx from the outside by going to my `<public-ip>:8080`

**expected results**
No rule should be added: nothing should be printed from step 6.
I must not reach nginx from the outside by going to `<public-ip>:8080`

Additional information you deem important (e.g. issue happens only occasionally):
A working workaround currently is to change this configuration on /etc/docker/deamon.json (rather than doing it in DOCKER_OPTS). That seems to be working.

**Output of `docker version`:**
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 5
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: solveit-app-002
ID: JG4E:XX65:CU26:RIC2:5L57:CESC:WRNV:6YJA:36LV:KQ6A:LOJV:ZBNU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details:**
Running in DigitalOcean cloud

**Comment by cpuguy83** [comment]
`/etc/default/docker` is a configuration file used by the upstart config.
If you have moved from upstart to systemd, this file will not be used.

It is best to configure the daemon using `/etc/docker/daemon.json`, which by default does not exist, but works on any distro.
Here's the docs: https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

Sorry for the inconvenience.
Closing since this is a non-issue.

Feel free to discuss further here if you like.

**Comment by or-shachar** [comment]
@cpuguy83 - I did not know that. That clarify everything :+1: 
docker daemon doesn't use upstart starting from ubuntu 15+

Thanks a lot!
