### ISSUE TITLE
overlay storage driver with overlayfs backing filesystem

### ISSUE THREAD

**Issue by p4l1ly** [docker/docker#27110]
**Description**

I need to use overlayed backing filesystem (see this post http://stackoverflow.com/questions/39775547/docker-is-it-possible-to-use-overlayed-backing-filesystem). Is there some way to do it or is there going to be one in future? Thank you. If there is not, please disable overlayfs backing filesystem for aufs and devicemapper storage driver, it does not work (some details are in the post mentioned above).

**Comment by cpuguy83** [comment]
This is not possible, overlay on overlay is not supported and causes issues.
The image store is already read-only, I'm not sure why you'd want to do this.

Closing since this is a non-issue, but feel free to discuss here.

**Comment by p4l1ly** [comment]
I want containers to reside in tmpfs. I don't want any writes to disk (SD card) except updating images.

**Comment by cpuguy83** [comment]
@p4l1ly Use `docker run --tmpfs /path/in/container`?

**Comment by p4l1ly** [comment]
I cannot even start the daemon:
`Error starting daemon: chmod /var/lib/docker: read-only file system`

**Comment by cpuguy83** [comment]
@p4l1ly Well yes, you need to give it a proper FS to sit on (probably ext4 or xfs for aufs/overlay/devmapper, or a dedicated btrfs/zfs.

**Comment by p4l1ly** [comment]
I have ext4, but it is read-only. I need to overlay it with some in-RAM filesystem to be able to run Docker on it.

Maybe it would be easier to imagine that you have docker images on CD and you want to run containers from them without copying them to disk because you actually don't have any disk. You cannot even copy them to tmpfs, because they are too big for your RAM. The only option that comes to my mind is to run containers in tmpfs overlayed over the read-only filesystem that is burned on the CD, so that only diffs reside in your RAM (the RAM is big enough for diffs but not for the whole image). I can imagine this is technically possible but Docker does not allow me to do it, because it refuses to work with overlay on overlay.

Maybe it is too exotic scenario for Docker and I will need to fork Docker or make my own Docker-inspired software for such purposes...

**Comment by p4l1ly** [comment]
Maybe I could have asked much more simply: Is it possible to run Docker from LiveCD?

**Comment by cpuguy83** [comment]
The issue here is that overlay-on-overlay causes problems, as does aufs-on-aufs, and any mixture of the two.
VFS would be the only thing to work here, which as you know is not going to be storage efficient.

**Comment by p4l1ly** [comment]
OK. So these problems are in Docker code or is it the overlayfs/aufs code? I suppose it is in Docker, because now I'm playing with overlayfs/aufs and I see no problems stacking and combining them. (I'd like to play around with the code and if I succeed I'd contribute)
