### ISSUE TITLE
Docker in Docker: Networking for inner containers

### ISSUE THREAD

**Issue by raphsoft** [docker/docker#27122]
Let's say I have a very restricted network where I need to use proxy env variables and custom DNS entries in /etc/resolv.conf. 

However, some of those files are encouraged not to touch. So I run a docker in docker container with custom DNS arguments as well as proxy env varaibles. Like this:
```
docker run --privileged --name my-docker -p 23123:2375 --dns x.x.x.x --dns y.y.y.y -d docker:1.8-dind
```

As I understand it will launch a dind container capable to launching inner containers. My question is: will the inner containers be able to connect to internet transparently? For instance, if I run a container with host network mode?

Q: Whay would I need such thing?
A: Well, basically, I'm testing eclipse-che. It launches "child" workspace containers in random ports and the code right now doesn't allow me to pass dns or env variables. So I was wondering if docker in docker can save me some time.

**Comment by prateekgogia** [comment]
@raphsoft You don't need host mode networking. As long as there is a docker0 bridge created in "my-docker" container, any container deployed inside "my-docker" should behave exactly like containers running on a host/ VM. You can pass in env variables, DNS and do port mapping for the containers inside "my-docker" container.

**Comment by thaJeztah** [comment]
looks like this question was answered, but feel free to continue the discussion here
