### ISSUE TITLE
Do not update /var/lib/docker/volumes/metadata.db if the volume is created by a volume plugin

### ISSUE THREAD

**Issue by ssuvasanth** [docker/docker#27129]
**Problem**
The problem arises when the data volumes are shared between multiple docker-engines using a volume plugin.
Removing a data volume created by the plugin (docker volume rm vol-name) on one of the docker-engine removes the entry for the volume in the metadata.db of that particular docker host. The removed volume entry is still present in the metadata.db of the other docker hosts which are running the other docker-engines.
This leads to a situation where a volume cannot be created again with the name same as the one deleted in one of the docker hosts which have a shared view of the volumes using the plugin. 
Other commands such as 'docker volume ls/rm/inspect' behave as expected and report that the volume is not present.

**Since, the existence of a volume is checked with the plugin for every command, I believe that it is appropriate to check with the plugin when a 'docker volume create -d plugin --name vol-name' is issued instead of just checking the metadata.db alone and concluding that the volume is created/present where the reality is different.**

It is undesirable to restart the docker daemon in other hosts to rebuild the metadata.db for every 'docker volume rm vol-name' issued against the volumes from the plugin.

**Comment by cpuguy83** [comment]
This is not caused by metadata.db. `metadata.db` is used to persist things like labels across daemon restarts.
Docker keeps an in-memory cache for a number of reasons that is not going to be easy to remove.

I believe the correct approach will be to provide a cluster-wide store (when enabled) rather than relying soley on local state.
We can also, in the short-term, improve volume creation to verify if a cached volume still exists before returning a name conflict.

**Comment by ssuvasanth** [comment]
Perfect. Both,
-- moving towards a cluster-wide store stored along with swarm 
-- and improving volume create to post a '/VolumeDriver.Get' if the driver is not local and even if the volume name is present in the cache 
are agreeable approaches.
Would you like to have a milestone for this? 
Can you share the project link which handles the volume create, so that I would give a try to improve it for this scenario and give a pull request?
Thank you very much.

**Comment by cpuguy83** [comment]
@ssuvasanth Already working on a PR to fix the short-term (Really carrying someone else's abandoned PR).
Will post when it's ready.

**Comment by ssuvasanth** [comment]
@cpuguy83 Thank you very much for your time.

**Comment by cpuguy83** [comment]
@ssuvasanth Thanks for looking at this.
Here's the PR... thought I had a bit more work to do on it, but a 1-liner fixed all my issues, so 💯 
#27164

If you could help review that would be much appreciated.
Thanks again!

**Comment by ssuvasanth** [comment]
Added a note in #27164 . Modified the condition to allow any driver to re-create the same volume name if the volume does not exist. Modifications at #27177 . Please review.

**Comment by ssuvasanth** [comment]
@cpuguy83 I have also verified the  behaviour.

**Comment by ssuvasanth** [comment]
@cpuguy83 Ahh..My bad. I didn't know that this could be done: http://stackoverflow.com/questions/9790448/how-to-update-a-pull-request .
New to git. Apologies for an extra PR. I thought I was helping your work. Sorry.

**Comment by ssuvasanth** [comment]
Carried forward to the issue #27273 with an alternate approach to the solution. Hence closing this. 
Thank you.
