### ISSUE TITLE
COPY results in stat: no such file or directory

### ISSUE THREAD

**Issue by hyperknot** [docker/docker#27133]
**Description**

**Steps to reproduce the issue:**
1. Try to build a docker file which contains the line `COPY VERSION /VERSION`, where VERSION is just a small text file, on a given Ubuntu 16.04 host
2. The build terminates 

**Describe the results you received:**
```
Step 43 : COPY VERSION /VERSION
stat /var/lib/docker/aufs/mnt/7491c79e185e2db712a88c7fa964010c08462a61bb5ca40a4595c801a55a8cc6/VERSION: no such file or directory
```

**Describe the results you expected:**
Build should have copied the file

**Additional information you deem important (e.g. issue happens only occasionally):**
1. I did an apt-get update and upgrade, which did not fix the issue. As part of the upgrade Ubuntu's kernel got upgraded from -36 to -38.
2. I did a system reboot.
3. The issue was fixed after a system reboot. Might be related to kernel upgrade, might be just the reboot.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 201
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 302
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.1 MiB
ID: 255Q:NZAT:MRO3:QZSV:BPIF:2X2D:GNBH:OVXW:UKYL:7KMU:R2Y5:46NP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 on Rackspace VM.

**Comment by cpuguy83** [comment]
Thanks, closing this as a dup of #27134
