### ISSUE TITLE
feature req: DOCKER_NO_CACHE env var for build environments

### ISSUE THREAD

**Issue by colemickens** [docker/docker#27137]
I have build scripts for building various components using Docker containers. During normal development, I don't mind having some things cached. During CI builds, I don't ever want to cache.

I could plumb around switches/flags for adding or omitting the `--no-cache` flag to `docker build` but in my ideal world, I would just be able to set `DOCKER_NO_CACHE` in my build environment and avoid all of the boilerplate that would be needed throughout Makefiles/build shell scripts.

**Expected:** Setting `DOCKER_NO_CACHE=1` causes `docker build` to act as if `--no-build` was supplied.

**Actually:** It's ignored.

Thanks for any consideration!

**Comment by cpuguy83** [comment]
👎 

Why not just:
```
$ export DOCKER_NO_CACHE="--no-cache"
$ docker build "$DOCKER_NO_CACHE" ...
```

**Comment by cpuguy83** [comment]
When you want no cache set the env-var to `--no-cache` when you don't, unset the env var.

**Comment by colemickens** [comment]
Yeah, that's what I was doing. It's messy and feels awkward and crufty.

I actually took to some `s/docker build/docker build --no-cache/g` approach instead because I really don't want to add that throughout my repo.

Any reason for opposition to an environment variable, or just feels like an unnecessary addition to you?

**Comment by colemickens** [comment]
Also, your proposed option doesn't actually work... that's the pain of trying to do this trick, the incantation actually becomes much more ugly to avoid this issue (quoted empty string):

```shell
$ docker build "$DOCKER_NO_CACHE" -t test .
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

$ export DOCKER_NO_CACHE="--no-cache"

$ docker build "$DOCKER_NO_CACHE" -t test .
Sending build context to Docker daemon 2.048 kB
Step 1 : FROM busybox
 ---> 2b8fd9751c4c
Step 2 : CMD ls
 ---> Running in 59e66646501e
 ---> 41911541ae7f
Removing intermediate container 59e66646501e
Successfully built 41911541ae7f

$ unset DOCKER_NO_CACHE

$ docker build "$DOCKER_NO_CACHE" -t test .
"docker build" requires exactly 1 argument(s).
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile
```

**Comment by cpuguy83** [comment]
Yes, environment variables are evil for this sort of thing.
It's not environmental, it's configuration of a particular instance.

Either way you would have to set or unset the variable.

It was my mistake in the example, there is no need for quotes around the env var.

```
$ export DOCKER_NO_CACHE="--no-cache"
$ docker build $DOCKER_NO_CACHE -t test .
```

**Comment by thaJeztah** [comment]
I think the proposed solution above is a good way to get this working, and don't think there's a need to implement this in docker itself.

I'll close this issue, but feel free to comment after that

**Comment by alkuzad** [comment]
@thaJeztah it's a pity that this this is closed. In strictly defined environments like gitlab-ci it is not encouraged to change code just to introduce another CI flag just for one re-build with failing cache. But environment variables are independent from flow configuration so they can be introduced without messing up with deploy code itself.

**Comment by thaJeztah** [comment]
@alkuza the point is; where does it end? The CLI interface is to use flags to provide options to pass to commands. Adding environment variables would mean that we'd have to add an environment variable for each flag, each command on the CLI.

If (e.g.) gitlab-ci does not support configuring this, I think that should be a feature request with GitLab (e.g. Docker Cloud allows enabling / disabling caching for automated builds)

**Comment by alkuzad** [comment]
For future readers, this is better version that will not split/glob and will use --no-cache regardless of value in variable.

```bash
build_args=("${DOCKER_NO_CACHE:+--no-cache}")
docker build "${build_args[@]}" .
```

**Comment by jdmarshall** [comment]
@thaJeztah It probably ends at --no-cache.

What other docker build flags are you likely to want to behave differently on a CI/CD server versus locally? And if docker build is but one step in your process, now you have to fish around inside multiple build scripts (because who builds just one Docker image in an enterprise?) to get it sorted.  Instead of one ENV variable in the build plan.

**Comment by jdmarshall** [comment]
Hello people of the future!

If you are only trying to avoid stale :latest tags, `docker build --pull` will do.

**Comment by kdenehy** [comment]
> @alkuza the point is; where does it end? The CLI interface is to use flags to provide options to pass to commands. Adding environment variables would mean that we'd have to add an environment variable for each flag, each command on the CLI.
> 

Do it like Java, Apache Tomcat, and others - have one environment variable that can contain multiple options.

E.g., JAVA_OPTS=-XX:MaxPermSize=512m -Xss2m -XX:+UseConcMarkSweepGC

So something similar, such as

DOCKER_BUILD_OPTS=--no-cache --quiet

And here's a use case:  I have a 3rd party program that runs docker itself, and the docker build command is a string inside an executable.  I have no way to modify it, and they provided no way of setting options.  If I could set an environment variable, I could force the no-cache option, which I really need.

**Comment by rulatir** [comment]
> @alkuza the point is; where does it end?

If done right, it ends with users being in full control and able rather than unable to do what they want to do.

**Comment by battlesnake** [comment]
Alternatively, an env-var that just specifies a path (or paths?) to a JSON (or YAML?) file with arguments, e.g.

```
export DOCKER_BUILD_CONFIG="$workspace/ci/clean_rebuild.json"
```

```
{
  "no_build": True,
  "pull": True",
  "label": [
    "built_by=ci"
  ]
}
```

That way, overrides for most args can be plumbed through multiple layers of 3rd-party tools, without an explosion of obscure env-vars
