### ISSUE TITLE
Docker with EC2 after restart: certificate is valid for ... not ...

### ISSUE THREAD

**Issue by peetonn** [docker/docker#27131]
**Description**

Previously, I set up Docker swarm on EC2 cluster and it worked with no problems. I stopped Docker machines when not using them (using `docker-machine stop` command). Now, when I tried to start machines again, I get errors in `docker-machine ls` like `Unable to query docker version: Get https://XXX.XXX.XXX.XXX:2376/v1.15/version: x509: certificate is valid for YYY.YYY.YYY.YYY, not XXX.XXX.XXX.XXX`. I do understand, that this happened due to EC2 instance got new IP address. However, how do I solve this problem?

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 8
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host overlay
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: RD6K:JSDU:WNYO:C4NV:NWUI:CHQS:2ZXU:MUJI:DJEM:NB4E:LXEF:C6SZ
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-10-04T00:43:51.39450096Z
 EventsListeners: 0
Username: peetonn
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using AWS.

**Comment by michelvocks** [comment]
You can try to update the certificates with `docker-machine regenerate-certs`. Otherwise you have to re-create the machines with `docker-machine create...`

If you want to reuse the existing instances you should use the [generic driver](https://docs.docker.com/machine/drivers/generic/).

**Comment by peetonn** [comment]
@michelvocks tried this, didn't help. yeah, I guess the only way is to re-create machines. 
the problem with swarm is that it takes very long to spin up 10-node cluster.
