### ISSUE TITLE
The docker run option --read-only causes trouble with the docker exec command

### ISSUE THREAD

**Issue by eriksank** [docker/docker#27142]
On a debian host:
```
$ uname -a
Linux test1 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
```
With the following docker version:
```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```
When I do a `docker run` with the following options, the container starts absolutely fine:

```
$ docker run --tty --detach --restart=always --net=cnxnet  \
  --net-alias=mycontainer --name=mycontainer \
  -v /webscripts:/var/www/scripts:ro -v /binscripts:/usr/local/bin:ro \
  -v mycontainer.cache:/var/cache/mycontainer -v mycontainer.etc:/etc/mycontainer \
  -v mycontainer.log:/var/log/mycontainer -p 5001:5001 -p 5013:5013 myimgs/mycnt
```
Executing instructions in this container with `docker exec` also works fine:
```
$ docker exec -i mycontainer /bin/bash -c "ps aux"
```
As soon as I add the following options to the `docker run` command, however:
```
--read-only --tmpfs /run --tmpfs /tmp
```
The very same `docker exec` instruction as above will lead to the following error condition:
```
Error response from daemon: Container 4362...74723 is restarting, 
wait until the container is running
```
The only change to the situation, ceteris paribus, is the addition of the `--read-only` option group.
For security reasons, with all writable areas actually moved into volumes, I am trying to lock down the remainder of the container. I would be interested in adding this option group. Any advice on how to go about doing that? Thanks!

**Comment by cpuguy83** [comment]
Not sure what you are asking for here.
But what it sounds like to me is your app is exiting because it can't write to some location that it wants to.

Can you check the container logs?

**Comment by thaJeztah** [comment]
closing, as we need more information, but happy to reopen once provided
