### ISSUE TITLE
.dockerignore doesn't ignore matches in subdirs

### ISSUE THREAD

**Issue by andrei-picus-hs** [docker/docker#27144]
**Description**

Using filenames in `.dockerignore` won't ignore files that match the name but reside in subdirectories. This is contrary to `.gitignore` which ignores any file matching the expression, regardless of directory hierarchy.

In short:

- .dockerignore` foo` matches `foo` but not `bar/foo`
- .gitignore `foo` matches both `foo` and `bar/foo`
- .dockerignore `**/foo `matches both `foo` and `bar/foo`

**Steps to reproduce the issue:**

1. `git init .`
2. `mkdir foo`
3. `touch foo/bar`
4. `touch foo/baz`
5. `echo baz > .dockerignore`
6. `echo FROM alpine >> Dockerfile`
7. `echo RUN mkdir -p /usr/src/app >> Dockerfile` 
8. `echo WORKDIR /usr/src/app >> Dockerfile`
9. `echo COPY foo . >> Dockerfile`
10. `echo CMD \"ls\" >> Dockerfile`
11. `docker build -t foo .`
12. `docker run foo`

**Describe the results you received:**

```
bar
baz
```

**Describe the results you expected:**

```
bar
```

If you do `echo baz > .gitignore && git add foo && git status` you'll get:

```
Changes to be committed:

	new file:   foo/bar
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 85
Server Version: 1.12.2-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 122
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.22-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: 6HGM:TIKG:I5GK:WBUG:BMI3:NMAK:5XFM:WZC5:NKVR:4ID3:U4P6:VQ5U
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 29
 System Time: 2016-10-04T15:42:22.963029342Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by tonistiigi** [comment]
cc @duglin

**Comment by duglin** [comment]
This is working as designed. In order not to break people, when we added wildcard support, we couldn't make "foo" match "bar/foo".

From the docs:
`
Matching is done using Go’s filepath.Match rules. A preprocessing step removes leading and trailing whitespace and eliminates . and .. elements using Go’s filepath.Clean. Lines that are blank after preprocessing are ignored.

Beyond Go’s filepath.Match rules, Docker also supports a special wildcard string ** that matches any number of directories (including zero). For example, **/*.go will exclude all files that end with .go that are found in all directories, including the root of the build context.
`

We can certainly change things to better align with .gitignore but that would be an incompatible change and we'd need the support for enough maintainers to do that.

**Comment by tonistiigi** [comment]
@duglin Thanks for the explanation

**Comment by briggySmalls** [comment]
In case someone comes here nowadays. The .dockerignore [docs](https://docs.docker.com/engine/reference/builder/#/dockerignore-file) quoted by @duglin has a type-o. The example should be `**/*.go`, which makes sense based on the surrounding context!

**Comment by oliver-ni** [comment]
@duglin I understand the reason behind this, but perhaps this needs to be better documented?

I just spent over an hour debugging an issue with exec formats being wrong (an included binary was compiled for the wrong platform), and turns out it was because a directory that was supposed to be excluded wasn't — due to this. In the past I've just assumed that `.dockerignore` worked the same way as `.gitignore` and I think a lot of people would initially assume that too...

Maybe a section with differences between how these two work since this doesn't seem to be the only case.

**Comment by thaJeztah** [comment]
@oliver-ni this is a 6-year old closed ticket; there's definitely things to improve, but some change may be difficult to change to prevent breaking backward-compatibility; there's https://github.com/moby/moby/issues/40319 and https://github.com/moby/moby/issues/40318 related to `.dockerignore` (and feature-parity with `.gitignore`). the documentation is currently maintained in the docker/cli repository (contributions welcome though!); https://github.com/docker/cli/blob/master/docs/reference/builder.md#dockerignore-file
