### ISSUE TITLE
Whats the proper way to get complete error messages on swarm services?

### ISSUE THREAD

**Issue by manast** [docker/docker#27151]
This is something that happens quite often and I wonder if there is some established way to get the errors from a service that fails to start, for instance:
```
$docker service ps occusell-mongoui
99vvw5q2e92bx53xn5hd7oho7   \_ occusell-mongoui.1  mongoclient/mongoclient:latest  caturra  Shutdown       Failed 5 seconds ago   "starting container failed: Vo…"
```

```"starting container failed: Vo…"``` is not super useful. My alternative many times is to go the the node in question and read the logs of the docker daemon, but there are so many other unrelated logs, that it takes quite time to find the error...

Suggestions?

**Comment by cpuguy83** [comment]
@manast `docker inspect 99vvw5q2e92bx53xn5hd7oho7`

Closing for now since this doesn't look like an issue.

**Comment by manast** [comment]
ah, ok thanks. I actually didn't know inspect worked on service tasks :)
