### ISSUE TITLE
Errors calling docker swarm init on Win Server 2016 TP5

### ISSUE THREAD

**Issue by ferrx** [docker/docker#27150]
**Description**
Calling "docker swam init" in PowerShell on Win Server 2016 TP5 produces errors.

**Steps to reproduce the issue:**
1. Open PS as admin
2. Run "docker swam init"

**Describe the results you received:**
Error response from daemon: could not choose an IP address to advertise since this system has multiple addresses - specify one with --advertise-addr

When attempting to use --advertise-addr with the following command:
docker swarm init --advertise-addr 192.my-ip:2377

Received error: 
Error response from daemon: listen unix C:\ProgramData\docker\swarm\control.sock: socket: An address incompatible with the requested protocol was used.

**Describe the results you expected:**
Success

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.0
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1045.amd64fre.rs1_release_svc.160705-1059)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 7 GiB
Name: my-name
ID: my-id
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running WS2016 as Azure VM.

**Comment by thaJeztah** [comment]
Swarm mode is not yet supported on Windows, but I'm not sure this error is related to that

/cc @mavenugo @jhowardmsft

**Comment by jhowardmsft** [comment]
That's expected in the current code base - there's no Windows distinguishing.

**Comment by mabead** [comment]
@thaJeztah Is it still the case that swarm mode is not yet supported on Windows? Do you have any idea of when it will be supported?

**Comment by thaJeztah** [comment]
@mabead more features coming in 1.13, but some things won't be functional yet until an update for Windows

**Comment by jaydo1** [comment]
so version 1.13 has been released can you create a swarm in windows2016 yet?

**Comment by thaJeztah** [comment]
@jaydo1 not yet, it still requires a Windows update to be released (not a docker update).

**Comment by mindriven** [comment]
Thanks for clearing this up @thaJeztah.
Could someone from MS-Docker team estimate how long will it take until we get the update?

**Comment by thaJeztah** [comment]
> Could someone from MS-Docker team estimate how long will it take until we get the update?

If they _know_ they are not allowed to share, so unfortunately not 😃
