### ISSUE TITLE
docker failing to start after upgrading

### ISSUE THREAD

**Issue by LorenzoBoccaccia** [docker/docker#27155]
**Description**

docker doesn't start after upgrade

**Steps to reproduce the issue:**
unsure about previous version of docker, current is version 1.12.1, build 23cf638

**Describe the results you received:**
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: read unix @->/var/run/dock       er.sock: read: connection reset by peer

**Describe the results you expected:**
docker working

**Additional information you deem important (e.g. issue happens only occasionally):**

tried aptitude purge/reinstall, to no avail

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version: read unix @->/var/run/docker.sock: read: connection reset by peer

```

**Output of `docker info`:**

```

An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info: read unix @->/var/run/docker.sock: read: connection reset by peer

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by michelvocks** [comment]
Is the docker daemon running? What OS and kernel version do you use?

**Comment by LorenzoBoccaccia** [comment]
Linux 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

`
root@castor:~# pstree
init─┬─acpid
     ├─atd
     ├─cron
     ├─dbus-daemon
     ├─docker-containe───10*[{docker-containe}]
     ├─8*[getty]
     ├─2*[iscsid]
     ├─nimbus───controller─┬─hdb
     │                     └─spooler───{spooler}
     ├─rpc.idmapd
     ├─rpc.statd
     ├─rpcbind
     ├─rsyslogd───3*[{rsyslogd}]
     ├─sshd───sshd───bash───pstree
     ├─systemd-logind
     ├─systemd-udevd
     ├─upstart-file-br
     ├─upstart-socket-
     ├─upstart-udev-br
     └─xe-daemon───sleep
root@castor:~# /etc/init.d/docker start
docker start/running, process 9818
root@castor:~# docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

`

^ I tried downgrading and upgrading again, the message has changed now to 

> Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by michelvocks** [comment]
Did you set a value to the environment variable DOCKER_HOST? It should be empty to automatically connect to the local docker socket. 
If not, does /var/run/docker.sock exist?

**Comment by LorenzoBoccaccia** [comment]
DOCKER_HOST is empty, the socket file exists and it's shown in use by dockerd



```
root@castor:~# echo $DOCKER_HOST

root@castor:~# ls /var/run/docker.sock
/var/run/docker.sock
root@castor:~# lsof | grep /var/run/docker.sock
dockerd   16949 16953       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16954       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16955       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16957       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16958       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16960       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16961       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16972       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock
dockerd   16949 16973       root    3u     unix 0xffff8801f34dd680      0t0      84454 /var/run/docker.sock

```

**Comment by michelvocks** [comment]
That is weird. Are there any other environment variables set? For example `DOCKER_TLS_VERIFY`?
You should run the docker daemon in debug mode to find out what is happening: https://docs.docker.com/engine/admin/#/ubuntu
It might be also good to have a look at the logs afterwards.

**Comment by LorenzoBoccaccia** [comment]
thanks for the dock - debug log now points to a specific message

```
time="2016-10-05T11:53:08.495207123Z" level=info msg="libcontainerd: new containerd process, pid: 7601"
time="2016-10-05T11:53:09.602921765Z" level=error msg="[graphdriver] prior storage driver \"aufs\" failed: driver not supported"
time="2016-10-05T11:53:09.603090245Z" level=fatal msg="Error starting daemon: error initializing graphdriver: driver not supported"

```

**Comment by LorenzoBoccaccia** [comment]
yep it was the issue here and the fix applied (reinstall/recreate all images)  http://askubuntu.com/questions/675925/aufs-driver-not-loaded-found-on-kernel-4-branch
