### ISSUE TITLE
Docker Engine Swarm Mode + Docker pull

### ISSUE THREAD

**Issue by saithala** [docker/docker#27176]
**Description**

I have docker engine running in swarm mode with 4 nodes in the swarm cluster

**Steps to reproduce the issue:**
1. I run the command to start a docker service using an image stored in the dockerhub private repo.
sudo docker service create --name serviceName  --network myNetwork --publish 8761:8761 orgName/imageName:version

**Describe the results you received:**
1. It seems that if the image does not exist in the local node where the service is scheduled to run, docker does not automatically pull the image from the private repo and the service fails to start
2. However if I manually pull the image in all of the nodes in the cluster and then start the service, it seems to work. 

**Describe the results you expected:**
1. I expected docker to automatically pull the image from the private repo hosted in the hub. To make sure that there are no connectivity issues I logged into the private repo using docker login in each of the 4 nodes in the cluster to make sure that the credentials to be used to connect to the repo are stored locally in the json file. Is this how its supposed to work? Should it not automatically pull from hub if the image is not available locally? Im I missing something?

Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64


```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 201
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-204218855-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.401 GB
 Data Space Total: 107.4 GB
 Data Space Available: 30.95 GB
 Metadata Space Used: 7.598 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: b11gagg35v2tojxnqemze6ey6
 Is Manager: true
 ClusterID: 7f9kda0i54yj0jl8js0vt84u5
 Managers: 3
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.1.2.56
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 47.01 GiB
Name: cmcmdmz101
ID: N6XG:EQOG:FPUM:GYCY:HXHQ:DOVU:AHFM:TFBB:4GM6:WKC3:QCN2:6RLP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: cmcdocker
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by saithala** [comment]
@thaJeztah Any ideas about this one?

**Comment by cpuguy83** [comment]
Please see the `--with-registry-auth` flag.
This passes registry credentials down to each node that gets a task scheduled from this service so it can pull the image as neccessary.

Unfortunately our docs page has been revamped and I am having a hard time finding this option there... maybe it's just missing?

**Comment by thaJeztah** [comment]
it's in the CLI reference documentation; https://github.com/docker/docker/blob/v1.12.1/docs/reference/commandline/service_create.md

https://docs.docker.com/engine/reference/commandline/service_create/

**Comment by saithala** [comment]
Thanks @cpuguy83  and @thaJeztah fpr your responses.. Should that even matter? Like I mentioned, I logged into all the hosts and manually executed the docker login command so that the credentials are stored locally in the config.json file. Assuming that its needed, could you please give me an example of the syntax?  How do I pass the password? I could not find an example in the docs.. sudo docker service create --name serviceName --network myNetwork  --publish 8761:8761 --with-registry-auth USERNAME orgName/imageName:version ?? is this right?

**Comment by cpuguy83** [comment]
@saithala `--with-registry-auth` is just a boolean flag, no arguments needed.
`docker login` is a mostly client-side command. Basically it asks for your credentials, then instructs the daemon to login with them... but this "login" is not persisted, it's per request.

What happens is the credentials are persisted on the client side so that when auth is required it can just read the credentials and pass them to the daemon.
In swarm mode, it was decided to not automatically pass credentials since worker nodes may be untrusted.

**Comment by saithala** [comment]
Thanks @cpuguy83.

**Comment by thaJeztah** [comment]
I think the question is answered, so I close this issue, but feel free to continue the discussion if it's not clear
