### ISSUE TITLE
Could not build docker.io 1.11.2 because of WaitForStateChange in grpc

### ISSUE THREAD

**Issue by yanxiaoliang** [docker/docker#27172]
**Description**

I am trying to build docker.io-1.11.2 under debian/sid environment, and I used golang-google-grpc-dev (1.0.0-1), it gave me a build error that could not find function WaitForStateChange.
That's because grpc adds a new struct addConn and assign function to it, the previous struct ClientConn becomes one variable of addConn, this could be found by below
https://github.com/grpc/grpc-go/blob/13edeeffdea7a41d5aad96c28deb4c7bd01a9397/clientconn.go 

**Steps to reproduce the issue:**
1. Use pbuilder to build package

**Describe the results you received:**
Building: bundles/1.11.2/dynbinary/docker-1.11.2
# github.com/docker/docker/libcontainerd
.gopath/src/github.com/docker/docker/libcontainerd/remote_linux.go:116: r.rpcConn.WaitForStateChange undefined (type *grpc.ClientConn has no field or method WaitForStateChange)
debian/rules:60: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/tmp/buildd/docker.io-1.11.2~ds1'
debian/rules:109: recipe for target 'build' failed
make: *** [build] Error 2

**Describe the results you expected:**
Hope anyone could provide a patch for remote_linux.go, so I could build through

**Additional information you deem important (e.g. issue happens only occasionally):**

Etcd has same issue could be found at below
https://github.com/coreos/etcd/issues/5561,
and be fixed by
https://github.com/coreos/etcd/pull/5583

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tonistiigi** [comment]
Docker vendors its dependencies under `/vendor` and only builds with these versions. So set up your `GOPATH` to include this dir or use docker to build docker(`make build`) like the rest of us.
