### ISSUE TITLE
Feature request for docker --filter : ability to search by PORT number, exposed or published and all published

### ISSUE THREAD

**Issue by virtuman** [docker/docker#27178]
Just wanted to voice an idea to implement a couple of new --filter's in docker cli tool

Often, I find myself looking for containers that run or publish certain ports, or sometime find all containers that publish ports and filter out all containers that don't publish and don't expose ports.

Does anyone think that they could also benefit from something like that?

It should allow matches by complete number and/or support wildcard or regex in the search mask. 
Proposed syntax:
docker ps --filter publishes=27017
docker ps --filter exposes=27017

docker ps --filter publishes=270*
docker ps --filter exposes=270*

docker ps --filter publishes=*
docker ps --filter exposes=*

**Comment by yongtang** [comment]
One issue with the wildcard is that we also need to take into consideration the protocols, i.e., `tcp` or `udp`.

I created a PR #27557 with filter `expose|publish=<port>[/<protocol>]|<from>-<to>[/<protocol>]`. This is an attempt with the hope to have more discussions.  Open to any suggestions or feedbacks.
