### ISSUE TITLE
Add `docker service ps` filtering capability to config.json

### ISSUE THREAD

**Issue by estesp** [docker/docker#27189]
`docker ps` can read the formatting options from command line as well as from `config.json`.

A user noted that `docker service ps` does not support this configured formatting stored in `config.json`, meaning you have to provide formatting each time you run the command.

// cc: @amouat

**Comment by vdemeester** [comment]
@estesp `docker service ps` (or `docker service ls`) do not support `--format` currently (only `docker service inspect`).
