### ISSUE TITLE
Docker client library can not build an image

### ISSUE THREAD

**Issue by rcshubhadeep** [docker/docker#27186]
Hello All,

This defeats me. I am not sure what I am doing wrong. There is so less documentation that searching did not produce good result. I will be happy to see what is the reason behind this strange behaviour. 

I am on a MAC (10.11.6) and I am running docker for MAC (beta) 

Here is the code I am trying to run

```
    package main
    
    import (
    	"fmt"
    
    	"github.com/docker/docker/api/types"
    	"github.com/docker/docker/client"
    	"golang.org/x/net/context"
    )
    
    func main() {
    	defaultHeaders := map[string]string{"User-Agent": "ego-v-0.0.1"}
    	cli, _ := client.NewClient("unix:///var/run/docker.sock", "v1.24", nil, defaultHeaders)
    	options := types.ImageBuildOptions{
    		Dockerfile:     "/path/to/my/Dockerfile",
    		SuppressOutput: false,
    		Remove:         true,
    		ForceRemove:    true,
    		PullParent:     true}
    	buildResponse, err := cli.ImageBuild(context.Background(), nil, options)
    	if err != nil {
    		fmt.Printf("%s", err.Error())
    	}
    	fmt.Printf("%s", buildResponse.OSType)
    }

```
This gives me this error -  

   ` Error response from daemon: {"message":"Cannot locate specified Dockerfile: /path/to/my/Dockerfile"}`

Whereas when I run this command (from the same directory where my Go code is)

    `docker build /path/to/my/Dockerfile`

It works absolutely fine. 

What am I doing wrong? I feel like banging my head against a wall now. Please help.

Paths are absolute and they completely exists. Also, If I add "Dockerfile" at the end of the path or not it does not make any difference for the code.

Here are some more info - 

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

And go version

`go version go1.7.1 darwin/amd64`

**Comment by cpuguy83** [comment]
`Dockerfile` is not what `docker build /path/to/dockerfile` is setting.
`docker build /path/to/dockerfile` is specifying the location of the build context, and it uses `/path/to/dockerfile/Dockerfile` as the default location of the Dockerfile.

See how the docker CLI uses the client lib: https://github.com/docker/docker/blob/master/cli/command/image/build.go#L304

Closing as this is not really an issue, but feel free to discuss here.

**Comment by rcshubhadeep** [comment]
Thanks for this indication. For what it is worth this is what I ended up doing

```
package main

import (
	"fmt"
	"os"

	"github.com/docker/docker/api/types"
	"github.com/docker/docker/client"
	"github.com/jhoonb/archivex"
	"golang.org/x/net/context"
)

func main() {
	tar := new(archivex.TarFile)
	tar.Create("path/to/final/archieve")
	tar.AddAll("path/to/source/folder", false)
	tar.Close()
	dockerBuildContext, err := os.Open("./repo.tar")
	defer dockerBuildContext.Close()
	defaultHeaders := map[string]string{"User-Agent": "ego-v-0.0.1"}
	cli, _ := client.NewClient("unix:///var/run/docker.sock", "v1.24", nil, defaultHeaders)
	options := types.ImageBuildOptions{
		Dockerfile:     "Dockerfile",
		SuppressOutput: false,
		Remove:         true,
		ForceRemove:    true,
		PullParent:     true}
	buildResponse, err := cli.ImageBuild(context.Background(), dockerBuildContext, options)
	if err != nil {
		fmt.Printf("%s", err.Error())
	}
	fmt.Printf("********* %s **********", buildResponse.OSType)
}
```

It will be helpful for people like us to have a little more documentation on this client library. Anyway, posting this code here so that someone can find it a handy reference. 

Using 

> github.com/jhoonb/archivex

 as I found it is easy and fast to use for my purpose. But the one that comes with Docker is also good. Just I was lazy to use it, and this one serves the purpose well for me.

**Comment by benkeil** [comment]
I don't get it tu run... After figuring out to send a tar file, I get the following error: `panic: Error response from daemon: Cannot locate specified Dockerfile: Dockerfile`

My code:

```go
tarfile, err := tarWorkdir(directory)
defer tarfile.Close()
//defer os.Remove(tarfile.Name())

buildResponse, err := cli.ImageBuild(context.Background(), tarfile, types.ImageBuildOptions{
	PullParent: true,
	Tags:       tags,
	//Dockerfile: "Dockerfile",
})
check(err)
defer buildResponse.Body.Close()
response, err := ioutil.ReadAll(buildResponse.Body)
check(err)
logger.Infof("Response from docker: %s", response)
```

And the content of the created tar file:

```
17:47:20 ben@MBP /tmp $ tar -tf 391898342.tar.gz
Dockerfile
README.md
```

What do I wrong?

**Comment by edupo** [comment]
@benkeil Probably is because of deferring `tarfile.Close()`? Just guessing here...

**Comment by rcshubhadeep** [comment]
I am not sure about this error, however, I forked and changed the `github.com/jhoonb/archivex` a bit in my profile to suit the need. That I remember very well.

**Comment by richmondwang** [comment]
how can we properly parse the output/response?

**Comment by PaulRosset** [comment]
Hi, I struggled during one day to figure out how to build an image with the API, then I dived in the source code and found a neat solution which consist to used the tools provided by docker for the creation of archive, here is what I've found, it may help some people:

```
import "github.com/docker/docker/pkg/archive"
reader, err := archive.TarWithOptions("path/to/the/project/where/the/dockefile/reside", &archive.TarOptions{})
```
Thus the `TarWithOptions` return what we need an `Io.Reader` to pass to the `buildContext`.  
To go further and fit a special need, you can pass several argument as [`TarOptions{}`](https://github.com/moby/moby/blob/master/pkg/archive/archive.go):

```
TarOptions struct {
		IncludeFiles     []string
		ExcludePatterns  []string
		Compression      Compression
		NoLchown         bool
		UIDMaps          []idtools.IDMap
		GIDMaps          []idtools.IDMap
		ChownOpts        *idtools.Identity
		IncludeSourceDir bool
		// WhiteoutFormat is the expected on disk format for whiteout files.
		// This format will be converted to the standard format on pack
		// and from the standard format on unpack.
		WhiteoutFormat WhiteoutFormat
		// When unpacking, specifies whether overwriting a directory with a
		// non-directory is allowed and vice versa.
		NoOverwriteDirNonDir bool
		// For each include when creating an archive, the included name will be
		// replaced with the matching name from this map.
		RebaseNames map[string]string
		InUserNS    bool
}
```

**Comment by inkychris** [comment]
For me, it also appears that (on Windows at least) you need to pass [`archive.TarWithOptions`](https://github.com/moby/moby/blob/master/pkg/archive/archive.go#L724) an absolute directory path and then make sure that the [`ImageBuildOptions.Dockerfile`](https://github.com/moby/moby/blob/master/api/types/client.go#L162) property uses forward-slashes rather than backslashes.
