### ISSUE TITLE
[docker/feature] create a light-weight init that can forward signals and reap zombies

### ISSUE THREAD

**Issue by rogaha** [docker/docker#27187]
**Description**

It would be great if Docker could handle the zombie processes within the container. Currently users have to add custom `init` applications in order to solve this issue (you can find more context here: https://blog.phusion.nl/2015/01/20/docker-and-the-pid-1-zombie-reaping-problem/).

A very cool project that solves that is: https://github.com/krallin/tini.

/cc @crosbymichael @justincormack @shykes

**Comment by cpuguy83** [comment]
@rogaha This is already in master.
Set `--init` at the daemon level or at the container level.

**Comment by rogaha** [comment]
Awesome, thanks for the heads up @cpuguy83! I wasn't aware about it!

**Comment by rogaha** [comment]
Do you have a link to the documentation or an example?

**Comment by cpuguy83** [comment]
https://github.com/docker/docker/blob/master/api/types/swarm/network.go#L74

Not really much to demo, just add `--init` to either `dockerd` or `docker run` and you will get a light-weight init in the container at PID1 that handles zombie reaping and signal forwarding.

It's using https://github.com/crosbymichael/grimes

**Comment by rogaha** [comment]
Awesome, thanks @cpuguy83. I'll try it out!

**Comment by rogaha** [comment]
@thaJeztah do we have docs for that feature? I'm assuming it will land on 1.13.

**Comment by thaJeztah** [comment]
@rogaha nope, no docs yet; unfortunately docs review was skipped (and I was on vacation); I labeled the PR with "docs-revisit", and will do a docs PR to fix that https://github.com/docker/docker/pull/26061

**Comment by rogaha** [comment]
Understood. Thanks for the heads up @thaJeztah. I'm glad to see it was already there! :)

**Comment by rogaha** [comment]
props to @crosbymichael!
