### ISSUE TITLE
docker run -it --isolation=hyperv microsoft/nanoserver cmd fails

### ISSUE THREAD

**Issue by vaibhavkhanduja** [docker/docker#27198]
**Description**

Docker run with isolation hyper v fails with error "no" hyper V plugin found.
**Steps to reproduce the issue:**
1.  Install windows evaluation ISO and run windows updates
2. Install docker as instructed on msdn and enable hyper V feature
3. Run hyper v isolation container 

docker run -it --isolation=hyperv microsoft/nanoserver cmd
docker: Error response from daemon: container 484d5da7efd80a68e314d875831ae11cea29d280e8a7b4776fe11e83c86f6774 encountered an error during CreateContainer failed in Win32: No hypervisor is present on this system. (0xc0351000) extra info: {"SystemType":"Container","Name":"484d5da7efd80a68e314d875831ae11cea29d280e8a7b4776fe11e83c86f6774","Owner":"docker","IsDummy":false,"VolumePath":"","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"","Layers":[{"ID":"c0c0f8ec-f1c4-5edf-a2e2-a4cf843fbadc","Path":"C:\ProgramData\docker\windowsfilter\644e7f35eaabca67a86df4412aea1e9f402cdafb4fc5387a363bbbdf3de2ff9d"}],"HostName":"484d5da7efd8","MappedDirectories":[],"SandboxPath":"C:\ProgramData\docker\windowsfilter","HvPartition":true,"EndpointList":["84a6a78d-e72b-4a7e-9e6c-575a3f8538b9"],"HvRuntime":{"ImagePath":"C:\ProgramData\docker\windowsfilter\644e7f35eaabca67a86df4412aea1e9f402cdafb4fc5387a363bbbdf3de2ff9d\UtilityVM"},"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by friism** [comment]
@vaibhavkhanduja can you provide more details on the environment you're running Windows Server in?

**Comment by vaibhavkhanduja** [comment]
Details are:

a) Server windows 2016 evaluation version with all updates installed 
b) The server running on VMWare ESX Server
c) Installed Docker as documented in MSDN, and was able run container "micrsoft/iis"
d) Enabled HyperV nested virtualization to enable the feature
e) Had issues with enabling HyperV containers, but went past that through: details below
f) The event log shows following error when using isolation hyper V

fatal task error [module=node/agent/taskmanager task.id=a8ey3mnegodcmm2jlbmahwdyv error=plugin not found]
......
Details of Hyper V install

Install-PackageProvider ContainerImage –Force

Enable-WindowsOptionalFeature -Online -FeatureName Containers

Install-ContainerImage NanoServer

It seems from latest version above command has been remove, printing following error on screen:

Install-ContainerImage -Name WindowsServerCore
Install-ContainerOSImage : The term 'Install-ContainerOSImage' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:502 char:5
+     Install-ContainerOSImage -WimPath $Destination `
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-ContainerOSImage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

 Do the following:
Start-BitsTransfer https://aka.ms/tp5/6b/docker/nanoserver -Destination nanoserver.tar.gz
docker load -i nanoserver.tar.gz
docker tag microsoft/nanoserver:10.0.14300.1030 microsoft/nanoserver:latest)

**Comment by friism** [comment]
@vaibhavkhanduja I'm unsure if Hyper-V will work when nested through VMWare. Can you confirm whether you can create and run a normal Hyper-V VM with Hyper-V manager?

The reason you can run `microsoft/iis` is that it runs with normal (non-hyperv) isolation, so that doesn't require the virt nesting to work.

**Comment by StefanScherer** [comment]
@vaibhavkhanduja You need `vhv.enable = "true"` in your vmx file to turn on [nested hypervisor](http://www.virtuallyghetto.com/2012/08/how-to-enable-nested-esxi-other.html).

**Comment by vaibhavkhanduja** [comment]
@StefanScherer it is enabled ... w/o this I was not able to enable HyperV feature ...

**Comment by StefanScherer** [comment]
@vaibhavkhanduja Yes, and you need `virtualhw.version = "11"` to make Hyper-V happy. My [packer templates](https://github.com/StefanScherer/packer-windows/blob/b2a7684f75b533091733ae5fb25609af233e1284/windows_2016_docker.json#L50) also set this hardware version.

**Comment by StefanScherer** [comment]
Instead of using `Install-ContainerImage NanoServer` you can just `docker pull microsoft/nanoserver` with the eval ISO (post TP5).

**Comment by vaibhavkhanduja** [comment]
Well! now I see docker service not starting ... bunch of errors in event log 

...
network ingress remove failed: network ingress not found [module=node/agent/taskmanager task.id=dio5h0f1bwbwuo2nyh86dgegz]
...

BTW, with Hyper VI was able to create a VM

**Comment by PatrickLang** [comment]
Can you try downloading the scripts here and running `Debug-ContainerHost.ps1` ? https://github.com/Microsoft/Virtualization-Documentation/tree/live/windows-server-container-tools/Debug-ContainerHost

It's a new script I'm working on to collect logs and diagnose problems automatically.

I also need to give a brief caveat regarding running Hyper-V under VMWare. As @StefanScherer mentioned it can work, but isn't officially supported by Microsoft and VMWare so its not suitable for production use.

**Comment by jhowardmsft** [comment]
This is environmental, not docker. It needs to be run on a Hypervisor which supports Hyper-V nested virtualization. Hence closing.
