### ISSUE TITLE
I can do this when I use docker run without error, but when I use dockerfile build here is some bugs!

### ISSUE THREAD

**Issue by GanLuo96214** [docker/docker#27197]
**Description**

/usr/bin/file: No such file or directory
when I Build and I used tar command, the extract files all owner is 501 in games group. I don't know why.

Dockerfile

```
yum install perl gcc gcc-c++ cmake make git bzip2 ncurses-devel -y;\
cd /usr/local/src;\
mkdir php mysql httpd pcre;\
cd /usr/local/src/pcre;\
curl -O http://jaist.dl.sourceforge.net/project/pcre/pcre/8.39/pcre-8.39.tar.gz;\
tar -xzf pcre-8.39.tar.gz;\
cd /usr/local/src/pcre/pcre-8.39;\
chown -R root . && chgrp -R root .;\
./configure && make install;\
cd /usr/local/src/httpd;\
curl -O http://mirrors.cnnic.cn/apache//httpd/httpd-2.4.23.tar.gz;\
tar -xzf httpd-2.4.23.tar.gz;\
cd /usr/local/src/httpd/httpd-2.4.23/srclib;\
curl -O http://mirrors.cnnic.cn/apache//apr/apr-1.5.2.tar.gz && curl -O http://mirrors.cnnic.cn/apache//apr/apr-iconv-1.2.1.tar.gz && curl -O http://mirrors.cnnic.cn/apache//apr/apr-util-1.5.4.tar.gz;\
tar -xzf apr-1.5.2.tar.gz && mv apr-1.5.2 apr && tar -xzf apr-iconv-1.2.1.tar.gz && mv apr-iconv-1.2.1 apr-iconv && tar -xzf apr-util-1.5.4.tar.gz && mv apr-util-1.5.4 apr-util; \
cd /usr/local/src/httpd/httpd-2.4.23;\
chown -R root . && chgrp -R root .;\
cd /usr/local/src/httpd/httpd-2.4.23/srclib/apr;\
./configure && make;\
cd /usr/local/src/httpd/httpd-2.4.23/srclib/apr-util;\
./configure --with-apr=../apr && make;\
cd /usr/local/src/httpd/httpd-2.4.23/;\
./configure --prefix=/usr/local/httpd2.4 --enable-mods-shared=all --with-mpm=worker --with-included-apr && make install;\
cd /usr/local/src/mysql;\
curl -O http://cdn.mysql.com//Downloads/MySQL-5.7/mysql-boost-5.7.15.tar.gz;\
tar -xzf mysql-boost-5.7.15.tar.gz;\
cd /usr/local/src/mysql/mysql-5.7.15;\
chown -R root . && chgrp -R root .;\
cmake -DCMAKE_INSTALL_PREFIX=/usr/local/mysql5.7 -DMYSQL_DATADIR=/usr/local/mysql5.7/data  -DWITH_BOOST=boost/boost_1_59_0 -DSYSCONFDIR=/usr/local/mysql5.7/etc -DWITH_MYISAM_STORAGE_ENGINE=1 -DWITH_INNOBASE_STORAGE_ENGINE=1 -DWITH_PARTITION_STORAGE_ENGINE=1 -DWITH_FEDERATED_STORAGE_ENGINE=1 -DWITH_BLACKHOLE_STORAGE_ENGINE=1 -DENABLED_LOCAL_INFILE=1 -DEXTRA_CHARSETS=all -DDEFAULT_CHARSET=utf8 -DDEFAULT_COLLATION=utf8_general_ci -DMYSQL_UNIX_ADDR=/tmp/mysql.sock && make install;\
```

**Steps to reproduce the issue:**

```
1./usr/bin/file: No such file or directory
2.tar extracted files with wrong auth.
3.
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 28
 Running: 0
 Paused: 0
 Stopped: 28
Images: 6
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-202285117-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.85 GB
 Data Space Total: 107.4 GB
 Data Space Available: 35.89 GB
 Metadata Space Used: 8.987 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.86 GiB
Name: localhost.localdomain
ID: YE5C:Y4AF:WG5L:E4SN:SNZG:SJWT:WIGI:QXPM:XSIQ:LDY4:P4MI:CUZA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox run in CentOS

**Comment by tonistiigi** [comment]
Sorry, I don't understand this report. Your dockerfile is not a dockerfile but a single long command. I'm not sure what "tar command" or extraction step you talking about during build.

**Comment by GanLuo96214** [comment]
Tar Problem:

    # docker run --rm -ti centos:7
    # cd /usr/local/src
    # curl -O http://jaist.dl.sourceforge.net/project/pcre/pcre/8.39/pcre-8.39.tar.gz
    # tar -xzf pcre-8.39.tar.gz
    # ls -l

0777  | I don't know this | owner | group | size | date | filename
----- | ----------------- | ----- | ----- | ---- | ---- | --------
drwxr-xr-x |  7 | 1169 | 1169 | 4096 | Jun 14 09:27 | pcre-8.39
-rw-r--r-- | 1 | root | root | 2062258 | Oct  6 17:41 | pcre-8.39.tar.gz

   please look at the owner and the group. @tonistiigi

**Comment by GanLuo96214** [comment]
sry about what I post my dockerfile problem,it's my mistake, and it's fixed.
can u see up one about tar problem?

**Comment by thaJeztah** [comment]
In your above example - what would be your expected result?

**Comment by GanLuo96214** [comment]
I want the files or dir belong who unzip him.

**now:**

    #whoami
    root
    #ls -l

| 0777 | I don't know this | owner | group | size | date | file
|------|------------------|-------|-------|-----|------|----|
| -rw-r--r-- | 1 | root | root | 22746881 | Oct 30 21:09  | node-v4.6.0.tar.gz |

   #tar -xzf node-v4.6.0.tar.gz
   #ls -l
   
| 0777 | I don't know this | owner | group | size | date | file
|------|------------------|-------|-------|-----|------|----|
| drwxr-xr-x | 9 | 502 | games | 4096 | Sep 27 23:58  | node-v4.6.0 |
| -rw-r--r-- | 1 | root | root | 22746881 | Oct 30 21:09  | node-v4.6.0.tar.gz |


**want:**

   #tar -xzf node-v4.6.0.tar.gz
   #ls -l
   
| 0777 | I don't know this | owner | group | size | date | file
|------|------------------|-------|-------|-----|------|----|
| drwxr-xr-x | 9 | root | root | 4096 | Sep 27 23:58  | node-v4.6.0 |
| -rw-r--r-- | 1 | root | root | 22746881 | Oct 30 21:09  | node-v4.6.0.tar.gz |


please notice file owner and group and date. it's all different, I don't know this is a bug or just for safe or maybe some other reason.

**Comment by GanLuo96214** [comment]
ping @thaJeztah Xp
