### ISSUE TITLE
hcsshim::ImportLayer failed in Win32: The system has attempted to load or restore a file into the registry, but the specified file is not in a registry file format. (0x3f9)

### ISSUE THREAD

**Issue by jsharland** [docker/docker#27193]
**Description**

I am using a Windows Server 2016 TP5 image in Azure and have been trying to get a docker image running any of the latest dotnet core images. I keep getting an error that the "system has attempted to load or restore a file into the regitry, but the specified file is not in a registry file format". It doesn't matter which image i use, I have tried with both the microsoft/iis and microsoft/dotnet images.

**Steps to reproduce the issue:**
1. Create a new Windows Server 2016 TP5 image in Azure
2. From a powershell prompt running as administrator run the following command
docker pull microsoft/iis

**Describe the results you received:**
I get the following output from running the command:

Using default tag: latest
latest: Pulling from microsoft/iis

9c7f9c7d9bc2: Pull complete
081af1807c20: Extracting [==================================================>] 112.2 MB/112.2 MB
552bd0bc6fa3: Download complete
0964ce0f4e6c: Download complete
failed to register layer: re-exec error: exit status 1: output: time="2016-10-06T14:23:55Z" level=error msg="hcsshim::ImportLayer failed in Win32: The system has attempted to load or restore a file into the registry, but the specified fileis not in a registry file format. (0x3f9) layerId=\\\\?\\C:\\ProgramData\\docker\\windowsfilter\\58809e452bef80e124f8419de1faf4c2743ffa1600fce89708f3b6c886fd34cd flavour=1 folder=C:\\Windows\\TEMP\\hcs289281991" hcsshim::ImportLayer failed in Win32: The system has attempted to load or restore a file into the registry, but the specified file is not in a registry file format. (0x3f9) layerId=\\?\C:\ProgramData\docker\windowsfilter\58809e452bef80e124f8419de1faf4c2743ffa1600fce89708f3b6c886fd34cd flavour=1 folder=C:\Windows\TEMP\hcs289281991

**Describe the results you expected:**
I expected to get the image downloaded so that I could see it when I run "docker images"

**Additional information you deem important (e.g. issue happens only occasionally):**
This has happened on all attempts I have made to pull an image.

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat overlay null
Swarm: inactive
Security Options:
Kernel Version: 10.0 14300 (14300.1061.amd64fre.rs1_release_svc.160907-0755)
Operating System: Windows Server 2016 Datacenter Technical Preview 5
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14 GiB
Name: dockervm
ID: VONV:UZA5:A7H2:J4PK:WCTE:MXW4:LFRA:GPC6:CVVS:KUOA:5HRF:BWEW
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Microsoft Azure VM running the Windows Server 2016 Datacenter Technical Preview 5 image, using a DS3_V2 Standard vm size. No additional configuration done to the server from what is provisioned.

**Comment by friism** [comment]
Can you try using the TP5-tag? Eg. `docker pull microsoft/iis:TP5`.

While there's not yet a preview image on Azure, I really recommend using the RTM preview instread:

 * https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-technical-preview
 * https://blog.docker.com/2016/09/build-your-first-docker-windows-server-container/

**Comment by jsharland** [comment]
Thank you @friism for you comment. Using the TP5 tag did download the image successfully. I am going to try and work out how I can use the full windows server 2016 evaluation.
