### ISSUE TITLE
Cannot create service with network parameter via Docker Remote API

### ISSUE THREAD

**Issue by fslev** [docker/docker#27190]
Hi,
Does anyone knows how to specify the network parameter (name and driver) while creating a docker service via Docker Remote API ?
I'm doing it like this:
POST: http://vm-test1.sandbox.lan:2375/services/create
Body:
>{
	"Name": "test-service",
	"TaskTemplate": {
		"ContainerSpec": {
			"Image": "vm-test1.sandbox.lan:5000/test-image"
		},
		"LogDriver": {
			"Name": "syslog",
			"Options": {
				"tag": "test-service"
			}
		},
		"EndpointSpec": {
			"Ports": [{
				"Protocol": "tcp",
				"PublishedPort": 10080,
				"TargetPort": 8080
			}]
		}
	},
	"Networks": [{
		"Name": "test_network",
		"Driver": "overlay"
	}]
}

However, I get a 403 Forbidden message:
`{"message":"network bridge is not eligible for docker services"}`

> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
c97a6c216498        bridge              bridge              local               
ew1wt4xa5olk        test_network        overlay             swarm               
6ae7e1d9fe4b        docker_gwbridge     bridge              local       

I believe that something is wrong inside my JSON request,  at "Networks" field.

Docker Remote API v1.24

> Create a service
> POST /services/create
> ...
> Networks – Array of network names or IDs to attach the service to.

**Comment by cpuguy83** [comment]
"bridge" networks (and all node-local networks) are not supported in swarm mode yet.
See #27082

**Comment by fslev** [comment]
I know.
The network which I want the service to use ("test_network") is of type overlay and scope swarm.
So it is nothing wrong with this. I can create the service with this network parameter , directly via Docker CLI

> docker service create --name test-service --network test_network test-image

However, via Docker Remote API I can't. 
Again, it is possible that the "Networks" parameter from the JSON request to be invalid.

**Comment by cpuguy83** [comment]
Sorry... have a bit of jet lag atm...

Yes it looks like your `Networks` section is not right.
See: https://github.com/docker/docker/blob/master/api/types/swarm/network.go#L74

**Comment by fslev** [comment]
is it me or it seems that the Network struct doesn't support the "name" field ?

**Comment by cpuguy83** [comment]
I believe `Target` is the name... based on the CLI code for `service create`.

**Comment by fslev** [comment]
Indeed, Target it is:

> "Networks":[
          {"Target":"cams_network"}
    ]

Thanks a lot,

**Comment by vranganatha2** [comment]
Thanks a lot this discussion helped me as well

**Comment by janie128** [comment]
Thanks this helped me too! Would be great if this was in the docker engine api examples for create service.

**Comment by stychos** [comment]
Oh, please, reflect this in the documentation (the `Target: Name` format), because there's only words about "array of names or network IDs", and I spent a lot of time thinking there's some bug :)

**Comment by thaJeztah** [comment]
Looks like the type is described here in the swagger file https://github.com/docker/docker/blob/master/api/swagger.yaml#L2068-L2078, and I _think_ the sample request is defined here, https://github.com/docker/docker/blob/master/api/swagger.yaml#L7426-L7495, but perhaps you're interested in looking into this and updating the example request? There's a README describing how the docs can be updated / previewed https://github.com/docker/docker/tree/master/api#updating-the-api-documentation
