### ISSUE TITLE
x509: certificate is valid for old_ip, not new_ip. 

### ISSUE THREAD

**Issue by Omnipresent** [docker/docker#27199]
**Description**
I've created a docker trusted registry on AWS. I am trying to test out pushing an image from my local server up to the newly created registry on AWS. Since the trusted registry is for testing purpose, I've removed any authentication from it and I do not care about HTTPS at the moment. 

When I first tried to push the image I got an error that the certificate is invalid. So I added the following to `/etc/init.d/docker` `DOCKER_OPTS="--insecure-registry <ip>.compute-1.amazonaws.com"`. In the mean time I had restarted my AWS EC2 instance so the IP address to access the trusted registry changed. So I tagged the image according to the new IP address.

However, now when I try to push the image I get the following error:

```
Get https://<new_ip>.compute-1.amazonaws.com/v1/_ping: x509: certificate is valid for <old_ip>.compute-1.amazonaws.com, not <new_ip.compute-1.amazonaws.com
```

**Steps to reproduce the issue:**
0. Tag image with `<currentip>.compute-1.amazonaws.com/foo/bar`
1. Try to push the above tagged image to a trusted registry (running in AWS) with an invalid certificate
2. Restart the trusted registry instance so that the IP address changes
3. Add `DOCKER_OPTS="--insecure-registry <newip>.compute-1.amazonaws.com"` to `/etc/init.d/docker`
4. Restart docker with `sudo service docker restart`
5. Tag the image with `<newip>.compute-1.amazonaws.com/foo/bar`
6. Tru to push the above tagged image
7. Observe error:

`Get https://<newip>.compute-1.amazonaws.com/v1/_ping: x509: certificate is valid for <oldip>.compute-1.amazonaws.com, not <newip>.compute-1.amazonaws.com`

**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 22
 Running: 0
 Paused: 0
 Stopped: 22
Images: 51
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 122
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.963 GiB
Name: prototype
ID: UFHV:DAPP:QTP3:TJRQ:R4LM:FP56:DG6L:R6IF:GTZH:W7SW:BKTH:H66Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**box from where image is being pushed**
Debian GNU/Linux 8 \n \l

**Docker trusted registry that the image is being pushed to**

The docker trusted registry is being run in AWS and was created using Docker Trusted Registry AMI from the AWS marketplace. As described in this video https://www.youtube.com/watch?v=t7yQPbfvYvs

**Comment by cpuguy83** [comment]
I see you are on debian jessie.
Jessie uses systemd by default, and in such a case, setting DOCKER_OPTS in /etc/init.d/docker is not going to do anything... nor in /etc/default/docker.

The best thing to do is to set the insecure registry in `/etc/docker/daemon.json`, which by default doesn't exist but docker will read from it.
Details on this file are here: https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

Please let me know if this resolves your issue.

**Comment by thaJeztah** [comment]
Looks like this question is answered, but feel free to comment if you need more info
