### ISSUE TITLE
fakeroot/fakeroot-sysv/fakeroot-tcp sometimes hangs with docker

### ISSUE THREAD

**Issue by m4h3** [docker/docker#27195]
**Description**

fakeroot seems to be broken with docker. This is a quite non-reproductible bug as it happens randomly (I would say 40% of the time), but this seems to be depending on load.

**Steps to reproduce the issue:**
1. use this dockerfile in some "test" directory:

```
FROM debian:latest
RUN apt-get update && apt-get install -y fakeroot python strace
```

2. build it with `docker build -t testdebian test/`
3. `docker run -ti --rm  testdebian fakeroot python`

**Describe the results you received:**

Hangs very randomly. Python console not showing.

However, python looks started:
```
$ pstree -s 7795
systemd───dockerd───docker-containe───docker-containe───fakeroot───python
```

stracing python from outside looks like:
```
strace: Process 7795 attached
semop(32768, [{0, -1, SEM_UNDO}], 1
```

stracing python from inside slows everything and the bug does not appear (...) 

killing the process from sigterm:
```
$docker run -ti --rm  testdebian fakeroot python
^C/usr/bin/fakeroot: line 1: kill: (13) - No such process
/usr/bin/fakeroot: line 1: kill: (13) - No such process
```

**Describe the results you expected:**

python started normally.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is a really occasional bug. Does not happen easily.
I've tested other fakeroot flavors (sysv and tcp), either hang of fails.

I've found some issues that looks like the same, but related to qemu or solaris (!)
[qemu with fakeroot and dh](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=707626)
[other bug related to solaris](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=171394)

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker info
Containers: 40
 Running: 0
 Paused: 0
 Stopped: 40
Images: 141
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 148
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: Latitude-E6430
ID: PRIVACY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
Are you getting the error `semop(2): encountered an error: Invalid argument`? I am, wanted to check if I was finding the same issue.

**Comment by m4h3** [comment]
Currently, i'm not getting this invalid argument semop thing.
But this looks familiar as i've already saw this.

**Comment by thaJeztah** [comment]
@justincormack did you manage to narrow down this issue?

**Comment by AkihiroSuda** [comment]
Command| Result (seems deterministic)
--- | --- 
`docker run -ti --rm testdebian fakeroot python` | Hangs
`docker run -ti --rm testdebian sh`, then execute `fakeroot python` manually inside the container| Works :smiley:
`docker run -ti --init --rm testdebian fakeroot python` | Hangs
`docker run -ti --rm testdebian sh -c fakeroot python` | Hangs

The result is weird.
Trying to analyze..

(master docker a2ad359, Ubuntu 16.04, kernel 4.4.0-42-generic, overlay2, amd64)

**Comment by AkihiroSuda** [comment]
I can hit `semop(2): encountered an error: Invalid argument` intermittently, but basically it hangs on my environment

**Comment by AkihiroSuda** [comment]
As @m4h3 reported, the issue does not appear if tty is not enabled.

Command | Result
--- | ---
`docker run -t  --rm testdebian fakeroot python -c 'print("hello")'` | Hang
`docker run --rm testdebian fakeroot python -c 'print("hello")' `| Works :smiley: 

Wondering if related to mounts...

**Comment by justincormack** [comment]
I think it is probably a bug in `fakeroot` but it is hard to tell. It does have a daemon, which could behave differently with or without a `tty`.

(What is the use case for `fakeroot` given you can use actual root if needed)?

**Comment by m4h3** [comment]
The use case was a naive port of a .deb build env from a dev environment chroot to a container base solution.
The fakeroot call appears after a USER statement from a Dockerfile, so it does need fakeroot IMHO, as most of the legacy build code expect not to be root anyway. I guess one solution is to transform fakeroot into `docker run -u 0 ....`, but the fact that it's a race should be a motivator to say 'it almost works lets fix it"

**Comment by m4h3** [comment]
The difference between hangs or fails depends on spawned daemon by fakeroot : faked. For some unknown reason, this one seems to randomly die prematurely, locking the fakerooted process in a IPC deadlock.

**Comment by AkihiroSuda** [comment]
I think I have determined the cause of the isssue: 

# `faked` dies when it received `SIGWINCH` (signal 28).

`fakeroot` seems not tolerant of fault in `faked` and hence hangs up.

## Without TTY
It works because it won't get `SIGWINCH`
```
$ docker run --rm testdebian faked-sysv --foreground --debug
using 2062561217 as msg key
msg_key=2062561217
FAKEROOT: msg=0, key=2062561217
2062561217:7
(keeps running as expected...)
```

```console
$ docker run --rm testdebian faked-tcp --foreground --debug
41843:7
fakeroot: detached=0 clients=0
(keeps running as expected...)
```

## WIth TTY
`faked` tends to die when it received `SIGWINCH` (28).

```console
$ docker run it  --rm testdebian faked-sysv --foreground --debug
using 1990170604 as msg key
msg_key=1990170604
1990170604:7
FAKEROOT: msg=0, key=1990170604
fakeroot: clearing up message queues and semaphores, signal=28
(exit with status 0)
```

```console
docker run -t --rm testdebian faked-tcp --foreground --debug
44731:7
fakeroot: detached=0 clients=0
fakeroot: signal=28
(exit with status 0)
```

It doesn't die if we injected some `sleep` because it begins running after `SIGWINCH` is issued.
```console
$ docker run -t --rm testdebian sh -c 'sleep 1; faked-sysv --foreground --debug'
using 812479523 as msg key
msg_key=812479523
812479523:8
FAKEROOT: msg=0, key=812479523
(keeps running as expected...)
```

But it dies if you resize the terminal :sweat_smile: 


IMO this is a issue of fakeroot and there is no need to fix the issue on Docker side.
@thaJeztah Please remove the labels (`area/runtime`, `kind/bug`)?
@m4h3 Please close the issue if my understanding is correct?

**Comment by m4h3** [comment]
I guess you nailed it:
https://github.com/mackyle/fakeroot/blob/master/faked.c#L1446 and 
https://github.com/mackyle/fakeroot/blob/master/faked.c#L1480 are responsible for calling cleanup on any signal received.

**Comment by m13253** [comment]
For some reason I can’t explain, by letting `faked` write its output to a file then read it back, rather than using a pipe to capture its output, seems to fix the issue:
```diff
--- /usr/bin/fakeroot.old	2024-06-06 06:38:53 +0000
+++ /usr/bin/fakeroot.new
@@ -138,7 +138,10 @@
 fi

 unset FAKEROOTKEY
-KEY_PID=`eval $FAKED $FAKEDOPTS $PIPEIN`
+KEY_PID_FILE="$(mktemp)"
+eval $FAKED $FAKEDOPTS $PIPEIN >"$KEY_PID_FILE"
+KEY_PID="$(cat -- "$KEY_PID_FILE")"
+rm -f -- "$KEY_PID_FILE"
 FAKEROOTKEY=`echo $KEY_PID|cut -d: -f1`
 PID=`echo $KEY_PID|cut -d: -f2`

```

**Comment by AlanIWBFT** [comment]
> For some reason I can’t explain, by letting `faked` write its output to a file then read it back, rather than using a pipe to capture its output, seems to fix the issue:
> 
> ```diff
> --- /usr/bin/fakeroot.old	2024-06-06 06:38:53 +0000
> +++ /usr/bin/fakeroot.new
> @@ -138,7 +138,10 @@
>  fi
> 
>  unset FAKEROOTKEY
> -KEY_PID=`eval $FAKED $FAKEDOPTS $PIPEIN`
> +KEY_PID_FILE="$(mktemp)"
> +eval $FAKED $FAKEDOPTS $PIPEIN >"$KEY_PID_FILE"
> +KEY_PID="$(cat -- "$KEY_PID_FILE")"
> +rm -f -- "$KEY_PID_FILE"
>  FAKEROOTKEY=`echo $KEY_PID|cut -d: -f1`
>  PID=`echo $KEY_PID|cut -d: -f2`
> ```
> 
> Not sure if this would introduce any security issues though.

A `ulimit -Ha` returns a pipe size of 8, which might explain

**Comment by trinitronx** [comment]
Although this issue is closed...

Seems that there is also still the bug in `fakeroot` mentioned by @nhed in [this comment][1].  I stumbled across that issue which has the same symptoms: `fakeroot` hangs in docker containers.

The symptoms in this case were also:

- `faked` process runs using `100%` CPU in the container (spawned by `makepkg` + `fakeroot`)
- Interrupt with <kbd>Ctrl</kbd>+<kbd>c</kbd> and it logs:

      fakeroot internal error #43: Identifier removed
      semop(2): encountered an error: Invalid argument
      /usr/bin/fakeroot: line 1: kill: (NNNNN) - No such process

I've been able to reproduce by trying to build Arch Linux packages with `makepkg` inside a docker container.  Using QEMU + Arm64 via `binfmt_misc` also makes it even slower due to emulation layer.  Seems the same as [this issue][2].

Workaround was effective, passing a smaller number of file limit via `--ulimit nofile=1024:524288` to `docker run` command.  Then `fakeroot` doesn't spin dealing with all the possible fd's.

[1]: https://github.com/moby/moby/issues/27195#issuecomment-1410745778
[2]: https://bugs.archlinux.org/task/61566
