### ISSUE TITLE
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided

### ISSUE THREAD

**Issue by Murf** [docker/docker#27208]
**Description**
```
$ docker deploy test
Loading bundle from test.dab
Creating network test_default
Creating service test_web
Creating service test_db
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided
```

I am following this tutorial:
http://blog.couchbase.com/2016/july/docker-services-stack-distributed-application-bundle

**Output of `docker version`:**
```
$ docker --version
Docker version 1.12.2-rc2, build ad9538a, experimental
$ docker-compose --version
docker-compose version 1.8.1, build 878cff1
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 84
Server Version: 1.12.2-rc2
Storage Driver: devicemapper
 Pool Name: docker-253:0-105335-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.727 GB
 Data Space Total: 107.4 GB
 Data Space Available: 42.08 GB
 Metadata Space Used: 15.2 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.132 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: active
 NodeID: d85uyvzk62u9tcc3ea9svxhz2
 Is Manager: true
 ClusterID: dnei7dxkorw97wwa2sei3vbit
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.101.169
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 7.633 GiB
Name: dr-host
ID: BTUN:L4DP:LBBK:6GYY:ELP4:5QVA:RAXG:JGMO:XWJ7:LZNE:2VFN:SO37
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 dr-host:5000
 127.0.0.0/8

*** SWARM CONFIG
1 Leader, 3 extra nodes
I am running the above commands on the leader
```

**Comment by aluzzardi** [comment]
Could you post the output of `docker service ls`?

And for each service, the output of `docker service inspect <service name>`

**Comment by idugalic** [comment]
I am experiencing the same issue.
_Docker version 1.12.2, build bb80604, experimental_
_docker-compose version 1.8.1, build 878cff1_

I have some example project, and I am running this [script](micro-company/docker/swarm-mode-local.sh) (all docker images are publicly available)
The problematic line is:  **docker deploy --file [micro-company.dsb](micro-company/docker/micro-company.dsb) micro-company**

**Comment by Murf** [comment]
$ docker deploy test
Loading bundle from test.dab
Creating network test_default
Creating service test_db
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided
$ docker service ls
ID  NAME  REPLICAS  IMAGE  COMMAND


No services seem to start.

**Comment by thaJeztah** [comment]
@Murf do you have any other container or service running that's using a port you're trying to publish? Is this still with the original example you reported with, or can you post the content of the .dab file?

**Comment by Murf** [comment]
Hi,
Still using the original example, and there are no other containers with any of the ports in the example

**Comment by Thubo** [comment]
IMHO the issue occurs when there is a definition of multiple ports:

The following example breaks as well (There are not other services running on the given ports).

```
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
```
(excerpt from docker-compose.yml)

All examples given so far have more than one value in the `ports` element.

**Comment by thaJeztah** [comment]
I reproduced this on 1.12.2 and on master c028a88, and can confirm it's a regression in 1.12.2

I wonder if this is related to https://github.com/docker/docker/issues/27390, although there's no combined udp/tcp involved here.

To reproduce, the simplest docker-compose.yml, and `.dab` file;

```yaml
version: "2"
services:
  web:
    image: nginx:alpine
    ports:
      - 80
      - 443
```

```json
{
  "Services": {
    "web": {
      "Image": "nginx@sha256:36b95728c0d9b6668bb8e4aa31476de27aeedbeba07dcddb6821b76fb72830b2",
      "Networks": [
        "default"
      ],
      "Ports": [
        {
          "Port": 80,
          "Protocol": "tcp"
        },
        {
          "Port": 443,
          "Protocol": "tcp"
        }
      ]
    }
  },
  "Version": "0.1"
}
```

**Comment by aluzzardi** [comment]
Should this be closed?

The PR closing this is bumping vendoring on master, I'm afraid we'll forget to cherry pick

**Comment by thaJeztah** [comment]
@aaronlehmann @vieux was this cherry picked into 1.12.3 as well?

**Comment by jgrabenstein** [comment]
Did this make it in? Any idea when an experimental build with this fix will be available?

**Comment by aaronlehmann** [comment]
> @aaronlehmann @vieux was this cherry picked into 1.12.3 as well?
> 

Yes. I only closed it after it was merged on both branches.

**Comment by aluzzardi** [comment]
1.12.3?

**Comment by aaronlehmann** [comment]
Yes.
