### ISSUE TITLE
Can not START, UPGRADE or UNINSTALL Docker in Windows 10, stuck at "Preparing Docker VM upgrade"

### ISSUE THREAD

**Issue by hasMobi** [docker/docker#27219]
**Description**

I have successfully installed Docker on Windows 10 and runned it for a while but somewhere in time - it just broke and was failing with "Unable to start Docker service" every time I start the computer.

Now I can neither:
1. Start it.
2. Uninstall it.
3. Upgrade it.

**Steps to reproduce the issue:**
1. Start Docker from the start menu or:
2. Download the new Docker installer from the beta channel and try to install it.

**Describe the results you received:**
If I try to launch a hello world example, I get this:
![image](https://cloud.githubusercontent.com/assets/9678143/19200743/501cc5bc-8cd3-11e6-8fb7-3539ffe1166b.png)

If I try to install the new version it gets stuch at:
![image](https://cloud.githubusercontent.com/assets/9678143/19200750/5ec84906-8cd3-11e6-9138-534dbb4cdb9b.png)

**Describe the results you expected:**
Either to be launch a container, install the new version of Docker or at least uninstall the old version to start fresh.

**Additional information you deem important (e.g. issue happens only occasionally):**

Windows 10 Professional, 64 bit

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:32:24 2016
 OS/Arch:      windows/amd64
 Experimental: true
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/version: open //./pipe/docker_engine: The system cannot find the file specified.
```

**Output of `docker info`:**

![image](https://cloud.githubusercontent.com/assets/9678143/19200805/9311f7d4-8cd3-11e6-9026-07ef252e8b0c.png)

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical computer with Hyper-V enabled.

**Comment by friism** [comment]
@hasMobi Thanks for reporting. Since this issue is about Docker for Windows, could I ask you to please close and re-open on the dedicated issue tracker for that product? https://github.com/docker/for-win/issues

Please also use the built-in diagnostic tool to create a dump that will help us debug the problem.

**Comment by flagtrax** [comment]
I recently installed docker at the recommendation of the nodeMCU Github site. I immediately found it was not what I needed. I never used it and can't uninstall it. in fact It won't even allow me to delete the files in command mode. dis allowing me access... Most disturbing to say the least. I'd like these files off my system!

**Comment by thaJeztah** [comment]
For docker for Windows (not native Windows containers), please report issues at https://github.com/docker/for-win/issues as mentioned above. I'll close this issue here
