### ISSUE TITLE
Using a seccomp profile failing with "oci runtime error: empty string is not a valid syscall"

### ISSUE THREAD

**Issue by pcgeek86** [docker/docker#27224]
**Description**

We are running a container with the default Docker seccomp profile, by using: `docker run --security-opt seccomp=/path/to/default.json`. When we do this, we immediately receive an error.

**Steps to reproduce the issue:**
1. Download the default Docker seccomp profile
2. Run a container with `--security-opt seccomp=/path/to/seccompfile.json`

**Describe the results you received:**

Received an error message from the daemon:

> docker: Error response from daemon: oci runtime error: empty string is not a valid syscall.

**Describe the results you expected:**

We expected the container to run successfully, with the default (unmodified) Docker seccomp profile.

We used the default Docker seccomp profile, with no modifications.

**Output of `docker info`:**

Containers: 39
Running: 0
Paused: 0
Stopped: 39
Images: 59
Server Version: 1.12.1
Storage Driver: devicemapper
Pool Name: docker-259:4-53084885-pool
Pool Blocksize: 65.54 kB
Base Device Size: 10.74 GB
Backing Filesystem: xfs
Data file: /dev/loop0
Metadata file: /dev/loop1
Data Space Used: 4.02 GB
Data Space Total: 107.4 GB
Data Space Available: 103.4 GB
Metadata Space Used: 7.184 MB
Metadata Space Total: 2.147 GB
Metadata Space Available: 2.14 GB
Thin Pool Minimum Free Space: 10.74 GB
Udev Sync Supported: true
Deferred Removal Enabled: false
Deferred Deletion Enabled: false
Deferred Deleted Device Count: 0
Data loop file: /var/lib/docker/devicemapper/devicemapper/data
WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
Library Version: 1.02.122 (2016-04-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.7.6-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54 GiB
Name: redacted
ID: 3WAS:YWEK:SCM4:5MGN:MAUN:XHTX:2VGU:SQB2:VGNP:3VWN:3QUG:SN4O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
127.0.0.0/8

Cheers,
**Trevor Sullivan**
Docker Captain
Microsoft MVP: Cloud & Data Center Management
https://trevorsullivan.net
https://twitter.com/pcgeek86

**Comment by justincormack** [comment]
Is that the default profile from git master? We made a format change and
while old profiles are compatible with new docker, the new default will not
work with released Docker.

**Comment by pcgeek86** [comment]
@justincormack Yes it's from Git master. What's the best path to resolution?

**Comment by justincormack** [comment]
Use the one from the 1.12 branch or the tag for eg 1.12.1. It only changed
once so any version before the change will be the same.

**Comment by pcgeek86** [comment]
@justincormack Can I just install the newer Docker Engine that supports the new format? Not released yet?

**Comment by justincormack** [comment]
No this will be released with 1.13.
