### ISSUE TITLE
Docker Swarm on ARM won't reconnect on reboot

### ISSUE THREAD

**Issue by huhlig** [docker/docker#27243]
This is running on a 6 node Raspberry Pi 3 cluster running HyperiotOS 1.0.0 Blackbeard with DHCP allocated static addresses.

To Reproduce:

master> docker swarm init
worker> docker swarm join --token <Token> 192.168.0.20:2377 

At this point the worker joins correctly. 

If the slave is rebooted. Its status never returns to READY and the only information provided is the following in /var/log/docker.log on the slave. However, if the node leaves and runs the join command again it works fine until the next reboot.

$ cat /var/log/docker.log
fatal error: rt_sigaction failure

runtime stack:
runtime.throw(0x14a17c0, 0x14)
        /usr/local/go/src/runtime/panic.go:547 +0x78
runtime.setsigstack(0x21)
        /usr/local/go/src/runtime/os1_linux.go:344 +0xec
runtime.initsig(0x1c6ad00)
        /usr/local/go/src/runtime/signal1_unix.go:75 +0x168
runtime.mstart1()
        /usr/local/go/src/runtime/proc.go:1094 +0xdc
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1068 +0x84

goroutine 1 [runnable]:
runtime.main()
        /usr/local/go/src/runtime/proc.go:105
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:990 +0x4

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_arm.s:990 +0x4

**Comment by aluzzardi** [comment]
@DieterReuter Have you ever seen this?

**Comment by aluzzardi** [comment]
@huhlig Could you provide the entire log file?

**Comment by aluzzardi** [comment]
@alexellis @justincormack @tianon Have you ever noticed this on ARM?

**Comment by alexellis** [comment]
Hi - I didn't have this issue and I did a lot of rebooting. That said I haven't upgraded the Docker version yet to the latest release. I can try to repro next week.

**Comment by StefanScherer** [comment]
@huhlig I've tried rebooting swarm workers with HypriotOS 1.1.0 + docker 1.12.2 without problems.
Hypriot 1.0.0 has docker 1.12.1, so consider updating either through reflashing or `sudo apt-get update && sudo apt-get upgrade`.

**Comment by thaJeztah** [comment]
I'll go ahead and close this, but ping me if it's still an issue
