### ISSUE TITLE
Docker daemon command does not work on  1.13.0-dev build

### ISSUE THREAD

**Issue by Ch3ck** [docker/docker#27244]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
I just built the Docker development container on Fedora 22 using the latest clone from the docker master. When I try to run a docker daemon('docker daemon -D&') and 'dockerd -D&' in the background following the documentation; I get the following error: 
Command "daemon" is deprecated, and will be removed in Docker 1.16. 
Please run `dockerd` directly.
exec: "dockerd": executable file not found in $PATH

Secondly I try running dockerd -D&. I get this error:
1.) bash: dockerd: command not found

**Steps to reproduce the issue:**
1. make shell
2. cp bundles/1.13.0-dev/binary-client/docker* /usr/bin 
3. docker daemon -D&
4. dockerd -D&

**Describe the results you received:**
```
root@ef16dbc09b92:/go/src/github.com/docker/docker# docker daemon -D& 
[1] 19079
root@ef16dbc09b92:/go/src/github.com/docker/docker# Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
exec: "dockerd": executable file not found in $PATH
^C
[1]+  Exit 1                  docker daemon -D
root@ef16dbc09b92:/go/src/github.com/docker/docker# dockerd -D&
[1] 19083
root@ef16dbc09b92:/go/src/github.com/docker/docker# bash: dockerd: command not found
^C
[1]+  Exit 127                dockerd -D
```
**Describe the results you expected:**
```
ash root@a8b2885ab900:/go/src/github.com/docker/docker# docker daemon -D& ...output snipped... DEBU[0001] Registering POST, /networks/{id:.*}/connect DEBU[0001] Registering POST, /networks/{id:.*}/disconnect DEBU[0001] Registering DELETE, /networks/{id:.*} INFO[0001] API listen on /var/run/docker.sock DEBU[0003] containerd connection state change: READY
```
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ef16dbc09b92:/go/src/github.com/docker/docker# docker --version
Docker version 1.13.0-dev, build 920aa95
```

**Output of `docker info`:**

```
root@ef16dbc09b92:/go/src/github.com/docker/docker# docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This is within my development container. But below is the information of my physical host.
```
[localhost@localhost hello]$ docker info
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 96
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-1057835-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.09 GB
 Data Space Total: 107.4 GB
 Data Space Available: 14.71 GB
 Metadata Space Used: 9.765 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.138 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.0.4-301.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.327 GiB
Name: localhost.localdomain
ID: SN3L:CUIC:XRDI:LH7Q:M6YY:JZTY:HBZ3:PR4X:26I2:MDUT:NR3H:LKXC
Username: ch3ck
Registry: https://index.docker.io/v1/
[localhost@localhost hello]$ docker --version
Docker version 1.10.3, build 20f81dd
[localhost@localhost hello]$
```

**Comment by coolljt0725** [comment]
@Ch3ck   you should use
`cp bundles/1.13.0-dev/binary-daemon/docker* /usr/bin` to copy the dockerd to your `/usr/bin`
dockerd is under the `bundles/1.13.0-dev/binary-daemon`

**Comment by Ch3ck** [comment]
@coolljt0725 Awesome, It works now. Is ok for me to Update the docker to reflect the changes from docker 1.12 where 'docker daemon' was deprecated and replaced by 'dockerd' ? I think it will be useful to alot of Gopher.

**Comment by justincormack** [comment]
I think the docs have been updated but they are not published for 1.13 yet as it is not released, they are just in the repository. If you can find anywhere where they were not updated please do file a PR though.

**Comment by Ch3ck** [comment]
Alright thanks @justincormack  Will do.

**Comment by thaJeztah** [comment]
@Ch3ck for installing the binaries in the build container, there's now also a `make install` that takes care of copying/moving all the binaries to the correct location;

```bash
make BIND_DIR=. binary shell
make install
dockerd --debug
```

I'll close this issue, because I think the question is answered, but feel free to continue the discussion
