### ISSUE TITLE
Can't create machine via docker driver on windows 10

### ISSUE THREAD

**Issue by Somebi** [docker/docker#27258]
Failed to create machine via powershell:

PS C:\Users\someb> docker-machine create --driver digitalocean 
Running pre-create checks...
Creating machine...
(manager1) Creating SSH key...
(manager1) Creating Digital Ocean droplet...
(manager1) Waiting for IP address to be assigned to the Droplet...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Error creating machine: Error detecting OS: OS type not recognized
PS C:\Users\someb> docker-machine ls
NAME           ACTIVE   DRIVER         STATE     URL                        SWARM   DOCKER    ERRORS
manager1   -        digitalocean   Running   tcp://139.59.190.81:2376           Unknown   Unable to query docker version: Get https://139.59.190.81:2376/v1.15/version:
dial tcp 139.59.190.81:2376: connectex: No connection could be made because the target machine actively refused it.
PS C:\Users\someb> docker-machine ssh manager1
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
PS C:\Users\someb>

**Comment by Somebi** [comment]
Machine is created, but it is useless at this point...

**Comment by Somebi** [comment]
Creation process is soooooooo long... Why it is so long? Can i provide some polling interval? Can it be printed? What is going on there... Ugh...

It staying until i press enter button... The instantly it goes to the next step... How is this even connected? Enter button and operations sequence. It's some specific of powershell or it's a bug in docker-machine creation process?

**Comment by Somebi** [comment]
Second time i have provided parameter --digitalocean-image ubuntu-16-04-x64, same effect. Error creating machine: Error detecting OS: OS type not recognized

It is creating machine about 8 minutes and then gives this error...
There is probably some timeout triggered and connection with the server is already dead and not retried for some unknown reason...

There is should be some verbosity parameter for docker-machine creation process. Would be nice to have such parameter for all operations.

--verbosity or log-level=debug etc.

To see actually what is going on AT THIS moment of time and not just sitting and looking on some text...

I'll have to debug with some network utility like tcpdump , to see what is actually going on there...

**Comment by justincormack** [comment]
Can you open this issue on the Docker Machine repo https://github.com/docker/machine/issues as you will be able to get support there, this is only for direct issues with the core Docker engine. I am going to close this issue here as the people here are unlikely to be able to help.
