### ISSUE TITLE
official docker shared storage plugins 

### ISSUE THREAD

**Issue by rajkumar49** [docker/docker#27254]
hi ,
any plan to build official docker storage plugins to map docker container volumes to shared storage like Ceph , AWS EBS or AWS s3, NFS etc? 
also i want this Shared storage data to work with Docker Swarm mode while the containers are failing over to new node .

**Comment by justincormack** [comment]
There exist plugins for most of these I believe. I am not aware of any plans to make them more official, although there is an ongoing process to improve the usability of plugins.

**Comment by rajkumar49** [comment]
thanks for the info

**Comment by rajkumar49** [comment]
since Docker is evolving faster , we need Docker engine with inbuilt storage adapters.

**Comment by rajkumar49** [comment]
https://github.com/rancher/convoy looks good and also works good .
