### ISSUE TITLE
Failed to mount docker command into container on Mac.

### ISSUE THREAD

**Issue by k82cn** [docker/docker#27251]
**Description**

**Steps to reproduce the issue:**
`docker run -v /usr/local/bin/docker:/usr/bin/docker -i -t ubuntu`

**Describe the results you received:**

`docker: Error response from daemon: mkdir /usr/local/bin/docker: file exists.`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens every time.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 26
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 177
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 7EBH:S636:WNO2:SQEV:ULXZ:6QHI:OJNK:UO3H:D5KJ:LW43:36WW:RVX7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2016-10-10T08:22:48.572517586Z
 EventsListeners: 1
Http Proxy: 9.21.58.21:3128
Https Proxy: 9.21.58.21:3128
Username: k82cn
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by justincormack** [comment]
What are you trying to achieve here? The `docker` binary on Docker for Mac in the VM is not in `/usr/local/bin` and the `docker` binary in that location on the Mac will not run on Linux. If you want `docker` in a container, I recommend you use the `get.docker.com` script, or a system package, or the `docker` official images on Hub.

**Comment by k82cn** [comment]
@justincormack , you're right. I'll use `get.docker.com` to handle it.
