### ISSUE TITLE
Docker overrides the IP address of my own manually created bridge

### ISSUE THREAD

**Issue by mne91** [docker/docker#27263]
I just sorted and wrote what I think is a bug here, please take a look and tell me what do you think, it is just exactly as the title, Docker always overrides the IP address of my own manually created bridge and ignores the ip address which I use for the birdge

http://serverfault.com/questions/808151/docker-overrides-the-ip-address-of-my-own-manually-created-bridge?noredirect=1#comment1026696_808151

**Comment by aboch** [comment]
@mne91 
On manual restart of docker, the bridge IP does not get overwritten.

I am guessing this has to do with some ordering at boot. Could it be docker is started before your bridge gets an IP assigned ? From the logs I am guessing your bridge gets an IP assigned via DHCP (which may in fact take some time).

**Comment by mne91** [comment]
@aboch 

I am not sure actually, I am creating the **bridge inside /etc/network/interfaces** file.

Could you tell me **how to prevent him from taking the ip from dhcp and force him to use what I wrote in interfaces** file?

**Comment by aboch** [comment]
@mne91 I am not sure, it may have to do with the fact you are enslaving your `eth0` interface into the bridge. Please try change that and see if the makes a difference. Or find out how to statically configure the IP address for your bridge.

**Comment by mavenugo** [comment]
@aboch i dont think this is a candidate for closing yet. We have to check the reproduction and if it is, then I think we should atleast document the behaviour. Especially as per the discussion in http://serverfault.com/questions/808151/docker-overrides-the-ip-address-of-my-own-manually-created-bridge, the author needs help with a recommended configuration.

**Comment by aboch** [comment]
@mne91 Assuming you are running a debian based distribution (from posting about `etc/networks/interfaces`) this link (https://www.howtoforge.com/debian-static-ip-address) for example should give you the info you need to statically configure the IP address for your `docker0` interface.

Based on the comments above, I think we should now close this issue as not docker specific.

**Comment by mavenugo** [comment]
Thanks @aboch.

@mne91 pls comment if you this issue should be re-opened.

**Comment by dylanpoe** [comment]
I just have the same issue, but another server works fine with the same config.
Used bridge util to create a bridge named kbr0, and configured dockerd options with -b=kbr0.
kbr0's address:172.17.3.1/24
after I restarted docker service, the address of kbr0 was changed to 172.18.0.1.

**Comment by sosozhuang** [comment]
I just have the same issue, but another server works fine with the same config.
Used bridge util to create a bridge named kbr0, and configured dockerd options with -b=kbr0.
kbr0's address:172.17.3.1/24
after I restarted docker service, the address of kbr0 was changed to 172.18.0.1.
