### ISSUE TITLE
Hostnames can't contain legal characters (and it shouldn't matter anyhow)

### ISSUE THREAD

**Issue by nbastin** [docker/docker#27275]
**Description**

Docker refuses completely legitimate hostnames:

```
$ sudo docker run -d -h foo.b_ar --name=1733310229999 --memory=64m --memory-swap=-1 --net="none" --cap-add=NET_RAW --cap-add=NET_ADMIN  bss.mdnsroot                                                                                                                                                    
docker: invalid hostname format for --hostname: foo.b_ar.
```

**Describe the results you expected:**

I expect it to launch my container.. :-)

**Additional information you deem important (e.g. issue happens only occasionally):**

This changed in 1.11 due to an apparent desire to be conformant to an RFC that is very inconsistently conformed to across various services.  More importantly (to me at least) this isn't really the right thing to do anyhow.  Docker containers are whatever I want them to be - if the code in the container can use a hostname with "illegal" characters, why can't I use them?

In practice this completely breaks our filter NFs for DKIM, as they rely on the hostname to seed the filter (and since you can't set the hostname inside the container, you are very limited in your workarounds).  It also presumes that your container is somehow a "host" in general - I already set `--net="none"`, why aren't the hostname rules constrained to the rules of the network I choose?

All that being said and philosophical arguments aside, the hostname used above is completely legal in all contexts.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 881
 Running: 881
 Paused: 0
 Stopped: 0
Images: 685
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1292
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 502.72 GiB
Name: <elided>
ID: X7WQ:D27D:XI7L:KJGR:ZK35:UM3N:QUZF:CQSA:65WX:WNH6:N4BV:3LTP
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical device.

**Comment by justincormack** [comment]
This is a consequence of #27067 as the thing we are setting as "hostname" is really the first part of the hostname (and should not contain dots), while the part after the dot should be setting the domain name, which can include underscores.

If #27067 is not going to be fixed, we should allow underscores after the first `.`.

**Comment by mostolog** [comment]
IMHO setting --hostname foo.domain.com doesn't looks very polite.

hostname is not the same as FQDN.

what _hostname_ command will return?
what name will be registered on /etc/hosts?
what name will be registered on DNS?

I think we are missing a --domain...anyway, I'll wait to https://github.com/docker/swarmkit/issues/1242

**Comment by masonoise** [comment]
This is a big issue for us in trying to upgrade to 1.12 from 1.10. In 1.10, our current hostnames work just fine with underscores in them. In testing 1.12 we can't even start any of our containers because there's a breaking change. It's this sort of unadvertised change without any deprecation warning that makes Docker so difficult to work with in production.

STRONG STRONG recommendation to fix this with a deprecation warning if you must, but right now we're completely blocked from upgrading because of this and the amount of time it will take to change our entire deployment mechanisms.

**Comment by cpuguy83** [comment]
@masonoise Is this old containers that were already created that can't start or new containers that can't be created?

Also, not disagreeing with the handling of deprecation here, however this is in the changelog for 1.11.0 and server-side validation should only be happening if the API version being used is >= 1.24 (docker 1.12).

**Comment by nbastin** [comment]
The changelog for 1.11.0 is wonderfully obtuse - it references adding support for an RFC that *NO OS* supports.  That RFC isn't even the right one - you have to dereference it to a related RFC to find that underscores are "not allowed" in hostnames, even though they're perfectly legal in any modern OS or DNS system.

The fact that this change was made unilaterally, as if every Docker user is an active participant in mailing lists and bug trackers, is crazy.  It should have gone through at LEAST one iteration of the tool reporting a deprecation warning, so that we could report that this was problematic before it actually become a firm requirement.  Docker deciding that it "knows better" than the container about what is a legal hostname is ridiculous.

We have moved 50k+ containers off of docker to another OCI runtime, and will move another 100k+ more soon (as well as all newly deployed sites), as the Docker community does not seem to care about users (or there would be a staged deprecation scheme, allowing users to provide feedback).  As such, obviously I no longer care about this problem, but it is indicative of a larger problem where Docker is advertised as being useful for more circumstances than it really is, and really you have to fit perfectly into the use case that the Docker maintainers support lest you find yourself screwed in a later version.

**Comment by cpuguy83** [comment]
@nbastin As stated for sure this community contribution slipped through the deprecation policy (for reference, documented here: https://docs.docker.com/engine/#feature-deprecation-policy, though recently changed from 2 release cycles to 3), in addition to the handling of the hostname/domain name split in the CLI.

@justincormack It looks like you looked at this a couple of times, WDYT? Is there a change that we ought to make for 1.13 (or maybe it's already resolved?)?

**Comment by masonoise** [comment]
@cpuguy83 I don't know anything about the API version (nor should I have to), and we're currently running 1.10 but wanted to test out 1.12 because of other storage-related bugs in 1.10. With this discovery, we now either work around the existing bugs or figure out how to modify every one of our deployments to deal with the hostname issue. Waiting until 1.13 and then discovering whatever bugs lurk in that one is not appealing. A 1.12 point version that reverses the unfortunate hostname decision would be the preferred and logical solution here.

**Comment by masonoise** [comment]
Agreed with @nbastin that this is another example of ongoing issues with Docker's seemingly insatiable desire to change things for the sake of changing them rather than focusing on stability of what is, after all, a mission-critical piece of infrastructure. There's a long, long list of known bugs: we'd love to get those fixed before unnecessary and almost-random breaking changes are made.

**Comment by cpuguy83** [comment]
I'm just going to go ahead and close/lock this issue.
If you are interested in following along in resolving the issue, you can follow the linked issue below.
