### ISSUE TITLE
check_config script does not have all modules needed for encrypted networks

### ISSUE THREAD

**Issue by justincormack** [docker/docker#27288]
I think the following should be checked for in order to support swarm ipsec based encrupted networks:

```
CRYPTO_ECHAINIV
CONFIG_INET_XFRM_MODE_TRANSPORT
CONFIG_XFRM
CONFIG_XFRM_ALGO
CONFIG_XFRM_USER
```

may also be more.

cc @aboch

**Comment by aboch** [comment]
Thanks will double check. For now I am crossing out what I know we do not need: `CONFIG_INET_XFRM_MODE_TUNNEL` our implementation does not use tunnel mode ipsec, we use transport mode only.

**Comment by justincormack** [comment]
ah ok, I added more options than I needed I know, changed to TRANSPORT...
