### ISSUE TITLE
Numeric value not able to set as env using Dockerfile

### ISSUE THREAD

**Issue by anumantharaja** [docker/docker#27284]
**Description**

I'm trying to build a dockerimage from docker file,  i'm setting an ENV in the Dockerfile(ENV GOROOT "/usr/share/go/1.6").. But I couldn't find the same ENV value inside the container. The value is set as "/usr/share/go". "/1.6" is missing.

**Steps to reproduce the issue:**
1. build the Dockerfile https://gist.github.com/anumantharaja/afa1fc1684a58b2646e2ae2d80489686
2. Run the image
3. and inside the container give echo $GOROOT

**Describe the results you received:**

i received /usr/share/go
**Describe the results you expected:**

i expected /usr/share/go/1.6
**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 20
 Running: 7
 Paused: 0
 Stopped: 13
Images: 70
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 215
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.19.0-69-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.69 GiB
Name: xxxxx
ID: 6HML:6WSF:RD7P:IRIA:45FO:7EUF:7K5F:D5HI:3IYO:GUPX:QG3U:JOLB
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Username: trov
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I tried in Azure and GCE its not worked..

**Comment by justincormack** [comment]
I can't replicate this:

Dockerfile:
```
FROM alpine

###   Add Env 
ENV GOPATH /root/.gopkg/ 
ENV GOROOT /usr/share/go/1.6
ENV PATH $PATH:$GOROOT/bin 
```

build it and
```
docker run -it 90315ad67f2c env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/share/go/1.6/bin
HOSTNAME=df66b418d1e6
TERM=xterm
no_proxy=*.local, 169.254/16
GOPATH=/root/.gopkg/
GOROOT=/usr/share/go/1.6
HOME=/root
```

Can you try upgrading your Docker version and seeing if it is still an issue?

**Comment by anumantharaja** [comment]
@justincormack in which version you tried?

**Comment by justincormack** [comment]
1.12.1

**Comment by anumantharaja** [comment]
thnks @justincormack

**Comment by anumantharaja** [comment]
issue was in my side.. Not docker version problem ....
