### ISSUE TITLE
Network timed out while trying to connect to index.docker.io

### ISSUE THREAD

**Issue by samarth** [docker/docker#27283]
**Description**

**Steps to reproduce the issue:**
1. did a docker pull hello-world
2.
3.

**Describe the results you received:**
Service 'web' failed to build: Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/python/images. You may want to check your internet connection or if you are behind a proxy.

**Describe the results you expected:**
I expected a docker pull to actually happen here since a curl on this same url was working fine.

**Additional information you deem important (e.g. issue happens only occasionally):**
I changed the priority of my DNS and put 8.8.8.8 at the top . This finally resolved the issue. I happen to have a few VPNs in my laptop but all other applications seem to recover gracefully. 

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 9
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: HSMX:OADM:YWKZ:L44J:SUGK:XCFR:BG7E:4VJZ:7YZH:CKF3:AJXE:PRWS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-10-11T10:35:53.043220886Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I think this issue may be specific to Docker for Mac; would you be able to reopen this in the docker for mac issue tracker? https://github.com/docker/for-mac/issues

**Comment by samarth** [comment]
Sure, here it is : 
https://github.com/docker/for-mac/issues/788

**Comment by thaJeztah** [comment]
Thank you! And thanks for reporting!
