### ISSUE TITLE
Feature request: Allow multiple instances of the same 'docker plugin'

### ISSUE THREAD

**Issue by bnaylor** [docker/docker#27299]
We are containerizing the NetApp Docker Volume Plugin for use with 'docker plugin'. 

The current version of the volume plugin is a native binary that can be run multiple times with different configuration details and driver names for each instance.  Storage administrators can do this in order to register differently-named volume drivers with different characteristics, eg. different types of backing storage systems, or systems with different service levels or performance characteristics.

As we transition to the new plugin model, we would prefer to maintain these instances as separate entities rather than bundle them into a monolithic container that would need additional orchestration logic to understand how to schedule the different back-ends that might have been provided. (The volume-provisioning driver seems like the wrong place for this kind of logic.)

While we could easily run multiple containers with 'docker run', it is not clear how we would instantiate multiple instances when the driver is executed as a docker plugin instead.

cc @anusha-ragunathan

**Comment by thaJeztah** [comment]
We discussed this in the maintainers meeting, and while we see the use case, it may be too early to add this. However, some suggestions were made during the meeting (e.g. allow aliasing plugins). This needs more discussion and a proper design, so let's keep this issue open to see what options there are.

/cc @tonistiigi @justincormack

**Comment by anusha-ragunathan** [comment]
Aliasing plugins is a problem atm, since we use pluginname as the unique identifier.

**Comment by anusha-ragunathan** [comment]
https://github.com/docker/docker/pull/29734/commits/38d914cc9648724c61afbfe8caa3f2735b58852d added support for aliases for plugins (amongst several other features), which will precisely allow multiple instances of a plugin. This issue is resolved now.

**Comment by bnaylor** [comment]
Great, thanks!
