### ISSUE TITLE
overlay2 storage driver changes directory perms on commit

### ISSUE THREAD

**Issue by MohammedYunus** [docker/docker#27298]
**Description**

Start a docker (version 1.12.1) container on Oracle Linux 6.8 ( 4.1.12-37.6.1.el6uek.x86_64) configured for overlay2 storage driver.
Delete and recreate some existing directory (owned by non-root user) and commit the container to an image. 
Stop and start the container from the newly committed image.

**Steps to reproduce the issue:**
1. docker run -it --name my_cont my_img /bin/bash
2. ls -ld /u01/app/oracle/product
drwxr-xr-x 1 oracle oinstall 4096 Aug 18 23:20 /u01/app/oracle/product
3. rm -rf /u01/app/oracle/product  
4. mkdir /u01/app/oracle/product
5. exit 
6. docker commit my_cont my_img
7. docker run -it --name my_cont my_img /bin/bash
8. ls -ld /u01/app/oracle/product
drwxr-xr-x 1 root root 4096 Oct 10 23:20 /u01/app/oracle/product

This issue is not present in overlay storage driver. 

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
cc @dmcgowan

**Comment by dmcgowan** [comment]
@MohammedYunus do you mind sending your `docker info`? If you are not using user namespaces (such as with `--userns-remap`) this would be expected behavior based on your instructions. If you see `ls -ld /u01/app/oracle/product` after the `mkdir` shows root/root, then the commit will keep those permissions. If you `chown oracle/oinstall` after making the directory then it should be preserved after commit.

**Comment by MohammedYunus** [comment]
The default user on container startup is "oracle" and not root. so the mkdir is done as the "oracle" user.
But once the container is commited to image, the ownership for the same directory becomes root

Pasting the docker info output
$> docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 16
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.1.12-61.1.10.el6uek.x86_64
Operating System: Oracle Linux Server 6.8
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.82 GiB
Name: adc00ppm
ID: RD5F:BR2D:GJYP:LHAK:JBOP:UAC2:UJLL:3KPQ:CC4Q:FZ5J:D64E:ZWJJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by dmcgowan** [comment]
@MohammedYunus: thanks, to help me create a reproducible test for this could you provide me the output of running `id` and `ls -ld /u01/app/oracle/product` after `mkdir /u01/app/oracle/product`.

**Comment by MohammedYunus** [comment]
Copy/pasting the requested info


[oracle@8ba8d3453148 ~]$ mkdir  /u01/app/oracle/product
[oracle@8ba8d3453148 ~]$ id
uid=1000(oracle) gid=500(oinstall) groups=500(oinstall),501(dba),502(asmadmin),503(asmdba)
[oracle@8ba8d3453148 ~]$ ls -ld /u01/app/oracle/product 
drwxr-xr-x 2 oracle oinstall 4096 Oct 14 17:38 /u01/app/oracle/product

**Comment by dmcgowan** [comment]
@MohammedYunus thanks for report, I am able to replicate this in a test and confirm it is happening with overlay2 and not overlay or devicemapper.  (See https://github.com/dmcgowan/dsdbench/blob/master/issues_test.go#L156)
