### ISSUE TITLE
Support using multiple ---volume-drivers on swarm

### ISSUE THREAD

**Issue by suryagaddipati** [docker/docker#27302]
`
    docker -v vol:/path --volume-driver custom-volume-driver image
`

If the image has VOLUME command  it tries to use custom-volume-driver instead of 'local' volume driver. This is expected behavior currently since `--volume-driver` applied to *all* volumes.  But I want to use `local` driver for VOLUMEs specified in the Dockerfile. 

There is no way to use 2 different volume drivers  on swarm.

The following workaround of using `docker volume create ` before launching the container is not equivalent because, 

```
docker volume create -d custom-volume-driver --name myvol

docker run -v myvol:/mount/path image
```

This creates volumes on **all** swarm nodes 

vs 

`  
 docker -v vol:/path --volume-driver custom-volume-driver image
 `

creates volume only the node that is running the container.

**Comment by AkihiroSuda** [comment]
You mean the Swarm *classic* (https://github.com/docker/swarm) right?

In the new Swarm mode (Docker 1.12), the feature seems actually supported:
https://docs.docker.com/engine/reference/commandline/service_create/
> The --mount flag allows you to specify a volume driver and volume driver options per volume, without creating the volumes in advance. In contrast, docker run allows you to specify a single volume driver which is shared by all volumes, using the --volume-driver flag.

There is also a PR that ports `--mount` to `docker run`:  https://github.com/docker/docker/pull/26825

**Comment by suryagaddipati** [comment]
@AkihiroSuda yes I've only tried this on `swarm classic` so perhaps I should close this issue here.

**Comment by thaJeztah** [comment]
Agreed with @AkihiroSuda - swarm mode supports this through the `--mount` flag, and https://github.com/docker/docker/pull/26825 adds this for docker run, possibly "swarm classic" will adopt that.

Let's close this issue
