### ISSUE TITLE
1.12 on amazon linux

### ISSUE THREAD

**Issue by roman-gliffy** [docker/docker#27313]
Amazon linux is not listed as OS for 1.12 

Nobody interested? Are there any plan to support it in the future?

**Comment by thaJeztah** [comment]
There was a pull request a while back from Amazon, but it would require an image to be made available to verify / build; they haven't made that available yet, so the PR was closed pending that.

You may be interested in the Docker for AWS beta though https://blog.docker.com/2016/06/azure-aws-beta/

i'll close this issue, as there's nothing we
can currently do, but feel free to comment after i closed

**Comment by redbaron** [comment]
@thaJeztah , FYI, Amazon released docker image with Amazon Linux: https://aws.amazon.com/blogs/aws/new-amazon-linux-container-image-for-cloud-and-on-premises-workloads/

**Comment by thaJeztah** [comment]
@redbaron thanks! I saw that, and we're already having a conversation with the Amazon team (no decisions made yet :smile:)

**Comment by eric-tucker** [comment]
Am I reading this correctly?  Docker has stopped support Amazon Linux?  Seriously?  This can't be happening...

**Comment by justincormack** [comment]
No, we haven't started supporting it yet.

**Comment by thaJeztah** [comment]
@eric-tucker there never has been an official package for docker on amazon linux; it looks like you were relying on the install-script; see this PR why that won't work for Amazon linux; https://github.com/docker/docker/pull/23480.
