### ISSUE TITLE
Feature request: Centralized validation of host dependencies for plugins

### ISSUE THREAD

**Issue by bnaylor** [docker/docker#27324]
We are containerizing the [NetApp Docker Volume Plugin](https://github.com/NetApp/netappdvp) for use with the new 'docker plugin' system.

This plugin supports mounting volumes for the NFS and iSCSI protocols.  For various reasons related to how mounting and data traffic work with these protocols, our plugin can only be partially containerized -- we need to execute certain commands on the container host system.  With a privileged container, sys_admin capabilities, and shared mounts, this works well enough.

This does, however, mean that we have some dependencies on the packages that are installed on the host system.  With the current native binary plugin, we simply point out the dependencies as part of the install documentation since the administrator has to install our binary and configuration files anyway.

When our plugin is distributed as a 'docker plugin', however, we begin to be able to bypass these manual configuration steps entirely, and users may inadvertently run the plugin on systems that lack the correct supporting tools.  We would like to automate the validation (and even installation) of the dependencies.

I have prototyped the basic flow of how we think it could work in a [simple demo](https://github.com/bnaylor/plugins-dep).

This involves booting a normal container (not really a plugin yet) with a shell script that does the checking and installation all within the container, and has hardcoded dependencies in the script.  Ideally, however, the logic for managing the packages would reside in a central place (docker) rather than as ad-hoc scripts in lots of plugin containers.  This would give all plugins that have host dependencies a common implementation and common behavior.  

The dependencies for any container could then be specified simply in the Manifest --

```
  "dependencies": [
            {
                "name": "yum",
                "description": "Host dependencies for distributions using yum",
                "value": ["nfs-utils", "lsscsi", "iscsi-initiator-utils", "sg3_utils", "device-mapper-multipath"]
             },
            {
                "name": "apt",
                "description": "Host dependencies for apt-based distributions",
                "value": ["nfs-common", "open-iscsi", "lsscsi", "sg3-utils", "multipath-tools scsitools"]
            }
        },
```

..and the engine could validate these dependencies at install or run time.  If the distribution in question isn't listed or detected, a simple warning would suffice, and it would be clearer than opaque failures that would subsequently occur otherwise.

I realize that there is plenty of room to quibble over the details of the granularity of the flavors.  "yum/apt", "redhat/debian", or fully enumerating specific distributions..  The goal is to list the specific packages that are required - whatever the best way to do that is down to the implementation.

cc @anusha-ragunathan

**Comment by justincormack** [comment]
Can you explain why you can't manage with containerised dependencies?

**Comment by bnaylor** [comment]
Sure.  And the underlying caveat to any of this should be that if anyone has fixes that would make it work, I'm all ears.

The primary issue is iscsi.  First, there are known problems running iscsid inside containers that seem to have been around for some time.  Examples: [A](https://bugs.launchpad.net/ubuntu/+source/lxc/+bug/1226855), [B](https://bugzilla.redhat.com/show_bug.cgi?id=1102911), [B'](https://bugzilla.redhat.com/show_bug.cgi?id=1100000).

However even should that be fixed, it's still not a great idea with the model we have for two reasons.  The first one is that starting iscsid inside a container would route the data traffic through NAT to the container, which would be undesirable from a performance perspective.  Some discussion of that [here](https://rootfs.github.io/iSCSI-Kubernetes/).  Secondly, our volume plugin would effectively become an iscsi proxy for all the containers it was doing mounts for - and a single point of failure for them all as well.  That is probably the worst part.

It is also a best practice with at least some of our platforms to use multipathing, and the stock multipathd seems to have similar issues running in containers.  I have not explored this to a great degree because of the underlying iscsid problems.

**Comment by bnaylor** [comment]
Theoretically, NFS _should_ work.  We would do the mount RPC calls from the plugin container, but the data flow would occur directly through the host kernel to whatever other container was accessing the files, and our container would not be a middle-man.  We've had trouble with it so far, but we could potentially remove this dependency, esp. if the iscsi issues are solved.

**Comment by justincormack** [comment]
For `iscsi` does `--net=host` work? that avoids the NAT, and maybe helps out with the netlink socket issue (which is somewhat unclear, and would probably need looking at the kernel code to see what is happening).

NFS does seem simpler to solve initially as it is mostly in kernel anyway.

**Comment by bnaylor** [comment]
Forgive the delay, it's been a while - I needed to give it another shot to remember exactly what failed in that case.  Looks like the first thing you run into is that iscsiadm wants the iscsi_tcp kmod.

**Comment by bnaylor** [comment]
Those details aside, even getting that to work in our container doesn't fix the problem of running iscsid in the "wrong" container.  What we're doing here should be analogous to how the Openstack Cinder module works; provisioning volumes out of band using management APIs, but leaving the data path to the interested parties.  A [diagram](https://varchitectthoughts.files.wordpress.com/2013/11/screen-shot-2013-11-18-at-11-06-14-am.png) of that.. ([source](https://cloudarchitectmusings.com/2013/11/18/laying-cinder-block-volumes-in-openstack-part-1-the-basics/))

**Comment by bnaylor** [comment]
I got NFS working a while back, so we can scratch that off the list.  And I've just learned that a colleague managed to get [iscsi to work](https://github.com/kangarlou/kubernetes-storage/blob/master/k8s-singlenode-setup/start-kubernetes.sh#L33:L47) as well, at least on a one-container-per-node basis.  We can work with that.  Closing this.

**Comment by anusha-ragunathan** [comment]
That's great news, @bnaylor
