### ISSUE TITLE
Feature request: `docker replace'

### ISSUE THREAD

**Issue by pikajude** [docker/docker#2733]
Say I have `organization/db`, which runs a Postgres instance, running and exposing port 5432; I also have `organization/app` running, which is linked to my database instance. If I want to upgrade my version of Postgres and restart the database, I also have to restart `organization/app`, since the database link will be broken when the database container is restarted.

It would be cool if we could `docker replace` a running container with a new container running a different image, which replaces the running container and usurps its port and virtual interface, so that the app won't even be able to tell its database was replaced, and the most downtime users would see would be one or two misc. network errors when trying to reach the database.

**Comment by resouer** [comment]
@bfirsh Could u plz give me some details about how you guys deal with **link** when recreating?

**Comment by nomadster** [comment]
+1

**Comment by virtuald** [comment]
+1 would be useful

**Comment by smitec** [comment]
+1 wrote a workaround that edits `/etc/hosts` manually which may help some people in the interim https://github.com/smitec/docker-hotswap

**Comment by cristoslc** [comment]
:+1:

**Comment by knownasilya** [comment]
What about waiting till all connections have been satisfied, and then replacing?

**Comment by NoiSek** [comment]
+1 this would be extremely useful

**Comment by calavera** [comment]
There are no plans to do this for now and I don't think this should be a feature in docker itself. Sorry, I'm going to close this issue because it sets a false expectative.

**Comment by cristoslc** [comment]
Could we please get a little explanation on why you don't think this should be a feature?

**Comment by NoiSek** [comment]
^ More explanation would be appreciated, this seems in direct contrast to [the very first reply](https://github.com/docker/docker/issues/2733#issuecomment-28634450) from earlier.

**Comment by calavera** [comment]
the first comment is from two years ago. I can tell you that there are no plans to implement this in the near future. You can get this kind of feature with external tools.

**Comment by NoiSek** [comment]
Two years ago from the, *cough*, guy who create docker.

Thank you for the clarification, however. If you could link a few of those external tools for people who stumble on this issue that would be great.

**Comment by knownasilya** [comment]
>  If you could link a few of those external tools for people who stumble on this issue via Google that would be great.

:+1:

**Comment by flaccid** [comment]
http://forums.rancher.com/t/zero-downtime-app-upgrades/112/5

**Comment by pwaller** [comment]
Over at ScraperWiki we've had a fairly successful experience with rolling our own tool, [`hanoverd`](https://github.com/scraperwiki/hanoverd), which speaks to the docker daemon and enables replacing an existing application. It even checks the new one is healthy before redirecting new traffic to it.

**Comment by bfirsh** [comment]
@calavera Even if don't intend to build this in the near future, I think we should keep this open to keep track of the feature request. It is a thing that users are asking for and would be extremely useful in Compose.

**Comment by calavera** [comment]
@bfirsh please feel free to open an issue in Compose to track it then. As I said, it doesn't belong to the engine.

**Comment by cusspvz** [comment]
+1 for CD

**Comment by sourcekick** [comment]
@calavera The decision not to support a command that replaces an existing container directly by the engine is to some degree lacking reasons here. Could you elaborate on the reasons behind the decision?

Also, when you point us to Compose, I do not see how it would help the requested use case. Some people do not have an app composed out of several containers. They have an app that consists of just one container. Still they want to be able to `docker replace` that container, ideally without additional tooling.

Perhaps you consider an app with just one container to be a special use case for Compose, but that would feel quite unintuitive.

Among other advantages, a replace would prevent long and unnecesary histories of past containers, displayed for example in the Kitematic UI. No need for cleaning that history now and then.

**Comment by thaJeztah** [comment]
@sourcekick with the new networking features in docker 1.9 and 1.10 (DNS based discovery of other containers by name), using a `--link` is no longer a requirement, and containers can be replaced more easily.

The reason for not including this in docker, is that a "replace" feature in its most basic form would be "docker rm container" followed by "docker run newcontainer", which is easily achieved out of bound (either using docker compose, or a shellscript/Makefile).

However, once we start implementing the above "basic" replace, soon there will be request to do a more smarter replace (`docker stop container`, `docker rename container oldcontainer`, `docker run new container`), "rollbacks", etc.

Once we head into that direction, the docker engine will be doing things that really belong in the orchestration layer.

We like to keep functionality of the "engine" limited to things the *engine* should do, so for that reason decided not to implement this.

**Comment by simkim** [comment]
@cpuguy83 , @wking : I wrote https://github.com/simkim/tcpdam to park generic tcp connections between container upgrade. It will help us to replace downtime with latency during complex migrations.

**Comment by wtrocki** [comment]
This feature is also available out of the box on Kubernetes/OpenShift platforms.

**Comment by flaccid** [comment]
Rancher *cough*

**Comment by thaJeztah** [comment]
This functionality is implemented in docker 1.12 through services, i.e.,

Create a service

    docker service create --name web --replicas=3 nginx:1.10

Update the service to a new image

    docker service update --image nginx:1.11

**Comment by tomfotherby** [comment]
@thaJeztah  - Did you miss the service name in the `update`? i.e. should it be `docker service update web  --image nginx:1.11`?

Will this work for data-containers. If the code for a website for example was in a data container, linked to a web-server, could I `update` the data-container with a new version as a way to update the website content with minimal downtime?

**Comment by justincormack** [comment]
I have a proposal that would make updating content with swarm services very
easy https://github.com/docker/docker/issues/30449
