### ISSUE TITLE
docker service create is parsing quoted fields for parameters

### ISSUE THREAD

**Issue by allingeek** [docker/docker#27336]
**Description**

When attempting to set a multi value JAVA_OPTS environment variable I discovered that quoted parameters to `docker service create -e` are being parsed for command line flags. Having experimented with several variations I have yet to discover an escape or quoting pattern to work around the issue.

**Steps to reproduce the issue:**
1. Create a service and set an environment variable where the value contains docker flags:

    docker service create --name env-test -e 'TEST=-ejunk -ejunk2 -ptest' alpine env

2. Create a service without the `-ptest` portion of the environment variable:

    $ docker service create \
      --name env-test \
      -e 'TEST=-ejunk -ejunk2' \
      alpine env

3. Lookup and view the logs of the resulting container:

    $ docker logs $(docker ps -lq)

**Describe the results you received:**
Step 1 will result in the following error message:

    invalid argument "test" for ptest: Invalid containerPort: test
    See 'docker service create --help'.

You are able to start the service by eliminating the -pXXX portion of the quoted environment variable in step two, however inspection of the environment within the container confirms that only the portion of the value prior to the space has been set (note that if you are running on a swarm cluster with more than one node you will need to determine both the node and container ID to view the logs):

    $ docker logs $(docker ps -lq)
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    HOSTNAME=3c77a7e0a77b
    TEST=-ejunk
    HOME=/root

I believe these are both incorrect behaviors.

**Describe the results you expected:**

I believe the first command should have succeeded in creating a service and that containers for that service should have a single environment variable named, "TEST" with a value of, "-ejunk -ejunk2 -ptest"

I believe the second service should have had a single environment variable named, "TEST" with a value of, "-ejunk -ejunk2"

**Additional information you deem important (e.g. issue happens only occasionally):**

This is repeatable and while the second behavior is problematic enough, the first behavior seems to happen with several different flag prefixes like -D, -e, -v, --link, and so on. In any case, the docker CLI should not be parsing this quoted string as command flags. It should be passed whole as an argument to the environment variable processor.

I've also tried several permutations of quoting patterns including whole-argument double, whole-argument single, value-only double and single quotes. I've tried escaping spaces. 

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 1
 Paused: 0
 Stopped: 11
Images: 33
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 58
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: b8a8ba9fpuyv5qogfdnot10o0
 Is Manager: true
 ClusterID: c1xxrj7alaz5uqqqtcbl01pws
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 107.170.232.116
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: client-cluster-m1
ID: W4V4:C25I:TSER:VQA3:L5UK:KSDK:2AFW:CCYL:NPO7:EBKH:I5ND:VTT4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: allingeek
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

DigitalOcean, not that it should matter. The client (which is the broken part) is running on my mac.

**Comment by justincormack** [comment]
cc @dnephin

**Comment by dnephin** [comment]
I can't reproduce the issue, it works correctly for me on linux.

```
$ docker service create --name testing -e 'TEST=-ejunk -ejunk2 -ptest' alpine:3.4 env
```
```
$ docker service inspect testing
...
                    "Env": [
                        "TEST=-ejunk -ejunk2 -ptest"
                    ]
]
```

I believe the quoting is actually the responsibility of the shell. By the time the args are received by the process (docker) they should already grouped properly. Are you using a non-standard shell?

I don't OSX to test it out.

**Comment by justincormack** [comment]
I don't see this on Docker for Mac either

**Comment by allingeek** [comment]
I'm satisfied that this is something broken with my terminal and not the Docker CLI.
