### ISSUE TITLE
Docker (1.12) run mounts, unmounts and then again mounts persistent volumes.

### ISSUE THREAD

**Issue by govint** [docker/docker#27339]
**Description**

**Steps to reproduce the issue:**
1. $ docker volume create -d vmdk --name v14
2. $ docker run --rm -it -w /data -v v14:/data busybox
3.

**Describe the results you received:**
The container runs but the engine is mounting the volume, unmounting and then again re-mounting.

**Describe the results you expected:**
A single mount should have been issued to the docker volume plugin.

**Additional information you deem important (e.g. issue happens only occasionally):**

Docker daemon logs
DEBU[0553] Calling POST /v1.24/volumes/create
DEBU[0553] form data: {"Driver":"vmdk","DriverOpts":{},"Labels":{},"Name":"v14"}
DEBU[0553] Registering new volume reference: driver "vmdk", name "v14"
DEBU[0567] Calling POST /v1.24/containers/create
DEBU[0567] form data: {"AttachStderr":true,"AttachStdin":true,"AttachStdout":true,"Cmd":["sh"],"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":["v14:/data"],"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"busybox","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":true,"StdinOnce":true,"Tty":true,"User":"","Volumes":{},"WorkingDir":"/data"}
DEBU[0567] container mounted via layerStore: /var/lib/docker/overlay/ef5beca6447c389c511ecd311a7ecb449d8727d2e42bcdfed814c74b852a7123/merged
DEBU[0567] copying image data from 2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269:/data, to v14
DEBU[0569] Calling POST /v1.24/containers/2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269/attach?stderr=1&stdin=1&stdout=1&stream=1
DEBU[0569] attach: stdin: begin
DEBU[0569] attach: stdout: begin
DEBU[0569] attach: stderr: begin
DEBU[0569] Calling POST /v1.24/containers/2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269/start
DEBU[0569] container mounted via layerStore: /var/lib/docker/overlay/ef5beca6447c389c511ecd311a7ecb449d8727d2e42bcdfed814c74b852a7123/merged
DEBU[0569] Assigning addresses for endpoint ecstatic_bohr's interface on network bridge
DEBU[0569] RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])
DEBU[0569] Assigning addresses for endpoint ecstatic_bohr's interface on network bridge
DEBU[0569] Programming external connectivity on endpoint ecstatic_bohr (ec168a8fffbcbe0f6d2537e31ac8988f64ea8ba2e745a4018d6c5ab3f871d24a)
DEBU[0570] sandbox set key processing took 43.097485ms for container 2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269
DEBU[0570] libcontainerd: received containerd event: &types.Event{Type:"start-container", Id:"2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269", Status:0x0, Pid:"", Timestamp:(*timestamp.Timestamp)(0xc8208171f0)}
DEBU[0570] Calling POST /v1.24/containers/2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269/resize?h=24&w=80
DEBU[0570] libcontainerd: event unhandled: type:"start-container" id:"2cfc0524ab0c0136f9a7fe9f13c4210bfac7212f9753d61b0b4ed46fc32fd269" timestamp:<seconds:1476338207 nanos:752031826 >
DEBU[0971] Calling GET /v1.24/version
DEBU[0984] Calling GET /v1.24/info

Volume plugin logs (see Mount, Unmount and then again Mount):

2016-10-13 05:56:44.98546386 +0000 UTC [INFO] Mounting volume name=v14
2016-10-13 05:56:46.012215424 +0000 UTC [INFO] Unmounting Volume name=v14
2016-10-13 05:56:46.637796495 +0000 UTC [INFO] Mounting volume name=v14

**Output of `docker version`:**

```
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 23:54:00 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.12.0
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local vmdk
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.8
Operating System: VMware Photon/Linux
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.953 GiB
Name: photon-jyLxAJ3OK
ID: OJHA:RMAT:A5AZ:CNNK:T33C:HOFU:N2V3:DSDL:7T7S:WU5U:ANR6:KAGL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
This is because of the API/client design.
`docker run` is two actions, a `docker create` and a `docker start`.
The volume is mounted on `docker create` so that the volume can be populated with container data.... then unmounted. WIth `nocopy`, you should not get a mount request here.

The volume is mounted again on `docker start` for use in the container.

**Comment by govint** [comment]
Ok, thanks for the clarification. Closing the issue.

**Comment by govint** [comment]
Taking a step back, the mount and unmount can be done iff there is really data to copy to the volume.

**Comment by shashankmjain** [comment]
For Docker create calling mount and unmount, is it a feature with 1.12 or existed in previous versions as well.
