### ISSUE TITLE
Docker Remote API - list of all containers/service-replicas in all nodes

### ISSUE THREAD

**Issue by rajkumar49** [docker/docker#27349]
Hi , 
any Docker Remote API command for Swarm Manager to get all the container details of all the nodes ?
any way to see the Docker container CPU usage from the Docker Swarm manager ?

**Comment by thaJeztah** [comment]
No this is (at least currently) not possible; to get details of individual containers, you need to connect to the daemon of the host that the container is running on.

For stats, there's a roadmap issue for integrating with prometheus to provide metrics on (initially) the daemon, and in a later stage for individual containers / services; https://github.com/docker/docker/issues/27307

I'll close this issue, but feel free to open a feature request for getting details on individual containers in the swarm, describing the use case as part of your request.

Also feel free to comment here if you need additional information
