### ISSUE TITLE
how can we dump dockerd running options

### ISSUE THREAD

**Issue by ryanlyy** [docker/docker#27344]
Here is just question not issue report....
As we know we can configure dockerd using /etc/docker/daemon.json. How can we dump those information from running dockerd including all default values for all options?

**Describe the results you expected:**
dockerd current indeed uses those options configured in daemon.json

Thanks and Best Regards,
Ryan

**Comment by justincormack** [comment]
I am not sure there is an easy way to do this right now. As we have configuration reload I can see if would be useful.

**Comment by thaJeztah** [comment]
this is a duplicate of https://github.com/docker/docker/issues/21559; I'll close this one, please continue the conversation in https://github.com/docker/docker/issues/21559
