### ISSUE TITLE
docker volume create should return error when volume name exists

### ISSUE THREAD

**Issue by allencloud** [docker/docker#27345]
**Description**
If we have already created a volume with name `volumeA`, then when we create another volume with  `volumeA` again, nothing conflict returns and returns a code of 201 from API.

In addition, if we add labels in volume create with an existing name, labels will not be added into this volume details.

related issue https://github.com/docker/docker/issues/26831

**Steps to reproduce the issue:**
1. `docker volume create --name volumeA`
2. `docker volume create --name volumeA`
3. `docker volume create --name volumeA --label aa=bb`
4. `docker volume inspect volumeA`

**Describe the results you received:**
In the output of Step 2, no conflict error happens.
In the output of Step 4, no labels in the volume details. I think this is really unreasonable.
```
root@ubuntu:~# docker volume inspect volumeA
[
    {
        "Name": "volumeA",
        "Driver": "local",
        "Mountpoint": "/var/lib/docker/volumes/volumeA/_data",
        "Labels": {},
        "Scope": "local"
    }
]
``` 

**Describe the results you expected:**
In the output of Step 2, conflict error happens.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 63
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 453
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: active
 NodeID: 4yghf0i19aa9a65dgsyitqns3
 Is Manager: true
 ClusterID: 7bgsisgkf388rd3fpz5i4k71s
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 117
 System Time: 2016-10-06T00:26:18.382343896+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 a=b
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dattatrayakumbhar04** [comment]
Hello allencloud ,
As per document below,
https://docs.docker.com/engine/reference/commandline/volume_create/

Volume names must be unique among drivers. This means you cannot use the same volume name with two different drivers. If you attempt this, then  docker returns an error:

In your case, 
1. docker volume create --name volumeA
2. docker volume create --name volumeA
3. docker volume create --name volumeA --label aa=bb
4. docker volume inspect volumeA

In all case, volume driver is as default "local" so It is as expected as per document.

**Comment by allencloud** [comment]
@dattatrayakumbhar04 Thanks a lot for your feedback 🐯 
Yes, the docs told us that, indeed.
While I think I have some different opinion on this.
The reason I hope to emphasize most is that I can not create a volume with labels if the given name is already exists in the volume store.

like `docker volume create --name volumeA --label aa=bb` works if vlomeA already exists, while no label was added into this volume. This may be some place we should take more serious. As no exception returns, no error, no error status code. It will make users misunderstand the operation.

ping @cpuguy83

**Comment by thaJeztah** [comment]
@allencloud looks like this is a duplicate of https://github.com/docker/docker/issues/16068 ?

**Comment by allencloud** [comment]
OK, sorry for the duplication. i will close this. 
Thanks @dattatrayakumbhar04 for the discussion.  We can go to #16068 if more discussion needed. 😄
