### ISSUE TITLE
Docker Backward Compatibility with Linux Kernel

### ISSUE THREAD

**Issue by sivaswami** [docker/docker#27352]
I was running Docker 1.7.1 in a Linux machine and it worked fine.  I had some issues with my environment and installed docker using below command which gives latest version 1.12.2
curl -sSL https://get.docker.com/ | sh
When I tried to start docker daemon, I hit the error 
FATA[0001] Your Linux kernel version 3.8.13-68.3.4.el6uek.x86_64 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer.
Any help on the below questions would be helpful.
1. Is there any way to download docker 1.7.1 instead of 1.12.2  ?
2. Is there any docker version vs Linux version compatibility matrix ?
3. Is there any way to override the above error message. Make 1.12.2 run on old linux kernels ?

**Comment by tonistiigi** [comment]
1. Install script only installs latest version. Packages for old versions are still available but must be installed manually then.
2. It should be `3.10` for `1.7+`. I think the difference is that in older versions it was only a warning. 
3. `DOCKER_NOWARN_KERNEL_VERSION=1`

**Comment by milindchawre** [comment]
@sivaswami To install specific docker version try this : 
`wget -qO- https://get.docker.com/ | sed 's/lxc-docker/lxc-docker-1.6.2/' | sh`
@tonistiigi So if we use `DOCKER_NOWARN_KERNEL_VERSION=1` then it is possible to run docker on any older kernels (older than 3.10)?

**Comment by tonistiigi** [comment]
@milindchawre It will then skip this validation on startup. The behavior is undefined and unsupported.

**Comment by sivaswami** [comment]
Thanks @tonistiigi @milindchawre .
I think such backward compatibility might be  required  as people  might upgrade docker more than their kernels. It would also be helpful if we have a FAQ session for installing / compatibilities

**Comment by justincormack** [comment]
@sivaswami it is unsupported as containerisation features and networking may not work on older kernels, so we cannot support them. We go back as far as we can. There are bugs in earlier versions that cannot be worked around. They may not affect your use cases.

**Comment by justincormack** [comment]
Closing as answered - if you have more questions please continue to ask...
