### ISSUE TITLE
Faied to connect to the Docker daemon ( Mac OS ) 

### ISSUE THREAD

**Issue by vikramvi** [docker/docker#27356]
**Description**

Jenkins user on Mac mini can't run docker command
1.1. Inside Jenkins build; Execute shell command says "docker command not found"
1.2 Shifting to Jenkins user on shell prompt and trying to run docker command gives error
   "Cannot connect to the Docker daemon. Is the docker daemon running on this host?"

**Steps to reproduce the issue:**
1.  Mac mini Jenkins and Docker installed ( through mac installer )
2. Verified both working fine independently ( with Mac mini admin user )
3. Jenkins user can't run docker commands

**Describe the results you received:**

sudo -s -u jenkins
Password:
bash-3.2$ whoami
jenkins
bash-3.2$ docker ps -a
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
bash-3.2$ 

**Describe the results you expected:**

currently installed docker containers

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 53
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: YEGE:PR2R:SKGB:MIKZ:NVU4:ILOC:B2OE:WCQT:A4JL:57QB:C46C:Q7Q5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-10-13T14:36:08.079296494Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Mac mini physical box in office network**

**Comment by justincormack** [comment]
Can you open the issue here instead https://github.com/docker/for-mac/issues

Docker for Mac generally expects that the user installing and running it is the same as the one using it.  However it may work if you change the permissions of `/var/run/docker.sock` so that the jenkins user can access it.

**Comment by vikramvi** [comment]
done https://github.com/docker/for-mac/issues/799

**Comment by justincormack** [comment]
ok thanks, will close here then.
