### ISSUE TITLE
Multiple IP addresses Swarm Mode

### ISSUE THREAD

**Issue by YouriT** [docker/docker#27350]
When using some public IP blocs, there is no way in Swarm Mode to stick a service on a specific ip address like it's possible with `docker run`. I understood that the main reason against that is the mesh and therefore the ingress interface that redirects traffic to the right node which makes sense. Nevertheless, you can never expose 2 times the same port to the outside world. Meaning that if you need this functionality and that you can not proxy the port, then you are screwed. Either `docker run` should be allowed to connect to the `swarm overlay` network either, this feature should be somehow available.

Simple example of use case:
Lets say that you have a SSH server on a machine that is accessible from the outside world on `1.1.1.1:22` and that you have a GitLab container and that you want to keep the GitLab ssh service `git@example.com => 1.1.1.2:22` from being available on port 22 alongside with your sshd.

From my understanding, with the actual implementation of Docker Swarm you cannot achieve such thing.

What would you advice?
Is their any room in improving this?

**Comment by cpuguy83** [comment]
Closing as a dup of #26696

btw, in 1.13 you will be able to `docker run` with an overlay network.
