### ISSUE TITLE
Docker commands inconsistency

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#27353]
Filing a bug based upon the tweet at https://twitter.com/agoncal/status/786187878195863552

`docker volume ls` / `docker service ls` / `docker network ls`. So why `docker images` and not `docker image ls` ? #Docker #Consistency

Thanks @agoncal!

**Comment by agoncal** [comment]
Based on the other Docker commands, I would expect the `image` command to be:

```
docker image inspect     
docker image ls         
docker image rm
...
```

**Comment by justincormack** [comment]
cc @bfirsh

**Comment by vdemeester** [comment]
See  #26025, should be in 1.13

**Comment by justincormack** [comment]
Ah as that issue is merged, will close this one.
