### ISSUE TITLE
Cannot run container on ARM when activating AppArmor

### ISSUE THREAD

**Issue by jcberthon** [docker/docker#27351]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

On a Raspberry Pi 2, I have recompile a Kernel adding the AppArmor and User namespace. I've install the new Kernel on the already configured Raspbian Jessie OS. The Pi boot correctly and after installing the apparmor package. I've installed Docker using the armhf package provided by the Docker website (version 1.12.2 as of writing). I rebooted, every is working correctly. AppArmor is properly activated, Docker daemon is running and configured successfully using the overlay2 storage backend.

Now if I try to run the 'armhf/hello-world' image or if I try to build a Dockerfile which contains a RUN instruction I get the following error:

    docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"apparmor: config provided but apparmor not supported\\\"\"\n".

**Steps to reproduce the issue:**
1. Install Raspbian Jessie on A Raspberry Pi 2 (or possibly on any armhf board or VM)
2. Make sure the kernel support AppArmor and make sure AppAmor is installed in the OS
3. Install Docker 1.12.2 for armhf
4. Run: docker run armhf/hello-world

**Describe the results you received:**

I get this error and the container is not launched:

    docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"apparmor: config provided but apparmor not supported\\\"\"\n".

**Describe the results you expected:**

The container should be up and running.

**Additional information you deem important (e.g. issue happens only occasionally):**

- Raspbian Jessie with latest updates (I did an apt-get upgrade)
- Kernel 4.4.23 compiled according to these instructions (https://www.raspberrypi.org/documentation/linux/kernel/building.md) using this repository for the Linux Kernel (https://github.com/jcberthon/linux) (a recent fork or the Raspberry Pi foundation own Kernel where I only added for the Raspberry Pi 2 configuration the parameters for supporting user namespace, seccomp filtering and apparmor).
- Docker 1.12.2 from Docker website (apt source: `deb [arch=armhf] https://apt.dockerproject.org/repo raspbian-jessie main`)

**Important**: When I compile a Kernel and add only the seccomp filtering and user namespace, then Docker is running correctly. I can launch a container, I can build images where `RUN` instructions are used, etc. Everything work smoothly. Only when adding the AppArmor configuration do I run into trouble.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:52:51 2016
 OS/Arch:      linux/arm

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:52:51 2016
 OS/Arch:      linux/arm
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 2
Server Version: 1.12.2
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.23-ns-seccomp-aa-v7+
Operating System: Raspbian GNU/Linux 8 (jessie)
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 957.2 MiB
Name: pidock
ID: ********
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpuset support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Here are the outputs of the commands uname and aa-status, and of the check-config.sh script from Docker git repo.

```
$ uname -a
Linux pidock 4.4.23-ns-seccomp-aa-v7+ #3 SMP Tue Oct 11 22:43:41 CEST 2016 armv7l GNU/Linux

$ ~/check-config.sh                                                 [13/648]
info: reading kernel config from /proc/config.gz ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- apparmor: enabled and tools installed
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_MEMCG_KMEM: missing
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
    Optional (for secure networks):
    - CONFIG_XFRM_ALGO: enabled
    - CONFIG_XFRM_USER: enabled
  - "ipvlan":
    - CONFIG_IPVLAN: enabled (as module)
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

$ sudo aa-status
apparmor module is loaded.
61 profiles are loaded.
26 profiles are in enforce mode.
   /usr/bin/evince
   /usr/bin/evince-previewer
   /usr/bin/evince-previewer//sanitized_helper
   /usr/bin/evince-thumbnailer
   /usr/bin/evince-thumbnailer//sanitized_helper
   /usr/bin/evince//sanitized_helper
   /usr/bin/irssi
   /usr/bin/lxc-start
   /usr/bin/pidgin
   /usr/bin/pidgin//launchpad_integration
   /usr/bin/pidgin//sanitized_helper
   /usr/bin/totem
   /usr/bin/totem-audio-preview
   /usr/bin/totem-video-thumbnailer
   /usr/lib/arm-linux-gnueabihf/lightdm/lightdm-guest-session-wrapper
   /usr/lib/chromium-browser/chromium-browser//browser_java
   /usr/lib/chromium-browser/chromium-browser//browser_openjdk
   /usr/lib/chromium-browser/chromium-browser//sanitized_helper
   /usr/sbin/apt-cacher-ng
   /usr/sbin/ntpd
   /usr/sbin/tcpdump
   docker-default
   gst_plugin_scanner
   lxc-container-default
   lxc-container-default-with-mounting
   lxc-container-default-with-nesting
35 profiles are in complain mode.
   /sbin/klogd
   /sbin/syslog-ng
   /sbin/syslogd
   /usr/lib/chromium-browser/chromium-browser
   /usr/lib/chromium-browser/chromium-browser//chromium_browser_sandbox
   /usr/lib/chromium-browser/chromium-browser//lsb_release
   /usr/lib/chromium-browser/chromium-browser//xdgsettings
   /usr/lib/dovecot/anvil
   /usr/lib/dovecot/auth
   /usr/lib/dovecot/config
   /usr/lib/dovecot/deliver
   /usr/lib/dovecot/dict
   /usr/lib/dovecot/dovecot-auth
   /usr/lib/dovecot/dovecot-lda
   /usr/lib/dovecot/imap
   /usr/lib/dovecot/imap-login
   /usr/lib/dovecot/lmtp
   /usr/lib/dovecot/log
   /usr/lib/dovecot/managesieve
   /usr/lib/dovecot/managesieve-login
   /usr/lib/dovecot/pop3
   /usr/lib/dovecot/pop3-login
   /usr/lib/dovecot/ssl-params
   /usr/sbin/avahi-daemon
   /usr/sbin/dnsmasq
   /usr/sbin/dovecot
   /usr/sbin/identd
   /usr/sbin/mdnsd
   /usr/sbin/nmbd
   /usr/sbin/nscd
   /usr/sbin/smbd
   /usr/sbin/smbldap-useradd
   /usr/sbin/smbldap-useradd///etc/init.d/nscd
   /usr/{sbin/traceroute,bin/traceroute.db}
   /{usr/,}bin/ping
2 processes have profiles defined.
1 processes are in enforce mode.
   /usr/sbin/ntpd (900)
1 processes are in complain mode.
   /usr/sbin/dnsmasq (774)
0 processes are unconfined but have a profile defined.```

**Comment by justincormack** [comment]
Did you add the userspace apparmor tools? I would not expect there to be anything different with Arm, but looks like you may be the first person to try it.

**Comment by jcberthon** [comment]
Hi @justincormack 
I installed the apparmor package (indeed because I could run `aa-status`) and in addition I installed some profiles: apparmor-profiles and apparmor-profiles-extra.

As you can see, I provided the aa-status output, so the apparmor user space tools should be installed correctly and it seems that apparmor is working correctly as well.

**Comment by jcberthon** [comment]
Ho and the check-config.sh tool is reporting `apparmor: enabled and tools installed`, so I guess the required tools are installed.

Let me know if you need other information.

**Comment by justincormack** [comment]
That is very odd, it all looks like `runc` is not compiled with apparmor support, even though the config suggests it should be.

**Comment by jcberthon** [comment]
This is also how I interpreted the error message but sometimes error messages are misleading. Anyway is it possible that the docker deb package for armhf isn't built with AppArmor support?

**Comment by justincormack** [comment]
The deb package seems to be, as `docker info` says `Security Options: apparmor`. So I think it must be `runc` even though the `Dockerfile.armhf` at the time did also add the `apparmor` build flag there. So it is a bit odd. I don't have a setup like this but may be able to set one up.

**Comment by jcberthon** [comment]
If you want me to build or execute something on my platform to save you from setting up one, let me know.

I also think it should be possible to create a KVM VM using armhf on a x86_64 host. But I'm not too sure how to install Raspbian in such environment.

**Comment by AshCoolman** [comment]
Also getting this on Ubuntu 16.04, and docker image https://github.com/mhart/alpine-node

```
docker build -t alpine-images .
```

**Comment by justincormack** [comment]
@AshCoolman that is a different issue, we are talking about running on a raspberry pi

**Comment by calmera** [comment]
We are experiencing the same issues with docker 1.12.2 running on ubuntu trusty 14.04.2 x86_64

**Comment by justincormack** [comment]
@calmera this issue is for Raspberry Pi/arm hardware only. Pleas open another issue. They might be related but it is fairly unlikely.

**Comment by calmera** [comment]
owkay will do. Just informational, but it seems that reinstalling apparmor solves it. The problem seems to be that the apparmor profiles are missing.

**Comment by jcberthon** [comment]
@calmera I'll try reinstalling AppArmor but at least the profile for Docker is there and listed by the `aa-status` command. So it seems that you have a different issue.

But as I said I will try it, in a couple of hours as I need to take care of my family now 😊

**Comment by jakerobers** [comment]
@calmera I am experiencing this issue on Ubuntu Trusty 16.04.1 with Docker 1.12.2. Have you made an issue yet? Otherwise I can.

**Comment by jcberthon** [comment]
I did test to remove and purge all my AppArmor and Docker package. Then I reinstall first AppArmor packages and then Docker. But to no avail, I still get the same exact error in the same context.

However, @justincormack I've found something interesting:

On Ubuntu 16.04 with Docker 1.12.2 when checking the lib dependencies of `docker-runc` I get this:

```
$ ldd /usr/bin/docker-runc 
	linux-vdso.so.1 =>  (0x00007ffcbc0da000)
	libapparmor.so.1 => /lib/x86_64-linux-gnu/libapparmor.so.1 (0x00007f546d684000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f546d467000)
	libseccomp.so.2 => /lib/x86_64-linux-gnu/libseccomp.so.2 (0x00007f546d228000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f546ce5f000)
	/lib64/ld-linux-x86-64.so.2 (0x00005573bd7df000)
```

Whereas on Raspbian Jessie with Docker 1.12.2 I get this:

```
$ ldd /usr/bin/docker-runc 
        linux-vdso.so.1 (0x7eec6000)
        /usr/lib/arm-linux-gnueabihf/libarmmem.so (0x76f33000)
        libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0x76ef9000)
        libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76db8000)
        /lib/ld-linux-armhf.so.3 (0x54b7a000)
```

Notice that there is no dependency on libapparmor1? I've checked that on both Ubuntu (although from the output of `ldd` it was obvious that it was installed) and Raspbian, `libapparmor1` is installed.

This seems to confirm what you said that runc seems to be missing the AppArmor dependecy (although it seems part of your build configuration).

**Comment by mlaventure** [comment]
We don't specify the `BUILDTAGS` for `runc` when building it in the `Dockerfile` for armhf deb and `runc` default to only `seccomp`, hence the issue.

**Comment by jcberthon** [comment]
One obvious way to fix the issue seems to add AppArmor to the BUILDTAGS. But I would say that when runc is built without this flag, it should still run on a host regardless if this host support (or not) AppArmor. So there seems to be a configuration problem (the build flag) and a bug.

**Comment by justincormack** [comment]
@mlaventure yes we do on 1.12.x https://github.com/docker/docker/blob/1.12.x/Dockerfile.armhf#L199

**Comment by justincormack** [comment]
PR to fix this for armhf ubuntu https://github.com/docker/docker/pull/27327

**Comment by jcberthon** [comment]
After reviewing the PR #27327 and as far as I understood the build procedure after going through it in the last 30 min, this seems to only consider Ubuntu Trusty armhf packages. Not Raspbian nor Debian.

Therefore, I'm have prepared another PR with correct build flags for `runc` for Debian and Raspbian on armhf. I have successfully build the deb package on Raspbian and I am now able to build or run containers on Raspbian with AppArmor activated.

**Comment by jcberthon** [comment]
**Note**: I don't know if it shall be considered a bug that `runc` cannot run a container on a host with AppArmor activated if `runc` was not compiled with AppArmor.  
If it is more of a feature, then perhaps the error message could be more explicit.

What do you think?
