### ISSUE TITLE
Feature request: Transfer images from one registry to another registry without pull, tag,push

### ISSUE THREAD

**Issue by sanket-thakkar** [docker/docker#27378]
If I want to transfer docker images from private registry to another private registry 
OR
If I want to transfer docker images from public registry to private registry.

In above listed cases its understood that user authorised to do operations for that registry server.

Reason for requesting this feature because then image pulling/pushing internet network traffic can be reduce tremendously if once images available in one image server place and then can transfer internally via LAN or WAN to speedup performance.

Known alternative:
1.
We can do it via docker save and load options. 
But in that case as well let's say if I want to transfer images from Docker hub (hub.docker.com) (Public docker repositories) to my private registry without pulling image locally in internal server machine and then transfer to private registry.

Is there any alternative provided by docker to support or handle this kind of situation? Any suggestions or corrections are most welcome.

Thanks

**Comment by thaJeztah** [comment]
Could you open this in the https://github.com/docker/distribution/issues repository? This question is really about the registry (distribution), not the docker engine.

I'll close this issue here, but feel free to continue the conversation
