### ISSUE TITLE
Arrows etc. still don't work properly in Docker 1.12.2 + ConEmu

### ISSUE THREAD

**Issue by vlascik** [docker/docker#27389]
**Description**
While docker 1.12.2-rc1 made arrows in bash work, in programs started from there they still don't work properly in ConEmu.

**Steps to reproduce the issue:**
Every time I'm doing `docker exec -it <container> /bin/bash`. TERM is set to `xterm`, and i'm running `less <some_log>` and trying to navigate using arrows inside.

**Describe the results you received:**
- cmd.exe + ubuntu:16.10 or 16:04 container -> works
- cmd.exe + alpine:latest container -> works
- cmd.exe + conemu + alpine container -> works
- cmd.exe + conemu + ubuntu container -> doesn't work
- msys + conemu + alpine container -> works
- msys + conemu + ubuntu container -> doesn't work

**Additional information you deem important (e.g. issue happens only occasionally):**
According to ConEmu author, "Docker has special branch in their code, which Docker uses when it see "ConEmu". In Unix there are two styles of Arrow keys representation. Seems like Docker stuck to one and forgot about other. That's not a ConEmu problem, ConEmu doesn't send xterm input sequences to Docker at all."
See https://github.com/Maximus5/ConEmu/issues/829

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 10
 Paused: 0
 Stopped: 2
Images: 448
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /mnt/sda/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 498
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - Tue Oct 11 23:40:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.947 GiB
Name: dev-vl
ID: YMKN:7X3C:H7KR:CU2D:33E6:RC7S:NQ6G:UJAB:KC6X:JE4N:D3NA:DW3F
Docker Root Dir: /mnt/sda/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 68
 Goroutines: 96
 System Time: 2016-10-14T14:56:51.853055821Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
docker toolbox in vmware on win10 x64

**Comment by jhowardmsft** [comment]
AFAIK, this is fixed. Closing - please re-open a new issue if you are still seeing oddities.

**Comment by dermeister0** [comment]
Docker version 17.03.0-ce, build 60ccb22 - not fixed.

F1-F4 keys do not work in ConEmu.
