### ISSUE TITLE
Consul protocol for docker.

### ISSUE THREAD

**Issue by aensidhe** [docker/docker#27398]
Sometimes container is not deleted from consul and adding it back (via docker network connect) results in error:
```
Error response from daemon: service endpoint with name <name> already exists
```

If I found and delete a key from consul: `docker/network/v1.0/endpoint/network-id/endpoint-id/` error changes to:

```
Error response from daemon: Address already in use
```

We use static ips, because we are not ready yet to move to real service discovery from consul.

What keys should I delete to cleanup that record?

**Comment by thaJeztah** [comment]
You can also `docker network disconnect --force ...` to force disconnecting (or removing it from the database if the container was already disconnected)

**Comment by aensidhe** [comment]
@thaJeztah thank you for your kind suggestion.

But we have this problem as the result of automatic deployment when the old container, connected to the network, was removed. And new container, created in place of old with same name for the sake of manageability can't connect to the swarm network.

So, output for your command is:
```
Error response from daemon: container ab4452821766c744b0fe8e1e9d51ce08cc5f7341a1950d69e802981326dca814 is not connected to the network
```

**Comment by thaJeztah** [comment]
Can you provide the output of `docker version` and `docker info`?

**Comment by aensidhe** [comment]
```
user@host:~$ docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   20f81dd
 Built:        Thu Mar 10 15:54:52 2016
 OS/Arch:      linux/amd64
user@host:~$ docker info
Containers: 13
 Running: 7
 Paused: 0
 Stopped: 6
Images: 148
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-252:0-11143696-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 14.02 GB
 Data Space Total: 107.4 GB
 Data Space Available: 93.35 GB
 Metadata Space Used: 14.05 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.133 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.77 (2012-10-15)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: null host overlay bridge
Kernel Version: 4.1.13-040113-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38 GiB
Name: hostname
ID: KAR6:6HMK:2ZRP:3RKE:X3N6:JIDI:U5GL:RPYJ:25AP:3FLD:PEO5:ZHCL
WARNING: No swap limit support
Cluster store: consul://consul_ip:consul_port
Cluster advertise: consul_ip:consul_advertise_port
user@host:~$
```

**Comment by thaJeztah** [comment]
would you be able to check if this is still an issue on the current release (1.12.2)?

**Comment by aensidhe** [comment]
@thaJeztah I need to restore current server back before proceeding to upgrade docker packages, unfortunately.

**Comment by aboch** [comment]
@aensidhe The only way to gracefully release the address is to go through the stale endpoint removal procedure that @thaJeztah suggested. 

But now that you manaully deleted the endpoint from the store, you won't no longer be able to release that address.

The db key which holds the IP assignment would be `docker/network/v1.0/ipam/default/config/GlobalDefault/` but if you remove it, you will loose the whole subnet and currently assigned addresses.

If you can, a better option is move your running containers to a newly created overlay network, remove and recreate your original overlay network and reconnect the containers back.

**Comment by aensidhe** [comment]
I know two things. 
1st: if I change a static ip for container, all will work well (but I'll need to redeploy all apps)
2nd: that key contains only subnetworks:
```
{"Scope":"","Subnets":{"GlobalDefault/10.11.0.0/16":{"ParentKey":{"AddressSpace":"","Subnet":"","ChildSubnet":""},"Pool":"10.11.0.0/16","RefCount":1},"GlobalDefault/10.21.0.0/16":{"ParentKey":{"AddressSpace":"","Subnet":"","ChildSubnet":""},"Pool":"10.21.0.0/16","RefCount":1},"GlobalDefault/10.31.0.0/16":{"ParentKey":{"AddressSpace":"","Subnet":"","ChildSubnet":""},"Pool":"10.31.0.0/16","RefCount":1}}}
```

**Comment by aboch** [comment]
@aensidhe 
Sorry what I posted was for the pool config.
The address assignment data is kept at the key: `docker/network/v1.0/ipam/default/data/GlobalDefault/<pool id>`

**Comment by aensidhe** [comment]
@aboch do I undestand correctly, that that key contains bitmap of assigned addresses?

**Comment by aboch** [comment]
Yes, that key contains the bitmasks of the assigned addresses for that address pool.

**Comment by aensidhe** [comment]
so, if I had /16 network, e.g. 10.1.0.0/16 and address 10.1.20.30, how should I calculate index? 20*256+30 or 30*256+20?

**Comment by aboch** [comment]
The first you said (downmark hid the `*`), 20 * 256 + 30

**Comment by aboch** [comment]
@aensidhe Are you planning to modify that pool's bitmask ? That cannot be done. The  `sequence` field contains more stuff than that. If you pass me the curent key value and tell me which IPs need to be reserved, I can prepare it for you.

**Comment by aensidhe** [comment]
@aboch timezone issues, I was asleep :)

Ok, I understand now, that it will be simplier to assign new ips.

Thank you for your help, this can be closed, I think.
