### ISSUE TITLE
Swarm mode services cannot publish ports as both TCP and UDP

### ISSUE THREAD

**Issue by jefflill** [docker/docker#27390]
**Description**

Docker swarm mode services cannot publish a port using **both** the TCP and UDP protocols.

**Steps to reproduce the issue:**
1. Create a swarm mode cluster.
2. Run: `docker service create --name test -p 10000:10000 -p 10000:10000/udp alpine sleep 100000`

**Describe the results you received:**
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided

**Describe the results you expected:**
The service should have been created with port 10000 mapped for both TCP and UDP.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 1.12.2
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: active
 NodeID: 57efxfpx4yqzx3vha67pmv998
 Is Manager: true
 ClusterID: 4oabtzwdobpc29fioqyzt49kt
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.1.30
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.851 GiB
Name: manage-0
ID: CMHY:WEPP:RVWT:KJIP:RZ5G:ZIZH:FL2V:CENO:UISY:WVUM:NMF2:XPMV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Windows 10 on a local Hyper-V cluster of Ubuntu-16.04 VMs.

**Comment by aboch** [comment]
I think this has just been fixed in https://github.com/docker/swarmkit/pull/1632

**Comment by jefflill** [comment]
Thanks: Very cool!

I'll have to figure out how to get the latest unstable bits and try it out.  Do you happen to know whether I can find these at http://test.docker.com or will I need to build this myself?

**Comment by aboch** [comment]
@jefflill Sorry I wasn't clear. The fix was just pushed to the swarmkit branch, but was not ported to docker/docker yet. When this is done via a vendoring PR, this issue can be closed.
So current docker build, does not have the fix yet.

**Comment by jefflill** [comment]
OK.  Thanks.

**Comment by thaJeztah** [comment]
i'll reopen as it's not fixed in docker/docker yet
