### ISSUE TITLE
docker stats Collection not working for Mesos.  Docker 1.12.2

### ISSUE THREAD

**Issue by raghu999** [docker/docker#27400]
**Description**

We are using `bobrik/collectd-docker` docker image in our Mesos environment to collect docker stats of our containers.  After updating to latest version of Docker 1.12.2 the docker stats returns empty values and also we observe we are not able to do a `docker exec` into the container pasting the two outputs for your reference

```
[root@mesosslv ~]# docker exec -ti ca16ec7d9c6e bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: cannot exec a container that has run and stopped\n"
```

<img width="917" alt="screen shot 2016-10-14 at 5 56 15 pm" src="https://cloud.githubusercontent.com/assets/12721392/19403980/b4dc7dd4-9238-11e6-98e9-6812df4f5b96.png">

-->

**Steps to reproduce the issue:**
1. Deploy `bobrik/collectd-docker` to multiple Mesos-Agents.
2. Try running `docker stats` and try do to do `docker exec` into the collectd container

**Describe the results you received:**
->Seeing Empty values returned for `docker stats`
->Unable to SSH into a container when running docker exec 
->Works in few mesos-agents does not work in most of the mesos-agents , All configurations are same for all the mesos-agents we also updated our docker.service file based on the release notes.

**Output of `docker version`:**

```
Docker version 1.12.2, build bb80604
```

**Output of `docker info`:**

```
[root@mesosslv ~]# docker info
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 5
Server Version: 1.12.2
Storage Driver: btrfs
 Build Version: Btrfs v3.19.1
 Library Version: 101
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null weavemesh overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.26 GiB
Name: mesosslv.foo.bar
ID: PFGD:OHJ3:GMU6:JABQ:WLHZ:3R4N:JRJV:L6QE:552X:ILYA:X2MW:CTKJ
Docker Root Dir: /srv/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 registry:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
looks like this was opened by mistake

**Comment by raghu999** [comment]
@thaJeztah I was updating the issue

**Comment by thaJeztah** [comment]
Reopening, sorry!

**Comment by mlaventure** [comment]
@raghu999 can you check that you have the correct version of `docker-runc` installed? 

The error you see is coming straight from it, not from the daemon per se.

The expected version for `1.12.2` is `02f8fa7863dd3f82909a73e2061897828460d52f`

**Comment by mlaventure** [comment]
i.e:
```
$ ./runc --version
runc version 1.0.0-rc2
commit: 02f8fa7863dd3f82909a73e2061897828460d52f
spec: 1.0.0-rc2-dev
```

**Comment by raghu999** [comment]
```
[root@mesoslv ~]# docker-runc --version
runc version 1.0.0-rc1
commit: cc29e3dded8e27ba8f65738f40d251c885030a28
spec: 1.0.0-rc1
```

**Comment by mlaventure** [comment]
That's your issue there. Somehow it didn't get updated.

**Comment by raghu999** [comment]
Updated my previous comment. We know of a issue which is fixed in 1.12.1 by this https://github.com/docker/docker/pull/21904

**Comment by mlaventure** [comment]
@raghu999 is this still an issue on 1.12.3?

**Comment by raghu999** [comment]
@mlaventure  I updated to 1.12.3 and I don't see any issue . Thanks
