### ISSUE TITLE
Docker Failes to start in windows7 64 bit 

### ISSUE THREAD

**Issue by chandu12345** [docker/docker#27406]
After Starting Docker Quick Start Terminal getting 

Docker Quick Start Terminal log 

Creating machine...
(default) Copying C:\Users\creddyp\.docker\machine\cache\boot2docker.iso to C:\U
sers\creddyp\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with boot2docker...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
To see how to connect your Docker Client to the Docker Engine running on this vi
rtual machine, run: C:\Program Files\Docker Toolbox\docker-machine.exe env defau
lt
Looks like something went wrong in step 'Checking status on default'... Press an
y key to continue...

**VM.log-------**

00:00:45.029355 VMMDev: Guest Log: VBoxService 5.1.6 r110634 (verbosity: 0) linux.amd64 (Sep 12 2016 18:11:10) release log
00:00:45.029533 VMMDev: Guest Log: 00:00:00.000208 main     Log opened 2016-10-15T01:00:00.921761000Z
00:00:45.031661 VMMDev: Guest Log: 00:00:00.002518 main     OS Product: Linux
00:00:45.032616 VMMDev: Guest Log: 00:00:00.003478 main     OS Release: 4.4.24-boot2docker
00:00:45.032801 VMMDev: Guest Log: 00:00:00.003666 main     OS Version: #1 SMP Fri Oct 7 20:54:27 UTC 2016
00:00:45.032950 VMMDev: Guest Log: 00:00:00.003813 main     Executable: /sbin/VBoxService
00:00:45.033067 VMMDev: Guest Log: 00:00:00.003815 main     Process ID: 2374
00:00:45.033174 VMMDev: Guest Log: 00:00:00.003816 main     Package type: LINUX_64BITS_GENERIC
00:00:45.038116 VMMDev: Guest Log: 00:00:00.008976 main     5.1.6 r110634 started. Verbose level = 0
00:00:45.041690 VMMDev: Guest Log: 00:00:00.012541 vminfo   rtldrNativeLoad: dlopen('libdbus-1.so.3', RTLD_NOW | RTLD_LOCAL) failed: libdbus-1.so.3: cannot open shared object file: No such file or directory
00:00:45.041910 VMMDev: Guest Log: 00:00:00.012769 vminfo   Error: Unable to connect to system D-Bus (1/3): D-Bus not installed
00:00:45.259098 NAT: IPv6 not supported
00:00:46.989461 NAT: DHCP offered IP address 10.0.2.15
00:00:46.990487 NAT: DHCP offered IP address 10.0.2.15
00:00:50.041219 VMMDev: Guest Log: 00:00:05.014414 vminfo   Error: Unable to connect to system D-Bus (2/3): D-Bus not installed
00:00:55.044601 VMMDev: Guest Log: 00:00:10.017738 vminfo   Error: Unable to connect to system D-Bus (3/3): D-Bus not installed

Please let us know any solution for this.

**Comment by chandu12345** [comment]
Docker Toolbox Version: DockerToolbox-1.12.2

**Comment by thaJeztah** [comment]
Looks like this is an issue related to docker-toolbox, or VirtualBox, can you re-open this issue in the docker toolbox issue tracker? https://github.com/docker/toolbox/issues
