### ISSUE TITLE
Dockerfile chains using `FROM` command

### ISSUE THREAD

**Issue by AnalogJ** [docker/docker#2740]
I did a quick search of the current issues list, but I apologize if this has already been brought up, there were 20+ pages referencing the Dockerfile.

Would it be possible to allow the `FROM` command to reference other Dockerfiles rather than just base images?

The current `FROM` command only supports the following:

`FROM <image>` Or ` FROM <image>:<tag>`

It would really help my code re-usability if we could also add in support for Dockerfiles and git repos à la the `docker build` command:

 `FROM <git repository>` or `FROM <file path>`
eg. `FROM github.com/analogj/docker-apache` 

This would make it easier to breakup my large Dockerfiles into smaller chain-able parts, while also making it easier to update my 'base images'

**Comment by jfrazelle** [comment]
also related https://github.com/docker/docker/issues/7115

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by wildone** [comment]
> Hello! We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Is this still the case?
