### ISSUE TITLE
Invalid JSON returned for /containers/create

### ISSUE THREAD

**Issue by matutter** [docker/docker#27418]
**Description**
The below is the response body for a `POST (uri)/containers/create?name=(name)` and it is malformed JSON but valid JS. This is an issue because `JSON.parse` cannot handle the response. Instead we have to resort to using `eval()` on the response.

Actual repsonse:
```json
{ Id: '604e48f4b7a650340b43c0bbb139d334edf63fe3476f2e503877b3e2c8cc1a2a',
  Warnings: null }
```

Should be:
```json
{ "Id": "604e48f4b7a650340b43c0bbb139d334edf63fe3476f2e503877b3e2c8cc1a2a",
  "Warnings": null }
```

**Steps to reproduce the issue:**
1. Make any valid `/containers/create` request to a engine remote
2. Run JSON.parse on the response's body
3. Handle error `SyntaxError: Unexpected token o in JSON at position 1`

**Describe the results you received:**
I received invalid JSON on a http response that should yield valid JSON for the content-type "application/json"

**Describe the results you expected:**
Valid json that meets RFC7159 specification  https://tools.ietf.org/html/rfc7159 
Specifically the part that says **"A string begins and ends with quotation marks."**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 10
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:0-202281288-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 932.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 33.4 GB
 Metadata Space Used: 2.22 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: vm
ID: RPLT:DWEL:LJBT:54Z6:H2KO:44F5:2NQB:BL6K:L7IT:UCMJ:OYQH:UT6Z
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 26
 System Time: 2016-10-16T09:59:17.159342406-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running Centos 7 in VirtualBox Version 5.1.6 r110634 (Qt5.5.1)
I can replicate this on my DigitalOcean VPS running Centos7 as well.
I encountered this while writing a NodeJS library https://github.com/matutter/docker-as-promised/tree/dev

**Comment by matutter** [comment]
After updating to `Docker version 1.12.2, build bb80604` the issue remains.

**Comment by thaJeztah** [comment]
I'm nog able to reproduce; could this be something in the library you're using?

To reproduce, I used cURL to send a request to the api;

```bash
curl -v \
  --unix-socket /var/run/docker.sock \
  "http://localhost/v1.24/containers/create?name=foobar" \
  -H "Content-Type: application/json" \
  -d '{"Image": "nginx:alpine"}'
```

```
*   Trying /var/run/docker.sock...
* Connected to localhost (/var/run/docker.sock) port 80 (#0)
> POST /v1.24/containers/create?name=foobar HTTP/1.1
> Host: localhost
> User-Agent: curl/7.50.3
> Accept: */*
> Content-Type: application/json
> Content-Length: 25
>
* upload completely sent off: 25 out of 25 bytes
< HTTP/1.1 201 Created
< Content-Type: application/json
< Server: Docker/1.12.2 (linux)
< Date: Mon, 17 Oct 2016 02:06:47 GMT
< Content-Length: 90
<
{"Id":"a4983e725bc6011a04daa87eaa3bf109501fb717117d730b04a0c4f92ef8f27a","Warnings":null}
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
```

Can you try reproducing without using that NodeJS library, and doing a direct call with cURL?

**Comment by matutter** [comment]
> I'm nog able to reproduce; could this be something in the library you're using?
Jeesh, yes it seems like it's feature of one of my dependencies. 

Not a bug.

**Comment by thaJeztah** [comment]
Thanks for confirming @matutter, and thanks for reporting as it could've been a bug :smile:
