### ISSUE TITLE
Feature request: a command to clear (truncate) container logs.

### ISSUE THREAD

**Issue by zerthimon** [docker/docker#27414]
For those containers that are logging to console .....

Such a basic feature and not implemented yet ?

**Comment by thaJeztah** [comment]
Can you explain your use case a bit more in depth? What would you expect this to look like, and isn't covered by;

- specifying log-rotation (max-size, max-files); https://docs.docker.com/engine/admin/logging/overview/#/json-file-options
- using `docker logs --tail 0 --follow <container>`

Implementing this would probably only be possible for the json-logs, but not for any other logging driver, which would really limit its use

**Comment by cpuguy83** [comment]
Closing since we support log rotation as well as a host of other log drivers.
