### ISSUE TITLE
docker - write pipe: bad file descriptor

### ISSUE THREAD

**Issue by openmax** [docker/docker#27410]
# **SOLVED for ppc64le  : docker run ppc64le/hello-world** 
# ** Open for other arch **

**Description**
Docker error : "write pipe: bad file descriptor" on every app that i run  !!
I'm on power8 ubuntu ppc64el but same error on intel arch ...
see : http://stackoverflow.com/questions/40022817/docker-write-pipe-bad-file-descriptor

**Steps to reproduce the issue:**
docker run hello-world

**Describe the results you received:**
write pipe: bad file descriptor

**Describe the results you expected:**

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/ppc64le

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/ppc64le

```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 1
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: ppc64le
CPUs: 40
Total Memory: 3.811 GiB
Name: ubuntu
ID: A2XW:VDZQ:C4I7:HLDP:26CE:XSNG:HBQU:YX2Z:M6BJ:NLSM:7AQ4:ZHWV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
uname -a
Linux ubuntu 4.4.0-43-generic #63-Ubuntu SMP Wed Oct 12 13:45:41 UTC 2016 ppc64le ppc64le ppc64le GNU/Linux

systemd --version
systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN

**Comment by thaJeztah** [comment]
PowerPC is currently not a supported architecture; how did you install docker? Did you compile yourself? Do the daemon logs show anything?

**Comment by openmax** [comment]
ppc64le is a supported platform by ubuntu , so i simple : "sudo apt-get install docker.io"
but the problem is the same on i686 intel look at the link i post  :  http://stackoverflow.com/questions/40022817/docker-write-pipe-bad-file-descriptor 

the daemon logs don't show anything , i suppose is a problem with systemd 

this is the syslog where i start : docker run hello-world

Oct 16 09:28:31 ubuntu kernel: [38716.489665] aufs au_opts_verify:1597:dockerd[2271]: dirperm1 breaks the protection by the permission bits on the lower branch
Oct 16 09:28:31 ubuntu kernel: [38716.522883] aufs au_opts_verify:1597:dockerd[2271]: dirperm1 breaks the protection by the permission bits on the lower branch
Oct 16 09:28:31 ubuntu kernel: [38716.564416] aufs au_opts_verify:1597:dockerd[2271]: dirperm1 breaks the protection by the permission bits on the lower branch
Oct 16 09:28:31 ubuntu kernel: [38716.604230] aufs au_opts_verify:1597:dockerd[2271]: dirperm1 breaks the protection by the permission bits on the lower branch
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <warn>  [1476602911.9234] device (veth9bb559a): failed to find device 4 'veth9bb559a' with udev
Oct 16 09:28:31 ubuntu systemd-udevd[19948]: Could not generate persistent MAC address for veth9bb559a: No such file or directory
Oct 16 09:28:31 ubuntu systemd-udevd[19950]: Could not generate persistent MAC address for veth248074b: No such file or directory
Oct 16 09:28:31 ubuntu kernel: [38716.612166] device veth248074b entered promiscuous mode
Oct 16 09:28:31 ubuntu kernel: [38716.612798] IPv6: ADDRCONF(NETDEV_UP): veth248074b: link is not ready
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <info>  [1476602911.9276] manager: (veth9bb559a): new Veth device (/org/freedesktop/NetworkManager/Devices/3)
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <warn>  [1476602911.9281] device (veth248074b): failed to find device 5 'veth248074b' with udev
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <info>  [1476602911.9303] manager: (veth248074b): new Veth device (/org/freedesktop/NetworkManager/Devices/4)
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <info>  [1476602911.9480] devices added (path: /sys/devices/virtual/net/veth248074b, iface: veth248074b)
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <info>  [1476602911.9481] device added (path: /sys/devices/virtual/net/veth248074b, iface: veth248074b): no ifupdown configuration found.
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <info>  [1476602911.9496] devices added (path: /sys/devices/virtual/net/veth9bb559a, iface: veth9bb559a)
Oct 16 09:28:31 ubuntu NetworkManager[1506]: <info>  [1476602911.9497] device added (path: /sys/devices/virtual/net/veth9bb559a, iface: veth9bb559a): no ifupdown configuration found.
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.2010] device (veth9bb559a): driver 'veth' does not support carrier detection.
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.2060] devices removed (path: /sys/devices/virtual/net/veth9bb559a, iface: veth9bb559a)
Oct 16 09:28:32 ubuntu kernel: [38716.894041] eth0: renamed from veth9bb559a
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.2457] device (veth248074b): link connected
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.2467] device (docker0): link connected
Oct 16 09:28:32 ubuntu kernel: [38716.932466] IPv6: ADDRCONF(NETDEV_CHANGE): veth248074b: link becomes ready
Oct 16 09:28:32 ubuntu kernel: [38716.932648] docker0: port 1(veth248074b) entered forwarding state
Oct 16 09:28:32 ubuntu kernel: [38716.932686] docker0: port 1(veth248074b) entered forwarding state
Oct 16 09:28:32 ubuntu kernel: [38716.932860] IPv6: ADDRCONF(NETDEV_CHANGE): docker0: link becomes ready
Oct 16 09:28:32 ubuntu kernel: [38717.062133] docker0: port 1(veth248074b) entered disabled state
Oct 16 09:28:32 ubuntu kernel: [38717.062354] veth9bb559a: renamed from eth0
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.4766] device (veth248074b): link disconnected
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.4767] device (docker0): link disconnected (deferring action for 4 seconds)
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <warn>  [1476602912.4769] device (veth9bb559a): failed to find device 4 'veth9bb559a' with udev
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.4803] manager: (veth9bb559a): new Veth device (/org/freedesktop/NetworkManager/Devices/5)
Oct 16 09:28:32 ubuntu kernel: [38717.173312] docker0: port 1(veth248074b) entered disabled state
Oct 16 09:28:32 ubuntu kernel: [38717.175795] device veth248074b left promiscuous mode
Oct 16 09:28:32 ubuntu kernel: [38717.175803] docker0: port 1(veth248074b) entered disabled state
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.5089] devices added (path: /sys/devices/virtual/net/veth9bb559a, iface: veth9bb559a)
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.5089] device added (path: /sys/devices/virtual/net/veth9bb559a, iface: veth9bb559a): no ifupdown configuration found.
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.5096] devices removed (path: /sys/devices/virtual/net/veth9bb559a, iface: veth9bb559a)
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.5106] device (veth9bb559a): driver 'veth' does not support carrier detection.
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.5109] device (veth248074b): driver 'veth' does not support carrier detection.
Oct 16 09:28:32 ubuntu NetworkManager[1506]: <info>  [1476602912.5125] devices removed (path: /sys/devices/virtual/net/veth248074b, iface: veth248074b)
Oct 16 09:28:34 ubuntu avahi-daemon[1399]: Joining mDNS multicast group on interface docker0.IPv6 with address fe80::42:76ff:fe97:9f8d.
Oct 16 09:28:34 ubuntu avahi-daemon[1399]: New relevant interface docker0.IPv6 for mDNS.
Oct 16 09:28:34 ubuntu avahi-daemon[1399]: Registering new address record for fe80::42:76ff:fe97:9f8d on docker0.*.
Oct 16 09:28:37 ubuntu NetworkManager[1506]: <info>  [1476602917.0038] device (docker0): link disconnected (calling deferred action)

**Comment by justincormack** [comment]
Looks like an issue with Ubuntu's packaging, as ppc64le works very well
generally. I would disable NetworkManager as it looks like it is messing
with the docker interfaces, or get it to ignore docker0 and veth*
interfaces.

**Comment by openmax** [comment]
I disable networkmanager without success , i think the problem in on this sylog line :
``
systemd-udevd[19948]: Could not generate persistent MAC address for veth9bb559a: No such file or directory
``

**Comment by justincormack** [comment]
Hmm, surprised this is not the same on x86, are you on the latest systemd?

**Comment by openmax** [comment]
``systemd 229
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ -LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN
``

**Comment by rcarmo** [comment]
I'm getting this on `armhf` as well. Ubuntu's `docker.io` package, and I, too, blame `systemd`.

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
```

**Comment by rcarmo** [comment]
A little more info. I've been using `strace` to figure out what is going on, and apparently `docker` is getting confused with a file descriptor (`3` in this dump). Watch as the `POST` call appears to trigger the `write pipe: bad file descriptor` message:

```
getsockname(3, {sa_family=AF_LOCAL, NULL}, [2]) = 0
getpeername(3, {sa_family=AF_LOCAL, sun_path="/var/run/docker.sock"}, [23]) = 0
futex(0x10c24824, FUTEX_WAKE, 1)        = 1
write(3, "POST /v1.24/containers/create HT"..., 1505) = 1505
futex(0x10c24824, FUTEX_WAKE, 1)        = 1
futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
futex(0x10c24aa4, FUTEX_WAKE, 1)        = 1
epoll_wait(4, [], 128, 0)               = 0
epoll_wait(4, [{EPOLLOUT, {u32=1976238816, u64=1976238816}}], 128, -1) = 1
epoll_wait(4, [{EPOLLOUT, {u32=1976238816, u64=1976238816}}], 128, -1) = 1
epoll_wait(4, [{EPOLLIN|EPOLLOUT, {u32=1976238816, u64=1976238816}}], 128, -1) = 1
clock_gettime(CLOCK_MONOTONIC, {850, 276190506}) = 0
futex(0xa4d308, FUTEX_WAKE, 1)          = 1
futex(0xa4d298, FUTEX_WAKE, 1)          = 1
read(5, "HTTP/1.1 101 UPGRADED\r\nContent-T"..., 4096) = 109
futex(0x10c245a4, FUTEX_WAKE, 1)        = 1
futex(0x10c24824, FUTEX_WAKE, 1)        = 1
                                           write(3, "POST /v1.24/containers/044b95d17"..., 207) = 207
                                                                                                     futex(0x10c24d24, FUTEX_WAKE, 1)        = 1
                                                                                                                                                futex(0xa4d9ac, FUTEX_WAIT, 0, NULLwrite pipe: bad file descriptor
)    = 0
        epoll_wait(4, [], 128, 0)               = 0
                                                   _newselect(0, NULL, NULL, NULL, {0, 100}) = 0 (Timeout)
                                                                                                          futex(0x10c24d24, FUTEX_WAKE, 1)        = 1
                                                                                                                                                     futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = -1 EAGAIN (Resource temporarily unavailable)
                                                               futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = 0
futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
futex(0x10c24aa4, FUTEX_WAKE, 1)        = 1
futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = 0
futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = -1 EAGAIN (Resource temporarily unavailable)
futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = 0
futex(0xa4d9ac, FUTEX_WAIT, 0, NULL)    = 0
epoll_wait(4, [], 128, 0)               = 0
_newselect(0, NULL, NULL, NULL, {0, 100}) = 0 (Timeout)
futex(0x10c24d24, FUTEX_WAKE, 1)        = 1
epoll_wait(4, [], 128, 0)               = 0
epoll_wait(4,  <unfinished ...>
+++ exited with 1 +++
```

This might point to some issue in re-using descriptors inside the Go runtime (wouldn't be the first time that Go binaries worked differently on different architectures), or even something that needs checking in the Go source. 

I might try to rebuild `docker` on my own and test that binary, but the last time I had to do that it took me hours to get an `armhf` build done, and last time I checked Xenial wasn't a supported target...

**Comment by justincormack** [comment]
Oh, is the systemd unit file using socket activation? That's no longer
recommended.

If you start the docker daemon manually does it work?

**Comment by rcarmo** [comment]
Well, this is getting interesting. I started the `docker` daemon manually with `sudo strace dockerd`.

Then I tried running one of my existing containers (http://github.com/rcarmo/rpi-registry) and on the daemon side, this is what I got:

```
clock_gettime(CLOCK_MONOTONIC, {3045, 661692768}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 680777992}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 681927365}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 685591368}) = 0
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
futex(0x56f9e5a4, FUTEX_WAKE, 1)        = 1
clock_gettime(CLOCK_MONOTONIC, {3045, 708348877}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 714711990}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 715873758}) = 0
futex(0x1d12084, FUTEX_WAIT, 0, {0, 100000}) = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {3045, 717828286}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 719671043}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 721169529}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 721704216}) = 0
futex(0x1d12070, FUTEX_WAIT, 0, {0, 100000}) = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {3045, 722045153}) = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 722196611}) = 0
futex(0x56ce8324, FUTEX_WAKE, 1)        = 1
futex(0x56f9e5a4, FUTEX_WAKE, 1)        = 1
futex(0x56ca80a4, FUTEX_WAKE, 1)        = 1
futex(0x1d12008, FUTEX_WAKE, 1)         = 1
futex(0x1d1227c, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
clock_gettime(CLOCK_MONOTONIC, {3045, 727311705}) = 0
clock_gettime(CLOCK_REALTIME, {1476626502, 61768013}) = 0
epoll_wait(4, [], 128, 0)               = 0
clock_gettime(CLOCK_MONOTONIC, {3045, 728661911}) = 0
futex(0x1d12078, FUTEX_WAKE, 1)         = 1
futex(0x1d12008, FUTEX_WAKE, 1)         = 1
futex(0x56ca80a4, FUTEX_WAKE, 1)        = 1
clock_gettime(CLOCK_MONOTONIC, {3045, 730611386}) = 0
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
_newselect(0, NULL, NULL, NULL, {0, 100}) = 0 (Timeout)
futex(0x56ca80a4, FUTEX_WAKE, 1)        = 1
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
_newselect(0, NULL, NULL, NULL, {0, 100}) = 0 (Timeout)
futex(0x56ca80a4, FUTEX_WAKE, 1)        = 1
futex(0x56ca80a4, FUTEX_WAKE, 1)        = 1
openat(AT_FDCWD, "/var/run/docker/libcontainerd/94c0a69af7086d208d2d0448bb397f4b2bb69b3e1b5a6f6f2c407db6b37acd42/init-stderr", O_RDONLY|O_LARGEFILE|O_CLOEXEC) = 17
read(17, "write pipe: bad file descriptor\n", 32768) = 32
futex(0x1d12078, FUTEX_WAKE, 1)         = 1
epoll_wait(4, [], 128, 0)               = 0
epoll_wait(4, [{EPOLLIN|EPOLLOUT, {u32=1168448208, u64=1168448208}}], 128, -1) = 1
clock_gettime(CLOCK_MONOTONIC, {3047, 631157795}) = 0
futex(0x1d12078, FUTEX_WAKE, 1)         = 1
futex(0x1d12008, FUTEX_WAKE, 1)         = 1
read(6, "\0\0\2\1\4\0\0\0\3\210\276\0\3Q\0\0\0\0\0\3\0\0\0\3L\n\311\6\n@94"..., 32768) = 902
futex(0x56f9e5a4, FUTEX_WAKE, 1)        = 1
read(6, 0x56fb0000, 32768)              = -1 EAGAIN (Resource temporarily unavailable)
futex(0x1d1271c, FUTEX_WAIT, 0, NULL)   = 0
```

Not quite sure what to make of that, really. Meanwhile, for the sake of argument, I also tried to run `dockerd` listening to TCP port (launched manually) and set `DOCKER_HOST` to that. Got exactly the same results.

**Comment by openmax** [comment]
ok blame me, i have to run : docker run **ppc64le**/hello-world , 
cannot run containers from other arch to power8 .

for armhf try docker run armhf/hello-world.

**Comment by justincormack** [comment]
@openmax so if you run the right containers, on a daemon you started yourself not via systemd is it working ok or not?

**Comment by openmax** [comment]
@justincormack docker server  is running via systemd and work. 
 start the server via "docker daemon" run ok too

**Comment by rcarmo** [comment]
I’m trying to run a container I built myself, on ARM. The container builds, but I cannot run anything that outputs a single byte to the console without getting that error.

Also, since I upgraded to Docker 1.12.1, my old containers on my ARM boxes stopped working.

**Comment by darthva** [comment]
I have the version Docker 1.12.1 running. Am exactly getting the same error as reported on the below link
http://stackoverflow.com/questions/40022817/docker-write-pipe-bad-file-descriptor
The Architecture being used is i686 still not able to figure out a workaround. I understand that ppc64le is resolved, anyone can throw some light on how to make it run on i686 would be really helpful

Thanks

**Comment by rcarmo** [comment]
Just did an apt-get dist-upgrade. Problem went away after a reboot, which is… interesting. I did get a new systemd (same reported version, different package revision). Can’t say that’s to blame or not, just stating a fact here.

**Comment by justincormack** [comment]
@rcarmo same reported version could well have patches.

**Comment by justincormack** [comment]
@darthva we do not provide any builds at all for i686, there is no Dockerfile for it, and I am not sure how it is being patched to work at all (if someone wants to contribute a build it would be possible but no one has done so far), so I am going to close the issue as it is completely unsupported. Can continue to try to help you. What image are you trying to run? There are not many i686 images around.

**Comment by darthva** [comment]
ok agreed,  am trying to run Fuego a testing framework which uses docker has it is main backbone,. Easy way would be to run the docker on 64 bit system?
Thanks again

**Comment by justincormack** [comment]
Yes, 64 bit system should be better.

**Comment by kfowlks** [comment]
Just for completeness and to help others using the PINE64, I have the same problem using ubuntu 16.04 on PINE64 arch armhf. I also have the same version of systemd that @rcarmo mentioned above, but for me doing an apt-get dist-upgrade and a reboot did not solve the issue. 

I did confirm running docker run armhf/hello-world seems to work.

```
ubuntu@pine64:~$ docker run armhf/hello-world

Hello from Docker on armhf!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Comment by prabhukhanna** [comment]
@kfowlks @openmax 
I am getting this same issue on ubuntu16.04. Kindly refer [this link](http://stackoverflow.com/questions/40022817/docker-write-pipe-bad-file-descriptor) for detailed description. My arch details are given below:
**Linux DISYS-4QNSN32 4.4.0-42-generic #62-Ubuntu SMP Fri Oct 7 23:10:22 UTC 2016 i686 i686 i686 GNU/Linux**

ubuntu@UBUNTU-4QNSN32:~$ docker run -it ubuntu bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu

6bbedd9b76a4: Pull complete 
fc19d60a83f1: Pull complete 
de413bb911fd: Pull complete 
2879a7ad3144: Pull complete 
668604fde02e: Pull complete 
Digest: sha256:2d44ae143feeb36f4c898d32ed2ab2dffeb3a573d2d8928646dfc9cb7deb1315
Status: Downloaded newer image for ubuntu:latest
write pipe: bad file descriptor

**Comment by openmax** [comment]
@prabhukhanna it can't run because you have a **i686** architecture , 
because without expliciting it in the command line : docker run -it **"architecture"**/ubuntu bash 
docker go to the default **amd64** architecture

in you case docker have to use this repository -> https://hub.docker.com/r/i686/ubuntu/
try this :  docker run -it i686/ubuntu bash

**Comment by prabhukhanna** [comment]
@openmax That works ! ! ! Likewise, If I run **docker run i686/hello-world** it didn't work. Any thoughts ?

**Comment by justincormack** [comment]
@prabhukhanna there is no i686 hello world image at present see https://hub.docker.com/u/i686/ for the available images. As said earlier, we do not support i686 and there is no way to even build it in the official repo at present. If someone wants to add support it could be made to work, but we have not had significant demand, and as you can see there are very few available images.

**Comment by prabhukhanna** [comment]
@justincormack Thanks. I am planning to change from Ubuntu 16.04 32bit to 64bit. Hope, this solves.

**Comment by pfeerick** [comment]
Just adding to what @kfowlks said... I am also a PINE64 user (64bit ARM/aarch64), and for me either of the two below commands worked - I feel the first is better though as that is the native architecture.

```
docker run aarch64/hello-world
docker run arm64/hello-world
```
