### ISSUE TITLE
docker ps -a by names?

### ISSUE THREAD

**Issue by RyanAntenor** [docker/docker#27413]
Is there a command to filter docker by name or specified fields? instead show all columns all the time?

maybe something 
"docker ps -a  --fields=name,ports "

**Comment by milindchawre** [comment]
Use docker ps  (-f or --filter) option to filter docker ps output.
https://docs.docker.com/engine/reference/commandline/ps/#/filtering

Use docker ps --format option to show specific columns.
https://docs.docker.com/engine/reference/commandline/ps/#/formatting

**Comment by RyanAntenor** [comment]
That should solved my problem. Thanks!
