### ISSUE TITLE
Why docker uses the trick that cloning dnephin/cobra instead of spf13/cobra?

### ISSUE THREAD

**Issue by zoumo** [docker/docker#27415]
When I read the docker source in ./docker/cmd/dockerd/docker.go
```golang
func newDaemonCommand() *cobra.Command {
        ...
	cmd := &cobra.Command{
		Use:           "dockerd [OPTIONS]",
		Short:         "A self-sufficient runtime for containers.",
		SilenceUsage:  true,
		SilenceErrors: true,
		Args:          cli.NoArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			opts.flags = cmd.Flags()
			return runDaemon(opts)
		},
	}
        ...
}
```
I find that `spf13/cobra.Command` does not have the field `Args`, then I find the following code in `./docker/hack/vendor.sh`
```
clone git github.com/spf13/cobra v1.4.1 https://github.com/dnephin/cobra.git
```
`dnephin` is a maintainer of docker. Maybe docker need some features which spf13/cobra doesn't provide. So dnephin implement it.

**My question is if docker needs these features, why docker uses the hack instead of using dnephin/cobra in source code directly?**

Thanks
---
I am crazy about docker and now studing docker by myself. We can discuss docker through email (jim.zoumo@gmail.com)

**Comment by justincormack** [comment]
We should go to using upstream, @dnephin what is the upstreaming situation?

**Comment by dnephin** [comment]
It's not a hack, it's a fork. We could change the dependency to use `dnephin/cobra`, I was waiting to see if upstream would merge my PRs.

So far they've merged some of the bug fixes, but none of the bigger features. The outstanding PRs are:
* https://github.com/spf13/cobra/pull/284
* https://github.com/spf13/cobra/pull/299

These features are necessary for docker/docker, so we can't use upstream until these are merged.

**Comment by zoumo** [comment]
Thank you for your explanation

**Comment by deterok** [comment]
@dnephin what is the status of the PRs now?
