### ISSUE TITLE
Service Communication Between Nodes on Overlay Network Needs More than Documented Ports

### ISSUE THREAD

**Issue by afrazkhan** [docker/docker#27425]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Services on overlay network can not communicate with services on other nodes in the same overlay network unless "All traffic" is open in an AWS security group. Opening only the documented required ports; `2377`, `4789`, and `7946` on UDP and TCP are insufficient. Even opening all TCP and UDP ports does not work, only selecting "All traffic" does.

**Steps to reproduce the issue:**
On AWS, inside a VPC:
1. Create a swarm with `swarm init`, and add other nodes via the supplied `join` command
2. Create an overlay network, e.g. `docker network create --driver overlay --subnet 10.0.9.0/24 --opt encrypted newnet`
3. Add a service (service1) to to one node (node1) in the cluster, then add another service (service2) to a different node (node2) in the cluster
4. Open ports `2377`, `4789`, and `7946` on UDP and TCP in the relevant AWS security group
4. From inside the service2 container, try to access a port in service1 from service2. For example, if service1 is MySQL, try `telnet service1 3306` from service2

**Describe the results you received:**
No access to service1 ports from service2. Only selecting to open "All traffic" in the security group works (not even "All TCP" and "All UDP").

**Describe the results you expected:**
Be able to reach service1 by only opening the ports required by Docker Swarm (above).

**Additional information you deem important (e.g. issue happens only occasionally):**
The strange part is that even selecting "All TCP" and "All UDP" does not work, only "All traffic". So what needs to be open that's not TCP or UDP?

**Output of `docker version`:**
```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: active
 NodeID: f43qckhb6hifw95hki6ihzbdt
 Is Manager: true
 ClusterID: 3ae1kkzosksoqvqgz6kclguhm
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.11.215
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-10-0-11-215
ID: 6LVV:2FUY:E2TD:DKIR:LFAX:3HF6:6ZZI:65CM:F7YY:CQ2X:IVJO:F23E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 type=master
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running in AWS inside a VPC on in it's private subnet.

**Comment by thaJeztah** [comment]
That's strange indeed; I added a "docs" label here so that we can document this once we found what's causing this

**Comment by thaJeztah** [comment]
ping @nathanleclaire @mrjana any ideas?

**Comment by thaJeztah** [comment]
Could it be the order in which you perform these steps? Does it work if you open the ports _before_ setting up swarm, network and services?

**Comment by aboch** [comment]
@afrazkhan In addition to what @thaJeztah suggested, given you are using data plane encryption, also make sure ESP packets are not blocked (ip protocol 50).

**Comment by afrazkhan** [comment]
@aboch wins the cigar. Opening up ECP (protocol 50 as "Custom protocol" in an AWS security group) wins all the things. Thank you!

Might I recommend we add this to the docs, @thaJeztah ;)

**Comment by thaJeztah** [comment]
@afrazkhan yes, definitely. Those docs are now in a separate repository;

- https://github.com/docker/docker.github.io/blob/master/engine/userguide/networking/index.md
- https://github.com/docker/docker.github.io/tree/master/engine/swarm

Would you be interested in opening a pull request there?

**Comment by afrazkhan** [comment]
@thaJeztah yup, for sure. I'll create a PR either today or tomorrow.

**Comment by thaJeztah** [comment]
Thank you!

**Comment by afrazkhan** [comment]
Her you go:

https://github.com/docker/docker.github.io/pull/230

**Comment by justincormack** [comment]
Closing this as the answer was found!
