### ISSUE TITLE
Docker 在Mac平台中容器间通信很慢 Docker container traffic in the Mac platform is very slow

### ISSUE THREAD

**Issue by bravist** [docker/docker#27439]
语言：PHP

框架：Laravel5.1

容器：php-fpm + nginx + mysql 

在Linux平台中 In Linux
![image](https://cloud.githubusercontent.com/assets/1323776/19430629/7b7d0242-9487-11e6-9aac-6eb4c45dfcab.png)

在Mac 平台中 In Mac

![image](https://cloud.githubusercontent.com/assets/1323776/19430677/b86eaf52-9487-11e6-8653-71242e31add6.png)

**Comment by allencloud** [comment]
Hi @bravist 
Could you please make all the issue details in English? Then I think all people can follow you. 🐳

**Comment by justincormack** [comment]
Hi please see https://github.com/docker/for-mac/issues/77 for performance issues on Docker for Mac.

**Comment by thaJeztah** [comment]
@bravist since this issue is specific to docker for mac, I'll close this issue here; can you check if https://github.com/docker/for-mac/issues/77 matches your issue, or open a new issue in the docker for mac issue tracker? https://github.com/docker/for-mac/issues

**Comment by boboyan** [comment]
@bravist 请问下 这个问题现在解决了么

**Comment by paul-wiz** [comment]
@boboyan https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/

**Comment by llitfkitfk** [comment]
https://blog.docker.com/2017/05/user-guided-caching-in-docker-for-mac/
