### ISSUE TITLE
docker overlay network doesn't provide external access when using ufw

### ISSUE THREAD

**Issue by va1en0k** [docker/docker#27430]
**Description**

I created an overlay network between multiple hosts, using `--cluster-store` and `--cluster-advertise` options of the docker daemon. I didn't use swarm or anything like that. It works wonders for the communication between the containers on this network.

However I can't access the internet from inside the containers on this network, and I really want to.

**Steps to reproduce the issue:**
1. In the `hdfs/docker-compose.yml`:
   
   ```
   networks:
     hadoop:
       driver: overlay
   ```
2. Run a container on this network: `docker run  --net hdfs_hadoop --rm -it ubuntu:14.04 /bin/bash`
3. Try `ping 8.8.8.8` and see the pinging never happen.

**Describe the results you received:**

No external network access: the ping doesn't work, nor does anything else.

**Describe the results you expected:**

Network access, working ping.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:43:49 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 80
 Running: 15
 Paused: 0
 Stopped: 65
Images: 146
Server Version: 1.11.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 373
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Kernel Version: 4.4.0-21-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.82 GiB
Name: <commented out>
ID: RKXJ:YWEH:AZNO:SALW:BQBY:QD7Y:LNGY:7OHM:F34T:6QMB:KA44:PHZU
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Cluster store: zk://<commented out>:2181
Cluster advertise: <commented out>:2376
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Maybe you need this:

This is inside the overlay network container, where the external networking won't work:

```
$ docker run  --net hdfs_hadoop --rm -it ubuntu:14.04 /bin/bash
root@f1f267614815:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3508: eth0@if3509: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether 02:42:0a:00:00:07 brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.7/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:7/64 scope link
       valid_lft forever preferred_lft forever
3510: eth1@if3511: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.3/16 scope global eth1
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe12:3/64 scope link
       valid_lft forever preferred_lft forever
```

This is in other, normal containers which can access the internet:

```
$ docker run --rm -it ubuntu:14.04 /bin/bash
root@0f25ccd1b399:/# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
3512: eth0@if3513: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:ac:11:00:0f brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.15/16 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:f/64 scope link
       valid_lft forever preferred_lft forever
```

This is to inspect the `docker_gwbridge`:

$ docker network inspect docker_gwbridge

```
[
    {
        "Name": "docker_gwbridge",
        "Id": "4783ea0ea5dfb25e1ae555cdb2b0fa6d20a9c5a2e06039252354bc383e888e8c",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1/16"
                }
            ]
        },
        "Internal": false,
        "Containers": {
            "e55c9ac385f7575d75940588756fde11695fce4f7b72af5375d35c2ba900041e": {
                "Name": "gateway_e55c9ac385f7",
                "EndpointID": "c72926772e64a2d0c908311d1dfbf19f995204d674608db0d24935fd240544df",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.enable_icc": "false",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.name": "docker_gwbridge"
        },
        "Labels": {}
    }
]
```

Thank you so much!

**Comment by sanimej** [comment]
@va1en0k Did you connect/disconnect the container in the overlay network `hdfs_hadoop` to any other bridge network ? Can you provide the routing table (`route -n`) from inside the container in the overlay network ?

**Comment by va1en0k** [comment]
@sanimej 

> Did you connect/disconnect the container in the overlay network hdfs_hadoop to any other bridge network ? 

No, and I don't really understand how and why should I do that. As far as I understood the documentation, `docker_gwbridge` should be enough and it seems to be there already, or am I wrong?

> Can you provide the routing table (route -n) from inside the container in the overlay network ?

```
$ docker run  --net hdfs_hadoop --rm -it ubuntu:14.04 /bin/bash
root@b69f7900aba9:/# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.18.0.1      0.0.0.0         UG    0      0        0 eth1
10.0.0.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth1
```

Thanks!

**Comment by va1en0k** [comment]
@sanimej I realized that it might be quite pertinent that I'm running `ufw`.

It wasn't a problem for the other containers to connect outside anyway.

Adding a rule to `ufw` like `Anywhere                   ALLOW       172.18.0.0/16` didn't work.

Disabling `ufw` didn't make it work, and even disabling it and rebooting didn't make it work.

So I guess `ufw` is not the problem.

The docker's settings might be a problem, they say:

    DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --iptables=false"

However the internet works from the other containers so maybe there's a way to have it here too without completely giving up on the firewall.

**Comment by va1en0k** [comment]
So right now, the `ufw` is disabled, the system is "clean" because I rebooted the server after disabling `ufw`, but the internet is inacessible from the container in the overlay network.

Just in case, I'll add some more info about the system:

    $ sysctl net.ipv4.conf.all.forwarding
    net.ipv4.conf.all.forwarding = 1

```
$ sudo iptables -t nat -L -nv
Chain PREROUTING (policy ACCEPT 18754 packets, 1087K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain INPUT (policy ACCEPT 18166 packets, 1050K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain OUTPUT (policy ACCEPT 15000 packets, 904K bytes)
 pkts bytes target     prot opt in     out     source               destination

Chain POSTROUTING (policy ACCEPT 15588 packets, 941K bytes)
 pkts bytes target     prot opt in     out     source               destination
```

**Comment by va1en0k** [comment]
Okay, I got it now. I enabled `--iptables` for the docker engine, rebooted, and the connectivity works.

However I want to run `ufw` anyway, and to use it for the docker-managed traffic too. Is there a way to do it? I already have `DEFAULT_FORWARD_POLICY="ACCEPT"` and it's been that way all the time but that seems not enough.

**Comment by va1en0k** [comment]
Those helped (with `ufw` enabled and `--iptables=false`):

        sudo iptables -t mangle -A FORWARD -i docker0 -o eno1 -j ACCEPT
        sudo iptables -t mangle -A FORWARD -i docker_gwbridge -o eno1 -j ACCEPT

I hope I'm not making the system less secure. I'm sorry for bothering you. I hope our comments in this issue will be helpful to others.

**Comment by sanimej** [comment]
@va1en0k sorry about the delay in responding. External connectivity not working in your case is not because you have `ufw` enabled. Its because of the daemon option `--iptables=false`. For external connectivity docker adds `MASQUERADE` rules to the nat table. Its not done when `--iptables=false` is set.

Its recommended to not use mangle table for filtering or NAT purposes. See under `Mangle Table` in http://www.iptables.info/en/structure-of-iptables.html  If you want to set `--iptables=false`  one option is to add the `MASQUERADE` rules yourself for external connectivity.

Also, look at https://github.com/docker/docker/issues/4737

**Comment by thaJeztah** [comment]
I'm gonna close this issue, because running with `--iptables=false` disables docker managing IPTables rules, in which case this is expected.

Feel free to continue the discussion though after I closed
