### ISSUE TITLE
Slow network performances in containers

### ISSUE THREAD

**Issue by gjongenelen** [docker/docker#27456]
When accessing a public url from within a container, the connection is slow and ping (too?) fast.

**Docker container:**
_curl https://google.com  6.03s user 0.10s system
ping google.com: avg 0.368 ms_

**Local (Mac):**
_curl https://google.com  0.03s user 0.01s system
ping google.com: avg 8.867ms_

Im running docker4mac version _1.12.2-beta28_.

(Tried with and without IPv6 & different distros)

**Comment by justincormack** [comment]
Hi, can you open this issue at https://github.com/docker/for-mac/issues as there are known issues there already and it is specific to Docker for Mac

I am going to close here as it is not a general issue with Docker.
