### ISSUE TITLE
Disk space available within a docker image is less than the space available in the VM

### ISSUE THREAD

**Issue by vasantivmahajan** [docker/docker#27454]
I am running a docker image on a windows system. The Virtual Machine on which it is running has 244 GB of memory allocated

![image](https://cloud.githubusercontent.com/assets/17990840/19445800/d08d1f34-9463-11e6-942a-70399afe6f85.png)
 
However, on checking the disk space in the docker container it shows only 19GB available

![image](https://cloud.githubusercontent.com/assets/17990840/19445876/23f4ef62-9464-11e6-9c0e-2e8f947704b8.png)

Why is the 244GB memory not available within the container?

Any help is appreciated!

**Comment by justincormack** [comment]
This looks like it might be a boot2docker specific issue, you may get better support at https://github.com/boot2docker/boot2docker

**Comment by thaJeztah** [comment]
By guess is, because it's a sparse filesystem, so it automatically grows until 244 GB, but currently is 19 GB.

However, this issue is specific to boot2docker / toolbox, and not something we can address in this repository, so I'll close this issue here, but feel free to comment after I closed
