### ISSUE TITLE
Add get tags command to CLI

### ISSUE THREAD

**Issue by steelbrain** [docker/docker#27462]
I tried to search for an existing issue with no luck, sorry if this is a duplicate

**Description**

Currently if we have to get list of available tags of an image, we have to use the raw API. and if we have to get the list of available tags in a private image, we first have to fake a web login, generate a jwt token and then use it to do the API calls to get available tags.

We have to do this again and again everywhere we want to get tags.

**Describe the results you received:**
Described above

**Describe the results you expected:**
It would be wonderful to have a `docker get-tags $image` and get list of available tags for that image. Doing it in docker cli would mean the user auth will be used by default, which is greaat

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64
```

**Comment by thaJeztah** [comment]
I think I found your duplicate; https://github.com/docker/docker/issues/14254 (also related; https://github.com/docker/docker/issues/17238) (no worries, we know GitHub search can be a PITA)

I'll close this issue, as it's a dup, but thanks for opening!
