### ISSUE TITLE
[1.12.2] Service create with two ports published fails

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#27469]
When creating a service that publishes two ports, but doesn't specify the host-port, service create fails;

```bash
$ docker service create --publish 80 --publish 443 --name web nginx:alpine
Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided
```

Note that this works;

```bash
docker service create --publish 80:80 --publish 443:443 --name web nginx:alpine
```

And so does;

```bash
docker service create --publish 80 --name web nginx:alpine
```

or

```bash
docker service create --publish 80 --name web nginx:alpine
```

or 

```bash
docker service create --publish 80:80 --publish 443 --name web nginx:alpine
```

Based on the above (especially the last one), it looks like published multiple ports tries to assign the same "random" port multiple times.

Tested on;

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

and on Linux (to exclude it being a Docker for Mac issue)

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:39:06 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:39:06 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

This looks to be a regression in 1.12.2.

**Comment by aaronlehmann** [comment]
> Based on the above (especially the last one), it looks like published multiple ports tries to assign the same "random" port multiple times.

I think what's happening here is that the published port is 0 at the API level when the request is sent to SwarmKit. The validation code considers two published ports of "0" to be duplicates, but this is wrong.

**Comment by aaronlehmann** [comment]
Opened https://github.com/docker/swarmkit/pull/1657

**Comment by yongtang** [comment]
I think #27208 is the same issue as this issue.

**Comment by yongtang** [comment]
See following for #27208: 
https://github.com/docker/docker/blob/v1.12.2/api/client/stack/deploy.go#L152-L158

**Comment by thaJeztah** [comment]
@yongtang possibly the same, although when using .dab, I also got the error even when specifying the host port. I discussed this with @vieux and we thought it was best to open a separate issue, just in case

**Comment by yank1** [comment]
+1
