### ISSUE TITLE
Docker service support multiples ports exposed/published for a service

### ISSUE THREAD

**Issue by mostolog** [docker/docker#27482]
Does docker services support multiples ports exposed/published for a service?

Wouldn't --expose make sense to enable internal-cluster services ? (ie: services I don't want to be available at host level, but needed for other services)

Seems docker service create --publish 8080 --publish 8888 doesn't work...
Regards

**Comment by sanimej** [comment]
Multiple published ports for a service is supported. But 1.12.2 has a bug, being tracked by #27469
