### ISSUE TITLE
Wrong date / timezone in container

### ISSUE THREAD

**Issue by mauritsl** [docker/docker#27488]
The date in the container is far off from the date of the host system, when using Docker for Mac. CEST is 2 hours behind UTC, but the reported difference is 16 hours. Se e the console output for a short summary:

```
$ date;docker run -it --rm ubuntu:16.04 date
Tue Oct 18 12:22:08 CEST 2016
Mon Oct 17 20:19:55 UTC 2016

$ date;docker run -it --rm -v /etc/localtime:/etc/localtime busybox date
Tue Oct 18 12:21:24 CEST 2016
Mon Oct 17 20:19:11 UTC 2016

$ date;docker run -it --rm -e TZ=Europe/Amsterdam ubuntu:16.04 date
Tue Oct 18 12:29:58 CEST 2016
Mon Oct 17 22:27:45 CEST 2016
```

Having a correct date is important for many security systems (i.e. SSL certificates that are 'not yet valid') and build tools that rely on file modification dates. This is a major issue in my option since many users are using Docker for this kind of things nowadays.

Many others are experiencing the same problems, as you can see from the links below. I have tried the suggestions I came across, but neither works. It's also not bound to the used image. I get the same output with ubuntu:16.04, debian and busybox.

References to other issues and forum posts:

Suggest sharing /etc/localtime:
https://github.com/docker/docker/issues/3359

Suggests TZ environment variable:
https://forums.docker.com/t/cannot-change-timezone-in-centos-7/12320/2

Also reporting large time differences in Docker for Mac, no solutions:
https://forums.docker.com/t/syncing-clock-with-host/10432/3
https://forums.docker.com/t/cant-change-timezone-in-alpine/22044

Suggest fixing it in Dockerfile:
https://github.com/docker/docker/issues/12084

**Comment by justincormack** [comment]
This seems to be two issues. If the system time (UTC) on Docker for Mac is not synced, please report in https://github.com/docker/for-mac/issues - there are some time related issues already. Please include the output of `ntpq -p` on the Mac, which will indicate whether your Mac is currently synced to a time service, and whether it is correctly synced if you restart Docker, or whether this happens after the Mac is sleeping.

The other issue is setting timezones in a container. I think you should just be able to set the `TZ` environment variable in your Dockerfile to do this.

**Comment by mauritsl** [comment]
I've tried setting TZ but doesn't help. It is definitely not a timezone issue, as you can see from the console output.
It's correctly synced after restarting Docker. Thanks for that suggestion!
Docker for Mac already has an issue on this. Closing this one.

**Comment by mauritsl** [comment]
For the records the requested ntpq output, in case it still matters:

```
$ ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 nlams2-ntp-001. .GPSs.           1 u  57m  256  100   13.581  -27830.  16.63
```

**Comment by justincormack** [comment]
@mauritsl can you post that in the other issue. Your Mac does not have time sync to the timeserver, you should have a `*` in the first column eg:

```
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
*nlams2-ntp-001. .GPSs.           1 u  219  128  376   13.534    4.305   0.941
```

This is why the VM did not sync to your Mac. We are trying to work out how common this is, so we can work out how to resolve this.
