### ISSUE TITLE
Localhost editor doesn't reflect changes in dev container per contributing docs

### ISSUE THREAD

**Issue by troy0820** [docker/docker#27495]
**Description**

When trying to contribute to docker using the suggested contributing docs, [contributing docs](https://docs.docker.com/opensource/project/set-up-dev-env/), using my default editor in localhost doesn't change the code in the image.  

**Steps to reproduce the issue:**
1.  Cloned repo and followed contributing docs
2. Did code change 
3. Checked to see if code was changed in container shell from `make shell` and code doesn't reflect change locally

**Results:** The results I received show the 1.13.0-dev code that was made during the initial make

**Expected:** The code changes from the contributing docs to make sure that it is changing the image. 

docker version of container is `Docker version 1.13.0-dev, build 15ea28f-unsupported`
docker version of localhost is `Docker version 1.12.2, build bb80604, experimental`
 
Running this on OSX 10.12 MacOS Sierra

Docker version inside dev container

``` 
DEBU[1980] Calling GET /v1.25/version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   15ea28f-unsupported
 Built:        Mon Oct 17 22:02:09 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   15ea28f
 Built:        Mon Oct 17 21:35:01 2016
 OS/Arch:      linux/amd64
```
**docker version inside localhost**
```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`: localhost**

```
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 48
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 32
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: FVI4:CG4B:QZE4:TT6Y:HT7F:OMCP:NPPY:ZY5F:R53G:Z2FF:NTRR:EJI4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 41
 System Time: 2016-10-17T22:13:45.171645885Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: troy0820
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by tophj-ibm** [comment]
`make shell` builds a docker-dev image every time that should copy over your local code into a new container. So if you re-run `make shell`, does that container have your updated code?

**Comment by troy0820** [comment]
@tophj-ibm Yeah, that actually works.  I'm just reading the docs, I can make a PR to that because it says 
```
Go to your running development container.
Remake the binary and copy it to usr/bin
Restart the Docker daemon with the new binary.
```
Which gave me the indication to run `hack/make.sh binary` before running the `make shell` to push up the changes to the docker image.

It's safe to close this issue.

**Comment by tophj-ibm** [comment]
I see where you got messed up now. Under that section the docs say `Running the make shell command mounted your local Docker repository source into your Docker container.` and this isn't the case, it's only mounting the bundles directory (which might be a bug). If it did mount your entire repository source, you wouldn't need to re-run `make shell` and then the docs are correct.

**Comment by troy0820** [comment]
Should we keep this open and reference this if it is a bug?  I put a PR in the docs for `working with a development container` to get around this issue.

**Comment by tophj-ibm** [comment]
I think we should keep this open until we can figure out if it's an actual bug in the docker code or just something that needs updating in the docs

**Comment by tophj-ibm** [comment]
@troy0820  looks like the intended behavior is `make BIND_DIR=. binary shell`, which will correctly bind mount you directory so you shouldn't have to call `make shell` again. A PR was merged into the old docs repo, and wasn't moved to the new one. I'll comment on your issue over there and someone should fix it. You should be able to close this now

**Comment by troy0820** [comment]
Awesome @tophj-ibm. Thanks.

**Comment by troy0820** [comment]
I can confirm that this works.  I understand that the repo linking the docs is not presently the docs that are on the website.  Are they using `docker/docker.github.io` for the docs or are they using `docker/opensource` for the docs?  Right now there is an issue in the `opensource` repo to move the docs to the other repository.  

The command in the README in my opinion should be updated to reflect what you are doing in the docker container after a code change because the above command `make BIND_DIR=. binary shell` _while valid_  is the command you are doing from the localhost terminal to make the binaries and open the docker container shell.  

After a code change, you can still `make` the binaries with `hack/make.sh binary` and then copy the contents to the `/usr/bin` with `cp bundles/1.13.0-dev/binary-daemon/docker* /usr/bin` && `cp bundles/1.13.0-dev/binary-client/docker* /usr/bin` in the docker container shell which the docs tell you to do but the make command isn't clearly distinguished from the commands listed above which has you do that to initially make the docker development container.  

So in between these steps :
```
 * Remake the binary and copy it to usr/bin
* Restart the Docker daemon with the new binary.
```
The make command should explicitly state the make command that the docker container uses `hack/make.sh binary` and the following instructions to copy the binaries to the `/usr/bin` in the docker container

Also, you shouldn't have to restart the docker daemon after the binaries are copied to the `/usr/bin/` of the docker dev container because the commands you executed are in the docker dev container.

**Comment by tophj-ibm** [comment]
docker/docker.github.io is the new repository for the docs. docker/opensource was one of the old ones used. 

You can also use `make BIND_DIR=. shell` which won't automatically make the binary for you (that's what the extra binary does), but will volume mount your docker source repo from your host machine to the dev container.

Feel free to add in the explanations in the docs PR

**Comment by troy0820** [comment]
Docs have been updated in PR https://github.com/docker/docker.github.io/pull/253.  Closing this issue.
