### ISSUE TITLE
 Linux Newly installed disk docker can not be found

### ISSUE THREAD

**Issue by MarkThink** [docker/docker#27498]
Linux Newly installed disk docker can not be found

[root@dev www]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

```
/dev/xvda1       40G   16G   22G   42% / - Linux System
/dev/xvdb1       20G  5.7G   13G   31% /www - The new disk
```

**Comment by mostolog** [comment]
Sorry, but I don't understand what you are talking about.

Do you mean a new local hardware disk is not being detected by docker-engine?

Please, could you elaborate a bit more?

**Comment by thaJeztah** [comment]
closing because we need more info to help you further
