### ISSUE TITLE
Docker not publishing ports correctly

### ISSUE THREAD

**Issue by xcellardoor** [docker/docker#27491]
Since the upgrade to 1.12 if I publish ports on Arch, Fedora or CentOS, I am unable to bind to them. This may be because Docker has stopped setting up masquerading correctly? I'm getting 'Connection reset by peer' (see below).

The iptables element of Docker is enabled and no special networks are being used, just the default one. However whenever I try to connect to the ports - nothing.

I've searched and so trust I'm not creating a duplicate issue. Happy to provide any and all info needed and run any diagnostics. 

[cellardoor@splendor ~]$ wget localhost:10080
--2016-10-18 13:22:17--  http://localhost:10080/
Resolving localhost (localhost)... 127.0.0.1, ::1
Connecting to localhost (localhost)|127.0.0.1|:10080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

--2016-10-18 13:22:18--  (try: 2)  http://localhost:10080/
Connecting to localhost (localhost)|127.0.0.1|:10080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

^C
[cellardoor@splendor ~]$

**Comment by justincormack** [comment]
Please can you give a full example, and full details of your Docker version and info as requested.

**Comment by xcellardoor** [comment]
Sure thing, if I were to execute an instance of Ghost:
`docker run --name some-ghost -p 8080:2368 -d ghost`

Then I am unable to reach the container on port 8080. This is true for web browser or a wget. Also true if I spin up a new docker bridge network such as 'docker-network' and then use `--net docker-network` as a startup argument.

The same is true for essentially any service I try to run (the ones I run on my other servers include nextcloud and gogs, on varying ports). Sometimes (though not always!) if I go directly to the containers IP e.g. 172.18.0.3:8080 I will be served the page. However trying 127.0.0.1:8080 will fail with the Connection reset error.

I've tried running with iptables and firewalld fully disabled to remove the idea of the firewall being responsible, but the same issue happens on my personal laptop which isn't running a firewall daemon. Docker versions are:

Laptop: Docker version 1.12.1, build 23cf638
CentOS Server: Docker version 1.12.2, build bb80604
Fedora Server: Docker version 1.10.3, build 8b7fa4a/1.10.3

**Comment by xcellardoor** [comment]
Further investigation has found that this is being caused by an ongoing issue with FirewallD/Docker - they do not play nicely! There are several other threads concerning this issue so this one can be closed.

To those who come across this - make sure that iptables is not disabled in Docker Daemon (it is on by default so you'd have had to manually disable it). The IPTables rule configures the containers so that they can reach the outside world, DNS, and also be connected back into. A temporary workaround from a security perspective is to bind containers to specific sockets and allow Docker to do its automated IPtables magic. For example:
`docker run --name nginx -p 172.22.14.12:10080:80 nginx'`
