### ISSUE TITLE
Proposal: configurable image pull policies for services

### ISSUE THREAD

**Issue by alexmavr** [docker/docker#27508]
Today, newly-scheduled tasks always try to pull the image indicated in the ContainerSpec, even if that exact image tag is available on the node where the task is scheduled (as indicated in the comment at https://github.com/docker/docker/issues/25211#issuecomment-236158843)

In order to make this behavior more configurable, I would like to propose a "Service Pull Policy" feature, featuring three policies:
- "always": The image is always pulled from a remote registry, even if an image with the same name and tag exists on the node where the task is scheduled. This would be the default behavior, as
- "missing": Only pull the image from the remote registry if the image is not already present on the node
- "never": Never attempt to contact a remote registry to pull an image. If the image does not exist, the task exits with an error code

This policy would effectively be a new field in the ServiceSpec (or the TaskTemplate, if more appropriate) which could be manipulated through the `service create` and `service update` operations. 

A hand-wavy CLI example:
````
docker service create --pull=missing <image:tag>
docker service update <service_name> --pull=always
```

## Cute animal photo

![](http://static.boredpanda.com/blog/wp-content/uploads/2015/09/cute-hamsters-23__880.jpg)

**Comment by aaronlehmann** [comment]
There is work underway to resolve the image digest automatically when creating the service, so that creating a service using the `busybox:latest` image actually inserts `busybox@sha256:29f5d56d12684887bdfa50dcd29fc31eea4aaf4ad3bec43daf19026a7ce69912` into the service definition. I think this would at least partially alleviate the need for this setting because there will never be a need to re-pull once we are using digests.

cc @nishanttotla

**Comment by stevvooe** [comment]
The pull policy is controlled by using image digests.

| Policy | Description |
+-------+-----------+
| `always` | image with no digest |
| `missing` | Does this no matter what, not very useful in a cluster if image is already pulled |
| `never` | Doesn't make sense. How would get the image their in the first place? |

The main issue with such an approach is that you're likely to have different images running on each host over time. Such policies don't really support convergence.

With digests or centralized digest resolution, you can achieve exactly the intent of these policies while ensuring convergence.

Closing.

**Comment by alexmavr** [comment]
I'll agree that digests are a better approach if they are applied by default, but just to convey the use case around "never":

In clusters with no access to a registry, an operator would want to manually pre-load images to each individual node. In that case, if the image is not present on a node, then it would be helpful if the task failed immediately rather than try to connect to an unavailable registry, as that could trigger firewall notifications and raise potential security concerns.

For organizations that use a private registry behind their own firewall, this use case would apply to the bootstrapping process of that registry.

**Comment by stevvooe** [comment]
@alexmavr How does one get images to the node in the first place? Even with a private registry, one must pull.

**Comment by alexmavr** [comment]
@stevvooe `docker load` from a vendor-distributed tarball

**Comment by stevvooe** [comment]
@alexmavr Ok, please submit a PR to swarmkit a field `Disable` on `PullOptions`.
