### ISSUE TITLE
Document how to revert a container to its zfs snapshot

### ISSUE THREAD

**Issue by kim0** [docker/docker#27504]
I'm running docker with the zfs backend. I'm taking snapshots every 10mins. Sorry if its obvious, but I could not figure out how do I revert a container to a recent snapshot. In fact, I cannot find a way to figure out the relation between a running container, and its zfs filesystem/snapshot/clone. 

An addition to docs explaining this, is most appreciated.

**Comment by cpuguy83** [comment]
Docker is using zfs to provide the layered fs that docker needs.
It does not specifically support features like snapshots and clones for these purposes and I do not believe we should document such use case sense *if* it works it would be so non-intentionally.

**Comment by kim0** [comment]
@cpuguy83 .. Is my understanding correct that every docker container, is living off of a zfs volume? How can I correlate which container is on which volume? It's Ok to not document snapshotting ..etc. 

Currently, I have a bunch of containers and a bunch of ZFS volumes with zero knowledge how to map the two. IMO, we should document this. Thanks

**Comment by 00angus** [comment]
I'm starting to use zfs heavily but this is something keeping me from going into production!
@cpuguy83 _I absolutely need a way to map a container to its zfs volume_. Then I'll be able to manage everything else I need, indeed. 
I need that info to build my own workflows.
- is it possible? Does someone can provide a links/hints/suggestions/scripts?
- if not possible, it would be needed IMHO

Thanks for the hard work on docker.

**Comment by kim0** [comment]
Glad someone else needs it .. i.e. I'm not crazy :) 
Tagging @Mic92 @baloose .. Hoping someone can help

**Comment by cpuguy83** [comment]
If you want to revert a container then you create a new one.
The image is the snapshot the container is created from.

Closing since this is not a real issue, but please feel free to continue to discuss.

**Comment by Mic92** [comment]
Volumes are not dedicated zfs volumes, which mean, you could only restore them as a whole:

```
docker inspect <container_id> | jq ".[0].Mounts"
```

`docker info` gives you the parent dataset. However `docker inspect` on the container currently does not return any useful information about the underlying zfs dataset. There is a method called `GetMetadata` at https://github.com/docker/docker/blob/master/daemon/graphdriver/zfs/zfs.go#L222, which could return the backing dataset. This interface did not exists, when I added zfs support to docker. It could return dataset name and the mountpoint.

**Comment by Mic92** [comment]
The following should return the information you want on `docker inspect`:

```patch
From ef299605a74f6bb13ce585a6e7a814e616b7461f Mon Sep 17 00:00:00 2001
From: =?UTF-8?q?J=C3=B6rg=20Thalheim?= <joerg@higgsboson.tk>
Date: Mon, 31 Oct 2016 13:06:59 +0100
Subject: [PATCH] zfs: expose mountpoint/dataset on inspection
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: 8bit

Signed-off-by: Jörg Thalheim <joerg@higgsboson.tk>
---
 daemon/graphdriver/zfs/zfs.go | 5 ++++-
 1 file changed, 4 insertions(+), 1 deletion(-)

diff --git a/daemon/graphdriver/zfs/zfs.go b/daemon/graphdriver/zfs/zfs.go
index ac10680..152da76 100644
--- a/daemon/graphdriver/zfs/zfs.go
+++ b/daemon/graphdriver/zfs/zfs.go
@@ -207,7 +207,10 @@ func (d *Driver) Status() [][2]string {

 // GetMetadata returns image/container metadata related to graph driver
 func (d *Driver) GetMetadata(id string) (map[string]string, error) {
-       return nil, nil
+       return [][2]string{
+               {"Mountpoint", d.mountPath(id)},
+               {"Dataset", d.zfsPath(id)},
+       }, nil
 }

 func (d *Driver) cloneFilesystem(name, parentName string) error {
--
2.10.1
```

**Comment by kim0** [comment]
@Mic92 .. Thanks for the patch! Would you be interested to upstream it please ?

**Comment by kim0** [comment]
@Mic92 .. so what I understand from your comment, is that for every new docker container, a clone of the (large) dataset underlying /var/lib/docker is created and the container lives there. Is this correct ? May I ask, why was this the decision, i.e. why don't we create thinner clones of the docker image, that hold only the needed container. So, if I had 10 containers, zfs list would show 10 datasets, one for each

**Comment by Mic92** [comment]
No, when I said parent dataset I meant the path, where docker datasets are created.
For example, if the dataset chosen for docker is `zroot/docker` mounted on `/var/lib/docker`,
then container will be created below: `zroot/docker/<id>`. The concrete implementation is described here: https://docs.docker.com/engine/userguide/storagedriver/zfs-driver/

**Comment by kim0** [comment]
@Mic92 .. Thanks a lot for clarifying things .. Now my main problem is that I cannot find a container's <id> as you said, in the location where it should be .. Here's a concrete example:
```
 # docker info
Storage Driver: zfs
 Zpool: zdocker
 Zpool Health: ONLINE
 Parent Dataset: zdocker/docker
 Space Used By Parent: 24755822592
 Space Available: 72623927296

 # zfs list -r zdocker/docker -d 1
NAME                                                                                   USED  AVAIL  REFER  MOUNTPOINT
zdocker/docker                                                                        9.16G  81.2G   163M  /var/lib/docker
zdocker/docker/009976880c086688528722aaa86fc464aef957d9b92497f67e7891469473c04d        232K  81.2G  90.0M  legacy
zdocker/docker/00ebb8dea67945217f7a16c93d96ced0a10bfcf3dfe4cc7d9171c3e4ccc0becd       66.1M  81.2G   420M  legacy
zdocker/docker/011dd245417bcb1e8c78c965fa4dfee5a865b0808dcbc29d236572658c3b9973        115M  81.2G   230M  legacy
zdocker/docker/0258f202035fd4b08f27ed66ecd8f3a9f1f935341067e0ead7f396ecdb94f208        112K  81.2G   754M  legacy
zdocker/docker/050496ca2cc765f3cc34b01300da22703b77e88fa2eedf3a93ca1e80d5d54ce9        112K  81.2G   387M  legacy
zdocker/docker/07cf270d3044e0171f49382afeb653526cbf3e4805e9b5a4ff4c3de3f79e1918        259M  81.2G   347M  legacy
 ...... snip ......


 # docker ps -a | grep wordpress
78a9b21a4009        wordpress                                 "docker-entrypoint.sh"   3 weeks ago         Up 7 days           0.0.0.0:4339->80/tcp                                                         c9wp


 # zfs list -r zdocker/docker -d 1 | grep 78a9b21a4009
 <nothing is found, why!> 
```

**Comment by Mic92** [comment]
The datasets get different ids, that's why I added the patch above. I currently cannot build docker because of limited network, you can make the pull request above though.

**Comment by 00angus** [comment]
@cpuguy83 : maybe I've expressed myself in a wrong way :)
AFAIK - but correct me please if I'm wrong - it is not possible to do the following:
 - given a running container, find the zfs filesystem/datased it's running on
    (the one I can match in a "zfs list")

This was the issue discussed on this thread.
Could it be implemented? Because I understand it's not yet available.

**Comment by kim0** [comment]
@Mic92 .. Alright! The patch didn't apply cleanly directly, it seems the lines got shifted a bit .. Anyway, I applied it manually and submitted a PR (under my name, sorry if this is not what you meant! it's the best I could do) .. Unfortunately, Jenkins is failing the builds. You can see the PR and build failures at https://github.com/docker/docker/pull/27903

@Mic92 .. you mentioned you have limited internet bandwidth .. if it would help, I can easily spin up a small linux VM on azure cloud and allow you exclusive access to work from, if this is will be helpful. Let me know. Thanks!
