### ISSUE TITLE
[1.13] Add Fedora 25 RPM's

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#27500]
This is a tracking issue to make sure we prepare RPM's for Fedora 25 as it will be released during 1.13 code freeze; https://fedoraproject.org/wiki/Releases/25/Schedule (2016-11-15)

During code freeze, we can use the "rawhide" tag (https://hub.docker.com/_/fedora/) which is "fedora 25 in the making"

@andrewhsu is going to look into this

/cc @runcom @vieux @andrewhsu

**Comment by runcom** [comment]
> During code freeze, we can use the "rawhide" tag (https://hub.docker.com/_/fedora/) which is "fedora 25 in the making"

Rawhide isn't F25 in the making anymore :( it's following its own cycle now since F25 already has a branch

**Comment by thaJeztah** [comment]
@runcom is there another image that can be used? Also, is "rawhide" no longer updated then, and should be considered "deprecated"?

**Comment by runcom** [comment]
> @runcom is there another image that can be used? Also, is "rawhide" no longer updated then, and should be considered "deprecated"?

rawhide == development release (it's like a rolling release), every 6 months or so we branch out from rawhide and tag a new upcoming release (say F25). So, no it's not deprecated, and I'm not sure which one you could use, since there's no F25 yet as you pointed out.

**Comment by andrewhsu** [comment]
Hmm...I see a docker image file for Fedora 25 that is labelled as "beta": https://getfedora.org/en/cloud/prerelease/docker.html

I was able to download it and `docker load` it according to instructions.

Looks like a minimal docker image similar to `fedora:24`:
```
bash$ docker run --rm --entrypoint=/bin/rpm fedora-docker-base-25_beta-1.1.x86_64:latest -qa | wc -l
     161
bash$ docker run --rm --entrypoint=/bin/rpm fedora:24 -qa | wc -l
     164
```

**Comment by thaJeztah** [comment]
@andrewhsu yeah, perhaps we should open an issue on GitHub, or contact the maintainers of the official image; https://github.com/fedora-cloud/docker-brew-fedora/issues (although it looks like they're not really following up on GitHub issues

ping @maxamillion would you be able to help out?

**Comment by andrewhsu** [comment]
I've created an issue here https://github.com/fedora-cloud/docker-brew-fedora/issues/40

**Comment by thaJeztah** [comment]
Also should be added to the installation docs in the "vnext-engine" branch once it's fixed; https://github.com/docker/docker.github.io/blob/vnext-engine/engine/installation/linux/fedora.md

**Comment by andrewhsu** [comment]
fyi, corresponding bugzilla ticket https://bugzilla.redhat.com/show_bug.cgi?id=1386866

**Comment by maxamillion** [comment]
@thaJeztah 

I'm not sure what's going on here, the issue talks about Fedora 25 RPMs and docker 1.13 but then the comments thread is talking about the fedora docker image on the Hub. What's actually requested here?

**Comment by thaJeztah** [comment]
@maxamillion thanks for looking! The Docker RPM's are built in a container, and for those containers, we use the official images from Docker Hub, e.g. the [Fedora 24 Dockerfile for RPM's](https://github.com/docker/docker/blob/master/contrib/builder/rpm/amd64/fedora-24/Dockerfile), and the script [hack/make/build-rpm#L70-L143](https://github.com/docker/docker/blob/master/hack/make/build-rpm#L70-L143). Since Fedora 25 will be released during our code freeze, and there's no Fedora 25 "beta" image on Docker Hub, we're looking to see what options we have to start preparing for Fedora 25.

Ideally, we'd like to have a Fedora 25-beta image on Docker Hub to use for the builds, and once Fedora 25 is out, we can switch to that image.

**Comment by maxamillion** [comment]
@thaJeztah Fedora doesn't currently push pre-release content to the Docker Hub, all pre-release images are available for testers via Fedora.

**Comment by thaJeztah** [comment]
@maxamillion that's the one @andrewhsu mentioned above? https://github.com/docker/docker/issues/27500#issuecomment-254658370

Looks like we need to use that then, until it's pushed to Docker Hub

**Comment by maxamillion** [comment]
@thaJeztah Yes, that's one of the images. We build nightlies also if you're interested in something more immediately up to date, but that would work fine if you just want to throw a `RUN dnf -y update` in the `Dockerfile`.

**Comment by andrewhsu** [comment]
I've loaded the image from fedora website and pushed it to dockerhub so we can work with something: https://hub.docker.com/r/andrewh5u/fedora-docker-base-25_beta/

**Comment by andrewhsu** [comment]
Hmm..saw that Fedora 25 was pushed out again to Nov 22 release date: https://fedoraproject.org/wiki/Releases/25/Schedule

**Comment by andrewhsu** [comment]
Fedora 25 was released earlier this morning! Still waiting on the [dockerhub docker image of Fedora 25](https://hub.docker.com/r/_/fedora/). The [announcement](https://fedoramagazine.org/fedora-25-released/) had this to say about it:

> Fedora will also offer a docker-formatted base image, to be updated monthly along with critical security updates, for use in building Linux containers.

**Comment by maxamillion** [comment]
Apologies for the lag time. https://github.com/docker-library/official-images/pull/2383

**Comment by thaJeztah** [comment]
ping @tianon :heart:

thanks @maxamillion!

**Comment by tianon** [comment]
Merged and pushed!

**Comment by thaJeztah** [comment]
@tianon awesome! it's there; https://hub.docker.com/r/library/fedora/tags/

**Comment by vieux** [comment]
fixed by https://github.com/docker/docker/pull/28733 

may we close @thaJeztah ?

**Comment by andrewhsu** [comment]
With the release of [docker 1.13.0 GA](https://github.com/docker/docker/releases/tag/v1.13.0), Fedora 25 packages are now available for install.

I think this issue is good to close.
