### ISSUE TITLE
Plugin systems overloaded use of the term "manifest" is pathological

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#27517]
Use of the term "manifest" in the plugin system confusing the context of distribution. A manifest is an abstract of list of resources, defined in https://github.com/docker/distribution/blob/master/docs/spec/manifest-v2-2.md. Overloading the terminology for plugins will cause confusion between the encompassing manifest with abstract resources and the plugin manifest, with the actual plugin config.

In particular, we need to make corrections in the following files:
- [ ] https://github.com/docker/docker/blob/master/docs/extend/manifest.md
- [ ] https://github.com/docker/docker/blob/master/docs/extend/index.md
- [ ] https://github.com/docker/docker/blob/master/api/types/plugin.go#L33
- [ ] https://github.com/docker/docker/blob/master/api/types/plugin.go#L143
- [ ] Don't introduce new way of versioning things (`manifestVersion` needs to go)

This must be done before the general release of plugin support.

**Comment by vieux** [comment]
@stevvooe do you have a term in mind ?

**Comment by stevvooe** [comment]
@vieux I was think `Config`, but I think that may be reserved for user configuration of a plugin. I would suggest `PluginSpec` or `PlugDescription` but I am not sure how this would be used.

**Comment by thaJeztah** [comment]
ping @vieux are you working on this?

**Comment by oulinbao** [comment]
Can I try to fix this one?
