### ISSUE TITLE
API to pull images with content trust enabled

### ISSUE THREAD

**Issue by sburnwal** [docker/docker#27511]
I want to programmatically pull signed images and make sure that signature of the signed images are verified. Basically, I want to do the same things as in docker pull with 'DOCKER_CONTENT_TRUST=true' but programmatically. I have 2 questions:

(1) Is there any docker remote API that allows me to pull images with content trust enabled ?
(2) I know when content trust is enabled and someone wants to push or pull images, it uses a key that is generated during the process. Is there a way to use my own certificate or key for this purpose instead of what is being generated.

**Comment by thaJeztah** [comment]
pong @cyli @endophage PTAL

**Comment by cyli** [comment]
@sburnwal 
> Is there any docker remote API that allows me to pull images with content trust enabled ?

I don't think there's a remote API for doing so, but docker uses [notary](https://github.com/docker/notary) to resolve the image name.  You do the same using notary either as a CLI tool or as a library: you could look up the image tag's digest, then use the docker remote API to pull the digest and re-tag.  (Please see https://github.com/docker/notary/blob/master/docs/getting_started.md#inspect-a-docker-hub-repository for more information)

> I know when content trust is enabled and someone wants to push or pull images, it uses a key that is generated during the process. Is there a way to use my own certificate or key for this purpose instead of what is being generated.

There are potentially two keys that are generated by the process - the root key and the repository/targets key.  The root key is generated only once - if you already have one, it's not re-generated again for any other repositories that you create.  For this one, you can use [notary to import your own existing key](https://github.com/docker/notary/blob/master/docs/command_reference.md#importing-and-exporting-keys).  The targets key is generated per image repository, and currently there is no way to circumvent this.

However, if you mainly want to use your own key to sign and push images, and don't care that an extra targets key is generated, you can use notary to [create a delegation](https://github.com/docker/notary/blob/master/docs/advanced_usage.md#work-with-delegation-roles) and specify your own key as a delegation key.  That way, it's the only key that you would need when signing and pushing.  Then the targets key would be needed if you needed to change this delegation key.

**Comment by sburnwal** [comment]
> I don't think there's a remote API for doing so, but docker uses notary to resolve the image name. You do the same using notary either as a CLI tool or as a library: you could look up the image tag's digest, then use the docker remote API to pull the digest and re-tag.

@cyli Does this mean that when I use my own registry server, docker would still use notary to resolve the image tag's digest ?

Another question I have - there is env var DOCKER_CONTENT_TRUST listed here https://docs.docker.com/engine/reference/commandline/cli/. When it is set and I use remote API to pull, will it not ensure trust or signature being enforced ?

My problem is this - I have my own registry and my customers would pull images from my registry. But I want this pull to be secure using some API. Do I need to have separate notary server as well or registry server is also acting as notary ? Do I need to distribute the root key to each of client on my customers ?

**Comment by sburnwal** [comment]
@cyli - thank you so much for answering my doubts, appreciate this!

**Comment by cyli** [comment]
@sburnwal Thank you for trying out content trust!
