### ISSUE TITLE
[1.13] Add Ubuntu 16.10 "yakkety yak" debs

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#27521]
Ubuntu 16.10 was released https://wiki.ubuntu.com/YakketyYak/ReleaseSchedule, so we should add this to the list of supported versions for 1.13

Also should be added to the installation docs in the "vnext-engine" branch; https://github.com/docker/docker.github.io/blob/vnext-engine/engine/installation/linux/ubuntulinux.md

/cc @vieux @andrewhsu

**Comment by DavidHazeldenUK** [comment]
Agreed.

**Comment by andrewhsu** [comment]
I concur.

**Comment by aadrian** [comment]
Following those steps, ```apt-cache policy docker-engine``` will return: 
```N: Unable to locate package docker-engine```

**Comment by thaJeztah** [comment]
@aadrian this is for docker 1.13, which has not yet been released. We do have a release candidate for docker 1.13 (see the "testing" repo); http://apt.dockerproject.org/repo/pool/testing/d/docker-engine/

And the easy way to install it is using `curl -fsSL https://test.docker.com | sh`

Keep in mind, that it's a release candidate, so should not be used for production, and that once 1.13 has been released, you need to switch to the "main" deb repository
