### ISSUE TITLE
.dockerignore is ignored when using ADD .

### ISSUE THREAD

**Issue by ionfist** [docker/docker#27538]
**Description**
.dockerignore is ignored when using ADD . /folder

**Steps to reproduce the issue:**
1. echo FROM ubuntu > Dockerfile
2. echo ADD . /tmp >> Dockerfile
3. echo a_file > .dockerignore
4. docker build .

**Describe the results you received:**
The a_file is still in the /tmp folder of the image

**Describe the results you expected:**
The a_file should not be in the /tmp folder of the image

**Additional information you deem important (e.g. issue happens only occasionally):**
1. echo FROM ubuntu > Dockerfile
2. echo ADD a_file /tmp/a_file >> Dockerfile
3. echo a_file > .dockerignore
4. docker build .

The above will actually filter the a_file out and I will get the following error:
lstat a_file: no such file or directory

I do not expect to get the error when using ADD . /folder since this can match more than the .dockerignore excluding patterns, but I do expect the .dockerignore to be honoured.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 15
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.92 GiB
Name: moby
ID: 4XAL:VR4S:5MQ2:TQFY:7ZRX:HXJP:KACZ:VDBC:HZYH:KH2E:NJIL:7S75
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 39
 System Time: 2016-10-15T10:59:05.6910176Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by duglin** [comment]
.dockerignore only applies to the copying of the build context to the server.

You showed two different Dockerfiles - which one is the issue? I'm assuming the 2nd one since I don't see an issue when I try the first. What's interesting about the 2nd usecase is that you're doing something that doesn't really make sense. You're specifically trying to ADD a file that you know isn't there - I would first recommend that you don't do stuff like that :-)    Having said that... do you have a more real usecase where this is an issue?

**Comment by ionfist** [comment]
@duglin thanks for the prompt reply. The issue is actually with the first one. The second is just an example to illustrate that when I use ADD <explicit file name> the exclude pattern works, but when I use ADD . then the exclude pattern does not work. 

Under which OS did you try? I have a feeling it can only affect windows.

**Comment by duglin** [comment]
@ionfist yea, I was on Linux so perhaps its a windows issue.  Not sure why it wouldn't work tho, I don't see anything windows/linux specific in your testcase.  Unless windows doesn't support .dockerfile ignore at all - ping @jhowardmsft

**Comment by jhowardmsft** [comment]
Should be supported...

**Comment by ionfist** [comment]
@jhowardmsft I agree it should.

**Comment by ionfist** [comment]
False alarm!
It seems that everything is working as it should. I was doing a mistake by running a container using the -v flag and my local folder was mounted, that's why I could see the excluded files.

Again I apologise for any trouble and I hope this comment will help anyone in the future with the same "issue".

**Comment by thaJeztah** [comment]
No problem, good to hear you found what caused it @ionfist
