### ISSUE TITLE
Restart Policies on Windows Containers not working on server reboot

### ISSUE THREAD

**Issue by mpwagne** [docker/docker#27544]
If I create a windows container with a restart policy of always... 
Example:
docker run --restart=always -d -e environment=local --name test_restart mycompany/myimage

then, I would expect this container to always start even if the host gets rebooted. 
Results:
- If I stop the Docker service and then start it, the container set to always restarts fine.
- If I reboot the Server, the container does not restart. The daemon is started and functional but the container **does not restart**.
- If I restart the Docker service after the Server has rebooted then the container starts up fine.

HINT: 
If I change the Docker service Startup Type from 'Automatic' to 'Automatic (Delayed Start)', then the container does startup properly after a Server reboot. Though it takes a long, long time to get the daemon started in this mode.

It would seem that some resource (network?) that the Docker service needs when it starts in Automatic mode is not ready at that point in time.  

I suggest someone might want to look at adding the proper dependency to the Docker service registration so the startup will not happen until the required dependency is up.

---

**Docker version:**
Client:
 Version:      1.12.2-rc1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   45bed2c
 Built:        Tue Sep 27 23:38:15 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

**Docker info:**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 78
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.999 GiB
Name: TST-SERVERDOCK2
ID: QFVZ:JA27:2AIK:37XT:EIVT:5IHQ:2KHC:SSZM:NE6C:I766:LAHT:A6N6
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by mpwagne** [comment]
I confirmed that adding a dependency for the Workstation service allows containers to restart properly after a host reboot. Though I don't know the docker service enough to know if this is the desired dependency to set for it long term.

I ran this command on the host as a workaround for the container restart issue.  
**sc config Docker depend=LanmanWorkstation**

It would be good to get the Docker install module to set the proper dependency during the Docker service install.

**Comment by friism** [comment]
pinging @jstarks (since he added the windows service registration).

@jhowardmsft can you put this in the Windows category?

**Comment by georgyturevich** [comment]
Hello all,

@jhowardmsft @jstarks 

When do you plan to fix it?

Btw, Setting a dependency from LanmanWorkstation `sc config Docker depend=LanmanWorkstation` did not  help us. Workaround with delayed start only work for us.

**Comment by jhowardmsft** [comment]
@darrenstahlmsft

**Comment by darrenstahlmsft** [comment]
I just submitted #30111 with the fix. As a current workaround, you can run in an Admin command prompt:
```
sc config Docker depend=ConDrv
```

@georgyturevich FYI

**Comment by drnybble** [comment]
Is anyone still seeing containers not starting up on a reboot? My Docker service is running but all 23 of my containers are stopped. If I restart the service they all start up. Seems to not be 100% consistent, sometimes when I start up my VM they do start up......I am running 17.03.1-ee-3 so it should have these fixes.

**Comment by darrenstahlmsft** [comment]
@drnybble Can you confirm that your docker service correctly has the dependency on `ConDrv`? From an elevated cmd prompt, run `sc.exe qc docker`, the output show show the dependency such as:

```
C:\Users\Administrator>sc.exe qc docker
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: docker
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\Windows\system32\dockerd.exe --run-service -D
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : Docker Engine
        DEPENDENCIES       : ConDrv
        SERVICE_START_NAME : LocalSystem
```

Since this change was to how the service is registered, it's possible that different install methods might not have the fix.

**Comment by drnybble** [comment]
I do not have the ConDrv dependency -- thanks for the tip. I can't remember how I installed it sadly! I'll try the .msi to verify it is working well, thanks.

**Comment by darrenstahlmsft** [comment]
If it has the ConDrv dependency, then it has the fix. Daemon logs from a time when it reboots but fails to restart containers would be helpful to diagnose this. Might want to create a new issue and CC me on it.

**Comment by drnybble** [comment]
I have just reinstalled Docker following the instructions on the Docker site: https://store.docker.com/editions/enterprise/docker-ee-server-windows

Install-Module -Name DockerMsftProvider -Force
Install-Package -Name docker -ProviderName DockerMsftProvider -Force
Restart-Computer -Force

Results of sc qc docker:

C:\Users\Administrator>sc qc docker
[SC] QueryServiceConfig SUCCESS

SERVICE_NAME: docker
        TYPE               : 10  WIN32_OWN_PROCESS
        START_TYPE         : 2   AUTO_START
        ERROR_CONTROL      : 1   NORMAL
        BINARY_PATH_NAME   : C:\Program Files\Docker\dockerd.exe --run-service
        LOAD_ORDER_GROUP   :
        TAG                : 0
        DISPLAY_NAME       : Docker
        DEPENDENCIES       :
        SERVICE_START_NAME : LocalSystem

So it appears that by following the main instructions for installing Docker, this problem remains.

**Comment by cblomart** [comment]
Seems a workaround is to add the dependency manually:
```dos
c:\> sc.exe config docker depend= ConDrv
```
