### ISSUE TITLE
Docker service logs

### ISSUE THREAD

**Issue by frimdo** [docker/docker#27553]
### Feature idea

Docker service is missing logs feature docker-cloud has.

**Steps to reproduce the issue:**
```
docker service logs ...
```
This would show logs, same way as [docker-cloud](https://docs.docker.com/docker-cloud/getting-started/deploy-app/8_view_logs/) does.

**Comment by thaJeztah** [comment]
Duplicate of https://github.com/docker/docker/issues/24812
