### ISSUE TITLE
address bind error while the port isn't already occupied

### ISSUE THREAD

**Issue by rxwen** [docker/docker#27572]
**Description**

Use docker compose to run services on a docker swarm cluster. I tried to stop and restart a redis container, it complained that failed to bind address x.x.x.x:6379. Although I checked system status, that the redis container has been removed completely and the 6379 port isn't occupied.

**Steps to reproduce the issue:**
1. docker-compose up -d
2. docker-compose stop
3. docker-compose up -d redis

**Describe the results you received:**
ERROR: for redis  Cannot start service redis: Error response from daemon: container 875cf5e0f08a4a4057503642c4ea254407417228893781421b97f7782b532f2d: endpoint join on GW Network failed: driver failed programming external connectivity on endpoint gateway_875cf5e0f08a (785dbb758a478e4d2703a459fec2f81d256cfac2b66716a18d9abd3dff37ad10): Error starting userland proxy: listen tcp 192.168.2.175:6379: bind: cannot assign requested address

**Describe the results you expected:**
The redis service should be able to start successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   23cf638
 Built:        Sat Sep 10 02:45:38 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      swarm/1.2.5
 API version:  1.22
 Go version:   go1.7.1
 Git commit:   HEAD
 Built:        <unknown>
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 119
Server Version: swarm/1.2.5
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 2
 t-centos: 10.0.0.174:2375
  └ ID: XECJ:CFK5:LPUH:NPO2:GUKD:PYFI:NALJ:2FA6:SWUL:HFNQ:72DI:LSXY
  └ Status: Healthy
  └ Containers: 1 (1 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.16 GiB
  └ Labels: io.xiaoyan.api=true, kernelversion=3.10.0-327.36.1.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2016-10-20T02:12:08Z
  └ ServerVersion: 1.12.1
 t-centos2: 10.0.0.175:2375
  └ ID: N2VS:7WNX:BYVX:J4Z6:6EYH:ISFC:EMC5:PLKC:ZUBQ:ERE7:RL46:RY6A
  └ Status: Healthy
  └ Containers: 2 (2 Running, 0 Paused, 0 Stopped)
  └ Reserved CPUs: 0 / 4
  └ Reserved Memory: 0 B / 16.17 GiB
  └ Labels: io.xiaoyan.database=true, kernelversion=3.10.0-327.el7.x86_64, operatingsystem=CentOS Linux 7 (Core), storagedriver=devicemapper
  └ UpdatedAt: 2016-10-20T02:12:19Z
  └ ServerVersion: 1.12.1
Plugins:
 Volume:
 Network:
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Security Options:
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: linux
Architecture: amd64
CPUs: 8
Total Memory: 32.33 GiB
Name: t-centos2
Docker Root Dir:
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
it's a physical box with centos 7
uname -a:
Linux t-centos 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by makersphereLabs** [comment]
@rxwen Interesting, we have a similar issue with UCP & docker-compose. #29765 
How did you resolve this? The error message is not really helpful... 🤔

**Comment by rxwen** [comment]
It's been a while, if I recall correctly, it's because I assigned a wrong IP address to the service in yml file. But the IP address isn't the box's ip. That's what I mean by configuration mistake.

**Comment by makersphereLabs** [comment]
@rxwen Thx for your quick reply. :)
You're right, the containers are getting scheduled to the wrong node. This means that the IPs are obviously not matching.
Now we have a completely different problem. 😅
