### ISSUE TITLE
First Container on on Windows Server 2016

### ISSUE THREAD

**Issue by cybage-santajig** [docker/docker#27577]
**Description**

I am trying to run my first docker container on windows server 2016 as per steps given at 
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server

I am using VMPlayer on my Windows Server 2012 R2 host to run Windows Server 2016 Datacenter with full desktop.

**Steps to reproduce the issue:**
1. Follow install instructions:https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server
2. Run docker pull microsoft/sample-dotnet, works...
3. Run docker run microsoft/sample-dotnet , hangs for ever until dockerd is restarted....
4. CTRL+C to stop and try to run any client command like docker ps and that also hangs.

**Describe the results you received:**
It hangs forever and i have to start the new command prompt.

**Describe the results you expected:**
IT should run the command and display the output displayed by microsoft/sample-dotnet image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**

Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 2
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.0.amd64fre.rs1_release.160715-1616)
Operating System: Windows Server 2016 Datacenter Evaluation
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 8 GiB
Name: santajig-VM16
ID: 35YK:H2GC:UCZR:TIV5:3ZAI:YC6O:2GW6:K3IE:RUPH:5KQ7:Q7ZA:4B5D
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am using VM player on Windows Server 2012 R2 to run my Windows Server 2016 Image.

**Comment by friism** [comment]
@cybage-santajig can you confirm that you've run Windows update and have all the latest updates?

**Comment by cybage-santajig** [comment]
Sorry for the late reply. Anyhow, because of our IS polices , i am not able to run the windows update. I shall try the same steps after windows update and shall update this issue again.

**Comment by cybage-santajig** [comment]
I installed the latest update by installing KB3176936. But still the same behavior. Please help me.

**Comment by friism** [comment]
@cybage-santajig Can you please try running this outside of VMWare? Please also try the latest version of Docker Engine:

```
Invoke-WebRequest https://get.docker.com/builds/Windows/x86_64/docker-1.13.0.zip -UseBasicParsing -OutFile docker.zip
Expand-Archive docker.zip -DestinationPath $Env:ProgramFiles
Remove-Item -Force docker.zip

dockerd --register-service

Start-Service docker
```

**Comment by cybage-santajig** [comment]
Running docker outside of VMWare will take some time for me. I shall update the ticket once i am done it.

**Comment by jhowardmsft** [comment]
This was a known issue on that build. Please apply all Windows updates and life should be good. Hence closing. Please re-open if you see the same on a fully patched current build.
