### ISSUE TITLE
Can not init swarm

### ISSUE THREAD

**Issue by sgerr** [docker/docker#27583]
**Description**
Can not init swarm.

**Steps to reproduce the issue:**
docker swarm init --advertise-addr [SOME_IP]

**Describe the results you received:**
Error response from daemon: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode

**Describe the results you expected:**
Swarm initialization as described at https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64
```

**Comment by justincormack** [comment]
The error message is telling you that you have set the `--cluster-store` and `--cluster-advertise` options on the daemon for old-style Swarm mode multihost networking. These cannot be used with the new Swarm mode, you need to remove these options from the daemon config to use the new Swarm mode.

In the 1.13 release you will be able to use the new overlay networks from swarm mode that do not need a standalone kv store for an old style swarm or containers.

**Comment by sgerr** [comment]
Hello. Thank you for the fast reply. I have fresh docker engine installed by yum (OS Oracle Linux 7.2).
Where can I find daemon config to remove these options?
I've checked out https://docs.docker.com/engine/admin/systemd/ but do not find that.

**Comment by sgerr** [comment]
Oh, yes. Found at /etc/docker/daemon.json

Now it works! Thank you!
