### ISSUE TITLE
Cannot GetProcAddress for Py_DontWriteBytecodeFlag

### ISSUE THREAD

**Issue by tabrisaugur** [docker/docker#27585]
When running docker compose, I get the following error:

Cannot GetProcAddress for Py_DontWriteBytecodeFlag

I've now gotten this error on both Windows 10 and Windows 7 (with Docker Toolbox). This has worked on other Windows machines without this error.

Diagnostic uploaded:
7F49371E-5D55-4825-99F2-9BDEF11B5F94/2016-10-20_15-29-54

**Steps to reproduce the issue:**
docker-compose --version

**Describe the results you received:**
Cannot GetProcAddress for Py_DontWriteBytecodeFlag

**Describe the results you expected:**
docker-compose version ...

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens always on some Windows machines, but not others.

**Output of `docker version`:**

```
Docker version 1.12.1, build 23cf638
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.942 GiB
Name: moby
ID: YYX3:44FZ:3HDN:GMCQ:KBGL:PYVQ:ZUPI:R4FE:NR5O:ZWSG:IWD5:6ZMZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-10-20T14:37:21.8635547Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by unclejack** [comment]
@aanand Can you take a look at this, please? It seems to be related to docker-compose.

**Comment by thaJeztah** [comment]
can you reopen this in the docker-compose issue tracker? https://github.com/docker/compose/issues 

That's way it'll get the attention of the docker compose team (and if there's a bug, it can be resolved there)

I'll close the issue in this issue tracker, but thanks for reporting!
