### ISSUE TITLE
Incompatible with Ember-Cli

### ISSUE THREAD

**Issue by ldubrois** [docker/docker#27584]
**Description**
When running, on Windows, Ember-Cli and Docker, the Host becomes unusable as everything is extremly slow. Docker only is fine, Ember-CLI is fine, but Docker + Ember-CLI is very very slow.

**Steps to reproduce the issue:**
1. Start Docker
2. Start Ember server
3. Make few changes on the Ember app to trigger Ember builds.

**Describe the results you received:**
After half an hour, the PC becomes unusable because every action on the PC is very slow.
Building an Ember app takes like 30 seconds (it takes normaly like 2.5 seconds).
Every other app is unstable and ususable (Chrome, IE, Firefox, Visual Studio, Visual Studio Code, Atom, ...)

**Describe the results you expected:**
The PC should remain usable.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      linux/amd64
 Experimental: true

**Output of `docker info`:**

Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 41
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.919 GiB
Name: moby
ID: 6IDZ:AB2F:WGAQ:GVUG:PFCK:4BN2:EAP7:N5E3:EXUE:Z6TI:YSGB:THDG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
Hi, as this seems specific to Docker for Windows can you open the issue at https://github.com/docker/for-win/issues

**Comment by ldubrois** [comment]
My mistake. It's done.
https://github.com/docker/for-win/issues/159
