### ISSUE TITLE
docker inspect --format .NetworkSettings.Ports doesn't work in Windows

### ISSUE THREAD

**Issue by emzeidan** [docker/docker#27592]
Hi team,

I am a Support Engineer from Atlassian and I'm working with a customer on an issue.

The following `docker inspect` command consistently does not seem to work on Windows:
`docker.exe inspect --format='{{(index (index .NetworkSettings.Ports "3000/tcp") 0).HostPort}}' $INSTANCE_ID`.

The command returns the following error:
> Template parsing error: template: :1: unexpected "/" in operand

In https://github.com/docker/toolbox/issues/433, there was a suggestion to switch the quotes from single to double, but that does not work, returning:
> Template parsing error: template: :1: malformed character constant: '3000/tcp'

The issue was tested on CentOS and it does work there.

I apologize if this is a duplicate issue, I was unable to find an existing one.

Thanks in advance!

**Comment by emzeidan** [comment]
Hi team, a quick update from our side. From our testing, it looks like escaping the internal quotes might work:
`docker.exe inspect --format='{{(index (index .NetworkSettings.Ports \"3000/tcp\") 0).HostPort}}' $INSTANCE_ID`



Thanks!

**Comment by thaJeztah** [comment]
Looks like you found the error, so I'll close

**Comment by 573** [comment]
What should work as well is:

    docker.exe inspect --format '{{(index (index .NetworkSettings.Ports "3000/tcp") 0).HostPort}}' $INSTANCE_ID
