### ISSUE TITLE
Container running on user-defined Docker network can't resolve external hosts after being restored from checkpoint

### ISSUE THREAD

**Issue by tswift242** [docker/docker#27597]
**Description**

When I run a container on a user-defined Docker network, and then C/R that container, the container is unable to resolve external hosts post-restore. It is able to resolve external hosts before the checkpoint. Additionally, if I use the default docker0 network instead of a user-defined network, external hosts resolve post-restore. There isn't really anything special about the user-defined network; it was just created to allow IP addresses to be assigned to containers, since that isn't allowed with the docker0 network.

**Steps to reproduce the issue:**
1. docker network create -d bridge --subnet=172.18.0.0/16 -o com.docker.network.bridge.enable_icc=false test
2. docker run --security-opt=seccomp:unconfined --name cr -d --net=test --ip=172.18.0.2 ubuntu /bin/bash -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
3. docker exec -it cr bash
    a) apt-get update && apt-get install -y curl
    b) curl http://www.google.com -- This will work
    c) exit
4. docker checkpoint create cr checkpoint1
5. docker start --checkpoint checkpoint1 cr
6. docker exec -it cr bash
    a) curl http://www.google.com -- This fails

**Describe the results you received:**

Doing "curl http://www.google.com" after the restore results in the error "curl: (6) Could not resolve host: www.google.com"

**Describe the results you expected:**

"curl http://www.google.com" should succeed post-restore, just as it did pre-checkpoint.

**Additional information you deem important (e.g. issue happens only occasionally):**

I've tried modifying the network create command in step 1 to set all of the options for that network to be the same as the docker0 network (except name and default_bridge, of course), and the issue still happens.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   55cd8f5
 Built:        Thu Oct 20 14:39:16 2016
 OS/Arch:      linux/amd64
 Experimental: true

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   55cd8f5
 Built:        Thu Oct 20 14:39:16 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 73
Server Version: 1.13.0-dev
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.25-040425-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.94 GiB
Name: ip-10-97-0-115
ID: EGIZ:TUC2:BOJF:WDEU:P7ZJ:UA5D:FSYY:GN7T:RTRW:7GNK:HDFQ:IINA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 29
 System Time: 2016-10-20T15:48:38.282302655Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Comment by thaJeztah** [comment]
ping @boucher @crosbymichael PTAL

**Comment by boucher** [comment]
I'll take a look. ping @avagin as well

**Comment by thaJeztah** [comment]
Thanks!

**Comment by boucher** [comment]
Still looking, but just to keep this updated: the network seems to be intact. If you grab the direct IP address for a domain you can ping it / hit it with wget just fine. So the issue seems to be just dns resolution.

**Comment by sanimej** [comment]
@boucher Docker embedded DNS server is used for name resolution for containers connected to user defined networks. And embedded DNS relies on iptables rules setup in the container net namespace to map port 53 to an ephemeral port that daemon is listening of. I think there is something off with that after a C/R.  I am not familiar with how C/R works. Will the tcp/udp ports being using by the container be restored after a C/R ?

**Comment by tswift242** [comment]
@sanimej Out of curiosity, why do only user-defined networks use the Docker embedded DNS server, but not the default docker0 network?

**Comment by sanimej** [comment]
@tswift242 Technically there is no issue in having embedded DNS server enabled on default bridge as well. But user defined networks and embedded DNS server were added relatively recently (1.9 and 1.10 respectively). At that point most of the Docker deployments were using the default bridge we didn't want to break apps that had hard coded assumptions about DNS (for ex: external nameservers being populated in /etc/resolv.conf)

**Comment by tswift242** [comment]
@boucher I believe Docker is responsible for restoring the container's net namespace, not CRIU, right? Docker specifies "--empty-ns network" to CRIU (https://github.com/docker/docker/blob/8ed31089c03c36954e95c2066b1f3724e2d5c849/libcontainerd/client_linux.go#L666), and I believe it does that because Docker wants to be the one to setup all the networking. As a result, I believe that Docker sets up networking for a container started from a checkpoint in the same way as it does for a container started the usual way. Is that correct? Did you have to do anything special with networking to get C/R to work in Docker, other than the --empty-ns flag? In which case, it's odd that the iptables rules which @sanimej mentioned are not being re-setup for containers started from checkpoints.

Any thoughts on this either of you?

**Comment by boucher** [comment]
That's right -- as far as I know we're not doing anything special to set up networking on the restored container, simply preventing CRIU from doing anything. CRIU itself does in some instances mess with iptables, maybe its possible that there's a conflict there?

**Comment by tswift242** [comment]
@boucher Who's the right person on the CRIU side to comment as to whether CRIU might be interfering with Docker's iptables rules, even with "--empty-ns network"?

**Comment by boucher** [comment]
@avagin or @xemul would know best I think. I will also try to take a closer
look in the next day or two, unfortunately I've been pretty busy.

**Comment by xemul** [comment]
Yes, this is us :) If we make a patch, would you be able to test one w/o the need to apply one into criu repo? Or at least take a custom branch from the repo...

**Comment by tswift242** [comment]
@xemul I'd be happy to test a patch. It could be a patch on top of criu master or criu-dev, or a separate branch. Either way is fine with me.

**Comment by xemul** [comment]
@tswift242 , I see. I'll try to cook the patch soon and post the link here :)

**Comment by tswift242** [comment]
@xemul Any updates on this?

**Comment by xemul** [comment]
@tswift242 yes. We've released 2.8 with the fix for issue https://github.com/xemul/criu/issues/235 . Now I'm cooking the patch for you on top of it, will post it here in 1-2 days.

**Comment by tswift242** [comment]
@xemul Awesome, thanks!

**Comment by thaJeztah** [comment]
@xemul are changes needed in the docker codebase, or Dockerfile we use to build docker? I see criu 2.2 is currently used https://github.com/docker/docker/blob/master/Dockerfile#L156-L162

**Comment by tswift242** [comment]
@thaJeztah I think the Dockerfile used to build docker needs to be updated to support C/R inside the docker-dev container. I was unable to get C/R to work inside docker-dev, even when using the simple example from the docs. Updating the version may be part of that. See https://github.com/docker/docker/issues/27200

**Comment by xemul** [comment]
@tswift242 , here's the patch: https://lists.openvz.org/pipermail/criu/2016-November/033174.html
It applies to criu-2.8 (which is currently at the top of master branch of the github repo).

**Comment by tswift242** [comment]
@xemul I can confirm that the patch fixes this issue. Thanks a lot!

**Comment by xemul** [comment]
@tswift242 great! :) And thanks for testing.

What are your expectations about this patch to be "officially released"? In current workflow I'll put this patch into next-release queue and it will be out in criu-2.9 December 12.

**Comment by tswift242** [comment]
@xemul We'd like to be able to use criu with this patch as soon as possible. Is is possible to merge this patch into the repo's master branch, directly on top of the 2.8 release? Perhaps that would provide a way to grab stable criu source which also has this patch, even if there's no official interim release for it (e.g. a 2.8.1)

**Comment by xemul** [comment]
@tswift242 sure thing :) The patch is in master branch of the repo. Have fun!

**Comment by thaJeztah** [comment]
@boucher can you take care if changes needed in docker/docker before 1.13 GA ?

**Comment by boucher** [comment]
@thaJeztah I believe so. @xemul it sounds like nothing needs to change on the Docker side though?

**Comment by xemul** [comment]
@boucher , yup, it's purely CRIU thing, just replace the binary.

**Comment by thaJeztah** [comment]
Perhaps we should have an integration test for this (once 2.9 is released). Would be good to have before it leaves "experimental"
