### ISSUE TITLE
sentiment-filtering on container names?

### ISSUE THREAD

**Issue by r2evans** [docker/docker#27600]
The name-generation engine is good at mitigating the chances of collisions and for providing memorable names to otherwise-unnamed containers. This one today caught my eye:

```bash
root@franz:/home/r2/docker/ads# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS                           PORTS                                                   NAMES
797c31849b43        76c44e1ee99d                 "/bin/sh -c 'mkdir -p"   About an hour ago   Exited (123) About an hour ago                                                           backstabbing_stallman
```

Namely, the name `backstabbing_stallman` is a little funny and can be seen as "bite the hand that feeds me" when used in FOSS (though I recognize this is not GPL). The odds of this one coming up one are 1 in over 10k (assuming 70 left and 154 right, as I counted hastily). I spent another moment and found several of the "left" words were indeed potentially-insulting and also funny in their randomness.

Then I noticed that you have [precisely one unacceptable pair](https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/pkg/namesgenerator/names-generator.go#L559) ...

(Not an issue, just wanted to share the funny pairing.)

**Comment by thaJeztah** [comment]
:smile: that line always makes me smile. You may be interested in a little pet-project called ["Docker Who"](https://github.com/cpuguy83/docker-who).

Let me close this issue, but thanks for sharing!
