### ISSUE TITLE
contrib/mkimage-alpine fails on aarch64 (ARMv8) with "segmentation fault"

### ISSUE THREAD

**Issue by vielmetti** [docker/docker#27614]
Using "contrib/mkimage-alpine.sh", alpine fails to build on aarch64 (ARMv8) with "segmentation fault". Docker 1.12.1, Ubuntu 16.04, linux/arm64 (aarch64, ARMv8).

**Steps to reproduce the issue:**
1. Build Docker 1.12.1 from source.
2. cd contrib
3. sudo ./mkimage-alpine.sh

**Describe the results you received:**

```
emv@armv8hello:~/src/docker/contrib$ sudo ./mkimage-alpine.sh 
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
tar: Ignoring unknown extended header keyword 'APK-TOOLS.checksum.SHA1'
fetch http://nl.alpinelinux.org/alpine/edge/main/aarch64/APKINDEX.tar.gz
(1/16) Installing musl (1.1.15-r4)
(2/16) Installing busybox (1.25.1-r0)
Executing busybox-1.25.1-r0.post-install
(3/16) Installing alpine-baselayout (3.0.3-r2)
Executing alpine-baselayout-3.0.3-r2.pre-install
Executing alpine-baselayout-3.0.3-r2.post-install
(4/16) Installing openrc (0.21.7-r1)
Executing openrc-0.21.7-r1.post-install
(5/16) Installing alpine-conf (3.4.1-r5)
(6/16) Installing libressl2.4-libcrypto (2.4.3-r1)
(7/16) Installing libressl2.4-libssl (2.4.3-r1)
(8/16) Installing zlib (1.2.8-r2)
(9/16) Installing apk-tools (2.6.7-r2)
(10/16) Installing busybox-suid (1.25.1-r0)
(11/16) Installing busybox-initscripts (3.0-r6)
Executing busybox-initscripts-3.0-r6.post-install
(12/16) Installing scanelf (1.1.6-r0)
(13/16) Installing musl-utils (1.1.15-r4)
(14/16) Installing libc-utils (0.7-r1)
(15/16) Installing alpine-keys (1.2-r0)
(16/16) Installing alpine-base (3.4.0-r0)
Executing busybox-1.25.1-r0.trigger
OK: 5 MiB in 16 packages
Segmentation fault
```

**Describe the results you expected:**

Expected alpine to build

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time. Not able to determine what is segfaulting.

**Output of `docker version`:**

```
emv@armv8hello:~/src/docker/contrib$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/arm64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/arm64

```

**Output of `docker info`:**

```
emv@armv8hello:~/src/docker/contrib$ docker info
Containers: 88
 Running: 21
 Paused: 0
 Stopped: 67
Images: 183
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: aarch64
CPUs: 96
Total Memory: 125.8 GiB
Name: armv8hello.local.lan
ID: QB72:5PAI:O62E:QEPU:4DKN:3M2K:33FC:AIJU:PXMC:YMGX:Y376:IAPK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

ARMv8 96 core system, no virtualization

**Comment by tianon** [comment]
Heh @vielmetti this is the same root cause as the issue you reported over at https://github.com/tianon/jenkins-groovy/issues/15 :smile:

(Namely that Alpine's `apk-static` binary from `edge` seems to segfault on `armhf` and `aarch64` ATM)

**Comment by vielmetti** [comment]
Thanks @tianon - I guess I'm getting closer to the problem because it's happening on my own machine. I was able to grab the apk.static binary and get a version number so we know at least what we're up against.

```
root@armv8hello:/var/tmp/alpine-docker-y2oEFmD4Ye/sbin# ./apk.static --version
apk-tools 2.6.7, compiled for aarch64.
```

I was able to identify http://git.alpinelinux.org/cgit/apk-tools as the source, and there's a diff at http://git.alpinelinux.org/cgit/apk-tools/commit/?id=06ae5fdfdccd0c8e6d5501d93666bd915d2604d1 that is specific to aarch64 and after 2.6.7, so this might be as simple as a new release to pick up that fix.

I opened up https://bugs.alpinelinux.org/issues/6372 with a little more information. If I had to guess, it might be better with apk-tools@master rather than apk-tools@2.6.7, but I don't know enough about the build process to test that myself.

**Comment by thaJeztah** [comment]
Also /cc @ncopa :+1:

**Comment by vielmetti** [comment]
http://git.alpinelinux.org/cgit/apk-tools/commit/?id=5723afded3fe67588fbdd7d398b8db19f134f759 is an upstream patch, which looks like it works but I haven't tested yet.

**Comment by vielmetti** [comment]
The discussion upstream is about pushing a new release of the affected tools tomorrow, which would allow people to do their own builds. I will report back as that happens.

**Comment by KurtStam** [comment]
Worked like a charm for me : https://hub.docker.com/r/project31/aarch64-alpine/

**Comment by vielmetti** [comment]
@KurtStam - which architecture are you building on?

**Comment by vielmetti** [comment]
The upstream bug https://bugs.alpinelinux.org/issues/6372 has been resolved, and alpine:edge now builds successfully on aarch64 (ARMv8) with the supplied script. 

The comment in the close message is "This seems to be an aarch64 specific binutils ld issue. It generates relocations. Workaround is to add -Bsymbolic linker flag. We will be adding this to gcc specs shortly."

This issue can be closed.

**Comment by thaJeztah** [comment]
Thanks @vielmetti @KurtStam
