### ISSUE TITLE
docker run --tmpfs through remote api

### ISSUE THREAD

**Issue by gsf-greece** [docker/docker#27636]
Hi, are there plans to support this in the future? This can be very helpful for example when running containers using docker maven plugin.

**Comment by justincormack** [comment]
Can you explain what you are asking for? You can add `tmpfs` mounts using the API - everything the CLI does is performed via the API.

**Comment by gsf-greece** [comment]
Thanks for your reply, I've tried the [forums](https://forums.docker.com/t/tmpfs-using-remote-api/21479), and IRC channel, but had no luck so far. I want to be able to run a mysql container that has /var/lib/mysql mounted as tmpfs. I'm running this through [docker maven plugin](https://github.com/fabric8io/docker-maven-plugin). 

If it is possible to do this using the remote api, can you give me an example so I can pass it on to the developer so he can add it to the plugin? The last time I asked he said it isn't [implemented](https://github.com/fabric8io/docker-maven-plugin/issues/455) yet.

**Comment by AkihiroSuda** [comment]
Here: https://github.com/docker/docker/blob/9f0593990f6d8ac95a5dde312e0b7401b472cfb9/api/types/container/host_config.go#L308


key is a mount point and value is a mount option string passed to the mount syscall (can be empty)


Maybe not documented yet?

**Comment by gsf-greece** [comment]
Thanks, I will pass it on! I have the feeling it is not documented.

**Comment by thaJeztah** [comment]
If it's not documented indeed, could you open a separate issue for that? (Or perhaps a pull request)

Let me close this issue,  because the original problem seems to be resolved, but feel free to continue the discussion
