### ISSUE TITLE
Docker behat Laravel issues.

### ISSUE THREAD

**Issue by juanmrad** [docker/docker#27637]
On version 1.12.1 behat comand runs db migrate from laravel super slow. I had to downgrade to version 1.12.0 in order to be able to run it smoothly. 

I'm running on OS El capitan 10.11.6 and Laravel 5.1. 
It takes over 5 minutes to run a simple scenario due to the slow migrate. doing a
php artisan migrate
takes over 2 minutes. DB only has 44 tables.

**Comment by unclejack** [comment]
@juanmrad This seems to be an issue with Docker for Mac. Can you open an issue on this repository instead: https://github.com/docker/for-mac/, please?

I'll close this issue now as it's not a Docker engine issue and it's mostly Docker for Mac related.
