### ISSUE TITLE
Docker should send "Accept-Encoding: identity" header when requesting layers

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#27642]
per the discussion on https://github.com/docker/docker/pull/25122, docker should send this header to prevent transparent decompression of 'x-gzip' content

/cc @stevvooe @dmcgowan

**Comment by aaronlehmann** [comment]
Summary should read `Accept-Encoding: identity`.

**Comment by thaJeztah** [comment]
reopening as it's not vendored yet

/cc @stevvooe
