### ISSUE TITLE
Swarm refuses unspecified listen address when advertise address is not a system address

### ISSUE THREAD

**Issue by LLParse** [docker/docker#27647]
**Description**

When creating cross-cloud Swarm clusters, traffic must be routed over the Internet. Doing so requires advertising a public IP address for each node. However, Swarm refuses to accept an unspecified listen address if the advertise address doesn't match a system address.

Is there a reason Swarm couldn't best-effort choose a network interface in this scenario, like it does when no options are provided?

**Steps to reproduce the issue:**
1. Create a Docker 1.12.2 node that advertises its public IP address that isn't also a system address.
2. Attempt to bootstrap a Swarm cluster `docker swarm init --advertise-addr <public_ip>:2377`

**Describe the results you received:**

```
Error response from daemon: must specify a listening address because the address to advertise is not recognized as a system address
```

**Describe the results you expected:**

```
Swarm initialized: current node (xxx) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-xxx \
    <public_ip>:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 6
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 38
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.708 GiB
Name: foo
ID: APBO:R7OP:N25R:R3FS:UP4S:TPEN:AIM6:ND52:RKZV:XOP6:P5L6:GH3O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Reproduces in AWS, GCE, and others..
DigitalOcean is not afflicted since the public IP is also a system address

**Comment by thaJeztah** [comment]
ping @aaronlehmann PTAL!

**Comment by aaronlehmann** [comment]
This requirement comes from overlay networking. My understanding is that it needs to know the local address so it can set up a tunnel.

ping @mavenugo @mrjana - can you clarify?

**Comment by LLParse** [comment]
If I specify no arguments, the interface for the overlay network is correctly deduced in cases where there is one private IP address. When there are multiple, I am guessing Swarm selects one at random or complains to the user to specify one.

It is my understanding that, in general terms, an advertise address is the address sent to other nodes which allows communication back to [the advertising] node, but has no effect on the configuration/functionality of the node itself. It is a pointer for others, useful when behind a proxy, NAT, etc.

Assuming that the advertise address isn't used in a unique way, it would be really, _really_ nice to be allowed to set the advertise address without setting the listen address.

**Comment by yongtang** [comment]
In non-swarm overlay mode (working with external K-V store like Consul/etcd), `--cluster-advertise` serves as both advertise and listen address as well. The PR #22663 will allow different listen/advertise addresses to be specified. In that case, you could bind a local address while at the same time advertise a public IP address that is at your public gateway (like in AWS's case).

The issue raised here is the swarm overlay mode so things could be different.

**Comment by yongtang** [comment]
In non-swarm overlay mode (external K-V store), each node is identified/managed through `Serf`. Serf allows you to specify two addresses: The advertise address is the address that identifies yourself. The listen address is the "bind address" that bind to a local interface so that you could listen to message sent from your peers to you. Your peers does not necessarily know your listen/bind address as it is not relevant. (Since bind address might be 0.0.0.0 or a private address behind the firewall.) You peers only know your advertise address as this is the address of your identification (from outside point of view).
Currently lib network only passed one address to Serf, PR #22663 will split the address into bind and advertise address.

In swarm mode, node discovery has been changed and Serf has been replaced. So will need to do more investigation.

**Comment by yongtang** [comment]
The raft in the swarmkit is using the advetiseAddr. It splits the advertise and listen address. It should be fine:
https://github.com/docker/docker/blob/c5ceb0f945d390500a0045b14ffe4dcecfe46a85/vendor/github.com/docker/swarmkit/manager/manager.go#L220-L244

Need to see if libnetwork has special requirement on advertise/listen address or not.

**Comment by aaronlehmann** [comment]
ping @mavenugo

**Comment by stevvooe** [comment]
I think the problem here is that we've bound the fate of advertise address and host overlay address.

The solution here is probably to require an `--overlay-addr` when `--advertise-addr` is not available on the machine.

**Comment by thaJeztah** [comment]
@stevvooe there's a PR opened here; https://github.com/docker/docker/pull/22663

**Comment by thaJeztah** [comment]
oh, sorry, that one is not for swarm mode :blush:

**Comment by LLParse** [comment]
Thank you everyone for addressing this!

**Comment by tchamabe1979** [comment]
Hello guys i am facing with the same issue
Initialize Swarm..
Error response from daemon: must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified
