### ISSUE TITLE
Incorrect installation documentation for Centos/RedHat

### ISSUE THREAD

**Issue by pembo13** [docker/docker#27650]
Documentation: http://docs.kalabox.io/en/stable/users/install/

The current recommend instructions may only be accurate for Fedora. 

```bash
sudo dnf update -y
sudo dnf install bridge-utils iptables cgroup-bin
sudo rpm -i kalabox.deb
```

On CentOS 7 (and I presume equivalent RHEL) the necessary commands are

```bash
yum update -y
yum install bridge-utils iptables cgroup-bin
yum install kalabox-v2.0.1.rpm
```

And even with these commands, one gets the following warning/error:

```
warning: %post(kalabox-2.0.1-1.x86_64) scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package kalabox-2.0.1-1.x86_64
```

To avoid this, one needs to use these commands instead:
```bash
yum update -y
yum install bridge-utils iptables cgroup-bin xdg-utils
yum install kalabox-v2.0.1.rpm
```

It should also be noted, that a web server listening on all 443 TCP ports will cause an error as well on install:

```
Cannot start container cdd298fd09beed13564a12d74ca044403dd8a76db2d3b90bd2259e438f8fea21: failed to create endpoint kalabox_proxy_1 on network bridge: Error starting userland proxy: listen tcp 10.13.37.100:443: bind: address already in use
```

**Comment by jphuynh** [comment]
I think you got the wrong project man. See: https://github.com/kalabox/kalabox/issues ?

**Comment by pembo13** [comment]
Definitely my mistake. Sorry.
