### ISSUE TITLE
Retag and push fails by "Retrying in" -- Not using pre-existing layers

### ISSUE THREAD

**Issue by rsvp** [docker/docker#27659]
**Description: Retag and push fails by "Retrying in" -- Not using pre-existing layers**

I locally retagged an official debian image as rsvp/jessie and pushed it to docker.io as my public repo, however, that failed in "Retrying in ..." as it tried to actually upload the bulk. All the necessary layers should already be pre-existing at Docker's hub, hence expected behavior would be no uploading necessary. 

**Steps to reproduce the issue:**

1. Pull any known image at Docker's hub
2. Retag this image as USER/NEWNAME
3. Push that retagged local image to hub

**Describe the results you received:**

4. Observed failure to find pre-existing layers
5. Observed upload fail by numerous "Retrying" messages.

**Describe the results you expected:**

- Struggle to upload should not even occur since the necessary layers pre-exist at the hub repository

**Additional information you deem important (e.g. issue happens only occasionally):**

- Major problem especially for popular large images, e.g. continuumio/anaconda
- Not suspecting a permission problem since operations are performed in public space

**Output of `docker version`:**

```
Docker version 1.12.2, build bb80604
```

**Output of `docker info`:**

```
Containers: 18
 Running: 1
 Paused: 0
 Stopped: 17
Images: 54
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 62
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.64 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by thaJeztah** [comment]
i think cross-repo sharing of layers depends on the registry version in use; it's possible Docker Hub does not use that version yet.

/cc @dmcg @tonistiigi

**Comment by rsvp** [comment]
Is the following info posted by  @stevvooe on May 14, 2015 for #13210 -- more than 17 months ago, still valid?

> Efficiency-wise, the V2 protocol is biased towards pull rather than push. The behavior you've described is a side-effect of access-control in the V2 protocol. From a high-level, the image has a list of blobs that make it up. Currently, all of these blobs need to be "mounted" into a remote repository (ie "centos"). When pushing these blobs (layers) for the first time into a new repository, the **client must "prove" they have access to the blob by sending it**. This gets verified and the blob then becomes available in the new repository. Even though data is sent "unnecessarily", data is only ever stored once.

If still current, there must be a better way to furnish proof than to resend a blob which could be enormous in size. It might seem reasonable for small *private* repos, however, if the blobs are public, then the hash should be sufficient proof to prevent unnecessary upload of a pre-existing layer.

The "Retrying in ..." upload issue can possibly be averted by setting *--max-concurrent-uploads* (in the daemon dockerd) but hinges on the individual user's internet capacity. 

Would be grateful to see other alternative solutions. Thanks!

**Comment by stevvooe** [comment]
@rsvp I think @thaJeztah was pointing that out: we do have a better way of proving ownership, called cross-repo mount, which may not be implemented by the hub.

> It might seem reasonable for small private repos, however, if the blobs are public, then the hash should be sufficient proof to prevent unnecessary upload of a pre-existing layer.

So, now the hashes of your content become sufficient to access that content? If you leak one of your layer hashes, do you want everyone else to have access to that data now? Even telling an attacker that a blob is public or private leaks too much information here.

I'd recommend you contact support.docker.com and discuss with them.

**Comment by rsvp** [comment]
Re: Push to registry v2 does not detect already pushed layers #1411 @RichardScothern commented on Feb 2, 2016:

> The v2 security model necessitated images being re-uploaded. Registry 2.3 does not require a re-upload if the client has read access to an existing layer in another repository.

Expected behavior would be that if the repository is public, then the read access is obviously set for everyone -- thus re-uploading would NOT be necessary. This certainly would make sense for saving disk space at the hub. And presumbly there's no security risk from exposing the hash values of the *public* blobs involved (assuming OP was not careless).  

Q: Does docker.io use cross-repo mount to prove ownership? How does an user query a hub about its features from CLI, e.g. the Registry protocol version?  *Appreciate your comments -- thanks!*

**Comment by stevvooe** [comment]
> Expected behavior would be that if the repository is public, then the read access is obviously set for everyone -- thus re-uploading would NOT be necessary. This certainly would make sense for saving disk space at the hub. And presumbly there's no security risk from exposing the hash values of the public blobs involved (assuming OP was not careless).

To be clear, we don't store the same data twice. We only force clients to prove they have the data if they want to redistribute it, unless they have permissions to mount from another repository.

While it may seem "obvious", the issues become clear when you start analyzing how to implement the ACLs in such a system. ACLs are done at the repository level to keep the size of ACL from bloating as the number of blobs grow and to avoid having to maintain an extra service (database or otherwise) to maintain this. There are also complexities involved when two entities disagree on the ACL of a blob. Let's say Bob says a blob _must_ be private but Alice insists that it is public. Do you just serve up that data to everyone because Alice said so?

To deal with this, there is no such thing as "public" repositories, from the registry perspective. Every user authenticates access to a repository, and that token is presented with each API request. When a repository is "public", this token is passed out to whoever asks, but it is still authenticated as anonymous.

> Q: Does docker.io use cross-repo mount to prove ownership? 

Again, this is a question for support.docker.com. docker.io is separate from the docker project and associated protocols.

> How does an user query a hub about its features from CLI, e.g. the Registry protocol version? Appreciate your comments -- thanks!

The mount is tried, optimistically,  [here](https://github.com/docker/distribution/blob/master/registry/client/repository.go#L717). If it works, then no upload is necessary. If not, the upload proceeds normally.

**Comment by rsvp** [comment]
@stevvooe Thanks very much for your thorough response. I think your Alice/Bob scenario nails the current issue. Very interesting that: **there is no such thing as "public" repositories from the registry perspective** -- this non-obvious fact should help resolve any misunderstanding regarding ACL (*Access Control List*), esp. why Docker may not be using pre-existing layers during a **push** to a hub.

As for the *security* aspect, Bob must trust Alice to keep his blobs private -- much like how his decrypted GPG private text should not be posted on her public blog for everyone's reading pleasure. 

**SUMMARY: This issue began with the intention to archive an official image, which was public, to an user's repository in a non-local hub for the sake of future replication, lest the official image be deleted. The ACL as described above indicates that necessary blobs will be accessible by the user even if official owner deletes their (pointers to the) blobs. *The cost involved is the download time involved in the push operation, even if one knows the layers already exist at the hub* -- to prove actual ownership.**

**Comment by stevvooe** [comment]
@rvsp Great summary!

I would like to add that this is addressed in registries with cross-repo mount, avoiding the extra upload cost, if supported.

Let me know if you have more questions!
