### ISSUE TITLE
docker images should return none zero if no image

### ISSUE THREAD

**Issue by neilhwatson** [docker/docker#27657]
Search for image that is not installed:

Steps:
1. docker image does-not-exist; echo $?

Expected results:
Returns none zero and no output

Actual results:
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
0

Why?
Programs need to be able to determine whether or not an image is installed.

root@node1:~# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 992.3 MiB
Name: node1
ID: XHPN:4KOB:NWD2:DIVF:GGJR:QKXJ:JH7Y:BCWN:HVN2:7FES:ZGBV:ISNS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by thaJeztah** [comment]
The image name specified is a filter, filtering with no results is not an _error_ so I don't think this should return a non-zero code. Is there a reason you cannot detect if the output is empty? Using the `-q` flag would return the image ID if it exists, and an empty result if not

**Comment by neilhwatson** [comment]
I expected it to function like grep and return 0 if the search matches and 1 if there is no match. Yes I can use a pipe, but that is less intuitive.

**Comment by thaJeztah** [comment]
if you are expecting grep, you can always use grep of course :smile:

/cc @tianon wdyt?

**Comment by ripcurld00d** [comment]
:+1:  @thaJeztah.
`docker images --format "{{.Repository}}:{{.Tag}} | grep ${image_name}`

**Comment by tianon** [comment]
While I agree that this is probably how this filtering should've worked originally, it's been this way for long enough that I don't think it warrants a breaking change IMO.

Personally, I usually use `docker inspect` for my existence checks, ie:
```bash
if ! docker inspect --type image image-does-not-exist &> /dev/null; then
  # something to do when the image doesn't exist
else
  # yay, we have the image we wanted
fi
```

**Comment by thaJeztah** [comment]
I'm going ahead and close this, but I hope the above examples help you in your use-case.

Thanks for suggesting, it is appreciated!
