### ISSUE TITLE
docker fails to start on centos 7

### ISSUE THREAD

**Issue by neilhwatson** [docker/docker#27661]
A fresh install of Centos 7. No previously installed docker.

[root@node1 ~]# uname -a
Linux node1 3.10.0-327.36.1.el7.x86_64 #1 SMP Sun Sep 18 13:04:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@node1 ~]# rpm -qa|grep docker-engine
docker-engine-selinux-1.12.2-1.el7.centos.noarch
docker-engine-1.12.2-1.el7.centos.x86_64

[root@node1 ~]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 

Oct 22 20:58:25 node1 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has begun starting up.
Oct 22 20:58:25 node1 docker[1252]: time="2016-10-22T20:58:25.775606292Z" level=fatal msg="no sockets found via socket activation: make sure the service was st
Oct 22 20:58:25 node1 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Oct 22 20:58:25 node1 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit docker.service has failed.
-- 
-- The result is failed.
Oct 22 20:58:25 node1 systemd[1]: Unit docker.service entered failed state.
Oct 22 20:58:25 node1 systemd[1]: docker.service failed.
Oct 22 20:58:25 node1 polkitd[654]: Unregistered Authentication Agent for unix-process:1247:108657 (system bus name :1.39, object path /org/freedesktop/PolicyK

Also from /var/log/messages:

# grep docker /var/log/messages 
Oct 22 20:44:02 localhost yum[995]: Installed: docker-engine-selinux-1.12.2-1.el7.centos.noarch
Oct 22 20:44:05 localhost yum[995]: Installed: docker-engine-1.12.2-1.el7.centos.x86_64
Oct 22 20:44:06 localhost docker: time="2016-10-22T20:44:06.442681769Z" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Oct 22 20:44:06 localhost systemd: docker.service: main process exited, code=exited, status=1/FAILURE
Oct 22 20:44:06 localhost systemd: Unit docker.service entered failed state.
Oct 22 20:44:06 localhost systemd: docker.service failed.
Oct 22 20:58:25 localhost docker: time="2016-10-22T20:58:25.775606292Z" level=fatal msg="no sockets found via socket activation: make sure the service was started by systemd"
Oct 22 20:58:25 localhost systemd: docker.service: main process exited, code=exited, status=1/FAILURE
Oct 22 20:58:25 localhost systemd: Unit docker.service entered failed state.
Oct 22 20:58:25 localhost systemd: docker.service failed.

**Comment by thaJeztah** [comment]
How did you install docker? And from which repository?

Can you verify if the systemd unit file matches the current one in this repo? https://github.com/docker/docker/blob/master/contrib/init/systemd/docker.service.rpm

**Comment by neilhwatson** [comment]
[root@node1 yum.repos.d]# cat docker.repo 
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1

What is the location of the file you want me to check? Guessing:

[root@node1 ~]# diff docker.service.rpm /lib/systemd/system/docker.service 
4c4
< After=network.target firewalld.service
---
> After=network.target

**Comment by thaJeztah** [comment]
hm odd, that change shouldn't make a difference here. I wonder why it's complaining about socket activation. Can't think of a reason there, unless there's a systemd drop-in / override in place somewhere.

**Comment by thaJeztah** [comment]
there's some info on that in the release notes https://github.com/docker/docker/releases/tag/v1.12.2

@mlaventure any ideas?

**Comment by neilhwatson** [comment]
Found this:

```
[root@node1 docker.service.d]# pwd
/etc/systemd/system/docker.service.d
[root@node1 docker.service.d]# cat override.conf 
[Service]
ExecStart=
ExecStart=/usr/bin/docker daemon --storage-driver=overlay -H fd://
```

**Comment by thaJeztah** [comment]
Ah! that would explain; you can remove the `-H fd://` there

However, I don't know where that file came from, other than possibly docker was installed on that machine already (or in the past)?

After changing, make sure to do a daemon reload of systemd, otherwise changes are not picked up

**Comment by thaJeztah** [comment]
oh, and for docker 1.12, change `docker daemon` to `dockerd`

**Comment by neilhwatson** [comment]
Was a scripted build, that someone else scripted. I think Docker is off the hook :)

**Comment by thaJeztah** [comment]
Good to hear it's resolved! Note that for changing daemon options, using a daemon.json file may be a good option instead https://docs.docker.com/engine/reference/commandline/dockerd/

**Comment by OldCrowEW** [comment]
@neilhwatson you should read the docs for what you are opening issues about: https://dcos.io/docs/1.8/administration/installing/custom/system-requirements/install-docker-centos/

**Comment by pumba-lt** [comment]
I had the same issue when running `docker-compose`. Tried `dockerd` and found out that CentOS 7 Linux kernel was too old (due to old virtualization system or smth):

    FATA[0001] Your Linux kernel version 2.6.32-042stab123.9 is not supported for running docker. Please upgrade your kernel to 3.10.0 or newer.

**Comment by jeffgreenca** [comment]
The -H fd:// is referenced here: https://success.docker.com/article/how-do-i-enable-the-remote-api-for-dockerd

Perhaps that document needs to be updated?

**Comment by thaJeztah** [comment]
@jeffgreenca yes, that document should probably mention that socket activation is not used on rpm-based (CentOS/RHEL) installs

**Comment by thaJeztah** [comment]
@jeffgreenca I opened an internal ticket to have that page updated, thanks!

**Comment by esxi1979** [comment]
in my case i can start docker after i  removed

removed -H fd://

But still i get below err

i user CentOS 7x - latest kernel 3.10.0-693.21.1.el7.x86_64 & the install done from repo , this is CE 

docker info
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by esxi1979** [comment]
i removed -H tcp://0.0.0.0:2375
as well

And all ok finally 

thx @thaJeztah

**Comment by danger89** [comment]
Alterntiavlly replace `-H fd://` with `-H unix://`
