### ISSUE TITLE
How to close docker client in golang

### ISSUE THREAD

**Issue by zjxpsetp** [docker/docker#27666]
I create a docker cli by 
`	cli, err := client.NewEnvClient()
	if err != nil {
		beego.Error("Connect docker client error.", err.Error())
		return result, err
	}`

But don't know how to close this cli.
I want to know this because I got many "dial unix /var/run/docker.sock: socket: too many open files" errors when call docker api too quickly.

**Comment by dnephin** [comment]
Every call on the client makes sure to close the response body. Otherwise I don't think there is anything else to close.

I don't think your error is related to the client. The client just attaches to a socket, it doesn't  create them.

**Comment by zjxpsetp** [comment]
`	project, err := docker.NewProject(&ctx.Context{
		Context: project.Context{
			ComposeFiles: []string{config.GetDockerComposeYmlFile()},
		},
	}, nil)

	if err != nil {
		return allInfo, err
	}

	// Get container name and status
	allInfo, err = project.Ps(context.Background())
	if err != nil {
		return allInfo, err 
	}`

with a loop to run this code, we found there are too many file descriptor under /proc/pid/fd.
@dnephin

**Comment by dnephin** [comment]
That looks like `libcompose` code? Please open an issue on the docker/libcompose issue tracker, it is likely a bug in `libcompose`

**Comment by rohit4813** [comment]
Hi,
I don't know whether it is related or not but I was also getting "dial unix /var/run/docker.sock: socket: too many open files" error while creating a docker container through golang SDK.

Found out that the number of file descriptors had reached the limit of 1024 for this process, most of them were for sockets.

The solution was to explicitly call **cli.Close()**(where cli, err := client.NewEnvClient()) after you are done with docker client.
