### ISSUE TITLE
docker events format is not reliably machine-readable

### ISSUE THREAD

**Issue by runcom** [docker/docker#27667]
The parenthesized key=value pairs are comma-separated but there's no protection for commas, making it challenging to parse something like:

      (Release=56, Vendor=Red Hat, Inc., Name=rhel7/rhel, ...)

There are many possible ways to address this. Some possibilities:

    * Backslash-escape commas within key or value: Vendor=Red Hat\, Inc.
    * Escape commas as HTML entities or using URL escaping: Vendor=Red Hat&#2C; Inc. or =Red Hat%2C Inc.
    * Double-quote values that contain space/comma/other: Vendor="Red Hat, Inc."

Note that commas aren't the only characters needing escape: also equal sign, and possibly close-paren. And, given any of the above mechanisms, its corresponding escape character itself (backslash, ampersand, percent, double-quote).

This is a can of worms, and there is not currently a compelling reason to parse this output... but there will be. Best to sort this out early and document it clearly.

Reproducer:
```sh
$ docker run --label test="a, really) not machine=readable)label," busybox

$ docker events # truncated...
705f13ff94b3fd52138f76 (image=busybox, name=adoring_feynman, test=a, really) not machine=readable)label,)
```

/cc @duglin @thaJeztah @vdemeester

**Comment by duglin** [comment]
I vote for using backslashes - it seems the easiest to parse, and doesn't expand things too much.

**Comment by thaJeztah** [comment]
No real preference for one or the other, unless there's a standard. Using quotes would be more consistent with the way to _set_ labels, although is possibly less easy to parse.

Question though; isn't the API more meant for automating? Should we have a `--format` flag, to allow formatting the output (and, e.g. output the raw JSON instead)

**Comment by runcom** [comment]
A format flag which outputs to JSON will solve this issue pretty well w/o requiring an API call directly. It's also pretty elegant to me to output in a well defined format such as json if asked to do so via a flag.

**Comment by thaJeztah** [comment]
Well, I can see it being valuable to have the default format being somewhat better parseable, so I'd be +1 for improving it

**Comment by runcom** [comment]
I see a format flag for json more valuable than adding and cluttering the default format which clearly targets humans instead of machines. Adding escaping and whatnot to the default format will make it less human readable for sure. A new format flag to json will target machine parsing while still having a human readable format (the default).

**Comment by thaJeztah** [comment]
SGTM

**Comment by runcom** [comment]
Alright, I'll submit a PR soon

**Comment by justincormack** [comment]
Yes, agree with @runcom there is no point in trying to make a poorly designed format parseable when we have existing formats that work already.

**Comment by runcom** [comment]
Forget me, there's already a way  to format json https://github.com/docker/docker/pull/26268 (but I  missed it)

**Comment by thaJeztah** [comment]
oh! yes you're right
