### ISSUE TITLE
Compilation broken with go < 1.7

### ISSUE THREAD

**Issue by runcom** [docker/docker#27669]
https://github.com/docker/docker/pull/27405 broke compilation on systems with go < 1.7 (e.g. Fedora 24):

```
---> Making bundle: dynbinary (in bundles/1.13.0-dev/dynbinary)
Building: bundles/1.13.0-dev/dynbinary-client/docker-1.13.0-dev
Created binary: bundles/1.13.0-dev/dynbinary-client/docker-1.13.0-dev
Building: bundles/1.13.0-dev/dynbinary-daemon/dockerd-1.13.0-dev
vendor/src/github.com/tonistiigi/fifo/fifo.go:4:2: cannot find package "context" in any of:
        /usr/lib/golang/src/context (from $GOROOT)
        /home/amurdaca/src/github.com/docker/docker/.gopath/src/context (from $GOPATH)
        /home/amurdaca/src/github.com/docker/docker/vendor/src/context
```

/cc @tonistiigi

**Comment by tonistiigi** [comment]
I think if we want to support 1.6 we should have a ci and validation scripts for that. Considering this is not part of the API packages, I'm not sure if we need to support builds that don't use the dependencies in our Dockerfile. This time I could do it for that package but if some other vendored package upgrades to go1.7 that shouldn't stop us from using it.

**Comment by justincormack** [comment]
Yes, it has broken at least four times already as we have no CI.

**Comment by mlaventure** [comment]
Like @tonistiigi I don't think we want to officially support dependencies that aren't the one we use in our Dockerfile, it would quickly become a maintenance nightmare.

**Comment by runcom** [comment]
> Like @tonistiigi I don't think we want to officially support dependencies that aren't the one we use in our Dockerfile, it would quickly become a maintenance nightmare.

@mlaventure how would you dynamically compile (dynbinary) on a RHEL/Fedora system that ship with go < 1.7? are we dropping support for dynamic compilation on those system? how would you "make rpm" anymore if the golang shipped with those systems is < 1.7?

**Comment by mlaventure** [comment]
@runcom I'm not sure I understand, `make rpm` will run compile everything via the image generated via the `Dockerfile` which include go1.7.

**Comment by runcom** [comment]
> @runcom I'm not sure I understand, make rpm will run/compile everything via the image generated via the Dockerfile which include go1.7.

yeah, forget that I was wrong, anyhow, distros building with system's golang like Fedora, RHEL, Suse will all be affected by this.

**Comment by runcom** [comment]
Fixed by https://github.com/docker/containerd/pull/338
