### ISSUE TITLE
"docker diff" error on windows

### ISSUE THREAD

**Issue by rs38** [docker/docker#27672]
`docker ps -a`

````
CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS                      PORTS               NAMES
4678a4ed444d        microsoft/nanoserver:latest   "powershell"        55 minutes ago      Exited (0) 13 minutes ago                       boring_boyd
````

`docker diff 467`

````
Error response from daemon: hcsshim::UnprepareLayer failed in Win32: Die angegebene Netzwerkressource bzw. das angegebene Gerät ist nicht mehr verfügbar. (0x37) layerId=4678a4ed444df9411a79ae1aa7b8
453958fe98bb960e820208e703ef3f279316 flavour=1
`````

tested on either Win10, Nano VM and Server2016 full.

Server Version: 1.12.2-cs2-ws-beta-rc1
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: nat null overlay
Swarm: inactive
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64

Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 511.6 MiB
Name: NanoVMi7

Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.91 GiB
Name: HPi7

**Comment by rs38** [comment]
also tested with 1.13.0 dev

Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9bece
 Built:        Sat Oct 22 22:35:05 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9bece
 Built:        Sat Oct 22 22:35:05 2016
 OS/Arch:      windows/amd64

**Comment by rs38** [comment]
@darrenstahlmsft can repo this also?

**Comment by darrenstahlmsft** [comment]
I'm also seeing this. I'm not sure if diff has ever worked on Windows though... I can take a look in a couple days unless someone else wants to look now.

/cc @jhowardmsft @jstarks @swernli FYI

**Comment by jstarks** [comment]
docker diff used to work.

**Comment by jhowardmsft** [comment]
#dibs

**Comment by jhowardmsft** [comment]
I'll see what I can find.

**Comment by jhowardmsft** [comment]
Opened https://github.com/docker/docker/pull/27842 to fix.

**Comment by rs38** [comment]
can confirm it now works!!
