### ISSUE TITLE
"docker stats" error on Windows

### ISSUE THREAD

**Issue by rs38** [docker/docker#27671]
`docker stats`
only shows
`Template parsing error: template: :1: unexpected "{" in command`

tested on either Win10, Nano VM and Server2016 full.

Server Version: 1.12.2-cs2-ws-beta-rc1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64

Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 511.6 MiB
Name: NanoVMi7

Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.91 GiB
Name: HPi7

**Comment by rs38** [comment]
also tested with 1.13.0 dev

Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9bece
 Built:        Sat Oct 22 22:35:05 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9bece
 Built:        Sat Oct 22 22:35:05 2016
 OS/Arch:      windows/amd64

**Comment by friism** [comment]
Works for me (Win10 client, remote WS2016):

```
C:\code\dockerfiles-windows [dont-use-openssl +1 ~0 -0 !]> docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 05:27:08 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
C:\code\dockerfiles-windows [dont-use-openssl +1 ~0 -0 !]> docker ps
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS               NAMES
407d460bcf5c        microsoft/windowsservercore   "powershell /c sleep "   45 seconds ago      Up 43 seconds                           hungry_payne
```

```
CONTAINER           CPU %               MEM USAGE / LIMIT   MEM %               NET I/O               BLOCK I/O           PIDS
407d460bcf5c        0.00%               0 B / 0 B           0.00%               89.56 kB / 12.46 kB   0 B / 0 B           0
```

It also works running the daemon on Windows 10 directly

**Comment by rs38** [comment]
any idea how to dig deeper?

**Comment by thaJeztah** [comment]
The template error could be if there's a custom format (`--format`) provided, although i thought that was not supported through a CLI config file

**Comment by rs38** [comment]
just tried with switching windows to US english regional settings, same result

**Comment by thaJeztah** [comment]
@rs38 what image are you running? What is running in your containers?

**Comment by rs38** [comment]
e.g. ` docker run -d microsoft/nanoserver ping -t localhost`

**Comment by darrenstahlmsft** [comment]
I can repro with the given container. I'm investigating.

**Comment by jhowardmsft** [comment]
#dibs

**Comment by jhowardmsft** [comment]
Sure, looking

**Comment by jhowardmsft** [comment]
Yes, I can repro. Investigating.

**Comment by jhowardmsft** [comment]
Was broken by 96622b2a7d58d74883bc1777d3be171c2b8f2165. Looking at a fix.

**Comment by rs38** [comment]
Thank you
