### ISSUE TITLE
interactive docker login won't work with docker toolbox and git for windows

### ISSUE THREAD

**Issue by Tschasmine** [docker/docker#27684]
**Description**

When working with the docker toolbox on windows using git for windows the docker login command won't work interactively. 
`docker login --username xxx --password yyy`
works fine, however

```
docker login
Login with your Docker ID to push and pull images from Docker Hub. If you don't have a Docker ID, head over to https://hub.docker.com to create one.
Username (xxx): yyy
```

won't work.
**Steps to reproduce the issue:**
1. Try authenticating with a docker hub account using docker toolbox and git for windows from bash using interactive `docker login` command.
2. You'll get ask for the password (username is already provided), like this: `Username (xxx):`
3. Enter password and hit enter.

**Describe the results you received:**
Login fails with "The handle is invalid."
`docker login --username xxx --password yyy`
works (using the same credentials).

**Describe the results you expected:**
interactive docker login should work and log me in successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:44:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:00:50 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 22
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.2 (TCL 7.2); HEAD : 9d8e41b - Tue Oct 11 23:40:08 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: default
ID: PPYD:FBN6:JMS7:B4TV:B43S:LAP7:2HUW:LCFD:YUTP:RZCY:D5PD:H6VI
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 22
 Goroutines: 100
 System Time: 2016-10-24T12:48:55.222171914Z
 EventsListeners: 0
Username: tschasmine
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 Anniversary Update
git for windows
`git version 2.7.0.windows.2`

**Comment by thaJeztah** [comment]
This could be a client-side issue, can you try updating your client binary as well?

**Comment by jhowardmsft** [comment]
There have been multiple fixes in this area since the above release - hence closing. Please re-open if this is still an issue on 1.13.x
