### ISSUE TITLE
docker logs --tails returns less lines than expected

### ISSUE THREAD

**Issue by hmdhasani** [docker/docker#27687]
I run this command  several times :
docker  logs --tail 10000  app | tee >(wc -l)
to count number of lines of log and got this results:
1212
52
346
2614

when I run :
docker  logs  app 
I will got much more (604147 lines)

I think there is a bug in --tail

**Comment by hmdhasani** [comment]
ut@TST-mcluster-13:~$ docker info
Containers: 22
 Running: 22
 Paused: 0
 Stopped: 0
Images: 74
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 298
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-72-generic
Operating System: Ubuntu 14.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 15
Total Memory: 39.3 GiB
Name: TST-mcluster-13
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by hmdhasani** [comment]
ut@TST-mcluster-13:~$ docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

**Comment by cpuguy83** [comment]
Are the logs rotated (aka split) across multiple files (ie,  `--log-opts max-size=N`, is set)

**Comment by hmdhasani** [comment]
no I don't think , I ran the app with no option about logs and this is the inspect:

    {
        "Id": "142d1f7690be3f303c9da2873d6a5c1f4937fd3e1273d479894a1810d113a23e",
        "Created": "2016-10-24T15:45:50.131301351Z",
        "Path": "catalina.sh",
        "Args": [
            "run"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 7727,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2016-10-24T15:49:21.584945476Z",
            "FinishedAt": "2016-10-24T15:49:20.933710912Z"
        },
        "Image": "sha256:426b1f49e6c0bd1aaed87c2c9cda46ff29444dc8556b4ce05b9e960a3b0cff1c",
        "ResolvConfPath": "/var/lib/docker/containers/142d1f7690be3f303c9da2873d6a5c1f4937fd3e1273d479894a1810d113a23e/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/142d1f7690be3f303c9da2873d6a5c1f4937fd3e1273d479894a1810d113a23e/hostname",
        "HostsPath": "/var/lib/docker/containers/142d1f7690be3f303c9da2873d6a5c1f4937fd3e1273d479894a1810d113a23e/hosts",
        "LogPath": "/var/lib/docker/containers/142d1f7690be3f303c9da2873d6a5c1f4937fd3e1273d479894a1810d113a23e/142d1f7690be3f303c9da2873d6a5c1f4937fd3e1273d479894a1810d113a23e-json.log",
        "Name": "/app",
        "RestartCount": 0,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "app-hosts-aliases:/etc/host-aliases"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "c0_net",
            "PortBindings": {
                "8080/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "7010"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [
            {
                "Name": "app-hosts-aliases",
                "Source": "/var/lib/docker/volumes/app-hosts-aliases/_data",
                "Destination": "/etc/host-aliases",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "142d1f7690be",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8080/tcp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "HOSTALIASES=/etc/host-aliases/host-aliases",
                "PATH=/usr/local/tomcat/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre",
                "JAVA_VERSION=8u91",
                "JAVA_DEBIAN_VERSION=8u91-b14-1~bpo8+1",
                "CA_CERTIFICATES_JAVA_VERSION=20140324",
                "CATALINA_HOME=/usr/local/tomcat",
                "TOMCAT_MAJOR=7",
                "TOMCAT_VERSION=7.0.69",
                "TOMCAT_TGZ_URL=https://www.apache.org/dist/tomcat/tomcat-7/v7.0.69/bin/apache-tomcat-7.0.69.tar.gz"
            ],
            "Cmd": [
                "catalina.sh",
                "run"
            ],
            "Image": "app",
            "Volumes": null,
            "WorkingDir": "/usr/local/tomcat",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "a8aa94060601402dceb9e58c77106beed6b3ff4af109f169e858b32d001b1603",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "8080/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "7010"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/a8aa94060601",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "c0_net": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "app",
                        "142d1f7690be"
                    ],
                    "NetworkID": "09f84af093b8c3b1d8c8629602a6ba86d4380fcc28f5db0e538a1fe8c779114e",
                    "EndpointID": "e2bd311dd97b7979727f83b8a0cb154d0d7a3ca03c5f1db6eadb7c4be069cc37",
                    "Gateway": "21.1.0.1",
                    "IPAddress": "21.1.0.19",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
            }
        }
    }
]

**Comment by cpuguy83** [comment]
Thanks! Just wanted to check because we have a custom reader implementation when multiple files are used.

**Comment by shaynewang** [comment]
#dibs

**Comment by shaynewang** [comment]
I'll look into it and see if I can fix it :)

**Comment by shaynewang** [comment]
I was not able to reproduce this problem on my end. What's the response for you if you just do a line count without the tee? like:     $ docker logs --tail 10000 app | (wc -l)
I'm asking because I wasn't sure why there are multiple numbers

**Comment by shaynewang** [comment]
It appears that if you run the logs with the "--tail" option when the service is writing to the stdout you will sometimes getting a random number of lines back. I'll investigate further no that I have reproduced the problem.

**Comment by hmdhasani** [comment]
@shaynewang No, running without tee does not solve the problem :(
Did you use the same docker version and os as mine? 
Server Version: 1.12.2
Ubuntu 14.04.1 LTS
Kernel Version: 3.19.0-72-generic

**Comment by shaynewang** [comment]
@hmdhasani  Yes, I have reproduced the problem. It seems that if you are reading the log while the log is being written at the moment then you will get a random number of lines return with --tail option. I'm working on the problem right now. Thanks!

**Comment by shaynewang** [comment]
@hmdhasani  I'm still on this. I think we need a -f functionality for --tail. I don't have a lot of free time but I'm working on it/

**Comment by hmdhasani** [comment]
Thank you, @shaynewang

**Comment by shaynewang** [comment]
pull request created #28203

**Comment by hmdhasani** [comment]
Thank you @shaynewang 
Is this patch included in version 1.13 ?

**Comment by cpuguy83** [comment]
Should be in 1.13 rc2 I believe.
