### ISSUE TITLE
Check network error during the creation of docker machine

### ISSUE THREAD

**Issue by mehdiAhmed** [docker/docker#27686]
**Description**
When I create a docker-machine I got the **error Check network to re-create if needed**.
 I'm using ubuntu 14.04, virtualbox 4.3.36 and docker 1.12.2.
Please how can I handle this error.
I re-installed virtualbox, docker-machine and docker-engine but I got the same error.

**Steps to reproduce the issue:**
docker-machine create --driver virtualbox default

**Describe the results you received:**
(default) Copying /home/myName/.docker/machine/cache/boot2docker.iso to /home/myName/.docker/machine/machines/default/boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
Error creating machine: Error in driver during machine creation: Unable to start the VM: exit status 1

**Describe the results you expected:**
  (default) Waiting for an IP...
  Waiting for machine to be running, this may take a few minutes...
  Machine is running, waiting for SSH to be available...

**Additional information you deem important (e.g. issue happens only occasionally):**

**docker version**
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
 Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**docker-machine version**
docker-machine version 0.8.2, build e18a919

**vboxmanage --version**
4.3.36_Ubuntur105129

**Ubuntu version**
Latitude-E7240:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Latitude-E7240:~$ docker info**
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by cpuguy83** [comment]
ping @nathanleclaire

**Comment by nathanleclaire** [comment]
> virtualbox 4.3.36

Thanks for the issue.  Please try w/ latest Virtualbox (5.1.6 IIRC) and also make sure to clear any host only networks you have created locally as well if possible (`VBoxManage list hostonlyifs` will show them on CLI, probably easiest to remove them from the VBox "Networks" GUI).

If the issue still persists, please file an issue with full `--debug` output on the docker/machine repo.

@cpuguy83 I'd recommend to close-- thanks all.

**Comment by cpuguy83** [comment]
Thanks @nathanleclaire, @mehdiAhmed
