### ISSUE TITLE
Create container error: chown xxx value too large for defined data type

### ISSUE THREAD

**Issue by liubin** [docker/docker#27691]
**Description**

**Steps to reproduce the issue:**
1. I have a volume driver.
2. create the a container use the driver with `-v vol:/some/path --volume-driver=mydriver` under marathon.

**Describe the results you received:**

Got error in `/var/log/upstart/docker.log`:

`Handler for POST /v1.21/containers/create returned error: chown /volume-mnts/vol-1: value too large for defined data type`

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 10
 Running: 10
 Paused: 0
 Stopped: 0
Images: 187
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 307
 Dirperm1 Supported: true
Logging Driver: fluentd
Cgroup Driver: cgroupfs
Plugins:
 Volume: local mydriver
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 62.68 GiB
Name: 10.80.10.18
ID: WLFJ:VV56:TVJ5:RUUY:TNY4:YYD6:2F57:AMYY:K6YE:PXF3:KVCY:OTDE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical Server

**Comment by liubin** [comment]
Other issue. Close it.

**Comment by dineshputchala** [comment]
How did you resolve this error ? I am also getting similar error while using docker 1.13
chown: changing ownership of 'test.zip': Value too large for defined data type

**Comment by liubin** [comment]
I googled, and the most cases is the 32bits OS's issue.

In my case, the net filesystem is the root cause, nothin to Docker.

`ls /volume-mnts/vol-1` get the same error alse.
