### ISSUE TITLE
Windows: `nat` and `null` network plugins listed twice in docker info

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#27695]
@msabansal Just noticed that on a default install (server 2016, RS1 up to date), no custom networking configured, nat and null are listed twice under Network:

D:\>docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   0ab13dd
 Built:        Mon Oct 24 18:57:12 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   0ab13dd
 Built:        Mon Oct 24 18:57:12 2016
 OS/Arch:      windows/amd64

D:\>docker info
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 5
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat nat null null transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 14 GiB
Name: jenkins-rs1-1
ID: JWX7:R6TS:HR6Q:6U3G:PUON:L3MV:NOCL:BWOB:EXNN:YSXE:INA6:WOEY
Docker Root Dir: D:\control
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

D:\>

**Comment by yongtang** [comment]
Created a PR #27699 for this issue.

**Comment by thaJeztah** [comment]
this should be fixed, now that https://github.com/docker/docker/pull/27699 was merged
