### ISSUE TITLE
Container clocks dont advance when a windows host resumes.

### ISSUE THREAD

**Issue by jessegranger** [docker/docker#27711]
**Description**

Docker containers hosted on Windows have their clock drift by exactly the amount of time the Windows host spends in suspend mode.  Upon resuming, all current and future docker containers created (until reboot) will have their clock stuck permanently in the past.

**Steps to reproduce the issue:**

Steps to reproduce:
1 Have Docker on Windows.
2 Check that containers are reading the same time as the system:
```
> date
Tue, Oct 25, 2016  1:06:05 AM
> docker run -it centos:centos7 date
Tue Oct 25 01:06:08 UTC 2016
```
3 Walk away. After 30 minutes, windows goes into suspend, and stays that way.
4 After N > 30 minutes, return and resume the machine.
5 Notice that the containers think that only 30 minutes have passed, for all values of N.
```
> date
Tue, Oct 25, 2016  3:21:42 AM
> docker run -it centos:centos7 date
Tue Oct 25 01:36:41 UTC 2016
```

**Describe the results you received:**
Container clocks have drifted by exactly the amount of time spent suspended.

**Describe the results you expected:**
Container clocks should not be significantly skewed by suspend/resume.

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 63
 Running: 0
 Paused: 0
 Stopped: 63
Images: 576
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 332
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.942 GiB
Name: moby
ID: 5R42:RGC2:JJIX:YXKW:WWOZ:LLU7:2ZDB:5DTW:L4CY:SDSH:S2XX:2A6J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-10-25T01:57:42.5726905Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

```
The System Time, in the above, is behind the true system time by about 2 hours.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 Pro 64-bit Version 1511 OS Build 10586.633

**Comment by friism** [comment]
I think this is a duplicate of this: https://github.com/docker/for-win/issues/72

**Comment by jessegranger** [comment]
Yep, looks like it. Sorry I only searched with the windows tag.

Closing as duplicate, Thanks
