### ISSUE TITLE
unable to update service image using Remote Api

### ISSUE THREAD

**Issue by rsalimian** [docker/docker#27712]
getting _service not found_ error when trying to update service image using service name:

`curl -X POST -v -H 'Content-Type: application/json' \
-d '
{
    "name":"myService",
    "TaskTemplate":{
        "ContainerSpec":{
            "Image":"myrepo\/myservice:v0020"
        }
    }
}' \
http://localhost:2375/services/myService/update?version=11`

error : 
`message":"rpc error: code = 5 desc = service myService not found"`

if i use service ID then i get `changing network in service is not supported`
`
curl -X POST -v -H 'Content-Type: application/json' \
-d '
{
    "name":"myService",
    "TaskTemplate":{
        "ContainerSpec":{
            "Image":"myrepo\/myservice:v0020"
        }
    }
}' \
http://localhost:2375/services/4224tq9vp73m4wb911og5b8mi/update?version=11 
`
error: `{"message":"rpc error: code = 2 desc = changing network in service is not supported"}`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5fda6e
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2-cs2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5fda6e
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 11
Server Version: 1.12.2-cs2
Storage Driver: devicemapper
 Pool Name: docker-253:0-201883342-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.26 GB
 Data Space Total: 107.4 GB
 Data Space Available: 45.3 GB
 Metadata Space Used: 5.255 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: 5nt7djdqho31m7prg4bym8rnw
 Is Manager: true
 ClusterID: 7jndr5yp0lcwmqw2ftvmmkpwg
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.168.16
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.3 MiB
Name: manager1
ID: PDK5:CIBZ:FX7R:EJ3C:M2UM:CHA4:JGY4:3CZX:3DXV:MSBX:HZXH:2RP3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jewelscent
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by rsalimian** [comment]
issue resolved after more investigation.

these steps helped me to be able update the service using remote API:

- update service using service name won't work (service not found error) and have to use FULL service ID
- first I need to inspect service to pull whole "Spec"
- use current version.index to use in service update
- update it with changes and use it to update service

**Comment by aluzzardi** [comment]
Hi @rsalimian, that's correct

> update service using service name won't work (service not found error) and have to use FULL service ID

Actually, that was a bug in the API and was fixed in master (#26093). You should be able to use names for service updates in the future.

**Comment by harshadyeola** [comment]
@aluzzardi 
This issue is still there
```
curl -X POST -v -H 'Content-Type: application/json' -d ' { "name":"myService", "TaskTemplate":{ "ContainerSpec":{ "Image":"org\/eximage:test" } } }' http://localhost:4243/services/myService/update

{"message":"rpc error: code = 2 desc = changing network in service is not supported"}
```
**docker version**
```
root@example:~# docker version
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:14:09 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
@harshadyeola that's a different issue; the issue reported here is that the API didn't recognise the service if it was passed by _name_ instead of _ID_, this was fixed by https://github.com/moby/moby/pull/26093.

The "changing network in service is not supported" message is expected for Docker 17.03, which doesn't support changing the network for an existing service. Changing networks was implemented recently in https://github.com/moby/moby/pull/32062, which is part of 17.05 (edge release) and will be in 17.06 (stable release channel)
