### ISSUE TITLE
docker-daemon killed as a result of limit of /docker-daemon

### ISSUE THREAD

**Issue by janson087** [docker/docker#27714]
i am running some app with docker(version 1.8.3),some day i found that docker daemon exit because of oom kill. so i deploy some script to monit the docker process, i found that Docker occupies a sudden increase in memory , and it exit in 2 minutes. 

here are the output:
message:
Oct 18 21:32:58 nr-paas12 kernel: docker invoked oom-killer: gfp_mask=0xd0, order=0, oom_score_adj=-900
Oct 18 21:32:58 nr-paas12 kernel: docker cpuset=docker-daemon mems_allowed=0
Oct 18 21:32:58 nr-paas12 kernel: CPU: 2 PID: 27350 Comm: docker Not tainted 3.10.0-229.el7.x86_64 #1
Oct 18 21:32:58 nr-paas12 kernel: Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 09/30/2014
Oct 18 21:32:58 nr-paas12 kernel: ffff8801fe938b60 000000005d47eb8d ffff8801a3e1f808 ffffffff81604b0a
Oct 18 21:32:58 nr-paas12 kernel: ffff8801a3e1f898 ffffffff815ffaaf 0000000000000001 ffff8801a3e1f850
Oct 18 21:32:58 nr-paas12 kernel: ffff88043ffce000 ffff8801a3e1f868 ffffffff81159fb6 ffff8803243a6068
Oct 18 21:32:58 nr-paas12 kernel: Call Trace:
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff81604b0a>] dump_stack+0x19/0x1b
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff8115a44e>] oom_kill_process+0x24e/0x3b0
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff8107bdde>] ? has_capability_noaudit+0x1e/0x30
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff811bd5ae>] __mem_cgroup_try_charge+0xb9e/0xbe0
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff811bdd80>] ? mem_cgroup_charge_common+0xc0/0xc0
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff811bdd19>] mem_cgroup_charge_common+0x59/0xc0
Oct 18 21:32:58 nr-paas12 kernel: [<ffffffff811bf96a>] mem_cgroup_cache_charge+0x8a/0xb0
Oct 18 21:32:58 nr-paas12 kernel: Task in /docker-daemon killed as a result of limit of /docker-daemon
Oct 18 21:32:58 nr-paas12 kernel: memory: usage 11388340kB, limit 11388340kB, failcnt 30857
Oct 18 21:32:58 nr-paas12 kernel: memory+swap: usage 11446700kB, limit 9007199254740991kB, failcnt 0
Oct 18 21:32:58 nr-paas12 kernel: kmem: usage 0kB, limit 9007199254740991kB, failcnt 0
Oct 18 21:32:58 nr-paas12 kernel: Memory cgroup stats for /docker-daemon: cache:1996KB rss:11386344KB rss_huge:165888KB mapped_file:0KB swap:58360KB inactive_anon:1462140KB active_anon:9924260KB inactive_file:988KB active_file:952KB unevictable:0KB
Oct 18 21:32:58 nr-paas12 kernel: [ pid ]   uid  tgid total_vm      rss nr_ptes swapents oom_score_adj name
Oct 18 21:32:58 nr-paas12 kernel: [ 1721]     0  1721  3946485  2851701    5719    15200          -900 docker
Oct 18 21:32:58 nr-paas12 kernel: Memory cgroup out of memory: Kill process 1614 (docker) score 78 or sacrifice child
Oct 18 21:32:58 nr-paas12 kernel: Killed process 1721 (docker) total-vm:15785940kB, anon-rss:11396508kB, file-rss:10296kB
Oct 18 21:32:59 nr-paas12 systemd: docker.service: main process exited, code=killed, status=9/KILL
Oct 18 21:32:59 nr-paas12 systemd: Unit docker.service entered failed state.
Oct 18 21:33:01 nr-paas12 kubelet: E1018 21:33:01.982395    7740 kubelet.go:2254] Container runtime sanity check failed after 100.392995ms, err: docker: failed to get docker version: dial unix /var/run/docker.sock: connection refused

monit output:
                                                                                                           sz          rss                                   
Tue Oct 18 21:29:55 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 670418 58464
Tue Oct 18 21:30:00 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 670418 58444
Tue Oct 18 21:30:05 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 670418 58444
Tue Oct 18 21:30:10 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 670418 58444
Tue Oct 18 21:30:15 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 670418 58444
Tue Oct 18 21:30:20 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 670418 58444
Tue Oct 18 21:30:25 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 677360 91768
Tue Oct 18 21:30:30 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 816484 583204
Tue Oct 18 21:30:35 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 964817 1042720
Tue Oct 18 21:30:40 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1261089 1845532
Tue Oct 18 21:30:45 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1261426 2089192
Tue Oct 18 21:30:50 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1854419 2806072
Tue Oct 18 21:30:55 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1854419 3576160
Tue Oct 18 21:31:01 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1854419 3950512
Tue Oct 18 21:31:06 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1854483 4213192
Tue Oct 18 21:31:11 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 1855306 4469008
Tue Oct 18 21:31:16 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 3040445 6641016
Tue Oct 18 21:31:21 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 3040445 6955732
Tue Oct 18 21:31:26 CST 2016 1721 /usr/bin/docker daemon -H t 4.3 3040445 723414

docker info:
Containers: 85
Images: 561
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 11.25 GB
 Data Space Total: 51 GB
 Data Space Available: 39.75 GB
 Metadata Space Used: 18.16 MB
 Metadata Space Total: 532.7 MB
 Metadata Space Available: 514.5 MB
 Udev Sync Supported: false
 Deferred Removal Enabled: false
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.7.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 7.64 GiB
Name: vm-paas-kubernetes03
ID: SPHQ:3GWP:DJMP:QAGQ:V2EI:HR45:7BZQ:K2CN:6OBT:RE2N:OT77:GL7Q
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

Is it a docker issue, what cause the issue?

**Comment by cpuguy83** [comment]
Could be a number of things we would really need more info to troubleshoot, such as what's running, how much logging is happening, etc.
Also bare in mind the OOM killer is indiscriminate in what it kills.

Since this is on 1.8.3 I'm not sure we are really going to be able to track this down since the codebase has changed significantly since then, bugs squashed, memory leaks plugged, etc.
I'm going to close this, but feel free to continue the discussion, or hop on the community slack or IRC if you like and we can debug live.

Thanks!
