### ISSUE TITLE
docker stats shows the memory limit is more than the total system/VM memory

### ISSUE THREAD

**Issue by aftakhan** [docker/docker#27727]
ISSUE: docket stats is showing memory more than present in VM

[root@dockerhost ~]# docker stats

 

CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O             PIDS

728c7cfbec9b        0.46%               284.3 MB / 16.66 GB   1.71%               0 B / 0 B           221.7 kB / 3.174 MB   0

c85311367a4d        0.08%               148.2 MB / 16.66 GB   0.89%               0 B / 0 B           2.593 MB / 3.05 GB    0

6aebf40cfc0a        0.00%               10.6 MB / 16.66 GB    0.06%               0 B / 0 B           209.4 kB / 0 B        0

1f030d5da9f0        0.00%               5.108 MB / 16.66 GB   0.03%               0 B / 0 B           320 kB / 0 B          0

eef73598629b        0.02%               43.82 MB / 16.66 GB   0.26%               0 B / 0 B           6.42 MB / 143.3 MB    0

3d822db1a783        0.00%               61.87 MB / 16.66 GB   0.37%               0 B / 0 B           939 kB / 0 B          0

0cc1ddc66c1a        0.00%               33.24 MB / 16.66 GB   0.20%               0 B / 0 B           1.625 MB / 0 B        0

[root@dockerhost ~]# free -g

              total        used        free      shared  buff/cache   available

Mem:             15           0          13           0           1          14

Swap:             1           0           1

 

[root@dockerhost ~]# cat /proc/meminfo

MemTotal:       16268376 kB  **(i.e. 16.268376 GB) which is less than 16.6 GB**

MemFree:        14524852 kB

MemAvailable:   15354584 kB

^C[root@dockerhost ~]# top
top - 06:00:24 up 15 days,  3:56, 15 users,  load average: 0.17, 0.06, 0.06
Tasks: 245 total,   1 running, 243 sleeping,   1 stopped,   0 zombie
%Cpu(s):  0.2 us,  0.2 sy,  0.0 ni, 99.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 16268376 **((i.e. 16.268376 GB) which is less than 16.6 GB)** total, 14530984 free,   547208 used,  1190184 buff/cache
KiB Swap:  2097148 total,  2097148 free,        0 used. 15362560 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND  

Thanks
Aftab

**Comment by coolljt0725** [comment]
@aftakhan  docker stats take 1k as 1000 but not 1024
16268376 kB * 1024/1000000000=16.65GB

**Comment by coolljt0725** [comment]
@aftakhan  I'm going to close since it's not an issue, but please feel free to comment :)

**Comment by aftakhan** [comment]
Hi Colljit0725,

As per the docker calculation total memory = 16.65, but as per Docker stats command output LIMIT = 16.66 GB. which is 0.01 GB more what docker calculates as per your comment. If we convert to MB as per docer 0.01*1000 = 10 MB. This is not a small no 10 MB. 

root@dockerhost ~]# docker stats consulserver01

CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O            PIDS
consulserver01      0.56%               43.75 MB / 16.66 GB   0.26%               0 B / 0 B           6.42 MB / 273.7 MB   0


**Main doubt:** Each System/VM/Container has it's own  swap, buffer/cache memory normally should not be used by any other process

in VM
++++++
[root@dockerhost ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:          15887         502       14237          17        1146       15035
Swap:          2047           0        2047
[root@dockerhost ~]# 
[root@dockerhost ~]# free -g
              total        used        free      shared  buff/cache   available
Mem:             15           0          13           0           1          14
Swap:             1           0           1
[root@dockerhost ~]# 

In Container
+++++++
bash-4.1# free -g
             total       used       free     shared    buffers     cached
Mem:            15          1         13          0          0          0
-/+ buffers/cache:          0         14
Swap:            1          0          1
bash-4.1# free -m
             total       used       free     shared    buffers     cached
Mem:         15887       1645      14241         17          1        789
-/+ buffers/cache:        854      15032
Swap:         2047          0       2047
bash-4.1# 

Would you please clarify the above points.

Thanks
Aftab

**Comment by aftakhan** [comment]
Please suggest how to re-open?

**Comment by thaJeztah** [comment]
The value shown in `docker stats` is rounded to 2 decimals; 
 16268376 kB * 1024/1000000000 = 16.658817024 (is 16.66 after rounding). You can get un-rounded numbers through the API;

```JSON
{
  "read": "2017-01-03T15:49:57.835632652Z",
  "preread": "2017-01-03T15:49:56.835236753Z",
  "pids_stats": {
    "current": 2
  },
  "blkio_stats": {
    "io_service_bytes_recursive": [],
    "io_serviced_recursive": [],
    "io_queue_recursive": [],
    "io_service_time_recursive": [],
    "io_wait_time_recursive": [],
    "io_merged_recursive": [],
    "io_time_recursive": [],
    "sectors_recursive": []
  },
  "num_procs": 0,
  "storage_stats": {},
  "cpu_stats": {
    "cpu_usage": {
      "total_usage": 23292070,
      "percpu_usage": [
        4762480,
        329983,
        1757179,
        16442428
      ],
      "usage_in_kernelmode": 10000000,
      "usage_in_usermode": 10000000
    },
    "system_cpu_usage": 1021989860000000,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "precpu_stats": {
    "cpu_usage": {
      "total_usage": 23292070,
      "percpu_usage": [
        4762480,
        329983,
        1757179,
        16442428
      ],
      "usage_in_kernelmode": 10000000,
      "usage_in_usermode": 10000000
    },
    "system_cpu_usage": 1021985870000000,
    "throttling_data": {
      "periods": 0,
      "throttled_periods": 0,
      "throttled_time": 0
    }
  },
  "memory_stats": {
    "usage": 1761280,
    "max_usage": 2019328,
    "stats": {
      "active_anon": 1421312,
      "active_file": 4096,
      "cache": 20480,
      "dirty": 0,
      "hierarchical_memory_limit": 9223372036854772000,
      "hierarchical_memsw_limit": 9223372036854772000,
      "inactive_anon": 4096,
      "inactive_file": 8192,
      "mapped_file": 4096,
      "pgfault": 725,
      "pgmajfault": 0,
      "pgpgin": 637,
      "pgpgout": 286,
      "rss": 1417216,
      "rss_huge": 0,
      "swap": 0,
      "total_active_anon": 1421312,
      "total_active_file": 4096,
      "total_cache": 20480,
      "total_dirty": 0,
      "total_inactive_anon": 4096,
      "total_inactive_file": 8192,
      "total_mapped_file": 4096,
      "total_pgfault": 725,
      "total_pgmajfault": 0,
      "total_pgpgin": 637,
      "total_pgpgout": 286,
      "total_rss": 1417216,
      "total_rss_huge": 0,
      "total_swap": 0,
      "total_unevictable": 0,
      "total_writeback": 0,
      "unevictable": 0,
      "writeback": 0
    },
    "limit": 2095861760
  },
  "name": "/web",
  "id": "a9a9aaec7441683f6c3cf92b8d907b17efdb01e95cd56707e5ce0a599e9dd27d",
  "networks": {
    "eth0": {
      "rx_bytes": 1296,
      "rx_packets": 16,
      "rx_errors": 0,
      "rx_dropped": 0,
      "tx_bytes": 648,
      "tx_packets": 8,
      "tx_errors": 0,
      "tx_dropped": 0
    }
  }
}
```

> Each System/VM/Container has it's own swap, buffer/cache memory normally should not be used by any other process

A container is not a VM; depending on the [storage driver that's used](https://docs.docker.com/engine/userguide/storagedriver/imagesandcontainers/), page cache can be shared between containers, which makes them more efficient.

Note that memory statistics inside a container may show incorrect values. Many tools rely on `/proc/meminfo` or `/proc/vmstat`, which are not cgroup-aware. See https://fabiokung.com/2014/03/13/memory-inside-linux-containers/, which can only be fixed in the kernel.
