### ISSUE TITLE
refresh a local docker image

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/docker#27720]
Allow to refresh a local docker image

**Steps to reproduce the issue:**
1. I pull an image myubuntu:latest
2. I update the docker image in a remote docker repository
3. Docker is not able to update the local image with the last version, I need to remove the local image for downloading the new version

**Describe the results you received:**
The local image is not the last version

**Describe the results you expected:**
Add a policy for downloading the last version of an image

**Comment by thaJeztah** [comment]
Can you explain

> Docker is not able to update the local image with the last version, I need to remove the local image for downloading the new version

If you `docker pull myubuntu`, docker will pull the latest version of the "myubuntu" image, is that not working for you?

**Comment by sylvainmouquet** [comment]
Yes the first time we got the last version of the image.
After when the image is in the local docker repository if we create a container from the image the image is taken from the local docker repository.
If the image is updated in the remote docker repository, the local docker repository is not refreshed with the last version. For getting the last version we need to remove the image from the local docker repository and pull the image.

**Comment by thaJeztah** [comment]
Is that  local _repository_, or the local image-cache (`docker images`)? If the local image-cache, then there's no need to remove the image, just `docker pull <image>` to have it pull the latest version.

**Comment by sylvainmouquet** [comment]
ok i did a docker run without call the docker pull <image> before

thanks i close the issue

**Comment by thaJeztah** [comment]
Thanks for confirming!
