### ISSUE TITLE
docker generated a non advertise addr when run 'docker swarm init --advertise-addr xxx'

### ISSUE THREAD

**Issue by TheBeeMan** [docker/docker#27728]
**Description**

docker info 

Containers: 18
 Running: 0
 Paused: 0
 Stopped: 18
Images: 59
Server Version: 1.13.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 386
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge bridge host host macvlan null null overlay overlay
Swarm: active
 NodeID: 59yjvlxx42yc7o5malo8ntzsw
 Is Manager: true
 ClusterID: 9subjvgzfzisgzvzyp3dkbzzd
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.79.181
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.843 GiB
Name: thebeeman-vt
ID: 7LDL:PJZO:3PDL:LH2I:L7U2:BTVY:24OQ:E7ZG:MRZ5:ETD5:3SBW:SSYR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 120
 System Time: 2016-10-25T18:58:10.618315261+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

I wanna create a swarm cluster using native instruction:
docker swarm init --advertise-addr xxx

> Swarm initialized: current node (59yjvlxx42yc7o5malo8ntzsw) is now a manager.
> 
> To add a worker to this swarm, run the following command:
> 
> ```
> docker swarm join \
> --token SWMTKN-1-04km6foy54zi2taxddx3lnlaruaxm6lou0tj7i9de11f8t6kwf-8ghhzjg5o0lkwrx14t0t7pbmw \
> [::]:2377
> ```

thus, a non overlay network addr generated, any other nodes could not join cluster memberlist, it says:

> WARN[0022] 2016/10/25 17:22:00 [WARN] memberlist: Failed to resolve ::: too many colons in address ::
> 
> ERRO[0022] Failed to join memberlist [::] on retry: 1 error(s) occurred:

I am very confused.

**Comment by mavenugo** [comment]
cc @aaronlehmann @sanimej

**Comment by dperny** [comment]
having the exact same problem on my branch. i think the latest swarmkit vendoring broke it?

**Comment by dperny** [comment]
Passing `--listen-addr` fixes the problem.

**Comment by aaronlehmann** [comment]
Will be fixed by https://github.com/docker/swarmkit/pull/1698

**Comment by aluzzardi** [comment]
@TheBeeMan This has been fixed. Could you please confirm with the latest master, and if it happens again, re-open this issue?

Thanks!
