### ISSUE TITLE
docker build failed when filename is given with -f or --file option even if file present in PATH

### ISSUE THREAD

**Issue by dattatrayakumbhar04** [docker/docker#27738]
**Description**
docker build failed with an error "unable to prepare context: The Dockerfile (/home/cloud-user/dk) must be within the build context (/home/cloud-user/helper/)", when filename is given with -f or --file option.

file dk is already  in /home/cloud-user/helper/ folder

**Steps to reproduce the issue:**
1. Have a custom file present in directory "/home/cloud-user/helper/" named test
2. We are in /home/cloud-user directory
3.  start docker build  with "docker build -f test /home/cloud-user/helper/"

**Describe the results you received:**
Docker build failed with an error "unable to prepare context: The Dockerfile (/home/cloud-user/test) must be within the build context (/home/cloud-user/helper/)
However file is present in build context.

**Describe the results you expected:**
Docker should get build.

**Additional information you deem important (e.g. issue happens only occasionally):**
Always

**Output of `docker version`:**
[root@nfs-server cloud-user]# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
[root@nfs-server cloud-user]# docker info
Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 5
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-747269-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 403.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 44.02 GB
 Metadata Space Used: 1.438 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: nfs-server.cisco.com
ID: YCHJ:GOSU:POEO:MGF3:C3QV:ZWIR:T5ZK:POHY:XBQS:CH7O:RLVB:75AZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: dattatrayakumbhar04
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Instance of centOS is on Openstack

**Comment by duglin** [comment]
`docker build -f test /home/cloud-user/helper/` means the context is `/home/cloud-user/helper` so the Dockerfile (test) isn't in there - which means the error message is correct.  Try moving the 'test' file into the "helper" dir, add "helper/" to the -f flag, then it should work.

**Comment by dattatrayakumbhar04** [comment]
@duglin,
Yes its right, we should have test file in /home/cloud-user/helper/ and i have already kept the file in same directory.

[root@nfs-server cloud-user]# ls -l /home/cloud-user/helper/
total 12
drwxr-xr-x. 10 root root 4096 Oct 24 14:03 docker-credential-helpers
drwxr-xr-x.  3 root root 4096 Oct 24 13:42 src
-rw-r--r--.  1 root root   26 Oct 25 13:43 test

Sample of file of test : 
[root@nfs-server cloud-user]# cat /home/cloud-user/helper/test
FROM ubuntu
MAINTAINER dk


one more observation is:
if file is needed in provided PATH like /home/cloud-user/helper/  , i also needed to add it in current directory also, otherwise it will give an error like "unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /home/cloud-user/test: no such file or directory
"
It meas we need  file in two places, 
1. Current directory,
2. provided PATH

**Comment by duglin** [comment]
@dattatrayakumbhar04 the `PATH` plays no role here. You just need to make sure its in the "build context dir" (someplace - can be in a nested dir).
