### ISSUE TITLE
docker info should show dockerd userns configuration

### ISSUE THREAD

**Issue by domdom82** [docker/docker#27740]
**Description**

I am trying to configure a container differently depending on detected daemon features.
For this feature detection I am running `docker info` and grep for the feature in use.
This is a generic pattern, you could also use it for other features such as used storage backend or enabled security like seccomp or apparmor.

I have noticed that `docker info` gives no information about whether or not the daemon is running namespaced or not. There are three indicators at the moment

1. `/var/lib/docker/<uid>.<gid>` exists
2. `/etc/subuid` / `/etc/subgid` contain `dockremap` (weak: only if default is used)
3. docker log contains this line:  
 ```
 User namespaces: ID ranges will be mapped to subuid/subgid ranges of: dockremap:dockremap
 ```

**Describe the results you expected:**

I would expect `docker info` to print userns configuration if this feature is enabled.
e.g.
```
(...)
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
User Namespaces:
 enabled: true
 user: dockremap
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
(...)
```

Alternatively it could appear in the "Security Options" section.

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 8
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/165536.165536/aufs
 Backing Filesystem: extfs
 Dirs: 42
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.17-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); HEAD : ef7d0b4 - Thu Aug 18 21:18:06 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9 MiB
Name: whisk
ID: 2GG5:Y3O4:OYJW:PYDV:NN3G:AYU5:VJZD:XZU3:MFIN:LNNK:YWQW:GVGR
Docker Root Dir: /mnt/sda1/var/lib/docker/165536.165536
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 26
 System Time: 2016-10-25T13:52:24.728753253Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8

**Comment by justincormack** [comment]
Yes I noticed it the other day. I think adding `userns` in security options would be fine too.

You can work it out as docker info displays the root eg `/var/lib/docker/10000.10000` but it is not ideal.

cc @estesp

**Comment by domdom82** [comment]
@justincormack exactly. it's doable with parsing `/var/lib/docker` but it should be easier :-)

**Comment by estesp** [comment]
Agree that we should add this--has come up a few times. I will work in this unless someone else is interested.

**Comment by domdom82** [comment]
@estesp thanks for the quick fix!
