### ISSUE TITLE
"docker exec" zsh autocompletion doesn't do container name autocompletion if used with options

### ISSUE THREAD

**Issue by ensonik** [docker/docker#27744]
**To reproduce:**
```
# docker exec -ti <tab>
zsh: do you wish to see all 3886 possibilities (972 lines)?
```

**Expected result:**
List of started containers.

Note: Everything is OK when there are no options used in the command line. e.g.:
```
$ docker exec <tab>
determined_heyrovsky  7b4ec7cf2109  --      10 minutes, mystartedcontainer
```

**Comment by thaJeztah** [comment]
ping @sdurrheimer

**Comment by sdurrheimer** [comment]
@ensonik Please take a look at the following [comment](https://github.com/docker/docker/blob/master/contrib/completion/zsh/_docker#L41-L43)

Short-option stacking is not enabled by default, activating it could cause invalid tab-completion, more information in this [commit message](https://github.com/docker/docker/commit/402caa94d23ea3ad47f814fc1414a93c5c8e7e58)

**Comment by thaJeztah** [comment]
Thanks for explaining @sdurrheimer. I'll close this issue as it looks to be resolved, but feel free to continue the discussion

**Comment by ensonik** [comment]
Thanks for the update @sdurrheimer . That workaround works fine for me.

**Comment by mcornella** [comment]
Re: how to make option stacking work without bugs, maybe the [ls completion](https://github.com/zsh-users/zsh/blob/master/Completion/Unix/Command/_ls) can be used as a model since it has a similar CLI. I haven't investigated further, just mentioning in case it's useful.

**Comment by sdurrheimer** [comment]
@mcornella Most of `ls` options are boolean, some of them require a argument value as `next word`.
In our case, docker can receive argument values as `next word` or `same word with equal sign`, which is, IMO, responsible of the stacking completion issue.
