### ISSUE TITLE
better way to run docker on ec2. 

### ISSUE THREAD

**Issue by jpca999** [docker/docker#27757]
I'm new to the docker.  I develop my code on my local and push it on the GitHub. 

Then i got to ec2 and pull all of it with help of docker file. 

I'm developing the application on node.js using mean stack. 

Is there a better way to do it since I'm running on Ubuntu ( ec2 ) itself,  can I save the space by not pulling the ubuntu via docker  ?

Do I even need to install docker on ec2 ?

**Comment by unclejack** [comment]
This question is related to how Docker should be used. It doesn't seem to be an issue with Docker or any kind of technical problem.

This issue tracker is meant to be used for bug reports, feature requests and pull requests. This isn't a general support forum.

Could you discuss this one the Docker forums found at https://forums.docker.com/, please?

I'll close this issue now.
