### ISSUE TITLE
Port mapping not working in Windows10 (14931.rs_prerelease.160916-1700)

### ISSUE THREAD

**Issue by rayterrill** [docker/docker#27762]
**Description**

Port mapping not working in Windows10 (14931.rs_prerelease.160916-1700). This used to work unless I'm losing my mind, but doesn't work anymore. Docker run is successful, but no firewall rules are created and no port mapping appears to be created. It doesn't appear to matter whether this is in daemon or interactive mode. Docker port shows the port mapping.

**Steps to reproduce the issue:**
1. 14931.rs_prerelease.160916-1700
2. docker run --rm -d -p 4000:4000 jekyll

**Describe the results you received:**

PS C:\wip\Jekyll> docker run --rm -d -p 4000:4000 jekyll
1c267c5f5792216a610059dbd7dcbd58b3f26ee2eaf57661378c2fe7a4f0c85d
PS C:\wip\Jekyll> docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS
          NAMES
1c267c5f5792        jekyll              "cmd /S /C 'powers..."   49 seconds ago      Up 33 seconds       0.0.0.0:4000->4
000/tcp   clever_einstein
PS C:\wip\Jekyll> docker port clever_einstein
4000/tcp -> 0.0.0.0:4000
PS C:\wip\Jekyll> netstat -an

Active Connections

  Proto  Local Address          Foreign Address        State
  TCP    0.0.0.0:135            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:445            0.0.0.0:0              LISTENING
  TCP    0.0.0.0:2179           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING
  TCP    0.0.0.0:17500          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49664          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49665          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49666          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49667          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49690          0.0.0.0:0              LISTENING
  TCP    0.0.0.0:49705          0.0.0.0:0              LISTENING
  TCP    10.61.30.69:62927      0.0.0.0:0              LISTENING
  TCP    127.0.0.1:843          0.0.0.0:0              LISTENING
  TCP    127.0.0.1:6263         0.0.0.0:0              LISTENING
  TCP    127.0.0.1:17600        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:49787        127.0.0.1:62522        ESTABLISHED
  TCP    127.0.0.1:50106        127.0.0.1:50107        ESTABLISHED
  TCP    127.0.0.1:50107        127.0.0.1:50106        ESTABLISHED
  TCP    127.0.0.1:50108        127.0.0.1:50109        ESTABLISHED
  TCP    127.0.0.1:50109        127.0.0.1:50108        ESTABLISHED
  TCP    127.0.0.1:50112        127.0.0.1:50113        ESTABLISHED
  TCP    127.0.0.1:50113        127.0.0.1:50112        ESTABLISHED
  TCP    127.0.0.1:62522        0.0.0.0:0              LISTENING
  TCP    127.0.0.1:62522        127.0.0.1:49787        ESTABLISHED
  TCP    172.31.16.1:53         0.0.0.0:0              LISTENING
  TCP    172.31.16.1:139        0.0.0.0:0              LISTENING
  TCP    192.168.1.195:139      0.0.0.0:0              LISTENING
  TCP    192.168.1.195:49414    65.52.108.197:443      ESTABLISHED
  TCP    192.168.1.195:49415    131.253.34.252:443     ESTABLISHED
  TCP    192.168.1.195:49421    131.253.34.250:443     ESTABLISHED
  TCP    192.168.1.195:49422    131.253.34.232:443     ESTABLISHED
  TCP    192.168.1.195:51895    173.194.202.188:5228   ESTABLISHED
  TCP    192.168.1.195:51902    162.125.18.133:443     ESTABLISHED
  TCP    192.168.1.195:51911    52.84.18.134:443       CLOSE_WAIT
  TCP    192.168.1.195:51918    192.30.253.124:443     ESTABLISHED
  TCP    192.168.1.195:51926    199.59.148.82:443      ESTABLISHED
  TCP    192.168.1.195:51936    54.164.252.96:443      CLOSE_WAIT
  TCP    192.168.1.195:51962    65.52.108.182:443      ESTABLISHED
  TCP    192.168.1.195:52088    204.79.197.200:443     ESTABLISHED
  TCP    192.168.1.195:52089    204.79.197.200:443     ESTABLISHED
  TCP    192.168.1.195:52090    204.79.197.200:443     ESTABLISHED
  TCP    192.168.1.195:52092    104.125.197.56:443     ESTABLISHED
  TCP    192.168.1.195:52093    104.125.197.56:443     ESTABLISHED
  TCP    192.168.1.195:52095    74.125.199.189:443     ESTABLISHED
  TCP    192.168.1.195:52101    216.58.216.131:443     ESTABLISHED
  TCP    192.168.56.1:139       0.0.0.0:0              LISTENING
  TCP    [::]:135               [::]:0                 LISTENING
  TCP    [::]:445               [::]:0                 LISTENING
  TCP    [::]:2179              [::]:0                 LISTENING
  TCP    [::]:7680              [::]:0                 LISTENING
  TCP    [::]:17500             [::]:0                 LISTENING
  TCP    [::]:49664             [::]:0                 LISTENING
  TCP    [::]:49665             [::]:0                 LISTENING
  TCP    [::]:49666             [::]:0                 LISTENING
  TCP    [::]:49667             [::]:0                 LISTENING
  TCP    [::]:49690             [::]:0                 LISTENING
  TCP    [::]:49705             [::]:0                 LISTENING
  UDP    0.0.0.0:5050           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5353           _:_
  UDP    0.0.0.0:5355           _:_
  UDP    0.0.0.0:17500          _:_
  UDP    0.0.0.0:55819          _:_
  UDP    0.0.0.0:56127          _:_
  UDP    0.0.0.0:56501          _:_
  UDP    10.61.30.69:62927      _:_
  UDP    127.0.0.1:1900         _:_
  UDP    127.0.0.1:56810        _:_
  UDP    172.31.16.1:53         _:_
  UDP    172.31.16.1:137        _:_
  UDP    172.31.16.1:138        _:_
  UDP    172.31.16.1:1900       _:_
  UDP    172.31.16.1:2177       _:_
  UDP    172.31.16.1:56807      _:_
  UDP    192.168.1.195:137      _:_
  UDP    192.168.1.195:138      _:_
  UDP    192.168.1.195:1900     _:_
  UDP    192.168.1.195:2177     _:_
  UDP    192.168.1.195:56809    _:_
  UDP    192.168.56.1:137       _:_
  UDP    192.168.56.1:138       _:_
  UDP    192.168.56.1:1900      _:_
  UDP    192.168.56.1:2177      _:_
  UDP    192.168.56.1:56808     _:_
  UDP    [::]:5353              _:_
  UDP    [::]:5353              _:_
  UDP    [::]:5353              _:_
  UDP    [::]:5353              _:_
  UDP    [::]:5355              _:_
  UDP    [::]:55819             _:_
  UDP    [::1]:1900             _:_
  UDP    [::1]:56806            _:_
  UDP    [2601:1c2:1601:86a8:29e5:ff91:36fc:1b27]:2177  _:_
  UDP    [2601:1c2:1601:86a8:e905:c07a:ab36:18e1]:2177  _:_
  UDP    [fe80::2817:eec6:a7ee:c6dd%10]:1900  _:_
  UDP    [fe80::2817:eec6:a7ee:c6dd%10]:2177  _:_
  UDP    [fe80::2817:eec6:a7ee:c6dd%10]:56803  _:_
  UDP    [fe80::90fa:af71:afdf:1f24%4]:1900  _:_
  UDP    [fe80::90fa:af71:afdf:1f24%4]:2177  _:_
  UDP    [fe80::90fa:af71:afdf:1f24%4]:56804  _:_
  UDP    [fe80::e905:c07a:ab36:18e1%9]:1900  _:_
  UDP    [fe80::e905:c07a:ab36:18e1%9]:2177  _:_
  UDP    [fe80::e905:c07a:ab36:18e1%9]:56805  _:_

**Describe the results you expected:**

Should map port 4000:4000 in this instance.

**Additional information you deem important (e.g. issue happens only occasionally):**

Consistently fails to map.

**Output of `docker version`:**

PS C:\WINDOWS\system32> docker version
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9bece
 Built:        Sat Oct 22 22:35:05 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9bece
 Built:        Sat Oct 22 22:35:05 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**

PS C:\WINDOWS\system32> docker info
Containers: 8
 Running: 1
 Paused: 0
 Stopped: 7
Images: 13
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat nat null null transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14931 (14931.1000.amd64fre.rs_prerelease.160916-1700)
Operating System: Windows 10 Pro Insider Preview
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.907 GiB
Name: DESKTOP-JU1FBGD
ID: F4JJ:PLVE:IPBG:V5YD:5PVS:IOPM:FG2D:MJQO:OYDE:RAIR:DH6O:2N2L
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows10 (14931.rs_prerelease.160916-1700) on a SurfacePro 3.

**Comment by friism** [comment]
cc @JMesser81

I think this might be covered here: https://blogs.technet.microsoft.com/virtualization/2016/05/25/windows-nat-winnat-capabilities-and-limitations/

**Comment by rayterrill** [comment]
@friism Wow - that's a deep article. Are you referring specifically to the "Accessing internal endpoints directly from the Host" section? If not, can you point me in the right direction?

Here's what my networking looks like right this second:

Ethernet adapter vEthernet (HNS Internal NIC):

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::2817:eec6:a7ee:c6dd%10
   IPv4 Address. . . . . . . . . . . : 172.31.16.1
   Subnet Mask . . . . . . . . . . . : 255.255.240.0
   Default Gateway . . . . . . . . . :

Ethernet adapter VirtualBox Host-Only Network #2:

   Connection-specific DNS Suffix  . :
   Link-local IPv6 Address . . . . . : fe80::90fa:af71:afdf:1f24%4
   IPv4 Address. . . . . . . . . . . : 192.168.56.1
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Default Gateway . . . . . . . . . :

Not able to access the running container at 192.168.56.1 or 172.31.16.1 on the mapped port 4000.

**Troubleshooting output:**

PS C:\wip\Jekyll> Get-NetNat

Name                             : Hd2c1212b-33ff-4c55-8107-01b1b15f4b7c
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 172.31.16.1/20
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True

PS C:\wip\Jekyll> Get-VMSwitch

Name SwitchType NetAdapterInterfaceDescription
---- ---------- ------------------------------
nat  Internal

PS C:\wip\Jekyll> Get-NetIPAddress -InterfaceAlias "vEthernet (HNS Internal NIC)"

IPAddress         : fe80::2817:eec6:a7ee:c6dd%10
InterfaceIndex    : 10
InterfaceAlias    : vEthernet (HNS Internal NIC)
AddressFamily     : IPv6
Type              : Unicast
PrefixLength      : 64
PrefixOrigin      : WellKnown
SuffixOrigin      : Link
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : 172.31.16.1
InterfaceIndex    : 10
InterfaceAlias    : vEthernet (HNS Internal NIC)
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : 20
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

PS C:\wip\Jekyll> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
2009662e2c6c        nat                 nat                 local
5c444e047496        none                null                local

**Comment by jhowardmsft** [comment]
I'm closing this due to it being opened against pre-release. If this still occurs on latest fully-patched Windows, please open a new issue.
