### ISSUE TITLE
Short lived containers stdin close err

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#27760]
On master, when running a short-lived container, the daemon gets errors in the logs about not being able to close the stdin fifo.

For builds I frequently see:

```
ERRO[0026] error closing stdin: %+vfifo /proc/self/fd/20 was closed before opening
```

For `docker run` I see:

```
WARN[0010] failed to close stdin: %!v(MISSING)
```

I'm not sure why I'd get different errors here, may just be race conditions.

Ping @tonistiigi

**Comment by tonistiigi** [comment]
There doesn't seem to be an actual issue behind this, only logging in invalid cases.

There's a question if `fifo` pkg should return an error if fifo is called before it is actually opened from the other side. Docker atm doesn't expect it to be error and probably this is correct. Another way would be to open stdin fifo `O_RDWR` like it used to be so it is always open.

**Comment by thaJeztah** [comment]
@cpuguy83 @tonistiigi is this resolve by https://github.com/docker/docker/pull/27763?

**Comment by cpuguy83** [comment]
The output is better, but I'm not sure it's fixed. I'll leave up to @tonistiigi if you think we should track this as an issue.

**Comment by aaronlehmann** [comment]
If we keep this error, we should stop printing a stack trace. It makes the error look like a crash, adds noise, and I doubt the stack is useful here.
