### ISSUE TITLE
mounts behavior differs between 1.10.3 and 1.12

### ISSUE THREAD

**Issue by runcom** [docker/docker#27773]
Reproducer:

```
#!/bin/bash
set -ex
docker volume rm v1 || true
docker rm t1 t2 || true
docker volume create --name v1
docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
cat a.tar | docker cp - t1:/
cat b.tar | docker cp - t1:/
docker create --name t2 \
-v $(docker volume inspect -f '{{ .Mountpoint  }}' v1)/0:/mountdir \
-v $(docker volume inspect -f '{{ .Mountpoint  }}' v1)/1:/mountfile \
busybox cat /mountfile
docker start -a t2
docker rm -f t1
docker rm -f t2
docker volume rm v1
```

`a.tar` and `b.tar` are in [testfiles.zip](https://github.com/docker/docker/files/552765/testfiles.zip)

That used to work in 1.10.3:

```
10:47:06 [~] ./testbug.sh
+ docker volume rm v1
Error response from daemon: get v1: no such volume
+ true
+ docker rm t1 t2
t2
Failed to remove container (t1): Error response from daemon: No such container: t1
+ true
+ docker volume create --name v1
v1
+ docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
665a3fc2041c1c1faf6009eae6f8713b8ecbfdb897a410231b7254bb1947a02e
+ cat a.tar
+ docker cp - t1:/
+ cat b.tar
+ docker cp - t1:/
++ docker volume inspect -f '{{ .Mountpoint  }}' v1
++ docker volume inspect -f '{{ .Mountpoint  }}' v1
+ docker create --name t2 -v /var/lib/docker/volumes/v1/_data/0:/mountdir -v /var/lib/docker/volumes/v1/_data/1:/mountfile busybox cat /mountfile
c850d9083be7d0202e649c119fb84d608e08782dcaafa61b14be0cebbde96b2f
+ docker start -a t2
FROM busybox
ENV name value
ENV name=value
ENV name=value name2=value2
ENV name="value value1"
ENV name=value\ value2
ENV name="value'quote space'value2"
ENV name='value"double quote"value2'
ENV name=value\ value2 name2=value2\ value3
ENV name="a\"b"
ENV name="a\'b"
ENV name='a\'b'
ENV name='a\'b''
ENV name='a\"b'
ENV name="''"
# don't put anything after the next line - it must be the last line of the
# Dockerfile and it must end with \
ENV name=value \
    name1=value1 \
    name2="value2a \
           value2b" \
    name3="value3a\n\"value3b\"" \
        name4="value4a\\nvalue4b" \% 
```

While on 1.12.x we get:

```
[root@centos ~]# ./testbug.sh
+ docker volume rm v1
Error response from daemon: Unable to remove volume, volume still in use: remove v1: volume is in use - [4fe62ced403a634b3156e8459ace181020acae8f4cff4851902a6120c3aa3f31]
+ true
+ docker rm t1 t2
t1
t2
+ docker volume create --name v1
v1
+ docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
dc6b0555e82c7828ed2553b0e580145f35e4bde074bdcb0cd672e9a7877c3b32
+ cat a.tar
+ docker cp - t1:/
+ cat b.tar
+ docker cp - t1:/
++ docker volume inspect -f '{{ .Mountpoint }}' v1
++ docker volume inspect -f '{{ .Mountpoint }}' v1
+ docker create --name t2 -v /var/lib/docker-latest/volumes/v1/_data/0:/mountdir -v /var/lib/docker-latest/volumes/v1/_data/1:/mountfile busybox cat /mountfile /
afb9161809ab7b4cc4b9350f0f1a1e2e69dc4136b1bc125eb062c1d93a16c427
+ docker start -a t2
cat: read error: Is a directory
cat: read error: Is a directory
```

/cc @cpuguy83

**Comment by cpuguy83** [comment]
More likely `docker cp` changed, I think?

**Comment by runcom** [comment]
> More likely docker cp changed, I think?

or maybe it's a bug there?

**Comment by runcom** [comment]
@cpuguy83 all I can see right now is that the docker cp'ed files end up into:
```sh
# I'm under /var/lib/docker
[root@centos lib]# find . | grep subdir
./docker-latest/overlay/bce480817519440ed692adb906b3fed1b23ec638d214c6955e377239be792411/upper/.imagebuilder-transient-mount/0/subdir
./docker-latest/overlay/bce480817519440ed692adb906b3fed1b23ec638d214c6955e377239be792411/upper/.imagebuilder-transient-mount/0/subdir/file2
```
Instead I've expected to end up under `/var/lib/docke/voloumes/....`

**Comment by cpuguy83** [comment]
@runcom Oh my! It sounds like the volumes aren't getting mounted for some reason on cp.

**Comment by runcom** [comment]
> @runcom Oh my! It sounds like the volumes aren't getting mounted for some reason on cp.

can be because of some mount options like rprivate and such? can be a kernel issue maybe

**Comment by cpuguy83** [comment]
Hmm I don't think so.
Since the daemon is supposed to be doing this essentially:

1. mount container rw layer
2. mount volumes on container rw layer
3. perform cp
4. unmount all the things

**Comment by runcom** [comment]
yeah, 1.10.3 works instead so it can't be what I said

**Comment by runcom** [comment]
@cpuguy83 were you able to reproduce?

**Comment by runcom** [comment]
weirdly enough... I can only reproduce this on CentOS (building official docker 1.12.1 there also) while I cannot repro on fedora...

**Comment by runcom** [comment]
seems like related to devicemapper - if I run the reproducer on fedora+devmapper I get that error, with overlay no error. Will test on CentOS.

**Comment by cpuguy83** [comment]
Haven't tried yet.

**Comment by runcom** [comment]
more debugging:

* overlayfs works correctly. It populates the volume under `/var/lib/volumes`. if you restart the daemon to use devmapper it will also work on devmapper, but...
* if you rm the volume created with overlay and start the reproducer again with devmapper, then everything fails as in the first comment.

marking this as a devmapper issue.

**Comment by runcom** [comment]
@cpuguy83 I sadly found out that your PR https://github.com/docker/docker/pull/22506/commits/85988b33d299697f410a3a92db5d537fdbee955b broke this :disappointed: by reverting it everything will work fine in devmapper as well.

**Comment by cpuguy83** [comment]
@runcom Is this before or after https://github.com/docker/docker/pull/27609?

**Comment by runcom** [comment]
@cpuguy83 I'll test it out and let you know

**Comment by runcom** [comment]
@cpuguy83 reverting #27609 doesn't help, I can only make this work again by reverting the whole https://github.com/docker/docker/pull/22506/commits/85988b33d299697f410a3a92db5d537fdbee955b directly

**Comment by thaJeztah** [comment]
Since https://github.com/docker/docker/pull/22506 already falls back if pivot_root doesn't work, should we disable it on devicemapper, and keep using it for other drivers?

**Comment by rhvgoyal** [comment]
I think we should first get to the bottom of the issue and see what's broken. Disabling it on devicemapper should come up only if there is no way to fix it on devicemapper.

**Comment by cpuguy83** [comment]
Using `chrootarchive` for `docker cp` is probably overkill, but... would definitely like to see what is causing the issue.

Maybe in 1.14 we can work towards using an actual container to handle extraction rather than what we are currently doing.

**Comment by runcom** [comment]
I would find out why this is broken though, may be something related to mount propagation, I'm still debugging this.

**Comment by thaJeztah** [comment]
> I think we should first get to the bottom of the issue and see what's broken. Disabling it on devicemapper should come up only if there is no way to fix it on devicemapper.

Yes, I definitely agree; earlier discussion headed towards reverting that change, and I wanted to prevent completely reverting if it's only causing issues on dm. :smile:

**Comment by runcom** [comment]
This is definitely an issue with `pivot_root` and volume mounts (maybe propagation) (@cpuguy confirmed that by using the old chroot mechanism doesn't trigger this issue)

**Comment by runcom** [comment]
@cpuguy83 found out that https://github.com/docker/docker/blob/master/pkg/chrootarchive/chroot_linux.go#L34 is causing this issue apparently.

**Comment by cpuguy83** [comment]
@rhvgoyal If we change https://github.com/docker/docker/blob/master/pkg/chrootarchive/chroot_linux.go#L34 just do an `rbind` (vs `bind` that `MakePrivate` is doing) it seems to work fine.
Curious why it's different on different kernels.

**Comment by runcom** [comment]
@tonistiigi do you happen to understand what's happening here?

**Comment by rhvgoyal** [comment]
difference betwee `rbind` and `bind` is that rbind is recursive. That is, if there are any mounts underneath `path` all these mounts will not be visible for the simple case of `bind`. But if you do `rbind`, these mounts will still be available.

**Comment by cpuguy83** [comment]
@rhvgoyal Right, but I'm wondering why this doesn't just always fail.

**Comment by rhvgoyal** [comment]
@cpuguy83  Is there a single command line I can run to reproduce the problem. How are you reproducing this issue.

**Comment by rhvgoyal** [comment]
In the case of pivot_root() in libcontainer, we are bind mount new rootfs dir first, then doing all the volume mount inside that new directory and then doing pivot_root(). So that means that even if we do just
bind mount of "path", it works because we are not relying on any existing mount points and all new volumes mount points will be created afterwards.

**Comment by cpuguy83** [comment]
@rhvgoyal What I mean is, this works fine in docker4mac, does not work on centos.
I have a patch prepared to do `rbind` as that seems correct, just strange that we're seeing differences on different distros.

**Comment by rhvgoyal** [comment]
@cpuguy83 I will be little skeptical of doing `rbind`. That means any existing mounts under "path" become visible.

I am still trying to wrap my head around, what's the basic problem. Once I understand that, we can try to figure out why that problem happens in certain platform and why not any other platform.

**Comment by cpuguy83** [comment]
@rhvgoyal Issue seems to be from:

docker cp to container -> mount rootfs -> mount volumes -> setup pivot -> pivot -> extract archive

Where in `setup pivot` the volume mounts get lost when we bind on the resolved rootfs path.

**Comment by rhvgoyal** [comment]
@cpuguy83 Ok. So simple bind mount masked out existing mounts under "path". And "rbind" will take care of that. I guess it is fine. 

Other way could be to do what libcontainer is doing. Do the bind mount of rootfs first, then do volume mounts under "path" and then do pivot_root(). But that's more work.

**Comment by cpuguy83** [comment]
Yeah, that's a lot more work.
I think we could change this up by running an actual container rather than doing all this later on.
New package `containerarchive`.

**Comment by rhvgoyal** [comment]
BTW, if I do simple copy of a file, it seems to work. So there is some correlation with tar too? I did following.

$ docker volume create --name v1
$ docker create -ti --name t1 -v v1:/foo busybox sh
$ docker cp foo.txt t1:/foo/

Now go to /var/lib/docker/ dir and do `find . -name foo.txt` and it shows up under volume v1.

That means file got copied in the volume as expected. And that means volume was visible and not got masked out. 

I am testing with docker 1.13-dev on fedora 24. And if I run runcom's script, I can see the problem. So why that's the case. If mounts are being masked always, why above simple copy is working.

**Comment by runcom** [comment]
@rhvgoyal I think your example is not going to work as you're copying a text file as opposed to copying from a tar steam (like my reproducer in the first comment).

**Comment by runcom** [comment]
Your simple copy works because it's not going through the pivot_root where extracting from a tar archive inside the Docker daemon (and also in a new mount namespace).

**Comment by rhvgoyal** [comment]
@runcom, I think even simple copy is going through pivot_root. Difference is that we are doing pivot_root on /foo/ and not on /. And /foo itself is a mount point and there are no submounts underneath it. Even if there were submounts, it would have been fine as MakePrviate() would not have done anything is path is already a mount point.

**Comment by edsantiago** [comment]
docker-1.12.3-8.el7 is failing, but not with `is a directory`:

    + docker start -a t2
    cat: can't open '/mountfile': Permission denied

Works with `setenforce 0`. `/var/log/audit.log` shows:

    type=AVC msg=audit(1479335994.774:10015): avc:  denied  { read } for  pid=2155 comm="cat" name="1" dev="vda1" ino=83898606 scontext=system_u:system_r:svirt_lxc_net_t:s0:c496,c738 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file

**Comment by rhvgoyal** [comment]
@rhatdan selinux issue?

**Comment by rhatdan** [comment]
Is this overlay?  Where is mountfile coming from?  Looks like it is labeled incorrectly.

**Comment by edsantiago** [comment]
Thinpool. See script at comment 0 for details. The important part (IIUC) is that the bind mount is happening through the filesystem:

    # docker volume inspect -f '{{ .Mountpoint  }}' v1
    /var/lib/docker/volumes/v1/_data
    # docker create --name t2 -v /var/lib/docker/volumes/v1/_data/0:/mountdir -v /var/lib/docker/volumes/v1/_data/1:/mountfile busybox cat /mountfile
    eb20a8e1f130356e3ab38672514d2747fcdde12e983e1a54124ec20a5ff29603
    # docker start -a t2
    cat: can't open '/mountfile': Permission denied

**Comment by rhatdan** [comment]
```
# docker create --name t2 -v /var/lib/docker/volumes/v1/_data/0:/mountdir -v /var/lib/docker/volumes/v1/_data/1:/mountfile*:Z* busybox cat /mountfile
```

**Comment by edsantiago** [comment]
That works (`:Z`) but the point is this is a regression: 1.10 does not need the `:Z`. I'm not qualified to say how important that is.

**Comment by cpuguy83** [comment]
@edsantiago Can you do `ls -Z /var/lib/docker/volumes/v1/_data`?

**Comment by cpuguy83** [comment]
btw, we should take this to a new issue, since this is something completely different.

**Comment by rhatdan** [comment]
@edsantiago if 1.10 did not need it then that was the bug.  This content should not be accessible unless it was labeled correctly.  We might have labeled /var/lib/docker/volumes differently, but I don't think so.  Some how the 1.10 version got a label on it that was writeable by the processes within the container.  The 1.12 version is the correct behaviour.  We don't want a container process to write to any content under /var/lib/docker by default.  We don't want them to be able to read most content under this directory either.

The default label for most content under /var/lib/docker is container_var_lib_t.  The following command shows you all the access available to container processes, container_t, on files labeled container_var_lib_t.

```
# sesearch -A -s container_t -t container_var_lib_t -C -c file
#
```

IE None.
