### ISSUE TITLE
Aufs image size does not become small after deleting files.

### ISSUE THREAD

**Issue by andyxning** [docker/docker#27776]
the docker images output of `nginx:latest` is: 
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
nginx               latest              a5311a310510        13 days ago         181.4 MB
```

the output of  `docker run nginx /bin/ls -lh /usr/sbin/nginx /usr/sbin/nginx-debug` is 
```
-rwxr-xr-x 2 root root 1.1M Oct 11 15:56 /usr/sbin/nginx
-rwxr-xr-x 2 root root 1.2M Oct 11 15:56 /usr/sbin/nginx-debug
```

It shows that `nginx` and `nginx-debug` will added up to **2.3M**. So, if we delete these two files in a child image, the image size will be less than `181.4MB` of `nginx:latest`. However, this is not the truth. :(

I have a Dockerfile about like this:
```
FROM nginx:latest

RUN rm /usr/sbin/nginx /usr/sbin/nginx-debug
```

run `docker build . --tag demo:demo` and we get the **demo:demo** image. 

`docker images -a` shows something like this, the **demo:demo** and **nginx:test** image is of the same size. 

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
demo                demo                f137bcac8392        4 seconds ago       181.4 MB
nginx               latest              a5311a310510        13 days ago         181.4 MB
```

we use AUFS as the storage driver with docker 1.12.0. Does this related to AUFS?

**Comment by thasmo** [comment]
This is not how Docker images work. Once files have been added (commited) to an image, they can't be removed i.e. the image's size can't be decreased. This has to do with how Docker images are built; using layers (of changes).

**Comment by andyxning** [comment]
@thasmo i think all unionfs that docker utilize will behave like what you have said.

**Comment by unclejack** [comment]
This is the expected and desired behavior for the code, as @thasmo has also stated above.

Each layer of an image builds on top of the previous layer:
a->b->c->d

`docker run` sets up a new layer which can be modified without affecting the image itself. You can simply think of this as:
a->b->c->d->container1
a->b->c->d->container2
Any modifications made to container1 or container2 won't affect the other container, nor any of the layers of the image.

Please take a look at the documentation at https://docs.docker.com/ to understand this better.

Please ask similar questions on https://forums.docker.com/. This issue tracker is for bug reports, feature requests and pull requests. This isn't a support forum.

You're welcome to continue the discussion on this issue. I'll close this now as the question has been answered and this isn't a Docker bug.
