### ISSUE TITLE
Not able to start docker from VDI

### ISSUE THREAD

**Issue by Gajanand1986** [docker/docker#27787]
I am using VDI, I have installed docker toolbox on my VDI. Now when I am starting the docker terminal I am getting following error 

_Starting "default"...
(default) Check network to re-create if needed...
This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
Looks like something went wrong in step 'Checking status on default'... Press an
y key to continue..._

Since I am on VDI so I am not able to go to BIOS. Can some one please help to understand how we can enable the Virtualization.

Looking forward for your help.
Thanks in advance.

**Comment by unclejack** [comment]
This isn't a supported setup. VT-X or AMD-v are required to run the VM for Docker.

Please take a look at the documentation to learn more: https://docs.docker.com/docker-for-windows/troubleshoot/#/hyper-v

The simplesst thing you can do is to request a Linux VM or use a dedicated machine for this.

I'll close this issue now as there's no way to get around this technical limitation. VT-X or AMD-v is required to get the Hyper-V VM to run.

Please feel free to continue the discussion. There's no need to open another issue.
