### ISSUE TITLE
Docker run with --blkio needs to change help message and it accepts 0 value

### ISSUE THREAD

**Issue by dattatrayakumbhar04** [docker/docker#27798]
**Description**
Docker run --help command has be low options, 
      --blkio-weight value          Block IO (relative weight), between 10 and 1000
      --blkio-weight-device value   Block IO weight (relative device weight) (default [])
  -c, --cpu-shares int              CPU shares (relative weight)
1. Does all wight should be integer.?
2. blkio-weight accepts 0 also. Help message shows that it should be in range 10-1000
3. If 0 is default then in help, we should show default value.

**Steps to reproduce the issue:**
1. Check docker run --help  
2. Create container with blkio weight as 0

**Describe the results you received:**
1. Docker run --help command has below options related to blkio weight
      --blkio-weight value          Block IO (relative weight), between 10 and 1000
      --blkio-weight-device value   Block IO weight (relative device weight) (default [])
2. docker run --blkio 0 busybox executed successfully.

**Describe the results you expected:**
1. Docker run --help command should show blkio-weight value as Int as weight is Int and range is between 10-1000.
      --blkio-weight int         Block IO (relative weight), between 10 and 1000
      --blkio-weight-device int   Block IO weight (relative device weight) (default [])
2. docker run --blkio 0 busybox.
  As blkio range is out of 10-1000, we should get proper error message saying " Range of blkio weight is from 10 to 1000"
1. If 0 is default value then we should see default value in docker run --help

**Output of `docker version`:**

Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
[root@nfs-server cloud-user]# docker info
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 2
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-747269-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 209.1 MB
 Data Space Total: 107.4 GB
 Data Space Available: 41.06 GB
 Metadata Space Used: 1.069 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: nfs-server.cisco.com
ID: YCHJ:GOSU:POEO:MGF3:C3QV:ZWIR:T5ZK:POHY:XBQS:CH7O:RLVB:75AZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by dattatrayakumbhar04** [comment]
![image](https://cloud.githubusercontent.com/assets/21226676/19742408/8fc7e80e-9be2-11e6-938c-191cacdbbf40.png)

**Comment by milindchawre** [comment]
#dibs
