### ISSUE TITLE
Copy/Pasting into PowerShell prompt running in Windows Container in interactive mode has 50 character limit?

### ISSUE THREAD

**Issue by rayterrill** [docker/docker#27793]
**Description**

When launching a Windows container in Server2016 and running a powershell prompt (docker run --rm -it microsoft/windowsservercore powershell), it appears you can only paste a max of 50 characters at a time into the running container (i.e. pasting something like "(New-Object System.Net.WebClient).DownloadFile('http://mirrors.jenkins-ci.org/windows-stable/latest', 'Jenkins.zip')" will only result in "(New-Object System.Net.WebClient).DownloadFile('ht" actually making it into the container, so you have to copy/paste in multiple chunks.

This does not appear to happen if you use cmd as opposed to Powershell.

**Steps to reproduce the issue:**
1. Launch container in interactive mode with a powershell prompt: docker run --rm -it microsoft/windowsservercore powershell
2. Paste a large amount of text: i.e. (New-Object System.Net.WebClient).DownloadFile('http://mirrors.jenkins-ci.org/windows-stable/latest', 'Jenkins.zip')

**Describe the results you received:**

Only 50 characters of the pasted input are received "(New-Object System.Net.WebClient).DownloadFile('ht"

**Describe the results you expected:**

The entirety of the pasted content should be received in the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens every time.

**Output of `docker version`:**

PS C:\Windows\system32> docker version
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

**Output of `docker info`:**

PS C:\Windows\system32> docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 27
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 6 GiB
Name: POPDOCKER1
ID: KS2Q:ORLC:HZR3:UAI5:YMOB:NYND:JMM6:CSBG:E5YO:GPJ5:4E42:4GWU
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Server2016 running in VMWare VM.

**Comment by friism** [comment]
I see this too. it works fine with `cmd` though. cc @jhowardmsft

**Comment by jhowardmsft** [comment]
I suspect this is most likely a PS bug rather than anything in docker. I'll start an email thread internally, but I don't think there's a lot I can do on this issue here.

**Comment by rayterrill** [comment]
@jhowardmsft Ok. This doesn't happen in normal PowerShell - only PowerShell WITHIN a Docker container.

**Comment by jhowardmsft** [comment]
Yes, I can repro. I'll follow up internally with the PS and console folks.

**Comment by rayterrill** [comment]
Thanks @jhowardmsft!

**Comment by jhowardmsft** [comment]
I'm going to close this issue here. It's being tracked internally via OS#9535413.

**Comment by jhowardmsft** [comment]
It's PSReadLine. See https://github.com/lzybkr/PSReadLine/issues/460

**Comment by dhirschfeld** [comment]
This has been closed as a dup of  lzybkr/PSReadLine#460, however in that issue @lzybkr states:
> *At any rate, I think it's obvious there's nothing I can do to fix this in PSReadLine, but if someone finds a workaround, then that'd be great.*

...so if the underlying issue *isn't* a PSReadline problem could this issue please be reopened and investigated.

Note: I've posted the same in PowerShell/PowerShell#5501 which was also closed as a dup of lzybkr/PSReadLine#460. I'm not sure myself if the underlying problem is with moby or powershell but since it is a real and significant problem for users it would be great if it could be investigated further.
