### ISSUE TITLE
wishlist item: add --prefix to network 

### ISSUE THREAD

**Issue by teodorescuserban** [docker/docker#27799]
Hi.

I was wondering what do you guys say about adding an additional option named `--prefix` to the network creation so that networks segments assigned automatically from global to be smaller and hence to be able to have more than 30ish networks.

I do have the `--subnet` option, the problem is that it would mean to hardcode a specific subnet and therefore encounter possible conflicts.

Ideas?

Thanks!

**Comment by teodorescuserban** [comment]
(I am referring strictly to the default bridge driver for now)

**Comment by aboch** [comment]
I think you are asking for the same feature requested in https://github.com/docker/docker/issues/21776#issuecomment-206133109

**Comment by teodorescuserban** [comment]
indeed, @aboch ! Sorry for not finding it.

**Comment by aboch** [comment]
@teodorescuserban I was not actually suggesting to close your issue though, just wanted to understand if it was the same request
Maybe we should ask the linked issue's submitter to change the description to reflect the feature request.

**Comment by teodorescuserban** [comment]
Thank you, I understood.
I closed it because indeed it looks the same.

Basically, I am happy with the autoselect algorithm, I didn't encountered network conflicts so far (but a bit worried) and I need more networks than the autoselect algorithm can provide with the default prefix (/16).
