### ISSUE TITLE
No networking in some containers when spawned at high rate

### ISSUE THREAD

**Issue by rawouter** [docker/docker#27808]
**Description**

When spawning container at high rate in network mode bridge, some containers will not have networking connectivity.

**Steps to reproduce the issue:**

1. Created a network with /16 address space, in bridge mode
2. Spawn container at high rate and try to access network (ping)

I can reproduce the issue with the following script, some container image work better but will fail at some point. Also, I can not reproduce the issue in host network mode.

```
for num in range {1..300}
do
        docker run --network taskers --rm  ubuntu:14.04 sh -c "ping -c 1 173.36.21.105; arp -n; ifconfig" | tee output_$num.txt &
done
```

**Describe the results you received:**

About 1% of the container will fail without networking.
Here some command outputs taken from the script above:

```
PING 173.36.21.105 (173.36.21.105) 56(84) bytes of data.
From 173.77.2.18 icmp_seq=1 Destination Host Unreachable

--- 173.36.21.105 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

Address                  HWtype  HWaddress           Flags Mask            Iface
173.77.0.1                       (incomplete)                              eth0

eth0      Link encap:Ethernet  HWaddr 02:42:ad:4d:02:12
          inet addr:173.77.2.18  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::42:adff:fe4d:212/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:14 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:438 (438.0 B)  TX bytes:1072 (1.0 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:112 (112.0 B)  TX bytes:112 (112.0 B)

X bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

**Describe the results you expected:**

No network failure, ping should go through, arp should resolve.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue only occur for 1% of the pods when the system is under load, spawning and deleting lots of containers.
It doesn't occur in host network mode.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7a86f89
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7a86f89
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 284
 Running: 113
 Paused: 0
 Stopped: 171
Images: 30
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: selinux
Kernel Version: 4.7.3-coreos-r1
Operating System: CoreOS 1192.2.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.43 GiB
Name: pink-node-01
ID: D6TN:CC4O:MEWN:5IY4:ZOIO:OGKZ:AWPG:ZN5B:7EM6:J3JM:U6G2:6E3M
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

We are running on CoreOS alpha (1192.2.0)

**Comment by thaJeztah** [comment]
It looks like you're running the CoreOS fork of docker; https://github.com/coreos/docker/commit/7a86f89. Can you report this in the CoreOS issue tracker, because we cannot provide support for those builds here (that code is not in the official 1.12.1 codebase; https://github.com/docker/docker/commit/23cf638307f030cd8d48c9efc21feec18a6f88f8 )
