### ISSUE TITLE
docker swarm does not update images when it is a mode global

### ISSUE THREAD

**Issue by fuentecilla86** [docker/docker#27811]
docker version

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
afuentes@chimera-swarm-dev-db-01:~$ sudo docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
```

I have declared a service with mode global and with a constraint to run it only in two servers (my cluster runs in 3 servers). When I try to update as following:

```
sudo docker service update --image $IMAGE:$TAG $SERVICE
```

**The service is not updated.**

If I do it with in "replicas" mode it works perfectly.

Thank you in advance.

**Comment by BretFisher** [comment]
I can confirm this is an issue on 1.12.0-1.12.3 and looks to be fixed in https://github.com/docker/swarmkit/pull/1570 which is planned for 1.13

**Comment by thaJeztah** [comment]
Just to confirm; if you update the service, are you changing the actual name/tag of the image, or is the name/tag of the image exactly the same as before?

**Comment by BretFisher** [comment]
Changing tag. The global service will create fine with constraints in place, but when running update, it won't actually change the image to the new tag. If constraints aren't used with initial create, it works as expected.

**Comment by aaronlehmann** [comment]
@BretFisher: I think you're right that docker/swarmkit#1570 fixes this. The problem in 1.12.x is that Docker tries to update the tasks one at a time, but because of the constraints, some of the tasks can never start, and this blocks the update.

I'll close this since the issue is believed to be fixed on the master branch.
