### ISSUE TITLE
Unable to run images containing a 'slash' in the name locally

### ISSUE THREAD

**Issue by bsodmike** [docker/docker#27826]
**Description**

Earlier today, I attempted to perform a `docker build` for an image that looked like `company/app-name` and this failed with the error stating that image could not be located, even though `docker images` clearly showed it was there.

This was resolved via passing the `--pull` flag to `docker build`, which as the man details show:

> --pull=false                    Always attempt to pull a newer version of the image

However, the same issue presented itself when attempting to run the container.
This issue https://github.com/docker/docker/issues/13331 refers to this as well.

**Steps to reproduce the issue:**

Easy &mdash; attempt to run an image that has a slash within the image name, example `company/app-name`

**Describe the results you received:**

Error staging the image could not be found, even though `docker images` showed it was there.  Removing the '/' from the image name fixed the issue.

**Describe the results you expected:**

It should allow running images with a slash in the image name.  Not assume that it needs to be pulled-down.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
Images: 74
Server Version: 1.9.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 80
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.19.0-73-generic
Operating System: Ubuntu 15.04
CPUs: 2
Total Memory: 1.954 GiB
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

DigitalOcean droplet with Ubuntu 15.04 with kernel  [`3.19.0-73-generic`](http://packages.ubuntu.com/trusty/kernel/linux-image-3.19.0-73-generic)

**Comment by justincormack** [comment]
Hi this works fine for me, eg 

```
docker tag alpine justin/image
docker run justin/image ls
```

Can you provide a more complete reproduction? You are using a very old version of docker, I don't think this should make a difference, but perhaps you can also try on a recent build?

**Comment by bsodmike** [comment]
Hi @justincormack thanks for spotting that; I'll check later this weekend, but I believe it's due to incorrectly installing `lxc-docker` package in Ubuntu LTS rather than `docker-engine`?

**Comment by bsodmike** [comment]
Just verified this by installing `docker-engine` on in Linux.  Apologies!

```
root@docker-engine-sgp-test:~# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```
