### ISSUE TITLE
Volume mount name incorrect and different from specified

### ISSUE THREAD

**Issue by phosphre** [docker/docker#27825]
**Description**

**Steps to reproduce the issue:**
1. docker run -it -v /opt/b:/opt/b centos bash

**Describe the results you received:**
[root@a7a1bbd07205 /]# ls /opt
b:

**Describe the results you expected:**
[root@a7a1bbd07205 /]# ls /opt
b

**Additional information you deem important (e.g. issue happens only occasionally):**
reproducible.  and I've just noticed also interior mounting eg:

host#  docker run -it -v /opt/d:/opt/c centos bash
[root@a79fcf1c42f7 /]# ls /opt
d:
[root@a79fcf1c42f7 /]# cd /opt/d
bash: cd: /opt/d: No such file or directory
[root@a79fcf1c42f7 /]# cd /opt/d:
[root@a79fcf1c42f7 d:]# ls -la
total 0
drwxr-xr-x. 3 root root 16 Oct 27 11:56 .
drwxr-xr-x. 3 root root 15 Oct 27 11:56 ..
drwxr-xr-x. 3 root root 14 Oct 27 11:56 opt
[root@a79fcf1c42f7 d:]# cd opt
[root@a79fcf1c42f7 opt]# ls -la
total 0
drwxr-xr-x. 3 root root 14 Oct 27 11:56 .
drwxr-xr-x. 3 root root 16 Oct 27 11:56 ..
drwxr-xr-x. 2 root root  6 Oct 27 11:56 c
[root@a79fcf1c42f7 opt]# cd c
[root@a79fcf1c42f7 c]# ls -la
total 0
drwxr-xr-x. 2 root root  6 Oct 27 11:56 .
drwxr-xr-x. 3 root root 14 Oct 27 11:56 ..
[root@a79fcf1c42f7 c]# pwd
/opt/d:/opt/c

Seems to only happen when the directory name has only one character.

**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
Containers: 9
 Running: 0
 Paused: 0
 Stopped: 9
Images: 2
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-67110529-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.158 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.66 GB
 Metadata Space Used: 2.757 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 489 MiB
Name: strontium
ID: 4AX7:CZJU:3DFN:GVFY:WZN7:34QR:FOOV:MU7K:R7NZ:TVYF:XIY2:L7SW
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical is a macbook pro, running latest vagrant/vbox centos 7.2 VMs which are acting as the docker host in this context.

**Comment by cpuguy83** [comment]
Not sure what to say here other than the version of docker you are using is quite old and also not the official build from get.docker.com.
Can you try with a more recent version from the official packages?

**Comment by phosphre** [comment]
good point - it was the latest from centos' yum repo, weirdly from yum -y install.  Using sudo wget -qO- https://get.docker.com/ | sh gets me 1.12.3 and this work.  Sorry should have checked that.
