### ISSUE TITLE
Docker service dependencies

### ISSUE THREAD

**Issue by mostolog** [docker/docker#27836]
Hi

_I'm almost sure this might be already discussed, but I haven't been able to find an issue with keywords like: service depends, dependency, order, precedence. Sorry for any inconvenience._

**Is there any plan to add something like --startorder, --depends, --after... to services to (https://github.com/docker/docker/issues/25303) in order to sequence service deployments?**
I have readed about using swarm mode+compose or bundled applications, but I haven't played with it yet.

Actually I'm having an issue with nginx-ELK caused by "container boot order".

Nginx upstream configuration requires hostname to be resolved on start, otherwise application stops. http://stackoverflow.com/questions/32845674/setup-nginx-not-to-crash-if-host-in-upstream-is-not-found

If any of the main (non backup) upstream servers can't be resolved, nginx won't start. So, to make it run, I have to start all kibana (proxied service) instances. It doesn't matter if I add 127.0.0.11 as DNS resolver, as long as the container is not run, name won't be registered.

IMHO nginx shouldn't crash when upstream is down, but probably there are other scenarios when this feature is also required.
With current behaviour, nginx service is launched several times, with their respective impact on system, until all upstream server names can be resolved.

As I'm sure I'm not the only one, neither the first having this issue, I'll like to ask how you solved this using swarm mode, and asking for the inclusion of such feature

Thanks.

**Comment by thaJeztah** [comment]
I don't think this is on the roadmap. Adding such a feature quickly leads to a lot of complexity.

- what is "after"? after deploying the service? after the containers where started? the containers are _running_? .._healthy_? All tasks/containers, or is a single one sufficient?
- when scaling a service that another service depends on, should we stop and redeploy the dependent service?
- etc.

In addition, services should be designed to be resilient against failures; not justat start, but during their entire lifecycle; what happens if a node goes down? A network connection fails? DNS is not working?

Such things cannot be handled by docker / swarm, but should be handled by the application running in the container. Failures _will_ happen, so it's best practice to take them into account when designing your application.

**Comment by duglin** [comment]
+1 to @thaJeztah. The entire before/after notion with things that can be restarted, or die, at any time is always a bit weird to me.

**Comment by mostolog** [comment]
@thaJeztah totally agree.

**Comment by thaJeztah** [comment]
Thanks @mostolog

**Comment by mostolog** [comment]
IIUC, this is now possible with docker deploy+healthchecks, isn't it?

**Comment by Yogu** [comment]
I'd like to propose an alternative way to depenencies, borrowed from systemd's dependency management ([socket activation](http://0pointer.de/blog/projects/socket-activation.html)):

Dependencies specified by `depends` do not prevent a container from being started, but they make sure that DNS names can be resolved and the ip packets sent to that service are buffered. Once the service is up and has opened a server on that port on its own, the buffered packets are sent to the service. One could even buffer the packets when a service is temporarirly down.

I know that this opens new problems for when services are down a long time and buffers overflow, but it would solve the problems outlined by @thaJeztah.

**Comment by coding2012** [comment]
@mostolog What did you end up doing to solve your dependency issue. I too have plans on using nginx hostnames that may not yet exist depending on the service deployment. I definitely want to have nginx "inside" the docker infrastructure rather than external.

**Comment by mostolog** [comment]
Hi.

For nginx I don't use upstream anymore but a variable:
```
	set $kibana_one hostname-one:5601;
	location ~ /elasticsearch {
		if ($denied) {
			return 403 "Forbidden";
		}
		proxy_pass http://$kibana_one;
	}
```

For other services it's still on TODO, but docker healthchecks could do the trick.
Regards
