### ISSUE TITLE
Docker swarm DNS and load balancing behaviour 

### ISSUE THREAD

**Issue by viveky4d4v** [docker/docker#27837]
Will swarm internal DNS keep entries for unhealthy containers ? If i have scaled a service to 4 containers & if one of them goes down how the DNS & LB will react to it ?

**Comment by langziming** [comment]
I meet the same problem , Please anybody help me?

**Comment by thaJeztah** [comment]
This is coming in docker 1.13, see https://github.com/docker/docker/pull/27279, and https://github.com/docker/docker/issues/24092

**Comment by thaJeztah** [comment]
I'll close this issue, because it's fixed in master, and will be coming in 1.13, but feel free to comment. If you have a system to test on, release candidates for 1.13 are now available for testing https://github.com/docker/docker/releases (but don't use them for production yet)
