### ISSUE TITLE
[1.13] add new documentation reference section for metrics API

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#27843]
per https://github.com/docker/docker/pull/25820#issuecomment-256800737, we need to add documentation for the new metrics API, and probably some examples in other parts of the documentation to show how it's used.

opening this issue for tracking, so that we unblock the PR that implements the feature

/cc @mstanleyjones @crosbymichael  - assigning you both so that we don't forget :smile:

**Comment by crosbymichael** [comment]
What file should this go in?

**Comment by thaJeztah** [comment]
@crosbymichael since it's a new API, probably a new file. Let me try to have @mstanleyjones to have a look

**Comment by mstanleyjones** [comment]
Right now the API files are versioned. Will the metrics API be another top-level API that is also versioned separately, or will it just be more endpoints in the API that already exists?

**Comment by stevvooe** [comment]
@mstanleyjones This is the regular docker API and we won't be using the same documentation pipeline (ie swagger) to version it. We may be able to autogenerate something from the metrics definitions, but that is a ways out. For the most part, this API will be covered by the prometheus documentation and exported help definitions from each metric declaration.

@thaJeztah Have we made it clear that this API and any exported metric names can change at any time?

**Comment by thaJeztah** [comment]
@stevvooe there is a mention about that; https://github.com/docker/docker/pull/27862/files#diff-ca4f406de134be5cca3ae377c03a4386R1109

**Comment by thaJeztah** [comment]
@arun-gupta On Docker for Mac;

First, enable experimental features and the metrics API; Set the following `daemon.json` and restart docker;

```json
{
  "experimental": true,
  "metrics-addr": "0.0.0.0:1337"
}
```

Docker for Mac does not automatically expose the port for the metrics API.
Although there _is_ a way to expose it (by digging into the VM) there is an easier
approach; If you have Swarm mode enabled, you can use this approach to get the
IP-address for prometheus to connect to;

Get the "node" address of your node on Docker for Mac;

```bash
$ docker info --format '{{.Swarm.NodeAddr}}'
192.168.65.2
```

Create an empty directory, and a `prometheus.yml` configuration file inside that
directory, and use the IP-address you found above as "target";

```yaml
scrape_configs:
  - job_name: 'docker'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.65.2:1337']
```

Start a prometheus container with the configuration file;

```bash
$ docker run -d -p 9090:9090 -v $(pwd):/etc/prometheus/ --name prom prom/prometheus
```

Visit http://localhost:9090 in your web-browser

**Comment by arun-gupta** [comment]
@thaJeztah that worked for me! Now will go hunting Prometheus expressions for my application. Some sample/usual suspects would be useful though.

**Comment by bvis** [comment]
I followed a different approach, which I described in this blog post: https://medium.com/@basilio.vera/docker-swarm-metrics-in-prometheus-e02a6a5745a#.kav4zk3fa

**Comment by kinghuang** [comment]
@bvis FYI, the solution in your blog post didn't work for me on either Docker for Mac or on a 4-node swarm on RHEL 7. It assumes that the container host is accessible via `172.18.0.1`, which isn't always the case.

**Comment by bvis** [comment]
Ops, if that's your case you can start the socat service defining your interface using the "IN" variable.

It's something not explained in the README file, but you'll find it in the Dockerfile.

https://github.com/bvis/docker-socat/blob/master/Dockerfile

**Comment by goettl79** [comment]
Actually I only see metrics for dockerd itself. Would' like to see metrics for started containers too - am I doing smthg. wrong or is it not yet implemented? (saw a discussion in the related pull request with discussions about the naming of network transmit metrics... )

**Comment by stevvooe** [comment]
@goettl79 That is not supported yet. The road map for prometheus metrics is in https://github.com/docker/docker/issues/27307. Externally observable metrics is on the road map but no one has implemented it yet.

Please note that this is an experimental feature and we reserve the right to change it drastically. Was this not clear from the docs?

@thaJeztah We might be missing something the docs about the specifics of the scope of metrics support.

**Comment by thaJeztah** [comment]
@stevvooe there's some discussion about that here; https://github.com/docker/docker.github.io/issues/1307
