### ISSUE TITLE
Flaky test: DockerSwarmSuite.TestPruneNetwork

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#27866]
Seen flakily failing on arm and ppc64le.

``` sh
----------------------------------------------------------------------
FAIL: docker_cli_prune_unix_test.go:26: DockerSwarmSuite.TestPruneNetwork

[d4ebd159337da] waiting for daemon to start
[d4ebd159337da] daemon started
docker_cli_prune_unix_test.go:35:
    c.Assert(err, checker.IsNil)
... value *exec.ExitError = &exec.ExitError{ProcessState:(*os.ProcessState)(0xc4205245a0), Stderr:[]uint8(nil)} ("exit status 1")

[d4ebd159337da] exiting daemon

----------------------------------------------------------------------
```

unfortunately the Jenkins logs were deleted as I was making this, but I'm seeing it on my local power machine on master as well.

**Comment by tophj-ibm** [comment]
hmm looks like a network isn't being cleaned up correctly, from failing docker.log here https://gist.github.com/tophj-ibm/bd415b07affffd124eee5e45ac82e408
```sh
time="2016-10-28T19:02:59.242218000Z" level=debug msg=""Calling POST /v1.25/networks/create"
time="2016-10-28T19:02:59.242366000Z" level=debug msg="form data: {\"Attachable\":false,\"CheckDuplicate\":true,\"Driver\":\"overlay\",\"EnableIPv6\":false,\"IPAM\":{\"Config\":[],\"Driver\":\"default\",\"Options\":{}},\"Internal\":false,\"Labels\":{},\"Name\":\"n4\",\"Options\":{}}"
time="2016-10-28T19:02:59.243590000Z" level=error msg="Handler for POST /v1.25/networks/create returned error: network with name n4 already exists"
```

**Comment by thaJeztah** [comment]
This test was added in https://github.com/docker/docker/pull/27525

ping @AkihiroSuda ptal

**Comment by AkihiroSuda** [comment]
https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/3558/console seems hitting this.

But AFAIK no test other than `TestPruneNetwork` creates a network named `"n4"`...

(bundle: https://jenkins.dockerproject.org/job/Docker%20Master%20(arm)/3571/)
```
$ find bundles -name docker.log | xargs grep '\\"n4\\"'
bundles/1.13.0-dev/test-integration-cli/d8e3bfbf769bf/docker.log:time="2016-10-29T20:02:58.304429896Z" level=debug msg="form data: {\"Attachable\":false,\"CheckDuplicate\":true,\"Driver\":\"overlay\",\"EnableIPv6\":false,\"IPAM\":{\"Config\":[],\"Driver\":\"default\",\"Options\":{}},\"Internal\":false,\"Labels\":{},\"Name\":\"n4\",\"Options\":{}}"
^
|
+---- this is the log for TestPruneNetwork
```

Maybe the error string `"error: network with name n4 already exists"` is wrong, but not sure yet.
Trying to reproduce..

**Comment by AkihiroSuda** [comment]
Reproduced during `BUILDFLAGS="-race" TESTFLAGS='-check.f TestPrune -test.count 100' make test-integration-cli`, on Ubuntu 16.10, kernel 4.8.0-26-generic, x86_64

So the test failure is 
* Not related to any other test
* Not related to arm nor ppc64le

Looking at the log ([mine](https://github.com/docker/docker/files/561329/docker.log.txt) and @tophj-ibm 's https://github.com/docker/docker/issues/27866#issuecomment-257006515) , the failure is caused when the ID of the `ingress` starts with `n4`..

e.g.
```
Allocating IPv4 pools for network ingress (n4whp4a1b4bkgw23akoamblhz)
````

Not sure why the ID is likely to start with `n4`...

**Comment by AkihiroSuda** [comment]
Anyway, I'll try to open PR that allows to create a network of which name is the prefix of the ID of the `ingress`.

PTAL for why `swarmkit/identity.NewID` is likely to generate "n4..." : @aaronlehmann @stevvooe

**Comment by AkihiroSuda** [comment]
opened https://github.com/docker/docker/issues/27938
