### ISSUE TITLE
Docs from docker website: devicemapper: wrong thinpooldev value

### ISSUE THREAD

**Issue by WeiZhang555** [docker/docker#27876]
See https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-docker-with-devicemapper  

Item 14: Configure the Docker daemon with specific devicemapper options.

```
--storage-driver=devicemapper --storage-opt=dm.thinpooldev=/dev/mapper/docker-thinpool-tpool --storage-opt=dm.use_deferred_removal=true --storage-opt=dm.use_deferred_deletion=true
```

can't find `/dev/mapper/docker-thinpool-tpool`

Combining recommended `daemon.json` configure, it should be `/dev/mapper/docker-thinpool`

**Comment by thaJeztah** [comment]
That part of the docs has moved to the central docs repo https://github.com/docker/docker.github.io/blob/master/engine/userguide/storagedriver/device-mapper-driver.md

Could you open a pull request there? Thanks!!

**Comment by WeiZhang555** [comment]
@thaJeztah Yep, I'll file a PR later :)

**Comment by thaJeztah** [comment]
Thank you!

**Comment by HaiNguyen007** [comment]
dm.thinpooldev=/dev/mapper/docker-thinpool-tpool is correct value, otherwise will have error when sudo systemctl start docker: "Error starting daemon: error initializing graphdriver: devmapp

**Comment by HaiNguyen007** [comment]
https://github.com/moby/moby/issues/21304
