### ISSUE TITLE
Cannot connect to container when dockerd is stopped and live-restore is enabled

### ISSUE THREAD

**Issue by ceecko** [docker/docker#27880]
When using `live-restore` and dockerd is stopped, connection to containers through a port is refused.

**Steps to reproduce the issue:**
1. Enable `live-restore` in the config
2. `docker run --name nginx -d -p 8080:80 nginx`
3. `curl localhost:8080` works
4. `systemctl stop docker`
5. `curl localhost:8080` returns `Connection refused`

**Describe the results you received:**
curl returns `Connection refused`

**Describe the results you expected:**
curl should properly connect to the container

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:29:41 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: xfs
 Dirs: 38
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.65 GiB
Name: fs1
ID: VQIH:4PNT:HWNL:XGDK:5GKR:4XZT:EOHA:JJZV:ZQ2I:RFM2:VF7W:4WFZ
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by aboch** [comment]
@ceecko This is a known limitation when daemon is started with userland-proxy enabled (which is the default). When the daemon goes down, so does the userland proxy and connections to the container's published ports won't be possible.

As the live-restore use-case is for updating the daemon and not meant to allow containers running for long time without the daemon, we considered this an acceptable tradeoff.

**Comment by ceecko** [comment]
@abcoh Thanks. I didn't know about the userland-proxy. I'd love to disable it but it seems it would only break things 😞 see https://github.com/docker/docker/issues/14856#issuecomment-238925313

**Comment by aboch** [comment]
@ceecko I know, hopefully one day that will work too.

I will close now this issue as know limitation. Thanks.
