### ISSUE TITLE
Cannot create container for service nc: Unable to find a node that satisfies the following conditions

### ISSUE THREAD

**Issue by viveky4d4v** [docker/docker#27887]
Docker machine setup -

    $ docker-machine ls
    NAME     ACTIVE      DRIVER    STATE     URL                        SWARM          DOCKER    ERRORS
    consul   -           generic   Running   tcp://192.168.99.94:2376                  v1.12.2   
    sm1      -           generic   Running   tcp://192.168.99.91:2376   sm5 (master)   v1.12.2   
    sm2      -           generic   Running   tcp://192.168.99.92:2376   sm5 (master)   v1.12.2   
    sm3      -           generic   Running   tcp://192.168.99.93:2376   sm5 (master)   v1.12.2   
    sm4      -           generic   Running   tcp://192.168.99.95:2376   sm5 (master)   v1.12.3   
    sm5      * (swarm)   generic   Running   tcp://192.168.99.96:2376   sm5 (master)   v1.12.3   

Setting the environment to master machine - 

     eval $(docker-machine env --swarm sm5)

Overlay network - 

     $ docker network ls 
     NETWORK ID          NAME                  DRIVER              SCOPE
     0db485a060f9        cheerios              overlay             global              
     48c0268d5393        db/bridge             bridge              local               
     1e022cc8c0e7        db/docker_gwbridge    bridge              local               
     659a7a4d85a7        db/host               host                local               
     f09560861ed8        db/none               null                local               
     6fb3c8779fdb        nc/bridge             bridge              local               
     50544f7796d7        nc/host               host                local               
     79b2f0d4d548        nc/none               null                local               
     54c037aa64d4        nc1/bridge            bridge              local               
     cb614bd91dd1        nc1/host              host                local               
     db46fdf10721        nc1/none              null                local               
     b1e2e123d2c5        wd/bridge             bridge              local               
     459edee88b77        wd/docker_gwbridge    bridge              local               
     c83be7e1b8b5        wd/host               host                local               
     d417ee893a2c        wd/none               null                local               
     31f4d58e34b7        web/bridge            bridge              local               
     b06e1704b0de        web/docker_gwbridge   bridge              local               
     b0b566aa617d        web/host              host                local               
     16b609f89d28        web/none              null                local               

Compose file - 

    version: "2" # https://docs.docker.com/compose/compose-file/

    services:
        nc:
          image: vivekh/nc:v1
          environment:
             - "constraint:node==sm4"
          ports:
             - 80:80
          command: "/usr/sbin/nginx"

         nc1:
             image: vivekh/nc:v1
             environment:
                 - "constraint:node==sm5"
             ports:
                - 80:80
             command: "/usr/sbin/nginx"

        networks:
          default:
              external:
                name: cheerios

Error while bringing the stack up - 

         ERROR: for nc1  Cannot create container for service nc1: Unable to find a node that satisfies the                following conditions 
          [port 80 (Bridge mode)]
          [ available container slots]
          [node==sm5]

         ERROR: for nc  Cannot create container for service nc: Unable to find a node that satisfies the following conditions 
         [port 80 (Bridge mode)]
          [available container slots]
         [node==sm4]
         ERROR: compose.cli.main.main: Encountered errors while bringing up the project.

I can confirm that nothing is running on port 80 on any of the machines "nc" & "nc1"  . Not really sure what i am really missing . I am fairly new to docker swarm . Please suggest .

**Comment by thaJeztah** [comment]
It looks like you're running"Swarm" (https://github.com/docker/swarm) not the "Swarm mode" / services introduced in Docker 1.12 (https://docs.docker.com/engine/swarm/).

If you want to use "classic" Swarm, could you report this in https://github.com/docker/swarm, or open a topic on the forums instead? https://forums.docker.com ?

Note that docker-compose does not (yet) support Swarm mode

**Comment by viveky4d4v** [comment]
Thanks for the redirection , created new issue 

https://github.com/docker/swarm/issues/2536

**Comment by thaJeztah** [comment]
@viveky4d4v I'd recommend having a look at Swarm mode as well; most new development takes place in Swarm Mode (SwarmKit), so if you're new to Swarm, it's probably better to invest time into that

**Comment by viveky4d4v** [comment]
@thaJeztah 

Docker version 1.12.2, build bb80604

I read this [https://docs.docker.com/compose/bundles/] earlier where compose can be deployed when docker engine is running in swarm mode .But i went by this [https://docs.docker.com/compose/swarm/] doc which suggests that compose can be integrated with swarm .

So i deployed swarm cluster in in multi host overlay network using KV store & docker machines , as per the doc once we have set up that we should be able to use compose except the limitations mentioned in the doc . Mentioned in compose swarm doc -

"""
Read Get started with multi-host networking to see how to set up a Swarm cluster with Docker Machine and the overlay driver. Once you’ve got it running, deploying your app to it should be as simple as:

$ eval "$(docker-machine env --swarm )"
$ docker-compose up

"""

Not sure where the things went wrong & in the compose swarm documentation , it isn't mentioned nowhere that we cannot use "constraint:node==xxxx"  .

If i am not able to use it this way then i have to go for the docker engine swarm mode .

**Comment by viveky4d4v** [comment]
@thaJeztah : I have started docker engine in swarm mode since compose is not yet fully integrated with swarm/swarm mode as you suggested . 

I need a fault tolerance of 2 & I know that manager nodes are workers as well so will it be fine if i go with all 5 as manager nodes ?
I saw some strange behaviour while using all masters like services fail intermittently, ingress LB doesn't work on all nodes sometimes etc . 

What do you suggest ?

**Comment by thaJeztah** [comment]
If you _require_ 2 manager fault tolerance, then having 5 managers is the only option (see https://docs.docker.com/engine/swarm/admin_guide/#/add-manager-nodes-for-fault-tolerance). Do keep in mind that more managers does not provide better performances (the contrary actually, because they are constantly "chatting" to stay in sync / reach consensus).

_Also keep in mind that_ putting load on managers for fault tolerance should be properly managed; depending on the cluster size, managers require sufficient memory / resources. If a manager becomes overloaded (e.g. running out of memory because a service did not have proper resource constraints, or running out of disk space, because you didn't configure log-rotation), your can loose that manager, resulting in another manager getting even more load, which can cause a cascading effect.

So, yes, you can, but take those into account
