### ISSUE TITLE
--link does not work in docker 1.12

### ISSUE THREAD

**Issue by kcris** [docker/docker#27882]
Steps to reproduce

docker run -p 9200:9200 -p 9300:9300 --name es elasticsearch:2.2.2
docker run --name kibana-4.4 --link es:elasticsearch -p 5601:5601 -d kibana:4.4

Results
Second container is not linked with first one.
There is no new entry in /etc/hosts in second container.

Expected results:
New host should be added in second container (pointing to first one).

ps: it works in docker 1.11.2

**Comment by aboch** [comment]
What specific 1.12.x version are you running ?

It seems to work fine in 1.12.2:

```
$ docker version | grep Version
 Version:      1.12.2
 Version:      1.12.2
$ docker run -d -p 9200:9200 -p 9300:9300 --name es elasticsearch:2.2.2
ac3f955ca5c9c13f2a1eba268bb06819c8ecd80e06d04c123192762357c8280a
$ docker run --name kibana-4.4 --link es:elasticsearch -p 5601:5601 -d kibana:4.4
faa35c55588b0635d798abeb3d3ad638beb10c728d07262a4cc0d27b5511f071
$ docker exec kibana-4.4 cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.18.0.1	elasticsearch ac3f955ca5c9 es      <--- <---
172.18.0.2	faa35c55588b
$
```

**Comment by kcris** [comment]
docker --version
1.11.2, build b9f10c9

running on ubuntu 16.04

**Comment by thaJeztah** [comment]
Let me go ahead and close this issue then. Thanks @kcris
