### ISSUE TITLE
Localhost refuse to connect (Simplest Flask site)

### ISSUE THREAD

**Issue by izzyleung** [docker/docker#27885]
**Description**

I am new to Docker, and this is my first time trying Docker using the tutorial from https://prakhar.me/docker-curriculum/   
I tried to create a simple Flask website, and run it inside a Docker container.  
All the code can be found at [here](https://gist.github.com/izzyleung/52ff04accf76bdee8388277a1f215b04)

**Steps to reproduce the issue:**
1. First, I tried to build the image by using the command `docker build -t izzyliang:Flask-Site .`
2. Second, I tried to run the image in a container using the command `docker run -p 8888:5000 --name flask izzyliang:Flask-Site`
3. Now, when I tried to access `localhost:8888`, Chrome will tell me: `The site can't be reached. localhost refuse to connect.`

**Additional information you deem important:**

I am using the latest version of macOS, and installed Docker using the command `brew cask install docker`

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.20-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: moby
ID: S2XY:Y4IO:WCJV:TYUM:TP5U:RZHK:VK5R:ZF5E:WHY4:A42U:PNIN:BFRX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 18
 Goroutines: 30
 System Time: 2016-10-30T02:06:15.173207168Z
 EventsListeners: 1
Username: izzyliang
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

Since I was using the Docker rather than Docker-toolbox, there are no `docker-machine` created, and I cannot get the IP address or the port for the `docker-machine` as described in the tutorial.

I have been trying to find out the cause for this issue for a whole day, I am really frustrated.  
However, I have to say thank you for reading all the information, and helping me in advance.

**Comment by thaJeztah** [comment]
It looks like the Homebrew script may be out of date, because the current version is 1.12.3, not 1.12.1. To get the current version, check the official installation here; https://docs.docker.com/docker-for-mac/

For your issue; keep in mind that the GitHub issue tracker is not a support forum, but for reporting bugs and feature requests. The tutorial you're following is not written by us, so it's possible there's an issue with the tutorial (I haven't tried it).

To exclude this possibility, could you try to update to the current version, and running this instead?


    docker run -d -p 8080:80 nginx:alpine


You should be able to then reach this webserver by visiting http://localhost:8080 in your browser

**Comment by izzyleung** [comment]
@thaJeztah 

Thank you so much for replying.
However, I have to apologize for asking for help here instead of posting bug information, because I am not quite sure about where to ask for help. So I closed this issue in order not to disturb the collaborators of this repo. 

I have uninstalled the Docker installed by brew cask, and reinstalled it using the package downloaded from the official site. However, the package is version 1.12.1, attached below is the output from docker's menu icon's option "About Docker".

```
Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856
```

Which means, the result of `docker version` produces the exact same output.

Strange thing is, I will be able to get the desired html page when running the command you provided in your previous reply, while I am not able to get the desired result in the browser.

In the meantime, I tried docker-toolbox (downloaded directly from the official GitHub page), and the demo still does not work.

**Comment by thaJeztah** [comment]
> Which means, the result of docker version produces the exact same output.

That's strange; I wonder if the link is not updated to the latest version; can you try selecting "check for updates" from the "whale" menu?

When running docker toolbox (however, I'd recommend using Docker for Mac instead), you don't connect to `localhost`, but the IP-address of the VM (usually 192.168.99.100)

> while I am not able to get the desired result in the browser.

Does the browser not work when opening localhost:8080, or does it work with my example, but not with your tutorial?

**Comment by izzyleung** [comment]
First, when I use the option "Check for Updates..." in the menu icon, docker says my version is currently the newest version available, humm, that's really weird.

Second, I do mean that your example works on my computer, while my example code does not work.
To be clear, when I run the command `docker run -d -p 8080:80 nginx:alpine` or just `docker run -d -p 80:80 --name webserver nginx` (example directly taken from the official website), I will be able to access `localhost:8080` and `localhost:80` in the browser, with the browser displaying the default nginx welcome page.
However, when running my example using the command `docker run -d -p 8080:5000 --name flask izzyliang:Flask-Site`, I am not able to access `localhost:8080` in the browser, because `Localhost refuse to connect`.

I was wondering if this is because I am not using nginx in my example, and I have to install nginx, setup the rules before I can have the desired result. 

Thanks again for your time and energy for helping me.

**Comment by thaJeztah** [comment]
Okay, I should check why 1.12.3 is not downloaded as the latest version, perhaps it's only on the beta channel :sweat_smile: 

w.r.t. Your Flask site; make sure that it's actually listening on 0.0.0.0:5000, and not just on 127.0.0.1:5000. I don't have experience with Flask, but I know it's been something that people ran into with other systems. (127.0.0.1 / localhost inside a container is the localhost of the _container_, not the host that the container runs on)
