### ISSUE TITLE
Memory limit not respected on windows server

### ISSUE THREAD

**Issue by gamma** [docker/docker#27892]
Docker on Windows Server 2016 seems to not respect the memory constraint. See the following output for reference.

    [gamma@gw2] (w10-fileserver) inetsoftware $ docker info
    Containers: 4
     Running: 2
     Paused: 0
     Stopped: 2
    Images: 98
    Server Version: 1.12.2-cs2-ws-beta
    Storage Driver: windowsfilter
     Windows: 
    Logging Driver: json-file
    Plugins:
     Volume: local
     Network: nat null overlay
    Swarm: inactive
    Security Options:
    Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
    Operating System: Windows Server 2016 Standard
    OSType: windows
    Architecture: x86_64
    CPUs: 8
    Total Memory: 31.96 GiB
    Name: w10-fileserver
    ID: DIKD:BD5K:Y6XJ:XWEE:7TPW:3XBE:I3AN:73O6:AZGQ:3JBX:UZSZ:DZFK
    Docker Root Dir: C:\ProgramData\docker
    Debug Mode (client): false
    Debug Mode (server): false
    Username: gamma
    Registry: https://index.docker.io/v1/
    Insecure Registries:
     127.0.0.0/8
    
    [gamma@gw2] (w10-fileserver) inetsoftware $ docker run -it -m 200M microsoft/windowsservercore cmd
    
    Microsoft Windows [Version 10.0.14393]
    (c) 2016 Microsoft Corporation. All rights reserved.
    
    C:\>systeminfo
                                                                                  
    Host Name:                 A5E4503B8C0F
    OS Name:                   Microsoft Windows Server 2016 Datacenter
    OS Version:                10.0.14393 N/A Build 14393
    OS Manufacturer:           Microsoft Corporation
    OS Configuration:          Standalone Server
    OS Build Type:             Multiprocessor Free
    Registered Owner:          N/A
    Registered Organization:   N/A
    Product ID:                00377-90000-00001-AA611
    Original Install Date:     9/22/2016, 11:59:54 AM
    System Boot Time:          10/31/2016, 6:44:28 AM
    System Manufacturer:       Hewlett-Packard
    System Model:              HP ProDesk 490 G2 MT
    System Type:               x64-based PC
    Processor(s):              1 Processor(s) Installed.
                               [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~800 Mhz
    BIOS Version:              AMI 02.06, 10/15/2014
    Windows Directory:         C:\WINDOWS
    System Directory:          C:\WINDOWS\system32
    Boot Device:               \Device\HarddiskVolume1
    System Locale:             en-us;Englisch (Vereinigte Staaten)
    Input Locale:              en-us;Englisch (Vereinigte Staaten)
    Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
    Total Physical Memory:     32,728 MB
    Available Physical Memory: 28,520 MB
    Virtual Memory: Max Size:  37,592 MB
    Virtual Memory: Available: 31,688 MB
    Virtual Memory: In Use:    5,904 MB
    Page File Location(s):     C:\pagefile.sys
    Domain:                    WORKGROUP
    Logon Server:              N/A
    Hotfix(s):                 2 Hotfix(s) Installed.
                               [01]: KB3176936
                               [02]: KB3192366
    Network Card(s):           N/A
    Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                               Virtualization Enabled In Firmware: No
                               Second Level Address Translation: Yes
                               Data Execution Prevention Available: Yes
    
    C:\>

**Comment by justincormack** [comment]
The memory reported may not be the same as the memory available, can you try allocating more memory than you asked for and see if it fails, as this is not a VM container so the reporting is probably for the host.

**Comment by gamma** [comment]
That is actually the problem we're facing: a java/gradle process reports that it has more memory then should be available due to the docker configuration. To be exact:

  * We have a 32GB RAM Win Server Host
  * The container has a 4GB RAM limit
  * Java/Gradle report 8GB available memory for allocation ( by default 1/4 of the reported available memory)
  * When Java reaches this limit due to allocation - and tries to go beyond the 4GB the container should have - it throws an OutOfMemoryError or related errors.

**Comment by friism** [comment]
It seems that it does respect the memory constraint since you get OOM when trying to allocate more than 4GB. @jhowardmsft would know if this is different on Windows, but on Linux at least, containers generally see the full host memory allotment: https://fabiokung.com/2014/03/13/memory-inside-linux-containers/

Can you override the Gradle/Java heap size to avoid it allocating more than 4GB?

**Comment by justincormack** [comment]
Also it sounds like Java needs to know how to read the actual available memory, as applicable in a container, not the total system memory. @jhowardmsft is there an API they could use to read that?

**Comment by gamma** [comment]
I verified that Linux works in the same way, maybe we just never ran into this issue.

We do set the available memory to java now.

Anyway: if there was a mechanism to allow java to read the actual available memory we will open a. If Report with Oracle.

Do other programs have problems with memory allocation?

**Comment by friism** [comment]
@justincormack such an API for a container process to learn how much memory is available to the container doesn't exist on Linux either, afaik.

**Comment by justincormack** [comment]
@friism yes

```
whale:docker justin$ docker run -it -m 200m alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
209715200
whale:docker justin$ docker run -it -m 300m alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
314572800
whale:docker justin$ docker run -it alpine cat /sys/fs/cgroup/memory/memory.limit_in_bytes
9223372036854771712
```

**Comment by friism** [comment]
@justincormack well, there's no documentation, so doesn't count :-). /cc @mstanleyjones

**Comment by gamma** [comment]
Since this is a known limitation I'd close the issue. There is the undocumented way for Linux which could be brought forward to Oracle ... It looks like there can't be done such thing for Windows yet.

**Comment by akashche** [comment]
Just for the record, cgroups memory limit support was recently implemented in jdk with `-XX:+UseCGroupMemoryLimitForHeap` switch - http://hg.openjdk.java.net/jdk8u/jdk8u-dev/hotspot/rev/c7140a91e56a

It is doing pretty much the same as the following:

    -XX:MaxRAM=`cat /sys/fs/cgroup/memory/memory.limit_in_bytes` 

but in a nice automatic way with proper checks.

**Comment by PatrickLang** [comment]
I pinged some Windows devs on this to see if they have an answer

**Comment by shanselman** [comment]
Bummer hit this today. No slider or way to see this. Does -m work in a docker compose?

**Comment by titoluyo** [comment]
@shanselman 
dotnetnuke_sqlserver:
  mem_limit: 4096m
