### ISSUE TITLE
How to customize the subnet of docker_gwbridge

### ISSUE THREAD

**Issue by shaloulcy** [docker/docker#27890]
In the swarm mode, there is a bridge named docker_gwbridge which provides the access to outside networks.  It gets the default subnet 172.18.0.0/16. So it add a route 172.18.0.0 which conflicts the existing routes. So how can I customize the subnet of docker_gwbridge?

**Comment by aboch** [comment]
@shaloulcy 
You need to create it manually before joining the cluster
Leave the swarm, remove the docker gw network, manually create it passing your configuration then init/join the cluster.

**Comment by shaloulcy** [comment]
Thanks!!!

**Comment by justincormack** [comment]
@aboch is this documented?

**Comment by aboch** [comment]
Not sure, need to check.

**Comment by aboch** [comment]
@justincormack Opened the above for updating the documentation.
I think this issue can be closed now as the requested information was provided.

**Comment by thaJeztah** [comment]
agreed, closing this issue; documentation is being handled in https://github.com/docker/docker.github.io/issues/400
