### ISSUE TITLE
Put "C:\ProgramData\Docker" on a different drive? Configuration option?

### ISSUE THREAD

**Issue by cons0l3** [docker/docker#27899]
With the new windows containers, I started playing around. The windowsservercore docker image is large and filled up my C: drive completly. (no getting a larger disk is not an option).

Where can I configure Docker to put all the ProgramData\Docker stuff? Can I move the ProgramData\Docker to a different disk?

**Description**
I am experimenting with the docker windows container services and have sucessfully pulled "windowsservercore" and used "chocolatey" do get some stuff installed. Awsome. Works. As I have now learned C:\ProgramData\Docker\... contains all the images\containers\volumes\...

After a few experiments my C: filled up completly. So I decided to move either C:\ProgramData or C:\ProgramData\Docker to another drive. I roughly followed the steps for moving the [C:\Users folder](http://www.tenforums.com/tutorials/1964-users-folder-move-location-windows-10-a.html#MethodTwo) and wanted to used "mklink" to link it back while in Windows "Save Mode".

**Steps to reproduce the issue:**
1. Get a almost full C: Drive
2. Pull large docker image (e.g. windowsservercore) to fill up C: drive
3. wait for explosion - windows is not happy if C: has 0 bytes free ;-)
4. reboot in Safe Mode
5. copy C:\ProgramData\Docker to different disk via "robocopy C:\ProgramData\Docker D:\ProgramData\Docker /MIR /COPYALL"

**Describe the results you received:**
Robocopy failed on so many levels, that I gave up moving it e.g. "bootmgr" could not be accessed... ApplicationData recursion problem (even though I am system in safe mode environment...)
I could not even remove target folder in safe mode, after the robocopy failed...

**Describe the results you expected:**
When installing Docker, I would like to tell it where to put the ProgramData\Docker stuff.
When running Docker, I would like to "move" the ProgramData\Docker stuff to another disk.

**Output of `docker version`:**

```
λ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
λ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 11.99 GiB
Name: BLAUBEERE10
ID: ZUJM:NRJZ:TPN2:OCLO:4BSZ:CB2V:HWDZ:LIRK:V7AD:XPZL:IUM6:56CU
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical machine

**Comment by friism** [comment]
Instead of trying to use a filesystem link, you can tell the Docker daemon to use a different drive for storage with the `-g` `dockerd.exe` commandline option:

      -g, --graph string                          Root of the Docker runtime (default "C:\\ProgramData\\docker")

If you want to move already downloaded images, the safest option is probably to `docker save` them, then change the daemon `-g` option, then run `docker load`. Or you can just download them anew.

**Comment by cons0l3** [comment]
@friism thanks, I am running "Docker for Windows" on Windows 10 V 1.12.3-beta29.2 (8280) channel: Beta, 902414d

Where do I find the dockerd.exe? I start docker by starting "Docker for Windows"-App. When in "windows container" mode, if I start "Settings..." from the context menu of the docker for windows icon in the systray, it tells me "There are not settings for Windows containers. Yet!"

Where do I access the "-g" switch?

**Comment by justincormack** [comment]
@cons0l3 sorry, can you open an issue for this in https://github.com/docker/for-win/issues as it is specific to Docker for Windows and there is an upstream solution in engine.

**Comment by cons0l3** [comment]
sure, will do: issue [docker/for-win #185](https://github.com/docker/for-win/issues/185)
