### ISSUE TITLE
Can't pull docker.io/microsoft/dotnet35:windowsservercore unkown manifest

### ISSUE THREAD

**Issue by pamanes** [docker/docker#27906]
**Description**

**Steps to reproduce the issue:**
1.Enabled containers and hyper-v on windows 10 pro, then installed docker beta 1.12.3-beta29.2 (8280)
2.Get dockerfiles from https://github.com/brogersyh/Dockerfiles-for-windows/archive/master.zip
3.docker build -t sqlexpress .

**Describe the results you received:**
Sending build context to Docker daemon 10.24 kB
Step 1/11 : FROM docker.io/microsoft/dotnet35:windowsservercore
manifest unknown: manifest unknown

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.92 GiB
Name: CorAlePal1
ID: GXFK:QKFW:ZGBI:TMMR:YADM:OWXY:FZV6:JAAE:5KXI:JQXT:45KC:XLWV
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by PatrickLang** [comment]
Please see https://hub.docker.com/r/microsoft/dotnet35/ - the repository name changed, and this Dockerfile hasn't been updated.

There are premade SQL Server Express images available:
- https://hub.docker.com/r/microsoft/mssql-server-2014-express-windows/
- https://hub.docker.com/r/microsoft/mssql-server-2016-express-windows/

And Dockerfiles here:
- https://github.com/Microsoft/sql-server-samples/tree/master/samples/manage/windows-containers

**Comment by thaJeztah** [comment]
I'm closing this issue, because it looks like it's answered, but feel free to comment after I closed @pamanes
