### ISSUE TITLE
tests from DockerSwarmSuite.* intermitently fail with "update out of sequence"

### ISSUE THREAD

**Issue by Snorch** [docker/docker#27904]
**Description**
Hi! I have a strange problem when running docker swarm tests in my Fedora 24. It reproduces in different swarm tests like DockerSwarmSuite.TestApiSwarmCAHash or DockerSwarmSuite.TestServiceUpdatePort.

**Steps to reproduce the issue:**
0. install docker-engine following https://docs.docker.com/engine/installation/linux/fedora/
1. git clone https://github.com/docker/docker.git --branch v1.12.3
2. cd docker
3. TESTFLAGS="-check.f=DockerSwarmSuite.*" make test-integration-cli

**Describe the results you received:**

```
FAIL: docker_cli_service_update_test.go:13: DockerSwarmSuite.TestServiceUpdatePort

[d40511895] waiting for daemon to start
[d40511895] daemon started
docker_cli_service_update_test.go:14:
    d := s.AddDaemon(c, true, true)
check_test.go:229:
    c.Assert(d.Init(swarm.InitRequest{}), check.IsNil)
... value *errors.errorString = &errors.errorString{s:"initializing swarm: invalid statuscode 500, \"{\\\"message\\\":\\\"error updating cluster settings: rpc error: code = 2 desc = update out of sequence\\\"}\\n\""} ("initializing swarm: invalid statuscode 500, \"{\\\"message\\\":\\\"error updating cluster settings: rpc error: code = 2 desc = update out of sequence\\\"}\\n\"")
```

Message "update out of sequence" is from v1.12.3:vendor/src/github.com/docker/swarmkit/manager/state/store/memory.go:490 func update().

And it seem that some object in swarm store is updating but version is not consistent. I can see always same versions: oldN.(Object).Meta().Version == {9} and o.Meta().Version == {2}.

**Describe the results you expected:**
No fail.

**Additional information you deem important (e.g. issue happens only occasionally):**
 It is quiet accidental: last time I managed to get the problem once after 4 successful test runs.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 53
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: vmlinuz-4.7.9-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.54 GiB
Name: dhcp-10-30-29-163.sw.ru
ID: FOBI:53SZ:3XT7:5E4Q:JJND:QPOY:PQAT:GPCK:IVQ6:L2AO:IZPY:QWKU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fedora 24, hardware node
bundles/1.12.3/test-integration-cli/d40511895/docker.log : https://gist.github.com/Snorch/3fc28b0f7edd07efca07ae8397911d11

**Comment by aluzzardi** [comment]
This is related to spec versioning and retries

/cc @aaronlehmann @mrjana

**Comment by Snorch** [comment]
Please do not forget about it.

**Comment by Snorch** [comment]
Any news?

**Comment by vdemeester** [comment]
I can't reproduce that on current master 😅 
I'll close for now, but feel free to discuss that more if it happens again, I'll reopen.

**Comment by josersleal** [comment]
still happens: 
Now lets wait another month, another release and the same answer, doesnt happen on my machine :)
are you using docker? you should :)
