### ISSUE TITLE
docker compose "extra_hosts" alternative in docker engine swarm mode 

### ISSUE THREAD

**Issue by viveky4d4v** [docker/docker#27902]
In docker compose file i was able to declare a domain & IP like below -

    extra_hosts:
      - "mshost:10.4.12.31"
      - "mongodb DEV-MONGODB:10.250.12.35"
I want to know the alternative to this while using command in docker engine swarm mode .

     "docker service create ...."

**Comment by aluzzardi** [comment]
/cc @dnephin @icecrime @mrjana 

Do we want to add this into the ContainerSpec? (that's `--add-host`)

**Comment by dnephin** [comment]
If it works, I guess it doesn't hurt to add it?

**Comment by yongtang** [comment]
This is loosely related to #27567.

**Comment by icecrime** [comment]
Makes sense to me. (Cc @vdemeester)

**Comment by vdemeester** [comment]
Make sence to me too 👼

**Comment by yongtang** [comment]
I can work on this issue once #27567 is merged in.

**Comment by yongtang** [comment]
#dibs

**Comment by yongtang** [comment]
Added a PR #28031. The flag `--add-host conforms to `docker run` though other suggestions are welcomed. No flag has been added to `docker service update` yet (not sure about `-add/-rm` case).

**Comment by dtmistry** [comment]
Is this feature available in 1.13.0-rc1 ?

**Comment by yongtang** [comment]
@dtmistry The PR has been merged in. You could use `docker service create --host` to specify additional extra hosts in 1.13.0-rc1.

**Comment by dtmistry** [comment]
@yongtang Thanks. I did not see this issue referenced in the 1.13.0-rc1 release notes. So just wanted to make sure.

**Comment by thaJeztah** [comment]
@dtmistry you're right, it was missing in the changelog. I'm working on updates to the changelog for changes we missed, so I'll add it
