### ISSUE TITLE
Docker server implementation of image import API does not respect request body in some scenarios

### ISSUE THREAD

**Issue by erikh** [docker/docker#27922]
**Description**

The docker engine server-side API does not respect the Source parameter provided by the API (which specifies a reader that can be used). When specifying a Source with no SourceName (they are described as mutually exclusive in the docs), it tries to process an empty string as a URL and while doing that successfully producing `http://`, yields no error except for in the response body, which makes it really fun to catch. :)

**Steps to reproduce the issue:**
1. use the docker api for image import with no SourceName and an open io.Reader attached to Source
2. monitor err and response reader, the latter will be readable with json output stating the error. the former will be nil.
3. observe it is trying to pull `http://`

**Additional information you deem important (e.g. issue happens only occasionally):**

I think the relevant code is here: look at this https://github.com/docker/docker/blob/master/api/server/router/image/image_routes.go#L109-L115

I don't believe the body is considered at all without examining the post parameters first.

Is this a case of wrong docs?

https://godoc.org/github.com/docker/docker/api/types#ImageImportSource

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

not using the docker client but I'm using the 1.12.3 tag and also tried docker/engine-api before finding out it was deprecated.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

building with go 1.7.3, but i really doubt that matters

**Comment by thaJeztah** [comment]
ping @aaronlehmann this was the issue i pinged you in this morning on slack

**Comment by aaronlehmann** [comment]
The code expects `SourceName` to be set to `-` when `Source` is being used. This is documented in the API reference: https://github.com/docker/docker/blame/master/docs/reference/api/docker_remote_api_v1.25.md#L1879-L1881

Feel free to submit a PR to clarify the comments in the source code.

**Comment by erikh** [comment]
Oh interesting! Sure, I will file a PR.

**Comment by erikh** [comment]
I took it on faith, but here's some code:

https://gist.github.com/anonymous/e6bb119f123055ffdb001162cfc3e252

Did I do something wrong here? Contents of /dev/zero never make it to
docker.

**Comment by aaronlehmann** [comment]
`/dev/zero` returns an infinite stream of zeros so I don't see how this would work. Can you try with a real file?

Here is the CLI code for import in case it's helpful: https://github.com/docker/docker/blob/master/cli/command/image/import.go

**Comment by erikh** [comment]
shouldn't it still yield an archive error? I really don't want to add
another 100 lines to this code to explain how to generate a tar file; it's
not the issue.

Run the code. You will see the problem.

**Comment by aaronlehmann** [comment]
When I run the code, it sends zero bytes to Docker forever, which is exactly what I'd expect. When I change it to open a saved tar file instead of `/dev/zero`, it works.

**Comment by erikh** [comment]
interesting. what version of the client are you running?

**Comment by erikh** [comment]
this is what I see with the same code:

{"status":"Downloading from http://"}
{"errorDetail":{"message":"Get http://: http: no Host in request
URL"},"error":"Get http://: http: no Host in request URL"}

**Comment by erikh** [comment]
FWIW, sending zero bytes to docker forever is exactly what I expected too,
I just didn't get that. :)

**Comment by aaronlehmann** [comment]
6e462412d721525ee85f8a8874e933f16d0a27ce

**Comment by erikh** [comment]
can you try the client on latest master? does it still work there with
1.12.3?

Sorry to be a problem; I just don't understand how I'm seeing this and you
aren't.

**Comment by aaronlehmann** [comment]
Yes, it works.

**Comment by erikh** [comment]
Hmm ok. Can we discuss on irc? Might be faster.
