### ISSUE TITLE
Error: Package: docker-engine-1.12.3-1   Requires: selinux-policy >= 3.13.1-23

### ISSUE THREAD

**Issue by penhauer-xiao** [docker/docker#27933]
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: selinux-policy >= 3.13.1-23
           Available: selinux-policy-3.10.0-98.23.amzn1.noarch (amzn-main)
               selinux-policy = 3.10.0-98.23.amzn1
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: libdevmapper.so.1.02(DM_1_02_97)(64bit)
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: libsystemd.so.0(LIBSYSTEMD_209)(64bit)
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: libsystemd.so.0()(64bit)
Error: Package: docker-engine-selinux-1.12.3-1.el7.centos.noarch (dockerrepo)
           Requires: selinux-policy-base >= 3.13.1-23
           Available: selinux-policy-minimum-3.10.0-98.23.amzn1.noarch (amzn-main)
               selinux-policy-base = 3.10.0-98.23.amzn1
           Available: selinux-policy-mls-3.10.0-98.23.amzn1.noarch (amzn-main)
               selinux-policy-base = 3.10.0-98.23.amzn1
           Available: selinux-policy-targeted-3.10.0-98.23.amzn1.noarch (amzn-main)
               selinux-policy-base = 3.10.0-98.23.amzn1
Error: docker-engine conflicts with docker-1.9.1-1.2.amzn1.x86_64
Error: Package: docker-engine-selinux-1.12.3-1.el7.centos.noarch (dockerrepo)
           Requires: selinux-policy-targeted >= 3.13.1-23
           Available: selinux-policy-targeted-3.10.0-98.23.amzn1.noarch (amzn-main)
               selinux-policy-targeted = 3.10.0-98.23.amzn1
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: selinux-policy >= 3.13.1-23
           Installing: selinux-policy-3.10.0-98.23.amzn1.noarch (amzn-main)
               selinux-policy = 3.10.0-98.23.amzn1
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: systemd-units
Error: Package: docker-engine-1.12.3-1.el7.centos.x86_64 (dockerrepo)
           Requires: libseccomp.so.2()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by thaJeztah** [comment]
Looks like you're installing on a system where a docker package is installed that's packaged / shipped through another repository;

```
Error: docker-engine conflicts with docker-1.9.1-1.2.amzn1.x86_64
```

Can you try;

- uninstalling the existing "docker" package
- Update your system
- then install the docker 1.12 packages again?

**Comment by penhauer-xiao** [comment]
As of https://docs.docker.com/engine/installation/linux/centos/
I have been update my system, but this issue is same, Could you tell my how to update my Centos on aws.

Or tell me how to update selinux-policy from 3.10.0-98.23.amzn1.noarch (amzn-main) to  3.13.1-23.

**Comment by thaJeztah** [comment]
I suspect it's not updating the selinux-policy because there is a version of docker from another repository installed. please remove that package before installing the package from our repository.

Also keep in mind that the GitHub issue tracker is not a support forum (https://forums.docker.com are better suited for those)

**Comment by penhauer-xiao** [comment]
Ok, thanks @thaJeztah , I know, The forum are better suited for this
