### ISSUE TITLE
Cannot mount /run/docker/plugins when in userns enabled Docker daemon

### ISSUE THREAD

**Issue by akalipetis** [docker/docker#27935]
**Description**

Cannot mount `/run/docker/plugins` inside a container, when running the daemon with user namespaces.

**Steps to reproduce the issue:**
1. Create a Docker daemon with user namespaces enabled
2. Run `docker run --rm -v /run/docker/plugins/:/run/docker/plugins/ alpine sh`

**Describe the results you received:**

The exception thrown is:

```
docker: Error response from daemon: oci runtime error: rootfs_linux.go:53: mounting "/run/docker/plugins" to rootfs "/mnt/docker/1001.1001/overlay2/70df3cf9d4375ad357af1be7537f73c6571b10302b99c9b2b27db4121df9bbe0/merged" caused "stat /run/docker/plugins: permission denied".
```

**Describe the results you expected:**

The container running without issues.

**Additional information you deem important (e.g. issue happens only occasionally):**

Creating a custom `tmpfs` and trying to reproduce, does not throw the error:

1. `mkdir /mnt/tmpfs`
2. `mount -t tmpfs -o size=512m tmpfs /mnt/tmpfs/`
3. `mkdir /mnt/tmpfs/some`
4. `docker run --rm -v /mnt/tmpfs/some:/mnt/tmpfs/some alpine sh`

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 56
 Running: 51
 Paused: 0
 Stopped: 5
Images: 743
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-42-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.675 GiB
Name: ip-10-0-0-233
ID: 5CYV:KOEG:JQNT:MCEQ:M33P:ALDA:3YXQ:WTV4:HQTO:V4MT:J4WX:DHP4
Docker Root Dir: /mnt/docker/1001.1001
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* AWS, `ami-ec3acf83`
* Zone eu-central-1

**Possibly related issues**

* #27629

**Comment by thaJeztah** [comment]
ping @estesp 

I think this may be expected; @akalipetis can you explain the use case? Bind-mounting host-directories and using user-namespaces sounds a bit contradictory, as user-namespaces is exactly _meant_ to not allow accessing anything on the host that requires root access

**Comment by estesp** [comment]
The problem is that the path must be readable by the remapped root user inside the container, and the permissions of `/run/docker/plugins` are too restrictive to allow a high UID to read the path (hence the message about `stat` failing in the error).  If it can't read it, it can't mount it inside the container, ignoring other potential problems with the ownership mismatch.

A temporary workaround to validate this is to allow "other" to read/execute the full path: `chmod o+rx` the path elements that are too restrictive, then try again. Once it is traversable by the high UID, the mount should work.

**Comment by akalipetis** [comment]
That's correct @estesp - I can't see an obvious workaround this. I'll close this, as it's not a bug of Docker IMO. Feel free to reopen though if you believe this would need special attention/tracking somehow.

**Comment by akalipetis** [comment]
@thaJeztah - in regards to the use-case, I wanted to start a Docker plugin inside a container. There seems to be more issues than this one though for this, especially for AuthZ plugins, so I won't stick with this approach for now.

**Comment by thaJeztah** [comment]
@akalipetis thanks, understood
