### ISSUE TITLE
Docker engine swarm mode all manager nodes

### ISSUE THREAD

**Issue by viveky4d4v** [docker/docker#27943]
I have started docker engine in swarm mode since compose is not yet fully integrated with swarm/swarm mode .

I need a fault tolerance of 2 & I know that manager nodes are workers as well so will it be fine if i go with all 5 as manager nodes ?
I saw some strange behaviour while using all masters like services fail intermittently , ingress LB doesn't work on all nodes sometimes i.e the published port doesn't respond on all nodes.

Is this behaviour expected, what do you suggest ?

**Comment by cpuguy83** [comment]
Closing since this isn't really an issue.

> so will it be fine if i go with all 5 as manager nodes ?
The more managers you have, the more traffic there is, the slower things are, etc


> Is this behaviour expected, what do you suggest ?
ingress should work on all nodes, regardless of worker/manager.
Please make sure you are using the latest release (1.12.3). If you find a specific problem, do open an issue.

Thanks!

**Comment by viveky4d4v** [comment]
@cpuguy83 - Thanks for the info . 

I am using "Docker version 1.12.3, build 6b644ec "  . 

May be the issue caused due to what you told -"The more managers you have, the more traffic there is, the slower things are, etc" .

**Comment by cpuguy83** [comment]
ping @mrjana 
There may still be an open issue where some people are hitting this problem, but I'm not sure.... but it's not likely the number of managers that's causing you issues.

Note that we do recommend managers to be run with `--availability=drain` so that they are not considered when scheduling tasks. This of course means you need nodes dedicated to being managers.

**Comment by mrjana** [comment]
@viveky4d4v Did you see ingress LB being flaky while there are more managers and not flaky when there are less managers? There should not be any issue with more managers as far as ingress LB is concerned. Please check your daemon logs to make sure there are no gossip related errors.

**Comment by viveky4d4v** [comment]
@mrjana I moved to a low manager setup i.e one manager & two workers . 

I created 3 replicas of my python container & nginx in global mode . Everything went fine in the start & i was able to see published port responding on all the nodes but after updating the python service replica to 1 it stopped working . 

Docker version - 

     Docker version 1.12.3, build 6b644ec

Suspected daemon log - 

       time="2016-11-01T16:18:13.618938196Z" level=error msg="Invalid concurrent query count" 
       time="2016-11-01T16:18:13.619858712Z" level=error msg="Invalid concurrent query count" 

Nginx logs -

    2016/11/01 16:33:34 [warn] 5#5: *118 upstream server temporarily disabled while connecting to      upstream, client: 10.10.10.13, server: localhost, request: "GET / HTTP/1.1", upstream: "http://10.10.10.5:8002/", host: "192.168.99.13"
  

I redeployed the services again with singe replica & it worked fine . 
This certainly is an issue & i believe something similar might have happened in my multi master setup .
I will try to reproduce it but just have a look if something is weird or unexpected.

**Comment by viveky4d4v** [comment]
FYI - I was not able to reproduce it .  The difference is i am not able to see below logs in daemon this time - 


   time="2016-11-01T16:18:13.618938196Z" level=error msg="Invalid concurrent query count" 
   time="2016-11-01T16:18:13.619858712Z" level=error msg="Invalid concurrent query count"
