### ISSUE TITLE
Gelf driver ignored

### ISSUE THREAD

**Issue by tronicum** [docker/docker#27944]
I am using fedora 24,
Docker 1.12.3 from docker rpm repo

**Steps to reproduce the issue:**
1. Install above setup
2. systemd file starts with "/usr/bin/docker daemon --log-driver=gelf --log-opt gelf-address=udp://192.168.<my.ip>:5000 --log-opt tag="SWM-DEV-NODE1" <more oprtions"
3. If u start docker, logs are written tou journald instead forwarded to the logserver 

**Describe the results you received:**
ov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.550650543+01:00" level=info msg="2016/11/01 12:32:26 [INFO] serf: EventMemberJoin: dev-node1 <mysubnet>.11\n"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.554994822+01:00" level=info msg="2016/11/01 12:32:26 [INFO] serf: EventMemberJoin: dev-node2 <mysubnet>\n"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.555267419+01:00" level=info msg="2016/11/01 12:32:26 [INFO] serf: EventMemberJoin: dev-node3 <mysubnet>\n"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.555358550+01:00" level=warning msg="2016/11/01 12:32:26 [WARN] memberlist: Refuting an alive message\n"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.555422498+01:00" level=info msg="2016/11/01 12:32:26 [INFO] serf: EventMemberJoin: dev-node5<mysubnet>15\n"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.555541433+01:00" level=info msg="2016/11/01 12:32:26 [INFO] serf: EventMemberJoin: dev-node4 <mysubnet>.14\n"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.566136262+01:00" level=error msg="failed to create osl sandbox while trying to restore sandbox f770979: failed to create a netlink handle: failed to set into net
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.566196888+01:00" level=error msg="failed to create osl sandbox while trying to restore sandbox 57fa67b: failed to create a netlink handle: failed to set into net
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.566398274+01:00" level=error msg="failed to create osl sandbox while trying to restore sandbox 67d49ac: failed to create a netlink handle: failed to set into net
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.566441278+01:00" level=error msg="failed to create osl sandbox while trying to restore sandbox bbc8666: failed to create a netlink handle: failed to set into net
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.566476040+01:00" level=error msg="failed to create osl sandbox while trying to restore sandbox eacfe85: failed to create a netlink handle: failed to set into net
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.593836019+01:00" level=info msg="There are old running containers, the network config will not take affect"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.603823973+01:00" level=info msg="Loading containers: done."
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.603884653+01:00" level=info msg="Daemon has completed initialization"
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.603903586+01:00" level=info msg="Docker daemon" commit=6b644ec graphdriver=overlay version=1.12.3
Nov 01 12:32:26 dev-node1 docker[21341]: time="2016-11-01T12:32:26.615240467+01:00" level=info msg="API listen on [::]:2376"

**Describe the results you expected:**
Logging forwarded to logstash server, configured with GELF plugin
Port is reachable, I can sent input with netcat to that daemon

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 9
 Running: 5
 Paused: 0
 Stopped: 4
Images: 68
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.6.4-301.fc24.x86_64
Operating System: Fedora 24 (Twenty Four)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.851 GiB
Name: dev-node1
ID: E6XN:WVZN:66HN:QYAT:RYPA:E3TX:GESB:CVHB:VRDX:MFFI:RQTV:5ZZX
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://myproxy:8080
Https Proxy: http://myproxy:8080
No Proxy: 127.0.0.1,localhost,.dmz.mydomain
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Cluster Store: consul://localhost:8500
Cluster Advertise: <mysubnet>.11:2376
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
running on vmware

**Comment by cpuguy83** [comment]
The logdriver option is to set the default log driver for containers.
Docker sends its own logs logs to stderr.

Closing since this is a non-issue.
