### ISSUE TITLE
Docker 1.12.1 macOSX crash

### ISSUE THREAD

**Issue by sylvainmouquet** [docker/docker#27954]
With MacOS Sierra version 10.12.1 (16B2555)
With docker version 1.12.1 (build : 12133)

Docker crashs brutally all containers are stopped
I have 70% of memory used and 50% of SWAP perhaps the problem occures when the system is out of memory
When i run `docker service ls` the services are listed but the service are not starting.
if i try to remove a service i have this error 
`docker service rm 04uyg9041ea
`Error response from daemon: rpc error: code = 4 desc = context deadline exceeded

The solution is to reset docker to factory defaults, reconfigure it and it's ok

> Nov  1 17:19:13   Docker[14015]: sendmsg ok
Nov  1 17:19:13   Docker[475]: Created instance tcp:0.0.0.0:389:tcp:172.18.0.2:389
Nov  1 17:48:56   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:07   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:07   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:11   Docker[443]: NSUserDefaults.synchronise() returned false
Nov  1 17:57:12   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:34   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:34   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:43   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:43   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:45   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:45   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:47   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:47   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:48   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:48   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:48   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:48   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:57:48   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:57:48   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 17:58:41   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 17:58:41   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:00:21   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:00:21   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:00:53   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:02:32   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:03:18   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:03:18   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:03:26   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:03:26   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:03:29   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:03:29   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:05:52   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:05:52   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:05:52   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:05:52   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:05:52   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:05:52   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:05:52   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:05:52   Docker[475]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 18:05:52   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:05:52   Docker[475]: TCP 192.168.65.2:42594 > 192.168.0.42:8082 proxy failed with flow proxy b: Connection refused
Nov  1 18:11:26   Docker[472]: Fatal unexpected exception: Socket.Closed
Nov  1 18:11:26   Docker[466]: Reap com.docker.osxfs (pid 472): exit status 1
Nov  1 18:11:26   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:11:27   Docker[466]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 477)
Nov  1 18:11:27   Docker[466]: Signal terminated to com.docker.driver.amd64-linux (pid 477)
Nov  1 18:11:27   Docker[477]: sending SIGTERM to com.docker.hyperkit pid 485
Nov  1 18:11:30   Docker[475]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 18:11:43   Docker[475]: DHCPRELEASE without request ip
Nov  1 18:11:51   Docker[477]: virtio-net-vpnkit: initialising, opts="uuid=ceef371d-aa55-499e-b5c2-335821c75d1d,path=/Users/sylvain/Library/Containers/com.docker.docker/Data/s50,macfile=/Users/sylvain/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/mac.0"
Nov  1 18:11:51   Docker[477]: Interface will have uuid ceef371d-aa55-499e-b5c2-335821c75d1d
Nov  1 18:11:51   Docker[477]: Connection established with MAC=c0:ff:ee:c0:ff:ee and MTU 1500
Nov  1 18:11:51   Docker[477]: virtio-9p: initialising path=/Users/sylvain/Library/Containers/com.docker.docker/Data/s40,tag=db
Nov  1 18:11:51   Docker[477]: virtio-9p: initialising path=/Users/sylvain/Library/Containers/com.docker.docker/Data/s51,tag=port
Nov  1 18:11:51   Docker[477]: linkname /Users/sylvain/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Nov  1 18:11:51   Docker[477]: COM1 connected to /dev/ttys000
Nov  1 18:11:51   Docker[477]: COM1 linked to /Users/sylvain/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
Nov  1 18:11:51   Docker[475]: PPP.listen: closing connection
Nov  1 18:11:51   Docker[466]: Reap com.docker.driver.amd64-linux (pid 477): exit status 0
Nov  1 18:11:51   Docker[476]: VM shutdown at 2016-11-01 18:11:51 +0100 CET
Nov  1 18:11:51   Docker[466]: Stop 2 children with order 2: com.docker.osxfs (pid 472), com.docker.slirp (pid 475)
Nov  1 18:11:51   Docker[466]: Signal terminated to com.docker.slirp (pid 475)
Nov  1 18:11:51   Docker[466]: Reap com.docker.slirp (pid 475): signal: terminated
Nov  1 18:11:51   Docker[466]: Starting com.docker.osxfs, com.docker.slirp, com.docker.driver.amd64-linux
Nov  1 18:11:51   Docker[466]: Start com.docker.osxfs (pid 14890)
Nov  1 18:11:51   Docker[466]: Start com.docker.slirp (pid 14891)
Nov  1 18:11:51   Docker[466]: Start com.docker.driver.amd64-linux (pid 14892)
Nov  1 18:11:51   Docker[14890]: Logging to Apple System Log
Nov  1 18:11:51   Docker[14891]: Logging to Apple System Log
Nov  1 18:11:51   Docker[14891]: Setting handler to ignore all SIGPIPE signals
Nov  1 18:11:51   Docker[14891]: vpnkit version 0c7cf02 with hostnet version local  uwt version 0.0.3 hvsock version 0.10.0 
Nov  1 18:11:51   Docker[14891]: starting port_forwarding port_control_url:fd:4 max_connections:Some 900 vsock_path:/Users/sylvain/Library/Containers/com.docker.docker/

**Comment by dnephin** [comment]
I believe this is fixed in 1.12.2.

**Comment by sylvainmouquet** [comment]
I have tried the version 1.12.3 and same result

> docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

> Nov  1 19:21:14  Docker[17570]: Created instance tcp:0.0.0.0:8085:tcp:172.18.0.2:8085
Nov  1 19:22:24  Docker[17570]: TCP 192.168.65.2:55740 > 192.168.0.42:8082 proxy failed with flow proxy b: Connection refused
Nov  1 19:23:36  Docker[15446]: NSUserDefaults.synchronise() returned false
Nov  1 19:36:37  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:36:39  Docker[17570]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 19:36:39  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:37:39  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:37:39  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:38:16  Docker[17570]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 19:38:16  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:38:51  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:38:51  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:41:01  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:41:36  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:41:47  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:43:03  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:43:37  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:44:00  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:46:40  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:48:24  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:48:24  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:48:45  Docker[17570]: Socket.TCPV4.write connected TCP: caught Uwt.Uwt_error(Uwt.EPIPE, "write", "") returning Eof
Nov  1 19:48:45  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:49:01  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:52:32  Docker[17569]: Fatal unexpected exception: Socket.Closed
Nov  1 19:52:32  Docker[15465]: Reap com.docker.osxfs (pid 17569): exit status 1
Nov  1 19:52:33  Docker[15465]: Stop 1 children with order 1: com.docker.driver.amd64-linux (pid 17571)
Nov  1 19:52:33  Docker[15465]: Signal terminated to com.docker.driver.amd64-linux (pid 17571)
Nov  1 19:52:33  Docker[17571]: sending SIGTERM to com.docker.hyperkit pid 17574
Nov  1 19:52:36  Docker[17570]: Socket.Stream: caught Uwt.Uwt_error(Uwt.ENOTCONN, "shutdown", "")
Nov  1 19:52:49  Docker[17570]: DHCPRELEASE without request ip

**Comment by justincormack** [comment]
This seems to be a Docker for Mac specific issue now, can you open an issue on https://github.com/docker/for-mac/issues and include a diagnostics link from the Diagnose option in the menu.

I am going to close the issue here as this does not look like an upstream docker issue any more but specific to Docker for Mac.
