### ISSUE TITLE
[upstream go] registry logout doesn't remove auth data

### ISSUE THREAD

**Issue by tophj-ibm** [docker/docker#27966]
I've been testing upstream docker with upstream go, and I currently get two failures on x86_64

```bash
----------------------------------------------------------------------
FAIL: docker_cli_logout_test.go:15: DockerRegistryAuthHtpasswdSuite.TestLogoutWithExternalAuth

docker_cli_logout_test.go:52:
    c.Assert(string(b), checker.Not(checker.Contains), privateRegistryURL)
... obtained string = "" +
...     "{\n" +
...     "\t\"auths\": {\n" +
...     "\t\t\"127.0.0.1:5000\": {}\n" +
...     "\t},\n" +
...     "\t\"credsStore\": \"shell-test\"\n" +
...     "}"
... substring string = "127.0.0.1:5000"


----------------------------------------------------------------------
FAIL: docker_cli_logout_test.go:61: DockerRegistryAuthHtpasswdSuite.TestLogoutWithWrongHostnamesStored

docker_cli_logout_test.go:98:
    c.Assert(string(b), checker.Not(checker.Contains), fmt.Sprintf("\"https://%s\": {}", privateRegistryURL))
... obtained string = "" +
...     "{\n" +
...     "\t\"auths\": {\n" +
...     "\t\t\"127.0.0.1:5000\": {},\n" +
...     "\t\t\"https://127.0.0.1:5000\": {}\n" +
...     "\t},\n" +
...     "\t\"credsStore\": \"shell-test\"\n" +
...     "}"
... substring string = "\"https://127.0.0.1:5000\": {}"


----------------------------------------------------------------------
```

Comparing before and after, I can see the stored auth data looks like this after loging out with go1.7.3

{
	"auths": {},
	"credsStore": "shell-test"
}

So it looks like the auths section isn't properly getting cleared after logging out.

Steps to recreate:
1.) Build docker with upstream go instead of go1.7.3
2.) Run the integration tests

**Comment by thaJeztah** [comment]
ping @runcom @aaronlehmann PTAL

**Comment by aaronlehmann** [comment]
@tophj-ibm: My suspicion is that `(*nativeStore).Erase` gets an error from `client.Erase`, and returns before calling `c.fileStore.Erase`. This error would be printed out by the client (`WARNING: could not erase credentials: ...`), but would not cause the client to exit with a non-zero status.

Could you try modifying the tests to print the output of the `logout` commands and see if such an error is being returned?

**Comment by tophj-ibm** [comment]
sure thing

**Comment by tophj-ibm** [comment]
@aaronlehmann definitely seems to be the case, unfortunately the error is not so helpful. 
```sh
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: ``
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: ``
WARNING: could not erase credentials: error erasing credentials - err: exit status 1, out: ``
```

**Comment by aaronlehmann** [comment]
Thanks for confirming.

Since the external helper is in shell, it shouldn't be affected by using a different Go version. The only thing I can think of is that switching to golang master changes the json that the script receives, and that causes the script to fail.

I would try logging the input to the credential helper and comparing it between golang versions.

**Comment by tophj-ibm** [comment]
Thanks for the help! Turns out there is a syntax error with jq in the shell fixture that errors out on older versions. I'll go ahead and update it, and make some changes to the way the errors are handled because they currently aren't being returned correctly from docker-credentials.
