### ISSUE TITLE
Allow manual entries in File Sharing settings of Docker for Mac OSX

### ISSUE THREAD

**Issue by eanvafaei** [docker/docker#27971]
Currently, the only allowed method is selecting from a pop up, however, the pop up will not allow selecting volumes like /var or /etc but add them as /private/var or /private/etc. So if the docker config is set to use /var, as it's volume, it will fail to start.
This is a problem where there is a mix of Linux and Mac machines using docker and docker-compose to setup development environment.

**Comment by cpuguy83** [comment]
ping @dsheets

**Comment by thaJeztah** [comment]
This is specific to docker for Mac; can you reopen this in the docker for Mac issue tracker? https://github.com/docker/for-mac/issues

Thanks!

**Comment by dsheets** [comment]
This is a duplicate of docker/for-mac#412 which is on the roadmap for our GUI team. Sorry for the inconvenience and thanks for your patience!
