### ISSUE TITLE
[New Feature] support k/v store connection to read and write for swarm container service

### ISSUE THREAD

**Issue by o3o3o** [docker/docker#27977]
I already know that it is not supported in swarm   from #25274.

But I wish the swarm mode support the internal k/v store connection to read and write just in swarm container.  
In many case we have to run Etcd/Consul cluster outside, if the k/v store cluster state is the synchronize  with swam mode,  it will simplify the user's project.

For security, I think we can split the k/v store into system and user data space.

**Comment by AkihiroSuda** [comment]
What's your problem in setting up etcd/consul via `docker service create`?

**Comment by o3o3o** [comment]
In our case, we run etcd cluster in docker swarm mode and  confd run in service container to get and update the service's setting .

It is not convenient that run etcd cluster in docker swarm mode. There are some thing we need to do:
1. Be sure to run 3+ etcd server on physical machine for cluster fault tolerance, instead 3+ etcd run in 3+ docker container which is in  one physical machine.
2. When add an etcd member, you have to execute command like [this](https://coreos.com/etcd/docs/latest/runtime-configuration.html#add-a-new-member), and then you should update the client(confd) setting connection which has already built in images. Although we can update the confd's setting with confd&etcd, but it is a trick not an normal solution.

For above 1: When running 3+ etcd server on different cluster node, you have to add etcd label for node to make sure one etcd only run on one real server.
```
docker node update --label etcd=etcd1 node1
docker node update --label etcd=etcd2 node2
docker node update --label etcd=etcd3 node3
```
Then start etcd1 servers:
```
       app="etcd1"
        docker service create \
            --env  ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379 \
            --env  ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379 \
            --env  ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380 \
            --env  ETCD_INITIAL_CLUSTER_TOKEN=${etcd-clustertoken} \
            --env  ETCD_INITIAL_CLUSTER_STATE=new \
            --constraint node.labels.etcd=${app} \
            --env  ETCD_NAME=${app} \
            --env  ETCD_ADVERTISE_CLIENT_URLS=http://${app}:2379 \
            --env  ETCD_INITIAL_ADVERTISE_PEER_URLS=http://${app}:2380 \
            --env  ETCD_INITIAL_CLUSTER="etcd1=http://etcd1:2380,etcd2=http://etcd2:2380,etcd3=http://etcd
3:2380" \
            --network mynet \
            --mount type=bind,src=/data/docker/etcd/${app},dst=/opt/etcd/ \
            --replicas=1  \
            --name ${app} ${REGISTRY}/etcd etcd
```
This is not simple, but all that we said above can be integrated  in docker swarm which already has k/v store. 
The etcd cluster number can be the same as the manager nodes, and the user  do not need to maintain the etcd cluster state.

**Comment by cpuguy83** [comment]
Swarm does not have a generic K/V store.
It uses raft to distribute an object store.

**Comment by cpuguy83** [comment]
While this sounds super convenient, I think this is not something people should be doing.

1. It unnecessarily complicates swarm
2. Unnecessarily ties your application to swarm

Swarmkit (and soon Docker) supports templating for certain commands now, meaning you can do stuff like: `docker swarm create --env TASK_ID={{ .Task.ID }}`.
This is basically exposing information that swarm already has for use by the application rather than stuffing application data into swarm.

WRT scheduling of etcd itself, I feel like this is a scheduling problem that can be fixed rather than adding tons of complexity to the object store.

**Comment by AkihiroSuda** [comment]
For fault tolerance, you will be able to use HA Schueduler.
It will be the default algorithm in 1.13.
https://github.com/docker/swarmkit/pull/1446
https://github.com/docker/swarmkit/issues/308

**Comment by thaJeztah** [comment]
I agree with @cpuguy83. In addition making Swarm potentially less stable by putting custom user data in the core mechanisms that drive Swarm is not something we want to do.

I'm gonna close this issue for that reason, but feel free to comment after
