### ISSUE TITLE
Challenge-response optimization to avoid pushing layers already in registry

### ISSUE THREAD

**Issue by JonathonReinhart** [docker/docker#27972]
The question is asked all the time: ["Why does docker push base image layers that are already on docker hub?"](https://forums.docker.com/t/why-does-docker-push-base-image-layers-that-are-already-on-docker-hub/2329/7)

The answer, of course, is in the case of private base images,
> you have to prove you have the layers you want to link to
- @dmp42

Here is an optimization I've not yet seen suggested:

- Distribution can provide a *challenge*.
- The Docker client can hash the concatenation of this challenge followed by the layer contents.
- Then instead of uploading the entire layer, the client can instead respond with this *response*.

Because a hash cannot be extended with blocks in an arbitrary order, the only way to compute the correct hash would be to actually own the content in question.

**Comment by dmp42** [comment]
I believe what you want has been implemented already (hence I'm going to close this - if you think I'm mistaken, please say so and I'll reopen).

Check "Cross Repository Blob Mount" in https://docs.docker.com/registry/spec/api/

I don't remember when that was shipped (calling @RichardScothern @aaronlehmann to the rescue).

**Comment by dmp42** [comment]
eg: IIRC, you basically say to the registry:

"Please mount layer X from image A, and here is my auth token that prove that I have read access to image A"

**Comment by JonathonReinhart** [comment]
@dmp42 Thanks for the quick response. Indeed that looks like a superior solution, as it avoids having to re-hash the layer, and instead relies upon the normal access checks.

That feature must have been added since the last time I read through that spec. I apologize for the noise.

**Comment by dmp42** [comment]
@JonathonReinhart no problem, and no apologies required, really. It's tough to track everything everyday :)

If you don't mind commenting on that forum thread so people reading it find the above ^ comments, that would help others.
