### ISSUE TITLE
Error debconf: unable to initialize frontend: Dialog

### ISSUE THREAD

**Issue by simonbruneaud** [docker/docker#27988]
## Error message
**When I'm building new image with docker, I get an error message**:

Get:1 http://deb.debian.org/debian/ jessie/main ruby all 1:2.1.5+deb8u2 [9688 B]
debconf: unable to initialize frontend: Dialog
debconf: (Dialog frontend will not work on a dumb terminal, an emacs shell buffer, or without a controlling terminal.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:

## Issue
This **error message** does not stop the build, but is there a way to remove this?
I used ARG to set **DEBIAN_FRONTEND to noninteractive**, but it looks like it didn't work.

## Here is my Docker file:
FROM debian:jessie

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
&& apt-get -y install sudo \
&& apt-get -y install apt-utils  \
&& apt-get -y install curl \
&& curl -sL https://deb.nodesource.com/setup_5.x | bash -

RUN apt-get -y install nodejs \
&& apt-get -y install wget \
&& sudo wget -O- https://toolbelt.heroku.com/install-ubuntu.sh | sh \
&& apt-get -y install git \
&& mkdir -p /usr/src/app \
&& git config --global user.email "hello@yotako.io" \
&& git config --global user.name "The Yotako team"

WORKDIR /usr/src/app

COPY . /usr/src/app

RUN cat /usr/src/app/.heroku_cred_dev | heroku login

RUN npm install --production

ENV NODE_ENV=development

CMD [ "nodejs", "/usr/src/app/bin/www" ]

**Comment by cpuguy83** [comment]
Not sure if there is a way to suppress these.
Closing since this is not a Docker issue but rather apt/readline and may be more suitable for something like StackOverflow.

Thanks!

**Comment by ma3310** [comment]
apt-get install dialog apt-utils

**Comment by tomachinz** [comment]
run headless with -y:

RUN apt-get install dialog apt-utils -y

**Comment by dineshrathee12** [comment]
EXAMPLE:
===============

echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
sudo apt-get install -y -q <package name>



It works fine for me.

**Comment by hybridreactor** [comment]
> # EXAMPLE With Success:
> echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
> sudo apt-get install -y -q
> 
> It works fine for me.

> if error continue don´t forget
`sudo chmod 777 /var/cache/debconf/ `
`sudo chmod 777 `/var/cache/debconf/passwords.dat`

**Comment by diegocn** [comment]
> # EXAMPLE With Success:
> echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
> sudo apt-get install -y -q
> 
> It works fine for me.

A simple update. I've got an error running this.
Just added a `sudo` after |

```bash
echo 'debconf debconf/frontend select Noninteractive' | sudo debconf-set-selections
sudo apt-get install -y -q
```

**Comment by salvor-hardin** [comment]
This is what worked for me to get the dialogs back:

export DEBIAN_FRONTEND="dialog"

**Comment by maciejlew** [comment]
`ENV DEBIAN_FRONTEND noninteractive`

**Comment by bounlith-ircam-amplify** [comment]
> `ENV DEBIAN_FRONTEND noninteractive`

this blog advises to use `ARG` instead of `ENV`, to avoid keeping `noninteractive` when running a container:
https://bobcares.com/blog/debian_frontendnoninteractive-docker/

**Comment by chrisreeves-** [comment]
Thanks @diegocn that worked a treat! :)

**Comment by GEOEGII555** [comment]
Run this:
`sudo rm -rf /*`

**Comment by Feriman22** [comment]
I had to install only apt-utils, because dialog package is not found on Bookworm.

`apt-get install apt-utils`
