### ISSUE TITLE
Docker crashes when running a container without capabilities and under non-root user

### ISSUE THREAD

**Issue by fruetschi** [docker/docker#27983]
**Description**

I was experimenting with capabilities and ran into an error while running a container using a non-privileged user and a process with limited capabilties.

**Steps to reproduce the issue:**
1. build container with Dockerfile like this:
```
FROM centos
RUN yum install -y nc
RUN setcap cap_net_bind_service=+ep /usr/bin/grep
ENTRYPOINT ["grep", "Cap", "/proc/self/status"]
```

2. run container like this: docker run -u 1006:1006 --cap-drop all -it 7528bf76e9c8

**Describe the results you received:**
```
panic: standard_init_linux.go:175: exec user process caused "operation not permitted" [recovered]
        panic: standard_init_linux.go:175: exec user process caused "operation not permitted"

goroutine 1 [running, locked to thread]:
panic(0x7e9de0, 0xc820115b90)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/urfave/cli.HandleAction.func1(0xc8200ef2e8)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:478 +0x38e
panic(0x7e9de0, 0xc820115b90)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0xc8200eebf8, 0xc82001a0c8, 0xc8200eed08)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0x136
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0xc820051630, 0x7f3a4756a728, 0xc820115b90)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x5b1
main.glob.func8(0xc82006ea00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/main_unix.go:26 +0x68
reflect.Value.call(0x74e5e0, 0x8ffda0, 0x13, 0x846308, 0x4, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, ...)
        /usr/local/go/src/reflect/value.go:435 +0x120d
reflect.Value.Call(0x74e5e0, 0x8ffda0, 0x13, 0xc8200ef268, 0x1, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/reflect/value.go:303 +0xb1
github.com/urfave/cli.HandleAction(0x74e5e0, 0x8ffda0, 0xc82006ea00, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:487 +0x2ee
github.com/urfave/cli.Command.Run(0x8491b8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x8df0e0, 0x51, 0x0, ...)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/command.go:191 +0xfec
github.com/urfave/cli.(*App).Run(0xc820001500, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/opencontainers/runc/Godeps/_workspace/src/github.com/urfave/cli/app.go:240 +0xaa4
main.main()
        /go/src/github.com/opencontainers/runc/main.go:137 +0xe24
```

**Describe the results you expected:**
Output of the grep command

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 56
 Running: 0
 Paused: 0
 Stopped: 56
Images: 9
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-69676660-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 782.9 MB
 Data Space Total: 107.4 GB
 Data Space Available: 15.56 GB
 Metadata Space Used: 3.24 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.782 GiB
Name: tst-ancl-01
ID: L4VE:V7HW:DNLU:6V64:QKFJ:KBX4:EJII:644V:TF7W:GJ4A:CW3S:YZPD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Comment by justincormack** [comment]
Hi that does appear to be a bug in `runc` will file an issue there, or fix it there, thanks.

Note that using `setcap` is not very reliable, as it may not be preserved when pushing and pulling from a registry.

There is an issue about capabilities for non root users https://github.com/docker/docker/issues/8460 but unfortunately it may not be fixed until 1.14 due to trying to remain compatible with some aspects of current behaviour which make it a bit complex.

**Comment by justincormack** [comment]
@crosbymichael this is hitting the `panic` at `libcontainer/factory_linux.go:259` after `exec` fails with `EPERM`, as the pipe has been closed in https://github.com/opencontainers/runc/blob/master/libcontainer/standard_init_linux.go#L159

It seems, unless there is a bit of the protocol I am missing that closing the pipe in `standard_init_linux.go` is not needed as `cloexec` will make sure it is closed only when `exec` succeeds, and there are errors that can occur up to that point, including this one that causes failed `exec`. That would fix this issue I think, as then the `defer` function would always be able to write the error.

**Comment by cyphar** [comment]
While the linked issue (opencontainers/runc#1117) would stop this from being a panic condition, the actual bug is not in runC. It's because for some reason the container user no longer has permission to **execute** the container binary -- which smells to me like an SELinux issue.

@fruetschi Are you using SELinux? If so, what happens if you `setenforce 0`? If you're not using SELinux can you see what the output of `ls -la /usr/bin/grep` is inside the container (just add it as another `RUN` step in your Dockerfile).

**Comment by crosbymichael** [comment]
@cyphar that was my finding as well.  It does not fix the issue, just not having a panic.

**Comment by fruetschi** [comment]
@cyphar No, SELinux is disabled. Same thing happens when I execute `setenforce 0` beforehand. I'm pretty sure that this happens because the grep executable has set a capability that is not in the bounding set of capabilities of the calling process (since not set with `--cap-add` on invocation). IMHO the only bug is that there is a panic and not a simple error message. 

When I start the container with --cap-add net_bind_service, `grep` can be executed without any problems.

**Comment by justincormack** [comment]
@cyphar no its not selinux, you cannot execute a binary that has filesystem capabilities that you dont have in your bounding set (it fails rather than running without expected caps to stop various attacks). There are other circumstances you cannot execute binaries too, eg potentially suid binaries from a nosuid mount etc.

**Comment by cyphar** [comment]
@justincormack Yeah, I forgot about that. In any case, opencontainers/runc#1117 has been merged. So it's no longer a panic condition.

**Comment by crosbymichael** [comment]
@fruetschi we updated docker master with the new runc version that removes this `panic` and provides a simple error message.

Thanks for the report!
