### ISSUE TITLE
Docker wait, live restore, and restarting dockerd

### ISSUE THREAD

**Issue by sakserv** [docker/docker#27987]
Docker wait exits with an EOF error during dockerd restart when live restore is enabled. This undesired behavior as it breaks the expected contract for docker wait.

**Steps to reproduce the issue:**
1. Enable live restore
2. Start a container and wait: docker wait $(docker run -d centos tail -f /dev/null)
3. Restart dockerd via systemd: systemctl restart docker 

**Describe the results you received:**
The docker wait exits with the following error:
```
An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/c11692777816e44049d610c4ad358a24eefbff707cdbd85c24df3d153c80401e/wait: EOF
```

**Describe the results you expected:**
Docker wait should "Block until a container stops, then print its exit code" - as intended.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 3
 Paused: 0
 Stopped: 4
Images: 3
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-253:0-453953286-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 5.111 GB
 Data Space Total: 107.4 GB
 Data Space Available: 89.5 GB
 Metadata Space Used: 7.848 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 11.5 GiB
Name: server.sakserv.org
ID: H6UV:LUN3:N5Z3:NACA:YQJC:IER7:H2QR:VXWQ:7PXK:22H6:4RTI:R3GY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: hwxycloud
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
If you get an EOF why not just re-connect?

There is no way to handle this. `docker wait` is a client command, if the daemon goes down, the connection will be cut.
Technically nothing to do with live-restore... do the same thing w/o live-restore and just `kill -9` the daemon so it can't shutdown the containers and you will get an EOF as well.

Now `docker wait` could implement some re-connect scheme, but this is potentially breaking for existing users since this has been the behavior forever. It would be better to handle this as needed.

A more reliable approach may be to talk to containerd directly.
The docker package does include a tool to do this: `docker-containerd-ctr`. The default socket location is `/run/docker/libcontainerd/docker-containerd.sock`

**Comment by dnephin** [comment]
It sounds like this is working as expected, so closing this issue.

**Comment by sakserv** [comment]
I would have to disagree with there being no way to handle this. As you said in your reply, why not just reconnect on EOF? Either I handle the reconnect or the docker client handles the reconnect. My preference would be the docker client, of course. :)

At a minimum there should be a warning in the live restore docs, as regardless of how kill -9 acted in the past, this behavior is surprising.

**Comment by sakserv** [comment]
@cpuguy83 Thank you for the feedback. I've taken your advice to heart and began looking at other approaches that are more reliable. I must say this is proving difficult.

Unless I'm missing something, if docker is stopped (via `systemctl stop docker` in my case), `docker-containerd-ctr` also doesn't work?

An alternative to using `docker wait` would be something like the following:
* `docker run`
* `docker inspect` to get the pid
* send the null signal (`kill -0`) in a loop until the process completes
* `docker inspect` to get the exit status

Obviously this has similar issues as docker wait, if docker is down I won't be able to get the final exit status (plus the associated issues with the null signal check due to pid reuse, etc).

Ultimately, `docker wait` has information that cannot be reliably retrieved in any manner if the docker daemon is restarted/down. This is the crux of the issue in my mind.

I wanted to get your feedback on a potential workaround. Docker run has the `--cidfile` option that can be used to store the container ID in a file. What is the feasibility of a similar option for exit status, ie `--exitstatusfile`? This would ensure that even if docker was down, we would have a file that we could use to retrieve the processes exit status once the null signal loop completed. It would also allow for better liveliness checks giving us both a pid and file to use as guards.

**Comment by cpuguy83** [comment]
If you start containerd yourself, docker will not stop it when it exits.... so that's one option.

You can also use `docker-runc` to check the state of the container.
