### ISSUE TITLE
cannot start dockerd on upgraded server 2016

### ISSUE THREAD

**Issue by clarity99** [docker/docker#27984]
I have a 2012r2 server in production that I've now upgraded to 2016 in order to test the container functionality. 

However the dockerd is not starting. If I run it from command line with --debug I get this:
```

time="2016-11-01T12:34:48.890755600+01:00" level=error msg="Resolver Setup/Start failed for container none, \"json: cannot unmarshal array into Go value of type hcsshim.HNSNetwork\""
time="2016-11-01T12:34:48.901737200+01:00" level=debug msg="Allocating IPv4 pools for network nat (c9baf78a40c8ae87a03ef07942ca9a6c58d244823487bae7c81ba9fd22dcab0b)"
time="2016-11-01T12:34:48.901737200+01:00" level=debug msg="RequestPool(LocalDefault, , , map[], false)"
time="2016-11-01T12:34:48.902737200+01:00" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.docker.network.gateway])"
time="2016-11-01T12:34:48.903736800+01:00" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Subnets\":[{\"AddressPrefix\":\"0.0.0.0/0\",\"GatewayAddress\":\"0.0.0.0\"}]} Address Space=[{0.0.0.0/0 0.0.0.0 []}]"
time="2016-11-01T12:34:50.429431400+01:00" level=debug msg="releasing IPv4 pools from network nat (c9baf78a40c8ae87a03ef07942ca9a6c58d244823487bae7c81ba9fd22dcab0b)"
time="2016-11-01T12:34:50.429431400+01:00" level=debug msg="ReleaseAddress(0.0.0.0/0, 0.0.0.0)"
time="2016-11-01T12:34:50.431454300+01:00" level=debug msg="ReleasePool(0.0.0.0/0)"
time="2016-11-01T12:34:50.431454300+01:00" level=debug msg="starting clean shutdown of all containers..."
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Unspecified error

```

I have all of the updates installed as of 1.11.2016.  Docker version:
docker version:
Version: 1.12.2-cs2-ws-beta
API version: 1.25
Go version: go1.7.1
Git commit: 050b611

I've also tried with 1.2.13 with the same results.

The VM is running under Hyper-V on Windows 10 Anniversary update.

I've also tried doing a fresh install from the same media and there it's working fine. So it has to be something to do with the upgrade from 2012r2, but I cannot figure what it could be.

I've uninstalled the container feature and reinstalled it, but the problem remains. 
Anything else I can do to help troubleshoot this?

**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by msabansal** [comment]
Thanks for the opening the bug. Can you please collect some traces:

```
ipconfig /all
Get-VmSwitch
Get-NetNat
netsh trace start globallevel=5 provider=Microsoft-Windows-Host-Network-Service provider={93f693dc-9163-4dee-af64-D855218af242}  report=di
<repro>
netsh trace stop

```

**Comment by clarity99** [comment]
`
PS C:\Users\Administrator> ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : hetzner
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No

Ethernet adapter Ethernet 5:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter #2
   Physical Address. . . . . . . . . : 00-15-5D-01-63-11
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::24ca:17a:b033:c1dd%17(Preferred)
   IPv4 Address. . . . . . . . . . . : 192.168.1.141(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Wednesday, November 2, 2016 8:36:19 PM
   Lease Expires . . . . . . . . . . : Thursday, November 3, 2016 8:36:18 PM
   Default Gateway . . . . . . . . . : 192.168.1.1
   DHCP Server . . . . . . . . . . . : 192.168.1.1
   DHCPv6 IAID . . . . . . . . . . . : 318772573
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1F-AB-CB-33-00-15-5D-01-63-11
   DNS Servers . . . . . . . . . . . : 192.168.1.1
   Primary WINS Server . . . . . . . : 192.168.1.1
   NetBIOS over Tcpip. . . . . . . . : Enabled

Tunnel adapter isatap.{AEE77D12-43D1-4BF4-B8BF-DC9A82AC9F19}:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Microsoft ISATAP Adapter
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes

Tunnel adapter Teredo Tunneling Pseudo-Interface:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Teredo Tunneling Pseudo-Interface
   Physical Address. . . . . . . . . : 00-00-00-00-00-00-00-E0
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : 2001:0:5ef5:79fb:3810:f72:a670:5857(Preferred)
   Link-local IPv6 Address . . . . . : fe80::3810:f72:a670:5857%2(Preferred)
   Default Gateway . . . . . . . . . : ::
   DHCPv6 IAID . . . . . . . . . . . : 385875968
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1F-AB-CB-33-00-15-5D-01-63-11
   NetBIOS over Tcpip. . . . . . . . : Disabled
PS C:\Users\Administrator>
PS C:\Users\Administrator> Get-VMSwitch
PS C:\Users\Administrator> Get-NetNat
PS C:\Users\Administrator>



`

Trace is here https://dl.dropboxusercontent.com/u/153770/NetTrace.etl

Compared to the machine with a clean install the Get-* commands are behaving quite differently.
I had remote access role installed on this machine, but I tried removing it, but the result is the same.

**Comment by bison92** [comment]
Hi,

I've just tried to install Docker for windows on Windows 2016 Server and it said it is not possible to install because of OS version. See the screenshot attached. 

Regards,
![docker no install](https://cloud.githubusercontent.com/assets/1010516/19986194/020d1cd4-a216-11e6-87e1-a514de4f41be.png)

**Comment by msabansal** [comment]
@bison92 That is a different issue. Docker is natively supported on windows. Docker for windows is a different solution.
@clarity99 Thanks for the info. Can you please check what does get-Service winnat gives. Seems like we are not able to setup winnat properly

MessageNumber	DiagnosisTypes	Timestamp	TimeElapsed	ResponseTime	Source	Destination	Module	Summary	TopModule	TopSummary	
35	None	2016-11-02T15:19:28.7235656					Microsoft_Windows_Host_Network_Service	HNS failed to create winnat instance with error '0x80041031', external ip prefix = '192.168.1.141/24', internal ip prefix = '172.27.32.1/20' and nat name = 'H95b2ac4b-ad4f-41c9-ad3f-7e9c05147559'.	Microsoft_Windows_Host_Network_Service	HNS failed to create winnat instance with error '0x80041031', external ip prefix = '192.168.1.141/24', internal ip prefix = '172.27.32.1/20' and nat name = 'H95b2ac4b-ad4f-41c9-ad3f-7e9c05147559'.

**Comment by clarity99** [comment]
Hmm, it was stopped. I turned it on and rerun dockerd but with same results:

```
PS C:\Users\Administrator> get-Service winnat

Status   Name               DisplayName
------   ----               -----------
Stopped  winnat             Windows NAT Driver


PS C:\Users\Administrator> Start-Service winnat
PS C:\Users\Administrator> get-Service winnat

Status   Name               DisplayName
------   ----               -----------
Running  winnat             Windows NAT Driver


PS C:\Users\Administrator> dockerd --debug
time="2016-11-04T10:13:33.849139700+01:00" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"

time="2016-11-04T10:13:33.853573300+01:00" level=debug msg="Stackdump - waiting signal at Global\\docker-daemon-7928"
time="2016-11-04T10:13:33.853573300+01:00" level=info msg="Windows default isolation mode: process"
time="2016-11-04T10:13:33.853573300+01:00" level=debug msg="Using default logging driver json-file"
time="2016-11-04T10:13:33.853573300+01:00" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\wi
ndowsfilter"
time="2016-11-04T10:13:33.855733900+01:00" level=debug msg="Using graph driver windowsfilter"
time="2016-11-04T10:13:33.857217900+01:00" level=debug msg="Max Concurrent Downloads: 3"
time="2016-11-04T10:13:33.858924700+01:00" level=debug msg="Max Concurrent Uploads: 5"
time="2016-11-04T10:13:33.885307600+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-11-04T10:13:33.888802800+01:00" level=debug msg="Option DefaultDriver: nat"
time="2016-11-04T10:13:33.888802800+01:00" level=debug msg="Option DefaultNetwork: nat"
time="2016-11-04T10:13:33.929736700+01:00" level=debug msg="Network Response : [  ]"
time="2016-11-04T10:13:33.930962100+01:00" level=debug msg="Launching DNS server for network%!(EXTRA string=none)"
time="2016-11-04T10:13:33.937919500+01:00" level=debug msg="Network Response : [  ]"
time="2016-11-04T10:13:33.938337000+01:00" level=error msg="Resolver Setup/Start failed for container none, \"json: cann
ot unmarshal array into Go value of type hcsshim.HNSNetwork\""
time="2016-11-04T10:13:33.948719300+01:00" level=debug msg="Allocating IPv4 pools for network nat (255c8cb61b4a88973013f
5ef79b45ab062b713113fd397cb14f26f40f6796855)"
time="2016-11-04T10:13:33.948719300+01:00" level=debug msg="RequestPool(LocalDefault, , , map[], false)"
time="2016-11-04T10:13:33.948719300+01:00" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.
docker.network.gateway])"
time="2016-11-04T10:13:33.949727300+01:00" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Sub
nets\":[{\"AddressPrefix\":\"0.0.0.0/0\",\"GatewayAddress\":\"0.0.0.0\"}]} Address Space=[{0.0.0.0/0 0.0.0.0 []}]"
time="2016-11-04T10:13:34.505540800+01:00" level=debug msg="releasing IPv4 pools from network nat (255c8cb61b4a88973013f
5ef79b45ab062b713113fd397cb14f26f40f6796855)"
time="2016-11-04T10:13:34.507266300+01:00" level=debug msg="ReleaseAddress(0.0.0.0/0, 0.0.0.0)"
time="2016-11-04T10:13:34.508240400+01:00" level=debug msg="ReleasePool(0.0.0.0/0)"
time="2016-11-04T10:13:34.508240400+01:00" level=debug msg="starting clean shutdown of all containers..."
Error starting daemon: Error initializing network controller: Error creating default network: HNS failed with error : Un
specified error
PS C:\Users\Administrator>
PS C:\Users\Administrator> get-Service winnat

Status   Name               DisplayName
------   ----               -----------
Running  winnat             Windows NAT Driver
```

**Comment by clarity99** [comment]
Even with the service running, these commands still return nothing:

```
PS C:\Users\Administrator> Get-VMSwitch
PS C:\Users\Administrator> Get-NetNat
PS C:\Users\Administrator>
```

**Comment by clarity99** [comment]
I've also done another trace now that the winnat is running:
https://dl.dropboxusercontent.com/u/153770/NetTrace2.rar

**Comment by clarity99** [comment]
I've also noticed in event viewer there are events from hyper-v-switch and have put them here:
https://dl.dropboxusercontent.com/u/153770/docker-hyper-switch.txt

seems nat switch gets created and then deleted.

**Comment by clarity99** [comment]
no more ideas?

**Comment by edvlucas** [comment]
Same thing here:
time="2016-12-10T20:29:23.933687300+01:00" level=debug msg="Listener created for HTTP on npipe (//./pipe/docker_engine)"

time="2016-12-10T20:29:23.943685100+01:00" level=debug msg="Stackdump - waiting signal at Global\\docker-daemon-1948"
time="2016-12-10T20:29:23.944692200+01:00" level=info msg="Windows default isolation mode: process"
time="2016-12-10T20:29:23.944692200+01:00" level=debug msg="Using default logging driver json-file"
time="2016-12-10T20:29:23.945690800+01:00" level=debug msg="WindowsGraphDriver InitFilter at C:\\ProgramData\\docker\\wi
ndowsfilter"
time="2016-12-10T20:29:23.950689700+01:00" level=debug msg="Using graph driver windowsfilter"
time="2016-12-10T20:29:23.951689200+01:00" level=debug msg="Max Concurrent Downloads: 3"
time="2016-12-10T20:29:23.951689200+01:00" level=debug msg="Max Concurrent Uploads: 5"
time="2016-12-10T20:29:24.016687600+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2016-12-10T20:29:24.027686700+01:00" level=debug msg="Option DefaultDriver: nat"
time="2016-12-10T20:29:24.028690200+01:00" level=debug msg="Option DefaultNetwork: nat"
time="2016-12-10T20:29:24.240821100+01:00" level=debug msg="Network Response : [  ]"
time="2016-12-10T20:29:24.250816700+01:00" level=debug msg="Launching DNS server for network%!(EXTRA string=none)"
time="2016-12-10T20:29:24.259815000+01:00" level=debug msg="Network Response : [  ]"
time="2016-12-10T20:29:24.259815000+01:00" level=error msg="Resolver Setup/Start failed for container none, \"json: cann
ot unmarshal array into Go value of type hcsshim.HNSNetwork\""
time="2016-12-10T20:29:24.286815300+01:00" level=debug msg="Allocating IPv4 pools for network nat (03c3e415f448f4248dc81
d573ffe82389ad26ad9bb9d5e58715e6a8db9a95427)"
time="2016-12-10T20:29:24.286815300+01:00" level=debug msg="RequestPool(LocalDefault, , , map[], false)"
time="2016-12-10T20:29:24.287817500+01:00" level=debug msg="RequestAddress(0.0.0.0/0, <nil>, map[RequestAddressType:com.
docker.network.gateway])"
time="2016-12-10T20:29:24.287817500+01:00" level=debug msg="HNSNetwork Request ={\"Name\":\"nat\",\"Type\":\"nat\",\"Sub
nets\":[{\"AddressPrefix\":\"0.0.0.0/0\",\"GatewayAddress\":\"0.0.0.0\"}]} Address Space=[{0.0.0.0/0 0.0.0.0 []}]"

**Comment by rwspeight** [comment]
Adding the "--bridge none" parameter resolved the problem for me.

**Comment by msabansal** [comment]
Dropped of this thread. Sorry. --bridge none makes docker daemon start without nat network and doesnt' solve the problem. If you are still facing issues after starting the winnat service you can look into the host-networking-service channel and see where the error is coming from.  Also i can help diagnose if you can share the following logs:

> ipconfig /all
> Get-VmSwitch
> Get-NetNat
> netsh trace start globallevel=5 provider=Microsoft-Windows-Host-Network-Service provider={93f693dc-9163-4dee-af64-D855218af242}  report=di
> <repro>
> netsh trace stop

**Comment by clarity99** [comment]
@msabansal I've attached all the traces and logs in the previous comments above.

**Comment by msabansal** [comment]
@clarity99 The logs still show failure in creating winnat instance

MessageNumber	DiagnosisTypes	Timestamp	TimeElapsed	ResponseTime	Source	Destination	Module	Summary	TopModule	TopSummary	
30	None	2016-11-04T02:25:38.5750928					Microsoft_Windows_Host_Network_Service	ActivityError: wilActivity=Dynamic: callContext=\HNSRequestHandler,currentContextId=8,currentContextMessage=,currentContextName=HNSRequestHandler,failureCount=25,failureId=25,failureType=0,fileName=vm\dv\net\hns\service\nat.cpp,function=,hresult=2147749937,lineNumber=68,message=,module=hostnetsvc.dll,originatingContextId=8,originatingContextMessage=,originatingContextName=HNSRequestHandler,threadId=7768	Microsoft_Windows_Host_Network_Service	ActivityError: wilActivity=Dynamic: callContext=\HNSRequestHandler,currentContextId=8,currentContextMessage=,currentContextName=HNSRequestHandler,failureCount=25,failureId=25,failureType=0,fileName=vm\dv\net\hns\service\nat.cpp,function=,hresult=2147749937,lineNumber=68,message=,module=hostnetsvc.dll,originatingContextId=8,originatingContextMessage=,originatingContextName=HNSRequestHandler,threadId=7768	

Can you please capture these traces: 
netsh trace start  globallevel=5 provider=microsoft-windows-winnat level=5 report=di capture=yes

**Comment by clarity99** [comment]
new trace file is at https://dl.dropboxusercontent.com/u/153770/NetTrace.etl

**Comment by clarity99** [comment]
I've also upgraded docker to 1.13. and rerun the trace: https://dl.dropboxusercontent.com/u/153770/NetTrace3.etl

**Comment by msabansal** [comment]
@clarity99 There is no winnat trace in the log files. I will probably have to set a local repro to get to the bottom of this.

**Comment by clarity99** [comment]
@msabansal if it would help I could give you rdp access to this vm? contact me directly at rob at awakeheart.net

**Comment by msabansal** [comment]
@clarity99 Thanks Robert. I have a local repro setup. I will try to debug this and get back to you in a couple of days.

**Comment by msabansal** [comment]
@clarity99 Doing mofcomp C:\Windows\System32\wbem\NetNat.mof fixes the issue for me.

**Comment by clarity99** [comment]
yay, this fixed it! thank you very much!

**Comment by hanxinimm** [comment]
i have the same error , @msabansal  thank you very much!

**Comment by ShannonMcCoy** [comment]
@msabansal  Thank you Sandeep, chased this issue for hours and nothing worked until I tried your fix.

**Comment by bpatton00** [comment]
Worked today for me as well, exact same issue and resolution.  Life saver

**Comment by davidathompson** [comment]
@msabansal fixed it for me...thank you!

**Comment by bashirkunya** [comment]
@msabansal You are a lagend.Thanks worked for me

**Comment by gennniius** [comment]
@msabansal  sorry im just a beginner, what do u mean by Doing mofcomp?

**Comment by gennniius** [comment]
i ve this issue as i had Docker for some time then i did uninstallation and nw im trying to install it again but it end up with this error 
![image](https://user-images.githubusercontent.com/45523835/70465816-73fe8f00-1aca-11ea-8149-80898ce287ff.png)
