### ISSUE TITLE
Docker daemon encounters error trying to chown a mounted NFS volume

### ISSUE THREAD

**Issue by kklemmicknvidia** [docker/docker#28001]
I've seen a few issues reported similar to this, but haven't found an exact match so I figured I'd post this here.

**Description**
We're seeing an issue where after mounting an NFS volume correctly, the docker daemon hits an error trying to chown the mounted directory. I see the same problem with both v1.11 and v1.12 (version/info output below).

We can work around the problem by disabling root squashing on the NFS server, but this is not a long term solution for us due to security concerns.

**Steps to reproduce the issue:**
1. Set up a NFS shared directory, say sc-nfs-01.nvidia.com:/export/scratch/
2. Ensure root squshing is enabled for that NFS directory.
3. Try to mount using docker run:
docker run --volume-driver nfs --volume sc-nfs-01.nvidia.com/export/scratch:/tmp/data -it -u 1000:1000 ubuntu /bin/bash

Output:
docker: Error response from daemon: chown /var/lib/docker-volumes/netshare/nfs/sc-nfs-01.nvidia.com/export/scratch: operation not permitted.

**Suggested fix**
Ideally, for our use case we'd disable the chown the docker daemon is doing. Of course, this would require the user the container is run as to have sufficient permissions on the nfs server to perform the task they're running, but would be preferable than disabling root squashing as a solution.

I've compiled the daemon myself, but looking through the code it's not clear to me (yet) what chown call is causing this error. If anyone has an idea here, I can implement this myself to test on our side and report my findings here.

Is there another way around this issue? I've tried various different options on both the docker-volume-netshare plugin and the volume/run commands on docker with no luck. I have verified that the volume mounted by docker-volume-netshare is mounted in a way sufficient for our needs (by disabling the dismount command), but we still can't run a container because of the daemon error.

Any help here would be appreciated! 

**Output of `docker version`:**
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 43
 Running: 0
 Paused: 0
 Stopped: 43
Images: 9
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 192
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: nfs local
 Network: host bridge null
 Authorization: authz-broker
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 80
Total Memory: 503.8 GiB
Name: dgx-1
ID: HCJD:X36R:FEUT:BVAH:NVUF:QPZN:MP6Q:4Y2D:DANF:IJ5S:VUN5:JS77
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 57
 Goroutines: 159
 System Time: 2016-11-02T15:07:42.543916239-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: IPv4 forwarding is disabled
Labels:

Thanks,
Kevin

**Comment by kklemmicknvidia** [comment]
docker.log for the create API call:

> time="2016-11-02T15:32:38.593903187-07:00" level=debug msg="Calling POST /v1.24/containers/create"
> time="2016-11-02T15:32:38.594172923-07:00" level=debug msg="form data: {\"AttachStderr\":true,\"AttachStdin\":true,\"AttachStdout\":true,\"Cmd\":[\"/bin/bash\"],\"Domainname\":\"\",\"Entrypoint\":null,\"Env\":[],\"HostConfig\":{\"AutoRemove\":false,\"Binds\":[\"sc-nfs-01.nvidia.com/export/scratch:/tmp/data\"],\"BlkioDeviceReadBps\":null,\"BlkioDeviceReadIOps\":null,\"BlkioDeviceWriteBps\":null,\"BlkioDeviceWriteIOps\":null,\"BlkioWeight\":0,\"BlkioWeightDevice\":null,\"CapAdd\":null,\"CapDrop\":null,\"Cgroup\":\"\",\"CgroupParent\":\"\",\"ConsoleSize\":[0,0],\"ContainerIDFile\":\"\",\"CpuCount\":0,\"CpuPercent\":0,\"CpuPeriod\":0,\"CpuQuota\":0,\"CpuShares\":0,\"CpusetCpus\":\"\",\"CpusetMems\":\"\",\"Devices\":[],\"DiskQuota\":0,\"Dns\":[],\"DnsOptions\":[],\"DnsSearch\":[],\"ExtraHosts\":null,\"GroupAdd\":null,\"IOMaximumBandwidth\":0,\"IOMaximumIOps\":0,\"IpcMode\":\"\",\"Isolation\":\"\",\"KernelMemory\":0,\"Links\":null,\"LogConfig\":{\"Config\":{},\"Type\":\"\"},\"Memory\":0,\"MemoryReservation\":0,\"MemorySwap\":0,\"MemorySwappiness\":-1,\"NetworkMode\":\"default\",\"OomKillDisable\":false,\"OomScoreAdj\":0,\"PidMode\":\"\",\"PidsLimit\":0,\"PortBindings\":{},\"Privileged\":false,\"PublishAllPorts\":false,\"ReadonlyRootfs\":false,\"RestartPolicy\":{\"MaximumRetryCount\":0,\"Name\":\"no\"},\"SecurityOpt\":null,\"ShmSize\":0,\"UTSMode\":\"\",\"Ulimits\":null,\"UsernsMode\":\"\",\"VolumeDriver\":\"nfs\",\"VolumesFrom\":null},\"Hostname\":\"\",\"Image\":\"ubuntu\",\"Labels\":{},\"NetworkingConfig\":{\"EndpointsConfig\":{}},\"OnBuild\":null,\"OpenStdin\":true,\"StdinOnce\":true,\"Tty\":true,\"User\":\"1000:1000\",\"Volumes\":{},\"WorkingDir\":\"/tmp/data\"}"
> time="2016-11-02T15:32:38.594609133-07:00" level=debug msg="AuthZ request using plugin authz-broker"
> time="2016-11-02T15:32:38.596416464-07:00" level=warning msg="IPv4 forwarding is disabled. Networking will not work"
> time="2016-11-02T15:32:38.597856376-07:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/7389fd2704e027c760cc9c6391b0bde5e786a369807bab2062046d5e804484c2-init: exec: \"auplink\": executable file not found in $PATH"
> time="2016-11-02T15:32:38.636588881-07:00" level=debug msg="container mounted via layerStore: /var/lib/docker/aufs/mnt/7389fd2704e027c760cc9c6391b0bde5e786a369807bab2062046d5e804484c2"
> time="2016-11-02T15:32:38.636744321-07:00" level=debug msg="copying image data from dc9a03fe89655b452c96b474cbf1ff501633b0fe7a833f4c7c3c6c8c4ef6a637:/tmp/data, to sc-nfs-01.nvidia.com/export/scratch"
> time="2016-11-02T15:32:38.788267344-07:00" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/7389fd2704e027c760cc9c6391b0bde5e786a369807bab2062046d5e804484c2: exec: \"auplink\": executable file not found in $PATH"
> time="2016-11-02T15:32:38.823542590-07:00" level=error msg="Handler for POST /v1.24/containers/create returned error: chown /var/lib/docker-volumes/netshare/nfs/sc-nfs-01.nvidia.com/export/scratch: operation not permitted"
> time="2016-11-02T15:32:38.823560671-07:00" level=error msg="Handler for POST /v1.24/containers/create returned error: chown /var/lib/docker-volumes/netshare/nfs/sc-nfs-01.nvidia.com/export/scratch: operation not permitted"

**Comment by cpuguy83** [comment]
Use the `:nocopy` option when specifying the volume.
e.g. `-v volname:/foo:nocopy`

**Comment by kklemmicknvidia** [comment]
That actually seems to work, thanks!

What I'd like to understand is why. It seems the nocopy option is supposed to avoid the copy docker would do otherwise if a mounted path already had files present in the container; But in my case no directory of that name exists so there should be nothing to copy, correct?

Maybe I'm not understanding this option correctly. I've not been able to find any good docs on it.

**Comment by kingpong** [comment]
I had exactly the same problem and the timing on this answer couldn't have been better. Adding `nocopy` fixed my problem, too. I also had to fix `MountFlags` as described in the [docker run](https://docs.docker.com/engine/reference/run/#volume-shared-filesystems) reference.

I have seen at least one [StackExchange answer](http://unix.stackexchange.com/questions/292999/mounting-a-nfs-directory-into-host-volume-that-is-shared-with-docker) recommend setting the `shared` option on the volume, which doesn't work in my docker (1.12.3 6b644ec). Also it's unclear from the `docker run` reference what this flag actually is supposed to do. And same with `Z`.

**Comment by cpuguy83** [comment]
@kingpong Responded on that stack exchange post.

Setting up `shared` propagation requires making sure that the root mount point that the thing you are wanting to flag as shared is also shared.
e.g., if the root mount is `/`, then you must make sure `/` is a shared mount in order to use `shared` propagation. The trick for doing this is to `mount --bind / / && mount --make-shared /`. In addition you may have to setup other things, such as systemd, which may be changing this.

`z` and `Z` are settings for selinux. They set the selinux labels so that either only the container can access the host mount or it can be shared with other containers.

@kklemmicknvidia Correct, it should only run if the container dir is non-empty and the volume dir is empty.

**Comment by kklemmicknvidia** [comment]
@kingpong Any idea how to set MountFlags when using upstart and a daemon.json configuration file? Since it doesn't read the /lib/systemd/system/docker.service file, setting this flag there has no effect. There doesn't seem to be any corresponding field in the /etc/docker/daemon.json schema. It seems ridiculous to me that Docker has so many different ways to pass options to its daemon and it doesn't look like all paths support all functionality.

Honestly though, since we're running Docker under Mesos, ideally we'd be able to pass this option down as part of the Mesos job request instead of forcing Docker to use it for everything, so I'll spend some time looking into that.

**Comment by kingpong** [comment]
Sorry, no idea. I'm not sure if it is required under upstart. It looks like a systemd setting, not a docker setting.

**Comment by cpuguy83** [comment]
@kklemmicknvidia Docker has 2 ways, via flags and config file (/etc/docker/daemon.json).
Everything is supported either way.

Setting up `MountFlags` is a systemd config, not a docker one.
