### ISSUE TITLE
Windows - eventsource type "long connections" are not working through NAT

### ISSUE THREAD

**Issue by volak** [docker/docker#28014]
Docker version 1.12.2-cs2-ws-beta, build 050b611

I am investigating an issue - I'm running ServiceStack inside a docker container with port mapping 80.  My app uses server sent events to keep clients up to date with changes and it seems the "long" eventsource type connections are being closed by the docker NAT prematurely.  

The reason why I think its a docker issue is because if I connect to the docker container directly (no nat) everything works.  Its only when I connect through the virtual docker port this issue comes up.

For instance if my container is running at `172.18.91.192` which I started with `-p 8080:80` - connecting to `http://172.18.91.192/` from the host works.  But when connected to `http://[host]:8080` all eventsource type connections are closed immediately after the initial response.

I  can provide any additional info requested or run tests - this is my current dockerfile

```
FROM microsoft/iis
ARG CONT_IMG_VER
ENV CONT_IMG_VER ${CONT_IMG_VER:-v1.0.0}

RUN powershell -Command \
	Add-WindowsFeature Web-Server; \
	Add-WindowsFeature Web-Net-Ext45; \
	Add-WindowsFeature Web-AppInit; \
	Add-WindowsFeature Web-Asp-Net45;

	
RUN powershell -Command Stop-WebAppPool -name DefaultAppPool
RUN powershell -Command Stop-WebSite -name 'Default Web Site'

COPY ./* C:/inetpub/wwwroot/bin/
COPY *.config C:/inetpub/wwwroot/
COPY *.asax C:/inetpub/wwwroot/
COPY *.cshtml C:/inetpub/wwwroot/
COPY *.css C:/inetpub/wwwroot/
COPY *.js C:/inetpub/wwwroot/

RUN powershell -Command \
	Import-Module WebAdministration; \
	Set-ItemProperty 'IIS:/Sites/Default Web Site' -name applicationDefaults.preloadEnabled -value True; \
	Set-ItemProperty 'IIS:/Sites/Default Web Site' -name serverAutoStart -value True; \
	Set-ItemProperty 'IIS:/AppPools/DefaultAppPool' -name autoStart -value True; \
	Set-ItemProperty 'IIS:/AppPools/DefaultAppPool' -name startMode -value 'alwaysrunning'; \
	Set-ItemProperty 'IIS:/AppPools/DefaultAppPool' -name managedRuntimeVersion -value 'v4.0'; 

RUN powershell -Command Start-WebAppPool -name DefaultAppPool
RUN powershell -Command Start-WebSite -name 'Default Web Site'

EXPOSE 80

CMD sc stop wuauserv
CMD netsh advfirewall set allprofiles state off
```

**Comment by volak** [comment]
Here is an example repo to demonstrate the problem https://github.com/volak/Chat

Dockerfile is inside project folder, image should be built from that location to get the bin, cshtml, js etc.

**Comment by volak** [comment]
Can I provide any more info for this?  Is it just a known issue?  This is preventing me from moving forward into production now without doing some kind of workaround like a dedicated IIS instance not inside docker

**Comment by msabansal** [comment]
@volak Will investigate. Sorry for the delay. Had fallen off the tracking

**Comment by msabansal** [comment]
I tried this on our latest builds and it seems i can't repro this anymore

![image](https://cloud.githubusercontent.com/assets/14339337/22840679/5cfbe49e-ef83-11e6-835a-53d206364e51.png)

Can you please see if this looks as expected? The code is running inside a container

**Comment by volak** [comment]
@msabansal Connecting to the docker host directly works fine - its only a problem when connecting to the virtualized docker port that long connections are terminated prematurely.

If you run this docker file with `-p 8080:80` and try to connect to `http://[host]:8080` you'll see the disconnects.  Specifically to `http://[host]:8085/event-stream` - this connection should live forever as its the transport back to the client from the server but it gets disconnected shortly after creation.

If this app is run without the docker virtual port as you've seen it works just fine `http://[host]:8085/event-stream` stays connected throughout.

  I just tried with docker `1.31.1` - same issue.

**Comment by msabansal** [comment]
@volak Soeven though the app is working properly the underlying even-stream closing is an issue?

**Comment by volak** [comment]
@msabansal Exactly - here's 2 screenshots to illustrate the problem

Good connection directly to host container -
<img width="1138" alt="sshot-67" src="https://cloud.githubusercontent.com/assets/1750226/22841754/59f7fd7c-ef98-11e6-8a10-eed8e2a270e2.png">

Bad connection through virtual port -
<img width="1582" alt="sshot-68" src="https://cloud.githubusercontent.com/assets/1750226/22841753/59f66264-ef98-11e6-8502-c5559d5919c6.png">

**Comment by msabansal** [comment]
@volak looking at the traces i see a lot of streams disconnecting at 10,20 or 30 seconds (10 being very common). I would debug some more when i get cycles on this. Please expect an update in a day or two

**Comment by msabansal** [comment]
@volak This is not a windows/container networking issue. The problem is in how the url are getting mapped by IIS. running the chat container by using -p 80:80 fixes the problem. 
When exposing a random port using -P it is not working because the heartbeat URL being return by service stack is incorrect. Service stack returns a url with port 80 mapped. Something like "heartbeatUrl":"http://10.1.1.3/event-heartbeat?id=PEffbScxqngzjTvGvbDI" while the container is exposed on a different port and service stack should have returned "heartbeatUrl":"http://10.1.1.3:1234/event-heartbeat?id=PEffbScxqngzjTvGvbDI" if the container was exposed on port 1234
Not sure how to fix this problem :|. Please let me know if the explanation is not clear

**Comment by volak** [comment]
@msabansal Wow thanks for looking into it so deeply

Servicestack has a .Net Core version of this app which works in linux docker which made me think there's an underlying windows issue here but what you say makes sense.  I'll dive deeper into this and see what can be done to fix - seems like it might be hard due to the docker mapping.. I dont know how SS would even know to return the right heartbeat url

**Comment by volak** [comment]
ping @mythz

**Comment by mythz** [comment]
ServiceStack constructs the heartbeatUrl from the incoming Request Url. You can see this if you run the same [ServiceStack .NET Core Chat App locally](https://github.com/NetCoreApps/Chat) where the heartbeatUrl returned is `http://localhost:1337/event-heartbeat?id=xxx`.

This .NET Core Chat App is also hosted on [chat.netcore.io](http://chat.netcore.io/) which is running in a Docker VM on port 5000 behind an nginx reverse proxy that proxies the external chat.netcore.io request and maps it to the Kestrel server running on port 5000. The [guide to how this is setup is documented here](http://docs.servicestack.net/deploy-netcore-docker-aws-ecs).

So I'd assume the issue is the incoming Request URL that reaches ServiceStack which you can override by hard-coding the Base URL in:

```csharp
SetConfig(new HostConfig {
    WebHostUrl = "http://10.1.1.3:1234/"
});
```

Or if you just want to replace the heartbeat url, you can override it with:

```csharp
Plugins.Add(new ServerEventsFeature {
    OnConnect = (sub, args) => {
        args["heartbeatUrl"] = args["heartbeatUrl"].Replace("//10.1.1.3/", "//10.1.1.3:1234/");
    }
});
```

**Comment by volak** [comment]
Thanks @mythz great info!  So basically if you are using random ports through docker as part of some load balancing setup - I'll need to set something up to feed servicestack the port back?

**Comment by mythz** [comment]
@volak The reverse proxy is what usually does the translation from external to internal url.

**Comment by volak** [comment]
yeahh I was just thinking about that - the whole problem is the content of the heartbeatUrl being sent back no way for SS or docker to do anything about this.  
Closing issue thanks a lot for your time @msabansal and @mythz

**Comment by volak** [comment]
@mythz Out of curiosity is there a reason for onConnect to return the full server address for `heartbeatUrl` and not just return `"heartbeatUrl":"~/event-heartbeat?id=oJghGRY0EuaycPB9SH90"` or similar?  Seems that too would solve local docker issues like this

**Comment by mythz** [comment]
@volak A `~` prefix doesn't make sense in a URL, but you could change it to `/event-heartbeat?id=xxx` but this only works when your ServiceStack Instance is hosted from root, e.g. `chat.netcore.io` not `chat.netcore.io/api` or any other virtual directory.
