### ISSUE TITLE
Windows containers. Switching the user

### ISSUE THREAD

**Issue by soanni** [docker/docker#28027]
Hello, Docker team.
I don't know whether i can ask about my problem here but i'll try.
How can i switch users in windows container?
I created a user, added it to Administrators group. and now i would like to configure an app under that user. Seems that dockerfile USER instruction is not applicable to windows containers (the daemon shows that USER command is not supported on this platform), Start-Process is also not a solution. the only idea i have is to run an IIS apppool under that user and create a simple .aspx script that will run my .ps1 script. IIS can interactively logon and i already checked that method, it's working but it seems strange to me that 'runas' doesn't work properly.
I'm running docker on Windows Server 2016.

This is docker version:

Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Thank you in advance for your help.

**Comment by friism** [comment]
Do you have more details on your use case? You might want to take a look at this article on using an AD service account: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_serviceaccounts

**Comment by soanni** [comment]
yeah, i'm checking this solution thank you. i'm just wondering why in windows container i'm restricted only to some strange user ContainerAdministrator? is it some specific limitation not allowing to switch users and running processes under different user? this solution with AD accounts might solve my issue but before that i used the IIS ability to run the application pool under my custom user because i wasn't able to start processes using 'runas' flag.

**Comment by friism** [comment]
Pinging @patricklang

**Comment by soanni** [comment]
@friism @patricklang i checked the solution https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_serviceaccounts. But this is not exactly what i need actually. i'm trying to place MS Sharepoint 2010 inside the container. Sharepoint needs to have access to domain users. Actual users with actual passwords, becase gMSA account is more like a special account for services. Is there any way to have the users (that the domain connected docker host machine has) inside the container. and run powershell commands under that users (OR just switch the user the way we are doing this in Linux container with USER instruction), so that after the container start i would be logged in under differrent user (not the ContainerAdministrator). Thank you in advance for your answers.

**Comment by friism** [comment]
@patricklang do you have thoughts?

**Comment by soanni** [comment]
for example this code works on host and process starts under different user 'sp_farm'. And whoami outputs: 'sp_farm'. Inside the container i'm getting error code -1073741502
-------------------------
$pw = convertto-securestring "Password" -asplaintext -force;

$pinfo = New-Object System.Diagnostics.ProcessStartInfo
$pinfo.FileName = "whoami"
$pinfo.RedirectStandardError = $true
$pinfo.RedirectStandardOutput = $true
$pinfo.UseShellExecute = $false
$pinfo.CreateNoWindow = $true;
$pinfo.Verb = "runas";
$pinfo.Arguments = "";
$pinfo.UserName = "sp_farm";
#$pinfo.Domain = "nextdocs"
$pinfo.Password = $pw

$p = New-Object System.Diagnostics.Process
$p.StartInfo = $pinfo
$p.Start() | Out-Null
$stdout = $p.StandardOutput.ReadToEnd()
$stderr = $p.StandardError.ReadToEnd()
$p.WaitForExit()
Write-Host "stdout: $stdout"
Write-Host "stderr: $stderr"
Write-Host "exit code: " + $p.ExitCode

**Comment by soanni** [comment]
So user can be created inside the container, but we can't run processes under that user. This is odd. Or am i missing smth?

**Comment by soanni** [comment]
this is code decrypt

PS C:\domain> certutil -error -1073741502
0xc0000142 (NT: 0xc0000142 STATUS_DLL_INIT_FAILED) -- 3221225794 (-1073741502)
Error message text: {DLL Initialization Failed}
Initialization of the dynamic link library %hs failed. The process is terminating abnormally.
CertUtil: -error command completed successfully.

**Comment by soanni** [comment]
I guess that's the answer.
---------------
Windows XP with SP2,Windows Server 2003, or later:  You cannot call CreateProcessWithLogonW from a process that is running under the "LocalSystem" account, because the function uses the logon SID in the caller token, and the token for the "LocalSystem" account does not contain this SID. As an alternative, use the CreateProcessAsUser and LogonUser functions.
---------------

It appears that ContainerAdministrator is not a user..

**Comment by PatrickLang** [comment]
We don't have domain join support for Windows Containers, which means you can't run services as regular domain users. There is only support for gMSA, so if Sharepoint can't run using a gMSA unfortunately it won't work.

**Comment by soanni** [comment]
Okay let's forget about domain. Why i can't switch local container users?

**Comment by darrenstahlmsft** [comment]
@jhowardmsft While I don't think it solves the whole issue here, I think USER in Dockerfiles can be enabled now on Windows.

**Comment by soanni** [comment]
@darrenstahlmsft @jhowardmsft that would be awesome

**Comment by jhowardmsft** [comment]
Fixed by https://github.com/docker/docker/pull/28415
