### ISSUE TITLE
Package docker for yakkety in https://apt.dockerproject.org/repo/dists/

### ISSUE THREAD

**Issue by zigarn** [docker/docker#28023]
Ubuntu Yakkety (16.10) is available since 2016-10-13.
Docker is not yet packaged for this distribution: https://apt.dockerproject.org/repo/dists/

**Comment by thaJeztah** [comment]
duplicate of https://github.com/docker/docker/issues/27521

**Comment by zigarn** [comment]
Missed it, sorry.

**Comment by thaJeztah** [comment]
no problem! :smile:
