### ISSUE TITLE
Unable to curl docker Linux binaries from get.docker.com

### ISSUE THREAD

**Issue by deitch** [docker/docker#28024]
Trying to get the binaries directly fails:

````
$ curl -I https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
HTTP/1.1 403 Forbidden
Connection: keep-alive
x-amz-error-code: AccessDenied
x-amz-error-message: Access Denied
Date: Thu, 03 Nov 2016 08:17:52 GMT
Server: AmazonS3
X-Cache: Error from cloudfront
Via: 1.1 002c7dd628aeaafbb16627d6bb5046c9.cludfront.net (CloudFront)
X-Amz-Cf-Id: aSEkJaVtoPyG6TBhposamzpsj-p-OliKH0ktPlz3seRnvFRDE7RnRg==
````

Technically not a _docker_ bug but a docker _distribution_ but, but still. :-)

This happens when I run it on an Ubuntu laptop or within a container on that laptop (Alpine:3.4 FWIW). 

If I keep it up, eventually I do get a clean download, maybe 1 out of 10?

Funny thing, on the same LAN, try it from Mac, it works. 

````
$ curl -I https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz
HTTP/1.1 200 OK
Content-Type: application/x-tar
Content-Length: 28891346
Connection: keep-alive
Date: Thu, 03 Nov 2016 02:40:35 GMT
Last-Modified: Wed, 26 Oct 2016 23:32:58 GMT
ETag: "1ad09523cddd93cd54d6848cb39e5a5f-4"
Server: AmazonS3
Age: 20524
X-Cache: Hit from cloudfront
Via: 1.1 f17892129c0657c8d9d0809a1b0b00be.cloudfront.net (CloudFront)
X-Amz-Cf-Id: E50AMcenacNrOGwKekFEQRTOSI1ZAbg5EgoD4mq6OJlLyFNqH6THWA==
````

**Comment by justincormack** [comment]
Hmm, I can't replicate but it looks like a cloudfront issue probably you are getting different endpoints. Let me see who can look into this.

**Comment by deitch** [comment]
Currently running it from Israel, so probably different endpoints. Happy to help with debugging, since I can replicate reasonably consistently. @justincormack you have my direct contact info (twitter DM, email) if you need to reach me directly; feel free to share privately among the team if needed.

**Comment by andrewhsu** [comment]
I cannot reproduce from my location in California. I'll have a look at our cloudfront and s3 setup to see if there was any hiccup.

**Comment by deitch** [comment]
It truly is strange. I still am getting it on Ubuntu and on containers run in the same Ubuntu, but not on a digital ocean VM or on a Mac.

Ran `curl -v -H https://get.....`. On both the `alpine:3.4` container running on the Linux laptop (fail) and the DO one (succeed), identical request headers. Both clean containers, but checked the `/etc/ssl/certs/ca-certificates.crt`, identical `sha1sum`.

What could possibly go in the request that would make it:

* Mac from IL: succeed
* Linux from IL: fail
* Linux alpine container from IL: fail
* Linux alpine container from US: succeed

**Comment by andrewhsu** [comment]
I think I found the requests that you made...I've scrubbed out your IP address for privacy:

Original failure request:
```
2016-11-03        08:17:53        FRA6    347     127.0.0.1  HEAD    d3vuzgspmaykda.cloudfront.net   /builds/Linux/x86_84/docker-latest.tgz  403     -       curl/7.47.0     -      -
        Error   aSEkJaVtoPyG6TBhposamzpsj-p-OliKH0ktPlz3seRnvFRDE7RnRg==        get.docker.com  https   116     0.171   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256     Error   HTTP/1.1
```

Success request:
```
2016-11-03        08:22:38        FRA6    431     127.0.0.1  HEAD    d3vuzgspmaykda.cloudfront.net   /builds/Linux/x86_64/docker-latest.tgz  200     -       curl/7.49.1     -      -
        Hit     E50AMcenacNrOGwKekFEQRTOSI1ZAbg5EgoD4mq6OJlLyFNqH6THWA==        get.docker.com  https   116     0.003   -       TLSv1.2 ECDHE-RSA-AES128-GCM-SHA256     Hit     HTTP/1.1
```

Looks like you used curl 7.47.0 in the failure request and curl 7.49.1 in the successful request. Many things changed in between those 2 versions...my gut says investigate there: https://curl.haxx.se/changes.html

If you have a suitable way to get it to consistently succeed in getting the `https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz` endpoint, I'm going to close this ticket because the service is up and working for other people.

**Comment by deitch** [comment]
Do they say what the error is?

> you used curl 7.47.0 in the failure request and curl 7.49.1 in the successful request

Not exactly. 7.49.1 is on the Mac, 7.47.0 is on the Ubuntu. **But** on the Alpine container it is consistently 7.50.3, and it failed regularly.

Can you find failed requests from the same IP (or range) from 7.50.3?

**Comment by andrewhsu** [comment]
curl requests with ip scrubbed https://gist.github.com/andrewhsu/bbf6e4360e492bb6d5292ce076351021

**Comment by deitch** [comment]
So the 7.49.1 are all hits, the 7.47.1 are all failures, and the 7.50.3 are all errors here, although I have had both kinds from within an Alpine container.

Do they say anywhere what the error was? Just "Error" from them isn't very helpful to you. :-)

**Comment by deitch** [comment]
For the last 36 hours or so, it has been working from the alpine:3.4 image running on Ubuntu, as stated before, version 7.50.3, and the Ubuntu host itself curl version 7.47.0.

Obviously, it no longer is an open issue, so if you want to close it, go ahead. But we aren't aware of root cause. If it bit me, it probably bit others, and might (will?) come back at some point. Not sure how much I can contribute to it without access to deeper CloudFront and S3 logs, and, for that matter, an ability to continually reproduce.

**Comment by deitch** [comment]
(I saw 36 hours; I was offline for the last 25, and it worked for the few hours before I went offline and now again; I cannot swear to the middle, though...).

**Comment by thaJeztah** [comment]
@deitch is this still an issue, or can we close this?

**Comment by deitch** [comment]
@thaJeztah I am not having issues with it anymore, per the earlier comment. But root cause? I have no idea. If you want me to take a look at the CloudFront and S3 logs, happy to help, but not sure what I will find.

I will close it out.
