### ISSUE TITLE
document templating features in swarm mode

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28022]
https://github.com/docker/docker/pull/27995 added templating features for swarm mode, but they were not documented yet.

The docs should be updated to document the templating, and include examples on how / when to use them

**Comment by vdemeester** [comment]
Ah forgot to add the piece of code to enable templating on the engine, I'll update as well as docs :wink:

**Comment by vdemeester** [comment]
Closing as #28486 has been merged
