### ISSUE TITLE
USER environment variable not populated as expected

### ISSUE THREAD

**Issue by ericcurtin** [docker/docker#28030]
If I run a command like follows:

`docker exec -it -u curtine container_name bash -c "env"`

the $USER environment variable you expect to be populated isn't.

But if I log into the docker interactively:

`docker exec -it -u curtine container_name bash`

the $USER environment variable you expect to be populated is.

The $USER environment variable should be populated in both cases.

Running CentOS6 guest on Ubuntu 16.04 host.

`docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64`

`docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 102
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 28
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.859 GiB
Name: curtinevmu
ID: WLZS:ATZR:GDFQ:7GHM:SBRF:2XHR:55LV:KJJL:LCDT:ZZJT:MOGA:SQWH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://web-proxy.corp.hp.com:8080/
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8`

**Comment by dnephin** [comment]
http://unix.stackexchange.com/a/76356

I think this behaviour is expected. It's not up to docker to set `$USER`. Maybe `bash -l -c` will do what you want?

**Comment by ericcurtin** [comment]
You are 110% correct! Thanks @dnephin and apologies for logging something that wasn't an issue. You normally don't notice this when you use bash -c as USER is exported... So it looked like a bug, rather than actually being one! I guess this issue should be closed...
