### ISSUE TITLE
use s.Rdev (type uint32) as type uint64--mips64el

### ISSUE THREAD

**Issue by vans88** [docker/docker#28058]
Recently I am building kubernetes on mips64el platform and getting the following error. Through googling , I find the source from https://github.com/docker/docker/blob/master/pkg/system/stat_linux.go line 13. Any suggestions for me？

**The error info：**
```
test/e2e_node/e2e_node.test
k8s.io/kubernetes/vendor/github.com/google/cadvisor/fs
k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/system
k8s.io/kubernetes/vendor/github.com/google/certificate-transparency/go/x509
# k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/system
vendor/github.com/docker/docker/pkg/system/stat_linux.go:13: cannot use s.Rdev (type uint32) as type uint64 in field value
# k8s.io/kubernetes/vendor/github.com/google/cadvisor/fs
vendor/github.com/google/cadvisor/fs/fs.go:422: cannot use buf.Dev (type uint32) as type uint64 in argument to major
vendor/github.com/google/cadvisor/fs/fs.go:423: cannot use buf.Dev (type uint32) as type uint64 in argument to minor
# k8s.io/kubernetes/vendor/github.com/google/certificate-transparency/go/x509
vendor/github.com/google/certificate-transparency/go/x509/x509.go:342: undefined: elliptic.P224
vendor/github.com/google/certificate-transparency/go/x509/x509.go:355: undefined: elliptic.P224
vendor/github.com/google/certificate-transparency/go/x509/x509.go:1461: undefined: elliptic.P224
Makefile:79: recipe for target 'all' failed
make: *** [all] Error 1

```
**segment of the source file **stat_linux.go：**
```
// fromStatT converts a syscall.Stat_t type to a system.Stat_t type
func fromStatT(s *syscall.Stat_t) (*StatT, error) {
	return &StatT{size: s.Size,
		mode: s.Mode,
		uid:  s.Uid,
		gid:  s.Gid,
		rdev: s.Rdev,
		mtim: s.Mtim}, nil
}
```
**my platform info**

```
[root@dscn2 kubernetes]# uname -a
Linux dscn2 4.4.21+ #3 SMP PREEMPT Wed Oct 12 09:14:23 CST 2016 mips64 mips64 mips64 GNU/Linux
[root@dscn2 kubernetes]# go env
GOARCH="mips64le"
GOBIN=""
GOEXE=""
GOHOSTARCH="mips64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/mygo"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_mips64le"
CC="gcc"
GOGCCFLAGS="-fPIC -mabi=64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build115989482=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

```

**Comment by justincormack** [comment]
Hi, at the moment Docker has no mips64 support, so it is likely there are some issues like this. Linux MIPS does have some unusual types for some things. We can accept patches for this, but it may be better to do a comprehensive port (which you will probably need anyway to run kubernetes).

**Comment by vans88** [comment]
**@justincormack**  I have ported docker for my mips64el platrom and will provide some information about docker.
```
[root@dscn2 ~]# which docker
/bin/docker
[root@dscn2 ~]# rpm -qf /bin/docker
docker-1.6.0-4.git9d26a07.fc21.loongson.3.mips64el
[root@dscn2 ~]# docker version
Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2 gccgo (GCC) 5.2.0 20150716 (Red Hat 5.2.0-5)
Git commit (client): 9d26a07/1.6.0
OS/Arch (client): linux/mipsn64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2 gccgo (GCC) 5.2.0 20150716 (Red Hat 5.2.0-5)
Git commit (server): 9d26a07/1.6.0
OS/Arch (server): linux/mipsn64

```
if so, Could I start to port kubernetes?  I know the  command "make release" is just from linux/amd64 platform. So I use "make -j15 all GOFLAGS=-v" which referenced "Makefile line 69-76 ".
```
[root@dscn2 kubernetes]# pwd
/usr/local/kubernetes
[root@dscn2 kubernetes]# ls  Makefile
Makefile

```

**Comment by vans88** [comment]
**@justincormack** 
 In my first comment, there is an error on "undefined: elliptic.P224".  Through googling I find the following link which has a comment pushed by **Antonio Murdaca**(comment num 21), who give a patch to avoid "P224" error.
https://bugzilla.redhat.com/show_bug.cgi?id=1038683.

**Comment by vans88** [comment]
**@justincormack**   Many thanks for your suggestions. Last afternoon, my command "make all" run successfully, That may means kubernetes  has been built done, if so, I wanna close this comment. What do you think of it?

**Comment by qiyongxiao** [comment]
I also meet the proble with this

> ```
> k8s.io/kubernetes/vendor/github.com/google/cadvisor/fs
> k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/system
> # k8s.io/kubernetes/vendor/github.com/docker/docker/pkg/system
> vendor/github.com/docker/docker/pkg/system/stat_linux.go:13: cannot use s.Rdev (type uint32) as type uint64 in field value
> # k8s.io/kubernetes/vendor/github.com/google/cadvisor/fs
> vendor/github.com/google/cadvisor/fs/fs.go:422: cannot use buf.Dev (type uint32) as type uint64 in argument to major
> vendor/github.com/google/cadvisor/fs/fs.go:423: cannot use buf.Dev (type uint32) as type uint64 in argument to minor
> Makefile:79: recipe for target 'all' failed
> make: *** [all] Error 1
> ```
> 
> 显然，文件fs.go中的错误也与“syscall.Stat_t”有关。通过搜索syscall.Stat_t，我从这个链接获得了定义：[https](https://golang.org/pkg/syscall/#Stat_t)：[//golang.org/pkg/syscall/#Stat_t](https://golang.org/pkg/syscall/#Stat_t)
> 
> ```
> type Stat_t struct {
>         Dev       uint64
>         Ino       uint64
>         Nlink     uint64
>         Mode      uint32
>         Uid       uint32
>         Gid       uint32
>         X__pad0   int32
>         Rdev      uint64
>         Size      int64
>         Blksize   int64
>         Blocks    int64
>         Atim      Timespec
>         Mtim      Timespec
>         Ctim      Timespec
>         X__unused [3]int64
> }
> ```
> 
> 见上文，“Dev”和“Rdev”都是“uint64”。
> ```
