### ISSUE TITLE
File-system event CLOSE_WRITE not propagating from host to container

### ISSUE THREAD

**Issue by evanlemke** [docker/docker#28050]
I'm using docker for local development.  When I mount a volume and edit the file from the host machine the "CLOSE_WRITE" event is not propagated to the container.  Many other events like create/delete/modify are working as mentioned here (https://forums.docker.com/t/file-system-events-not-correctly-propagating-from-host-to-container/15201).

here is a simple test case
```
docker run -v /code:/code -it fedora bash
inotifywait -rme modify,attrib,move,close_write,create,delete,delete_self /code/*.txt
```

I get this output after modifying a file from the host machine.
```
/code/file.txt ATTRIB
/code/file.txt MODIFY
```

When I modify the file from inside the container i get the following.
```
/code/file.txt MODIFY 
/code/file.txt CLOSE_WRITE,CLOSE 
```

Host Machine - OS X version 10.11.4
Container Image - Official Fedora
Docker for Mac - 1.12.3-beta29.2

**Comment by justincormack** [comment]
Please can you open the issue in https://github.com/docker/for-mac/issues as it is specific to the mapping of OSX file notification events to Linux ones in Docker for Mac, not a general issue.

**Comment by evanlemke** [comment]
Ok, the issue has been moved here https://github.com/docker/for-mac/issues/896
