### ISSUE TITLE
Swarm panic in keymanager.rotateKey: index out of range

### ISSUE THREAD

**Issue by adaphi** [docker/docker#28067]
**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: pending
 NodeID:
 Is Manager: false
 Node Address: 10.199.50.146
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.21-rancher
Operating System: RancherOS v0.7.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-10-199-50-146.aws.company.com
ID: LQ7Z:2BN3:4DXF:KL5R:BHIF:7HQE:BVTT:PIXQ:XCD7:UF3B:56OJ:UOKR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 35
 System Time: 2016-11-04T10:53:42.936383693Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker swarm on three AWS ec2 instances, running rancherOS v0.7.0

**Additional Information:**
We create a swarm on three machines as they start, using an init script (the first one to run creates the swarm and gets to be master, the other two join as workers). Most of the time it is stable for a while, but eventually the master panics and dies:

```
time="2016-11-03T17:33:17.911332106Z" level=debug msg="Assigning addresses for endpoint gateway_ingress-sbox's interface on network docker_gwbridge"
time="2016-11-03T17:33:17.911355293Z" level=debug msg="RequestAddress(LocalDefault/172.18.0.0/16, <nil>, map[])"
time="2016-11-03T17:33:17.918615099Z" level=debug msg="Assigning addresses for endpoint gateway_ingress-sbox's interface on network docker_gwbridge"
time="2016-11-03T17:33:17.965977986Z" level=debug msg="Programming external connectivity on endpoint gateway_ingress-sbox (7747f460e03b8686321f24bd5f9814d9ff49d2708bab2f07406343a43314a6d8)"
time="2016-11-03T17:35:13.957511582Z" level=debug msg="Calling GET /version"
time="2016-11-03T17:35:13.960010580Z" level=debug msg="Calling GET /v1.24/swarm"
time="2016-11-03T17:36:37.059151036Z" level=debug msg="Calling GET /v1.24/version"
time="2016-11-03T17:36:58.207552031Z" level=debug msg="Calling GET /version"
time="2016-11-03T17:36:58.209370108Z" level=debug msg="Calling GET /v1.24/swarm"
panic: runtime error: index out of range

goroutine 435 [running]:
panic(0x1b1e1c0, 0xc820012030)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/swarmkit/manager/keymanager.(*KeyManager).rotateKey(0xc820ee63c0, 0x7fd97453ddf0, 0xc82032fa80, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/keymanager/keymanager.go:139 +0xd29
github.com/docker/swarmkit/manager/keymanager.(*KeyManager).Run(0xc820ee63c0, 0x7fd97453ddf0, 0xc82032fa80, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/keymanager/keymanager.go:217 +0x7ae
github.com/docker/swarmkit/manager.(*Manager).Run.func2.2(0x7fd97453ddf0, 0xc82032fa80, 0xc820ee63c0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:358 +0x4a
created by github.com/docker/swarmkit/manager.(*Manager).Run.func2
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:361 +0x14b9
```

This puts it into a cycle of trying to restart and panicking again (though with a slightly different error after the first time):

```
time="2016-11-04T05:33:21.725650259Z" level=debug msg="libcontainerd: containerd connection state change: READY"
time="2016-11-04T05:33:25.081305327Z" level=info msg="3da1eb410c6175ff is starting a new election at term 2"
time="2016-11-04T05:33:25.081441634Z" level=info msg="3da1eb410c6175ff became candidate at term 3"
time="2016-11-04T05:33:25.081462656Z" level=info msg="3da1eb410c6175ff received vote from 3da1eb410c6175ff at term 3"
time="2016-11-04T05:33:25.081492789Z" level=info msg="3da1eb410c6175ff became leader at term 3"
time="2016-11-04T05:33:25.081507133Z" level=info msg="raft.node: 3da1eb410c6175ff elected leader 3da1eb410c6175ff at term 3"
time="2016-11-04T05:33:25.083329347Z" level=error msg="agent: session failed" error="session initiation timed out" module=agent
time="2016-11-04T05:33:25.083472100Z" level=debug msg="agent: rebuild session" module=agent
panic: runtime error: index out of range

goroutine 188 [running]:
panic(0x1b1e1c0, 0xc820012030)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/swarmkit/manager/keymanager.(*KeyManager).Run(0xc820ab2e00, 0x7fe020534e20, 0xc8208c34c0, 0x0, 0x0)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/keymanager/keymanager.go:191 +0x9f5
github.com/docker/swarmkit/manager.(*Manager).Run.func2.2(0x7fe020534e20, 0xc8208c34c0, 0xc820ab2e00)
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:358 +0x4a
created by github.com/docker/swarmkit/manager.(*Manager).Run.func2
        /go/src/github.com/docker/docker/vendor/src/github.com/docker/swarmkit/manager/manager.go:361 +0x14b9
```

(full debug log [docker.log.txt](https://github.com/docker/docker/files/571317/docker.log.txt))

I fully expect this is something strange we've done to it, but I haven't been able to figure out what...

**Comment by jiaweizhou** [comment]
I think here is the bug.
[https://github.com/docker/swarmkit/blob/master/manager/keymanager/keymanager.go#L190](url)
It does not check if clusters is empty.

**Comment by sanimej** [comment]
@aaronlehmann panic is at https://github.com/docker/docker/blob/v1.12.1/vendor/src/github.com/docker/swarmkit/manager/keymanager/keymanager.go#L139

There is a check for error from the store read. Any idea why the cluster object might not be available ? We can add a check; but want to confirm if not being to find the cluster object is a symptom of some other issue.

@adaphi After you create the cluster does everything work ok; ie: service create, accessing the service etc. ?

**Comment by adaphi** [comment]
@sanimej Yes, everything is fine until it panics, as far as we can tell.

**Comment by aaronlehmann** [comment]
@sanimej: That is strange indeed. I would not expect this slice to come back zero-length in steady-state operation. More logs from the managers might shed light on what's going on.

In any case, there should definitely be a check on the length of the slice before accessing index 0.

Also, I'd suggest upgrading to 1.12.3. There have been a few key raft bug fixes since 1.12.1 that might be a factor here.

**Comment by adaphi** [comment]
@aaronlehmann I attached the full debug-level log on the end of the original report. We didn't use the cluster in that particular instance (it actually died almost immediately, which is unusual). I can try and replicate the issue on one that runs a little longer, if that helps?

**Comment by aaronlehmann** [comment]
Thanks for the log. I'd be curious to see the files in `/var/lib/docker/swarm/raft`. Please don't post them here unless this is a throwaway cluster, since they contain private keys. If you want to send them privately, my email address is aaron.lehmann@docker.com. Thanks.

**Comment by adaphi** [comment]
Thanks. I've mailed those on to you just now.

**Comment by aluzzardi** [comment]
> In any case, there should definitely be a check on the length of the slice before accessing index 0.

True - but our only outcome at that point is to panic anyway :/

This should never happen in the first place ...

@adaphi Can you confirm the cluster **was** running at some point?

Also - are you issuing `docker swarm update` commands at all (either manually or automatically)?

Is the manager panicking while idle or are you running commands through the API?

Any other information that might help us repro the same environment?

Thanks!

**Comment by aaronlehmann** [comment]
Thanks very much for sending the files. Unfortunately, I haven't been able to reproduce the problem using them. I was able to confirm that there is a cluster object defined in this raft log. It's very strange that `FindClusters` apparently does not pick it up. It's also interesting that the first stack trace shows that it would have accessed the cluster object before calling `rotateKey`, without no panic at that time.

**Comment by adaphi** [comment]
I'll describe the setup in full:
We're using a CloudFormation template to create an auto-scaling group of 3 AWS spot instances, with rancher. The template defines a script that generates TLS certs and pulls a swarm-init docker image from our registry.
The init image has a simple script that looks to see if a swarm exists and if not, creates one. We make sure the instances have a staggered start, so the first one to come up creates the swarm and becomes the master, the other two find the existing swarm and join in. The script also registers the private IP with consul (running elsewhere).
We were using this cluster during the day with no problems, running a bunch of services, so it definitely works when it first comes up. However overnight (while idle) it would invariably panic and crash. To aid with the debugging I created another group from the same template, with debug logging on. This new test cluster isn't actually in use, but still has the panic (which is what I posted above).
To work around spot instance availability, we have a swarm maintainer script that deregisters dead instances from consul, and will recreate the swarm if it thinks it isn't working. This is the only other thing that could have possibly touched the test cluster, since it drives from consul. However we disabled it as a first step - in the log I posted above, I turned the maintainer off before bringing up the instances.
It might be interesting to note: if the maintainer notices that the registered master isn't working, it will recreate the swarm with one of the other nodes as master. When it's on, and the current master panics, it does exactly that - which causes the new master to start panicking. It then promotes the last node which also starts panicking. This is the behaviour we initially saw - all three nodes would be in the panic loop shown in the logs. In the case of the test cluster without the maintainer running, only the original master panics; the other two nodes are just sitting waiting for it to come back.

I don't actually have access to any of this from where I am at the moment. On Monday I'll be able to confirm some details about the scripts and I'll re-run the test cluster, make sure I can run services on it, etc.

**Comment by adaphi** [comment]
We restarted both clusters (the one in use and the test one) over the weekend, and today the masters in both clusters have panicked as described. The four worker nodes are fine. The swarm-maintainer I mentioned has been disabled all this time so it can't be involved. Also, the cluster that is in use is still running containers on the worker nodes, which proves that it was working when it first started.

Regarding the swarm-init script, this is what it does (all using the python docker client):
* Check docker api version >= 1.24
* Check docker info for any current swarm
* Makes a http request to amazon to get some metadata
* Looks in consul to see if the swarm exists yet
* If so, talks to the master to get the join token, and joins the swarm
* If not, does a swarm init to create it
* Waits for the swarm to be properly available
* Registers itself with consul

**Comment by adaphi** [comment]
`docker info` from the manager at the start:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: active
 NodeID: b8h9smmolme0u477vk55siw0f
 Is Manager: true
 ClusterID: bjmjtdp0j2yic57lykix3tn7b
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 10
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.199.18.148
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.21-rancher
Operating System: RancherOS v0.7.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-10-199-18-148.aws.openbet.com
ID: H4PJ:BLEG:NSOG:QNVM:VARD:YOWA:ILJZ:GXOG:IFQE:ZNER:GD5X:H3LX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 132
 System Time: 2016-11-07T12:58:11.154001793Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

from one of the workers:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.1
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: active
 NodeID: 406i3cnwm6bm6f1wioie7qxel
 Is Manager: false
 Node Address: 10.199.18.208
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.21-rancher
Operating System: RancherOS v0.7.0
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: ip-10-199-18-208.aws.openbet.com
ID: HKIO:PJUU:OBDY:HLHO:L56B:XLOG:2VVD:HSHK:CKOX:5AFX:LHAZ:NX7V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 67
 System Time: 2016-11-07T12:58:38.517051075Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Comment by thaJeztah** [comment]
> if the maintainer notices that the registered master isn't working, it will recreate the swarm with one of the other nodes as master.

Curious; Is there a reason you're not configuring the swarm for high availability (and configure multiple managers as master)? You seem to be duplicating what swarm mode itself already does

**Comment by adaphi** [comment]
Eventually there'll be multiple. Currently we only have two availability zones; if we had three managers then a price hike in one zone could take out two at once and render the cluster unusable (since they're just spot instances). With only one master we can recover from price changes things slightly more easily. When we have a third AZ we'll probably do as you describe, since there'll be less chance of a price change breaking the cluster entirely.

**Comment by aaronlehmann** [comment]
@adaphi: Can you please try upgrading to Docker 1.12.3?

**Comment by adaphi** [comment]
Would love to, we have an open ticket with rancher about making it available - sadly there's no AMI with it yet, so we're a bit stuck. We'll see if we can recreate on a different base image (e.g. ubuntu with 1.12.3 installed)

**Comment by adaphi** [comment]
As an update: we've tried creating three separate spot instances and manually creating the swarm, and it works perfectly well. So we're assuming there's something in our CloudFormation template causing the issue. I'm going to rule as much out as I can, hopefully I can come up with a minimal template that recreates the problem.

**Comment by thaJeztah** [comment]
Thank you @adaphi

**Comment by aluzzardi** [comment]
Thank you @adaphi, much appreciated

Even if it turns out that the root cause in your CloudFormation template, we're very much interested to hear about it as we should have prevented misuse of the cluster in the first place

**Comment by adaphi** [comment]
A quick update on where we are:
There's an AMI with rancherOS v0.7.1 and has docker 1.12.3 available so we're testing that out now, should have the results this week.
I've also confirmed that it is something to do with our swarm-init container process - a cluster without it (with swarm commands run manually) works perfectly well, but pulling and running that container (even outside of the CloudFormation template) causes it to panic eventually.

**Comment by aluzzardi** [comment]
That's great, thanks!

If you can give us access to your swarm-init container process we could set
it up on our side and help you investigate the root cause

**Comment by adaphi** [comment]
Hey,
I've managed to reproduce on docker 1.12.3 with rancherOS v0.7.1, so that doesn't fix it :(
I'm working on getting permission to release the swarm-init code. Also trying to take various parts of it away to see if I can determine the problem directly.

**Comment by adaphi** [comment]
[swarm-init.zip](https://github.com/docker/docker/files/616247/swarm-init.zip)

This is a copy of the swarm-init script and Dockerfile.

We've been unable to get any further in our debugging as we've had to shut down the clusters and move back to something a bit more stable.

**Comment by aaronlehmann** [comment]
Thanks for the script. This is finally making sense.

The key bit is this:

```
    spec = client.create_swarm_spec(
        name=config['swarm_name']
    )

    try:
        result = client.init_swarm(
            advertise_addr=config['interface'],
            listen_addr='0.0.0.0:2377', 
            force_new_cluster=False,
            swarm_spec=spec
        )
```

Let me back up and explain a little bit about the cluster object. This stores cluster-level settings and metadata like network encryption keys. Currently there is only a single cluster object, named `default`, however it was designed with federation in mind, so in the future it may be possible to have multiple cluster objects.

However, the API allows you to provide a cluster spec (in a field called `swarm_spec` in the code above). If you provide one with a name other than `default`, it actually renames the cluster object!

So the key manager looks for the cluster object named `default`, but doesn't find it. This causes the panic.

I'll submit a fix for Docker to make it refuse any cluster spec with a name other than `default`. As a workaround, I believe hardcoding the name of the swarm spec to `default` will solve the problem.

This explains why no one else had reported the bug. The CLI always uses the name `default`, so it is only possible to trigger this through the API.

**Comment by aaronlehmann** [comment]
Opened #28914 to validate that specs provided to the API use the canonical name.

**Comment by adaphi** [comment]
Awesome! Thanks everyone for all your help in investigating this, and for the resolution and workaround. I lost more than a few hairs over this one!

**Comment by yayuntian** [comment]
LGTM

**Comment by yayuntian** [comment]
But the RESTful API  swarm update does not seem to do the operation check（check spec name）, will panic , and do not know when it will trigger this operation, the other hope to support fix swarm cluster name, there is this plan?
