### ISSUE TITLE
ApplyLayer exit status 1 on ZFS

### ISSUE THREAD

**Issue by mskarbek** [docker/docker#28071]
**Description**
Docker fails to load image if storage driver is set to ZFS, the same image loads correctly on Device Mapper.

**Steps to reproduce the issue:**
1. docker load -i ~/path/to/image_file.tar.xz

**Describe the results you received:**
````
Error response from daemon: ApplyLayer exit status 1 stdout:  stderr: operation not supported
````

**Describe the results you expected:**
Docker should correctly load image.

**Additional information you deem important (e.g. issue happens only occasionally):**
Replicates on two different hosts (both physical).

**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-9.git667d6d1.fc24.x86_64
 Go version:      go1.6.1
 Git commit:      667d6d1/1.10.3
 Built:           
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-1.10.3-9.git667d6d1.fc24.x86_64
 Go version:      go1.6.1
 Git commit:      667d6d1/1.10.3
 Built:           
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.10.3
Storage Driver: zfs
 Zpool: storage
 Zpool Health: ONLINE
 Parent Dataset: storage/docker
 Space Used By Parent: 19456
 Space Available: 282092225024
 Parent Quota: no
 Compression: lz4
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.8.4-200.fc24.x86_64
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 15.58 GiB
Name: <removed>
ID: RP6J:5KOC:B6Y3:MDMM:KY4A:3V4D:5COM:DJ6L:JQIZ:3DWX:3CYV:FAX5
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- two physical hosts
- Fedora 24 - all available updates installed
- ZFS - official ZFS On Linux repo, latest stable release (0.6.5.8)

**Comment by dnephin** [comment]
Any chance you're able to try Docker 1.12? There have been two major releases since 1.10.3

**Comment by mskarbek** [comment]
I quickly tested version 1.12 from official Docker repository - it behaves correctly but unfortunately I'm not able to use it. I'm relaying on enhancements made by RedHat but refused by mainline Docker.
Looks like I'll have to wait until Fedora 25 release.

**Comment by dnephin** [comment]
Thanks for confirming the issue is fixed.
