### ISSUE TITLE
Docker 1.12.3 has different permissions behavior than 1.12.2 for files bind-mounted over top of existing files

### ISSUE THREAD

**Issue by chriskuehl** [docker/docker#28083]
**Description**

Docker 1.12.3 has different permissions behavior than 1.12.2 for files bind-mounted over top of files already existing in the image.

**Steps to reproduce the issue:**
1. Create a `Dockerfile`:
    ```Dockerfile
    FROM busybox
    RUN touch /asdf && chmod 644 /asdf
    ```
2. Build the image: `docker build -t mytest .`
3. Create a file locally and give it restrictive permissions: `echo secret > asdf && chmod 400 asdf`
4. Run the image created above as nobody while mounting the local file on top of the `/asdf` file in the image:
    ```
    docker run --user=nobody -v $(pwd)/asdf:/asdf:ro mytest ls -l /asdf
    docker run --user=nobody -v $(pwd)/asdf:/asdf:ro mytest cat /asdf
    ```

**On Docker 1.12.2 the results I receive are:**
```
ckuehl@hal:/tmp/tmp.5JFqKZGCr1$ sudo docker run --user=nobody -v $(pwd)/asdf:/asdf:ro mytest ls -l /asdf
-r--------    1 28460    1000             7 Nov  4 23:22 /asdf
ckuehl@hal:/tmp/tmp.5JFqKZGCr1$ sudo docker run --user=nobody -v $(pwd)/asdf:/asdf:ro mytest cat /asdf
secret
```

**On Docker 1.12.3 the results I receive are:**
```
ckuehl@hal:/tmp/tmp.5JFqKZGCr1$ sudo docker run --user=nobody -v $(pwd)/asdf:/asdf:ro mytest ls -l /asdf
-r--------    1 28460    1000             7 Nov  4 23:22 /asdf
ckuehl@hal:/tmp/tmp.5JFqKZGCr1$ sudo docker run --user=nobody -v $(pwd)/asdf:/asdf:ro mytest cat /asdf  
cat: can't open '/asdf': Permission denied
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The new behavior seems like it's better, but I can't find anything relevant in the changelog, and we were surprised to see this behavior change in a patch release without any documentation. We may well have been relying on a bug, but if this is expected behavior, it'd be nice to at least have more context.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:43:41 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 17:43:41 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 30
 Running: 0
 Paused: 0
 Stopped: 30
Images: 57
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-0:37-37178-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 17.41 GB
 Data Space Total: 107.4 GB
 Data Space Available: 50.13 GB
 Metadata Space Used: 22.4 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.125 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.90 (2014-09-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay null bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.7.0-0.bpo.1-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 125.9 GiB
Name: hal
ID: IT5Z:JBGZ:CXGO:GFWD:TZ23:AJGU:LWTH:2VFW:77PP:2Y77:KF7Q:ARUD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical. `/var/lib/docker` is a tmpfs (it's unclear to me why `docker info` says it's `ext4`).

**Comment by thaJeztah** [comment]
ping @justincormack is this related to the RunC change?

**Comment by cpuguy83** [comment]
@chriskuehl Did you try this on any version other than 1.12.2? I suspect it would have given permission denied there as well.

**Comment by cpuguy83** [comment]
Relevent change is likely this: https://github.com/docker/docker/pull/27610
This behavior would have only been in 1.12.2.

**Comment by chriskuehl** [comment]
Yup, confirmed this behavior doesn't seem to exist in 1.12.0 or 1.12.1, so I think it's safe to say we were just relying on a bug.

Sorry for missing that in the changelog. I did read "Fix ambient capability usage in containers" but didn't consider it might be related to this issue. I'm happy to close this issue now.

**Comment by cpuguy83** [comment]
Thanks, Chris! Sorry for the confusion!
