### ISSUE TITLE
add backwards compatibility for docker info api change from #26276

### ISSUE THREAD

**Issue by vikstrous** [docker/docker#28113]
#26276 introduced a backwards incompatible api change in the docker info api. If the client reports a lower API version than 1.25, we need to return a response using the old format.

**Comment by runcom** [comment]
@vikstrous can you tell me more about this issue you're facing?

```sh
$ curl --unix-socket /var/run/docker.sock http:/v1.24/info | jq '.SecurityOptions'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2068    0  2068    0     0   156k      0 --:--:-- --:--:-- --:--:--  168k
[
  "seccomp"
]
$ curl --unix-socket /var/run/docker.sock http:/v1.25/info | jq '.SecurityOptions'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2158    0  2158    0     0   234k      0 --:--:-- --:--:-- --:--:--  263k
[
  {
    "Key": "Name",
    "Value": "seccomp"
  },
  {
    "Key": "Profile",
    "Value": "/home/amurdaca/src/github.com/docker/docker/profiles/seccomp/default.json"
  }
]
```

**Comment by runcom** [comment]
Are you using the API client? I can only imagine there's a problem there because the client uses the wrong `types.Info` struct. I don't know docker has ever kept backward compatibility there.

**Comment by runcom** [comment]
Alright, I figured this was an issue in the API client. Opened https://github.com/docker/docker/issues/28118 which fixes it (it was a version issue)
