### ISSUE TITLE
"docker exec {CONTAINER ID} powershell" hangs when container is stopped/killed

### ISSUE THREAD

**Issue by cons0l3** [docker/docker#28119]
@friism asked me to open the issue with docker/docker (previously opened at docker/for-win/issues/206 and ping @jhowardmsft .

# Expected behavior

if `PS C:> docker run -it microsoft/windowsservercore powershell` is exited while a second `PS C:> docker exec -it {CONTRAINER ID} powershell` is running. The second `docker exec powershell` will also exit the container and return to the calling shell.

# Actual behavior

The `docker exec {CONTAINER ID} powershell` hangs.

# Steps to reproduce the behavior

1. `docker run -it microsoft/windowsservercore powershell`
2. `docker exec -it {CONTAINER ID} powershell`
3. `exit` the container from step 1. It returns to the powershell it was called from. Excellent.
4. try to do anything in the second (from step 2.) powershell. It hangs.

# Docker info

PS D:\Entwicklung\docker-w-python> docker info
Containers: 3
Running: 0
Paused: 0
Stopped: 3
Images: 18
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 11.99 GiB
Name: BLAUBEERE10
ID: E2WR:C7YS:2BZ5:TNFX:NCJL:FZPY:6U6F:3MFC:CBX4:DJCP:LZFO:RZS3
Docker Root Dir: E:\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
127.0.0.0/8

# Docker Version

PS D:\docker-w-python> docker version
Client:
Version: 1.12.3
API version: 1.24
Go version: go1.6.3
Git commit: 6b644ec
Built: Thu Oct 27 00:09:21 2016
OS/Arch: windows/amd64
Experimental: true

Server:
Version: 1.12.2-cs2-ws-beta
API version: 1.25
Go version: go1.7.1
Git commit: 050b611
Built: Tue Oct 11 02:35:40 2016
OS/Arch: windows/amd64

# Windwos host, Windows container, Powershell Versions
PS C:\Users\carst> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.206
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.206
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by jhowardmsft** [comment]
@darrenstahlmsft Could you PTAL. Thanks.

**Comment by darrenstahlmsft** [comment]
I'll take a look this afternoon, but I have a strong suspicion that this might've been fixed 5 mins ago by https://github.com/docker/docker/pull/27615, but I need stacks to confirm. I'll confirm soon.

**Comment by darrenstahlmsft** [comment]
Confirming that this was fixed by #27615. 
![execexit](https://cloud.githubusercontent.com/assets/14114019/20114609/ca59fc8e-a5a9-11e6-803c-81c4caf58e03.png)

**Comment by jhowardmsft** [comment]
Thanks @darrenstahlmsft. Closing.
