### ISSUE TITLE
docker pull microsoft/windowsservercore returns connection forcibly closed error.

### ISSUE THREAD

**Issue by git-jiby-me** [docker/docker#28110]
**Description**

In latest windows nano server, with current master build of docker daemon, when pulling any images (for example microsoft/windowsservercore) it returns an error saying 

```
docker : Error response from daemon: Get https://registry-1.docker.io/v2/microsoft/windowsservercore/manifests/latest:
read tcp 10.0.2.15:49858->52.5.234.85:443: wsarecv: An existing connection was forcibly closed by the remote host.
    + CategoryInfo          : NotSpecified: (Error response ...he remote host.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Steps to reproduce the issue:**
1. Setup current master build of docker in windows nano
2. docker pull microsoft/windowsservercore

**Describe the results you received:**

```
docker : Error response from daemon: Get https://registry-1.docker.io/v2/microsoft/windowsservercore/manifests/latest:
read tcp 10.0.2.15:49858->52.5.234.85:443: wsarecv: An existing connection was forcibly closed by the remote host.
    + CategoryInfo          : NotSpecified: (Error response ...he remote host.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

**Describe the results you expected:**

windowsservercore image should be pulled.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue seems to have recently crept in, and i doubt if this is related to something in golang, since i see such error reports in their test fails.

**Output of `docker version`:**

Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   c5ceb0f
 Built:        Sat Nov  5 03:24:43 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   c5ceb0f
 Built:        Sat Nov  5 03:24:43 2016
 OS/Arch:      windows/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.351.amd64fre.rs1_release_inmarket.161014-1755)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 1024 MiB
Name: Nano
ID: YW4I:IDUQ:VG5A:PEG5:3LCZ:3LI7:4SBS:NOL2:G7ZB:XEZU:ZRKB:GQ2R
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 21
 System Time: 2016-11-06T18:37:48.7473063Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The nano server is running inside VirtualBox

**Comment by Kalle80** [comment]
I have the same error when I try to pull IIS server with normal desktop version of Windows Server 2016. Server is running in VirtualBox 5.1.8 on Mac 

`PS C:\Users\Administrator> docker run -it -p 80:80 microsoft/iis
Unable to find image 'microsoft/iis:latest' locally
C:\Program Files\Docker\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/microsoft/iis/manife
sts/latest: Get https://auth.docker.io/token?account=eekamak&scope=repository%3Amicrosoft%2Fiis%3Apull&service=registry.
docker.io: read tcp 10.0.2.15:49805->52.45.33.149:443: wsarecv: An existing connection was forcibly closed by the remote
 host..`

**Comment by martinmosegaard** [comment]
I got these errors on VirtualBox. For me, it helped to change the VM's network from `NAT` to `NAT Network`.

**Comment by git-jiby-me** [comment]
it seems the problem is related to virtualbox rather than docker itself, i downgraded to virtualbox 5.1.6 and everything started working, hence closing the issue.
