### ISSUE TITLE
libnetwork/drivers/bridge -- allow use of an existing pre-configured bridge

### ISSUE THREAD

**Issue by awhitcroft** [docker/docker#28125]
The bridge libnetwork driver allows use of networks based on bridges as networks within Docker. I would be nice to be also able to attach a Docker network to a pre-existing bridge without affecting the configuration of that bridge.

**Comment by aboch** [comment]
@awhitcroft This should already be possible:

```
docker network create --subnet <your bridge subnet> --gateway <your bridge IP> --opt com.docker.network.bridge.name=<your bridge name> <your network name>
```

In docker 1.13, thanks to https://github.com/docker/libnetwork/pull/1301, the bridge won't be touched when you remove the docker network.

**Comment by cpuguy83** [comment]
@aboch So the bridge will be removed on 1.12? 😨

**Comment by aboch** [comment]
@cpuguy yes, in any docker version < 1.13.x

**Comment by aboch** [comment]
@awhitcroft Was your question answered ?

**Comment by aboch** [comment]
With no more information from submitter, I am closing this request because docker 1.13.x will allow to create bridge network backed by existing linux bridge, and the bridge won't be removed on network removal.
