### ISSUE TITLE
Request: Image creation events during docker build

### ISSUE THREAD

**Issue by leth** [docker/docker#28120]
I'd like the API **container commit** event to include the ID of the image it created. 

I have a small util which tracks how recently docker images have been used, and cleans up dangling images after some time if they have not been reused.
To do this I need to keep track of image creation, however layers created by docker build come from container commit events, which do not tell you the ID of the image.

**Comment by leth** [comment]
Hmm, I suppose a more general request would be for the build stage to emit events directly.

**Comment by justincormack** [comment]
Adding the image ID to the commit event is probably quite simple, and seems reasonable - do you want to have a go at a PR?

**Comment by leth** [comment]
Hmm, I guess I could have a go
