### ISSUE TITLE
docker doesn't service after we using exec -it /bin/bash to run background command with & and exit

### ISSUE THREAD

**Issue by KevinTHU** [docker/docker#28155]
**Description**
docker doesn't service after we using exec -it /bin/bash to run background command with & and exit

**Steps to reproduce the issue:**
1. docker run -d --name=hx-123-test centos ping www.baidu.com
2. docker exec -it hx-123-test /bin/bash
3. ping www.sina.com &
4. exit   [sometimes run exit may not be ok to exit /bin/bash, because the stdout is printing, so you kan click exit quickly for more times]
5. docker ps

**Describe the results you received:**
docker ps will not work, also docker run.... docker doesn't service, but the docker service is still running, btw, this docker is in a 3 docker physical node swarm-alone cluster, other docker node can still use docker ps command, and list the docker cantainers on the problem docker node. 

**Describe the results you expected:**
at least docker service should not become unusable

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 246
 Running: 12
 Paused: 0
 Stopped: 234
Images: 45
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 57.81 GB
 Data Space Total: 1.1 TB
 Data Space Available: 1.042 TB
 Metadata Space Used: 21.42 MB
 Metadata Space Total: 10.74 GB
 Metadata Space Available: 10.72 GB
 Thin Pool Minimum Free Space: 110 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null vlcp overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.6 GiB
Name: kvm-yz-dev-073-003-004
ID: CED3:DJX6:VW6I:LJLX:CEVJ:Z4L2:FYPX:KTIQ:CTO2:4JRD:U7L3:WN4L
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 100
 Goroutines: 180
 System Time: 2016-11-08T15:59:13.781008258+08:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: zk://100.73.3.4:2181,100.73.3.5:2181,100.73.3.6:2181
Cluster Advertise: 100.73.3.4:2375
Insecure Registries:
 jdocker.me
 127.0.0.0/8

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
3 centos7.2 pythsical machine, a swarm stand-alone cluster

**Comment by cpuguy83** [comment]
@KevinTHU I know there were problems specifically with docker exec around this.
Can you try with 1.12.3? I see you are on 1.12.1.

**Comment by KevinTHU** [comment]
@cpuguy83 ok, I will take a test in 1.12.3 in the next few days, but this test is easy, I think some one who has a 1.12.3 environment can test it soon.

**Comment by shaynewang** [comment]
#dibs I'll test it and see what I find

**Comment by thaJeztah** [comment]
@KevinTHU @shaynewang have you had time to test on 1.12.3?

**Comment by KevinTHU** [comment]
@thaJeztah it's ok on 1.12.3

**Comment by thaJeztah** [comment]
Thanks for testing! Let me close this issue then
