### ISSUE TITLE
WebSocket attach endpoint can send non-UTF-8 data in text frames

### ISSUE THREAD

**Issue by wsong** [docker/docker#28176]
**Description**

The WebSocket container attach endpoint at `/containers/<container ID>/attach/ws` always sends text frames, but the data contained within those frames is just the bytestream from the container's stdout or stderr. This means that the text frames may not contain valid UTF-8 data, but the WebSocket spec requires that text frames only contain valid UTF-8:

https://tools.ietf.org/html/rfc6455#section-8.1

Web browsers such as Chrome, for instance, will automatically close a WebSocket connection if they get invalid UTF-8 data in a text frame.

**Steps to reproduce the issue:**
One can create a container that creates invalid UTF-8 data by simply doing:

```
docker run -it busybox sh -c "while true; do echo -e '\\xc3\\x28'; done"
```

**Describe the results you received:**
Got invalid UTF-8 bytes in a WebSocket text frame.

**Describe the results you expected:**
The frames would either be marked as binary frames or their contents would be sanitized somehow.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Server:
 Version:      1.12.2-cs2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5fda6e
 Built:        Wed Oct 12 22:55:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 73
Server Version: 1.12.2-cs2
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.24-boot2docker
Operating System: Boot2Docker 1.12.1 (TCL 7.2); master : 4b170dc - Fri Oct  7 22:28:40 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default-cs
ID: AMY7:2Q4A:QOPC:LLOK:7C5O:OOTV:Q7OS:5RZN:QBQR:DC3B:DFXB:MPL6
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 125
 System Time: 2016-11-08T19:52:31.989430161Z
 EventsListeners: 0
Username: wsongdocker
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Would changing this be a backward incompatible change?

**Comment by wsong** [comment]
Some WebSocket clients, like the standard golang library, treat both text and binary frames as the same; however, most clients (and in particular Javascript) require users to define separate handlers for text and binary frames. Thus, if the Docker daemon started sending binary frames instead of text frames, clients would have to update their code.

Maybe we could have a `binary=1` query var or something to get around this.

**Comment by thaJeztah** [comment]
Yes, I was thinking about that as an option. Is there something in the frame that _indicates_ if it's a binary frame or a text frame? (Versioning it in the API would be an alternative, so trying to get clear what the options are)

**Comment by wsong** [comment]
Yes, WebSocket frames have a byte indicating what kind of frame they are (text frames, binary frames, ping frames, etc.).

**Comment by bfirsh** [comment]
If this will potentially break clients, it sounds like we should put this behind an API version change.

I don't think there's any point giving users an option – the old method sounds broken. But, users have presumably been working around the brokenness, which is why we should version it. ;)

**Comment by yongtang** [comment]
@wsong @thaJeztah @bfirsh Added #30460 a PR to change the text frame to binary frame. Please take a look.

**Comment by justincormack** [comment]
I would think it might be better to sanitise data to utf8 for websocket.
Logs are not intended to be arbitrary binary data, they are line delimited
text I think.

**Comment by justincormack** [comment]
Hmm though I guess some use cases are binary though...
