### ISSUE TITLE
Allow rename() on /etc/resolv.conf & /etc/hosts

### ISSUE THREAD

**Issue by jchia** [docker/docker#28187]
**Description**
This is a feature request to allow rename() to work on /etc/resolv.conf & /etc/hosts. Currently, adding a new file to /etc, writing to /etc/resolv.conf & /etc/hosts work, but renaming these two files fails.

**Steps to reproduce the issue:**
1. Run -it a new container for a typical Linux distro, e.g. Fedora.
2. At the shell, issue "mv /etc/hosts /etc/hosts.backup"

**Describe the results you received:**
An error message appears `mv: cannot move '/etc/hosts' to '/etc/hosts.backup': Device or resource busy`. `strace` also indicates that the system call `rename()` fails.

**Describe the results you expected:**
`rename()` on these special files to work. If writing to them and making new files in /etc both work, semantically, it's weird that renaming doesn't work.

**Additional information you deem important (e.g. issue happens only occasionally):**
The use case is that a third-party app I'm trying to run needs to modify /etc/resolv.conf and tries to backup the original version first by renaming it.

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-33587401-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.561 GB
 Data Space Total: 107.4 GB
 Data Space Available: 104.8 GB
 Metadata Space Used: 2.154 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93 (2015-01-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.14-200.fc22.x86_64
Operating System: Fedora 22 (Twenty Two)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.35 GiB
Name: smoothie
ID: XREU:DUUM:7KRY:NRV5:ZHMC:QGPF:JDJO:BJCU:JICF:PGP7:DTUR:I7KA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
This is very difficult, as bind mounting a single file bind mounts the inode, not the name. You can update the file by modifiying it in place, but that is very racy. We could have to bind the new version over the top of the old one in the container, which would leak space for all the old versions. So there does not seem to be a satisfactory way of doing this that anyone has come up with yet.

**Comment by win-t** [comment]
Hi, I know this is an old issue,
but recently, I struggling with this problem.

I propose, instead of bind mount to `/etc/resolv.conf`, `/etc/hostname`, and `/etc/hosts`, we should bind mount it to `/etc/resolv.conf.docker`, `/etc/hostname.docker`, and `/etc/hosts.docker`, and then create symlink when the container started, via oci [hook](https://github.com/opencontainers/runtime-spec/blob/master/config.md#posix-platform-hooks)

**Comment by win-t** [comment]
what do you think @justincormack ?
