### ISSUE TITLE
after install docker from official script host network failed

### ISSUE THREAD

**Issue by L-Jovi** [docker/docker#28191]
hi there, the issue like title say, after my docker installed, I can't ping any website then.

provide my vps information below,

![image](https://cloud.githubusercontent.com/assets/7262199/20127719/84d28d60-a67c-11e6-8027-aa11c5a64c38.png)

and I follow [install-with-the-script](https://docs.docker.com/engine/installation/linux/centos/#/install-with-the-script) and start with below commands __(use root as user)__

    $ curl -fsSL https://get.docker.com/ | sh
    $ systemctl enable docker.service
    $ systemctl start docker

then I find that I can't ping any website after above commands make sense, 

![image](https://cloud.githubusercontent.com/assets/7262199/20127765/1a987940-a67d-11e6-93c1-3a623d28135b.png)

I think maybe above shell script change some config in network, I find some append records from iptables after docker installed.

![image](https://cloud.githubusercontent.com/assets/7262199/20127777/4c2e72ac-a67d-11e6-912e-ca5b78153ff3.png)

but I don't ensure it's relevant with network, what should I do now :(

thanks for your time,

regards.

**Comment by thaJeztah** [comment]
I'm not able to reproduce this (same CentOS version); 

```
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination
DOCKER-ISOLATION  all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (1 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

Are you still having this issue?

**Comment by L-Jovi** [comment]
@thaJeztah  thanks for your reply, I eventual solve it.

someone change rules via firewall-ctl on my centos vps, 

thanks for your time,

regards.

**Comment by thaJeztah** [comment]
Thanks! Good to hear it's resolved
