### ISSUE TITLE
Docker Swarm Mode service does not publish port  to host in Oracle Linux 6.6

### ISSUE THREAD

**Issue by prparmar77** [docker/docker#28190]
**Description**

Docker Swarm Mode service does not publish port  to host in Oracle Linux 6.6 and docker logs shows following error ..

time="2016-11-08T04:10:25-05:00" level=info msg="Firewalld running: false"
time="2016-11-08T04:10:25-05:00" level=error msg="setting up rule failed, [-t nat -A POSTROUTING -m ipvs --ipvs -d 10.255.0.0/16 -j SNAT --to-source 10.255.0.2]:  (iptables failed: iptables -t nat -A POSTROUTING -m ipvs --ipvs -d 10.255.0.0/16 -j SNAT --to-source 10.255.0.2: **iptables v1.4.7: Couldn't load match `ipvs':/lib64/xtables/libipt_ipvs.so: cannot open shared object file: No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n (exit status 2))"**
time="2016-11-08T04:10:25.620384456-05:00" level=error msg="Failed to add firewall mark rule in sbox /var/run/docker/netns/ingress_sbox: reexec failed: exit status 5"

**Steps to reproduce the issue:**

1.Install OEL6.6 with UEK4  - 4.12 Kernel on two nodes
2.Install docker 1.12.2
3.docker run -it --name oel7 oraclelinux /bin/bash
4.Install httpd using yum and commit the image with name say: oel7:1.0
5.Save the image and load the image in second node 
6.Create swarm overlay network with name say: app-wls
7.Initialize Swarm Mode and create simple docker service using above image

8.docker service create --name oel6test -p 80:80/tcp --network app-wls  oel7:1.0 /bin/bash -c "tail -f /dev/null"

Login into node start httpd process ,by default it starts at port 80

9.[root@8154fe407929 /]# /usr/sbin/httpd

**Describe the results you received:**

Try connecting to browser with host ip 
   http://129.144.55.88/ 
11.Check the log and will show error as per description given in bug 

**Describe the results you expected:**

12.I expect that I should be able to browse httpd(Apache Web Page) home page when I access the service with host ip and published port 80 as in command

**Additional information you deem important (e.g. issue happens only occasionally):**

There seems to be bug with iptables module on OEL6.6 linux, the problem may also happen on redhat 6.X linux as both linux flavours supply only iptables-1.4.7 version rpm's and there are no iptables released by neither Oracle nor redhat for 6.x version.

The upgrade to Oracle Linux 7.2 which has latest version of iptables as shown below does not have this issue and I can access the service using published port mapped back to container

[opc@bdfdb9 ~]$ rpm -qa |grep iptables
iptables-services-1.4.21-16.el7.x86_64
iptables-1.4.21-16.el7.x86_64

Note : The check-config.sh does not detect any issue with the iptables version , may check-config.sh needs to have this checks included 

**Output of `docker version`:**

[opc@docker ~]$ sudo docker version

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   19fddc2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   19fddc2
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
[opc@docker ~]$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 11
Server Version: 1.12.2
Storage Driver: btrfs
 Build Version: Btrfs v4.2.2
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: active
 NodeID: 2caur21cl3obi6ievjnxwxdsk
 Is Manager: true
 ClusterID: 82yzwxclfekga3n0xl0dyl1qr
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.106.56.210
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.1.12-61.1.13.el6uek.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.06 GiB
Name: docker
ID: L7U7:IXAX:J5IH:D5VZ:SLLV:ZOZH:SM6E:WV4X:7M37:ZMFL:BPQ5:TMSL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Oracle Public Cloud - Compute Nodes

**Comment by thaJeztah** [comment]
Thanks for reporting @prparmar77, as for RHEL6; we dropped support for RHEL6 over a year ago because there was no longer active support for Docker in the kernel it used. Oracle Linux could still be used because of the updated kernel.

ping @Djelibeybi PTAL

> Note : The check-config.sh does not detect any issue with the iptables version , may check-config.sh needs to have this checks included

Agreed. Even better; if a minimum version is required, perhaps that requirement should be set in the packages (cc @andrewhsu)

**Comment by thaJeztah** [comment]
also ping @mrjana PTAL

**Comment by Djelibeybi** [comment]
Pinging @thtanaka to review.

**Comment by aluzzardi** [comment]
welp @mavenugo

**Comment by Djelibeybi** [comment]
We're internally investigating whether it's time to drop Oracle Linux 6 support due to userspace being too old to handle new Docker requirements.

**Comment by Djelibeybi** [comment]
We just pushed an updated `iptables` package for OL6 which should resolve this issue.

**Comment by thaJeztah** [comment]
Thanks @Djelibeybi - does that mean OL6 remains "supported" by Oracle to run Docker?

**Comment by thaJeztah** [comment]
@prparmar77 are you able to verify if the issue is resolved for you?

**Comment by Djelibeybi** [comment]
At this point, OL6 remains supported by Oracle.

**Comment by prparmar77** [comment]
I tested this with new iptables package from yum repository configured with Oracle Linux ,it is working now .

**Comment by thaJeztah** [comment]
Thanks for testing! Glad to hear it's resolved

**Comment by rashwinkumar** [comment]
@Djelibeybi ,Hello ,can i know the package version of iptables that was pushed to the repo please ?

**Comment by Djelibeybi** [comment]
@rashwinkumar it's fixed in ELEA-2017-3507: https://oss.oracle.com/pipermail/el-errata/2017-January/006630.html

So:

```
iptables-1.4.7-16.0.5.el6.x86_64.rpm
iptables-devel-1.4.7-16.0.5.el6.x86_64.rpm
iptables-ipv6-1.4.7-16.0.5.el6.x86_64.rpm
```

**Comment by aravichandran** [comment]
@Djelibeybi :thanks . It worked like a charm !
