### ISSUE TITLE
1.12.x RPM packages no longer show build-date

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28206]
It looks like something changed in our build-process, resulting in the `Built:` field to be empty in `docker info`.

In docker 1.11.2;

```
yum install docker-engine-0:1.11.2-1.el7.centos.x86_64

 docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
...
```

In docker 1.12.0 (and up);

```
yum install docker-engine-0:1.12.0-1.el7.centos.x86_64

docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:
 OS/Arch:      linux/amd64
...
```

noticed while discussing https://github.com/docker/docker/issues/26487

/cc @vieux @andrewhsu

**Comment by andrewhsu** [comment]
Hmm...yes I can confirm:
```
# docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        
 OS/Arch:      linux/amd64
```

**Comment by thaJeztah** [comment]
Looks like it's set here; https://github.com/docker/docker/blob/77fca662dd71da6be7fd4bb3b40f7074b355607e/hack/make.sh#L85

and here https://github.com/docker/docker/blob/1e673b9876ab4a12e7718424db9484fca6f516b3/hack/make/.go-autogen#L18

**Comment by vdemeester** [comment]
Reverting https://github.com/docker/docker/commit/5e6f8cb4a7f8bf294b3b459d2c2afed6d69fcdf1 makes it back. ping @jhowardmsft :angel:

**Comment by jhowardmsft** [comment]
Hmmm. There's something more to this. I introduced that hack in make.sh in https://github.com/docker/docker/pull/18397 to solve a problem on Windows to Linux CI servers, where the Windows side was running an old version of bash (the only one available at the time), and where `--rfc-3339` wasn't supported, so `date --rfc-3339 ns 2> /dev/null | sed -e 's/ /T/'` was returning a null string.

But that makes no sense why it should be returning an empty string on Linux platforms, unless somehow that statement too is returning null for another reason? (It didn't on my Ubuntu 16.x VM though). 

But also this is affecting 1.12 too, so that shouldn't have anything to do with https://github.com/docker/docker/commit/5e6f8cb4a7f8bf294b3b459d2c2afed6d69fcdf1

Will look some further. This is deeper rooted....

**Comment by jhowardmsft** [comment]
@vdemeester How can I repro this - seems to work on 1.13.0-rc2 on Ubuntu for me:

![image](https://cloud.githubusercontent.com/assets/10522484/20806521/1aa34e6c-b7b0-11e6-93d3-87b72b9f98b2.png)

**Comment by runcom** [comment]
> @vdemeester How can I repro this - seems to work on 1.13.0-rc2 on Ubuntu for me:

is ubuntu using RPM? I'll take a look at this shortly though

**Comment by runcom** [comment]
found it probably
