### ISSUE TITLE
docker tag command usability

### ISSUE THREAD

**Issue by glensc** [docker/docker#28204]
the `docker tag` command has always confused me, because the two arguments can be easily mixed resulting wrong tag overwrite, because docker client doesn't even complain that tag exists.

the usage, printed is not useful at all indicating which of the arguments is SOURCE and which is TARGET tag, i.e which one would be REFERENCED and which one will be CREATED.

```
$ docker tag --help

Usage:  docker tag IMAGE[:TAG] IMAGE[:TAG]

Tag an image into a repository

Options:
      --help   Print usage

```

So to get definitive answer one has to visit [reference documentation](https://docs.docker.com/engine/reference/commandline/tag/#/examples) or just experiment which command works. that is not productive at all.

i think the major confusion cames due the fact that the arguments are reversed from `git(1)` usage.

```
       git tag [-a | -s | -u <keyid>] [-f] [-m <msg> | -F <file>]
               <tagname> [<commit> | <object>]
```

Proposed solutions:
- rename arguments in usage to `REFERENCE[:TAG] IMAGE[:TAG]`
- reject tag creation if tag already exists, unless `-f` option added
- add flag to tag command to reject tag creation if exists (opposite of previous suggestion)

**Comment by oulinbao** [comment]
#dibs

**Comment by coolljt0725** [comment]
> reject tag creation if tag already exists, unless -f option added

the `-f` flag has been removed in https://github.com/docker/docker/pull/23090

**Comment by glensc** [comment]
#23090 does not explain why it was deprecated,  but found from linked docs reference:
https://github.com/docker/docker/blob/v1.10.0/docs/deprecated.md#-f-flag-on-docker-tag

**Comment by ripcurld00d** [comment]
can I take this one?
