### ISSUE TITLE
Infinite loop in names-generator.go

### ISSUE THREAD

**Issue by jbrunk1966** [docker/docker#28239]
in https://github.com/docker/docker/blob/master/pkg/namesgenerator/names-generator.go, in line 557-561, if the outcome of `name` is `boring_wozniak` the resulting goto ends in an infinite loop

**Comment by cpuguy83** [comment]
Is this something you experienced?
It would only be infinite if each time `boring_wozniak` was the result, which is highly unlikely.

**Comment by jbrunk1966** [comment]
Sorry i wasn't aware that rnd.Intn() delivers a new random value each time

**Comment by cpuguy83** [comment]
No worries, thanks for reporting!
