### ISSUE TITLE
[Question] swarm does't schedule containers executed by "docker run" to any swarm nodes ?

### ISSUE THREAD

**Issue by albamc** [docker/docker#28234]
I'm not sure but I remember that before 1.11.x swarm modes, If I run a container by "docker run" command,  containers would be executed in any docker nodes in swarm cluster.
But after 1.12.x version, If I run a container by "docker run", container only executed in docker hosts which docker run command received.
Does swarm cluster's container (not service task) scheduling policy is changed ?
Or just not yet implemented ?

**Comment by cpuguy83** [comment]
`docker run` against classic swarm is scheduled across the cluster.
`docker run` on a swarm-mode enabled docker engine is a node-local command.

Closing since this isn't an issue (or really even a change), but feel free to discuss further.
Thanks!

**Comment by albamc** [comment]
Oh... I understood.
Thanks for your answers!
