### ISSUE TITLE
Implement --network-add and --network-rm for docker service update

### ISSUE THREAD

**Issue by programmerq** [docker/docker#28247]
These were part of the 1.12 cli, but never implemented in the daemon, so the CLI options were taken out in https://github.com/docker/docker/pull/25646.

Having this feature implemented would be great.

**Comment by yongtang** [comment]
I noticed there are some issues related to network names in the current implementation. Currently the network name will be resolved into network ID and the original name will not be kept in ServiceSpec.

As a result, when trying to update the network, it will not be able to track which network should be added and which one should be removed.

One solution is to resolve the network on docker client but that is less than desirable. Another solution is to keep a copy of original network name in ServiceSpce.

I added a docker PR #29463 and a SwarmKit PR (docker/swarmkit#1813) to address the issue first.

**Comment by thaJeztah** [comment]
Also see https://github.com/docker/docker/issues/25876, and https://github.com/docker/swarmkit/issues/1029

**Comment by yongtang** [comment]
Here is a list of items that needs to be done:
- docker/swarmkit#1029 (need to detect changes in network attachment)
- docker/swarmkit#1029 (need to be reverted)
- docker/swarmkit#1813 (or alternatively resolve the network ID at the client side)

**Comment by genki** [comment]
I think the issues affect only to --network-rm behavior.
Even if only --network-add is implemented, it's quite useful to moving services to other newly created networks. @yongtang

**Comment by taiidani** [comment]
Would very much like to see this -- I'm specifying networks in my Compose v3 file and any time they are tweaked I get:
```
Error response from daemon: rpc error: code = 2 desc = changing network in service is not supported
```
I must manually remove the stack's services before I can `docker stack deploy` again.

**Comment by yongtang** [comment]
Add the reference of #30453 here. Currently there are some issues if multiple networks of the same name exist (`CheckDuplicate = false`) as the executor may not be able to locate the correct network. This issue needs to be addressed to move forward.

**Comment by yongtang** [comment]
Also, https://github.com/docker/docker/issues/30242#issuecomment-273517205 is related and needs to be addressed.

**Comment by allamand** [comment]
Would definitely loved to have an option to network-add network-rm additional networks on existing services. My use case : I 've got a Reverse Proxy that can be used to access internal services. Thoses services can also lived internally without this reverse proxy to that they life are separated, but I would like to be able to add the Reverse Proxy to existing service networks, without having to delete/create my reverse proxy
