### ISSUE TITLE
Text information in the web site

### ISSUE THREAD

**Issue by dev-lusaja** [docker/docker#28245]
Guys,
In the web site: 
[]()https://www.docker.com/partners/partner-program

In the section "DOCKER SPOTLIGHT PARTNERS" correct the text that says:

Amazon Web Servces

for 

**Amazon Web Services**

**Comment by thaJeztah** [comment]
Oh, thanks for reporting! I'll pass this on through to the team

I'll close the issue here because this issue tracker is only for the docker open source project, but I'll ask them if they can reply once it's fixed 👍

**Comment by dev-lusaja** [comment]
Ok thnx 👍

**Comment by hansfrederickbrown** [comment]
Fixed
