### ISSUE TITLE
docker: Error response from daemon: containerd: container not started.

### ISSUE THREAD

**Issue by korabelnikov** [docker/docker#28258]
**Description**
cant run container from image
(bug or not?)

**Steps to reproduce the issue:**
1.nvidia-docker run 87d162763d5b

**Describe the results you received:**
docker: Error response from daemon: containerd: container not started.

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
'docker ps -a' shows container with status 'created'

**Output of `docker version`:**
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   bb80604
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**

Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 28
Server Version: 1.12.1
Storage Driver: btrfs
 Build Version: Btrfs v4.7.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nvidia-docker
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-gentoo
Operating System: Gentoo/Linux
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 251.8 GiB
Name: Beelzebub
ID: CYUG:T3FX:PPBU:HOPF:LCKV:5WWS:DUJJ:ICHZ:2O3F:EMKP:QFPX:5BOB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by kunalkushwaha** [comment]
> 1.nvidia-docker run 87d162763d5b
It seems you are running a container which was already created?
How this container was created?

**Comment by korabelnikov** [comment]
@kunalkushwaha  thank for quck reply.

> It seems you are running a container which was already created?

I run and image with 'docker run' command.
As i know it creates new container from image and run it. I make a few containers in past with 'run' and image name.
Maybe i'm wrong in smth, feel free to correct me.

the full command is 
nvidia-docker run -dit -v /avtoplan_data/Learning/:/root/host/ -p 34448:34448 -p 32022:22 -p 32000:5000 --entrypoint /bin/bash --name smedx-kor2 87d162763d5b

whe 87d162763d5b is id of image, that i comitted before

**Comment by kunalkushwaha** [comment]
@korabelnikov your command is correct. and yes ``docker run`` creates container.

Is it easily reproducable? 
If possible, please enable daemon debug logging https://docs.docker.com/engine/admin/#/configuring-docker and see if you can find anything.

**Comment by korabelnikov** [comment]
@kunalkushwaha yes. but just restart of docker deamon solves my problem. 
It's not the best choice because there were other working containers.
As I remember, this problem raises first time when my disk space became very low.

**Comment by lyndon160** [comment]
I just came across the same issue. Mine was caused when I stopped a container to copy the image and start another copy of the container with some different flags. The issue was resolved by restarting docker.

**Comment by dustingetz** [comment]
`service docker restart` worked for me

**Comment by erikbgithub** [comment]
In the year 2017 `systemctl restart docker` should be used instead of `service docker restart`.

**Comment by sigmundv** [comment]
@erikbgithub Depends on which Linux distro you're using. Say you're on RHEL or CentOS 6.9 (which are still supported), then it's `service docker restart`.

**Comment by thaJeztah** [comment]
RHEL or CentOS 6.x as a distro may still be supported by Red Hat, but there's no support for running docker on them anymore. The last version of docker released for them is docker 1.7.1, which is no longer maintained, and has known vulnerabilities, thus highly discouraged
