### ISSUE TITLE
Can't build dockerfile.Windows on Hyper-V containers

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#28263]
Yeah, I need to figure out what's going on. Can only use in Windows server containers. See https://github.com/docker/docker/pull/28261.

**Comment by andschwa** [comment]
To clarify, the Dockerfile can be built without problem. The Docker build cannot be run inside the container (because none of the POSIX tools from Git work) when using process isolation.

**Comment by jhowardmsft** [comment]
This has been fixed for a while. Closing.
