### ISSUE TITLE
Hom can i access the container config file name config.v2.json on Mac OS through Docker for Mac?

### ISSUE THREAD

**Issue by sencho** [docker/docker#28283]
**Hom can i access the container config file name config.v2.json on Mac OS through Docker for Mac?**

**Steps to reproduce the issue:**
1.cd  /var/lib/docker/

**Describe the results you received:**
cd: no such file or directory: /var/lib/docker/

**Describe the results you expected:**
I want to aaccess the file at /var/lib/docker/containers/[container id]/config.v2.json like on Ubunto,but it is not fine on Mac OS through Docker for Mac

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 5
 Paused: 0
 Stopped: 10
Images: 62
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 285
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: CNLU:SY3R:X2HJ:4PHO:NI3J:XUZL:VAKK:HUJQ:IZU2:VHTD:6277:3X4E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 62
 System Time: 2016-11-11T04:51:02.36982445Z
 EventsListeners: 2
No Proxy: localhost、172.*.*.*、192.*.*.*、*.csair.com、*.csair.com、*.csair.cn、10.*.*.*、*.cs-air.com
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Why?
This file is considered private to the docker engine and should not be modified.

In docker4mac and docker4windows, docker is running in a tiny VM, with it's own filesystem, and thus it's own `/var/lib/docker`.
You can `docker run -v /var/lib/docker:/var/lib/docker ...` and then access the directory from inside a container, but not that mounting the docker directory like this can cause issues with mounts not being able to be cleaned up properly, and subsequently containers/images.
