### ISSUE TITLE
Docker for Windows does not support live-restore option

### ISSUE THREAD

**Issue by georgyturevich** [docker/docker#28295]
**Description**

When I read documentation about live-restore option I supposed that it is supported by Docker for Windows. There is no one mention that it is not supported: https://docs.docker.com/engine/admin/live-restore/

Furthermore, this documentation https://docs.docker.com/engine/reference/commandline/dockerd/ lists this option in "Windows configuration file" section. But I was not able to configure it in both ways (as an argument of dockerd and variable of daemon.json)

**Steps to reproduce the issue:**
1. When I try to run dockerd with --live-restore option I got a error
```
PS C:\Users\Administrator> dockerd --live-restore --register-service
Status: unknown flag: --live-restore
See 'dockerd --help'., Code: 125
```
2. When I added ``` "live-restore": true ``` to the daemon.json and started dockerd I got another error
```
PS C:\Users\Administrator> dockerd
unable to configure the Docker daemon with file C:\ProgramData\docker\config\daemon.json: the following directives don't match any configuration option: live-restore
```

**Expected behaviour:**
I expect that dockerd should run successfully with this option. Or at least have mention in the documentation that it is not supported

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: EC2AMAZ-P7L1INT
ID: 6JSQ:WIFX:QJ25:TM5T:JBOG:CR7M:NSOW:X2AJ:QJXR:PRID:CLE2:6Q67
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is a EC2 instance which was launched from "Windows Server 2016 with containers image"

**Comment by mlaventure** [comment]
This feature is indeed not supported on Windows, thanks for pointing out that the documentation needs to be updated.

/cc @jhowardmsft @thaJeztah @crosbymichael

**Comment by georgyturevich** [comment]
@mlaventure Hi Kenfe-Mickaël,

Thanks for the answer! Do you have a plan to add a support of this option for Windows?

**Comment by bbayani** [comment]
#dibs
