### ISSUE TITLE
Took long time for Docker Swarm service turn desired state from Ready to Running

### ISSUE THREAD

**Issue by zdtsw** [docker/docker#28291]
**Description**
After I run "docker service update" it took around 60 seconds for each task from "Ready" to "Running" in desired states. It was around 25-35 seconds with the same application version and on the same docker swarm cluster. What could cause this issue? (I believe it is rather the servers than the docker itself) but how can I trouble shooting this? And I could not see any documentation described what "Ready" means for desired states

**Describe the results you received:**
>docker service ps service
ID                         NAME             IMAGE                                                       NODE                      DESIRED STATE  CURRENT STATE          ERROR
663dyntbzxdwixoauzqwpxmr7  service.1  myNexus:18444/app/service:0.0.150  server1  Ready          Ready 59 seconds ago   
alv8egzz7l3otbrukyp0w12up  service.2  myNexus:18444/app/service:0.0.140  server2  Running        Running 3 minutes ago  

>docker service ps service
ID                         NAME             IMAGE                                                       NODE                      DESIRED STATE  CURRENT STATE          ERROR
663dyntbzxdwixoauzqwpxmr7  service.1  myNexus:18444/app/service:0.0.150  server1  Running        Running 1 seconds ago  
alv8egzz7l3otbrukyp0w12up  service.2  myNexus:18444/app/service:0.0.140  server2  Running        Running 3 minutes ago  

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
We used the same docker swarm master and 2 docker swarm workers. There are not much load on all these three servers and all with the same docker version and all servers are in the same sub network.

**Output of `docker version`:**
Docker version 1.12.3, build 6b644ec

**Output of `docker info`:**
Containers: 2
 Running: 1
 Paused: 0
 Stopped: 1
Images: 29
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host null bridge
Swarm: active
 NodeID: 72gvia35ix61itfohl7k3u6rg
 Is Manager: true
 ClusterID: 7cwfx7po774vp8pfj40algdlb
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 1
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.14.57.32
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: master1
ID: NTMK:JGIK:ZDHP:37KK:LYTO:BJJV:6LIA:LVAC:S4GX:SGWX:LWTS:Z2MP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 44
 Goroutines: 141
 System Time: 2016-11-11T09:33:07.023284896+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by zdtsw** [comment]
Is there any setting for swarm to define how long time it should use for update a task?
looks all the tasks (even a different service) take the same amount of 60 seconds now.

**Comment by zdtsw** [comment]
after set back "docker swarm update --task-history-limit 5", problem solved!
so there is something wrong with the --task-history-limit which pauses the task for 1 minute and then start  pulling image + run container..........

**Comment by aaronlehmann** [comment]
It sounds like it's taking a long time for the old task to shut down. By default, a task is given up to a minute to shut down before proceeding with the update. You might want to try setting the `--stop-grace-period` option to something shorter.

I'm not sure why passing the `--task-history-limit` option would make a difference. This may be a coincidence - or something very strange is going on.

**Comment by zdtsw** [comment]
Thanks! 
would have a try with --stop-grace-period and set --task-history-limit=1 again to see if still an issue there.

**Comment by zdtsw** [comment]
Hi again,
It did not work with --stop-grace-peroid...... no matter which value I set for --stop-grace-period, once --task-history-limit either =1 or =0, it still takes exactly 1 minute for each task in the service to change from "Ready" to "Running". and once set --task-history-limit back to 5, it just runs within 2 seconds to have the task done.

**Comment by cpuguy83** [comment]
Something to do with healtcheck settings? Do you have a healthcheck defined?
How is it configured?

**Comment by rogerwelin** [comment]
@cpuguy83 no healthcheck defined in the Docker file

**Comment by ShogunPanda** [comment]
Same issue here.

**Comment by thaJeztah** [comment]
We need more info if you're running into this, otherwise it will be just "wild guessing";

- daemon log-files (with debug enabled), and possibly log files of the container may show what's happening at each point, and where the delay is.
- exact steps to reproduce (which image is used, how is the service configured, etc.)

Keep in mind that `docker service update` stops the running containers (tasks) and starts new ones to replace them, which could take time, depending on what's running in the container (e.g. writing data to disk if it's a statefull service, initializing on startup). Docker 1.12 also performs a `docker pull` on each update to check if a more recent version of the image is available. If the task ends on a different node, that image may not be in the local image cache yet

**Comment by zarnovican** [comment]
same issue here (on Docker 1.13.1)

This problem exhibits for `--task-history-limit` zero or one. Any service, any image.. Unrelated to `docker pull` or time to shutdown container.

> * exact steps to reproduce (which image is used, how is the service configured, etc.)

## Steps to reproduce

Set swarm task history to 1
```
$ docker service ls
ID  NAME  MODE  REPLICAS  IMAGE
$ docker swarm update --task-history-limit 1
Swarm updated.
```
Create dummy service
```
$ docker service create --name top busybox top
4owezg5kku7bh18vnlcjzoo91
$ docker service scale top=3
top scaled to 3
$ docker service ps top
ID            NAME   IMAGE           NODE  DESIRED STATE  CURRENT STATE           ERROR  PORTS
pavf5i2gpnc0  top.1  busybox:latest  vm5   Running        Running 14 seconds ago         
a4mbs9s237kg  top.2  busybox:latest  vm6   Running        Running 6 seconds ago          
wg8yji6zp5dt  top.3  busybox:latest  vm6   Running        Running 6 seconds ago          
```
Trigger service update
```
$ docker service update top --force
top
```

## Expected result

Update to be completed within seconds. Just as it is the case for task-history >1.

## Actual result

It takes three minutes to complete the update. One minute for each task, during which, the task is in "Ready" state
```
$ docker service ps top
ID            NAME   IMAGE           NODE  DESIRED STATE  CURRENT STATE           ERROR  PORTS
pavf5i2gpnc0  top.1  busybox:latest  vm5   Running        Running 44 seconds ago         
nxvl7t35mj8a  top.2  busybox:latest  vm6   Ready          Ready 19 seconds ago           
wg8yji6zp5dt  top.3  busybox:latest  vm6   Running        Running 37 seconds ago         
```

**Comment by aaronlehmann** [comment]
Strange, I can't reproduce this.

```
$ docker version
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      linux/amd64
 Experimental: true
$ docker swarm update --task-history-limit 1
Swarm updated.
$ docker service create --name top busybox top
x6akq7s1w54r58mp36q8p543s
$ docker service scale top=3
top scaled to 3
$ docker service ps top
ID            NAME   IMAGE           NODE  DESIRED STATE  CURRENT STATE           ERROR  PORTS
68qqap8156zf  top.1  busybox:latest  moby  Running        Running 11 seconds ago
weehc721jaqk  top.2  busybox:latest  moby  Running        Running 1 second ago
ncp2g2ktqb7c  top.3  busybox:latest  moby  Running        Running 1 second ago
```

**Comment by zarnovican** [comment]
@aaronlehmann I don't see the `service update` in your output.

**Comment by aaronlehmann** [comment]
My mistake. I can see the problem now and I'll work on a fix.

**Comment by aaronlehmann** [comment]
I've opened https://github.com/docker/swarmkit/pull/1948 to fix this. Thanks for the simple repro steps.
