### ISSUE TITLE
Container daemon crashes while trying to process a DNS request

### ISSUE THREAD

**Issue by andrewslotin** [docker/docker#28308]
**Description**

The contained daemon has crashed while one of the containers was handling an HTTP request.
Here is the [panic log](https://github.com/docker/docker/files/586170/docker.log.gz).

**Steps to reproduce the issue:**

I was not able to reproduce the issue. 

**Describe the results you received:**

Container daemon panicked.

**Describe the results you expected:**

I'd expect the container daemon to not to crash.

**Additional information you deem important (e.g. issue happens only occasionally):**

This was the first time it happened, never experienced this issue before.

**Output of `docker version`:**

```
Client:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   4dc5990
 Built:        Wed Apr 13 18:34:23 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 33
Server Version: 1.11.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 490 MiB
Name: vpn.suddendef.ru
ID: ZZP5:55N4:O53C:AKCO:4GZZ:3AOY:F6TB:LZ2D:LML2:5HMR:VDMX:OSQX
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Standard DigitalOcean installation of Docker.

**Comment by cpuguy83** [comment]
You are on a really old version of Docker.
I believe 1.11.2 is the most current in the 1.11 branch if you could try that, although realistically we don't backport patches to older releases right now... so giving 1.12.3 a try may be better.

This is likely already fixed, but pinging @sanimej anyway.

**Comment by sanimej** [comment]
This was reported in #22081 and has been fixed in 1.11.1. Consider upgrading to 1.11.2 as suggested by @cpuguy83

**Comment by andrewslotin** [comment]
Upgraded, thanks everyone!

**Comment by cpuguy83** [comment]
Thanks!
