### ISSUE TITLE
Cannot make dockerd for Windows 1.12.3-beta30 listen to tcp://0.0.0.0:2375

### ISSUE THREAD

**Issue by lusitania** [docker/docker#28320]
Following the instructions from [Docker](https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file) and [Microsoft](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/docker/configure_docker_daemon#configure-docker-with-configuration-file) I can't start up docker with a changed hosts section of the config.

**Steps to reproduce the issue:**
1. change Settings->Docker Daemon to
```
{
  "registry-mirrors": [],
  "insecure-registries": [],
  "hosts": [
    "tcp://10.0.75.0:2375",
    "tcp://"
  ]
}
```
2. try to start
3. change port 2376, repeat
4. change IP to 0.0.0.0, try with un-/enc ports
5. remove remote option and just keep the default for Windows (tcp://)

**Describe the results you received:**
```
Error response from daemon: Bad response from Docker engine

   at Docker.Backend.DockerDaemonChecker.Check()
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)
```

**Describe the results you expected:**
Startup of daemon

**Additional information you deem important (e.g. issue happens only occasionally):**
5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-11-11_19-55-28 (example above)
5B7AC43B-CA65-42E7-98A8-B482CA7FC66D/2016-11-11_20-03-41 (defaults)

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 36
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 735.9 MiB
Name: moby
ID: H7LJ:K7SI:AFW5:3OYN:TCI2:LV5Y:USEZ:NIV4:TUGT:LQJA:U2IV:J2KA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2016-11-11T19:06:03.7319736Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Comment by cpuguy83** [comment]
ping @friism

**Comment by zer0beat** [comment]
I have tried to follow the same Microsoft steps and I got the same error. Reported error with id: 28F9AE61-5E87-4E83-9D1D-FE3DEEA38C58/2016-11-13_17-00-05

**Comment by thaJeztah** [comment]
Looks like this is docker for Windows, not native Windows containers, so should probably be reported at https://github.com/docker/for-win/issues

/cc @justincormack @rneugeba

**Comment by rneugeba** [comment]
@lusitania @zer0beat could you open an issue at https://github.com/docker/for-win/issues so we can track it there?

**Comment by zer0beat** [comment]
@rneugeba done

**Comment by thaJeztah** [comment]
Closing, as this is now tracked through https://github.com/docker/for-win/issues/225, thanks!
