### ISSUE TITLE
adjust release.sh for solaris

### ISSUE THREAD

**Issue by andrewhsu** [docker/docker#28326]
**Description**

The [release.sh](https://github.com/docker/docker/blob/e6866492c4492db3bb9546afa2fbaed20f4c1883/hack/release.sh#L217) script used during docker's release process is failing because it cannot handle solaris builds.

**Steps to reproduce the issue:**
```
$ docker run ... docker-dev:1-13-x hack/release.sh
...
error: can't convert solaris to an appropriate value for 'uname -s'
```

**Describe the results you received:**

Most of the binaries uploaded to s3 except for solaris and windows.

**Describe the results you expected:**

Stuff to work.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

something recent

**Output of `docker info`:**

stuff

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
@andrewhsu given that there is no released version of Solaris yet that has the functionality to support docker, should we change the script to _skip_ Solaris?

**Comment by amitkris** [comment]
@andrewhsu @thaJeztah I would like to add that the cross build for Solaris does not work due to CGO calls in Solaris platform code. Until that is enabled I think it would be best get the script to skip Solaris too.

**Comment by tiborvass** [comment]
Putting back to 1.13 so that we at least skip solaris for release.
