### ISSUE TITLE
MongoDB cannot distinguish overlay-networked containers under Docker 1.13-rc1.

### ISSUE THREAD

**Issue by phyllisstein** [docker/docker#28358]
**Description**
Hey Dockers,
I recently attempted to upgrade to Docker 1.13-rc1 from Docker 1.12, and ran into some trouble when redeploying my services. It seems that some change in Docker's networking has made it impossible for MongoDB to distinguish between container hosts running on the same overlay network. When adding services to a replica set, it throws the following error:

```json
{
	"ok" : 0,
	"errmsg" : "The hosts mongo1:27017 and mongo2:27017 all map to this node in new configuration version 3 for replica set ignotae",
	"code" : 103
}
```

I've [reached out to](https://jira.mongodb.org/browse/SERVER-27012) the MongoDB folks to see if they can provide some color on which checks are failing with their server, but thought I'd ask here whether any of the changes between 1.12 and 1.13 jumped out as potentially connected to the glitch.

Thanks so much for any guidance you can provide! I'm eager to make the leap to 1.13 and would love to get this cleared up.

**Steps to reproduce the issue:**
1. Create a new Docker swarm and overlay network.

	```shell
	$ docker swarm init
	$ docker network create --driver=overlay --subnet=10.0.72.0/24 ignotae-private
	```

2. Deploy three separate MongoDB services on the same overlay network. Prepare them for attachment to a replica set.

	```shell
	$ docker service create --name=mongo1 --mode=replicated --replicas=1 --publish=27017 --network=ignotae-private mongo:rc mongod --replSet=ignotae --storageEngine=wiredTiger
	$ docker service create --name=mongo2 --mode=replicated --replicas=1 --publish=27017 --network=ignotae-private mongo:rc mongod --replSet=ignotae --storageEngine=wiredTiger
	$ docker service create --name=mongo3 --mode=replicated --replicas=1 --publish=27017 --network=ignotae-private mongo:rc mongod --replSet=ignotae --storageEngine=wiredTiger
	```

3. `docker exec` into a container and create the replica set.

	```
	$ docker exec -it fd610ba1a8b7 mongo
	MongoDB shell version v3.4.0-rc2
	connecting to: mongodb://127.0.0.1:27017
	MongoDB server version: 3.4.0-rc2
	> rs.initiate()
	```

4. Attempt to add additional containers' hosts to the replica set.

	```
	ignotae:PRIMARY> rs.add('mongo2:27017')
	{
		"ok" : 0,
		"errmsg" : "The hosts mongo1:27017 and mongo2:27017 all map to this node in new configuration version 3 for replica set ignotae",
		"code" : 103,
		"codeName" : "NewReplicaSetConfigurationIncompatible"
	}
	```

5. Verify network connectivity between the containers, just for kicks.

	```
	$ docker exec -it fd610ba1a8b7 /bin/bash
	root@fd610ba1a8b7:/# ping mongo2
	PING mongo2 (10.0.72.4): 56 data bytes
	64 bytes from 10.0.72.4: icmp_seq=0 ttl=64 time=0.035 ms
	^C--- mongo2 ping statistics ---
	1 packets transmitted, 1 packets received, 0% packet loss
	round-trip min/avg/max/stddev = 0.035/0.035/0.035/0.000 ms
	root@fd610ba1a8b7:/# ping mongo3
	PING mongo3 (10.0.72.6): 56 data bytes
	64 bytes from 10.0.72.6: icmp_seq=0 ttl=64 time=0.035 ms
	64 bytes from 10.0.72.6: icmp_seq=1 ttl=64 time=0.070 ms
	^C--- mongo3 ping statistics ---
	2 packets transmitted, 2 packets received, 0% packet loss
	round-trip min/avg/max/stddev = 0.035/0.053/0.070/0.000 ms
	root@fd610ba1a8b7:/# mongo --host=mongo2
	MongoDB shell version v3.4.0-rc2
	connecting to: mongodb://mongo2:27017/
	MongoDB server version: 3.4.0-rc2
	```

**Describe the results you received:**
MongoDB's heuristics for verifying that multiple hosts are not identical failed and it refused to add additional swarm services to its replica set.

**Describe the results you expected:**
The containers' network settings should be sufficiently distinguishable that MongoDB does not confuse them.

**Additional information you deem important (e.g. issue happens only occasionally):**
The steps described above are successful under Docker 1.12, but fail under Docker 1.13-rc1.

**Output of `docker version`:**
```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:56:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:56:45 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**
```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: s2bmbr92rlpv3asa62uqcafjd
 Is Manager: true
 ClusterID: hqncwv56hjfvsgrp6iq3dbqkg
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.27.0.62
 Manager Addresses:
  10.27.0.62:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-27-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.951 GiB
Name: ip-10-27-0-62
ID: SC3N:IBM4:27TA:QPUL:F4EO:5B33:FFZL:63PM:D2LE:FBK2:ZRDN:HG5N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 206
 Goroutines: 408
 System Time: 2016-11-13T13:20:51.631429526Z
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Ubuntu 16.10 on an EC2 instance.

**Comment by thaJeztah** [comment]
ping @mrjana PTAL

**Comment by sanimej** [comment]
@phyllisstein A change we did in 1.13 is to add the vip of all services as an alias IP to the overlay network interface. This was to allow ping to the VIP of other services in the same network. Can you check with the MongoDB folks if adding a container to the replica set has any assumptions based on its IP address ?

**Comment by phyllisstein** [comment]
I just posted all this info to the `mongodb-user` group on Google, since they closed my original ticket without providing much guidance; I'll drop a link here when it clears moderation. Since the servers are three separate Docker services, it at least _seems_ as though making their VIPs available shouldn't muck anything up. My (limited) understanding is that MongoDB uses the servers' hostnames and ports to check uniqueness; hopefully someone on the mailing list will be able to correct or confirm that.

**Comment by phyllisstein** [comment]
I noted while testing that I was able to create the replica set if I used the containers' hashes as hostnames, rather than their service names:

```
ignotae:PRIMARY> rs.add('9f5b8b2f3319')
{ "ok" : 1 }
ignotae:PRIMARY> rs.add('abd4f23cd0f3')
{ "ok" : 1 }
ignotae:PRIMARY> rs.config()
{
	"_id" : "ignotae",
	"version" : 3,
	"protocolVersion" : NumberLong(1),
	"members" : [
		{
			"_id" : 0,
			"host" : "95c4914099aa:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 1,
			"host" : "9f5b8b2f3319:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		},
		{
			"_id" : 2,
			"host" : "abd4f23cd0f3:27017",
			"arbiterOnly" : false,
			"buildIndexes" : true,
			"hidden" : false,
			"priority" : 1,
			"tags" : {

			},
			"slaveDelay" : NumberLong(0),
			"votes" : 1
		}
	],
	"settings" : {
		"chainingAllowed" : true,
		"heartbeatIntervalMillis" : 2000,
		"heartbeatTimeoutSecs" : 10,
		"electionTimeoutMillis" : 10000,
		"catchUpTimeoutMillis" : 2000,
		"getLastErrorModes" : {

		},
		"getLastErrorDefaults" : {
			"w" : 1,
			"wtimeout" : 0
		},
		"replicaSetId" : ObjectId("582a5334285653766d6a0a7d")
	}
}
```

So it would seem that the issue is connected to resolving and differentiating the aliases `mongo1`, `mongo2`, and `mongo3`. I'm not sure if this gets us any closer to the core of the problem.

**Comment by phyllisstein** [comment]
I did some digging in the Mongo source, and verbosified the logging in my containers, and came up with some more clues:

```
2016-11-15T22:34:35.493+0000 D COMMAND  [conn1] command: replSetReconfig
2016-11-15T22:34:35.493+0000 I REPL     [conn1] replSetReconfig admin command received from client
2016-11-15T22:34:35.493+0000 D NETWORK  [conn1] getBoundAddrs(): [ 127.0.0.1] [ 10.0.72.7] [ 10.0.72.2] [ 10.0.72.4] [ 10.0.72.6] [ 172.18.0.5] [ 10.255.0.9] [ 10.255.0.4] [ 10.255.0.6] [ 10.255.0.8]
2016-11-15T22:34:35.493+0000 D NETWORK  [conn1] getAddrsForHost("77001cacd987:27017"): [ 10.0.72.7]
2016-11-15T22:34:35.494+0000 D NETWORK  [conn1] getBoundAddrs(): [ 127.0.0.1] [ 10.0.72.7] [ 10.0.72.2] [ 10.0.72.4] [ 10.0.72.6] [ 172.18.0.5] [ 10.255.0.9] [ 10.255.0.4] [ 10.255.0.6] [ 10.255.0.8]
2016-11-15T22:34:35.495+0000 D NETWORK  [conn1] getAddrsForHost("mongo2:27017"): [ 10.0.72.4]
```

It looks like MongoDB's `getBoundAddrs` method (defined [here](https://github.com/mongodb/mongo/blob/6471618952c8727bc5b06039ed2cf861e1a36436/src/mongo/db/repl/isself.cpp#L227)) somehow manages to find every VIP for every service in the network. `10.0.72.7` is the current container's `eth0` address, but `10.0.72.2` is the VIP for `mongo1`, `10.0.72.4` for `mongo2`, and `10.0.72.6` for `mongo3`. It works when I enter a container's internal hostname specifically because MongoDB apparently resolves the container's `eth0` IP rather than its VIP:

```
2016-11-15T22:44:13.771+0000 D COMMAND  [conn2] command: replSetReconfig
2016-11-15T22:44:13.771+0000 I REPL     [conn2] replSetReconfig admin command received from client
2016-11-15T22:44:13.771+0000 D NETWORK  [conn2] getBoundAddrs(): [ 127.0.0.1] [ 10.0.72.7] [ 10.0.72.2] [ 10.0.72.4] [ 10.0.72.6] [ 172.18.0.5] [ 10.255.0.9] [ 10.255.0.4] [ 10.255.0.6] [ 10.255.0.8]
2016-11-15T22:44:13.771+0000 D NETWORK  [conn2] getAddrsForHost("77001cacd987:27017"): [ 10.0.72.7]
2016-11-15T22:44:13.771+0000 D NETWORK  [conn2] getBoundAddrs(): [ 127.0.0.1] [ 10.0.72.7] [ 10.0.72.2] [ 10.0.72.4] [ 10.0.72.6] [ 172.18.0.5] [ 10.255.0.9] [ 10.255.0.4] [ 10.255.0.6] [ 10.255.0.8]
2016-11-15T22:44:13.772+0000 D NETWORK  [conn2] getAddrsForHost("99420993a796:27017"): [ 10.0.72.5]
```

...and so it doesn't see any conflict with the bound addresses.

I'm afraid I'm pretty firmly out of my depth here w/r/t Docker's internals and the Linux networking stack, but hopefully this'll clue in someone more knowledgeable than I.
