### ISSUE TITLE
`docker daemon` is not working on '1.13.0-rc1'

### ISSUE THREAD

**Issue by twang2218** [docker/docker#28368]
**Description**

Failed to start the docker daemon by `docker daemon` command.

**Steps to reproduce the issue:**
1. Create a 1.13-rc1 docker host on Digital Ocean via `docker-machine` command:

```bash
$ docker-machine create -d digitalocean \
    --engine-install-url "https://test.docker.com/" \
    --engine-storage-driver overlay2 \
    d1
```

2. ssh into the machine, and you will find you cannot run `docker` command

```bash
$ docker-machine ssh d1
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-47-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.


root@d1:~# docker info


^C
root@d1:~# docker --version
^C
root@d1:~#
```

Checking the running process

```bash
root@d1:~# ps -ef | grep docker
root       985     1  0 01:51 ?        00:00:00 /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=digitalocean
```

You will find the `/usr/bin/docker daemon` is used (which is came from `docker-machine` template).

Then, check the systemd status

```bash
root@d1:~# systemctl status docker
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-11-14 01:51:14 UTC; 2min 49s ago
 Main PID: 985 (docker)
    Tasks: 4
   Memory: 14.1M
      CPU: 25ms
   CGroup: /system.slice/docker.service
           └─985 /usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pe

Nov 14 01:51:14 d1 systemd[1]: Started docker.service.
Nov 14 01:51:14 d1 docker[985]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
```

There is no further information, which should have more docker daemon boot up info. It seems the docker daemon stuck there.

Edit the `/etc/systemd/system/docker.service`, replace the `docker daemon` with `dockerd`, then reboot the docker service

```bash
root@d1:~# systemctl daemon-reload
root@d1:~# systemctl restart docker
root@d1:~# systemctl status docker
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-11-14 01:58:23 UTC; 3s ago
 Main PID: 1731 (dockerd)
    Tasks: 16
   Memory: 51.4M
      CPU: 363ms
   CGroup: /system.slice/docker.service
           ├─1731 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --t
           └─1737 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd -

Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.094362027Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.095659953Z" level=info msg="Loading containers: start."
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.135899718Z" level=info msg="Firewalld running: false"
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.313196823Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.356318661Z" level=info msg="Loading containers: done."
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.376632354Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.377394788Z" level=info msg="Daemon has completed initialization"
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.377644240Z" level=info msg="Docker daemon" commit=75fd88b graphdriver=overlay2 version=1.13.0-rc1
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.389155910Z" level=info msg="API listen on /var/run/docker.sock"
Nov 14 01:58:25 d1 dockerd[1731]: time="2016-11-14T01:58:25.389750526Z" level=info msg="API listen on [::]:2376"
```

This time, we can see the real boot log. And `docker` command can be used as well.

```bash
root@d1:~# docker --version
Docker version 1.13.0-rc1, build 75fd88b
```

I understand `docker daemon` is deprecated, but should work until 1.16.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: d1
ID: M7VK:YNAL:VPTV:T5CX:CAS3:W7WX:WT6E:3PVE:GOBD:TQKT:MJLT:5K7C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by vdemeester** [comment]
@twang2218 I cannot reproduce :sweat: It works fine with `docker daemon` (it's deprecated — but still there until 1.16). `/usr/bin/docker daemon` actuallly runs `dockerd` (if you do a `ps afx | grep docker` you should see it).

I think docker daemon didn't start for another reason but not sure why… Do you still have access to your machine and the systemd logs ?

**Comment by twang2218** [comment]
@vdemeester As I said in the debug section, `ps -ef` did show the `/usr/bin/docker daemon` process, however, the log of daemon doesn't seem right, it's not full booted, and the `docker` command was not working, either.

Yes, I still have the access of the machine, and the problem is repeatable. If I change it to `dockerd`, everything will be fine, and if I change it to `docker daemon`, then the problem appears. So, if you want anything, just let me know.

Here is the `systemctl status`

```bash
root@d1:~# systemctl status docker
● docker.service
   Loaded: loaded (/etc/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2016-11-14 16:08:53 UTC; 6min ago
 Main PID: 10431 (docker)
    Tasks: 3
   Memory: 189.9M
      CPU: 15ms
   CGroup: /system.slice/docker.service
           └─10431 /usr/bin/docker daemon -D -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --storage-driver overlay2 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pe

Nov 14 16:08:53 d1 systemd[1]: Started docker.service.
Nov 14 16:08:53 d1 docker[10431]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
```

Here is `journalctl` output:

```bash
root@d1:~# journalctl -u docker
-- Logs begin at Mon 2016-11-14 01:44:24 UTC, end at Mon 2016-11-14 16:15:59 UTC. --
...
-- Reboot --
Nov 14 16:08:53 d1 systemd[1]: Started docker.service.
Nov 14 16:08:53 d1 docker[10431]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
```

This is the full log when using `docker daemon`, nothing else, even I enabled the debug option `-D`.

The Docker Machine version is `0.8.2`, which is the part of Docker for Mac, `1.12.3 (13776)`:

```bash
$ docker-machine -v
docker-machine version 0.8.2, build e18a919
```

As you saw in the `docker info` section, the OS I choose on Digital Ocean is `Ubuntu 16.04.1 LTS`, and fully updated and 'dist-upgraded', the kernel version is `4.4.0-47-generic`.

Here is the settings I used for docker-machine on creating host on Digital Ocean:

```bash
#!/bin/bash
export DOCKER_API_VERSION=1.24
export DIGITALOCEAN_IMAGE=ubuntu-16-04-x64
export DIGITALOCEAN_REGION=sfo2
export MACHINE_DRIVER=digitalocean
```

After `source` the variables, I just simply create the host by

```bash
docker-machine create --engine-install-url "https://test.docker.com/" --engine-storage-driver overlay2 d1
```

**Comment by thaJeztah** [comment]
I can confirm that using `docker daemon` in a systemd unit file results in the service not starting. Possibly systemd thinks the command failed because the warning was printed. Manually running the command works

**Comment by thaJeztah** [comment]
Just checked with @vdemeester and he confirmed it worked for him on DigitalOcean (Ubuntu), so we're a bit confused now :smile:

**Comment by twang2218** [comment]
I double checked it on Vultr.com, I created a Ubuntu 16.04 host on Vultr via `docker-machine` with Vultr driver. It's repeatable, and not Digital Ocean only problem.

One thing I noticed this time, if I just created the host via `docker-machine` and SSH into the host, the docker daemon is booted up, everything is right, however, after I `ps -ef | grep docker`, I found it's `dockerd` rather than `docker daemon`, I double checked all the `docker.service`, they are all `docker daemon`. So, somehow, `docker-machine` use the `dockerd` for the first time.

So, I just reboot the system, to make sure it's using what stated in the `docker.service`, and this time, bug appears.

**Comment by twang2218** [comment]
I tried without using `docker-machine`, on both Digital Ocean and Vultr, same result. 

I created a clean Ubuntu 16.04.1 host, and after update and reboot, then I run the following command to install the docker

```bash
curl -fsSL https://test.docker.com/ | sh
```

After the installation, the docker is running, I can run `docker info`, and `ps -ef | grep docker` show me the `dockerd` process.

Then, I edit `/etc/systemd/system/multi-user.target.wants/docker.service`, change the `dockerd` to `docker daemon`.

Reload and restart the docker service:

```bash
systemctl daemon-reload
systemctl restart docker
```

The `systemctl restart docker` never returned, I waited for several minutes.

After Ctrl-C, or just logged in from another console, the bug appears.

```bash
# systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (start) since Mon 2016-11-14 17:27:05 UTC; 1min 48s ago
     Docs: https://docs.docker.com
 Main PID: 11507 (docker)
    Tasks: 3
   Memory: 6.2M
      CPU: 20ms
   CGroup: /system.slice/docker.service
           └─11507 /usr/bin/docker daemon -H fd://

Nov 14 17:27:05 d2 systemd[1]: Starting Docker Application Container Engine...
Nov 14 17:27:05 d2 docker[11507]: Command "daemon" is deprecated, and will be removed in Docker 1.
```

And all `docker` commands, even `docker --version`, are not responding.

**Comment by nathanleclaire** [comment]
I ran into this issue as well.  I'm going to fix machine to use `dockerd` for starters.

**Comment by cpuguy83** [comment]
@nathanleclaire Can you check out #28501?

**Comment by nathanleclaire** [comment]
in my admittedly limited and probably flawed testing, seems to work 👍

 a unit file with `/usr/bin/docker daemon` seems to result fine in a running `dockerd` instance without the hang issue ! thanks all.
