### ISSUE TITLE
Upgrade from docker-engine 1.11.2 to docker-engine 1.12.3: Containers are not starting

### ISSUE THREAD

**Issue by rsmoorthy** [docker/docker#28363]
Was running docker-engine 1.11.2 and I upgraded by "apt-get install docker-engine" which upgraded it to 1.12.3. After upgrade, the existing containers refused to start with the message:

Error response from daemon: invalid header field value "oci runtime error: container with id exists: xxxx

I am able to create and run new containers, but I cannot run existing containers.

time="2016-11-13T13:02:51.154186453-05:00" level=error msg="Failed to start container 0c0d6b78357ba46c8d19929b7f86af56618...db85f\\n\""
time="2016-11-13T13:02:51.177876671-05:00" level=error msg="Failed to start container 12b1b5d36f5373567ed4d5b2b2a5d3282fe...35e53\\n\""
time="2016-11-13T13:02:51.177982779-05:00" level=info msg="Loading containers: done."
time="2016-11-13T13:02:51.178432714-05:00" level=info msg="Daemon has completed initialization"
time="2016-11-13T13:02:51.178474420-05:00" level=info msg="Docker daemon" commit=6b644ec graphdriver=aufs version=1.12.3
Started Docker Application Container Engine.
time="2016-11-13T13:02:51.204743562-05:00" level=info msg="API listen on /var/run/docker.sock"
time="2016-11-13T13:03:19.483864034-05:00" level=error msg="containerd: start container" error="oci runtime error: contai...1f1d1dcf313
time="2016-11-13T13:03:19.493263674-05:00" level=error msg="Create container failed with error: invalid header field valu...cf313\\n\""
time="2016-11-13T13:03:19.550028887-05:00" level=error msg="Handler for POST /v1.24/containers/mongo/start returned error...cf313\\n\

# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:53:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:53:11 2016
 OS/Arch:      linux/amd64

# docker info
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 73
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 107
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 15.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: *********
ID: NJUT:O5K3:JIIQ:ZECF:2JRP:GF46:SJVN:ESCK:KZ75:LB6R:DHWA:JXWO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

After restarting the service, status shows:

systemd[1]: Started Docker Application Container Engine.
dockerd[16519]: time="2016-11-13T13:04:25.179464746-05:00" level=info msg="API listen on /var/run/docker.sock"
dockerd[16519]: time="2016-11-13T13:04:33.818974899-05:00" level=error msg="containerd: start container" error="oci runtime error: container with id exists: a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f\n" id=a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f
dockerd[16519]: time="2016-11-13T13:04:33.828063423-05:00" level=error msg="Create container failed with error: invalid header field value \"oci runtime error: container with id exists: a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f\\n\""
dockerd[16519]: time="2016-11-13T13:04:33.898069562-05:00" level=error msg="Handler for POST /v1.24/containers/pdftools/start returned error: invalid header field value \"oci runtime error: container with id exists: a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f\\n\""
dockerd[16519]: time="2016-11-13T13:16:00.844896963-05:00" level=error msg="Handler for POST /v1.24/containers/pdftools/stop returned error: Container pdftools is already stopped"
dockerd[16519]: time="2016-11-13T13:16:05.61774549-05:00" level=error msg="containerd: start container" error="oci runtime error: container with id exists: a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f\n" id=a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f
dockerd[16519]: time="2016-11-13T13:16:05.625739217-05:00" level=error msg="Create container failed with error: invalid header field value \"oci runtime error: container with id exists: a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f\\n\""
dockerd[16519]: time="2016-11-13T13:16:05.689705052-05:00" level=error msg="Handler for POST /v1.24/containers/pdftools/start returned error: invalid header field value \"oci runtime error: container with id exists: a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f\\n\""
dockerd[16519]: time="2016-11-13T13:16:51-05:00" level=info msg="Firewalld running: false"

Whenever an existing container is started, /var/log/kern.log says:
[13316628.073427] aufs au_opts_verify:1597:docker[32174]: dirperm1 breaks the protection by the permission bits on the lower branch

Then downgraded the docker-engine back to 1.11.2, via apt-get install docker-engine=1.11.2~0-wily

After the installation of 1.11.2, the existing containers cannot start still and says the message:

docker start pdftools
Error response from daemon: rpc error: code = 6 desc = "mkdir /run/containerd/a5f4f4d75e2bea1c85e7eff1dbb43b241a6568d6f2d5517b589266e2b496552f: file exists"
Error: failed to start containers: pdftools

Now restart docker-engine service and the service does not start:

docker[20639]: time="2016-11-13T14:07:46.160420970-05:00" level=info msg="[graphdriver] using prior storage driver \"aufs\""
docker[20639]: time="2016-11-13T14:07:46.227486842-05:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
docker[20639]: time="2016-11-13T14:07:46.234824312-05:00" level=info msg="Firewalld running: false"
docker[20639]: time="2016-11-13T14:07:46.369831824-05:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
docker[20639]: time="2016-11-13T14:07:46.388700303-05:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: cannot create network b0453b6def557d691cbec99502fecaaec53ca9b97df4907740cd7e395c041803 (docker0): conflicts with network b441a9b25fb41fbb29b2c6c85ff36061d2a0a3775a11ff4584b8435b751f00c7 (docker0): networks have same bridge name"
systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
docker[20639]: time="2016-11-13T14:07:46-05:00" level=info msg="stopping containerd after receiving terminated"
systemd[1]: Failed to start Docker Application Container Engine.
systemd[1]: docker.service: Unit entered failed state.
systemd[1]: docker.service: Failed with result 'exit-code'.

**Steps to reproduce the issue:**
1. docker 1.11.2 running happily on Ubuntu 15.10
2. Upgrade to docker 1.12.3 via apt-get install
3. Existing containers do not start, new containers can be created and run
4. Downgrade to 1.11.2 back
5. Existing containers do not start
6. Restart the service
7. The service wont start

**Comment by rsmoorthy** [comment]
It has been really crazy.  Further I tried the following:

1. Reboot the server
2. docker (running 1.11.2) won't star, with the same message indicted above.
3. upgraded docker again to 1.12.3
4. All existing containers up and running!

I would be happy to know what exactly happened!!

**Comment by cpuguy83** [comment]
ping @mlaventure

**Comment by mlaventure** [comment]
It looks like during the upgrade the containers didn't get correctly destroyed, `docker` was probably forced killed before it had the time to properly shut them down.

A solution would have been to run `docker-runc delete <container-id>`

**Comment by rsmoorthy** [comment]
That sounds a possible explanation, though I am not in a position to confirm this. (I can at least confirm that docker daemon or containers were not forced killed).

Next time around, I would at least make sure that the containers are stopped before attempting an upgrade.

Will close this issue, with that.
