### ISSUE TITLE
docker pull is not working on windows containers

### ISSUE THREAD

**Issue by hamdiRuwiss** [docker/docker#28361]
**Description**

 docker pull microsoft/aspnetcore not working

**Steps to reproduce the issue:**
1.install docker for windows version 1.12.3 beta30 on windows 10 version 1607
2.switch to windows containers
3.run  docker pull microsoft/aspnetcore

**Describe the results you received:**

error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/
2f/2f9f5374bb7003abd768e3da072bd47775503cdde04dcda782f76d945aaf4baa/data?Expires=1479062647&Signature=BCBt-s0nFLUwcH50k2
PrWCaVVbHxL5tMpRCzaTCbedgjHe8409j4qZPBoBkY6vqkmvrZWzFW7bf1j0UUf1G1gBmI62IuXKDtkGU3QtEwTxFvxMPr2ETNcjBnLsoqoYumugsf4oJpUn
xiRnj6sMpk8ucDlmb5TAJzbmRekdHB~~Y_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 192.168.1.3:3953->54.239.174.51:443: wsare
cv: An existing connection was forcibly closed by the remote host.

**Describe the results you expected:**

container downloading

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay transparent
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 5.864 GiB
Name: HAMDI
ID: QEK4:NFJE:KHN4:QLVQ:PRNI:OVXZ:36SO:OWTW:6PZM:54AR:7NNP:L32J
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

some output form the service log

[20:47:12.197][WindowsDockerDaemon][Info   ] time="2016-11-13T20:47:12.197388300+03:00" level=error msg="Not continuing with pull after error: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/c5/c54a2cc56cbb2f04003c1cd4507e118af7c0d340fe7e2720f70976c4b75237dc/data?Expires=1479060429&Signature=Jiv5bU5qbkt5Q6VxEe9GzHYGvpwbwEyaKZKD-wBfjTsZbmkjEAs0VU3AF6X~JC40hgldEo9P6VdUWIPVu7wpnvQr8JysHtiCOLIbH1OUZX75Q~s4JG5KlUz1-I-D0D0Cvq0BY5tW6oAmwuaOq-Xm7JKSeIvVCA9flyqbagy0BkY_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: read tcp 192.168.1.3:2886->54.239.174.145:443: wsarecv: An existing connection was forcibly closed by the remote host." 
[20:47:12.197][ApiProxy       ][Info   ] proxy << POST /v1.24/images/create?fromImage=hello-world&tag=latest
[20:47:37.508][VpnKit         ][Debug  ] com.docker.slirp.exe: using default callback for non-IPv4 frame

**Comment by git-jiby-me** [comment]
@hamdiRuwiss do  you happen to be running the windows machine on virtualbox, and specifically 5.1.8 ?

**Comment by hamdiRuwiss** [comment]
No never used virtualbox and i desiable firewall and windows defender and i get the same error

**Comment by git-jiby-me** [comment]
@hamdiRuwiss ok, i just asked because i had this issues when using virtualbox 5.1.8, seems its not specific to virtualbox then.

**Comment by hamdiRuwiss** [comment]
Ok wait i think this is related to server side resources because when i tried now it is working yaee.Thank you

**Comment by git-jiby-me** [comment]
@hamdiRuwiss well for me, if i retry couple of times, it used to succeed and not succeed sometimes (completely randomly).

**Comment by hamdiRuwiss** [comment]
this is definitely network related because now i use in my workplace network and it is fast

**Comment by thaJeztah** [comment]
Looks like this is resolved, so I'll close this issue, but let me know if theres something to be resolved :)
