### ISSUE TITLE
 Docker-compose.yml Is not working for elasticserch

### ISSUE THREAD

**Issue by DhairyashilBhosale** [docker/docker#28376]
**Version Used:**

**Docker-compose** = 1.3.2

**Docker** = 1.12.3

**Os**: Ubuntu-14.04LTS

**- 1: docker-compose.yml**

`  

    elk: 

    image: elasticsearch:latest       

    ports:  

        - "9200:9200"
        - "9300:9300"

    volumes:
      - ./Elasticsearch/data:/etc/elasticsearch/data
      - ./Elasticsearch/config/elasticsearch.yml:/etc/elasticsearch/config/elasticsearch.yml

    command: bash -c "service elasticsearch start"

    tty : true
 `

**- 2: $ docker-compose up**

```
Creating elkdockerdir_elk_1...
Attaching to elkdockerdir_elk_1
elk_1 | [2016-11-14T06:28:18,458][INFO ][o.e.n.Node               ] [] initializing ...
elk_1 | [2016-11-14T06:28:18,573][INFO ][o.e.e.NodeEnvironment    ] [UERHECj] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sda6)]], net usable_space [409.6gb], net total_space [442.8gb], spins? [possibly], types [ext4]
elk_1 | [2016-11-14T06:28:18,573][INFO ][o.e.e.NodeEnvironment    ] [UERHECj] heap size [1.9gb], compressed ordinary object pointers [true]
elk_1 | [2016-11-14T06:28:18,576][INFO ][o.e.n.Node               ] [UERHECj] node name [UERHECj] derived from node ID; set [node.name] to override
elk_1 | [2016-11-14T06:28:18,579][INFO ][o.e.n.Node               ] [UERHECj] version[5.0.0], pid[1], build[253032b/2016-10-26T05:11:34.737Z], OS[Linux/3.13.0-32-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_111/25.111-b14]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [aggs-matrix-stats]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [ingest-common]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [lang-expression]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [lang-groovy]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [lang-mustache]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [lang-painless]
elk_1 | [2016-11-14T06:28:19,066][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [percolator]
elk_1 | [2016-11-14T06:28:19,067][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [reindex]
elk_1 | [2016-11-14T06:28:19,067][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [transport-netty3]
elk_1 | [2016-11-14T06:28:19,067][INFO ][o.e.p.PluginsService     ] [UERHECj] loaded module [transport-netty4]
elk_1 | [2016-11-14T06:28:19,067][INFO ][o.e.p.PluginsService     ] [UERHECj] no plugins loaded
elk_1 | [2016-11-14T06:28:19,149][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
elk_1 | [2016-11-14T06:28:20,424][INFO ][o.e.n.Node               ] [UERHECj] initialized
elk_1 | [2016-11-14T06:28:20,424][INFO ][o.e.n.Node               ] [UERHECj] starting ...
elk_1 | [2016-11-14T06:28:20,571][INFO ][o.e.t.TransportService   ] [UERHECj] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
elk_1 | [2016-11-14T06:28:20,576][INFO ][o.e.b.BootstrapCheck     ] [UERHECj] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elk_1 | ERROR: bootstrap checks failed
elk_1 | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
elk_1 | [2016-11-14T06:28:20,587][INFO ][o.e.n.Node               ] [UERHECj] stopping ...
elk_1 | [2016-11-14T06:28:20,608][INFO ][o.e.n.Node               ] [UERHECj] stopped
elk_1 | [2016-11-14T06:28:20,608][INFO ][o.e.n.Node               ] [UERHECj] closing ...
elk_1 | [2016-11-14T06:28:20,620][INFO ][o.e.n.Node               ] [UERHECj] closed
elkdockerdir_elk_1 exited with code 78
Gracefully stopping... (press Ctrl+C again to force)
```

**3: $ docker ps -a**

`CONTAINER ID        IMAGE                  COMMAND                  CREATED              STATUS                           PORTS               NAMES
a8799b8fe969        elasticsearch:latest   "/docker-entrypoint.s"   About a minute ago   Exited (78) About a minute ago                       elkdockerdir_elk_1
`

**Questions:**

_1: How to run docker-compose.yml with commands i.e. `command: bash -c "service elasticsearch start"` for given docker-compose and docker version ?_

**Comment by DhairyashilBhosale** [comment]
Hi Akihirosuda, Not getting the solution for this issues...

**Comment by AkihiroSuda** [comment]
The problem seems that `bash -c "service elasticsearch start"` exits immediately and does not keep running.
A workaround I can suggest it to use `tail -f /dev/null` for keep it running. i.e. `bash -c "service elasticsearch start && tail -f /dev/null`.

**Comment by DhairyashilBhosale** [comment]
Hi @AkihiroSuda thanks for that after adding `bash -c "service elasticsearch start && tail -f /dev/null` its working fine ,
Please check after `$ docker ps -a`

`CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                       PORTS                              NAMES
bfbc12a69a8a        elasticsearch:latest   "/docker-entrypoint.s"   13 seconds ago      Up 12 seconds                0.0.0.0:9200->9200/tcp, 9300/tcp   elkdockerdir_elk_1
`

its runing but when testing elasticsearch by using curl:
`$  curl 'http://localhost:9200/?pretty' `
its giving error like: 
`curl: (56) Recv failure: Connection reset by peer
`

**Comment by DhairyashilBhosale** [comment]
and 
_>>  But basically, you should supply your own init script that keeps running without this trick, so that exit code can be propagated._

where to add custom init script in elasticsearch docker images or in host can you please give example.

**Comment by DhairyashilBhosale** [comment]
HI @AkihiroSuda ` && tail -f /dev/null` will keep compose running but `elasticsearch` is not running just checked, I got the exact problem that How to pass `command: bach -c "service elasticsearch start"` in docker-compose.yml ?

**Comment by DhairyashilBhosale** [comment]
**issues :**
 `elk_1 | max virtual memory areas vm.max_map_count [65530] likely too low, increase to at least [262144]
`

Solution:
`$  sudo sysctl -w vm.max_map_count=262144 
`
Thanks.

**Comment by cpuguy83** [comment]
You shouldn't need to do `service elasticsearch start`, the elastic search image should be starting elastic search by default. See https://github.com/docker-library/elasticsearch/blob/master/2.4/Dockerfile#L53-L54

Closing since indeed it looks like elasticsearch was having an issue starting up due to a kernel config.
Thanks!

**Comment by ctrlaltdylan** [comment]
@DhairyashilBhosale thanks your command worked for me but isn't persistent after making a new session on the host machine. Did you include this in your startup script to make it permanent?

**Comment by thaJeztah** [comment]
@ctrlaltdylan if you run docker-compose in the foreground, then containers will stop if you terminate your session; use `docker-compose up -d` (`-d` for detached), then you should be able to log out of your session without the containers terminating

**Comment by ctrlaltdylan** [comment]
@thaJeztah I meant that when I restart my host (physical) machine that the `vm.max_map_count` change is forgotten.

**Comment by ctrlaltdylan** [comment]
Nevermind, just added `sudo sysctl -w vm.max_map_count=262144` to `/etc/rc.d`

**Comment by flippakitten** [comment]
If you want to persist this change across reboots on Ubuntu (haven't tried others):

```
sudo vi /etc/sysctl.conf
# Add if not already there
vm.max_map_count=262144

sudo vi /etc/security/limits.conf
your_user  -  nofile  65536
```

**Comment by equivalent** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode

**Comment by senkadir** [comment]
> my dev laptop ES 7.7 setup:
> 
> https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-dev-mode
> 
> ```
> ---
> version: '3'
> services:
>   elasticsearch:
>     image: elasticsearch:7.7.0
>     environment:
>       - "discovery.type=single-node"
> ```

Have you any idea about the reason? Why it's worked?
