### ISSUE TITLE
Unable to run systemd inside Container

### ISSUE THREAD

**Issue by nmagerko** [docker/docker#28377]
**Description**

I have an image that adds a systemd service to a container, enables that service, and then finally starts that service with the following command:
```
CMD  ["systemctl", "start", "example.service"]
```

Unfortunately, whenever I try to run the container, I get an error (see below).

**Steps to reproduce the issue:**
1. Create a Dockerfile that attempts to start a `systemd` service
2. `..$ docker run -it [tag] /bin/bash` (run the container and drop into bash)
3. `..# journalctl -u example.service` (check logs of service; will not exist)
4. `..# systemctl start example.service` (try to start again; will fail)

**Describe the results you received:**
```
Failed to get D-Bus connection: Unknown error -1
```

**Describe the results you expected:**
I expected to see the service I had started in my Dockerfile to be running

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue #25516 had a problem similar to what I am experiencing. However, when I try to run the command mentioned by @thaJeztah [here](https://github.com/docker/docker/issues/25516#issuecomment-238527775) I get the following result immediately:

```
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"--security-opt\\\": executable file not found in $PATH\"\n".
```

This result occurs consistently. I am not sure which file it is referring to.

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: O26P:LOJX:KTYW:OAL6:WN5N:K6AJ:XZCT:GU4O:GCA3:FATM:UEBR:ZWXH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 21
 Goroutines: 34
 System Time: 2016-11-14T07:06:53.071173729Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
- Running MacOS X Sierra
- Building `FROM node:4.6.2`

**Comment by thaJeztah** [comment]
> `starting container process caused "exec: "--security-opt": executable file not found in $PATH`

It looks like you put the `--security-opt` _after_ the name of the image you're running. This option is an option for _docker_, not the process in the container; in other words;

    docker run ubuntu --security-opt some=thing

Will try to run `--security-opt` as command in an "ubuntu" container, whereas;

    docker run --security-opt some=thing ubuntu

Correctly sets the "security-opt some=thing" docker option when starting the container

> and then finally starts that service with the following command:

    CMD  ["systemctl", "start", "example.service"]

That won't work. If you want to run `systemd` in a container, systemd must be the primary process of the container. `systemctl` is just a command to start a service after systemd is already running. See my original example; `/usr/sbin/init` is the command of the container (which is systemd); https://github.com/docker/docker/issues/25516#issuecomment-238527775

> Building `FROM node:4.6.2`

Is there a specific reason you need `systemd` in your container? The official `node` images are designed to work without. Remember that a container is not a VM, it's basically isolating a _process_, not reconstructing a VM.

**Comment by nmagerko** [comment]
@thaJeztah Yes the ordering of the security option was the problem but the `Unknown error -1` remains. However, reading your comments again, I am now unsure if I do need `systemd`. 

The reason I wanted to use it in the first place is because I wanted to try to keep the `node` process alive even if an exception/error occurred. There are `node` packages that will allow me to do this, but I wanted to try to use a system utility instead. 

Should I not worry about the process dying? My only concern is that I'll eventually try running this on AWS ECS, and if a container goes down due to an exception, it might take a few seconds to spin up a new one to replace it. I'm probably misunderstanding how this all works, though.

**Comment by thaJeztah** [comment]
If the process in the container dies, the container dies, but you can set a restart-policy on the container itself (e.g. `--restart=on-failure`, `--restart=always`), that would result in docker restarting the container if it exits.

I don't know the details of your project of course, but question is; in what cases should the process be restarted? Keeping the process alive "even if an exception/error occurred" could also hide serious issues; expected errors/exceptions should be handled by the application, so that _unexpected_ cases result in an error. For example, if for some reason the application fails to run normally, and you don't monitor that situation, but "hide" it by automatically restarting in all cases, that's dangerous. Perhaps it's better in such case to actually _fail_ so that you _know_ something's wrong. You can start a new container to replace the existing one, and investigate the reason the original container is failing.

**Comment by nmagerko** [comment]
Yes, that makes sense. Errors in my project that are unhandled are identified by the exit code of node itself. 

Right now, an exit code of 1 indicates an critical unhandled error, but one that is worth restarting the container for (e.g. there might have been a divide by zero error for a specific function, but I'd rather keep the rest of my project up while I fix it than kill the entire container). If there's an error code of, say, 3, then my application has encountered a configuration error and the container should not restart; the application itself will be unusable.

Does that sound like a reasonable use-case?

**Comment by atyu30** [comment]
# docker run -tid -p 80:80 nginx-server:v1
6447c6283c51f03328a34a8f99dcaa20afe7cda751246f4f8e82b7b4544c3127
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"systemctl start nginx\\\": executable file not found in $PATH\"\n".

**Comment by thaJeztah** [comment]
@atyu30 please don't comment on closed issues;

In your case, this is expected, `systemd` requires additional privileges. Without those, it will not be able to run (IIRC, `--cap-add SYS_ADMIN`), however, it should also be the _main_ process of the container (running as PID1). In most cases though, systemd is not needed, and for an nginx server, simply start `nginx` as the main process (like is done in the official nginx image; https://github.com/nginxinc/docker-nginx/blob/3e8a6ee0603bf6c9cd8846c5fa43e96b13b0f44b/mainline/jessie/Dockerfile#L27).

Keep in mind that the GitHub issue tracker is intended for reporting bugs and feature requests. For questions about _using_ docker, consider using;

- https://forums.docker.com
- the Docker Community Slack channel https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/
- StackOverflow

**Comment by skylei** [comment]
PS C:\docker\mydockerbuild> docker run docker-whale .
container_linux.go:247: starting container process caused "exec: \".\": executable file not found in $PATH"
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: oci runtime error: container_linux.
go:247: starting container process caused "exec: \".\": executable file not found in $PATH".
PS C:\docker\mydockerbuild> docker run docker-whale
 ________________________________________
/  "Logic and practical information do   \
| not seem to apply here."               |
|                                        |
| "You admit that?"                      |
|                                        |
| "To deny the facts would be illogical, |
| Doctor"                                |
|                                        |
| -- Spock and McCoy, "A Piece of the    |
\ Action", stardate unknown              /
 ----------------------------------------
    \
     \
      \
                    ##        .
              ## ## ##       ==
           ## ## ## ##      ===
       /""""""""""""""""___/ ===
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~
       \______ o          __/
        \    \        __/
          \____\______/

**Comment by thaJeztah** [comment]
@skylei your issue is completely unrelated; by typing a `.` after the image name, you're telling docker to use `.` as command for the container. Obviously, that command doesn't exist, so the container fails to start.

**Comment by thaJeztah** [comment]
I'm locking this issue, the original issue reported here was answered. If you're running into issues with docker, and suspect it's a bug, please open a new issue.
