### ISSUE TITLE
Can't set working dir to a subfolder of a volume on Windows

### ISSUE THREAD

**Issue by samcayford** [docker/docker#28390]
When supplying a volume i'm unable to set the working directory with the `-w` flag to a subfolder of that volume. Eg,
This works:
`docker run --rm -v c:/Files:c:/Files -w c:/Files microsoft/windowsservercore:10.0.14393.206 ping localhost`

This does not:
`docker run --rm -v c:/Files:c:/Files -w c:/Files/net microsoft/windowsservercore:10.0.14393.206 ping localhost`
The net folder definitely exists. In fact i've tried with numerous subfolders.

On OSX, using a different image of course, i'm able to do it, eg:
`docker run --rm -v /Users/sam.cayford:/Files -w /Files/docker tomcat:9.0-alpine ping localhost`

**Steps to reproduce the issue:**
1. Start up windows container with a volume attached and set working directory to subfolder of the volume using -w

**Describe the results you received:**
No container started, ping request not run. Error received on command line:
`docker: Error response from daemon: container da243595e9f78645d0192c0ceaf6521c942906909158e72cc86c0a98ebf53e33 encountered an error during CreateContainer: failure in a Windows system call: The directory is not empty. (0x91) extra info: {"SystemType":"Container","Name":"da243595e9f78645d0192c0ceaf6521c942906909158e72cc86c0a98ebf53e33","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{082c0282-a5b5-11e6-a946-12bdebcbc97e}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\da243595e9f78645d0192c0ceaf6521c942906909158e72cc86c0a98ebf53e33","Layers":[{"ID":"04b97519-d714-5f7d-82f8-3e8ed30313da","Path":"C:\\ProgramData\\docker\\windowsfilter\\ae50307fbc9fb05b272eb3ef7669d0a30a56da3d089e1c9700aea9a9f83d06a4"}],"HostName":"da243595e9f7","MappedDirectories":[{"HostPath":"c:\\files","ContainerPath":"c:\\files","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0}],"HvPartition":false,"EndpointList":["b6588754-47c4-4e64-8ef5-61823334c8b6"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.`

I am able to place a .bat file into C:/ that simply does a `cd` into `c:/Files/net` before running the supplied command and it works:
```
docker run --rm -v c:/files:c:/files wscrunner runner.bat "ping localhost"

C:\>(cd c:\Files\net   && ping localhost )

Pinging 9e43f4899bb2 [::1] with 32 bytes of data:
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms
Reply from ::1: time<1ms

**Describe the results you expected:**
I would expect it to work, like on OSX.
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 1024 MiB
Name: EC2AMAZ-AP4K7SM
ID: 6JSQ:WIFX:QJ25:TM5T:JBOG:CR7M:NSOW:X2AJ:QJXR:PRID:CLE2:6Q67
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Username: rusticileeroy
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS Windows 2016 Server with containers image.

**Comment by thaJeztah** [comment]
ping @jhowardmsft

**Comment by jhowardmsft** [comment]
This is a platform issue rather than a docker bug. I'm not sure we can actually fix it though in the current design of how mapped directories are implemented in Windows. A workaround would be to cd to the right place and then execute the command as you have suggested. Hence closing this on GH as there's nothing we can do in docker itself to fix this.
