### ISSUE TITLE
Healthcheck deadlock on container lock

### ISSUE THREAD

**Issue by jhowardmsft** [docker/docker#28405]
@thaJeztah @vieux @tiborvass @talex5 @mlaventure @tonistiigi 

Note this affects 1.13. I've seen several instances of timeout CI failures on Windows RS1 whereby the daemon under test hangs in the healthcheck CLI tests (specifically `DockerSuite.TestPsListContainersFilterHealth`). I finally got the stacks out of one of the production CI servers to investigate, and it's a real deadlock from what I can tell in the healthcheck code. This isn't a Windows-specific deadlock though, it's a race condition so should affect Linux as well.

Here's three relevant threads:

The first is the goroutine started from updateHealthMonitor at https://github.com/docker/docker/blob/master/daemon/health.go#L237

```
goroutine 16975 [semacquire, 101 minutes]:
sync.runtime_Semacquire(0xc0431fa5b4)
	c:/go/src/runtime/sema.go:47 +0x37
sync.(*Mutex).Lock(0xc0431fa5b0)
	c:/go/src/sync/mutex.go:85 +0xd7
github.com/docker/docker/daemon.handleProbeResult(0xc04200e1e0, 0xc0433e9c80, 0xc043098640)
	c:/go/src/github.com/docker/docker/daemon/health.go:111 +0x4d
github.com/docker/docker/daemon.monitor(0xc04200e1e0, 0xc0433e9c80, 0xc0431e12c0, 0x1f58e60, 0xc043ac14a1)
	c:/go/src/github.com/docker/docker/daemon/health.go:186 +0x431
created by github.com/docker/docker/daemon.(*Daemon).updateHealthMonitor
	c:/go/src/github.com/docker/docker/daemon/health.go:237 +0xf8
```
This thread is attempting to take the container lock `0xc0431fa5b4`, but is hung waiting as another thread already has it.

The second thread is also hung attempting to take the container lock `0xc0431fa5b4` as a result of a CLI call to kill the container. This thread isn't really that interesting - just a second deadlocked thread.

```
goroutine 16943 [semacquire, 101 minutes]:
sync.runtime_Semacquire(0xc0431fa5b4)
	c:/go/src/runtime/sema.go:47 +0x37
sync.(*Mutex).Lock(0xc0431fa5b0)
	c:/go/src/sync/mutex.go:85 +0xd7
github.com/docker/docker/container.(*State).WaitStop(0xc0431fa5b0, 0xffffffffc4653600, 0x0, 0x0, 0x0)
	c:/go/src/github.com/docker/docker/container/state.go:191 +0xce
github.com/docker/docker/daemon.(*Daemon).Kill(0xc04200e1e0, 0xc0433e9c80, 0x0, 0x73f5d0)
	c:/go/src/github.com/docker/docker/daemon/kill.go:147 +0x9c
github.com/docker/docker/daemon.(*Daemon).cleanupContainer(0xc04200e1e0, 0xc0433e9c80, 0x101, 0x0, 0x0)
	c:/go/src/github.com/docker/docker/daemon/delete.go:85 +0xb1
github.com/docker/docker/daemon.(*Daemon).ContainerRm(0xc04200e1e0, 0xc043e242d9, 0xc, 0xc042ade78b, 0x0, 0x0)
	c:/go/src/github.com/docker/docker/daemon/delete.go:45 +0x30b
github.com/docker/docker/api/server/router/container.(*containerRouter).deleteContainers(0xc04236a780, 0x1f70160, 0xc042cd83c0, 0x1f6ca60, 0xc043adc000, 0xc043bbc000, 0xc042cd82d0, 0x16a78de, 0x5)
	c:/go/src/github.com/docker/docker/api/server/router/container/container_routes.go:402 +0x17f
github.com/docker/docker/api/server/router/container.(*containerRouter).(github.com/docker/docker/api/server/router/container.deleteContainers)-fm(0x1f70160, 0xc042cd83c0, 0x1f6ca60, 0xc043adc000, 0xc043bbc000, 0xc042cd82d0, 0x41a30f, 0x30)
	c:/go/src/github.com/docker/docker/api/server/router/container/container.go:75 +0x70
github.com/docker/docker/api/server/middleware.ExperimentalMiddleware.WrapHandler.func1(0x1f70160, 0xc042cd83c0, 0x1f6ca60, 0xc043adc000, 0xc043bbc000, 0xc042cd82d0, 0x1b, 0x22)
	c:/go/src/github.com/docker/docker/api/server/middleware/experimental.go:27 +0xdf
github.com/docker/docker/api/server/middleware.VersionMiddleware.WrapHandler.func1(0x1f70160, 0xc042cd8390, 0x1f6ca60, 0xc043adc000, 0xc043bbc000, 0xc042cd82d0, 0x179db02, 0x40a9fc)
	c:/go/src/github.com/docker/docker/api/server/middleware/version.go:47 +0x5d1
github.com/docker/docker/pkg/authorization.(*Middleware).WrapHandler.func1(0x1f70160, 0xc042cd8390, 0x1f6ca60, 0xc043adc000, 0xc043bbc000, 0xc042cd82d0, 0xc042f75af0, 0x415247)
	c:/go/src/github.com/docker/docker/pkg/authorization/middleware.go:43 +0x846
github.com/docker/docker/api/server.(*Server).makeHTTPHandler.func1(0x1f6ca60, 0xc043adc000, 0xc043bbc000)
	c:/go/src/github.com/docker/docker/api/server/server.go:139 +0x23a
net/http.HandlerFunc.ServeHTTP(0xc04241b920, 0x1f6ca60, 0xc043adc000, 0xc043bbc000)
	c:/go/src/net/http/server.go:1726 +0x4b
github.com/docker/docker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc04214c3c0, 0x1f6ca60, 0xc043adc000, 0xc043bbc000)
	c:/go/src/github.com/docker/docker/vendor/github.com/gorilla/mux/mux.go:103 +0x25c
github.com/docker/docker/api/server.(*routerSwapper).ServeHTTP(0xc0427d6150, 0x1f6ca60, 0xc043adc000, 0xc043bbc000)
	c:/go/src/github.com/docker/docker/api/server/router_swapper.go:29 +0x77
net/http.serverHandler.ServeHTTP(0xc04215ee00, 0x1f6ca60, 0xc043adc000, 0xc043bbc000)
	c:/go/src/net/http/server.go:2202 +0x84
net/http.(*conn).serve(0xc0449dfa00, 0x1f6e5e0, 0xc043e24280)
	c:/go/src/net/http/server.go:1579 +0x4be
created by net/http.(*Server).Serve
	c:/go/src/net/http/server.go:2293 +0x454
```

The third thread is the most interesting one.
- Libcontainerd is calling back into monitor.go `StateChanged` with StateExit after a container has exited.
- `StateChanged` takes the container lock https://github.com/docker/docker/blob/master/daemon/monitor.go#L41
- It calls into `updateHealthMonitor` https://github.com/docker/docker/blob/master/daemon/health.go#L227 with the container lock held
- It then calls into `CloseMonitorChannel` https://github.com/docker/docker/blob/master/container/health.go#L42
- `CloseMonitorChannel` sends `struct{}{}` into the stop channel. https://github.com/docker/docker/blob/master/container/health.go#L48. Note this is a blocking send.
- This wakes the first thread in this issue `goroutine 16975` which cannot take the container lock as it is already held in this goroutine.

```
goroutine 16970 [chan send, 101 minutes]:
github.com/docker/docker/container.(*Health).CloseMonitorChannel(0xc043398f40)
	c:/go/src/github.com/docker/docker/container/health.go:48 +0xe6
github.com/docker/docker/daemon.(*Daemon).updateHealthMonitor(0xc04200e1e0, 0xc0433e9c80)
	c:/go/src/github.com/docker/docker/daemon/health.go:240 +0x88
github.com/docker/docker/daemon.(*Daemon).StateChanged(0xc04200e1e0, 0xc0442f5180, 0x40, 0x16a6929, 0x4, 0xc00000010000318c, 0x16a69fd, 0x4, 0x0, 0x0, ...)
	c:/go/src/github.com/docker/docker/daemon/monitor.go:54 +0x439
github.com/docker/docker/libcontainerd.(*container).waitExit(0xc042b06fc0, 0xc042b06fc0, 0x1, 0xc04336dca0, 0xc0430716d0)
	c:/go/src/github.com/docker/docker/libcontainerd/container_windows.go:255 +0x543
created by github.com/docker/docker/libcontainerd.(*container).start
	c:/go/src/github.com/docker/docker/libcontainerd/container_windows.go:147 +0xdde
```

There are a couple of solutions which come to mind. One could be to make the channel send in `CloseMonitorChannel` at https://github.com/docker/docker/blob/master/container/health.go#L48 into a non-blocking send (https://gobyexample.com/non-blocking-channel-operations) such as

```
select {
    case: s.stop <- struct{}{}
    default:
}
```

Another is to re-work the way in which the container lock is not held when calling into `updateHealthMonitor`. This would be a lot more involved though.

I'm going to try out the non-blocking send to see if this is a viable and easy solution and submit a PR if it passes tests locally consistently. Would be interested in thoughts on this.

**Comment by talex5** [comment]
The send is blocking to prevent another race, IIRC.

Could we get `handleProbeResult` to give up trying to get the lock and abort early if `stop` becomes ready while it's waiting?

**Comment by jhowardmsft** [comment]
I don't know how you could make `handleProbeResult` quit attempting to take the lock based on a channel becoming ready.

Do you have any more information on the other race you're alluding to?

**Comment by talex5** [comment]
If you don't wait for the monitor thread to stop, then you might go on to handling the next event and find that it requests starting a new monitor thread. Now you have two monitor threads running at the same time on the same structure.

**Comment by tonistiigi** [comment]
Why not just close the stop channel(check if needs to be protected with `sync.Once`). On `handleProbeResult` after getting the lock check if container has exited. Before every iteration in `health.monitor()` check if stop has been closed and return if it has.

**Comment by talex5** [comment]
We also stop monitoring if the container becomes paused, so testing for exited isn't quite right. But we get a new `stop` channel each time, so we could check if the old one has been closed after getting the lock.

**Comment by jhowardmsft** [comment]
Hang on - how could it get the lock? That's the whole point behind this issue...

**Comment by tonistiigi** [comment]
@jhowardmsft If we just close stop without blocking send, `updateHealthMonitor` would not block, container lock would be released and `handleProbeResult` can aquire it. Then after getting it in `handleProbeResult` we just need to detect the stopped case case and cancel.

**Comment by jhowardmsft** [comment]
@tonistiigi Do you want to try to fix this?
