### ISSUE TITLE
Document Compose V3 support in 1.13

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#28414]
https://github.com/docker/docker/pull/27998 seems to have been merged with without any documentation.

There should be.

Short version how to use these features to get the ball rolling:

1. Make a new `docker-compose.yml` or port an existing one, with `version: '3'` explicitly specified.  Seems the "schema" (layout of `services`, `networks`, etc. keys) did not change much in this new version but some parameters for services are unsupported.  I'm guessing `build:` is likely not supported as well?
2. Run `docker deploy --compose-file docker-compose.yml stackname`.
3. `docker stack` can be used to view the generated services for the "stack" defined by the Docker Compose file.  e.g., `docker stack ls` to view created stacks, `docker stack services stackname` to view the services associated with that stack, etc.

FYI @londoncalling @johndmulhausen

**Comment by johndmulhausen** [comment]
Anyone reading this: Come on over the docs and add this information over in the `vnext-compose` branch, and we'll be sure it gets published at release time. 

https://github.com/docker/docker.github.io/tree/vnext-compose

In addition, when you send the PR over there, tag it with the milestone using the GitHub UI:

https://github.com/docker/docker.github.io/milestone/3

**Comment by nathanleclaire** [comment]
@johndmulhausen Just to make sure you're aware, this is Docker CLI / API functionality which happens to use the Compose format, and is different than the ["Python Compose implementation"](https://github.com/docker/compose).  If you're certain you'd like the IA to have this information about `docker deploy` etc. in the `vnext-compose` branch, 👍

**Comment by faddat** [comment]
This leaves me with two questions:

1) Compose is being added to the docker executable?
2) Does this mean we can forget about DABs?

**Comment by cpuguy83** [comment]
@faddat 

> 1) Compose is being added to the docker executable?
Sort of. Direct support for compose files via `docker deploy` is available via the experimental docker.

> 2) Does this mean we can forget about DABs?
Both DAB and compose file support are available.

**Comment by faddat** [comment]
Suggestion for new company motto:

"Docker: It moves fast, so life stays interesting"


Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by thaJeztah** [comment]
We received a lot of feedback based on the experimental "docker deploy" functionality; many people wanted to be able to deploy directly from the docker-compose file, without having to create an intermediate file.

**Comment by faddat** [comment]
@thajeztah absolutely, you can count me as solidly in that group.

**Comment by dnephin** [comment]
The docs PR is open here: https://github.com/docker/docker.github.io/pull/716

It needs some attention

**Comment by johndmulhausen** [comment]
Copy/pasting a comment from PR number 716:

@aanand @londoncalling @dnephin @mstanleyjones

I think we meant to do this in vnext-compose as it's for Compose v1.10.

It should also be tracked against the Compose v1.10 milestone: https://github.com/docker/docker.github.io/milestone/5

So, one more revert, and one more re-do. Sorry.

CC'ing @mstanleyjones because I'm not sure when the last time we rebased vnext-compose was.

**Comment by londoncalling** [comment]
@dnephin @thaJeztah @johndmulhausen please see https://github.com/docker/docker.github.io/pull/937

**Comment by thaJeztah** [comment]
closing now that docs are merged
