### ISSUE TITLE
Host path creation (of bind mount) not supported in Compose V3 / stack deploy

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#28416]
In `volumes:` for a Compose file in `1.13.0-rc1` a bind mount will not be created if it does not already exist...

```
time="2016-11-14T21:28:51.372422927Z" level=error msg="failed to start taskManager" error="invalid bind mount source, source path not found: /srv/docker/gitlab/postgresql" module="node/agent"
```

... this breaks with existing `docker run` behavior and should probably at least be documented as a caveat. (cfr: https://github.com/docker/docker/issues/28414). Although I'm somewhat surprised it doesn't just go create the host directory. @aanand @dnephin wdyt?

**Comment by dnephin** [comment]
`docker stack deploy` uses the services API, so it should behave the same was as it does for `docker service create`.

**Comment by cpuguy83** [comment]
Yes, this is expected.
Swarm does not create bind paths automatically.

**Comment by thaJeztah** [comment]
It's expected indeed, but I can see the need for explicitly mentioning it in the docs for compose V3 / stack deploy (https://github.com/docker/docker/issues/28414). Let's close this issue, and use that issue for tracking
