### ISSUE TITLE
Handling of `--rm` broken when talking to older daemons

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#28439]
With the new daemon-side auto-remove on exit, the `--rm` flag causes the CLI to hang when talking to an older (pre-1.13) daemon.

Reproduce:

1. Build a 1.13 client
2. Do a `docker run --rm` against a 1.12 daemon

**Comment by thaJeztah** [comment]
/cc @mlaventure @WeiZhang555 

introduced in https://github.com/docker/docker/pull/20848

**Comment by cpuguy83** [comment]
Working on a fix.

**Comment by cpuguy83** [comment]
#20848

**Comment by WeiZhang555** [comment]
One thing to mention, I think we already have a policy that we don't support newer client + old daemon, we only need to guarantee old client + new daemon for backward compatibility https://github.com/docker/docker/pull/20848#issuecomment-191747105

But if @cpuguy83 added this without many codes, it's also good to me. :smile:

**Comment by cpuguy83** [comment]
We do support this now.

**Comment by thaJeztah** [comment]
@WeiZhang555 yes, I later realized that feature was not in place when your PR was merged. Docker 1.13 adds support for talking to older daemons, see https://github.com/docker/docker/pull/27745

**Comment by WeiZhang555** [comment]
@thaJeztah Obviously this is a cool feature for end users, but I can imagine there would be lots of hard works to achieve this. I must be away for too long and miss so many things :stuck_out_tongue:
