### ISSUE TITLE
Docker Remote API docs should document `Tmpfs` as a `HostConfig` option

### ISSUE THREAD

**Issue by Ghnuberath** [docker/docker#28441]
While it's clear how to use the `--tmpfs` flag on `docker run`, it isn't clear how to accomplish the same thing via the Remote API because the `HostConfig.Tmpfs` option is undocumented [here](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/create-a-container).

It took a fair amount of trial-and-error to figure out that it's meant to look something like this:

```js
'HostConfig': {
  // ...
  'Tmpfs': {
    '/tmp': 'rw,exec' // mount options (your choice)
  }
}
```

Hopefully documenting this here, and eventually in the actual API docs, will save someone else from diving through [this](https://github.com/docker/docker/blob/master/api/types/container/host_config.go).

**Comment by cpuguy83** [comment]
Thanks for pointing this out.

We're moving to swagger generated docs, which will help make sure we don't miss stuff like this, currently it's all done manually.

I'll add the doc label here if someone wants to make a quick PR to fix this. I don't remember how far back this goes, though.
API docs are in `docs/reference/api` in this repo.

**Comment by Ghnuberath** [comment]
I think it's at least as far back as one of the 1.10.x's
