### ISSUE TITLE
overlay network plugin is missing from docker info output

### ISSUE THREAD

**Issue by vincebowdren** [docker/docker#28450]
**Description**

The output from docker info includes a section *Plugins*, within which there is *Network*. Typically this shows four items: *bridge null host overlay* (in no particular order); but on my docker installations it only shows three: *bridge null host* .

**Describe the results you received:**

```
Plugins:
 Volume: local
 Network: bridge null host
```

**Describe the results you expected:**
```
Plugins:
 Volume: local
 Network: bridge null host overlay
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.10.x86_64
 Go version:      go1.6.3
 Git commit:      d381c64-unsupported
 Built:           Thu Aug  4 13:21:17 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:2-395657-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 644.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 7.127 GB
 Metadata Space Used: 1.552 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: json-file
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 31.26 GiB
Name: webdmz8-10-250-130-124
ID: 2FHN:3AEV:SPGX:QHHJ:34HL:A3MW:LGR5:MCPB:D7HQ:6CPQ:A4WV:WLVX
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

A set of virtual machines each running CentOS 7.0; the same problem is observed on all seven.

Note: I understand that the [overlay driver should now be supported on kernel 3.10](https://github.com/docker/docker/releases/tag/v1.10.0) however there might be some remaining incompatibility problem?

**Comment by thaJeztah** [comment]
The reason it's not showing is that 1.10 based the output of `docker info` is based on drivers in use by a network. For docker 1.10, overlay networking requires an external k/v store.

If looks like you're using the red hat fork of docker, and an older version; can you try installing the current (1.12.3) version from the official repositories? https://docs.docker.com/engine/installation/linux/rhel/

**Comment by vincebowdren** [comment]
OK, thanks @thaJeztah , that makes sense. I've been *trying* to get an external k/v store working in order to use an overlay network, so far without success; I was wondering if the driver not showing up in docker info was an indication of why it wasn't working for me - but it sounds like it's the other way around, it's a symptom not a cause.

I'll carry on doing the tricky work of wrangling the the cluster-store and cluster-advertise options into dockerd, and not worry about the docker info output for now.

**Comment by thaJeztah** [comment]
@vincebowdren in docker 1.12, overlay networking for "swarm mode" works out of the box, without having to set up an external k/v store. In 1.13, this is being extended so that it can also be used for `docker run`.

**Comment by vincebowdren** [comment]
Thanks - I'll be looking into swarm mode in due course as well.
