### ISSUE TITLE
Problem with `--cpus` error message

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker#28456]
**Description**

Using 1.13 RC1 on Linux, I try to run a container with `--cpus=2` when I only have one CPU. The error message I get seems like a bug, and the `--help` text also says the unit is a "decimal" when that makes me wonder if it would accept a floating-point number.

```
ubuntu@ip-172-31-46-109:~$ docker run --help

Usage:	docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container

Options:
...
      --cpus decimal                          Number of CPUs (default 0.000)
...
```

```bash
$ docker run --cpus=2 hello-world

docker: Error response from daemon: Range of Nano CPUs is from 1 to 1000000000.
See 'docker run --help'.

$ docker run --cpus=2.0 hello-world

docker: Error response from daemon: Range of Nano CPUs is from 1 to 1000000000.
See 'docker run --help'.

$ docker run --cpus=1 hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 2
 Paused: 0
 Stopped: 3
Images: 55
Server Version: 1.13.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 64
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 0p14wy00b3h8nfkumrjucmhln
 Is Manager: true
 ClusterID: lkln9som0ao5w3o4vppafe9wh
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.46.109
 Manager Addresses:
  172.31.46.109:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-46-109
ID: IAXO:F4VE:QY6K:DYL7:QHEJ:XA47:2FDM:BITI:XSAL:OTJH:4LDS:TSCA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running 1.13 binary on an EC2 Ubuntu 16.04 box.

**Comment by yongtang** [comment]
@mstanleyjones The `Nano CPUs` is the concept in daemon. The `--cpus` is converted into NanoCPUs before passed to the daemon. However `Nano CPUS` itself is invisible to the user.

I think we could change the error message to `CPUs`. 

#dibs

**Comment by thaJeztah** [comment]
@yongtang I think there's multiple issues here;

1. confusing about the correct input value (is it indeed a decimal (1.0, 1.5 etc))?
2. the error message is confusing (2 and 2.0 are between 1 and 1000000000)

In this case, the error seems to be because there's only 1 CPU, so CPUs cannot be bigger than 1? Should we have a separate error message for that?

**Comment by mstanleyjones** [comment]
I don't think 1000000000 CPUs is a serious possibility anyway...

**Comment by yongtang** [comment]
@thaJeztah @mstanleyjones When `--cpus` is passed, it takes a decimal like `1.00`, `2.00`, etc. This value is converted (internally) into NanoCPUs (`1000000000`, `2000000000`) before it is passed to daemon.

Inside the daemon it uses the `NanoCPUs` to show up the error message.

So if there is only 1 CPU, and `--cpus 2.0` is passed, it will show an error that `Range of Nano CPUs is from 1 to 1000000000`.

**Comment by yongtang** [comment]
I realized that potentially there is another issue: the minimal CPUs that could be specifed is also not `0.000000001` (`1 NanoCPU`).

On Windows, since CPUs has to be converted into percent so the range of CPUs should be (`0.01 - 1.00`) (1 CPU case).

I will need to investigate more to find out the minimal CPUs on Linux.

**Comment by thaJeztah** [comment]
Oh, just wanted to comment that for a single-cpu machine, valid _user_ values are between `0.000000001` and `1.0`

I don't expect people to enter values with that level of precision, so "assuming" two decimals sounds good to me.

We should probably still have a better error to explain that for _this_ machine there's only a single CPU, so the range is `0.01` - `1.00` (suggestions welcome for that)

**Comment by yongtang** [comment]
It seems that on Linux, the highest precision is `0.001`.

The reason is that the highest `cpu.cfs_period_us` is `1s` and the lowest `cpu.cfs_quota` is `1ms` so we could get to `0.001` (1ms/1s):
https://www.kernel.org/doc/Documentation/scheduler/sched-bwc.txt

On Windows the precision is `0.01`.

Maybe it make sense to fix the precision to `0.01` for both Windows and Linux? We could also set precision to `0.01` on Windows and `0.001` on Linux if this is preferred.

**Comment by crosbymichael** [comment]
Yes, 2 decimal places is a good start for docs

**Comment by yongtang** [comment]
@crosbymichael @mstanleyjones @thaJeztah PR #28458 has been created. Please take a look and let me know if there are any issues.
