### ISSUE TITLE
Problem create service with parameters

### ISSUE THREAD

**Issue by ildarmf** [docker/docker#28479]
Hello!

I have docker image, I want to run this image in swarm with replicas with the following parameters(volumes, ports, env, command)

How can I do that?

Example:
This command works:
docker service create --with-registry-auth --name low --replicas=5 image

What i want
docker service create --with-registry-auth --name low --replicas=5 image --env= {user=test, sign='qwerty' } --volume=/data command=sh bin/start.sh

**Comment by cpuguy83** [comment]
I'm not sure I understand here. These options all exist as exact counterparts from `docker run`, except for `--volume`, which is `--mount type=volume,target=/data`

**Comment by ildarmf** [comment]
When I asked the question I originally read this article https://docs.docker.com/engine/reference/commandline/service_create/
In this article, I have not found how to run the command(example: command)

After your comment @cpuguy83 
I found this article https://docs.docker.com/swarm/install-manual/

I want to understand how to do better through docker service or docker run.
If you use a docker create how to run commands?

**Comment by thaJeztah** [comment]
Note that the second article is about "classic" swarm, not swarm _mode_ (new in docker 1.12). However, this should work;

```
docker service create --name foo -e user=test -e sign=qwerty nginx sh -c "bin/start.sh"
```

**Comment by ildarmf** [comment]
@thaJeztah thank you!

I solved my problem:
`docker service create --with-registry-auth --name low -p 7799:7799  -p 9209:9209 -p 9099:9098 -e  USER="tst1" -e SIGNATURE="2ebe634644364e7b274967feccc1720bc96aeb9b" -e DATABASE_HOST=mongo --network=tst1 --replicas=5 backend:1.9 bin/run.sh`

**Comment by cpuguy83** [comment]
Thanks @ildarmf!
