### ISSUE TITLE
Parameterizing FROM in Dockerfile

### ISSUE THREAD

**Issue by Puneeth-n** [docker/docker#28478]
Is it possible to parametrize partially the `FROM` statement in a `Dockerfile`?

The use case is as below.

We want to check if multiple versions of the base image is compatible with a microservice on a CI server. That would mean maintaining multiple redundant Dockerfiles per base image or parameterize the version number in the `FROM` statement.

**Comment by ripcurld00d** [comment]
@Puneeth-n can you specify your use case.
Because different images use different package managers and tools and parameterizing `FROM` will bring more complexity to the Dockerfile.

**Comment by Puneeth-n** [comment]
@ripcurld00d Thanks for the reply. Let me tell you my use case.

I have a `nodejs` library called `my_nodejs_lib` whose docker images is with tags `1.0.0` and `latest`. I have 20 `nodejs` microservices each of which has a `Dockerfile` which extends my nodejs library as `FROM my_lodejs_lib:latest` Note that I have hardcoded the `tag` to `latest` because I don't want to update 20 Dockerfiles everytime there is a new version of `my_nodejs_lib`.

Now suppose, I want to release a new version of `my_nodejs_lib` with tags `1.0.1` and `latest`. Before I can assign the `latest` tag to `1.0.1` I would like to test all the 20 odd micro services to check if this update breaks any of the micro services. Therefore I would like to have something in the Dockerfile of my micro services as `FROM my_nodejs_lib:${my_version:-latest}` Therefore, for testing, I would set `my_version` with `1.0.1` and build all my microservices and run tests before assigning the `latest` tag to `1.0.1`

**Comment by Puneeth-n** [comment]
Maybe I am doing something completely wrong. I would really appreciate your thoughts on this.

**Comment by ripcurld00d** [comment]
@Puneeth-n 
Thank you for the details.

From what I know, the part that creates an image from Dockerfile is going to be moved to the client side.
What it means is that it will allow building custom implementations of Dockerfile syntax or a custom builder.
Read more here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

/cc @thaJeztah

**Comment by Puneeth-n** [comment]
Thanks. @ripcurld00d One more use case is for folks using single repository approach where say 30 microservices are in a single repo including their shared library. Each microservice in this repo has its own Dockerfile and is extending the common shared library image. In such case, a typical CI/CD pipeline would be:

**Comment by AkihiroSuda** [comment]
I would use eruby or erb for that purpose, but I'm not sure it is a cleaner approach 😅

**Comment by Puneeth-n** [comment]
@AkihiroSuda Seems like using some template engine is the way to go for now!

**Comment by unclejack** [comment]
The right way to accomplish this would be through multiple images built from multiple Dockerfile. `docker build` accepts a parameter which specifies the path to the Dockerfile to be used. This would make it easy to build multiple images from the same directory.

Here's an example with multiple directories.
./a/Dockerfile:
```
FROM alpine
RUN do-something-important
```
builds the image: a
./b/Dockerfile:
```
FROM a
RUN do-another-important-thing
CMD ["/usr/bin/some-realy-important-process"]
```
builds the image: b

You can apply the same technique to generate a Dockerfile on the fly based on whatever you need. There's no need to make `FROM` parametric.

There are many use cases for `docker build` with various setups. Many of these neded features can be scripted or made part of a bigger build. Projects which have multiple images for various services will have a custom build system anyway.

@Puneeth-n Does this help?

**Comment by Puneeth-n** [comment]
@unclejack You are right about the image building part. This is what we currently do and this works as long as a PRs are tested sequentially on a buildserver like `Jenkins` But doesn't work once PRs are tested in parallel. Imagine 1 PR fixes a bug in `my_nodejs_lib` and the 2nd PR changes something in `my_cool_service` whose Dockerfile "inherits" from `my_nodejs_lib` Each PR has a different version of `my_nodejs_lib` needed and when these PRs are built on `Jenkins` in parallel there will be a race condition between the version of `my_nodejs_lib` used.

Yes I agree that we should develop some custom implementation to generate Dockerfiles on the fly.

**Comment by unclejack** [comment]
@Puneeth-n That seems to be very tied to your particular workflow. This can be managed easily by triggering a rebuild of all the images which rely on that parent image. This is what everyone does. There's really no need for a parametric FROM for this use case.

This discussion is more appropriate for https://forums.docker.com.

**Comment by thaJeztah** [comment]
Note that there's an open discussion that's related; https://github.com/docker/docker/issues/18119

**Comment by Puneeth-n** [comment]
@thaJeztah Thanks for the pointers.

**Comment by philippe-granet** [comment]
You can now use build-time args (ARG) in FROM https://github.com/moby/moby/pull/31352
