### ISSUE TITLE
BUG: Docker for Mac stable or beta locks up (beachball)

### ISSUE THREAD

**Issue by zbeckman** [docker/docker#28481]
**Description**

After downloading either Docker for Mac stable *or* beta, running the Docker app appears to fail; no app starts, no Docker whale appears in the toolbar. Docker does not appear to be installed (e.g.: no links appear in /usr/local/bin). Running a `ps ax|grep Docker` reveals:

```
599 zbeckman:bin$ ps ax|grep Docker
 4312   ??  S      0:00.11 /Applications/Docker.app/Contents/MacOS/Docker -psn_0_2105858
```

**Steps to reproduce the issue:**
1. Download the latest release (stable) or beta release
2. Drag Docker.app to /Applications
3. Double-click on Docker.app

**Describe the results you received:**

Docker.app appears to beachball. No icon appears in the toolbar.

**Describe the results you expected:**

I expected to see the Docker whale in my toolbar and have an operational Docker system.

**Additional information you deem important (e.g. issue happens only occasionally):**

Running `/Applications/Docker.app/Contents/Resources/bin/docker-diagnose` generates the following output:

```
OS X: version 10.12.1 (build: 16B2657)
Docker.app: version: 1.12.3 (583d1b8)
Local time: Wed Nov 16 10:06:46 EST 2016
UTC:        Wed Nov 16 15:06:46 UTC 2016
Timestamp:  20161116-100646
Running diagnostic tests:
[ERROR]   docker-cli       cannot find docker
Error docker -v: timeout after 10.00s
[OK]      Moby booted
[ERROR]   driver.amd64-linux com.docker.driver.amd64-linux -db is not running
[ERROR]   vmnetd           /private/tmp/vmnetd/com.docker.vmnetd is not running
[ERROR]   osxfs            com.docker.osxfs is not running
[ERROR]   db               Connection refused (ECONNREFUSED) connecting to /Users/zbeckman/Library/Containers/com.docker.docker/Data/s40: check if service is running
[ERROR]   db               com.docker.db is not running
[ERROR]   slirp            Connection refused (ECONNREFUSED) connecting to /Users/zbeckman/Library/Containers/com.docker.docker/Data/s51: check if service is running
[ERROR]   slirp            com.docker.slirp is not running
[OK]      disk
[OK]      menubar
[OK]      environment
[OK]      Docker
[OK]      VT-x
Error docker -v: got timeout (docker -v: exit 127)
[OK]      kern.hv_support
Error exec: echo "00000003.0000f3a6" | nc -U /Users/zbeckman/Library/Containers/com.docker.docker/Data/@connect > /tmp/2A7766C2-0B78-4EB6-ABB8-53EF34A03F8A/20161116-100646/diagnostics.tar: exit 1
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by zbeckman** [comment]
More info (and a fix, but I think this is still a legit bug):

**Resolution**

After reading up on #8 and #107, I tried a lot of hacking. Finally... after many attempts, doing this:

```
sudo launchctl remove com.docker.vmnetd
```

And running Docker.app seems to have solved the problem. Docker is now functioning correctly as far as I can tell.

Seems there should be some kind of check in the app so a dead process and a beachball is not the only result.

**Comment by justincormack** [comment]
Please can you open docker for mac specific issues in https://github.com/docker/for-mac/issues and include a diagnostic ID. This repo is for docker engine specific issues, so I am closing this here.

**Comment by zbeckman** [comment]
Issue opened: https://github.com/docker/for-mac/issues/961
