### ISSUE TITLE
Prune based on age

### ISSUE THREAD

**Issue by astropuffin** [docker/docker#28497]
https://github.com/docker/docker/pull/26108 is fantastic. However, it doesn't handle this use case: a CI server where I need to keep images around for a couple days for caching, but need to prune them after that. I would like to have a time parameter (in days or hours) to exclude image/container/etc pruning. An LRU system would be ideal, but more technically complicated. For context, I am handling this with the script below. It's a little gross, but gets the job done.
```
#!/bin/bash
function check_age(){
    while read cid
    do
        age=$(date -d $(docker inspect -f '{{.Created}}' $cid) +%s)
        if [ $age -lt $TOO_OLD ]; then
            echo "$cid"
        fi
    done
}

get_names(){
    while read cid
    do
        docker inspect -f '{{.RepoTags}}' $cid | tr -d '[]'
    done
}

echo "cleaning containers"
TOO_OLD=$(echo "$(date +%s)-60*60*6" | bc)
docker rm -v $(docker ps --filter status=exited -q 2>/dev/null)
docker rm -f $(docker ps -aq --no-trunc | check_age)

echo "cleaning images"
docker rmi $(docker images --no-trunc -q --filter "dangling=true")
TOO_OLD=$(echo "$(date +%s)-60*60*24*7" | bc)
docker rmi $(docker images -q --no-trunc | check_age | get_names)

exit 0
```

**Comment by ripcurld00d** [comment]
I think what you're talking about is a garbage collector for Docker.
See more here: https://github.com/docker/docker/issues/18601

**Comment by astropuffin** [comment]
Yes a full GC would completely cover this (and be great). However, a fully automatic GC is larger in scope that what I am describing here. My intention is a very narrow expansion of the prune command to allow a time parameter.

**Comment by yongtang** [comment]
Added a PR #28535 so that it is possible to have `--until` for `docker container prune` and `docker image prune`.
