### ISSUE TITLE
Frequent log message: failed to retrieve docker-init version

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#28494]
After upgrading a host from Docker 1.12.3 to 1.13.0-rc1, I'm seeing this message in the logs every 20 seconds:

```
time="2016-11-16T19:51:31.192624068Z" level=warning msg="failed to retrieve docker-init version: unknown output format"
```

```
# docker version
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:41:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:41:05 2016
 OS/Arch:             linux/amd64
 Experimental:        false

# docker info
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.13.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: dw0lwvpnl1qyablsx9qymm0xc
 Is Manager: true
 ClusterID: 1y6spf1vqrxndmu1x1icuji2c
 Managers: 2
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.11.220
 Manager Addresses:
  52.23.174.225:2377
  54.209.84.184:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
Kernel Version: 3.13.0-92-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5 MiB
Name: ip-172-31-11-220
ID: 2GKH:OS2J:AS52:MPMM:JB2N:IW7L:WSD7:K5FY:I3ED:6LB2:TPWQ:J3RM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mlaventure** [comment]
Fixed in https://github.com/docker/docker/pull/28310

**Comment by rogaha** [comment]
I'm still getting this error message:
```
Client:
 Version:      17.04.0-ce-rc1
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   d2532c6
 Built:        Sat Mar 18 00:00:21 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.04.0-ce-rc1
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   0f573db
 Built:        Thu Mar 16 06:35:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by mlaventure** [comment]
@rogaha does `docker-init` exist and is executable on your system?

**Comment by danielmorlock** [comment]
Getting this error, too

``` bash
$ docker --version
Docker version 17.03.1-ce, build c6d412e
$ which docker-init
/usr/bin/docker-init
$ docker-init --version
tini version 0.13.2
```

**Comment by thaJeztah** [comment]
@danielmorlock what platform are you running on, and how did you install? Looking at the 17.03.1 source code, https://github.com/moby/moby/blob/v17.03.1-ce/daemon/info_unix.go#L57, it expects the version of `tini` to be a _commit_, not a version (see https://github.com/moby/moby/blob/v17.03.1-ce/hack/dockerfile/binaries-commits#L8)

In that case you would see _this_ error message: https://github.com/moby/moby/blob/v17.03.1-ce/daemon/info_unix.go#L75

Docker 17.05 adds some improvement for the version parsing, see https://github.com/moby/moby/pull/32187, and https://github.com/moby/moby/pull/32436

**Comment by danielmorlock** [comment]
I'm running it on Gentoo. I think this is a packaging problem since there might be the wrong tini version packaged.

**Comment by andreister** [comment]
I'm seeing the same on an AWS EC2 instance spinned up few days ago:
```
$ tail /var/log/docker
time="2017-07-28T18:48:14.699653604Z" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc2\nspec: 1.0.0-rc2-dev\n"
time="2017-07-28T18:48:14.699708030Z" level=warning msg="failed to retrieve docker-init version"
time="2017-07-28T18:50:17.397442668Z" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc2\nspec: 1.0.0-rc2-dev\n"
time="2017-07-28T18:50:17.397499756Z" level=warning msg="failed to retrieve docker-init version"
```
```
$ docker info
Containers: 488
 Running: 3
 Paused: 0
 Stopped: 485
Images: 4
Server Version: 17.03.1-ce
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 2.988 GB
 Data Space Total: 23.35 GB
 Data Space Available: 20.37 GB
 Metadata Space Used: 16.59 MB
 Metadata Space Total: 33.55 MB
 Metadata Space Available: 16.97 MB
 Thin Pool Minimum Free Space: 2.335 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:  (expected: 4ab9917febca54791c5f071a9d1f404867857fcc)
runc version: N/A (expected: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.32-15.41.amzn1.x86_64
Operating System: Amazon Linux AMI 2017.03
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.5 MiB
Name: ip-xxx-xx-xx-xxx
ID: 6Z4W:6243:SNV5:2KDP:PWUY:Q4WU:MO5E:3JY4:MGQJ:55Y4:WTOB:L7UI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I suspect that's an issue with how those AMIs are set up; there are no official packages for Amazon Linux currently; have you opened a ticket with Amazon?

**Comment by andreister** [comment]
No, what's the best place for that?

**Comment by thaJeztah** [comment]
Not really an AWS expert myself, so can't help there

**Comment by iahmad-khan** [comment]
Same issue on rhel7 , latest docker CE

**Comment by thaJeztah** [comment]
@iahmad-khan can you post full output of `docker version` and `docker info`?

**Comment by sumeng001** [comment]
Apr 26 17:12:41 localhost systemd: Started Network Manager Script Dispatcher Service.
Apr 26 17:13:25 localhost dockerd-current: time="2018-04-26T17:13:25.353148630+08:00" level=warning msg="failed to retrieve docker-runc version: unknown output format: runc version 1.0.0-rc2\nspec: 1.0.0-rc2-dev\n"
Apr 26 17:13:25 localhost dockerd-current: time="2018-04-26T17:13:25.353229032+08:00" level=warning msg="failed to retrieve docker-init version"
Apr 26 17:20:01 localhost systemd: Started Session 193 of user root.
Apr 26 17:20:01 localhost systemd: Starting Session 193 of user root.
Apr 26 17:30:01 localhost systemd: Started Session 194 of user root.
Apr 26 17:30:01 localhost systemd: Starting Session 194 of user root.
Apr 26 17:40:01 localhost systemd: Started Session 195 of user root.
Apr 26 17:40:01 localhost systemd: Starting Session 195 of user root.

I also encountered this problem. I want to know if this log is influential.
[root@10-0-5-106 ~]# docker version
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: <unknown>
 Go version:      go1.8.3
 Git commit:      774336d/1.13.1
 Built:           Wed Mar  7 17:06:16 2018
 OS/Arch:         linux/amd64
 Experimental:    false

[root@10-0-5-106 ~]# docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Init Binary: docker-init
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 40
Total Memory: 125.6 GiB
Name: 10-0-5-106
ID: 7GOO:6WKZ:YDIC:SAGM:WLLH:DQMC:BZSX:B4WC:TKIV:VHDS:WQP4:7LP2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

**Comment by thaJeztah** [comment]
@sumeng001 looks like you're running a (very old) version of the Red Hat fork of Docker; Docker 1.13 has reached end of life a year ago, and the Red Hat fork is not maintained in this repository (issues with that version of Docker have to be reported with Red Hat).

If you install a current version of the official Docker packages, that issue should be resolved.
