### ISSUE TITLE
[1.13 swarm] image column in `service ps` and `docker ps` shows full digest

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#28502]
When doing a `docker service ps` or a `docker ps`, the image column now shows the full image digest rather than the image name the user specified... it's also quite long and makes the output pretty unbearable to use.

**Comment by aaronlehmann** [comment]
cc @nishanttotla

**Comment by nishanttotla** [comment]
@cpuguy83 This is currently being fixed, along with other items relevant to pin by digest, specified here: https://github.com/docker/docker/pull/28173#issuecomment-259762062
