### ISSUE TITLE
Sigusr1 generates huge files

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#28517]
#27331 added daemon-data logging on `sigusr1` (in addition to printing stacktraces).

In linux this file contains a lot of useless information, for example array of 65536 IP addresses. While we can use this file to figure out where to cut allocations the current form doesn't help debugging actual problems and makes is harder for users to send us these files.

For empty daemon this file contains 102297 lines and is `6.3MB`.
As soon as swarm mode is enabled the file had `8312739` lines, `731MB` and took 14 seconds to generate(plus shows some proto warnings). I'd assume it contains CA keys when swarm is not locked.

**Comment by tonistiigi** [comment]
Setting to `P1` as #27331 is in `v1.13` and `700MB` seems something that definitely needs to be resolved.

@jhowardmsft @thaJeztah

**Comment by aaronlehmann** [comment]
A few findings from a dump with swarm mode enabled...

- The WAL writer has a 1 MB buffer, which might be a bit excessive
- This serialization does not deduplicate complex objects that were already referenced somewhere else. This seems to cause a lot of output bloat in swarm mode. For example, every structure that has a reference to the memory store causes the entire store to be dumped.

**Comment by jhowardmsft** [comment]
Hmmm. Open to suggestions. Revert it for Linux in rc2? The files are much smaller on Windows that I've seen. However is this really P1? How often are dumps triggered by normal users? I do want add though that this HAS been useful debugging Windows dumps.

**Comment by aaronlehmann** [comment]
Perhaps we could stream the dump through a compressor and write a compressed version to disk? With the example I generated, gzipping it reduces it from 700 MB to 28 MB.

**Comment by thaJeztah** [comment]
we sometimes ask users for debugging; 700+ MB sounds like a risk if it results in a manager running out of disk (perhaps i'm overthinking)

**Comment by thaJeztah** [comment]
so P1 is reasonable just so we don't release before deciding (whichever direction)

**Comment by cpuguy83** [comment]
In addition to compression, maybe we only dump the spew logs when the daemon is in debug mode?

**Comment by cpuguy83** [comment]
Or move it to SIGUSR2

**Comment by tonistiigi** [comment]
Even uncompressed, with over 8 million lines of text it's impossible to even understand what is in this file, moreover understand if the state of the file points to a problem. If the issue is inefficient dumping with lots of duplicates we should improve that, probably together with blacklisting lots of things(looking at that 65536 lines of IPs that first caught my eye).

To me, we could also start by just dumping the containers/images data. Then over time when debugging issues we could see what more info would have been useful and extend it.

**Comment by cpuguy83** [comment]
Opened #28551 which reduces what we're dumping.
