### ISSUE TITLE
RFE: Please fix the Flakey GPG Key Import Fails

### ISSUE THREAD

**Issue by todd-dsm** [docker/docker#28510]
# Description
Occasionally, the GPG keys fail to be imported. 

The Docker GPG keys fail to import during an Packer build. With a little Googling this problem seems widespread.  I've seen mention of this with variant conditions all with the same result. I don't believe this is a Packer problem as much as that Packer exposes the issue early in the OS install process and therefore seems to be related. 

This behavior seems random but I've isolated at least 1 aspect of the error, [dash][2]. Since Packer executes all scripts defined in `"provisioners"` with `sudo` root is the user executing them. On inspection, the root user - by default - uses `sh` to execute; `/bin/sh` is a softlink `dash`. It's worth mentioning:
  * dash is only invoked at this early stage because it is the result of a process, not initiated by a user after login. 
  * **_after login_** users have a proper bash shell
  * dash is a POSIX-compliant shell so this should not happen.

However, there may be other causes for the same/similar failures.

## TEST Steps: a failed run
1. [Download][3] Packer and install it
2. [Download][4] VirtualBox and install it
3. git clone git@github.com:chef/bento.git
4. Edit: debian-8.6-amd64.json; search for  "scripts":
5. Add [scripts/common/autoprep.sh][5] after `"scripts/common/metadata.sh",`
6. Add [scripts/debian/inst-docker.sh][6] after `"scripts/debian/update.sh",`
7. Run the automation: `packer build --only=virtualbox-iso debian-8.6-amd64.json`
8. The build will fail while attempting to pull the docker GPG key:

## Actual Results
```bash
    virtualbox-iso: + apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.tCXkthl6S4 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
    virtualbox-iso: ?: [fd 4]: read error: Connection reset by peer
    virtualbox-iso: gpgkeys: key 58118E89F3A912897C070ADBF76221572C52609D partially retrieved (probably corrupt)
    virtualbox-iso: gpg: no valid OpenPGP data found.
    virtualbox-iso: gpg: key 2C52609D: no valid user IDs
    virtualbox-iso: gpg: this may be caused by a missing self-signature
    virtualbox-iso: gpg: Total number processed: 1
    virtualbox-iso: gpg:           w/o user IDs: 1
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Script exited with non-zero exit status: 2
```

## TEST Steps: a successful run
1. Edit `scripts/common/autoprep.sh`; uncomment Lines 16-19.
2. Tell the Debian installer to set the dash boolean to false in `http/debian-8/preseed.cfg`; e.g.:
```bash
...
  /usr/lib/pre-pkgsel.d/20install-hwpackages                                       
d-i dash dash/sh boolean false    # just add this line between these existing ones, without this comment
d-i time/zone string UTC                                                           
...
```
3. Re-run the automation. 

## Expected Results

```bash
...
    virtualbox-iso: + apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.RgYU2mnHa6 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-squeeze-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    virtualbox-iso: gpg: requesting key 2C52609D from hkp server p80.pool.sks-keyservers.net
    virtualbox-iso: ?: [fd 4]: read error: Connection reset by peer
    virtualbox-iso: gpg: key 2C52609D: public key "Docker Release Tool (releasedocker) <docker@docker.com>" imported
    virtualbox-iso: gpg: Total number processed: 1
    virtualbox-iso: gpg:               imported: 1  (RSA: 1)
    virtualbox-iso: + apt-get update
    virtualbox-iso: Hit http://security.debian.org jessie/updates InRelease
    virtualbox-iso: Hit http://security.debian.org jessie/updates/main Sources
...
```

### Additional Info
I have not had the time for root-cause analysis and likely won't. My feeling is that the key is not being presented/distributed in a way that a purely POSIX-compliant interpreter (dash) can properly process it. These findings will be left to your engineers to decide their value and take the required action.

Being adherent to the POSIX requirements _is_ the method of guaranteeing proper transaction results.  I'm quite certain the Debian engineers examine and select packages meticulously and that baking-in something like dash was very attractive because of its POSIX conformity. FWIW, those guys are hardened psychos that only see the world in this pure form; and I'm happy they do it. 

This is why it's my _"feeling"_. 

**Output of `docker version`:**

```bash
$ docker --version
Docker version 1.12.3, build 6b644ec
```

**Output of `docker info`:**

```
$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.4 MiB
Name: debian-8
ID: RWJ4:ETMG:XCFD:RDIC:7IXA:5UTJ:GF67:SHRU:3F6H:GTW5:CVWD:YUYW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Based on the nature of the issue the results should be consistent regardless of the environment.

[1]: https://www.packer.io/
[2]: https://wiki.ubuntu.com/DashAsBinSh/Spec
[3]: https://www.packer.io/downloads.html
[4]: https://www.virtualbox.org/wiki/Downloads
[5]: https://gist.github.com/todd-dsm/f9f542e8878cb4574fad3db026c16e7d
[6]: https://gist.github.com/todd-dsm/81346267264c9b221186946ba12dd5d7

**Comment by thaJeztah** [comment]
This may be related to an interruption in the keyserver that was attempted to download the key from. Unfortunately, this happens occasionally; it's worth trying to add alternative key servers to the script, as was done in the install script on get.docker.com; https://github.com/docker/docker/blob/v1.12.3/hack/install.sh#L31-L35

**Comment by todd-dsm** [comment]
I have run into the problem that you describe. On successful runs a few fail occasionally.

However, using the provided process gets the same result consistently. In the case of dash, fail=true 100%.

**Comment by thaJeztah** [comment]
The error causing the issue most likely is;

```
virtualbox-iso: ?: [fd 4]: read error: Connection reset by peer
```

Actually, wondering if this relates to the VirtualBox bug discussed in https://github.com/docker/docker/issues/27734 (https://www.virtualbox.org/ticket/16084)

**Comment by todd-dsm** [comment]
As stated, this is 1 aspect of the problem; there are undoubtedly more. Run the test steps as presented and you'll see that there is a method that does work around the error with the same exact version of VirtualBox and it's repeatable.

**Comment by thaJeztah** [comment]
I'm not sure if there's anything we can fix here; these are regular key servers, widely in use (not just by docker). Outage of those servers cannot be prevented by us, and we can only take outages into account (as was done in the install script)

**Comment by harrybvp** [comment]
Downgrading Virtual Box from 5.1.8 (latest release) to 5.1.6 seems to fix the issue.
Issue has been described in https://www.virtualbox.org/ticket/16084
