### ISSUE TITLE
driver name: if driver is specified name is required

### ISSUE THREAD

**Issue by friism** [docker/docker#28528]
I think there's a 1.13.0-rc1 (client) / 1.12.3 (server) incompatibility.

**Steps to reproduce the issue:**

1. `docker deploy --bundle-file .\iv.dab iv`

**Describe the results you received:**

Loading bundle from .\iv.dab
Creating network iv_back-tier
Error response from daemon: rpc error: code = 3 desc = driver name: if driver is specified name is required

**Describe the results you expected:**

DAB file deployed

**Additional information you deem important (e.g. issue happens only occasionally):**

This works with 1.12.3 client

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.24 (downgraded from 1.25)
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 22:32:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.12.3
 API version:         1.24
 Minimum API version:
 Go version:          go1.6.3
 Git commit:          6b644ec
 Built:               Thu Oct 27 00:09:21 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running Windows client and Docker for AWS.

DAB file below:

```
{
  "services": {
    "db": {
      "Image": "postgres@sha256:f76245b04ddbcebab5bb6c28e76947f49222c99fec4aadb0bb1c24821a9e83ef", 
      "Networks": [
        "back-tier"
      ]
    }, 
    "redis": {
      "Image": "redis@sha256:2e75b1750a11e1bb060b3af6a80f8f5c536a2b16bc85c02e006ffc2f93ec8ba6", 
      "Networks": [
        "back-tier"
      ], 
      "Ports": [
        {
          "Port": 6379, 
          "Protocol": "tcp"
        }
      ]
    }, 
    "result": {
      "Image": "docker4x/demo-result@sha256:9932a45ccc04447430659acb88243ddf3ff207efc8cd28f6cda03da0c9d4a426", 
      "Networks": [
        "front-tier", 
        "back-tier"
      ], 
      "Ports": [
        {
          "Port": 80, 
          "Protocol": "tcp"
        }
      ]
    }, 
    "vote": {
      "Image": "docker4x/demo-vote@sha256:c961faf9a715176f09fe10104fd763b96cf8341d274031cf477b0dfd1fe2af32", 
      "Networks": [
        "front-tier", 
        "back-tier"
      ], 
      "Ports": [
        {
          "Port": 80, 
          "Protocol": "tcp"
        }
      ]
    }, 
    "worker": {
      "Image": "docker4x/demo-worker@sha256:df16d85fba95eef19d2d53f1ee5367c22aa4956fab0977ed9a187d69ec15dab0", 
      "Networks": [
        "back-tier"
      ]
    }
  }, 
  "version": "0.1"
}
```

cc @vieux @mavenugo

**Comment by yashgt** [comment]
The docker engine was 1.12 and the docker command was of 1.13. Possibly this caused the issue. I installed 1.13 fresh and it it now working fine. Sorry about the trouble.

**Comment by AkihiroSuda** [comment]
@vdemeester 
Can we close this issue? Or should we try to fix this?
As DAB is still experimental feature, IMO incompatibility here is not critical

**Comment by thaJeztah** [comment]
I think we should look into this; docker 1.13 should support using a newer version of the client with an older version of the daemon.

Although "experimental" features by themselves are not supported cross-version, see https://github.com/docker/docker/issues/28655, this looks like API 1.24 on a 1.12 daemon is not the same as API 1.24 on a 1.13 daemon.

This error is related to https://github.com/docker/docker/issues/26580, https://github.com/docker/docker/issues/25735, and https://github.com/docker/engine-api/pull/372

**Comment by thaJeztah** [comment]
> this looks like API 1.24 on a 1.12 daemon is not the same as API 1.24 on a 1.13 daemon.

Sorry, just realized that's not necessarily the case; as it will use API 1.25 in the "1.13 + 1.13" situation. Still we should check if this only affects `.dab` or also other features (i.e. are we creating the right requests for the right API version).

**Comment by yogiGueta** [comment]
I have the same issu (i'm trying to define a static IP address for container):
Error response from daemon: rpc error: code = 3 desc = driver name: if driver is specified name is required.
**My version is:**

Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:55:47 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:55:47 2016
 OS/Arch:      linux/amd64
 Experimental: true

**My compose file is (i'm using docker stacks):**
networks:
  default_network:
    driver: overlay
    ipam:
      config:
      - subnet: 10.5.0.0/16
        gateway: 10.5.0.1
