### ISSUE TITLE
compose on swarm: update parallelism needs better default

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#28520]
If I don't specify an `update_config` in my compose file, I get the defaults, which is great.

If I specify something like this:

```
     deploy:
       update_config:
         failure_action: pause
```

...then I get an `UpdateConfig` in the service, but the other fields are initialized to 0. For `Parallelism`, this is inconsistent with the CLI, where it defaults to 1.

I believe the other fields in `UpdateConfig` are handled correctly. `RestartConfig` and other structs also look okay.

cc @dnephin @vdemeester @aluzzardi

**Comment by dnephin** [comment]
I guess we need to use a pointer for parallelism to determine if it's set to 0 or not set.
