### ISSUE TITLE
empty cgroups left behind

### ISSUE THREAD

**Issue by guoshimin** [docker/docker#28522]
**Description**

**Steps to reproduce the issue:**
I don't have specific steps to reproduce, but we have a kubernetes cluster of around 20 nodes, and the nodes have been running for 1-3 months. Most of the nodes are exhibiting the problem.

**Describe the results you received:**
There are cgroups created by docker that contain 0 processes. The cgroups look like `/sys/fs/cgroup/devices/system.slice/docker-122fb452a2062d6305e6c18fe9e2996ca96082f25fbd24304d4c5387ed1e1611.scope`, and the file `cgroup.procs` inside them is empty.

**Describe the results you expected:**
Cgroups that are no longer in use are deleted.

**Additional information you deem important (e.g. issue happens only occasionally):**
We are running Kubernetes 1.3.8 on CoreOS v899 nodes. We are also hitting the problem described in https://github.com/docker/docker/issues/5618.

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   4419fdb-dirty
 Built:        Fri Dec 18 00:01:03 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 382
Images: 1736
Server Version: 1.9.1
Storage Driver: overlay
 Backing Filesystem: extfs
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.3.3-coreos
Operating System: CoreOS 899.1.0
CPUs: 16
Total Memory: 62.91 GiB
Name: ip-10-20-8-66.us-west-2.compute.internal
ID: MX3R:IWX4:7JRC:JKR6:JBNV:CWAV:5AVU:233B:5AJ7:REFQ:GUBM:E6EN
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by thaJeztah** [comment]
Can you report this issue with CoreOS? This version of Docker is built by them, and contains code changes that are not in our code base, so we cannot help with that.

I'll close this issue here, but feel free to comment after
