### ISSUE TITLE
docker configurate file not found， why？

### ISSUE THREAD

**Issue by 467754239** [docker/docker#28542]
/etc/default/docker and /etc/sysconfig/docker  not found in local system

[root@zhengyscn ~]# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core) 
[root@zhengyscn ~]# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

[root@zhengyscn ~]# ll /etc/default/docker 
ls: cannot access /etc/default/docker: No such file or directory
[root@zhengyscn ~]# ll /etc/sysconfig/docker
ls: cannot access /etc/sysconfig/docker: No such file or directory

**Comment by vdemeester** [comment]
@467754239 I think Centos 7.2 use systemd and thus uses systemd unit files. See https://docs.docker.com/engine/admin/systemd/ for the documentation about it :angel:
