### ISSUE TITLE
SELinux regression, bind mounts, 1.10 to 1.12

### ISSUE THREAD

**Issue by edsantiago** [docker/docker#28568]
Forked from #27773 ; please see there for reproducer script and data.

The principal bug (`read error: Is a directory`) seems fixed, but there's a new SELinux AVC:

    + docker volume create --name v1
    v1
    + docker create --name t1 -v v1:/.imagebuilder-transient-mount busybox
    5971d5ed971e4413ac146e9562b2fd57687bdc3b0425ce276166e71abe346675
    + cat a.tar
    + docker cp - t1:/
    + cat b.tar
    + docker cp - t1:/
    ++ docker volume inspect -f '{{ .Mountpoint }}' v1
    + mp=/var/lib/docker/volumes/v1/_data
    + docker create --name t2 -v /var/lib/docker/volumes/v1/_data/0:/mountdir -v /var/lib/docker/volumes/v1/_data/1:/mountfile busybox cat /mountfile
    a2d2799dba144a12484b6357981bbf6f341865fd5101557a53d8da81fc086e15
    + ls -lZR /var/lib/docker/volumes/v1/_data
    /var/lib/docker/volumes/v1/_data:
    drwxr-xr-x. root root system_u:object_r:container_var_lib_t:s0 0
    -rw-r--r--. root root system_u:object_r:container_var_lib_t:s0 1

    /var/lib/docker/volumes/v1/_data/0:
    -rw-r--r--. root root system_u:object_r:container_var_lib_t:s0 Dockerfile
    -rw-r--r--. root root system_u:object_r:container_var_lib_t:s0 file
    drwxr-xr-x. root root system_u:object_r:container_var_lib_t:s0 subdir

    /var/lib/docker/volumes/v1/_data/0/subdir:
    -rw-r--r--. root root system_u:object_r:container_var_lib_t:s0 file2

    + docker start -a t2
    cat: can't open '/mountfile': Permission denied

    # grep -2 AVC /var/log/audit/audit.log
    type=NETFILTER_CFG msg=audit(1479436145.586:10341): table=nat family=10 entries=0
    type=SYSCALL msg=audit(1479436145.586:10341): arch=c000003e syscall=56 success=yes exit=12300 a0=6c028011 a1=7ffe0bb24360 a2=7ffe0bb25490 a3=0 items=0 ppid=12290 pid=12299 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="exe" exe="/usr/libexec/docker/docker-runc" subj=system_u:system_r:container_runtime_t:s0 key=(null)
    type=AVC msg=audit(1479436145.698:10342): avc:  denied  { read } for  pid=12300 comm="cat" name="1" dev="vda1" ino=29369739 scontext=system_u:system_r:svirt_lxc_net_t:s0:c17,c911 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=file
    type=SYSCALL msg=audit(1479436145.698:10342): arch=c000003e syscall=2 success=no exit=-13 a0=7ffe657a8f81 a1=0 a2=0 a3=6fac70 items=0 ppid=12282 pid=12300 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="cat" exe="/bin/cat" subj=system_u:system_r:svirt_lxc_net_t:s0:c17,c911 key=(null)
    type=ANOM_PROMISCUOUS msg=audit(1479436145.736:10343): dev=veth405a9f1 prom=0 old_prom=256 auid=4294967295 uid=0 gid=0 ses=4294967295

```
# rpm -qa|egrep 'docker|container-se'|sort
container-selinux-1.12.3-8.el7.x86_64
docker-1.12.3-8.el7.x86_64
docker-common-1.12.3-8.el7.x86_64
docker-rhel-push-plugin-1.12.3-8.el7.x86_64
docker-selinux-1.10.3-57.el7.x86_64
python-docker-py-1.9.0-1.el7.noarch
```

```
# docker info                                                                                      Containers: 2                                                                                                                 Running: 0                                                                                                                   Paused: 0                                                                                                                    Stopped: 2
Images: 5
Server Version: 1.12.3
Storage Driver: devicemapper                                                                                                  Pool Name: vg--docker-docker--pool                                                                                           Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB                                                                                                   Backing Filesystem: xfs
 Data file:                                                                                                                   Metadata file:                                                                                                               Data Space Used: 1.917 GB                                                                                                    Data Space Total: 4.287 GB                                                                                                   Data Space Available: 2.37 GB
 Metadata Space Used: 630.8 kB
 Metadata Space Total: 12.58 MB
 Metadata Space Available: 11.95 MB
 Thin Pool Minimum Free Space: 428.3 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: bridge null host overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Employee SKU
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 3.702 GiB
Name: esm-rhel7-d12-2.localdomain
ID: G6HE:BDTU:7SWY:WSA3:APKT:LROE:JRAN:G5YT:WBDJ:SO5E:4PR6:4JIM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://registry.access.redhat.com/v1/
Insecure Registries:
 127.0.0.0/8
Registries: registry.access.redhat.com (secure), docker.io (secure)
```

**Comment by edsantiago** [comment]
@rhatdan @cpuguy83

**Comment by thaJeztah** [comment]
Are you only seeing this problem with the Red Hat version of docker, or also with a vanilla version?

**Comment by edsantiago** [comment]
I only have access to the Red Hat build.

**Comment by edsantiago** [comment]
Per @rhatdan on the original issue:

>The 1.12 version is the correct behaviour.

**Comment by anassahmed** [comment]
This issue affects me when creating a *named* volume under Fedora 25. normal volumes (that gets created with containers) don't break!

Link to RHBZ Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1401260
