### ISSUE TITLE
Support to identify hostPort inside the Docker Container via ENV variables

### ISSUE THREAD

**Issue by AjitDas** [docker/docker#28574]
For example I am running a Docker container (within AWS ECS ) which allocates dynamic ports (by specifying servicePort=0), inside my container I need to know the actual hostPort it bounded to.

I would need host and port information, I could get the host (both public & private) information using 'ec2-instance-metadata' but there is no equivalent information to get the port.

In short we need something like this inside the container, outside of container we can get information from docker host like this 'docker inspect --format='{{(index (index .NetworkSettings.Ports "8080/tcp") 0).HostPort}}' CONTAINER_NAME'.

Other platform (like mesosphere etc) have a way ( ex $PORT_8080) to inspect this info, but AWS doesn't have it.

**Comment by thaJeztah** [comment]
Container introspection has come up quite a few times (see, e.g. https://github.com/docker/docker/issues/8427), and is still something on the list of things to tackle. Setting an environment variable may not be the best solution here. Random port assignments can be both _dynamic_ (i.e., it's possible ports change during a restart of the container), and can have multiple values, for example:

```
docker run -d -p 80 -p 80 -p 8080:80 -p 8081:80 --name foo nginx:alpine

docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                               NAMES
56248fcaae63        nginx:alpine        "nginx -g 'daemon off"   5 seconds ago       Up 4 seconds        443/tcp, 0.0.0.0:8080->80/tcp, 0.0.0.0:8081->80/tcp, 0.0.0.0:32768->80/tcp, 0.0.0.0:32769->80/tcp   foo
```

There is a PR currently being discussed that would bring an introspection API, and would allow obtaining this information from inside the container, see https://github.com/docker/docker/pull/26331

**Comment by AjitDas** [comment]
@thaJeztah good point about the random ports with multiple values, container inspection is what need of the hour, I couldn't find any mention on port inspection in #26331 hopefully it will include the hostPort inspection as well. ENV variable is also not bad option (something similar what is provided as part of container linking) if we can set multiple values (comma separated or json) that can be available inside container.

**Comment by AkihiroSuda** [comment]
@AjitDas #26331 does not include the hostPort yet, but we can incrementally add such features :+1:

**Comment by melo** [comment]
Maybe we should fold this ticket into #3778... Covers the same concept.

**Comment by thaJeztah** [comment]
Good suggestion; lets move this to https://github.com/docker/docker/issues/3778 to keep the discussion central
