### ISSUE TITLE
USER in Windows Container. How to change user with password?

### ISSUE THREAD

**Issue by soanni** [docker/docker#28585]
Hi docker team. I opened this issue as a follow up for https://github.com/docker/docker/pull/28415 and https://github.com/docker/docker/issues/28027.

Tested USER functionality on this build
```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   27699ba
 Built:        Fri Nov 18 05:45:33 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          27699ba
 Built:               Fri Nov 18 05:45:33 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```
if i'm adding user without password i'm able to switch user
```
FROM microsoft/windowsservercore:latest

RUN NET USER sp_farm /add
RUN NET LOCALGROUP Administrators /add sp_farm

USER sp_farm
SHELL ["powershell"]
RUN whoami
```
but if i'm adding user with password i got the error. Or i need to start-process powershell and provide PSCredentials object. It's not clear how i can do it in Dockerfile during image build.
```
FROM microsoft/windowsservercore:latest

RUN NET USER sp_farm "Password1234" /add
RUN NET LOCALGROUP Administrators /add sp_farm

USER sp_farm
SHELL ["powershell"]
RUN whoami
```
![image](https://cloud.githubusercontent.com/assets/5715840/20429985/3f7de10c-adab-11e6-8034-474e77d823a0.png)

**Comment by soanni** [comment]
i tried this. created 2 users - one with password another without password. I'm switching first to the one without password, and can see that whoami gives me the correct user name. then under this user i'm trying to run elevated powershell with 'runas' under another user with password. I'm getting the same error that i've already seen when i tried to do the same under ContainerAdministrator. I described the error in https://github.com/docker/docker/issues/28027.

My dockerfile

`FROM microsoft/windowsservercore:latest

COPY "." /
# add sp_farm user, add him to Administrators group

RUN NET USER my_admin /add
RUN	NET LOCALGROUP Administrators /add my_admin

RUN NET USER sp_farm "Password" /add
RUN	NET LOCALGROUP Administrators /add sp_farm

USER my_admin
RUN whoami
RUN powershell c:\script.ps1`

script.ps1
`
$pw = convertto-securestring "Password" -asplaintext -force;

$pinfo = New-Object System.Diagnostics.ProcessStartInfo
$pinfo.FileName = "whoami"
$pinfo.RedirectStandardError = $true
$pinfo.RedirectStandardOutput = $true
$pinfo.UseShellExecute = $false
$pinfo.CreateNoWindow = $true;
$pinfo.Verb = "runas";
$pinfo.Arguments = "";
$pinfo.UserName = "sp_farm";
#$pinfo.Domain = "nextdocs"
$pinfo.Password = $pw

$p = New-Object System.Diagnostics.Process
$p.StartInfo = $pinfo
$p.Start() | Out-Null
$stdout = $p.StandardOutput.ReadToEnd()
$stderr = $p.StandardError.ReadToEnd()
$p.WaitForExit()
Write-Host "stdout: $stdout"
Write-Host "stderr: $stderr"
Write-Host "exit code: " + $p.ExitCode
`

**Comment by soanni** [comment]
hi team, could you please tell me any updates on this?

**Comment by fntlnz** [comment]
ping @jhowardmsft  @johnstep

**Comment by jhowardmsft** [comment]
Unfortunately there's no support in the platform for this so it won't work. In recent client flights, the ability to run as "NT Authority\System" was added, but no support for passing passwords into HCS.
 
@patricklang - you might want to track this internally.

**Comment by artisticcheese** [comment]
@jhowardmsft How did you specify for docker to use "NT Authority\System"?

**Comment by jhowardmsft** [comment]
eg `docker run --user "NT AUTHORITY\SYSTEM"...`

You will need an RS2 build for it to work, so that means client only AFAIK for public releases and flights. Server is RS1 still.

**Comment by JannikMichel123** [comment]
Hey, are there any Update on this?

**Comment by khaffner** [comment]
I want to run a windowsservercore container as the SYSTEM account as @jhowardmsft commented above, it does not work for me:
`docker run --rm -it microsoft/windowsservercore --user "NT AUTHORITY\SYSTEM"`
`C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container a7e52a4a75784e3d79e0fcac144d31c2f94f5c3c3649aeb612995d9fc43bc0be encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"--user \"NT AUTHORITY\\SYSTEM\"","WorkingDirectory":"C:\\","EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[72,271]}.`

What am I doing wrong?

**Comment by darstahl** [comment]
@khaffner Put the `--user "NT AUTHORITY\SYSTEM"` parameter prior to the container image name. By putting it after the name, Docker interprets it as a commandline to call in the container, hence it is unable to find the file `--user` file to execute.

**Comment by khaffner** [comment]
Thanks @darstahl, that worked! :)

**Comment by JuanPerezActivus** [comment]
I am still having similar issue as the one described on this thread. 
I tried different combinations including using a docker file and within: creating a local user, set its password, set the newly created account to not expire, added it to local admins group.. all successful when running the build, but when I tried to run the container via docker file USER statement the result is the same

Using as example the _NT AUTHORITY\SYSTEM_ account got the same result
<
D:\docker\dockerfiles> **_docker run --user "NT AUTHORITY\SYSTEM" -it 2016coreoracle cmd_**
**C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container 39ac286cc84f6aba95540860966acc3c3110cc7ad42447cf052480ebfec9846f encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)**
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"cmd","User":"NT AUTHORITY\\SYSTEM","WorkingDirectory":"C:\\","EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[59,203]}.
> 

< 
PS D:\docker\dockerfiles> **_docker run --user "NT AUTHORITY\SYSTEM" -it 2016coreoracle_**
**C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: container edfa1e9ead7ba04b24f012ce8cd4d5558e64a50c58b68f4c8df001a3194f24e3 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)**
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"c:\\windows\\system32\\cmd.exe","User":"NT AUTHORITY\\SYSTEM","WorkingDirectory":"C:\\","EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[59,203]}.
PS D:\docker\dockerfiles>
>
 
Tried to run it with the account created when executing the build via dockerfile, same result
<
PS D:\docker\dockerfiles> **_docker run --user oracledbuser -t 2016coreoracle_**
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: **Error response from daemon: container 4415372e7b375e767d7c0e2e1a94a2416349dc85a4220d7beffa970f16b3ed76 encountered an error during CreateProcess: failure in a Windows system call: The user name or password is incorrect. (0x52e)**
[Event Detail:  Provider: 00000000-0000-0000-0000-000000000000] extra info: {"CommandLine":"c:\\windows\\system32\\cmd.exe","User":"oracledbuser","WorkingDirectory":"C:\\","EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"ConsoleSize":[59,203]}.
PS D:\docker\dockerfiles>
>

**Comment by andyfisher100** [comment]
is there still no way of creating a new user with a password and then switching to that user? just seems basic stuff to secure a container image

**Comment by jhowardmsft** [comment]
@andyfisher100 No, this is not possible. It would require support from the platform as it doesn't support starting a container with user+password. I can start a conversation with kernel folks or program management team if you feel that is an important scenario.

**Comment by andyfisher100** [comment]
> @andyfisher100 No, this is not possible. It would require support from the platform as it doesn't support starting a container with user+password. I can start a conversation with kernel folks or program management team if you feel that is an important scenario.

Im not sure. Im just looking for the best way to secure a windows container, it seemed to be by creating a user with a known password. Would be nice if the USER command also took a password or something. maybe you have some reference material about the best way of securing a windows container?

**Comment by Amlys** [comment]
> @andyfisher100 No, this is not possible. It would require support from the platform as it doesn't support starting a container with user+password. I can start a conversation with kernel folks or program management team if you feel that is an important scenario.

It's very important for me and customers of my company to create a container from our image with the same user as current user in the host. Please, can you tell me if it's possible to have a solution for this ?

**Comment by JasonNoonan** [comment]
Especially with the mcr.microsoft.com/windows:1809 and 1903 images supporting full GUI applications for automated testing, being able to run as a specific user, or use a specific user inside of the container with a known password is important to me.

**Comment by BMOD89** [comment]
Is it possible to change the user name while the container is running? I tried the Rename-LocalUser command but whoami still shows the previous user name.

**Comment by muniprakash2b9** [comment]
Do we have any other way to create user and execute exe file with same user. Does Seevercorr images support UAC?

**Comment by ShazlyAbozeid** [comment]
i have  a  problem with   assigning   admin  user to service  inside the container 
any idea please?

**Comment by ShazlyAbozeid** [comment]
here is the command for build
docker build -t db . 
here is the command for run
docker run -it --name Test3  -v C:\Container\DBShared:c:\Sharedfolder\ --entrypoint powershell db:latest


and need to install SQL services with assigning for it the admin  user 

any help

**Comment by SumBeast** [comment]
For me the firewall was the issue.

**Comment by ritikaguptams** [comment]
> For me the firewall was the issue.

How did you fix this ?
