### ISSUE TITLE
[1.13] `docker build` failed if there is a comment line in the multi-line RUN statements

### ISSUE THREAD

**Issue by twang2218** [docker/docker#28587]
**Description**

I ran into a problem that some of my `Dockerfile` cannot be built under new Docker 1.13.0-rc1. I found it might caused by a comment line in the `RUN` statement.

**Steps to reproduce the issue:**

First, create a `Dockerfile` with the following content:

```Dockerfile
FROM ubuntu:latest
RUN echo "hello" > /root/article.txt \
# A comment line
    && echo "world" >> /root/article.txt
```

The `RUN` statement is a multi-line command, using `\` at the end of each line, and a comment line is in the between of those lines.

**Describe the results you received:**

Try to build the image

```bash
$ docker --version
Docker version 1.13.0-rc1, build 75fd88b

$ docker build -t testimage .
Sending build context to Docker daemon 4.096 kB
Error response from daemon: Unknown instruction: &&
```

Then I got an error: `Unknown instruction: &&`.

**Describe the results you expected:**

However, it's used to be ok. If I build this `Dockerfile` under Docker 1.12, everything is ok:

```bash
$ docker --version
Docker version 1.12.3, build 6b644ec

$ docker build -t testimage .
Sending build context to Docker daemon 4.096 kB
Step 1 : FROM ubuntu:latest
latest: Pulling from library/ubuntu
aed15891ba52: Pull complete
773ae8583d14: Pull complete
d1d48771f782: Pull complete
cd3d6cd6c0cf: Pull complete
8ff6f8a9120c: Pull complete
Digest: sha256:35bc48a1ca97c3971611dc4662d08d131869daa692acb281c7e9e052924e38b1
Status: Downloaded newer image for ubuntu:latest
 ---> e4415b714b62
Step 2 : RUN echo "hello" > /root/article.txt     && echo "world" >> /root/article.txt
 ---> Running in 586405a87df6
 ---> cccb2f193a86
Removing intermediate container 586405a87df6
Successfully built cccb2f193a86
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 24
 Running: 3
 Paused: 0
 Stopped: 21
Images: 31
Server Version: 1.13.0-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: fluentd
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: d1
ID: M7VK:YNAL:VPTV:T5CX:CAS3:W7WX:WT6E:3PVE:GOBD:TQKT:MJLT:5K7C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The test environment is a Digital Ocean Ubuntu 16.04 droplet.

**Comment by duglin** [comment]
This change was done on purpose to more closely align with how scripts work. For example:
```
echo hello \
# ignore 
  world
```
generates an error because "world" isn't added to after "hello". IMO, the old behavior as a mistake.

**Comment by duglin** [comment]
Closing since this was an intentional change.

**Comment by twang2218** [comment]
@duglin Could you redirect me to the docs of the change? Thanks.

**Comment by duglin** [comment]
@twang2218 in the docs the best I could find is, in
https://github.com/docker/docker/blob/master/docs/reference/builder.md
look for `Line continuation characters are not supported in comments.`

The PR that introduced this change is: https://github.com/docker/docker/pull/24725

**Comment by twang2218** [comment]
Got it, Thank you.

**Comment by tianon** [comment]
Oh man, this one's going to fun to communicate -- having comments in the middle of a really long `RUN` line is a _really_ common pattern in my experience. :sweat_smile:

**Comment by twang2218** [comment]
Yeah, I use the same pattern for comenting a long RUN, which is very common in Dockerfile if you follow the best practices, and it's quite useful. 😊 Now, I have to change every comment to 'echo', which doesn't make any sense as I use 'set -xe' already.😭

**Comment by thaJeztah** [comment]
Discussion continued in https://github.com/docker/docker/issues/29005

I'll lock this issue from commenting to prevent future "passers by" from commenting here, and the discussion being spread across too many issues
