### ISSUE TITLE
golint validation is not being enforced

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#28592]
In this build: https://jenkins.dockerproject.org/job/Docker-PRs/35557/consoleFull

```
20:50:04 Errors from golint:
20:50:04 daemon/cluster/convert/secret.go:43:1: exported function SecretReferencesFromGRPC should have comment or be unexported
20:50:04 
20:50:04 Please fix the above errors. You can test via "golint" and commit the result.
```

However the build is marked as successful. The failure of the `validate/lint` script does not cause the build to fail.

**Comment by vdemeester** [comment]
Gonna fix that :sweat_smile:

**Comment by yongtang** [comment]
`go vet` and `gofmt` may have issue as well #28538.

**Comment by vdemeester** [comment]
@yongtang yep, I'm making sure they all work back smoothely :angel:

**Comment by aaronlehmann** [comment]
Appears to be fixed now.

**Comment by LK4D4** [comment]
@vdemeester is it really fixed?

**Comment by vdemeester** [comment]
@LK4D4 I'll create a PR to prove it 😇
