### ISSUE TITLE
[1.13.0-rc1] experimental features are availabe in non-experimental mode

### ISSUE THREAD

**Issue by albers** [docker/docker#28621]
According to the [1.13.0-rc1  release notes](https://github.com/docker/docker/releases/tag/v1.13.0-rc1), `docker checkpoint` is experimental.
I would expect it to be unavailable if the daemon is running in non-experimental mode. But it _is_ available:

```bash
user@swarm1:~$ docker version
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:41:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:41:05 2016
 OS/Arch:             linux/amd64
 Experimental:        false
user@swarm1:~$ docker checkpoint

Usage:  docker checkpoint COMMAND

Manage checkpoints

Options:
      --help   Print usage

Commands:
  create      Create a checkpoint from a running container
  ls          List checkpoints for a container
  rm          Remove a checkpoint

Run 'docker checkpoint COMMAND --help' for more information on a command.
```

This is also valid for current HEAD of master (96f50e9b7087bad25cb38e2985c26b509be0c403)

**Comment by albers** [comment]
Other experimental features that are available in non-experimental mode:

- `docker deploy`
- `docker stack`

```bash
user@swarm1:~$ docker version | grep Experimental
 Experimental:        false
user@swarm1:~$ docker stack

Usage:  docker stack COMMAND

Manage Docker stacks

Options:
      --help   Print usage

Commands:
  ls          List stacks
  ps          List the tasks in the stack
  rm          Remove the stack
  services    List the services in the stack

Run 'docker stack COMMAND --help' for more information on a command.
user@swarm1:~$ docker deploy
"docker deploy" requires exactly 1 argument(s).
See 'docker deploy --help'.

Usage:  docker deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack
```

**Comment by albers** [comment]
Experimental features are hidden in help output unless the daemon is running in experimental mode (this is broken in RC1 but fixed in current HEAD). For consistency, these features should not be available to the user in non-experimental mode.

**Comment by thaJeztah** [comment]
I think these should be fixed through https://github.com/docker/docker/pull/28561, and  https://github.com/docker/docker/pull/28524, but I'm building master now to confirm

**Comment by albers** [comment]
With current head (96f50e9), it is broken, see above.

**Comment by thaJeztah** [comment]
> With current head (96f50e9), it is broken, see above.

Oh, missed that last line, apologies

**Comment by thaJeztah** [comment]
I can only partly reproduce this. These fail and give the correct message;

```
$ docker stack deploy foo
only supported with experimental daemon
$ docker stack
only supported with experimental daemon
$docker checkpoint
only supported with experimental daemon
```

The only exception is if the command is incorrect (i.e., missing parameters);

```
$ docker stack deploy
"docker stack deploy" requires exactly 1 argument(s).
See 'docker stack deploy --help'.

Usage:  docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack
```

I'm not sure we'd be able to fix that last one easily, because that validation takes place on the client, so doesn't trigger a check with the daemon.

ping @vieux any thoughts?

**Comment by thaJeztah** [comment]
This was on master 96f50e9

**Comment by albers** [comment]
Ah yes, you are right. The output was generated with the RC. On master, things are slightly different:
```bash
$ docker stack
only supported with experimental daemon
$ docker deploy
"docker deploy" requires exactly 1 argument(s).
[...]
```
So there is an inconsistency in error management.

**Comment by albers** [comment]
The intent of this PR was to report a problem in RC1 that I thought was still present in master.
It turned out that on master, we have a different problem. 
So I
- created #28626 to track the new problem
- close this issue because the problem in RC1 is resolved.

Thanks @thaJeztah for verifying and refining the error conditions.
