### ISSUE TITLE
[Feature request] Support filters for `docker plugin ls`

### ISSUE THREAD

**Issue by albers** [docker/docker#28624]
It would be nice to have something like `docker plugin ls --filter enabled=true`.
This would enable me to refine bash completion for `docker plugin enable` and `docker plugin disable` with official Docker CLI means.

**Comment by thaJeztah** [comment]
Agreed, I think that would be a good addition. Perhaps someone is interested in working on this, and contributing.

**Comment by albers** [comment]
I would also welcome a way to filter by plugin type: `--filter type=network|volume|authentication` (just like the grouping in output of `docker info`):
```bash
docker info
[...]
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
[...]
```

Usecase: I would like to include the plugins in completion for `docker {volume,network} create --driver` or `docker {volume,network} ls --filter driver=`. But as `docker plugin ls` retruns unspecific output, this is not feasable.

**Comment by albers** [comment]
@vdemeester added support for several filters before. Perhaps he is interested.

**Comment by yongtang** [comment]
Added a PR #28627 for `docker plugin ls --filter enabled=true`

**Comment by yongtang** [comment]
Oh I didn't notice the other comment about additional flags:
 `--filter type=network|volume|authentication`

Will update the PR.

**Comment by albers** [comment]
@yongtang Thanks a lot for providing this feature!
It works perfectly.
