### ISSUE TITLE
Can external machine look up the created secret?

### ISSUE THREAD

**Issue by ghostplant** [docker/docker#28620]
For something like: **echo hello | docker secret create test**

Is there a way to lookup the content of secret directly using docker instructions instread of running a node attaching the secret and running "**cat /run/secrets/test**" by "**docker exec**"?

**Comment by ghostplant** [comment]
If this is possible, then it can be used as a lite distributed k/v store and take place of etcd.

**Comment by thaJeztah** [comment]
No there's no such feature. The secrets functionality was designed for providing secrets to services / containers, not as a general purpose secrets store.
