### ISSUE TITLE
Docker deploy compose external network doesn't work

### ISSUE THREAD

**Issue by techninja1008** [docker/docker#28635]
When I `docker deploy` a compose file containing:

```
networks:
    webrouter_webtier:
        external: true
```

When I add it to a service under `networks:`, after inspecting the service it is never added to the service

**Steps to reproduce the issue:**

Explained above

**Describe the results you received:**

No webrouter_webtier on the service

**Describe the results you expected:**

webrouter_webtier on the service

**Additional information you deem important (e.g. issue happens only occasionally):**

Always happens, and I can see where and why it is happening in the code. I might create a PR if I have time.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc1
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   75fd88b
 Built:        Fri Nov 11 19:47:07 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc1
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          75fd88b
 Built:               Fri Nov 11 19:47:07 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

```
Containers: 130
 Running: 4
 Paused: 0
 Stopped: 126
Images: 296
Server Version: 1.13.0-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 914
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 8agsrahzgub7m48dr66508iuv
 Is Manager: true
 ClusterID: 9l3fu4qrystn2d4h5dgly9uhc
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.2.52
 Manager Addresses:
  192.168.2.52:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 8517738ba4b82aff5662c97ca4627e7e4d03b531
runc version: ac031b5bf1cc92239461125f4c1ffb760522bbf2
init version: N/A (expected: v0.13.0)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: docker-x86-1
ID: NKCQ:BOL4:6JUP:BUHD:LU46:KLAQ:FDKZ:VP7I:U5FN:VYDI:OS2J:SP3K
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical box running Ubuntu 16.04

**Comment by vdemeester** [comment]
This is even worse than that actually. Created a compose-file (https://github.com/vdemeester/break-all-the-thing/blob/master/compose-on-swarm/simple-network.yml) where I have 2 networks defined and 3 services. Each services are supposed to be on either one or the other but not on the default one.

But when doing `docker deploy --compose-file simple-network.yml ohnoes`, all containers are on the `default` network (i.e. `ohnoes_default`) and none are on the other network as defined in the compose file (`ohnoes_baz` and `ohnoes_bat` have no containers).

I'll take a look.
