### ISSUE TITLE
Windows 10: Docker does not release disk space after deleting all images and containers

### ISSUE THREAD

**Issue by aludin** [docker/docker#28636]
**Description**
Using Windows 10 Professional, when running  docker images, the docker virtual disk MobiLinuxVM.vhdx keeps on growing. After having finished with the images/containers, deleted all of them. However the virtual disk still uses the same amount of space. Expected behavior: MobiLinuxVM.vhdx should shrink and release unused space.

**Steps to reproduce the issue:**

1. Run various containers and observe that MobiLinux grows (once a container was running, I added my own software, which amounted to about 20GB).
2. Deleted all containers & images using: `docker rm $(docker ps -a -q)` and `docker rmi $(docker images -q)`. 

**Describe the results you received:**
MobiLinuxVM.vhdx still 40+GB in size

**Describe the results you expected:**
Expected behavior: MobiLinuxVM.vhdx should have "shrunk" to its original size when initially installing Docker on my Windows 10 box. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.919 GiB
Name: moby
ID: IWNC:POO5:TSO4:GIAK:MLHK:C46G:DRJF:IWBM:YSRO:COUL:6TKR:M2ZC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 12
 Goroutines: 22
 System Time: 2016-11-20T17:06:20.2301916Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 professional. Docker latest install using Hyper-V.

**Comment by thaJeztah** [comment]
could you reopen this issue in the docker for Windows issue tracker? This is specific to docker for Windows, so not something that can be solved in this repository; you can find the issue tracker here; https://github.com/docker/for-win/issues

I'll close the issue here, but feel free to comment after I closed

**Comment by aludin** [comment]
Reopened issue as requested: https://github.com/docker/for-win/issues/244

**Comment by thaJeztah** [comment]
Thank you!
