### ISSUE TITLE
/dev/shm is not mounted ro when --read-only is used

### ISSUE THREAD

**Issue by diogomonica** [docker/docker#28639]
When I run a `--read-only` container, the expectation is that `/dev/shm` should also be ro.

```
➜ docker run -it --read-only alpine sh
/tmp # cd /dev/shm
/dev/shm # echo bla > bla
/dev/shm # ls
bla
```

**Comment by justincormack** [comment]
I would not expect that, I think it only refers to root filesystem. Eg
volumes can be rw, and tmpfs etc.

**Comment by justincormack** [comment]
The current way to specify a `ro` (ie non functional) `/dev/shm` mount is:

```
docker run -it --read-only --mount type=tmpfs,target=/dev/shm,readonly=true alpine ...
```
eg I get
```
whale:moby justin$ docker run -it --read-only --mount type=tmpfs,target=/dev/shm,readonly=true alpine mount | grep shm
tmpfs on /dev/shm type tmpfs (ro,nosuid,nodev,noexec,relatime)
```

**Comment by diogomonica** [comment]
This works for me as a workaround.

**Comment by justincormack** [comment]
docker run -it --read-only -v /var/empty:/dev/shm:ro ...' should work without using `--mount` so long as you Linux system is LSB compliant.

**Comment by seisdr** [comment]
I'm using proot and I can't mount shm 
```
root@localhost:~# mkdir /dev/shm && mount -t shm tmpfs /dev/shm
mount: /dev/shm: cannot mount tmpfs read-only.
```
