### ISSUE TITLE
docker ps hang on CentOS7.2 with docker version 1.12.1

### ISSUE THREAD

**Issue by huanglm** [docker/docker#28650]
**Description**
"docker ps " and "docker info" command hang

**Steps to reproduce the issue:**
1."docker ps " and "docker info" command hang
2.
3.

**Describe the results you received:**
"docker ps " and "docker info" command hang

**Describe the results you expected:**
"docker ps " and "docker info" command hang

**Additional information you deem important (e.g. issue happens only occasionally):**
# service  docker  status
```
Redirecting to /bin/systemctl status  docker.service
?.docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2016-10-12 19:35:53 MMT; 1 months 9 days ago
     Docs: https://docs.docker.com
 Main PID: 10743 (dockerd)
   Memory: 1.9G
   CGroup: /system.slice/docker.service
           ?..10743 /usr/bin/dockerd
           ?..10749 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-i...

Nov 21 12:44:28 ygnmsc1_1 dockerd[10743]: time="2016-11-21T12:44:28.962844095+06:30" level=error msg="Failed to log msg \"143816725 2016-11-2...
Nov 21 12:44:28 ygnmsc1_1 dockerd[10743]: time="2016-11-21T12:44:28.963777729+06:30" level=error msg="Failed to log msg \"{\\\"remide...\",\\\"d
Nov 21 12:44:28 ygnmsc1_1 dockerd[10743]: yConsumeTxt\\\":\\\"0 MB\\\",\\\"displayBalTxt\\\":\\\"1.00 GB\\\"},{\\\"balanceType\\\":2,..."effDate
Nov 21 12:44:28 ygnmsc1_1 dockerd[10743]: "displayTotalTxt\\\":\\\"1.00 GB\\\",\\\"displayConsumeTxt\\\":\\\"0 MB\\\",\\\"displayBalT...Type\\\"
Nov 21 12:44:28 ygnmsc1_1 dockerd[10743]: TotalTxt\\\":\\\"1.00 GB\\\",\\\"displayConsumeTxt\\\":\\\"0 MB\\\",\\\"displayBalTxt\\\":\\\"1.00 ...
Nov 21 12:44:28 ygnmsc1_1 dockerd[10743]: time="2016-11-21T12:44:28.964977285+06:30" level=error msg="Failed to log msg \"\\r\" for logger js...
Nov 21 12:44:34 ygnmsc1_1 dockerd[10743]: time="2016-11-21T12:44:34.461661164+06:30" level=error msg="Handler for DELETE /v1.24/conta... use -f"
Nov 21 12:44:38 ygnmsc1_1 dockerd[10743]: time="2016-11-21T12:44:38.552773448+06:30" level=error msg="Failed to log msg \"143826605 2016-11-2...
Nov 21 12:44:42 ygnmsc1_1 dockerd[10743]: time="2016-11-21T12:44:42.796518240+06:30" level=error msg="Error saving dying container to... device"
Nov 21 14:26:23 ygnmsc1_1 dockerd[10743]: time="2016-11-21T14:26:23.097764261+06:30" level=error msg="Handler for GET /v1.24/images/d... docker"
```

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
command hang
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Can you send `SIGUSR1` to the dockerd process then grab the stack dump from the logs? possibly related to https://github.com/docker/docker/issues/28575 or https://github.com/docker/docker/issues/25993

**Comment by huanglm** [comment]
Dear,

we want to restart docker, but get faiure:

[root@ygnmsc1_1 ~]# systemctl status docker
?.docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor 
preset: disabled)
   Active: failed (Result: exit-code) since Tue 2016-11-22 14:48:00 MMT; 
28s ago
     Docs: https://docs.docker.com
  Process: 27250 ExecStart=/usr/bin/dockerd (code=exited, 
status=1/FAILURE)
 Main PID: 27250 (code=exited, status=1/FAILURE)
   Memory: 1.9G
   CGroup: /system.slice/docker.service

Nov 22 14:47:38 ygnmsc1_1 dockerd[27250]: 
time="2016-11-22T14:47:38.149854499+06:30" level=info 
msg="libcontaine...7260"
Nov 22 14:47:39 ygnmsc1_1 dockerd[27250]: 
time="2016-11-22T14:47:39.184294074+06:30" level=warning 
msg="devmappe...ion."
Nov 22 14:47:39 ygnmsc1_1 dockerd[27250]: 
time="2016-11-22T14:47:39.213398499+06:30" level=warning 
msg="devmappe...red."
Nov 22 14:47:39 ygnmsc1_1 dockerd[27250]: 
time="2016-11-22T14:47:39.246559789+06:30" level=info 
msg="[graphdrive...er\""
Nov 22 14:48:00 ygnmsc1_1 dockerd[27250]: 
time="2016-11-22T14:48:00.432601437+06:30" level=fatal msg="Error 
star...eout"
Nov 22 14:48:00 ygnmsc1_1 systemd[1]: docker.service: main process exited, 
code=exited, status=1/FAILURE
Nov 22 14:48:00 ygnmsc1_1 systemd[1]: Failed to start Docker Application 
Container Engine.
Nov 22 14:48:00 ygnmsc1_1 systemd[1]: Unit docker.service entered failed 
state.
Nov 22 14:48:00 ygnmsc1_1 systemd[1]: docker.service failed.
Nov 22 14:48:10 ygnmsc1_1 systemd[1]: Stopped Docker Application Container 
Engine.
Hint: Some lines were ellipsized, use -l to show in full.

[root@ygnmsc1_1 ~]# systemctl start docker
Job for docker.service failed because the control process exited with 
error code. See "systemctl status docker.service" and "journalctl -xe" for 
details.



南京研发中心:国际产品线-系统集成
姓名:黄理敏
地址:南京市江宁区正方中路888号.211153
--------------------------------------------
ZTESOFT TECHNOLOGY CO.,LTD.
Address:No.888, Zhengfang Road, Jiangning Economic and
Technological Development Zone, Nanjing, P.R.China
Name:Huang Limin
Mobile:+86-13913033529 (china)
       +095-009455820787（Myanmar）
E-mail:huang.limin1@zte.com.cn




发件人:         Sebastiaan van Stijn <notifications@github.com>
收件人:         docker/docker <docker@noreply.github.com>
抄送:   huanglm <huang.limin1@zte.com.cn>, Author 
<author@noreply.github.com>
日期:   2016/11/21 22:55
主题:   Re: [docker/docker] docker ps hang on CentOS7.2 with docker 
version 1.12.1 (#28650)



Can you send SIGUSR1 to the dockerd process then grab the stack dump from 
the logs? possibly related to #28575 or #25993
―

**Comment by huanglm** [comment]
what can I do now?

**Comment by thaJeztah** [comment]
@huanglm your logs are truncated; can you try getting the full logs using the `-l` option? I see some messages about device mapper, could it be your host or device mapper ran out of disk space?

**Comment by huanglm** [comment]
I already resolved this issue. The /var filesystem is full.

**Comment by thaJeztah** [comment]
Thanks for the update @huanglm. Let me close this issue then
