### ISSUE TITLE
docker 1.12 compilation failure

### ISSUE THREAD

**Issue by xianwei2016** [docker/docker#28653]
Hi guys,

It's my first time to compile docker based on a dev-image(some one build it), I have two questions in here:
1.  it reports "I don't seem to be running in a Docker container.", but it is compiled in continaer.
2. there have compilation errors as below shows.

I guess it's not Docker's problem, it should be the problem about how I tryed to compile it. Appreciate if anyone can help me on this. Thanks.

$sudo docker run -it --privileged -v /home/xianwei.zw/docker:/mnt/docker -w /mnt/docker -t docker-dev-env:1.12 hack/make.sh binary
\# WARNING! I don't seem to be running in a Docker container.
\# The result of this command might be an incorrect build, and will not be
\# officially supported.
\#
\# Try this instead: make all
\#

\#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
\# GITCOMMIT = 6a0ce49-unsupported
\# The version you are building is listed as unsupported because
\# there are some files in the git repository that are in an uncommited state.
\# Commit these changes, or add to .gitignore to remove the -unsupported from the version.
\# Here is the current list:
 M Makefile
\#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bundles/1.12.3 already exists. Removing.

---> Making bundle: binary (in bundles/1.12.3/binary)
Building: bundles/1.12.3/binary-client/docker-1.12.3
Created binary: bundles/1.12.3/binary-client/docker-1.12.3
Building: bundles/1.12.3/binary-daemon/dockerd-1.12.3
\# _/mnt/docker/cmd/dockerd
cmd/dockerd/daemon.go:276: unknown "github.com/docker/docker/daemon/cluster".Config field 'NetworkSubnetsProvider' in struct literal
cmd/dockerd/daemon.go:277: unknown "github.com/docker/docker/daemon/cluster".Config field 'DefaultAdvertiseAddr' in struct literal
cmd/dockerd/daemon_unix.go:64: undefined: libcontainerd.WithOOMScore
cmd/dockerd/daemon_unix.go:64: cli.Config.OOMScoreAdjust undefined (type *"github.com/docker/docker/daemon".Config has no field or method OOMScoreAdjust)

**Comment by thaJeztah** [comment]
I see you made some modifications to the source code (`6a0ce49-unsupported`); could those be related?

The easiest way to build is to use the makefile, which will set all the right options to build and run docker in a container, for example:

```
git checkout v1.12.3
Previous HEAD position was 6a0ce49... Merge pull request #28262 from mstanleyjones/more_metadata_fixes
HEAD is now at 6b644ec... Bump VERSION to v1.12.3

make BIND_DIR=. binary shell
```

The above builds docker in a container, but bind-mounts your local source in the container, so that you can make modifications to the source in your local editor (without having to make them inside the container).

After building, it opens a shell in the container, in which you can install the built binaries;

```
root@3562aca9dfa4:/go/src/github.com/docker/docker# make install
hack/make/.detect-daemon-osarch: line 11: docker: command not found
hack/make/.detect-daemon-osarch: line 11: docker: command not found
hack/make/.detect-daemon-osarch: line 11: docker: command not found
hack/make/.detect-daemon-osarch: line 11: docker: command not found
KEEPBUNDLE=1 hack/make.sh install-binary

---> Making bundle: install-binary (in bundles/1.12.3/install-binary)
Installing docker to /usr/local/bin/
Installing dockerd to /usr/local/bin/
Installing docker-proxy to /usr/local/bin/
```

and run the docker daemon:

```
root@3562aca9dfa4:/go/src/github.com/docker/docker# dockerd --debug
DEBU[0000] docker group found. gid: 999
DEBU[0000] Listener created for HTTP on unix (/var/run/docker.sock)
INFO[0000] libcontainerd: new containerd process, pid: 160
DEBU[0000] libcontainerd: containerd connection state change: TRANSIENT_FAILURE
DEBU[0000] containerd: read past events                  count=0
DEBU[0000] containerd: supervisor running                cpus=4 memory=1997 runtime=docker-runc runtimeArgs=[] stateDir=/var/run/docker/libcontainerd/containerd
DEBU[0000] containerd: grpc api on /var/run/docker/libcontainerd/docker-containerd.sock
...
```

**Comment by xianwei2016** [comment]
Thanks so much. @thaJeztah, I found I mounted the wrong path for source code. It's fixed. 

Because there don't have external network access in my env, so I have to use compiled-image for docker compilation instead of build by "make BIND_DIR=. binary shell".
Do you know how to install docker binary after generated it in my container? 
The docker binary already generated by "sudo docker run -it --privileged -v /home/xianwei.zw/docker:/go/src/github.com/docker/docker -t docker-dev-env:1.12 hack/make.sh binary"
But I don't know how to install the binary to my host env, not container env.

**Comment by thaJeztah** [comment]
The binaries are stored in the `bundles` directory. If you don't use `BIND_DIR`, the makefile will automatically use a bind-mount for the bundles directory;

```
docker inspect --format "{{ json .Mounts }}"  27237bc79e7b
[
  {
    "Source": "/Users/sebastiaan/Projects/docker/bundles",
    "Destination": "/go/src/github.com/docker/docker/bundles",
    "Mode": "",
    "RW": true,
    "Propagation": "rprivate"
  },
  {
    "Name": "40094419af02a626957aff331e9bd2453ab257f5f197055314018afd15c6403b",
    "Source": "/var/lib/docker/volumes/40094419af02a626957aff331e9bd2453ab257f5f197055314018afd15c6403b/_data",
    "Destination": "/var/lib/docker",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  }
]
```

So you can copy the binaries from there
