### ISSUE TITLE
docker stack deploy lacks "--with-registry-auth"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28662]
There's currently no option to deploy a stack that's using private images. We should add a `--with-registry-auth` flag to `docker stack deploy` to allow this (was discussing with @vdemeester).

/cc @aanand @dnephin @vdemeester

**Comment by dnephin** [comment]
I'm pretty sure that flag has been on `stack deploy` since 1.12

**Comment by thaJeztah** [comment]
Oh my, lol, you're right, PEBKAC, we were discussing an error, then I was watching at the wrong output in my terminal.

Abort abort, ignore ignore

**Comment by thaJeztah** [comment]
TL;DR there's no such thing as `docker service deploy` 😇
