### ISSUE TITLE
Folder sharing is case sensitive on Windows 7/Docker Toolbox?

### ISSUE THREAD

**Issue by ceball** [docker/docker#28660]
**Description**

Folder sharing is case sensitive?

This command creates a folder ``t123`` containing ``test`` file on the host:
```
$ docker run -it -v /c/Users/testing123/t123:/t123 alpine sh -c "touch /t123/test"
```
This command does not:
```
$ docker run -it -v /c/users/testing123/t123:/t123 alpine sh -c "touch /t123/test"
```
Both commands create ``t123/test`` in the container and ``/c/users/testing123/t123/test`` in the ``default`` VM.

I found this problem while trying to figure out why a docker-compose.yml file that worked fine on Windows 10/Docker for Windows 1.12.3 was behaving differently on Windows 7/Docker Toolbox 1.12.3:

```
version: '2'
services:
  one:
    [...]
    volumes:
      - ./t123:/t123
```

On Windows 10/Docker for Windows, this results in ``./t123`` (``c:/users/testing123/t123``) being created on the host, and files being shared between host and guest. On Windows 7/Docker Toolbox, ``./t123`` is not created on the host.

If I change the volume mount in docker-compose.yml to be ``/c/users/testing123/t123:/t123`` the result is the same. However, if I change it to be ``/c/Users/testing123/t123:/t123`` then it works.

**Steps to reproduce the issue:**

1. Install Windows 7 Professional x64 using VMware Workstation 12 Player with user testing123 and apply all 'important' updates (just mentioning all that because it's exactly what I just happened to do...)
2. Install DockerToolbox-1.12.3 accepting all defaults
3. Open docker quickstart terminal and run the following commands...
```
testing123@WIN-ON3GMQSBBNH MINGW64 /c/users/testing123
$ ls t123
ls: cannot access 't123': No such file or directory

testing123@WIN-ON3GMQSBBNH MINGW64 /c/users/testing123
$ docker run -it -v /c/users/testing123/t123:/t123 alpine sh -c "touch /t123/test"

testing123@WIN-ON3GMQSBBNH MINGW64 /c/users/testing123
$ ls t123
ls: cannot access 't123': No such file or directory

testing123@WIN-ON3GMQSBBNH MINGW64 /c/users/testing123
$ docker run -it -v /c/Users/testing123/t123:/t123 alpine sh -c "touch /t123/test"

testing123@WIN-ON3GMQSBBNH MINGW64 /c/users/testing123
$ ls t123
test
```

**Describe the results you received:**

As shown in the session above, I find that mounting ``/c/Users`` as a volume works, while ``/c/users`` does not.

**Describe the results you expected:**

I expected either ``/c/Users`` or ``/c/users/`` to work, because Windows is case insensitive.

**Additional information you deem important (e.g. issue happens only occasionally):**

I assume this issue arises from VirtualBox. The problem I have is that if I distribute Docker-based software to people, and those people use Windows/Docker Toolbox, I'm going to have a hard time explaining about figuring out which case their ``/c/users/username`` path is stored in on the file system, because Windows itself is case insensitive so this will all be foreign to them...

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 10
 Running: 0
 Paused: 0
 Stopped: 10
Images: 4
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 51
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-boot2docker
Operating System: Boot2Docker 1.12.3 (TCL 7.2); HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: EKPO:5LQC:OIUK:LNPW:MKTD:OYND:L4NO:TUYZ:M3E2:NVTV:CWOY:2L4W
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 24
 System Time: 2016-11-21T14:17:52.553906094Z
 EventsListeners: 0
Username: XXX
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Debian 8/VMware Workstation 12 Player running guest Windows 7 Professional x64.
VirtualBox version 5.1.8 r111374. Shared "users" folder for the ``default`` VM was set up automatically by Docker Toolbox's installer, with Name=``c/Users``, Path=``\\?\c:\Users``, Auto-mount=Yes, Access=Full.

**Comment by justincormack** [comment]
This is not really an issue that we can fix here, I think you want to file a toolbox issue or a virtualbox issue at a guess, but yes, case insensitive filesystems are a world of pain...

**Comment by ceball** [comment]
> This is not really an issue that we can fix here, I think you want to file a toolbox issue 

Oops, sorry, I failed to spot there's a separate tracker for toolbox. I'll submit this issue there.

> but yes, case insensitive filesystems are a world of pain...

Ha, the file system (NTFS) is case sensitive, but the operating system (Windows) is mostly case insensitive...at least as far as I can tell (or care - I'm not really a Windows user). My problem is that just about all the users of my software are on Windows (a large part of the reason I'm using docker in the first place...).
