### ISSUE TITLE
Flaky test TestCleanupMountsAfterDaemonAndContainerKill

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#28687]
https://jenkins.dockerproject.org/job/Docker%20Master/7625/label=fedora23%20&&%20devicemapper/console

Daemon logs https://gist.github.com/tonistiigi/5a8edf4190efe82c7d84720ae86a05c2 show lot of things going wrong. Multiple errors/warnings in restore path and in the end daemon fails to mark the container as stopped.

https://github.com/docker/docker/pull/28590 fits with the timing but uncertain if it really is the regression point.

@mlaventure

**Comment by tonistiigi** [comment]
I've seen it in fedora/centos/arm

**Comment by tonistiigi** [comment]
Adding to `v1.3.0` as it is an actual bug, not only a test issue.

**Comment by tonistiigi** [comment]
TestDaemonRestartWithKilledRunningContainer has started failing with same error https://jenkins.dockerproject.org/job/Docker%20Master/label=centos72%20&&%20devicemapper/7680/console

```
time="2016-11-22T21:02:00.010662541Z" level=error msg="Failed to restore df9a4179588592240fbddc15887bea6bf339
c85812c0bb2224ab50540363ca73 with containerd: rpc error: code = 13 desc = get all pids for container: exit st
atus 1: \"container \\\"df9a4179588592240fbddc15887bea6bf339c85812c0bb2224ab50540363ca73\\\" does not exist\\
n\""
```

**Comment by thaJeztah** [comment]
Seen failing a couple of times on master https://jenkins.dockerproject.org/job/Docker%20Master/label=fedora23%20&&%20devicemapper/7727/console, https://jenkins.dockerproject.org/job/Docker%20Master/label=centos72%20&&%20devicemapper/7728/console, https://jenkins.dockerproject.org/job/Docker%20Master/label=centos72%20&&%20devicemapper/7726/console
