### ISSUE TITLE
Intermittent "unexpected EOF" error from ADD command when using remote URI

### ISSUE THREAD

**Issue by nathan-osman** [docker/docker#28694]
**Description**

I am attempting to add [this file](https://curl.haxx.se/ca/cacert.pem) to a container through an `ADD` command in the Dockerfile. However, when building the container, Docker hangs and eventually spits out an error.

**Steps to reproduce the issue:**
1. Create a new `Dockerfile` that inherits from `scratch`
2. Add the following line: `ADD https://curl.haxx.se/ca/cacert.pem /etc/ssl/certs/`
3. Run `docker build -t failing-build .`

**Describe the results you received:**

Docker sometimes hangs on the `ADD` command.

**Describe the results you expected:**

The file is always downloaded and added to the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

The error consistently happens from the same server, whereas it succeeds on others. I am able to use `wget` to successfully retrieve the file from the same server that the `ADD` command fails on.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 22:01:48 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 26
 Running: 25
 Paused: 0
 Stopped: 1
Images: 71
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 316
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: [...]
ID: [...]
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: [...]
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

The failures are consistently happening from a 4GB Linode in Dallas, TX and Newark, NJ. The command succeeds on a DigitalOcean droplet in SF. `wget` succeeds in downloading the file on all machines.

**Comment by nathan-osman** [comment]
Interesting! Further investigation has led to an interesting discovery.

The DigitalOcean droplet was running Docker 1.6, which works fine. I confirmed this by creating a completely new droplet with Ubuntu 14.04 and Docker 1.6 - it succeeds. I then rebuilt the droplet with Ubuntu 16.10 and Docker 1.12 and the build fails.

It would appear that this is a regression of some sort.

**Comment by justincormack** [comment]
It is probably related to the root certificates or ciphers supported. These builds are built with different Go versions that may support different ciphers, and your boxes may have different root certs.

**Comment by CameronGo** [comment]
Has anyone seen any updates or workarounds related to this issue?  I am seeing this behavior during docker build as well.  I can confirm that from my host where the build is occurring I am able to curl the URL and wget with no issues, so I don't think it is root certs or cipher support on my host machine.
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:00:36 2016
 OS/Arch:      linux/amd64

**Comment by AlexRudd** [comment]
Seems to be a problem with the version of Go used to build Docker.

Here's where Docker build detects that ADD is using a remote uri: https://github.com/docker/docker/blob/master/builder/dockerfile/internals.go#L120

Here's the function in httputils which is evoked to do the download: https://github.com/docker/docker/blob/master/pkg/httputils/httputils.go#L19

As you can see it passes the url straight to `http.Get()`

To try and replicate this I wrote a snippet of Go:
```go
package main

import (
	"net/http"
	"fmt"
)

func main() {
	if _, err := http.Get("https://curl.haxx.se/ca/cacert.pem"); err != nil {
		fmt.Printf("Didn't work: %s", err.Error())
	} else {
		fmt.Printf("Worked!")
	}
}
```

And then compiled and it using different versions of Go:

```sh
# Compile with golang:1.6
docker run -v `pwd`:/go/src golang:1.6 go build -o ./src/main ./src/main.go
./main
# Didn't work: Get https://curl.haxx.se/ca/cacert.pem: unexpected EOF

# Compile with golang:1.7
docker run -v `pwd`:/go/src golang:1.7 go build -o ./src/main ./src/main.go
./main
# Worked!
```

No idea about a workaround, adding files from other remote uri's works for me but I can't find this file hosted anywhere else trustworthy.

**Comment by thaJeztah** [comment]
Is this still an issue on the current version of docker (17.03 or up)? Docker is now built with Go 1.7, so if it's related to Go 1.6, this should be resolved.

**Comment by nathan-osman** [comment]
I'll give it a go and report back shortly.

**Comment by nathan-osman** [comment]
Confirmed that this is now working with Docker 17.03.0-ce. Feel free to close the issue.

**Comment by thaJeztah** [comment]
Good to hear, thanks!

I'll go ahead and close :+1:
