### ISSUE TITLE
List of containers with networkID filter is not working (docker ps --filter "network=nwID")

### ISSUE THREAD

**Issue by dattatrayakumbhar** [docker/docker#28722]
**Description**
docker ps --filter does not work for partial network ID.

**Steps to reproduce the issue:**
1.  Created a network dk0

    [root@datta-bastion-dns docker]# docker network ls
  NETWORK ID          NAME                DRIVER              SCOPE
  f5c40491da47        bridge              bridge              local
  2968b0850d98        dk0                 bridge              local
  0d4ed75c8c6c        host                host                local
  e6919f3b8d9a        none                null                local

2. Create a container with a network in #1.
   docker run -it -d --net=2968b0850d98 busybox sh  

3. Filter with same network
    docker ps --filter "network=2968b0850d98"

Note: Filter with full networkID worked.

**Describe the results you received:**
able to create container with network ID ( Partial ID ) which is shown in 'docker network ls'

\# docker ps --filter "network=2968b0850d98"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

Observed Empty output

**Describe the results you expected:**
docker ps with filter should show container with network ID "2968b0850d98"

**Output of `docker version`:**
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

**Output of `docker info`:**
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 64
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: datta-bastion-dns.cisco.com
ID: 7ZBB:T5UR:R7FN:ZMZS:DG4R:26W5:GOW7:5CV4:CDCE:GQ54:LVXV:OQPK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 43
 System Time: 2016-11-22T19:57:40.567435847Z
 EventsListeners: 0
Username: dattatrayakumbhar04
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by pikeszfish** [comment]
It's OK to use full network ID or network name to filter.
But can not use the short network ID.


from src/github.com/docker/docker/daemon/list.go:441
```
func includeContainerInList(container *container.Container, ctx *listContext) iterationAction {
......

    networkExist := fmt.Errorf("container part of network")
	if ctx.filters.Include("network") {
		err := ctx.filters.WalkValues("network", func(value string) error {
			if _, ok := container.NetworkSettings.Networks[value]; ok {
				return networkExist
			}
			for _, nw := range container.NetworkSettings.Networks {
				if nw.EndpointSettings == nil {
					continue
				}
				if nw.NetworkID == value {
					return networkExist
				}
			}
			return nil
		})
		if err != networkExist {
			return excludeContainer
		}
	}
}
```
