### ISSUE TITLE
Docker pull fails on low bandwidth connection

### ISSUE THREAD

**Issue by jacobtomlinson** [docker/docker#28724]
**Description**

When pulling an image, over a slow connection, with two larger layers (>40M) followed by a small layer (<10M) it can fail due to i/o timout errors.

**Steps to reproduce the issue:**
1. Install docker on machine where connection can be throttled
2. Throttle network to 2-3mbps
3. `docker pull` image with a few larger layers

**Describe the results you received:**
Docker downloads three layers at a time. So initially the first three start to download. Then once one of them completes the fourth layer attempts to download, however all available bandwidth is being used by the two layers still downloading. When bandwidth is this low the request for the fourth layer fails. After a couple of retries the pull aborts with a `dial tcp ... i/o timeout` error, regardless of whether the other two layers are still successfully downloading.

**Describe the results you expected:**
It would be nice to have a command line flag for `docker pull` along the lines of `--num-downloads=1` which downloads each layer one at a time. This way bandwidth would be available for each layer because the previous would've completed.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 15
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-33598067-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 465.2 MB
 Data Space Total: 107.4 GB
 Data Space Available: 27.72 GB
 Metadata Space Used: 1.294 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 993.3 MiB
Name: localhost
ID: QKQN:YZZU:PCRX:WO66:FGG4:LUR4:PVR5:QBLM:NKE4:B52W:ZCAU:5TRQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VMware VM running Centos 7 on a home broadband connection

**Comment by thaJeztah** [comment]
Such an option already exists; you can set the number if concurrent downloads / uploads as a daemon option; https://docs.docker.com/engine/reference/commandline/dockerd/

does that resolve your issue?

**Comment by jacobtomlinson** [comment]
@thaJeztah yes that solves it perfectly thank you! I was looking here https://docs.docker.com/engine/reference/commandline/pull/ for information on this, I didn't think of looking in the daemon reference.

Maybe it would be useful to update the pull docs to reference it?

**Comment by thaJeztah** [comment]
@jacobtomlinson perhaps that's useful yes; would you be interested in contributing and opening a pull request? The source for that page of the documentation is part of this repository; 

https://github.com/docker/docker/blob/master/docs/reference/commandline/pull.md

And for push 

https://github.com/docker/docker/blob/master/docs/reference/commandline/push.md

**Comment by jacobtomlinson** [comment]
@thaJeztah see #28726

**Comment by thaJeztah** [comment]
Thanks! Just saw it ❤️
