### ISSUE TITLE
insecure registries- i have followed the instructions for daemon.json, does not work

### ISSUE THREAD

**Issue by inasingh** [docker/docker#28731]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
could you add some more info, as requested in the issue template, there's currently not enough information to look into your issue

**Comment by inasingh** [comment]
I am running-
virtualbox on mac
on top, ubuntu 16.04
on top docker installed by docker.io
I did create damon.json but it does not help .

**Comment by thaJeztah** [comment]
please provide the info requested in the template, the exact steps you followed (e.g. did you restart the daemon after changing the file), and the content of your daemon.json
i'm closing this issue until there's enough information
