### ISSUE TITLE
Error when committing container

### ISSUE THREAD

**Issue by manucarbonell** [docker/docker#28745]
I have created a container in an AWS t2.small instance with 30G of storage. There I have installed opencv and tensorflow. Everything works fine until I want to commit the container:

I do 
`docker commit myContainer tensorbox`
and I get
`Error response from daemon: devmapper: Error mounting '/dev/mapper/docker-202:1-396477-8795478ef38c8bf8e43978b32bae6d2a829188f5e4c85064e729dfe087cfde2d-init' on '/var/lib/docker/devicemapper/mnt/8795478ef38c8bf8e43978b32bae6d2a829188f5e4c85064e729dfe087cfde2d-init': input/output error`

Does anybody know what does this error mean?

Thanks

**Comment by AkihiroSuda** [comment]
Please use this template for reporting issues?
https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by manucarbonell** [comment]
The problem was the instance didn't have enough memory, solved after doing the same process in an instance with 80 G storage.

**Comment by dbsquared** [comment]
@manucarbonell can you please share more about your solution?
What did you mean by "doing the same process in an instance with 80 G storage."

instance meaning your hosting server or the container?

it will be much appreciated.

**Comment by thaJeztah** [comment]
@dbsquared a bigger AWS instance (host / server)
