### ISSUE TITLE
docker save results in cannot access file

### ISSUE THREAD

**Issue by MihaMarkic** [docker/docker#28744]
**Description**

Running "docker save" results in "rename DIRECTORY\.docker_temp_893108827 DIRECTORY/images.tar: The process cannot access the file because it is being used by another process."

**Steps to reproduce the issue:**
1. Run "docker save --output "DIRECTORY/images.tar" image1:latest image2:latest image3:latest"
2. Run it more than once. For me it stops usually after the first run (first is successful).

**Describe the results you received:**
```
rename DIRECTORY\.docker_temp_893108827 DIRECTORY/images.tar: The process cannot access the file 
because it is being used by another process.
```

**Describe the results you expected:**

I'd expect a file images.tar generated in DIRECTORY.

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens after few successful runs. When it starts, it is very persistent. Even restarting docker service doesn't help usually.
I'm still trying to pinpoint the cause (no idea) and a workaround.

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 639
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 451
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.30-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.918 GiB
Name: moby
ID: MMEV:J3D4:HLSY:7YKR:AJ2O:ZRP7:K7F5:KD3T:YMHZ:XQTQ:GZVS:CMOY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: mihamarkic
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical PC.

**Comment by MihaMarkic** [comment]
Wrong tag by @GordonTheTurtle. It is Docker for Windows stuff, not swarm.

**Comment by MihaMarkic** [comment]
Still looking at it, but it might not be docker's fault after all. In one instance Visual Studio 2015 (or one of its extensions) held the lock on temporary image file for some reason.

**Comment by thaJeztah** [comment]
> Wrong tag by @GordonTheTurtle. It is Docker for Windows stuff, not swarm.

Heh, looks like your mention of  restarting the `docker service` put it on the wrong foot;
https://github.com/docker/docker/blob/master/poule.yml#L26

> Still looking at it, but it might not be docker's fault after all. In one instance Visual Studio 2015 (or one of its extensions) held the lock on temporary image file for some reason.

That was my initial thought; since this file is on the _client_, not the daemon side, it could be another process (virus scanners, indexing service are possible other candidates)

**Comment by thaJeztah** [comment]
Can you keep us posted if that was indeed the problem?

**Comment by MihaMarkic** [comment]
Sure, asap I have any new info. I've tried to reproduce it right now, but for some reason it just works.
Said that, when it (if) happens again, I'll try different solutions and let you know about my findings.

**Comment by thaJeztah** [comment]
Let me close this issue for now, but happy to reopen if there's still something that needs fixing. Thanks!
