### ISSUE TITLE
[experimental] docker checkpoint create should print name (or ID) on success

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28756]
Unlike other commands (`docker volume create`, `docker network create`),
the `docker checkpoint` create command does not return the "id" or "name"
of the checkpoint;

```bash
$ docker checkpoint create my-container charlie
<nothing printed>
```

To be consistent with other commands, the name (or "id") should be printed;

```bash
$ docker checkpoint create my-container charlie
charlie
```

**Comment by adshmh** [comment]
#dibs

**Comment by adshmh** [comment]
Could I give this a try?

**Comment by thaJeztah** [comment]
@adshmh sure, go ahead!

**Comment by adshmh** [comment]
Currently, the client only receives an error from the server (and no details regarding the checkpoint itself). As pointed out by @mlaventure, the name of the checkpoint can be printed without enhancing the server's response, as the checkpoint name is provided by the client side.

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/pull/29073 was merged, so closing this
