### ISSUE TITLE
[experimental] docker checkpoint create cryptic error message on duplicate

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28755]
When creating a checkpoint for a container, and a checkpoint with that
name already exists for the container, a cryptic error message is printed;

```bash
$ docker checkpoint create cr checkpoint2
Error response from daemon: Cannot checkpoint container cr: rpc error: 
code = 6 desc = mkdir /var/lib/docker/containers/c4ba0c844c93a31db50dcda57fc0126fd17ec1c4a73cd550a501aac117685a6c/checkpoints/checkpoint2:
file exists
```

`docker checkpoint create` should;

- check if a checkpoint already exists
- if exists, print a proper error message

Expected behavior;

```bash
$ docker checkpoint create cr checkpoint2
Error response from daemon: checkpoint with name foo already exists for container cr
```

/cc @boucher

**Comment by dattatrayakumbhar04** [comment]
#dibs 
I wanted to work on this.

**Comment by thaJeztah** [comment]
Thank you @dattatrayakumbhar04! Let me know if you need input. If you want to discuss things, we're moving from IRC to Slack, see https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

**Comment by dattatrayakumbhar04** [comment]
Thanks @thaJeztah . I will try to reproduce it on my platform. If I need any input, I will ask for help surely
Is checkpoint feature available in 1.13 release?

**Comment by karsinkk** [comment]
@thaJeztah  Is this issue resolved? Can I work on it?

**Comment by thaJeztah** [comment]
@karsinkk looks like there's an open pull request; https://github.com/docker/docker/issues/29099
