### ISSUE TITLE
[experimental] docker checkpoint ls error messages

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28766]
The `docker checkpoint ls` command's error messages can be slightly
improved;

```bash
$ docker checkpoint ls nosuchcontainer
Error response from daemon: No such container: nosuchcontainer
```

This is inconsistent with other commands, which don't print `Error response from daemon:`;

```bash
$ docker service ps nosuchthing
Error: No such service: nosuchthing

$ docker container inspect nosuchthing
[]
Error: No such container: nosuchthing
```

I also found this;

```bash
$ docker checkpoint ls ../../
Error response from daemon: page not found
```

Whereas (e.g.)

```bash
$ docker service ps ../../
Error: No such service: ../../
```

It's really a corner case, and I'm not sure why other commands succeed in this case, but would be nice
to improve if it's an easy fix :)

**Comment by bbayani** [comment]
#dibs

**Comment by thaJeztah** [comment]
@bbayani thanks! Let me know if it's an easy fix or requires big changes, I haven't fully looked into this. I know several other commands return `Error response from daemon:` which may be considered either "useful" or an "implementation detail", so I'm also open to suggestions.

The "page not found" error may be related to https://github.com/docker/docker/issues/28769, I haven't checked yet of the PR fixing that also fixes that issue :smile:

If you want to discuss, feel free to register for the Docker Community Slack (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or ping me on IRC (which is still active)

**Comment by karsinkk** [comment]
@thaJezath Has this issue been resolved? If not can I have a go at it?

**Comment by bbayani** [comment]
@karsinkk Please go ahead.

**Comment by krasi-georgiev** [comment]
https://github.com/docker/docker/blob/master/client/request.go#L184

The difference between 
`docker checkpoint ls nosuchcontainer`
and all other commands is the return code 

if serverResp.statusCode < 200 || serverResp.statusCode >= 400 {
.
.
return serverResp, fmt.Errorf("Error response from daemon: %s", strings.TrimSpace(errorMessage))
}

or else it simply returns the server reply.


so I think it is logical to leave it as it is and maybe change the return code form the daemon 

@thaJeztah  what do you think ?
