### ISSUE TITLE
e-lm

### ISSUE THREAD

**Issue by eirikur-ari** [docker/docker#28763]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Looks to be opened in error, but comment if you were trying to report an issue :smile:
