### ISSUE TITLE
[1.13] docker version output too wide due to "Min Api Version"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28775]
The output of `docker version` is now not nicely "balanced" due to `Minimum Api Version` being added in 1.13; Can we come up with an alternative title, so that it looks nice again?

Before:

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

After:

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   839e405
 Built:        Wed Nov 23 20:32:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          839e405
 Built:               Wed Nov 23 20:32:14 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

/cc @jhowardmsft @tiborvass

**Comment by thaJeztah** [comment]
FWIW I thought about

```
API version:  1.24 (minimum version 1.12)
```

But I'm not sure that would break people parsing the output

**Comment by jhowardmsft** [comment]
I see a perfectionist at work 😸 I kind of like your idea above.

**Comment by vieux** [comment]
@thaJeztah when we downgrade, there is already `(xxx)` after the API version, might be too much, wdyt ?

**Comment by tiborvass** [comment]
@vieux that's great, that means we could add it like so: `1.24 (minimum=1.12 maximum=1.25)`

**Comment by thaJeztah** [comment]
@vieux @tiborvass the `downgraded from` is always on the `client`; this is on the `server` section, so should not be an issue

**Comment by tiborvass** [comment]
@vieux @thaJeztah good point. However what do you think having `minimum=1.12` and `maximum=1.25` in the respective Server and Client sections? Or maybe we just want it to be human readable/understandable.

**Comment by thaJeztah** [comment]
@tiborvass I thought you meant as a workaround for having to show the "downgraded" and "minimum version" on a single line. If we want min/max version, then it should be _instead_ of "version" probably (server "version" always matches "maximum"?)

**Comment by tiborvass** [comment]
@thaJeztah what I meant is:
```
Client:
 Version:      1.12.3
 API version:  1.24 (maximum=1.25)
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.3
 API version:  1.24 (minimum=1.12)
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by thaJeztah** [comment]
Hm, I like "downgraded from" as I think it more clearly describes what's happening. Highly personal probably, so welcome other input.
