### ISSUE TITLE
service create --publish supports udp, but is not documented

### ISSUE THREAD

**Issue by hehailong5** [docker/docker#28788]

**Comment by thaJeztah** [comment]
Looks like it's supported;

```bash
docker service create --name udp-service --publish 800:80/udp nginx:alpine
docker service inspect  --pretty udp-service

ID:		ug4wack6i8g1wgd75t6vq7wdk
Name:		udp-service
Service Mode:	Replicated
 Replicas:	1
Placement:
UpdateConfig:
 Parallelism:	1
 On failure:	pause
 Max failure ratio: 0
ContainerSpec:
 Image:		nginx:alpine@sha256:5c6be3514a00db611371806c5aeb510dfd285a4b8261c6e5c3323387e396b66b
Resources:
Endpoint Mode:	vip
Ports:
 PublishedPort 800
  Protocol = udp
  TargetPort = 80
```

But I see it is not mentioned in the documentation;

https://github.com/docker/docker.github.io/blob/master/engine/swarm/ingress.md
https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md#publish-service-ports-externally-to-the-swarm--p---publish

**Comment by thaJeztah** [comment]
ping @mstanleyjones @mavenugo

**Comment by genki** [comment]
`docker service create --name dns-cache -p 53:53 -p 53:53/udp dns-cache
`

Above command causes an error like this:

> Error response from daemon: rpc error: code = 3 desc = EndpointSpec: duplicate published ports provided

**Comment by mavenugo** [comment]
@thaJeztah @genki We also introduced the `--port` functionality recently and there is an effort to consolidate them under `--publish` and document them appropriately. I think @vdemeester is looking into that. We can dupe this to the other issue and consolidate the work.

**Comment by mstanleyjones** [comment]
@genki the following syntax does work:

```bash
$ docker service create --name dns-cache -p 53:53/tcp -p 53:53/udp dns-cache
6mrdkdjotd9n93x5ffw81xkht
```

**Comment by thaJeztah** [comment]
@genki are you running the latest version (1.12.3)? I think that was a bug in an older version of docker 1.12; docker 1.12.3 accepts this (using a different image, but that should not make a difference here);

```
docker service create --name dns-cache -p 53:53 -p 53:53/udp nginx:alpine
```
