### ISSUE TITLE
Can't run daemon service in Jeston Tk1

### ISSUE THREAD

**Issue by mylamour** [docker/docker#28785]
emeded device: Jeston Tk1 
OS: ubuntu 14.04
Install from apt-get
install docker step by step from document. Try different solvers , and still can't start the daemon service.

**Comment by AkihiroSuda** [comment]
Please use this template for reporting issues: https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md

Also, for questions, Docker Forums is generally preferred
https://forums.docker.com/

**Comment by justincormack** [comment]
This is an arm64 CPU, we do not provide apt repositories for Docker on this platform at present. As you do not give any details of how you installed it it is very hard to help.

**Comment by thaJeztah** [comment]
closing for now, but we can reopen if more information is provided

**Comment by mylamour** [comment]
This is the detail. 
~ `dpkg -l | grep docker`
ii  docker                                                1.5-1                                               armhf        System tray for KDE3/GNOME2 docklet applications
ii  docker-engine                                         1.12.3-0~trusty                                     armhf        Docker: the open-source application container engine
rc  docker.io                                             1.6.2~dfsg1-1ubuntu4~14.04.1                        armhf        Linux container runtime


~` docker images `
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/json: read unix @->/var/run/docker.sock: read: connection reset by peer
