### ISSUE TITLE
docker can not start on Bash on Ubuntu on Windows

### ISSUE THREAD

**Issue by liudonghua123** [docker/docker#28801]
I installed the `Bash on Ubuntu on Windows`, It is ubuntu 16.04. Then I installed the latest docker according to the official document. But when I start it, it always could not be started.

Any help would be appreciate!

```
liudonghua@DESKTOP-LJJAR95:~/code/KODExplorer$ sudo service docker restart
 * Starting Docker: docker                                                                                               [ OK ]
liudonghua@DESKTOP-LJJAR95:~/code/KODExplorer$ sudo service docker status
 * Docker is not running
liudonghua@DESKTOP-LJJAR95:~/code/KODExplorer$ cat /var/log/docker.log
time="2016-11-24T19:30:00.460686400+08:00" level=fatal msg="Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: fork/exec /usr/bin/docker-containerd: invalid argument"
time="2016-11-24T19:33:27.260330100+08:00" level=fatal msg="Failed to connect to containerd. Please make sure containerd is installed in your PATH or you have specificed the correct address. Got error: fork/exec /usr/bin/docker-containerd: invalid argument"
liudonghua@DESKTOP-LJJAR95:~/code/KODExplorer$ docker -v
Docker version 1.12.3, build 6b644ec
liudonghua@DESKTOP-LJJAR95:~/code/KODExplorer$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
liudonghua@DESKTOP-LJJAR95:~/code/KODExplorer$
```

**Comment by liudonghua123** [comment]
According to the discussion on http://serverfault.com/questions/767994/can-you-run-docker-natively-on-the-new-windows-10-ubuntu-bash-userspace

docker may not runable on `Bash on Ubuntu on Windows`

**Comment by AkihiroSuda** [comment]
It's not supported.
Closing this issue.

**Comment by AkihiroSuda** [comment]
Probably you can use docket for windows instead
https://docs.docker.com/engine/installation/windows/

**Comment by eafx** [comment]
You dismissed the issue and closed the ticket, but in essence, this should work, no? After all, you are running ubuntu in a VM which means the linux kernel is loaded or am I missing something? the whole point with docker on linux is the support for shell scripts and the ability to automate composition. I would like to run both docker on windows 10 and docker in bash... two separate processes?

**Comment by eafx** [comment]
I see. Thank you for the clarification.

**Comment by VijayChandamala** [comment]
Hi, my only solution to this problem was finding an alternative to docker called [Podman](https://podman.io/getting-started/) , it can get this problem fixed since it doesn't need a daemon as in docker. It's almost same as docker except for the commands use 'podman' instead of 'docker' , that can be fiixed too, by writing an alias `alias docker='podman'`

**Comment by liudonghua123** [comment]
Now, you can run docker on `wsl2`.
