### ISSUE TITLE
Attachable networks return inconsistant information

### ISSUE THREAD

**Issue by programmerq** [docker/docker#28817]
**Description**

When using 1.13.0-rc2 in swarm mode, `--attachable` networks show inconsistent information.

Say I have one swarm mode manager, and one worker joined.

I create a network on the manager by doing this:

    docker network create -d overlay --attachable fo

On the master it shows up in `docker network ls`, but doesn't show up in the worker until after a container is launched. This seems counter intuitive since I'm running the container directly on the worker node. I should be able to see any resources I can use before I use them.

I also noticed that the results of `docker network inspect fo` disagree on the master and the worker:

On the manager:

	# docker network inspect fo
	[
	    {
		"Name": "fo",
		"Id": "c7cni744uq99g9crw4cwg1raw",
		"Created": "0001-01-01T00:00:00Z",
		"Scope": "swarm",
		"Driver": "overlay",
		"EnableIPv6": false,
		"IPAM": {
		    "Driver": "default",
		    "Options": null,
		    "Config": []
		},
		"Internal": false,
		"Attachable": true,
		"Containers": null,
		"Options": {
		    "com.docker.network.driver.overlay.vxlanid_list": "4097"
		},
		"Labels": null
	    }
	]

On the worker:

	# docker network inspect fo
	[
	    {
		"Name": "fo",
		"Id": "c7cni744uq99g9crw4cwg1raw",
		"Created": "2016-11-24T22:45:29.046784491Z",
		"Scope": "swarm",
		"Driver": "overlay",
		"EnableIPv6": false,
		"IPAM": {
		    "Driver": "default",
		    "Options": null,
		    "Config": [
			{
			    "Subnet": "10.0.0.0/24",
			    "Gateway": "10.0.0.1"
			}
		    ]
		},
		"Internal": false,
		"Attachable": false,
		"Containers": {
		    "7bb614b0d5c2e873f4b89dbc279ffb62fc6971664e3ee504e84a57e2ac4a565d": {
			"Name": "reverent_liskov",
			"EndpointID": "2b2cab84c045d67180ca50ff7bf0dfefac19e29df0a0209d6d60bc4e2897b4a1",
			"MacAddress": "02:42:0a:00:00:02",
			"IPv4Address": "10.0.0.2/24",
			"IPv6Address": ""
		    }
		},
		"Options": {
		    "com.docker.network.driver.overlay.vxlanid_list": "4097"
		},
		"Labels": {},
		"Peers": [
		    {
			"Name": "th2-cd7695a6d9bc",
			"IP": "104.131.133.172"
		    }
		]
	    }
	]

I would expect the output of the inspect to be consistent across the whole cluster.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:32:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:32:39 2016
 OS/Arch:             linux/amd64
 Experimental:        false

```

**Output of `docker info`:**

Manager:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: rht8ru18thr4unjsvkdwmbqyr
 Is Manager: true
 ClusterID: jfvqqd6082okbrwjw31cihjao
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 159.203.223.75
 Manager Addresses:
  159.203.223.75:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: th1
ID: Y4MO:O3JV:5F4J:FQGE:PKTZ:KJ54:SPGG:T7FN:QTMH:KFFJ:SMID:W7SP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Worker:

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: tkz2wquukb9wp9r6lo1w4fzyr
 Is Manager: false
 Node Address: 104.131.133.172
 Manager Addresses:
  159.203.223.75:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: th2
ID: 5CJA:CNEX:Z65A:YXYY:KL7I:T6DY:BKQR:XNS2:XWE2:VNL3:K54O:GBZM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=digitalocean
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I provisioned these hosts via docker-machine using the digitalocean driver, and the `--engine-install-url https://test.docker.com/` option to get the latest 1.13 release candidate.

**Comment by thaJeztah** [comment]
> On the master it shows up in docker network ls, but doesn't show up in the worker until after a container is launched. 

I think that's the way swarm managed networks work; the network is automatically extended to nodes where it is in use, to keep it efficient. Only managers have access to this information (as it's stored in raft).

> I also noticed that the results of docker network inspect fo disagree on the master and the work

Probably related; I think what happens is this;

Since the network is not in use on the master node, the master node only shows the information that is known in raft; i.e., the configuration that was used to _define_ the network. Because no "subnet" or "mask" was provided when creating the network, these are not shown.

The "network inspect" on the _worker_ on the other hand, has access to the actual network information, and the automatically selected Subnet and Netmask are visible there.

There is an open PR to show both the _provided_ configuration, and the _active_ configuration in network inspect; see https://github.com/docker/docker/pull/26880

Afaik, there is one thing not yet addressed; only endpoints (containers) that are on the same host as the `network inspect` is run are shown. I think there were plans to show all connected containers / endpoints, but I don't know what the status is for that (see https://github.com/docker/docker/issues/24186)

@aboch perhaps you know?

**Comment by mavenugo** [comment]
Resolved via https://github.com/docker/docker/pull/28721
