### ISSUE TITLE
Does the host affect the Docker container?

### ISSUE THREAD

**Issue by IrvinZhang** [docker/docker#28828]
**Description**
I use vagrant + virtualBox to open a virtual machine and the virtual machine’s version is as follows:

    # cat /etc/redhat-release
    CentOS Linux release 7.2.1511(Core)
    # uname -a
    Linux zde 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
        
I start the docker(PHP56) in the virtual machine to execute the following PHP script:

    #!/bin/env php
    <?php
    error_reporting(E_ALL);
    $url = "http://www.baidu.com";
    $stream_opts = array(
        "http" => array(
            "method"          => "GET",
            "timeout"         => 15.0,
            //"follow_location" => true,
            //"max_redirects"   => 3,
            //"ignore_errors"   => false,
            //"header" => "Content-Type: text/html;charset=utf-8",
        ),
    );
    $context = stream_context_create($stream_opts);
    $http_response_header = array();
    $include_path = false;
    $content = file_get_contents($url, $include_path, $context);
    var_dump(strstr($content, "</body></html>"));
    
Here is the result of the PHP script execution:
![image](https://cloud.githubusercontent.com/assets/16041822/20617823/96440fc2-b326-11e6-9598-a59b8a685693.png)

It is because the network request which the file_get_contents() wanna get is sometimes truncated that cause the bool(false).What confuse me is that I use the PHP’curl or Linux’curl to do the same thing both can get correct result.Moreover!!! I put the same container into Mac’s docker can get correct result.The others use the same container in their virtual machine(the same configuration:vagrant,virtualbox,docker) both execute correctly. So,does the host affect the Docker container to execute file_get_contents()?
Ps: The problem has been verified with the PHP version, request timeout, request address has nothing to do.
My English is not good,forgive me! 😋 
Thanks for your reading!!!

**Comment by AkihiroSuda** [comment]
The question is probably just about the behavior of baidu.com, and does not seem related to Docker.

If you still think the issue is specific to Docker, can you provide much more information, e.g. HTTP headers when you get "false"?

**Comment by IrvinZhang** [comment]
VirtualBox 5.1.8 has problems.
