### ISSUE TITLE
DAB does not support volumes

### ISSUE THREAD

**Issue by yashgt** [docker/docker#28825]
A bundle is supposed to avoid having to issue multiple **docker service create** commands. It is hence necessary to allow all options of docker service create in the bundle file.

The recommendation given in the documentation is to use the swarm mode instead of the standalone swarm. When we generated a DAB file the message we get is:
$ docker-compose bundle
WARNING: Unsupported key 'network_mode' in services.nsqd - ignoring
WARNING: Unsupported key 'links' in services.nsqd - ignoring
WARNING: Unsupported key 'volumes' in services.nsqd - ignoring

This means the DAB/Stacks feature takes away the feature we go from docker-compose. Can we include a way by which at least the basic features are retained. It is common for people to mount volumes so that after successive deployments, the data used by the containers remains intact. 
#24795

**Comment by thaJeztah** [comment]
You may be interested in the `--compose-file` option that's added in 1.13 in this PR: https://github.com/docker/docker/pull/27998

https://github.com/docker/docker/blob/master/docs/reference/commandline/stack_deploy.md#compose-file

You can try it with the current release candidate for docker 1.13 if you have a machine for testing

https://github.com/docker/docker/releases

**Comment by yashgt** [comment]
That works.
