### ISSUE TITLE
`docker deploy` is experimental whereas `docker stack deploy` is not

### ISSUE THREAD

**Issue by albers** [docker/docker#28830]
Is this intended?
According to https://github.com/docker/docker/blob/master/docs/reference/commandline/deploy.md, `docker deploy` is just an alias to `docker stack deploy`. IMHO, it makes no sense to keep it experimental.

Observed in current master.

**Comment by vdemeester** [comment]
See https://github.com/docker/docker/pull/28839#issuecomment-262956917 :angel: This is by design :angel:

**Comment by vdemeester** [comment]
I'll close this one for now too :angel:

**Comment by albers** [comment]
Ah, yes. Makes sense. Thanks very much for clarifying.
