### ISSUE TITLE
Fedora 25 repo forbidden to sync

### ISSUE THREAD

**Issue by ssaavedra** [docker/docker#28846]
**Description**

Fedora 25 is now GA.

Docs [[1]] say we should add a repository at `https://yum.dockerproject.org/repo/main/fedora/$releasever/`, however, for Fedora 25 the server returns a code 403 Forbidden.

When following the steps, if you miss the `Failed to synchronize cache for repo 'dockerrepo', disabling.
` line, you will end up installing docker from fedora/updates repos (currently 1.12.3-9.git47e22f2.fc25).

[1]: https://docs.docker.com/engine/installation/linux/fedora/

**Steps to reproduce the issue:**
1. Open the Docker Docs for installing in Fedora [[1]]
2. Go with the DNF approach

**Describe the results you received:**

Docker installed comes from fedora/updates; currently `https://yum.dockerproject.org/repo/main/fedora/25` returns a 403 Forbidden code status, and dnf cannot sync data from it.

**Describe the results you expected:**

`https://yum.dockerproject.org/repo/main/fedora/25` returns 200 OK and allows dnf to actually download docker-engine from your repositories, so that the docs work.

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is happening currently from Spain on a Dell XPS with Fedora 25 x86_64.

**Comment by thaJeztah** [comment]
Fedora 25 was released after 1.12.3, therefore there is no package for 1.12.3. 

We will be adding support for Fedora 25 in docker 1.13 (see https://github.com/docker/docker/issues/27500)

For now, you can try if the Fedora 24 packages work (but no guarantees)

I'm closing this issue, because this is expected, and support for Fedora 25 is being tracked in https://github.com/docker/docker/issues/27500

**Comment by marcelom56** [comment]
Hey @ssaavedra, seems that docker 1.13.0 will be released in 2016-12-08.

See [here](https://github.com/docker/docker/blob/master/CHANGELOG.md).

**Comment by ssaavedra** [comment]
Thanks for the update. Anyway, nevermind; I'm using Fedora's built copy.

It's awkward to have a "canonical" source for packages that is less updated
than the distribution's. I think that should be up for a discussion
somewhere else; I don't think it's reasonable to have people waiting on a
package and not recommending any other way of getting it.

**Comment by cpuguy83** [comment]
@ssaavedra Currently the process for adding of new distro versions and the release process are tied together, this makes it difficult to release for new distros outside the normal release process.
We understand this is not ideal and are working on it.
