### ISSUE TITLE
`docker-compose scale` doesn't scale down, only up

### ISSUE THREAD

**Issue by hamx0r** [docker/docker#28851]
**Description**
When using `docker-compose scale`, it properly scales "up" when using a larger number than the existing number of containers, but it fails to scale down when using a smaller number.    This is described in #23819 as well, though that issue was closed since it centered around docker swarm instead of docker-compose

**Steps to reproduce the issue:**
1.  Scale up a _new_ service: `docker-compose scale web=5`
2. Observe 5 instances are created: `docker ps -a`
3. Attempt to scale down: `docker-compose scaled web=2`
4. Observe we still have 5 instances: `docker ps -a`

**Describe the results you received:**
Five instances of the "web" container still exist after scaling down.

**Describe the results you expected:**
Only two "web" containers to exist.  I expect excess containers to be deleted. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens consistently.  

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 100
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 152
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-68-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.54 GiB
Name: Mid18
ID: 4CPD:OTRW:BV5P:VF6Z:CP2Y:W6NZ:OHHU:M6XR:YJ2O:U3PB:24CU:UHOG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
$ docker-compose --version
docker-compose version 1.9.0, build 2585387
```

**Comment by justincormack** [comment]
Can you open an issue on https://github.com/docker/compose/issues instead? This seems `compose` specific, not related to docker engine. Thanks.
