### ISSUE TITLE
cant start docker in openvz

### ISSUE THREAD

**Issue by vvavepacket** [docker/docker#28850]
**Description**

Running docker in OpenVZ is possible, provided bridge mode is enabled... My current host doesn't want to enable bridge mode. Is there anyway to run Docker daemon without using bridge? I'm getting the below message when starting docker service

**Steps to reproduce the issue:**
1. systemctl status docker.service -l

**Describe the results you received:**

```

* docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: http://docs.docker.com

Nov 25 20:02:19 kr docker-current[24230]: time="2016-11-25T20:02:19.501592064-05:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Nov 25 20:02:19 kr docker-current[24230]: time="2016-11-25T20:02:19.503486894-05:00" level=warning msg="Running modprobe bridge br_netfilter failed with message: , error: exit status 1"
Nov 25 20:02:19 kr docker-current[24230]: time="2016-11-25T20:02:19.504919833-05:00" level=warning msg="Running modprobe nf_nat failed with message: ``, error: exit status 1"
Nov 25 20:02:19 kr docker-current[24230]: time="2016-11-25T20:02:19.526339346-05:00" level=info msg="Firewalld running: true"
Nov 25 20:02:19 kr docker-current[24230]: time="2016-11-25T20:02:19.665851505-05:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Nov 25 20:02:19 kr docker-current[24230]: time="2016-11-25T20:02:19.699399880-05:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default \"bridge\" network: package not installed"
Nov 25 20:02:19 kr systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Nov 25 20:02:19 kr systemd[1]: Failed to start Docker Application Container Engine.
Nov 25 20:02:19 kr systemd[1]: Unit docker.service entered failed state.
Nov 25 20:02:19 kr systemd[1]: docker.service failed.
```

**Describe the results you expected:**

Docker successful

**Output of `docker version`:**
```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-46.el7.centos.14.x86_64
 Go version:      go1.6.3
 Git commit:      cb079f6-unsupported
 Built:           Fri Sep 16 13:24:25 2016
 OS/Arch:         linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OpenVZ

**Comment by AkihiroSuda** [comment]
can you run https://github.com/docker/docker/blob/master/contrib/check-config.sh

**Comment by vvavepacket** [comment]
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
error: cannot find kernel config
  try running this script again, specifying the kernel config:
    CONFIG=/path/to/kernel/.config ./check-config.sh or ./check-config.sh /path/to/kernel/.config

**Comment by thaJeztah** [comment]
OpenVZ is still at kernel 2.6 (which is not supported for Docker), and only supports `vfs` as a graph-driver (which is _strongly_ discouraged, and basically only useful for testing, but nothing other than that); https://openvz.org/Docker_inside_CT

I see there's some work going on to move to kernel 3.10 https://openvz.org/Download/kernel, but nothing stable yet.

In the current situation, running Docker under OpenVZ is _not_ a supported setup

**Comment by thaJeztah** [comment]
I'll close this issue because of the above, but feel free to comment after that
