### ISSUE TITLE
Confusing documentation about logging drivers

### ISSUE THREAD

**Issue by Kukunin** [docker/docker#28860]
Current documentation about logging in Docker seems confusing. It even causes wrong PR being merged into Ansible's `docker_container` module: https://github.com/ansible/ansible-modules-core/pull/5482

[Documentation](https://docs.docker.com/engine/admin/logging/overview/) says:

> Use the --log-driver=VALUE with the docker run command to configure the container’s logging driver. If the --log-driver option is not set, docker uses the default (json-file) logging driver.

However, it's not completely true. If my daemon is running with different `log_driver` option, all containers without explicit `log_driver` option will fall back to daemon's log_driver, which is not always `json-file`.

To prove that, I have docker daemon with syslog log_driver:

    $ ps aux | grep dockerd
    root     12509  0.0  1.9 776004 39412 ?        Ssl  Nov25   0:21 /usr/bin/dockerd --log-driver=syslog --log-opt tag={{.Name}} --raw-logs

And I run new container without explicit `log_driver` option

    docker run --name test debian:jessie true

It shows `syslog` log_driver for that container:

    $ docker inspect test | grep -A 2 'LogConfig'
                "LogConfig": {
                    "Type": "syslog",
                    "Config": {

**Additional information you deem important (e.g. issue happens only occasionally):**

<details>

```bash
$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64
```
</details>

**Comment by thaJeztah** [comment]
Could you open this issue in the documentation repository, or perhaps you're interested in opening a pull request? https://github.com/docker/docker.github.io/blob/master/engine/admin/logging/overview.md

**Comment by Kukunin** [comment]
@thaJeztah thanks for pointing me. I'll try PR
