### ISSUE TITLE
Can't reach container by templated hostname 1.13

### ISSUE THREAD

**Issue by yellowmegaman** [docker/docker#28861]
**Description**

Created service with templated hostname
https://github.com/docker/swarmkit/pull/1738

**Steps to reproduce the issue:**
1. docker service create --name tmpl --hostname "{{.Service.Name}}-{{.Task.Slot}}" --network overlords --replicas 2 nginx:latest
2. docker exec -ti tmpl.1.53l54w9j8p38kewybm0341bsc /bin/bash
3. apt-get update && apt-get install links netcat -y
4. 
ping -c1 tmpl-1 - ok
links http://tmpl-1 - ok
nc -zv tmpl-1 80 - ok
all above for tmpl-2 - unknown host
all above for tmpl-2 CONTAINER ID - ok

**Describe the results you received:**
Got unknown host reaching container by templated name

**Describe the results you expected:**
Connecting to container by its templated name

**Additional information you deem important (e.g. issue happens only occasionally):**
docker 1.13.0~rc2-0~debian-jessie amd64

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:17:45 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:17:45 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 4
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: ia9vbuazsu1rfmyrkck9oekiw
 Is Manager: true
 ClusterID: jtnyl5pllcxoicbnxuhm7qsao
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.60.101
 Manager Addresses:
  172.31.58.225:2377
  172.31.60.101:2377
  172.31.61.245:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.686 GiB
Name: ip-172-31-60-101
ID: EYJD:4JFM:IOGW:4PBL:AQNK:AINV:NOXH:XBRR:NC52:VT4D:E4FR:M4V7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS/physical

Thanks a lot in advance! 
Really hoping this will help to sort out (at least) some difficulties with clustering hostname-demanding software like couchbase and rabbitmq.

**Comment by thaJeztah** [comment]
The `--hostname` of the container is not the name under which the container is reachable on the network, it only sets `hostname` inside the container. To access a service on the network, use the service name (`tmpl`)  or the container's name (`tmpl.1.53l54w9j8p38kewybm0341bsc`) to access individual containers

**Comment by yellowmegaman** [comment]
Thanks for the info, using consul anyway.
