### ISSUE TITLE
Swarm mode: Identify service containers by service name

### ISSUE THREAD

**Issue by yashgt** [docker/docker#28875]
I have a compose file which has a client and a server defined as services my_client and my_server respectively. If I start these using **compose up**, the client container is able to connect to the server using the name my_server. Apparently the DNS entry gets created in the client container so that my_server is referenced by name.

But in swarm mode, when I deploy a stack, the name of the stack is prefixed to the name of the service to create the name of a container. Due to this, the client container which assumes that the server is named my_server, is not able to connect to the server.

We should have an option to allow the client DNS entry to be made using the name of the service without a prefix. Let the service get created with the stack name as its prefix. But within a stack, the containers should know each other by the name of the un-prefixed service.

Attached my compose file.
[docker-compose.txt](https://github.com/docker/docker/files/615921/docker-compose.txt)

**Comment by mlaventure** [comment]
@yashgt do you mind providing the output of `docker version` and `docker info` so the swarm team can know where to look?

**Comment by yashgt** [comment]
Tried again. Surprisingly, now the client is able to ping my_server. not sure what was wrong earlier.
