### ISSUE TITLE
Can't set docker service create --dns to hostname

### ISSUE THREAD

**Issue by yellowmegaman** [docker/docker#28887]
**Description**

I'm trying to create a service that needs DNS inside overlay network. DNS-server being consul cluster, and node count shifting dynamically, i'd like to address it via hostname ( "tasks.consul-cluster" or dnsrr "consul-cluster"). 

**Steps to reproduce the issue:**
1. docker service create --name couchbase --network over --dns consul-cluster coucbase:latest

**Describe the results you received:**
`invalid argument "consul-cluster" for --dns: consul-cluster is not an ip address`

**Describe the results you expected:**
Creation of couchbase service

**Additional information you deem important (e.g. issue happens only occasionally):**
I have a working consul cluster and want to use it for clustering coucbase/cassandra/rabbitmq purposes.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:32:39 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:32:39 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.0-rc2
Storage Driver: devicemapper
 Pool Name: docker-202:1-263647-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 611.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 50.63 GB
 Metadata Space Used: 1.405 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 22irjsera0v182kcxn12s5yti
 Is Manager: true
 ClusterID: 3vxmsimik45ajqnvmsbl9nedp
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.63.22
 Manager Addresses:
  172.31.49.15:2377
  172.31.51.159:2377
  172.31.56.149:2377
  172.31.63.22:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.674 GiB
Name: ip-172-31-63-22
ID: U2WW:7VP2:KGSJ:46MX:XKHY:JIOU:3ZSR:6T4A:OCE4:MV7U:O26B:6WG7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS/Physical

Thanks a lot in advance!

**Comment by StEVeeCMC** [comment]
+1

**Comment by antkudr** [comment]
+1

**Comment by Aurora12** [comment]
+1

**Comment by xseven** [comment]
+1

**Comment by folex** [comment]
+1

**Comment by emstlk** [comment]
the same problem (

**Comment by tttzof351** [comment]
+1

**Comment by sanimej** [comment]
@yellowmegaman Is `consul-cluster` a swarm service running on the same overlay network ?

**Comment by yellowmegaman** [comment]
Sure it is, and dnsrr "consul-cluster" is resolvable from all hosts in it.

**Comment by sanimej** [comment]
If `consul-cluster` is the name of the service it will resolve to a VIP from all the tasks attached to the same network. Its not dnsrr. What you are trying to do currently is not possible. What you can do instead is to pass the VIP of `consul-cluster` as the `--dns` IP to couchbase service. You can get the VIP IP from `docker service inspect`.

**Comment by thaJeztah** [comment]
I think the current behavior is expected, because you cannot specify a domain-name as DNS. So it looks like this is _feature request_ to resolve the IP-address of the specified hostname, and use that IP-address as name server?

**Comment by yellowmegaman** [comment]
Exactly, sorry if i didn't make it clear from the beginning. Actually i'm also interested if wanna-be ip would be stored permanently, or, for example, resolved every time service is scaled. Asking because i have zero understanding whenever VIP's change after full cluster power down, outages can happen.

**Comment by sanimej** [comment]
@thaJeztah With the current UX we can't accept a hostname because there is no way to specify the namespace to resolve it (ie: should it be resolved in the host or the network to which this task is being attached to or something else ?).

@yellowmegaman VIP is a logical IP from the subnet associated with the overlay network. It doesn't change on service scale up/down. Can you try the option [I suggested] (https://github.com/docker/docker/issues/28887#issuecomment-263637295).

**Comment by yellowmegaman** [comment]
Yeah, probably gonna stick with it. Thank you. 
One last question though - if i edit resolv.conf inside container via some automatic templating, won't it interfere with embedded dns server?

**Comment by sanimej** [comment]
container's resolv.conf has only 127.0.0.11 which is the address of the embedded DNS server. External servers passed through `--dns` are maintained internally in the embedded DNS server and used to forward the queries that can't be resolved in the docker domain. So editing resolv.conf could interfere or break embedded server for that container.

**Comment by yellowmegaman** [comment]
Thanks for clarification. But if i just replace existing record in resolv.conf with the one serving consul dns, no possibility of break here? Pure replacement/
