### ISSUE TITLE
backwards compatibility of client API

### ISSUE THREAD

**Issue by ndegory** [docker/docker#28895]
**Description**

The Docker client API from tag v1.13.0-rc2 breaks the ImageList API when used with a Docker server below 1.25.

**Steps to reproduce the issue:**

1. Create a client with version 1.24: ```client := NewClient(socket, "1.24", nil, header))```
2. Build an ImageListOptions object with a ```reference``` filter (replaces the MatchName property from previous versions of the API):
```
    filter := filters.NewArgs()
    filter.Add("reference", imageName)
    options := types.ImageListOptions{All: false, Filters: filter}
```
3. Use the ImageList object with these options: ```list, err := client.ImageList(ctx, options)```
4. Test the client against a 1.12.3 Docker engine

**Describe the results you received:**

The Docker engine complains about an unknown filter:
Error response from daemon: Invalid filter 'reference'

**Describe the results you expected:**

The API should adapt (based on the version passed to NewClient) and provide the proper parameters to the server.

**Comment by vdemeester** [comment]
@ndegory true :sweat: working on fixing it for next RC :wink:
