### ISSUE TITLE
Content-Type from layer HEAD checks used on image push for manifest 2v2 images

### ISSUE THREAD

**Issue by sentientmonkey** [docker/docker#28894]
For Manifest 2v2 images, during an image push, Docker relies on the Content-Type returned from [the layer HEAD check][1] to set the mediaType in the manifest being pushed.

On the first push of the config layer, [the mediaType is set][2] as "application/vnd.docker.distribution.manifest.v2+json", but on later pushes it relies on the Content-Type being returned. As a result, registries that don't provide this "Content-Type" end up either missing the mediaType in the subsequent images being pushed or setting incorrectly (i.e. to "text/plain"). [The Registry V2 API documentation][3] includes only "Content-Length" and "Docker-Content-Digest" for successful responses and does not mention "Content-Type".

Is this intended behavior for Docker? If so, how should a registry determine the Content-Type for the config layers?

[1]: https://github.com/docker/distribution/blob/38fbd03266d86923d963566a6565c3fa01f496d8/registry/client/repository.go#L800
[2]: https://github.com/docker/docker/blob/783d4ac6d40b48f40e752561c79e777b35c2c0a9/distribution/push_v2.go#L542
[3]: https://docs.docker.com/registry/spec/api/#/pushing-a-layer

**Comment by thaJeztah** [comment]
The content type headers are part of the specification; Given that this is about the registry, could you reopen this in that issue tracker, because that's where that specification lives https://github.com/docker/distribution/tree/master/docs/spec (https://github.com/docker/distribution/issues). Thanks!

**Comment by sentientmonkey** [comment]
I've posted [#2084](https://github.com/docker/distribution/issues/2084) to the registry repository.

**Comment by thaJeztah** [comment]
Thank you!
