### ISSUE TITLE
Docker pull microsoft/nanoserver on Linux daemon fails with "unknown blob"

### ISSUE THREAD

**Issue by darrenstahlmsft** [docker/docker#28892]
**Description**

When a Linux daemon attempts to pull a Windows based image, it fails to download the base layer. It attempts to retry multiple times before failing with the error message "unknown blob". 

**Steps to reproduce the issue:**
Targeting a Linux daemon:
1. docker pull microsoft/nanoserver

**Describe the results you received:**

Multiple retries on both layers followed by:
unknown blob

**Describe the results you expected:**

An error message about the platform being incompatible with the image.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

This occurs on 1.12 and 1.13

**Output of `docker info`:**

Any Linux based daemon will repro

**Comment by pires** [comment]
Microsoft Windows Container images will only run in Windows Containers environments. It won't work on Linux.

**Comment by sobek85** [comment]
Same issue here
