### ISSUE TITLE
Reduced performance while building on bind mount outside of docker

### ISSUE THREAD

**Issue by kscherer** [docker/docker#2891]
Host and Guest: 12.04.3
Docker: 0.6.6
lxc: 0.7.5
Kernel: 3.8.0-29

Hardware: Dual 6C Xeon with 64GB RAM and 100GB root SSD and dual 3TB RAID0

Docker is installed on the SSD using deb packages.

I created a docker image based off the base ubuntu in the registry. This image is located in /var/lib/docker on the SSD. I created a world writable directory on the RAID0 drive and bind mounted into the docker image. All the source code and builds were done in the bind mounted directory on RAID0 drive. I launched /bin/bash inside the container and then ran the build.

Builds not using docker on RAID0 take 30-40 minutes. Inside docker the builds on RAID0 bind mount were consistently 55-65 minutes (not at the same time of course).

I then ran 'docker export' and placed rootfs on RAID0 drive. I copied most of lxc config from docker and ran lxc directly using lxc-start. The build directory was again bind mounted into the lxc container. The build using lxc directly completed in 32 min. In docker and lxc the bind mount has the same options: rw,relatime,data=ordered.

I then tried docker again and bind mounted host /tmp to a container /tmp. I did the same with /var/tmp because docker diff showed changes on /var/tmp. No change in build times.

I don't know what is going on here. The rootfs is essentially read only and on ssd. I would expect the aufs overhead only when writing, not when reading. It seems that if the rootfs is aufs, a build on a mount outside of the aufs filesystem is still affected.

If there is some option/configuration I missed let me know, otherwise I will wait until the device-mapper implementation is ready and try again.

Thanks for a great tool.

**Comment by jfrazelle** [comment]
can you see if this is a still an issue with the latest version of docker

**Comment by kscherer** [comment]
Docker 1.5 on Ubuntu 14.04 with 3.16 utopic LTS kernel.

The current stable poky release is dizzy:

    cd <buildarea>
    mkdir downloads
    chmod 777 downloads
    git clone --branch dizzy git://git.yoctoproject.org/poky
    source poky/oe-init-build-env mybuild
    ln -s ../downloads .
    bitbake -c fetchall core-image-minimal
    time bitbake core-image-minimal

There is no need to set the parallel packages and jobs now in
local.conf because bitbake now chooses reasonable defaults. 

Bare Metal:

    real    29m59.190s
    user    278m0.988s
    sys     59m47.379s

Devicemapper:

    real    32m21.074s
    user    281m53.994s
    sys     68m45.554s

AUFS:

    real    37m14.612s
    user    259m19.226s
    sys     85m50.269s

I only ran each build once so this is not an authoritative
benchmark. It shows that there is a performance overhead of approx 20% when using the
aufs backend even if the IO is done on a bind mount.

**Comment by unclejack** [comment]
@kscherer Docker 1.6 will have direct io support for aufs and it should be faster. How did you set up devicemapper? I'm asking about devicemapper because I know some people are using it in production, but the way it's set up matters.

**Comment by kscherer** [comment]
On 15-04-06 11:04 AM, unclejack wrote:
> @kscherer <https://github.com/kscherer> Docker 1.6 will have direct io
> support for aufs and it should be faster. How did you set up
> devicemapper? I'm asking about devicemapper because I know some people
> are using it in production, but the way it's set up matters.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/2891#issuecomment-90093183>.
>

That is good news and I look forward to rerunning my tests.

I am using the devicemapper backend in loopback mode. This has been 
working well enough, although the instance creation fails sometimes 
(Issue #4096). I will look into the devicemapper direct-lvm mode.

**Comment by kscherer** [comment]
Update for Docker 1.7

- Ubuntu 14.04.2
- Vivid kernel 3.19.0-21-generic
- Dual 6C Xeon with 64GB RAM and 100GB root SSD and dual 3TB RAID0

Building poky, fido release, core-image-minimal on a ext4 bind mount with the docker
image using different storage backends.

    cd <buildarea>
    mkdir downloads
    git clone --branch fido git://git.yoctoproject.org/poky
    source poky/oe-init-build-env mybuild
    ln -s ../downloads .
    sed -i 's/#MACHINE ?= "qemux86-64"/MACHINE ?= "qemux86-64"/' conf/local.conf
    bitbake -c fetchall core-image-minimal
    time bitbake core-image-minimal

Bare-metal:

    real    33m5.260s
    user    289m41.356s
    sys     27m23.488s

Aufs:

    real    40m24.416s
    user    258m48.932s
    sys     56m29.284s

Devicemapper with official binary in loopback mode:

    real    35m24.415s
    user    289m10.660s
    sys     34m21.168s

Devicemapper with my own compiled dynamic binary:

    real    34m18.387s
    user    294m1.720s
    sys     31m43.764s

Overlayfs:

    real    33m46.890s
    user    293m40.084s
    sys     35m31.480s

See http://kscherer.github.io/docker/2015/07/09/benchmarking-docker-storage-backends/ for the Dockerfile used.

The performance of the aufs backend in this scenario has improved, but the overhead is still significant. With the udev sync requirements for devicemapper on docker 1.7, it is clear to me that overlayfs is my best option on Ubuntu now.

Since I now have two options for storage backends with acceptable performance, there isn't much point to keeping the issue open.

Thanks again for the amazing work on Docker!
