### ISSUE TITLE
secrets: validation on "length" not working

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#28927]
Stumbled upon this while trying to trigger an error;

```bash
$ echo| docker secret create empty
slhlh25ruhac1rauto7nshgdg
```

or

```bash
echo "" | docker secret create empty2
gfy974zqmdeosuxekm4ja6sci
```

Does not produce an error, whereas;

```bash
$ docker secret create empty3
^D
Error response from daemon: rpc error: code = 3 desc = secret data must be larger than 0 and less than 512000 bytes
```

Difference between those two is that the first example produces this API call;

```
DEBU[36601] Calling POST /v1.26/secrets/create
DEBU[36601] form data: {"Data":"Cg==","Name":"empty"}
```

and the last example produces;

```
DEBU[36676] Calling POST /v1.26/secrets/create
DEBU[36676] form data: {"Name":"empty3"}
```

Validation should work here, to prevent people from accidentally creating (and using) an empty value, e.g.;

```bash
$ echo $MY_SECRET_THAT_WAS_NOT_SET | docker secret create empty4
rduz246w7tn2bstrw7v2qn54y
```

**Comment by yongtang** [comment]
`"Cg=="` is the base64 encoding of `0x0A`. I think additional validation might be needed to prevent the white-spaces (`" "`, `"\t"`, `"\n"`, `"\r"`, etc) only data.

**Comment by thaJeztah** [comment]
> "Cg==" is the base64 encoding of 0x0A.

Ah, yeah, I meant to look up what it was. Weird that it's adding a newline in this case

**Comment by ehazlett** [comment]
checking on this

**Comment by aaronlehmann** [comment]
> Weird that it's adding a newline in this case

It's not weird at all. `echo` without `-n` always adds a newline. If you use `-n` it should behave as expected.

I'm not in favor of disallowing whitespace-only secrets. I think we should let people store arbitrary data in a secret. If we start putting more restrictions on what a secret has to look like, people will hit corner cases when they try to store things that don't pass our validation.

**Comment by thaJeztah** [comment]
Generally, I agree, but I'm a bit worried about the last case I described, where it's easy to accidentally create an empty secret. Since there's no easy way to confirm / read back the secret, this may be problematic

**Comment by aluzzardi** [comment]
This is how I think it should work:

```
docker secret create foo -f <filename>
echo foo | docker secret create -
```

Having `create` with no arguments hang is a UX bug
Also, expecting people to get it right with `echo` is unrealistic - we should provide a `-f` here

/cc @diogomonica @ehazlett

**Comment by aluzzardi** [comment]
Alternative:

```
docker secret create name -f file.txt
docker secret create name -f -
```

/cc @diogomonica @aaronlehmann @thaJeztah

**Comment by diogomonica** [comment]
I'm down with either.

**Comment by ehazlett** [comment]
@aluzzardi  I have no opinion.  whatever you want.

**Comment by cyli** [comment]
Either works for me :)

**Comment by aaronlehmann** [comment]
Preference for `-f [filename|-]`, because it's inconsistent for `-` to be a positional argument but the filename to be provided with a `-f` flag.

It would also be okay to use a positional argument `[filename|-]`, but I think `-f` is slightly better because it will leave us more flexibility for the future.

Arguably the name shouldn't be positional either, and the command should look like `docker secret create --name mysecret -f secretsource.txt`.

No strong feelings as long as the solution is consistent with itself.

**Comment by thaJeztah** [comment]
Name should not be a flag, as it's not optional. W.r.t `-` or just `--file`; I think `-` is used if the file name is a positional argument (see `docker build`), but not needed if it's the default.

Someone with more knowledge of Linux CLI conventions may want to confirm that

**Comment by tianon** [comment]
Can't `--name` be optional though?  (ie, just create this secret with a random name, similar to containers, volumes, etc)

I'm definitely +1 on explicit `-f` for reading from a file directly, especially since it leaves room for a potential `--value` or `--ascii` or `--text` or something later for directly setting a textual value. :innocent:

**Comment by thaJeztah** [comment]
@tianon current implementation only uses stdin; `echo foo | secret create dear-diary`

**Comment by tianon** [comment]
@thaJeztah right, but if we go with `-f` instead of a positional argument, that could potentially change in the future (leaves the door open), and using a positional argument for "name" is inconsistent with most other existing Docker CLI "create" subcommands which use `--name`

**Comment by tianon** [comment]
Regarding stdin, IMO defaulting to stdin is sane (especially with an explicit ability for `-f` to override and read from a file directly instead), and `-` is a very common CLI convention for stdin (for folks to be explicit with something like `-f -`).

A good example is `wget`.  I use `wget -qO- ...` often for grabbing a remote file to stdout.

**Comment by diogomonica** [comment]
@tianon not sure if random secret names make sense, mostly because they have meaning to the user (whereas different containers of the same image don't).

**Comment by tianon** [comment]
@diogomonica ok, so imagine as part of my deployment, I want to ensure that I can deploy to any system (regardless of existing secrets), and thus don't want to enforce an explicit "secret name" (or want to be able to deploy the same system more than once with different randomly-generated or otherwise unique secrets)

Given the way that container and volume naming works, I'd expect to be able to do something like this:
```console
$ secretName="$(echo "my new secret $RANDOM" | docker secret create)"
$ docker service create --secret "$secretName":explicit-in-container-name ...
```

**Comment by diogomonica** [comment]
why not:

```
$ secretName="$(echo "my new secret $RANDOM" | docker secret create $OTHER_RANDOM)"
$ docker service create --secret "$secretName":explicit-in-container-name ...
```

**Comment by tianon** [comment]
Sure, that's easy, but inconsistent with the rest of the Docker CLI experience -- what conceptually makes secrets different from volumes?

**Comment by tianon** [comment]
Are there _any_ other `docker` CLI subcommands where the name of the object we're creating is provided as a positional argument?  I think `docker tag` and `docker commit` might be the only examples I can think of off-hand -- everything else uses `--name` explicitly AFAIK (or `-t`/`--tag`).

**Comment by thaJeztah** [comment]
@tianon `docker volume create` and `docker network create`

**Comment by tianon** [comment]
Network, yes, but volume has a "--name" flag:
https://docs.docker.com/engine/reference/commandline/volume_create/

**Comment by thaJeztah** [comment]
@tianon see https://github.com/docker/docker/issues/23345, https://github.com/docker/docker/pull/23830

**Comment by diogomonica** [comment]
I say this is the best path forward. /cc @aaronlehmann @aluzzardi @cyli @ehazlett

```
- Optional name for secrets (allowing `secret_id=$(genpass | docker secret create -f -`)
- Mandatory `-f`, and stdin using `-f -` (edited)
- common usage: `echo $WHTAVER | docker secret create —name secret.txt -f -`
```

**Comment by aluzzardi** [comment]
So the thing for `service create` is, like `run`, the positional argument is the image name.

Right now we have an inconsistency between `network` (positional) and `volume` (`--name`), and for secrets we're mirroring the network behavior.

It's going to be inconsistent either way ...

**Comment by thaJeztah** [comment]
Volumes uses positional now in 1.13 (`--name` is still there, but hidden though)

**Comment by yongtang** [comment]
PR #28629 addresses the issue of explicit `--file`/`-f`, and stdin using `-f -`. It does not cover the positional vs. `--name` part yet.

**Comment by ehazlett** [comment]
We should take #28629 and not make the name optional.  Secrets were explicitly built with names in mind and during design it was decided to have names.  #28629 solves the original issue of sending empty passwords and validation.

**Comment by diogomonica** [comment]
I'm fine with that too.
