### ISSUE TITLE
Docker daemon incorrectly reports "Error response from daemon: Cannot link to a non running container: /live-drupal AS /live-httpd/live-drupal" when container is live-drupal is running

### ISSUE THREAD

**Issue by rkeiii** [docker/docker#28937]
**Description**

**Steps to reproduce the issue:**
1. Start container live-drupal
2. Start container live-httpd with a link to the live-drupal container
3. Cause a fault in live-drupal which will also crash live-httpd
4. Start live-drupal container
5. Try to start live-httpd container and receive "Cannot link to a non running container" message even though the live-drupal container is running

**Describe the results you received:**
```
rone@app6:~$ sudo docker start live-httpd
Error response from daemon: Cannot link to a non running container: /live-drupal AS /live-httpd/live-drupal
Error: failed to start containers: live-httpd
rone@app6:~$ 
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
This seems to happen fairly reliably when a fault occurs in our live-drupal container.
```
user@app6:~$ sudo docker start live-drupal
live-drupal
rone@app6:~$ sudo docker start live-httpd
Error response from daemon: Cannot link to a non running container: /live-drupal AS /live-httpd/live-drupal
Error: failed to start containers: live-httpd
rone@app6:~$ sudo docker ps
CONTAINER ID        IMAGE                                                                      COMMAND                  CREATED             STATUS              PORTS                    NAMES
6dc80009a363        the.docker.repo.com/drupal:5.6.26-fpm   "php-fpm"                28 minutes ago      Up 28 minutes       0.0.0.0:9000->9000/tcp   live-drupal
602e1618874a        the.docker.repo.com/tomcat:8-jdk8                 "catalina.sh run"        7 days ago          Up 7 days           0.0.0.0:8085->8080/tcp   live-tomcat-auth
667a8709e0a7        the.docker.repo.com/tomcat:8-jdk8                 "catalina.sh run"        7 days ago          Up 11 hours         0.0.0.0:8084->8080/tcp   live-tomcat-service2
12f49e5c8d3b        the.docker.repo.com/tomcat:8-jdk8                 "catalina.sh run"        7 days ago          Up 7 days           0.0.0.0:8083->8080/tcp   live-tomcat-admin
48e9f8dc5794        the.docker.repo.com/tomcat:8-jdk8                 "catalina.sh run"        7 days ago          Up 7 days           0.0.0.0:8082->8080/tcp   live-tomcat-service
a74f7849dc19        the.docker.repo.com/tomcat:8-jdk8                 "catalina.sh run"        7 days ago          Up 7 days           0.0.0.0:8081->8080/tcp   live-tomcat-catalog
f6b1d8427657        the.docker.repo.com/tomcat:8-jdk8                 "catalina.sh run"        7 days ago          Up 7 days           0.0.0.0:8080->8080/tcp   live-tomcat-public
6e0df1c9b2ed        the.docker.repo.com/pgbouncer:live      "/bin/sh -c 'rm /var/"   7 days ago          Up 7 days           0.0.0.0:6432->6432/tcp   live-pgbouncer
6f9abc7e3cc5        the.docker.repo.com/haproxy:live        "haproxy -f /etc/hapr"   7 days ago          Up 7 days           0.0.0.0:8000->8000/tcp   live-haproxy
64acf7d0eae4        the.docker.repo.com/postfix:latest                "/bin/sh -c '/opt/ins"   7 days ago          Up 7 days           0.0.0.0:25->25/tcp       live-postfix
user@app6:~$ 
```

**Output of `docker version`:**

Docker version 1.12.3, build 6b644ec
```

**Output of `docker info`:**

```
Containers: 11
 Running: 10
 Paused: 0
 Stopped: 1
Images: 30
Server Version: 1.12.3
Storage Driver: zfs
 Zpool: ebs-zfs
 Zpool Health: ONLINE
 Parent Dataset: ebs-zfs/docker
 Space Used By Parent: 2073217024
 Space Available: 27070443520
 Parent Quota: no
 Compression: off
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: app6
ID: 2IRG:JFO4:XTNB:W6PN:XXBP:YAEU:TCA6:QZ3B:IAXL:TNCH:SFGX:GMD5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

Running into this on AWS EC2 instances in us-east-1 region under Ubuntu 16.04.

**Comment by thaJeztah** [comment]
After the `live-drupal` failed, did you create a _new_ container with the same
name to replace it?

The error message you describe is also shown if the original linked container
was _removed_ (not just stopped). It looks like this changed in docker 1.10; in
docker 1.9, the link was _removed_ from the containers that linked to it, whereas
in docker 1.10 and above, the link is kept in place, resulting in this error;


On docker 1.9

```bash
$ docker run -d --name one nginx:alpine
$ docker run -d --name two --link one:one nginx:alpine

$ docker inspect --format '{{json .HostConfig.Links}}' two
["/one:/two/one"]

$ docker stop one
$ docker rm one

# Here it's visible that the link was removed from container two
$ docker inspect --format '{{json .HostConfig.Links}}' two
null

# So it's able to restart without errors
docker restart two
two
```

On docker 1.10


```bash
$ docker run -d --name one nginx:alpine
$ docker run -d --name two --link one:one nginx:alpine

$ docker inspect --format '{{json .HostConfig.Links}}' two
["/one:/two/one"]

$ docker stop one
$ docker rm one

# After container "one" was removed, the link is still present on container "two"
$ docker inspect --format '{{json .HostConfig.Links}}' two
["/one:/two/one"]

# resulting in an error when restarting
$ docker restart two
Failed to kill container (two): Error response from daemon: Cannot restart container two: linknotrunning: Cannot link to a non running container: /one AS /two/one

# same error on docker 1.12, but slightly different error-message
Error response from daemon: Cannot restart container two: Cannot link to a non running container: /one AS /two/one
```


Given that the "legacy" links are being deprecated, and this error has been in
docker for multiple releases, we should discuss if it's worth to address this,
and will depend on the amount of changes required.

The classic "links" have a lot of issues; first of all, as can be seen here,
they are not "dynamic", so if you start a new container  with the same name,
it cannot take the place of the old container. Also, because environment-variables
are shared between containers, there is a security issue, because (for example)
passwords/credentials are accessible by any container that is linked.

Docker networking (available since Docker 1.10) replaces this feature, and allows
you to contact any container on the same user-defined netwok, using its _name_ as
hostname. Aliases are also supported, either "container-scoped" (using the same
syntax as `--link`) or "network scoped" aliases (`--network-alias`). Finally,
the docker networks are bi-directional, so containers can connect both ways,
which was not possible with legacy links.

For example, to have two containers communicate, simply create a network,
and give the containers a name (only containers that are explicitly named
can be accessed by their name);


```bash
docker network create my-network

docker run -d --net=my-network --name=one nginx:alpine

docker run -d --net=my-network --name=two nginx:alpine


# ping container one from inside container two;

$ docker exec two ping -c1 one

PING one (172.22.0.2): 56 data bytes
64 bytes from 172.22.0.2: seq=0 ttl=64 time=0.089 ms

--- one ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.089/0.089/0.089 ms



# ping container two from inside container one;

$ docker exec one ping -c1 two

PING two (172.22.0.3): 56 data bytes
64 bytes from 172.22.0.3: seq=0 ttl=64 time=0.064 ms

--- two ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.064/0.064/0.064 ms


# or even add a third container
$ docker run -d --name three nginx:alpine

# connect the third container to the network
$ docker network connect my-network three

# And it's accessible from all other containers on the `my-network` network
$ docker exec one ping -c1 three

PING three (172.22.0.4): 56 data bytes
64 bytes from 172.22.0.4: seq=0 ttl=64 time=0.086 ms

--- three ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.086/0.086/0.086 ms
```


Read the documentation on docker networks here;
https://docs.docker.com/engine/userguide/networking/

**Comment by rkeiii** [comment]
Thanks for the reply thaJeztah. I will look into swapping out legacy links for the network approach you've brought up. I didn't even know they were being deprecated or I would've moved away from them. I guess I should actually read the release notes sometime :)

**Comment by thaJeztah** [comment]
Thanks @rkeiii. I'll go ahead and close this issue, but I'll /cc @cpuguy83 to check if there's a possibility to easily fix the incorrect message, and include that in a future release

**Comment by nicodewet** [comment]
This has been said already, but just to re-iterate that deleting (docker rm) both offending containers fixed it for me (rolling with: _Docker version 17.12.1-ce, build 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3_).
