### ISSUE TITLE
Swarm mode: containers start on incorrect nodes

### ISSUE THREAD

**Issue by yashgt** [docker/docker#28930]
I started a stack using:

> docker deploy --compose-file docker-compose.yml e1

My docker-compose file instructs the **my_server** service to be hosted on **gol05854** and **my_client** to be hosted on **default**.

I have ensured that the **yashgt/client** and **yashgt/proc1** images are removed from default using **docker rmi**.
[docker-compose.txt](https://github.com/docker/docker/files/618759/docker-compose.txt)
[dockerinfo_default.txt](https://github.com/docker/docker/files/618765/dockerinfo_default.txt)

What I observe is that contrary to the constraints in the compose file, the my_server and my_client containers start on opposite nodes.

> [admin@gol05854 compose]$ docker ps
> CONTAINER ID        IMAGE                                                                                   COMMAND                  CREATED             STATUS              PORTS               NAMES
> b7c7471c1a07        yashgt/client@sha256:19c5a75057b1626f15a0a35420cbdf462e7a3bd6b3592084019c8cb433a83a59   "/bin/sh -c ./clie..."   12 seconds ago      Up 9 seconds                            e1_my_client_1.1.qgxpnpy02xlzaqvwrm0uewlo6

> docker@default:~$ docker ps
> CONTAINER ID        IMAGE                                                                                  COMMAND                  CREATED             STATUS              PORTS               NAMES
> fe637114378b        yashgt/proc1@sha256:2bfb426c533d7b6c08a0457d694ddadffde09589b6f558a399520bd0a6eb07cd   "/bin/sh -c './ser..."   8 seconds ago       Up 7 seconds                            e1_my_server.1.w15rir8tgfg4qw5azojiw8v2d

I checked that the default node has magically received the yashgt/proc1 image and it has no tag.

> docker@default:~$ docker images
> REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
> yashgt/proc1              <none>              1a022ceefad0        4 days ago          4.8 MB

I was expecting the swarm will force the default node to pull the yashgt/client image from registry and start it as a container.

**Comment by cpuguy83** [comment]
ping @dnephin 

I believe swarm mode has specific settings for constraints rather than what docker-swarm did which was just hijack environment variables.

**Comment by dnephin** [comment]
Yes, that's correct. Constraints need to be under `deploy.placement.constraints`

**Comment by yashgt** [comment]
Swarm mode lets you deploy using a bundle file or a compose file. Hence, both the options are expected to have a facility by which the placement constraints can be provided to docker for deployment. And the files are also expected to provide a facility to state that if an image is not available locally, it should be pulled from the registry. I was not able to find any documentation or example around deploy.placement.constraints. @dnephin. @cpuguy83 can you point me to the right documentation?

**Comment by dnephin** [comment]
The docs aren't merged yet, you can find them here: https://github.com/docker/docker.github.io/pull/716/files

**Comment by yashgt** [comment]
Thanks.
