### ISSUE TITLE
docker stats CPU usage greater than 100% times number of cores on Azure VM

### ISSUE THREAD

**Issue by jaredcnance** [docker/docker#28941]
**Description**

I have an Azure VM with 2 cores. From my understanding, the CPU % returned by docker stats can be greater than 100% if multiple cores are used. So, this should max out at 200% for this VM. However, I get results like this with CPU % greater than 1000%:

```
CONTAINER           CPU %               MEM USAGE / LIMIT       MEM %               NET I/O               BLOCK I/O             PIDS
545d4c69028f        3.54%               94.39 MiB / 6.803 GiB   1.35%               3.36 MB / 1.442 MB    1.565 MB / 5.673 MB   6
008893e3f70c        625.00%             191.3 MiB / 6.803 GiB   2.75%               0 B / 0 B             0 B / 24.58 kB        35
f49c94dc4567        0.10%               46.85 MiB / 6.803 GiB   0.67%               2.614 MB / 5.01 MB    61.44 kB / 0 B        31
08415d81c355        0.00%               28.76 MiB / 6.803 GiB   0.41%               619.1 kB / 3.701 MB   0 B / 0 B             11
03f54d35a5f8        1.04%               136.5 MiB / 6.803 GiB   1.96%               83.94 MB / 7.721 MB   0 B / 0 B             22
f92faa7321d8        0.15%               19.29 MiB / 6.803 GiB   0.28%               552.5 kB / 758.6 kB   0 B / 2.798 MB        7
2f4a27cc3e44        0.07%               303.8 MiB / 6.803 GiB   4.36%               32.52 MB / 20.27 MB   2.195 MB / 0 B        11
ac96bc45044a        0.00%               19.34 MiB / 6.803 GiB   0.28%               37.28 kB / 12.76 kB   0 B / 3.633 MB        7
7c1a45e92f52        2.20%               356.9 MiB / 6.803 GiB   5.12%               86.36 MB / 156.2 MB   806.9 kB / 0 B        16
0bc4f319b721        14.98%              101.8 MiB / 6.803 GiB   1.46%               138.1 MB / 64.33 MB   0 B / 73.74 MB        75
66aa24598d27        2269.46%            1.269 GiB / 6.803 GiB   18.65%   
```

**Steps to reproduce the issue:**
1. Provision an Ubuntu VM in Azure with 2 cores
2. Install Docker and start some containers -- one of the offending containers above is GitLab
3. Run docker stats

**Describe the results you received:**
CPU percent > 200% on 2 core machine

**Describe the results you expected:**
CPU percent should max at 100 times the number of cores (200%)

**Additional information you deem important (e.g. issue happens only occasionally):**
```
$ grep -c ^processor /proc/cpuinfo
2
```

However, `lshw` shows more than 50 disabled processors and I'm wondering if this is skewing the results.

**Output of `docker version`:**

```
root@server:~# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Mon, 10 Oct 2016 21:38:17 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Mon, 10 Oct 2016 21:38:17 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@server:~# docker info
Containers: 13
 Running: 13
 Paused: 0
 Stopped: 0
Images: 56
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.8.0-26-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.803 GiB
Name: david
ID: ABLT:GB2P:N76B:2EDT:CD6M:VWFY:QI6B:LQND:W55P:TLM3:PZGD:523C
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Azure Standard DS2 v2 (2 cores, 7 GB memory)

**Comment by jaredcnance** [comment]
Hey guys - I appreciate all the work you do and was wondering if someone could point me in the right direction so I can help get this resolved.

I **believe** this is preventing me from using Marathon as an orchestration service because it is killing containers when they exceed the allowed CPU (even though this is not possible).

Thanks

**Comment by misko321** [comment]
We have the same problem, we've got t2.micro EC2 machine with one cpu core, but docker reports over 300% of CPU utilization at some points of time.

**Comment by justincormack** [comment]
I don't think this is due to the offline CPUs on Azure (which are normal), as I can also replicate this on AWS, which does not have offline CPUs, with a t2.small, I get 1400% CPU sometimes.

**Comment by ijc25** [comment]
I installed a Debian Jessie VM and performed some experiments with a kernel build workload.

* 1/1 vCPU / 1024M RAM:
  * 3.16.0-4-amd64 (aufs) + docker-engine 1.11.2-0\~jessie: \~100% CPU usage :+1:
  * 3.16.0-4-amd64 (aufs) + docker-engine 1.12.6-0\~debian-jessie: \~100% CPU usage :+1:
  * 3.16.0-4-amd64 (aufs) + docker-engine 1.13.0-0\~debian-jessie: \~100% CPU usage :+1:
  * 4.9.0-0.bpo.1-amd64 (overlay2) + docker-engine 1.13.0-0\~debian-jessie: \~100% CPU usage :+1:
* 2/2 vCPU / 1024M RAM:
  * 4.9.0-0.bpo.1-amd64 (overlay2) + docker-engine 1.13.0-0\~debian-jessie: \~200% CPU usage :+1:
  * 4.9.0-0.bpo.1-amd64 (overlay2) + docker-engine 1.13.1\~rc1-0\~debian-jessie: \~200% CPU usage :+1:
* 1/4 vCPU (so one vCPU out of a max of 4, so with 3 available for hotplug) / 1024M RAM:
  * 3.16.0-4-amd64 (aufs) + docker-engine 1.13.1\~rc1-0\~debian-jessie: \~100% CPU usage :+1:
  * 4.8.0-0.bpo.2-amd64 (overlay2) + docker-engine 1.13.1\~rc1-0\~debian-jessie: \~400% CPU usage :-1:
  * 4.9.0-0.bpo.1-amd64 (overlay2) + docker-engine 1.13.1\~rc1-0\~debian-jessie: \~400% CPU usage :-1:

So at least for this VM the unplugged VCPUs does appear to be relevant.

For another datapoint my laptop (4/4 cores, 4.9.0-1-amd64, 1.13.1~rc1-0~debian-stretch) uses \~400% and so isn't demonstrating the issue (@justincormack -- I was wrong when we spoke IRL in thinking I could repro on my native laptop because I incorrectly thought I had only 2 cores when I actually have 4).

My next step is to bisect the kernel versions in http://snapshot.debian.org/package/linux-signed/ and http://snapshot.debian.org/package/linux/ and see if I can identify when this might have started.

**Comment by ijc25** [comment]
In the "1/4 vCPU / 1024M RAM" config:
* 4.9.0-0.bpo.1-amd64 (overlay2) with docker-engine's {1.12.6-0\~debian-jessie, 1.13.0-0\~debian-jessie, 1.13.1\~rc1-0\~debian-jessie} all show \~400% :-1:
* 4.7.0-0.bpo.1-amd64 (overlay2) with docker-engine 1.13.0-0\~debian-jessie: \~400% :-1:
* 4.6.0-0.bpo.1-amd64 (overlay2) with docker-engine 1.13.0-0\~debian-jessie: \~100% :+1:
* 4.5.0-0.bpo.2-amd64 (overlay2) with docker-engine 1.13.0-0\~debian-jessie: \~100% :+1:
* 4.1.0-0.bpo.2-amd64 (overlay2) with docker-engine 1.13.0-0\~debian-jessie: \~100% :+1:

So it looks like the issue arises somewhere between 4.6.0-0.bpo.1-amd64 (good) and 4.7.0-0.bpo.1-amd64 (bad).

**Comment by ijc25** [comment]
Bug was already present in kernel 4.7.0-rc3-amd64. Unfortunately that's as far as snapshot.debian.org will take me. I also took the chance to confirm that the issue is still present in 4.10.0-rc6-amd64.

**Comment by ijc25** [comment]
I wonder if this could be due to torvalds/linux@5ca3726af7f66a8cc71ce4414cfeb86deb784491 which looks to have gone in v4.7-rc1. (Found just by trawling the commits in v4.6..v4.7-rc3)

**Comment by ijc25** [comment]
Yes. I think torvalds/linux@5ca3726 has broken the code at [cli/command/container/stats_helpers.go#L184](https://github.com/docker/docker/blob/master/cli/command/container/stats_helpers.go#L184). Specifically `len(v.CPUStats.CPUUsage.PercpuUsage)` changed (in my case) from 1 to 4 (i.e. from reporting online cpus to reporting total possible cpus), corresponding to the CPU utilization going from 100% to 400%.

**Comment by justincormack** [comment]
@ijc25 aha! So should we get that patch reverted or fix the code?

**Comment by ijc25** [comment]
I'm not really sure why the code on our end is multiplying by the number of CPUs, I suspect knowing that would make the answer clear.

**Comment by ijc25** [comment]
I've not really been able to find a definitive answer as to what the units of the values given in sysfs are here, they look like they are either ns or `USER_HZ` increments but then I'm not sure why those would then need to be scaled by `nr_online_cpus` (and I don't see anything kernel side which does the opposite conversion).

On the flip side the numbers produced by the existing code did seem to be correct until the kernel change so the scaling seems correct in practice so I'm not sure what to think.

/cc @crosbymichael trawling git history looks like you originally wrote this (it's been moved around several times and refactored a bit but looks to be fundamentally the same code), do you have any insight?

**Comment by crosbymichael** [comment]
I think the logic should be changed to:

```go
cpuPercent = ((cpuDelta / systemDelta) * 100) * float64(len(v.CpuStats.CpuUsage.PercpuUsage))
```

**Comment by ijc25** [comment]
I don't think the existing `( X / Y ) * Z * 100.0` is meaningfully different from the proposed `( ( X / Y ) * 100 ) * Z` since the latter is just `( X / Y ) * 100 * Z` (in C maybe there would be some subtle or not-so-subtle differences due to type coercions happening in different orders, but I don't think that applies to Go).

> Maybe we need to account for active cpus vs all of them in the patch as well.

That seems most likely, although I haven't yet figured out if that can be done with the information at hand or if more data needs to be collected/plumbed through from the lower layers.

I [asked on LKML](https://lkml.org/lkml/2017/2/15/247) a few days back but haven't heard back yet.

**Comment by ijc25** [comment]
I looked into this a bit on Friday. The payload of the info provided by the `/containers/<id>/stats` ReST endpoint (which is what `docker stats` consumes) is something like:
```
{
  "cpu_usage": {
    "total_usage": 34379799796,
    "percpu_usage": [
      9709573338,
      12452334191,
      12217892267,
      0
    ],
    "usage_in_kernelmode": 4970000000,
    "usage_in_usermode": 28840000000
  },
  "system_cpu_usage": 7300960000000,
  "throttling_data": {
    "periods": 0,
    "throttled_periods": 0,
    "throttled_time": 0
  }
}
```
which I don't think contains sufficient information to be able to do anything sensible. IOW I think we are looking at an API bump here.

**Comment by isvogor-foi** [comment]
Any progress here?

**Comment by thaJeztah** [comment]
@isvogor-foi what version of Docker are you running? The issue you're commenting on was resolved in Docker 17.03.1.

**Comment by isvogor-foi** [comment]
I'm running v18+... Even when you do docker-ps, you can see the same thing happening, I've noticed that it goes up to 200%

**Comment by thaJeztah** [comment]
200% is correct if two cores are fully used

**Comment by isvogor-foi** [comment]
Hm.. alright, I'll look into it. Thanks!

**Comment by hellobinge** [comment]
i am having the same issue. I created a container, and limit its cpuset from core 0 to core 15. It is supposed to use at maximum 1600% cpu usage. But it is actually using 2500%+. And according the result of htop, it seems the container process are running on other cores. Is this a bug?
![screenshot from 2018-09-28 17-38-18](https://user-images.githubusercontent.com/6814841/46238904-160edd00-c346-11e8-8972-da89196376a2.png)
![screenshot from 2018-09-28 17-43-23](https://user-images.githubusercontent.com/6814841/46238905-160edd00-c346-11e8-92bb-4e5180939095.png)
![screenshot from 2018-09-28 17-43-36](https://user-images.githubusercontent.com/6814841/46238906-160edd00-c346-11e8-83a6-ef5055954320.png)

**Comment by lth2015** [comment]
> i am having the same issue. I created a container, and limit its cpuset from core 0 to core 15. It is supposed to use at maximum 1600% cpu usage. But it is actually using 2500%+. And according the result of htop, it seems the container process are running on other cores. Is this a bug?
> 
> result from docker stats
> ![screenshot from 2018-09-28 17-38-18](https://user-images.githubusercontent.com/6814841/46238904-160edd00-c346-11e8-8972-da89196376a2.png)
> result from docker inspect
> ![screenshot from 2018-09-28 17-43-23](https://user-images.githubusercontent.com/6814841/46238905-160edd00-c346-11e8-92bb-4e5180939095.png)
> result from htop
> ![screenshot from 2018-09-28 17-43-36](https://user-images.githubusercontent.com/6814841/46238906-160edd00-c346-11e8-83a6-ef5055954320.png)
> 
> @thaJeztah

I have the same problem.

![1e848d4a-84f4-4f0d-a28a-1cdcb8532a02](https://user-images.githubusercontent.com/12841814/48914222-b5b79a00-eeb5-11e8-8ca5-d41ab7efeb7f.png)

![82b9426c-cd7c-48e3-a7d3-42a107b372a5](https://user-images.githubusercontent.com/12841814/48914235-c10ac580-eeb5-11e8-93d0-ddee228e882a.png)

**Comment by thaJeztah** [comment]
@hellobinge @lth2015 could you open a new issue with details as requested in the issue template? (at least output from `docker version` and `docker info`, but also any additional information you have (logs, perhaps output of the [`check-config.sh`](https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh) script

**Comment by thaJeztah** [comment]
Also check if `docker info` doesn't show a warning (`WARNING: No cpuset support`), because in that case the cpuset option won't take effect.

**Comment by lth2015** [comment]
OS version:
NAME="Ubuntu"
VERSION="14.04.3 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.3 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

-----------------------------------------

uname -a
Linux sjsa-k8s-node01 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

-----------------------------------------
docker info:

Containers: 241
 Running: 234
 Paused: 0
 Stopped: 7
Images: 1622
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16804
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 251.8 GiB
Name: sjsa-k8s-node01
ID: ECMN:RDMS:Q24L:6ON2:6OU5:VBYQ:GPOR:E2RN:3JCN:OESP:XYT2:UBPM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8


-----------------------------------------

docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

-----------------------------------------
we use kubernetes(1.4.9)
cpu.shares/cpu.cfs_quota_us/cpu.cfs_period_us:

docker_id: b44d524a89e6034999108791db3da8527924bb8dfca47b2a5d0bd876a63bf42e
cpu.cpu_period_us: 100000
cpu.cpu_quota_us: 200000
cpushares: 2048

docker_id: b8c2ff4fc9b5426970e879a51caeef6b1ab120f6eed6ef2406a4d1c1f00f9c19
cpu.cpu_period_us: 100000
cpu.cpu_quota_us: 200000
cpushares: 204

docker_id:  bec7143877eb1f2e0cf1bdb38bc7ac43c4427428c0c2ae66bfb851901eedd12f
cpu.cpu_period_us: 100000
cpu.cpu_quota_us: 20000
cpushares: 51


-----------------------------------------

### **In addition, the load of our physical machine will rise very high, causing the physical machine to crash, and no reason is found.**

**Comment by lth2015** [comment]
> @hellobinge @lth2015 could you open a new issue with details as requested in the issue template? (at least output from `docker version` and `docker info`, but also any additional information you have (logs, perhaps output of the [`check-config.sh`](https://raw.githubusercontent.com/moby/moby/master/contrib/check-config.sh) script

I have open a new issue: [#38253](https://github.com/moby/moby/issues/38253)  .
Thanks for your help.

**Comment by shuaichang** [comment]
> 200% is correct if two cores are fully used
> […](#)
> On 16 Aug 2018, at 21:28, Ivan Švogor ***@***.***> wrote: I'm running v18+... Even when you do docker-ps, you can see the same thing happening, I've noticed that it goes up to 200% — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

From the docker stats document https://docs.docker.com/engine/reference/commandline/stats/ it defines "CPU % and MEM % | the percentage of the host’s CPU and memory the container is using
-- | --", so it sounds like it should never go above 100% even the host has 2 cores, would appreciate if you can clarify the 200% behavior.


I also had hard time understanding why `len(v.CPUStats.CPUUsage.PercpuUsage)` was multiplied after the `deltaUsage/deltaSystemUsage * 100`, looked through the thread but was not able to figure it out.
