### ISSUE TITLE
[Feature request] Support plugins in `docker inspect`

### ISSUE THREAD

**Issue by albers** [docker/docker#28946]
#23614 added support for "all" types to `docker inspect`.
Now that the plugin API is no longer experimental, plugins could also be inspectable from `docker inspect`.
This seems natural because just like the other supportet types, there is also a `docker plugin inspect`.

I suggest to add `docker inspect --type plugin`.

Related: #28735, #28789. Maybe @yongtang is interested?

**Comment by yongtang** [comment]
@albers Added a PR #28967 for that. Please take a look.
