### ISSUE TITLE
the bridge network doesn't respect --link'd containers

### ISSUE THREAD

**Issue by skelterjohn** [docker/docker#28947]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

When adding a container to the bridge network using 'docker network connect --link', containers using that network cannot address the linked container by its linked name. When doing the same process with a new network, the linked container can be addressed by its linked name.

**Steps to reproduce the issue:**
To reproduce the network not behaving as expected:

```
$ docker run -d -p 8080:8080 --name serv skelterjohn/http
$ # first disconnect it, since it's automatically added without --link and with an IP address
$ docker network disconnect bridge serv
$ docker network connect --link serv:serv bridge serv
$ docker run --network bridge curl serv:8080
curl: (6) Couldn't resolve host 'serv'
```

skelterjohn/http creates a simple container that serves "Hello, world!" on port 8080. skelterjohn/curl creates a simple container that has a 'curl' entrypoint.

If instead of serv:8080 I use the IP address found in 'docker network inspect bridge', it is able to connect successfully.

If, instead of bridge, I make a new network, things work.

```
$ docker run -d -p 8080:8080 --name serv skelterjohn/http
$ # first disconnect it, since it's automatically added without --link and with an IP address
$ docker network create mynetwork
$ docker network connect --link serv:serv mynetwork serv
$ docker run --network mynetwork curl serv:8080
Hello, world!
```

**Describe the results you received:**

When using bridge, I was not able to connect to the container using the name I provided with the --link option.

**Describe the results you expected:**

I expected to be able to connect.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 25
 Running: 2
 Paused: 0
 Stopped: 23
Images: 6
Server Version: 1.12.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-47-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.613 GiB
Name: foobar
ID: IK4B:7YFO:ZDYA:OS3P:XJ5T:UJYW:6P3O:X756:RZ2C:FDO2:GEFP:43GN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: skelterjohn
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

ubuntu trusty on GCE.

**Comment by cpuguy83** [comment]
`--link` is local to the container, not bound to the network.
If you want to provide an alias to the joining container that works across the network, use `--alias`.

I'm also not sure if these are meant to work with the `bridge` network, though.

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by skelterjohn** [comment]
"Error response from daemon: Network-scoped alias is supported only for containers in user defined networks"

Regarding --link being local to the container - is the fact that it worked with mynetwork in the example above the bug? :(

**Comment by cpuguy83** [comment]
@skelterjohn No, because the container is already named "serv", there's no linking required to get the name.

**Comment by mavenugo** [comment]
@skelterjohn I think you are mixing the default Service Discovery feature of user-defined networks with the --link functionality. The DNS based Service Discovery feature is NOT enabled on default bridge network.

The --link functionality as @cpuguy83 explained is per-container. And you are using it incorrectly. `--link` should be configured on the consuming container and not the serving container.

Also `--net-alias` is supported only on user-defined networks (not on default bridge network).

In your case, pls try using the `--link` in the consuming `curl` container.

**Comment by skelterjohn** [comment]
I should give the full context of what I'm trying to do.

I'm on the team that created the Google Container Builder service, and the way people build containers using the service is they (via a list of build steps that can also do other things) run 'docker build' on our VM.

Now, a build step is just a container that we run for you. It so happens that we provide one with 'docker' as its entry point (and we run it with the docker daemon's socket volume-mounted in). Then, to build an image they use that container and specify the args. So, ['build', '.', '--tag=foo'], for example.

We also provide credentials to the build by spoofing the GCE metadata server, which is hosted at metadata.google.internal if you're already on a GCE machine. But *we* own that machine, so the "real" metadata server will not have credentials for the customer's build. Instead, we run another container that acts like the real metadata, but has customer information instead.

For build steps, we --link the metadata container to the step container, and so it looks like metadata is available and has the customer's information without them doing anything special.

Unfortunately, when the build step turns around and does a 'docker build', the containers created by 'docker build' to create layers do not have this --link. Asking them to specify a --network=cloudbuild is a little annoying for DX, considering this is supposed to be transparent and "just work".

So, I wanted to add it to the default network.

If aliases can't be used in the bridge network, is there some way to make another network the default?

**Comment by skelterjohn** [comment]
I was just referred to https://docs.docker.com/engine/userguide/networking/default_network/build-bridges/ which seems to provide the guidance I seek.
