### ISSUE TITLE
Filter option and exit code

### ISSUE THREAD

**Issue by y3ti** [docker/docker#28951]
Hi,

*Nix grep command uses exit codes. 
- grep returns `0` when string was found
- grep returns `1` when string was not found

For example:

```
$ (echo "foo" | grep foo > /dev/null) && echo "found" || echo "not found"
found

$ (echo "foo" | grep bar > /dev/null) && echo "found" || echo "not found"
not found
```

It would be nice to have the same functionality for docker filter commands. Currently every `docker [command] --filter` return 0.

```
$ docker network ls
NETWORK ID          NAME                  DRIVER              SCOPE
ede94df542af        bridge                bridge              local               
2c10f1247c63        host                  host                local               
fc7a3b9043ec        none                  null                local               

$ docker network ls --filter 'name=bridge' > /dev/null; echo $? 
0

$ docker network ls --filter 'name=not-existed' > /dev/null; echo $?
0
```

Example practical use cases: create a new network `foo` if not exists

```
docker network ls -f 'name=^foo$' > /dev/null || docker network create foo
```

**Comment by thaJeztah** [comment]
I think this is a duplicate / closely related to https://github.com/docker/docker/issues/27657, but was rejected https://github.com/docker/docker/issues/27657#issuecomment-258271259, could you have a look if that solution works for you?

**Comment by y3ti** [comment]
@thaJeztah thank you for the links. This helped me with understand your point of view.

I think that `docker inspect --type` resolves most of my problems and/or my use cases except `docker networks`. Is there a chance to add a new type (network) to `docker inspect` command, I mean:

`docker inspect --type network`

**Comment by thaJeztah** [comment]
That's coming in docker 1.13; https://github.com/docker/docker/pull/23614 (if you have a machine for testing, release candidates are available now https://github.com/docker/docker/releases)

For _performance_, `docker network inspect` may be a better option, as it will skip trying all different kind of objects

**Comment by y3ti** [comment]
@thaJeztah awesome! I will wait for docker 1.13. 
Thank you again. I think we can close this issue.

**Comment by thaJeztah** [comment]
Thanks @y3ti, and sorry that we could not address your request.
