### ISSUE TITLE
Docker -rm implementation for run -d option

### ISSUE THREAD

**Issue by codingground** [docker/docker#28970]
Hi Docker team,

Thanks for your usual support. Since long time we are struggling in deleting docker instances and many time daemon is getting hanged while removing docker instances running in the background. It continues showing "Removal in progress" and then number of instances get piled up.

Is there any technical reason behind not implementing instance auto removal mechanism while instance is running in the background? It will be really helpful if we can provide -rm option with -d option as well so that as soon as we exit out of the instance then it should get removed automatically. This will be helpful in a an environment where large number of instances are being created and removed every minutes. You may ask where it is required, so you can check following URL [CODINGGROUND](https://www.tutorialspoint.com/codingground.htm) where we provide online terminals and IDE for different languages where users can come do some coding practical online. Because its open screen so many people keep launching these IDEs and when any IDE is passive for 10-15 minutes we exit out of it.

Thanks for considering my request and looking into a possibility for auto removal for background instances.

**Comment by coolljt0725** [comment]
@codingground  it's implemented in https://github.com/docker/docker/pull/20848 and the coming release 1.13.0  will have this.

**Comment by AkihiroSuda** [comment]
Closing this issue, but feel free to reopen if #20848 is not sufficient

**Comment by codingground** [comment]
Thank you sir for your quick response on this. May I know any tentative timelines to release 1.13.0?
