### ISSUE TITLE
Error starting daemon: Couldn't create Tag store repositories-devicemapper

### ISSUE THREAD

**Issue by gl328518397** [docker/docker#28977]
docker version 1.8
when I restart ,It err
![qq 20161130160235](https://cloud.githubusercontent.com/assets/14244945/20744351/7b3a89c4-b716-11e6-95ce-9373b9fcc883.png)

**Comment by gl328518397** [comment]
hello ,I have fix it 。。I found the file "/var/lib/docker/repositories-devicemapper" is not json format 。 So, I     edit the file to current JSON format  ..then restart docker ,and it works >..
but ，some images  tag message show <none> ..

but ，i never change the file ,so ，I don’t know  why the file format is err ..(2016-12-1)

**Comment by wujianlin** [comment]
the same error i meet in docker 1.11. but the file is /var/lib/docker/image/devicemapper/repositories.json. this file is not json format. i never change this file. is any process will change this file?

**Comment by wujianlin** [comment]
@gl328518397, i hope you can help me.
