### ISSUE TITLE
[1.12.3] What is the meaning of the field "peers" in the command "docker network inspect"?

### ISSUE THREAD

**Issue by Wsine** [docker/docker#28984]
I run the command as below:
```
# sudo docker network inspect --format='{{json .Peers}}' ingress | python -m json.tool
[
    {
        "IP": "192.168.10.232",
        "Name": "raspberrypi-1e1ce7a98c58"
    },
    {
        "IP": "192.168.10.170",
        "Name": "raspberrypi_wm2-5c23aadd97fb"
    },
    {
        "IP": "192.168.10.143",
        "Name": "raspberrypi_wm1-8599f654a2ad"
    },
    {
        "IP": "192.168.10.210",
        "Name": "raspberrypi_wm-ab4a261b0b1f"
    }
]
```

I wonder what is the meaning of the suffix of the name, like “1e1ce7a98c58”？
I searched almost all the related information(nodeId, serviceId, containerId...) but I found nothing. Could you please explain the meaning behind it?
thx

**Comment by thaJeztah** [comment]
hm, yes, that's confusing, this was added in https://github.com/docker/docker/pull/28078, and although not mentioned it's the _node_ ID ("Node name is of the format `<hostname>-<unique ID>`."), it would be what's expected, but they don't match the node ID indeed


```
docker node ls
ID                           HOSTNAME       STATUS  AVAILABILITY  MANAGER STATUS
71izy0goik036k48jg985xnds    swarm-test-02  Ready   Active        Reachable
79y6h1o4gv8n120drcprv5nmc    swarm-test-03  Ready   Active        Leader
btc6isqzpiuvu7wmg8fhabt1t    swarm-test-04  Ready   Active
d6axrxvko4zkp1w0t1aa4elaz *  swarm-test-01  Ready   Active        Reachable
```

```json
"Peers": [
    {
        "Name": "swarm-test-04-cebc66a5ae06",
        "IP": "10.133.24.169"
    },
    {
        "Name": "swarm-test-02-eca03e45bf4f",
        "IP": "10.133.24.158"
    },
    {
        "Name": "swarm-test-01-f1379758d800",
        "IP": "10.133.24.133"
    },
    {
        "Name": "swarm-test-03-776f99d32de1",
        "IP": "10.133.24.159"
    }
]
```

ping @sanimej could you have a look?

**Comment by sanimej** [comment]
@Wsine Peers displayed in the `network inspect` output are the members of the cluster that currently have a task on that network. This helps to identify if any node has issues in joining the gossip cluster. Such nodes would be missing from the peers list even if it has a task attached to that network.

Peer name here is the node's name in the gossip cluster. The unique-id that is appended to the `hostname` of the node is to make sure the node has a unique name in the cluster if the `hostname` happens to conflict with some other node. Its mentioned in the [documentation](https://github.com/docker/docker/blob/master/docs/reference/commandline/network_inspect.md)

**Comment by sanimej** [comment]
@thaJeztah The node name used in the gossip cluster is not the same as the `node ID` allocated by the swarm manager.

**Comment by thaJeztah** [comment]
@sanimej would it be possible to use that ID? That ID should already be unique in the cluster, and would allow verifying which nodes are connected, and which ones are missing. The current identifiers are unique, but there's no way to lead them back to the correct node

**Comment by Wsine** [comment]
I agreed with @thaJeztah that "would it be possible to use that ID?". Could you please tell me where to set the peers's name field?

**Comment by ling-pan** [comment]
I meet the same problem too. How can I modify the unique ID to be the node's own id?

**Comment by Wsine** [comment]
I do want to know the answer sincerely. Could you @sanimej @thaJeztah  please tell me where to set the peers's name field?

**Comment by sanimej** [comment]
@Wsine Its an internal name that doesn't have an exposed UX. For overlay networks gossip layer has always been using the peer name for control plane information exchange. In 1.13 its displayed in the `network inspect` for troubleshooting purposes.

**Comment by Wsine** [comment]
@sanimej thank you for replying. I found a solution for my problem. Maybe I should learn more about the design of docker swarm. Thanks again.

**Comment by mavenugo** [comment]
Closing this as the question is answered.

**Comment by perrefe** [comment]
> @Wsine Peers displayed in the `network inspect` output are the members of the cluster that currently have a task on that network. This helps to identify if any node has issues in joining the gossip cluster. Such nodes would be missing from the peers list even if it has a task attached to that network.
> 
> Peer name here is the node's name in the gossip cluster. The unique-id that is appended to the `hostname` of the node is to make sure the node has a unique name in the cluster if the `hostname` happens to conflict with some other node. Its mentioned in the [documentation](https://github.com/docker/docker/blob/master/docs/reference/commandline/network_inspect.md)

There is not much information about this around the internet (for medium/advanced users), and I got here because I'm having trouble with the routing mesh connectivity in a medium size cluster (10 nodes with 3 workers in it). To clarify myself on what could be going on, before opening an issue, I have this question:

When a service is attached to an overlay network created by me as a part of a stack, the node where the container starts MUST appear in the peers list of the network ?

What if not? , Is there a special condition that I don't know yet?

Thanks!

**Comment by AdrianSkib** [comment]
@perrefe Did you ever find more info about this? I've noticed that whenever DNS lookup by service name fails the node that the service runs on isn't in the peers list. I'm unable to find any information about what is required to end up in the peers list, and there are no error messages that I can see anywhere in the swarm indicating that something is wrong, although it clearly is.
