### ISSUE TITLE
Dockerfile with trailing backslash in comment ignores next line

### ISSUE THREAD

**Issue by cpetschnig** [docker/docker#28982]
A Dockerfile with such two lines will not execute the second line:

    RUN echo foo # blah \
    RUN echo bar

Output:

    Step 19 : RUN echo foo # blah RUN echo bar
     ---> Running in 715c5b4577d1
    foo

I am sure this can be identified as expected behaviour by the parser, yet it causes trouble when you try to find the error in your file.

**Comment by duglin** [comment]
this is because comments can only appear at the start of lines, not in the middle.  So we don't actually see the "#" in there at all. 

See:  https://docs.docker.com/engine/reference/builder/   and search for "comment", in particular the RUN example in there.

**Comment by cpetschnig** [comment]
Thank you
