### ISSUE TITLE
Support for non-RFC compliant hostnames broken prematurely

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#28985]
This is a continuation of #27275

In 1.11 a change was introduced to validate that hostnames are RFC compliant (#20566, https://tools.ietf.org/html/rfc1123).
This change did not follow the normal deprecation policy and broke users using non-RFC compliant hostnames.

Affected versions are Docker 1.11 - 1.13-rc2

Ping @thaJeztah 
@vdemeester who I believe introduced version checking at least in the API to only valid in api versions >= 1.24 (1.12+)

**Comment by cpuguy83** [comment]
Also some relevant discussion here: #23729

**Comment by vdemeester** [comment]
@cpuguy83 yes, I though it was versionned with https://github.com/docker/docker/pull/23740.

**Comment by vdemeester** [comment]
I'll work on a fix for 1.12.x and master/1.13.x so it's just a warning and applying depreciation policy :wink:

**Comment by masonoise** [comment]
Please do announce a 1.12.x version with this fixed, we're waiting on it in order to be able to upgrade from 1.10.3. Thanks.

**Comment by cpuguy83** [comment]
FYI, a revert for this validation is merged to master and 1.12.x

**Comment by thaJeztah** [comment]
Looks like all PR's to revert this change were merged, so I'll close this issue.

This will be fixed in 1.12.4, and 1.13
