### ISSUE TITLE
Dockerignore multi-dir wildcard issue

### ISSUE THREAD

**Issue by s0x** [docker/docker#29014]
## Description

The multi-dir wildcard does not behave like described in the documentation. In case a particular file should be ignored, the pattern matches every file which ends with the same name also.

## Steps to reproduce the issue:
1. Create a file .example and some.example in the root or any subdirectory
2. Add "**/.example" to you .dockerignore
3. Create a Dockerfile which includes a copy command such as `COPY . /`
2. Build the image

## Describe the results you received:
Neither .example nor some.example is added to the image

## Describe the results you expected:
some.example should be present in the image

## Additional information:

In case you work with gradle projects, this behavior is quite important. (e.g. exclude .gradle but not settings.gradle or even build.gradle)

This issue seems to be present since Oct 14, 2015 (eddb14a). As I can see it, this is when the multi-dir wildcard was introduced.

File `pkg/fileutils/fileutils.go`:

Line 172 states: Treat **/ as ** so eat the "/"

Furthermore the documentation for this is quite misleading:

```
Matching is done using Go’s filepath.Match rules. A preprocessing step removes
leading and trailing whitespace and eliminates . and .. elements using Go’s
filepath.Clean. Lines that are blank after preprocessing are ignored.
```

Line 135 on the other hand states that the filepath.Match is not used at all because of "some really weird rules". Line 141 makes use of its Error Message only.

**Comment by thaJeztah** [comment]
ping @duglin

**Comment by duglin** [comment]
I'm on it....
