### ISSUE TITLE
Unable to run any containers on Windows server 2016 Evaluation,  client hangs

### ISSUE THREAD

**Issue by renerchen** [docker/docker#29017]
Description

On a clean installed Windows 2016 server Evaluation, I'm not able to run containers ( WindowsServerCore). 
Steps to reproduce the issue:

Follow install instructions: https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_server
Run docker pull microsoft/dotnet-samples, works...
Run docker run microsoft/dotnet-samples , hangs for ever until dockerd is restarted....
CTRL+C to stop and try to run any client command like docker ps and that also hangs.
Then open another powershell, restart docker:
Restart-service docker,  

PS C:\Users\Administrator> docker ps -a
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS               NAMES
5000f47478e8        microsoft/sample-dotnet   "dotnet dotnetbot.dll"   3 hours ago         Created                                 fervent_knuth

The container status is created. 
Does anyone know why?

**Comment by renerchen** [comment]
I had updated windows with  KB3194496, it works!

**Comment by thaJeztah** [comment]
Looks like the issue was resolved, so I'll close this
