### ISSUE TITLE
which is the default mode of macvlan in docker 1.12

### ISSUE THREAD

**Issue by hallwin** [docker/docker#29016]
docker version :1.12.3

question:

as we know, macvlan has 4 mode(VEPA/bridge/private/Passthru)

what's the mode in docker1.12 ?

Thank you !

**Comment by aboch** [comment]
bridge

https://github.com/docker/docker/blob/v1.12.3/vendor/src/github.com/docker/libnetwork/drivers/macvlan/macvlan_network.go#L44

**Comment by aboch** [comment]
Closing as answered
