### ISSUE TITLE
Improve docker pull exit codes

### ISSUE THREAD

**Issue by pruje** [docker/docker#29038]
Hello

Until now (v. 1.12.3), if you pull an existing image from a private registry but you are not authenticated, the `docker pull` command returns:
```
$ docker pull privateregistry.com/existingimage
Using default tag: latest
Pulling repository privateregistry.com/existingimage
Error: image existingimage:latest not found
```
with exit code = 1.

As is it, we cannot determine if it fails because image really does not exists, or if it's because we are not authenticated.

It should return a specific message like:
```
Error: please log in to privateregistry.com before pull
```
with a specific exit code.

Thanks and keep on the great work

**Comment by vieux** [comment]
@pruje :wave: :fr: 

I think that's expected, we don't want to people to detect private images names via brute force.

That's why whether the image exists or not, you get the same error.

**Comment by thaJeztah** [comment]
note that for 1.13, improvements were made where (if the user has access to a repository), an alternative message is shown if the image really doesn't exist. See https://github.com/docker/docker/pull/28235; would that address your issue?

**Comment by pruje** [comment]
Hi @vieux 🇫🇷 !
Thanks @thaJeztah, that's perfect for me.
Can we close this issue or close it when 1.13 will be released?

**Comment by thaJeztah** [comment]
I'll close this issue, as it's already fixed by https://github.com/docker/docker/pull/28235, but I'll add it to the milestone to make it easier to find "which release" fixed it
