### ISSUE TITLE
Docker for OSX, maven download slow

### ISSUE THREAD

**Issue by Noodle05** [docker/docker#29037]
I'm trying to create a java project building docker, it will use svn checkout project and using maven to build it.

Same docker image works pretty good on Linux host, but maven download extremely slow/stucks on OSX host.

I tried to check network connection status from inside the docker when it stuck, and find that maven TCP connection stuck at SYN_SENT state for very long time. This is not always happen. For example, after I restart Docker engine on OSX, it will running fine for a while. If I wait long enough, it will slowly move and then run fine for a while too. But if your have lot dependencies, it will be happened every other run.

While maven download stuck, I still can download with "curl" even from same maven repo host.

Not sure if this is maven issue or Docker issue, but since same docker running fine on Linux host, I guess this maybe a xhyve network issue on OSX?

OSX version: 10.11.6

docker info

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 40
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 120
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 23.5 GiB
Name: moby
ID: xxxxxxxxxxxxxxxxxxxx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 59
 Goroutines: 91
 System Time: 2016-12-01T19:32:03.128567602Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment]
Can you open an issue on https://github.com/docker/for-mac/issues rather than here as it is specifically related to Docker for Mac. I will close this one as we can't help here as it does not seem to be a Docker Engine issue.
