### ISSUE TITLE
docker 1.13 breaks restart policy: maximum restart count must be a positive integer

### ISSUE THREAD

**Issue by Bekt** [docker/docker#29035]
**Description**
**Steps to reproduce the issue:**
1. Get docker v1.13 on Docker for Mac
2. `docker run -d --restart=on-failure nginx`

**Describe the results you received:**
```
docker: Error response from daemon: maximum restart count must be a positive integer.
See 'docker run --help'.
```

**Describe the results you expected:**
* Container is started without a problem.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

http://pastebin.com/raw/ckKsKLNh

**Additional environment details (AWS, VirtualBox, physical, etc.):**
* Docker for Mac
* The same thing works with docker v1.12.

**Comment by thaJeztah** [comment]
Confirmed, looks like this is what's sent by the client;

```
    "RestartPolicy": {
      "MaximumRetryCount": 0,
      "Name": "on-failure"
    },
```

I'll check what the 1.12 client sends to see if it's the client that changed, or just the validation

**Comment by thaJeztah** [comment]
Validation was changed in https://github.com/docker/docker/commit/94e95e4711643640701bd614902e75a2d01f12c5 (https://github.com/docker/docker/pull/24073)

**Comment by thaJeztah** [comment]
1.12 sends the same;

```
   "RestartPolicy": {
      "MaximumRetryCount": 0,
      "Name": "on-failure"
    },
```

And, `0` should be valid (as "unlimited"), so this should be updated. Let me open a PR to fix

**Comment by aaronlehmann** [comment]
> And, `0` should be valid (as "unlimited"), so this should be updated. Let me open a PR to fix

This should probably be the case if it matches the previous behavior, but I do find this a bit confusing. I would expect `"MaximumRetryCount": 0` to mean "no retries".

**Comment by thaJeztah** [comment]
@aaronlehmann I think that's a separate discussion; what's the alternative for "unlimited"? We've had quite a number of issues trying to implement that (`-1`, `not set`, `0`, where distinguishing between `0`, and `not set` has been a nightmare as well)

**Comment by aaronlehmann** [comment]
Yes, it's tricky in general.

-1 or unset would be slightly more obvious to me for "unlimited".

I don't want to derail this discussion, though.

**Comment by Bekt** [comment]
>I would expect "MaximumRetryCount": 0 to mean "no retries"

I think it's more confusing to run the `on-failure` restart policy with no retries (0).

**Comment by Bekt** [comment]
Thanks for quick fix guys 👍

**Comment by thaJeztah** [comment]
Thanks for reporting, and testing the RC's!
