### ISSUE TITLE
swagger generation is broken

### ISSUE THREAD

**Issue by vieux** [docker/docker#29045]
since https://github.com/docker/docker/pull/28840/ got merged, the swagger generation is not working as expected.

* doing a `make swagger-gen` now generated a `api/types/containers` with an `s` owned by root instead of updating the files in `api/types/container`
* `rm api/types/volume/volumes_create.go && make swagger-gen` doesn't' generate the missing file.

looks like tags have a effect on the folder where the types are generated and the above PR changed them.

/cc @bfirsh @dnephin 

it blocks https://github.com/docker/docker/pull/29002

**Comment by bfirsh** [comment]
A fix: https://github.com/docker/docker/pull/29071
