### ISSUE TITLE
Docker-git arch linux (antergos) docker-proxy error

### ISSUE THREAD

**Issue by anquegi** [docker/docker#29057]
I get this error running docker:

 2016-12-02 09:30:15 ⌚ |ruby-2.3.0@learn| toshiba-antergos in ~
○ → docker --version
Docker version 1.14.0-dev, build a756c1a

 2016-12-02 09:29:38 ⌚ |ruby-2.3.0@learn| toshiba-antergos in ~
○ → docker run --name redis-antifraude -p 6379:6379 -d redis:3.0.7
Unable to find image 'redis:3.0.7' locally
3.0.7: Pulling from library/redis
386a066cd84a: Pull complete 
769149e3a45c: Pull complete 
1f43b3c0854a: Pull complete 
70e928127ad8: Pull complete 
8d5b99cac616: Pull complete 
7f6b341e7d04: Pull complete 
9fce0b703d71: Pull complete 
572fb30a08f6: Pull complete 
Digest: sha256:17c49dd2dbb4c8c980d27173fd2ba9fe4aa0ace7557336228d3b2a29af3713e1
Status: Downloaded newer image for redis:3.0.7
048cb96a1fe9a839864db822592b046a5c5c7a198c2f4754f214b070e124470e
docker: Error response from daemon: driver failed programming external connectivity on endpoint redis-antifraude (189634a23114a98bde28cdb4be850fd2aef15ec7e5420b1ec156cb4238ec354e): exec: "docker-proxy": executable file not found in $PATH.

**Comment by justincormack** [comment]
Looks like the package is not configured correctly there should be a `docker-proxy` executable available. We do not provide packages for Arch at present, so you need to file an issue with the upstream packager.
