### ISSUE TITLE
Docker issue with Hyper-V, vCloud

### ISSUE THREAD

**Issue by samuel-peers** [docker/docker#29079]
On a Windows 10 Enterprise (version 1607, build 14393.447) VM on vSphere, we receive the following error when trying to start a windows container (e.g. docker run microsoft/nanoserver):

`...failure in a Windows system call: No hypervisor is present on this system. (0xc0351000)...`

YES the hypervisor feature is on.
YES virtualization is enabled in the BIOS.
I also followed instructions in this [article ](https://www.derekseaman.com/2014/06/nesting-hyper-v-2012-r2-esxi-5-5.html)to no avail.

I followed these [instructions ](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/quick_start/quick_start_windows_10)to install Docker.

The VM was created in vCloud Director, yes hardware-assisted CPU virtualization is exposed.

**Output of `docker version`:**
```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   3c5e09f
 Built:        Sat Nov 12 03:56:46 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-dev
 API version:         1.25
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          3c5e09f
 Built:               Sat Nov 12 03:56:46 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```

**Output of `docker info`:**
```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 1
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 5
Total Memory: 8 GiB
Name: w10-Docker
ID: PGH2:AG7E:JV4O:BH5Z:ZMLA:5IRH:XY7X:VIBB:DXMY:WHQJ:R2LE:PCNX
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by friism** [comment]
@samuel-peers Can you create a normal Hyper-V VM (eg. whatever you have handy, Ubuntu some sort of Windows) in the nested Windows 10 VM?

**Comment by samuel-peers** [comment]
@friism I am able to create Hyper-V VM using Hyper-V manager, but I get the following error when I run it:

`Failed to start the virtual machine 'test' because one of the Hyper-V components is not running.`

So maybe this is more of a Hyper-V issue than a Docker issue.

**Comment by friism** [comment]
@samuel-peers ok, thanks for confirming.

@thaJeztah recommend closing this issue as un-related to Docker.

**Comment by thaJeztah** [comment]
Agreed, looks like this is not a docker issue, but feel free to continue the conversation
