### ISSUE TITLE
Build arg validation changes the API

### ISSUE THREAD

**Issue by ismith** [docker/docker#29084]
**Description**

Previous to today's upgrade to 1.13.0-rc2, I was able to use --build-arg FOO, meaning "set the build arg FOO to the current value of the env var FOO in the environment".  (This behavior matches how environment variables are handled by -e.)  Now, that same behavior fails, and I have to do --build-arg FOO=$FOO.

**Steps to reproduce the issue:**
1.  Run `docker build -t foo --build-arg FOOVAR=$FOOVAR .` as a working case; no error.
2. Run `docker build -t foo --build-arg FOOVAR .` as error case.

**Describe the results you received:**
```
$ docker build -t foo --build-arg FOOVAR .
invalid argument "FOOVAR" for --build-arg: bad format for build-arg: FOOVAR
See 'docker build --help'.
```

**Describe the results you expected:**
Expected `--build-arg FOOVAR` to use the value of the environment variable FOOVAR, and proceed without error.

**Additional information you deem important (e.g. issue happens only occasionally):**
I believe this was introduced in https://github.com/docker/docker/commit/5426510bea290a8; prior to that commit, --build-arg was using ValidateEnv, and that commit introduced ValidateArg.

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 17:40:58 2016
 OS/Arch:      darwin/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 17:40:58 2016
 OS/Arch:             linux/amd64
 Experimental:        true
```

**Output of `docker info`:**

```
Containers: 15
 Running: 0
 Paused: 0
 Stopped: 15
Images: 206
Server Version: 1.13.0-rc2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.10-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: OQWZ:7VAW:36RJ:57U5:PLXK:J6CD:RHOP:GWA3:WRL6:4ASG:V32S:UNVA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2016-12-02T20:08:41.405406736Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by ismith** [comment]
I see in https://github.com/docker/docker/pull/26103 that this may have been deliberate, but I'm not sure why - the above use case of pulling in environment variables was a useful one.

**Comment by cpuguy83** [comment]
Thanks for looking at this in detail.
I don't think this was intentional.

Ping @thaJeztah 
I think we need to make a fix and cherry-pick for 1.13.

**Comment by cpuguy83** [comment]
CLI should probably check if the env var is actually set.

**Comment by thaJeztah** [comment]
The build arg should be able to pick up environment variables, for example in the case of `--build-arg http_proxy` to use the proxy that's set on the host. (Although there's a different discussion on that in https://github.com/docker/docker/pull/26318, because those settings should ideally come from the host where the _daemon_ runs, which may be different than the client)

It should use the same semantics as `-e` / `--env` (not sure if that requires a trailing `=`, we should check that)

**Comment by thaJeztah** [comment]
@cpuguy83 if you have time to look into that and either revert, or fix the change for 1.13, that'd be great

**Comment by duglin** [comment]
If not i may have some time this weekend

**Comment by duglin** [comment]
@cpuguy83 I think I have a fix for this - just creating some new tests.

**Comment by duglin** [comment]
PR: https://github.com/docker/docker/pull/29104
