### ISSUE TITLE
Can swarm pull images from different registrys?

### ISSUE THREAD

**Issue by bobo200128docker** [docker/docker#29119]
I have a scene:
I have a swarm,the nodes belong to two data center.
when I pull image by means of the api of swarm, I want use the local registry of the two data center.
for example:
Swarm （node A （belong to Data Center A’）and node B（Data Center B‘）），
Registry A（belong to Data Center A’）where Image_1 exists,When I pull Image_1 at node A, I wish from Registry A
Registry B（belong to Data Center B’）where Image_1 exists,When I pull Image_1 at node B, I wish from Registry B

but Now,I have to pull Image_1 at node A and node B from either Registry A or Registry B. 

How can I do:
DOCKER_SWARM = "tcp://10.10.10.10:4000"
docker_client_tmp = docker.Client(base_url=DOCKER_SWARM, timeout=10)
docker_client_tmp.pull("?/Image_1", stream = True)

**Comment by cpuguy83** [comment]
Registry is specified by the name of the image currently.
So `docker pull busybox` will always pull busybox from Docker Hub.
`docker pull myregistry:5000/busybox` would always pull from `myregistry` on port 5000, etc.

One can specify a list of mirrors to the engine which it can check if the image exists there first.

**Comment by cpuguy83** [comment]
Going to close this because it's not really an issue, but feel free to discuss here.
