### ISSUE TITLE
Non-Experimental mode hides `--bundle-file`

### ISSUE THREAD

**Issue by albers** [docker/docker#29112]
In experimental mode, `docker stack deploy --help` output contains both `--compose-file` and `--bundle-file`.
In non-experimental mode, only `--compose-file` is shown. Since `--compose-file` is a recent addition, I suppose it is or was experimental and that the visibility of the flags got confused.

```bash
$ docker version --format '{{.Server.Experimental}}'
false
$ docker stack deploy --help | grep -e -file
  -c, --compose-file string   Path to a Compose file
# restart daemon in experimental mode
$ docker version --format '{{.Server.Experimental}}'
true
$ docker stack deploy --help | grep -e -file
      --bundle-file string    Path to a Distributed Application Bundle file
  -c, --compose-file string   Path to a Compose file
```
ping @thaJeztah PTAL. If any of these options is experimental, I'd like to take this into account in bash completion.

**Comment by AkihiroSuda** [comment]
`--bundle-file` is intentionally marked as experimental, and `--compose-file` is marked as non-experimental
 https://github.com/docker/docker/issues/28960#issuecomment-264063845

**Comment by vdemeester** [comment]
As @AkihiroSuda, it is by design. ´--bundle-file´ is meant to stay experimental.

**Comment by albers** [comment]
Thanks a lot for clarification!
