### ISSUE TITLE
"--hostname" not working when running in "--net=host"

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#29129]
Possibly I'm doing something wrong, but https://github.com/docker/docker/pull/20177 added support for changing the container's hostname when running in `--net=host`; according to that PR, the container gets its own UTS namespace, so changing the hostname only affects the container's hostname.

Testing that feature, however, it looks like the hostname is not set at all;

```bash
$ docker run --rm --net=host --hostname foobar alpine sh -c 'echo $HOSTNAME && hostname'
8af04ff88b77
8af04ff88b77
```

(`8af04ff88b77` is the hostname of the "host"; running docker-in-docker)

I tried to reproduce on 1.11.2, 1.12.3, and 1.13.0-rc2 to verify if there was a regression, but none of those versions worked. Trying on docker 1.10 correctly shows an error message (`docker: Error response from daemon: Conflicting options: hostname and the network mode.`), which is expected.

/cc @estesp @jheiss

**Comment by thaJeztah** [comment]
To be sure this was not a regression due to the integration of RunC / containerd, I built a binary from https://github.com/docker/docker/pull/20177/commits/3f445e63b4568845f439c5d30a99ba10603b1938, and tested the same;

```
Client:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.6
 Git commit:   3f445e6-unsupported
 Built:        Mon Dec  5 14:25:05 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.0-dev
 API version:  1.23
 Go version:   go1.6
 Git commit:   3f445e6-unsupported
 Built:        Mon Dec  5 14:25:05 2016
 OS/Arch:      linux/amd64
```

(the `-unsupported` is because I had to change the Dockerfile, because http://llvm.org/apt/trusty/ is no longer active)

```
docker run --rm --net=host --hostname foobar alpine sh -c 'echo $HOSTNAME && hostname'
6e65cdca7485
6e65cdca7485
```

**Comment by yongtang** [comment]
Added a PR #29144 to address the issue.

**Comment by jheiss** [comment]
Thanks @yongtang. I'm a bit embarrassed to admit that on recollection I think I spent so much time making sure that I got the command line option handling right that I didn't actually test that my change worked.

**Comment by estesp** [comment]
@jheiss it happens to the best of us :joy: not to mention those of us who reviewed it (ahem..like me) should be equally embarrassed for not testing it properly :-]

**Comment by yongtang** [comment]
@jheiss it happens to me all the time as well 😅
