### ISSUE TITLE
secrets: secret rm ignores non-existing secrets

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#29125]
When providing multiple names to `docker secret rm`, the non-existing names are ignored.

**When providing multiple names, non-existing names are ignored**

```bash
$ echo "foo" | docker secret create foo
ra4t9sb7bvd30rczgin4if7pr

$ docker secret rm foo bar baz
ra4t9sb7bvd30rczgin4if7pr
```

Only the existing secret is attempted to be deleted, but no error is shown for the non-existing secrets;

```
DEBU[1151] Calling GET /v1.26/secrets?filters=%7B%22names%22%3A%7B%22bar%22%3Atrue%2C%22baz%22%3Atrue%2C%22foo%22%3Atrue%7D%7D
DEBU[1151] Calling DELETE /v1.26/secrets/ra4t9sb7bvd30rczgin4if7pr
DEBU[1151] secret removed                                method=RemoveSecret secret.ID=ra4t9sb7bvd30rczgin4if7pr
```

This is inconsistent with other `rm` commands, which leave resolution to the daemon;

```bash
$ docker create --name foo busybox
8820a306e95aab39b633045771de202dbfd6101409f40742530b959906ee4759

$ docker rm foo bar baz
foo
Error response from daemon: No such container: bar
Error response from daemon: No such container: baz
```

Which makes these API calls;

```
DEBU[2445] Calling DELETE /v1.26/containers/baz
ERRO[2445] Handler for DELETE /v1.26/containers/baz returned error: No such container: baz
DEBU[2445] Calling DELETE /v1.26/containers/foo
DEBU[2445] Calling DELETE /v1.26/containers/bar
ERRO[2445] Handler for DELETE /v1.26/containers/bar returned error: No such container: bar
```

**Proposed solution**

This issue looks to be introduced by https://github.com/docker/docker/commit/70d2cefd51e853ca4f3bbf8eb0386360809e026b (https://github.com/docker/docker/pull/28716), which added support for removing multiple secrets.

Given that the API supports both "IDs" and "names", there should not be a need to lookup ID's in advance.

One thing that _should_ be tested is that the provided names cannot be mis-used, e.g. that `docker secret rm ../containers/foo` does not lead to deleting a container named "foo" 😇 

/cc @ehazlett

**Comment by ehazlett** [comment]
Taking a look

**Comment by ehazlett** [comment]
The implementation in #29218 fixes this.

**Comment by allencloud** [comment]
I tested in the master. Yes, I think #29218 fixed this. @thaJeztah @yongtang 
Please have a try. 😄

**Comment by yongtang** [comment]
Thanks @allencloud. Yes I can verify the issue has been fixed:
```
ubuntu@ubuntu:~/docker$ echo "foo" | docker secret create foo -
m5ad1xsmzgsox9zf2fbaxpp28
ubuntu@ubuntu:~/docker$ docker secret rm foo bar baz
foo
Error response from daemon: no such secret: bar
Error response from daemon: no such secret: baz
ubuntu@ubuntu:~/docker$ docker version
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   011a408
 Built:        Sat Jan 28 17:45:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   011a408
 Built:        Sat Jan 28 17:45:15 2017
 OS/Arch:      linux/amd64
 Experimental: false
ubuntu@ubuntu:~/docker$ 
```

/cc @thaJeztah

**Comment by vdemeester** [comment]
:tada:
