### ISSUE TITLE
Bug: Could not remove unused volume

### ISSUE THREAD

**Issue by phatle** [docker/docker#29154]
**Description**

Could not remove the volume even that there is no container associated with that volume.

**Steps to reproduce the issue:**
1. Use [docker-sync](http://docker-sync.io/) to create a volume
2. Stop all containers, restart the docker daemon, and also restart the machine
3. docker volume rm volumne_name got failed

**Describe the results you received:**
`$ docker ps`
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
`$ docker volume rm eh_sync`
Error response from daemon: Unable to remove volume, volume still in use: remove eh_sync: volume is in use - [26601c6b63deb9526da4ab550b34d312917e78c431b2b61dbed41722143d2843]

**Describe the results you expected:**

The volume should be removed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 8
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 66
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: BTR2:BEC6:TZ44:ZWK6:NPJU:J6IT:GYFZ:JVAW:GNHZ:XJKK:34DS:HW6B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 27
 System Time: 2016-12-06T00:42:19.521769536Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Darwin Phats-MacBook-Pro.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64

**Comment by cpuguy83** [comment]
Can you check `docker ps -a`?
Specifically it thinks there is a reference to a container with ID `26601c6b63deb9526da4ab550b34d312917e78c431b2b61dbed41722143d2843`

**Comment by cpuguy83** [comment]
@phatle Is there something in `/var/lib/docker/containers/26601c6b63deb9526da4ab550b34d312917e78c431b2b61dbed41722143d2843`?

**Comment by phatle** [comment]
Yes. my folder data

**Comment by cpuguy83** [comment]
Is there a config json in there?
Trying to figure out how/why there would be a container referenced but no container loaded for it.
Since the volume refs are only stored in memory, it's getting reloaded for some reason on daemon restart but not showing up in `docker ps -a` (Some weird partially loaded state?)

**Comment by phatle** [comment]
@cpuguy83 Yup. It has config.v2.json and hostconfig.json

**Comment by phatle** [comment]
@cpuguy83 Updated ```docker ps -a```

```
CONTAINER ID        IMAGE                                                                           COMMAND                  CREATED             STATUS                      PORTS                                            NAMES
f7c43a32882e        eugenmayer/unison:unox                                                          "/entrypoint.sh super"   59 minutes ago      Exited (0) 9 minutes ago                                                     eh_sync
26601c6b63de        979797940137.dkr.ecr.ap-southeast-2.amazonaws.com/APPNAME/webdev:1.0.1   "/script/start_web.sh"   4 days ago          Exited (1) 3 minutes ago    0.0.0.0:3000->3000/tcp, 0.0.0.0:8080->8080/tcp   devenv_web_1
c1f15adf3b75        busybox                                                                         "sh"                     4 days ago          Exited (0) 18 minutes ago                                                    devenv_bundle_gems_1
68121c170f40        busybox                                                                         "sh"                     4 days ago          Exited (0) 18 minutes ago                                                    devenv_node_modules_1
5bf1844402ea        postgres:9.4                                                                    "/docker-entrypoint.s"   4 days ago          Exited (1) 3 minutes ago    0.0.0.0:5432->5432/tcp                           devenv_db_1
4fec1955f65e        redis:3.2-alpine                                                                "docker-entrypoint.sh"   4 days ago          Exited (1) 3 minutes ago    0.0.0.0:32769->6379/tcp                          devenv_redis_1
```

**Comment by cpuguy83** [comment]
@phatle What changed between the previous `docker ps -a` and this one?
And yep, the container the volume is complaining about seems to exist (2nd entry in your list).

**Comment by phatle** [comment]
@cpuguy83 Thanks for helping me. Can I close it because I can not reproduce that? Sorry about that. Happy coding

**Comment by cpuguy83** [comment]
Thanks for the report, glad we got it figured out!
