### ISSUE TITLE
RepoTags become null in /images/json 

### ISSUE THREAD

**Issue by Ralph-Wang** [docker/docker#29157]
**Description**
I found that RepoTags from remote api, /images/json, would become null.

**Steps to reproduce the issue:**
1. pull an image. such as 'alpine'
2. rebuild an image named the same
3. request the remote api  /images/json

**Describe the results you received:**
The RepoTags becomes null
```json
{
    "Created": 1476822682,
    "Labels": null,
    "VirtualSize": 4799225,
    "ParentId": "",
    "RepoTags": null,
    "RepoDigests": [
      "alpine@sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c"
    ],
    "Id": "sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3",
    "Size": 4799225
  }
```

**Describe the results you expected:**
The RepoTags becomes "`<none>:<none>`" instead of null
```json
{
    "Created": 1476822682,
    "Labels": null,
    "VirtualSize": 4799225,
    "ParentId": "",
    "RepoTags": [
          "<none>@<none>"
    ],
    "RepoDigests": [
      "alpine@sha256:1354db23ff5478120c980eca1611a51c9f2b88b61f24283ee8200bf9a54f2e5c"
    ],
    "Id": "sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3",
    "Size": 4799225
  }
```

**Additional information you deem important (e.g. issue happens only occasionally):**
If we don't pull image from registry, just build the same image twice (of cause, with some edit), the problem above will not happen.
**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-100873853-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 979.6 MB
 Data Space Total: 107.4 GB
 Data Space Available: 16.31 GB
 Metadata Space Used: 2.142 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 976.9 MiB
Name: default
ID: RDJX:WI6S:TCZL:H2CW:CQLL:WJRJ:JIV2:X3IC:LI42:JYYV:DC4X:7E7R
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=generic
Insecure Registries:
 docker.logicmonitor.net
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
This cannot be done. The `<none>:<none>` tags printed on the command line are not actual tags, but are just a way to show that an image is "untagged" (doesn't have tags associated with it); when you build an image with the same name and tag as an existing image, the existing image is automatically untagged (`null` in the image json show that there are no tags for the image).

I'll close this issue, because making this change is not possible, as it would break many things, but happy to answer questions; feel free to comment after I closed

**Comment by Ralph-Wang** [comment]
But the other scenario is that:
1. Build an image locally, such as test:latest
2. Make some changes on Dockerfile, and rebuild it
3. Request the /images/json api.

I can actually get the json result like:
```json
    {
        "Id": "sha256:f2af0e90c81e2ece7040caecfb5cf268ca8a4ba4187246f42969f384e9b5a350", 
        "ParentId": "sha256:baa5d63471ead618ff91ddfacf1e2c81bf0612bfeb1daf00eb0843a41fbfade3", 
        "RepoTags": [
            "<none>:<none>"
        ], 
        "RepoDigests": [
            "<none>@<none>"
        ], 
        "Created": 1481425514, 
        "Size": 4799225, 
        "VirtualSize": 4799225, 
        "Labels": {}
    }
```

**Comment by thaJeztah** [comment]
Is that what you're seeing or what you would _like_ to see?

This is what I get;

```
{
  "Id": "sha256:9a8a4914b40e3a5c8a38b3820a32916a88ce93efbd6339a73fc678fa29500d19",
  "RepoTags": [],
  "RepoDigests": [],
  "Parent": "sha256:1efc1d465fd6255396d0efd90a899f57aba2b7b294b02d5f55c6f5505ca9f3e5",
  "Comment": "",
```

The JSON that's returned from the API should show the actual state; in this case it shows that there _are_ no `RepoTags` or `RepoDigests` for that image, why would you expect "fake" values to be inserted there? Can you explain the use case?

**Comment by Ralph-Wang** [comment]
That's what I'm seeing in my environment in the second case.
I just confused about the `null` value of `RepoTags` in the first case.
"fake" value is not necessary indeed, but I think we can't have 2 value, `null` and empty array, to show there are no `RepoTags`.
