### ISSUE TITLE
Windows equivalent of `unix:///var/run/docker.sock`

### ISSUE THREAD

**Issue by cdancy** [docker/docker#29178]
DISCLAIMER: I'm the maintainer of the [gradle-docker-plugin](https://github.com/bmuschko/gradle-docker-plugin) and am a windows noob ;)

Is there a windows equivalent that you guys use to connect to docker on windows? For unix based machines we have the above which works great but I didn't know if you guys implemented something similar to easily connect to docker API on windows. I ask because I'd like to provide a default URL for windows users that will just work OOTB. 

Thanks AOT!

**Comment by cpuguy83** [comment]
`npipe:////./ppe/docker_engine`

**Comment by friism** [comment]
@cpuguy83 I think there's a typo in you comment, it's `npipe:////./pipe/docker_engine`
