### ISSUE TITLE
Support expanded ports and mount format in the the compose v3 format

### ISSUE THREAD

**Issue by dnephin** [docker/docker#29193]
Following the decisions made in #28527 we should also support the expanded ports and mount format. Instead of CSV we should use an object for each.

**Comment by techninja1008** [comment]
I would be grateful if this could be included in 1.13 as it is vital for my use case.

**Comment by ginjo** [comment]
Any updates on this? The port (or publish?) option ```mode=host``` is key to my deployments in swarm mode (which I really like BTW).

**Comment by techninja1008** [comment]
I'm giving up on swarm mode, and I'm moving to rancher and kubernetes, as it's simple to set up and very, very powerful.

**Comment by cirocosta** [comment]
should we consider this closed as of "Support expanded syntax of ports in `docker stack deploy` #30476 " ?

**Comment by dnephin** [comment]
It will be closed when #30597 is merged

**Comment by ginjo** [comment]
This may be redundant info, but.... the expanded syntax of ports in compose v3.1 for ```docker stack deploy``` works well in Docker 17.04.0-dev, build 6e04fbf. Thanks!

**Comment by jonathan-kosgei** [comment]
@ginjo what about the expanded mount format?

**Comment by cirocosta** [comment]
@jonathan-kosgei I'd say it's there already: https://github.com/docker/docker/blob/fc6d8fb94d2d9070e58d83dbf13f40c0efa715e3/cli/compose/loader/full-example.yml#L223

**Comment by ginjo** [comment]
@jonathan-kosgei yes it's all good, working as expected. @cirocosta thanks for the link to that example page.
