### ISSUE TITLE
Add switch to disable security warning for the "You are building Linux container from Windows client" scenario

### ISSUE THREAD

**Issue by sandersaares** [docker/docker#29209]
If you build a Linux container from a Windows Docker client, you get this warning in stderr: `SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.`

See also https://github.com/docker/docker/issues/20397 for illustrative purposes.

It would be desirable to be able to disable this specific error, without being forced to ignore any stderr output.

Reason: we have automated build processes and we are aware of this limitation and accept it. We want to ignore it. However, because it is written to stderr, the automation considers it an error. We tried just telling it to not treat stderr as an error but this actually hid some error conditions that apparently signaled exit code 0, so this workaround may lead to actual errors not being discovered.

**Comment by jhowardmsft** [comment]
I don't have an opinion either way. I wasn't involved in docker when the decision to put this warning in was introduced. Unfortunately Ahmet is no longer at MS. I don't know who else was involved in the discussion.

**Comment by StefanScherer** [comment]
It seems that option `-q` can be used to suppress this message https://github.com/docker/docker/blob/3d52c86d4c8405372445502b2592e8f63132ce99/cli/command/image/build.go#L337

**Comment by sandersaares** [comment]
Right. Unfortunately `-q` also suppresses a lot more, which is undesirable. We would still like to keep full logs overall, just not have something in stderr if it is just a warning we deliberately choose to ignore.

**Comment by jhowardmsft** [comment]
What about is the warning was written to `Out()` rather than `Err()` - would that work? I think that's strictly OK as it's not really an error...  Easy change to make, happy to do it.

**Comment by jhowardmsft** [comment]
@thaJeztah ^^

**Comment by thaJeztah** [comment]
I'm not against that, generally, the "security" implication of this is not too big, so from that PoV, sounds ok.

Would there be cases where people want the literal output that's printed by the _build_ process, and where adding the warning to that output could be a problem?

**Comment by jhowardmsft** [comment]
@thaJeztah It's a case of the devil you know or the devil you don't. I can't see if anyone could answer that question.

**Comment by thaJeztah** [comment]
Let's see then :smile:

**Comment by jhowardmsft** [comment]
https://github.com/docker/docker/pull/29856
