### ISSUE TITLE
Docker Windows network create: Error response from daemon: HNS failed with error : Unspecified error

### ISSUE THREAD

**Issue by hmdhasani** [docker/docker#29207]
when I run the following on windows server 2016:
docker network create -d nat --subnet=15.16.1.0/24  MyNatNet
I get this error:
Error response from daemon: HNS failed with error : Unspecified error
I found that if I run
Get-NetNat | Remove-NetNat
the issue will fix
but after creating a network, the error will come back
It seems that the created network will set as the result of Get-NetNat and prevent creating of another network

**Comment by hmdhasani** [comment]
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 79
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 10
Total Memory: 4 GiB
Name: WIN-NIG1BQKP266
ID: 7C6M:3IJ2:MZLB:CE42:Y6IX:E7DB:WP26:Z57C:YLHE:QEYN:F25O:ZJ3S
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by hmdhasani** [comment]
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

**Comment by darrenstahlmsft** [comment]
cc @msabansal

**Comment by msabansal** [comment]
@hmdhasani This is a known limitation. At present windows only supports one NAT network. Removing Netnat by invoke Remove-Netnat is not supported.

**Comment by fmuecke** [comment]
I want to run the mssql-server docker container on my Windows 10 machine.

How am I supposed to access the db server from my host if 

- port mapping is limited with the windows implementation (access to container only works via IP) see #253
- static IP assignment is not supported for the default NAT network
- a second network is not supported as well

???

**Comment by msabansal** [comment]
@fmuecke  Newer docker versions support static IP for the default NAT network and also container name resolution. Please give a try.

**Comment by fmuecke** [comment]
Using static IP for the default NAT works with v1.13. That helps a lot. Thanks.
I didn't have any luck with container name resolution however,

**Comment by seanfisher** [comment]
@hmdhasani @fmuecke @msabansal Could you give the commands you used to accomplish this?

    $ipAddress = "172.29.124.1"
    docker run -d -p 1433:1433 --ip=$ipAddress --rm -e sa_password=somepassword -e ACCEPT_EULA=Y -v C:/data/:C:/data/  --name sql microsoft/mssql-server-windows

> docker : C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: User specified IP address is supported 
only when connecting to networks with user configured subnets.

I tried using Get-NatNet and creating a network with
    docker network create -d nat --subnet=172.24.64.2/16 --gateway=172.24.64.1 myNetwork

> docker : Error response from daemon: HNS failed with error : The object already exists.

or sometimes with differing subnet designations I get 

> docker : Error response from daemon: HNS failed with error : Unspecified error

**Comment by msabansal** [comment]
@seanfisher For the first error please upgrade docker.

Multiple nat networks are not supported for now.

**Comment by jonashackt** [comment]
[This issue](https://github.com/Microsoft/Virtualization-Documentation/issues/273) helped me. Just run:
```
dockerd -H npipe:// -b "none"
```
This prevents docker to try to create a NAT... dockerd is starting after that, but I don´t know the limitations later...

**Comment by Hal1987** [comment]
still not working how do i setup static ip
