### ISSUE TITLE
[Question] What is the influence if swarm certificates expire?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#29214]
What is the influence of swarm certificates expire?

I found that in `docker swarm init --cert-expiry 1h`, certificates expiry has minimum of 1 hour. When I finished to set this, one hour ago, I have no idea what will happen.

Have no idea about output, I have no way to test this.

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.13.0-rc2
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   1f9b3ef
 Built:        Wed Nov 23 06:24:33 2016
 OS/Arch:      linux/amd64

Server:
 Version:             1.13.0-rc2
 API version:         1.25
 Minimum API version: 1.12
 Go version:          go1.7.3
 Git commit:          1f9b3ef
 Built:               Wed Nov 23 06:24:33 2016
 OS/Arch:             linux/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 58
Server Version: 1.13.0-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 357
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: mqwom0ky012fjvig86ni43dhm
 Is Manager: true
 ClusterID: qakt3ylxb8hn7kbcoxxo9dzrk
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: About an hour
 Node Address: 192.168.59.103
 Manager Addresses:
  192.168.59.103:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: HRBI:EV6M:3NAC:CXZ3:BDS7:UOKL:PD6Y:ZCK4:V3PF:V7MR:CU2Y:3LGG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 183
 System Time: 2016-12-06T14:37:11.714967661+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
The certificates will automatically be regenerated and rotated, however if for some reason nodes don't have access to the swarm (e.g. if there's a network outage), the certificate expires, and the nodes will no longer be able to join. For that reason, the default is not set to a short expiration time

**Comment by allencloud** [comment]
Thanks for your detailed explanation. @thaJeztah

**Comment by thaJeztah** [comment]
Some information is available here; https://docs.docker.com/engine/swarm/how-swarm-mode-works/pki/

ping @mstanleyjones @diogomonica I know this came up in a discussion, but I don't recall if we added something to the documentation to explain how the best expiry should be selected

**Comment by diogomonica** [comment]
The main recommendation is: leave the expiration at 3months unless you know what you're doing. If you want to have less exposure to the validity of a compromised certificate, you can reduce the rotation time to whatever you feel like is adequate (2 weeks, for example). If you are concerned about certificates being rotated too often, or have a use-case in which nodes go out of contact with managers for long periods of time (can't really think of one), then increase it to something like 1 year.

**Comment by allencloud** [comment]
Thanks a lot for your explanation. @diogomonica
