### ISSUE TITLE
Feature request: protected images

### ISSUE THREAD

**Issue by nosovk** [docker/docker#29227]
We have some server application packed into docker image. Now customers could download it from privat docker registry and configurate docker-compose to expose server in a right way. But there is two more problems.
1. Customer could extract server code from image (it's an issue if server written in nodejs)
2. Customer may copy image to multiple hosts. It would be nice to allow only one deployment for container (and tag them with customer names)

Those scenarios both connected with distribution of proprietary applications using docker, not by admins, but by end-customers.

**Comment by AkihiroSuda** [comment]
I'm not sure it is technically possible..

For 1, I think you can use some obfuscator. 

For 2, I think you can implement your own license activation system.

**Comment by nosovk** [comment]
Yep, but it's hard to get out from container to understand where exactly you launched. The best resolution in my mind is to generate GUID for each docker-daemon. Then I can crypt customer image with key based on that GUID, to avoid ruining on other docker-daemon.

**Comment by cpuguy83** [comment]
Closing since this is not a docker concern.
The way to handle this is no different than without containers, it's the same problem that had to be dealt with with VMs vs physical machines.

It is unfortunately not a problem that can be solved in Docker.
