### ISSUE TITLE
Add ability to control address pool and subnet mask length for networks created with default parameters

### ISSUE THREAD

**Issue by zarbis** [docker/docker#29239]
I've discovered fact that if you try to create a bunch of networks with default parameters you run out of available networks REALLY fast.

**Steps to reproduce:**
1) Spin up fresh environment with Docker (VirtualBox, Ubuntu 16.04, Docker 1.12.3 in my case).
2) Try to create 50 networks.
```
for i in {1..50}; do docker network create net-$i; done
```
3) Notice error messages after some amount of created networks
4) Take a look at result.
```
for i in $(docker network ls -q); do docker network inspect --format='{{.Name}} {{.IPAM.Config}}' $i; done
```

```
net-1 [{172.18.0.0/16  172.18.0.1/16 map[]}]
net-2 [{172.19.0.0/16  172.19.0.1/16 map[]}]
net-3 [{172.20.0.0/16  172.20.0.1/16 map[]}]
net-4 [{172.21.0.0/16  172.21.0.1/16 map[]}]
net-5 [{172.22.0.0/16  172.22.0.1/16 map[]}]
net-6 [{172.23.0.0/16  172.23.0.1/16 map[]}]
net-7 [{172.24.0.0/16  172.24.0.1/16 map[]}]
net-8 [{172.25.0.0/16  172.25.0.1/16 map[]}]
net-9 [{172.26.0.0/16  172.26.0.1/16 map[]}]
net-10 [{172.27.0.0/16  172.27.0.1/16 map[]}]
net-11 [{172.28.0.0/16  172.28.0.1/16 map[]}]
net-12 [{172.29.0.0/16  172.29.0.1/16 map[]}]
net-13 [{172.30.0.0/16  172.30.0.1/16 map[]}]
net-14 [{172.31.0.0/16  172.31.0.1/16 map[]}]
net-15 [{192.168.0.0/20  192.168.0.1/20 map[]}]
net-16 [{192.168.16.0/20  192.168.16.1/20 map[]}]
net-17 [{192.168.32.0/20  192.168.32.1/20 map[]}]
net-18 [{192.168.48.0/20  192.168.48.1/20 map[]}]
net-19 [{192.168.64.0/20  192.168.64.1/20 map[]}]
net-20 [{192.168.80.0/20  192.168.80.1/20 map[]}]
net-21 [{192.168.96.0/20  192.168.96.1/20 map[]}]
net-22 [{192.168.112.0/20  192.168.112.1/20 map[]}]
net-23 [{192.168.128.0/20  192.168.128.1/20 map[]}]
net-24 [{192.168.144.0/20  192.168.144.1/20 map[]}]
net-25 [{192.168.160.0/20  192.168.160.1/20 map[]}]
net-26 [{192.168.176.0/20  192.168.176.1/20 map[]}]
net-27 [{192.168.192.0/20  192.168.192.1/20 map[]}]
net-28 [{192.168.208.0/20  192.168.208.1/20 map[]}]
net-29 [{192.168.224.0/20  192.168.224.1/20 map[]}]
net-30 [{192.168.240.0/20  192.168.240.1/20 map[]}]
```

It was able to create 30 networks total. Seems like default subnet allocation rules are like this:
1) Docker uses RFC1918 networks 172.16/12 and 192.168/16 
2) Network masks are picked in a way that would divide both networks into 16 subnets.

**Why it's important?**

This issue becomes prominent when you deploy apps using Compose in your CI pipeline.
Compose creates separate network for each project by default, which seems like a reasonable behavior.
However you are limited to 30 projects that can be deployed with default subnet allocation policy.
I want to avoid hardcoding networks in `docker-compose.yml` file at all costs since it makes them unportable and human error-prone.

**What is my proposal?**

Docker daemon already has option `--fixed-cidr` that allows to change address pool for IP addresses assigned to containers by default.
Adding options like `--default-subnet-pool` and `--default-subnet-mask` (names are subject to change) will allow user to control default subnet allocation policy and with values like `--default-subnet-pool=10.0.0.0/8 --default-subnet-mask=/24` will virtually eliminate issue of subnet depletion without affecting Compose files in CI pipelines.

**Comment by aboch** [comment]
Thanks for the clear description. I believe the same feature was asked in #21776.
If you confirm, we can close this one as duplicate.

**Comment by zarbis** [comment]
@aboch Indeed, this issue is duplicate. Safe to close.
