### ISSUE TITLE
Feature Request: docker load -d folder

### ISSUE THREAD

**Issue by TamalSaha** [docker/docker#29235]
Currently we can load a docker image from a tar file that was previously generated via `docker save`. It will be great if  we could load that same image from a folder with the contents of tar file. So,

`docker load -i abc.tar`
or
```
tar xzvf abc.tar
docker load -d {folder_name with tar contents unzipped} 
```

Why?
We are shipping some private docker images using `docker save` and `docker load`. To reduce the size of the final archive, we have written a [script](https://github.com/appscode/baler) that dedups the layers inside the tar file. The issue is for loading, we have to rebuild the original tars. This takes time. If docker could load images from unzipped folder with exact same tar contents then it could save time during the reload phase.

Thanks.

**Comment by tonistiigi** [comment]
The API accepts a tar, if you specify a directory then just docker client would make the tar.

If you have the directory run `tar cv . | docker load`

**Comment by TamalSaha** [comment]
@tonistiigi that is what I am doing now, but creating tars take time. It seems to me that it should be possible to load a folder directly without needing to tar that first.

**Comment by tonistiigi** [comment]
@TamalSaha No, we can't do that. Docker uses a client-daemon model with HTTP API in the middle. Daemon can't directly open files from client, they have to be sent through the API and tar is the format used for the transport.

**Comment by TamalSaha** [comment]
@tonistiigi I understand. Thanks for explaining.
