### ISSUE TITLE
docker-engine RC versions for 1.13.0 have disappeared from Ubuntu repos!

### ISSUE THREAD

**Issue by liyaka** [docker/docker#29249]
I'm working with docker-engine 1.13.0 rc2 for a a couple of weeks, and today trying to install docker engine on the new machine, I got this message:
stderr: E: Version '1.13.0\~rc2-0\~ubuntu-trusty' for 'docker-engine' was not found

And indeed the list of version in https://apt.dockerproject.org/repo/dists/ubuntu-trusty/testing/filelist does not include any of 1.13.0 RC version any more!

Is it a mistake? When it's going to be fixed??

It a HUGE BLOCKER for my work!

**Comment by justincormack** [comment]
cc @andrewhsu

**Comment by andrewhsu** [comment]
I can confirm the `filelist` does not contain the correct contents. Working on a fix at the moment.

**Comment by andrewhsu** [comment]
@liyaka fixed in production now, the `filelist` should have 1.13.0

**Comment by liyaka** [comment]
Thank you!

**Comment by thaJeztah** [comment]
Thanks @andrewhsu, and apologies for the hiccup @liyaka 

I'll close this issue, as it's resolved
