### ISSUE TITLE
[1.13-rc3] getting "certification expired" error on 'docker inspect'

### ISSUE THREAD

**Issue by shykes** [docker/docker#29242]
**Description**

I get the following error after upgrading to 1.13.0rc3 on Docker for Mac beta channel today.

```
$ docker inspect something_that_does_not_exist
[]
Error response from daemon: Swarm certificates have expired. To replace them, leave the swarm and join again.
```

The error only appears for containers that do not exist (as listed by `docker ps -a`):

```
$ docker inspect something_that_exists
[…] normal output
```

Below is some diagnostic information.

```
$ docker version
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      linux/amd64
 Experimental: true

$ docker info
Containers: 71
 Running: 3
 Paused: 0
 Stopped: 68
Images: 95
Server Version: 1.13.0-rc3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 250
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: error
 NodeID:
 Error: Swarm certificates have expired. To replace them, leave the swarm and join again.
 Is Manager: false
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.12-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: IEMY:6NDR:XEEJ:5HXA:AZCF:NJMX:KBDX:ATTA:K4RN:O3PF:P5LN:JFR7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 55
 Goroutines: 77
 System Time: 2016-12-08T08:27:54.125249557Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: shykes
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Thank you!

**Comment by thaJeztah** [comment]
Per our conversation on Slack, the `Swarm certificates have expired` error itself may be expected, because this was a machine that hadn't been active for a while (which lead to the certificates not being automatically renewed by SwarmKit). If I misunderstood, let me know, then we should look into that issue separately.

For _this_ example (`docker inspect something_that_exists`); given that the user didn't explicitly ask for a _swarm_ object (`service`, `task`, or `node`), we should ignore this error, and skip it (same as we do for "node is not a swarm manager"; https://github.com/docker/docker/blob/90bb2cdb9f15a9b1b9a4e2ea4242882665daac4e/cli/command/system/inspect.go#L130-L135)

**Comment by tonistiigi** [comment]
"Swarm certificates have expired" can happen if either
- Daemon wasn't running for a long time in this machine before the upgrade, at least 18 days.
- Daemon was upgraded from `<v1.12.2`. These versions had a bug that could lower the minimal delay between restarts more. (https://github.com/docker/docker/issues/24132#issuecomment-250848852)

If these conditions don't match we have to investigate more. @diogomonica Considering that usage patterns of Docker4Mac may be quite different maybe we should choose different defaults there. Or just lower the update time from `50-80%` to `40-50%`.

**Comment by justincormack** [comment]
18 days is not really very long for desktop use cases eg a machine you dont use much.

**Comment by diogomonica** [comment]
@tonistiigi I think this issue is more related to the error showing up in a non-swarm functionality, but I'm completely ok with reducing the update time.

**Comment by thaJeztah** [comment]
@diogomonica correct. I just added you both in case the certificate expiring was unexpected. Not against improving it though if it makes the desktop experience better.

**Comment by diogomonica** [comment]
@thaJeztah agreed.

@tonistiigi might be good to verify again if certificate rotation logic is working correctly w/ laptops going in and out of sleep. I haven't had any issues, so far, but just reduce my expiration on my laptop down to 24 hours to see if something weird is happening.
