### ISSUE TITLE
Docker Deamon hangs on System with many container starts

### ISSUE THREAD

**Issue by qeqar** [docker/docker#29250]
hello,

i first have this behavior on 0.6 and now in 1.11.2 (was not using the verisons in between)

On system were i starting a lot of one shot containers, after some time (mostly days) the docker daemon hangs. the container don't start and command lines like docker ps never finish.

Only way i found to repair is, reboot the system.

the first acurance were with a cronjob. i did something like docker run --rm ...... every x minutes
at the moment i have a k8s cluster on coreos were i running jenkins slave -> one new slave(container) per job.

i don't see any log or chrash reports. 
most of the time it the only symtom ist that new container will not start up, or like docker ps timeout.

any ideas? 

thanks mark

**Comment by thaJeztah** [comment]
could you provide the information that was requested in the bug report template? https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

**Comment by qeqar** [comment]
`docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:        
 OS/Arch:      linux/amd64
`

`docker info   
Containers: 34
 Running: 22
 Paused: 0
 Stopped: 12
Images: 156
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.7.3-coreos-r2
Operating System: CoreOS 1185.3.0 (MoreOS)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 58.97 GiB
Name: int0000-kubernetes-worker-1.int0000.gkh-setu.de
ID: ST5M:PWE6:SULX:RPJA:SMK3:VHIT:A6U6:QZS3:7QE3:3VYQ:65SI:UDJR
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
`

**Comment by qeqar** [comment]
**Steps to reproduce the issue:**
it happens after a wile on running K8S cluster.
but only on the one with the jenkins worker.
start around 200 worker(container) for several days

**Describe the results you received:**
Docker deamon hangs 

**Describe the results you expected:**
docker deamon woks fine

**Comment by cpuguy83** [comment]
When you get a hang, best to use `SIGUSR1` to the docker daemon and collect the stacktrace from the logs.
This way we can troubleshoot.

However, 1.11 a bit old (8 months), and there's been many bug fixes that would potentially fix hangs that you are seeing.

**Comment by qeqar** [comment]
ok, will try the stacktrace on the next ocurence

for new version we need to wait new stable coreos

**Comment by qeqar** [comment]
Looks like something diffrent, i am not able to reproduce it in the last days.

will close the ticket.

**Comment by qeqar** [comment]
Ok, shortly after closing this ticket the next occourance.

i pasted a stack trace here: https://gist.github.com/qeqar/fe96d7ebe573271dcc9b99d84ab41b67

docker ps hangs and only reboot has helped.

mark

**Comment by cpuguy83** [comment]
Looks like it's hung waiting on netlink.
If you check `dmesg` I imagine you'll see something like `usage count = N, waiting for vethN to become free`.

Can you confirm?

**Comment by qeqar** [comment]
@cpuguy83 yes can confirm

**Comment by cpuguy83** [comment]
Ok, this is a dup of #5618, which is unfortunately a nasty kernel bug.

In 1.12.4 we added a timeout on this netlink request so that at least docker won't freeze from it. You probably still won't be able to start/stop any new containers, but can at least get information from Docker.

Closing since it's a duplicate.
Thanks!
