### ISSUE TITLE
volume ls

### ISSUE THREAD

**Issue by TopheC** [docker/docker#29254]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by unclejack** [comment]
This seems to have been opened by mistake. Please comment if this isn't the case.
