### ISSUE TITLE
[Proposal] Global memory limit for docker engine / docker swarm node

### ISSUE THREAD

**Issue by approxit** [docker/docker#29278]
### Background
Running Docker 1.12 gives a Swarm Mode that makes magic. With this cloud solutions is a "dreams come true" case. Batteries included.

If you are moving further you suddenly wake up: It's batteries included only for STATIC swarm deployment.

When you have a cloud that runs containers/services DYNAMICALLY to users actions, you can easily run out of memory. Spawning more and more containers/services will finally stuck whole node due to memory starvation and moving to swap which finally takes up all CPU. And what about room for system or administrative tools?

#### What docker gives us now?
- Memory limit per container/service - it's not enough due to container count.
- Container count limit - it's not enough due to different memory limit per container/service.
- Undocumented `--reserve-memory` - it's still can fill host memory with small chunks.

### The goal of this proposal
- To give docker ability to set global memory limit for whole engine/node. Docker is not alone in host machine.
- ~Refuse to start containers/services which memory limit will exceed that limit.~ (covered with undocumented `-reserve-memory`)

### The use cases
- ~Application will be secured from node memory starvation and moving to swap which finally takes up all CPU. Note that ingress network need some resources to forward data to destination node.~ (partially covered with `--reserve-memory`)
- Give room for system needs and for other tools that runs outside from docker (administrative tools for eg.)

#### Or even more goodies
- Application will be able to reply user with "Our application cloud is BIG, but you just requested way too much... Your request was accepted, but we need make the could a little bigger. It can take a few moments. You can wait or abort your request. [I WILL WAIT] [I WANT TO ABORT]".
- Application will be able to receive swarm-out-of-memory events and deploy new node to swarm, making room for overflowing containers/services.
- Or just wait until some running services will be removed.

**Comment by PWojtal** [comment]
It would be great to have such feature.

**Comment by kusik23** [comment]
add this feature, please.

**Comment by 1dziubo1** [comment]
This should be definitely implemented! Good idea!

**Comment by thaJeztah** [comment]
Have you tried using `--reserve-memory` for a service? e.g.

```
docker service create --reserve-memory=4GB --name=too-big nginx:alpine
```

doing so on a 2GB node will keep the service in "pending";

```
NAME                    IMAGE         NODE  DESIRED STATE  CURRENT STATE           ERROR  PORTS
too-big.1.9852765ynawb  nginx:alpine        Running        Pending 14 seconds ago
```

**Comment by approxit** [comment]
@thaJeztah You're right. `--reserve-memory` will fix that critical memory->cpu starvation I wrote about. It's a pity that `--reverse-memory` is not documented properly and only mentioned in params list.

But even with this, docker can eat all free memory that host machine have (many containers with small reserved chunks for eg.). In particular moment memory reservation will fit the limited resources... But what then? Living the moment is not so "cool". Let's think about other things that runs outside docker. Yup, he's not alone on the host machine.
Imagine case when you can assign 40% of host machine memory for docker, leaving the rest for tricky magic business logic, or 90%, leaving space for administrative tools, or just for host system.

The other thing docker currently missing (which can be a totally different issue, but mentioned in use case) is that we have totally no idea what's happening under service layer. We don't have any mechanism to potentially know that there is no more room for containers from services with `--reserve-memory`. Checking based on intervals? Naah... We should have events for that. We should.

I should alter the proposal goal to cover issue title more accurate, and think about making another proposal for service events just to show that it's needed. Decisions, decisions...

**Comment by cpuguy83** [comment]
@approxit I don't think docker should be worrying about placing resource constraints on itself... in fact it's already boosting it's OOM score to prevent the kernel from killing it before other processes.

This should be done with cgroups. If you are using systemd you can do this pretty easily.

**Comment by approxit** [comment]
@cpuguy83 You... are... actually... totally right! It should be done in cgroups and it works with cgroups like a charm.

There is no leads anywhere about this simple solution. It must be mentioned docs too. I'm gonna point this to docs guys. Thanks for feedback.

The last thing is knowing that service can't spawn container due to OOM and other other interesting service events, but it will be a different discussion.

**Comment by thaJeztah** [comment]
@approxit if you opened an issue in the docs issue tracker, could you link it here for future reference? Docs issue tracker can be found here; https://github.com/docker/docker.github.io/issues

**Comment by cpuguy83** [comment]
Thanks @approxit, glad it solves your case!

**Comment by lukaszw84** [comment]
It would be great to have such feature, agree!

**Comment by PatWski** [comment]
Please, add this feature.

**Comment by cpuguy83** [comment]
There's nothing to add here. You can reserve memory for containers already.
Resource management of Docker needs to happen outside of Docker (cgroups).

**Comment by sasavilic** [comment]
@cpuguy83 Could you please more elaborate on how limiting memory in systemd is supposed to work. Let's say I have 31G on my node. I tell in systemd to limit docker to 30G. Does docker itself now knows that total sum of all containers + docker daemon itself must not go beyond 30G? 

Will docker consider daemon when looking into free memory? Let's say that docker daemon is consuming 0.25G and all containers combined 29.5G. And I want to start another container that needs 0.4G. Will it be scheduled or will be kept pending?

Thanks in advance!

**Comment by sasavilic** [comment]
@cpuguy83 If you could, I would really appreciate if you could respond to my previous question or point in right direction (documentation/code). We have some issues with docker and it seams that your knowledge could solve the it.

**Comment by cpuguy83** [comment]
@sasavilic 

> Does docker itself now knows that total sum of all containers + docker daemon itself must not go beyond 30G

No docker does not do this accounting.
I'm also not certain if containers would be under the parent cgroup of docker vs in a cgroup placed by docker in the cgroup root.
At the very least, containers can be placed into a custom parent.

**Comment by aroundthecode** [comment]
> @cpuguy83 Resource management of Docker needs to happen outside of Docker (cgroups).

Detailed procedure of doing so in documentation would be much appreciated since it's basically an advanced configuration for the docker engine itself.

**Comment by elouanKeryell-Even** [comment]
I found this: https://stackoverflow.com/a/46557336/3037171

**Comment by dnk8n** [comment]
What is the correct way to set limits as described in https://stackoverflow.com/a/46557336/3037171 if I am using a distro (Ubuntu 14.04) that uses Upstart as an init system instead of Systemd?

**Comment by nevmerzhitsky** [comment]
> This should be done with cgroups. If you are using systemd you can do this pretty easily.

I totally agree! But give an example how to do this in this article https://docs.docker.com/install/linux/linux-postinstall/

I trying to achieve limiting by cgroups for engine via "cgroup-parent" in `/etc/docker/daemon.json` but it looks like not working in the issue context.

**Comment by mohsenasm** [comment]
That wouldn't be better if there was something in `docker node update` that set a total memory limit for docker nodes?
