### ISSUE TITLE
Mounted directory in the Windows container is always in lowercase

### ISSUE THREAD

**Issue by sandersaares** [docker/docker#29271]
**Description**

Mounted directory in the Windows container is always in lowercase.

**Steps to reproduce the issue:**
1. `mkdir c:\tmp`
2. `docker run --volume c:\tmp\:C:\Foo\ -it microsoft/windowsservercore cmd`
3. `dir`

**Describe the results you received:**

`12/09/2016  10:53 AM    <SYMLINKD>     foo [...]`

**Describe the results you expected:**

`12/09/2016  10:53 AM    <SYMLINKD>     Foo [...]`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-dev
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   3c5e09f
 Built:        Sat Nov 12 03:56:46 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.13.0-dev
 API version:         1.25
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          3c5e09f
 Built:               Sat Nov 12 03:56:46 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 24
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.447.amd64fre.rs1_release_inmarket.161102-0100)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92 GiB
Name: jose
ID: 7YUR:ZJ6B:47ZU:ZJ2G:SNCO:FDE3:QMAX:BXBK:F3H2:3RYF:NRM2:VRVD
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Username: saaresaxinom
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

My physical PC.

**Comment by cpuguy83** [comment]
Presumably this is because windows is case-insensitive.

Ping @jhowardmsft

**Comment by jhowardmsft** [comment]
It is case insensitive. There's no issue here I can see...

**Comment by sandersaares** [comment]
Case-insensitivity does not make it okay for it to change the case of my typed in names. If I create a directory "Foo" in Windows, it does not get renamed to "foo". I would expect the same to hold true if I create it via Docker's `--volume` parameter.

**Comment by jhowardmsft** [comment]
And the issue actually is? This is by design on Windows. What's the actual problem this is causing in the real world?

**Comment by sandersaares** [comment]
It is merely a matter of increased compatibility with multiplatform code, to avoid needless platform differences. Consider multiplatform code that is (wrongly but realistically) case-sensitive. It creates a mount and later tries to use it.

This behavior would work on Linux and on Windows, as both are case-preserving, even if not case-sensitive. But it fails with Windows Docker, as it is not case-preserving. As a result, an avoidable compatibility problem is introduced.

**Comment by jhowardmsft** [comment]
Real world actual example that fails on Windows?

**Comment by sandersaares** [comment]
None to offer at the moment.

**Comment by jhowardmsft** [comment]
Then there is no issue. Please reopen if you have a concrete example.

**Comment by ivancavanaugh** [comment]
I do have an example. Fitnesse (https://github.com/fhoeben/hsac-fitnesse-docker/blob/master/chrome/Dockerfile) runs from dir /fitnesse/wiki/FitNesseRoot which is case sensitive. When I mount my local FitNesseRoot to this directory it is mounted as /fitnesse/wiki/fitnesseroot. Loosing the case renderd FitNesse not able to find the test.

compose snippet:
FrontEndIntegrationTests:
    image: hsac/fitnesse-fixtures-test-jre8-chrome:latest
    environment:
      - RE_RUN_FAILED=true
    command: -DfitnesseSuiteToRun=IntegrationTests.FrontEndTests
    volumes:
      - ./fitnesse/wiki/FitNesseRoot:/fitnesse/wiki/FitNesseRoot:rw

**Comment by jangorecki** [comment]
@lowenna shouldn't this be re-opened? there seems to be example provided 3 months ago

**Comment by joelvaneenwyk** [comment]
Agreed, this is a real issue. We have tests that run within the Windows Docker container that validate casing as it runs Perforce commands within the container and Perforce server is case sensitive. The workaround we have is to create the folders during build with the correct case and then when they are mounted those folders remain at the correct case, but this is incredibly brittle.
