### ISSUE TITLE
dockerd memory leak with gelf log driver

### ISSUE THREAD

**Issue by mdavranche** [docker/docker#29282]
**Description**

dockerd memory usage is growing up on high container output, and never releases it. The memory leak appears especially while using gelf log driver.

**Steps to reproduce the issue:**

1. Build a simple image that generates a lot of output on stdout:
```
# cat Dockerfile 
FROM debian:jessie
ADD entrypoint.sh /
ENTRYPOINT /entrypoint.sh
# cat entrypoint.sh 
#!/bin/bash
while `/bin/true`
do
  cat /var/log/*.log
done
# docker build --tag plopsimage .
```

2. Launch a fresh dockerd using gelf

`/usr/bin/dockerd -H 0.0.0.0:5040 -H unix://var/run/docker.sock -s overlay --log-driver=gelf --log-opt gelf-address=udp://127.0.0.1:25826`

3. Launch 3 containers using this image

`docker run -d plopsimage` (3 times)

4. Check the dockerd memory (resident size memory) in KB

```
# while `/bin/true`
do
  ps -eo rss,cmd | awk '{ if ($2 == "/usr/bin/dockerd") print $1 }'
  sleep 15
done
38100
69044 <= I launched the 3 containers
154464
184008
189272
189272
189272
189520
189520
189520
194440
194440
194440
194640
194640 <= I stopped and rm the 3 containers 
194640
194584
194584
```

**Describe the results you received:**

The dockerd resident size memory grows up (200MB for 3 containers) and never goes down. In my production environment, I have 25GB dockerd that are OOM killed most of the time!

**Describe the results you expected:**

Exactly the same test with a json-file log driver (in KB):

```
39292
61404 <= I launched the 3 containers
62444
62444
62444
64056
64056
64056
64164
64164
64164
64164
64164
64164
64164 <= I stopped and rm the 3 containers
64164
64164
64164
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Fri Nov  4 13:16:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Fri Nov  4 13:16:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: gelf
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.2.0-ovh-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 6.655 GiB
Name: privatesql002
ID: DYZS:OARC:7V5V:UPVO:3C6R:3OPI:35AA:MFE7:O7WM:3QFR:XVV2:KAZ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

OpenStack, Debian Jessie

**Comment by cpuguy83** [comment]
I'm not certain there's a leak here.
The increased usage is likely from buffering, where writing to disk as is done with the json logger is a bit faster than the network latency involved with gelf.

Then once go gets hold of some memory it does not free it right away.

**Comment by cpuguy83** [comment]
What may help here is to enable debug mode and capture the pprof data.

**Comment by mdavranche** [comment]
I think you're right about the buffering @cpuguy83 . The problem is that the memory is never freed as we can see on my production: dockerd using 25-30GB of RAM after few weeks, and before being OOM killed.

Here is the `go tool pprof --raw http://127.0.0.1:8080/debug/pprof/profile > local.raw` output.
[pprof.zip](https://github.com/docker/docker/files/645604/pprof.zip)

**Comment by cpuguy83** [comment]
@mdavranche What we really need is a snapshot from the `/heap` endpoint

**Comment by mdavranche** [comment]
Here is the `go tool pprof --raw http://127.0.0.1:8080/debug/pprof/heap > local.raw` output.
[pprof.zip](https://github.com/docker/docker/files/660796/pprof.zip)

**Comment by cpuguy83** [comment]
@mdavranche I don't know why I'm not able to load these profiles.
But probably something like `go tool pprof --svg --alloc_space http://127.0.0.1:8080/debug/pprof/heap` will be all that's needed.

**Comment by mdavranche** [comment]
Here it is!
[result.svg.zip](https://github.com/docker/docker/files/661669/result.svg.zip)

**Comment by cpuguy83** [comment]
@mdavranche Do you have the non-truncated version?
Also an `--in_use` instead of `--alloc_space` may be helpful here as well (Sorrt for the back and forth!).

**Comment by mdavranche** [comment]
Those 3 commands had been launched few seconds after running dockerd with 3 test containers detailed above:

`# ps -eo size,rss,cmd | awk '{ if ($3 == "/usr/bin/dockerd") print $0 }'
969236 223356 /usr/bin/dockerd -H 0.0.0.0:5040 -H unix://var/run/docker.sock -s overlay -D --log-driver=gelf --log-opt gelf-address=udp://127.0.0.1:25826`
(947MB allocated, 218MB used)

`go tool pprof --svg --inuse_space http://127.0.0.1:8080/debug/pprof/heap`
[inuse_space.zip](https://github.com/docker/docker/files/708446/inuse_space.zip)

`go tool pprof --svg --alloc_space http://127.0.0.1:8080/debug/pprof/heap`
[alloc_space.zip](https://github.com/docker/docker/files/708433/alloc_space.zip)

**Comment by cpuguy83** [comment]
@mdavranche Can you run this with many many more containers, and keep them running and outputting to stdout for awhile?

**Comment by mdavranche** [comment]
I launched 100 containers like the one described above.
`while `/bin/true`; do ps -eo size,rss,cmd | awk '{ if ($3 == "/usr/bin/dockerd") print $1" "$2 }'; sleep 15; done`
[output.zip](https://github.com/docker/docker/files/709003/output.zip)

pprof launched just after the 100 containers had been launched (2.6GB allocated, 688MB used):
[1.zip](https://github.com/docker/docker/files/709011/1.zip)

1 hour later (2.7GB allocated, 796MB used):
[2.zip](https://github.com/docker/docker/files/709013/2.zip)

**Comment by cpuguy83** [comment]
This is only happening with gelf?

**Comment by mdavranche** [comment]
Yes. This is why I roll-backed my log driver to the json one.

**Comment by cpuguy83** [comment]
From the usage stats you provided, I'm not sure that it's really leaking, more likely logs getting backed up on sending.
You may try disabling compression in the gelf driver with `--log-opt gelf-compression-type=none`

**Comment by mdavranche** [comment]
Indeed, using the `gelf-compression-type=none` log option consumes much less memory.

I close this issue. Please feel free to re-open it or open a new one if you consider that stopping and removing the containers should free the dockerd memory. Presently it does not, for any log driver, as you can see in this issue description (see both "I stopped and rm the 3 containers").

Thanks for your help @cpuguy83

**Comment by cpuguy83** [comment]
Go is pretty stingy about releasing memory back to the OS, and we're also doing some funky stuff with buffer allocation for stdio that may be what you are seeing.
But it'd probably be good to take a closer look at some of this... maybe in some case there's a buffer that's not properly freed and as such can't get GC'd? Or could be somewhere else entirely.
