### ISSUE TITLE
Misleading default for --replicas

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#29291]
The help text for `--replicas` on `service update` and `service create` says the default is "none".

```
      --replicas uint                    Number of tasks (default none)
```

In fact, creating a replicated service without `--replicas` uses 1 replica, not zero as this description might suggest.

**Comment by thaJeztah** [comment]
I think this is a problem in general (we may have an open issue for this, but I should search); the problem here is that many defaults are set on the daemon, not by the client. Because of this, the client cannot show the default, because they are only known by the daemon

**Comment by aaronlehmann** [comment]
Yes, that issue is #24959. However, I think of this one differently. We should simply not display `(default none)`, because this reads as if the default is no replicas. No information is better than misleading information. Displaying useful defaults would be nice, but I see that as a different issue.

**Comment by thaJeztah** [comment]
Agreed, that not showing this would be good in this case

**Comment by yongtang** [comment]
The output of `(default none)` is handled in:
https://github.com/docker/docker/blob/v1.13.0-rc3/vendor/github.com/spf13/pflag/flag.go#L422-L452
https://github.com/docker/docker/blob/v1.13.0-rc3/vendor/github.com/spf13/pflag/flag.go#L535-L541

One way to prevent`(default none)` is to set `f.Value.String()` to `""`. Added a PR #29450 for that.

Note `--restart-max-attempts` is similar to `--replicas`. Maybe we should change `--restart-max-attempts` to not display `(default none)` as well?

**Comment by aaronlehmann** [comment]
Let's also do this for `--restart-delay`, `--restart-max-attempts`, and `--stop-grace-period`.
