### ISSUE TITLE
docker push - denied

### ISSUE THREAD

**Issue by mvlach** [docker/docker#29315]
```
mvlach$ docker login registry.XXXX.cz
Username (miloslav.vlach):
Password:
Login Succeeded
```

```
mvlach$ docker push registry.XXXX.cz/project/elasticsearch:1.7.4
The push refers to a repository [registry.XXXX.cz/project/elasticsearch]
949663c76548: Layer already exists
3241175a9c5c: Layer already exists
43f07eff48f7: Layer already exists
222cf85e9eec: Layer already exists
23b37b346afc: Layer already exists
2084abd15ec9: Layer already exists
ef98afca0081: Layer already exists
0f02d635c0b1: Layer already exists
c045569e5db3: Layer already exists
e4b690d9ba33: Layer already exists
133d54bcd235: Layer already exists
1be3b0873025: Layer already exists
0de9d866d419: Layer already exists
149636c85012: Layer already exists
f96222d75c55: Layer already exists
denied
```

**Comment by justincormack** [comment]
Please can you give enough information to debug the issue, at least what is required by the template, and some information about what the registry is and if the registry logged any errors.

**Comment by harunurkst** [comment]
I am following this [tutorial]( https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-ubuntu-16-04)
I just create an ubuntu image and want to push it. it shows: 
```
harun@:~$ docker login -u harunurn
Password: 
Login Succeeded
harun@:~$ docker push ubuntu
The push refers to a repository [docker.io/library/ubuntu]
5eb5bd4c5014: Preparing 
d195a7a18c70: Preparing 
af605e724c5a: Preparing 
59f161c3069d: Preparing 
4f03495a4d7d: Preparing 
denied: requested access to the resource is denied
```

**Comment by thaJeztah** [comment]
@harunurkst that's expected; you are trying to overwrite the official `ubuntu` image, but you're not allowed to.

You can only push to your own repository on docker hub, so you have to `docker tag` that image first, e.g.;

    docker tag some-image harunurn/some-image
    docker push harunurn/some-image

**Comment by thaJeztah** [comment]
I'm closing this issue because there's not enough information from the original reporter to act on

**Comment by 31H0B1eV** [comment]
@harunurkst i think you miss note in this [page](https://docs.docker.com/engine/getstarted/step_six/) which told that your image tag must be the same as your Docker Hub account name.

**Comment by kingberrill** [comment]
i fixed the issue by tagging the image to the same username as my docker hub account and it worked

**Comment by Jithinbabusbce** [comment]
Try adding the tag and push the image

docker tag image YOUR_DOCKERHUB_NAME/iimage

 docker push YOUR_DOCKERHUB_NAME/image

**Comment by timbobb** [comment]
@Jithinbabusbce .... thanks for the input.. it worked
