### ISSUE TITLE
How many containers in a cluster use macvlan network mode will cause ARP broadcast storm ?

### ISSUE THREAD

**Issue by hallwin** [docker/docker#29322]
docker version: 1.12.3
network mode: macvlan

How many containers(or hosts) in a cluster use macvlan network mode will cause ARP broadcast storm ? or affect the network performance caused by ARP broadcast?

thank you !

**Comment by allencloud** [comment]
ARP broadcast storm?

**Comment by wenjianhn** [comment]
Broadcast traffic should be less than 20 percent of all traffic on each network segment.
(Some networks are more sensitive to broadcast traffic and should use a 10 percent
threshold.)
The thresholds might not apply to all networks.

**Comment by cpuguy83** [comment]
Closing since it's not really an issue. Feel free to continue discussing here, or hop onto the community slack in the docker-networking channel.
