### ISSUE TITLE
awslogs: support for CreateLogGroup if awslogs-group does not exist

### ISSUE THREAD

**Issue by consultantRR** [docker/docker#29334]
Just making an enhancement request for support for auto-creation of a new Log Group (using a CreateLogGroup call in AWS) if the specified `awslogs-group` does not exist.

Currently this fails as follows:

```
ResourceNotFoundException: The specified log group does not exist.
```

**Comment by yongtang** [comment]
In our experience, when we hit a resource not found issue in AWS, it is very common the region was not correctly configured. From that standpoint I am thinking if awslog driver in docker automatically creates Log Group, we may want to set the default behavior to false (only enable it explicitly). Otherwise Log Groups might be created inadvertently if user is not very careful with region configuration.

/cc @samuelkarp

**Comment by consultantRR** [comment]
That sounds like a sensible approach to me.

**Comment by consultantRR** [comment]
I also note that the official AWS CloudWatch Logs Agent _does_ create missing log-groups by default, so doing so in docker would not necessarily be unexpected or inconsistent behavior.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/AgentReference.html

**Comment by thaJeztah** [comment]
This functionality was disabled on purpose, see https://github.com/docker/docker/pull/19617#issuecomment-175873698, and https://github.com/docker/docker/pull/19617#issuecomment-182095699 for some background.

Quoting here;

> For some background: I originally decided against this behavior due to the service limit of [500 log groups](http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_limits.html) and to protect against exhausting that limit accidentally by making typos.  However, I'd be happy to defer to the Docker maintainers if this behavior is ultimately desirable.

And

> Since logs are generated for every container on the system, and potentially we end up calling CreateGroup every time, it seems redundant and potentially surprising.

**Comment by consultantRR** [comment]
Is there potentially any leeway for a user option to explicitly enable this behavior, as @yongtang suggested? For some use cases, the need to externally create log groups in advance is a hassle at best, and sometimes more problematic. And, as I mentioned, it counters the behavior of the official AWS logs agent.

**Comment by thaJeztah** [comment]
Maybe there is; perhaps @samuelkarp has some suggestions for that. Having previously rejected a feature does not mean it is permanently rejected; it just didn't look like a good option at the time. With a proper design / proposal, perhaps there is a reasonable solution that would address the problems raised in the previous discussion.

We sometimes just have to be conservative, and go for the "common rule"; "no is temporary, yes is forever" (i.e., once something is implemented, we'll basically have to support it for every future version)

**Comment by samuelkarp** [comment]
I think @yongtang's suggestion about enabling creation through an option but defaulting to not creating a log group is reasonable.  Possibly something like `--log-opt awslogs-create-group` where the default is false.

**Comment by yongtang** [comment]
Added a PR #29504 as an attempt for `--log-opt awslogs-create-group`. Please take a look.
