### ISSUE TITLE
Docker exec failed to set user after docker daemon restart

### ISSUE THREAD

**Issue by amyangfei** [docker/docker#29342]
**Description**

**Steps to reproduce the issue:**
1. Enable docker with `live-restore=true`
2. Start a container from existing image. `docker run -it --rm python:2.7 /bin/bash`
3. Create a new user in this container. `groupadd -r test && useradd -r -g test test -s /bin/bash`
4. Open another terminal, use `docker exec` to run some command, such as `docker exec -u test ce5e1b718c9c python -c "import os; print os.getuid()"`
5. Restart docker daemon
6. Run the same command in step 4 again. `docker exec -u test ce5e1b718c9c python -c "import os; print os.getuid()"`

**Describe the results you received:**

In `step 2` we get `999` which  corresponds with `test:x:999:999::/home/test:/bin/bash` in `/etc/passwd`

However in `step 6` we get:
```
unable to find user test: no matching entries in passwd file
```
`docker exec` seems to find user from `/etc/passwd` on host machine after `docker daemon` restart

**Describe the results you expected:**

We wish to get `999` in step 6, 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:39:14 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 27
 Running: 10
 Paused: 0
 Stopped: 17
Images: 390
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /home/projects/docker/aufs
 Backing Filesystem: extfs
 Dirs: 393
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 494.4 MiB
Name: psigor-node-igor
ID: KGA3:GPR7:YP6T:VEV7:MBP2:YOHZ:6XHZ:W7VK:EKG4:RPDX:P4DX:USY6
Docker Root Dir: /home/projects/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
Confirmed that this issue is not solved in master ( e9076c0f00898e7af05e667d65ecb84a6e15d9c8 )

**Comment by thaJeztah** [comment]
ping @justincormack @mlaventure PTAL

**Comment by yongtang** [comment]
It looks like `BaseFS` is not present when calling `getUser`. Added a PR #29365 to try to address this issue.
