### ISSUE TITLE
cannot stop/connect service container on swarm cluster

### ISSUE THREAD

**Issue by shankarkc** [docker/docker#29343]
I have created a service. One of its container turned zombie. Containers uses tini to avoid zombie containers. But i still hit this issue.

Container doesnt respond to docker connect/stop command

**Steps to reproduce the issue:**
1. check the containers ID and try to connect to it OR try to stop it.
```
root@mo-7ecf25ab6:~# docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                NAMES
2a125ed7e9d2        registry.mo.sap.corp:5004/ai/node:0.0.23   "/tini -- /opt/seleni"   16 hours ago        Up 16 hours         3000/tcp, 5555/tcp   SeleniumNode.7.bf7nyrzl9l2r5w2u4nzhzt3wn

root@mo-7ecf25ab6:~# docker exec -it 2a125ed7e9d2 bash
rpc error: code = 13 desc = invalid header field value "oci runtime error: exec failed: container_linux.go:247: starting container process caused \"process_linux.go:83: executing setns process caused \\\"exit status 16\\\"\"\n"

root@mo-7ecf25ab6:~# docker stop 2a125ed7e9d2
^C
```
**Describe the results you received:**
Connecting to docker container gives the error shown above.
docker stop CONTAINERID hangs.
Even docker service restart wont help to get rid of this zombie container
Here is the upstart log...
```
time="2016-12-13T03:12:40.473657504Z" level=info msg="Container 2a125ed7e9d2f91d037a7dd097aeee42fe7dd688fb22015f59adbe256c835e68 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-12-13T03:12:50.475221412Z" level=info msg="Container 2a125ed7e9d2 failed to exit within 10 seconds of kill - trying direct SIGKILL"
time="2016-12-13T03:14:12.506438976Z" level=error msg="Error running exec in container: rpc error: code = 13 desc = invalid header field value \"oci runtime error: exec failed: container_linux.go:247: starting container process caused \\\"process_linux.go:83: executing setns process caused \\\\\\\"exit status 16\\\\\\\"\\\"\\n\""
time="2016-12-13T03:14:12.506892670Z" level=error msg="Handler for POST /v1.24/exec/488fa7b76e82a56362b604ae248bca58286cf170fe4b863540a8a36e16bc3c0d/resize returned error: rpc error: code = 2 desc = containerd: process not found for container"
time="2016-12-13T03:15:11.929252959Z" level=info msg="Container 2a125ed7e9d2f91d037a7dd097aeee42fe7dd688fb22015f59adbe256c835e68 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-12-13T03:15:16.930656043Z" level=error msg="Handler for DELETE /v1.24/containers/2a125ed7e9d2 returned error: You cannot remove a running container 2a125ed7e9d2f91d037a7dd097aeee42fe7dd688fb22015f59adbe256c835e68. Stop the container before attempting removal or use -f"
time="2016-12-13T03:15:21.930249727Z" level=info msg="Container 2a125ed7e9d2 failed to exit within 10 seconds of kill - trying direct SIGKILL"
time="2016-12-13T03:20:01.834086435Z" level=info msg="Container 2a125ed7e9d2f91d037a7dd097aeee42fe7dd688fb22015f59adbe256c835e68 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-12-13T03:20:11.835354321Z" level=info msg="Container 2a125ed7e9d2 failed to exit within 10 seconds of kill - trying direct SIGKILL"
time="2016-12-13T03:20:12.305977845Z" level=info msg="Container 2a125ed7e9d2f91d037a7dd097aeee42fe7dd688fb22015f59adbe256c835e68 failed to exit within 10 seconds of signal 15 - using the force"
time="2016-12-13T03:20:17.306046419Z" level=error msg="Handler for DELETE /v1.24/containers/2a125ed7e9d2 returned error: You cannot remove a running container 2a125ed7e9d2f91d037a7dd097aeee42fe7dd688fb22015f59adbe256c835e68. Stop the container before attempting removal or use -f"
```
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
As of now only way to getRidOf this container is to uninstall docker and reinstall it. Is this a known issue?
after this if i restart docker service and execute docker ps command it hangs forever. 

**Output of `docker version`:**
```
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 21:44:32 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 10
 Running: 1
 Paused: 0
 Stopped: 9
Images: 1
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 45
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge overlay null
Swarm: active
 NodeID: cd2wz7idadk07kj7fzjf71vby
 Is Manager: false
 Node Address: 10.173.77.81
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.66 GiB
Name: mo-7ecf25ab6
ID: KFYI:3LXO:3CZL:Q67A:QJER:4HY5:ESFO:3GA7:YL5Q:Q5ZC:NCNZ:DJXC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 seleniumNodeType=node
Insecure Registries:
 127.0.0.0/8
```

**Comment by cpuguy83** [comment]
When it's hung, can you send `SIGUSR1` to the dockerd process and collect the stacktrace from the logs?

**Comment by shankarkc** [comment]
I just released that aws machine. I will try this and get call stack when i hit it again.

**Comment by shankarkc** [comment]
Here the stack trace 

[docker.log.zip](https://github.com/docker/docker/files/657031/docker.log.zip)

Thanks
Shankar KC

**Comment by shankarkc** [comment]
Can you pls help me to get rid of this zombie container? it does respond to stop/rm. If I restart docker and run "docker ps" it hangs forever. Only option is to remove and reinstall docker which is painful

**Comment by shankarkc** [comment]
Hi there is there any way to remove this zombie container?  Did the stack dump helped to find out the rott cause?

**Comment by thaJeztah** [comment]
@shankarkc I notice that that container is part of a service; given that Swarm will start new containers to replace failing ones, is it really a "ghost" container, or is swarm just creating a new container because the previous one failed? What does `docker service ps SeleniumNode` show?

I notice you're running aufs on kernel 4.2.0-27; there was a bug in kernel versions lower than 4.2.0-30.35, resulting in processes hanging (although mainly for Java processes); see https://github.com/docker/docker/issues/18180#issuecomment-193708192. It may be worth making sure you're running the latest 4.2 kernel, and see if that helps for your issue as well.

**Comment by shankarkc** [comment]
Its a zombie container for sure because even after  removing SeleniumNode service it wont go away. I even have scaled it to zero.  Still this zombie container exist. Neither stop containerId nor rm -f containerid helped. I will check if i am running latest kernel and update tomorrow once i reach office.

**Comment by thaJeztah** [comment]
> even after removing SeleniumNode service it wont go away.

looking at your top description, that may be because you ran `docker stop`; manually stopping a container makes swarm mode stop managing it, so removing the service will no longer remove it

**Comment by shankarkc** [comment]
I  don't see service container hang after updating kernel. So closing the issue.
