### ISSUE TITLE
FAIL: docker_cli_logs_test.go:250: DockerSuite.TestLogsFollowSlowStdoutConsumer

### ISSUE THREAD

**Issue by YummyPeng** [docker/docker#29341]
**Description**

When I run docker-v1.9.1 integration test these days, I always got this error:
```
----------------------------------------------------------------------
FAIL: docker_cli_logs_test.go:250: DockerSuite.TestLogsFollowSlowStdoutConsumer

docker_cli_logs_test.go:279:
    c.Fatalf("Invalid bytes read: %d, expected %d", actual, expected)
... Error: Invalid bytes read: 2786, expected 200000


----------------------------------------------------------------------
```
I have tried to explore the issue list but haven't got a helpful solution. However, this failure didn't appear in docker-v1.11.2. I guess maybe the implementation of `docker logs -f` in docker-v1.9.1 causes the issue but I can't find the root causes.
Tons of thanks if anyone can help.

**Steps to reproduce the issue:**

```
root@ubuntu:~/docker# TESTFLAGS='-check.f TestLogsFollowSlowStdoutConsumer' make test-integration-cli
```

**Output of `docker version`:**

```
root@ubuntu:~/docker# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
root@ubuntu:~/docker# uname -a
Linux ubuntu 3.16.0-77-generic #99~14.04.1-Ubuntu SMP Tue Jun 28 19:17:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
This may have been a flaky test (also see https://github.com/docker/docker/issues/16462, https://github.com/docker/docker/pull/27782), but given that we no longer do maintenance on the 1.9.x branch, I don't think there's anything we can do here. I'll close this issue for that reason, but feel free to continue the conversation

Is there a reason for you to build the 1.9.x binaries?

**Comment by YummyPeng** [comment]
@thaJeztah I don't think my issue is related with race in `docker logs -f` because it never hangs. 

I met this issue occasionally a few days ago and tried hard to find solution but failed, so I turn to here to see if anyone can solve my confusion.

Thank you anyway :smile:
