### ISSUE TITLE
Failed to pull docker image on RHEL 7 with docker 1.13

### ISSUE THREAD

**Issue by liyaka** [docker/docker#29354]
**Description**
Failed to pull docker image on RHEL 7 after upgrading to 1.13.rc3
**Environment**
Red Hat Enterprise Linux Server release 7.2 (Maipo)
docker version:
```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        
 OS/Arch:      linux/amd64
 Experimental: false
```
Docker service configuration:
```
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target firewalld.service

[Service]
Type=notify
# the default is not to use systemd for cgroups because the delegate issues still
# exists and systemd currently does not support the cgroup feature set required
# for containers run by docker
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock --log-opt max-size=50m  --insecure-registry ourregistry:5000 --label=role=app --storage-driver=devicemapper --storage-opt dm.datadev=/dev/ttt/docker-data --storage-opt dm.metadatadev=/dev/ttt/docker-metadata  --storage-opt dm.use_deferred_removal=true --storage-opt dm.basesize=30G
ExecReload=/bin/kill -s HUP $MAINPID
# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
#TasksMax=infinity
TimeoutStartSec=0
# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes
# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
```
Filesystem:
lsblk 
```
NAME                           MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
xvda                           202:0    0   20G  0 disk 
|-xvda1                        202:1    0    1M  0 part 
`-xvda2                        202:2    0   20G  0 part /
xvdf                           202:80   0  300G  0 disk 
|-ttt-docker--data        253:0    0  200G  0 lvm  
| `-docker-202:2-17191269-pool 253:3    0  200G  0 dm   
|-ttt-docker--metadata    253:1    0    3G  0 lvm  
| `-docker-202:2-17191269-pool 253:3    0  200G  0 dm   
`-ttt-data                253:2    0   93G  0 lvm  /Data
```
Commands I run:
```
docker pull hello-world
Using default tag: latest
latest: Pulling from library/hello-world
c04b14da8d14: Pull complete 
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest
```
Works fine. But then trying for a bigger image:
```
docker pull portainer/portainer:1.10.2
1.10.2: Pulling from portainer/portainer
a3ed95caeb02: Already exists 
802d894958a2: Extracting [==================================================>] 143.3 kB/143.3 kB
c6e381376096: Download complete 
failed to register layer: devmapper: Unknown device 262ad7c056621dda8e3bd916da56eb213e9e2cfaebbab802bcab3035734bbb71
```

What can be the problem?

**Comment by thaJeztah** [comment]
Could you add the output of `docker info` ? Is it possible device mapper ran out of space?

**Comment by liyaka** [comment]
docker info
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 14
Server Version: 1.13.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-202:2-17191269-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 32.21 GB
 Backing Filesystem: xfs
 Data file: /dev/thetaray/docker-data
 Metadata file: /dev/thetaray/docker-metadata
 Data Space Used: 12.32 GB
 Data Space Total: 214.7 GB
 Data Space Available: 202.4 GB
 Metadata Space Used: 17.56 MB
 Metadata Space Total: 3.221 GB
 Metadata Space Available: 3.204 GB
 Thin Pool Minimum Free Space: 21.47 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: wu51b5zyqyv41vgw55jhg52s4
 Is Manager: true
 ClusterID: yb522mycxt13m2enefikncdvs
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.16.1.75
 Manager Addresses:
  172.16.1.75:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 14.28 GiB
Name: ip-172-16-1-75.us-west-2.compute.internal
ID: RLGZ:DDZ5:S7SG:APF4:BM2A:PTQN:OAEY:FX34:JSVA:MQVN:2UFD:UR2E
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 role=app
Experimental: false
Insecure Registries:
 ourregistry:5000
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by thaJeztah** [comment]
ping @rhvgoyal @tonistiigi any ideas?

**Comment by rhvgoyal** [comment]
Unknown device message comes from lookupDevice() in devicemapper.

That means a file with details to this device is not there. I suspect that somehow that device has been removed in the past.

Looking at messages

a3ed95caeb02: Already exists

I suspect this device might be belonging to this layer. You can do `docker inspect a3ed95caeb02` and see what's the storage device associated with it. 

Try removing image layer image `a3ed95caeb02` and pull again and see if it works.

**Comment by liyaka** [comment]
There is no such a layer..

**Comment by rhvgoyal** [comment]
@thaJeztah  If there is no such layer and docker pull says layer already exists, I think there is some bug in generic layer code and its not a graph driver issue.

**Comment by liyaka** [comment]
btw, everything worked fine with 1.12.x on the same machine, so it looks like a bug in 1.13

**Comment by liyaka** [comment]
Any workaround you can suggest?

**Comment by tonistiigi** [comment]
@rhvgoyal You can't inspect a layer or even more, a hash of a compressed distribution layer blob that `a3ed95caeb02` is.

**Comment by rhvgoyal** [comment]
@tonistiigi not sure why we will not be able to inspect `a3ed95caeb02`. docker pull says this layer is already present and if that's the case we should be able to inspect it.

If its associated graph driver Id (I guess calculated using hash of contents), is missing, then I agree inspect will fail as graph driver will refuse to return data associated with it.

But as I understand, core of the problem seems to be that `docker images -a` does not list the image. Is that right @liyaka . If that's the not the problem, then issue is how graph driver data got deleted while image data is still around.

**Comment by tonistiigi** [comment]
@rhvgoyal `a3ed95caeb02` is a hash of a blob not an image. Even if it was a layer(the ones you see in `docker inspect --format '{{.RootFS}}'`) it's not an image and can't be inspected.

Most likely thing that is happening here is that after the upgrade devicemapper's backing storage got switched out. Afaik docker does not detect any changes to `--storage-opt` and metadata about existing layers is only stored by the driver name. So docker expects layers to exist because it has metadata about it but when they are looked up from the driver they appear to be missing. Other way how this would show is that old images pulled with `v1.12` would show up in `docker images` but when you create a container from them you would get the same device lookup error. If this is the case and switch to a fresh devicemapper devices was intentional then the docker storage dir `/var/lib/docker` should be cleared as well.

**Comment by rhvgoyal** [comment]
@tonistiigi, ok, it is hash of blob and not image id. did not know it.

Iven if data/metadata device was switched out, this error should not have happened. It can't find the file with same name in /var/lib/docker/devicemapper/... dir. 

Also if data/metadata device was switched out, devicemapper will detect it. When it activates thin pool, it queries the UUID of base device file system and matches it with the stored UUID. If it does not match, docker fails saying wrong thin pool. That's the mechanism we introduced to catch these kind of errors.

**Comment by tonistiigi** [comment]
@rhvgoyal If I do

```
> dockerd -s devicemapper --storage-opt dm.override_udev_sync_check=true -D 2>/daemon.log &
> docker pull busybox
> kill %1 && wait %1
> rm -rf /var/lib/docker/devicemapper/
> dockerd -s devicemapper --storage-opt dm.override_udev_sync_check=true -D 2>/daemon.log &
> docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
busybox             latest              e02e811dd08f        2 months ago        1.09 MB
> docker run busybox ls
docker: Error response from daemon: devmapper: Unknown device 35ab199fb7ac37e94ee072de54e6a41562fcca6f6f5c2a4e554699e0b2757eed.
See 'docker run --help'.
```

**Comment by tonistiigi** [comment]
@rhvgoyal For the "metadata" I meant the data docker keeps about layers `/var/lib/docker/image/devicemapper/` etc. not the devicemapper's own metadata.

**Comment by rhvgoyal** [comment]
@tonistiigi ok, got it. I was referring to switching thin pool data or metadata device. Agreed, if you do something with /var/lib/docker, then things will go wrong for sure.

**Comment by liyaka** [comment]
I got the same problem with clean docker 1.13 rc3 install on RHEL 7.2, so it doesn't seem to be an upgrade issue..
@rhvgoyal image is indeed not listed

**Comment by tonistiigi** [comment]
@liyaka Does it show `a3ed95caeb02: Already exists` for a fresh install on first pull?

**Comment by liyaka** [comment]
@tonistiigi not on the first pull

**Comment by liyaka** [comment]
I found a bug in my automatic installation - thank to your questions!
Please close this issue
