### ISSUE TITLE
Accept Linux-style mount paths on Windows

### ISSUE THREAD

**Issue by sandersaares** [docker/docker#29353]
**Description**

It would be nice if Docker supported Linux style paths for `--volume` even when operating on Windows. Keeps things uniform and enables the same automation/scripting be used regardless of platform.

**Steps to reproduce the issue:**

1. `docker run --volume /tmp/:/tmp/ microsoft/windowsservercore`

**Describe the results you received:**

```
c:\Program Files\docker\docker.exe: Error response from daemon: invalid bind mount spec "/tmp/:/tmp/": invalid volume specification: '\tmp\:\tmp\'.
```

**Describe the results you expected:**

Successful mounting of `C:\tmp\` to `C:\tmp\`.

**Additional information you deem important (e.g. issue happens only occasionally):**

Many other Windows tools (e.g. PowerShell and .NET) work fine with Linux style paths and treat a Linux root as the root of the "current" drive. Obviously the drive ambiguity is not solvable in this case but as far as all I care about is a single drive, life is well improved with this enhancement.

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   e308f6b
 Built:        Tue Nov 22 18:15:55 2016
 OS/Arch:      windows/amd64

Server:
 Version:             1.14.0-dev
 API version:         1.26
 Minimum API version: 1.24
 Go version:          go1.7.3
 Git commit:          e308f6b
 Built:               Tue Nov 22 18:15:55 2016
 OS/Arch:             windows/amd64
 Experimental:        false
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 35
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.479.amd64fre.rs1_release.161110-2025)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92 GiB
Name: jose
ID: 7YUR:ZJ6B:47ZU:ZJ2G:SNCO:FDE3:QMAX:BXBK:F3H2:3RYF:NRM2:VRVD
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): false
Username: saaresaxinom
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical pc

**Comment by jhowardmsft** [comment]
Why? Would it make sense for a Linux daemon to accept Windows-style semantics? It makes no sense to me. Windows is not Linux. Linux is not Windows. Let's face the reality of the platform differences. Hence closing.

**Comment by sandersaares** [comment]
> Windows is not Linux. Linux is not Windows. Let's face the reality of the platform differences.

I think this is an old world mindset that is every day holding less true in the modern world. It is sad that the design of the Windows Docker components propagates platform differences in this way.

**Comment by friism** [comment]
@sandersaares I agree with @jhowardmsft - trying to do this kind a magic is brittle and fails in non-intuitive ways. Other parts of the Docker toolchain have tried to do similar things historically (eg. `docker-compose` on Windows running on Docker Toolbox running a Linux engine). The different pieces of magic invariably get in each others way.

The history of developer tools is littered with attempts at papering over Linux/Windows differences (line-endings, path separators, eg.) and in my experience the result is never good.

**Comment by AceHack** [comment]
@sandersaares I agree with you 100%, I'm trying to create multi-arch containers and things like this force maintaining two versions of composing files, one for windows and one for everything else, this simple change would make the experience much better.  Especially since most windows file APIs accept Linux file paths without any issues or "magic".  Windows itself understands Linux path styles.
