### ISSUE TITLE
1.13-rc3 will not work with compose file

### ISSUE THREAD

**Issue by lenshion** [docker/docker#29350]
Hi,

I am using 1.13-rc3 experimental, try to use compose-file to orchestrating my services.

I tried commands like this:

[ec2-user@ip-192-168-1-110 ~]$ sudo docker stack deploy --compose-file docker-compose.yml
"docker stack deploy" requires exactly 1 argument(s).
See 'docker stack deploy --help'.

Usage:  docker stack deploy [OPTIONS] STACK

Deploy a new stack or update an existing stack

Here is my docker information:

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-202:2-33554688-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB

What did I missed? Or 1.13 doesn't support a compose file.

**Comment by thaJeztah** [comment]
the stack name is a required parameter; unlike docker-compose, it doesn't automatically generate one from the name of the directory that the docker-compose file is in.

 from your description, it looks like you forgot to add that
