### ISSUE TITLE
image deprecation warnings or notifications

### ISSUE THREAD

**Issue by unclejack** [docker/docker#2936]
Some Docker users have found documentation on the Internet which still hasn't been updated to reflect the fact that the `base` image is being deprecated and that the `ubuntu` images should be used instead. Some other users have been using Docker since `base` was the image the docs were recommending as the standard image.

There should be a way to let users know an image has been deprecated. Here are some options on how users could be warned or notified that a particular image is being deprecated :

1. display a warning on the index page of that image (can be combined with other options or used as a standalone option)
2. display a warning when the user pulls the image from the registry (alternative to 3)
3. start serving the image with a deprecation flag once it's marked for deprecation (alternative to 2)
4. add a new flag to `docker pull` which only checks if an image (or any of its layers) is marked for deprecation (could be used together with 1 and 2)

This issue supersedes #1379.

**Comment by LK4D4** [comment]
@aaronlehmann @stevvooe This is very old issue. Do you think anything can be done on docker side and worth it?

**Comment by aaronlehmann** [comment]
Doesn't sound worth it to me.

**Comment by LK4D4** [comment]
Closing it then for now.
