### ISSUE TITLE
Error using an image which already exists in another storage driver

### ISSUE THREAD

**Issue by shykes** [docker/docker#2943]
My docker installation has the image `ubuntu` already installed on the `devicemapper` driver.

If I restart my docker daemon with the `aufs` daemon, I get an error when using the `ubuntu` image:

```
# docker run ubuntu echo hello
2013/11/28 22:58:20 Error: create: Unable to mount using aufs invalid argument
# dmesg | tail -n 1
[246620.657816] aufs opt_add:714:docker[28297]: lookup failed /var/lib/docker/aufs/diff/8dbd9e392a964056420e5d58ca5cc376ef18e2de93b5cc90e868a1bbc8318c1c (-2)
#
```

I verified this with multiple images, not just ubuntu. If the image exists on the other driver, it fails. If it doesn't exist on the other driver, it works.

**Comment by cpuguy83** [comment]
I'm not sure I see the point of the issue right now?
Is this issue specifically that docker won't pull `ubuntu` if it's loaded from a previously run graph driver or is there something deeper here?
If so it seems like that is no longer an issue.

**Comment by crosbymichael** [comment]
I think we can close this one now. You will not get an error anymore because the image tags are stored in driver specific files.
