### ISSUE TITLE
docker-compose on ubuntu with 1.12.4 doesn't work

### ISSUE THREAD

**Issue by MihaMarkic** [docker/docker#29445]
**Description**
docker-compose on ubuntu 16.04 and docker 1.12.4 doesn't work. It works with 1.12.3 and earlier.

**Steps to reproduce the issue:**
1. start any docker-compose up

**Describe the results you received:**

> ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

**Describe the results you expected:**

docker-compose should start containers

**Additional information you deem important (e.g. issue happens only occasionally):**

Happens all the time

**Output of `docker version`:**

```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 3
 Paused: 0
 Stopped: 12
Images: 22
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 150
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 983.8 MiB
Name: kauchuk
ID: ROJ7:X3EK:6OVR:LI3P:TMVE:W44H:DLHN:SIGT:M6TN:O2OJ:3NQC:5FUG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by ripcurld00d** [comment]
@MihaMarkic 
From the error message I guess `docker-compose` fails to send the request to `dockerd` because it uses a different unix-socket.

Let me try and figure out what is going on there unless someone else knows better.
😅

**Comment by MihaMarkic** [comment]
Hi guys, I downgraded to 1.12.3 for now and I'm a bit afraid to try it again since it's my production server. Will try to repro locally.

**Comment by tiborvass** [comment]
@MihaMarkic what's the output of `docker-compose version` ?

**Comment by MihaMarkic** [comment]
@tiborvass 
```
docker-compose version 1.9.0, build 2585387
docker-py version: 1.10.6
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by justincormack** [comment]
cc @andrewhsu

**Comment by thaJeztah** [comment]
@MihaMarkic to confirm; only `docker-compose` failed to connect to the daemon, but you could still run docker commands directly (`docker run` , `docker info`). And containers were still running as usual (based on your output of `docker info`)

Can you give some more information about your setup? Is `docker-compose` installed on the same host as the daemon is running, or are you using a local `docker-compose` to connect to a remote daemon?

**Comment by MihaMarkic** [comment]
@thaJeztah Actually docker-compose containers weren't running (they should restart: always).
Setup: all local.

**Comment by MihaMarkic** [comment]
I upgraded to 1.12.6 and docker-compose is working jut fine now.
