### ISSUE TITLE
docker logs --sinceminutes <ago>

### ISSUE THREAD

**Issue by tronicum** [docker/docker#29449]
would you be interested in a PR that implements docker logs --sinceminutes (that just calculates a timestamps X minutes ago)? I would find that more handy than the 2016-12-15T14:00 format.

**Comment by AkihiroSuda** [comment]
SGTM, but for UX, I think  the CLI should be consistent with proposed `docker container prune --filter until=<ago>` https://github.com/docker/docker/pull/29226
The CLI design for 29226 is not fixed yet and under discussion

**Comment by yongtang** [comment]
See discussion in https://github.com/docker/docker/pull/29226#discussion_r91424455 about having 
` --until="5s ago"` or ` --since="5m ago"`

/cc @AkihiroSuda @mlaventure @vdemeester

**Comment by thaJeztah** [comment]
Have you tried if this works? I think it does;

```
docker logs --since 10m --timestamps <container>
```

Also, there's

```
docker logs --tail 100 <container>
```

to show the last 100 entries

**Comment by tronicum** [comment]
tail works fine, but is line based vs. time based

docker logs --since 10m --timestamps <container>
"docker logs" requires exactly 1 argument(s). (at least with 1.12.1)

**Comment by tronicum** [comment]
tail works, too. docker logs --since "100m" works. Maybe just document that within the --help
