### ISSUE TITLE
Improve documentation about Swarm API "version" usage

### ISSUE THREAD

**Issue by ghostplant** [docker/docker#29448]
**Description**

There is very little information from API documentation that can explain how to use REST request to promote or demote swarm node from remote side. It seems I should post "/nodes/id/update" with parameters attached. However, some parameters like 'version' are vague. Can you provide an example to show promote/demote?

Something like:
`curl --unix-socket /var/run/docker.sock -X POST -H 'Content-Type: application/json' -d '{"version": .., ..}' http:/nodes/id/update`

Thanks

**Comment by thaJeztah** [comment]
The easiest way to learn how the API requests should be made, is to (manually) start a daemon in debug mode, then run the commands you want to do through the API.

You can do so inside a container, for example;


Start the official docker container (I picked 1.13-rc), and start the daemon in it;
```bash
docker run -it --rm --name mydocker --privileged -v /var/lib/docker --entrypoint /bin/sh docker:1.13-rc
/ # dockerd --debug --iptables=false
```

You'll see the daemon logs;

```
DEBU[0002] Registering POST, /networks/{id:.*}/disconnect
DEBU[0002] Registering POST, /networks/prune
DEBU[0002] Registering DELETE, /networks/{id:.*}
INFO[0002] API listen on /var/run/docker.sock
```

Then, in another shell, open a second session in that container;

```bash
docker exec -it mydocker sh
/# docker swarm init
Swarm initialized: current node (y7vh9fkzbsusf2euvhhm2ly36) is now a manager.

To add a worker to this swarm, run the following command:

    docker swarm join \
    --token SWMTKN-1-5nzrbr7wnblym7mvqx0mm4tlcwf3bhloufdxkavisxawtzwnwl-7e7lpol7zcw2iucla179zxvq4 \
    172.17.0.4:2377

To add a manager to this swarm, run 'docker swarm join-token manager' and follow the instructions.
```

Any command you run, will show what API calls the client makes in the daemon logs in the first shell. For example, running `docker node demote`;


```
DEBU[0233] Calling GET /v1.25/nodes/y7vh9fkzbsusf2euvhhm2ly36
DEBU[0233] Calling POST /v1.25/nodes/y7vh9fkzbsusf2euvhhm2ly36/update?version=9
DEBU[0233] form data: {"Availability":"active","Role":"worker"}
ERRO[0233] Error updating node y7vh9fkzbsusf2euvhhm2ly36: rpc error: code = 9 desc = attempting to demote the last manager of the swarm
ERRO[0233] Handler for POST /v1.25/nodes/y7vh9fkzbsusf2euvhhm2ly36/update returned error: rpc error: code = 9 desc = attempting to demote the last manager of the swarm
```

> some parameters like 'version' are vague

The "version" is used to prevent simultaneous requests from updating Swarm "objects" (services, nodes, etc) using outdated information. The version number is incremented each time the object is updated, and the Swarm API requires each request to contain the version that it is updating _from_.

For example, to get the current version of the `web` service;

```
docker service inspect --format '{{ .Version.Index }}' web
20
```

Now, update the service;

```
docker service update --label-add f00=bar web
```

which makes this API call;

```
DEBU[1172] Calling GET /v1.25/services/web
DEBU[1172] Calling POST /v1.25/services/nfjy6pd05czmnay9yvzcybeuj/update?registryAuthFrom=spec&version=20
DEBU[1172] form data: {"EndpointSpec":{"Mode":"vip"},"Labels":{"f00":"bar"},"Mode":{"Replicated":{"Replicas":1}},"Name":"web","TaskTemplate":{"ContainerSpec":{"DNSConfig":{},"Image":"nginx:alpine@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4"},"ForceUpdate":0,"Placement":{},"Resources":{"Limits":{},"Reservations":{}},"RestartPolicy":{"Condition":"any","MaxAttempts":0}},"UpdateConfig":{"FailureAction":"pause","MaxFailureRatio":0,"Parallelism":1}}
```

You can see that `version=20` is included in the request, and after updating, the version is incremented;

```
docker service inspect --format '{{ .Version.Index }}' web
21
```

Imagine another client also tried to update the same service, but using different information;

```
curl \
  --unix-socket /var/run/docker.sock \
  -X POST \
  -H 'Content-Type: application/json' -d '{"EndpointSpec":{"Mode":"vip"},"Labels":{"f00":"bar"},"Mode":{"Replicated":{"Replicas":1}},"Name":"web","TaskTemplate":{"ContainerSpec":{"DNSConfig":{},"Image":"nginx:alpine@sha256:aee97412fee873bd3d8fc2331b80862d7bd58913f7b12740cae8515edc1a66e4"},"ForceUpdate":0,"Placement":{},"Resources":{"Limits":{},"Reservations":{}},"RestartPolicy":{"Condition":"any","MaxAttempts":0}},"UpdateConfig":{"FailureAction":"pause","MaxFailureRatio":0,"Parallelism":1}}' \
  "http://localhost/v1.25/services/nfjy6pd05czmnay9yvzcybeuj/update?registryAuthFrom=spec&version=20"
```

The Swarm API returns a message that the specified version is outdated; 

```
{"message":"rpc error: code = 2 desc = update out of sequence"}
```

The client should now fetch the _current_ version of the object, re-apply the desired changes, and perform the request again (with the current version).

**Comment by ghostplant** [comment]
Thanks. Very detailed explanations!

**Comment by thaJeztah** [comment]
You're welcome! Let me rename this issue, because I think the documentation may need some information about the version number / sequence

**Comment by stevvooe** [comment]
@thaJeztah I have an explanation of this elsewhere. We should fold these into the API documentation.

**Comment by aaronlehmann** [comment]
@stevvooe: Are you thinking of https://github.com/docker/swarmkit/issues/1394#issuecomment-240850719 ?

I'm definitely in favor of improving the documentation around this parameter. Do you want to keep the issue open until the docs changes are made?

**Comment by stevvooe** [comment]
@aaronlehmann Yes, that is the one.

Yes, let's make sure this is documented so it doesn't get "de-featured".

**Comment by thaJeztah** [comment]
Documentation probably needs to go into https://github.com/docker/docker/blob/master/api/swagger.yaml, but yes, something improving the docs around this would be welcome
