### ISSUE TITLE
Proposal : Adding support for Qemu/KVM containers

### ISSUE THREAD

**Issue by harche** [docker/docker#29454]
# Adding support for Qemu/KVM containers

## What?

This proposal is about adding support  for docker container execution on Linux using KVM hypervisor.

## Why?

The conventional way of running docker containers on Linux leveraging namespaces and cgroups (runc) works great and we absolutely love it! But there are situations where we would like to have a stronger isolation between the container and the host kernel. 

## Here is how!

The basic idea here is to isolate the running container from the host kernel by running it inside a virtual machine. Traditional hypervisors are good at having a separation between the `guest` kernel and `host` kernel. So in a nutshell, we propose to use the KVM hypervisor to run docker containers! (But, what about performance??? see the section **'who is it for?**')

There are alternate approaches like those from Hyper, Clear Containers. However one of our motives was to make this happen transparently without requiring users to alter their docker 'experience'. 

Our proposal is to add a qemu option to the existing `--isolation` flag allowing the container to be run as a KVM VM rather than a default namespace based container. Further there is 1:1 mapping between a container and a VM. This is similar to Hyper-V containers approach (https://github.com/docker/docker/pull/16412). Our approach allows the user to execute containers with default as well as QEMU isolation simultaneously without changing the docker runtime.

Anyway, this is a sample invocation with the isolation=qemu option.

`docker run --isolation=qemu busybox /bin/ls`

The output of above command looks similar to the default docker container execution on Linux. i.e. without `--isolation=qemu`

`docker run busybox /bin/ls`

Which is,
```
$docker run busybox /bin/ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
$
$docker run --isolation=qemu  busybox /bin/ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
$
```

Except for the fact that with `--isolation=qemu` the container actually ran inside a virtual machine.

Also, `docker ps` shows container running while in the background the task is getting executed inside a virtual machine.

## But exactly how?

Our main objective here is to execute the container inside a virtual machine on linux. Following steps will help you understand how we go about it,

1. When the user says, `docker run busybox /bin/ls` docker essentially gets the `busybox` image and runs `/bin/ls` within the confinements of container started from that `busybox` image. When we move this logic to a virtual machine we have to do the following:
   - Boot a the virtual machine image.
   - configure the VM networking by using networking info provided by docker engine (e.g. IP, Mac address etc)
   - Mount a file system consisting of the `busybox` image.
   - chroot to that filesystem
   - execute the command `/bin/ls`
   - Redirect the stdout/stderr to docker cli so that user gets a consistent experience with or without qemu isolation driver.

2. So we need to have a virtual machine that can configure itself and execute the command intended for a container (in this case, `/bin/ls`). Here is how we went about it,
   - cloud-init (https://cloudinit.readthedocs.io/en/latest/) - VMs installed with cloud-init software mount a config-drive during their bootup and parse a `yaml` file to configure the VM(e.g. networking). One can also embed commands in cloud-init yaml file to be executed by VM after bootup. 
   - We start with creating the config-drive on the fly whenever user executes the ‘run’ command with the flag, `--isolation=qemu`. 
   - A Yaml file is injected into this ISO image with the information from docker daemon about it's networking and command that needs to be executed.
   - We also mount the docker image (e.g. busybox) into this image as a passthrough disk from the host filesystem. Once the VM completes the boot we do the chroot to this drive and execute the command (both using cloud-init)
   - VM stdout/stdin is redirected to the docker cli.
   - If user does `docker stop`, in the background this will be mapped to stopping a corresponding virtual machine, or if the user decides to do `docker rm` on that container we will map it to undefining the virtual machine apart from the standard flow. Same approach can be extended to other docker commands as well (like, `docker logs`)
 
**Here is the [sample implementation](https://github.com/harche/docker/tree/qemu-isolation) for anyone to try it out.**

## Who is it for?

Places where applications don't wish to share kernel with hosts can take advantage of such approach. This gives them the flexibility of running any docker image with the isolation of a virtual machine on linux without compromising the docker workflow they are used to and love.

The obvious drawback of this approach is the speed. We are trying to boot a VM and then execute the command. This will have overheads when compared to the default approach of using namespaces.

**Comment by cpuguy83** [comment]
Can't we already do this with `docker run --runtime`?

**Comment by justincormack** [comment]
Have you looked at the other implementations, eg the Intel Clear Containers, `runv`, the unikernels work? The general approach that people have been looking at usually involves a replacement for `runc` that launches VMs, or a container that wraps the process. The `--isolation` flag is not something that there was a plan to expand I don't think, as there are more general mechanisms since then with pluggable runtimes via OCI compliant runners.

**Comment by nathanleclaire** [comment]
Like Justin mentioned, https://github.com/hyperhq/runv is prior art here.  https://github.com/hyperhq/runv#run-it-with-docker seems to pretty much do what you're describing already, no?

**Comment by harche** [comment]
@justincormack @nathanleclaire thanks for your replies. 
 
We are aware of the OCI compliant runtime runv. But we really liked the way `hyperv` uses the `--isolation` and it would have helped a great deal to the specific use case we have if we take the similar approach for `qemu`. But before I get into details of that use case, can you/anyone confirm that `--isolation` is really not up for the expansion?

**Comment by justincormack** [comment]
All of the actual Docker runtime is going to be via the OCI compliant mechanisms, and will be managed by `containerd`. There may be some generic ways to pass parameters to those runtimes, but it is really hard to see how `--isolation` fits into this.

**Comment by resouer** [comment]
What this issue is talking about is definitely what Intel CC and runV already solved, and both of them can work well with Docker (thanks to containerd project!).  What's more, CC and runV all perform much better than full blown VM as you suggest :) 

Anyhow, `--runtime` is a much better option.

**Comment by harche** [comment]
Thanks everyone for your feedback. We will evaluate the option of having our own `runtime` for the use case we have. I will post my findings here.

**Comment by harche** [comment]
I am closing this issue because based on the feedback and our investigation we are not going to follow on `--isolation` path
