### ISSUE TITLE
docker engine 1.13.0 OSS not available in yum repo

### ISSUE THREAD

**Issue by amitsehgal** [docker/docker#29460]
**Description**

**Steps to reproduce the issue:**
1. Try installing latest ucp 2.0.1
2.
3.

**Describe the results you received:**
FATA[0000] Your engine version 1.12.3 OSS is too old.  UCP requires at least version 1.12.1 CS or 1.13.0 OSS.

**Describe the results you expected:**
Installation successful

**Additional information you deem important (e.g. issue happens only occasionally):**
packages not available in repo https://yum.dockerproject.org/repo/main/centos/7/Packages/

**Output of `docker version`:**

```
(paste your output here)
```
FATA[0000] Your engine version 1.12.3 OSS is too old.  UCP requires at least version 1.12.1 CS or 1.13.0 OSS.
**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
centos 7 rpms are not published for 1.13.0 docker engine version

**Comment by justincormack** [comment]
1.13.0 has not been released yet.

**Comment by thaJeztah** [comment]
for ucp, install the CS engine; see https://docs.docker.com/cs-engine/install/ for instructions

I'll close this issue, because 1.13 has not yet been released, and the CS engine should work to resolve this, but feel free to comment after i closed

**Comment by quitemansi** [comment]
I see that, 1.13 has been released on 01/18/2017. is there any progress on this ticket?

**Comment by thaJeztah** [comment]
@quitemansi what issue are you running into? What distro (and version) are you running?
