### ISSUE TITLE
Docker not rotate daemon log to syslog logstash

### ISSUE THREAD

**Issue by AlehFiliutsich** [docker/docker#29477]
**Description**
Docker  not rotate daemon log to logstash

**Steps to reproduce the issue:**
1. Configure run docker daemon with options 
> cat /etc/sysconfig/docker
OPTIONS='.... --log-driver=syslog  --log-opt syslog-address=tcp://logstash.com:514 --log-opt tag=docker-daemon'

2. Create some actions with containers
 docker run --name test --rm centos  bash -c ' echo zazazazazazazazazazazazazAAAAAAAAAAAAAAAAA'

**Describe the results you received:**
In logstash I saw only
zazazazazazazazazazazazazAAAAAAAAAAAAAAAAA log

**Describe the results you expected:**
In logstash I need
zazazazazazazazazazazazazAAAAAAAAAAAAAAAAA log,
and daemon log like in journald
Dec 16 12:29:15 some_host forward-journal[319]: time="...." level=info msg="{Action=wait,...}"
Dec 16 12:29:15 some_host forward-journal[319]: time="...." level=info msg="{Action=remove,...}"

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.centos.x86_64
 Go version:      go1.4.2
 Git commit:      9419b24-unsupported
 Built:           Fri Jun 24 12:09:49 2016
 OS/Arch:         linux/amd64

```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 877
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker--vg-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 10.31 GB
 Data Space Total: 21.35 GB
 Data Space Available: 11.03 GB
 Metadata Space Used: 5.394 MB
 Metadata Space Total: 25.17 MB
 Metadata Space Available: 19.77 MB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: syslog
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 3.613 GiB
Name: ECSC001048AD
ID: QGHW:ZAM4:KSVM:NDWZ:SRBR:MX3M:Y6VE:VXIW:57OH:3GKC:W32X:GWEB
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: ECSC001046A2.epam.com (secure), docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS

**Comment by cpuguy83** [comment]
I don't understand what the issue you are reporting is.

> In logstash I saw only
zazazazazazazazazazazazazAAAAAAAAAAAAAAAAA log

and 

> In logstash I need
zazazazazazazazazazazazazAAAAAAAAAAAAAAAAA log

Are the same thing.

Can you provide more details?

**Comment by AlehFiliutsich** [comment]
I try understood why docker daemon not send own log about stop/start containers events in syslog

**Comment by cpuguy83** [comment]
Ah, ok.
Docker sends its logs to stderr which is the "correct" thing to do here. These will be picked up by whatever init system you are using (e.g. journald with systemd).
Log drivers are for containers, not the docker daemon logs.

**Comment by cpuguy83** [comment]
I'm going to close this as it is working as expected.
