### ISSUE TITLE
up

### ISSUE THREAD

**Issue by szazo** [docker/docker#29481]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
guess this was opened accidentally, closing

**Comment by szazo** [comment]
yes, (facepalm), sorry

**Comment by thaJeztah** [comment]
GitHub has a shortcut `c` for create issue; it happens frequently, no worries :smile:
