### ISSUE TITLE
docker build does not clean up tmp files

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#29486]
**Description**

When interrupting a `docker build`, tmp-files stored in `/var/lib/docker/tmp` are not cleaned up. Stopping and starting the daemon also does not cleanup these files.

**Steps to reproduce the issue:**

To reproduce;

```bash
rm -rf /var/lib/docker/tmp/*
```

Create a big file for testing;

```bash
mkdir repro && cd repro
fallocate -l 300M bigfile
```

Create a dockerfile;

```Dockerfile
cat > Dockerfile <<EOF
FROM scratch
COPY ./bigfile /
EOF
```

start `docker build`, and cancel while building;

```bash
docker build -t stopme .
Sending build context to Docker daemon 69.63 MB^C
```

check content of `/var/lib/docker/tmp/`

```bash
du -h /var/lib/docker/tmp/
67M	/var/lib/docker/tmp/docker-builder436390135
67M	/var/lib/docker/tmp/
```

stop and start the daemon, to verify it's not cleaned up;

```bash
systemctl stop docker
systemctl start docker

du -h /var/lib/docker/tmp/
67M	/var/lib/docker/tmp/docker-builder436390135
67M	/var/lib/docker/tmp/
```

**Describe the results you received:**

The content is not cleaned up

**Describe the results you expected:**

- The content to be cleaned up, especially after a daemon restart
- The content to be cleaned up as part of `docker system prune` 

**Output of `docker version`:**

Tested on CentOS 7, but platform should not make a difference here;

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-253:1-132954-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 40.25 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.797 GiB
Name: centos-2gb-ams3-01
ID: NGW7:ERCJ:AQC6:YCBQ:HSZE:5WAU:5IZE:GTB5:M67E:PUCH:6L7T:AACM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
linking to https://github.com/docker/docker/issues/29284#issuecomment-267570345 as well (thanks @monikakatiyar16 )

**Comment by yongtang** [comment]
Added a PR  #29497 to clean up the tmp file left by `chrootarchive.Untar(sum, root, nil)`

**Comment by zleswomp** [comment]
Docker version 17.04.0-ce, build 4845c56 seems to still have this issue.  `/var/lib/docker/tmp` continues to grow.

**Comment by mlaventure** [comment]
@zleswomp it is only cleaned up on daemon start

**Comment by zleswomp** [comment]
@mlaventure Is the idea then that people are restarting docker periodically in production?

**Comment by mlaventure** [comment]
@zleswomp it is not :)

actually, I may have read this issue incorrectly.

What's the content of your `/var/ib/docker/tmp` ?

**Comment by zleswomp** [comment]
Loads of files like so @mlaventure :

```
/var/lib/docker/tmp/GetImageBlob465498918
/var/lib/docker/tmp/GetImageBlob146347537
/var/lib/docker/tmp/GetImageBlob086005534
/var/lib/docker/tmp/GetImageBlob474592280
/var/lib/docker/tmp/GetImageBlob018798153
/var/lib/docker/tmp/GetImageBlob903256995
/var/lib/docker/tmp/GetImageBlob864084918
/var/lib/docker/tmp/GetImageBlob732277381
/var/lib/docker/tmp/GetImageBlob994785934
/var/lib/docker/tmp/GetImageBlob674815906
```

Is it safe to remove this when docker is running?

**Comment by zleswomp** [comment]
Specifically, I want to `find /var/lib/docker/tmp/ -type f -mmin +90 -delete` the files in cron.  This is filling the root disk on one of our hosts.  We likely have an issue with an image that is getting deployed, or failing to deploy, but in the meantime, other images need to deploy without issue.

**Comment by mlaventure** [comment]
I think those are from images pull (cc @aaronlehmann)

**Comment by aaronlehmann** [comment]
These files should be automatically removed when the pull finishes, either successfully or unsuccessfully.

Could you please share the part of the Docker daemon log from when one of these pulls take place?

It also might be helpful to know the scenario that leads to excessive disk consumption; for example, whether the pull fails or succeeds, which registry is being used, etc.

**Comment by mlaventure** [comment]
@zleswomp when doing the above (as requested by Aaron), please open a new issue :)

**Comment by zleswomp** [comment]
@aaronlehmann I've just replaced our XFS devicemapper hosts with Ext4 hosts.  I was seeing an error about not enough space free in the metalvm.  I suspect this might be related.  Now that the hosts have been replaced, I'll let them run until tomorrow and see where its at.

**Comment by zleswomp** [comment]
Will do, thanks @mlaventure.
