### ISSUE TITLE
Register Swarmkit Port 2377 with IANA

### ISSUE THREAD

**Issue by programmerq** [docker/docker#29498]
**Description**

Port 2375 and 2376 have been reserved in the IANA registry. Swarmkit uses 2377, but it is currently listed as "unassigned":

    docker	2375	tcp	Docker REST API (plain text)	[DOCKER]	[Christopher_Liljenstolpe]	2014-04-17
    docker-s	2376	tcp	Docker REST API (ssl)	[DOCKER]	[Christopher_Liljenstolpe]	2014-04-17					
    2377-2378		Unassigned		

(as seen at https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?&page=43)

Port 2377 ought to be registered as well. See https://github.com/docker/docker/issues/1440 for the original discussion on getting the docker and docker-s ports registered.

**Comment by mgoelzer** [comment]
I started the port assignment process for 2377 about 6 weeks ago.  It's currently in the expert review stage.

**Comment by mgoelzer** [comment]
Port 2377/tcp is now assigned:

```
swarm              2377        tcp    RPC interface for Docker     [Docker_Inc]                                          [Mike_Goelzer]                                            2016-12-23
                                      Swarm
                   2377        udp    Reserved
```

See:  
http://www.iana.org/assignments/service-names-port-numbers

**Comment by thaJeztah** [comment]
Thanks @mgoelzer
