### ISSUE TITLE
RFE: daemon option --default-shm-size

### ISSUE THREAD

**Issue by flx42** [docker/docker#29492]
We run containerized high-performance applications in my team, some of them have a multi-process approach to parallelism, for instance the [Microsoft Cognitive Toolkit](https://github.com/Microsoft/CNTK).
The default size for `/dev/shm` is [64MB](https://github.com/docker/docker/blob/1.13.x/container/container_unix.go#L26-L27), which is often largely insufficient for our applications running on high-end machines. We need to remember to set `--shm-size` for each `docker run` we do.

Thus, it would be very helpful to have a daemon configuration option to set the default value.
@justincormack: you mentioned implementing this [here](https://github.com/docker/docker/issues/24743#issuecomment-233322278). Below, you also mentioned doing the same for [sysctl](https://github.com/docker/docker/issues/24743#issuecomment-248582403), that would also be helpful for us.

**Comment by justincormack** [comment]
Yes, I am still planning to do the `sysctl` one soon. Setting a `shm-size` default should be pretty straightforward - do you want to try to do a PR?

**Comment by flx42** [comment]
I'll see if I have time. With the holidays season coming, I'm not so sure. But don't wait for me if someone else has time to do it!

**Comment by thaJeztah** [comment]
To prevent ending up with a `default-x` flag for every option that `docker run` has; would it be better to (e.g.) have a `--container-defaults` option, or have a `defaults` section in the `daemon.json`?

**Comment by justincormack** [comment]
@thaJeztah in theory yes, in practise a defaults section in the daemon.json makes sense, but then it breaks the automatic mapping to the daemon cli options, so not quite sure how to do it best.

**Comment by yongtang** [comment]
Added a PR #29692 for that issue.
