### ISSUE TITLE
[Feature Request]: docker build should provide an option for more efficient output in batch mode

### ISSUE THREAD

**Issue by hmdhasani** [docker/docker#29507]
When Docker build is used in batch mode (like Jenkins) the output of "Sending context to docker daemon..." repeats many times, fill the console output with useless output. currently we have to use -q option but it is not the proper solutions because We want the build output.
maven has the same problem. they provide an option (-B) for this situation. I think this would be nice if we have a similar option in docker

**Comment by thaJeztah** [comment]
I think this changed at some point in https://github.com/docker/docker/pull/17428, and there was a change in https://github.com/docker/docker/pull/18210 (but according that PR, it already worked for pull)

ping @LK4D4 @ripcurld00d any idea if there's a solution currently to suppress _just_ the progress bars?

**Comment by ripcurld00d** [comment]
@thaJeztah @LK4D4 
I think it is feasible by passing to the daemon a parameter specifying whether the client is TTY or not and according to that skipping the progress-bar part (https://github.com/docker/docker/blob/master/api/server/router/build/build_routes.go#L189-L222).

**Comment by ripcurld00d** [comment]
If it's fine, I would like to call "dibs" on that.

**Comment by thaJeztah** [comment]
We may want to decide if we want it to automatically detect, or if it should be a flag; do we know if there's situations where auto-detecting may not work?

**Comment by hmdhasani** [comment]
@thaJeztah, currently the output of pull in jenkins is like this:

16.04: Pulling from ubuntu
ff1f1f1de862: Pulling fs layer
0c7b035e2a1a: Pulling fs layer
ac8ee255ff41: Pulling fs layer
bf3d47be55f8: Pulling fs layer
22a909724a97: Pulling fs layer
bf3d47be55f8: Waiting
22a909724a97: Waiting
ac8ee255ff41: Download complete
0c7b035e2a1a: Verifying Checksum
0c7b035e2a1a: Download complete
bf3d47be55f8: Verifying Checksum
bf3d47be55f8: Download complete
22a909724a97: Verifying Checksum
22a909724a97: Download complete
ff1f1f1de862: Download complete
ff1f1f1de862: Pull complete
0c7b035e2a1a: Pull complete
ac8ee255ff41: Pull complete
bf3d47be55f8: Pull complete
22a909724a97: Pull complete
Digest: sha256:35dca5fc91c4890f787a266a057ad76b98ff3af43c75aa7e10962d06f06fd6e5

that seems efficient.
I think the output of build could be something like this:

Sending build context to Docker daemon: sending 601.6 MB...
Sending build context to Docker daemon: send complete

Step 1/9 : FROM microsoft/windowsservercore
 ---> f49a4ea104f1

**Comment by yongtang** [comment]
@hmdhasani  PR #25690 will reduce the output of `Sending build context to Docker daemon` in non tty environment. Wondering if that helps?

**Comment by thaJeztah** [comment]
@yongtang oh! perhaps that's already it. Forgot all about that one :smile:

**Comment by thaJeztah** [comment]
@hmdhasani do you have a test setup where you can install the 1.13 release candidates? Keep in mind, it's a release candidate, so bugs can still be present

**Comment by hmdhasani** [comment]
I will check that

**Comment by hmdhasani** [comment]
This is the result of docker build in Jenkins:

Sending build context to Docker daemon 1.829 GB

Step 1/1 : FROM hub.docker.iais.co:5000/ubuntu:16.04
 ---> 45bc58500fa3

So the issue is resolved in 1.13

**Comment by thaJeztah** [comment]
Thanks for testing @hmdhasani! I'll close this issue, as it's resolved
