### ISSUE TITLE
[1.13-rc3]constraints willn't work in compose

### ISSUE THREAD

**Issue by lenshion** [docker/docker#29530]
I have a 5 EC2 swarm cluster running in AWS. I wanna schedule a redis server to bigger memory instance. But won't work.

**Here is my doker info:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.13.0-rc3
Storage Driver: devicemapper
 Pool Name: docker-202:2-33554688-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 922 MB
 Data Space Total: 107.4 GB
 Data Space Available: 106.5 GB
 Metadata Space Used: 1.421 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: jjw8b54znxdhzctfbo5g1rjzy
 Is Manager: false
 Node Address: 192.168.1.120
 Manager Addresses:
  192.168.1.110:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.26 GiB
Name: ip-192-168-1-120.us-west-2.compute.internal
ID: WZDW:6PAI:FU7R:BBMO:LVNI:LLAX:ZLWK:VHXK:22QA:654I:TPV6:VMK6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
  **stats.role=redis**
Experimental: false
Insecure Registries:
 192.168.1.250:5000
 127.0.0.0/8
Live Restore Enabled: false

**Here is my compose file:**

redis:
    image: 192.168.1.250:5000/redis
    hostname: redis
    environment:
      - "constraint:engine.labels.stats.role==redis"
    ports:
      - "6379:6379"

Whe I use "docker stack deploy --compose-file xxx redis", it will randomly place container in different VM.

**Comment by vdemeester** [comment]
hi @lenshion,

Passing constraint via `environment` key only works with v1 swarm. There is a new *object* for deployment configuration on the v3 compose-file (the one you can use with `docker stack deploy`, see https://github.com/docker/docker.github.io/pull/716/files#diff-7f92e63d2e7e84a65a6497458b96739cR189

**Comment by lenshion** [comment]
Thanks, eager to use compose for full stack deployment. Will try

**Comment by cpuguy83** [comment]
Closing since this isn't really an issue.
