### ISSUE TITLE
docker ps throws error message.

### ISSUE THREAD

**Issue by RupenAnjaria** [docker/docker#29553]
I was unable to pull image due to the issue mentioned here: http://stackoverflow.com/questions/37527888/docker-commands-fails-in-windows

After trying the solution (setting environment variables) I am getting below error message:
An error occurred trying to connect: Post https://xxx.xx.xx:2376/v1.24/imag
es/create?fromImage=hello-world&tag=latest: dial tcp xxx.xxx.xx.xxx:2376: connec
tex: A connection attempt failed because the connected party did not properly re
spond after a period of time, or established connection failed because connected
 host has failed to respond.

Any idea?

**Comment by thaJeztah** [comment]
The solution of setting environment variables works if you are running docker toolbox, but is not the right solution if you are running Docker for Windows; or when running native windows containers. however, you did not provide any information about your setup; please provide the information that was requested in the bug report template when you opened the issue https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

**Comment by RupenAnjaria** [comment]
Docker commands fails (in Windows)

If we run "docker ps" then getting this error message:

C:\windows\system32>docker ps
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/containers/json: open //./pipe/docker_engine: The system cannot find the fi
le specified.


**Steps to reproduce the issue:**
1. Install docker toolbox v 1.12.3 on Windows 7
2. Execute "docker ps" in command tool running as an administrator

**Describe the results you received:**
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/containers/json: open //./pipe/docker_engine: The system cannot find the fi
le specified.

**Describe the results you expected:**
Should list all the running containters

**Additional information you deem important (e.g. issue happens only occasionally):**
--none

**Output of `docker version`:**

```
Docker version 1.12.3, build 6b644ec
```

**Output of `docker info`:**

```
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/info: open //./pipe/docker_engine: The system cannot find the file specifie
d.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Using Oracle Virtual box V 4.3.16 r95972

**Comment by friism** [comment]
The Toolbox setup guide has troubleshooting suggestions: 

 * https://docs.docker.com/toolbox/toolbox_install_windows/#/step-3-verify-your-installation
 * https://docs.docker.com/toolbox/faqs/troubleshoot/

If you get stuck, please start a thread in the Docker Toolbox forums: https://forums.docker.com/c/open-source-projects/docker-toolbox

This repo is primarily for tracking bugs and issues with the Docker Engine and it looks like you're encountering problems getting Toolbox and Docker Machine working.

**Comment by thaJeztah** [comment]
Agreed, this looks to be an issue with Docker Toolbox, or configuration. I'm closing the issue because of the above, but feel free to comment after
