### ISSUE TITLE
docker exec with "/bin/bash -ic" raise bash warning

### ISSUE THREAD

**Issue by roroco** [docker/docker#29562]
here is my code
```
docker exec ro-crm-2 /bin/bash -ic ls
```
here is output:
```
roroco@roroco ~/Dropbox/rbs/ro_cmds_global $ docker exec ro-crm-2 /bin/bash -ic ls
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
bin
boot
dev
```

I use bash -i for auto `source ~/.bashrc`

**Comment by roroco** [comment]
My tmp solution is using ruby capture docker exec output and remove first 2 lines

**Comment by gianarb** [comment]
Hello @roroco ! Thanks for your message. Are you using Docker 1.13 rc4 or another version? Can you paste the out of your `docker version` command? Thanks

**Comment by cpuguy83** [comment]
Sounds like you need `-t`... `docker exec -t ro-crm2 /bin/bash -ic ls`

Closing as this is not really an issue.

**Comment by roroco** [comment]
@cpuguy83 it work
