### ISSUE TITLE
error

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker/docker#29560]
Linux node1 3.10.0-327.36.1.el7.x86_64 
time="2016-12-20T09:04:25.635589836+08:00" level=warning msg="mountpoint for pids not found"
Dec 20 09:04:32 localhost dockerd: time="2016-12-20T09:04:32.854802791+08:00" level=error msg="containerd: deleting container" error="exit status 1: \"container 7fdb7e014dbad54a5240bb4ece7190165a034ce60072b371829b6082b7cc873f does not exist\\none or more of the container deletions failed\\n\""

**Comment by thaJeztah** [comment]
please provide the information that was requested in the bug report template when you opened the issue https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

**Comment by timchenxiaoyu** [comment]
1.I compile docker 1.13.0 rc3 and cover my host(centos7 Linux node1 3.10.0-327.36.1.el7.x86_64 )
2.in /var/log/message ,I see this error:
time="2016-12-20T09:04:25.635589836+08:00" level=warning msg="mountpoint for pids not found"
Dec 20 09:04:32 localhost dockerd: time="2016-12-20T09:04:32.854802791+08:00" level=error msg="containerd: deleting container" error="exit status 1: "container 7fdb7e014dbad54a5240bb4ece7190165a034ce60072b371829b6082b7cc873f does not exist\none or more of the container deletions failed\n"

**Comment by thaJeztah** [comment]
Actually, looking at your other issue, I think this is related; if you don't have uDev sync support, things like this happen (https://github.com/docker/docker/issues/29531). I'll close this issue
