### ISSUE TITLE
How to provide cpu-quota and cpu-period values while creating a service in swarm mode?

### ISSUE THREAD

**Issue by adityacs** [docker/docker#29579]
We can assign cpu-quota and cpu-period using docker run command. How to achieve the same using docker service create command?.

In docker 1.12, swarm mode, there is only "--limit-cpus" option.

**Comment by allencloud** [comment]
Maybe we can find more details in issue: https://github.com/docker/docker/issues/25303

**Comment by adityacs** [comment]
Thanks

**Comment by thaJeztah** [comment]
@adityacs `--limit-cpus` / `--cpus` actually sets these values under the hood; see https://github.com/docker/docker/issues/27921, https://github.com/docker/docker/pull/27958

**Comment by adityacs** [comment]
@thaJeztah Thanks. Didn't know this. Good to see this feature. 
Working for me :)

**Comment by cpuguy83** [comment]
Closing as this is resolved.
