### ISSUE TITLE
[Feature request] Import a filesystem image

### ISSUE THREAD

**Issue by Rudloff** [docker/docker#29587]
I need to import the content of ext4 filesystem image into my Docker image.
Currently, I need to mount the image somewhere then use COPY in order to import the content.

I would be easier if I could extract the image directly from the Dockerfile.

**Comment by justincormack** [comment]
Mounting a filesystem is a high security risk, as it is untrusted input and the kernel has fairly unsafe paths. You can use eg `libguestfs` to read a filesystem image in userspace, that should just work in a `docker build`.

**Comment by Rudloff** [comment]
I tried using libguestfs during build but it seems it requires a privileged container:
```
libguestfs: trace: mount_local "/data/local/tmp/system-readonly/"
libguestfs: guestfs_impl_mount_local: fuse_mount /data/local/tmp/system-readonly/
fuse: failed to open /dev/fuse: Operation not permitted
libguestfs: error: fuse_mount: /data/local/tmp/system-readonly/: Operation not permitted
```

**Comment by thaJeztah** [comment]
I'm going to close this issue, because this is not something we'll implement, but feel free to continue the discussion here
