### ISSUE TITLE
dockerd exits when init swarm fails: network is unreachable 

### ISSUE THREAD

**Issue by allencloud** [docker/docker#29580]
Hi, All, 

I ran into an issue, and here is the case:

I have a laptop with 3 VMs created by virtualbox.
1. when I was in my work office, my VMs are in the network of 10.1.4.0/24,ip is  10.1.4.103, 10.1.4.104, 10.1.4.105. I make them be a swarm cluster via command.
2. When I moved to my house, three VMs will change their IPs, this time IPs are 192.168.59.103, 192.168.59.104, 192.168.59.105.

But I found that when I start docker daemon, it fails with the dockerd log 
```
time="2016-12-20T02:05:50.419437798+08:00" level=fatal msg="Error creating cluster component: could not find local IP address: dial udp 10.1.4.105:2377: connect: network is unreachable"
```
We can find that this a fatal log here https://github.com/docker/docker/blob/master/cmd/dockerd/daemon.go#L289,
it makes dockerd exit immediately.

**Actually I only change the work place and IP changes, then I have no ability to use docker daemon. I think this is UNACCEPTABLE for users.**

I suggest that when swarm cluster init fails, it only affects the swarm part, not related to original API parts. 

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Dockerd fails to start with log 
```
time="2016-12-20T02:05:50.419437798+08:00" level=fatal msg="Error creating cluster component: could not find local IP address: dial udp 10.1.4.105:2377: connect: network is unreachable"
```

**Describe the results you expected:**
Dockerd can start with an error log without fatal log.

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:30:42 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 37
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 194
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: Q2ZC:GWDN:27OH:GRMH:G6QU:W7QP:4TIX:Q5F6:YEVK:45XP:EXHC:HOB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 23
 System Time: 2016-12-20T02:31:47.207169643+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by aaronlehmann** [comment]
ping @tonistiigi

https://github.com/docker/swarmkit/pull/1826 will avoid this problem since the swarm manager will no longer need to connect back to itself over TCP, but this is still a work in progress and won't be part of 1.13.

It might be worth considering a short-term fix for this problem.

**Comment by aaronlehmann** [comment]
I think having some kind of `--swarm-join` style option is a good idea. This will probably be easier with the changes in docker/swarmkit#1826. Let's target 1.14.

**Comment by CrimsonGlory** [comment]
For those googling and arriving here, looking for a hot-fix-right-now: not that easy.

A big ```grep -r <ip>``` shows that the IP that needs to be changed is in the following files in ```/var/lib/docker/swarm/``` folder:
- ```state.json```
- ```docker-state.json```
- ```.wall``` files in ```raft/wall```

The problem with modifying the [.wall](https://github.com/coreos/etcd/blob/master/wal/doc.go) file is that:
- its content is distributed across nodes
- it is a binary file
- has CRC throughout its contents.

Although a hot-fix is possible, I think it is not as easy as ```vim file.wall``` + ```:wq```
=/

**Comment by Fuffi** [comment]
Coming from this #31237 is there a workaround?
