### ISSUE TITLE
[feature request] make dockerd support reloading config registry mirror

### ISSUE THREAD

**Issue by allencloud** [docker/docker#29594]
Hi, All, 

I found that currently dockerd does not support reload config registry mirror, while today I ran into a case that we have chance to add this, but there are already some workload on the docker daemon.

If we hope to add registry mirror, we have to edit the config file and restart dockerd which is not OK for the workload. 

So, I hope to have registry mirror config reload support in docker daemon.

P.S.
Here are the reload options support in docker daemon: https://github.com/docker/docker/blob/master/daemon/daemon.go#L1009-L1019
```
// Reload reads configuration changes and modifies the
// daemon according to those changes.
// These are the settings that Reload changes:
// - Daemon labels.
// - Daemon debug log level.
// - Daemon insecure registries.
// - Daemon max concurrent downloads
// - Daemon max concurrent uploads
// - Cluster discovery (reconfigure and restart).
// - Daemon live restore
// - Daemon shutdown timeout (in seconds).
```

**Comment by allencloud** [comment]
#dibs

**Comment by cpuguy83** [comment]
I swear there is a PR to do this already.

**Comment by allencloud** [comment]
Oh, Actually the PR search failed me with keyword `mirror` and `reload`. Really sorry. really appreciate it if we can have the PR's link. 😄

**Comment by cpuguy83** [comment]
You know what, I'm probably thinking of insecure registry, not mirror.

**Comment by allencloud** [comment]
Oh, yeah. I submitted a PR before and merged a few days ago. And it is about insecure registry. 😃
