### ISSUE TITLE
dockerd crash with nil pointer error

### ISSUE THREAD

**Issue by piontec** [docker/docker#29598]
**Description**
Docker daemon 1.12.4 crashed with nil pointer error

**Steps to reproduce the issue:**
Running on ubuntu 16.04 on AWS on x1.32xlarge

**Describe the results you received:**
```
Dec 20 14:33:47 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:33:47.456073207Z" level=info msg="Container 1e494db42a1cf22d4ba72f73201bc8791192166eb73d6c536e92fa37c9b1ac05 failed to exit within 10 seconds of signal 15 - using the force"
Dec 20 14:33:47 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:33:47.767456469Z" level=warning msg="libcontainerd: container 1e494db42a1cf22d4ba72f73201bc8791192166eb73d6c536e92fa37c9b1ac05 restart canceled"
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:34:04.776606196Z" level=error msg="failed to close stdin: rpc error: code = 2 desc = containerd: container not found"
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: time="2016-12-20T14:34:04.880619893Z" level=error msg="Handler for GET /v1.24/exec/7456091f2e588e028b90c4dc16b32b72f6141b206845733e99dad543b348520b/json returned error: Container 529b294762d5692a7419166ddfe9433321d793d72d3a2d441f0125057064f048 is restarting, wait until the container is running"
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: [signal 0xb code=0x1 addr=0x0 pc=0x601668]
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: goroutine 35252 [running]:
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: panic(0x1aa2760, 0xc82000c090)
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/local/go/src/runtime/panic.go:481 +0x3e6
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: github.com/docker/docker/libcontainerd.(*container).start(0xc821093140, 0x0, 0x0, 0x0)
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:143 +0x708
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: github.com/docker/docker/libcontainerd.(*container).handleEvent.func1.1(0xc8260d2900, 0xc821093140, 0xc828b20ff0, 0xc8281d29c0)
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:227 +0x11a
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: created by github.com/docker/docker/libcontainerd.(*container).handleEvent.func1
Dec 20 14:34:04 ip-10-69-11-89 dockerd[123488]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:243 +0x226
```

**Additional information you deem important (e.g. issue happens only occasionally):**
Never happened with 1.12.3

**Output of `docker version`:**

```
Client:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.4
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   1564f02
 Built:        Tue Dec 13 00:08:34 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 430
 Running: 358
 Paused: 0
 Stopped: 72
Images: 1328
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /opt/io1/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3794
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-53-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 128
Total Memory: 1.876 TiB
Name: ip-10-69-11-89
ID: UGZS:UFD3:GB4C:W5MX:JU2L:K7PH:6ZWS:4GPM:27Q5:UNNN:X3DC:YDT7
Docker Root Dir: /opt/io1/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

```

**Comment by thaJeztah** [comment]
ping @mlaventure ptal

**Comment by mlaventure** [comment]
@piontec could you confirm if you have `--live-restore` enabled?

**Comment by piontec** [comment]
Yes, this is with live-restore enabled.

**Comment by casevilus** [comment]
Hi, Is there any update on this?

Same error happens first day of year :)

Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]: panic(0x1ab9ba0, 0xc82000e090)
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]:         /usr/local/go/src/runtime/panic.go:481 +0x3e6
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]: github.com/docker/docker/libcontainerd.(*container).start(0xc82011a3c0, 0x0, 0x0, 0x0)
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]:         /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:147 +0x708
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]: github.com/docker/docker/libcontainerd.(*container).handleEvent.func1.1(0xc822f9bf20, 0xc82011a3c0, 0xc8222afe00, 0xc821d2f400
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]:         /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:231 +0x11a
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]: created by github.com/docker/docker/libcontainerd.(*container).handleEvent.func1
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com dockerd[13598]:         /usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/container_linux.go:247 +0x226
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com systemd[1]: docker.service: Unit entered failed state.
Jan 01 03:19:08 docker-linux-eu-1.lonems.aws.messageone.com systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 02 07:17:24 docker-linux-eu-1.lonems.aws.messageone.com systemd[1]: Stopped Docker Application Container Engine.

**Output of docker info**
Containers: 50
 Running: 50
 Paused: 0
 Stopped: 0
Images: 20
Server Version: 1.12.5-cs5
Storage Driver: btrfs
 Build Version: Btrfs v4.4
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 64
Total Memory: 480.3 GiB
Name: docker-linux-eu-1.lonems.aws.messageone.com
ID: PGFD:OXCG:TDWZ:DKVN:KOIR:TZH2:RXAT:MNUH:KKTC:NWP7:QGBS:Y5QA
Docker Root Dir: /mnt/docker_main
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Output of docker version**
Client:
 Version:      1.12.5-cs5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   f7aca07
 Built:        Wed Dec 21 20:48:29 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5-cs5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   f7aca07
 Built:        Wed Dec 21 20:48:29 2016
 OS/Arch:      linux/amd64

**Comment by mlaventure** [comment]
@casevilus #29643 will fix it.

**Comment by thaJeztah** [comment]
https://github.com/docker/docker/pull/29643 was included in the 1.12.6 release, so this should be fixed, but please comment if this is still an issue

**Comment by mangelov95** [comment]
Hello, I seem to have this issue with the new Docker 17.03.0-ce when trying to use the swarm image to initialise a swarm. After this error it shows me a list of different goroutines.

**Comment by thaJeztah** [comment]
@mangelov95 it's probably a different issue, can you open a new bugreport with details and the output of that error?
