### ISSUE TITLE
Services do not run on dedicated nodes according to predefined constraints

### ISSUE THREAD

**Issue by liyaka** [docker/docker#29607]
I'm running swarm cluster with docker 1.13.0 rc4 on RHEL 7.
I have several services that suppose to run on nodes according to predefined engine.label.role constraints.
Some of the services start running on the wrong nodes.

The same configuration runs successfully on Ubuntu 14.04

**Comment by thaJeztah** [comment]
can you provide more info and steps to reproduce? Also, `docker info`, and `docker version` output would be useful here; Are all nodes RHEL 7.2 or 7.3? There are incompatible changes in SELinux between those versions that may result in containers failing to start; finally, logs could be useful if anything stands out

**Comment by shibli786** [comment]
try using node.hostname constraint **--constraint node.hostname=="node-1"**  
**example**
sudo docker service create --name mysql_container \
--mount type=bind,source=/root/data_src/database,destination=/var/lib/mysql \
--constraint node.hostname=="node-1" \
-e=MYSQL_ROOT_PASSWORD=abcd \
-e=MYSQL_DATABASE=test2 mysql

**Comment by liyaka** [comment]
All nodes are RedHat 7.2 and have docker 1.13.0 rc 4 installed.
There is no logs! This is one of the problems.. I couldn't find anything relevant in /var/log/messages
I had the same issue on several installations, so I downgraded docker to 1.13.0 rc 3 and now it works properly.

**Comment by thaJeztah** [comment]
@liyaka could you provide the exact steps to reproduce, and what you were seeing?

- How did you specify the constraint?
- If you `docker node inspect` the nodes, are you seeing the "Engine" labels in the output?

**Comment by liyaka** [comment]
Each node has `--label=role=<node_role>` for example `--label=role=app `or `--label=role=db`
and each service create command has:
--constraint 'engine.labels.role==<node role>' 
like 
--constraint 'engine.labels.role==app' 

Since I downgraded to 1.13.0 rc3, everything works as expected, and I don't have an environment with rc4 at the moment to check `docker node inspect` output.
I will create one and update

**Comment by liyaka** [comment]
@shibli786 using node hostnames is not an option in my case

**Comment by thaJeztah** [comment]
be aware that `engine` labels are set on the daemon (either through the `daemon.json` configuration file, or by setting `--label` flags on `dockerd`. "node" labels are set from a swarm manager (`docker node update --label-add foo=bar`)

**Comment by liyaka** [comment]
I use engine labels defined in docker service because I didn't find an option to set node label while joining the swarm.

**Comment by liyaka** [comment]
Tried again with 1.13.0 rc4 and everything worked. Closing the issue
