### ISSUE TITLE
Docker failing to try `localhost:5000` before returning "getsockopt: connection refused"

### ISSUE THREAD

**Issue by etotheipi** [docker/docker#29608]
Docker version 1.12.5
Registry version 2.5.1
OS:  OSX

**Description**
NOTE:  This looks like a kubernetes question, but I'm fairly certain it's not.  The kubernetes description is for context.

I have setup a registry:2.5.1 in an AWS kubernetes cluster.  I have proxied the registry so that all cluster nodes see it as `localhost:5000`.  I can successfully push and pull images this way when SSH'd into the hosts. 

When attempting to access from outside, I use `kubectl port-forward` to forward my local OSX host port 5000 to port 5000 on the registry pod/container.   I **can** successfully curl the list of images through the port-forward, but cannot use any docker commands.  In fact, it looks like `docker pull` doesn't even attempt to use the port-forward.

```
$ # port-forward localhost:5000 directly to the pod/container port 5000
$ kubectl port-forward kube-registry-v2-if515 5000:5000
Forwarding from 127.0.0.1:5000 -> 5000
Forwarding from [::1]:5000 -> 5000
```

The in another terminal:

```
$ curl -X GET http://localhost:5000/v2/_catalog
{"repositories":["centos7","registry","testimg"]}
# port-forward terminal pops up "Handling connection for 5000"
$ curl http://localhost:5000
# port-forward terminal pops up "Handling connection for 5000"
```

Most importantly, I see `Handling connection for 5000` pop up in the kubectl-port-forward terminal, indicating that curl commands are successfully traversing the port-forward.  Unfortunately: 

```
$ docker push localhost:5000/centos7
The push refers to a repository [localhost:5000/centos7]
Put http://localhost:5000/v1/repositories/centos7/: dial tcp [::1]:5000: getsockopt: connection refused
# port-forward terminal shows nothing
```

There is no `Handling connection for 5000` pop up, indicating that `docker push` is **not even attempting** to traverse the `localhost:5000` port-forward.  Because of this, I'm fairly certain the issue is something to do with Docker not respecting `localhost` registries on my system for some reason.  I have no problem pushing to other, non-localhost registries.  

I've also tried replacing the `kubectl port-forward` with an `ssh -L 5000:localhost:5000 ...` port forward command to one of the nodes that can access via `localhost:5000`.  Exact same issue.

**Output of `docker version`:**

```
Docker version 1.12.5, build 7392c3b
```

**Output of `docker info`:**

```
Containers: 163
 Running: 0
 Paused: 0
 Stopped: 163
Images: 1214
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1034
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: ...
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2016-12-20T22:06:33.753680609Z
 EventsListeners: 1
Username: etotheipi
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 localhost:5000
 127.0.0.1:5000
 127.0.0.0/8
```

**Comment by svetlyak40wt** [comment]
I have the same issue with docker on OSX:
```
Docker version 1.12.0-rc2, build 906eacd, experimental
```

**Comment by svetlyak40wt** [comment]
Upgraded docker for OSX, same issue with
```
Docker version 1.12.5, build 7392c3b
```

**Comment by tappleby** [comment]
Running into this as well, testing out a local registry on minikube kubernetes cluster.

Pushing with kubectl port-forward + localhost:5000 failed but when I exposed the port on the cluster and pushed to the IP directly it worked fine.

**Comment by etotheipi** [comment]
So of course there is a straightforward explanation.  On Mac, docker runs
in a VM, so using `localhost` in a docker command is specifying the VM's
localhost, not the host system with the port forwarded.  Need to add a port
forwarding rule in Virtualbox to map guest port to host port.

**Comment by svetlyak40wt** [comment]
Interesting, @etotheipi, but before some day, localhost:5000 worked for me. I'm using Native Docker for OSX, not running in VirtualBox. Native.

**Comment by etotheipi** [comment]
So I just learned that the latest incarnation of Docker doesn't use
virtualbox, but it still uses a VM (Moby?). It has to, since you need an
underlying Linux kernel to run your Linux containers.  I have not figured
out how to (if possible) setup forwarding from that VM to the host.

**Comment by xuwang** [comment]
You'll need to set ssh tunnel with local ip:
* local_ip=$(ipconfig getifaddr en0)
* ssh -N -L *:5000:localhost:5000 \<username\>@\<remote-registry-server\>
* Add ${local_ip}:5000 to docker daemon config insecure registries; save and restart docker daemon
* docker pull  ${local_ip}:5000/<user>/<image>

**Comment by builtinnya** [comment]
@xuwang solution worked for me. Thank you!

**NOTE: Be sure to add prefix `*:` (bind_address) explicitly for `-L`.** 

**DOESN'T WORK**
```
$ ssh -N -L '5000:localhost:5000' <username>@<remote-registry-server>
```

**WORK**
```
$ ssh -N -L '*:5000:localhost:5000' <username>@<remote-registry-server>
```

**Comment by cpuguy83** [comment]
`docker push` happens on the daemon, not on the client.
So the address needs to be relevant to the docker daemon. Unless there is a port forward for localhost port 5000 on the docker host to the container port this will not work.

In addition, `localhost` appears to be resolving to the ipv6 address, is this really what you want?

Closing because this looks more like a config issue/bad assumption.
But feel free to discuss, especially if you think I'm mistaken.

Thanks! 👼

**Comment by artronics** [comment]
kubernetes port-forwarding didn't work until instead of pod I expose the service:
`kubectl port-forward svc/docker-registry 5000:80`
