### ISSUE TITLE
BTRFS, Disk Full but not?, Unresponsive Sometimes

### ISSUE THREAD

**Issue by charlescva** [docker/docker#29601]
**Description**

Running any docker commands, such as docker ps -a, is just hanging and completely unresponsive.
Operating system reports "No space left on device" when i try to 'touch test'

df -h reports:

> Filesystem      Size  Used Avail Use% Mounted on
> /dev/sdd2       839G  152G  686G  19% /

/var/lib/docker/btrfs is part of /

df -i reports:
Filesystem Inodes IUsed IFree IUse% Mounted on
/dev/sdd2 0 0 0 - /
devtmpfs 5125529 519 5125010 1% /dev
tmpfs 5128157 1 5128156 1% /dev/shm
tmpfs 5128157 660 5127497 1% /run
tmpfs 5128157 16 5128141 1% /sys/fs/cgroup
/dev/sdd1 97317888 358 97317530 1% /boot
/dev/sda 0 0 0 - /mnt/bigdata
tmpfs 5128157 1 5128156 1% /run/user/0

btrfs fi show
> Label: 'centos'  uuid: ca43b802-5cd4-458c-9fd1-00c5f71268b6
> 	Total devices 1 FS bytes used 149.72GiB
> 	devid    1 size 838.19GiB used 838.19GiB path /dev/sdd2

There seem to be a lot of btrfs subvolumes, which I understand make up the underlying structure of Images and Containers.  However I would like to remove anything and everything, except the current containers that are running and their required images/snapshots.

Basically, I want to clean-up and blow away everything except the current containers that are running, and the latest snapshot/version of their underlying image.

**Steps to reproduce the issue:**
1. install docker on btrfs on centos 7
2. use it for about a year doing yum updates periodically.
3. wait for the day everything just stops working.

**Describe the results you received:**

Docker daemon requests via docker cli just hang.  Disk is reported to be full.

**Describe the results you expected:**

Docker daemon requests respond, disk doesnt needlessly fill up.  Or Docker explains in 'layman's terms' that my btrfs filesystem is at capacity, even though the OS volume looks fine.  And that i need to either add disk to the btrfs subsystem, or I need to clean up old snapshots.  With a specific list of commands that explain how, or even a link to a website.

**Additional information you deem important (e.g. issue happens only occasionally):**

I deleted some yum packages and stuff on the root that wasnt needed.  although it seemed to help, i'm now back to where i was yesterday.

**Output of `docker version`:**
I can't get that because the daemon is froze.... wait, there it goes:

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: 
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: 
 Go version:      go1.6.3
 Git commit:      3999ccb-unsupported
 Built:           Thu Dec 15 17:24:43 2016
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 65
Server Version: 1.10.3
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 24
Total Memory: 39.12 GiB
Name: host-192-168-1-39
ID: QK5Q:JCMA:ATGR:ND6W:YOT4:PZ7G:DBV5:PR26:YZQL:INRU:HAUC:CQ6B
Registries: docker.io (secure)

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical Dell T710
Linux host-192-168-1-39 3.10.0-514.2.2.el7.x86_64 #1 SMP Tue Dec 6 23:06:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
What about `df -i`?

**Comment by charlescva** [comment]
df -i
Filesystem       Inodes IUsed    IFree IUse% Mounted on
/dev/sdd2             0     0        0     - /
devtmpfs        5125529   519  5125010    1% /dev
tmpfs           5128157     1  5128156    1% /dev/shm
tmpfs           5128157   660  5127497    1% /run
tmpfs           5128157    16  5128141    1% /sys/fs/cgroup
/dev/sdd1      97317888   358 97317530    1% /boot
/dev/sda              0     0        0     - /mnt/bigdata
tmpfs           5128157     1  5128156    1% /run/user/0

**Comment by charlescva** [comment]
is there something i can or should do to update/remove the status/more-info-needed label?

**Comment by cpuguy83** [comment]
@charlescva Hmm, it's not clear where `/var/lib/docker/btrfs` is, or inode usage on `/`, etc...

**Comment by charlescva** [comment]
/var/lib/docker/btrfs is part of the root (/) volume

**Comment by charlescva** [comment]
Okay, I was able to resolve this issue.  Here is my layman's breakdown.


The BTRFS uses and underlying block device in an 'allocation' manner for subvolumes/snapshots, which are the underpinning of your containers and images.  Even though docker deletes subvolumes and snapshots when you delete containers/images, btrfs still needs to 'rebalance' or "reclaim' unused storage blocks at some time.  By default this doesnt happen automatically, so over time your "disk block usage" fills up.  Consider this weird graph thing below:

--------container------------image----------------container-----------------------------------docker
--------subvolume---------subvolume-----------subvolume---------------------------------btrfs
--------blocks---------------blocks----------------blocks-------------blocks--------blocks--device/disk

you'll notice i left some 'blocks' allocated on the far right, even though there are no btrfs subvolumes or containers there.  This is because BTRFS needs to rebalance the data allocation across 'all' disks in your BTRFS raid configuration.  After re-balancing you'd get something like this:

--------container------------image----------------container-----------------------------------docker
--------subvolume---------subvolume-----------subvolume---------------------------------btrfs
--------blocks---------------blocks----------------blocks--------------------------------------device/disk

The problem for me, is that when your disk is 100% full, there is not enough space to perform the rebalance. so it looks like this:

--------container------------image----------------container-----------------------------------docker
--------subvolume---------subvolume-----------subvolume---------------------------------btrfs
blocksblocksblocksblocksblocksblocksblocksblocksblocksblocksblocksblocksblocdevice/disk

You can always tell if you are in this situation by typing the following:

btrfs filesystem show /
Label: 'centos'  uuid: ca43b802-5cd4-458c-9fd1-00c5f71268b6
	Total devices 1 FS bytes used 149.72GiB
	devid    1 size **838.19GiB used 838.19GiB** path /dev/sdd2

So, basically you need to add a little extra space to the btrfs filesystem, and run a re-balance.  You can use a USB stick, RAMDISK, or really any 'device' that you can find.  In my case I have another mount point that had plenty of free space. /mnt/bigdata -> /dev/sdd2 (6TB)

So here is how I fixed this issue:


`
[root@host ~]# dd if=/dev/zero of=/mnt/bigdata/btrfs bs=1G count=5
5+0 records in
5+0 records out
5368709120 bytes (5.4 GB) copied, 2.99536 s, 1.8 GB/s

[root@hostname ~]# losetup -v -f /mnt/bigdata/btrfs

[root@hostname ~]# btrfs device add /dev/loop
loop0         loop-control  
[root@hostname ~]# btrfs device add /dev/loop0 /
Performing full device TRIM (5.00GiB) ...

[root@hostname ~]# btrfs balance start -v -dusage=1 /
Dumping filters: flags 0x1, state 0x0, force is off
  DATA (flags 0x2): balancing, usage=1
Done, had to relocate 673 out of 842 chunks

[root@hostname ~]# btrfs filesystem show /
Label: 'centos'  uuid: ca43b802-5cd4-458c-9fd1-00c5f71268b6
	Total devices 2 FS bytes used 149.56GiB
	devid    1 size 838.19GiB used 165.04GiB path /dev/sdd2
	devid    2 size 5.00GiB used 2.00GiB path /dev/loop0

[root@hostname ~]# btrfs device delete /dev/loop0 /

[root@hostname ~]# btrfs balance start -v -dusage=1 /
Dumping filters: flags 0x1, state 0x0, force is off
  DATA (flags 0x2): balancing, usage=1
Done, had to relocate 0 out of 169 chunks


`

At this point you can start the docker service and should be good to go.  (I actually had to restart it a second time after I started it, because it was giving me an odd error:

docker start db
Error response from daemon: service endpoint with name db already exists
Error: failed to start containers: db

After restarting the service I ran docker start db again, and it started fine.

**Comment by cpuguy83** [comment]
Ah yes, rebalancing. One of the "fun" things about btrfs.
Thanks for reporting back!

**Comment by thaJeztah** [comment]
Is this something we should mention in the storage driver user guide? https://docs.docker.com/engine/userguide/storagedriver/btrfs-driver/

**Comment by cpuguy83** [comment]
Yes, rebalancing is required periodically, like an oil change.

**Comment by charlescva** [comment]
Yea, I ran in to a similar issue with ZFS a few years ago.  apparently 80% full is kind of like 100% full on some of these fancy software raid solutions.

While I understand that the onus should be on me as the user to understand what file system I'm using, and how it works.  I see no harm in docker attempting a re-balance after "N" number of subvolumes are created/destroyed.   the reality of the situation is that most development shops have someone like me integrating and working with 10 - 20 different pieces of software, file-systems, security protocols, etc.  It 'feels' like the goal of the docker community is to make the complexities of LXC and Storage, well... less complex.

I think the fact that a re-balance is required for docker to continue working, it should be done on some kind of schedule to prevent this from happening.  Otherwise the ignorant yet influential voices will interpret this as a reason not to use docker, because it will suddenly lock up, become unresponsive, and behave weird.

At a minimum, i would add a point here: https://docs.docker.com/engine/userguide/storagedriver/btrfs-driver/#/configuring-docker-with-btrfs , telling the end user to set up a cron job to re-balance once a week during slow times, or whatever is sensible for their environment. And warn them that if they don't, docker will become unresponsive as their disk fills up and prevents future re-balancing.  something like that.

Thanks guys!

**Comment by thaJeztah** [comment]
@charlescva would you be interested in opening a pull request in the documentation repository to add a mention of this? Should probably go in the "performance" section; https://github.com/docker/docker.github.io/blob/master/engine/userguide/storagedriver/btrfs-driver.md#btrfs-and-docker-performance

**Comment by charlescva** [comment]
@thaJeztah https://github.com/docker/docker.github.io/pull/960
