### ISSUE TITLE
docker error processing tar file(exit status 1)

### ISSUE THREAD

**Issue by gwdgithubnom** [docker/docker#29625]
I need to install tensorflow by docker install method, but my pc could not connect the google service (gcr.io/tensorflow/tensorflow:latest-devel: ). So, I had to download it or save it. Firstly, I had used the vpn or other methods to connect the server, but it failed. Then, I tried to use fedora os to download it(I don't know why it could work well), and it download very quickly. So, I started to save the resource to a tar file. Here are my operation steps.

(In fedora, the docker version is newest, Docker version 1.10.3, build a612434/1.10.3)

> docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow:latest-devel

> docker save -o tensorflow_docker_cpu  gcr.io/tensorflow/tensorflow:latest-devel

And, I tried load the "tensorflow_dockercpu" file in windows.(Docker version 1.12.5). But it failed.

> docker load < tensorflow_docker_cpu

![Error](https://raw.githubusercontent.com/gwdgithubnom/issues-resources/master/docker/docker/2016/12/11/201612211425.png)

**Comment by friism** [comment]
What's the size of the tar-file? (I just want to make sure you downloaded the actual image and didn't pipe an error page into a `.tar` file).

More importantly, using `>`, `<` and `|` with binary files on Windows is dicey. I don't know the behavior in mingw/git-bash, but powershell messes files up: https://github.com/PowerShell/PowerShell/issues/1908

Use `docker load -i yourfile.tar` instead.

**Comment by thaJeztah** [comment]
Also looks like the version of docker used to pull and save the image is not an official package, but Red Hat's fork (see the commit that it's built from https://github.com/projectatomic/docker/commit/a612434f4fa5da18833706885c24a1786dfac8e2). This could well play a role

**Comment by gwdgithubnom** [comment]
@friism , thank you for the reply, and I had followed your advice. (I checked the file information. As show under the picture.) I had tried used the PowerShell to running, it was the same error.


![file-info](https://raw.githubusercontent.com/gwdgithubnom/issues-resources/master/docker/docker/2016/201612231506.png)

I had used docker load -i myfile.tar instead. And get the same error.

![file-info](https://github.com/gwdgithubnom/issues-resources/blob/master/docker/docker/2016/201612231511.png?raw=true)

**Comment by gwdgithubnom** [comment]
I had tried another install resource, https://download.docker.com/win/stable/InstallDocker.msi.
![Docker.msi](https://raw.githubusercontent.com/gwdgithubnom/issues-resources/master/docker/docker/2016/12/11/closed%20issue.png)
