### ISSUE TITLE
[1.13.0-rc4 -- Compose V3] Ports are not being exposed

### ISSUE THREAD

**Issue by foleymic** [docker/docker#29639]
When deploying a stack defined via a version 3 docker compose file, my ports are not getting exposed/published.  Is there something I'm missing here?

**Steps to reproduce the issue:**
Use this simplified docker-compose.yml file:
```
version: '3'

services:
  web:
    image: nginx
    ports:
      - "80:80"
```
``` 
$ docker deploy --compose-file docker-compose.yml test 
$ docker stack ps test 
ID            NAME        IMAGE         NODE             DESIRED STATE  CURRENT STATE           ERROR  PORTS
f8h8rz043j09  test_web.1  nginx:latest  alvd-rdbase1710  Running        Running 13 minutes ago

```

**Describe the results you expected:**
The container starts up, but port 80 is not exposed outside the container. 

I also tested with experimental off using ```docker stack deploy```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 1.13.0-rc4
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: liuih8dugncig2c69mhd93n7x
 Is Manager: true
 ClusterID: qobu5ita4tepqb9w87n5hpct6
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.50.72.105
 Manager Addresses:
  10.50.72.105:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.8-esx
Operating System: VMware Photon/Linux
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 11.72 GiB
Name: alvd-rdbase1701
ID: X6RW:SYD5:Q4GS:TSEN:PRLI:TMSD:NUNP:YEAR:4PSQ:JWJI:PCT2:OKM3
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 34
 Goroutines: 134
 System Time: 2016-12-21T09:27:56.044981582-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Experimental: true
Insecure Registries:
 myreg.mydomain.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I have also tested on a AMI (AWS) Linux VM with the same results.

**Comment by cpuguy83** [comment]
Hmm, this seems to be a display issue only as `PortStatus` is not populated in the task.

Ping @aboch @mavenugo

**Comment by foleymic** [comment]
@cpuguy83 - It looks like you are correct.  I have been testing this on my photon VMs and was not able to connect to the running container from outside (or even curl http://localhost), so when saw that the port status was still not populated on the AWS VM, I never bother to do the curl test and assumed it was a docker issue and not just a display problem.  

My photon VMs, I probably have another IPTable issue that is blocking the request.  I'll dig into that separately but keep this ticket open as it still is a display issue with ```portstatus```

**Comment by mavenugo** [comment]
This is not a display issue either. It is working as intended. --publish for a service provides both port-publishing and routing-mesh. Hence we dont populate the `ports` column of individual containers. But the user uses the new host-mode introduced in 1.13 for publishing, it works at a container level and it will be displayed here. `-p mode=host,target=x,published=y` (unfortunately this new format at the engine is not integrated into compose yet).

**Comment by liyaka** [comment]
@mavenugo Where can i find documentation on this new format that you've mentioned?
-p mode=host,target=x,published=y
Thank you

**Comment by foleymic** [comment]
@liyaka - https://github.com/docker/docker.github.io/blob/vnext-engine/engine/reference/commandline/service_create.md#publish-service-ports-externally-to-the-swarm--p---publish

**Comment by liyaka** [comment]
@foleymic I don't see format like this: -p mode=host,target=x,published=y
Is there a way to publish port on the same node where actual container is running, but not to load balancer?

**Comment by foleymic** [comment]
Sorry, here is a better link - https://github.com/docker/docker.github.io/blob/vnext-engine/engine/swarm/services.md#configure-service-networking-options

**Comment by liyaka** [comment]
@foleymic Thank you
