### ISSUE TITLE
Docker hv-sock proxy (vsudd) is not reachable

### ISSUE THREAD

**Issue by mfaizanse** [docker/docker#29634]
**Description**
I have installed latest beta build and installed it on windows 10 enterprise x64. But when I try to start it. It fails to start.

**Steps to reproduce the issue:**
1. Download Docker 1.13.0-rc4-beta34 (9562) for windows.
2. Install setup
3. Start Docker

**Describe the results you received:**
An error occured
Docker hv-sock proxy (vsudd) is not reachable
   at Docker.Backend.ContainerEngine.Linux.ConnectToVsud(TaskCompletionSource`1 vmId)
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Start(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Describe the results you expected:**
Docker Started

**Additional information you deem important (e.g. issue happens only occasionally):**
**Crash Report Diagnostic ID**
...
AB86FF97-FDED-4A14-B14D-FAF8DF99282E/2016-12-21_15-25-51
[log.txt](https://github.com/docker/docker/files/666068/log.txt)

...

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker info`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows 10 Enterprise x64 
Version 1607
OS Build 14393.0

**Comment by justincormack** [comment]
Please can you open in this in https://github.com/docker/for-win/issues as it is Docker for Windows specific.

**Comment by mfaizanse** [comment]
The problem was with windows 10 build 14393. I updated windows to latest build and the issue got resolved.
