### ISSUE TITLE
powershell in interactive container can paste only 50 chars from clipboard

### ISSUE THREAD

**Issue by StefanScherer** [docker/docker#29646]
**Description**

I still have an annoying problem working with interactive containers using a PowerShell terminal inside a Windows container. Try to paste a longer command into the terminal and it gets clipped.

**Steps to reproduce the issue:**
1. `docker run -it microsoft/windowsservercore cmd`
2. select a longer text and copy that to clipboard and paste it into the cmd shell in container -> works
3. `docker run -it microsoft/windowsservercore powershell`
4. paste the same clipboard into the powershell in container -> will be clipped at 50 characters

**Describe the results you received:**

Pasted text is clipped at 50 characters.

**Describe the results you expected:**

Should paste all the clipboard into the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc3
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc3
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   4d92237
 Built:        Tue Dec  6 01:15:44 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 13
Server Version: 1.13.0-rc3
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 2
Total Memory: 4 GiB
Name: vagrant-2016
ID: GFMQ:2WNU:6SWN:N6QC:32F4:TDD7:PMJD:ALQZ:ZCF6:VF7L:XXLN:BC2X
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows Server 2016 running in VMware Fusion Pro 8.5.3

**Comment by StefanScherer** [comment]
A pictures with such a situation. I copied the first command into clipboard and pasted it into a cmd and a powershell container:

<img width="890" alt="bildschirmfoto 2016-12-21 um 23 28 21" src="https://cloud.githubusercontent.com/assets/207759/21408596/2bede4a8-c7d6-11e6-8a19-b3e6ecfcbc52.png">

**Comment by hmdhasani** [comment]
Also in cmd when I hold the left arrow for more than about 3 seconds the entire line disappears!

**Comment by Sarafian** [comment]
I verify the problem. Version is 
```
C:\Users\Alex>docker --version
Docker version 1.13.0-rc5, build 43cc971
```

**Comment by thaJeztah** [comment]
ping @johnstep ptal

**Comment by johnstep** [comment]
Looking.

**Comment by Sarafian** [comment]
It's also rather slow and there is this other strange behavior I've noticed. Not sure if it is a generic issue or a rather specific to Windows images issue.

I run interactively a Microsoft/windowsservercore image with CMD or PowerShell. After executing command and script that output many screens with of lines then I execute `CLS`. What happens is that only the visible area gets cleaned and there is more to scroll up. 

Not sure if this relates to the output of `Write-Progress`. In general the progress output was not behaving very well and overlapped useful lines when scrolling so I turned it off.

**Comment by StefanScherer** [comment]
Duplicate of #27793, seems to be handled in https://github.com/lzybkr/PSReadLine/issues/460

**Comment by StefanScherer** [comment]
Just found out that this only happens in `microsoft/windowsservercore` containers. PowerShell in `micrsoft/nanoserver` doesn't have this problem. So another reason to use nanoserver.

**Comment by dwkerwin** [comment]
This appears to still be an open issue, and is unrelated to PSReadLine, as I don't have that module installed and am experiencing this with the microsoft/windowsservercore image.  Docker version 17.03.1-ce, build c6d412e

**Comment by Sarafian** [comment]
@dwkerwin it is still an issue and I don't believe it's PowerShell related. Same behavior applies for the command prompt. For those that might be interested, a work around is to start the container with a volume mapping, end execute scripts e.g. `Invoke.ps1` from that location inside the container. Use your editor outside the container to edit `Invoke.ps1` and leverage full copy-paste support.

**Comment by DjTrilogic** [comment]
I can confirm that the issue should stay open, as I'm facing the same problem using Docker Version 17.03.0-ee-1

**Comment by StefanScherer** [comment]
The problem is the `microsoft/windowsservercore` image that has PSReadLine installed.

Try it with the following command, copy it to clipboard,

```
Write-Host Paste and execute this command does not loose characters.
```

 then start an interactive container

```
docker run -it microsoft/windowsservercore powershell
```

Now paste your clipboard into it (I also can repro it from my Mac pasting it into a Windows container). The command is missing the last two words. Try it again in `microsoft/nanoserver` and it will work.

A fix could be removing PSReadLine from windowsservercore until it is fixed in PSReadLine module.

```Dockerfile
FROM microsoft/windowsservercore
WORKDIR "Program Files"
RUN rd /S /Q WindowsPowerShell\Modules\PSReadLine
WORKDIR /
```

**Comment by Sarafian** [comment]
I just verified this and I also want to correct myself about reporting that same problem applied for cmd prompt also. Thanks @StefanScherer  for the clarification.

**Comment by lsiddiquee** [comment]
Any update or timeline for a potential fix other than the workaround

**Comment by rismoney** [comment]
i experience this issue in windows nano 10.0.14393, not at the command line specifically, but if i open any text based app.  50 characters max, and i haven't found workaround.

**Comment by pinemosquito** [comment]
I also have same problem.

docker run -it -p 8888:8888 tensorflow/tensorflow

**Comment by joostmeijles** [comment]
Having the same problem when I exec into a container using powershell from a powershell session. 

But *not having* the copy buffer problem when I exec into a container using powershell from a Cmder bash session.

**Comment by vors** [comment]
There are so many cross-referenced issues. My understanding is that PSReadLine is red hearing: it exposes the problem on the first line of the input, but the problem is present on multi-line pastes without it. So not having it installed is a reasonable workaround for one-line pastes for me for now.

Where is the real issue that tracks this work (and I can subscribe too)?

**Comment by Asshiah** [comment]
Still encountering this problem

**Comment by StefanScherer** [comment]
@Asshiah Yes, the problem still occurs in `mcr.microsoft.com/windows/servercore:ltsc2016` based images and I guess won't be fixed there.
The problem is solved in `mcr.microsoft.com/windows/servercore:ltsc2019` based images, so if you can, update to Windows Server 2019.
