### ISSUE TITLE
Label ARM issues through Poule

### ISSUE THREAD

**Issue by alexellis** [docker/docker#29644]
A change was proposed while speaking to @justincormack to label ARM issues so that they can be identified/categorized.

More info here:

https://github.com/icecrime/poule/issues/30

PR to follow.

**Comment by alexellis** [comment]
While we're discussion this.. @icecrime is there a handler/config to try to guess what the issue is about (for common ones) and post a link to docs? I.e. about people trying to run 64-bit images on the wrong architecture?

**Comment by alexellis** [comment]
dibs

**Comment by icecrime** [comment]
Mmmm no, that would require an "auto-comment" operation in `poule` that doesn't exist yet :disappointed:

**Comment by alexellis** [comment]
@icecrime what's the process that says as Gordon "oh you need to sign that commit, here's how.."?

**Comment by alexellis** [comment]
Merged.
