### ISSUE TITLE
Couldn't create subordinate ID ranges

### ISSUE THREAD

**Issue by sharenz** [docker/docker#29659]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

I want to use option --userns-remap=default, but docker daemon throws an error on start. Looks like it calls usermod -v, which simply does not exist.

**Steps to reproduce the issue:**
1. touch /etc/subuid /etc/subgid
2. Start docker with --userns-remap
3.

**Describe the results you received:**
Daemon does not start. 
dockerd[7233]: time="2016-12-22T13:05:07.278189571Z" level=fatal msg="Error starting daemon: Error during \"dockremap\" user creation: Couldn't create subordinate ID ranges: Unable to add subuid range to user: \"dockremap\"; output: usermod: invalid option -- 'v'\nUsage: usermod [options] LOGIN\

**Describe the results you expected:**
Docker starts with user namespaces.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.6.3
 Git commit:   bac3bae
 Built:
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
CoreOS 1185.5.0

**Comment by tonistiigi** [comment]
cc @estesp

**Comment by thaJeztah** [comment]
We don't provide official packages for CoreOS, so Docker is not tested on that platform. It may be best to report this in the CoreOS issue tracker, because CoreOS ships with their own fork of Docker.

The code that is causing this error is here; https://github.com/docker/docker/blob/81683e898a53a7bcbcb0e812db640173c3895c28/pkg/idtools/usergroupadd_linux.go#L90-L126

If there is a "universal" patch for this, we could be open to accepting a pull request, but reporting at CoreOS first would probably be the first step

**Comment by sharenz** [comment]
Ok, I've opened an issue at coreos: https://github.com/coreos/bugs/issues/1728

**Comment by justincormack** [comment]
You can just create the remap files yourself.

The approach being used is not really suited to appliances, as discussed
elsewhere.

**Comment by euank** [comment]
@justincormack is correct that creating the remap files yourself would have worked.

In addition, releases of Container Linux from 1284.0.0 on include a new enough `useradd`/`usermod` command that docker can create the user and mappings itself with `--userns-remap=default`.

I think this issue can be closed.
