### ISSUE TITLE
How to deploy updated container without stopping old one

### ISSUE THREAD

**Issue by rajasekaran07** [docker/docker#29660]
Hi Team,

We are following Jenkins CICD pipeline flow for our AWS ECS container based applications. My CICD will start whether we updated any configuration in old container, Task definition, Service or any docker service. That will build new docker images based on the changes and uploaded in AWS ECR than it will deploy in our ECS cluster. 

While we deploying we stopped old containers and start with new one, Since we cant use same docker name and same port for updated container.

Kindly someone can suggest how to deploy updated container without downtime.

Regards,
Raja

**Comment by cpuguy83** [comment]
@rajasekaran07 Please use `docker service` if you would like this kind of functionality, which supports rolling updates.

**Comment by thaJeztah** [comment]
> While we deploying we stopped old containers and start with new one, Since we cant use same docker name and same port for updated container.

Also note that you can `docker rename` a container; https://docs.docker.com/engine/reference/commandline/rename/
