### ISSUE TITLE
Implement Kubernetes CRI (Container Runtime Interface)

### ISSUE THREAD

**Issue by GreatSUN** [docker/docker#29678]
Hi all,

as we are largely using Kubernetes and would like to offer our (at least internal customers) the option to use Docker, we would like to request the implementation of Kubernetes CRI to have the possibility to make use of Docker beyond it.

Are you planning to do so? If yes, is there some kind of timeline you could offer to us?

Thanks in advance,
Stefan

**Comment by runcom** [comment]
From what i can tell I believe there will be a dockershim which consumes Docker through CRI in k8s itself.

**Comment by thaJeztah** [comment]
Docker is more than a Runtime; in fact, docker itself doesn't even run containers, but uses OCI Compliant Runtimes (RunC on Linux; https://runc.io, other runtimes such as RunZ for Solaris may follow) For projects, such as Kubernetes, that want to make use of other functionality, such as networking, and images, a roadmap for containerd was announced recently  http://containerd.io. Containerd has a low level gRPC API to enable it to be embedded in other projects.

**Comment by GreatSUN** [comment]
So do I understand this properly now? Docker will basically fall out of Kubernetes and conrainerd will be placed instead?

**Comment by thaJeztah** [comment]
As @runcom mentioned, there is an adapter / shim; https://github.com/kubernetes/kubernetes/tree/release-1.5/pkg/kubelet/dockershim

**Comment by cpuguy83** [comment]
Yes, this doesn't make sense for Docker (or likely even containerd itself) to implement CRI.
These should be adapters... for which I assume one for dockerd already exists.

Closing, but feel free to discuss.
