### ISSUE TITLE
Docker log options syslog doesn't work.

### ISSUE THREAD

**Issue by Killertjuh** [docker/docker#29671]
Hey There,

I have a docker envi look at the information below for more information. I use the this options to active the syslog driver in the /etc/docker/daemon.json file.

```	
{
        "insecure-registries":["webpage:5000"],
        "dns": ["DNS IP", "DNS IP2"],
	"log-driver": "syslog"
}
```

docker info:
```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 9
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 152
 Dirperm1 Supported: true
Logging Driver: syslog    < -----------------
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.797 GiB
Name: Hostname
ID: VSIG:QOQD:OTHH:2T7B:MTBG:7DQZ:3HRK:2YVH:5LGQ:YJPN:46JE:EVK2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 webpage:5000
 127.0.0.0/8
```

When i start docker with debug mode i can see that syslog is activated: 
```
# journalctl | grep syslog
dockerd[6862]: time="2016-12-23T09:05:18.982617083+01:00" level=debug msg="Using default logging driver syslog"
```

But i dont recieve any log about docker containers in /var/log/syslog
I can even use "docker logs containerid" command to get the log from containers. 

bron: https://docs.docker.com/engine/admin/logging/overview/
> The docker logs command is available only for the json-file and journald logging drivers.

Is there something i`m doing wrong ore is this a bug ?

**Comment by cpuguy83** [comment]
Logs would be forwarded to whatever is listening at /dev/log.
Since the containers are able to start, this means docker is indeed connecting to a service there and logs are most likely being delivered.
Maybe journald is listening on a socket there? (Just a guess).

Closing as this just looks like a configuration issue on the host, but please feel free to discuss.

**Comment by Killertjuh** [comment]
@cpuguy83 Nope i dont have any container log in journalctl

I still can use docker logs containerid and it seems that the documentation about docker log thats this is impossible when using syslog.

**Comment by cpuguy83** [comment]
Sorry, I've misread the comment about getting logs.

How did you start the container?
Was it already created when you set the daemon level config?

**Comment by Killertjuh** [comment]
Yep containers are already there. First i build everthing after that i change the logging trough the daemon.json

**Comment by cpuguy83** [comment]
Ok, that's it then.
The option in the daemon config changes the default option for new containers, not existing containers.
