### ISSUE TITLE
Why  "docker attach" will hang sometimes?

### ISSUE THREAD

**Issue by erxian** [docker/docker#29670]
Hi, this issue is intended to figure out the  reason why  ```docker attach```  will hang sometimes.

Problem Reproduce

First, I run the following command to start a container , and  the container ID is 8cb40c275eff :

 ``` docker run -d -p 8080:8080 daocloud.io/daocloud/dao-tomcat:v7.0.5 ``` 

Then, I run docker attach command to attach to the running container :
```docker attach 8cb40c275eff```

However,  docker attach command will hang for ever no matter how many times I enter Ctrl+C or exit. 

The wired thing is, when I run docker attach command in another machine,  I can attach to the running container with the same command, but the container will die after I exit .

So,  firstly I wonder know why the docker attach will hang sometimes.

secondly,  I wonder know when I attached the container,  why the container will die after I exit.

Thirdly, I wonder know what's the function of  ```docker attach```, and what's the meaning of **view its ongoing output** in attach.md https://github.com/docker/docker/blob/master/docs/reference/commandline/attach.md

Docker version

```Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   bb80604
 Built:        Tue Oct 11 18:19:35 2016
 OS/Arch:      linux/amd64```

**Comment by cpuguy83** [comment]
Attach literally attaches you to the running process in the container. This means if you started up a shell, and you type exit, it exits that shell, which in turn stops the container
Attach I'm guessing is not hanging, it just isn't displaying anything that was already sent to stdio. Resizing your terminal will likekly cause it to redraw these items, including the shell prompt.

**Comment by cpuguy83** [comment]
Closing because this does not look like an issue, but feel free to discuss.
