### ISSUE TITLE
"docker node ps [nodeId]" show nothing even ran a container on node 

### ISSUE THREAD

**Issue by wcggit** [docker/docker#29672]
work node run  "docker ps"   

<img width="963" alt="2016-12-23 3 15 42" src="https://cloud.githubusercontent.com/assets/16461697/21448936/d13ab650-c922-11e6-9fc5-17ddef127267.png">

manage node ls 

![image](https://cloud.githubusercontent.com/assets/16461697/21448982/4b6b4976-c923-11e6-938f-8a5e81731401.png)

then I ran docker node ps but show noting 
![image](https://cloud.githubusercontent.com/assets/16461697/21449000/88036d50-c923-11e6-9ae7-11549a18861c.png)

I ran docker node ps -a  return "**unknown shorthand flag: 'a' in -a**" then I ran "docker node ps --help" show me 

![image](https://cloud.githubusercontent.com/assets/16461697/21449059/3eee7334-c924-11e6-815c-ecfacbc33464.png)

my docker version 

![image](https://cloud.githubusercontent.com/assets/16461697/21449012/abffd450-c923-11e6-977e-ec0ec9dad7e8.png)

 why?

**Comment by cpuguy83** [comment]
Because "node ps" is showing service tasks, not containers.

Closing as this is a non-issue, but feel free to discuss.
