### ISSUE TITLE
DNS property is ignored while creating service via compose file

### ISSUE THREAD

**Issue by Thanaton** [docker/docker#29685]
**Description**
Creating a service via a compose file in Docker 1.13-rc4 doesn't seem to support the DNS property, even though assigning a custom DNS server through the commandline tool is possible. The documentation for the new Docker Compose version 3 file doesn't indicate that the DNS property is unsupported either.

**Steps to reproduce the issue:**
1. Create a swarm with `docker swarm init`
2. Run `docker stack deploy --compose-file test.yml test` with the following compose file:

```
# test.yml
version: '3'

services:
  hello:
    image: hello-world:latest
    dns: 8.8.8.8
```

**Describe the results you received:**
Running the deploy command shows the output below. Notice the "Ignoring unsupported options: dns" line.

```
Ignoring unsupported options: dns

Creating network test_default
Creating service test_hello
```

**Describe the results you expected:**
The service should be started with the custom DNS server, as happens when we create it via the commandline tool with `docker service create --dns 8.8.8.8 --name test hello-world:latest`.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: j7e2dqmqhrahu9b4fnxp22esq
 Is Manager: true
 ClusterID: kbp1q4rd44axp9hyqk346u0xj
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: AMFI:3SYV:IXKB:BNOT:TOQF:ITPN:VHK6:RMMR:PVIJ:QEQX:3KXW:TXX6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 30
 Goroutines: 135
 System Time: 2016-12-24T16:07:23.4117973Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested on both Docker for Windows and AWS EC2 with equal results. The `docker info` and `docker version` outputs were created in the Docker for Windows environment.

**Comment by dnephin** [comment]
There is already a warning for this: `Ignoring unsupported options: dns`, so this is working correctly for 1.13.  We can add support in the next release.

**Comment by Thanaton** [comment]
Thank you for your response.

Two questions:

1. Might it be useful to document somewhere that this option is unsupported? Maybe in the compose file v3 documentation?

2. Is there a way to work around this other than updating the service through the CLI? As all my containers need the same DNS server, I tried adding it to /etc/docker/daemon.json on the swarm host, but to no avail. I still can't resolve the necessary domains. Are these 'default' DNS servers not added to swarm networks?

**Comment by thaJeztah** [comment]
@Thanaton the V3 file format documentation was added in this pull request; https://github.com/docker/docker.github.io/pull/937 and will be published when docker 1.13 is released. Would you be interested in opening a pull request if you have suggestions on what to add to that documentation? The pull request should be opened against the `vnext-compose` branch; https://github.com/docker/docker.github.io/blob/vnext-compose/compose/compose-file.md

**Comment by ifourmanov** [comment]
Any alternative ways of specifying container DNS server/options in a stack? 
Otherwise docker stack set of utilities is just useless for me

**Comment by vdemeester** [comment]
@ifourmanov a PR is opened to add support for it : https://github.com/docker/docker/pull/32059

**Comment by Thanaton** [comment]
@ifourmanov I refrained from using Compose V3 and swarm mode for this reason.

However, while testing in Januari I found a possible solution. If all of your containers use the same DNS servers and options, you can change the configuration of each Docker daemon in your swarm.

For example, add the configuration below in de daemon configuration file (default: /etc/docker/daemon.json) and restart the daemon. All containers started on that server should now use that DNS server.

```
{
    "dns": "8.8.4.4"
}
```

Once the PR goes through, you should be able to specify DNS servers and options per container instead of per server / daemon.

**Comment by mahnunchik** [comment]
Hi All @thaJeztah @vdemeester @seriousben 

This issue should be reopened according this issue: https://github.com/moby/moby/issues/34259
