### ISSUE TITLE
docker on windows has an annoying delay on container startup

### ISSUE THREAD

**Issue by hmdhasani** [docker/docker#29689]
Running this:
Measure-Command {docker run --rm  microsoft/windowsservercore cmd Exit}
or this
Measure-Command {docker run --rm  microsoft/nanoserver cmd Exit}
result in about 15 seconds

I also tried the equivalent on Linux: 
Measure-Command {docker -H 172.16.111.8:2375 run --rm ubuntu:16.04 bash}
which result in less than a second.

docker info:
Containers: 23
 Running: 17
 Paused: 0
 Stopped: 6
Images: 81
Server Version: 1.12.5
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Security Options:
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Standard Evaluation
OSType: windows
Architecture: x86_64
CPUs: 10
Total Memory: 4 GiB
Name: WIN-NIG1BQKP266
ID: 7C6M:3IJ2:MZLB:CE42:Y6IX:E7DB:WP26:Z57C:YLHE:QEYN:F25O:ZJ3S
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

docker version:
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      windows/amd64

**Comment by thaJeztah** [comment]
This is due to the way containers work on the Windows platform. I don't think Docker can change anything to improve that.

/cc @jstarks

**Comment by friism** [comment]
On a fast Windows machine, starting a windows container takes ~1 second (nanoserver-based images are fastest). This is still a lot slower than Linux containers, but workable.

I recommend upgrading to 1.13-RC which will have all the latest improvements: https://github.com/docker/docker/releases/tag/v1.13.0-rc4

Slide 34 in this presentation has details on expected performance and overhead: https://docs.com/taylorbrown/1326/windows-containers-ignite?c=1PXgwD

**Comment by hmdhasani** [comment]
I have tested on a stronger system( VM with Intel Xeon E5620 2.4 and 20GB of RAM, non SSD) and I've got around 6-11 seconds (few cases more than 15 seems to be result of cache miss).
Docker for windows is a great feature that made our life simple and this startup delay does not count in longtime cases like IIS, but many times we want to do a short time task and in these cases this delay matters.

**Comment by friism** [comment]
That sounds weird - on an EC2 c4.xlarge, this is what I see:

```
measure-command { docker run --rm microsoft/nanoserver cmd /s /c echo hello }
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 384
Ticks             : 13845710
TotalDays         : 1.60251273148148E-05
TotalHours        : 0.000384603055555556
TotalMinutes      : 0.0230761833333333
TotalSeconds      : 1.384571
TotalMilliseconds : 1384.571
```

One think you can try experimenting with is disabling parts of Windows Defender:

```
Set-MpPreference -DisableRealtimeMonitoring $true
```

**Comment by thaJeztah** [comment]
@hmdhasani have you tried @friism's suggestion?

**Comment by hmdhasani** [comment]
I will check that as soon as I get a powerful server

**Comment by thaJeztah** [comment]
Let me close this issue for now, but happy to hear your results

**Comment by mitchcapper** [comment]
Slightly off topic but trying to wrap my head around the windows docker performance expectations and windowsfilter expectations.   https://docs.com/taylorbrown/1326/windows-containers-ignite?c=1PXgwD is dead and unable to find a cached copy or the ignite presentation by taylor.
