### ISSUE TITLE
[Feature Request]: add UNION to Dockerfile syntax

### ISSUE THREAD

**Issue by fshp** [docker/docker#29719]
To reduce the number of layers, combining technique used commands through the operator "&&".

But this operator can not be combined arbitrary commands, only the commands in RUN.

I propose to introduce a new unit construction in Dockerfile syntax, which allows to combine several commands in one commit.

For example:

Instead
```Dockerfile
RUN apt-get update && \
    apt-get dist-upgrade --no-install-recommends -y
```
You can write
```Dockerfile
BEGIN
RUN apt-get update
RUN apt-get dist-upgrade --no-install-recommends -y
END
```
But such a structure in the current syntax in general is impossible:
```Dockerfile
BEGIN
ADD binary /binary
RUN /binary
END
```

**Comment by AkihiroSuda** [comment]
Starting from Docker 1.13, you can use `docker build --squash` to squash layers

```
--squash                     Squash newly built layers into a single new layer
```

Does it satisfy your requirement?

**Comment by fshp** [comment]
@AkihiroSuda great!
But this flag is very radical.
It can not combine part. Just everything.

But for my needs that's enough. Thank you.

**Comment by thaJeztah** [comment]
There's a number of similar issues that were opened in the past, but closed
because the Dockerfile syntax was frozen;

https://github.com/docker/docker/issues/1554, https://github.com/docker/docker/issues/1799, https://github.com/docker/docker/issues/16058

Also this one: https://github.com/docker/docker/pull/12198, and this one may be relevant here as well https://github.com/docker/docker/issues/7115

**Comment by fshp** [comment]
@thaJeztah thanks you for links. It was interesting to read. So I close this.

**Comment by franklinyu** [comment]
@thaJeztah The Dockerfile syntax *was* frozen, but you "unfroze" it in 07250457df03396ea61dbf3782b5f8cf1094e7e0. So is this feature under consideration now?

**Comment by muescha** [comment]
i would like to have same syntax like in a bash file (so i can copy and paste the content):

```javascript
RUN BEGIN
  apt-get update
  apt-get dist-upgrade --no-install-recommends -y
END
```

or 

```javascript
RUN {
  apt-get update
  apt-get dist-upgrade --no-install-recommends -y
}
```

**Comment by thaJeztah** [comment]
Those following this issue may be interested in https://github.com/moby/moby/issues/34423
