### ISSUE TITLE
Reference DigitalOcean volume driver from docs

### ISSUE THREAD

**Issue by omallo** [docker/docker#29729]
I've implemented a Docker volume driver to integrate DigitalOcean's block storage solution into Docker:
https://github.com/omallo/docker-volume-plugin-dostorage

If you deem it appropriate, the driver might be referenced from the Docker docs:
https://docs.docker.com/engine/extend/legacy_plugins/

**Comment by thaJeztah** [comment]
Sure; feel free to open a pull-request to add your driver; you can find the file that's used to generate that page in the documentation here; https://github.com/docker/docker/blob/master/docs/extend/legacy_plugins.md

**Comment by omallo** [comment]
Created a [pull-request](https://github.com/docker/docker/pull/29763).
