### ISSUE TITLE
Docker Remote API - Volume Create Doesn't properly support DriverOptions

### ISSUE THREAD

**Issue by raystorm** [docker/docker#29735]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Creating volumes with the Remote API doesn't support properly support **DriverOptions**

**Steps to reproduce the issue:**
1.  Create a volume 
```json
{ "Name":"curl-aserver", "Driver":"local", "DriverOpts": { "o": "uid=1000,gid=1000,gripid=1000" } }
```
2.  run `docker volume inspect curl-aserver`
3.  run `sudo ls -la` on the directory just about _data for the volume
4.  see that _data is root:root instead of whatever user has uid 100 and whatever group is gid:1000

**Describe the results you received:**
See Step 4 above.

**Describe the results you expected:**
when you run:
```shell
docker volume create --name shell-aserver --driver local --opts o=uid=1000,gid=1000,grpid=1000
````

and then check the permissions of the _data dir it has the user with UID 1000 and the group with GID 1000 listed as the file system permissions.  I expect the remote API to match.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 68
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-253:2-274722043-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 60 GB
 Data Space Total: 107.4 GB
 Data Space Available: 47.38 GB
 Metadata Space Used: 34.69 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.113 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /home/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /home/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.5 GiB
Name: labip1128.lab.lowes.com
ID: QZ46:IC4D:B4E5:IDCN:SPU7:4YKP:UYWS:ZQ3I:UQA5:HLHN:LHRG:RV6O
Docker Root Dir: /home/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
This client is running inside of a virtual machine, VMWare I think. I don't know the details.

**Comment by cpuguy83** [comment]
This is working as expected.
These are not options supported by the `local` driver, and I do not think it's correct to support them.

Closing, but feel free to discuss here.

**Comment by raystorm** [comment]
@cpuguy83 Thank you for responding so quickly.

I thought the remote API was supposed to mirror the command line functionality.

According to: 
[docker volume create](https://docs.docker.com/engine/reference/commandline/volume_create/)

> The built-in local driver on Linux accepts options similar to the linux mount command. You can provide multiple options by passing the --opt flag multiple times. Some mount options (such as the o option) can take a comma-separated list of options. Complete list of available mount options can be found [here](http://man7.org/linux/man-pages/man8/mount.8.html).

The page also has a code sample
```shell
docker volume create --driver local --opt type=tmpfs --opt device=tmpfs --opt o=size=100m,uid=1000 --name foo
```

The sample lists `uid=1000`  as one of the options passed to `docker volume create --opt`

Also
[Make uid & gid configurable for shared volumes](https://github.com/docker/docker/issues/7198) was closed citing [Support mount opts for `local` volume driver](https://github.com/docker/docker/pull/20262)

Is there something I'm missing?

**Comment by cpuguy83** [comment]
The options you listed are specific to tmpfs.

**Comment by raystorm** [comment]
Before filing this issue, I upgraded my docker install from 1.11 to 1.12 just in case it was something already fixed in a later version.  I just deleted and recreated my volume that I created with the command line, and now it doesn't have the correct permissions like it did before.

**Comment by cpuguy83** [comment]
@raystorm These options are *not* supported by the local volume driver.
What is supported is doing something like:

```Dockerfile
FROM busybox
RUN mkdir /foo && touch /foo/bar && chown -R 1000:1000 /foo
```

```
$ docker build -t test -< /that/Dockerfile/up/there
$ docker volume create --name hello
$ docker run -d -v hello:/foo test
```

And then the contents of the `hello` volume will be owned by 1000:1000.

The options you listed are specific to `--opt type=tmpfs`, and of course other types support this as well, but it's dependent on `type`, and completely handled by the underlying kernel module for the given type.

**Comment by joebowbeer** [comment]
@cpuguy83 Thanks for the explanation. I wish these options *were* supported by the local volume driver.

I've resorted to using a one-liner to create and chown the `named` volume:

```bash
docker run --rm -v named:/foo busybox chown -R 1000:1000 /foo
```
