### ISSUE TITLE
Feature request: separate build endpoint.

### ISSUE THREAD

**Issue by SamMousa** [docker/docker#29746]
I've looked around and could not find a duplicate request. This request is related to docker API permissions / authorization so there could be overlap with issues regarding API permissions.

Currently in my CI pipeline I'd love to be able to use `docker build`. There is however a big issue with exposing the docker socket as your security documentation mentions.

As far as I can tell the main security issue with exposing the docker socket is the ability to mount volumes / run containers on the host.

My proposal is to (optionally) expose a 2nd socket that only supports the build / import / export commands. The advantage here is that this will allow CI systems to build containers without allowing them (potential) full access to the docker host system.
Of course there could still be things like resource starvation, but at least not privilege escalation.

**Comment by thaJeztah** [comment]
This is already possible with authorization plugins; which allow you to block API endpoints; see https://docs.docker.com/engine/extend/plugins_authorization/

**Comment by SamMousa** [comment]
After googling so much... :|
Feel free to close this.

**Comment by thaJeztah** [comment]
You're welcome! Perhaps we should have an article on that in the user guide or "admin" section of the docs; https://github.com/docker/docker.github.io/tree/master/engine

Feel free to open an issue in the documentation issue tracker https://github.com/docker/docker.github.io/issues 👍
