### ISSUE TITLE
sharing drive throws firewall block error with windows native docker when corporate VPN is ON

### ISSUE THREAD

**Issue by sudhakar999** [docker/docker#29745]
Expected Behaviour:

	Filesharing should work even corporate VPN is ON

Actual behaviour:

	Sharing drive C fails by throwing firewall block detected error

Information:

Installed native docker on windows 10 enterprise version 10.0.14393
Also, F-secure is installed on my laptop and opened necessary network firewall openings with f-secure (to allow all traffic between 10.0.75.1 & 10.0.75.2)
Everything works fine as long as the corporate cisco anyconnect VPN is NOT ON.

But as soon as corporate cisco anyconnect vpn is ON, sharing drive C fails by throwing firewall detected error.

As you know, when switching to cisco anyconnect vpn, routing tables gets modified and it looks that filesharing is not working.

Is there any hack for this issue so that filesharing works by accessing the localhost?

**Comment by justincormack** [comment]
Can you open the issue on https://github.com/docker/for-win/issues as this issue is specific to how file sharing works on Docker for Windows. Closing here as it is not a Docker engine issue.
