### ISSUE TITLE
Docker ps not showing the ports the application is running on 

### ISSUE THREAD

**Issue by manik2131** [docker/docker#29750]
i am trying to run selenium standalone server inside docker . i was able to make to server up but when i am trying to use the docker ps , its not giving me the ports on which my container is running on . Also i am not able to connect to the webpage of the selenium server through my host system . Below are the commands i am using for my docker .

CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
0fb67f999d28        ubuntu              "/bin/bash"         6 days ago          Up 3 seconds                            sad_keller

i have tried to open the webpage for docker from my host system on default port of 4444 on which selenium listens but that also doesn't work out.

**Comment by ripcurld0** [comment]
@manik2131  how did you create and run this container?

**Comment by thaJeztah** [comment]
You need to _publish_ ports that you want to make available on the host, otherwise they are not accessible. For example, to run the official selenium image, and publish port `4444` to port `5555` on the host, run:

```
docker run -d -p 5555:4444 selenium/hub
```

And when looking at `docker ps`;

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
9d4edd8f387b        selenium/hub        "/opt/bin/entry_po..."   3 seconds ago       Up 2 seconds        0.0.0.0:5555->4444/tcp   cranky_kare
```

Now you can access the container at `http://<docker-host>:5555`

I'll close this issue, because this does not look like a bug, and doesn't have a lot of information to go on, but if you think there's a bug, please provide the information that was requested in the issue-template when you opened this issue; https://raw.githubusercontent.com/docker/docker/master/.github/ISSUE_TEMPLATE.md

**Comment by abhinavprakash1** [comment]
I am facing the same issue even though I am publishing the port.

Command:
docker run -d --name=control-center --net=host --ulimit nofile=16384:16384 --expose 9021 -p 9021:9021 -v /tmp/control-center/data:/var/lib/confluent-control-center -e CONTROL_CENTER_ZOOKEEPER_CONNECT=localhost:32181 -e CONTROL_CENTER_BOOTSTRAP_SERVERS=localhost:29092 -e CONTROL_CENTER_REPLICATION_FACTOR=1 -e CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS=1 -e CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS=1 -e CONTROL_CENTER_STREAMS_NUM_STREAM_THREADS=2 -e CONTROL_CENTER_CONNECT_CLUSTER=http://localhost:28082 confluentinc/cp-enterprise-control-center:3.3.0


PS C:\WINDOWS\system32> docker ps
CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
839565ceeee9        confluentinc/cp-enterprise-control-center:3.3.0   "/etc/confluent/dock…"   6 seconds ago       Up 6 seconds                            control-center
355554088d39        confluentinc/cp-kafka-rest:3.3.0                  "/etc/confluent/dock…"   12 hours ago        Up 12 hours                             kafka-rest
0fcd22e1221a        confluentinc/cp-kafka:3.3.0                       "/etc/confluent/dock…"   12 hours ago        Up 12 hours                             kafka
a0faddad9070        confluentinc/cp-zookeeper:3.3.0                   "/etc/confluent/dock…"   12 hours ago        Up 12 hours                             zookeeper
