### ISSUE TITLE
docker 1.13.0 CLI seems to break previous flag parsing behavior

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#29761]
```console
$ docker-machine config default
--tlsverify
--tlscacert="/Users/nathanleclaire/.docker/machine/certs/ca.pem"
--tlscert="/Users/nathanleclaire/.docker/machine/certs/cert.pem"
--tlskey="/Users/nathanleclaire/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.100:2376

$ docker $(docker-machine config default) version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64

$ docker-machine config default
--tlsverify
--tlscacert="/Users/nathanleclaire/.docker/machine/certs/ca.pem"
--tlscert="/Users/nathanleclaire/.docker/machine/certs/cert.pem"
--tlskey="/Users/nathanleclaire/.docker/machine/certs/key.pem"
-H=tcp://192.168.99.100:2376

$ docker $(docker-machine config default) version
could not read CA certificate "\"/Users/nathanleclaire/.docker/machine/certs/ca.pem\"": open "/Users/nathanleclaire/.docker/machine/certs/ca.pem": no such file or directory

$ docker --version
Docker version 1.13.0-rc4, build 88862e7
```

I'm not sure what's going on but this used to work before.  Any ideas @thaJeztah ?

**Comment by thaJeztah** [comment]
hm new to me; is this since RC4?

**Comment by nathanleclaire** [comment]
Not sure.  I'll try RC1 next.

**Comment by nathanleclaire** [comment]
FWIW, commands like `docker -H="unix:///var/run/docker.sock" ps` seems to work fine.

**Comment by nathanleclaire** [comment]
Yeah, same behavior w/ 1.13.0-rc1

**Comment by thaJeztah** [comment]
Looks like it's caused by the double quotes; they're escaped for some reason;

This fails:

```bash
docker $(echo '--tlsverify --tlscacert="/Users/sebastiaan/.docker/machine/certs/ca.pem" --tlscert="/Users/sebastiaan/.docker/machine/certs/cert.pem" --tlskey="/Users/sebastiaan/.docker/machine/certs/key.pem" -H=tcp://192.168.99.100:2376') version

could not read CA certificate "\"/Users/sebastiaan/.docker/machine/certs/ca.pem\"": open "/Users/sebastiaan/.docker/machine/certs/ca.pem": no such file or directory
```

Doing the same without double quotes;

```bash
docker $(echo '--tlsverify --tlscacert=/Users/sebastiaan/.docker/machine/certs/ca.pem --tlscert=/Users/sebastiaan/.docker/machine/certs/cert.pem --tlskey=/Users/sebastiaan/.docker/machine/certs/key.pem -H=tcp://192.168.99.100:2376') version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Sat Dec 17 01:34:17 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by nathanleclaire** [comment]
Just to note why they're quoted -- IIRC, the reason we added quoting was because users might have paths that include spaces in them.

**Comment by thaJeztah** [comment]
I suspect it's related to https://github.com/docker/docker/pull/22769#issuecomment-220720692 ;

> A few tests are breaking because pflag doesn't do this: https://github.com/docker/docker/commit/0e9c40eb8243fa437bc6c3e93aaff64a10cb856e
> Personally that behaviour feels wrong. Do we want to continue to support that quote trimming?

**Comment by dnephin** [comment]
The shell would normally remove the quotes, but I guess the strings are not being interpreted by the shell in this form, so the docker CLI is receiving a string with quotes.  The quotes are then being escaped by the error message (`"could not read CA certificate %q: %v"`).

The old flag parser had some unexpected logic to strip off quotes, which we dropped because the shell should handle it for us.

**Comment by thaJeztah** [comment]
Looks like this previously failed on docker-machine, and was changed (before that patch I linked above was applied); https://github.com/docker/machine/pull/649

**Comment by dnephin** [comment]
I guess we could create a special flag type that strips quotes and use it for these flags... It still feels very wrong to me.

**Comment by dnephin** [comment]
That PR brings up a good point. Fixing this in the docker CLI will only fix it for one case. Most CLIs will break on these double quotes.

**Comment by thaJeztah** [comment]
@nathanleclaire I guess the quotes were added for situations where the path contains spaces; could we make `docker-machine config` escape such paths (`/Users/sebastiaan\ van\ stijn/.docker/....`)?

**Comment by nathanleclaire** [comment]
or would `--flag "foo"` work?  is it just the `flag="val"` notation that's not intended to work?  I don't fully understand the desired vs. non-desired flag types.

**Comment by nathanleclaire** [comment]
As suggested, I think I'll fix this in Machine by escaping spaces with `\` -- probably the best solution as I think this was relying on incidental Docker CLI behavior before.

**Comment by nathanleclaire** [comment]
(BTW, I think this is heavily associated with subshell behavior vs. regular CLI / shell -- if I copy-paste and use the `foo="bar"` args directly, it works fine)

**Comment by nathanleclaire** [comment]
Hmmm.. seems there is an issue with that approach.. any shell experts (@tianon?) know what's going on here?  The `\` seems not to be escaping ` `.

```console
$ ./bin/docker-machine -s /tmp/nate\ store config foo1
--tlsverify
--tlscacert=/tmp/nate\ store/machines/foo1/ca.pem
--tlscert=/tmp/nate\ store/machines/foo1/cert.pem
--tlskey=/tmp/nate\ store/machines/foo1/key.pem
-H tcp://192.168.99.102:2376

$ docker $(./bin/docker-machine -s /tmp/nate\ store config foo1) version
docker: 'store/machines/foo1/ca.pem' is not a docker command.
See 'docker --help'
```

**Comment by tianon** [comment]
Correct -- `$(...)` without quotes will always space-separate.  If you want proper shell quoting parsing, you _have_ to use `eval "$(...)"` (which is one of the reasons we updated all the b2d/docker-machine suggested invocations to use that form quite some time back).

**Comment by nathanleclaire** [comment]
Ah, right... Unfortunate... I'm not sure what to do here on Machine's end.  It's not really possible to `eval $(...)` the way `docker-machine config` is intended to work, huh?

**Comment by tianon** [comment]
Yeah, one could do something like `eval "docker $(docker-machine config ...) ..."`, but there will be other side effects. :disappointed:

**Comment by nathanleclaire** [comment]
heh.. the point of `docker-machine config` is it's supposed to be fairly succinct and "non-committal" as well...

**Comment by tianon** [comment]
You could do something like `docker-machine docker <machine-name> <docker-args>`, but that's a pretty different workflow. :disappointed:

**Comment by nathanleclaire** [comment]
Yeah, I'm more concerned about backwards compat than adding new workflows. I dunno, I'm not sure the right thing to do here.  I can see the motivation for wanting the Docker CLI behavior to be a bit cleaner, but I currently can't think of any way to keep supporting `docker-machine config` with the 1.13.0 behavior.

**Comment by dnephin** [comment]
We can use a `flags.Var()` for these flags that use this flag type: https://github.com/docker/docker/compare/master...dnephin:strip-quotes-from-args

That way we don't have to support this quote trimming for all the flags, but it should be backwards compatible.

**Comment by nathanleclaire** [comment]
Ah, that'd be lovely.  Thanks Dan.

**Comment by thaJeztah** [comment]
It's likely there's other scripts in the wild that use `docker $(something that outputs options)` (other than docker machine); should we trim the quotes for every flag, or would that be difficult to implement? It feels inconsistent to only strip quotes on _some_ flags

**Comment by dnephin** [comment]
The flag trimming behaviour is really unusual, and I would say unexpected. I think removing it is generally the right idea. Since we have one very common case where it's necessary for backwards compatibility we need to add a special case, but I don't think we should apply that case to every flag.
