### ISSUE TITLE
Docker logging deamon using too much memory, 1.11.2

### ISSUE THREAD

**Issue by Hamada92** [docker/docker#29790]
Hi,

I am using Dokku and running a single app, but looks like a docker deamon is using too much memory and I can't create any more containers : 

Here is the output of `htop` 

<img width="709" alt="screen shot 2016-12-30 at 12 37 23 am" src="https://cloud.githubusercontent.com/assets/20448796/21560149/3b4a2b98-ce28-11e6-82c3-e345306aa08e.png">

I think the daemons at the bottom are what's causing the issue. 

Any help is appreciated. 

Thanks

**Comment by gianarb** [comment]
Hello @Hamada92 thanks for your report.  Can you provide more info in order to make easier for us to replicate? 

1. Can you copy paste output of `docker version` command
2. Can you copy paste output of `docker info`
3. Where are you running the daemon? CPU, Memory are good info in this case

In this way, we can also know how many containers are you running when you get this issue.
Thanks

**Comment by Hamada92** [comment]
Hi @gianarb , sure thing : 

1. `docker version` : 
```
[Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64](url)
```

2. `docker info` : 
```
Containers: 23
 Running: 12
 Paused: 0
 Stopped: 11
Images: 27
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 102
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 3.13.0-85-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 994 MiB
Name: dokku-1gb-tor1-01
ID: NSAJ:BUNI:DNM7:25WK:VOQD:NJ6I:BFTB:GXDD:3N2Z:72OC:VVQP:KWGF
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
```

**Comment by Hamada92** [comment]
also the fact that 23 containers, 12 of them are running is worrying, I only have one app that has 2 instances only, is that normal with Dokku?

**Comment by cpuguy83** [comment]
From what I can see, docker is using 2.4% of your memory, 2.7 if you include containerd.
Best to hide userland threads (which is all shared memory) when looking at htop.

What sort of error are you getting when you try to start a container?

**Comment by Hamada92** [comment]
The problem was due to too many running containers, thanks for the help. closing.
