### ISSUE TITLE
network name format in docker 1.13

### ISSUE THREAD

**Issue by gkvijay** [docker/docker#29829]
With the fix for issue #27449, docker 1.13 has a very strict check on the network names. This breaks some plugin implementations  that use the character '/' as a separator for encoding tenant name. Please allow some symbols like '/', ':', etc

**Comment by thaJeztah** [comment]
ping @mavenugo @tiborvass; also looks like the intent was to make this a versioned change https://github.com/docker/docker/issues/27449#issuecomment-256094323

**Comment by thaJeztah** [comment]
@vieux adding this to the 1.13 milestone for now; we may need to decide if the validation should be loosened up

@gkvijay orthogonal to this issue, but would using "labels" be a solution?

**Comment by gkvijay** [comment]
@thaJeztah, we could use labels to encode tenant name, but that would not let multiple tenants create networks with the same network name

**Comment by tiborvass** [comment]
@gkvijay couldn't you both add a label to encode tenant name, and a prefix for the name with the existing regex? `tenantname_networkname` ?

**Comment by gkvijay** [comment]
How is docker planning to handle host upgrades to docker 1.13 if users have special characters in these names? I would assume this will be a problem for swarm mode with overlay networks as well.

**Comment by aboch** [comment]
@gkvijay 
Existing docker network are not going through the name check. Same for network removal operation.
Only network create is affected.

As suggested by @tiborvass, shouldn't be possible for your plugin/client to convert the old separator `/` with a new one that is accepted by current restriction.

**Comment by aboch** [comment]
Also, embedding a semantic into the name of a resource which belong to and is managed by another process does not seem correct. You cannot guarantee that that process will never change the resource name syntax.

**Comment by gkvijay** [comment]
If docker network creation can take a tenant parameter as well and have unique names for networks within a tenant (key=tenant+network), we don't need to embed the tenant in the network name. A tenant may not even see the network names of other tenants (for security) and hence may not be able to provide unique names across all tenants

**Comment by mavenugo** [comment]
@tiborvass @thaJeztah @allencloud should we think about reverting https://github.com/docker/docker/issues/27449 and introduce it after we have a proper version check to avoid such backward compatibility breakages ? Yes, 1.13.0 already broke this. But we can atleast ease the pain of the users for 1.13.1 and properly introduce such changes on a particular api-verison as @tiborvass suggested.

**Comment by thaJeztah** [comment]
@mavenugo I think it makes sense, hope it's not too late for 1.13.1 though

**Comment by mavenugo** [comment]
@thaJeztah we have an upcoming libnetwork vendoring for the 1.13.1-rc2 and we can pick up the revert as well.

@tiborvass @allencloud pls voice your opinion about https://github.com/docker/docker/issues/29829#issuecomment-276660658.

**Comment by thaJeztah** [comment]
oh @tiborvass gave a thumbs up

**Comment by mavenugo** [comment]
ah. emoji reactions .... thanks. @allencloud do you have any input here ?

**Comment by thaJeztah** [comment]
While I agree with having a more sane set of accepted characters, I think we should revert and revisit for 1.14. Also wondering if the validation should go all the way in libnetwork (which is not only used by docker), or in the docker API. Putting it in the docker API makes it easier to version the change as well

**Comment by allencloud** [comment]
Oh, thanks @mavenugo for the information. Actually I am OK for the revert. Back compatibility is a very important aspect in a enterprise solution. I missed that at the very beginning. Thanks a lot.
