### ISSUE TITLE
Docker API reference doesn't define valid tags precisely

### ISSUE THREAD

**Issue by timthelion** [docker/docker#29821]
https://docs.docker.com/engine/reference/commandline/tag/

````
A tag name may contain lowercase and uppercase characters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.
````

What is a character? You mean ASCII Latin letters? The use of the word "character" is WRONG because a character refers to ANY code point! There is also more than one character referred to as dash and underscore in unicode. That needs to be specified properly too. I know you're probably referring to ASCII and not unicode, but you never actually write that.

**Comment by thaJeztah** [comment]
> The use of the word "character" is WRONG because a character refers to ANY code point!

Finding the right balance between "correctness" and "readability" can be hard; perhaps you're interested in opening a pull request to clarify that only ASCII `a-z` are accepted.

> There is also more than one character referred to as dash and underscore in unicode.

This feels like taking it too far, I think it's acceptable to keep that as-is.

**Comment by timthelion** [comment]
@thaJeztah I've create a PR which I think should make things clear. Sorry for the potentially nasty tone in the issue text. I was trying to be terse while explaining why the change is needed, but I think it reads in a mean way.
