### ISSUE TITLE
Overlay network not working between host and docker machine on same host. 

### ISSUE THREAD

**Issue by marius311** [docker/docker#29836]
I've followed the instructions [here](https://docs.docker.com/engine/swarm/swarm-tutorial/create-swarm/) to create a swarm / overlay network with two Vbox Docker machines running on the same host, and it works perfectly. 

I'm now trying to have one Docker daemon be running inside a Vbox Docker machine, but the other (the manager) natively on the same host. (Fyi, the reason I'm doing this is because this is the setup when locally testing a particular new feature of the Dockerized BOINC client, boinc-server-docker.) In this case, I have to replace the `swarm init` with:

```
docker swarm init --advertise-addr 10.0.2.2 --listen-addr 127.0.0.1:2377
```

since `10.0.2.2` is the IP address where I can reach the host from inside the Vbox VM, but otherwise the commands are all the same as in the link above. 

The swarm is created and services on it are run correctly, however, the overlay network doesn't work. Containers running on the different swarm nodes (i.e. inside the VM vs. on the host) can't ping each other using their VIP (I get a Destination Host Unreachable). 

Perhaps useful, from the host, running `nmap` on the docker-machine ip gives me, 

```
PORT     STATE         SERVICE
2376/tcp open          docker
2377/tcp closed        unknown
4789/tcp closed        unknown
7946/tcp open          unknown
2376/udp closed        unknown
2377/udp closed        unknown
4789/udp open|filtered unknown
7946/udp open|filtered unknown
```

and from inside the VM, running `nmap` on `10.0.2.2` gives me 

```
PORT     STATE         SERVICE
2376/tcp closed        docker
2377/tcp open          unknown
4789/tcp closed        unknown
7946/tcp closed        unknown
2376/udp open|filtered unknown
2377/udp open|filtered unknown
4789/udp open|filtered unknown
7946/udp open|filtered unknown
```

This is run after the both nodes have joined the swarm. 

Any help figuring out what's wrong? 

**Output of `docker version`:**

Note: I've tried both with 1.12.5 and with 1.13.0-rc4 and results are identical. The output below is after having installed the latter. 

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 23:06:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 23:06:50 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

(that was the host, I'm using the same version inside the docker-machine). 

**Output of `docker info`:**

```
docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1851
Server Version: 1.13.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1654
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: dlyhhw1urh7fa6hkhsb8pxzh1
 Is Manager: true
 ClusterID: 39cqkgraxiokcwk80sds57p7g
 Managers: 1
 Nodes: 2
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.2.2
 Manager Addresses:
  10.0.2.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.54 GiB
Name: martop
ID: DINQ:TKYT:YAE2:SHDA:LPTX:YA6H:KYUD:BETG:IX7F:ZDJT:3T2E:JSAB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: marius311
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by jmzwcn** [comment]
What is the host ip?

**Comment by marius311** [comment]
> What is the host ip?

Which IP exactly? If you mean on the host-only network (vboxnet0) its 192.168.99.1. I'm not sure it's local IP at the time of the above tests and I don't currently have my laptop on that same LAN, but I could repeat the tests and let you know if you think that's an important detail.

**Comment by jmzwcn** [comment]
The --advertise-addr flag configures the manager node to publish its address. The other nodes in the swarm must be able to access the manager at the IP address.

Not sure if this 10.0.2.2 could be access by 192.168.99.1?

**Comment by marius311** [comment]
Thanks, so yes, from inside the VM I can ping 10.0.2.2 and I get the host (which is the swarm manager). Also, the swarm itself is working fine, its just the overlay network that is not working in this configuration.

I have also tried with `--advertise-addr 192.168.99.1` but in this case neither the overlay nor the swarm works.

**Comment by thaJeztah** [comment]
Is `--listen-addr 127.0.0.1:2377` correct? Does it work with `--listen-addr 0.0.0.0:2377`?

**Comment by marius311** [comment]
With `10.0.2.2` as the advertise-addr I get 

```
$ docker swarm init --advertise-addr  10.0.2.2 --listen-addr 0.0.0.0:2337
Error response from daemon: must specify a listening address because the address to advertise is not recognized as a system address, and a system's IP address to use could not be uniquely identified
```

With `192.168.99.1` as the advertise-addr, it works, i.e.

```
docker swarm init --advertise-addr  192.168.99.1 --listen-addr 0.0.0.0:2337
Swarm initialized: current node (q4kg26ewaj86ps1ux10nbmwrc) is now a manager.
...
```

However the behavior in this case is exactly the same as with `--advertise-addr  10.0.2.2 --listen-addr 127.0.0.1:2337`, i.e. the swarm works but not the overlay network.

**Comment by thaJeztah** [comment]
Overlay networking uses these ports; https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-ports-between-the-hosts so looks like the issue is there. Perhaps there's other things at play, not sure

**Comment by marius311** [comment]
I think you must be right. Does the output from `nmap` above look like its supposed to? Any other diagnostics I can run?

**Comment by marius311** [comment]
Ah, bingo, you were right, it was a `listen-addr` problem. I think the swarm manager was listening on the wrong interface. It should have been using the `vboxnet0` interface which is created by Vbox for the "host-only" network. With the command, 

```
docker swarm init --advertise-addr  192.168.99.1 --listen-addr vboxnet0:2337
```

it now fully works, including the overlay network.

For future reference I'll post back if I can figure out how to make it work with `--advertise-addr 10.0.2.2` as well, but closing for now.

**Comment by thaJeztah** [comment]
Oh, that's good news! Glad to hear you resolved your issue
