### ISSUE TITLE
Error response from daemon: linux init cgroups path: mkdir /init.scope: read-only file system

### ISSUE THREAD

**Issue by lrusak** [docker/docker#29833]
**Description**

docker run fails to start the container

**Steps to reproduce the issue:**
1. use `docker run --rm armhf/hello-world`

**Describe the results you received:**

```
docker: Error response from daemon: linux init cgroups path: mkdir /init.scope: read-only file system.
```

**Describe the results you expected:**

for the container to be run successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

I think the error is a red herring. I'm not sure how else to debug. starting docker daemon in debug mode doesn't yield anything else. I'm not sure if it is a kernel issue or a docker issue.

I am testing docker 1.13 on LibreELEC. LibreELEC uses a squashfs, read-only file system, however, everything works fine with 1.12

dockerd is run via

```
/storage/.kodi/addons/service.system.docker/bin/dockerd --exec-opt native.cgroupdriver=systemd --group=root --graph=/storage/.kodi/userdata/addon_data/service.system.docker/docker --storage-driver=overlay2
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   1.13.0-rc4
 Built:        Mon Jan  2 23:56:09 UTC 2017
 OS/Arch:      linux/arm

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   1.13.0-rc4
 Built:        Mon Jan  2 23:56:09 UTC 2017
 OS/Arch:      linux/arm
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.13.0-rc4
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862 (expected: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e)
runc version: N/A (expected: 51371867a01c467f08af739783b8beafc154c4d7)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Kernel Version: 4.9.0
Operating System: LibreELEC (community) - Version: devel-20161213102424-r24950-g2c4fd3c
OSType: linux
Architecture: armv7l
CPUs: 4
Total Memory: 735.7 MiB
Name: LibreELEC
ID: YILE:FLLX:VW3C:SJAZ:LZYR:MX2L:6B6B:MRAQ:PFS2:BYBJ:NFI4:AHCY
Docker Root Dir: /storage/.kodi/userdata/addon_data/service.system.docker/docker
Debug Mode (client): true
Debug Mode (server): false
Username: lrusak
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

uname -a
```
Linux LibreELEC 4.9.0 #1 SMP Tue Dec 13 10:24:02 PST 2016 armv7l GNU/Linux
```
Raspberry Pi 2

**Comment by thaJeztah** [comment]
Error is coming from https://github.com/docker/docker/blob/96a84ed85a010c2cf6dc3308ae30e6594a519e59/daemon/oci_linux.go#L668 (actual error is caused here; https://github.com/docker/docker/blob/1dd941077653bc93ee4141c4d2bac90534678e3f/daemon/daemon_unix.go#L1200-L1204)

Which was added in https://github.com/docker/docker/commit/56f77d5ade945b3b8816a6c8acb328b7c6dce9a7

Looks like _at least_ that path should only be created if that option is set
