### ISSUE TITLE
hcsshim::ImportLayer fail -- Installation of SDK 8 and 10 on windowsservercore image

### ISSUE THREAD

**Issue by bikashmishra100** [docker/docker#29849]
Hello,

I am using the below docker environment.

```
Client:
Version: 1.12.1
API version: 1.24
Go version: go1.6.3
Git commit: 23cf638
Built: Thu Aug 18 17:52:38 2016
OS/Arch: windows/amd64

Server:
Version: 1.12.1
API version: 1.24
Go version: go1.6.3
Git commit: 23cf638
Built: Thu Aug 18 17:52:38 2016
OS/Arch: windows/amd64
```

I am installing windows sdk via visual studio executable on docker image windowsservercore with the below command line. It is the community edition with version 14.0.6023.29133.
run vs.exe /quiet /norestart /AdminFile deployment.xml /log c:\vs.log

The installation fails with the below error.

re-exec error: exit status 1: output: time="2017-01-02T08:31:42Z" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\ProgramData\docker\windowsfilter\3441b25be8f57331dcf863571134468a5d12fea40dfd932abc3cb7126da7a2cf flavour=1 folder=C:\Windows\TEMP\hcs640213855"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\?\C:\ProgramData\docker\windowsfilter\3441b25be8f57331dcf863571134468a5d12fea40dfd932abc3cb7126da7a2cf flavour=1 folder=C:\Windows\TEMP\hcs640213855

I cannot do a docker commit on the last container to save and check what happened. That also gives the similar error. I have pasted the deployment.xml file contents below.

Please let me know how i can provide debug logs from daemon if it is required. I have attached the deployment.xml file as txt file.

Thanks,
Bikash
[Deployment.txt](https://github.com/docker/docker/files/682340/Deployment.txt)

**Comment by thaJeztah** [comment]
What version of Windows are you running on? Also, this may be related; https://github.com/docker/docker/issues/27019

ping @friism @jhowardmsft

**Comment by bikashmishra100** [comment]
I am running on windows 2016. OS Build 14393.321

**Comment by friism** [comment]
@bikashmishra100 can you confirm that your system is fully updated?

**Comment by bikashmishra100** [comment]
@friism I updated my system and it installed KB3199986 and KB3206632. I still get the error. Please let me know if you are hinting at a specific update then i will search in the cumulative update list to see whether i got it.

**Comment by bikashmishra100** [comment]
@friism Please let me know if i can try something else.

**Comment by jhowardmsft** [comment]
OK, we can repro here. Adding my repro steps below. Between myself and @swernli we'll try to debug what's going on in the storage layers below docker.

Create `e:\docker\build\vs`
From https://www.visualstudio.com/vs/community/, download `community_ENU__887601353.1463417944.exe` into the above folder
Rename to `vsinstall.exe`
Save `deployment.xml` above into the same folder
Create `dockerfile` with the following contents in the same directory

```
PS E:\docker\build\vs> type dockerfile
#escape=`
FROM microsoft/windowsservercore
WORKDIR c:\installer
ADD vsinstall.exe .
RUN vsinstall.exe /quiet /norestart /AdminFile c:\installer\deployment.xml /log c:\vs.log
PS E:\docker\build\vs>
```

Run a docker build
```
PS E:\docker\build\vs> docker build --no-cache .
Sending build context to Docker daemon 228.4 kB
Step 1/4 : FROM microsoft/windowsservercore
 ---> 29264cbc5db6
Step 2/4 : WORKDIR c:\installer
 ---> 365f8c3bf12b
Removing intermediate container a8258869b244
Step 3/4 : ADD vsinstall.exe .
 ---> 092d8eb4c429
Removing intermediate container 9749e8ea043c
Step 4/4 : RUN vsinstall.exe /quiet /norestart /AdminFile c:\installer\deployment.xml /log c:\vs.log
 ---> Running in c4090ce22d66
re-exec error: exit status 1: output: time="2017-01-27T09:33:26-08:00" level=error msg="hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\\\?\\C:\\control\\windowsfilter\\3310426eb0a27d2f982721aa4841df92b7c5e9488e9563cdc4c25b311b195704 flavour=1 folder=C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\1\\hcs312474535"
hcsshim::ImportLayer failed in Win32: The system cannot find the path specified. (0x3) layerId=\\?\C:\control\windowsfilter\3310426eb0a27d2f982721aa4841df92b7c5e9488e9563cdc4c25b311b195704 flavour=1 folder=C:\Users\ADMINI~1\AppData\Local\Temp\1\hcs312474535
PS E:\docker\build\vs>
```

**Comment by jhowardmsft** [comment]
The import layer bug is fixed by https://github.com/docker/docker/pull/30614. I'm not sure if VS is actually installed though at the end - or if there's a bug in the deployment.xml file. However, you can commit the layer with the fix in 30614. It was a length check out-by-one error on alternate data stream filenames.

**Comment by bikashmishra100** [comment]
thank you @jhowardmsft. My deployment.xml file was invalid. I generated a fresh one and it installed visual studio completely.

**Comment by jhowardmsft** [comment]
@bikashmishra100 Great news :smile: Is there any chance you could share the revised deployment.xml file? (Or point me to how I could create one) Thanks.

**Comment by bikashmishra100** [comment]
there is a /createadminfile parameter. So you can invoke vs.exe /createadminfile c:\admin.xml to generate one.

**Comment by jhowardmsft** [comment]
Closing

**Comment by dhirschfeld** [comment]
Hello, I'm getting the same error with an up-to-date Windows Server 2016 and running a bleeding-edge docker version ```17.06.0-dev 749d90e```

PR 30614 linked above is on the moby repo. I don't know what moby is. Is it supposed to be a component of the [docker windows binary](https://master.dockerproject.org/)? And if so has there been a release of that incorporating the fixed moby?

Alternatively, is moby some component of Windows Server itself and if so has an update been released for Windows Server 2016 which incorporated the patch?

:confused:

**Comment by jhowardmsft** [comment]
@dhirshfiels - can you open a new issue with all the appropriate info. Docker version. Docker info. And repro steps

**Comment by dhirschfeld** [comment]
@jhowardmsft - I opened #32838

Sorry I haven't (yet) been able to make a minimal repro - it only seems to fail for me on the specific `testenv.yml` I am using. I think I've included all the necessary bits to repro it so I'm interested to see if it fails for others or is something specific to my environment.

In the meantime I'll continue to see if I can narrow the problem down at all...

**Comment by thaJeztah** [comment]
I'm locking the conversation on this issue, as the original issue was resolved; if you arrive here with the same issue, please open a new issue with details
