### ISSUE TITLE
syscall.GUID composite literal uses unkeyed fields

### ISSUE THREAD

**Issue by YuPengZTE** [docker/docker#29842]
**Description**

**Steps to reproduce the issue:**
1.go tool vet -all
2.
3.

**Describe the results you received:**
src\github.com\docker\docker\daemon\logger\etwlogs\etwlogs_windows.go:132: syscall.GUID composite literal uses unkeyed fields

**Describe the results you expected:**
go vet pass 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Based on https://godoc.org/golang.org/x/sys/windows#GUID, this should probably be;

```patch
diff --git a/daemon/logger/etwlogs/etwlogs_windows.go b/daemon/logger/etwlogs/etwlogs_windows.go
index c7fbdf2..0933874 100644
--- a/daemon/logger/etwlogs/etwlogs_windows.go
+++ b/daemon/logger/etwlogs/etwlogs_windows.go
@@ -130,8 +130,10 @@ func unregisterETWProvider() {
 func callEventRegister() error {
        // The provider's GUID is {a3693192-9ed6-46d2-a981-f8226c8363bd}
        guid := syscall.GUID{
-               0xa3693192, 0x9ed6, 0x46d2,
-               [8]byte{0xa9, 0x81, 0xf8, 0x22, 0x6c, 0x83, 0x63, 0xbd},
+               Data1: 0xa3693192,
+               Data2: 0x9ed6,
+               Data3: 0x46d2,
+               Data4: [8]byte{0xa9, 0x81, 0xf8, 0x22, 0x6c, 0x83, 0x63, 0xbd},
        }

        ret, _, _ := procEventRegister.Call(uintptr(unsafe.Pointer(&guid)), 0, 0, uintptr(unsafe.Pointer(&providerHandle)))
```

Did you want to open a pull request?

**Comment by YuPengZTE** [comment]
Thanks @thaJeztah.
 I have opened a pull request https://github.com/docker/docker/pull/29843
