### ISSUE TITLE
can't start docker service in ubuntu

### ISSUE THREAD

**Issue by computerwan** [docker/docker#29868]
**Description**

**Steps to reproduce the issue:**
i use ubuntu16.04 and vmware workstation12.5.2，and use proxy to connect Internet
everything is fine when i install it ,but when some time late,some wrong happens,like this:
when i restart docker daemon,it will be fine for some time,but late this wrong will happens again.

dock ps
```
An error occurred trying to connect: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: read unix @->/var/run/docker.sock: read: connection reset by peer
```

service docker status
```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─http-proxy.conf
   Active: failed (Result: exit-code) since 三 2017-01-04 10:35:34 CST; 5s ago
     Docs: https://docs.docker.com
  Process: 7544 ExecStart=/usr/bin/dockerd -H fd:// $DOCKER_OPTS (code=exited, status=1/FAILURE)
 Main PID: 7544 (code=exited, status=1/FAILURE)

1月 04 10:35:34 wan-virtual-machine systemd[1]: Stopped Docker Application Container Engine.
1月 04 10:35:34 wan-virtual-machine systemd[1]: Starting Docker Application Container Engine...
1月 04 10:35:34 wan-virtual-machine dockerd[7544]: /usr/bin/dockerd: "/usr/bin/dockerd" requires 0 arguments.
1月 04 10:35:34 wan-virtual-machine dockerd[7544]: Usage:        dockerd [OPTIONS]
1月 04 10:35:34 wan-virtual-machine systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
1月 04 10:35:34 wan-virtual-machine systemd[1]: Failed to start Docker Application Container Engine.
1月 04 10:35:34 wan-virtual-machine systemd[1]: docker.service: Unit entered failed state.
1月 04 10:35:34 wan-virtual-machine systemd[1]: docker.service: Failed with result 'exit-code'.
```
i try many solutions,but fail,is anyone can help me,thank you.

**Output of `docker version`:**

```
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-43-generic
Operating System: Ubuntu Kylin 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.937 GiB
Name: wan-virtual-machine
ID: IAKV:AGQW:XCEC:DAZO:5DXY:E3HR:3UMP:LLDU:5I6V:2NKR:JJTD:DQXQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by YummyPeng** [comment]
Can these commands help you? :point_right: [#17846 (comment)](https://github.com/docker/docker/issues/17846#issuecomment-155233858)

**Comment by thaJeztah** [comment]
I suspect your `$DOCKER_OPTS` may contain a value that causes this;

```
   /usr/bin/dockerd: "/usr/bin/dockerd" requires 0 arguments.
```

Note that the `$DOCKER_OPTS` environment variable is not used in the official packages; are you perhaps running a version of docker that's packaged by Ubuntu?

The recommended way to configure daemon options is to use a `daemon.json` configuration file;
https://docs.docker.com/engine/reference/commandline/dockerd/#/daemon-configuration-file

If you want to configure through systemd, use drop-in files, see https://docs.docker.com/engine/admin/systemd/#/custom-docker-daemon-options

Please keep in mind that the GitHub issue tracker is for reporting bugs and feature requests, for other type of questions, consider using;

- https://forums.docker.com
- The Docker Community Slack channel; https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/

From the information above, I don't think this is a bug in docker, so I'll close this issue, but feel free to continue the conversation
