### ISSUE TITLE
Why docker images File descriptors always keep 65535?

### ISSUE THREAD

**Issue by BambooAce** [docker/docker#29875]
**Description**

**Steps to reproduce the issue:**
1. I tried to move WebSocket server into Debian Docker image.
2. run Docker image with --ulimit nofile=500000:500000 and into container use ulimit command to check it , it works.
3. When i run clients about 100000, it only keep 65535 connections.
4. I also tried to modify /etc/init/docker.conf rlimit, but it not work, keep 65535
5. And my websocket server and client are no problem, i had tried without docker in my machine. And for docker image memory, CPU is enough .

**Describe the results you received:**

keep 65535 connections.
**Describe the results you expected:**
want 100000 connections.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.12.5, build 7392c3b
```

**Output of `docker info`:**

```
Containers: 4
 Running: 0
 Paused: 0
 Stopped: 4
Images: 10
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 25
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.86 GiB
Name: HPDMDebian
ID: RKPM:J3WR:ES5Q:UFZA:BEA2:JITV:INSE:QJCJ:OSPU:2AGJ:BI3Q:W6DN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http:*************************************
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Could this be limited by something else (not `nofile`), e.g. 

```
/ # sysctl -a | grep 65536
fs.aio-max-nr = 65536
kernel.ngroups_max = 65536
net.ipv4.neigh.eth0.unres_qlen_bytes = 65536
net.ipv4.neigh.lo.unres_qlen_bytes = 65536
net.ipv4.netfilter.ip_conntrack_max = 65536
net.ipv6.conf.lo.mtu = 65536
net.ipv6.neigh.eth0.unres_qlen_bytes = 65536
net.ipv6.neigh.lo.unres_qlen_bytes = 65536
net.netfilter.nf_conntrack_max = 65536
sunrpc.tcp_max_slot_table_entries = 65536
vm.mmap_min_addr = 65536
```

**Comment by BambooAce** [comment]
@thaJeztah Thanks.   Great,  set net.ipv4.netfilter.ip_conntrack_max and net.netfilter.nf_conntrack_max items bigger, it works.   Thank you.

**Comment by livfc** [comment]
Sorry if this is a stupid question, but should the net.ipv4.netfilter.ip_conntrack_max and net.netfilter.nf_conntrack_max be set in the container or the host?

**Comment by BambooAce** [comment]
The docker container will keep some kernel arguments same like host kernel, but you`d better  set --sysctl when docker run . And maybe you should create new bridge and use the new bridge. I`m not sure that the default docker0 bridge maybe whether could use sysctl to set kernel argument.

docker create network --bridge br0
docker run --network=br0   --sysctl 
(https://docs.docker.com/engine/reference/commandline/network_create/#network-internal-mode)

**Comment by hcm007** [comment]
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false
And I have elasticsearch.yml file

version: "3.3"
services:

  elasticsearch:
    image: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - efk_overlay
    ports:
      - 9200:9200
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 1000M
networks:
  efk_overlay:
    driver: overlay
    attachable: true
When I run docker stack deploy -c elasticsearch.yml elas,
the stack will failed, and the error is max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536] 
But when I run "docker service create elasticsearch"   there is no error
I think there is something wrong to do with overlay network

**Comment by thaJeztah** [comment]
@hcm007 both `stack deploy` and `docker service create` should use the same API endpoints, so that shouldn't make a difference, but if you think there's a bug, please open a new issue with more details (also the exact command you use to deploy the service with `docker service create`).

I do notice you seem to be running Docker on Amazon Linux, for which there is no official support (those packages are maintained by Amazon), so your primary point for support would be Amazon support.

**Comment by hcm007** [comment]
@thaJeztah  I can use docker service create elasticsearch (by default, use bridge)
but when I    docker network create --driver overlay test
                     docker service create --network=test elasticsearch
It will show me  max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]

**Comment by hcm007** [comment]
@thaJeztah  I fixed it, thank for your reply.

**Comment by thaJeztah** [comment]
Great!
