### ISSUE TITLE
Unable to use tcp in --gelf-address

### ISSUE THREAD

**Issue by rajasekaran07** [docker/docker#29871]
Hello,

We are running our application in AWS ECS and we are trying to collect our container logs via TCP port using gelf log driver. But if I used TCP in --log-driver-options --gelf-address tcp://ipaddress:port my container is not starting.

docker: Error response from daemon: gelf: endpoint needs to be UDP.

Kindly suggest how to use TCP in gelf-address option.

My docker version is 1.12

Regards,
Raja

**Comment by thaJeztah** [comment]
I think GELF only supports UDP; see http://docs.graylog.org/en/2.1/pages/gelf.html (and the [library that's used](https://github.com/Graylog2/go-gelf/#go-gelf---gelf-library-and-writer-for-go)

ping @mariussturm

**Comment by mariussturm** [comment]
Yes right, currently only UDP is supported.

**Comment by thaJeztah** [comment]
Thanks @mariussturm 

@rajasekaran07 given the discussion above, I'm closing this issue, because it cannot be implemented in docker currently. Feel free to ping me though if it's implemented in GELF at some point.

Also note that we are working on an option to have _external_ logging driver plugins (see https://github.com/docker/docker/pull/28403), which would more easily allow to add custom logging drivers to docker that have features that are not part of the "core" docker functionality

**Comment by rajasekaran07** [comment]
@thaJeztah @mariussturm Can we add additional tags in awslogs driver. Because while taking logs using awslogs driver we are getting minimal information. (Only container ID), How can I take image name, container name and host IP.

Regards,
Raja

**Comment by mariussturm** [comment]
@rajasekaran07 what is the awslogs driver? Anyway this is a support question that should go the IRC channel or mailing list. GH issues are used for bug reports in Docker itself. Thanks.

**Comment by thaJeztah** [comment]
@rajasekaran07 more options coming to the awslogs driver in docker 1.13, see https://github.com/docker/docker/pull/27707, and https://github.com/docker/docker.github.io/pull/380

**Comment by rajasekaran07** [comment]
@mariussturm awslogs driver is a log collector, which stream docker logs to AWS Cloudwatch log group. But it only taking container ID. I am trying to get all docker information like image name, host ip.. etc...
Thanks,
Raja

**Comment by Hermain** [comment]
FYI Gelf TCP is supported with the 17.12 ce as seen in the [docs](https://docs.docker.com/engine/admin/logging/gelf/#gelf-options)
