### ISSUE TITLE
docker stack deploy should support removing a service

### ISSUE THREAD

**Issue by ManoMarks** [docker/docker#29898]
**Description**
Currently, if I run `docker stack deploy --compose-file STACKFILE.yml STACKNAME` multiple times, subsequent `deploy` commands update the stack to match the file, with one exception. If I remove a service, the service remains in the stack. This is a feature request to have the service removed if it isn't listed, or alternately have a `remove` key in the service definition.

**Comment by campbel** [comment]
Seconded. This can be an issue if you rename a service that is binding a specific port. The next deployment will fail.
