### ISSUE TITLE
docker export doesn't work on stopped container, poor documentation

### ISSUE THREAD

**Issue by weegreenblobbie** [docker/docker#29933]
**Description**

I'm trying to export a docker image I've created so others can use it.  I'm doing this in-house and not using a shared repo yet, so I have been using docker save, but it creates huge files.  I was hoping to use docker export, but it is not working as expected.

The documentation (https://docs.docker.com/engine/reference/commandline/export/) suggests the command is:
`docker export [OPTIONS] CONTAINER`

It's not clear to me what `CONTAINER` means here.

**Steps to reproduce the issue:**
1. run `docker images` to get a list of images
2. run `docker export repo:tag -o file.tar

**Describe the results you received:**

Docker errors out with `Error response from daemon: No such container: repo:tag`

**Describe the results you expected:**

I expected `file.tar` to be written out for my repo:tag while it's not running.  I expected the documentation provide enough details that I can figure out how to use the command without searching the internet.

**Additional information you deem important (e.g. issue happens only occasionally):**

After a bunch of hacking, I was able to export something (haven't yet verified it) only if the container is running.  This is because `CONTAINER` means a container ID which only exists if an image is running.

To discover the running container ID use `docker ps` and look for your repo:tag, the first column is the container ID.  Then I was able to export with this command

```
docker export 30edce203817 | bzip2 > /tmp/docker_image.tar.bz2
```

If one stops the running container and starts it again, the container ID will change.  So I suspect that the container must be running.  If this is so, please update the documentation. 

**Output of `docker version`:**

```
Docker version 1.12.4, build 1564f02
```

**Output of `docker info`:**

```
Containers: 96
 Running: 1
 Paused: 0
 Stopped: 95
Images: 146
Server Version: 1.12.4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 972
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56 GiB
Name: slpl-nhilton-01
ID: 6NJE:OHDC:VPUA:WL5X:RA4C:AS5J:CSLO:ELVP:RS4P:7IIP:ZY6D:TXOG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Ubuntu 14.04 x86_64 laptop.

**Comment by cpuguy83** [comment]
A container would be, well, a container.
"docker export" exports a container's rootfs into a tarball. It does not handle images.
To export an image (with all its fs layers and configuration), use "docker save" and "docker load".

I think you are confusing a container with an image.
Containers can be started, stopped, restarted, etc, and will keep the same id.
Images are immutable objects.

Note that "docker run" is equivalent of "docker create" + "docker start".

**Comment by weegreenblobbie** [comment]
Clearly I'm confused, thanks for taking the time to clarify.  I am by no means a docker foo master.  I see that the ticket is closed.  Does the main the documentation won't be updated?

Being a somewhat newbie to docker, I've taken the time to document my experience in the hope that the documentation can be improved.  I didn't immediately open the ticket, having searched the internet for help and was greatly confused by this ticket: https://github.com/docker/docker/issues/2116.

Only now as I write this do I start to understand what "stopped container" means.  Yesterday I thought it meant a non running image.

I do think it's reasonably for the documentation to provide some information for the non expert to understand the command.  For example, how about a code snippet or link to something on how to determine the container id?

**Comment by cpuguy83** [comment]
I think the distinction between images and containers is fairly well covered in the getting started guide: https://docs.docker.com/engine/getstarted/step_two/

Probably a lot of the confusion comes in because people tend refer to images as containers, which is incorrect.
But do let me know if you think the getting started guide needs further improvement.

ping @thaJeztah

**Comment by mstanleyjones** [comment]
I agree that lots of people get confused by this, and that's why we have it in the Getting Started link above. Please have a look through the Getting Started content and let us know if you see ways that it can be improved. The command-line reference is not the place to address Docker basics like containers vs images, in my opinion. Thanks so much for taking the time to give us feedback. Remember that even if an issue is closed, it is still searchable and others can still find it helpful.

**Comment by weegreenblobbie** [comment]
Thanks!

From my perspective, the Getting Started guide wouldn't be a place I would go since I've been creating and running images for a while now.

The real reason I stumbled into this, I was looking for a way to squash my created image to export for others to run at my company.  We don't have an internal repo for this yet so I've been using docker save.

Besides my initial confusion about what CONTAINER meant, it also doesn't make sense to me why an IMAGE must be running to export the filesystem, after all, all the layers are sitting in /var/lib/docker/aufs/layers/.

Again, thanks for the clarifications!

**Comment by thaJeztah** [comment]
@weegreenblobbie there's no need to have an image running if you want to save it (`docker save image` is for that), but `docker export` exports a containers filesystem, including the writable layer that is mounted for the container; that layer is mounted when the container is started

**Comment by JohnLKramer** [comment]
@thaJeztah the responses here don't really address the root issue. The problem is that `docker save image` creates a tar of the image itself which is a bunch of tar and json files whereas `docker export container` actually gives you a tar of the file system of the running container.

There should be a way to export the filesystem of an image (yes, yes, an image is actually a bunch of layers and such but at the end of the day it produces a filesystem when started) without actually starting the container.

You may be asking why someone would want to do this. Well, if there as an issue starting the container (or if is designed to run to completion) having a dump of the filesystem can help troubleshoot.

**Comment by laurazard** [comment]
@JohnLKramer this is definitely something which should be easier to do, but in the meantime I'd suggest checking out https://github.com/crazy-max/undock (usage examples in https://crazymax.dev/undock/usage/examples/) to achieve what you want. (ty @thaJeztah for telling me about it :))

**Comment by JohnLKramer** [comment]
Cool! Thanks for your suggestion. That seems like a great workaround. I do think you guys should put this feature on your roadmap.

I did find a workaround though. I grabbed the Dockerfile I was inheriting from, munged it together with my docker-compose command into a new Dockerfile, and replaced the CMD with...I believe sleep or something. Then I extracted the contents of the running container.

This looks much easier. I'll use it next time.

**Comment by lee-b** [comment]
> [@thaJeztah](https://github.com/thaJeztah) ...
> There should be a way to export the filesystem of an image (yes, yes, an image is actually a bunch of layers and such but at the end of the day it produces a filesystem when started) without actually starting the container.
> 
> You may be asking why someone would want to do this. Well, if there as an issue starting the container (or if is designed to run to completion) having a dump of the filesystem can help troubleshoot.

A strong reason for this is to inspect the contents of an image without executing it.
