### ISSUE TITLE
docker always trying to pull image from https endpoint when insecure-registries define in /etc/docker/daemon.json

### ISSUE THREAD

**Issue by pawankkamboj** [docker/docker#29936]
We are facing a strange issue with latest docker build 1.12.5, Recently we have upgraded it from 1.12.1 to 1.12.5. 
With version 1.12.5, when we try to pull image from our private registry which http://qaregistry.test.com:5000, docker client always try to pull from https endpoint, we add in /etc/docker/daemon.json "insecure-registries", it was working fine with 1.12.1 but getting issue with 1.12.5.
But when i define insecure-registries in docker.service file it is working fine.

below is error with 1.12.5
[root@master ~]# docker pull qaregistry.test.com:5000/http-2.4:v1
Error response from daemon: Get https://qaregistry.test.com:5000/v1/_ping: http: server gave HTTP response to HTTPS client
[root@master ~]# 

Here is daemon.json file
{
        "storage-driver": "devicemapper",
        "storage-opts": ["dm.fs=xfs" ],
        "hosts": ["tcp://0.0.0.0:2375", "unix:///var/run/docker.sock"],
	"insecure-registries": ["qaregistry.test.com:5000"],
        "selinux-enabled": false
}

------- docker service file
[root@master ~]# cat /usr/lib/systemd/system/docker.service 
[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target

[Service]
Type=notify
ExecStart=/usr/bin/dockerd -D --log-level=debug
ExecReload=/bin/kill -s HUP $MAINPID
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
TimeoutStartSec=0
Delegate=yes
KillMode=process

[Install]
WantedBy=multi-user.target

------- docker info-------
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-253:0-26129075-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.251 GB
 Data Space Total: 107.4 GB
 Data Space Available: 4.57 GB
 Metadata Space Used: 2.064 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.145 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 3.836 GiB
Name: master.test.com
ID: Y2ZH:637S:7Y7X:4LUV:NFQL:GYI2:IEQI:EQ2X:OBK6:G7A7:JGFI:U4OZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 23
 System Time: 2017-01-06T11:00:14.64316222+05:30
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 qaregistry.test.com:5000
 127.0.0.0/8
-------------------------------------------------------

**Comment by yongtang** [comment]
I am not able to reproduce with the most recent master branch.

Though I noticed that if insecure registry is provided with a scheme (.e.g, `dockerd --debug --insecure-registry http://qaregistry.test.com:5000`) then docker pull will try to use https endpoint instead of http endpoint.

**Comment by BlaM** [comment]
Same issue here. I just updated docker from v1.12.x (nor sure which) to v1.13 on Debian Jessie and now I can't update containers anymore.

**Comment by thaJeztah** [comment]
@BlaM I notice the quotes in the output of your `docker info`, are you perhaps setting the insecure registries in a systemd unit file? If so, make sure to _not_ surround them with quotes, because when providing options in a unit file, those quotes are not stripped by the shell, causing them to be used as literal values (i.e., a registry named `"vincent:5555"`)

@yongtang I think we should add validation for that; I think we may have discussed parsing the input to be a valid url or ip-address, and not just checking if it contains `http(s)://`; wdyt?

**Comment by yongtang** [comment]
@thaJeztah I think strict validation makes sense. Added a PR #30746 for that.

**Comment by BlaM** [comment]
@thaJeztah I was able to fix it by removing the config from the systemd file (as you guessed) and add it to daemon.json. I didn't find this thread anymore so I couldn't add the info here.

The strange thing is, that it used to work before and just broke when I updated docker.

**Comment by pawankkamboj** [comment]
Just update to latest release "docker-engine-1.13.0-1.el7.centos.x86_64" and it is working fine when I define insecure-registry in daemon.json
