### ISSUE TITLE
when used NFS driver.  service is Rejected from some node in the docker swarm mode 

### ISSUE THREAD

**Issue by xang555** [docker/docker#29943]
### **hi everyone please help me understand this problem.**

i need Test persistence storage in swarm mode which i used NFS driver for create it but i have some error
here is some steps i create swarm

-  i have 4 VM which 3 VM installed docker and 1 VM install nfs server to share file or directory 
-  in the manager node i had installed [Netshare](http://netshare.containx.io/docs/nfs) for created nfs driver and start it normally 
-  after that i created volume from command :
```
docker volume created -d nfs --name myvolume -o share=<my_ip_nfs_server>:/var/data
```
 also i created overlay network from command :
```
docker network create -d overlay mynetwork
```

- and finally i'm start service from command :
```
docker service  create \
--replicas 3 \
--name myblog \
--network mynetwork\
-p 1000:2368 \
--mount type=volume,src=myvolume,dst=/var/lib/ghost \
 ghost
```
and here the problem when i used command for see status of service :
```

docker service ps myblog

```
** i saw this error :**
```

ID                         NAME          IMAGE  NODE     DESIRED STATE  CURRENT STAT                      EERROR
3lxx80e8ecnujl87vglg5y7a6   \_ myblog.1  ghost  bro2-vm  Shutdown       Rejected 2 seconds ago            "chown /var/lib/docker-volumes…"
9l77xq089y9h7ctix45ung9on   \_ myblog.1  ghost  bro2-vm  Shutdown       Rejected 7 seconds ago            "chown /var/lib/docker-volumes…"
0m9o400lnddvq9ug1kmuwjowb   \_ myblog.1  ghost  bro2-vm  Shutdown       Rejected 12 seconds ago           "chown /var/lib/docker-volumes…"
e0hjjzpb0r94c0kmlnux0jvck   \_ myblog.1  ghost  bro2-vm  Shutdown       Rejected 16 seconds ago           "chown /var/lib/docker-volumes…"
0arodm6io8drunvcw12h10lbg  myblog.2      ghost  bro2-vm  Running        Running 8 minutes ago
4z7smtvsaq9ocsa0u0a9lisi0  myblog.3      ghost  bro2-vm  Running        Running 8 minutes ago

```

**i'm kid of docker. what happen  about error ?. and how to fix it ?.**

thank you for your help !!

**Comment by thaJeztah** [comment]
Probably best to get check if 

- the tasks have an error message (`docker inspect <taskid>`)
- if the volume is indeed present on the host (i.e., if you run `docker run -it -v myvolume:/test busybox`, does it successfully start?

**Comment by xang555** [comment]
hi @thaJeztah  i'm try your instructions . in the case 2 i have been error message  
like this :
```
docker: Error response from daemon: VolumeDriver.Mount: exit status 32.

```
that mean, command for create volume(```docker volume create -d nfs --name mydata -o share=103.x.x.x:/var/data```) not work right ? because when i run container by using this command
```
docker run -i -t --volume-driver nfs -v 103.x.x.x/var/data:/data busybox

```
it is work !.

how can i do for fix this error ? and if don't annoy you , can you give instructions to me about persistence storage such as  how to do that ?

thank you so much for your help .

**Comment by ziqingzhu** [comment]
@xang555 you do not have to run `docker volume create`,just run
```style
docker service  create \
--replicas 3 \
--name myblog \
--network mynetwork\
-p 1000:2368 \
--mount type=volume,volume-opt=o=addr=`your nfs server addr`, volume-opt=device=:/var/data, volume-opt=type=nfs, source=myvolume, target=/var/lib/ghost
 ghost
```
it will create a volume with local driver, you can see it with `docker volume ls`

**Comment by thaJeztah** [comment]
oh, yes, I just realised you're trying to use `nfs` as _driver_, but there's no such driver by default (unless you have installed a custom plugin); use the default ("local") driver with `type=nfs`, as @ziqingzhu showed, and as explained in the docs here; https://docs.docker.com/engine/reference/commandline/volume_create/#/driver-specific-options.

You _can_ use a custom plugin / driver for services, but you need to make sure that plugin is installed on each node that you want to run the service.

Based on the above, I don't think this is a bug in Docker, so I'll close this issue, but feel free to continue  the conversation

**Comment by xang555** [comment]
thank you so mush @thaJeztah  for your  instructions this is good for me to continues learn about docker swarm .  and @ziqingzhu  thank you for your showed
