### ISSUE TITLE
Docker Exec -it CONTAINER bash - kills docker daemon

### ISSUE THREAD

**Issue by rcsavage** [docker/docker#29945]
When I run docker exec -it CONTAINER bash, it seems to kill the docker daemon in FreeBSD-11.   I see the following errors in /var/log/docker.log:

time="2017-01-05T17:40:21.932323800-05:00" level=debug msg="Calling POST /containers/{name:.*}/exec"
time="2017-01-05T17:40:21.932364867-05:00" level=info msg="POST /v1.19/containers/5849031a5776/exec"
time="2017-01-05T17:40:21.933046448-05:00" level=debug msg="Calling POST /exec/{name:.*}/start"
time="2017-01-05T17:40:21.933062232-05:00" level=info msg="POST /v1.19/exec/f7c53df4adc90c68fdc458216072256792b88ddfcf5a64a9e6e235892a6edfb1/start"
time="2017-01-05T17:40:21.933126346-05:00" level=debug msg="starting exec command f7c53df4adc90c68fdc458216072256792b88ddfcf5a64a9e6e235892a6edfb1 in container 5849031a577625f84f1b59b1b049ccd940aca6ccbff530b88a724f708506100f"
time="2017-01-05T17:40:21.933201845-05:00" level=debug msg="attach: stdin: begin"
time="2017-01-05T17:40:21.933246124-05:00" level=debug msg="attach: stdout: begin"
time="2017-01-05T17:40:21.933647083-05:00" level=debug msg="Calling POST /exec/{name:.*}/resize"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x1b pc=0x933b8b]

goroutine 118 [running]:
panic(0xbe2760, 0xc820010080)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/docker/docker/daemon/execdriver/jail.(*TtyConsole).AttachPipes(0xc82031b4a0, 0xc8202e7228, 0xc8202714d0, 0x0, 0x0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/daemon/execdriver/jail/driver.go:413 +0x14b
github.com/docker/docker/daemon/execdriver/jail.NewTtyConsole(0xc8202e7228, 0xc8202714d0, 0x12cf630, 0x0, 0x0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/daemon/execdriver/jail/driver.go:379 +0x109
github.com/docker/docker/daemon/execdriver/jail.(*driver).Exec(0xc820295080, 0xc82004a000, 0xc8202e7228, 0xc8202714d0, 0xc82031b450, 0x4171d2, 0x0, 0x0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/daemon/execdriver/jail/driver.go:203 +0xa5
github.com/docker/docker/daemon.(*Daemon).Exec(0xc820074270, 0xc8200e21e0, 0xc8202e7200, 0xc8202714d0, 0xc82031b450, 0x3532363737356131, 0x0, 0x0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/daemon/exec.go:235 +0x97
github.com/docker/docker/daemon.(*Container).monitorExec(0xc8200e21e0, 0xc8202e7200, 0xc82031b450, 0x0, 0x0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/daemon/container.go:1635 +0x1fe
github.com/docker/docker/daemon.(*Container).Exec.func2(0x0, 0x0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/daemon/container.go:1616 +0x3e
github.com/docker/docker/pkg/promise.Go.func1(0xc8202a4d20, 0xc8201acde0)
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:8 +0x1d
created by github.com/docker/docker/pkg/promise.Go
        /usr/ports/sysutils/docker-freebsd/work/docker-582db78/.gopath/src/github.com/docker/docker/pkg/promise/promise.go:9 +0x5d

However, when I do not run docker exec in TTY mode, it works, although I do not get a pseudo tty

[root@rogue /var/log]# docker exec -i 2391b705e191 bash
ls
bin
boot
dev
etc
home
lib
lib64
media
mnt
opt
proc
root
run
sbin
srv
sys
tmp
usr
var
uname -a
Linux  2.6.32 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Closing since this code doesn't even exist anymore.
Any sort of execution on BSD must be handled by an OCI compatible runtime.
See https://github.com/opencontainers/runtime-spec

**Comment by rcsavage** [comment]
Cheap cop-out.  Thanks alot lazy.

**Comment by justincormack** [comment]
@rcsavage the FreeBSD port was never upstreamed so we cannot support it here. There is some talk of doing it upstream, which would be great, as we all want FreeBSD support.

**Comment by cpuguy83** [comment]
@rcsavage First off, thanks for the kind words of support.

This code doesn't exist in docker anymore. All low-level container abstractions must be handled by an OCI-compatible runtime, including even Linux containers (see opencontainers/runc).
There is nothing here for us to debug in Docker, there is no patch to be made to Docker that will fix your issue, and your build of Docker is over a year old... this is why I have closed your issue.

As always the comments remain open for anyone who wants to coordinate on such an issue.
