### ISSUE TITLE
Docker for Mac: slow (>5sec) DNS resolution

### ISSUE THREAD

**Issue by bandesz** [docker/docker#29948]
**Description**

On Docker for Mac since the latest update (1.12.5) the DNS resolution is really slow with libcurl. We can see resolution times little over 5 seconds. This happens on everyone's laptop consistently who upgraded to 1.12.5. (Also I didn't find the previous release anywhere (1.12.3), can we download that from somewhere?)

**Steps to reproduce the issue:**
1. Start e.g. a debian container and install curl
2. curl --trace-time -v https://google.com

**Describe the results you received:**

[...]
15:03:29.175495 * Hostname was NOT found in DNS cache
15:03:34.722908 *   Trying 216.58.198.238...
[...]

As you can see DNS resolution takes >5 seconds. We see the same results from our node.js app.

If I run nslookup or ping it responds quickly as expected.

**Describe the results you expected:**

DNS resolution should be miliseconds. If I run the same container but with "--dns 8.8.8.8" the DNS resolution will be quick as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue happens consistently on multiple different Macbooks. My OS X version is 10.12.2.

Contents of /etc/resolv.conf:
```
domain local
nameserver 192.168.65.1
nameserver 192.168.65.10
nameserver 192.168.65.9
nameserver 192.168.65.8
nameserver 192.168.65.7
nameserver 192.168.65.6
nameserver 192.168.65.5
nameserver 192.168.65.4
nameserver 192.168.65.3
```

**Output of `docker version`:**

```
Docker version 1.12.5, build 7392c3b
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.39-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 7UPW:NUYF:NA2F:ZJGU:STME:6VU5:Q5M2:RHBB:GX7C:6TNA:S6MN:N7HY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 29
 System Time: 2017-01-06T15:08:14.181376688Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: bandesz
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment]
Please can you open an issue in https://github.com/docker/for-mac/issues as this is specific to the Mac not to Docker engine. Also I would recommend you try the beta channel of Docker for Mac as there are a lot of fixes related to DNS, but support in for-mac will be able to help more effectively.

I am going to close this here as it is not a docker engine issue.
