### ISSUE TITLE
Not able to bind to non local ip in a container even if net.ipv4.ip_nonlocal_bind is set

### ISSUE THREAD

**Issue by krishnasrk** [docker/docker#29954]
I am trying to setup two docker containers one as a Active and other as Standby in a HA pair. Active container will hold a Virtual IP (VIP). 
I need to bind to VIP in both Active and Standby to listen for external messages. As VIP will be present in one of the containers, I enabled the net.ipv4.ip_nonlocal_bind on host machine. Able to bind to VIP on both containers when network mode is set to host. But not when network mode is set to default bridge.

**Q. Is there a way to bind on non-local ip with default bridge network mode?**

Additional Info
=============
Container is based on centos:7.2.1511
docker run options for both containers
1. --privileged 
2. -d

Docker version
==============
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        
 OS/Arch:      linux/amd64

Docker info
============
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 49
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-68468610-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.212 GB
 Data Space Total: 107.4 GB
 Data Space Available: 44.71 GB
 Metadata Space Used: 5.956 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.28.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 31.26 GiB
Name: localhost.localdomain
ID: XGH5:M4II:TMSQ:OCLI:EW5H:EIMD:AXYB:FOOM:D3KK:ILNP:B3H2:3XN6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8

**Comment by justincormack** [comment]
Network namespaces are different IP stacks, they are isolated, thats how namespaces work, so not like that. You can put the containers in the same namespace with `docker run --network container:<name|id>` see https://docs.docker.com/engine/reference/run/#/network-container then they will share the same network stack.

**Comment by krishnasrk** [comment]
Thanks for your quick response. With network-container, both will have same iP addresses I need to have different IP's so keepalives will be sent between the containers, based on keepalives and other priorities Vitrual IP will assigned (similar to keepalived).    
```
            -------------------------------(VIP-172.17.0.100)
            | Container1 (172.17.0.2)       |
            |                 |             |------ Container3(172.17.0.4)
            |                 |(keepalives) |
            | Container2 (172.17.0.3)       |
            --------------------------------
```

**Comment by justincormack** [comment]
hmm, cc @aboch any ideas?

**Comment by aboch** [comment]
@krishnasrk  Did you try to manually set the `net.ipv4.ip_nonlocal_bind` in each container ?

**Comment by krishnasrk** [comment]
Yes @aboch

**Comment by krishnasrk** [comment]
I found a workaround for binding standby container where VIP IP is not associated with the container as below.

1. On Active container 172.17.0.2 (where VIP is assigned), do bind to VIP.
2. Now make this 172.17.0.2 container as standby and make other container 172.17.0.3 as active (VIP is moved)
3. On 172.17.0.3 Do bind to VIP. So now both containers bind to VIP and when flip happens there is no issue.

But I am looking to see for a better way to make with net.ipv4.ip_nonlocal_bind

**Comment by sanimej** [comment]
@krishnasrk What error are you seeing when you try to bind to the VIP in the container ? From a quick check it does seem to work; but I didn't verify the connectivity from a different container.

**Comment by krishnasrk** [comment]
I am getting this Error @sanimej "Cannot assign requested address" for bind call. As you mentioned it works in your setup, is it centos based docker container running on centos Host machine?

**Comment by aquarapid** [comment]
This looks like it's an upstream kernel problem with CentOS (RedHat):  https://bugs.centos.org/view.php?id=11238

**Comment by mavenugo** [comment]
Thanks @aquarapid . 
Closing this based on the above comment https://github.com/docker/docker/issues/29954#issuecomment-274222691.

Pls try another distro or wait for the fix from centos.
