### ISSUE TITLE
docker stack deploy assumes HostPort is an integer

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#29961]
`docker stack deploy` uses `ConvertPortToPortConfig` to convert a port specification parsed from a compose file. This function does no error checking when converting `binding.HostPort` from a string to an int:

https://github.com/docker/docker/blob/6d77c02240c43b79ed518ad9ef92466aa84b2b4a/opts/port.go#L136

However, the parser that generated `binding.HostPort` does not necessarily put a valid int there. It may also generate a range:

https://github.com/docker/docker/blob/6d77c02240c43b79ed518ad9ef92466aa84b2b4a/vendor/github.com/docker/go-connections/nat/nat.go#L228

I think that `ConvertPortToPortConfig` should not ignore the error from `ParseUint`, or there should be special handling for port ranges.

Feel free to close this if it's not actually a problem. I noticed it while reading the code and didn't look right.

cc @dnephin @tiborvass

**Comment by TDAbboud** [comment]
#dibs

**Comment by TDAbboud** [comment]
The PortConfig struct in the swarm types only accepts a uint32 as a PublishedPort. So if we encounter that the user has entered a range when converting to a PortConfig should we just state that the swarm api doesn't accept a hostPort Range and fail gracefully?

**Comment by aaronlehmann** [comment]
Precisely, we should fail gracefully in this case.
