### ISSUE TITLE
How to install latest rc on ubuntu?

### ISSUE THREAD

**Issue by whitecolor** [docker/docker#29977]
Kind of basic question but didn't find particular recommendations in docs: what is a preferred way to install latest RC/beta on ubuntu, and how to get exact (previously available RC/beta) version if needed?

**Comment by cghislai** [comment]
https://docs.docker.com/engine/installation/linux/ubuntulinux/#install-a-pre-release-version contains all the information you need (first search result for install docker ubuntu btw )

**Comment by whitecolor** [comment]
Thanks!
