### ISSUE TITLE
[multi-arch support] Expose host target as an ENV in Dockerfile

### ISSUE THREAD

**Issue by bluefoxicy** [docker/docker#29978]
This was a bit hard to search for; I tried, and may have missed it.

**Description**

Currently, Docker registries such as Docker Hub cannot support a multi-architecture format.  In the future, Docker could have the ability to select an image based on its target system, such as 'darwin-x64' (MacOSX) or 'linux-armhf' (Raspberry pi).

To facilitate this, I suggest Docker expose its target as the `DOCKER_TARGET` environment variable.  That is the minimum required to support multi-arch in a single `Dockerfile`.  

As an example, the below would produce an Alpine Linux image:

```Dockerfile
FROM scratch

# Security- and performance-related CFLAGS
# for downstream images built from source
ENV CFLAGS "-fstack-protector-strong -fpic -fpie -Wl,-O1 -O2 -Wl,--hash-style=both"
ENV CPPFLAGS "$CFLAGS"
ENV LDFLAGS "-O1 --hash-style=both"

ADD https://mirrors.alpinelinux.org/alpine/v3.5/releases/armhf/alpine-minirootfs-3.5.0-${DOCKER_TARGET}.tar.gz /

RUN apk update && apk upgrade && find /var/cache/apk -type f -delete

CMD ["/bin/sh"]
```

So long as there is an Alpine minirootfs for the target with that path specification, this will build.  Thus, Alpine could release several tarballs:

* alpine-minirootfs-3.5.0-linux-x86_64.tar.gz /
* alpine-minirootfs-3.5.0-darwin-x86_64.tar.gz /
* alpine-minirootfs-3.5.0-linux-armhf.tar.gz /
* alpine-minirootfs-3.5.0-linux-aarch64.tar.gz /

Attempting to build the above Dockerfile on Linux x86-64, on MacOSX, and on a Raspberry Pi (armhf) or Android (armhf, aarch64) would just work.

**Additional information**

This makes it possible to write one Dockerfile and have it build to whatever `DOCKER_TARGET` the machine represents.

A future update to the registry and `docker` engine could allow tagging of images such that `docker pull alpine` would attempt to pull one of several target-specific `alpine:latest` images, instead of _the only_ `alpine:latest` image.  The infrastructure changes to support that are a matter for another issue.

**Comment by justincormack** [comment]
There already is multi arch support. Not all the tooling is in place yet but its in progress. See #27455 for the WIP PR, and there are several blogposts most recently https://container-solutions.com/multi-arch-docker-images/

**Comment by justincormack** [comment]
I am going to close this as you can already do this, and the tooling to make it easy is being worked on.

**Comment by bluefoxicy** [comment]
Thanks, I couldn't find anything concrete about this with some amount of googling over the past weeks.
