### ISSUE TITLE
Add --read-only for Swarm Services

### ISSUE THREAD

**Issue by docwhat** [docker/docker#29972]
Please add the `--read-only` flag to Swarm services (i.e. `docker service create` and `docker service update`).

I tried searching, but didn't find any issues that matched this request.  For others searching... when doing a `docker inspect`, the attribute is `HostConfig` / `ReadonlyRootFS`.

**Comment by justincormack** [comment]
The options missing in swarm mode are being tracked in #25303

**Comment by docwhat** [comment]
Ah, thanks!  That was really hard to search for.

**Comment by justincormack** [comment]
I have linked this issue from the table. It should be really easy to implement, if you want to have a go...

**Comment by yongtang** [comment]
Add PR #30162 and https://github.com/docker/swarmkit/pull/1872 to address the issue.
