### ISSUE TITLE
OSX & Docker Volume via NFS

### ISSUE THREAD

**Issue by kotowick** [docker/docker#29971]
Hello,

Has any one tried to use a NFS docker volume with OSX? I can't seem to get it to work.

**Steps**
1. On OSX, add this to /etc/exports: `/Users -alldirs -network 172.18.0.0/16 -rw -mapall=root`
2. run "docker volume create --driver local --opt type=nfs --opt o=addr=<mac_ip_address>,rw --opt device=:/Users/<user>/<folder_to_mount> --opt  --name local/nfs
3. docker run -it -v local/nfs:/webapp <docker_image> bash

**Errors:**
docker: Error response from daemon: error while mounting volume with options: type='nfs' device=':/Users/<user>/<folder_to_mount>' o='addr=<mac_ip_address>,rw': permission denied

**Reference:**
https://docs.docker.com/engine/reference/commandline/volume_create/

**Comment by justincormack** [comment]
The network connection probably doesnt appear to come from `172.18.0.0/16`. It might be `127.0.0.1` actually, as the connections are proxied locally by vpnkit.  You will get better support if you open an issue in https://github.com/docker/for-mac/issues as this is specifically for Docker for Mac, so I will close this here as this is specifically for docker engine issues.
