### ISSUE TITLE
[1.13.0-rc5] Disabling/remapping _default Compose network doesn't work with Swarm mode

### ISSUE THREAD

**Issue by IevgenKabanets** [docker/docker#29982]
There is no way to disable the creation of `[projectname]_default` network using Compose v3 files and experimental `docker deploy` feature. 
I would assume a creation of the custom top-level network (with overlay driver, for example) will eliminate the need for `default` network. Also, the attempt to use a pre-existing (external) network as `default` fails to give the result.  
I would expect `default` network to be unnecessary when external one is being used (as Swarm mode handles it all right) or the possibility to use a pre-existing one. 

**Environment**:
Docker version: 1.13.0-rc5, Swarm mode (node is manager).
Compose file, 'v3'.
Ubuntu 14.04, amd64, kernel 3.19.0-25-generic.

**Steps to reproduce the issue:**
1. Use [this](https://gist.github.com/IevgenKabanets/c75e3f7c7373dcdf9283a06811a96492) or [this](https://gist.github.com/IevgenKabanets/dacf3a7c9f73955c0697b426ee52ba3c) Docker Compose file as an example.
2. Run `docker deploy --compose-file compose.yml my_service`.
3. Run `docker network ls`.

**Network configuration in Compose file**:
```
networks:
  default:
    external:
      name: some-network
```
or
```
networks:
  some-network:
```

**Describe the results you received:**
Both `[projectname]_default` and custom network are present.
In a case of an attempt to use a pre-existing network - `[projectname]_default` is still being created.

**Describe the results you expected:**
I would expect an option to disable `[projectname]_default` network or at least use the pre-existing one.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:47:37 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 00:47:37 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.13.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 60
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: mqvoca80bsaifkk9u6pjnz4hd
 Is Manager: true
 ClusterID: 3ofrxxpsyxd4utq2j0sm4jia6
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.31.63.115
 Manager Addresses:
  10.31.63.115:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: vamsdocker03
ID: 74XR:BTT3:Q53C:3CB5:HWUL:CHYV:CH5S:27LI:XEQI:ZZ45:AINI:5I6Q
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by IevgenKabanets** [comment]
[This issue's](https://github.com/docker/compose/issues/2470) resolution doesn't work (as I described).

**Comment by akalipetis** [comment]
Seems like [there's already in the TODO](https://github.com/docker/docker/blob/f5af9b9/cli/compose/convert/compose.go#L51) for that.

We could pass the whole `config` there, [like we do in `convert.Services`](https://github.com/docker/docker/blob/f5af9b9/cli/compose/convert/service.go#L16) and check if the default network is used. I could give it a try if the proposal above is fine with you.

**Comment by akalipetis** [comment]
We should also probably relabel this `area/bundles` instead of `area/networking`.

**Comment by vdemeester** [comment]
Should be fixed by #29994

**Comment by mostolog** [comment]
I'm not able to find clear documentation on this. Having an already created network called "mynet", **what's the supposed syntax for compose 3?**

```
# this?
networks:
  default:
    mynet:
      external: true

# or this?
networks:
  default:
    external:
      name: mynet
# or none of them?
```

Regards

**Comment by dnephin** [comment]
https://docs.docker.com/compose/compose-file/#/external-1

The second should work

**Comment by mostolog** [comment]
It seems it doesn't. Already filled an issue after testing in multiple ways.
