### ISSUE TITLE
"Docker run -it xxx /bin/bash "  error

### ISSUE THREAD

**Issue by xzy256** [docker/docker#29990]
hi,
When i exec "docker run -it xxx /bin/bash", i get as follow error. But other order i can get correct result.
I build docker(1.12.5) , contanierd(0.2.5), and runc(1.0.0) by myself.
The deamon log:
ERRO[2872] containerd: start container error=containerd: container not started id=c32a13df611a0a2af3831042930c197769f6a80a895b476eb4ef38992a84a743
ERRO[2872] Create container failed with error: containerd: container not started
ERRO[2873] Handler for POST /v1.24/containers/c32a13df611a0a2af3831042930c197769f6a80a895b476eb4ef38992a84a743/start returned error: containerd: container not started

**As if the containerd gets error .How to do for fixing it?**
bash# docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.7
 Git commit:   1df474a-unsupported
 Built:        Fri Jan  6 22:30:36 2017
 OS/Arch:      linux/mips64le

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.7
 Git commit:   1df474a-unsupported
 Built:        Fri Jan  6 22:30:36 2017
 OS/Arch:      linux/mips64le

**Comment by thaJeztah** [comment]
>  But other order i can get correct result. I build docker(1.12.5) , contanierd(0.2.5), and runc(1.0.0) by myself.

It looks like you're not building from the 1.12.5 commit (https://github.com/docker/docker/commit/7392c3b0ce0f9d3e918a321c66668c5d1ef4f689), using different versions of `containerd` and `runc` than are used for 1.12.5 (https://github.com/docker/docker/blob/7392c3b0ce0f9d3e918a321c66668c5d1ef4f689/Dockerfile#L245, https://github.com/docker/docker/blob/7392c3b0ce0f9d3e918a321c66668c5d1ef4f689/Dockerfile#L256), and an architecture that's not supported (mips64le).

We won't be able to help you with that directly, so I'll close this issue, but happy to answer questions where needed

**Comment by xzy256** [comment]
Thanks for your answer. Could you tell me the corresponding version between containerd and runc?
I learn about  corresponding version between docker and container from containerd github.
> Container v0.2.5
> @mlaventure mlaventure released this on 6 Dec 2016 · 185 commits to master since this release
> Used by docker 1.12.5

By the way,thank you again.

**Comment by thaJeztah** [comment]
> Could you tell me the corresponding version between containerd and runc

Best way to get the exact commit needed is to look in the Dockerfile (https://github.com/docker/docker/blob/v1.12.5/Dockerfile).

**Comment by xzy256** [comment]
I build docker again according to what you said.
But i get a new error.

docker:Error response from deamon:invalid header field value "oci runtime error :container_linux.go:247:starting container process caused operation not supported"

**Comment by thaJeztah** [comment]
I you're running on mips64le, you can't run the regular images from docker hub; most of those are for amd64.

You'll  need to create your own images from scratch (or search on docker hub if someone else made some)

There's no official images for that architecture, because it's not a supported architecture

**Comment by xzy256** [comment]
Images is created by myself. And it run nomally on old docker-1.6 at my plated.
