### ISSUE TITLE
invalid header field value"oci runtime error"

### ISSUE THREAD

**Issue by xzy256** [docker/docker#30017]
hello,
When i exec "docker run -it xxx  /bin/bash", I get
the next error. Having no idea how to do.

error log:
docker :Error response from daemon :invalid header field value "oci runtime error:container_linux:247:starting container process cause \"operation not supported\"\n"

by the way, 
bash#docker version
Client:
Version:  1.12.5
API version:  1.24
Go version: go1.7
Git commit: 7392c3b-unsupported
Built: Mon Jan 9 21:44:28 2017
OS/Arch: linux/mips64el

thanks

**Comment by xzy256** [comment]
images is created by my self.  Runing normal in docker-1.6 at our plate

**Comment by justincormack** [comment]
Hi, we currently do not have official support for MIPS platforms, so not surprised you are running into issues, and as you see you are running an unsupported commit as well, and you have not provided the information requested in the template. I don't know where you got your Docker from, or what the image you are trying to run is, I am not sure if there are mips64el images available either, so there is very little I can do to help other than guessing. My guess would be you don't have the right options for containers compiled into your kernel; the `check-config.sh` script in this repo.

As far as I know no one is currently working on mips64 support, although there has been some discussion of mips32 support once the Go port is done. It would be nice if someone wants to work on it though.

I am closing this as there is no mips support, and master will not build on mips at all at present as there is no gccgo support any more, so it needs a real port done. Feel free to continue discussion here though.

**Comment by xzy256** [comment]
Thank you. I git clone docker from github. Built docker,containerd,runc etc.  What's more, i run other orders successfully except "docker run". By the way, Image  is created by making tiny system, and exec "cat xxx.tar|docker import - xxx" .

**Comment by xzy256** [comment]
@justincormack When i run the check-config.sh , the console output is as follow. I guess the reason why "CONFIG_NETFILTER_XT_MATCH_IPVS" is disable .

[bash]$ sh ./contrib/check-config.sh
warning: /proc/config.gz does not exist, searching other paths for kernel config ...
info: reading kernel config from /boot/config-3.10.84-11.fc21.loongson.mips64el ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
**- CONFIG_NETFILTER_XT_MATCH_IPVS: missing**
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: missing
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: missing
- CONFIG_MEMCG_SWAP: enabled
- CONFIG_MEMCG_SWAP_ENABLED: enabled
- CONFIG_MEMCG_KMEM: enabled
- CONFIG_RESOURCE_COUNTERS: enabled
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: enabled
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: missing
- CONFIG_NETPRIO_CGROUP: missing
- CONFIG_CFS_BANDWIDTH: enabled
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: enabled
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: missing
- CONFIG_IP_VS_RR: missing
- CONFIG_EXT3_FS: enabled
- CONFIG_EXT3_FS_XATTR: enabled
- CONFIG_EXT3_FS_POSIX_ACL: enabled
- CONFIG_EXT3_FS_SECURITY: enabled
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: missing
    Optional (for secure networks):
    - CONFIG_XFRM_ALGO: enabled
    - CONFIG_XFRM_USER: enabled
  - "ipvlan":
    - CONFIG_IPVLAN: missing
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 200
    This should be set to at least 10000, for example set: sysctl -w kernel/keys/root_maxkeys=1000000
