### ISSUE TITLE
No line numbers on Dockerfile parse errors

### ISSUE THREAD

**Issue by justincormack** [docker/docker#30022]
In 1.13 we pre parse the Dockerfile for errors, but the reporting sadly lacks the context you would get from the previous setup, as you can't see where in the Dockerfile you have got to. This came up while debugging yesterday where there were two places in the Dockerfile the error could occur, and the user had I think only checked the first one, but the error did not help.

eg with this Dockerfile
```
FROM alpine
ERROR
RUN echo
ERROR
```

I get 
```
buckeye:error justin$ docker build .
Sending build context to Docker daemon 2.048 kB
Error response from daemon: Unknown instruction: ERROR
```

Obviously here they are more obvious but with errors due to comments and continuations they are less so.

**Comment by ripcurld0** [comment]
@justincormack - I thought it could be easily figured out from the "step x/y" messages unless the --quiet flag is set.

**Comment by justincormack** [comment]
You do not get these on 1.13 if there is a syntax error as we are check
syntax now.

**Comment by ripcurld0** [comment]
#dibs
