### ISSUE TITLE
"docker run" stops while Mac sleeps

### ISSUE THREAD

**Issue by tsuyo** [docker/docker#30028]
**Description**

"docker run" stops entirely while Mac sleeps.

**Steps to reproduce the issue:**
1. docker run --rm -ti centos:latest /bin/bash -c "while :; do date; sleep 1; done"
2. choose Sleep from the Apple () menu on Mac and wait for several seconds
3. come back from Sleep Mode and check the output again

**Describe the results you received:**

Tue Jan 10 16:47:18 UTC 2017
Tue Jan 10 16:47:19 UTC 2017
Tue Jan 10 16:47:20 UTC 2017
Tue Jan 10 16:47:21 UTC 2017
**Tue Jan 10 16:47:22 UTC 2017
Tue Jan 10 16:47:43 UTC 2017** // see the leap
Tue Jan 10 16:47:44 UTC 2017
Tue Jan 10 16:47:45 UTC 2017
Tue Jan 10 16:47:46 UTC 2017
...

**Describe the results you expected:**

Tue Jan 10 16:47:18 UTC 2017
Tue Jan 10 16:47:19 UTC 2017
Tue Jan 10 16:47:20 UTC 2017
Tue Jan 10 16:47:21 UTC 2017
Tue Jan 10 16:47:22 UTC 2017
Tue Jan 10 16:47:23 UTC 2017
Tue Jan 10 16:47:24 UTC 2017
...

**Additional information you deem important (e.g. issue happens only occasionally):**

If you just replace the step 1 into "while :; do date; sleep 1; done" on Mac Terminal (i.e. bash in Mac and *not* within docker container), you can get the expected result above.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 165
Server Version: 1.13.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 238
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.15-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 37GP:IIZF:ZIWU:QUM2:YGH4:WGAE:T7A3:4IUH:SRTS:NUME:QRR3:5N62
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-01-10T16:52:11.960903166Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: kirasoa
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
OS X El Capitan Version 10.11.6
MacBook Pro (Retina, 15-inch, Mid 2015)
```

**Comment by thaJeztah** [comment]
Since this is specific to Docker for Mac; could you reopen this in the Docker for Mac issue tracker? https://github.com/docker/for-mac/issues
