### ISSUE TITLE
Plugin should not have tag in separate field

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#30030]
https://github.com/docker/docker/blob/313502488e8809910127891d8923672baf43a742/api/types/plugin.go#L31 has the `Tag` separated out. We have been slowly undoing this separation to avoid having to parse image references on the client-side.

Having a separate field here is a _massive_ step back. We'll need to deprecate this field.

**Comment by vieux** [comment]
ping @tonistiigi @tiborvass

**Comment by stevvooe** [comment]
@vieux Actually, this looks to have been fixed in master. The search takes me to an old version.

We'll need to update swarmkit to make sure it is doing the right thing.
