### ISSUE TITLE
docker install failed

### ISSUE THREAD

**Issue by loongshaw** [docker/docker#30048]
*****
my linuux server is :

$uname -r
3.10.0-327.ali2000.alios7.x86_64

*****
install docker files:

$rpm -qa | grep docker
docker-engine-selinux-1.12.6-1.el7.centos.noarch
docker-engine-1.12.6-1.el7.centos.x86_64

*****
run output:

$systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2017-01-11 11:26:19 CST; 7min ago
     Docs: https://docs.docker.com
  Process: 20082 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 20082 (code=exited, status=1/FAILURE)

![1](https://cloud.githubusercontent.com/assets/6045592/21834902/ab1cd216-d7f3-11e6-9942-a12dbce7e0ba.png)

**Comment by ZYNCMA** [comment]
> Jan 11 11:26:19 e010125061089.bja dockerd[20082]: time="2017-01-11T11:26:19.928964273+08:00" level=fatal msg="Error starting daemon: Error initializing network controller: Error creating default "bridge" net

It shows that docker daemon failed to create bridge.
Maybe the network segment docker used to create bridge had been used.
Output of `ip r` should be useful.

**Comment by thaJeztah** [comment]
Did you previously have docker running on this host? Note that we don't have official packages for alios 7. It looks like it's based on CentOS / RHEL, but of course there may be differences.

It looks like the error message is truncated; is there anything after ` Error creating default "bridge" net`?

**Comment by loongshaw** [comment]
@thaJeztah , i have consulted the developer of  alios, they replied that install docker on alios should use a internal tool called sigma. i need ask for help from them. thanks.

alios based on CentOS / RHEL, there are a lot of differences. user cannot install docker directly.

**Comment by thaJeztah** [comment]
Thanks @loongshaw. Let me close this issue for now, because I don't think there's something we can do here. But let us know if you were able to resolve the issue 👍
