### ISSUE TITLE
docker for mac always be starting

### ISSUE THREAD

**Issue by leejansq** [docker/docker#30049]
docker for mac always be starting

**Steps to reproduce the issue:**
1. update docker for mac

**Describe the results you expected:**

how to solve the problem? I commited major docke-image to docker for mac

**Output of `docker version`:**

```
Version 1.13.0-rc5-beta35 (14875)
Channel: Beta
25211e84dd
```

**Comment by cpuguy83** [comment]
Can you please give a full explanation?

1. What is the problem?
2. What are you expecting to happen?

Closing for now since there doesn't seem to be any info on even what is being reported, but if you can provide more details we can re-open.
Thanks!

**Comment by leejansq** [comment]
docker for mac could't be started.the status is starting always

**Comment by thaJeztah** [comment]
@leejansq Docker for Mac has a separate issue tracker; https://github.com/docker/for-mac/issues

it may be worth searching for similar issues
