### ISSUE TITLE
docker exec --privileged does not work on ubuntu 16.04 (but works on 14.04)

### ISSUE THREAD

**Issue by ijrandom** [docker/docker#30068]
**Description**
it is possible to use 'docker exec --privileged' on ubuntu 14.04 (as host OS) but on 16.04 process inside a container is still unprivileged.

**Steps to reproduce the issue:**
1. docker run --rm -ti --name nonprivileged ubuntu bash
2. docker exec --privileged nonprivileged hostname privileged

**Describe the results you received:**
hostname reports that you must be a root to do it (hostname syscall fails with EACCESS)

**Describe the results you expected:**
hostname is changed to privileged

**Additional information you deem important (e.g. issue happens only occasionally):**
hostname is only given as an  example of a privileged syscall.
In my case it is also fails with ptrace which is used by a java heap dump utility (jmap). 

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 30
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 30.87 GiB
Name: dshyshkin-thinkpad
ID: OD5W:DTUM:EXXT:62LW:OJ3C:4ART:CHQP:DWQK:TWRD:YSRD:SFSU:X37J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by justincormack** [comment]
It is privileged, but the `seccomp` profile is attached to the container config not the `exec` config, and that stops `ptrace` and various other things. 

See https://github.com/docker/docker/issues/21984

For debugging you can do `docker run -it --privileged --pid=container:name justincormack/nsenter1` which will have the same effect as exec...

**Comment by ijrandom** [comment]
```docker run -it --privileged --pid=container:name ``` works for jmap if you run container with same jdk version. Thank you

**Comment by thaJeztah** [comment]
Looks like there's a workaround for now; i'll close this issue in favor of https://github.com/docker/docker/issues/21984, which is tracking this. Thanks for reporting though!
