### ISSUE TITLE
Unable to start service when not connected to internet

### ISSUE THREAD

**Issue by hipposareevil** [docker/docker#30072]
I tried to create a service from a local image, and it fails when docker is unable to connect to https://registry-1.docker.io. 
I am in an isolated network and won't have access to the internet. When I do have a proxy set up, docker will reach the registry, see my image doesn't exist and then finds it locally.
It'd be great to have way to shortcircuit looking to the registry for images, or have a way to fake out the registry. I know an option is to use a local repository, but that is not possible for our env.

**Steps to reproduce the issue:**
1. Create local image (either docker build or docker load)
2. Start service from image

**Describe the results you received:**
There is no output from 'docker ps' and the logs contain:
`level=error msg="pulling image failed" error="Error: image library/foo.bar.latest not found" module=taskmanager task.id=dvmwc8yl1o3ks2ddcd0hqlgbz
time="2017-01-11T17:48:09.869090677Z" level=error msg="Not continuing with pull after error: Error: image library/foo.bar:latest not found"`

**Describe the results you expected:**

I expected the service to be started.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   19fddc2
 Built:
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.2
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   19fddc2
 Built:
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.12.2
Storage Driver: devicemapper
 Pool Name: docker-8:5-794451-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.989 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.448 GB
 Metadata Space Used: 3.813 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.117-RHEL6 (2016-08-15)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay bridge host null
Swarm: active
 NodeID: 6sv4wgg86v9muy68uxosommmk
 Is Manager: true
 ClusterID: ckp665zitgc2q802sl0hrfp8r
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.0.0.12
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.1.12-61.1.21.el6uek.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.46 GiB
Name: 0-16-3e-33-0-3
ID: ZDRA:QNMO:IAL4:AADX:WZGR:HQW5:A3K5:UG2B:3POC:DRTO:MMC6:HH3F
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM and physical. Seen on redhat and ubuntu.

**Comment by thaJeztah** [comment]
ping @aaronlehmann @nishanttotla  is this still the same in 1.13 after the "pin by digest"?

**Comment by aaronlehmann** [comment]
The service should continue to start after that failure if the image `foo.bar.latest` exists.

Can you confirm that the image exists? Perhaps you meant `foo.bar:latest`?

**Comment by hipposareevil** [comment]
Howdy,
I timed it out after 10 minutes. I will re-try.
"foo.bar.latest" was typo, should've been "foo.bar:latest"

**Comment by hipposareevil** [comment]
apologies. After filing this bug it is now working.

**Comment by hipposareevil** [comment]
I've redone testing on this and am consistently seeing long start times for a service. 
steps:
1- running behind firewall and remove proxy setting
2- verify by doing a "docker pull alpine", which times out (as expected)
3- start a new test service with an already downloaded image:
> docker service create --name test alpine sh -c "sleep 6000"
4- wait for service to come up.

Output from my service creation until it was up:
> docker service create --name test alpine sh -c "sleep 6000"; date
0mkwvbekc4rl25qc1icmpejnj
Fri Jan 27 **07:58:59** PST 2017
>  date; d service ls
Fri Jan 27 07:59:06 PST 2017
ID            NAME  REPLICAS  IMAGE   COMMAND
0mkwvbekc4rl  test  0/1       alpine  sh -c sleep 6000
....
...
> date; docker service ls
Fri Jan 27 **07:59:46** PST 2017
ID            NAME  REPLICAS  IMAGE   COMMAND
0mkwvbekc4rl  test  1/1       alpine  sh -c sleep 6000


question:
Is there a way to disable the checking of registry-1.docker.io for a service?

It takes a long time to come up, even with the image in the local engine.

**Comment by aaronlehmann** [comment]
If you specify an image ID rather than a name, that would avoid connecting to `registry-1.docker.io`.

**Comment by hipposareevil** [comment]
I tried this with the short id and full hash with same results. The engine was still trying to reach docker.io.

> docker service create --name test sha256:88e169ea8f46ff0d0df784b1b254a15ecfaf045aee1856dca1ec242fdd231ddd sh -c "sleep 6000"

> docker service create --name test 88e169ea8f46 sh -c "sleep 6000"

**Comment by aaronlehmann** [comment]
If it happens with long IDs (including the `sha256` prefix), that's a bug. Can you please file an issue for this?

**Comment by aaronlehmann** [comment]
Also, can you confirm you are using Docker 1.13? I see the original bug report was filed against 1.12.2.

**Comment by hipposareevil** [comment]
On 1.13.0 for mac:
- image name used for service, takes about 15 seconds
- short image ID and the service didn't come up
- long image ID and it came up right away, no reaching out to docker.io.

I will retry this on my original linux box with 1.13.

**Comment by nishanttotla** [comment]
@hipposareevil I tested this on my setup, and it seems to be working for me (with both long ids and repodigest). I'm on 1.13.0 on Mac as well. 

@aaronlehmann one thing I noticed with the long image id is that the service starts, but I get the warning
```
$ docker service create --name test1 sha256:88e169ea8f46ff0d0df784b1b254a15ecfaf045aee1856dca1ec242fdd231ddd sh -c "sleep 6000"
unable to pin image sha256:88e169ea8f46ff0d0df784b1b254a15ecfaf045aee1856dca1ec242fdd231ddd to digest: image reference is an image ID
uf1mn5izzeqa17sn6sqayh4ht
```
This is being discussed in #29205 but I think we could suppress the warning in this case (and certain other cases when it can be confusing).

**Comment by aaronlehmann** [comment]
Yes, we should suppress the warning in this case.

**Comment by hipposareevil** [comment]
@aaronlehmann 
I see the long startup time on Ubuntu with 1.12.6.  Should I file a bug against 1.12.6 for this then?

**Comment by aaronlehmann** [comment]
If it behaves properly in 1.13.0, I think a bug report isn't necessary.

**Comment by hipposareevil** [comment]
I will close this out then as 1.13 works.  
thanks for the assistance
