### ISSUE TITLE
Docker app for MacOS not starting up all the way/hangs

### ISSUE THREAD

**Issue by joannbrereton** [docker/docker#30070]
**Steps to reproduce the issue:**
1.  Start docker application (Spotlight, type "Doc", select Docker icon).
2.  Docker icon in upper right shows "Starting"
3.  Never finishes starting.

**Describe the results you expected:**
Expect that eventually Docker will have finished starting and I will be able to docker build, docker run, etc. 

**Additional information you deem important (e.g. issue happens only occasionally):**
Tried rebooting, still hangs.

**Output of `docker version`:**
```
BAM-034083-JB:~ brereton$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64
Error response from daemon: Bad response from Docker engine

```

**Output of `docker info`:**

```
Error response from daemon: Bad response from Docker engine
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac, 

Version of OS/X is 10.10.5

**Comment by justincormack** [comment]
Mac specific issues need to be opened in https://github.com/docker/for-mac/issues and should include a diagnostic code. I am closing this here as this is for engine specific issues.
