### ISSUE TITLE
docker cp not working as documented

### ISSUE THREAD

**Issue by josh-tepper** [docker/docker#30082]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**
The command:
`docker cp containerid:source/path/src_folder_name/ dest/path/dest_folder_name/`

puts the contents of `src_folder_name` in `dest/path/dest_folder_name/src_folder_name` instead of the parent dir `dest/path/dest_folder_name` as documented.  See documentation here:

https://docs.docker.com/engine/reference/commandline/cp/

Both `source/path/src_folder_name/` and `dest/path/dest_folder_name/` exist and are directories.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 52
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 98
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.951 GiB
Name: moby
ID: XEI4:KV5E:QUMI:STWS:2Y2X:MXS2:X5QC:FUHS:Z27W:ZW3I:4ZKO:O4KR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-01-12T00:03:34.814396512Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on Mac OS 10.11.6

**Comment by Jsvcycling** [comment]
This behavior seems consistent with the *nix `cp` command.

**Comment by thaJeztah** [comment]
From the same page; https://docs.docker.com/engine/reference/commandline/cp/

- `DEST_PATH` exists and is a directory
  - `SRC_PATH` does not end with `/`
    the source directory is copied into this directory
  - `SRC_PATH` does end with `/`
    the content of the source directory is copied into this directory

**Comment by thaJeztah** [comment]
Did a quick check;

```bash
$ docker run -d --name mycontainer nginx:alpine
```

A) Without trailing slash; creating the destination directory first

```bash
$ mkdir -p dest
$ docker cp mycontainer:/usr/share/nginx/html dest

$ tree dest
dest
└── html
    ├── 50x.html
    └── index.html

1 directory, 2 files
```

B) Trailing slash on `source`, creating the destination directory first;

```bash
$ mkdir -p dest2
$ docker cp mycontainer:/usr/share/nginx/html/ dest2
$ tree dest2
dest2
└── html
    ├── 50x.html
    └── index.html

1 directory, 2 files
```

C) Trailing slash, but _not_ creating the destination directory first

```bash
$ docker cp mycontainer:/usr/share/nginx/html/ dest3
$ tree dest3
dest3
├── 50x.html
└── index.html

0 directories, 2 files
```

"B" looks to be either incorrect, or the documentation is incorrect

ping @jlhawn could you check? ^^

**Comment by jlhawn** [comment]
Looks like you just misread the documentation. I took a screenshot:

<img width="538" alt="screen shot 2017-01-11 at 6 14 39 pm" src="https://cloud.githubusercontent.com/assets/1441929/21874472/ea8e66cc-d829-11e6-9d94-d9cfebcf86c3.png">


As you can see from the screenshot, the actual line is:

- `SRC_PATH` does [not] end with `/.`

The trailing `.` is *not* punctuation.

Generally, if you specify a directory such as `/path/to/foo` as the `SRC_PATH`, that means *copy this directory in its entirety*. But if you specify it as `/path/to/foo/.` then that extra `.` path component means "copy all of the contents of this directory".

If you modify your case *B)* with this change then I would expect this result:

```
$ mkdir -p dest2
$ docker cp mycontainer:/usr/share/nginx/html/. dest2
$ tree dest2
dest2
├── 50x.html
└── index.html
```

**Comment by josh-tepper** [comment]
@jlhawn You are correct.  I definitely read the `.` as punctuation.  I apologize for the silly issue.

**Comment by jlhawn** [comment]
@josh-tepper no problem! I don't think it's a silly issue, really. I remember back to when I was trying to get the behavior correct to match the *nix `cp` utility. There are actually subtle differences between BSD and GNU copy utilities that I discovered. For example, in Mac OS X's `cp` utility, specifying `path/to/foo/` is the same as specifying `path/to/foo/.`.

Another interesting thing to note is that, on most systems, the trailing `/` means to dereference a symlink if the last component is a symlink, e.g.: if `/path/to/foolink` is a symbolic link, then `cp -a /path/to/foolink /dest/foolink` copies *the symlink* and not the symlink target, however `cp -a /path/to/foolink/ /dest/foo` resolves the symlink and copies its target!

**Comment by thaJeztah** [comment]
Oh! Yes, I definitely overlooked it, I was aware of differences between trailing slash or not, but missed the dot. 👍

**Comment by ijc25** [comment]
Would ending the list items with some actual punctuation (":" looks like it would be appropriate in the context) make this clearer do you think?

i.e. 

* `DEST_PATH` exists and is a directory:
   * `SRC_PATH` does not end with `/.`:
        the source directory is copied into this directory
    * `SRC_PATH` does end with `/.`:
        the _content_ of the source directory is copied into this directory

or/and perhaps just spelling it out, literally saying:

... end with `/.` (that is: _slash_ followed by _dot_)

?

**Comment by thaJeztah** [comment]
I think spelling it out literally takes away any confusion, so would have my preference (even if it is verbose).

**Comment by ijc25** [comment]
@thaJeztah I'd offer to make a PR but I'm unsure which of `docs/reference/commandline/cp.md` and/or `man/src/container/cp.md` I should change.

**Comment by thaJeztah** [comment]
@ijc25 they may both have to be updated; I think the plan is to use a single source (and use the man pages), but the man pages currently lack a lot of information that is present in the "reference" docs, so  please update both :)

**Comment by josh-tepper** [comment]
Thanks for the fix @ijc25.

There's one other ambiguity in the documentation/implementation that I've come across.  @jlhawn - Maybe you can confirm the behavior/whether I should open another new github issue:  When I run:
```
docker --follow-link container_id:source/path dest/path
```
I would expect that when `source/path/` contains files that are symlinked, e.g. `source/path/file.symlink`, and subdirectories that are symlinked, e.g., `souce/path/dir.symlink/more_files`, that all of those would be resolved, and that I would get the files at `dest/path`.  This is not the case.  Instead I end up with broken symlinks.

My best guess is that `--follow-link` refers to links that are in `source/path/` itself, e.g., `souce.symlink/path/`, but I haven't tested that.  Even so, that doesn't really make so much sense for me as a feature.  This is because as @jlhawn pointed out above, there is already a *nix cp notion as to whether to resolve symlinks at the end of path (based on the trailing `/`), and it seems that symlinks in the middle of a path should always be resolved.

Let me know if this is also confusing to you guys -- if so I'll open a new issue.

**Comment by seocliffdev** [comment]
It doesn't work if you have not installed the latest version. I was using podman-docker and it didn't have `docker cp` command. However, `docker-ce` package has `docker cp` command
