### ISSUE TITLE
docker stats "NET I/O" metric has a max value(4GB a little more), which cause the value of metric not correct.

### ISSUE THREAD

**Issue by KevinTHU** [docker/docker#30089]
**Description**
I have a container which is network-Intensive, perhaps 10MB/s, then I use command `docker stats` to monitor the network flow, I found the value of 'NET I/O' is not quite right, and wait for some time, I know the reason, that when the value of 'NET I/O' reaches a max value(4GB a little more), the value will return to count from zero.

**Steps to reproduce the issue:**
1.start a container, run the command `docker stats` for it.
2.download some big file from net
3.watch the value of 'NET I/O' in the output of `docker stats`

**Describe the results you received:**
when the value of 'NET I/O' reaches a max value(4GB a little more), the value will return to count from zero.

**Describe the results you expected:**
the result above will not happen, and the value increases correctly and consecutively

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 4
 Paused: 0
 Stopped: 11
Images: 189
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 171.2 GB
 Data Space Total: 1.1 TB
 Data Space Available: 928.3 GB
 Metadata Space Used: 41.63 MB
 Metadata Space Total: 10.74 GB
 Metadata Space Available: 10.7 GB
 Thin Pool Minimum Free Space: 110 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host vlcp
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.6 GiB
Name: kvm-yz-dev-073-003-004
ID: CED3:DJX6:VW6I:LJLX:CEVJ:Z4L2:FYPX:KTIQ:CTO2:4JRD:U7L3:WN4L
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 70
 Goroutines: 107
 System Time: 2017-01-12T14:12:29.65455978+08:00
 EventsListeners: 3
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Cluster Store: zk://100.73.3.4:2181,100.73.3.5:2181,100.73.3.6:2181
Cluster Advertise: 100.73.3.4:2375
Insecure Registries:
 jdocker.me
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical, swarm cluster

**Comment by KevinTHU** [comment]
I read the docker code, find the network statistics value is got from "libnetwork/osl/interface_linx.go func (i *nwIface) Statistics()", and then "vishvananda/netlink/link_linx.go"， I think some max limit was set in the package vishvananda/netlink

**Comment by thaJeztah** [comment]
Sounds like 32-bit is used for something

**Comment by KevinTHU** [comment]
@thaJeztah perhaps it is, when I have time, I will trace it, or some one have time to do it.

**Comment by justincormack** [comment]
Some of us old timers remember when Linux network interfaces used to do this...

**Comment by KevinTHU** [comment]
@justincormack I found the key code is in `vishvananda/netlink/link_linx.go execGetLink(req *nl.NetlinkRequest)`, this method will get the value through `req.Execute(syscall.NETLINK_ROUTE, 0)`, and parse it by `linkDeserialize(msgs[0])`, in the method `linkDeserialize(msgs[0])`, we can find out there is a case `case syscall.IFLA_STATS:` for network stats, which has call `parseLinkStats `method, in this method, the []byte data was transfer to `LinkStatistics`, the bug is just in `LinkStatistics`, all attributes in it is Uint32, so I fix it with a PR, maybe can fix our docker bug. reference:[https://github.com/vishvananda/netlink/pull/189](url), likely it's CI test is not quite right, so the code is not build correctly, just wait for their comment.

**Comment by aboch** [comment]
@KevinTHU Now that the netlink change was merged, you should be able to fix this issue by updating the import of vishvananda/netlink to latest, in vendor.conf.

No need to update the libnetwork code, the removal of the unnecessary uint64 casting can be done later, IMO.

**Comment by KevinTHU** [comment]
@aboch Thx a lot~I will try it later.
@justincormack @thaJeztah The commit version of vendor need to be updated for this bug, PTAL

**Comment by antime** [comment]
I meet it,too! and the version is 1.12.3

**Comment by waltcow** [comment]
This bug can be still  reproduced  in `Version: 17.03.1-ce`

docker info 

```
Containers: 18
 Running: 13
 Paused: 0
 Stopped: 5
Images: 45
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 74
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-103-generic
Operating System: Ubuntu 14.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: iZt4nixe052l3d35h81fj0Z
ID: MC75:PUKJ:54X7:ITIT:SCJT:KNMM:3WT2:WEFH:M5F4:I6NM:JFAY:4TB4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by aboch** [comment]
Yes the fix will be in docker 17.04

**Comment by antime** [comment]
when it will be fixed

**Comment by aboch** [comment]
https://github.com/docker/docker/releases
