### ISSUE TITLE
WORKDIR causes docker build to not use cache

### ISSUE THREAD

**Issue by ChristopherBiscardi** [docker/docker#30081]
**Description**

`WORKDIR` in a Dockerfile causes `docker build -t t .` to not cache layers.

**Steps to reproduce the issue:**
1. Use the following Dockerfile
```dockerfile
FROM alpine

WORKDIR /opt/whatever

RUN sleep 5s

CMD ["echo", "stuff"]
```

2. run `docker build -t t .`
3. run `docker build -t t .` again. Observe that there was no caching used.

**Describe the results you received:**

The results of two consecutive builds results in no caching in the second build:

```shell
 λ docker build -t t .
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM alpine
 ---> 88e169ea8f46
Step 2/4 : WORKDIR /opt/whatever
 ---> ab24c914f7ad
Removing intermediate container f5e5d62d8476
Step 3/4 : RUN sleep 5s
 ---> Running in 5f63d943d5f1
 ---> cdf23a3419c7
Removing intermediate container 5f63d943d5f1
Step 4/4 : CMD echo stuff
 ---> Running in 938cad195763
 ---> 71e2b1215dc4
Removing intermediate container 938cad195763
Successfully built 71e2b1215dc4
 λ docker build -t t .
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM alpine
 ---> 88e169ea8f46
Step 2/4 : WORKDIR /opt/whatever
 ---> 608d9e2b6d66
Removing intermediate container 85b77e27cd63
Step 3/4 : RUN sleep 5s
 ---> Running in 5109be334f42
 ---> bfbd8ab7ca7d
Removing intermediate container 5109be334f42
Step 4/4 : CMD echo stuff
 ---> Running in 86c5dbb64f66
 ---> 508ed4147f5b
Removing intermediate container 86c5dbb64f66
Successfully built 508ed4147f5b
```

**Describe the results you expected:**

All layers should be cached when building the second time.

**Additional information you deem important (e.g. issue happens only occasionally):**

Issue seems to be related to `WORKDIR`

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 03:07:30 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 61
Server Version: 1.13.0-rc5
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.8.15-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: A3C4:SQBJ:CPK5:UGNZ:6CKX:WFZ2:SRNA:JDFV:HC3Y:A2GP:S5RY:TJ5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-01-12T00:03:28.636038728Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for Mac
Version 1.13.0-rc5-beta35 (14875)
Channel: Beta
25211e84dd

**Comment by astropuffin** [comment]
I'm experiencing the same thing... :(
```
> cat Dockerfile 
FROM ubuntu:16.04
RUN echo "This is cached"
WORKDIR /var
RUN echo "This is not cached"
> docker build -t tmp .
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM ubuntu:16.04
 ---> 104bec311bcd
Step 2/4 : RUN echo "This is cached"
 ---> Running in 1d8006f2eaf8
This is cached
 ---> bffd0f37d2ea
Removing intermediate container 1d8006f2eaf8
Step 3/4 : WORKDIR /var
 ---> 6e353d93970a
Removing intermediate container 143b88dacfe9
Step 4/4 : RUN echo "This is not cached"
 ---> Running in d4247e2fbde7
This is not cached
 ---> 869fb264cd35
Removing intermediate container d4247e2fbde7
Successfully built 869fb264cd35
> docker build -t tmp .
Sending build context to Docker daemon 2.048 kB
Step 1/4 : FROM ubuntu:16.04
 ---> 104bec311bcd
Step 2/4 : RUN echo "This is cached"
 ---> Using cache
 ---> bffd0f37d2ea
Step 3/4 : WORKDIR /var
 ---> 6e002118d267
Removing intermediate container 7e171c3676ef
Step 4/4 : RUN echo "This is not cached"
 ---> Running in ff350e49d245
This is not cached
 ---> 89be445ec3be
Removing intermediate container ff350e49d245
Successfully built 89be445ec3be
```
Docker for mac:
```
Version 1.13.0-rc5-beta35 (14875)
Channel: Beta
25211e84dd
```

**Comment by FrenchBen** [comment]
Patch is in: https://github.com/docker/docker/pull/29956

**Comment by thaJeztah** [comment]
Yup, this is fixed in 1.13.0-rc6, which is available now

Thanks for reporting @ChristopherBiscardi! I'll close this one, but ping me if you're still seeing this on rc6

**Comment by nahuelmyob** [comment]
I think this is still happening in Docker version 17.06.0-ce, build 02c1d87 (Mac)

**Comment by arjunsss** [comment]
I seem to be seeing the same issue with Version 17.09.1-ce-mac42 (21090)

**Comment by thaJeztah** [comment]
@arjunsss can you open a new issue with reproduction steps? It's possible that it has a different cause

**Comment by arjunsss** [comment]
I've been noticing that it doesn't use the cache sporadically. It may be unrelated to WORKDIR. I'll open a new issue if I can isolate repro.

**Comment by juanjoDiaz** [comment]
Using `Version 17.12.0-ce-mac49 (21995)` (Channel: stable, f50f37646d) I can reproduce this consistently.

Wherever I place a `WORKDIR` the cache stop working.

**Comment by thaJeztah** [comment]
@juanjoDiaz not able to reproduce on Ubuntu (17.12), or Docker for Mac 18.02;

```bash
docker build -t repro-30081 -<<EOF
FROM alpine

WORKDIR /opt/whatever

RUN sleep 5s

CMD ["echo", "stuff"]
EOF
```

First run:

```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM alpine
 ---> 053cde6e8953
Step 2/4 : WORKDIR /opt/whatever
Removing intermediate container 9fdd01b76bbd
 ---> dafe61a887a7
Step 3/4 : RUN sleep 5s
 ---> Running in 22344a139bc4
Removing intermediate container 22344a139bc4
 ---> 9659215259ca
Step 4/4 : CMD ["echo", "stuff"]
 ---> Running in c532c4763c9c
Removing intermediate container c532c4763c9c
 ---> ab4052893771
Successfully built ab4052893771
Successfully tagged repro-30081:latest
```

Second run:

```
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM alpine
 ---> 053cde6e8953
Step 2/4 : WORKDIR /opt/whatever
 ---> Using cache
 ---> dafe61a887a7
Step 3/4 : RUN sleep 5s
 ---> Using cache
 ---> 9659215259ca
Step 4/4 : CMD ["echo", "stuff"]
 ---> Using cache
 ---> ab4052893771
Successfully built ab4052893771
Successfully tagged repro-30081:latest
```

If you are able to reproduce with those steps, could you open a new issue with details?

**Comment by nilpunning** [comment]
I too was not able to reproduce the problem with the simple `WORKDIR /opt/whatever` example, but with a more complicated Dockerfile the cache was invalidated when running a WORKDIR command.  A work around was to add a `RUN mkdir /opt/whatever` before the `WORKDIR /opt/whatever`.  No idea why that worked.

```
docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.10
 Git commit:	0520e24302
 Built:	Fri Mar 23 01:47:41 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.10
  Git commit:	0520e24302
  Built:	Fri Mar 23 01:48:12 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

**Comment by thaJeztah** [comment]
@nilpunning if you're able to provide a minimum Dockerfile / example to reproduce, please open a new issue with details so that it can be looked into

**Comment by FernandoMiguel** [comment]
I'm seeing cache invalidation for WORKINGDIR  if the next layer is a `COPY .`
```
Step 3/19 : WORKDIR /src
 ---> Using cache
 ---> 74042b465320
Step 4/19 : COPY . /src
```

while if I copy a file, it is cached

```
Step 13/19 : WORKDIR /src
 ---> Using cache
 ---> 6306ffcebc8c
Step 14/19 : COPY --from=node-builder-ms /src/package.json /src/package.json
 ---> Using cache
```

**Comment by thaJeztah** [comment]
@FernandoMiguel did you add your Dockerfile to `.dockerignore` ? Otherwise it's probably because the Dockerfile was modified, so the cache for `.` being invalidated

**Comment by FernandoMiguel** [comment]
@thaJeztah yeah, `/dockerfile` (entire folder with multiple Dockerfiles inside) is on .dockerignore
last night rewrote most of our Dockerfile and moved `WORKDIR` to a much later stage. and now I got cache as expected.
so much so, that I had to cache bust some inbetween layers as they were caching other docker images ahah

**Comment by thaJeztah** [comment]
@FernandoMiguel if you have a minimal case that reproduces on the current version of Docker, could you open a new issue for that?

Also; if you're on Docker 18.06 or up, I highly recommend trying the new buildkit builder (set the environment variable  `DOCKER_BUILDKIT=1`); buildkit has many improvements to caching, and much smarter when building multi-stage dockerfiles (resulting in builds that may be twice as fast or even more); here's a recent presentation showing it; https://drive.google.com/drive/folders/1QPP_p6VdeSfakYQpZtu-rPT6oFHMSN6r?usp=sharing

**Comment by FernandoMiguel** [comment]
thanks for the tip. will rebuild with it enable to see if it gets better for our use case.
when i'm back to work  i'll try to get you one of our dockerfiles

**Comment by kgoryunov** [comment]
![image](https://user-images.githubusercontent.com/48957843/67087050-ceeec680-f1aa-11e9-8f88-b53ac3c8155a.png)
It looks like I'm having something similar to the original issue.
The first output is from CircleCI running docker 17.09.0-ce from docker-compose.
The second output is from CircleCI running docker 17.09.0-ce from docker build command. 
And the third one is from my local setup with docker 19.03.3-ce where I'm trying to reproduce it with docker build command.

**Comment by FernandoMiguel** [comment]
@kgoryunov 17.09 is rather old by now :s 

as someone who was affected by this before, I rewrote the Dockerfile to place WORKDIR at the bottom of the build, and it fixed it.
a later release no longer had this issue , for us

**Comment by thaJeztah** [comment]
Current versions of `docker-compose` and `docker build` in many (or all) cases will not share the build cache, or at least not produce the same digest. The reason for that is that when sending the build context with `docker-compose`, it will use a slightly different compression (`docker-compose` is written in Python, whereas the `docker cli` is written in Go). There may other differences due to them being a different implementation (and language).

The next release of docker compose will have an (currently opt-in) feature to make it use the actual `docker` cli to perform the build (by setting a `COMPOSE_DOCKER_CLI_BUILD=1` environment variable). This was implemented in https://github.com/docker/compose/pull/6865

With that feature, docker compose can also use BuildKit for building images (setting the `DOCKER_BUILDKIT=1` environment variable). I would _highly_ recommend using buildkit for your builds if possible. When using BuildKit (requires Docker 18.09 or up, and at this point is not supported for building Windows containers), you will see a _huge_ improvement in build-speed, and the duration taken to send the build-context to the daemon in repeated builds (buildkit uses an interactive session to send only those files that are needed during build, instead of uploading the entire build context).

As @FernandoMiguel mentioned; Docker 17.09 is indeed very old, and **should not be used** as it reached EOL a long time ago, is no longer maintained, and has known, unpatched vulnerabilities, some of which are _critical_.

Quite likely, the `WORKDIR` issue may also be resolved in newer versions of Docker.
