### ISSUE TITLE
additive build context

### ISSUE THREAD

**Issue by justincormack** [docker/docker#30101]
I commented on this in https://github.com/docker/docker/pull/29405#issuecomment-270971356 and below, so making an issue.

Docker build needs to accept multiple arguments to create the context, it should be modelled after eg `go build` not `git`, ie
```
docker build file1 file2 directory ...
```
This means you can construct a context additively, rather than having to use a .`dockerignore` file to remove parts of the context. This is especially useful if you have two Dockerfiles in the same directory that use different contexts. Currently I emulate this behaviour in every single build I do by using
```
tar cf - file1 file2 directory ... | docker build -
```
But that is much more limiting, eg you cannot use with compose, you need tar which is not on Windows etc. This change is very simple and easy to understand, and is a big improvement.

As a future enhancement, add some more `tar` features, especially dereference symlinks (frequently requested) and `-C` to change directories.

**Comment by tonistiigi** [comment]
First, `docker build foo` and `tar cf - foo | docker build -` are not equivalent.

I really would like to keep build as self contained as possible, I think it is a very important and if you can't put together a more complicated build flow that is still self-contained, we have done bad design decisions. Of course we have made exceptions to it in the past and `--ignore-file` has the same problem(and makes way less sense than this) so it is quite unfair to bring it up now.

There have been discussions about lazy context loading. Hopefully we can start working on it soon. In most cases people should not worry about ignore files then.

This does seem to be only solution if we want to solve symlink dereference. But need to figure out the syntax conflict first.

**Comment by justincormack** [comment]
@tonistiigi I know they are not exactly equivalent, but they are close enough for my use cases.

I am not sure that control of context is exclusive with a default that works for most use cases, we could have both.

**Comment by tonistiigi** [comment]
@justincormack I'm not sure what solution you are suggesting for the conflict with the current syntax.

So to be clear
`docker build foo` == `tar cf - -C foo . | docker build -` 
Suggested in this issue:
`docker build file1 file2 directory` == `tar cf - file1 file2 directory | docker build -`

I like this if we can figure out the syntax conflict but I don't think it makes sense if it would do `tar cf - -C file1 . -C ../file2 . -C ../directory . | docker build -`. Are you suggesting a different behavior depending if there are 1 or more arguments(or first arg is special?). With this merge behavior this isn't useful for lots of cases, doesn't solve the symlink problem and makes lazy context loading inefficient as everything needs to be scanned when a subdir of a context is requested.

**Comment by justincormack** [comment]
No, it would not do the `-C`, it would just add the specified files at their paths, so

```
docker build a/b/c d e/f
```
would have `a/ a/b/ a/b/c d e/ e/f` in the context, ie the paths as specified just as `tar` would create them.

I suggested `-C` support as an enhancement, but its pretty unusual to need it, but it would be explicit if supported eg
```
docker build -C a/b c -C .. d -C e f
```
would add `c d f` to the context.

I use this pretty rarely and could avoid.

**Comment by tonistiigi** [comment]
@justincormack Repeating my question: Are you suggesting a different behavior depending if there are 1 or more arguments(or first arg is special?) . I don't like `-C` either but that is the current behavior for single arg.

**Comment by justincormack** [comment]
Oh, sorry, I misunderstood.

Oh if thats the current behaviour, then ugh, there is no way to make it usable. It can't be different for the first arg, or if >1 arg.

**Comment by tonistiigi** [comment]
@justincormack Discussed this with @thaJeztah last week. What do you think about `docker build -v /local/path:/path/in/context base-context` (probably mount syntax instead) that could be used to overwrite locations in context before pushing it up.
