### ISSUE TITLE
Volume file changes are not detected in container on Windows 10 host

### ISSUE THREAD

**Issue by micdahl** [docker/docker#30105]
**Description**
Using docker for developing an Angular CLI app, running via `ng serve` inside the container does not detect file changes made on the host in a volume. Therfore I have to restart docker run everytime I made changes to files. Timestamp and content of the files though are updated in the container. So alternative I can use touch <filename> inside the container to rebuild but this is not really a satisfying development flow as I have to do this for every changed file.

**Steps to reproduce the issue:**
1. Run `docker build` for the Dockerfile given below
2. Start container with a volume pointing to a directory on the host
3. Run `ng init` inside of the container
4. Run `npm start` inside of the container
5. Edit and save src files on the host

**Describe the results you received:**
Edited file and timestamp change inside of the container, but ng build process is not restarted,

**Describe the results you expected:**
Edited file and timestamp change inside of the container and ng build process gets restarted,

**Additional information you deem important (e.g. issue happens only occasionally):**
Thought first, this was a  [docker-compose issue](https://github.com/docker/compose/issues/4326) but running the container without compose had the same results.

**Output of `docker version`:**

```
    Client:
    Version: 1.12.6
    API version: 1.24
    Go version: go1.6.4
    Git commit: 78d1802
    Built: Wed Jan 11 00:23:16 2017
    OS/Arch: windows/amd64

    Server:
    Version: 1.12.6
    API version: 1.24
    Go version: go1.6.4
    Git commit: 78d1802
    Built: Wed Jan 11 00:23:16 2017
    OS/Arch: linux/amd64
```

**Output of `docker info`:**

```
Containers: 68
Running: 0
Paused: 0
Stopped: 68
Images: 176
Server Version: 1.12.6
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 265
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.919 GiB
Name: moby
ID: YYNX:753B:ZI7R:HAY4:EVAG:WBK2:RD6P:YS7Y:Z67V:3SY3:JFUL:PLDQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
File Descriptors: 13
Goroutines: 23
System Time: 2017-01-12T15:08:14.0497198Z
EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
127.0.0.0/8
```

**Dockerfile**
```
    FROM node:latest

    RUN apt-get update && apt-get install -y xvfb chromium
    RUN npm install -g angular-cli

    ENV APP_HOME /usr/src/app

    RUN mkdir -p $APP_HOME

    WORKDIR $APP_HOME

    EXPOSE 4200

    CMD ["npm", "start"]
```

**Comment by friism** [comment]
This is a known limitation of Docker for Windows: https://docs.docker.com/docker-for-windows/troubleshoot/#/inotify-on-shared-drives-does-not-work

As a workaround, you can probably use polling: https://www.npmjs.com/package/onchange#poll---p----poll-

**Comment by thaJeztah** [comment]
Let me close this issue; a more in-depth discussion about this can be found in the docker for windows issue tracker (I noticed you were already redirected from the docker compose issue tracker, apologies for that :smile:); see here for that discussion https://github.com/docker/for-win/issues/56

Thanks for reporting though, and feel free to comment here after I closed 👍

**Comment by micdahl** [comment]
@friism Thank you for the advice with polling.
For those who are getting into the same troubles: To achieve this with angular-cli, 
`"poll": 1000` has to be inserted into the `defaults`-object in angular-cli.json. Unfortunately, this is not well documented.

**Comment by JonathanStoye** [comment]
FYI to whom it may concern: had a similar issue on macOS 10.14 on a MacBook Pro (15-inch, 2018) with Docker Desktop Community Version 2.0.0.0-mac81 (29211)

File changes were not detected anymore at some point even though it worked for quite some time. Seems like the docker engine was unhealthy and restarting the engine worked fine. After more testing it seems like the docker engine does not like sleep modus that much.

**Comment by dimitriy-k** [comment]
@JonathanStoye how did you fixed it? I have the same situation, wrapped angular-cli in docker, but it is not rebuilding after file changes.

Have you added `poll: 1000` to angular.json or just restarted docker? I have restarted docker, but it did not helpt

**Comment by JonathanStoye** [comment]
As I said I just restarted the docker engine and then it was fine again. In my case it was just the standby of Mac OS that seemed to cause troubles with docker

**Comment by francescobianco** [comment]
@micdahl @friism @thaJeztah @JonathanStoye @dimitriy-k My solution is create a clone of INOTIFYWAIT full bash based on polling using a diff screenshot of filesystem, please take a look and support it work perfect on WINDOWS systems
https://github.com/javanile/inotifywait-polling

**Comment by hayreddintuzel** [comment]
thanks @JonathanStoye

**Comment by madacol** [comment]
This has been solved in the new stable release of `Docker Desktop Community 2.2.0.0`

https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2200

> Docker Desktop now supports inotify events on shared filesystems.

**Comment by joelharkes** [comment]
Just upgraded to docker 2.2, currently having issues that changes are no longer detected..

**Comment by thaJeztah** [comment]
There were some regressions in the Docker Desktop 2.2 release. I don't have a direct link to specific issues at hand, but they should be present in https://github.com/docker/for-win/issues

This issue is specific to Docker for Windows / Docker Desktop (not something that can be addressed in this repository)
