### ISSUE TITLE
API Endpoint GET /containers/redis1/stats Hangs

### ISSUE THREAD

**Issue by afrazkhan** [docker/docker#30124]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Sendging a GET to the endpoint `/containers/[CONTAINER_ID OR NAME]/stats` never gets a response (hangs).

**Steps to reproduce the issue:**
Send a call like `GET /containers/[CONTAINER_NAME or ID]/stats`

Also tested with the raw socket:
```
curl --unix-socket /var/run/docker.sock http://localhost/containers/[CONTAINER_ID]/stats
```

**Describe the results you received:**
Docker daemon logs show:
```
level=debug msg="Calling GET /containers/f32f765cf23c1e56900460807f7c482aa988d37648e28d50875151322df6885f/stats"
```
So the request is received, but never gets a response.

**Describe the results you expected:**
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.24/#/get-container-stats-based-on-resource-usage

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 15
 Running: 3
 Paused: 0
 Stopped: 12
Images: 162
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 420
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: active
 NodeID: 4oh2xqqiexi4rk8julf5o9rj6
 Is Manager: true
 ClusterID: a6h0antslmorusyo7dx1z3fph
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: 4TDG:QGRX:JGMX:TP4V:KZQ4:W2A4:DY4X:SYQY:E7PK:KNTI:WS77:IAYI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 176
 System Time: 2017-01-13T10:50:53.415533429Z
 EventsListeners: 4
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 0.0.0.0:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Tested on Mac only.

**Comment by cpuguy83** [comment]
Can you provide more details?
The CLI uses this API endpoint to get stats.

Is that the right syntax for curl with unix socket?
Thought the url should just be `http:/<path>`

**Comment by thaJeztah** [comment]
> Is that the right syntax for curl with unix socket? Thought the url should just be `http:/<path>`

The syntax differs between cURL 7.40 and 7.50; https://github.com/docker/docker/blob/1.12.x/docs/reference/api/docker_remote_api.md;

To connect to the Docker daemon with cURL you need to use cURL 7.40 or
later, as these versions have the `--unix-socket` flag available. To
run `curl` against the daemon on the default socket, use the
following:

When using cUrl 7.50 or later:

```console
$ curl --unix-socket /var/run/docker.sock http://localhost/containers/json
```

When using cURL 7.40, `localhost` must be omitted:

```console
$ curl --unix-socket /var/run/docker.sock http://containers/json
```

If you have bound the Docker daemon to a different socket path or TCP
port, you would reference that in your cURL rather than the
default.

The current version of the API is v1.24 which means calling `/info` is the same
as calling `/v1.24/info`. To call an older version of the API use
`/v1.23/info`. If a newer daemon is installed, new properties may be returned
even when calling older versions of the API.

**Comment by afrazkhan** [comment]
I can confirm that it's the right syntax, as @thaJeztah says. It works for other endpoints. I also finally tested it on a real server on the actual production network, and it also hung there.

Strange thing is that I've come home and it's started working on my laptop (where I was originally testing it). Logged into AWS, and it's now working there too.

I'm still clueless as to what happened, but I'm betting on the side of a brain-fart, so I'm closing this report. I'll re-open if it turns out it _was_ something non-idiotic.
