### ISSUE TITLE
Allow memory setting to be specified in percentage of the host

### ISSUE THREAD

**Issue by nschoe** [docker/docker#30126]
Currently, we can constraint a container's memory usage with the `-m, `--memory` setting.
So we can constraint a container to use 1Gb of memory with `--memory=1G`.

The thing is: I have much less memory on my computer that I have on my server, and during my tests, I was trying to allow specifying the memory limit in term of percentage of the host's total memory, like `--memory=10%`

So I'm asking you: does it seem like a plausible use-case for you?

**Comment by justincormack** [comment]
What would be the use case? If your program only needs 10% of your laptop's memory, then give it that anywhere and run more programs on your server... If it benefits from lots of cache, then probably running it without a memory constraint is ok.

The underlying interface allocates memory sizes directly, so this maps to that fairly directly. Servers may have hotplug memory or ballooning etc, so even a percentage might not be that useful.

**Comment by nschoe** [comment]
Okay I see your point, I was "afraid" that something like this might be true.
It's just that the software doesn't need to same amount of memory when it's in testing mode or in production mode, reading to server thousands of clients.

But yes I see, it would not make much sense to have this settings. Thanks.
Shall I close?

**Comment by justincormack** [comment]
Ah yes, that is more difficult to handle. I have a feeling it may in some cases be better to limit the number of connections and memory use of each container to a lower level, and scale up to more containers for the service for this kind of case. This is easy to do if you use swarm mode, as you can just scale up to many smaller containers. Then you run them at the same size.

Its annoyingly hard to write software with known memory usage though...

**Comment by nschoe** [comment]
Indeed!
Thanks for the answers!
