### ISSUE TITLE
Update volume plugin APIs docs

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#30149]
https://docs.docker.com/engine/extend/plugins_volume needs to be updated for pluginv2. In pluginv2, plugins are containerized. As a result, the mount paths are relative to the container, not the host.

All instances where we refer to "path to directory on host" should be updated. For example, VolumeDriver.Mount's response in pluginv2 would be:

Response: json { "Mountpoint": "/path/to/directory/on/plugin", "Err": "" } 

cc @tiborvass @cpuguy83  @thaJeztah

**Comment by anusha-ragunathan** [comment]
Misty, would you be able to work on this? TIA!

**Comment by mstanleyjones** [comment]
I'll get to it as soon as I can. It didn't get in in time for 1.13.0.

**Comment by anusha-ragunathan** [comment]
That would be great!

**Comment by thaJeztah** [comment]
addressed by https://github.com/docker/docker/issues/30524
