### ISSUE TITLE
Unable to mount a volume on Windows container using volume plugin on Windows.

### ISSUE THREAD

**Issue by datarashutosh** [docker/docker#30148]
**Description**
==========
I am using docker 1.13.0-rc4 & I created a volume using a volume plugin on Windows.
The plugin returns absolute mount path of the volume when VolumeDriver.Mount is called. e.g. C:\testmount\vol1
When I tried running a container by attaching the volume I created, it gave errors.

**Steps to reproduce the issue:**
=====================
1.	Created a docker volume using “docker volume create –d <plugin> vol1” – SUCCESS.
2.	Tried running a container with this volume: “docker run -it --rm -v vol1:c:\vol1 microsoft/windowsservercore cmd”
3.	Docker called plugin’s “VolumeDriver.Mount” implementation. A volume was presented to the host using iSCSI channel and an access path is assigned (C:\ProgramData\Volumes\vol1). This path was then returned back to the docker.
json { "Mountpoint": C:\ProgramData\Volumes\vol1", "Err": "" }
4.	Running a container failed with following error (as found in event logs as well as printed on the console) and triggered VolumeDriver.Unmount immediately.
Create container failed with error: container 16c781026b7e570d4c0f9f294b99d103c603492ebb7a1341ceceb87064fa2b1b encountered an error during CreateContainer: failure in a Windows system call: The filename, directory name, or volume label syntax is incorrect. (0x7b) extra info: {"SystemType":"Container","Name":"16c781026b7e570d4c0f9f294b99d103c603492ebb7a1341ceceb87064fa2b1b","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{be4691ac-d76d-11e6-836f-a178e8f260bb}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\\docker\\windowsfilter\\16c781026b7e570d4c0f9f294b99d103c603492ebb7a1341ceceb87064fa2b1b","Layers":[{"ID":"863df56d-1ee0-54d6-b56c-3ecb83f103ce","Path":"C:\\ProgramData\\docker\\windowsfilter\\4deba93ab1b3ca796b719f7a450235d3a666e3964739a733274412f4a1d4c533"},{"ID":"9450c7b4-201b-5208-90ae-1d5a2878944f","Path":"C:\\ProgramData\\docker\\windowsfilter\\1f959e52bd30c0c3306812fe320543a3c64a7a423a6cafe9ad6baad79cc58120"}],"HostName":"16c781026b7e","MappedDirectories":[{"HostPath":"\\C:\\ProgramData\\Volumes\\vol1","ContainerPath":"c:\\vol1","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0}],"HvPartition":false,"EndpointList":["80d38bec-7626-4f3f-8ed7-a2fa208193f4"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}

5.	Please Note that docker added a leading slash “\” to the mount point returned by the plugin. 
6.	This is different than the behavior observed earlier (during September 2016 timeframe with 1.13 bits).
7.	On further research & some guesswork, I figured docker is now expecting the relative path (relative to the filesystem root, C:\) for the mount point. E.g. Just this – “ProgramData\Volumes\vol1”).
8.	To quick test: Here is what I did-
a.	Created an empty directory C:\ProgramData\Volumes\vol1”. Please Note that this is not an access path added to the volume but just an empty directory created directly on the host FS.
b.	Returned “ProgramData\Volumes\vol1” as mount point from the plugin when VolumeDriver.Mount was called.
json { "Mountpoint": ProgramData\Volumes\vol1", "Err": "" }
c.	Docker successfully mounted the directory inside the container.
9.	However, this change is also not completely working.
a.	Instead of creating the directory locally, I actually mounted a volume over iSCSI to the host and returned the relative path back as mount point: “ProgramData\Volumes\vol1”.
b.	This was expected to work based on my experience in step 8 above but this failed with following error:
C:\Program Files\Docker\docker.exe: Error response from daemon: container d5f392bb480747451b191eb84abc37376890b622629e7f290bbcca8467d2121e encountered an error during CreateContainer: failure in a Windows system call: The filename or extension is too long. (0xce) extra info: {"SystemType":"Container","Name":"d5f392bb480747451b191eb84abc37376890b622629e7f290bbcca8467d2121e","Owner":"docker","IsDummy":false,"VolumePath":"\\\\?\\Volume{be46933e-d76d-11e6-836f-f6b74750e915}","IgnoreFlushesDuringBoot":true,"LayerFolderPath":"C:\\ProgramData\
\docker\\windowsfilter\\d5f392bb480747451b191eb84abc37376890b622629e7f290bbcca8467d2121e","Layers":[{"ID":"863df56d-1ee0-54d6-b56c-3ecb83f103ce","Path":"C:\\ProgramData\\docker\\windowsfilter\\4deba93ab1b3ca796b719f7a450235d3a666e3964739a733274412f4a1d4c533"},{"ID":"9450
c7b4-201b-5208-90ae-1d5a2878944f","Path":"C:\\ProgramData\\docker\\windowsfilter\\1f959e52bd30c0c3306812fe320543a3c64a7a423a6cafe9ad6baad79cc58120"}],"HostName":"d5f392bb4807","MappedDirectories":[{"HostPath":"\\ProgramData\\Volumes\\vol1","ContainerPath":"c:\\vol1","ReadOnly":false,"BandwidthMaximum":0,"IOPSMaximum":0}],"HvPartition":false,"EndpointList":["a49718f3-70f8-43fc-8743-a4ccfb08e4c8"],"Servicing":false,"AllowUnqualifiedDNSQuery":true}.

10.	Basically, the absolute mount path does not work and relative path works only in case of local directories and not on access paths assigned to volumes.

**Output of `docker version`:**
PS C:\Users\Administrator> dockerd --version
Docker version 1.13.0-rc4, build 88862e7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Virtual (Windows server 2016 RTM).

**Comment by anusha-ragunathan** [comment]
MappedDirectories HostPath has a extraneous backslashes prepended to the path. "\C:\ProgramData\Volumes\vol1". This is a regression caused by https://github.com/docker/docker/commit/c54b717caf1a55e525ce180bfcb42addd59c6633

For pluginv1 on windows, BasePath() should return an empty string, since the plugin is fully aware of the mount path. Also, unlike Linux where all paths are relative to "/", Windows paths are dependent on system drives and mapped drives.

**Comment by anusha-ragunathan** [comment]
Something like https://github.com/docker/docker/commit/f2fe22a158fb692a02916017a70079b9bea5e08a should help. ping @tiborvass

**Comment by tiborvass** [comment]
Agree with @anusha-ragunathan. That patch seems good.
