### ISSUE TITLE
Support --net=container:<NameOrId> for Windows containers (Process Isolation only)

### ISSUE THREAD

**Issue by madhanrm** [docker/docker#30152]
**Description**
Support for Windows containers to share network Endpoints

Enable --net=container:<NameOrId> for windows

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by madhanrm** [comment]
I am going to open a PR for this requested. So opened a new enhancement bug

**Comment by justincormack** [comment]
You do not need to open an issue first if there is nothing to discuss eg the design. This issue is no use, so closing.
