### ISSUE TITLE
Failed to start Docker Application Container Engine

### ISSUE THREAD

**Issue by xumm4011** [docker/docker#30167]
Unit docker.service entered failed state.
Jan 14 23:37:04 VM_215_206_centos systemd[1]: docker.service failed.
Jan 14 23:49:42 VM_215_206_centos systemd[1]: Starting Docker Application Container Engine...
Jan 14 23:49:42 VM_215_206_centos dockerd[19232]: time="2017-01-14T23:49:42.976923901+08:00" level=info msg="libcontainerd: new containerd process, pid: 19239"
Jan 14 23:49:43 VM_215_206_centos dockerd[19232]: time="2017-01-14T23:49:43.995724225+08:00" level=error msg="[graphdriver] prior storage driver \"devicemapper\" failed: devmapper: Unable to find loopback mount for: /var/lib/docker/devicemapper/devicemapper/data"
Jan 14 23:49:43 VM_215_206_centos dockerd[19232]: time="2017-01-14T23:49:43.995872303+08:00" level=fatal msg="Error starting daemon: error initializing graphdriver: devmapper: Unable to find loopback mount for: /var/lib/docker/devicemapper/devicemapper/data"
Jan 14 23:49:43 VM_215_206_centos systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jan 14 23:49:44 VM_215_206_centos systemd[1]: Failed to start Docker Application Container Engine.
Jan 14 23:49:44 VM_215_206_centos systemd[1]: Unit docker.service entered failed state.
Jan 14 23:49:44 VM_215_206_centos systemd[1]: docker.service failed.

**Comment by gianarb** [comment]
Hello @xumm4011 Can we have a little bit of context here?

* Which version of docker are you using? And how did you install it?
* In which OS are you trying to run it?
* Do you get this error in a fresh environment?

**Comment by xumm4011** [comment]
@gianarb, thanks，I uninstall the reboot of the machine has been solved

**Comment by gianarb** [comment]
Can you close the issue @xumm4011 ? thanks
