### ISSUE TITLE
docker secret create doesn't work on docker windows

### ISSUE THREAD

**Issue by s101d1** [docker/docker#30171]
I installed docker toolbox v1.13.0-rc7 on windows.

I run comand `docker service create my-login-password /c/Users/Bill/secret.txt` on docker quickstart terminal.

Got this result:
> 
> time="2017-01-15T03:45:52+07:00" level=warning msg="Unable to use system certificate pool: crypto/x509: system root pool is not
> available on Windows"
> open /c/Users/Bill/secret.txt: The system cannot find the path specified.

I already make sure the file exists. With docker linux, the command is working fine.

Output of `docker version`:
```
Client:
 Version:      1.13.0-rc7
 API version:  1.24
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.5
 API version:  1.24 (minimum version )
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 06:14:34 2016
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by cpuguy83** [comment]
I'm not following.
The command you are running is `docker service create` but the title says `docker secret create`, and you are running a 1.12.5 daemon (which doesn't support secrets).

**Comment by thaJeztah** [comment]
This looks like a user error, so i'll close, but feel free to continue the conversation if we misunderstood

**Comment by s101d1** [comment]
Sorry it's typo. I mean `docker secret create`.

**Comment by thaJeztah** [comment]
`docker secret create` is part of the docker 1.13 release, but you need to update the _daemon_ for that, not the client.

**Comment by s101d1** [comment]
Thanks, I just updated the docker-machine (ref: https://github.com/docker/toolbox/issues/622). However the `docker secret create` still returns error `The system cannot find the path specified`. Turns out I have to use normal windows path: `c:/Users/Bill/secret.txt`

**Comment by friism** [comment]
@s101d1 this is being worked on: https://github.com/docker/docker/pull/29738

**Comment by thaJeztah** [comment]
@friism this one is not for native Windows containers (daemon is Linux / b2d)
