### ISSUE TITLE
HEALTHECK bootstrap period before running normal hatlchecks

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/docker#30172]
I am working on improving the percona cluster autoscaling

the problem I am facing is that when a new node joins to the  cluster (auto scaling) it needs some time to sync with the cluster and depending on the size of the master node it might take even more than an hour.
so the healthcheck kills the container before it syncs with the node and starts a new one

as a workaround I have set the --retries=30 , but once the container is started I don't want so many retries before the container is marked as unhealthy. when running I want --timeout=5s --retries=5

What about adding a  "--bootstrap-period" option which will allow the initial container bootstrap 

During the --bootstrap-period run healthchecks  , but don't kill the container even if the healthcheck fails

if during the --bootstrap-period the healthcheck returns healthy sooner than the bootstrap-period threshold than switch to --timeout=5s --retries=5 and continue normal monitoring

HEALTHCHECK --bootstrap-period=60min --timeout=5s --retries=5 CMD ["/healthcheck.sh"]

**Comment by cpuguy83** [comment]
Sounds like #26664 and #28938

Closing this, but please let me know if these don't meet your needs.
