### ISSUE TITLE
How to get the whole error message(too long) from command: docker service ps svcname

### ISSUE THREAD

**Issue by wisher2018** [docker/docker#30174]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by allencloud** [comment]
I was wondering if `--no-trunc        Do not truncate output` flag is what you need.

```
root@ubuntu:~# docker service ps --help

Usage:	docker service ps [OPTIONS] SERVICE

List the tasks of a service

Options:
  -f, --filter filter   Filter output based on conditions provided
      --help            Print usage
      --no-resolve      Do not map IDs to Names
      --no-trunc        Do not truncate output
  -q, --quiet           Only display task IDs
```

**Comment by wisher2018** [comment]
Thanks,  I have got the whole error message by command: service docker status -l.

**Comment by wisher2018** [comment]
Yes,  you are right! But my docker version is 1.12.5, so it hasn't the flag.
