### ISSUE TITLE
PXE boot related service doesn't work on Docker for Windows

### ISSUE THREAD

**Issue by mscribe** [docker/docker#30196]
**Description**
When I try running a simple TFTP service on port 69/udp on Docker for Windows, I cannot fetch a file from it.  I really want to be able to connect a laptop to a network, run a Docker container on it, and start PXE booting other computers from the laptop.

**Steps to reproduce the issue:**

***Example 1***
1. Install Docker for Windows Version 1.13.0-rc7-beta37 (9733) on a Windows 10 Pro computer.  The Docker for Windows installer will set up MobyLinuxVM in Hyper-V.
2. Disable the Windows Firewall.
3. Create a new example Dockerfile with these contents:
```
FROM alpine

RUN apk add --no-cache tftp-hpa; \
    wget -P /var/tftpboot http://boot.ipxe.org/undionly.kpxe

EXPOSE 69/udp

ENTRYPOINT ["in.tftpd", "--foreground", "--secure", "/var/tftpboot"]
```
4. Build the image by running the following command in Windows Powershell:
```
docker build -t tftp .
```
5. Run the TFTP server with the following command (try with `--net=host` too):
```
docker run -it --rm -p 69:69/udp tftp
```
***Example 2 (pixiecore)***
1. Install Docker for Windows Version 1.13.0-rc7-beta37 (9733) on a Windows 10 Pro computer.  The Docker for Windows installer will set up MobyLinuxVM in Hyper-V.
2. Disable the Windows Firewall.
3. Run the following command in Windows Powershell:
```
docker run --net=host -v ${PWD}:/image danderson/pixiecore boot https://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz https://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz --cmdline='coreos.autologin'
```

**Describe the results you received:**

***Example 1***
From either Windows or another Linux computer, test the TFTP server.
```
C:\Users\Bill>tftp -i 192.168.0.8 GET undionly.kpxe

OR

bill@nuc1:~$ tftp 192.168.0.8
tftp> get undionly.kpxe
Transfer timed out.
```
***Example 2 (pixiecore)***
Turn on another computer in the same network that first tries to boot from network.

**Describe the results you expected:**
When I run this software on Docker on a computer running Ubuntu, TFTP serves undionly.kpxe just fine and network booting from pixiecore also works as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**
- Windows Docker containers (172.17.0.1/24) can send UDP packets to an Ubuntu box.
- An Ubuntu box can send UDP packets to a Windows Docker container at 192.168.0.8.
- Windows host PowerShell can TFTP a file from an Ubuntu box.
- Windows Docker containers (172.17.0.1/24) cannot TFTP from an Ubuntu box.
- Windows host Powershell cannot TFTP a file from a Windows Docker container at 192.168.0.8.
- Windows Docker containers cannot TFTP a file from another Windows Docker container at 192.168.0.8.
- Windows Docker containers (172.17.0.1/24) *can* TFTP a file from another Windows Docker container through an address from 172.17.0.1/24

**Output of `docker version`:**
```
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 16
Server Version: 1.13.0-rc7
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 43
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 3cri74k2gzb3s8m0z0s1rg3qt
 Is Manager: true
 ClusterID: 908edch466kp3sw5u3snssll8
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.3-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934 GiB
Name: moby
ID: 4TJT:YSEG:BAWD:D5VK:J7SE:R3AV:QTJY:JB74:DKHQ:LENC:LCTA:2JWE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 36
 Goroutines: 127
 System Time: 2017-01-17T04:39:02.0906497Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Microsoft Surface Book with Windows 10 Pro; VirtualBox *NOT* installed.

**Comment by justincormack** [comment]
Can you open this in https://github.com/docker/for-win/issues as it seems to be specific to Docker for Windows.

I am going to close this here as you say it is working elsewhere.

**Comment by mscribe** [comment]
*Created [issue #395](https://github.com/docker/for-win/issues/395).*
