### ISSUE TITLE
Environment variables set by docker are only visible in single user process on Windows

### ISSUE THREAD

**Issue by artisticcheese** [docker/docker#30192]
**Description**
When you launch docker container with -e parameter (environment variables) then those environment variables are only seen in default process but not seen by the whole machines

**Steps to reproduce the issue:**
1. Run docker.exe, specifiying environment variables
`docker run -e "aadd=dds" -d microsoft/iis`
2. Check environment variables by default docker process
`docker exec -it 5a  "cmd.exe"`

```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>set aadd
aadd=dds
```

and by open powershell session into the same container

```
PS C:\Users\admin> Enter-PSSession -ContainerId (Get-Container 5a).ID
[5aa2576356cb...]: PS C:\Users\ContainerUser\Documents> $env:aadd -eq $null
True
```
2.
3.

**Describe the results you received:**
For default docker process environment variables are visible, for alternative shell they are not

**Describe the results you expected:**
I expected those environment variables to be set on Machine level so they are visible for other applications withing the same running container

**Additional information you deem important (e.g. issue happens only occasionally):**
Always happens
**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 2
 Paused: 0
 Stopped: 1
Images: 23
Server Version: 1.13.0-rc7
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows 10 Enterprise
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 15.92 GiB
Name: gsuvalia-MOBL3
ID: AP6M:KE34:A3UR:L36C:6SNC:RBXS:TKMR:ZW2Q:FO6L:FA7O:W7II:QVD3
Docker Root Dir: D:\images
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 34
 System Time: 2017-01-16T17:28:24.7135606-06:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Happens all over the medium, not host specific

**Comment by thaJeztah** [comment]
ping @johnstep

**Comment by artisticcheese** [comment]
Please update if this is considered a defect which will be fixed or not. I rely on this to work pass secrets while instantiating container which does not work.

**Comment by friism** [comment]
cc @jhowardmsft

**Comment by jhowardmsft** [comment]
This is by design - the environment block is passed through from docker to HCS on the process that is launched via Win32 which means docker run and docker exec. A PS remote session doesn't go through docker, so those will not be visible.
