### ISSUE TITLE
Not able to run docker containers. Flag provided but not defined: -console

### ISSUE THREAD

**Issue by harche** [docker/docker#30198]
**Steps to reproduce the issue:**
1. Docker run command 

**Describe the results you received:**
```
# docker run hello-world 
docker: Error response from daemon: oci runtime error: flag provided but not defined: -console. 
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   23cf638
 Built:        Tue, 27 Sep 2016 12:25:38 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 24
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.504 GiB
Name: harshal-ThinkPad-T450
ID: CHWO:C47J:VEGI:PGXN:GCBC:QLSW:5KMX:NWZ4:NDNF:NMSP:C7AC:BX7O
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
Did you install non-default runc?

**Comment by harche** [comment]
yes, but I didn't modify it. All I did was,

```
cd github.com/opencontainers
git clone https://github.com/opencontainers/runc
cd runc

make
sudo make install
```

**Comment by AkihiroSuda** [comment]
The latest runc is incomatible with Docker 1.12.
You can use the `docker-runc` (should be installed with docker by default)

**Comment by harche** [comment]
Where can I find it? I tried to list the package content of the docker package in ubuntu by `dpkg -L  docker.io` didn't find any runc binary. 

where can I find the runc binary shipped with docker?

**Comment by harche** [comment]
anyway, I uninstalled my custom runc and it's working fine now.

**Comment by thaJeztah** [comment]
@harche it may be you installed Ubuntu's package - that's not maintained by us. packages can be found at apt.dockerproject.org (see https://docs.docker.com/engine/installation/linux/ubuntulinux/)

**Comment by harche** [comment]
@thaJeztah  thanks.

**Comment by lamby** [comment]
This is a regression in recent runc. Downgrade to (eg. 0.1.1+dfsg1-2)

See also https://bugs.debian.org/855208
