### ISSUE TITLE
attachable property not supported in docker-compose v3 format

### ISSUE THREAD

**Issue by raarts** [docker/docker#30191]
@dnephin 

**Description**

it's not possible to set `attachable: true` in the global network key.

**Steps to reproduce the issue:**

```
networks:
  my-network:
    driver: overlay
    attachable: true
```

**Describe the results you received:**

attachable Additional property attachable is not allowed

**Describe the results you expected:**

just creating an attachable network

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 06:37:02 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 10
Server Version: 1.13.0-rc7
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local local-persist
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: wx2cm0cgduy2r82wgkw0pgayy
 Is Manager: true
 ClusterID: mhdentu8t3yzti0z62r5h1hqh
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.8.128.73
 Manager Addresses:
  10.8.122.201:2377
  10.8.127.73:2377
  10.8.128.73:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 4.8.14-docker-1
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.857 GiB
Name: d0001.ams.tc.xxxxxx.com
ID: I2Z7:LP7H:TNVC:WZ7A:3O6B:OKSD:XET5:G62C:YHRE:JQYZ:OZ3F:YPUU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: raarts
Registry: https://index.docker.io/v1/
Labels:
 provider=generic
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by nathanleclaire** [comment]
Yeah... This would be pretty nice especially for local development...

**Comment by vdemeester** [comment]
Hum thinking of `docker/compose`, should this be just ignored (maybe a warning then) when using `docker-compose` (which doesn't talk to the swarm) ?

**Comment by thaJeztah** [comment]
Looks like the `bridge` driver already ignores the option;

```bash
$ docker network create --attachable -d bridge foobar
6a552771d516ae246376ec8ba15846f0a05e879f8e5a6d730ddccca698e25571
```

```bash
$ docker network inspect foobar
```
```json
[
    {
        "Name": "foobar",
        "Id": "6a552771d516ae246376ec8ba15846f0a05e879f8e5a6d730ddccca698e25571",
        "Created": "2017-01-20T14:25:26.398470731Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]
```

Looking at the above;

- wondering; is `attachable` an option of the _overlay_ driver (should it _actually_ be `--opt attachable`?
- should it not actually _set_ the `attachable` option? If the `bridge` driver does not support `attachable` it should not actually show up in the network specification?

ping @mavenugo @aboch ^^

**Comment by dnephin** [comment]
@vdemeester In docker-compose this field is always enabled, as of version Compose format v2.1 (https://github.com/docker/compose/pull/4232).

**Comment by mavenugo** [comment]
@thaJeztah it is not a driver specific option. It is a swarm-mode option to allow both services and unmanaged containers to run in the same network. As of 1.13.0, overlay driver is the only supported driver in swarm-mode. But with 1.13.1, we are trying to bring-in plugin support in swarm-mode and this `--attachable` option will be used by networks using other plugins as well.

**Comment by taiidani** [comment]
Would love to see this. Being able to `docker-compose run` using the service definitions in our V3 docker-compose.yml file would make it much easier to run one-offs such as crons, database migration scripts, etc.

**Comment by bkc1** [comment]
+1.  
I am also having issues dealing with one-off  containers in V3 compose-managed service stacks and swarm overlay networks. After running: 
```
$ docker stack deploy -c docker-compose.yml my_service
```
The only way I have been able to connect a one-off container into a service stack is to create another service attached into the _my_service_ network with a sleep command which seems goofy: 
```
$docker service create --name temp_service  --network my_service_default centos:centos7 sleep 5000
$docker exec -it temp_service.1.qk16sb2xgvpygqkgy03d0k03l bash
```

**Comment by galindro** [comment]
Guys, any updates about this issue?

**Comment by dnephin** [comment]
This was added in #30742. It will be in Compose file v3.2 format in the next release.
