### ISSUE TITLE
one docker daemon can support how many docker containers??

### ISSUE THREAD

**Issue by zhu312542860** [docker/docker#30195]
I hava a physical machine，the machine has 512 GB memory and 64 core CPUS。

Now,I want to run the docker container on the physical machine，i will install the centos 7.2 os and the 1.12 docker vesion。

the one physical machine or one docker daemon can run how mach contaienrs at most??

**Comment by gianarb** [comment]
Hello @zhu312542860 

It's something that you can calculate but we have not enough information and it's hard to get a 100% correct answer. You can use cgroup to limitate the amount of resource used by each container. In this way you can have an idea about how many containers you can run.

Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other types of questions, consider using one of:

* https://forums.docker.com
* the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
* StackOverflow

**Comment by thaJeztah** [comment]
Yes, GitHub is not the best place for this, so I'll close this issue, but feel free to continue the conversation
