### ISSUE TITLE
Error while restoring a container. 

### ISSUE THREAD

**Issue by harshitdaga** [docker/docker#30224]
**Description**
Kindly help me. I am trying to checkpoint a docker, which is done on one server. Thereafter I am taking the checkpoint image to another server (with same docker version running) and trying to restore to the docker container. The restore is failing with the error "Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0" . The containers on both the servers were started with the same configuration. Restore log details at http://pastebin.com/x6Z0qwa1

**Steps to reproduce the issue:**
1.docker checkpoint ck cr
2.scp /var/lib/docker/containers/921de66b87.../checkpoints/ck server2
3.docker start --checkpoint ck cr_second

**Describe the results you received:**
Error response from daemon: oci runtime error: criu failed: type NOTIFY errno 0
log file: /var/lib/docker/containers/39bc78109ac6be1e47b95eb76fa7d7516b75f730cf619868d25ed30099daf943/checkpoints/ck/criu.work/restore-2017-01-17T21:06:33Z/restore.log

**Describe the results you expected:**
docker container should have started. I had earlier tried the same thing with docker 1.13.0-dev experimental and it use to work. However trying with Docker version 1.14.0-dev is giving me the above mentioned issue.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
Docker version 1.14.0-dev

**Output of `docker info`:**
Containers: 6
Running: 1
Paused: 0
Stopped: 5
Images: 277
Server Version: 1.14.0-dev
Storage Driver: overlay
Backing Filesystem: extfs
Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
Volume: local
Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 4.5.0-040500rc1-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.66 GiB
Name: xx.xx.xx.xx
ID: xx:xx:xx:xx
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**criu --version**
Version: 2.6

**Comment by thaJeztah** [comment]
ping @boucher @xemul ptal

@harshitdaga can you also add which version of criuu you have installed?

**Comment by harshitdaga** [comment]
@thaJeztah added

**Comment by boucher** [comment]
Does anyone know what `/proc/asound` is?

**Comment by xemul** [comment]
The /proc/asound is the sound subsystem file. And it's missing on the destination node.

**Comment by harshitdaga** [comment]
seems like /proc/sound is indeed the sound subsystem file. I have no idea why it started giving an issue now. I tried doing the same case on a different set of servers and it worked. 
Thanks for the help :)

**Comment by xemul** [comment]
It's, I would say, an issue to be fixed in the long run. AFAIU the /proc/asound file is hidden by runc at container start with a bind-mount, so when restoring the corresponding container on a node that doesn't have this file, the restore shouldn't fail (unless the file is opened), but instead this bind-mount should just be ignored.

**Comment by rockymtnman** [comment]
@xemul I came across this issue as well when restoring to a CentOS VM (worked fine in RHEL 7).  Did a CRIU ticket for this ever get created?

**Comment by xemul** [comment]
@rockymtnman this is not CRIU issue, that's what CRIU caller should do before calling criu restore -- tune the objects to restore before doing the restore itself. So no, ticket for CRIU has not been created for this. If there's some API missing on the CRIU side to make this work, then surely I'll create one, but in this particular case the --ext-mount-map option for asound should not be given.

**Comment by farooqte96** [comment]
@xemul I am facing same issue on one destination host. Would you like to tell if there is any fix for this problem? Thanks
