### ISSUE TITLE
Docker hangs and all containers stuck, cannot stop container, docker info, logs command are also hang.

### ISSUE THREAD

**Issue by SeanZhu20** [docker/docker#30229]
**Description**
As described in title, our docker hangs after docker run, and "docker stop", "docker info", "docker logs containerID" are all hangs.

**Steps to reproduce the issue:**
Have no idea how does it occured.

**Describe the results you received:**
Docker containers stuck, and docker info, docker logs, docker stop are hang.

**Describe the results you expected:**
Docker containers should run normally and all command should not hang.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:25:01 UTC 2015
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
Images: 388
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-2097925-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: 
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 35.76 GB
 Data Space Total: 104.2 GB
 Data Space Available: 68.39 GB
 Metadata Space Used: 37.45 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.11 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.18.27
Operating System: CentOS Linux 7 (Core)
CPUs: 4
Total Memory: 15.67 GiB
Name: slave2.g1.r2.sh
ID: EWQL:SZWJ:6M6W:2HBB:VGNQ:2KUG:QYMD:JAF4:OOCO:CIZW:HZXO:53WM
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Output of `uname -a`:**

```
Linux slave18.g1.r2.sh 3.18.27 #1 SMP Mon Feb 29 16:36:56 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
```

We have a cluster with about 200 machines, and this occured a couple of times. And we use docker on jenkins, so this problem will hangs the related jenkins jobs, too.

What can I do for solving this?

**Comment by coolljt0725** [comment]
@SeanZhu20  can you send `SIGUSR1` to docker daemon( you can use` kill -SIGUSR1 $(cat /var/run/docker.pid)`) and paste stack dump?

**Comment by SeanZhu20** [comment]
@coolljt0725 It was recovered by using restart docker service. I will try when it show again.

**Comment by thaJeztah** [comment]
Let me close this issue for now, but feel free to comment if you see the issue again. Keep in mind that docker 1.9 is no longer maintained, so we won't be fixing issues in that version

**Comment by SeanZhu20** [comment]
@thaJeztah Showed again in docker 1.12.3:
docker info stuck and not returning anything, docker run stuck too.

output of docker version:

`Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        
 OS/Arch:      linux/amd64`

output of docker info from another machine:
`Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 26
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-2097729-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 46.66 GB
 Data Space Total: 104.2 GB
 Data Space Available: 57.5 GB
 Metadata Space Used: 49.42 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.098 GB
 Thin Pool Minimum Free Space: 10.42 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.18.27
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.67 GiB
Name: slave42.g1.r2.sh
ID: EWQL:SZWJ:6M6W:2HBB:VGNQ:2KUG:QYMD:JAF4:OOCO:CIZW:HZXO:53WM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 23
 System Time: 2017-02-13T11:53:22.535459998+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Insecure Registries:
 0.0.0.0/0
 127.0.0.0/8`

output of uname -a:
`Linux slave42.g1.r2.sh 3.18.27 #1 SMP Mon Feb 29 16:36:56 CST 2016 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by 4tilo2** [comment]
I have the sam issue with TeamCity-Server-Container and TeamCity-Agent-Container on a .net Core C# build with NPM.
I cant stop or kill any running container (4 Containers are running).
I am running it on a VM `Linux h2695462 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux` with `2 GB Ram` and `1 Core`.

**Docker Version**
```
Docker version 17.03.0-ce, build 3a232c8
```

**Docker Info output**
```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-78-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.945 GiB
Name: h2695462
ID: PM6H:37NA:XWKO:TYLS:QAJW:BGMP:QX3K:4CRS:GSWJ:34HS:DKLB:IICP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Tried the following but it did not work:
[https://github.com/moby/moby/issues/22357](https://github.com/moby/moby/issues/22357)

**Comment by MichaelGreco** [comment]
docker stop  ym_pipeline-app.2.z2swusmgkgbku34rmlwhdkxau

hanging ...  

docker -v
Docker version 17.12.1-ce, build 7390fc6

ok it's old ...

**Comment by Xerus2000** [comment]
well even `docker -v` hangs for me - what is this?

**Comment by egrigolon** [comment]
@Xerus2000 I have the same issue

**Comment by lezi1022** [comment]
i have the same issue, docker ps hung up, but docker info is ok

**Comment by remort** [comment]
I faced the same issue. It seems that `docker-compose up` hangs after a while if I run it in non-daemonized mode (containers stdout logs to console). Otherwise (with `-d` option) it works stable for days, no problem is occured. Check this case please.
