### ISSUE TITLE
no method to modify pre-defined network subnet?

### ISSUE THREAD

**Issue by vanloswang** [docker/docker#30237]
**Description**
The default network subnet for docker0 is 172.17.0.0/16, and default ip of docker0 is 172.17.0.1/16. I want to modify it to another, I did not find a best way for how and where to modify.  Docker will also  prevent user to rm default bridge or create default bridge. it is limit for use in some network environment.
Additionly, I have tried to add '--bip' to docker daemon start options, it will cause problem for k8s to get allocated subnet infomations. So it is not a good solution for me.

**Steps to reproduce the issue:**
1. install docker on CentOS 7, start it and execute 'docker network ls', find bridge
2. execute 'docker network rm bridge'
3. execute 'docker network create --driver=bridge --subnet=162.16.0.0/16 --gateway=162.16.0.1 bridge'

**Describe the results you received:**
step 2 and step 3 will failed, and report following informations:
```bash
Error response from daemon: bridge is a pre-defined network and cannot be removed
```

**Describe the results you expected:**
it is better to add 'docker network edit' and let user to modify some item for docker network.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.x86_64
 Go version:      go1.4.2
 Git commit:      7ffc8ee-unsupported
 Built:           Fri Jun 17 15:27:21 2016
 OS/Arch:         linux/amd64

Server:
 Version:         1.10.3
 API version:     1.22
 Package version: docker-common-1.10.3-44.el7.x86_64
 Go version:      go1.4.2
 Git commit:      7ffc8ee-unsupported
 Built:           Fri Jun 17 15:27:21 2016
 OS/Arch:         linux/amd64
```

**Comment by gianarb** [comment]
Hello @vanloswang 
I think that this document can help you to achieve your goal
https://docs.docker.com/engine/userguide/networking/default_network/custom-docker0/

Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other types of questions, consider using one of:

* https://forums.docker.com
* the docker community slack channel (https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
* StackOverflow

Thanks!

**Comment by vanloswang** [comment]
@gianarb Thanks, find a solution in https://support.zenoss.com/hc/en-us/articles/203582809-How-to-Change-the-Default-Docker-Subnet. the subnet is read from docker0.
