### ISSUE TITLE
daemon allows creating two network with same name when checkDuplicate is false, REASONABLE?

### ISSUE THREAD

**Issue by allencloud** [docker/docker#30242]
**Description**

Hi, All,

I found that we could create two bridge networks with same name, as we use a field `"checkDuplicate":false,` in the api request payload.

Is it reasonable?

Here is my request:
```
POST 192.168.59.103:2375/networks/create
payload:
{
	"Name":"ouyang",
	"Driver":"bridge",
	"EnableIPv6":false,
	"Internal":false,
	"Attachable":false,
	"Options":{},
	"checkDuplicate":false,
	"Labels":{},
	"IPAM":{
		"Driver":"default",
		"Options":{},
		"Config":[]
	}
}
```

With the first create request, we got the response:
```
{
  "Id":"1c4fcb3e1e9b3a25aa04164328a6d680bab897e151dbc09a0c8e3d414e22a0bc",
  "Warning": ""
}
```

With the first create request, we got the response:
```
{
  "Id": "1c4fcb3e1e9b3a25aa04164328a6d680bab897e151dbc09a0c8e3d414e22a0bc",
  "Warning": "Network with name ouyang (id : 77ab41fbbe321bc02622b50d81ef2404b3229a8d8a53aeb8922f762b9d15ec9f) already exists"
}
```
We create twice, and get result like this:
```
root@ubuntu:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
30d1f8c9ec34        bridge              bridge              local
85ded5476b05        docker_gwbridge     bridge              local
d909a9f88b4c        host                host                local
f799odklwkfi        ingress             overlay             swarm
615a39ff6c47        none                null                local
77ab41fbbe32        ouyang              bridge              local
1c4fcb3e1e9b        ouyang              bridge              local
```

Two network ouyang, is it reasonable? Since it happens, we could not use `docker network inspect ouyang` and some other network commands using network name:
1. `docker network inspect ouyang` may get the wrong network;
2. `docker network rm ouyang` may  remove the wrong network;
3. .....

Or it is for some kind of back compatibility?  If that, I think we should mark that in the source code.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@ubuntu:~# docker version
Client:
 Version:      1.13.0-rc4
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:59:15 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc4
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   88862e7
 Built:        Fri Dec 16 22:59:15 2016
 OS/Arch:      linux/amd64
 Experimental: false
root@ubuntu:~#
```

**Output of `docker info`:**

```
root@ubuntu:~# docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 37
Server Version: 1.13.0-rc4
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 202
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 07jqxh286upar2z13e9cf69ad
 Is Manager: true
 ClusterID: vkawf2iglgltjxyupnvpbst5f
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.59.103
 Manager Addresses:
  192.168.59.103:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-25-generic
Operating System: Ubuntu 14.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.954 GiB
Name: ubuntu
ID: Q2ZC:GWDN:27OH:GRMH:G6QU:W7QP:4TIX:Q5F6:YEVK:45XP:EXHC:HOB5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 90
 Goroutines: 184
 System Time: 2017-01-17T14:45:33.364813219+08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://a.b.c/
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
This is by design

https://github.com/docker/docker/issues/18864#issuecomment-167006094

**Comment by allencloud** [comment]
Thanks a lot @AkihiroSuda 

Currently I ran into another situation base on this which I think may be a bug.

First Step: Create a bridge network named allen with CheckDuplicate false
```
{
	"Name":"allen",
	"Driver":"bridge",
	"EnableIPv6":false,
	"Internal":false,
	"Attachable":false,
	"Options":{},
	"CheckDuplicate":false,
	"Labels":{},
	"IPAM":{
		"Driver":"default",
		"Options":{},
		"Config":[]
	}
}
```

Second Step: Create an overlay network named allen with CheckDuplicate false:
```
{
	"Name":"allen",
	"Driver":"overlay",
	"EnableIPv6":false,
	"Internal":false,
	"Attachable":false,
	"Options":{},
	"CheckDuplicate":false,
	"Labels":{},
	"IPAM":{
		"Driver":"default",
		"Options":{},
		"Config":[]
	}
}
```

Third Step: using `docker network ls` to get networks, and we can find that bridge network allen has a scope of **SWARM** : 
```
root@ubuntu:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
ax6hvpbxkzej        allen               overlay             swarm
232bed45a9d7        allen               bridge              swarm
30d1f8c9ec34        bridge              bridge              local
85ded5476b05        docker_gwbridge     bridge              local
d909a9f88b4c        host                host                local
f799odklwkfi        ingress             overlay             swarm
615a39ff6c47        none                null                local
```

**Comment by yongtang** [comment]
I think the issue is that `nw.Name()` instead of `nw.ID()` was used:
https://github.com/docker/docker/blob/v1.13.0-rc7/api/server/router/network/network_routes.go#L166

Created a PR #30250 to address the issue.

**Comment by thaJeztah** [comment]
Yes, that looks like a bug (was just looking at it) 👍 

Looks like it also prevents services from being started properly; SwarmKit keeps trying until it gets the right network I think;

```
docker service create --name web --network allen nginx:alpine

/test # docker service ps web
ID            NAME       IMAGE         NODE          DESIRED STATE  CURRENT STATE               ERROR                             PORTS
jq8ki2jhcwuf  web.1      nginx:alpine  0f2f801ba7d3  Running        Running about a minute ago
a5ulnupdafzj   \_ web.1  nginx:alpine  0f2f801ba7d3  Shutdown       Failed about a minute ago   "starting container failed: Us…"
wtbyktd95un0   \_ web.1  nginx:alpine  0f2f801ba7d3  Shutdown       Failed about a minute ago   "starting container failed: Us…"
f50lfile1dib   \_ web.1  nginx:alpine  0f2f801ba7d3  Shutdown       Failed about a minute ago   "starting container failed: Us…"
myawz9c3nzz9   \_ web.1  nginx:alpine  0f2f801ba7d3  Shutdown       Failed about a minute ago   "starting container failed: Us…"
```

Showing this in the log;
starting container failed: User specified IP address is supported only when connecting to networks with user configured subnets
```

**Comment by yongtang** [comment]
@thaJeztah The service creation failure is related to the non-uniqueness of network names and are impacted by several APIs (like `FindNetwork` when container is dispatched/executed at nodes by manager). Will take a deeper look into it.

**Comment by allencloud** [comment]
I think the original issue is solved by @yongtang, am I right? 
If that, I think it is proper to close this one. While feel free to contact if more info needed.

**Comment by yongtang** [comment]
Thanks @allencloud. Yes the original issue has already been addressed.

The additional comment https://github.com/docker/docker/issues/30242#issuecomment-273517205 should be addressed by #30897 (I hope).

**Comment by stealthybox** [comment]
I am still able to reproduce:
```
cd projectname
docker-compose up -d
docker-compose stop
docker deploy -c docker-compose.yaml projectname
```
results in the error @thaJeztah mentions from `docker service ps --no-trunc projectname_svc`:
```
starting container failed: User specified IP address is supported only when connecting to networks with user configured subnets
```

**Comment by thaJeztah** [comment]
@stealthybox I don't think that error is actually a bug; `User specified IP address is supported only when connecting to networks with user configured subnets` - custom IP addresses are not supported for services, only containers (`docker run` / `docker-compose up`)

**Comment by stealthybox** [comment]
Hi @thaJeztah,

The bug is that the swarm tasks are being attached to networks of the same name that were created by compose instead of the stack's swarm scoped overlays.

Like @yongtang suggested, I believe his change in #30897 fixes this, but it looks like there is some work to make it mergeable again.

This seems fairly simple to reproduce, but I can provide more detail if need be.
This bug definitely caught me off gaurd.

**Comment by yongtang** [comment]
PR #30897 has been rebased. Will look for another review.
