### ISSUE TITLE
Docker toolbox 1.12.6 parsing degradation

### ISSUE THREAD

**Issue by AndrewBryukhov** [docker/docker#30241]
My config is work for 1.12.3. After upgrade to 1.12.6 i see:

>   volumes:
>     - ~/compose/:/connectors:ro

> ERROR: for elastic  Cannot create container for service elastic: Invalid bind mount spec "C:\\Users\\andrew\\compose:/config:ro": Invalid volume specification: 'C:\Users\andrew\compose:/config:ro'
> [31mERROR[0m: Encountered errors while bringing up the project.

Double slash:
![screenshot](https://cloud.githubusercontent.com/assets/15821889/22062197/8eee5bf0-dd89-11e6-9e88-08437025d179.png)

> $ ls ~/compose -la
> total 889
> ...

2. 

>   volumes:
>     - /srv/docker/postgresql:/var/lib/postgresql

> ERROR: for PostgreSQL  Cannot create container for service PostgreSQL: create \srv\docker\postgresql: "\\srv\\docker\\postgresql" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed

> $ docker-compose config
> networks: {}
> services:
>   **PostgreSQL**:
>     environment:
>       DB_EXTENSION: ''
>       DB_NAME: ''
>       DB_TEMPLATE: ''
>       DEBUG: 'false'
>       POSTGRES_PASSWORD: ''
>       POSTGRES_USER: postgres
>       REPLICATION_MODE: ''
>       REPLICATION_PASS: ''
>       REPLICATION_SSLMODE: ''
>       REPLICATION_USER: ''
>     image: postgres:9.6
>     network_mode: bridge
>     restart: unless-stopped
**>     volumes:
>     - \srv\docker\postgresql:/var/lib/postgresql:rw**
>   elastic:
>     environment:
>       ES_JAVA_OPTS: -Xms512m -Xmx512m
>       bootstrap.memory_lock: 'true'
>     image: elasticsearch:5.1.2
>     network_mode: bridge
>     ports:
>     - 9200:9200
>     restart: unless-stopped
>     volumes:
>     - C:\Users\andrew\compose:/config:ro
>     - C:\compose\Vending\volumes\elastic:/usr/share/elasticsearch/data:rw
>   fpm:
>     image: ...
>     links:
>     - PostgreSQL
>     - elastic
>     network_mode: bridge
>     restart: unless-stopped
>     volumes:
>     - C:\Users\andrew\.ssh:/root/.ssh:ro
>     - C:\Users\andrew\compose\vending:/var/www:rw
>   kibana:
>     environment:
>       ELASTICSEARCH_PASSWORD: ''
>       ELASTICSEARCH_URL: http://elastic:9200
>       ELASTICSEARCH_USERNAME: ''
>     image: kibana:5.1.2
>     links:
>     - elastic
>     network_mode: bridge
>     ports:
>     - 5601:5601
>     restart: unless-stopped
>   logstash:
>     command: -f /connectors/simple-out.conf
>     image: logstash:5.1.2
>     links:
>     - PostgreSQL
>     - elastic
>     network_mode: bridge
>     restart: unless-stopped
>     volumes:
>     - C:\Users\andrew\compose:/connectors:rw
>     - C:\Users\andrew\compose:/connectors:ro
> ...
> version: '2.1'
> volumes: {}

**Comment by AndrewBryukhov** [comment]
COMPOSE_CONVERT_WINDOWS_PATHS=1 docker-compose up -d
is fixing this issue.
At old version i run "docker-compose up -d" without  COMPOSE_CONVERT_WINDOWS_PATHS=1

**Comment by gianarb** [comment]
Hello @AndrewBryukhov I am not finding the PR atm but this is the expected behavior
https://docs.docker.com/compose/reference/envvars/#/composeconvertwindowspaths

He a PR that can help
https://github.com/docker/compose/pull/4026

**Comment by thaJeztah** [comment]
Thanks @gianarb!

Yes, I don't think there's a bug here, but it _is_ a change in behavior between docker-compose 1.9 and 1.10 (which changed the default, and added the `COMPOSE_CONVERT_WINDOWS_PATHS` environment variable).

I'm closing this issue, but feel free to comment after I closed. If you think additional changes are needed in docker-compose, it's best to open an issue in the docker-compose issue tracker (https://github.com/docker/compose/issues), so that the maintainers of docker-compose can have a look at it 👍
