### ISSUE TITLE
Docker cleanup don't free space on disk

### ISSUE THREAD

**Issue by alexandrevicenzi** [docker/docker#30254]
**Description**

Docker don't cleanup space if remove images, containers or volumes.

It was working until the last update.

**Steps to reproduce the issue:**

Just tried to remove some old stuff to free some data.

**Describe the results you received:**

Everything was excluded but no free space was available after.

**Describe the results you expected:**

Exclude and free space on disk.

**Additional information you deem important (e.g. issue happens only occasionally):**

The OS is OS X El Capitain (10.11.6).

This was what left on docker dir after the cleanup. The qcow2 doesn't change the size.

```
alexandrevicenzi@mac ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux $ ls -lah
total 85795296
drwxr-xr-x  12 alexandrevicenzi  staff   408B Jan 18 17:52 .
drwxr-xr-x  21 alexandrevicenzi  staff   714B Jan 18 17:52 ..
-rw-r--r--   1 alexandrevicenzi  staff    41G Jan 18 18:00 Docker.qcow2
-rw-r--r--   1 alexandrevicenzi  staff    64K Jan 18 17:52 console-ring
-rw-r--r--   1 alexandrevicenzi  staff     5B Jan 18 17:52 hypervisor.pid
-rw-r--r--   1 alexandrevicenzi  staff     0B Sep  6 16:09 lock
drwxr-xr-x  56 alexandrevicenzi  staff   1.9K Jan 12 00:00 log
-rw-r--r--   1 alexandrevicenzi  staff    17B Jan 18 17:52 mac.0
-rw-r--r--   1 alexandrevicenzi  staff    36B Sep  6 16:09 nic1.uuid
-rw-r--r--   1 alexandrevicenzi  staff     5B Jan 18 17:52 pid
-rw-r--r--   1 alexandrevicenzi  staff   1.0M Jan 18 17:52 syslog
lrwxr-xr-x   1 alexandrevicenzi  staff    12B Jan 18 17:52 tty -> /dev/ttys005
```

The only solution found was to wipe all data from docker. What I dislike because I need to rebuild my images, but since there's isn't any better option this solved.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.41-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.951 GiB
Name: moby
ID: KFY5:FQYD:363H:EYKM:XYMW:2AYS:WW7L:FYDM:CH2Y:5NSU:BJCT:PWXV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 27
 System Time: 2017-01-18T20:06:35.861090271Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: alexandrevicenzi
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by justincormack** [comment]
Please open Docker for Mac specific issues in https://github.com/docker/for-mac/issues not here, which is for general issues. I am closing this here.

This feature is currently available only in the beta channel, but will be in the stable 1.13.0 release, which happens to be released later today.

**Comment by alexandrevicenzi** [comment]
@justincormack What feature are you talking about? I don't use docker beta.

**Comment by alexandrevicenzi** [comment]
For future reference:

- [Docker.qcow2 never shrinks - disk space usage leak in docker for mac](https://github.com/docker/for-mac/issues/371)
-[docker-for-mac: add a FAQ about reducing the qcow2 size](https://github.com/docker/docker.github.io/pull/1100)
