### ISSUE TITLE
Failed to fetch zfs-native ppa when run `make build`.

### ISSUE THREAD

**Issue by J-Liu** [docker/docker#30264]
**Description**

**Steps to reproduce the issue:**
1. git clone https://github.com/docker/docker.git
2. cd docker
3. make build

**Describe the results you received:**
Get:7 http://deb.debian.org jessie Release [148 kB]
Get:8 http://deb.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:9 http://deb.debian.org jessie/main amd64 Packages [9049 kB]
W: Failed to fetch http://ppa.launchpad.net/zfs-native/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
Fetched 9872 kB in 35s (280 kB/s)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 7
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 8
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.936 GiB
Name: ubuntu
ID: 754T:NIYE:LDVM:KC6A:I6YZ:OGO6:ZCTV:CDUI:EHVS:GFYP:ZRYK:RCAF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting, this could be a temporary issue with that repository. Unfortunately there's not really something we can do about that, because we don't own that repository, it's a dependency for building docker.

I'll close this issue, but feel free to continue the conversation

**Comment by J-Liu** [comment]
Then, how can I build docker from source?  Is there any other option? Or some special build instructions?
I tried it for days, zfs-native repository was always down.
Thank you.

**Comment by MistShi** [comment]
+1

**Comment by thaJeztah** [comment]
- Are you manually able to browse that repository (in a browser)?
- I do notice the repository only has compressed (`.gz`, `.bz2`) `Packages` files; check if both those are supported on your machine
- are you building docker inside a container, or on the host?
- is your network using a (transparent) proxy?

**Comment by J-Liu** [comment]
1, I can open the ppa address in browser, and I can get the Packages.gz file, but can NOT get Packages.bz2.
2, Sure `gunzip Packages.gz` is running fine.
3, I'm building docker just type `make build` in the source tree, I'm not sure is it inside a container.
4, nothing else but GFW.

Is there something wrong?  Thank you for reply.

<img width="581" alt="c8473225-265a-4db1-b606-e76e6da6bf1b" src="https://cloud.githubusercontent.com/assets/1065112/22845597/604bf56c-f01e-11e6-8e4a-cfd391d2dc1b.png">

<img width="736" alt="295ede5d-9abb-493a-a899-9e4a93f86e53" src="https://cloud.githubusercontent.com/assets/1065112/22845619/7e9b75b0-f01e-11e6-8fd5-9241eefa61b4.png">

<img width="735" alt="aae914aa-364b-4fc1-9b61-2ca441818c8e" src="https://cloud.githubusercontent.com/assets/1065112/22845654/a16db706-f01e-11e6-848f-35925356571a.png">

**Comment by thaJeztah** [comment]
Where does the 120.52.72.23 IP-address come from? Doing a reverse lookup for that IP address doesn't resolve anything. For me, the IP resolves to 91.189.95.83, which resolves to haetae.canonical.com

On 91.189.95.83, all files are there;

<img width="943" alt="screen shot 2017-02-10 at 2 13 47 pm" src="https://cloud.githubusercontent.com/assets/1804568/22846440/65ca9584-ef9c-11e6-8453-86e9cece8df0.png">

**Comment by J-Liu** [comment]
120.52.72.23 IP-address atomically by DNS?
I can get the `bz2` file right now, and sure I have `bzip2` and `gunzip` on my system, but `make binary` still get the same error.  I really have no idea about it...

<img width="733" alt="425172fa-aa40-4977-804f-8becc55cee8d" src="https://cloud.githubusercontent.com/assets/1065112/22858499/7af71162-f0fa-11e6-9faf-bd0c841a0c58.png">

<img width="681" alt="54630d47-5c31-4b6f-b112-4515ce0d5139" src="https://cloud.githubusercontent.com/assets/1065112/22858505/a0ef30f2-f0fa-11e6-9d4c-1e4064621270.png">

**Comment by xinbinhao** [comment]
@J-Liu is this question ok?

**Comment by J-Liu** [comment]
@xinbinhao The problem is gone, but I didn't get the opportunity to working on docker.

**Comment by left2right** [comment]
@J-Liu how could you fix this problem?

**Comment by J-Liu** [comment]
@left2right Done.
