### ISSUE TITLE
Missing bash completion for dockerd/docker run --init

### ISSUE THREAD

**Issue by flx42** [docker/docker#30263]
1.13.0 release note:
> Add boolean flag --init on dockerd and on docker run to use tini a zombie-reaping init process as PID 1 #26061 #28037

But it looks like this option is missing from the bash completion script:
https://github.com/docker/docker/blob/e91dbba7ff62a92bd395bc419f522fa66618ae7b/contrib/completion/bash/docker#L1733-L1747
https://github.com/docker/docker/blob/e91dbba7ff62a92bd395bc419f522fa66618ae7b/contrib/completion/bash/docker#L1399-L1404

cc @albers

**Comment by albers** [comment]
Thanks for spotting this.
#dibs

**Comment by albers** [comment]
#dibs

**Comment by albers** [comment]
@GordonTheTurtle?
