### ISSUE TITLE
Docker exposed port unreachable

### ISSUE THREAD

**Issue by Durisvk** [docker/docker#30293]
I am running Node JS application on docker container. It is 100% working because if I run it without docker it works.

Problem is the exposed port 3002 doesn't work in browser. Nmap shows this port is available and opened but it doesn't work in browser.

I have the second app working on exposed port 3001 also through docker. This one does work. What could be the problem?

**Comment by aboch** [comment]
@Durisvk 
> What could be the problem?

We need more information to answer this question.
Please attach the o/p of `docker info`, what daemon flags you specify, how are you running your container, which network, or are you running a swarm service...

**Comment by Durisvk** [comment]
Sorry I didn't know what you need so I didn't attach anything to the question.

---------- `$ sudo docker info` ----------------

Containers: 4
 Running: 1
 Paused: 0
 Stopped: 3
Images: 18
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 29
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-91-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: juraj-Lenovo-IdeaPad-S510p
ID: 7EDH:JFUL:GEM6:MG7T:MAI5:TP5J:QMQ5:33CL:OZPL:CDLN:LQPJ:GF2L
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

------------- `Dockerfile` -------------

# create a file named Dockerfile
FROM node:7.4.0-alpine

RUN mkdir /app
WORKDIR /app

COPY package.json /app
RUN npm install
RUN npm install -g lab

COPY . /app

EXPOSE 3002

CMD ["npm", "start"]


--------------- `docker-compose.yml` ---------------

version: "2"
services:
  soho-api:
    build: .
    image: messenger-bot:0.1
    container_name: messenger-bot
    environment:
      NODE_ENV: development
    ports:
      - "3002:3002"
    volumes:
      - ./src:/app/src

------------ `deploy.sh` -------------

#!/bin/sh
sudo docker stop messenger-bot
sudo docker rm messenger-bot
sudo docker rmi messenger-bot:0.1
sudo docker-compose build
sudo docker-compose up -d


-------------------------------------------

I run my container with: `$ bash deploy.sh` command.

**Comment by thaJeztah** [comment]
Without access / insight into the app itself, I don't think we'll be able to help easily. Given that the other app works correctly, I'm also wondering if this is an actual bug, or something in your application (or applications configuration)

What IP address is your application listening on? Make sure it listens on `0.0.0.0:3002`, not on `127.0.0.1:3002`

**Comment by Durisvk** [comment]
@thaJeztah Brilliant, You've helped me solve the problem. Thank You

The problem was with this line:
`server.connection({ port: 3002, host: 'localhost' });`
(I am using HapiJS).

I  should have done this:
`server.connection({ port: 3002 });`

(remove localhost as a host!)

Please close this issue, everything's alright now, working.
