### ISSUE TITLE
Windows docker cannot pull microsoft/windowsservercore if a virus scanner is installed

### ISSUE THREAD

**Issue by drnybble** [docker/docker#30296]
Please see this issue that has been logged for months but no action:
  https://github.com/Microsoft/Virtualization-Documentation/issues/355
Maybe it is not logged in the correct place? so I am logging an issue here.

**Description**

Please see https://github.com/Microsoft/Virtualization-Documentation/issues/355 for details from many people who have encountered this problem in different contexts.

Having a virus scanner installed prevents any Docker images from being loaded on Windows Server 2016.

**Steps to reproduce the issue:**
1. Install docker on Windows Server 2016
2. Symantec Endpoint Protection 12.1.6 is installed (or any other scanner listed in the aforementioned issue)
3. docker pull microsoft/windowsservercore OR docker pull microsoft/nanoserver

**Describe the results you received:**

The image is downloaded and extracted. Sometime after the extraction completes the pull fails with an error:
bce2fbc256ea: Extracting [==================================================>] 252.7 MB/252.7 MB
3ac17e2e6106: Download complete
failed to register layer: re-exec error: exit status 1: output: ProcessUtilityVMImage C:\ProgramData\docker\windowsfilter\47bb01e457a6b11b3dad02d3bfe3b3e84f7ac24e208685e282ead787d0292567\UtilityVM: The process cannot access the file because it is being used by another process.

**Describe the results you expected:**

Able to pull microsoft/windowsservercore OR microsoft/nanoserver

**Additional information you deem important (e.g. issue happens only occasionally):**

Reported by many people for a variety of different virus scanners. It does not appear that disabling the scanner or creating folder exclusion rules helps. Only completely uninstalling the scanner works which is not possible in many environments.

I also tried with the latest docker 1.14-dev with the same results.

**Output of `docker version`:**

```
Client:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.2-cs2-ws-beta
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null overlay
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.321.amd64fre.rs1_release_inmarket.161004-2338)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 32 GiB
Name: VOTTPAWEIN2016
ID: YA6Z:R7KB:MKR2:FKSX:PGZ2:P7FD:FWEA:GS5S:F7CC:TAJ4:P2Q4:QPS2
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

In this case Windows Server 2016 is a VM running under VMWare.

**Comment by friism** [comment]
@drnybble There's not really a lot that the Docker can do if you've elected to install software on your machine (antivirus in this case) that blocks Docker from operating. I recommend getting in touch with the people that implemented the software that's blocking Docker from working on your system. Microsoft has also helpfully published a guide to antivirus programmers, that you can reference: https://msdn.microsoft.com/en-us/windows/hardware/drivers/ifs/anti-virus-optimization-for-windows-containers

**Comment by drnybble** [comment]
I installed a trial version of Symantec Endpoint Protection 14 and indeed I am now able to pull images successfully. I will close this issue. However, folks have reported issues with a variety of AV packages:
- Norton 360
- Norton Internet Security
- Symantec Endpoint Protection
- BitDefender
- McAfee
At least this issue will alert them to upgrade to the latest or hound their AV provider!

**Comment by dukenukem7j** [comment]
I had the same error with "The process cannot access the file because it is being used by another process.". I tried to disable Kaspersky Internet Security, to add exclusion, but only after complete uninstall of KIS things are finally working.

**Comment by thaJeztah** [comment]
@dukenukem7j it may be worth opening a ticket with Kaspersky for that; I know there's other virus scanners that made changes to bring compatibility with Docker
