### ISSUE TITLE
Container loses external network access when added to default bridge

### ISSUE THREAD

**Issue by JoyceBabu** [docker/docker#30302]
I have a docker daemon running on 192.168.0.10. Subnet for default bridge network is 172.17.0.0/24. There is another user defined network ‘net-external’ with subnet 10.10.0.0/24. On my router I have added the route 10.10.0.0/24 via 192.168.0.10.

I am successfully able to ping to containers on the network `net-external` from my LAN, until I connect the container to th edefault bridge. But it is responding to pings from the docker host, it is only access from the LAN that is blocked.

If I add a default route for 172.17.0.0/24 on my router, the container responds to pings from the LAN on its docker0 ip. 

**Steps to reproduce the issue:**
On docker host (ip 192.168.0.10)

- `docker network create net-external --subnet 10.10.0.0/24`
- `docker run -d -ti --net net-external --ip 10.10.0.150 --name nginx nginx`
- `ping 10.10.0.150` (ping is successful)

On another machine on the same LAN network (lets call it `machine1`)
- `route add -net 10.10.0.0/24 gw 192.168.0.10`
- `ping 10.10.0.150` (ping is successful)

Back on docker host
- `docker network connect bridge nginx`
- `ping 10.10.0.150` (ping is successful)

On `machine1`
- `ping 10.10.0.150` (ping is timing out)

**Describe the results you received:**
Ping times out, when nginx is added to default network `bridge`

**Describe the results you expected:**
The container remains accessible on the the network, even when it is added to the network `bridge`.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
$ docker info
Containers: 18
 Running: 13
 Paused: 0
 Stopped: 5
Images: 74
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: weavemesh null overlay bridge host
Swarm: active
 NodeID: <removed>
 Is Manager: true
 ClusterID: <removed>
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.0.10
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-57-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.7 GiB
Name: ennexa
ID: ZJIB:ZUVY:X7GR:R44F:UMW5:4MDV:PKFK:TYAU:OCFI:T55C:4J6F:Q2AK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
physical

**Comment by sanimej** [comment]
This is likely because the container's default route changes when you attach to the default `bridge` network. When a container is connected to more than one network that can provide a default gw the network whose name is lexicographically lower is used. You can check the `route -n` output in the container before and after attaching to default `bridge` network. 

After attaching to the bridge network can you remove the default route, add it via the gateway IP for `net-external` network and see if that fixes the ping issue ?  `--cap-add NET_ADMIN` is required to modify the route inside the container.

**Comment by JoyceBabu** [comment]
I have upgraded to docker 1.13.0, and now I have lost external access completely.

I can `ping 10.10.0.1` successfully from LAN, but cannot ping any container.

The containers are accessible from the docker host.

**Comment by JoyceBabu** [comment]
@sanimej I am not sure whether the `route -n` output is relevant anymore, since I have lost external access completely. But here is the output before and after connecting to the `net-external` network.

**Before**

```root@1fec2fc3425d:/# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.10.0.1       0.0.0.0         UG    0      0        0 eth0
10.10.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
```

**After**
```root@1fec2fc3425d:/# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.17.0.1      0.0.0.0         UG    0      0        0 eth1
10.10.0.0       0.0.0.0         255.255.255.0   U     0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth1
```

Isn't the default route inside the container applicable only for connections originating from the container? My issue is with connections originating from outside the container.

**Comment by sanimej** [comment]
@JoyceBabu The reason the default route changes is because the name of the network `bridge` is lexicographically lower than the first network the container was connected to, `net-external`. A work around to avoid this is to name is differently, for ex: `anet-external` or something which is lexicographically lower than `bridge`

**Comment by JoyceBabu** [comment]
Thank you. It worked.
