### ISSUE TITLE
1.13.0 - system prune vs. images -f dangling=true: different behaviour

### ISSUE THREAD

**Issue by RRAlex** [docker/docker#30307]
**Description**
`docker system prune -f` is supposed to remove dangling images but images tagged `<none>` aren't necessarily removed. 
Meanwhile, `docker rmi $(docker images -f dangling=true)` will remove more images. 
Something is not coherent in one of those?

**Steps to reproduce the issue:**
1. Pull an image by a digest (docker pull image@sha256:...)
2. docker system prune -f
3. docker rmi $(docker images -f dangling=true)

**Describe the results you received:**
3rd command above still deletes an image.

**Describe the results you expected:**
Prune should have done all the work before the last command.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 31
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Linux Mint 18
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 30.99 GiB
Name: octet
ID: Z6SL:RSSC:M7BQ:NXJX:KHVZ:7IAZ:TIO2:G2QP:HKVC:NM76:ZWOH:KMVC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AlekSi** [comment]
I would like `docker system prune` to remove untagged images. If this is not going to be a default behavior, can we have a flag for that? It's useful after pulling newest `latest` images.

**Comment by mbelang** [comment]
On my end, the prune is deleting untagged images but I have an other behavior where it doesn't reclaim all reclaimable space.

```
$ docker system df
TYPE                TOTAL               ACTIVE              SIZE                RECLAIMABLE
Images              13                  0                   3.36 GB             3.36 GB (100%)
Containers          0                   0                   0 B                 0 B
Local Volumes       0                   0                   0 B                 0 B
```

```
$ docker system prune -f
Total reclaimed space: 0 B
```
**docker info:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 89
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.7.4-040704-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.58 GiB
Name: max-mac
ID: A2JJ:D7X4:67OO:IAJ5:OHU7:KKJU:HLM5:KVTP:K76Z:N7U4:GIMY:AGML
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I'm not sure if it is related to the issue and the fix that is being develop but prune is not acting as I was expected. I was under the impression that all images with no container should be deleted.

**Comment by mlaventure** [comment]
@AlekSi try using the `-a` flag. By default it was decided not to remove images without a container attached to them as people may just be using the machine as a build machine and doing so would erase their cache.

**Comment by AlekSi** [comment]
I use Docker with Drone CI. I don't want to remove, for example, latest `mysql:5.7` even if it doesn't have a container, but I want to remove previous versions of this tag. `-a` would remove the latest version, without this flag previous versions will not be removed.

I wonder what images `docker system prune` without `-a` removes?

This issue is about a difference in behavior and definition of the word "dangling". If you want to keep it, then I think:
1. Help message should be updated to describe what would be removed.
2. Some flag should be added to remove all untagged images.

**Comment by mlaventure** [comment]
@AlekSi oh, I didn't understand your first comment it seems.
 
#30330 should fix `system prune` so it also removes untagged images hence matching `dangling` definition in `docker  image -f dangling=true`
