### ISSUE TITLE
Packages for Photon OS are not available on yum.dockerproject.org

### ISSUE THREAD

**Issue by frapposelli** [docker/docker#30305]
**Description**

Can't install `docker-engine` on Photon OS by using:

```console
$ curl -sSL get.docker.com | sh
```

**Steps to reproduce the issue:**
1. Start a Photon OS machine
2. Run `curl -sSL get.docker.com | sh`

**Describe the results you received:**

```console
$ curl -sSL get.docker.com | sh
+ sudo -E sh -c 'sleep 3; tdnf -y install docker-engine'
Error: Failed to synchronize cache for repo 'Docker main Repository' from 'https://yum.dockerproject.org/repo/main/photon/1.0'
Disabling Repo: 'Docker main Repository'
No package docker-engine available
Error(1011) : No matching packages
```

Visit https://yum.dockerproject.org/repo/main and see no `photon` directory.

**Describe the results you expected:**

Expecting `docker-engine` to be installed on Photon OS.

**Comment by justincormack** [comment]
We do not ship packages for all the systems with build scripts in the repository, they are just there as a convenience for users wanting to build packages. The decision for what we ship is independent, and is a Docker decision not a decision of the open source project. I recommend you talk to @friism he should be able to help.
