### ISSUE TITLE
All volumes, containers and images gone after update to 1.13.0 

### ISSUE THREAD

**Issue by esBeee** [docker/docker#30316]
**Description**
I've just updated to 1.13.0 by clicking on the _Install now_ button (or whatever it is called exactly) in the _New Docker version available_ pop-up window. When Docker was back to _Docker is running_, all volumes were gone along with the containers and images.

**Steps to reproduce the issue:**
1. Update _Docker for Mac_ to 1.13.0

**Describe the results you received:**
- Docker updated to 1.13.0
- Images, volumes, containers gone

**Describe the results you expected:**
- Images, volumes, containers still exist

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: QQRQ:262B:QJ33:COUT:KJHA:G3ZI:U7YR:5GHL:DRKA:OFNC:CZM2:Y2LG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-01-20T14:11:30.259001582Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: esbeee
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by justincormack** [comment]
Please open Docker for Mac specific issues here https://github.com/docker/for-mac/issues

I will close this as it is specific to the Mac version.

It switched over to `overlay2` which means that it probably had to reformat the drive. The new version has checks for filesystem corruption which were missing in the old version. Unfortunately that means if you were running with a corrupted filesystem (which might cause all sorts of issues) you will have lost your containers.

**Comment by esBeee** [comment]
Reopened this issue [here](https://github.com/docker/for-mac/issues/1175).
