### ISSUE TITLE
IPv6 CIDR validation failing in docker version 1.13.0

### ISSUE THREAD

**Issue by lenovouser** [docker/docker#30315]
**Description**

Docker doesn't start anymore after upgrading to `v1.13.0` due to CIDR validation failing

**Steps to reproduce the issue:**

1. Have `--ipv6` and `--fixed-cidr-v6` enabled
2. Upgrade to Docker version 1.13.0, build 49bf474

**Describe the results you received:**

Docker doesn't startup anymore. Error message is:

```
Error starting daemon: Error initializing network controller: invalid CIDR address: "xxxx:xxxx:x:xxxx::/64"
```

**Describe the results you expected:**

Docker should start

**Additional information you deem important (e.g. issue happens only occasionally):**

The CIDR is correct, e.g. `0000:0000:0:0000::/64` is a valid CIDR block, even though it obviously doesn't exist. Also it was working in `v1.12.4`, where I got told to use `--fixed-cidr-v6` in #29386

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 37
Server Version: 1.13.0
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.4 GiB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical dedicated Debian 8 server

**Comment by justincormack** [comment]
cc @aboch

**Comment by thaJeztah** [comment]
Can you tell how you set the flag? Did you perhaps set it in a systemd unit file, including quotes?

I can reproduce this error with this; (notice the extra quotes);

```
dockerd --debug --iptables=false --fixed-cidr-v6="\"0000:0000:0:0000::/64\""
```

The error-message shows the _literal_ value, the quotes are not _added_ in the error;

```
dockerd --debug --iptables=false --fixed-cidr-v6="foobar"

Error starting daemon: Error initializing network controller: invalid CIDR address: foobar
```

So, I think this may be related to https://github.com/docker/docker/issues/29761

**Comment by thaJeztah** [comment]
ping @dnephin as well

**Comment by lenovouser** [comment]
Yep, I set it in a SystemD unit file like this:

```
--ipv6 --fixed-cidr-v6="0000:0000:0:0000::/64"
```

switching to

```
--ipv6 --fixed-cidr-v6 0000:0000:0:0000::/64
```

fixes it 👍 

It's weird though that this worked before.

**Comment by dnephin** [comment]
Glad it's fixed. We changed the flag parsing library in 1.13 and it no longer strips off unnecessary quotes (that are normally handled by the shell).
