### ISSUE TITLE
dockerd leaks ExecIds on failed exec -i

### ISSUE THREAD

**Issue by ijrandom** [docker/docker#30311]
Each ```docker exec -i``` command leaks ExecID (and consumes dockerd memory) if command is not present in the target container. The leak is permanent. ExecIDs will not be collected by dockerd background jobs

**Steps to reproduce the issue:**
1. sudo docker run -ti --rm --name test ubuntu bash
2. sudo docker exec -i test invalidcommand
3. sudo docker inspect test | grep -A 10 ExecIDs

**Describe the results you received:**
1. number of ExecIDs increasing by one per docker exec
2. dockerd memory usage is increasing

**Describe the results you expected:**
1. number of ExecIDs is zero
2. dockerd memory usage is not increasing

**Additional information you deem important (e.g. issue happens only occasionally):**
This issue may cause more problems than someone could expect from the description. For example: I have a zabbix monitoring which collects information each minute from each container by executing ```ifconfig eth0```. But not every container contains ```ifconfig```. In such situation I have observed about 2Gb memory leak per day for dockerd.

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Tue Jan 10 20:38:45 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 19
 Running: 19
 Paused: 0
 Stopped: 0
Images: 31
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: none
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 62.63 GiB
Name: forge
ID: ZPOD:35LZ:RAF6:RFIG:662U:2CKK:22HE:MYBM:FUBV:N2Q3:CG4Z:FQOH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Comment by fudali113** [comment]
rpc error: code = 2 desc = containerd: container not found
