### ISSUE TITLE
docker windows - time sync does not noticed docker host timezone

### ISSUE THREAD

**Issue by mattmeye** [docker/docker#30322]
hi,

on my windows dev mashine with new docker version 1.13 the host sync time now - yeah! thx for this update. but it only sync date & time - numbers, not the host timezone.

Example:

I operate from Europe/Berlin Timezone, it is now 16:45 in local time (utc 15:45) and docker containers are sync time to 16:45 - but - UTC not UTC+1

When change the timezone in windows to utc - time and zone is in sync - if i switch back to utc+1 timezone is not in sync.

**Comment by thaJeztah** [comment]
Timezone inside a container is separate from the host's timezone. There's some earlier discussions around this for linux containers; https://github.com/docker/docker/issues/3359, https://github.com/docker/docker/issues/12084, https://github.com/docker/docker/issues/27488, but I'm not sure what the equivalent is on a Windows container

/cc @johnstep ^^

**Comment by justincormack** [comment]
Are you talking about Docker for Windows running Linux containers or Windows containers?

How are you determining what is going on? How are your containers configured?

**Comment by mattmeye** [comment]
i have no special configuration for my containers:

#windows time is now 16:30 (utc+1 europe/berlin)

#create example container
docker run --name some-nginx -d nginx

#get time of the container
docker exec some-nginx date
# i get 16:30 utc

# change windows timezone to utc (15:30)
# restart docker service via guid
docker start some-nginx
docker exec some-nginx date
# i get 15:30 utc

**Comment by justincormack** [comment]
Ok, in that case can you open the issue here instead https://github.com/docker/for-win/issues as it is specific to Docker for Windows.

**Comment by justincormack** [comment]
Closing here as docker for Windows specific, please open as above.
