### ISSUE TITLE
docker inspect -f option not displaying keys

### ISSUE THREAD

**Issue by ronaldpetty** [docker/docker#30335]
**Description**

Keys are missing when using `inspect` subcommand with formatting.

**Steps to reproduce the issue:**
1. docker run image
2. docker inspect image -f '{{.ContainerConfig}}'

**Describe the results you received:**

Only values are returned.

```
$ docker inspect lab/websvr:0.2.0 -f '{{.ContainerConfig}}'
{90a56af49c64   false false false map[80/tcp:{}] false false false [PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin APACHE_RUN_USER=www-data APACHE_RUN_GROUP=www-data APACHE_LOG_DIR=/var/log/apache2] [/bin/sh -c #(nop)  CMD ["/usr/sbin/apache2" "-D" "FOREGROUND"]] <nil> true sha256:594979eaf75fc7fbabe1ff9e30da03b3513da09faac5653b52fa7fdff76a0017 map[]  [] false  [] map[maintainer:docker-lab]  <nil> []}
```

**Describe the results you expected:**

Key and values, or JSON (preferred.)

```
user@ubuntu:~/websvr$ docker inspect lab/websvr:0.2.0 | jq .[].ContainerConfig | head -5
{
  "Hostname": "90a56af49c64",
  "Domainname": "",
  "User": "",
  "AttachStdin": false,
...
```

**Output of `docker version`:**

```
user@ubuntu:~/websvr$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
user@ubuntu:~/websvr$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.842 GiB
Name: ubuntu
ID: FCZQ:DUQS:2TRC:B6SE:PPA3:64I7:3PFJ:MC26:UCGW:3GO7:BWZ3:VETT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMWare Fusion - Ubuntu 16.04.1 - latest stable docker (via get.docker.com)

**Comment by ronaldpetty** [comment]
Potentially related.  Autocomplete for the inspect command seems not be working as expected.  Once you hit the colon for tagging it autocompletes the repository name and not tags.

**Comment by thaJeztah** [comment]
The default output format is the "string" presentation that Go uses, for structs, that is only showing the values,

To output in `JSON`, prefix the template with json;

    --format 'json {{.ContainerConfig}}'

**Comment by thaJeztah** [comment]
You can find some other examples in the docs here; https://docs.docker.com/engine/admin/formatting/

**Comment by ronaldpetty** [comment]
Thank you.  Just to clarify, the default output of inspect is not using the same default output as inspect with the format flag?

**Comment by thaJeztah** [comment]
Correct, the `--format` option applies a go template. This allows you to format it in different ways (e.g., to just get the value of a single property). Formatting as JSON is one of the options, but there's other options as well;  for example when using `--format` on `docker ps` you can use `table`

**Comment by ronaldpetty** [comment]
OK, I can go (:)) with that.  

My two cents, I would use the same output if you don't specify something specifically (so I don't have to look it up!)  I am sure this is highly opinionated, but relying on build language DSLs are good for 'the' developers and less for 'other' developers. 

Thanks again, I appreciate the help.

**Comment by thaJeztah** [comment]
Hindsight is 20/20, there's also been discussion that the default format of `inspect` should have been a "human readable" presentation of the data, and JSON an _alternative_ output format. Changing this would be a breaking change, so we decided to keep the current format.

Happy to help, and thanks for the feedback, it is appreciated!

Let me close this issue, but feel free to continue the conversation
