### ISSUE TITLE
Cannot create transparent network on Windows 10: hnsCall failed in Win32: The remote procedure call failed. (0x6be)

### ISSUE THREAD

**Issue by heaths** [docker/docker#30342]
**Description**

I'm trying to create a transparent network on my Surface Pro 3 with Windows 10 (all updates applied). This worked with Docker 1.12 but after upgrading to 1.13 I had to recreate the networks which fails. I've removed all virtual networks from the Hyper-V management console and re-installed Docker. The DockerNAT vnet is created automatically, but after switching to Windows containers creating a transparent network fails.

**Steps to reproduce the issue:**
Run: `docker network create -d transparent wlan`

**Describe the results you received:**
Whether I specify the interface name or not (via the `com.docker.network.windowsshim.interface` option or not), I receive the following error:

> Error response from daemon: hnsCall failed in Win32: The remote procedure call failed. (0x6be)

**Describe the results you expected:**

The transparent network is created.

**Additional information you deem important (e.g. issue happens only occasionally):**

This works fine on my Lenovo X1 Carbon, on which I've been beta testing 1.13 for many months.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.24)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 3
Server Version: 1.13.0
Storage Driver: windowsfilter
 Windows: 
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.907 GiB
Name: SurfacePro3
ID: DTAI:B4FU:CVX6:LU7C:AYOM:CW6B:HDTQ:E4P7:B2LQ:5O4Y:7FKM:X56H
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 16
 System Time: 2017-01-21T08:52:13.5464519-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by heaths** [comment]
I should also note that if I run the same failed command again, a "Layered Wi-Fi" (my adapter name was "Wi-Fi" and if I rename it, says "Layered <name>") vnet is created and I get an hnsCall error that an "Object already exists".

**Comment by thaJeztah** [comment]
ping @msabansal ptal

**Comment by kallie-b** [comment]
@heaths -- can you please share the output of the following on your system?
get-vmswitch
get-netnat
get-containernetwork

**Comment by dirething** [comment]
I appear to be having the same or similar issue.  Here are the requested results before and after the error:

```
PS C:\Windows\system32> Get-ContainerNetwork

Name Id                                   Subnets           Mode SourceMac DNSServers DNSSuffix
---- --                                   -------           ---- --------- ---------- ---------
nat  27f1006d-1586-4152-9f45-e2b02feaef7f {172.30.176.0/20} NAT                                



PS C:\Windows\system32> get-netnat


Name                             : H27f1006d-1586-4152-9f45-e2b02feaef7f
ExternalIPInterfaceAddressPrefix : 
InternalIPInterfaceAddressPrefix : 172.30.176.1/20
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True




PS C:\Windows\system32> get-vmswitch

Name SwitchType NetAdapterInterfaceDescription
---- ---------- ------------------------------
nat  Internal                                 



PS C:\Windows\system32> docker network create -d transparent -o com.docker.network.windowsshim.networkname=TransparentNetwork TransparentNetwork
docker : Error response from daemon: hnsCall failed in Win32: The remote procedure call failed. (0x6be)
At line:1 char:1
+ docker network create -d transparent -o com.docker.network.windowsshi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...failed. (0x6be):String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

PS C:\Windows\system32> Get-ContainerNetwork

Name          Id                                   Subnets           Mode        SourceMac DNSServers DNSSuffix
----          --                                   -------           ----        --------- ---------- ---------
Layered Wi-Fi 3bd2f366-c1d1-43e2-80fb-145b7fe6e1ae                   Transparent                               
nat           27f1006d-1586-4152-9f45-e2b02feaef7f {172.30.176.0/20} NAT                                       



PS C:\Windows\system32> get-netnat


Name                             : H27f1006d-1586-4152-9f45-e2b02feaef7f
ExternalIPInterfaceAddressPrefix : 
InternalIPInterfaceAddressPrefix : 172.30.176.1/20
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True




PS C:\Windows\system32> get-vmswitch

Name          SwitchType NetAdapterInterfaceDescription
----          ---------- ------------------------------
nat           Internal                                 
Layered Wi-Fi Private                                  



PS C:\Windows\system32> docker network create -d transparent -o com.docker.network.windowsshim.networkname=TransparentNetwork TransparentNetwork
docker : Error response from daemon: HNS failed with error : {Object Exists} An attempt was made to create an object and the object name already existed.
At line:1 char:1
+ docker network create -d transparent -o com.docker.network.windowsshi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Error response ...lready existed.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 

PS C:\Windows\system32> 
```

**Comment by thaJeztah** [comment]
ping @kallie-b ptal :-)

**Comment by msabansal** [comment]
There is a fix for this in the next windows update

**Comment by heaths** [comment]
@msabansal you mean the Creator's update, or the next Patch Tuesday? Either way, you could probably close this issue then unless you wanted me to confirm and close after it ships.

**Comment by kallie-b** [comment]
The fix will be included in the next Patch Tuesday. And the fix addresses an issue related to the wifi adapter. It's probably fine to close this issue, but I'll remain subscribed to the thread just in case anyone has follow up questions after the fix is released.

**Comment by dirething** [comment]
Fix is in the pipeline, Understood.

If this is a WiFi related issue, until April 11, 2017 I should be able to set up transparent on machines that also have Ethernet adapters?  or machines that ONLY have Ethernet adapters? or have I made a poor assumption here and I should just wait for next month's patch cycle?

**Comment by thaJeztah** [comment]
Thanks all! Let me close this issue for housekeeping, but feel free to continue the discussion, and let us know once it's resolved 👍

**Comment by dineshgovindasamy** [comment]
This is only a Wi-Fi Issue. Ethernet Adapter will work. Please let us know if you face any issue with Ethernet.
thanks

**Comment by kallie-b** [comment]
And, just in case you need it, here's the syntax to bind to a specific network interface: 

C:\> docker network create -d transparent -o com.docker.network.windowsshim.interface="Ethernet 2" TransparentNet2

(https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking)

**Comment by dirething** [comment]
@kallie-b the 1703 update did a number on my machine, network dead, studio, and docker unusable with truly bizarre failures.  I had to do a system restore and reinstall most of my tools.

docker on my machine is now 17.05.0-ce-rc1

I can start from VS17 in the nat and debug, that is as far as I had gotten on this machine before.

I can add a network with -d transparent without error and I can launch (but not connect to) a docker started on that network.  When I docker network inspect the network it looks like the machine is there, but didn't get an address from DHCP.  

Possibly what I had read originally was out of date, so I attempted to follow the process in your link above but there does not appear to be any get-containernetwork powershell anymore and there is not any additional instruction on adding mac spoofing when running on a physical host.  This command definitely existed at the point I first commented here, so something has changed, or something is still broken from the windows updates.

I am probably doing something incorrectly here, but with the variety of changes I am uncertain what.

Sorry for being a noob, but with the amount of things that went wrong here I am no longer certain if I am doing something wrong, the instructions are wrong, or the machine is still wrong.  Could someone point me in a useful direction?

**Comment by dirething** [comment]
Looking like I am dumb here, inside the container there is an IP and in "docker network inspect <networkname>" there is no IP.  In hind sight I am guessing because that is only showing me configuration not current state and it treats DHCP as current state?  If this is normal then my only outstanding question is if "get-containernetwork" is supposed to have been removed or not.

**Comment by kallie-b** [comment]
@dirething -- So let me make sure I understand your machine state/issue here.

- You're using Windows 10, with Docker CE (Docker CE install instructions are [here](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10#1-install-docker-for-windows)), and all of the [latest Windows updates](https://support.microsoft.com/en-us/instantanswers/c4a6d3df-d0d4-42b6-0018-ca48577f9909/update-windows-10)
- After installing Docker CE on your machine, you [switched to Windows Containers](https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-10#2-switch-to-windows-containers)
- Now you're able to start Docker, but your containers do not have network connectivity. 

A question:
- Are you seeing network for all containers (i.e. containers created on the default 'nat' network), or just for containers connected to a transparent network?

**Comment by dirething** [comment]
@kallie-b 

yes, yes, & they have connectivity now

In the first attempts after updating from patch Tuesday neither nat or transparent worked, I started to notice a lot of other things amiss outside docker, eventually after doing a system restore and reinstalling to 17.05.0-ce-rc1, hyper-v and containers, nat worked, but transparent showed no address, or so I thought.

"docker network inspect TransparentNetwork" says there isn't an address on my transparent network container, but there is if you run an ipconfig /all from inside docker exec, at least after a minute or two it would seem.  if this is normal, so be it, but I was unsuccessful at finding an example to compare to when using DHCP.

In trying to follow your instructions in your earlier reply (https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-networking) I noticed I no longer had the"get-containernetwork" powershell.  This was definitely there before as I had to use it several times to clean up when I was first trying to create the transparent network.

If that is supposed to be gone in this version and inspect is not supposed to show you DHCP addresses then possibly I have it all working correctly at this point and I would thank you for your time and apologize for not catching on faster on my own.  If these outcomes are not expected any suggestion on how to proceed in correcting the issue would be appreciated.

Hopefully at this point it is just my misunderstanding

**Comment by kallie-b** [comment]
@dirething -- apologies for the delayed reply. I don't believe the behavior you're describing is normal. If you have a transparent network on your host, "TransparentNetwork", and you create a container to be attached to that transparent network, you should see the container listed as an endpoint when you do "docker network inspect TransparentNetwork." 

Specifically, if you follow these commands:

```
C:\> docker network create -d transparent TransparentNetwork
C:\> docker run --network TransparentNetwork microsoft/nanoserver
C:\> docker network inspect TransparentNetwork
```

You should see the ID of the container listed as an endpoint in the output of "docker network inspect TransparentNetwork." 

Is that not the case for you?

**Comment by dirething** [comment]
@kallie-b  No worries, thanks for putting up with my confusion.

Running your commands (but with a different network name since I already had that name)

It shows in the inspect, but without an address:

```
PS C:\WINDOWS\system32> docker network inspect TransparentNetwork1
[
    {
        "Name": "TransparentNetwork1",
        "Id": "6f5b3db1ed1df2eb6f2d780c3f5335c2249dc31a6cd43abec4d13f7bad4e944d",
        "Created": "2017-04-28T14:16:10.355859-04:00",
        "Scope": "local",
        "Driver": "transparent",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "windows",
            "Options": {},
            "Config": [
                {
                    "Subnet": "0.0.0.0/0",
                    "Gateway": "0.0.0.0"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "Containers": {
            "71662d5871b5c4605290aedd3a352a5d659afc6c39dc9427ef86d5de3951103b": {
                "Name": "sharp_jackson",
                "EndpointID": "9b99ae870b72a667c5e76e0dbf9c6e08a7ec7f7edc8a5c4dd61607bf03b1d535",
                "MacAddress": "00:15:5d:50:d8:a1",
                "IPv4Address": "",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.windowsshim.hnsid": "fb13d025-b41e-4d72-a8ad-00e0a7887e1a"
        },
        "Labels": {}
    }
]
```

but if I connect to it interactively and check the ip from the container's point of view it has one:

```PS C:\WINDOWS\system32> docker run -i --network TransparentNetwork1 microsoft/nanoserver
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>ipconfig /all
ipconfig /all

Windows IP Configuration

   Host Name . . . . . . . . . . . . : 71662d5871b5
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : sti.local

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : sti.local
   Description . . . . . . . . . . . : Microsoft Hyper-V Network Adapter
   Physical Address. . . . . . . . . : 00-15-5D-50-D8-A1
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : fe80::f904:27d8:c456:69d2%4(Preferred)
   IPv4 Address. . . . . . . . . . . : 10.0.101.206(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.0.0
   Lease Obtained. . . . . . . . . . : Friday, April 28, 2017 2:27:51 PM
   Lease Expires . . . . . . . . . . : Friday, April 28, 2017 3:27:51 PM
   Default Gateway . . . . . . . . . : 10.0.254.254
   DHCP Server . . . . . . . . . . . : 10.0.1.1
   DHCPv6 IAID . . . . . . . . . . . : 67114333
   DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-20-95-41-FE-00-15-5D-50-D8-A1
   DNS Servers . . . . . . . . . . . : 10.0.1.1
                                       10.0.1.2
   NetBIOS over Tcpip. . . . . . . . : Disabled

C:\>
```

this is the part I am guessing might possibly be normal and I have just misunderstood

the disappearance of the containernetwork powershell commands still confuses me, but I now see others having this problem like: https://github.com/docker/for-win/issues/679 so if the inspect result is as expected I can probably leave you alone.

**Comment by nexusguy59** [comment]
Hello Everyone,

          I am very new to docker on WIndows, I have tried everything i can think of and searched google till I am blue in the face.

Here is how I tried to add a network to my docker for windows:
PS C:\Users\Administrator> **docker network create -d transparent -o com.docker.network.windowsshim.interface="Ethernet 3"
 tlan1**
_Error response from daemon: plugin "transparent" not found_

PS C:\Users\Administrator> **get-vmswitch**

Name               SwitchType NetAdapterInterfaceDescription
----               ---------- ------------------------------
nat                Internal
DockerNAT          Internal
Layered_Ethernet 2 External   Intel(R) Ethernet Connection (2) I219-LM

PS C:\Users\Administrator> **get-netnat**


Name                             : Hec9ffadc-03ab-46ca-b0c2-e8977d093b52
ExternalIPInterfaceAddressPrefix :
InternalIPInterfaceAddressPrefix : 172.17.80.0/20
IcmpQueryTimeout                 : 30
TcpEstablishedConnectionTimeout  : 1800
TcpTransientConnectionTimeout    : 120
TcpFilteringBehavior             : AddressDependentFiltering
UdpFilteringBehavior             : AddressDependentFiltering
UdpIdleSessionTimeout            : 120
UdpInboundRefresh                : False
Store                            : Local
Active                           : True

Name                                                             Id                                   Subnets
----                                                             --                                   -------
nat                                                              ec9ffadc-03ab-46ca-b0c2-e8977d093b52 {172.17.80.0/20}
DockerNAT (1)                                                    0590a357-1ac2-4d0e-901c-e1abb2f3f01a {172.24.64.0/20}
e6b08d31c3e77fa8b64ce15dd543ac972a6aa9d98b62d2ea43f67baa55bf36c0 5806fad2-95b5-42db-a0db-4407dc52b74e {}

I am confused and lost not sure what to do from here. Any help would be greatly appreciated.

Thanks,
Michael

**Comment by msabansal** [comment]
@nexusguy59 Try updating docker. Works fine on latest docker:

PS C:\Windows\system32> docker version
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
PS C:\Windows\system32> docker network create -d transparent -o com.docker.network.windowsshim.interface="Ethernet" tlan1
9d63589cf0df37351f04ec4a0d5f8fa46afa9952c647a60a53a5cfeeaab8dc63

**Comment by MythreyaK** [comment]
Similar Issue [Cannot create Transparent Network](https://github.com/docker/for-win/issues/3592#issue-422684847)

**Comment by CXW0504** [comment]
docker version:
C:\Users\Administrator\Desktop>docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 22.99GiB
Name: linuxkit-00155d010224
ID: KTFL:YSU3:VMIN:SYCT:74JV:6LUM:UCRH:DYD7:H6IF:PPVO:WO4S:HDI4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 22
 Goroutines: 46
 System Time: 2019-06-20T22:01:07.3925473Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
support   macvlan commd
