### ISSUE TITLE
can --insecure-registry support "all" 

### ISSUE THREAD

**Issue by allan1991** [docker/docker#30347]
Now, when visiting a registry with http addr, we have to add the `--insecure-registry` in docker daemon configuration, and restart docker daemon. Can `--insecure-registry` supports something that means supporting all http registry, like `*` or `all`? If that, user who uses insecure registries will config it once, and no needs to restart docker daemon every time adding a new item.

**Comment by cpuguy83** [comment]
I think I would be -1 to this as it's just lazy (to the extreme) and detrimental to push/pull security.

Why not add the CA to the the list of trusted CA's?

**Comment by allan1991** [comment]
I don't think so, it's not lazy, it's a choice for users. In production environment, users often deploy a registry in their private network,  or service provider has to support user’s private insecure registry. I don't think it's a good idea to ask users to do that. After all, it's a private registry. And in my opinion, we should provide the ability, and leave the choice to users.

**Comment by justincormack** [comment]
I think you can probably just set it to `0.0.0.0/0`?

**Comment by thaJeztah** [comment]
Yes, `0.0.0.0/0` should work, but using that is not a wise choice, as any communication to _any_ registry (which may be outside your private network) will allow falling back to a non-TLS connection.

I'll close this issue, because it looks like this is possible, but feel free to comment after I closed

**Comment by allan1991** [comment]
Thank you very much, that's what I want.
