### ISSUE TITLE
Docker 1.13.0  Swarm Mode - consistent packet loss when pinging containers using custom hostname created with "templates" feature

### ISSUE THREAD

**Issue by ash9002** [docker/docker#30353]
**Description**

I've created a swarm using the following command:

`docker service create -e SERVICE_PORTS="15672" --name rmq --network rnet --constraint "node.role != manager" -e RABBITMQ_ERLANG_COOKIE='myrabbitcookie' --replicas 4 --hostname="{{.Service.Name}}{{.Task.Slot}}" rabbitmq`

Four replicated RabbitMQ containers are successfully started with the following hostnames: `rmq1, rmq2, rmq3, rmq4`. However, I'm having issues successfully connecting containers using these custom hostnames created with `--hostname` for `docker service create` For example: `ping rmq1` consistently results in some amount of packet loss. 

Therefore, I'm unable to create a RabbitMQ cluster, which uses hostnames to identify each node in the cluster. For example `rabbitmqctl join_cluster rabbit@rmq1` fails. 

**Steps to reproduce the issue:**
1. Create overlay network with `docker network create -d overlay rnet`

2. Create service using `docker service create -e SERVICE_PORTS="15672" --name rmq --network rnet --constraint "node.role != manager" -e RABBITMQ_ERLANG_COOKIE='myrabbitcookie' --replicas 4 --hostname="{{.Service.Name}}{{.Task.Slot}}" rabbitmq`

3. Get hostname of one of the replicated containers (say `container-A`):
 `docker exec -it container-A /bin/bash -c "hostname"`

4. Repeat previous step for a different replicated container (`container-B`)

5. Attempt to ping one of the containers from the other using hostname: `ping rmq2`

6. Get RabbitMQ node name from `container-A` using: `docker exec -it container-A /bin/bash -c "rabbitmqctl cluster_status"`. Say the RabbitMQ node name is `rabbit@rmq1`

7. From `container-B`, run the following: 

- `docker exec -it container-B /bin/bash -c "stop_app"`

- `docker exec -it container-B /bin/bash -c "reset"`

- `docker exec -it container-B /bin/bash -c "rabbitmqctl join_cluster rabbit@rmq1"`

**Describe the results you received:**

1.  Packet loss when pinging containers using hostnames:
`^C--- rmq1 ping statistics ---`
`10 packets transmitted, 1 packets received, 90% packet loss`

2. Unable to create RabbitMQ cluster. Receive following error:
`Error: unable to connect to nodes [rabbit@rmq1]: nodedown`

**Describe the results you expected:**
I expected 0% packet loss when pinging the containers, which is what happens when I exclude the `--hostname` option from `docker service create` and use the default random hostnames.

I expected to be able to create the RabbitMQ cluster, which also happens when using default random hostnames and excluding `--hostname` from `docker service create`

**Additional information you deem important (e.g. issue happens only occasionally):**
I receive 0% packet loss when I use the overlay IP to ping between the 4 replicated containers

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 7
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-11518725-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.338 GB
 Data Space Total: 107.4 GB
 Data Space Available: 1.114 GB
 Metadata Space Used: 4.391 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 1.114 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: k1fvva2a4zse89yzw1aix2izr
 Is Manager: false
 Node Address: 192.168.1.178
 Manager Addresses:
  192.168.1.176:2377
  192.168.1.179:2377
  192.168.1.180:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: worker-2
ID: HC23:G72K:NPST:2MQB:OURN:RGVK:T3TS:C7L7:JVSX:566Q:J3LV:NKXW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

- 3-node Swarm Mode cluster (3 CentOS VMs in VirtualBox)
- Host machine running Mac OS X 10.12.2 (16C67)
- Using `latest` official RabbitMQ image from Docker Hub

**Comment by thaJeztah** [comment]
I think this is expected; `hostname` is only local to the container itself, and not used to discover a container on the network. To find the names and IP-addresses of a task, you can `nslookup tasks.<servicename>`, which returns those; see https://docs.docker.com/engine/swarm/networking/#/use-swarm-mode-service-discovery

I _did_ see something interesting, i.e. that if a custom hostname is set, the name of the host itself is overwritten in that response;

`docker exec` into task `rmq.2.6em3q6uvh5y9h66mv3if12mif` (hostname `rmq2`);

```
docker exec -it b25e721a4240 sh                                                                                                                                                                                                                                                                                                                / # nslookup tasks.rmq
nslookup: can't resolve '(null)': Name does not resolve

Name:      tasks.rmq
Address 1: 10.0.2.4 rmq2
Address 2: 10.0.2.5 rmq.3.qpgka88kqhrn36u01jb1ba73v.rnet
Address 3: 10.0.2.6 rmq.4.coqzw2grxhwgocdodyn7sydqa.rnet
Address 4: 10.0.2.3 rmq.1.edo8guq2tft50fr8j3k0it1q9.rnet
```

Although the other name alsol works;

```
/ # ping rmq.2.6em3q6uvh5y9h66mv3if12mif
PING rmq.2.6em3q6uvh5y9h66mv3if12mif (10.0.2.4): 56 data bytes
64 bytes from 10.0.2.4: seq=0 ttl=64 time=0.031 ms
64 bytes from 10.0.2.4: seq=1 ttl=64 time=0.059 ms
64 bytes from 10.0.2.4: seq=2 ttl=64 time=0.056 ms
```

**Comment by thaJeztah** [comment]
So, I don't think there's a bug here, but let me know if there's something I misunderstood

**Comment by ash9002** [comment]
Many thanks @thaJeztah - the behaviour makes sense given your explanation.  One more more question:

Can you explain why pinging the default hostname, which by default is also the container ID, works? 
eg. `ping b25e721a4240`. Is it merely because it corresponds to the container ID and each container is somehow aware of the other container IDs in the cluster?

**Comment by thaJeztah** [comment]
> Can you explain why pinging the default hostname, which by default is also the container ID, works?

That's a good question, and I don't have a direct answer. Possibly @sanimej is able to answer that :smile:

**Comment by thaJeztah** [comment]
Actually, I recall this being added in docker 1.12; see https://github.com/docker/docker/pull/21901

**Comment by ash9002** [comment]
@thaJeztah many thanks for sharing the link, all makes sense now. I'll close the issue - however it would be useful to have similar functionality for custom hostnames if possible in future.
