### ISSUE TITLE
Issue while starting Docker service.

### ISSUE THREAD

**Issue by vchibber** [docker/docker#30354]
**Description**

**Steps to reproduce the issue:**

```
sudo yum update
sudo yum install docker-engine
sudo service docker start
```

**Describe the results you received:**

```
Redirecting to /bin/systemctl start  docker.service
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
```

`journalctl -xe` shows below result :-1: 

```
Jan 22 21:48:30 va10dlvpoc145 sudo[3107]:  ac51178 : TTY=pts/0 ; PWD=/usr/bin ; USER=root ; COMMAND=/sbin/service docker start
Jan 22 21:48:30 va10dlvpoc145 polkitd[629]: Registered Authentication Agent for unix-process:3108:176305 (system bus name :1.64 [/usr/bin/pkttyagent --notify-fd 5 --fal
Jan 22 21:48:30 va10dlvpoc145 systemd[1]: Cannot add dependency job for unit microcode.service, ignoring: Unit is not loaded properly: Invalid argument.
Jan 22 21:48:30 va10dlvpoc145 systemd[1]: Starting Docker Application Container Engine...
-- Subject: Unit docker.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has begun starting up.
Jan 22 21:48:30 va10dlvpoc145 docker[3125]: Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
Jan 22 21:48:30 va10dlvpoc145 docker[3125]: no sockets found via socket activation: make sure the service was started by systemd
Jan 22 21:48:30 va10dlvpoc145 systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Jan 22 21:48:30 va10dlvpoc145 systemd[1]: Failed to start Docker Application Container Engine.
-- Subject: Unit docker.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
--
-- Unit docker.service has failed.
--
-- The result is failed.
Jan 22 21:48:30 va10dlvpoc145 systemd[1]: Unit docker.service entered failed state.
Jan 22 21:48:30 va10dlvpoc145 systemd[1]: docker.service failed.
Jan 22 21:48:30 va10dlvpoc145 polkitd[629]: Unregistered Authentication Agent for unix-process:3108:176305 (system bus name :1.64, object path /org/freedesktop/PolicyKi
~
```

```
[ac51178@va10dlvpoc145 bin]$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
```

**Describe the results you expected:**

The Docker Service start start as expected.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64



```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Its a virtual a Virtual machine with RHEL 7.3 with below details 

Linux va10dlvpoc145 3.10.0-514.2.2.el7.x86_64 #1 SMP Wed Nov 16 13:15:13 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

I have to setup Docker Data Center on couple of virtual machines. I was able to finish but then my virtual machine crashed and i need to redo this. Now am stuck with the docker  engine installer.

Would appreciate quick help.

**Comment by subbu05** [comment]
Install docker-engine-selinux-1.13.0 and restart the vm and check.

**Comment by vchibber** [comment]
Hi ,

I tried rebooting it multiple times but still the same.

Thanks
Varun

**Comment by thaJeztah** [comment]
@vchibber looking at this message;

```
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly.
```

It looks like you are running with an outdated or customised systemd unit file. Can you show the content of your docker unit-file? This should probably work;

```
sudo systemctl cat docker.service
```

**Comment by thaJeztah** [comment]
The message `no sockets found via socket activation: make sure the service was started by systemd` may be the reason it's not starting; see the "**important**" message at the top of the docker 1.12 release notes; https://github.com/docker/docker/releases/tag/v1.12.6

**Comment by vchibber** [comment]
Thanks for the quick response. Let me check and get back to you.

**Comment by vchibber** [comment]
I amusing docker version1.13.0.
But the below details are for 1.12.6.

Thanks
Varun

**Comment by thaJeztah** [comment]
Correct, the change was made in docker 1.12, so mentioned in the changelog for 1.12. If you upgraded from (e.g.) 1.10, or 1.11 to 1.13 the same applies obviously

**Comment by vchibber** [comment]
I followed that link and I don't see any issue.there Is no
Requires=docker.socket in the current file I have. In fact I compared the
1.12.0 and 1.13.0. I have the 1.13.0 on my system which has
firewalls.service after network.target.

I didn't have docker installed on this VM. I just did a yum update and
pulled the latest version I.e 1.13.0. And it's been giving this issue. I
tried removing docker engine and installing it back.

I have another VM which had previous version I.e 1.12.6 and that was
working fine. I upgraded the docker on that VM to 1.13.0 and that one is
still working. I mean even after upgrade.

**Comment by thaJeztah** [comment]
What does your `ExecStart` look like? The `Command "daemon" is deprecated` message should come from _somewhere_, if it's [not in your unit file](https://github.com/docker/docker/blob/v1.13.0/contrib/init/systemd/docker.service.rpm#L11)

Do you have a drop-in file installed that overrides the `ExecCommand`?

**Comment by vchibber** [comment]
You are right. I didn't see the drop-in files. Let me check that

**Comment by vchibber** [comment]
There was a drop-in file after removing which I was able to start it
successfully.

Thanks a lot for your prompt respons and support.

Thanks
Varun

**Comment by thaJeztah** [comment]
You're welcome! Happy to hear it's resolved 👍 let me close this issue, but feel free to comment after that
