### ISSUE TITLE
container renaming

### ISSUE THREAD

**Issue by dhrp** [docker/docker#3036]
I would be nice if we could rename a container (and/or remove the container name)

The problem I face today is that I might depend on container naming to determine if a container is already running, or otherwise present on a system. But If I have to remove the actual container to remove the name I risk destroying data.

I'd suggest just naming the command 'rename' or just 'name' 

Removing the container name could be ``docker name <containerid> "" ``

**Comment by elsonrodriguez** [comment]
+1, for various silly reasons.

**Comment by chatmoa** [comment]
+1

**Comment by ronniewang** [comment]
+1
