### ISSUE TITLE
docker does not release mem after running docker-cp

### ISSUE THREAD

**Issue by vmindru** [docker/docker#30366]
this is related to https://github.com/docker/docker/issues/30365 

after executing `docker cp  container:path localpath` docker would not release the memory consumed during command execution. 

how to reproduce

```
docker exec big_pare dd if=/dev/urandom of=/root/file bs=10M count=100
docker cp big_pare:/root/file ./file4
top -d 0.5 -n 1 -b | grep docker
```

after docker cp is finished observe high docker mem usage, this will stay around until docker restart. 

```
[vmindru@vmutil docker-cp]$ top -d 0.5 -n 1 -b | grep docker
20736 root      20   0 3406456 2.169g   6088 S   0.0 78.1   0:04.41 dockerd-current
20743 root      20   0  207272   3576   1536 S   0.0  0.1   0:00.03 docker-containe
[vmindru@vmutil docker-cp]$ 
```

expected behavior:
release the memory as soon as docker cp process ends in a timely manner 

docker version:
```
[vmindru@vmutil docker-cp]$ docker --version
Docker version 1.12.5, build 047e51b/1.12.5
[vmindru@vmutil docker-cp]$ uname -a
Linux vmutil 3.10.0-514.2.2.el7.x86_64 #1 SMP Wed Nov 16 13:15:13 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
[vmindru@vmutil docker-cp]$ 
```

**Comment by thaJeztah** [comment]
possibly related https://github.com/docker/docker/issues/29282#issuecomment-273794870

**Comment by unclejack** [comment]
I'm closing this in favor of https://github.com/docker/docker/issues/30365.

Please continue the discussion on that issue.
