### ISSUE TITLE
remove "kickass" from name generator adjectives

### ISSUE THREAD

**Issue by Thynix** [docker/docker#30374]
As fun as "kickass" is, it's uncomfortable to be presented with it - or other curse words - in some settings, such as at work. (Admittedly depending on the work environment.) I don't want to have to put something like "kickass_thompson" into documentation. (I could use the container ID, but still.)

**Comment by Thynix** [comment]
I'm working on a pull request for this.

**Comment by shaynewang** [comment]
Hello @Thynix you could use `docker run --name "custom name"` to specify container names. for your reference [https://docs.docker.com/engine/reference/run/#/name---name](url)

Thanks!
