### ISSUE TITLE
ubuntu 16.04 container: fail to map "/var/run/mysqld/mysqld.sock"

### ISSUE THREAD

**Issue by igenyar** [docker/docker#30386]
**Description**
BUG REPORT INFORMATION

**Steps to reproduce the issue:**
1. edit a Dockerfile with followings

    FROM ubuntu:16.04
ENV container docker
ENV init /lib/systemd/systemd

    RUN apt-get update
RUN apt-get install -y mysql-client
VOLUME [ "/sys/fs/cgroup" ]
ENTRYPOINT ["/lib/systemd/systemd"]

2. install mysql server on host, make sure /var/run/mysqld/mysqld.sock exists
3. run docker container like below
sudo docker run --privileged -d -v /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -it image_name

**Describe the results you received:**
cannot find /var/run/mysqld/mysqld.sock in container

**Describe the results you expected:**
expect /var/run/mysqld/mysqld.sock in container

**Additional information you deem important (e.g. issue happens only occasionally):**
+ /sys/fs/cgroup is mapped correctly
+ used to work on 12.04 container

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:33:38 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 258
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-915484-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 6.434 GB
 Data Space Total: 107.4 GB
 Data Space Available: 10.84 GB
 Metadata Space Used: 12.41 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.135 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-36-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.5 MiB
Name: ubuntu-512mb-nyc3-01
ID: 2UTO:RNJS:IVRJ:QYY7:ARHY:5E6W:KCSD:VLEX:RSNJ:ZCYY:4US7:HVLD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Do you have some more details? What does the container `inspect` look like? Does the directory tree for the container path exist?
Are you sure you are talking to the a daemon on the same host?

**Comment by igenyar** [comment]
**Output of `docker inspect`:**

Note, for privacy only "Mounts" is shown

```
        "Mounts": [
            {
                "Source": "/var/run/mysqld/mysqld.sock",
                "Destination": "/var/run/mysqld/mysqld.sock",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/sys/fs/cgroup",
                "Destination": "/sys/fs/cgroup",
                "Mode": "ro",
                "RW": false,
                "Propagation": "rprivate"
            }
        ],
```

The directory tree of "/var/run/mysqld" does not exist in the container if this is what you ask.
```
$ docker exec -ti ... ls -1 /var/run/
agetty.reload
apache2
initctl
lock
log
mount
network
sendsigs.omit.d
shm
systemd
user
utmp
```

Not sure about your last question, but they are all on the same host. If you want to run some commands to check, I can check for you and supply more info.

The thing is "/sys/fs/cgroup" is mounted correctly but not "/var/run/mysqld/mysqld.sock", and mysql is run correctly on the host.
```
$ docker exec -ti ... ls -1 /sys/fs
$ docker exec -ti f9528279cd0c ls -1 /sys/fs/
aufs
bpf
cgroup
ecryptfs
ext4
fuse
pstore
```

**Comment by thaJeztah** [comment]
@igenyar if you run your image with `--entrypoint=/bin/bash` (i.e., don't use `systemd` as command), is the `/var/run/mysqld/mysqld.sock` then present?

**Comment by igenyar** [comment]
@thaJeztah, yes, confirmed.

I guess this could be the work-around, but what if I still need "systemd"?

**Comment by thaJeztah** [comment]
May be tricky in this case, `systemd` is known to "mess" with just about anything on your system; in this case, possibly unmounting te mysql socket in the container.

Is there a reason you need systemd? In general, having a single process/service per container is recommended ([containers are not VMs](https://blog.docker.com/2016/03/containers-are-not-vms/)). There are alternatives though, if you really need to run multiple processes, e.g. http://www.supervisord.org, or http://www.skarnet.org/software/s6/, which don't need additional privileges in your container

**Comment by igenyar** [comment]
OK, I will check the links and thank you very much for the help!

**Comment by thaJeztah** [comment]
You're welcome! Let me close this issue, but feel free to continue the conversation
