### ISSUE TITLE
Request failing between containers

### ISSUE THREAD

**Issue by saman7766** [docker/docker#30384]
**Description**

Consul service on docker 1.12.3 on swarm mode was working perfectly , after upgrading to 1.13.0, health check request start failing with the next message `Get http://10.255.0.37:8765/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Steps to reproduce the issue:**
1. Create a Consul service inside a swarm with docker 1.13.0
2. Register a service in Consul (In my case this service is a Spring boot app that register itself on Consul)
3. Consul try to verify the service health but it fails

**Describe the results you received:**

Get http://10.255.0.37:8765/health: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Describe the results you expected:**

Healty service

**Output of `docker version`:**

Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-101637473-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.462 GB
 Data Space Total: 107.4 GB
 Data Space Available: 8.749 GB
 Metadata Space Used: 5.706 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 7r8tjdf5vsdpcwefe72gkhpi5
 Is Manager: true
 ClusterID: woxko6w9ulfec82j2u4b13v8g
 Managers: 3
 Nodes: 6
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.1.232.240
 Manager Addresses:
  10.1.232.240:2377
  10.1.232.241:2377
  10.1.232.242:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: FBWMSCENTOS01
ID: 54PE:IUGI:IQYE:62MY:3ZNM:Y6WA:KQW3:BSZ2:TW4H:NMNW:YKWF:QGNY
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 10.1.232.226:18444
 127.0.0.0/8
Live Restore Enabled: false

**Comment by cpuguy83** [comment]
Can you explain more? How is the service setup?
When you say healthcheck, is this a docker healthcheck of the consul instance, or healthchecks to something else?

**Comment by saman7766** [comment]
Hi and thanks for the reply, the healthcheck is between the Consul Instance and my app with spring boot it has nothing to do with Docker, it seems the issue is related to the new way to publishing ports in docker 1.13.0, for example i can make the request with curl from outside the swarm using one of the hosts IPs, but from inside a container in the swarm it throws Connection timed out.

This is the config that i'm using to create the consul service and my backend service.

```
docker network create --driver overlay --subnet 172.20.0.0/24 consul-net

docker service create \
  --name consul \
  --publish 8500:8500 \
  --network consul-net \
  --replicas 3 \
  -e 'CONSUL_BIND_INTERFACE=eth0' \
  -e ‘CONSUL_LOCAL_CONFIG={“skip_leave_on_interrupt”:true}’ \
  consul agent -server -ui -client=0.0.0.0 \
  -bootstrap-expect=3 \
  -data-dir=consul/data \
  -retry-join 172.20.0.3 \
  -retry-join 172.20.0.4 \
  -retry-join 172.20.0.5 \
  -retry-interval 5s
```

```
docker service create \
  --name backend \
  --publish 8765:8765 \
  --replicas 2 \
  --with-registry-auth \
  10.1.232.226:18444/backendtest:0.0.1
```

**Comment by cpuguy83** [comment]
ping @aboch 

How come you don't put both services on the same network?

**Comment by aboch** [comment]
Yes, in 1.13 we no longer allow containers to cross the networks boundaries (e.g. task on network X talk to task on network Y) via ingress network.
The ingress network (10.255.0.0/16) is part of the infrastructure and to only serve the purpose of routing mesh. See docker/libnetwork/pull/1496

**Comment by saman7766** [comment]
Thanks for the answer @aboch , with that in mind, i added to my spring boot application a propertie to ignore the "ingress" network, and now the healthcheck is working fine.

thanks so much to veryone.
