### ISSUE TITLE
Unable to join Docker swarm

### ISSUE THREAD

**Issue by joelchen** [docker/docker#30393]
**Description**
Unable to join Docker swarm recently.

**Steps to reproduce the issue:**
1. Create new Ubuntu 16.04 instance on AWS.
2. `sudo apt-get update && sudo apt-get upgrade && sudo apt-get -y dist-upgrade`
3. `curl -sSL https://get.docker.com/ | sh`
4. `docker swarm init`
5. Copy `docker swarm join --token <token> <server IP>:2377` command.
6. Run copied command on another Ubuntu 16.04 instance with latest updates.

**Describe the results you received:**
```
Error response from daemon: can't initialize raft node: rpc error: code = 13 desc = connection error: desc = "transport: x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"swarm-ca\")"
```

**Describe the results you expected:**
This node joined a swarm as a worker.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker swarm worked on Docker 1.13 before, this issue happened recently.

**Output of `docker version`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
Containers: 8
 Running: 8
 Paused: 0
 Stopped: 0
Images: 8
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 63
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: o982gng00i8o01gtuap16yp3u
 Is Manager: true
 ClusterID: wapxgt1ve73pvrxyikhqw2uvl
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.16.112
 Manager Addresses:
  172.31.16.112:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.952 GiB
Name: ip-172-31-16-112
ID: SWAH:VWD3:HGAX:NKEB:MKVC:LK7B:BPQ2:S6X5:DA6J:QPXD:Y3AN:XAQV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS t2.small instance.

**Comment by ColdFreak** [comment]
Exactly the same problem

**Comment by thaJeztah** [comment]
ping @cyli any ideas?

**Comment by ColdFreak** [comment]
After restart the docker engine, it joins the cluster successfully

**Comment by cyli** [comment]
@ColdFreak @joelchen Just trying to rule some things out here - do repeated join commands fail?  Or does it sometimes succeed if the command is run again?

**Comment by cyli** [comment]
Part of the reason I ask is that I am able to replicate if `/var/lib/docker/swarm/certificates/swarm-root-ca.crt` exists before I run `docker swarm join`.  

So I'm wondering if maybe the node that is joining was previously part of some other swarm, and maybe something didn't get cleaned up.

**Comment by fntlnz** [comment]
@cyli can you try to star the daemon manually with the debug  `-D` flag and post the output ? There should be the reason.

**Comment by cyli** [comment]
@fntlnz I only trying to replicate original poster's error :)  so cc @ColdFreak @joelchen:  any debug logs on the daemon?

**Comment by joelchen** [comment]
@cyli How do I get debug logs?

**Comment by fntlnz** [comment]
@joelchen start the daemon with the `-D` flag like `dockerd -D <your-other-parameters>` and post the output

@cyli sorry, wrong mention :)

**Comment by joelchen** [comment]
Strange but issue is not happening these days.

**Comment by cyli** [comment]
One way there could be a swarm ca cert already in `/var/lib/docker/swarm/certificates`, and no TLS certificates, is that:

1.  `docker swarm join` was run, but failed with `Error response from daemon: Timeout was reached before node was joined. The attempt to join the swarm will continue in the background. Use the "docker info" command to see the current swarm status of your node.`.

2. Later attempt to `docker swarm join` was run to join a different swarm.
