### ISSUE TITLE
Broken link to logger/context.go at https://docs.docker.com/engine/admin/logging/log_tags/

### ISSUE THREAD

**Issue by soulne4ny** [docker/docker#30403]
The page https://docs.docker.com/engine/admin/logging/log_tags/ provides link `logging context` to https://github.com/docker/docker/blob/master/daemon/logger/context.go that is not available any more.

**Comment by thaJeztah** [comment]
I opened a pull request in the documentation repository to fix this; https://github.com/docker/docker.github.io/issues/1351
