### ISSUE TITLE
Volume example for ambassador pattern

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#3041]
a few weeks ago i was shooting the breeze on irc about how to use VOLUMEs, wrt to backup, migration and general portability.

after writing up the linking example for ambassador pattern, it became clear that what I'd described was pretty much the same thing, just for VOLUMEs

ie, to backup VOLUMEs on one container

```(volume container) --> (backup container which writes to wherever)```

and to migrate from one docker host to another (ok, to be totally magic, it would require ``dind`` to also create the other services containers...

```(volume container) --> (backup) ---network---> (restore) --> (new volume container)```

similarly, you could do live syncing, or even bi-directional syncing

```(volume container) --> (rsync) ---network---> (rsync) --> (backup volume container)```

and like in the linking example, the data service can be just that, and the backup, sync or spying containers can be changed out as requirements change.

also, from irc @shykes was mentioning 

```
<shykes_> so you could do 'docker run -volumes-from=prod_data ubuntu tar -C /var/lib/postgres -c . | ssh $IP_OF_OTHER_CONTAINER tar -C /var/lib/postgres -x'
<shykes_> or more precisely
<shykes_> docker run -volumes-from=prod_data ubuntu sh -c "tar -C /var/lib/postgres -c . | ssh $IP_OF_OTHER_CONTAINER tar -C /var/lib/postgres -x'"
```

I'm going to try to write this in the next days - though tomorrow isn't likely :)

<div class="discussion-labels">...</div>

**Comment by jfrazelle** [comment]
@SvenDowideit status?

**Comment by calavera** [comment]
Volumes have changed a lot in 1 year. I'm going to close this issue because we have good documentation about volumes now.
