### ISSUE TITLE
Docker starts at log in even when "Start when you log in" checkbox has been cleared

### ISSUE THREAD

**Issue by josephby** [docker/docker#30423]
**Description**

Despite having cleared the "Start Docker when you log in" checkbox, Docker starts when I log in to Windows.

**Steps to reproduce the issue:**
1. Start Windows
2. Log In

**Describe the results you received:**

Docker icon is visible in system tray. If you right click the icon and click "Settings," you will see that "Docker is running" and that the "Start Docker when you log in" checkbox is cleared.

**Describe the results you expected:**

Docker should not start at log in. The Docker icon should not be visible in the System Tray.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker info`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

```
Edition: Windows 10 Pro
Version 1607
Running as standard user (i.e. non-Administrator)
```

**Comment by thaJeztah** [comment]
This looks like an issue specific to Docker for Windows, which has its own issue tracker; could you reopen this issue there? https://github.com/docker/for-win/issues

**Comment by josephby** [comment]
Thanks. Opened as [Docker for Windows issue 476](https://github.com/docker/for-win/issues/476).
