### ISSUE TITLE
IPAM request should be part of the transaction of overlay network creation in swarm mode

### ISSUE THREAD

**Issue by yuewko** [docker/docker#30426]
**Description**
When creating an overlay network in swarm mode, it is observed that the network creation completes instantaneously (and successfully) before corresponding IPAM request completes. A remote IPAM driver is used in this case.

**Steps to reproduce the issue - scenario 1:**
*Scenario 1: Create overlay network without specifying a subnet*
The intention is for the IPAM driver to allocate a subnet from a predefined pool.

1. Run the following command on the manager node to create an overlay network:
```
root@manager:~# docker network create --driver=overlay --ipam-driver=infoblox overlay-tst
```
where ```infoblox``` is the remote IPAM driver.

2. It is observed that the command returns instantaneously with an network ID.
However, this is despite of the IPAM request is still being processed. Here's the log output of the IPAM driver:
```
2017/01/24 22:03:30 Plugin: /IpamDriver.RequestPool
2017/01/24 22:03:30 RequestPoolRequest is '&{networkview/ZG5zLm5ldHdvcmtfdmlldyQxNg:docker-global/false   map[] false}'
2017/01/24 22:03:30 Allocating network from Container:'172.18.0.0/16'
2017/01/24 22:03:30 RequestPool: returing 'map[PoolID:network/ZG5zLm5ldHdvcmskMTcyLjE4LjAuMC8yNC8xNg:172.18.0.0/24/docker-global Pool:172.18.0.0/24]'
2017/01/24 22:03:30 res is 'map[Pool:172.18.0.0/24 PoolID:network/ZG5zLm5ldHdvcmskMTcyLjE4LjAuMC8yNC8xNg:172.18.0.0/24/docker-global]'
```
Note that the Pool returned by the RequestPool request is 172.18.0.0/24.

3. Run network inspect on the overlay created:
```
root@manager:~# docker network inspect overlay-tst
[
    {
        "Name": "overlay-tst",
        "Id": "02vqvoleivrgtgpsldi6eucfg",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "infoblox",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": false,
        "Containers": null,
        "Options": {
            "com.docker.network.driver.overlay.vxlanid_list": "4097"
        },
        "Labels": null
    }
]
```
Note that although the IPAM "Driver" name is populated, "Config" is not populated at all.

**Describe the results you received:**
The overlay network was created, but is not populated with the result of the IPAM request.

**Describe the results you expected:**
The overlay network should have been assigned Pool according to the result of the IPAM request.

**Steps to reproduce the issue - scenario 2:**
*Scenario 2: Create overlay network specifying a subnet that has already been occupied in the IPAM driver backend*
In this scenario, the IPAM request fails because the user specified subnet has already been occupied. The network creation is expected to fail as a result.

1. Run the following command on the manager node to create an overlay network:
```
root@manager:~# docker network create --driver=overlay --ipam-driver=infoblox --subnet=123.0.0.0/16 overlay-tst
```
In this test scenario, the subnet 123.0.0.0/16 was already preallocated in the IPAM backend and is therefore not available for the above overlay.

2. It is observed that the command returns instantaneously with an network ID.
However, this is despite of the IPAM request is still being processed. Here's the log output of the IPAM driver:
```
2017/01/24 22:07:17 Plugin: /IpamDriver.RequestPool
2017/01/24 22:07:17 RequestPoolRequest is '&{networkview/ZG5zLm5ldHdvcmtfdmlldyQxNg:docker-global/false 123.0.0.0/16  map[] false}'
2017/01/24 22:07:17 requestSpecificNetwork: network is already used '{{ [] map[]} network/ZG5zLm5ldHdvcmskMTIzLjAuMC4wLzE2LzE2:123.0.0.0/16/docker-global docker-global 123.0.0.0/16 map[]}'
2017/01/24 22:07:17 RequestPool: returing 'map[]'
2017/01/24 22:07:17 IPAM Driver returned nil result
2017/01/24 22:07:17 IPAM Driver error 'network already in use'
2017/01/24 22:07:17 res is 'map[Error:network already in use]'
```
Note that an empty Pool was returned by the RequestPool request. as well as ``Error:network already in use```

3. Run network inspect on the overlay created:
```
root@manager:~# docker network inspect overlay-tst
[
    {
        "Name": "overlay-tst",
        "Id": "gkv4g5191ohxy77l0jlpabn7y",
        "Created": "0001-01-01T00:00:00Z",
        "Scope": "swarm",
        "Driver": "",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "infoblox",
            "Options": null,
            "Config": [
                {
                    "Subnet": "123.0.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": null,
        "Options": null,
        "Labels": null
    }
]

```
Note that the output indicates that the Subnet 123.0.0.0/16 has been successfully allocated, when in fact the IPAM request has failed.

**Describe the results you received:**
The overlay network was created with the specified subnet.

**Describe the results you expected:**
The creation of the overlay network should have failed as a result of the failed IPAM request.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   5e74dc1
 Built:        Tue Jan 24 21:46:27 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   5e74dc1
 Built:        Tue Jan 24 21:46:27 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 6
 Paused: 0
 Stopped: 1
Images: 3
Server Version: 1.14.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 21
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: cx5izyiwhrdf6ycx5wr7k57p9
 Is Manager: true
 ClusterID: xc0pk44pl8pttopelz9nwv5dp
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.23.18.211
 Manager Addresses:
  172.23.18.211:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: d7975b89804b207b68f8b446cf1e2af72589bfcf
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: manager
ID: DZSF:P5GR:E3LN:V6QL:2AA7:X6VB:BAOR:OTRJ:P2KO:2KC4:UTAE:NHNU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Swarm consist of one manager node and two worker nodes.
Each node is run under VirtualBox, and the output of ```uname -a``` for each node is:
```
Linux manager 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
The VirtualBox host also runs the same version of Ubuntu.

**Comment by aboch** [comment]
> When creating an overlay network in swarm mode, it is observed that the network creation completes instantaneously

Swarm uses an asynchronous mode of operation. The fact that the network creation command did not fail, does not mean this configuration was actually translated into an operational state.
This is true for other swarm resources as well, like services.

It may stay there forever failing to be allocated.

**Comment by yuewko** [comment]
Thank you, @aboch !

> Edit: What is missing now is a clear information about the network state in the network inspect output, that may probably help make the logic more clear.

Totally agreed. The information should provide enough detail so that it can be used to determine if and what remedial action is necessary.
