### ISSUE TITLE
Support exec for Swarmkit Tasks

### ISSUE THREAD

**Issue by ehazlett** [docker/docker#30429]
This is the engine issue to track support `exec` for Swarmkit tasks.

Refs: https://github.com/docker/swarmkit/issues/1895

**Comment by thaJeztah** [comment]
I think this is a duplicate of https://github.com/docker/docker/issues/27552, shall I close this one?

**Comment by ehazlett** [comment]
Yup  thx @thaJeztah.  Closing.
