### ISSUE TITLE
dockerd died unexpectedly crashreport

### ISSUE THREAD

**Issue by freeseacher** [docker/docker#30433]
**Description**

dockerd died unexpectedly on rhel 7.3

**Steps to reproduce the issue:**
1. launch docker
2. ???
3. dockerd dies

**Additional information you deem important (e.g. issue happens only occasionally):**

[log.txt](https://github.com/docker/docker/files/728735/log.txt)
**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
# docker info 
Containers: 14
 Running: 14
 Paused: 0
 Stopped: 0
Images: 24
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.39 GiB
Name: scedr07owltow01
ID: JFOZ:QQNR:ZUX4:2ADX:D5GX:R5Z7:4TB2:6THT:4ZOK:DZNB:PHAV:Z3RI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Https Proxy: 10.36.131.11:8080
Username: freeseacher
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by urban-it-solutions** [comment]
same issue here. centos 7.3, docker 1.13, overlayfs. crash-report attached.
[docker-crash-report.txt](https://github.com/docker/docker/files/731873/docker-crash-report.txt)

**Comment by thaJeztah** [comment]
@urban-it-solutions can you post the full output of `docker version` and `docker info`

ping @LK4D4 @justincormack @rhvgoyal PTAL

**Comment by cpuguy83** [comment]
@urban-it-solutions @freeseacher Can you provide any details as to what was going on during the crash?
From the stack dump it looks like you have an active `docker logs` consumer?
Also can you confirm you are using the journald driver?
Any other details would be extremely helpful! 🙇 

Thanks!

**Comment by freeseacher** [comment]
My systemd unit looks like this 
```
# /etc/systemd/system/docker.service.d/override.conf
[Service]
Environment=https_proxy=XXXX:8080
ExecStart=
ExecStart=/usr/bin/dockerd --log-driver=journald --storage-driver overlay --live-restore
```

**Comment by urban-it-solutions** [comment]
@cpuguy83 
My Options:
OPTIONS='--storage-driver=overlay --log-driver=journald'

I have an openshift-origin 1.5.2 alpha running on top.

@thaJeztah : Sorry, I already downgraded to docker 1.12.6 
But it is the same configuration, only Centos7.3 instead of RHEL7.3.

Now I have:

 docker info
Containers: 52
 Running: 22
 Paused: 0
 Stopped: 30
Images: 26
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: xfs
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.38 GiB
Name: lxdedevoshift02
ID: C43C:CW6L:LI5Q:IGAT:5KZG:FYNQ:F5VN:XJ2A:QSR2:VV5Z:GMXU:U5FF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: http://p-proxy.int.hlg.de:8080/
Https Proxy: http://p-proxy.int.hlg.de:8080/
No Proxy: 172.30.116.124,172.30.0.1,172.30.97.73,10.1.0.0/16,172.30.0.0/16,172.20.132.0/24
Registry: https://index.docker.io/v1/
Insecure Registries:
 172.30.116.124:5000
 127.0.0.0/8

**Comment by thaJeztah** [comment]
ping @nalind could you have a look? @cpuguy83 suspects journald may be involved here (not sure though, but we could have some extra eyes)

**Comment by enst** [comment]
Looks like I ran into a similar issue.
Feb 03 14:34:23 tor4.localdomain dockerd[17378]: *** Error in `/usr/bin/dockerd': corrupted double-linked list: 0x00007fc668002000 ***

docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

docker info
Containers: 31
 Running: 29
 Paused: 0
 Stopped: 2
Images: 154
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 249
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay weavemesh
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: tor4.localdomain
ID: HASN:JZHW:LIWV:RQVM:YS7Q:IIXS:3DXU:WCZQ:SLCF:Y4IW:BQYN:4WC2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by enst** [comment]
I didn't lose containers. Most of them restarted. And I manually started a couple of "Exit" state containers.
The crashing started today and happened a couple of times already.

**Comment by cpuguy83** [comment]
@enst Sounds like you are hitting this frequently.
What kind of workloads are you throwing at it?

**Comment by enst** [comment]
I was. It didn't crash since my last post.
The workloads is very light. 
I'm using weave networks BTW.

**Comment by enst** [comment]
It crashed again just now. 
I've downgraded to 1.12.1. Will see.

**Comment by amatsus** [comment]
I've got the same issue. 
CentOS 7.3 / docker 1.13.0 and 1.13.1 / `-s overlay` and `-s overlay2`
[dockerd-crash-report.txt](https://github.com/docker/docker/files/765989/dockerd-crash-report.txt)
[gdb-dockerd-core.txt](https://github.com/docker/docker/files/765997/gdb-dockerd-core.txt)

**Comment by boutros** [comment]
We are hitting this also, at infrequent intervals. It's always gives the same cause. It must be something with the journald integration.

We are logging a lot to journald, so it might be workload related, but so far it seems to happen quite randomly.

**Crash:** 

```
Feb 21 07:33:59 sputnik docker[35858]: *** Error in `dockerd': corrupted double-linked list: 0x00007fe720000aa0 ***
Feb 21 07:33:59 sputnik docker[35858]: ======= Backtrace: =========
Feb 21 07:33:59 sputnik docker[35858]: /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fe7d0de37e5]
Feb 21 07:33:59 sputnik docker[35858]: /lib/x86_64-linux-gnu/libc.so.6(+0x80477)[0x7fe7d0dec477]
Feb 21 07:33:59 sputnik docker[35858]: /lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fe7d0def98c]
Feb 21 07:33:59 sputnik docker[35858]: dockerd[0x46f380]
```

**Cause:**

```
Feb 21 07:33:59 sputnik docker[35858]: SIGABRT: abort
Feb 21 07:33:59 sputnik docker[35858]: PC=0x7fe7d0da1428 m=32
Feb 21 07:33:59 sputnik docker[35858]: signal arrived during cgo execution
Feb 21 07:33:59 sputnik docker[35858]: goroutine 6240889 [syscall, locked to thread]:
Feb 21 07:33:59 sputnik docker[35858]: runtime.cgocall(0x1473770, 0xc4206e0590, 0x0)
Feb 21 07:33:59 sputnik docker[35858]: #011/usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4206e0560 sp=0xc4206e0520
Feb 21 07:33:59 sputnik docker[35858]: github.com/docker/docker/daemon/logger/journald._Cfunc_free(0x7fe720000bf0)
Feb 21 07:33:59 sputnik docker[35858]: #011github.com/docker/docker/daemon/logger/journald/_obj/_cgo_gotypes.go:108 +0x41 fp=0xc4206e0590 sp=0xc4206e0560
Feb 21 07:33:59 sputnik docker[35858]: github.com/docker/docker/daemon/logger/journald.(*journald).drainJournal(0xc420236500, 0xc422a2c990, 0x0, 0x0, 0x0, 0xffffffffffffffff, 0x1, 0x7fe7a8000c60, 0x7fe720000bf0, 0x7fe720000bf0)
Feb 21 07:33:59 sputnik docker[35858]: #011/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/logger/journald/read.go:239 +0x263 fp=0xc4206e06c0 sp=0xc4206e0590
Feb 21 07:33:59 sputnik docker[35858]: github.com/docker/docker/daemon/logger/journald.(*journald).followJournal.func1(0x7fe7a8000c60, 0x22e0000000e, 0xc420fe69b0, 0xc420236500,
 ```

**Docker info:** 

```
bibadmin@sputnik:~/koha-prod$ docker info
Containers: 20
 Running: 15
 Paused: 0
 Stopped: 5
Images: 152
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 834
 Dirperm1 Supported: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 40
Total Memory: 62.81 GiB
Name: sputnik
ID: YBXP:WL5P:WWY5:QDCZ:5AHB:XF2P:QEEY:OBB7:CG7B:GT4W:6Y5H:X5SG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by boutros** [comment]
It happened again, two times in a day..

I'm suspecting the problem could be  https://github.com/docker/docker/pull/27420

I'm downgrading docker to 1.12.1 for now...
