### ISSUE TITLE
Reclaimable space value has wrong format

### ISSUE THREAD

**Issue by Deathofdemigod** [docker/docker#30434]
Expected behavior

Reclaimable space in readable format.

Actual behavior

PS C:\WINDOWS\system32> docker system df
TYPE TOTAL ACTIVE SIZE RECLAIMABLE
Images 13 10 15.65 GB -4.752e+10 B (-303%)
Containers 14 0 0 B 0 B
Local Volumes 0 0 0 B 0 B
PS C:\WINDOWS\system32>

Information

Diagnostic ID from "Diagnose & Feedback" in the menu.
a reproducible case if this is a bug, Dockerfiles FTW
page URL if this is a docs issue or the name of a man page
host distribution and version (Windows version, build number, etc)
A diagnostic was uploaded with id: 3071BE33-3E80-4065-894F-DFA3B436841C/2017-01-23_09-00-51

Win 10 Enterprise v 1607 build 14393.223
64Gb of Ram.

Steps to reproduce the behavior

open powershell as adm
run "docker system df"

recreated from https://github.com/docker/for-win/issues/413

**Comment by thaJeztah** [comment]
thanks for reporting! thus has been fixed on "master" through  https://github.com/docker/docker/pull/30378  and will be in docker 1.13.1

I'll close this issue because it's fixed, but feel free to continue the conversation
