### ISSUE TITLE
Checkpoint/Restore - capture all processes in container

### ISSUE THREAD

**Issue by jamesdboone** [docker/docker#30448]
**Description**
Checkpoint and restore feature appears to only manage primary process and processes forked underneath.  For long running containers where processes may be restarted over time, new PIDs will not be captured via checkpoint/restore.  Can feature be updated to capture all processes in the container?

**Steps to reproduce the issue:**
1  docker run -d --security-opt=seccomp:unconfined --name ca bash sleep 5000
3  docker exec -d ca bash -c '/bin/sleep 5000'
4  docker exec ca ps -ef (see two 'sleep' processes)
5  docker checkpoint create ca cr
6  docker start --checkpoint=cr ca
7 docker exec ca ps -ef

**Describe the results you received:**
Only a single sleep process is restored, PID 1.

**Describe the results you expected:**
Both sleep processes restored and resuming where they left off.

**Additional information you deem important (e.g. issue happens only occasionally):**
Looks like forked processes get captured/restored, but handling all processes in container would be a more complete/reliable solution.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 19
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.478 GiB
Name: globalhost.centos7
ID: HNRD:AEH2:PERA:2UCE:J3O7:7YOZ:7OHP:QLG2:4NLU:OJDQ:WXE5:4YTB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 27
 Goroutines: 38
 System Time: 2017-01-25T11:19:22.6317991-05:00
 EventsListeners: 0
Http Proxy: http://webproxy.ext.ti.com:80/
No Proxy: localhost,127.0.0.1,tmgadfdockucp2.itg.ti.com,tmgadfdockucp3.itg.ti.com,tmgadfdockreg.itg.ti.com
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @boucher @xemul ptal

**Comment by boucher** [comment]
@xemul will have a better answer, but I'm not sure this will be possible (or at least, not easily). CRIU is focused checkpointing a single process (and all its children). It could be possible I suppose to iterate over any execs both during the checkpoint and the restore and treat them separately. 

My instinct would be to punt for now, as it feels like an uncommon use case to me, since Docker tries to advocate for containers that run one process.

**Comment by thaJeztah** [comment]
I think there was some discussion about reparenting of `exec` processes, but changes were needed in RunC (I may be mistaking that discussion though).

**Comment by jamesdboone** [comment]
It does look like the runc fix will resolve, just need to hang in there for
that fix.  Thanks!

On Jan 25, 2017 11:35 AM, "Sebastiaan van Stijn" <notifications@github.com>
wrote:

I think there was some discussion about reparenting of exec processes, but
changes were needed in RunC (I may be mistaking that discussion though).

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/30448#issuecomment-275175973>, or mute
the thread

**Comment by xemul** [comment]
Sorry for long delay in response.

Right now CRIU dumps a single subtree of processes, which is in Docker case -- container pid1 and its kids (including reparented ones). Or at least it should be such.
Technically we can add support for two or more subtrees, but the question is -- who to reparent the restored 2nd, 3rd and all the others? BTW, @jamesdboone , in your example, can you show the output of the ps -xaf command, and point the processes you expect to be dumped?

We have a feature request to C/R not subtrees, but inhabitants of a certain cgroup (https://github.com/xemul/criu/issues/41), but the question "who will be the parent of all the secondary subtrees" still stands there.

**Comment by jamesdboone** [comment]
Here's an image of the ps -xaf as the formatting didn't translate well to the webpage directly.  The 'sleep 5000' is from the 'docker run' call, and the 'sleep 500' is from the 'docker exec' call.  Ideally, both would get captured in the checkpoint and restored.  Would it make sense to have one more layer 'parent process' for every container, where the 'run' process and 'exec' processes all spawn as children?  Seems like this would simplify things (for the end user anyway) as we then don't need to worry about 'how' we started processes in the container, everything would fall under the same tree.

![image](https://cloud.githubusercontent.com/assets/19520951/22397647/ea1e17e0-e53b-11e6-9ef6-e7bb29e40b68.png)

**Comment by xemul** [comment]
@jamesdboone , it seems to me that supporting this case would me better to be done on runc/docker side, so that docker checkpoint suspends all the ... subtrees (?) that were spawned by it into the respective "container" (whatever it means). This is possible to do "atomically", criu can work on freeze cgroups, so runc/docker will have to freeze the cgroup with all subtrees in it and call criu for every subtree . This would complicate the image dir structure however.

**Comment by jamesdboone** [comment]
Sorry, I agree.  Closing this issue.  Thanks for the responses/feedback!
