### ISSUE TITLE
Docker client package can not retrieve docker server version on docker for mac.

### ISSUE THREAD

**Issue by morriswinkler-simplesurance** [docker/docker#30440]
I already opened an issue on the for mac repro, https://github.com/docker/for-mac/issues/938,
 but haven't had any luck, it looks like my problem was simply not understood. I am writing a go tool that uses the client package to communicate to docker. Since the for mac version moved to the new osx hypervisor docker-machine env is not existing on osx. So there is no safe way to pull the daemon version from env or that command.

In the moment my program works on mac only for the latest docker for mac installation. Is there a way to fetch the daemon version without knowing the API revision from the daemon directly. Would be good if the client could just query the API revision and doesn't need to rely on some user provided value.

some example using "github.com/docker/docker/client"
```
cli, err := client.NewClient(host, version, httpClient, nil)
	if err != nil {
		return nil, err
	}
```

Will fail if the version is wrong. Any idea how to fix this.

**Comment by justincormack** [comment]
The API version is in the returned http headers
```
> GET /info HTTP/1.1
> Host: docker
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Api-Version: 1.25
< Content-Type: application/json
< Date: Wed, 25 Jan 2017 11:11:16 GMT
< Docker-Experimental: true
< Server: Docker/1.13.0 (linux)
< Transfer-Encoding: chunked
```

**Comment by justincormack** [comment]
or you can use the json or templated output from `docker version` see https://docs.docker.com/engine/reference/commandline/version/

**Comment by morriswinkler-simplesurance** [comment]
Thanks, that helped a lot.

**Comment by justincormack** [comment]
I will close this now as the answers on this and the linked issue should be sufficient.

**Comment by morriswinkler-simplesurance** [comment]
great
