### ISSUE TITLE
File mounted into container presents in image with 0 size after committing

### ISSUE THREAD

**Issue by garagatyi** [docker/docker#30466]
**Description**
When I commit container that has bind-mounted file and start container from created image without volumes I see that file exists in container with 0 size.

**Steps to reproduce the issue:**
```
1. docker run -d -v /etc/hosts:/hostsfile --name commitvolumetest ubuntu tail -f /dev/null 
2. testimageId=$(docker commit commitvolumetest)
3. docker run ${testimageId} bash -c "ls -l /hostsfile"
```

**Describe the results you received:**
`-rwxr-xr-x 1 root root 0 Jan 26 12:38 /hostsfile`

**Describe the results you expected:**
`ls: cannot access '/hostsfile': No such file or directory`

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:42:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 31
 Running: 22
 Paused: 0
 Stopped: 9
Images: 27
Server Version: 1.12.5
Storage Driver: aufs
 Root Dir: /data/docker/aufs
 Backing Filesystem: extfs
 Dirs: 183
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.4 GiB
Name: gaal-workstation
ID: PXA5:XZLW:URNL:T76F:7V2Z:W3G2:YQCF:IT2H:NRV4:RKLK:4PNW:DDE2
Docker Root Dir: /data/docker
Debug Mode (client): false
Debug Mode (server): false
Username: garagatyi
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 172.19.20.12:5000
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04 PC

**Comment by thaJeztah** [comment]
This is expected; the file is bind-mounted in the container, and for this to work, the mount-point (the location where the file (or directory)  is mounted inside the container) has to exist; see [Example uses of the Linux Command mount](https://www.lifewire.com/uses-of-linux-command-mount-2201110);

>  `mount /dev/fd0 /mnt/floppy`
> This command will connect the device "/dev/fd0" (usually the floppy drive) to the directory
> "/mnt/floppy" so that you can access the files and directories (folders) on the floppy disk in the floppy drive under the "/mnt/floppy" directory.
> The directory "/mnt/floppy" is also called the "mount point", which must already exist when this command is executed.

You'll see the same when mounting a _directory_ (not a file);

```
$ docker run -dit -v /foobar --name commitvolumetest busybox
$ testimageId=$(docker commit commitvolumetest)
$ docker run --rm ${testimageId} bash -c "ls -la /foobar"
total 8
drwxr-xr-x    2 root     root          4096 Jan 26 13:11 .
drwxr-xr-x    1 root     root          4096 Jan 26 13:11 ..
```

This is working as expected, and not a bug

**Comment by garagatyi** [comment]
OK, thanks for the explanation.
