### ISSUE TITLE
Docker stack prefixes my volumes and networks

### ISSUE THREAD

**Issue by whoan** [docker/docker#30483]
I am using a docker-compose.yml version 3 with `docker stack deploy` and I can't figure it out how to make my db service to use my old database volume.

Let's say I have a database volume named **somevolume** and `docker stack deploy` creates a new volume **stackname_somevolume** instead of using **somevolume**.

What can I make my *stacked* service to use my existing **somevolume**?

---------------

If there is no solution right now, I think it would be nice if you:

- Add option to avoid `docker stack` adding prefixes to my networks and volumes.

or

- Add option to rename volumes (regard to networks I think we can `rm` and `create` it again with no problems).

**Comment by vdemeester** [comment]
@whoan it works like docker-compose. You can use external volumes to achieve what you want (https://docs.docker.com/compose/compose-file/#/volume-configuration-reference)

**Comment by xvitcoder** [comment]
The same problem here, the stack prefix also creates problems when referencing a service using its hostname. It seems that the hostnames are also prefixed.

```
services:
    redis:
        image: redis
        hostname: redis
    my-service:
        image: my-service
        hostname: my-service
```

if I want to connect to my-service to redis service, in _docker compose_ it works fine, but deploying it as a _stack_ , it does not work, cause the stack prefixes each service with the stack name, so if the stack name is _myapp_ then the services hostname becomes _myapp_redis_ and _myapp_my-service_.

So I suggest to allow somehow to ignore the stack name in links, hostnames, volumenames, networks etc... or to allow prepend it automatically when referenced

**Comment by vdemeester** [comment]
@xvitcoder There should be a network alias with the name of the service between services and thus they should be accessible from each other by the name of the service (non-prefixed).

```
services:
  foo:
    image: busybox
    command: top
  bar:
    image: busybox
    command: ping foo
```

The service `bar` should be `ok` and should ping successully `foo`.

**Comment by matzegebbe** [comment]
I have the problem that we have some references to the service name for auto update services etc.
Is there an option i can use docker compose without any prefix?

Thank you!

docker update $SERIVCENAME does not find STACKNAME_$SERVICENAME :(

**Comment by thaJeztah** [comment]
@matzegebbe you mention using `docker update`, not `docker service update`, is that a typo?

**Comment by vdemeester** [comment]
>  Is there an option i can use docker compose without any prefix?

Nope 😅

**Comment by matzegebbe** [comment]
@thaJeztah Yes, sorry. Bad example. I updated my comment

**Comment by bewinsto7604** [comment]
Hi, is there a fix for this issue?

**Comment by jbacken** [comment]
I had the scenario where I started a service via docker-compose that mapped (and manipulated a) volume successfully, then I re-started that same service via docker stack, but the stack instance prefixed the volume with "service-name_", so it did not map the same volume as the docker-compose call.

I stumbled on: https://docs.docker.com/compose/compose-file/#external, which indicates you can specifically call out the docker volume name to map, ala:
```
volumes:
  my-data-volume:
    external:
      name: my-data-volume

```
... and my docker-stack instance now sees the same data populated by the docker-compose.  This may not be a common scenario (switching between instantiation methods), but at least I could get passed the auto-prefixing.

**Comment by maxim-ge** [comment]
Have had same problem

**Comment by delmartechdude** [comment]
For anyone else who comes across this in regards to `networks`, you have to specify it as external:

> The stack command cannot create a new attachable network. To use an attachable network with a stack we must define it ahead of time with docker network create then specify the network as external:
> ```
> version: "3"
> services:
>   nginx:
>     image: nginx
>     networks:
>     - core-infra
> 
> networks:
>   core-infra:
>     external: true
> ```
> source: https://blog.alexellis.io/docker-stacks-attachable-networks/

**Comment by koo9** [comment]
@villasenor but docker stack deploy ... did create an overlay network but with the prefix. is there some hidden documentation somewhere on this?

**Comment by villasenor** [comment]
@koo9 Interesting. Maybe something changed. This was a long time ago, and I don't use Swarm much anymore, but I think the advice still applies. Ignore the fact that it says the `stack` command can't create an attachable network because whether that is true or not, the important thing here is that you can get around the logic used to name the network by creating it manually like `docker network create -d overlay --attachable my-attachable-overlay`, and referencing it as an external network in your `docker-compose` for use in `docker stack deploy` :)

see: https://docs.docker.com/network/overlay/

**Comment by shrinidhi111** [comment]
Is there a solution for this??

**Comment by thaJeztah** [comment]
Yes, use `external: true` for the volume, and specify a custom `name:`
https://docs.docker.com/compose/compose-file/compose-file-v3/#name

```yaml
version: "3.9"
services:
  foo:
    image: "nginx:alpine"
    volumes:
      - data:/app/data

volumes:
  data:
    external: true
    name: my-app-data
```

**Comment by shrinidhi111** [comment]
> Yes, use `external: true` for the volume, and specify a custom `name:`
> https://docs.docker.com/compose/compose-file/compose-file-v3/#name
> 
> ```yaml
> version: "3.9"
> services:
>   foo:
>     image: "nginx:alpine"
>     volumes:
>       - data:/app/data
> 
> volumes:
>   data:
>     external: true
>     name: my-app-data
> ```

Okay. Then the only additional step is creating the network/volume beforehand and then using it in the stack.

Alright.
