### ISSUE TITLE
Checkpoint/Restore not working on 32bit/debian 

### ISSUE THREAD

**Issue by rockymtnman** [docker/docker#30486]
**Description**

**Steps to reproduce the issue:**
1. run the following command to start a simple counter within the 32-bit debain container
docker run --security-opt=seccomp:unconfined --name debian_demo -d 32bit/debian /bin/sh -c 'i=0; while true; do echo $i; i=$(expr $i + 1); sleep 1; done'
2. attempt to save checkpoint
docker checkpoint create b9 test --leave-running=true

**Describe the results you received:**
Error received:
Error response from daemon: Cannot checkpoint container b9: rpc error: code = 2 desc = exit status 1: "criu failed: type NOTIFY errno 0\nlog file: /var/lib/docker/containers/b95465cc0763a1712f80b06465de1d2ac3536331d8df817f9953a767a6cf5902/checkpoints/test2/criu.work/dump.log\n"

The checkpoint is visible when doing checkpoint ls, but cannot be used

**Describe the results you expected:**
Expected checkpoint to be saved.  Checkpointing works great for other container images (Centos 7, etc.).  Only 32bit/debian gives the error

**Additional information you deem important (e.g. issue happens only occasionally):**
May be related to CRIU issue
https://github.com/xemul/criu/issues/199

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: true

```

**Output of `docker info`:**

```
Containers: 16
 Running: 2
 Paused: 0
 Stopped: 14
Images: 21
Server Version: 1.13.0
Storage Driver: devicemapper
 Pool Name: docker-8:2-33666391-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem: ext4
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 8.232 GB
 Data Space Total: 107.4 GB
 Data Space Available: 8.111 GB
 Metadata Space Used: 7.741 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.14 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.844 GiB
Name: 
ID: 
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running docker in CentOS 7 VM

**Comment by thaJeztah** [comment]
can you also attach the criu.work/dump.log file?

/cc @boucher @xemul

**Comment by xemul** [comment]
32bit x86 is not yet supported in CRIU. We're working on it (https://github.com/xemul/criu/issues/43), the patches to make this happen are already in criu-dev branch in the repo.

**Comment by thaJeztah** [comment]
Thanks! Looks like this is something to be addressed by criu, so let's close this here, as it's not a bug in docker

**Comment by rockymtnman** [comment]
Thanks very much for the clarification guys.  I'll look for the the 32-bit compatibility update in CRIU
