### ISSUE TITLE
docker pull error 'Error response from daemon: repository myUsername/myDockerHubRepo not found: does not exist or no pull access'

### ISSUE THREAD

**Issue by s2zaman** [docker/docker#30498]
Error while pulling from **hub.docker.com**
`Error response from daemon: repository myDockerHubUsername/myDockerHubRepo not found: does not exist or no pull access`

**Solution:**
Just make your docker hub repo, as **Public** 👍

**Comment by thaJeztah** [comment]
Looks you found the solution, so let me close 👍
