### ISSUE TITLE
Feature Request: support for Secrets when deploying a stack from a compose file

### ISSUE THREAD

**Issue by sophokles73** [docker/docker#30501]
Hi,

I have been playing around with the newly introduced feature to deploy a stack using a compose file with Docker 1.13 in swarm mode.
This is really a fantastic feature that will make our lives so much easier :-) However, I am missing a way of specifying the Docker secrets that a service should get access to within the compose file. I can imagine having another sub-option for `deploy`, e.g. `secrets` which can then have an array of names as its value.

**Comment by sophokles73** [comment]
Just saw that there already is #29968

**Comment by thaJeztah** [comment]
Yes, this will be added in docker 1.13.1, which will be released soon
