### ISSUE TITLE
Command "docker events --since 1" => only last 64 events

### ISSUE THREAD

**Issue by Nurza** [docker/docker#30502]
**Description**

When you run the command "docker events --since 1", the output of the command only displays the last 64 events of the daemon.

**Steps to reproduce the issue:**
1. Run docker daemon
2. Do some "docker run" enough to generate events
3. Launch "docker events --since 1"

**Describe the results you received:**

Only last 64 events

**Describe the results you expected:**

All events since the beginning of the docker installation

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 90
 Running: 1
 Paused: 0
 Stopped: 89
Images: 248
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1387
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.55 GiB
Name: n90
ID: HSQW:J3AJ:3DAB:BQF4:C3IK:C77C:P7F2:6NHP:LWPH:JJWN:FRMI:HP3S
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: nurza
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, but I can reproduce on KVM virtual machine too.

**Comment by cpuguy83** [comment]
Going to close as a dup of #22917

We cannot really store all events for all time, this is too much.
Right now events is intentionally capped at 64 and are only kept in memory.

**Comment by Nurza** [comment]
But it will be very useful to log every OOM, crash, etc. I really need this feature to make centralized logs on docker clusters failures.

Why not a logrotated log like containers?

**Comment by cpuguy83** [comment]
@Nurza Maybe you can comment on the other issue?
