### ISSUE TITLE
Docker Swarm with Centos 6.5 and Docker 1.7.1

### ISSUE THREAD

**Issue by Devopsminjarj** [docker/docker#30505]
Hi All,

We're having a requirement of Docker swarm environment with CentOS 6.5. So, for Centos 6.5, the latest supported docker version is 1.7.1. We've installed and tried to form Swarm cluster. We're running into below issues and errors.

*. When we do Docker info in Swarm manager.

docker info
Containers: 0
Images: 0
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint, whitelist
Nodes: 1
(unknown): Swarm-Client-IP:2375
└ ID:
└ Status: Pending
└ Containers: 0
└ Reserved CPUs: 0 / 0
└ Reserved Memory: 0 B / 0 B
└ Labels:
**└ Error: Cannot connect to the Docker daemon at tcp://Swarm-Client-IP:2375. Is the docker daemon running?**
└ UpdatedAt: 2017-01-27T14:47:44Z
└ ServerVersion:
Kernel Version: 2.6.32-642.13.1.el6.x86_64
Operating System: linux
CPUs: 0
Total Memory: 0 B
Name: mgr1

We've tried adding -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock as well in config and restarted docker in client node. Didn't help.

Below are the error in docker logs,

time="2017-01-27T14:34:37.800902512Z" level=warning msg="You are running linux kernel version 2.6.32-642.13.1.el6.x86_64, which might be unstable running docker. Please upgrade your kernel to 3.10.0."
time="2017-01-27T14:34:37.804149359Z" level=info msg="Listening for HTTP on unix (/var/run/docker.sock)"
time="2017-01-27T14:34:37.817544948Z" level=info msg="[graphdriver] using prior storage driver "devicemapper""
time="2017-01-27T14:34:37.823226969Z" level=warning msg="Running modprobe bridge nf_nat failed with message: , error: exit status 1"

Could anyone help, how to resolve below error.

****Error: Cannot connect to the Docker daemon at tcp://Swarm-Client-IP:2375. Is the docker**

**Comment by Devopsminjarj** [comment]
Here is the version details,

**docker version**
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d/1.7.1
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d/1.7.1
OS/Arch (server): linux/amd64
 
**uname -a**
Linux ip-10-5-3-183 2.6.32-642.13.1.el6.x86_64 #1 SMP Wed Jan 11 20:56:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rahulkrishnanfs** [comment]
#dibs

**Comment by cpuguy83** [comment]
Can you paste the full logs?
The last message is only a warning about modprobe failing.

Also I'm going to close this since it's not really an active issue and we don't do any development on 1.7, but happy to help you fix your issue (maybe the community slack would be better, though?)
