### ISSUE TITLE
[Feature] Docker max restart time

### ISSUE THREAD

**Issue by Nurza** [docker/docker#30503]
The problem here is the docker run "--restart" option.
It allows the container to restart after a crash. 
When the container is in a crash loop, Docker wait every restart like this:

container crash
wait 100ms
container start
container crash
wait 200ms
container start
container crash
wait 400ms
container start
etc... until waiting 544878449 years

It can be useful to set a maximum restart time to avoid too long (and ridiculous) restart time.

**Comment by cpuguy83** [comment]
Darnit, I swear we've fixed this a half dozen times...
I don't think we need a flag, just a cap.

**Comment by cpuguy83** [comment]
For anyone interested, this logic is here: https://github.com/docker/docker/blob/master/restartmanager/restartmanager.go#L76

**Comment by rreinurm** [comment]
I also propose to have a flag to set max restart cap per container.

**Comment by milindchawre** [comment]
I would like to work on it!
#dibs

**Comment by milindchawre** [comment]
@cpuguy83 Should I set a max value? What should be the value?

**Comment by cpuguy83** [comment]
ping @mlaventure

**Comment by thaJeztah** [comment]
Should we add a random offset if the max is reached, to prevent all containers that failed to start after a reboot from retrying simultaneously?

**Comment by mlaventure** [comment]
Uh, I sure that value was set to something like 10/15sec at one point

**Comment by mlaventure** [comment]
Oh actually that was the value if the container managed to run long enough.

Hum, for one stuck in a restart loop indefinitely, I would say 1min should be good enough, wdyt @tonistiigi?

@thaJeztah `containerd` only allow 10 containers to be started concurrently

**Comment by tonistiigi** [comment]
@mlaventure 1-2min seems fine to me.
