### ISSUE TITLE
dockerfile: Split the ADD command

### ISSUE THREAD

**Issue by amluto** [docker/docker#3050]
Currently the ADD command is IMO far too magical.  It can add local and remote files.  It will sometimes untar a file and it will sometimes not untar a file.  If a file is a tarball that you want to copy, you accidentally untar it.  If the file is a tarball in some unrecognized compressed format that you want to untar, you accidentally copy it.

There's also essentially no security for downloads.

Can we have unambiguous options, please.  For example:

    COPY-IN <local file or directory> <target in image>

    UNTAR <local tarball> <target directory in image>

    DOWNLOAD NOVERIFY <URL> <target>

    DOWNLOAD SHA256 <sha256 hash> <URL> <target>

etc.

**Comment by dreamcat4** [comment]
Need the following:

* To have `ADD` or `UNPACK` or `EXTRACT` work for at least a minimum of compressed `.tar.gz` and `tgz` compressed format. But also as many others as is possible.

* Have `ADD` or `UNPACK` or `EXTRACT` be able to fetch and download and unpack in 1 step. From remote http:// `curl/wget` URL - whether it is ssl verified or not.

**Comment by duglin** [comment]
Once we have https://github.com/docker/docker/pull/10775 merged we can look to add options to ADD to allow for finer control over what happens.  I would prefer to do that than to add a ton of new top level Dockerfile commands that almost do the same thing as each other.  We can even then look to merge COPY and ADD, even having just those two causes confusion.

**Comment by thaJeztah** [comment]
> Once we have #10775 merged we can look to add options to ADD to allow for finer control over what happens

:+1:

**Comment by dreamcat4** [comment]
We also need a reliable caching of `ADD`'ed tarballs. Docker build is *supposed* to set `mtime` from `last-modified` HTTP header. But isn't working for us, neither from github releases URLS (redirected to s3 with a session key). Nor from local Apache webserver.

Where #7748 is as another possible solution to our caching problem. It downloads them every time, which sucks.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
