### ISSUE TITLE
docker pull fails with Error processing tar file

### ISSUE THREAD

**Issue by fluffy88** [docker/docker#30530]
**Description**
I cannot pull docker images as extraction fails.

**Steps to reproduce the issue:**
1. Clean install of Ubuntu Gnome
2. Follow "Install using the repository" and "Post-installation steps for Linux" from https://docs.docker.com/engine/installation/linux/ubuntu/
3. `docker pull mysql`

**Describe the results you received:**
All parts download but extraction fails on the first part with the following error
```
Using default tag: latest
latest: Pulling from library/mysql
5040bd298390: Extracting [==================================================>] 51.36 MB/51.36 MB
55370df68315: Download complete 
fad5195d69cc: Download complete 
a1034a5fbbfc: Download complete 
17f3570b42ae: Download complete 
6bf4b16e5339: Download complete 
9700c9731729: Download complete 
f2fea9c5b632: Download complete 
2f8101f5336d: Download complete 
0dc8f8a1031a: Download complete 
a1b9627588c7: Download complete 
failed to register layer: Error processing tar file(exit status 1): open /usr/share/man/man3/Locale::gettext.3pm.gz: invalid argument
```

**Describe the results you expected:**
Image should pull to my local machine.

**Additional information you deem important (e.g. issue happens only occasionally):**
I was able to pull the docker fedora image, but mysql, nextcloud and apache all fail with the same error.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 10:05:19 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 10:05:19 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: <unknown>
 Dirs: 3
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-34-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.57 GiB
Name: MY-PC-NAME
ID: SCJO:O3RC:FGT2:NDNJ:4H56:AJ7E:F3EG:5TVF:5ZTF:IV4H:24OU:SEYO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
**Output of `uname -a`:**
```Linux 4.8.0-34-generic #36-Ubuntu SMP Wed Dec 21 17:24:18 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux```

**Comment by thaJeztah** [comment]
What file system are you running on?

    Backing Filesystem: <unknown>

**Comment by fluffy88** [comment]
I have `/var/lib/docker` mounted on an NTFS filesystem.

```
/dev/sdb1 on /var/lib/docker type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
/dev/sdb1 on /var/lib/docker/aufs type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
/dev/sdb1 on /media/data/Docker/aufs type fuseblk (rw,relatime,user_id=0,group_id=0,allow_other,blksize=4096)
```

**Comment by fluffy88** [comment]
I tried unmounting the NTFS drive (leaving /var/lib/docker on an ext4 FS) and running docker again.  This time it worked perfectly.

I can continue working with this for now, but I would like to see NTFS supported as my ext4 drive is an SSD and it quite small (it's shared between Windows and Linux) so I like to move all the larger directories onto the HDD.

**Comment by thaJeztah** [comment]
unfortunately NTFS is not supported as a backing file system, and i don't think we'll be able to, so i'll have to close this issue

**Comment by fluffy88** [comment]
Fair enough, thanks for the help.
