### ISSUE TITLE
Docker supported 'external bridge' type

### ISSUE THREAD

**Issue by jamesdboone** [docker/docker#30535]
Feature request.

Need the equivalent of 'expose all ports, map all ports to external IP XYZ' capability.

I guess i can see this implemented in two ways:
a) create a custom bridge type, maybe 'external-bridge' that exposes container IPs like a bridge w/ NIC iface added.
b) Come up with a 'publish-all-ports-to-external-ip=XYZ' container run option.  Effective port 'range' management would be better, but having hundreds or thousands of individual port based processes running and/or iptable configs as currently implemented isn't going to be manageable.

Solution needs to translate across docker hosts, i.e. need to be able to bring down a container on one host and spin it up on another w/ same IP (hosts all on same subnet).

I'm managing this currently through a mix of docker commands and Linux native network commands overriding some things.  Have concerns with the long term supportability of this workaround...

**Comment by cpuguy83** [comment]
I'm pretty sure macvlan/ipvlan handles this case.
Have you looked at these?

**Comment by jamesdboone** [comment]
Ach!  I think you're right!  I didn't remember seeing the -parent option before when looking at macvlan.  Thanks for pointing me in the right direction!
