### ISSUE TITLE
Debian wheezy repository issue

### ISSUE THREAD

**Issue by PastisD** [docker/docker#30547]
**Steps to reproduce the issue:**

1. Follow insctructions for debian Wheezy here : https://docs.docker.com/engine/installation/linux/debian/
2. in my sources.list, I have : 
>deb https://apt.dockerproject.org/repo/ debian-wheezy main
>deb-src https://apt.dockerproject.org/repo/ debian-wheezy main
3. Running `apt-get update`

**Describe the results you received:**
Running `apt-get update` on Debian Wheezy just now results in

> W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-wheezy/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

**Comment by boskiv** [comment]
I have simmilar problem, but with xenial repo
```
root@git:/etc/init.d# curl -v https://apt.dockerproject.org/repo
*   Trying 52.84.223.83...

```
Seams like DNS problem. Are you using cloudfront ? I notice that last days slack have issues with DNS resolve/response.

**Comment by PastisD** [comment]
DNS are good on my side and i don't use cloudfront : 

```
root@ns*****:~# curl -v https://apt.dockerproject.org/repo
* About to connect() to apt.dockerproject.org port 443 (#0)
*   Trying 52.85.217.158...
* connected
* Connected to apt.dockerproject.org (52.85.217.158) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=*.dockerproject.org
*        start date: 2016-03-19 00:00:00 GMT
*        expire date: 2017-04-19 12:00:00 GMT
*        subjectAltName: apt.dockerproject.org matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
> GET /repo HTTP/1.1
> User-Agent: curl/7.26.0
> Host: apt.dockerproject.org
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 302 Moved Temporarily
< Content-Type: text/html; charset=utf-8
< Content-Length: 313
< Connection: keep-alive
< x-amz-error-code: Found
< x-amz-error-message: Resource Found
< Location: /repo/
< Date: Mon, 30 Jan 2017 09:29:49 GMT
< Server: AmazonS3
< X-Cache: Miss from cloudfront
< Via: 1.1 cc546671c46a09adf9c7ed8355a6a5e4.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: fMTp4K1T7xRPZXOLnHXdaqP53h6hmf4FCTcSHB1EeRN46443zP5Cww==
<
<html>
<head><title>302 Moved Temporarily</title></head>
<body>
<h1>302 Moved Temporarily</h1>
<ul>
<li>Code: Found</li>
<li>Message: Resource Found</li>
<li>RequestId: 24A7275320FC8462</li>
<li>HostId: a10C1CcQLulgqgah5M+e1TSaGVHQVF4LTQufud5o3ejaUnF19crl4EM7Gr/LizhV6gKo+dnfBRA=</li>
</ul>
<hr/>
</body>
</html>
* Connection #0 to host apt.dockerproject.org left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
```

**Comment by boskiv** [comment]
You use :)
` Via: 1.1 cc546671c46a09adf9c7ed8355a6a5e4.cloudfront.net (CloudFront)`
But resolved IP adresses are different(i think i't because GEO DNS settuped)

**Comment by PastisD** [comment]
Ah yes ok, it's apt.dockerproject.org that use cloudfront :P
Maybe a cloudfront issue then.

**Comment by tonistiigi** [comment]
@andrewhsu

**Comment by andrewhsu** [comment]
@PastisD I'm unable to reproduce your issue from my connection in California. Can you get me an output of `curl -v https://apt.dockerproject.org/repo/dists/debian-wheezy/Release > /dev/null`?

An up-to-date `Release` object should have `Last-Modified: Mon, 30 Jan 2017 19:46:34 GMT` like so:
```
$ curl -v https://apt.dockerproject.org/repo/dists/debian-wheezy/Release > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.84.244.17...
* TCP_NODELAY set
* Connected to apt.dockerproject.org (52.84.244.17) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.dockerproject.org
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
* Server certificate: Starfield Services Root Certificate Authority - G2
> GET /repo/dists/debian-wheezy/Release HTTP/1.1
> Host: apt.dockerproject.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 29373
< Connection: keep-alive
< Date: Tue, 31 Jan 2017 18:34:17 GMT
< x-amz-meta-s3cmd-attrs: uid:0/gname:root/uname:root/gid:0/mode:33261/mtime:1485562792/atime:1485562852/md5:e5ba0eca249296e52fdb923296ad86e3/ctime:1485562792
< Last-Modified: Mon, 30 Jan 2017 19:46:34 GMT
< x-amz-version-id: HDTLlbCMOoc6WFH0oHhxo5omF.RqCfAS
< ETag: "e5ba0eca249296e52fdb923296ad86e3"
< Server: AmazonS3
< Age: 43
< X-Cache: Hit from cloudfront
< Via: 1.1 b04a4cffa8fb4f524ff7edcab1b5ae31.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: 6edyIfFIKCFWLGUkwd-rotQsNuDsVb6G_R6JTVFyM_7NIN0cD_zHNQ==
< 
{ [16384 bytes data]
* Curl_http_done: called premature == 0
100 29373  100 29373    0     0   557k      0 --:--:-- --:--:-- --:--:--  562k
* Connection #0 to host apt.dockerproject.org left intact
```

**Comment by PastisD** [comment]
The Last-Modified date is the same here :s

```
root@ns333691:~# curl -v https://apt.dockerproject.org/repo/dists/debian-wheezy/Release > /dev/null
* About to connect() to apt.dockerproject.org port 443 (#0)
*   Trying 52.85.217.158...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* connected
* Connected to apt.dockerproject.org (52.85.217.158) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
*        subject: CN=*.dockerproject.org
*        start date: 2016-03-19 00:00:00 GMT
*        expire date: 2017-04-19 12:00:00 GMT
*        subjectAltName: apt.dockerproject.org matched
*        issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*        SSL certificate verify ok.
> GET /repo/dists/debian-wheezy/Release HTTP/1.1
> User-Agent: curl/7.26.0
> Host: apt.dockerproject.org
> Accept: */*
>
* additional stuff not fine transfer.c:1037: 0 0
* HTTP 1.1 or later with persistent connection, pipelining supported
< HTTP/1.1 200 OK
< Content-Type: text/plain
< Content-Length: 29373
< Connection: keep-alive
< Date: Tue, 31 Jan 2017 18:32:50 GMT
< x-amz-meta-s3cmd-attrs: uid:0/gname:root/uname:root/gid:0/mode:33261/mtime:1485562792/atime:1485562852/md5:e5ba0eca249296e52fdb923296ad86e3/ctime:1485562792
< Last-Modified: Mon, 30 Jan 2017 19:46:34 GMT
< x-amz-version-id: HDTLlbCMOoc6WFH0oHhxo5omF.RqCfAS
< ETag: "e5ba0eca249296e52fdb923296ad86e3"
< Server: AmazonS3
< Age: 291
< X-Cache: Hit from cloudfront
< Via: 1.1 469e23f84ba232044692da91403d240b.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: mbeJb3BAm_Y4_V_PYmUWNatr9ct608E_19bzP4YhWuavQADnECPuzg==
<
{ [data not shown]
100 29373  100 29373    0     0   190k      0 --:--:-- --:--:-- --:--:--  270k
* Connection #0 to host apt.dockerproject.org left intact
* Closing connection #0
* SSLv3, TLS alert, Client hello (1):
} [data not shown]

```

**Comment by andrewhsu** [comment]
Ok, cache looks like it is serving the correct file from origin.

Can you output your `/etc/apt/sources.list` and `/etc/apt/sources.list.d/docker.list`? It almost seems like you have a rogue `deb-src` entry somewhere that is trying to download source pkgs from the apt repo.

**Comment by PastisD** [comment]
/etc/apt/sources.list :

```
deb http://debian.mirrors.ovh.net/debian/ wheezy main
deb-src http://debian.mirrors.ovh.net/debian/ wheezy main

deb http://security.debian.org/ wheezy/updates main
deb-src http://security.debian.org/ wheezy/updates main

deb http://http.debian.net/debian wheezy main non-free
deb http://http.debian.net/debian wheezy contrib

deb http://ftp.debian.org/debian wheezy-backports main
deb https://apt.dockerproject.org/repo/ debian-wheezy main
deb-src https://apt.dockerproject.org/repo/ debian-wheezy main

```

I don't have a `/etc/apt/sources.list.d/docker.list` file

**Comment by andrewhsu** [comment]
Remove the `deb-src https://apt.dockerproject.org/repo/ debian-wheezy main` line and try again.

**Comment by PastisD** [comment]
It worked, thx you :D

**Comment by szarouski** [comment]
I can confirm that I had the same issue on debian wheezy and removing deb-src like mentioned above helped. Thank you.

**Comment by schattenlink** [comment]
Yeah. Removing the source may resolve the warning at apt-get update but updating or installing of the docker-engine surely is not possible any more because of that. So it's not an acceptable solution. 
Also [this Issue on the docs.docker repo](https://github.com/docker/docker.github.io/issues/1654) points on this problem.

**Comment by szarouski** [comment]
Yes, I had to update to jessie. Fortunately it was straight forward for me.

**Comment by ksigjayt** [comment]
szarouski, can you please update debian wheezy too?  I am seeing the same issue there.
# lsb_release -cs
wheezy

# sudo apt-get update
...
W: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-wheezy/Release  Unable to find expected entry 'main/source/Sources' in Release file (Wrong sources.list entry or malformed file)

**Comment by ksigjayt** [comment]
Adding additional information to this thread in case this helps. I can't install docker-engine because the repo appears to have bad information

# lsb_release -a -cs
Debian
Debian GNU/Linux 7.7 (wheezy)
7.7
wheezy

# grep docker /etc/apt/sources.list 
deb https://apt.dockerproject.org/repo/ debian-wheezy main
deb-src https://apt.dockerproject.org/repo/ debian-wheezy main

**Comment by their** [comment]
Also confirm that on wheezy removing deb-src fixes issue:

```
deb https://apt.dockerproject.org/repo/ debian-wheezy main
#deb-src https://apt.dockerproject.org/repo/ debian-wheezy main
```

```
uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.84-2 x86_64 GNU/Linux
```

**Comment by ksigjayt** [comment]
If I comment out the deb-src line you mentioned above, that does not resolve my issue.
The problem is with the content in the repository, not on the client-side.

If I were to uncomment out the deb-src line you reference above from my sources.lst file, I am unable to install the docker-engine package -- which was the whole point people adding it in the first place.  I am showing below the output I get from apt-get if I uncomment the line you are referencing...  I appreciate the help, but I'm pretty sure that uncommenting the line is not the correct fix here - the repository content is not correct for debian wheezy running on arch=armhf.  

The repo has a bad Release file.
==> Unable to find expected entry 'main/source/Sources' in Release file

Please check the repo as this file does not exist that is specified in 
https://apt.dockerproject.org/repo/dists/debian-wheezy/Release




# sudo apt-get -y install docker-engine
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package docker-engine

People are following the documentation at the below link and it doesn't work:
https://docs.docker.com/engine/installation/linux/debian/#/install-using-the-repository

**Comment by Hoeze** [comment]
I've got the same problem with debian stretch:
`deb-src [arch=amd64] https://download.docker.com/linux/debian stretch stable`
=>

> Reading package lists... Done
> E: Failed to fetch https://download.docker.com/linux/debian/dists/stretch/InRelease  Unable to find expected entry 'stable/source/Sources' in Release file (Wrong sources.list entry or malformed file)

**Comment by thaJeztah** [comment]
@Hoeze does it work if you comment that line?

**Comment by Hoeze** [comment]
yes, when i comment out that line it works without problems

**Comment by godleydemon** [comment]
any fix for this yet, this is still an issue

**Comment by jtorvald** [comment]
Exact same issue here

**Comment by Hoeze** [comment]
Could somebody reopen this issue?
Simply ignoring the package source code is pretty bad practice, especially in terms of reproducible packaging.

**Comment by blop** [comment]
Same issue as of today : following documentation on https://docs.docker.com/engine/installation/linux/docker-ce/debian/
