### ISSUE TITLE
Can't mount a host directory if the container directory exists and contains a file

### ISSUE THREAD

**Issue by dgageot** [docker/docker#30556]
When using Windows containers, you can mount a host directory and overlay an existing container directory.

An error occurs when trying to start the container:

> docker: Error response from daemon: container db565702e017c2680415b7cd5681a3467d8bd3c769ce7f4499de9f429927ad45 encountered an error during Start: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a).

### Information

λ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Thu Oct 27 00:09:21 2016
 OS/Arch:      windows/amd64
 Experimental: true

Server:
 Version:      1.12.2-cs2-ws-beta
 API version:  1.25
 Go version:   go1.7.1
 Git commit:   050b611
 Built:        Tue Oct 11 02:35:40 2016
 OS/Arch:      windows/amd64
### Steps to reproduce the behavior

Example Dockerfile:

```
FROM microsoft/nanoserver 

WORKDIR c:/temp
COPY a.file c:/temp/a.file
```

Build and then run:

```
docker run -v c:/temp:c:/temp foo-image cmd

docker: Error response from daemon: container 3952c075b90fb85ff79b9616626e3b7b8acc1056a33b7e7546ffa801a094976c encountered an error during Start: failure in a Windows system call: The connection with the Virtual Machine hosting the container was closed. (0xc037010a).
```

Linux containers allow mounting under this scenario. The host directory would overlay the container directory, but would not remove the pre-existing content. 

Interestingly, it's fine if there is no file in the existing container directory, e.g.:

```
FROM microsoft/nanoserver 

WORKDIR c:/temp
```

```
docker run -v c:/temp:c:/temp foo-image cmd

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\temp>
```

**Comment by lurock** [comment]
I am having the same issue on this version:

**Comment by furman87** [comment]
Same here.

**Comment by thaJeztah** [comment]
Unfortunately this is a limitation of the platform (Windows); a note has been added to the documentation; https://github.com/docker/docker/pull/28778, but there's nothing we can do in Docker's source code to fix this  https://github.com/docker/docker/pull/28778#discussion_r89413902, https://github.com/Microsoft/Virtualization-Documentation/issues/497#issuecomment-262636687

For that reason, I'm closing this issue
