### ISSUE TITLE
Docker Swarm Mode --advertise-addr need help

### ISSUE THREAD

**Issue by anupriya17** [docker/docker#30550]
Docker 1.13 running in Swarm Mode
 ```
--listen-addr     0.0.0.0:2377
--advertise-addr  PUBLIC-IP:2377
```
On Linode/Digital Ocean the data transfer within the same data center is free. 

Lets says 3 Nodes in Datacenter-1 and 4 nodes in Datacenter-2.

So how will swarm load balance the services within data center using public IP or private IP?

I want private IP to be used in same datacenter and public IP for cross datacenter connections. 
Could this be possible or do i need different settings?

Thanks

**Comment by fntlnz** [comment]
@anupriya17 
You could use the public IPs to setup the cluster and then configure ip forwarding (e.g via the iptables OUTPUT chain) on each node to match your requirement (route a public ip to a private ip if is a node on the same provider)

**Comment by anupriya17** [comment]
@fntlnz 
Sorry again, I'm new to iptables, after digging on google i found this. Will this work:

```
sysctl net.ipv4.ip_forward=1
```

```
iptables -t nat -A OUTPUT -p tcp -s PUBLIC-IP -j DNAT --to-destination PRIVATE-IP
```

**Comment by fntlnz** [comment]
@anupriya17 yes just that but you will want to allow all protocols, e.g: overlay networking uses UDP

something like:

```
iptables -t nat -A OUTPUT -p all  -d PUBLIC-IP -j DNAT --to-destination PRIVATE-IP
```

**Comment by anupriya17** [comment]
Yep you're right. Thanks.
