### ISSUE TITLE
Installing Docker RHEL 7 failed

### ISSUE THREAD

**Issue by hypePG** [docker/docker#30559]
**Description**

Hey,

during the rpm installation of docker on a RHEL7 system i get the following error:

 sudo yum install /tmp/docker-engine-1.13.0-1.el7.centos.x86_64.rpm
Loaded plugins: langpacks, product-id, rhnplugin, search-disabled-repos
This system is receiving updates from RHN Classic or Red Hat Satellite.
Examining /tmp/docker-engine-1.13.0-1.el7.centos.x86_64.rpm: docker-engine-1.13.0-1.el7.centos.x86_64
Marking /tmp/docker-engine-1.13.0-1.el7.centos.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package docker-engine.x86_64 0:1.13.0-1.el7.centos will be installed
--> Processing Dependency: docker-engine-selinux >= 1.13.0-1.el7.centos for package: docker-engine-1.13.0-1.el7.centos.x86_64
--> Processing Dependency: libltdl.so.7()(64bit) for package: docker-engine-1.13.0-1.el7.centos.x86_64
--> Processing Dependency: libseccomp.so.2()(64bit) for package: docker-engine-1.13.0-1.el7.centos.x86_64
--> Running transaction check
---> Package docker-engine.x86_64 0:1.13.0-1.el7.centos will be installed
--> Processing Dependency: docker-engine-selinux >= 1.13.0-1.el7.centos for package: docker-engine-1.13.0-1.el7.centos.x86_64
---> Package libseccomp.x86_64 0:2.3.1-2.el7 will be installed
---> Package libtool-ltdl.x86_64 0:2.4.2-21.el7_2 will be installed
--> Finished Dependency Resolution
Error: Package: docker-engine-1.13.0-1.el7.centos.x86_64 (/docker-engine-1.13.0-1.el7.centos.x86_64)
           Requires: docker-engine-selinux >= 1.13.0-1.el7.centos
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

3.10.0-514.2.2.el7.x86_64
Red Hat Enterprise Linux Server release 7.3 (Maipo)

I saw that there were similiar issues, but i wasn't able to resolve mine with the advices given.

thanks in advance.

**Comment by hypePG** [comment]
Installation is successful up to Docker 1.8.3 every release after this fails.

**Comment by thaJeztah** [comment]
I'm not too familiar with the update channels, but could this be related?

    This system is receiving updates from RHN Classic or Red Hat Satellite.

Could it be that updates are pinned to older versions because of that?

ping @andrewhsu any ideas?

**Comment by andrewhsu** [comment]
@hypePG the docker-engine rpm depends on docker-engine-selinux rpm and it can't find it because it looks like the repo is not defined for yum to retrieve docker-engine-selinux.

I'd recommend installing docker using the official instructions: https://docs.docker.com/engine/installation/linux/centos/

Instead of installing from manually downloaded rpms placed in `/tmp` directory.

Using the official instructions will setup a repo definition for yum where you can get the latest updates from docker when they are released.

**Comment by thaJeztah** [comment]
Oh, completely missed the install from `/tmp/docker-engine-1.13.0-1.el7.centos.x86_64.rpm`
@hypePG can you try with the steps @andrewhsu mentioned? I suspect that's the reason it's not working, so let me go ahead and close, but please let us know if you succeeded
