### ISSUE TITLE
Unable to map files into Windows container

### ISSUE THREAD

**Issue by dgageot** [docker/docker#30555]
### Expected behavior
Mapping a file should show the file in the container. 

### Actual behavior
Mapping a file or a directory both work on Linux.
Mapping a file fails on Windowsm with Windows Containers.

### Information
Docker: 1.13.0-rc5-beta35 (9606)
OS: Windows 10 (1607 - Anniversary edition) and Windows Server 2016 with containers (Azure)

### Steps to reproduce the behavior
 `docker run -v C:\users\ramon\test:C:\test nanoserver cmd /c dir \`

```
Error response from daemon: invalid bind mount spec "C:\\users\\ramon\\test.config:C:\\test.config": invalid volume specification: 'C:\users\ramon\test.config:C:\test.config': invalid mount config for type "bind": source path must be a directory.
```

**Comment by justincormack** [comment]
Bind mounting files is a Linux specific quirk, no other Unix or non Unix OS I know of supports it, and portable code should not rely on it.

**Comment by drnybble** [comment]
https://docs.docker.com/engine/reference/commandline/run/

The following examples will fail when using Windows-based containers, as the destination of a volume or bind-mount inside the container must be one of: a non-existing or empty directory; or a drive other than C:. Further, the source of a bind mount **must be a local directory, not a file.**

**Comment by thaJeztah** [comment]
Correct, bind-mounting files is not possible on Windows. On Linux, there's also quite some pitfalls though, so mounting a directory is preferred in many situations.

**Comment by friism** [comment]
Should we change the samples to only do things that are likely to be portable?

**Comment by thaJeztah** [comment]
Where possible, we should definitely try to avoid examples that bind-mount individual files. As mentioned, bind-mounting files can cause a lot of headaches (e.g. editing such a file can lead to issues as well).

Given that the information around this is spread over various locations in the docs, I guess we need a big rewrite to consolidate all that information

**Comment by jhowardmsft** [comment]
From an immediate issue perspective, I'm closing this as it is in the documentation under https://docs.docker.com/engine/reference/commandline/run/#/mount-volume--v---read-only. It is a platform limitation on Windows, not docker itself.

```
The following examples will fail when using Windows-based containers, as the destination of a volume or bind-mount inside the container must be one of: a non-existing or empty directory; or a drive other than C:. Further, the source of a bind mount must be a local directory, not a file.
```

**Comment by Drewster727** [comment]
ummm is this really still happening? I'm shocked lol. I guess I'll write an entrypoint script that copies files into my container from a mounted folder? hacky.

**Comment by thaJeztah** [comment]
@Drewster727 I think mounting files is now possible in Windows Server 2019 (RS5 and up)

**Comment by thaJeztah** [comment]
This may be an interesting read: https://blog.sixeyed.com/what-you-can-do-with-docker-in-windows-server-2019-that-you-couldnt-do-in-windows-server-2016/

**Comment by Drewster727** [comment]
Hey @thaJeztah thanks for the reply.
At the bottom of that article it states 

"One quirk remains. You still can't mount a single file as a volume, you'll get invalid mount config for type "bind": source path must be a directory"

I'm attempting this on server 2019, still no bueno unfortunately. It's getting better though!

**Comment by Drewster727** [comment]
For some context on my situtation--
For those of us running apps in the legacy .NET framework world (/sad-face) -- we have .config files mixed in with our application binaries. 
We don't want to build environment-specific containers, so of course, we try to share config files that have been transformed per environment directly inside the container to the location our application expects them. 

In case it helps anyone, I have an entrypoint.ps1 script to get around this issue for now. Share a directory to c:\conf with config files in it, the script will copy them into the app context folder on start:
```if(Test-Path c:\conf){
    Copy-Item -path c:\conf\*.* -Recurse -Destination . -Force
}```

**Comment by thaJeztah** [comment]
Whoops, I might've recalled incorrectly then 😔 apologies, think I got overexcited because mounting the docker API named pipe worked

**Comment by olegburov** [comment]
> I think mounting files is now possible in Windows Server 2019 (RS5 and up)

Unfortunately, it still doesn't work. I gave it a try on Windows 10 version 1903 (aka Windows 10 May 2019 Update).

```powershell
PS C:\> docker run --rm -it `
          -v "C:\Program Files\Docker\Docker\Resources\bin\docker.exe:C:\Program Files\Docker\Docker\Resources\bin\docker.exe:ro" `
          -v //./pipe/docker_engine://./pipe/docker_engine `
          mcr.microsoft.com/windows/servercore:1903

docker: Error response from daemon: invalid volume specification: 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe:C:\Program Files\Docker\Docker\Resources\bin\docker.exe:ro': invalid mount config for type "bind": source path must be a directory.
See 'docker run --help'.
```

**Comment by artisticcheese** [comment]
I just use symbolic link mapping instead of copying files over in such cases, this seems to be do the trick with no drawbacks of other solutions https://artisticcheese.wordpress.com/2021/05/02/circumventing-windows-containers-limitation-on-volume-mounts/

**Comment by leblancmeneses** [comment]
Thank @Drewster727. I'm dealing with the same type of configs.

I'm using lifecycle events to avoid updating Dockerfile's for all the legacy apps we are bringing under k8.
```
          lifecycle:
            postStart:
              exec:
                command: ["powershell", "c:/onstart/on.start.ps1"]
```
