### ISSUE TITLE
LXD - Docker pull "failed to register layer"

### ISSUE THREAD

**Issue by CarltonSemple** [docker/docker#30569]
**Description**
When running Docker in an LXD container, following the Docker profile setup as described here https://www.stgraber.org/2016/04/13/lxd-2-0-docker-in-lxd-712/ ,
some images fail to pull. Docker gives an 

**Steps to reproduce the issue:**
1. lxc launch ubuntu-daily:16.04 docker -p default -p docker
2. lxc exec docker -- apt install docker.io -y
3. lxc exec docker bash
4. docker pull gcr.io/google_containers/etcd-amd64:3.0.4

**Describe the results you received:**
The pull process ends with 
`failed to register layer: ApplyLayer exit status 1 stdout:  stderr: lchown /usr/local/bin/etcd: invalid argument`

**Describe the results you expected:**
The `docker pull gcr.io/google_containers/etcd-amd64:3.0.4` works on the host machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
root@docker:~# docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   6b644ec
 Built:        Mon, 19 Dec 2016 09:20:48 +1300
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
root@docker:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.3
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 31.38 GiB
Name: docker
ID: M23A:7M66:UQAE:HMVX:7QUP:36FN:W5BG:WOJ7:G3I5:PDMG:P4PI:NEFC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
LXD container

**Comment by justincormack** [comment]
Docker in `lxd` is not currently a supported platform, and quite a few issues have been reported. It would be good to get it working, but it may be complicated.

**Comment by CarltonSemple** [comment]
Sorry, I opened this in the wrong repository then
