### ISSUE TITLE
Port Range in cloud.docker YAML 

### ISSUE THREAD

**Issue by zarubto4** [docker/docker#30589]
Hi, 
There is a possibility to set a range of public ports.
But in the Cloud tool  its forbidden.

![snimek obrazovky 2017-01-31 v 13 57 01](https://cloud.githubusercontent.com/assets/16296782/22465683/287dd006-e7bd-11e6-89c1-b675be92b2e8.png)

> Value u "-"9090-9091:8080-8081" 'for field' <volume> .ports' is not the type of array. See 'https://docs.docker.com/docker-cloud/feature-reference/stack-yaml-reference/' for more details

**Comment by zarubto4** [comment]
In this case
![snimek obrazovky 2017-01-31 v 13 54 46](https://cloud.githubusercontent.com/assets/16296782/22465611/dd59a8de-e7bc-11e6-8881-a8e5266ed265.png)

I have:

> - Service 'homer': Value u'-"3000:8080" -"8500:8500" -"8501:8501" -"1881:1881"' for field '<obj>.ports' is not of type array. See 'https://docs.docker.com/docker-cloud/feature-reference/stack-yaml-reference/' for more details

**Comment by ehazlett** [comment]
Could you post this in the Docker Cloud forums (https://forums.docker.com/c/docker-cloud).  We can't fix this here.  Thanks!
