### ISSUE TITLE
docker top breaks when showing thread information after processes

### ISSUE THREAD

**Issue by resilva87** [docker/docker#30580]
**Description**

Attempting to show threads after process in `top` command (`m` flag) returns 

`Error response from daemon: Unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax` 

**Steps to reproduce the issue:**
1. Pull any image
2. Run a new container
3. Run `docker top <container-id> m`

**Describe the results you received:**

`Error response from daemon: Unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax` 

**Describe the results you expected:**

ps information such as:

```
PID TTY      STAT   TIME COMMAND
  173 ?        -      0:00 /bin/bash
    - -        Ss     0:00 -
  190 ?        -      0:00 ps m
    - -        R+     0:00 -
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Combining `m` flag with any other causes the problem (such as `ps muax`)

This error seems related to ps output parsing function implemented in https://github.com/docker/docker/blob/master/daemon/top_unix.go

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.659 GiB
Name: rsilva-note
ID: G3OH:BUGW:Z6RR:6BVO:YSAV:QYEE:6VVL:FJQ4:Q7LW:OXIJ:LUHT:Q2VJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.10

**Comment by catinthesky** [comment]
@resilva87, refer here https://docs.docker.com/engine/reference/commandline/top/, you need provide "ps" command available option, for instance: "docker top 67ca37486c63 -aef" (make sure "-" ahead of the option).

However, it seems a little mis-understanding, to give feedback when there is no such option for command "ps", say:

[root@c9t23123 docker]# docker top 67ca37486c63 -m
Error response from daemon: Unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax

Recommend to give more meaningful message, such as "Please provide valid 'ps' command option" or whatever proper.

**Comment by catinthesky** [comment]
The problem can also be reproduced in latest version, which was caused here in the code(~/daemon/top_unix.go):
-------------------
 60   // loop through the output and extract the PID from each line
 66     p, err := strconv.Atoi(fields[pidIndex])
 67     if err != nil {
 68       return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
 69     }
------------------
When using the "ps m" command whose output like:
-----------
  PID TTY      STAT   TIME COMMAND
  321 pts/16   -      0:00 bash
    - -        Ss+    0:00 -
  805 pts/2    -      0:00 bash
    - -        Ss+    0:00 -
 1651 pts/23   -      0:12 go tool tour
------------
The line with invalid pid "  - -        Ss+    0:00 -" will lead to the problem (not able to convert the "-" to "int")

Any suggestions on how to fix it ( I intend to create a PR for this ).

**Comment by catinthesky** [comment]
The problem can also be reproduced in latest version, which was caused here in the code(~/daemon/top_unix.go):
 _60   // loop through the output and extract the PID from each line
 66     p, err := strconv.Atoi(fields[pidIndex])
 67     if err != nil {
 68       return nil, fmt.Errorf("Unexpected pid '%s': %s", fields[pidIndex], err)
 69     }_

When using the "ps m" command whose output like:

  _PID TTY      STAT   TIME COMMAND
  321 pts/16   -      0:00 bash
    - -        Ss+    0:00 -
  805 pts/2    -      0:00 bash
    - -        Ss+    0:00 -
 1651 pts/23   -      0:12 go tool tour_

The line with invalid pid "  - -        Ss+    0:00 -" will lead to the problem (not able to convert the "-" to "int")

Any suggestions on how to fix it ( I intend to create a PR for this ).

**Comment by resilva87** [comment]
Hi,

After messing around a bit with both code and unit tests, I wonder, is it still necessary to verify that the number of header  titles match the number of fields in `ps` output?

I mean, I'm more than favor for such validation specially when it depends on system tools but I can't see any example of `ps` showing extra headers (or fields) than required. 

The unit tests for `top` daemon command (https://github.com/docker/docker/blob/master/daemon/top_unix_test.go) don't seem to test clearly this expectation, so I'd like to understand if this still has its points or maybe it should be simpler enough to only format `ps` output in tabular format (after removing the validation code below unit tests still passed):

```
for _, pid := range pids {
    if pid == p {
        // Make sure number of fields equals number of header titles
        // merging "overhanging" fields
        process := fields[:len(procList.Titles)-1]
        process = append(process, strings.Join(fields[len(procList.Titles)-1:], " "))
        procList.Processes = append(procList.Processes, process)
    }
}
```

Thanks.

**Comment by catinthesky** [comment]
Checking "ps" command's output, it seems only option "-m" having set column "PID" as "-" in the output,  so in PR #30669,  fixing the bug through ignoring the thread line when found "PID" column being "-".

**Comment by resilva87** [comment]
Hi,

Don't know if just ignoring thread information lines is the best option here. It's valid output and one I'm interested checking.

I still wonder, is there such case that the number of header titles won't match the number of fields? I can't find a way to reproduce such problem.

Thanks.

**Comment by catinthesky** [comment]
@resilva87,  the number of header titles should match the number of fields, they are generated from "ps" output, why are you worried in this regard.

From checking the source code, the "docker top" command on purpose checking the PID, so only the lines with matching PID should be returned, so currently not all the information is intended to be exposed by such command.

**Comment by resilva87** [comment]
@catinthesky No worries. What I'm saying is that if this validation is not necessary, than the complete output of `ps` command should be returned, which is not happening due to the code above: 

```
for _, pid := range pids {
    if pid == p {
        // Make sure number of fields equals number of header titles
        // merging "overhanging" fields
        process := fields[:len(procList.Titles)-1]
        process = append(process, strings.Join(fields[len(procList.Titles)-1:], " "))
        procList.Processes = append(procList.Processes, process)
    }
}
```

Also, `docker top` not only checks one PID. All processes running inside a container are listed, which is kind the point of this command in a host system (of course you can filter a given PID)

**Comment by ripcurld0** [comment]
@resilva87 I probably wrong but it feels like the current implementation of top is problematic when specifying number of ps options such as -L and m.

**Comment by resilva87** [comment]
Hi,

@ripcurld0 I understand. Don't get me wrong, I think this a very nice feature to have for monitoring my containers, but it would be even cooler to have the same kind of information I can get with my host `ps` :). That's why I don't think skipping these problematic lines in the output would be great... The info is there, it's only a matter of formatting.

**Comment by catinthesky** [comment]
@ripcurld0,  I checked the option "L":
when command like: "docker top <container-id> L", its output without column "PID" will make it fail.
What's the problem of "T" option,  can you share the problem you found.

@thaJeztah, is there some suggestion or resource to ping, it looks the problem of "docker top" command in regard of "TmL" (thread related)  is problematic, in summary, command fails in:
    1) when "pid" column (being "-") not able to be converted into "int" 
    2) when output not containing "pid" column.
Which is caused by "pid" checking, can it be ignored ? 
or if keep "pid" checking what's the proper strategy to deal with the above situation?

**Comment by catinthesky** [comment]
I dig a little further to find that, current implementation kind of like: (in daemon/top_unix.go), first using:
         pids, err := daemon.containerd.GetPidsForContainer(container.ID)
to get the container contained process ids, then using this statement:
        output, err := exec.Command("ps", strings.Split(psArgs, " ")...).Output()
to get all the "ps"'s output, ten filtered based on the above contained pids to get the right output.

So, the strategy I think of so far: 
      1) keep current, PID filtering, for "docker top" with "-m" option,  can get the following threads lines added until encounter next process, but it can not solve the "L" exclusive option (which to my checking, no way to make PID added to the output).
     2)  Directly using command: exec.Command("docker-runc", args...).CombinedOutput() in table format to get the output, but this also having problem when it comes to "m" "L" option, so need to raise bug to "runc" project to see if it can be fixed. 

_[root@c9t23123 containerd]# docker-runc ps --format=table  "7dced85bcbdf633d04ae0fca848628613fe2c2ed1843910076f51fd8050c7afb" L
couldn't find PID field in ps output
[root@c9t23123 containerd]# docker-runc ps --format=table  "7dced85bcbdf633d04ae0fca848628613fe2c2ed1843910076f51fd8050c7afb" m
  PID TTY      STAT   TIME COMMAND
unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax
[root@c9t23123 containerd]# docker-runc ps --format=table  "7dced85bcbdf633d04ae0fca848628613fe2c2ed1843910076f51fd8050c7afb" -m
  PID TTY          TIME CMD
unexpected pid '-': strconv.ParseInt: parsing "-": invalid syntax_

I would recommend the second option to raise bug to "runc" project.

**Comment by thaJeztah** [comment]
I left a suggestion on the PR https://github.com/docker/docker/pull/30669#issuecomment-277181577

We're aware that the `docker top` implementation is far from ideal, because it relies on commands on the host (which is not standardized, and differs  between distros)

**Comment by catinthesky** [comment]
@thaJeztah , thanks a lot.

**Comment by GonzaloGM** [comment]
I'm having this error too. I'm using Windows 10 Pro x64 in English. Happens to me on every container I try. I hope I'm reporting this where it belongs. If not, let me know. Thanks.

```
PS D:\node\docker> docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
f44a78a520df        mongo               "docker-entrypoint..."   6 minutes ago       Up 6 minutes        27017/tcp           mongo
PS D:\node\docker> docker top mongo
Error response from daemon: Unexpected pid '113361root': strconv.Atoi: parsing "113361root": invalid syntax
PS D:\node\docker> docker inspect mongo
[
    {
        "Id": "f44a78a520df8f5458d4c67ed7d452119d8b7a51388243622f758b819a8de561",
        "Created": "2017-07-08T00:33:26.1265152Z",
        "Path": "docker-entrypoint.sh",
        "Args": [
            "mongod"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 123355,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-07-08T00:33:26.690844Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:57c67caab3d8f9ed1fbffe159b10be52e0a0610122c16b3efea50a90ff435584",
        "ResolvConfPath": "/var/lib/docker/containers/f44a78a520df8f5458d4c67ed7d452119d8b7a51388243622f758b819a8de561/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/f44a78a520df8f5458d4c67ed7d452119d8b7a51388243622f758b819a8de561/hostname",
        "HostsPath": "/var/lib/docker/containers/f44a78a520df8f5458d4c67ed7d452119d8b7a51388243622f758b819a8de561/hosts",
        "LogPath": "/var/lib/docker/containers/f44a78a520df8f5458d4c67ed7d452119d8b7a51388243622f758b819a8de561/f44a78a520df8f5458d4c67ed7d452119d8b7a51388243622f758b819a8de561-json.log",
        "Name": "/mongo",
        "RestartCount": 0,
        "Driver": "overlay2",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                32,
                159
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/302a2f49532595c7a2bfe1211a78f098fbdf942db79464671880fc217f18d017-init/diff:/var/lib/docker/overlay2/495b4d6f7203b379099772e27ba9199131537500c4fcf318b8f31681c0278eba/diff:/var/lib/docker/overlay2/f5bede3e06314f50788134c830535671f66b56269be42caa994ddb0bb84fd325/diff:/var/lib/docker/overlay2/7b7cbbb405ba617884c42ccd743dfa495bb9f7684ff852146a153f53345689b5/diff:/var/lib/docker/overlay2/7bc2cb44d6e5d7c7893609b58414d2763dbd42918b598bb8ac9bad6595bab223/diff:/var/lib/docker/overlay2/0e92416422a8d0ac51548f1c8be476a8e9946dced9b4532780f2679cb405f679/diff:/var/lib/docker/overlay2/d4e2c0c6242649c00c14ad5006a6cebedff5cba7c40a76447fd56e745e17f3f0/diff:/var/lib/docker/overlay2/74b6840937f06d0d59fa33d86886f75580a4716dd09d5927e906b4b74f7cd031/diff:/var/lib/docker/overlay2/02ad9da337f519dd8b770777e2a9c5fc4141f2793af2b267637247f8085269f2/diff:/var/lib/docker/overlay2/e1c8d3db225a407d0b88cb25561000169330e2b71b34aa36ebd44c5f5412b634/diff:/var/lib/docker/overlay2/a9ce056cd169e484f72577c940dc8cc00c1b2b0e1ee579a044306a93e2908ed3/diff:/var/lib/docker/overlay2/4a4af9ecca54098e7cdc0633e219e6f3d88ff512188acbd5f5c4e922f3982448/diff",
                "MergedDir": "/var/lib/docker/overlay2/302a2f49532595c7a2bfe1211a78f098fbdf942db79464671880fc217f18d017/merged",
                "UpperDir": "/var/lib/docker/overlay2/302a2f49532595c7a2bfe1211a78f098fbdf942db79464671880fc217f18d017/diff",
                "WorkDir": "/var/lib/docker/overlay2/302a2f49532595c7a2bfe1211a78f098fbdf942db79464671880fc217f18d017/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "volume",
                "Name": "6e87a2248b88217fc78ea4089178bb2dde759092890e7568c5a82c6c8437c904",
                "Source": "/var/lib/docker/volumes/6e87a2248b88217fc78ea4089178bb2dde759092890e7568c5a82c6c8437c904/_data",
                "Destination": "/data/configdb",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "e0596cf37fa6783363654f916148806269c40c3a72da623d92938da8a18afc5e",
                "Source": "/var/lib/docker/volumes/e0596cf37fa6783363654f916148806269c40c3a72da623d92938da8a18afc5e/_data",
                "Destination": "/data/db",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
        ],
        "Config": {
            "Hostname": "f44a78a520df",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "27017/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "GOSU_VERSION=1.7",
                "GPG_KEYS=0C49F3730359A14518585931BC711F9BA15703C6",
                "MONGO_PACKAGE=mongodb-org",
                "MONGO_REPO=repo.mongodb.org",
                "MONGO_MAJOR=3.4",
                "MONGO_VERSION=3.4.6"
            ],
            "Cmd": [
                "mongod"
            ],
            "ArgsEscaped": true,
            "Image": "mongo",
            "Volumes": {
                "/data/configdb": {},
                "/data/db": {}
            },
            "WorkingDir": "",
            "Entrypoint": [
                "docker-entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {}
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "aa886946f63adf9c466fa7fc15792641da701cdd229fa9d45572e6fb85e95d91",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "27017/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/aa886946f63a",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "b30bbb8f45b9ee82534b1d5ff19a6c9d68371f0938c7cff80fea73617e6bca29",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "453e4a328572e1c96e29b7e9feef3e01e55e1a88f4c9f0a7ab8565672969f325",
                    "EndpointID": "b30bbb8f45b9ee82534b1d5ff19a6c9d68371f0938c7cff80fea73617e6bca29",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
PS D:\node\docker>
```
