### ISSUE TITLE
docker exec attempting to honor docker-compose links??

### ISSUE THREAD

**Issue by danonorato** [docker/docker#30596]
I just installed the native docker for MAC OS. (had been using docker-machine for a few years). I can no longer "docker exec it <containter_id>" for containers launched via docker-compose who have links to transient containers(ie come up and run and exit, like to hydrate a database for example). I now get the "Error response from daemon: Cannot link to a non running container: AS error.

Steps to reproduce:

1) Create a docker compose file that defines 2 containers(A,B) and has a link to container B from container A.
2) Have container B run a trivial command and exit
3) docker-compose up
4) docker exec -it <container A> /bin/bash
3) Notice this error
Error response from daemon: Cannot link to a non running container: AS error.

Docker version :: 1.13.0, build 49bf474
docker-compose version :: 1.10.0, build 4bd6f1a

I hope there is a work around that does require the complication of docker networks. Frustrated to see this regression.

**Comment by justincormack** [comment]
cc @aboch @shin-

**Comment by aboch** [comment]
I do not see recent changes in docker engine related to that code path.
In what docker engine & docker-compose versions things were working as you expected ?
Not sure, could it be previous docker-compose used to first start the parent container before having the child container linked to it ?

**Comment by danonorato** [comment]
@aboch  My assumption is that this started failing in docker 1.13.0 as the problem only produces for me when I'm running in the context of the native MAC docker engine.   The docker version running on the default docker-machine created by the old MAC tools is 1.12.2 ``Boot2Docker version 1.12.2, build HEAD : 9d8e41b - Tue Oct 11 23:40:08 UTC 2016
Docker version 1.12.2, build bb80604```   I've made no changes to my docker-compose file.  I simply installed the native MAC tools in attempt to see if they were stable and suitable from my team to migrate to.

**Comment by thaJeztah** [comment]
> I hope there is a work around that does require the complication of docker networks. Frustrated to see this regression.

Can you explain the "complication" of docker networks?

If you change your compose file to use `version: 2` I suspect everything works (you can probably even remove the `links`)


@aboch I think the root cause of this is actually introduced in docker 1.10; see this comment, which shows the difference in behavior between 1.9 and 1.10; https://github.com/docker/docker/issues/28937#issuecomment-265135384

**Comment by danonorato** [comment]
@thaJeztah   moving to version: 2 of docker-compose syntax did the trick.  Thanks much.

One further question on the Native Docker engine.  Is there a command I can execute in an exiting command shell to re-source the docker environment after s stop/start the Docker service?  It seems existing windows can't find docker after stop/start.   ie.  something like docker-machine env && eval $(docker-machine env) in the old tools.  Regards Dan

**Comment by thaJeztah** [comment]
@danonorato great to hear it worked; by switching to `version: 2` you're now using "docker networks" 👍 (they're really not difficult to use)

> It seems existing windows can't find docker after stop/start.

Hm, depends; if you're using `docker for windows`, the env vars shouldn't be needed, but if you're using Docker Toolbox, you can probably set those env-vars in your Windows configuration (https://kb.wisc.edu/cae/page.php?id=24500)

**Comment by danonorato** [comment]
@thaJeztah   should have been more clear on the "windows".  I should have stated "command line shells"  I'm on MAC,  no windows OS here.    So if I have a command line shell open, and then I stop/start the docker service on the MAC, all docker commands fail in that command line shell.  ie.. they timeout trying  to find docker....

**Comment by thaJeztah** [comment]
@danonorato is that `docker for mac` or `docker toolbox` (i.e., is docker running in a VirtualBox VM?)

**Comment by danonorato** [comment]
@thaJeztah   that would be docker for mac.  No VirturalBox

**Comment by thaJeztah** [comment]
I'm not able to reproduce that, but could you report that in the docker for mac issue tracker; https://github.com/docker/for-mac/issues ?

**Comment by danonorato** [comment]
@thaJeztah   sure will do.  We can close out this issue at this point.   thx for the replies.

**Comment by thaJeztah** [comment]
Will do, thanks!
