### ISSUE TITLE
Docker CLI/API allows containers to be set to an invalid name

### ISSUE THREAD

**Issue by djones-skytap** [docker/docker#30609]
**Description**

Docker CLI/API is allows containers to be set to an invalid name

**Steps to reproduce the issue:**
1. docker create --name invalidname- {any image}
2. docker start invalidname-

also

1. docker run -itd --name validname {any image}
2. docker rename validname invalidname2-
3. docker stop invalidname2-
4. docker start invalidname2-

**Describe the results you received:**
```
Error response from daemon: invalid name: "invalidname-" includes invalid characters, resource name has to conform to "^[\\w]+[\\w-. ]*[\\w]+$"
Error: failed to start containers: invalidname-
```

```
Error response from daemon: invalid name: "invalidname2-" includes invalid characters, resource name has to conform to "^[\\w]+[\\w-. ]*[\\w]+$"
Error: failed to start containers: invalidname2-
```

**Describe the results you expected:**
creating and renaming a container should not allow invalid names. CLI states valid names are: [a-zA-Z0-9][a-zA-Z0-9_.-]
Names do not appear to be allowed to end with period or dash, but these conditions are not caught.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 1
Server Version: 1.13.1-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.6-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: K2GS:Q25F:CY3U:4MY3:O2D4:SF26:3UDA:EMSM:5QIC:FFB5:OH6G:SVDX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 36
 System Time: 2017-01-31T22:32:08.992451828Z
 EventsListeners: 1
Username: djones
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for Mac; Also able to repro on Ubuntu 16.04.

**Comment by djones-skytap** [comment]
Since created and stopped containers cannot be started with an "invalid" name I'm not sure what the backwards compatibility issue is. In other words, back-compat has already been broken.

**Comment by yongtang** [comment]
@djones-skytap That is true although technically docker create is a separate command.

Since the name checking happens in docker and libnetwork repo separately, I am wondering if we should make the change in docker repo? /cc @mavenugo

**Comment by yongtang** [comment]
It looks like #30690 will address the invalid name issue.
