### ISSUE TITLE
TestStackRemove is flaky

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#30604]
```
12:42:59 ----------------------------------------------------------------------
12:42:59 FAIL: docker_cli_stack_test.go:103: DockerSwarmSuite.TestStackRemove
12:42:59 
12:42:59 [d319f74f7d4ba] waiting for daemon to start
12:42:59 [d319f74f7d4ba] daemon started
12:42:59 
12:42:59 docker_cli_stack_test.go:117:
12:42:59     c.Assert(strings.Split(strings.TrimSpace(out), "\n"), checker.HasLen, 2)
12:42:59 ... obtained []string = []string{"Nothing found in stack: testdeploy"}
12:42:59 ... n int = 2
12:42:59 
12:42:59 [d319f74f7d4ba] exiting daemon
12:43:01 
12:43:01 ----------------------------------------------------------------------
```

**Comment by tonistiigi** [comment]
In win2lin there seems to be problem with all `TestStack*` https://jenkins.dockerproject.org/job/Docker%20Master%20(win2lin)/1377/console

@dnephin

**Comment by LK4D4** [comment]
Yup, but I've encountered it on experimental.

**Comment by dnephin** [comment]
@tonistiigi Those failures are coming from `s.AddDaemon()` which is used by every single swarm related test. I think it was just a coincidence that it started to fail when it go to the stack deploy tests. The issue was something with that node, not the test.

**Comment by dnephin** [comment]
@LK4D4 Do you have a link to the build with those failures?

The failure seems to be that the stack never started, which would mean that all the stack tests would be equality as flaky.

**Comment by LK4D4** [comment]
@dnephin no, sorry :/ I'll post here if see new.

**Comment by tonistiigi** [comment]
@dnephin The difference then seems to be that all other tests are behind a build tag.

`TestStackRemove` is different, I've seen that fail outside win2lin as well.

**Comment by dnephin** [comment]
Ah, thanks, I missed that. I can add `!windows`.

**Comment by tonistiigi** [comment]
@dnephin Found https://jenkins.dockerproject.org/job/Docker%20Master/label=rhel72%20&&%20overlay/8306/console for `TestStackRemove`

**Comment by dnephin** [comment]
Sounds like #30643 fixed this

**Comment by tonistiigi** [comment]
@dnephin Seems #30643 only fixed the win2lin case. Happened again in #31257

https://jenkins.dockerproject.org/job/Docker-PRs/40617/console

```
23:11:12 
23:11:12 ----------------------------------------------------------------------
23:11:12 FAIL: docker_cli_stack_test.go:105: DockerSwarmSuite.TestStackRemove
23:11:12 
23:11:12 [d04ff5cdd87db] waiting for daemon to start
23:11:12 [d04ff5cdd87db] daemon started
23:11:12 
23:11:12 docker_cli_stack_test.go:119:
23:11:12     c.Assert(strings.Split(strings.TrimSpace(out), "\n"), checker.HasLen, 2)
23:11:12 ... obtained []string = []string{"Nothing found in stack: testdeploy"}
23:11:12 ... n int = 2
23:11:12 
23:11:12 [d04ff5cdd87db] exiting daemon
23:11:14 
23:11:14 ----------------------------------------------------------------------
23:11:14 PASS: docker_cli_stack_test.go:17: DockerSwarmSuite.TestStackRemoveUnknow
```
