### ISSUE TITLE
Docker fails prematurely when warning is encountered in unzip utility

### ISSUE THREAD

**Issue by aifred** [docker/docker#30622]
**Description**
Docker build from a Dockerfile fails when a warning is being thrown by unzip utility. 

**Steps to reproduce the issue:**
An example would be to run the following snippets in a Dockerfile from an ubuntu image:
```
RUN wget https://github.com/SonarSource-VisualStudio/sonar-scanner-msbuild/releases/download/2.2/sonar-scanner-msbuild-2.2.0.24.zip
RUN unzip -d /opt/sonar -q sonar-scanner-msbuild-2.2.0.24.zip; 
```

**Describe the results you received:**
warning:  sonar-scanner-msbuild-2.2.0.24.zip appears to use backslashes as path separators
The command '/bin/sh -c unzip -d ${sonar_dir} -q sonar-scanner-msbuild-2.2.0.24.zip ;' returned a non-zero code: 1

**Describe the results you expected:**
When doing an unzip of the same archive in macOS with the unzip utility, despite the warning being thrown, the unzip process was still successful with the output files.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 10
 Running: 5
 Paused: 0
 Stopped: 5
Images: 33
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 65
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: TTR2:4CKA:JS3O:4MON:Q45C:KOXZ:BLPT:EDXA:RNDK:7VDQ:6KVC:HLPQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 37
 Goroutines: 43
 System Time: 2017-02-01T08:04:14.653446751Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker for mac

**Comment by justincormack** [comment]
This is not a Docker issue, you are doing a `RUN` and `unzip` is setting the return code to 1, which means failure. You can replace it with a script that ignores the error `RUN unzip ... | true` or a slightly more complex one that tests for return code being 1 and succeeds. It is quite annoying there does not seem to be an option on `unzip` to just ignore warnings, you could file a bug.
