### ISSUE TITLE
Dockerfile reference advises against using build-time variables for secrets but offers no alternative

### ISSUE THREAD

**Issue by underyx** [docker/docker#30627]
The [ARG section](https://docs.docker.com/engine/reference/builder/#/arg) says the following:

>**Warning:** It is not recommended to use build-time variables for passing secrets like github keys, user credentials etc. Build-time variable values are visible to any user of the image with the docker history command.

This, however, is not very helpful. The warning should mention what to use instead when you need secrets during build time.

**Comment by justincormack** [comment]
The plan is to add https://github.com/docker/docker/pull/28079 at some point I believe, so that the currently swarm runtime only secrets are also available at build time. cc @ehazlett 

In terms of what to do right now, yes some more docs would be good.

**Comment by ehazlett** [comment]
@underyx as justin said, we hope to improve the build options.  I have rebased and opened a PR for build (GH wouldn't let me re-open the original) and would love your feedback -- https://github.com/docker/docker/pull/30637

**Comment by thaJeztah** [comment]
I think the question is answered, and the discussion currently takes place on https://github.com/docker/docker/pull/30637, so let me close this issue to prevent the discussion from diverging, but thanks for reporting (and, yes, I agree build-time secrets are badly needed 😇 https://github.com/docker/docker/issues/13490)
