### ISSUE TITLE
Cannot set the number of containers per services when deploying a STACK in docker SWARM 1.13

### ISSUE THREAD

**Issue by fabio-barile** [docker/docker#30632]
**Description**
when deploying a stack on docker 1.13 in SWARM mode,  it seems that setting the number of containers using the parameter "target_num_containers" per service fails

**Steps to reproduce the issue:**
1. create a "" stackfile like the one below
```
version: '3'
services:
 router:
  image : XXXXXXXX
  target_num_containers: 10
  ports:
   - 1234:1234
```
2. deploy using the command 
`docker stack deploy -c stackfile <STACK_NAME>`
3.the following error occurs: 
`target_num_containers Additional property target_num_containers is not allowed`

**Expected results:**
We should be able to set the number of containers in the stackfile

**Comment by fabio-barile** [comment]
I have just found a example how to set it  here : https://github.com/docker/docker/issues/30419

**Comment by ScottNeaves** [comment]
@fabio-barile I have the same issue as you (I am getting `Additional property target_num_containers is not allowed`) but I cannot find the example in the link you posted. How did you solve this problem?
