### ISSUE TITLE
Docker for Mac: Provide a functioning loopback hostname

### ISSUE THREAD

**Issue by mcandre** [docker/docker#30636]
# Summary

Please get `docker.local`, or some reusable host address, working in Docker for Mac, so that networked applications can be configured more easily.

# Mitigation

Evaluate the shell command `ifconfig en0 inet | grep inet | awk '{print $3}'`, and configure the resulting IP address in the relevant applications.

Repeat this process every time the link-local 192.168.2.x address changes. This can happen when your Mac sleeps, changes WiFi networks, or otherwise alters the NIC.

**Comment by gianarb** [comment]
Hello @mcandre 

Thanks for your report but I am going to close this PR because this repo is specific for the engine. You can open this request here https://github.com/docker/for-mac/issues . 

Thanks
