### ISSUE TITLE
Swarm mode service expose ports not accessible 

### ISSUE THREAD

**Issue by cten** [docker/docker#30630]
**Description**
Port inaccessible from other containers within the overlay network

Briefly describe the problem you are having in a few paragraphs.
Trying to move from old swarm to swarm mode but when I deploy a service serving on a port (ex: 8080) the port seems to be inaccessible from other containers on the same overlay network. 

**Steps to reproduce the issue:**
(Have swarm mode swarm setup with overlay network created)
1. Create service that serves http on port XXXX
2. Try to access that port from another container in the same overlay network

**Describe the results you received:**
wget/curl act as if nothing is serving on the port, except from within the container itself. 

**Describe the results you expected:**
Be able to access the port

**Additional information you deem important (e.g. issue happens only occasionally):**
Sorry, this swarm is running in an isolated environment so I am trying to hand type some of the info.

**Output of `docker version`:**

```
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
Sorry due to not being able to copy paste I will try to include non-default or possibly different parameters, and I can provide any others if needed.
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Storage Driver: devicemapper
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
all physical systems

**Comment by gianarb** [comment]
Hello @cten  thanks for your report. The useful part seems
```
time="2017-02-01T10:25:47.369865738Z" level=fatal msg="Error starting daemon: error initializing graphdriver: devicemapper: Non existing device docker-docker--pool"
```
And it can be a duplicated of this one https://github.com/docker/docker/issues/21304

**Comment by cten** [comment]
It appears to be a firewall issue. We had the firewall disabled, but once we added docker0 as TRUSTED things started working. Thought Docker made all the necessary changes to the firewall but maybe bc it had been disabled it messed something up.
