### ISSUE TITLE
Creating a container via API results in "No such image" error but CLI works

### ISSUE THREAD

**Issue by djspa** [docker/docker#30658]
**Description**

When attempting to create a container via the API results in this following error:

`{"message":"No such image: hello-world:latest"}`

However, when creating a container via the CLI with the same options, it will correctly download the image from Docker Hub. This issue affects docker 1.13 on both Linux and OS X, and it doesn't matter if the image is in a private repo or on docker hub.

If the image already exists, then the same API call will work, as docker will use the cached image. I've checked the logs on OS X and nothing is leaping out at me, so further assistance in troubleshooting this would be appreciated.

**Steps to reproduce the issue:**
1. RUN: `curl -H "Content-Type: application/json" -X POST -d '{"Image":"hello-world","HostConfig":{"PublishAllPorts":true}}' http://{IP Address}:2375/containers/create`
2. Should get the error `"{"message":"No such image: hello-world:latest"}"`
3. RUN: `sudo docker run -P hello-world`
4. Image will download as normal, and container starts.
5. Remove the container
6. Run the same curl command again, and this time it'll work.

````bash
djspa@mbp:~ $ curl -H "Content-Type: application/json" -X POST -d '{"Image":"hello-world","HostConfig":{"PublishAllPorts":true}}' http://127.0.0.1:2375/containers/create
{"message":"No such image: hello-world:latest"}
djspa@mbp:~ $ docker run -P hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
78445dd45222: Pull complete
Digest: sha256:c5515758d4c5e1e838e9cd307f6c6a0d620b5e07e6f927b07d05f6d12a1ac8d7
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/

djspa@mbp:~ $ curl -H "Content-Type: application/json" -X POST -d '{"Image":"hello-world","HostConfig":{"PublishAllPorts":true}}' http://127.0.0.1:2375/containers/create
{"Id":"e53a20b7c9cc3d2a8b0eb37d8d64536de63ec9fa919a1c206cdb28075ac38d3f","Warnings":null}
````

**Describe the results you received:**

Attempting to create a container via the API results in the error `"{"message":"No such image: hello-world:latest"}"`

**Describe the results you expected:**

Docker should download the hello-world image, and the API should return the container ID.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is happening on both docker for mac, and docker on linux. Attempting to download an image from my private registry shows that docker isn't even making a HTTP request to attempt to download the image.

**Output of `docker version`:**

Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

Containers: 7
 Running: 2
 Paused: 0
 Stopped: 5
Images: 42
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 67
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: ORNA:XW4L:NCZP:ACGD:FTC7:ALPJ:RQIG:GP6F:NUGI:INYC:SBYK:AAON
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 28
 Goroutines: 35
 System Time: 2017-02-02T00:42:19.616386052Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Additional environment details (AWS, VirtualBox, physical, etc.):** Physical, Docker for Mac client

**Comment by cpuguy83** [comment]
This is expected behavior.
The cli is doing a lot here, including initiating a "POST /images/create" if docker sends the error about the missing image.

Note that if you have a look at the daemon logs with debug mode enabled you'll see each request that is being made.

Closing as this is working as designed, but feel free to discuss here.
Thanks!

**Comment by djspa** [comment]
So is this a change in behaviour from 1.12 to 1.13? Where instead of the container create request doing to automagically, I'll need to run "POST /mages/create?fromImage=hello-world/latest" before the container create request?

**Comment by cpuguy83** [comment]
This has always been this way.

**Comment by djspa** [comment]
Huh, colour me confused then. I must not have run into this before because all images were cached locally before.

Thanks for the help!

**Comment by thaJeztah** [comment]
Here's the log for running `docker run hello-world` on docker 1.12;

```
DEBU[0009] Calling POST /v1.24/containers/create
DEBU[0009] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""}
ERRO[0009] Handler for POST /v1.24/containers/create returned error: No such image: hello-world:latest
DEBU[0009] Calling GET /v1.24/info
DEBU[0009] Calling POST /v1.24/images/create?fromImage=hello-world&tag=latest
DEBU[0009] Trying to pull hello-world from https://registry-1.docker.io v2
DEBU[0010] Pulling ref from V2 registry: hello-world:latest
DEBU[0010] pulling blob "sha256:78445dd45222097f5f8d5a16e48dc19c4ca162dcdb80010ab6f1ccfc7e2c0fa3"
DEBU[0012] Downloaded 78445dd45222 to tempfile /var/lib/docker/tmp/GetImageBlob532978021
DEBU[0012] Applied tar sha256:98c944e98de8d35097100ff70a31083ec57704be0991a92c51700465e4544d08 to 06a0abb130b6fc1e59a0580f5b8f1d8c33e8040c162a5d41e53d505acb09ef2a, size: 1840
DEBU[0012] Calling POST /v1.24/containers/create
DEBU[0012] form data: {"AttachStderr":true,"AttachStdin":false,"AttachStdout":true,"Cmd":null,"Domainname":"","Entrypoint":null,"Env":[],"HostConfig":{"AutoRemove":false,"Binds":null,"BlkioDeviceReadBps":null,"BlkioDeviceReadIOps":null,"BlkioDeviceWriteBps":null,"BlkioDeviceWriteIOps":null,"BlkioWeight":0,"BlkioWeightDevice":null,"CapAdd":null,"CapDrop":null,"Cgroup":"","CgroupParent":"","ConsoleSize":[0,0],"ContainerIDFile":"","CpuCount":0,"CpuPercent":0,"CpuPeriod":0,"CpuQuota":0,"CpuShares":0,"CpusetCpus":"","CpusetMems":"","Devices":[],"DiskQuota":0,"Dns":[],"DnsOptions":[],"DnsSearch":[],"ExtraHosts":null,"GroupAdd":null,"IOMaximumBandwidth":0,"IOMaximumIOps":0,"IpcMode":"","Isolation":"","KernelMemory":0,"Links":null,"LogConfig":{"Config":{},"Type":""},"Memory":0,"MemoryReservation":0,"MemorySwap":0,"MemorySwappiness":-1,"NetworkMode":"default","OomKillDisable":false,"OomScoreAdj":0,"PidMode":"","PidsLimit":0,"PortBindings":{},"Privileged":false,"PublishAllPorts":false,"ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":0,"Name":"no"},"SecurityOpt":null,"ShmSize":0,"UTSMode":"","Ulimits":null,"UsernsMode":"","VolumeDriver":"","VolumesFrom":null},"Hostname":"","Image":"hello-world","Labels":{},"NetworkingConfig":{"EndpointsConfig":{}},"OnBuild":null,"OpenStdin":false,"StdinOnce":false,"Tty":false,"User":"","Volumes":{},"WorkingDir":""}
DEBU[0012] container mounted via layerStore: /var/lib/docker/aufs/mnt/8abfa441a10eb1d91de96625519892083e83dbd1b31bddb823c13d6f6594869f
DEBU[0012] Calling POST /v1.24/containers/4af12a5b2ef23531df8edd3eae24561c3a559d8656a5602ed1e8e7dbcfe74468/attach?stderr=1&stdout=1&stream=1
DEBU[0012] attach: stdout: begin
DEBU[0012] attach: stderr: begin
DEBU[0012] Calling POST /v1.24/containers/4af12a5b2ef23531df8edd3eae24561c3a559d8656a5602ed1e8e7dbcfe74468/start
```

**Comment by jayph88** [comment]
you may try below

curl -H "Content-Type: application/json" -X POST -d '{"Image":"index.docker.io/hello-world","HostConfig":{"PublishAllPorts":true}}' http://{IP Address}:2375/containers/create
