### ISSUE TITLE
[Feature Reqeust]docker system prune -fa --reserve <image_name>

### ISSUE THREAD

**Issue by zhenyulin** [docker/docker#30678]
I'm creating a very large amount of intermediate images by running test during development, and currently using "docker system prune -fa" to remove those excessive images, while I would like to protect certain images from being removed though they are not used by any container at the moment.

It would be nice to have "docker system prune -fa --reserve <image_name>" or have a file like .dockerpruneignore to whitelist the images or maybe an interactive shell.

I feel this is a quite common use case.

**Comment by cpuguy83** [comment]
Hey thanks for opening.
This is a dup of #29999, so closing this one.

Thanks!
