### ISSUE TITLE
External connectivity lost to some apps after installing docker

### ISSUE THREAD

**Issue by sudhakarbetha** [docker/docker#30675]
I have docker installed on my linux machine. 
I am able to pull/push images from/to the public repository. 
I can run containers, map the ports on the linux machine and access the container applications very well.

However, I have some other applications running on the linux machine , which are non container based, and have nothing to do with Docker. 
They are simply J2EE Applications and web applications deployed on Weblogic and Tomcat servers.
I can access these applications within the linux machine , but cannot access these applications from outside the machine.

I am behind a corporate firewall and these are apps within the network.
These apps where accessible before I installed docker on the linux machine. I tried to un-install docker, but that did not help. Is there any thing else I can do rather than a machine reboot to be able to access (non docker container based)  apps from outside the linux machine as usual?

Im guessing this has something to do with the additional docker0 ip connection created for bridge containers, or I may be wrong. 

Kindly let me know if there is any way I can access these apps outside the linux machine

$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:49:16 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:49:16 UTC 2015
 OS/Arch:      linux/amd64

$ docker info 
Containers: 5
Images: 42
Server Version: 1.9.1
Storage Driver: devicemapper
 Pool Name: docker-202:1-1846816-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 107.4 GB
 Backing Filesystem:
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.608 GB
 Data Space Total: 107.4 GB
 Data Space Available: 19.3 GB
 Metadata Space Used: 3.719 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.89-RHEL6 (2014-09-01)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.8.13-44.1.1.el6uek.x86_64
Operating System: <unknown>
CPUs: 4
Total Memory: 14.07 GiB
Name: den00rni
ID: J3V3:45ZX:W4FX:SAGY:2Y6L:NKI6:F3VO:O4Y7:KRKT:LFX6:VPXJ:SE4L
Username: sudhakarbetha
Registry: https://index.docker.io/v1/

$ uname -a
Linux den00rni 3.8.13-44.1.1.el6uek.x86_64 #2 SMP Wed Sep 10 06:10:25 PDT 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tonistiigi** [comment]
@aboch

**Comment by aboch** [comment]
@sudhakarbetha 

That should not happen, check the docker created linux bridge do not conflict with your host IP addresses, or if you created any docker contaner publishing on the same ports your apps are listening to.

> I tried to un-install docker, but that did not help. Is there any thing else I can do rather than a machine reboot to be able to access (non docker container based) apps from outside the linux machine as usual?

If the issue is still there after uninstalling docker, then it is not because of a docker running component.
Two things will be left over after uninstalling docker:
- the `docker0` interface and another `br-xxxxx` interface for each docker network you may have created
- the docker programmed iptables rules

To see which one is the culprit, first remove the bridges `ip link del docker0` 
If that does not help, then remove from the docker installed iptables rules from the `nat` and `filter` table. 

To identify which rule may be intercepting the traffic to your existing apps, look for counter increase in the `iptables -t <nat | filter> -nvL` output.

**Comment by thaJeztah** [comment]
A couple of things I notice in your setup;

- you're running docker 1.9.1, which is very dated and EOL
- the minimum kernel version supported to run docker is 3.10
- from the output of `docker info` it looks like you're running on RHEL6, which isn't supported for a long time (I think our last release for RHEL6 is docker 1.7.1)

**Comment by sudhakarbetha** [comment]
I specifically notice, that I am able to access Apache Tomcat hosted applications but cannot access Oracle Weblogic hosted applications.

**Comment by sudhakarbetha** [comment]
@aboch 
I have checked 'ifconfig' and see the docker0 bridge doesnt conflict with the Host IP Address

How do I , 
"If that does not help, then remove from the docker installed iptables rules from the nat and filter table." ?

**Comment by sudhakarbetha** [comment]
It worked now, 
I see that my /etc/hosts was updated with docker0 interface ip address and the services started after docker installation had this local ip assigned to it .
$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:6F:70:C0:00
          inet addr:172.17.0.1  Bcast:0.0.0.0  Mask:255.255.0.0


$ netstat -an | grep 7103
tcp        0      0 172.17.0.1:7103             0.0.0.0:*                   LISTEN

So, I had to edit /etc/hosts to include my global ip and restart the services.
