### ISSUE TITLE
Docker partially hungs up after second SIGHUP in pure Swarm cluster

### ISSUE THREAD

**Issue by mmorhun** [docker/docker#30680]
**Description**
Docker which connected to pure Swarm (as a node) after receiving SIGHUP signal second time partially hungs up.

**Steps to reproduce the issue:**
Run pure Swarm with two or three nodes. On a node:
1. Create `/etc/docker/daemon.json` file with content: `{}` (empty json)
2. Send SIGHUP signal to docker (`# kill -SIGHUP <docker pid>`)
3. Send SIGHUP again

**Describe the results you received:**
Docker hungs up on `docker info`, `docker run`, `docker pull`, but works fine for `docker ps`, `docker images`.

**Describe the results you expected:**
Docker shouldn't hung up.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue can be reliably reproduced.

Docker logs after first SIGHUP:
```
...
time="2017-02-02T09:01:18.846724652Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json" 
time="2017-02-02T09:01:18.846878306Z" level=error msg="Error reconfiguring the daemon: discovery service not supported" 
...
```
Docker logs after second SIGHUP:
```
...
time="2017-02-02T09:01:21.782353695Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json"
...
```

#### It can be reproduced on AWS
AWS EC2 Centos 7.3
Master: c4.2xlarge
3 Nodes: r3.xlarge
Swarm 1.2.5
Zookeeper 3.4.9

**Output of `docker version`:**
```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:23:59 2016
 OS/Arch:      linux/amd64
```
**Output of `docker info`:**
```
Containers: 8
 Running: 4
 Paused: 0
 Stopped: 4
Images: 39
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-202:0-1708215-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/vg-docker/data
 Metadata file: /dev/vg-docker/metadata
 Data Space Used: 29.52 GB
 Data Space Total: 69.79 GB
 Data Space Available: 40.27 GB
 Metadata Space Used: 40.24 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.107 GB
 Thin Pool Minimum Free Space: 6.979 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.36.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 29.55 GiB
Name: node2.c5.codenvy-stg.com
ID: EMDA:WZ57:VTC2:KNIC:TDWE:I5AO:L2B2:MNS5:C3W7:KSWE:M4L2:ZIFH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
Cluster Store: zk://some-host.com:some-port
Cluster Advertise: 172.30.12.84:2375
Insecure Registries:
 some-host.com:5000
 127.0.0.0/8
```

#### Also it can be reproduced locally:
Swarm 1.2.6 (in container)
Zookeeper 3.4.9 (in container)
(Physical docker: Version: 1.13.0 API version: 1.25)
2 docker-machine nodes:
`docker-machine create -d virtualbox --virtualbox-memory 4096 --virtualbox-cpu-count=2 --engine-opt="cluster-store=zk://<host-ip>:2181"  --engine-opt="cluster-advertise=eth1:2375" --engine-opt="host=tcp://0.0.0.0:2375" --engine-env="DOCKER_TLS=no" node1`

**Output of `docker version`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```
**Output of `docker info`:**
```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.43-boot2docker
Operating System: Boot2Docker 1.13.0 (TCL 7.2); HEAD : 5b8d9cb - Wed Jan 18 18:50:40 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.858 GiB
Name: node1
ID: FR46:HB4X:X5NN:5BGD:RDDP:5JPY:7FFZ:6UNG:MGWC:6N5S:IDL4:B3LR
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 54
 System Time: 2017-02-02T16:09:50.261921897Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Cluster Store: zk://172.19.20.195:2181
Cluster Advertise: 192.168.99.101:2375
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by mmorhun** [comment]
Fell free to ping me if you have questions or it is needed to clarify some detail etc

**Comment by mmorhun** [comment]
After some additional testing I've found that `cluster-store` and `cluster-advertise` options impact on docker hung up.
A bit detailed steps to reproduce (I tested it locally only, but I believe that it can be reproduced on AWS as well):
1. Run Zookeeper: `docker run -p 0.0.0.0:2181:2181 -d zookeeper:3.4.9`
2. Create 2 nodes using docker machine:
`docker-machine create -d virtualbox --virtualbox-memory 4096 --virtualbox-cpu-count=2 --engine-opt="cluster-store=zk://<host-ip>:2181" --engine-opt="cluster-advertise=eth1:2375" --engine-opt="host=tcp://0.0.0.0:2375" --engine-env="DOCKER_TLS=no" node1`
3. Run Swarm: `docker run -d -v /tmp/node_list:/node_list -p 127.0.0.1:23751:2375 swarm:1.2.6 manage -H 0.0.0.0:2375 file:///node_list`, where /tmp/node_list is text file with nodes IPs obtained from `docker-machine ls`. We **do not** use service discovery.
4. SSH into a node
5. create `/etc/docker/daemon.json` with content (I used max-concurrent-downloads option just for control whether config is applied):
```
{
  "max-concurrent-downloads": 4
}
``` 
6. Send SIGHUP signal to docker: `sudo kill -SIGHUP <docker-PID>` and read logs.
7.  Repeat previous item 2-3 times.

So:
- if both `cluster-store` and `cluster-advertise` options are present, docker hungs up after secong SIGHUP signal as described in the issue above.
 - if only `cluster-store` is present, then docker hungs up after third SIGHUP signal. Logs:
```
time="2017-02-07T13:19:18.661579317Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json" 
time="2017-02-07T13:19:18.661771835Z" level=debug msg="Initializing discovery service" name=zk uri="<host-ip>:2181" 
time="2017-02-07T13:19:18.661784409Z" level=info msg="Initializing discovery without TLS" 
time="2017-02-07T13:19:18.661811447Z" level=debug msg="Option Experimental: false" 
time="2017-02-07T13:19:18.661817781Z" level=debug msg="Option DefaultDriver: bridge" 
time="2017-02-07T13:19:18.661822227Z" level=debug msg="Option DefaultNetwork: bridge" 
time="2017-02-07T13:19:18.661826658Z" level=debug msg="Option OptionKVProvider: zk" 
time="2017-02-07T13:19:18.661831655Z" level=debug msg="Option OptionKVProviderURL: <host-ip>:2181" 
time="2017-02-07T13:19:18.661840320Z" level=debug msg="Reset Max Concurrent Downloads: 4" 
time="2017-02-07T13:19:18.661845701Z" level=debug msg="Reset Max Concurrent Uploads: 5" 
...
time="2017-02-07T13:20:18.620647092Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json" 
time="2017-02-07T13:20:18.620767361Z" level=error msg="Error reconfiguring the daemon: discovery service not supported"
...
time="2017-02-07T13:20:35.780443737Z" level=info msg="Got signal to reload configuration, reloading from: /etc/docker/daemon.json"
```
- if create nodes without `cluster-store` and `cluster-advertise` options, e.g.
`docker-machine create -d virtualbox --virtualbox-memory 4096 --virtualbox-cpu-count=2 --engine-opt="host=tcp://0.0.0.0:2375" --engine-env="DOCKER_TLS=no" node1`
everithing works fine.

**Comment by mmorhun** [comment]
With this issue we cannot reload docker service config, what brings some troubles.
I still cannot understand why docker on a node wants to do some discovering? I failed to find something about it in docs...
Can we disable or skip that discovery feature somehow? Any answers would be appreciated.

**Comment by cpuguy83** [comment]
You are using discovery, that's what `cluster-store` and `cluster-advertise` are for.

**Comment by cpuguy83** [comment]
I'm curious, where are the engine-opts being set from machine?

**Comment by mmorhun** [comment]
Thank you for response.
We need KV storage for overlay networks, no more. Do we have to have discovering for this? Or is it discovering for overlay networks only not for nodes?

As about engine-opts (I am not sure that I fully understand question) I added it on docker-machine creation as described above.
Also I could add some options through config json file & SIGHUP signal inside vm (`docker-machine ssh nodename`). At least for adding `cluster-store` and `cluster-advertise` it works. But for next times this bug is appeared.
At the end it is possible to kill and start dockerd with wanted options inside vm, but it is needed to detach process from terminal to prevent process killing after ssh disconnect.

**Comment by cpuguy83** [comment]
@mmorhun yes it's required for overlay networks unless you use the new swarm mode.

For the engine-opts, I'm wondering where the options get stored in the target machine as I'm trying to track down where this issue could be coming from. Docker (thinks) it is seeing a change to your cluster-store to something that is invalid.

**Comment by mmorhun** [comment]
@cpuguy83 thank you for explanation.
If you need (or just want to know) some details or additional tests which I can perform - feel free to ask me.

**Comment by cpuguy83** [comment]
This might be fixed by #31029

Would you be able to give it a shot?

**Comment by mmorhun** [comment]
@cpuguy83 sure.
We built docker with the fix and it works as expected. Thank you.

**Comment by cpuguy83** [comment]
Awesome, thanks!
