### ISSUE TITLE
Deploy Compose application to Swarm mode cluster

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#30689]
https://docs.docker.com/docker-for-aws/deploy/ needs to be updated to show how a Compose application can be deployed to Docker for AWS. It shows only individual services at this time.

@thaJeztah this may be your domain?

**Comment by thaJeztah** [comment]
Hm, docker for AWS is not really my domain; could you use the [feedback link on that page](https://github.com/docker/docker.github.io/issues/new?title=Feedback%20for:%20docker-for-aws/deploy.md&assignee=johndmulhausen&body=File:%20[docker-for-aws/deploy.md](https://docs.docker.com/docker-for-aws/deploy/)) to report this in the documentation issue tracker?

(thanks for reporting though!)
