### ISSUE TITLE
Object reference not set to an instance of an object when starting docker for windows

### ISSUE THREAD

**Issue by devedse** [docker/docker#30687]
**Description**

I installed Docker onto my computer but got a blue screen after the installation. (Due to an unrelated problem where I can't create HyperV VHD's on my C Drive due to a Bios NVME driver).

I created a symlink for the c:\users\....\.docker\machine\machines folder to another drive which would solve the issue of the blue screen.

However when I now start Docker for Windows.exe I only see the following error:

![image](https://cloud.githubusercontent.com/assets/2350015/22564612/72d4d1da-e985-11e6-9231-eab1aa16868a.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

I already tried reinstalling docker and Hyper-V without any luck. I also tried manually creating a new VM with the following command:
docker-machine create --driver hyperv vm

However this didn't solve the issue.

Also running any commands with docker run give errors. E.g.:
```
C:\Users\Davy>docker pull hello-world
Using default tag: latest
Warning: failed to get default registry endpoint from daemon (error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.). Using system default: https://index.docker.io/v1/
error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/images/create?fromImage=hello-world&tag=latest: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Output of `docker info`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.25/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
My enviroment is Windows 10 with Docker for Windows which I want to run in the linux VM.

**Comment by thaJeztah** [comment]
this looks to be an issue with Docker for Windows; can you open this in the Docker for Windows issue tracker instead? https://github.com/docker/for-win/issues

**Comment by devedse** [comment]
Done, created the issue here:
https://github.com/docker/for-win/issues/464

**Comment by thaJeztah** [comment]
Thanks!
