### ISSUE TITLE
DNS Flush / refresh - feature request

### ISSUE THREAD

**Issue by bgrissin** [docker/docker#30693]
We are seeing a variety of engagements where docker hosts participating in a swarm cluster somehow lose state in DNS,, thus containers on an overlay network fail to resolve other containers on the same overlay network.  The issue appears to be intermittent, but we have seen cases where all containers on a node have stopped resolving

Would like a less disruptive way to refresh/re-establish a functional DNS on a docker node than too restart the docker daemon, which is too disruptive for some customers.

This issue with varying similar circumstances is known to have occurred on many customer support engagements.  

Attempts to repro the issue within Docker labs thus far have not been successful, but here is a summary of the steps during a troubleshooting session that identifies the issue/symptoms

1) can deploy containers on existing and newly created overlays via compose, view networks, etc.  Nodes seems to be communicating fine with the controllers

2) Once multiple containers are deployed on existing overlay networks or on newly created overlays  via docker run or compose, during an unknown or specified timeline container(s) stop responding.  

3) confirm those failing containers by entering into a container that has been reported that is running,idocker exec -it <container_id> sh and running nslookup to the other container that exists on the overlay network

4) confirm container and overlays are being used by checking the output of docker inspect

Issue has been reported using engine 1.12.x 

[inspect-devv-testapi.txt](https://github.com/docker/docker/files/749049/inspect-devv-testapi.txt)
[inspect-devv-te2-proxy.txt](https://github.com/docker/docker/files/749052/inspect-devv-te2-proxy.txt)
[inspect-devv-net-proxy.txt](https://github.com/docker/docker/files/749050/inspect-devv-net-proxy.txt)
[inspect-devv-net-backend.txt](https://github.com/docker/docker/files/749051/inspect-devv-net-backend.txt)

**Comment by thaJeztah** [comment]
Are the occurrences you've seen on the same (comparable) distro / version? Or completely different setups?

**Comment by bgrissin** [comment]
the references I have are RHEL.

**Comment by thaJeztah** [comment]
ping @mavenugo PTAL

**Comment by bgrissin** [comment]
related issue posted  -  https://github.com/docker/orca/issues/4888

**Comment by natalequarato** [comment]
Hello,
we have the same issue. 
do you have a solution to resolve it? what i shoud be to flush the dns records? that not be to delete the overlay net ? 
Below the tests:

mvirno@dockersvil:~/metlife$ docker-compose ps
        Name                       Command              State              Ports
--------------------------------------------------------------------------------------------
metlife_pcsl-server_1   catalina-docker.sh run          Up      172.16.1.143:32805->8080/tcp
metlife_pxcalc_1        ./Bin/CalcServer -interactive   Up      30001/tcp
mvirno@dockersvil:~/metlife$ docker inspect -f {{.NetworkSettings.Networks}},{{.Name}} metlife_pxcalc_1
map[metlife:0xc4204aa3c0],/metlife_pxcalc_1
mvirno@dockersvil:~/metlife$ docker inspect -f {{.NetworkSettings.Networks.metlife.IPAddress}},{{.Name}} metlife_pxcalc_1
10.0.5.3,/metlife_pxcalc_1
mvirno@dockersvil:~/metlife$ docker run -it --net=metlife tutum/dnsutils dig pxcalc
ERRO[0000] error getting events from daemon: EOF

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> pxcalc
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 11169
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;pxcalc.                                IN      A

;; ANSWER SECTION:
pxcalc.                 600     IN      A       10.0.5.3
pxcalc.                 600     IN      A       10.0.5.6
pxcalc.                 600     IN      A       10.0.5.4
pxcalc.                 600     IN      A       10.0.5.5
pxcalc.                 600     IN      A       10.0.5.2
pxcalc.                 600     IN      A       10.0.5.7

;; Query time: 0 msec
;; SERVER: 127.0.0.11#53(127.0.0.11)
;; WHEN: Mon Feb 20 16:30:50 UTC 2017
;; MSG SIZE  rcvd: 156


mvirno@dockersvil:~/metlife$ docker network inspect metlife
[
    {
        "Name": "metlife",
        "Id": "9xej7cmkjjhj9xwkmfyoxcanq",
        "Scope": "swarm",
        "Driver": "overlay",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": []
        },
        "Internal": false,
        "Attachable": true,
        "Containers": {
            "1d83e989d00c782d9d312bb16e3e763cf6d9ceffbbf5f552288d8349ccb52247": {
                "Name": "metlife_pcsl-server_1",
                "EndpointID": "80f567ec56871f0d7268346a13e0eb3c25efc633c4d113a4f63a7ddc1b0b0b51",
                "MacAddress": "02:42:0a:00:05:04",
                "IPv4Address": "10.0.5.4/24",
                "IPv6Address": ""
            },
            "88c2057ed0f246320730ebc236ea7370c7b1e7ec45d64e742629946c908a5568": {
                "Name": "metlife_pxcalc_1",
                "EndpointID": "5110cfabb0b9459baed9b25da4bb6bf675e47b498628ff82f3fba98d2ed00ac2",
                "MacAddress": "02:42:0a:00:05:03",
                "IPv4Address": "10.0.5.3/24",
                "IPv6Address": ""
            },
            "e2f2e9af74e4fb317f0fd1f99fb3f179c8378956211c553e8bf053a26f83c230": {
                "Name": "heuristic_golick",
                "EndpointID": "1d64c2aad5a18e3b4a8955ecd66e564574c387e8dee3c2dc86bba331618d7424",
                "MacAddress": "02:42:0a:00:05:02",
                "IPv4Address": "10.0.5.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.driver.mtu": "1400",
            "com.docker.network.driver.overlay.vxlanid_list": "4103"
        },
        "Labels": {
            "com.docker.ucp.access.label": "dagmef",
            "com.docker.ucp.access.owner": "admin"
        }
    }
]


mvirno@dockersvil:~/metlife$ docker version
Client:
 Version:      1.13.1-cs1
 API version:  1.24 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:53:15 2017
 OS/Arch:      linux/amd64

Server:
 Version:      ucp/2.0.2
 API version:  1.26 (minimum version )
 Go version:   go1.7.4
 Git commit:   b6fbfe4
 Built:        Wed Jan 18 17:34:53 UTC 2017
 OS/Arch:      linux/amd64
 Experimental: false
