### ISSUE TITLE
Docker-qemu-plug-in 

### ISSUE THREAD

**Issue by necrose99** [docker/docker#30695]
Run docker containers with foreign binarys 
( @** wish list enhancement) 

Proot , qemu static sometimes works sometimes  don't in image , image updates , 
Ie gentoo arm64 tarball updates , and it breaks. 

If the system is native,  then ignore emulator.  
If not have option to call for qemu plug-in etc. 

However mere mortals can't obtain  arm64  (for now ) servers , over a rassbery-pi 3's , but likewise slow. 
However  can call a wrapper for qemu or proot etc 
From docker , on your average intel i7 etc. 

However, one can pull in static qemu or proot... however,  prone to breakages...  
Not as long term reliable. 

Anyhow,  having a wrapper or plug-in would be a plus.

**Comment by AkihiroSuda** [comment]
https://translate.google.co.jp/translate?hl=ja&sl=ja&tl=en&u=http%3A%2F%2Finaz2.hatenablog.com%2Fentry%2F2015%2F03%2F03%2F235759

According to the report linked above, you would be able to run arm container on amd64 just using qemu-user-static.
(locally it didn't work for me though due to ENOENT about some library)

**Comment by thaJeztah** [comment]
@justincormack may know more about this

**Comment by justincormack** [comment]
This does work, we implemented it for Docker for Mac and Windows. To have it completely transparent you need a 4.8 or later Linux kernel, and you may also need some patches to qemu (if you want to run Go code). There is also a container that @DieterReuter made that can set it up on any machine, again if you are running a 4.8 or 4.9 kernel (eg Debian stretch, or the new distros that will be released this year).

Docker itself can't do this, so I am going to close the issue, but it is possible and should become easier with newer distros.

**Comment by necrose99** [comment]
Namily Gentoo arm64 , the tarball root worked in emulation ,  but after awhile updates nada... 
Least locally in proot static and umeq (static & hacked. .. Debian dev's... docker hacking for qemu)  However the Jan 2017 fs root  busted. That. 
It's been about as stable as dropping gallons of nitroglycerin. .. on trampolines... 
Dockerhub docker dies. 
Just the gd tarball unpacking makes a "stable"...
But useless,  without docker on a real arm64... 
If I knew busybox rapper tricks I could likely rig the emu to more likely fire up. 

Anyhow,  I was just thinking of a measure for docker to run proot & /or/ qemu ie via plug-in , or add on/ add on module / scrips. 
Making the additional binary adds to docker containers moot... more transparent,  stable etc. 
Less of unpredictable mess. 

Sabayon Linux  (Gentoo) , have a 4.8 kernel.  
Docker-companion. 

For the love of gentoo , Windows 10 and Sabayon 
Proot +umeq ,  2016 may/June arm64 had it just barely running in virtualbox as prof... tried to replicate in docker....  Frankenstein-ish  on imgur...

I'll take a look , at the docs
just for Gentoo it's been quite unstable,  and it may be easy to franken rig , debian , add as chroot. ...
