### ISSUE TITLE
file is not reloaded by process

### ISSUE THREAD

**Issue by jney** [docker/docker#30705]
**Description**

I use docker for a project , in the stack:
- `node.js`
- `consul-template`

It is a `node.js` server which uses `cluster` utility. When a key/value is updated in `consul`, `consul-template` reload a configuration file, and send a `SIGHUP` which is caught by `node.js`' master cluster, a new fork is started, then old ones are stopped.

Running this locally just works, the fork process is aware about the new configuration file.
But running in docker the fork still use the old configuration file. 

**Output of `docker version`:**

```
Docker version 1.12.6, build 7392c3b/1.12.6
```

**Output of `docker info`:**

```
Containers: 105
 Running: 14
 Paused: 0
 Stopped: 91
Images: 18
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: ext4
 Data file:
 Metadata file:
 Data Space Used: 6.935 GB
 Data Space Total: 63.71 GB
 Data Space Available: 56.77 GB
 Metadata Space Used: 7.295 MB
 Metadata Space Total: 67.11 MB
 Metadata Space Available: 59.81 MB
 Thin Pool Minimum Free Space: 6.371 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.39-34.54.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.8 GiB
Name: ip-10-101-11-222
ID: UIB5:VXYE:VUCE:BJDZ:SDAQ:OTIF:NIUZ:XFJ6:JGQO:PBR5:QJI3:QTIN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Comment by cpuguy83** [comment]
@jney How is it getting this configuration? Are you sure the process is handling SIGHUP? Are you sure the process reload is being triggered?

**Comment by jney** [comment]
hi @cpuguy83,

> Are you sure the process is handling SIGHUP? Are you sure the process reload is being triggered?

I'm indeed pretty sure, as i can see the log messages in cloudwatch, see my code below

`master.js`

```js
'use strict'

const cluster = require('cluster')

console.log('started master with pid', process.pid)

// fork the first process
cluster.fork()

process.on('SIGHUP', function () {
  delete require.cache['/app/index.js']
  const w = cluster.workers
  const newWorker = cluster.fork()
  newWorker.on('listening', function () {
    // stop all other workers
    console.log('listening...')
    for (const id in cluster.workers) {
      if (id !== newWorker.id.toString()) {
        console.log('killing', id)
        cluster.workers[id].kill('SIGTERM')
      }
    }
  })
})
```


`index.js`

```js
'use strict'

const cluster = require('cluster')

require('dotenv').config({silent: true})

if (cluster.isMaster) {
  require('./master')
} else {
  require('./dist')
}
```

> How is it getting this configuration?

I tried to make a sample, but it actually does not reproduce the behaviour

**Comment by cpuguy83** [comment]
> I tried to make a sample, but it actually does not reproduce the behaviour

Any repro would help.

In the end Docker is really not doing anything here.
The signal is sent to the process not to docker.
Are you sure the configuration is being updated (in the container) correctly?

Closing since this looks more like some config error, but we can discuss and re-open if needed.

**Comment by jney** [comment]
> Are you sure the configuration is being updated (in the container) correctly?

Yes i can see it displaying (`console.log`) it in the `master.js` and `index.js`

> In the end Docker is really not doing anything here.

For now, it is my main suspect, i mean i''m investigating on the problem for a few days before creating this issue here and i can tell:

- if the linux distro changes (alpine/debian) the problem remains
- if the node.js changes (7.0/7.4) the problem remains
- it does work on local (osx), it doesn't work in a docker container

Thinking it's a kind of memory cache

> Any repro would help.

i've got the same problem in 2 repos (it as been reproduced)

> Closing since this looks more like some config error, but we can discuss and re-open if needed.

Ok, I will do my best to try to reproduce it, and give some appropriate material to work on.

Thanks for support

**Comment by cpuguy83** [comment]
How is the signal being sent to the process?
Can you log an entry like "CAUGHT SIGHUP" and make sure it's produced in the output?

**Comment by jney** [comment]
@cpuguy83 sure, i did it. i can event tell the line `console.log('listening...')` is reached.
It means, the process has been stopped, then the fork was restarted, and was listening.

**Comment by cpuguy83** [comment]
@jney Can you have it dump the config so you can verify if it's seeing changes?
It seems like it's just not picking up anything new.

**Comment by jney** [comment]
Dockerfile is:

```dockerfile
FROM mhart/alpine-node:7.4

ENV CONSUL_TEMPLATE_VERSION 0.18.0

ADD https://releases.hashicorp.com/consul-template/${CONSUL_TEMPLATE_VERSION}/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip /tmp/

RUN apk update \
 && apk add git \
 && mkdir -p /app \
 && unzip /tmp/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip -d /usr/local/bin \
 && rm -rf /tmp/consul-template_${CONSUL_TEMPLATE_VERSION}_linux_amd64.zip

WORKDIR /app
COPY . /app
RUN npm install --production --quiet --unsafe-perm=true \
 && apk del --purge git

CMD ["./bin/start"]

EXPOSE 8080
```

i can now tell it **works** locally... but still doesn't on ecs.

**Comment by jney** [comment]
locally i have the following docker version:

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Comment by jney** [comment]
my bad it was not about docker. another piece of software make some cache without been aware of

**Comment by cpuguy83** [comment]
@jney 👏 Glad you were able to get to the bottom of it!
