### ISSUE TITLE
docker login in docker machine

### ISSUE THREAD

**Issue by viveky4d4v** [docker/docker#30703]
I have a private docker image hosted on Dockerhub. I am using docker machine using generic driver to handle my virtualbox VMs. I have already done "docker login" on my manager & worker machine both but i keep getting below error -

    unable to pin image xxyyzz/xyz-sm:v1 to digest: errors:
    denied: requested access to the resource is denied
    unauthorized: authentication required
Can someone please help me authenticating to the private dockerhub repositories from only the manager node or while creating the docker machine itself ?

**Comment by cpuguy83** [comment]
Need to use `--with-registry-auth` to tell docker to pass credentials to workers.
