### ISSUE TITLE
Is it possible to create image from local file using Docker API?

### ISSUE THREAD

**Issue by isanych** [docker/docker#30715]
I'm trying to create docker image from file on docker host using python docker API.
Client running on different host, so I would like to avoid downloading file to client and then uploading it to docker host. This test:
```
import docker
d = docker.from_env()
print(d.images.client.api.import_image("/data/file.tar", "acme.com/test"))
print(d.images.client.api.import_image("file:///data/file.tar", "acme.com/test"))
```
produces next output:
```
{"status":"Downloading from http://%2Fdata%2Ffile.tar"}
{"errorDetail":{"message":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""},"error":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""}

{"status":"Downloading from file:///data/file.tar"}
{"errorDetail":{"message":"Get file:///data/file.tar: unsupported protocol scheme \"file\""},"error":"Get file:///data/file.tar: unsupported protocol scheme \"file\""}
```
Docker daemon 1.13 running in Ubuntu 16.04 VM on ESXi 6 host. Client is docker python API 2.0.2 running on physical Windows 10 host.

**Comment by fntlnz** [comment]
@isanych Please note that this is the issue tracker of the Docker project and not a Q/A Forum. This kind of questions can be made here: https://forums.docker.com/

I see that you opened another issue (#30714) regarding image creation so I'll keep that one and close this
