### ISSUE TITLE
Dockertools installation is broken (pipe/docker_engine error)

### ISSUE THREAD

**Issue by cookiengineer** [docker/docker#30712]
**Description**

Windows installation of Docker is broken. The docker toolbox (timestamp 2/1/2017) setup does not work correctly. One one hand kitematic gives the no pipe error, BUT works seemingly with the "Use Virtualbox" fallback.

However, docker itself doesn't work when being used in CMD, git bash or mingw environments. When trying to execute a `docker build -t` command, the following output will come up:

```bash
An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/
v1.24/build?buildargs=%7B%7D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cp
usetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&rm=
1&shmsize=0&t=lycheejs&ulimits=null: open //./pipe/docker_engine: The system can
not find the file specified.
```

**Steps to reproduce the issue:**
1. Use Windows 7/8/10
2. Install Docker toolbox
3. Use a working Dockerfile of your choice, execute `docker build` command.

**Describe the results you received:**

`open //./pipe/docker_engine: The system can
not find the file specified.`

**Describe the results you expected:**

Docker building something.

**Output of `docker version`:**

```
Docker version 1.12.6, build 78d1802
```

**Output of `docker info`:**

```
An error occurred trying to connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v
1.24/info: open //./pipe/docker_engine: The system cannot find the file specifie
d.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical machine with Windows 8 or Windows 10. Same problems, different machines.

**Comment by friism** [comment]
cc @FrenchBen

**Comment by FrenchBen** [comment]
@cookiengineer When using Docker Toolbox, you will need to make sure that your ENV is setup properly prior to using `docker ...` within a terminal.
This is done by executing the following command in your terminal, and following the instructions:
`docker-machine env default`
This has been documented in our docs: 
https://docs.docker.com/toolbox/toolbox_install_windows/

We do however provide a `Docker Quickstart` shortcut that should set everything up for you. 
Kitematic will prefer the native installation of Docker for Windows, but will give you the option to use Virtualbox instead.

**Comment by thaJeztah** [comment]
This looks like a user error, otherwise an issue with Docker Toolbox, which has its own issue tracker (https://github.com/docker/toolbox/issues), so let me close this, but feel free to continue the conversation if you don't manage to get it working

**Comment by cookiengineer** [comment]
@thaJeztah 

> This looks like a user error

Well, I tend to disagree as the error shown has nothing to do with an influence that a user can find out for themselves. And I bet the issue tracker will be flooded by other users with the same problem if it stays the same.

Why not simply show a message that the user knows this is intended? Like, a proper fix suggestion on what to do? A generic no pipe error is the same as a windows blue screen, and helps no one.

@FrenchBen I'm going to verify whether that fixes the issue or not. I have a Windows machine only at work, so I cannot verify this at weekends.

**Comment by cookiengineer** [comment]
Wanted to report back: The problem does not occur when using a Docker Quickstart (mingw) environment. However, the Kitematic Tool still has the no pipe error, so this issue is probably a duplicate of the Docker Tools' issues then.

**Comment by soundyogi** [comment]
+1

**Comment by nsidhaye** [comment]
@cookienginee: In docker Quickstart it will internally might use docker-machine ssh. If you run only bash prompt then you will see error.

Even from windows command prompt If I use docker-machine ssh then I can use docker commands. But I guess we want from windows prompt or only bash prompt one can see docker images.

Am I right? 

````
C:\Program Files\Git\bin>bash
USER@LAPTOP-DEV MINGW64 /bin
$ docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

USER@LAPTOP-DEV MINGW64 /bin
$ docker-machine env default
You can further specify your shell with either 'cmd' or 'powershell' with the --shell flag.

SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.99.100:2376
SET DOCKER_CERT_PATH=C:\Users\USER\.docker\machine\machines\default
SET DOCKER_MACHINE_NAME=default
SET COMPOSE_CONVERT_WINDOWS_PATHS=true
REM Run this command to configure your shell:
REM     @FOR /f "tokens=*" %i IN ('"C:\opt\Docker Toolbox\docker-machine.exe" env default') DO @%i

USER@LAPTOP-DEV MINGW64 /bin
$ docker ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.30/containers/json: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

USER@LAPTOP-DEV MINGW64 /bin
````

**Comment by nsidhaye** [comment]
@FOR /f "tokens=*" %i IN ('docker-machine env --shell cmd default') DO @%i
