### ISSUE TITLE
Inconsistent API response

### ISSUE THREAD

**Issue by isanych** [docker/docker#30714]
**Description**

incorrect images/create API call returns response 200 OK and 2 json messages, one of them is error description

**Steps to reproduce the issue:**
`$ curl -v --unix-socket /var/run/docker.sock -X POST "http:/v1.25/images/create?repo=acme.com%2Ftest&fromSrc=%2Fdata%2Ffile.tar"`
or
```
import docker
d = docker.from_env()
print(d.images.client.api.import_image("/data/file.tar", "acme.com/test"))
```

**Describe the results you received:**
```
*   Trying /var/run/docker.sock...
* Connected to http (/var/run/docker.sock) port 80 (#0)
> POST /v1.25/images/create?repo=acme.com%2Ftest&fromSrc=%2Fdata%2Ffile.tar HTTP/1.1
> Host: http
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Api-Version: 1.25
< Content-Type: application/json
< Docker-Experimental: true
< Server: Docker/1.13.0 (linux)
< Date: Fri, 03 Feb 2017 15:03:38 GMT
< Transfer-Encoding: chunked
<
{"status":"Downloading from http://%2Fdata%2Ffile.tar"}
{"errorDetail":{"message":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""},"error":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""}
* Connection #0 to host http left intact
```
or
```
{"status":"Downloading from http://%2Fdata%2Ffile.tar"}
{"errorDetail":{"message":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""},"error":"parse http://%2Fdata%2Ffile.tar: invalid URL escape \"%2F\""}
```

**Describe the results you expected:**
I would expect non 200 response and single json message, so response could be parsed.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm using python docker API which does not raise exception on this incorrect request, as response code is 200. Also python API returns response as text and could not parse response if I specify json response type as there are 2 messages in response.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 19
 Running: 14
 Paused: 0
 Stopped: 5
Images: 102
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 110
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-59-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 30
Total Memory: 31.42 GiB
Name: jbuild
ID: TNIU:DAHP:PAIG:EGPV:HVX4:E4P6:KENQ:TOAX:QDEP:A3VD:JSPL:JQME
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: true
Insecure Registries:
 docker.acme.com
 registry-proxy.acme.com
 127.0.0.0/8
Registry Mirrors:
 registry-proxy.acme.com
Live Restore Enabled: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker daemon running in Ubuntu 16.04 VM on ESXi 6 host. Client is docker python API 2.0.2 running on physical Windows 10 host.

**Comment by ripcurld0** [comment]
Hey @isanych, 
After looking into it it seems like you have a case here.
Although the Docker CLI catches the error and exits with status code 1, the API just display the error JSON message with response code 200 which is odd.

A way to fix that is to send a HTTP HEAD request to the `src` to validate it can be read before downloading the file.

Regarding your question in #30715:
it is possible to do that by piping the tar file into the standard input using `docker import` or setting `--data` to the path to the tar file using `cURL`.

//cc @thaJeztah @tonistiigi

**Comment by isanych** [comment]
Yes, docker cli is ok, but I'm rewriting my scripts on python api currently. According question, yes, I'm sending data to docker daemon now, but because I'm using remote server I'm downloading file from docker host first and then send it back, That's why I'm trying to specify host location, so daemon would directly read it.
