### ISSUE TITLE
Docker for AWS doesn't appear to benefit from ECR Policy during Stack / Service Creation

### ISSUE THREAD

**Issue by ambrons** [docker/docker#30713]
**Description**

Using Docker for AWS just release with docker version 1.13.0.   I'm able to use `docker stack deploy -c <composefile.yaml> --with-registry-auth <stack name>` without issue having done a `aws ecr get-login...` prior.  

However because AWS ECR docker login passwords are only good for 12 hours if the scheduler rebalances the deployed services after 12 hours and the node it's being deployed on doesn't have the existing authentication it fails to authenticate and you fail to find the image.

I've read through the issues and found this issue talking about enhancements to how --with-registry-auth works to allow it to use refresh tokens or the like.  https://github.com/docker/docker/issues/24940

I choose to create a new ticket as #24940 appears to be more geared towards solving dockerhub and less about ECR.  

I've also looked at several posts on the docker for aws forums.  The one that pin points the problem with no real solution is this:

https://forums.docker.com/t/possible-to-use-aws-ecr-for-image-registry/22295/3

Considering this is a Docker for AWS and you have developed Docker AWS containers to run on the EC2 instances specific to AWS, why can't we just include the ECR ReadOnly Policy to the ProxyRole created during cloud formation to have access to ECR without having to worry about authentication at all?

I have attempted to add the Policy (AmazonEC2ContainerRegistryReadOnly) to the created ProxyRole used by the InstanceProfile for all Docker Nodes in the cloud formation, however this has zero effect.  The result from a service ps is as follows:

```
$ docker-swarm service ps 3sgzt87ip19t
ID            NAME                   IMAGE                                                                            NODE                           DESIRED STATE  CURRENT STATE            ERROR                             PORTS
x6l8jtn9hnw0  esports_wallets.1      ###.dkr.ecr.us-east-1.amazonaws.com/path/to/image:tag  ip-172-31-20-65.ec2.internal   Ready          Rejected 2 seconds ago   "No such image: ###.d…"  
```

However if I remove the service and create it after typing `$(aws ecr get-login --region us-east-1)` it works fine, finds the image and runs.  However then it's back to 12 hours later I'm likely in the state referenced in the forum link above or in issue #24940.

We've been using ECS for over a year and the behavior of making sure the Instance profile role has the AmazonEC2ContainerRegistryReadOnly policy is all that's needed.

I dug a little down in the dockers deployed on an EC2 instance, cool stuff there how the SSH is actually a docker as well as the metadata service.  My assumption is we're not trying to assume the instance policy role during a registry fetch.  Or I could be talking out my butt there.

I've even gone as far as modifying the cloud formation template to include the ECR policies at creation time, but made no difference.

**Steps to reproduce the issue:**
1. Use AWS Console to apply  AmazonEC2ContainerRegistryReadOnly policy to cloud formation generated ProxyRole used by InstancePolicy of Docker For AWS
2. Create service or stack with an image referenced in ECR
3. service ps or container inspect to see that image is not found aka authentication wasn't present.

**Describe the results you received:**

```
$ docker-swarm service ps 3sgzt87ip19t
ID            NAME                   IMAGE                                                                            NODE                           DESIRED STATE  CURRENT STATE            ERROR                             PORTS
x6l8jtn9hnw0  esports_wallets.1      ###.dkr.ecr.us-east-1.amazonaws.com/path/to/image:tag  ip-172-31-20-65.ec2.internal   Ready          Rejected 2 seconds ago   "No such image: ###.d…"  
```

**Describe the results you expected:**

The service should have started without issue using the AWS InstanceProfile / Role / ECR Policy to obtain access to ECR

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 6
Server Version: 1.13.0
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: awslogs
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 6kup6o2m8rmgrydrj9k3p1089
 Is Manager: true
 ClusterID: sgq7930ifiv21xlc94jci3tsd
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.40.242
 Manager Addresses:
  172.31.40.242:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.785 GiB
Name: ip-172-31-40-242.ec2.internal
ID: REJ6:Q2GX:RYQD:KC3A:2ZK2:5JZJ:PT42:BT6B:64TN:XQED:WKBH:H7PC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 77
 Goroutines: 190
 System Time: 2017-02-03T14:48:08.410775982Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS / Docker for AWS 1 manager and 3 workers

**Comment by yongtang** [comment]
@ambrons You may want to take a look at
https://github.com/awslabs/amazon-ecr-credential-helper

In my case we use credential helper to integrate ECR with AWS instance profiles. I don't have experience with ECS so I don't know if you would encounter any issues with ECS though.

**Comment by ambrons** [comment]
@yongtang thanks for the suggestion I'll take a look.  However my issue isn't ECS.  It works great.  It was a comparison that I think Docker for AWS should behave in a similar manner when fetching docker images from ECR.

**Comment by thaJeztah** [comment]
ping @friism PTAL

**Comment by friism** [comment]
@ambrons thanks for opening this issue, we already have an internal tracking issue.

Since this is specifically about Docker for AWS, could I trouble you to close this issue and re-open on the dedicated Docker for AWS issue tracker? https://github.com/docker/for-aws/issues/new

Sorry about the back and forth.
Michael

**Comment by thaJeztah** [comment]
Let me go ahead and close the issue here
