### ISSUE TITLE
Predefined build-time arguments persisting in the resulting image.

### ISSUE THREAD

**Issue by maynep** [docker/docker#30721]
**Description**

Predefined ARG HTTP_PROXY and HTTPS_PROXY are persisting in the resulting image. **Security risk if proxy requires username and password.**

**Steps to reproduce the issue:**
1. docker build using --build-arg HTTP_PROXY=http://username:password@proxy.thing.com:8080/
2. docker run -ti

**Describe the results you received:**
$ echo $HTTP_PROXY
http://username:password@proxy.thing.com:8080/

**Describe the results you expected:**
$ echo $HTTP_PROXY
<blank>

**Additional information you deem important (e.g. issue happens only occasionally):**
Repeatable

**Output of `docker version`:**
```
$ docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 13
 Running: 0
 Paused: 0
 Stopped: 13
Images: 4
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 55
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 2.669 GiB
Name: moby
ID: ZQNT:ZJL4:KAGX:4RUB:ZLRE:XY72:MNHL:FJYD:AQSO:XPLY:O7EV:LXZZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Http Proxy: <removed>
Https Proxy: <removed>
No Proxy: <removed>
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running Docker for Windows

**Comment by alexellis** [comment]
👍 I also found this and it prevents me from wanting to push any images produced with build-args to the public Hub. We don't want to leak the details of our proxy servers to the internet.

Any thoughts whether this is hard/easy to mask/remove after using --build-arg @justincormack ?

The other place it shows up is on `docker history`.

**Comment by justincormack** [comment]
Cc @dave-tucker

**Comment by thaJeztah** [comment]
Build args show up in the image history as a prefix to each `RUN` command's instruction (see the output of `docker history`), which is documented; https://docs.docker.com/engine/reference/builder/#/arg, and the reason they are not intended to contain confidential information.

These variables _wont_ persist in the image as an environment variable though, unless they are are used in (e.g.) an `ENV` instruction.

What @maynep may be seeing, is that Docker for Mac / Docker for Windows automatically sets `*_proxy` environment variables when _running_ images as well

**Comment by paddy-hack** [comment]
@thaJeztah Documenting it is good but it still sucks if your behind an authenticating proxy :disappointed: 

Maybe that #30637 can be of help but that would sure get rather ugly
```
RUN https_proxy=$(cat /run/secrets/https_proxy 2>/dev/null); \
    curl <url>
```
It would work both with and without the secret available though so is portable.

**Comment by dave-tucker** [comment]
I think this should be fixed by https://github.com/docker/docker/pull/31584

**Comment by thaJeztah** [comment]
Yes; this will be in 17.05
