### ISSUE TITLE
Docker breaks Windows networking services when enabling Hyper-V on a non compatible processor

### ISSUE THREAD

**Issue by riahc3** [docker/docker#30737]
**Description**

Docker enabled Hyper-V on a non SLAT processor that is not compatible with Windows 10 Hyper-V and it broke a lot of networking services (OpenVPN, Npcap, etc)

**Steps to reproduce the issue:**
1. Install OpenVPN and nmap on a processor without SLAT.
2. Install Docker
3. Docker will ask you if you want to enable Hyper-V. Say yes.
4. Docker gives a error but auto restarts any ways.
5. Weird networking starts.

**Describe the results you received:**
Nmap said it could not find the service it needed to snif. OpenVPN could not use it's tap adapter... Other things as well.

**Describe the results you expected:**
The opposite.

**Additional information you deem important (e.g. issue happens only occasionally):**
Docker should autodetect the ability for the system to be compatible with itself and Hyper-V. I imagine it enables Hyper-V thru a Powershell command and NO.

**Output of `docker version`:**
Latest. Just downloaded it and tested to reproduce it.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I also had VMWare Workstation and VirtualBox to test that it affected the network stack and I confirm it does. They were installed BEFORE Docker.

**Comment by friism** [comment]
@riahc3 did this happen when installing Docker for Windows? If so, please close and re-open issue here: https://github.com/docker/for-win/issues/new

**Comment by riahc3** [comment]
@friism Yes. My apoligies for putting it in the incorrect section.
