### ISSUE TITLE
[proposal] more consistent rest and cli api documentation

### ISSUE THREAD

**Issue by krasi-georgiev** [docker/docker#30739]
follow up from #6889 and #27919

* The problem:
    some api help  is missing from the the cli and it is present in the rest api docs 

    docker image list --help  - no documentation for available filters
    https://docs.docker.com/engine/api/v1.25/ - filters well documented here

* In the following context
       swagger is now used to generate the REST docs
       swagger will be used to generate most or all  go api/types
       api/types are shared between the client and the daemon

I suggest that swagger is also used to generate one extra type that will be used when adding a cobra command

* cobra command now
      Use:   "images [OPTIONS] [REPOSITORY[:TAG]]",
      Short: "List images",

* cobra command after
      Use:   types.cli.use,
      Short: types.cli.short,

**the command descriptions for the cli and the rest api should remain separate,  but should be in a single swagger file.**

I am not familiar with swagger , but hopefully it allows adding custom fields which will be used to generate the go type used for the cobra command

I think this has the following advantages:
*  the maintainers don't have to remember to change the REST docs and the cli docs
*  better UX 
*  reuse some command descriptions

**Comment by krasi-georgiev** [comment]
Just had a quick look at the https://github.com/goadesign/goa

https://www.youtube.com/watch?v=t1MxuSKVXPc

this package seems to do exactly what we need and has a better approach.

instead of using swagger for generating the go code the goa package generates the swagger file and also bootstraps the app  (the cobra command as well)

this will eliminate the problem that all maintainers need to learn  swagger

**Comment by cpuguy83** [comment]
ping @dnephin @thaJeztah
