### ISSUE TITLE
docker run -v doesn't follow symlinks when checking if a directory can be mounted

### ISSUE THREAD

**Issue by barisione** [docker/docker#30738]
**Description:**

`docker run` (on macOS Sierra) **doesn't resolve symlinks** passed with `-v`, so it complains that the path is not mountable.
The Preferences UI **does resolve symlinks** so you cannot add the directory that failed mounting to your list of allowed directories.

**Steps to reproduce the issue:**

1. Verify that `/var` is a symlink to `/private/var` on macOS (this is the normal behaviour).
2. Verify that the Docker configuration contains  `/private` in the list of directories which can be mounted (Docker... -> Preferences -> File Sharing).
3. Run `docker run -v /var/folders/foo:/foo true`.
4. Get an error about `/var/folders/foo` not being shared.
5. Try to add `/var/folders/foo` to the list of shared folders.
6. Get an error because “The export path /private/var/foo overlaps with the export path /private.”.

**Describe the results you received:**

When doing docker run:
```
docker: Error response from daemon: Mounts denied:
The path /var/folders/foo
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
```

When trying to add the path in the preferences:
```
The export path /private/var/foo overlaps with the export path /private.
```

**Describe the results you expected:**

I would expect either docker run to cope with symlinks by resolving them or the preferences dialog to allow adding paths with symlinks.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Wed Jan 18 16:20:26 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 54
 Running: 2
 Paused: 0
 Stopped: 52
Images: 40
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 157
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.4-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: D6YQ:LVUU:NFES:MJAW:73F5:T4DH:HZHB:Q7GW:F6BK:OGES:FEKB:XKBD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 29
 Goroutines: 36
 System Time: 2017-02-03T19:00:50.848113147Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Thanks for reporting; This looks like an issue with the GUI on Docker for Mac, can you reopen it in the docker for mac issue tracker? https://github.com/docker/for-mac/issues
