### ISSUE TITLE
ENTRYPOINT ['/bin/bash'] not work, but `--entrypoint=/bin/bash` works

### ISSUE THREAD

**Issue by eromoe** [docker/docker#30752]
Docker: 1.12.5
OS: centos 7

My Dockfile:
```
FROM python:3

# Set the locale
RUN echo 'LC_ALL=en_US.UTF-8\n\
LANGUAGE en_US:en\n\
LANG=en_US.UTF-8' >> /etc/environment

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

RUN pip --no-cache-dir install -U 'requests[security]' \
    -U 'requests[socks]' \
    jieba \
    lxml \
    readability-lxml \
    jupyter \
    ipython \
    ujson

COPY jupyter_notebook_config.py /root/.jupyter/

ENTRYPOINT ['/bin/bash']
```

but `docker run -it --rm py3` not work, got
```
/bin/sh: 1: [/bin/bash]: not found
```

whilst add `--entrypoint=/bin/bash` works
```
docker run -it --rm --entrypoint=/bin/bash py3
```

I also tried `ENTRYPOINT [/bin/sh', '-c', 'bash']` and `CMD ['/bin/bash']`, both not work.

**Comment by thaJeztah** [comment]
You need to use double quotes, as single quotes are not valid JSON, therefore docker will use it as a regular command, and run `/bin/sh -c "['/bin/bash']"`.

Change it to 

```Dockerfile
ENTRYPOINT ["/bin/bash"]
```

And it should work.

I'll close this issue, because I don't think there's a bug at hand, but feel free to continue the conversation

**Comment by ScreamZ** [comment]
Just lost half a day with that T_T

**Comment by kasabov** [comment]
I also lost so much time on this, thought of leaving this here:

     $ docker run -it --entrypoint=/bin/sh mariadb -c /bin/bash

**Comment by alexandrebarbaruiva** [comment]
At least you're not the only one
