### ISSUE TITLE
docker run --rm reports error attempting to remove container in version 1.13 with 1.24 API

### ISSUE THREAD

**Issue by bmitch3020** [docker/docker#30775]
**docker run --rm reports an error when attempting to remove container in version 1.13 with 1.24 API**

This appears to be a side effect of [PR #20848](https://github.com/docker/docker/pull/20848). When using a newer client and server, but reverting the API to something before 1.25, I'm seeing an error from a failed attempt to remove a container. This is generating nuisance errors with the classic swarm as seen in [issue #2620](https://github.com/docker/swarm/issues/2620).

**Steps to reproduce the issue:**
```
$ # normal result
$ docker run -it --rm busybox echo hello
hello

$ # error when using an older api version
$ DOCKER_API_VERSION=1.24 docker run -it --rm busybox echo hello
hello
ERRO[0002] error removing container: Error response from daemon: removal of container dc8b9e47ddfdea3c8d5c6abfd5b6fd4d703a5aa43fd5a712be3dcc8d730a163c is already in progress
```

**Describe the results you received:**
The container is removed by the docker daemon and then the docker client attempts to also remove the container, resulting in the error message.

**Describe the results you expected:**
When using an API before 1.25, the docker server should not perform the auto remove, it should instead be performed by the client. I'm not sure if this change needs to be made as part of the client request or the daemon processing of the request.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've reproduced this issue in multiple environments

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:44:08 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 233
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /home/var-docker/aufs
 Backing Filesystem: extfs
 Dirs: 578
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: w4dwja2i927qhe4tbuuirwhkg
 Is Manager: true
 ClusterID: am788rn0mc5vdqtqna79g237a
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.234.174
 Manager Addresses:
  192.168.234.174:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.75 GiB
Name: bmitch-asusr556l
ID: LTRH:V6W7:3UHO:4AV2:OSYM:6G4R:WKJR:2BRK:MGCO:Z4KJ:UPTF:LTRU
Docker Root Dir: /home/var-docker
Debug Mode (client): false
Debug Mode (server): false
Username: bmitch3020
Registry: https://index.docker.io/v1/
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Labels:
 foo=bar
 env=laptop
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Seen on physical and virtual machines, Debian and RHEL.

**Comment by thaJeztah** [comment]
Thanks for reporting; this issue has been fixed on master through https://github.com/docker/docker/pull/30113, and will be in docker 1.14; the error message itself can be ignored.

I'll close this issue, because this has been resolved, but feel free to continue the conversation
