### ISSUE TITLE
docker login with a wrong path.

### ISSUE THREAD

**Issue by Hyzhou** [docker/docker#30779]
**Description**

docker@default-online:~$ docker login index.docker.io/namespace
Username: hyzhou
Password:
Login Succeeded

I provided the registry for user. Some people say they are already login but can not pull the they private image. In the end, we find the user login with a domain and path.

If docker can refuse the login, when login url like this.

**Describe the results you received:**

Login Succeeded

**Describe the results you expected:**

Login Faild

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker@default-online:~$ docker version
Client:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.3
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   6b644ec
 Built:        Wed Oct 26 23:26:11 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
docker@default-online:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.3
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host overlay null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.27-boot2docker
Operating System: Boot2Docker 1.12.3 (TCL 7.2); HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default-online
ID: LXGY:ZWCS:I6JU:QJGI:6VDP:VYDW:W75W:WUO7:YYO5:TO2D:ZDHF:B4IE
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 23
 System Time: 2017-02-07T08:29:55.299882751Z
 EventsListeners: 0
Username: hyzhou
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Ok so the problem seems to be;

When doing

    docker login index.docker.io/namespace


```
cat ~/.docker/config.json
{
	"auths": {
		"index.docker.io": {
			"auth": "<redacted>"
		}
	}
}
```

However, when doing just `docker login`;

```
cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "<redacted>"
		}
	}
}
```

One stores credentials under `index.docker.io`, but the other one under `https://index.docker.io/v1/`

**Comment by krasi-georgiev** [comment]
#dibs

**Comment by krasi-georgiev** [comment]
@thaJeztah is there any trial account with private repos or a coupon so  I can  troubleshoot this?

**Comment by Hyzhou** [comment]
```
docker@default-online:~$ docker login index.docker.io/namespace
Username: xxxxxxxxxx
Password:
Login Succeeded
docker@default-online:~$ cat .docker/config.json
{
	"auths": {
		"index.docker.io/namespace": {
			"auth": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
		}
	}
}
```

@thaJeztah the "auths" like this. can not pull my private repo.

**Comment by thaJeztah** [comment]
@krasi-georgiev free accounts on Docker Hub come with one private repository, and unlimited public repo's.

**Comment by krasi-georgiev** [comment]
@thaJeztah yes you are right , I was looking at the organisation repos.
