### ISSUE TITLE
Unable to set args for v2 plugins

### ISSUE THREAD

**Issue by e4jet** [docker/docker#30795]
**Unable to set args for v2 plugins**
The plugin I'm using supports 3 arguments as seen in this output:
```
# docker plugin inspect nimble
[
    {
        "Config": {
            "Args": {
                "Description": "Group connection information",
                "Name": "group",
                "Settable": [
                    "ip",
                    "user",
                    "pass"
                ],
                "Value": [
                    "",
                    "",
                    ""
                ]
            },
```

However, I am not able to set the values.
```
# docker plugin set nimble group.ip=10.1.2.3
Error response from daemon: "group.ip" is not settable
```

**Steps to reproduce the issue:**
1. Create a plugin with 'Args' defined
2. Inspect the plugin
3. Attempt to set the arguments defined in the 'Args' configuration

**Describe the results you received:**
Unable to set args
```
DEBU[6382] Calling POST /v1.25/plugins/nimble/set       
ERRO[6382] Handler for POST /v1.25/plugins/nimble/set returned error: "group.ip" is not settable 
```

**Describe the results you expected:**
Args should be set.

**Additional information you deem important (e.g. issue happens only occasionally):**
None.

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 6
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: eforgette-u16p2
ID: UQWP:CEW2:4P3T:AFR2:3R7U:SUL3:QH2Y:5JGY:AYIY:64YM:WRT5:AZRJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 22
 System Time: 2017-02-07T09:53:59.166981721-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
None.

**Comment by e4jet** [comment]
#dibs

**Comment by e4jet** [comment]
@vieux and @anusha-ragunathan looks like v2/settable/isSettable() will only allow a settable named "value" to be set.  This seems like a bug.  In addition, args looks like it will be replaced with only that which is set (loosing all other values).

**Comment by vieux** [comment]
@e4jet I believe your plugin should look like this:

```
# docker plugin inspect nimble
[
    {
        "Config": {
            "Args": {
                "Description": "Group connection information",
                "Name": "group",
                "Settable": [
                    "ip",
                    "user",
                    "pass"
                ],
                "ip": "",
                "user": "",
                "pass": "",
            },
```

The values in `Settable` refer to an actual key in the config

**Comment by e4jet** [comment]
Thanks for the quick reply @vieux.  Unfortunately, that didn't work.  The plugin starts, but the JSON gets converted.

snip from config.json
```
  "Args": {
    "Description": "Group connection information",
    "Name": "group",
    "Settable": [ "ip", "user", "pass" ],
    "ip": "",
    "user": "",
    "pass": ""
  },
```

snip from 'docker plugin inspect'
```
            "Args": {
                "Description": "Group connection information",
                "Name": "group",
                "Settable": [
                    "ip",
                    "user",
                    "pass"
                ],
                "Value": null
            },
```

This seems to be the right marshaling behavior because 'Value' is defined as a slice of strings in api/types/plugin/PluginConfigArgs.  I may still be missing something though...

**Comment by vieux** [comment]
ping @tiborvass  :)

**Comment by e4jet** [comment]
I wonder if Args was supposed to be a slice of PluginConfigArgs like Env is a slice of PluginEnv.  It might be a bit too late for a change like that since this is out of experimental now (and would be a breaking API change)...

**Comment by tiborvass** [comment]
@e4jet So there are 2 solutions:

```json
"Args": {
  "Description": "Arguments to be passed to the plugin",
  "Name": "args"
}
```
And then do `docker plugin set $plugin args="--group-ip 1.2.3.4 --group-user username --group-pass password"` but your program will have to parse the cli args. The problem with this solution is that it bypasses the settings mechanism. As a hack you could put in the description, what flags to put in the args setting but it's weird.

Or you can also do:
```json
"Env": [
  {
    "Name": "group.ip",
    "Description": "Group IP"
  },{
    "Name": "group.user",
    "Description": "Group user"
  },{
    "Name": "group.pass",
    "Description": "Group password"
  }
]
```

And then run `docker plugin set $plugin group.ip=... group.user=... group.pass=...` but your program will have to read these as environment variables.

Hope this helps, we'll update the documentation to make things a bit clearer.

**Comment by anusha-ragunathan** [comment]
Docs explained in https://github.com/docker/docker/pull/32103
