### ISSUE TITLE
With Docker Engine Swarm will we be able to access containers via hostname?

### ISSUE THREAD

**Issue by the-nw1-group** [docker/docker#30793]
**Description**

Using Docker 1.13.1 our application uses OpenLDAP to store users/etc. We've configured this for master/master/master, but I can't see how to use Docker Engine Swarm to create this. If I use (obv. abbreviated here):
```
--replicas 3 --name ldap --hostname "{{.Service.Name}}-{{.Task.Slot}}"
```
I get three ldap containers, each with a hostname of `ldap-1 ldap-2 ldap-3` for example. I'm able to access the service through `ldap` from my esb container. But the ldap's need to access the other masters directly to replicate data between them. They can't access each other through their hostnames.

If I create 3 separate ldaps:
```
--replicas 1 --name ldap-1
--replicas 1 --name ldap-2
--replicas 1 --name ldap-3
```
I can then set up the replication ok, but my esb can't then access them through the swarm load balancer, and we'd have to create our own load balancer container (and worry about failover for that as well.)

Am I missing something?

**Steps to reproduce the issue:**

Create swarm, and join nodes to it
Create overlay network autotest_common
Create a simple service:
```
docker service create --replicas 3 --name test --network autotest_common --hostname "{{.Service.Name}}-{{.Task.Slot}}" busybox top
```
Try to ping one of the test containers via it's hostname from another container:
```
docker exec test.1.x1deheydtkdtcjykt4m5s4re1 ping test-2
```
**Describe the results you received:**

Successful ping

**Describe the results you expected:**

```
ping: bad address 'test-2'
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Steps above is just an example to show the point.

**Output of `docker version`:**
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
docker info
Containers: 9
 Running: 4
 Paused: 0
 Stopped: 5
Images: 51
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-204660330-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 9.776 GB
 Data Space Total: 107.4 GB
 Data Space Available: 97.6 GB
 Metadata Space Used: 31.89 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.116 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 90x41gmg4zqpjniuuo7yz7di4
 Is Manager: true
 ClusterID: mifoxi450x0l6en3co0esj07m
 Managers: 1
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.102.71.163
 Manager Addresses:
  10.102.71.163:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.702 GiB
Name: vm-pe-tst00
ID: YGKS:SQHV:RS6U:26F5:FU3O:A5A5:YDYG:NUGF:K7CC:7SJ5:RYXC:MSKV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VMs within our corporate datacentre

**Comment by thaJeztah** [comment]
containers/services are discoverable by their _name_, not the _hostname_ you set. The hostname is local to the container, and only available _inside_ the container.

Note that there's a discussion to add `--network-alias` to services (https://github.com/docker/docker/issues/24787), which would allow you to set a custom alias for services, which _can_ be used on the network, and I just opened a proposal (https://github.com/docker/docker/issues/31964) to add an advanced `--network` syntax, to allow setting this option _per network_, and also mentioned adding an option to set these options _per container_ / _task_ backing the service.

I hope this answers your question; I'll go ahead and close this issue for housekeeping, but feel free to continue the discussion.
