### ISSUE TITLE
docker service update --rollback option not available in Docker 1.12.6

### ISSUE THREAD

**Issue by dvohra** [docker/docker#30799]
Is the `docker service update` option `--rollback` not available in Docker 1.12.6? The `--rollback` does not get applied. CoreOS stable has Docker 1.1.2.6 pre-installed.

**Comment by aaronlehmann** [comment]
No, `--rollback` was added in Docker 1.13.0.

**Comment by dvohra** [comment]
Thanks @aaronlehmann. Was `--force` also added in 1.13, for the` docker service update` command?

**Comment by aaronlehmann** [comment]
Yes.

**Comment by dvohra** [comment]
@aaronlehmann.

Thanks. The issue may be closed.

**Comment by dvohra** [comment]
Tested `docker service update` options `--rollback` and `--force` on Docker 1.13 and these are supported on Docker 1.13.
