### ISSUE TITLE
"docker wait my_container" returns 0 if my_container is non-interactive and still running

### ISSUE THREAD

**Issue by mstanleyjones** [docker/docker#30803]
**Description**

"docker wait my_container" returns 0 while my_container is still running

**Steps to reproduce the issue:**
1.  Start a non-interactive container in the background:
    
    ```bash
    $ docker run -d --name=my_container ubuntu bash
    ```
2.  In another terminal, run `docker wait my_container`.

**Describe the results you received:**

The `docker wait` command returns 0 immediately, even though `my_container` is still running.

**Describe the results you expected:**

I expected `docker wait` to block like it would with an interactive container. You get this result if you start `my_container` with `-dit` flags.

**Output of `docker version`:**

```none
Client:
 Version:      1.13.1-rc1
 API version:  1.25
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1-rc1
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   2527cfc
 Built:        Sat Jan 28 00:43:00 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```none
Containers: 23
 Running: 1
 Paused: 0
 Stopped: 22
Images: 248
Server Version: 1.13.1-rc1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: g35wgnc8gq8vj00coqm5tfy7r
 Is Manager: true
 ClusterID: tovqmbzkj5mi9rmmcvmug8ecw
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.6-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: Q6NJ:KJI4:MYVU:E3QH:TQN2:HNRH:7DSM:ESVO:L6EE:TRI7:HQIQ:ZXWG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 39
 Goroutines: 141
 System Time: 2017-02-07T23:37:23.12485272Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

cc @thaJeztah

**Comment by jmzwcn** [comment]
$ docker run -d --name=my_container ubuntu **top**
In another terminal, run docker wait my_container.

Maybe it will work use "top" instead of bash

**Comment by thaJeztah** [comment]
Yes, the problem here is that the container would exit immediately; can you double check if the container is running?

**Comment by mstanleyjones** [comment]
You are right! I thought the container was still running but it was actually a different container. But is it weird that `docker wait` returns 0 if the container you say you are waiting for has already stopped? It seems like that should be an error condition.

**Comment by thaJeztah** [comment]
Well

```
Block until one or more containers stop, then print their exit codes
```

I guess it does what it describes; print the exit code (which is `0` in this case). The `wait` command can be used if something has to wait until the container exits; if it would be an _error_ that would mean we're introducing a race condition (I need to be in time to _start_ the `docker wait` _before_ the container exits)

Anyway, I'm closing this issue, because it seems to work as advertised, but we can continue the discussion 👍
