### ISSUE TITLE
Docker Volume Request HTTP/1.1 with empty `Host` value failed nginx proxy

### ISSUE THREAD

**Issue by ghostplant** [docker/docker#30827]
**Description**

When docker daemon post HTTP/1.1 request to drivers, the headers contains Host key with empty value, which is not allowed by standard HTTP/1.1 protocol. See also RFC 2316, section 14.23.

This blocks HTTP wrapper engines like nginx failing to wrap docker daemon requests and proxy to specific drivers.

**Comment by ghostplant** [comment]
This is the illegal HTTP request data:

POST /Plugin.Activate HTTP/1.1
Host:
User-Agent: Go-http-client/1.1
Content-Length: 0
Accept: application/vnd.docker.plugins.v1.2+json

**Comment by cpuguy83** [comment]
This is expected since `Host` doesn't make sense for unix sockets, and is incorrect to use a unix socket path as the host header here.
There seems to be a lot of back and forth on whether or not an empty host header is valid, but from what I can tell it is, just that nginx is not handling it correctly.

From the spec:
```
A client MUST include a Host header field in all HTTP/1.1 request messages . If the requested URI does not include an Internet host name for the service being requested, then the Host header field MUST be given with an empty value. An HTTP/1.1 proxy MUST ensure that any request message it forwards does contain an appropriate Host header field that identifies the service being requested by the proxy. All Internet-based HTTP/1.1 servers MUST respond with a 400 (Bad Request) status code to any HTTP/1.1 request message which lacks a Host header field.
```

Note, it says the field must be present, it does not say it can't be empty... and in fact says that it must be empty in some cases.

Also see we even had to make a special case for this to hack around older Docker clients talking to golang >= 1.6
https://github.com/docker/docker/blob/master/cmd/dockerd/hack/malformed_host_override.go

**Comment by ghostplant** [comment]
As the `request data` above, docker daemon indeed contains 'Host' field but nginx still regards it as empty and I got 400. How to enable the malformedhack?

**Comment by cpuguy83** [comment]
I'm really not sure on nginx, or even how to get nginx to proxy a unix socket like that.

**Comment by ghostplant** [comment]
nginx can listen on unix:/var/run/docker/plugins/driver.sock and work with auth & security pre-check.

**Comment by samprog1** [comment]
Try adding the following lines to your default.conf:

`proxy_http_version 1.1;`
`proxy_set_header Upgrade $http_upgrade;`
`proxy_set_header Host $host;`
`proxy_set_header Connection "upgrade";`
`proxy_buffering Off;`
`proxy_cache_bypass $http_upgrade;`

If you haven't already

**Comment by ghostplant** [comment]
@samprog1 
Still with no luck, nginx server discards illegal request protocol before doing proxy.

**Comment by ghostplant** [comment]
@cpuguy83 
Do you think reserving a system environment variable DOCKER_HTTP_SET_HOST is a solution? Docker daemon will read this variable and set HTTP request as the 'Host: $DOCKER_HTTP_SET_HOST'.
If DOCKER_HTTP_SET_HOST is not defined, docker request HTTP with 'Host: ' as original behavior does.

**Comment by cpuguy83** [comment]
No, these kinds of magic env vars are not good, especially so for working around a short-coming in 3rd party software.
From what I can tell, an empty host header is perfectly legal.
If nginx can't handle this, then nginx should be updated (it is open source as well!).

Out of curiousity, why are you using nginx here? Plugins should be running on the host and not proxied to some other service.

**Comment by ghostplant** [comment]
@cpuguy83 
It is used to proxy a non-root plugin driver.

**Comment by thaJeztah** [comment]
I have to side with @cpuguy83 here, as I don't see this being a bug in docker; I suggest opening an issue or pull request in the nginx issue tracker.

I'm closing this issue, but feel free to continue the conversation

**Comment by maxdebayser** [comment]
I know this topic has been closed for a few months now, but I had the same issue and found a workaround for nginx. So I'll just leave it here for anyone who experiences this problem:

    server {
        listen unix:/var/run/docker_proxy/docker_proxy.sock default_server;
        ignore_invalid_headers on;
        server_name _ "";

        # hack to get nginx to accept the empty Host
        # header sent by some docker clients
        error_page 400 = @mylocation;

        location / {
            try_files $uri @mylocation;
        }

        location @mylocation {
            internal;
            proxy_intercept_errors off; 
            proxy_pass http://unix:/var/run/docker.sock;
        }
    }

**Comment by ghostplant** [comment]
@maxdebayser Thanks, handling error page will work.

**Comment by maxdebayser** [comment]
@ghostplant I just realised that any request that has a POST body will fail (nginx will not forward the body to the error handler) because nginx stops processing the request when it finds the empty host header. In the end I think it's easier to disable the Host header verification and recompile nginx.

**Comment by ghostplant** [comment]
@maxdebayser Actually, the body will be passed to error handler but the 'content-length' header is dropped. So nginx body handler no longer reads body content.

**Comment by minidfx** [comment]
Hack works well for IoT devices which connects to the proxy server using an IP and send an empty **Host** as described by the RFC.

Thank you @maxdebayser !

I hope NGinx will support this use case without Hack!

**Comment by thaJeztah** [comment]
As mentioned above; nginx is open source as well, so definitely worth opening a pull request there to fix the header validation
