### ISSUE TITLE
Windows Server 2016 Event Viewer errors and warnings about disk operations

### ISSUE THREAD

**Issue by akunaatrium** [docker/docker#30824]
**Description**

Building a Docker image on Windows Server 2016 results in errors and warnings in the Windows Event Viewer.

**Steps to reproduce the issue:**
1. Build an image.
2. Take a look at the Event Viewer -> Windows logs -> System

**Describe the results you received:**
Errors and warnings in the Event Viewer.
![errors](https://cloud.githubusercontent.com/assets/1319115/22738425/12a3352e-ee10-11e6-842e-42011f34d111.png)
![warnings](https://cloud.githubusercontent.com/assets/1319115/22738430/151294d0-ee10-11e6-81a7-4141efb18aa7.png)

**Describe the results you expected:**
No errors and warnings.

**Output of `docker version`:**
```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   d1515a5
 Built:        Thu Dec 15 09:24:59 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.4
 Git commit:   d1515a5
 Built:        Thu Dec 15 09:24:59 2016
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 12
Server Version: 1.14.0-dev
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.576.amd64fre.rs1_release_inmarket.161208-2252)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 3.999 GiB
Name: ODIN
ID: U5LZ:SW2H:35BO:JTNL:FNEB:EGNI:T4Q5:W554:ASP5:OSGC:GQ3E:QRHP
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Azure VM

**Comment by friism** [comment]
@akunaatrium can you post the Dockerfile (or one that also exhibits the problem) that you're trying to build so that the problem can be reproduced or are you seeing this when building any Dockerfile?

**Comment by jhowardmsft** [comment]
@akunaatrium Looking at the log above (particularly the second one), I'm suspecting a failing disk - at least that's what the error suggests. I've just looked at the event log on a couple of machines here after doing some builds and it's clean. For that reason, and that you haven't posted the dockerfile asked for above, I'm closing this issue. Please re-open once you can attach the dockerfile and have verified that there isn't a hardware issue. Thanks.
