### ISSUE TITLE
[swarm mode][volume plugin] docker volume rm does not delete info in metadata.db when run in different host

### ISSUE THREAD

**Issue by jzhoucliqr** [docker/docker#30837]
**Description**

In swarm mode, with volume plugin, If create volume in host1, then run `docker volume rm` in host2, the volume is deleted, but the info in /var/lib/docker/volumes/metadata.db in host1 is not cleaned up, and it stays there forever. 

Maybe we should error out when can't find metadata info on current host for volume rm. 

**Steps to reproduce the issue:**
1. on host1: docker volume create -d testvol
2. on host2: docker volume rm testvol
3. check host1: /var/lib/docker/volumes/metadata.db

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:55:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Yep, this is expected.
`docker volume *` are node-local commands and swarm-mode is not supported currently.

Closing as this is currently expected behavior... but feel free to discuss.
Thanks for the report 🙇
