### ISSUE TITLE
Files with special characters in ADD and COPY

### ISSUE THREAD

**Issue by ruippeixotog** [docker/docker#30833]
I'm trying to add in a Dockerfile a file with square brackets. Consider, for example, the following minimalistic Dockerfile:

```
FROM alpine

ADD "arr[0].txt" /

CMD ["bash", "-c", "ls -la *.txt"]
```

And a file called `arr[0].txt` in the working directory. Trying to build this Dockerfile, I get:

```
Step 2/3 : ADD "arr[0].txt" /
No source files were specified
```

I already tried several variations of this command based on [Go filepath](https://golang.org/pkg/path/filepath/#Match), with no luck:

* `ADD "arr\\[0\\].txt" /` (No source files were specified)
* `ADD ["arr\\[0\\].txt", "/"]` (No source files were specified)
* `ADD arr\\[0\\].txt /` (lstat arr\\[0\\].txt: no such file or directory)
* `ADD "arr\[0\].txt" /` (lstat arr\\[0\\].txt: no such file or directory)
* `ADD ["arr\[0\].txt", "/"]` (No source files were specified)
* `ADD arr\[0\].txt /` (No source files were specified)

Am I just missing the right pattern, or is this a bug?

**Comment by justincormack** [comment]
You want
```
FROM alpine
ADD arr[[]0].txt /
```

Its somewhat confusing, as it uses Go file pattern matches not shell, see https://golang.org/pkg/path/filepath/#Match so to match `[` you need to match the range only containing `[` ie `[[]`...

**Comment by ruippeixotog** [comment]
That works, thanks! I was reading that pattern syntax on my first tries but from what I understood, I could use:

```
'\\' c      matches character c
```

To match a `[` using `\\[`. Isn't that right?

**Comment by justincormack** [comment]
Yes it is a bit odd. Actually by `'\\'` they mean a single backslash (due to Go string literal escaping), but eg in the JSON form you need to double that up (due to JSON escaping) but oddly I can't get it to work for the `[` case (it works to escape other characters).

**Comment by ruippeixotog** [comment]
Ok, makes some sense. Thanks! Unless you want to leave this open to push for a further clarification in the docs or more consistent expectations on the file patterns, you can close this issue.

**Comment by justincormack** [comment]
Well I might leave it open for a bit to see if anyone can clarify the `\` case...

**Comment by yongtang** [comment]
It is kind of interesting:

https://github.com/docker/docker/blob/v1.13.0/builder/dockerfile/internals.go#L308
https://github.com/docker/docker/blob/v1.13.0/builder/dockerfile/internals_unix.go#L28

- `ADD arr\[0\].txt /`:
Internally `arr[0].txt` is passed, and `filepath.match` will be invoked to check the match as `containsWildcards(origPath)` is true.
But the `filepath.match` is against `arr[0].txt` so no file found.

- `ADD arr\\[0\\].txt /`:
Internally `arr\[0\].txt` is passed, and `filepath.match` will not be invoked (will check `stat` instead) to check the match as `containsWildcards(origPath)` is false.
But then `stat` is done against `arr\[0\].txt` so no file found.

**Comment by thaJeztah** [comment]
I've add a "docs" label to this; is someone willing to open a pull request to add an explanation / some examples to the docs? https://github.com/docker/docker/blob/master/docs/reference/builder.md#copy.

**Comment by ffoysal** [comment]
I created pull request 
https://github.com/docker/docker/pull/31982

**Comment by ffoysal** [comment]
@thaJeztah just wondering should this issue still be open as the PR is merged

**Comment by thaJeztah** [comment]
Oh, yup this can be closed now :+1:
