### ISSUE TITLE
--mount type=bind an img file to a directory? 

### ISSUE THREAD

**Issue by ascora** [docker/docker#30830]
**Description**

We got an ext4 image located on a shared storage, which we can mount and use easily on a local server, e.g. via:
	mount /nfs/disk.img /mnt

With our containers running in Docker Swarm mode we would now like to mount it in order to use the content of the img file inside the container.

We want to use 
    --mount type=bind,src=/nfs/disk.img,dst=/var/www/html/ 
but we always get an error message that the file is not a folder.

We already tried alternative ways:
-We could mount it on the host server before using "docker service create ..."  but we don't know at which server the task will be deployed by docker swarm
-We could of course map the img file to an img file inside the container. But in that case our Dockerfile needs to mount the file and it doesn't have privileges to do so. I'm not sure if this is even possible to create privileged services but even if it is, it doesn't feel right.

What can we do?

**Steps to reproduce the issue:**
1. Create a sparse file: dd of=sparse-file bs=1k seek=102400 count=0 # creates a 100Meg disk.img; mkfs.ext4 disk.img
2. Try to mount it to a docker service:  --mount type=bind,src=/nfs/disk.img,dst=/var/www/html/ 

**Describe the results you received:**
We receive an error message that the file is not a folder

**Describe the results you expected:**
mounting the img to a folder

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
The img file is currently located on a shared Gluster device. However, the results are identical when using local or NFS files.

**Comment by justincormack** [comment]
That is not a bind mount, which moves existing directories, it is just a normal loopback mount. These are not currently supported directly in `--mount`. They are not supported by the local volume driver either, which can mount devices, I think you need to loopback mount it first.

**Comment by ascora** [comment]
>  I think you need to loopback mount it first.

@justincormack Do you mean mounting it on the host first? But if I see it correctly, then this would be impossible because we use Docker Swarm Mode with 5 nodes and I cannot predict at which node the task will be started. And I can't loopback mount it on all node hosts simultaneously without damaging it...

**Comment by yanislavb** [comment]
I am afraid, but it's impossible.

i am suggest to refuse from img, and use folder as mount folder (with read-only mode)

**Comment by willseward** [comment]
This seems like a job for a custom volume plugin.

**Comment by thaJeztah** [comment]
I briefly discussed with @justincormack and, yes, a custom volume driver plugin is the best solution for this. We discussed an option to extend the `--mount` to support loopback mounts, but there are big security issues in doing so, so not something to be supported by the default driver.

I'll close this issue because of the above, but feel free to comment after I closed
