### ISSUE TITLE
Incorrect message when trying to remove a paused container

### ISSUE THREAD

**Issue by johnma14** [docker/docker#30842]
**Description**

The error message printed when trying to delete a paused container is incorrect/incomplete.

**Steps to reproduce the issue:**
1. create a container
docker create --name tmpredis redis

2. start the container
docker start tmpredis

3. pause the container
docker pause tmpredis

4. remove the container
docker rm tmpredis

**Describe the results you received:**

Error response from demon: You cannot remove a running container <id>. Stop the container before attempting removal or use -f

**Describe the results you expected:**
To remove a paused container, we have to first unpause it then stop it for remove it using -f option. The error message needs to include a statement to unpause the container if it is paused.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
```
Client:
 Version:      1.14.0-dev
 API version:  1.26
 Go version:   go1.7.4
 Git commit:   f018c0d-unsupported
 Built:        Tue Feb  7 19:33:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.14.0-dev
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.4
 Git commit:   f018c0d-unsupported
 Built:        Tue Feb  7 19:33:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.14.0-dev
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 10
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 1137bf2ba633587aa5d8ce41862c3306519f074b
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Debian GNU/Linux 8 (jessie) (containerized)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 5.767 GiB
Name: 3ae83a9d4ce5
ID: PKSO:Y5K3:WFIY:6VCW:5YES:S7Q3:GKL6:RNQI:E66A:FHHH:JKXS:TOKE
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-02-08T20:32:54.747933128Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by johnma14** [comment]
#dibs

**Comment by ripcurld0** [comment]
#dibs

**Comment by ripcurld0** [comment]
@thaJeztah we cam close this ticket

**Comment by thaJeztah** [comment]
ah, yes, closing because https://github.com/docker/docker/issues/30870 was merged, thanks!
