### ISSUE TITLE
doc for deprecated engine features has wrong indentation in side TOC

### ISSUE THREAD

**Issue by gpflaum** [docker/docker#30841]
The TOC on the right side of https://docs.docker.com/engine/deprecated/ has some entries at the wrong indentation. All the entries should have the same indentation.

<img width="233" alt="image" src="https://cloud.githubusercontent.com/assets/11357370/22755255/64201d9a-ee10-11e6-9bfd-4780cff3a403.png">

**Comment by gpflaum** [comment]
I'll make a pull request.

**Comment by thaJeztah** [comment]
Hi @gpflaum I see you made some changes, but haven't seen a pull request; are you still working on this?

**Comment by gpflaum** [comment]
@thaJeztah Thanks for the nudge. I made a pull request.
