### ISSUE TITLE
Upgrading Ubuntu 14.04 LTS to 16.04 LTS breaks bash completion

### ISSUE THREAD

**Issue by albers** [docker/docker#30867]
In the official packages for Docker 1.13.0 and 1.13.1 for Ubuntu 16.04, bash completion was relocated from `/etc/bash_completion.d/docker` to `/usr/share/bash-completion/completions/docker`:

```bash
$ dpkg -c /var/cache/apt/archives/docker-engine_1.12.6-0~ubuntu-trusty_amd64.deb | grep bash.completion
drwxr-xr-x root/root         0 2017-01-10 21:28 ./etc/bash_completion.d/
-rw-r--r-- root/root     59437 2017-01-10 20:36 ./etc/bash_completion.d/docker
$ dpkg -c /var/cache/apt/archives/docker-engine_1.13.0-0~ubuntu-xenial_amd64.deb | grep bash.completion
drwxr-xr-x root/root         0 2017-01-17 11:02 ./usr/share/bash-completion/
drwxr-xr-x root/root         0 2017-01-17 11:02 ./usr/share/bash-completion/completions/
-rw-r--r-- root/root     80611 2017-01-17 10:02 ./usr/share/bash-completion/completions/docker
$ dpkg -c /var/cache/apt/archives/docker-engine_1.13.1-0~ubuntu-xenial_amd64.deb | grep bash.completion
drwxr-xr-x root/root         0 2017-02-08 07:53 ./usr/share/bash-completion/
drwxr-xr-x root/root         0 2017-02-08 07:53 ./usr/share/bash-completion/completions/
-rw-r--r-- root/root     84202 2017-02-08 07:08 ./usr/share/bash-completion/completions/docker
```

The installer does not remove an existing `/etc/bash_completion.d/docker`, though.
This leaves anybody upgrading to 13.x with two competing completion scripts, resulting in an outdated completion.

This is probably true for all Debian-based packages. I only checked the Ubuntu 16.04 packages, see above.

This is a different issue than #30858.

**Comment by albers** [comment]
A quick test for an outdated bash completion is:
- type `docker c`
- type tab key twice

If the list of suggested commands does not contain `container`, your completion is outdated.

The issue can be resolved by deleting the outdated completion file `/etc/bash_completion.d/docker` and logging in again.

**Comment by albers** [comment]
Ah, I got it wrong: I updated both Ubuntu and Docker.

The point is that the Docker installers have different locations the for completion files depending on the Ubuntu version but regardless of Docker version:
```bash
$ for os in trusty xenial ; do
> for docker in 1.12.6 1.13.0 1.13.1 ; do
> printf "%-8s%-8s%s\n" $os $docker $(curl -s https://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_${docker}-0~ubuntu-${os}_amd64.deb | dpkg -c - | grep -o '\..*bash.completion.*/docker')
> done
> done
trusty  1.12.6  ./etc/bash_completion.d/docker
trusty  1.13.0  ./etc/bash_completion.d/docker
trusty  1.13.1  ./etc/bash_completion.d/docker
xenial  1.12.6  ./usr/share/bash-completion/completions/docker
xenial  1.13.0  ./usr/share/bash-completion/completions/docker
xenial  1.13.1  ./usr/share/bash-completion/completions/docker
```

So if you update your Ubuntu from 14.04 to 16.04, you will end up having two conflicting completions files. Resolve by deleting the old one:
```bash
rm /etc/bash_completion.d/docker
```

**Comment by albers** [comment]
I'm closing this because it only affects Users upgrading the OS.
Docker could do something to avoid this situation (checking for existing scripts), but I think this is out of scope.

/cc @thaJeztah

**Comment by thaJeztah** [comment]
Hm, interesting. Yes also don't know what the regular approach for this would be

@ijc25 @tianon any suggestions?

**Comment by ijc25** [comment]
I think `/etc/bash-completion.d/docker` is probably being preserved because it is a [conffile](https://www.debian.org/doc/manuals/maint-guide/dother.en.html#conffiles). This is a class of file handled special by dpkg, most conffile's are configuration files under `/etc`, but not every file under `/etc` is a conffile, since a package maintainer might opt to do something else via the packages maintainer scripts, e.g. debconf, ucf or manual handling

dpkg doesn't delete conffile's since they could container local sysadmin modifications, but this means that the package needs to take manual actual when removing a conffile (whether because it is to be removed or because it is transitioning to another management scheme).

I think the answe would be for the package's postinst script to make a call to [`dpkg-maintscript-helper`](http://man.cx/dpkg-maintscript-helper) with the `rm_conffile` mode to cause the file to be deleted/unregistered as a conffile.

**Comment by tianon** [comment]
@ijc25++; I think `docker/hack/make/.build-deb/docker-engine.maintscript` is probably the easiest way to add that, although if it's not related to the package version, it's a little harder to get right. :disappointed:

It'll have lines like this in it:
```
rm_conffile /etc/bash_completion.d/docker 1.13.0~
```
(the man page @ijc25 linked has more details :+1:)
