### ISSUE TITLE
Is there any way to assign the memory of nvidia gpu?

### ISSUE THREAD

**Issue by Lone5267** [docker/docker#30869]
Is there any way to assign the memory of nvidia gpu?

**Comment by justincormack** [comment]
Hi see https://github.com/docker/docker/issues/23917 for the main issue discussing Nvidia issues.

**Comment by unclejack** [comment]
I'll close this issue in favor of #23917. There's no need to keep multiple issues on the same topic open.

Please continue the discussion on issue #23917.
