### ISSUE TITLE
Error processing tar file(exit status 1): Error making old root private after pivot: permission denied

### ISSUE THREAD

**Issue by jbb100** [docker/docker#30862]
I want to move the image from internet connected PC to offline server in my company.

But I've got an error like below.

I doubt the security tool installed on my company's server named Redcastle.

I think this security tool would block Docker processes. 

How can I solve this problem?

p.s. coworker said Redcastle will block "chroot" command.

**[Executed Command]**
1. Executed on internet connected PC 
docker save -o "aa.tar"

2. Executed on offline Server
 docker load < "aa.tar"

**[Error Message]**
Error processing tar file(exit status 1): Error making old root private after pivot: permission denied

**[docker info]**
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.3
Storage Driver: devicemapper
 Pool Name: docker-253:17-7477521-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 11.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 107.4 GB
 Metadata Space Used: 581.6 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /SAM/DOCKER/devicemapper/devicemapper/data
 Metadata loop file: /SAM/DOCKER/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-10-14)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 28
Total Memory: 94.06 GiB
Name: SLPDLAAL01
ID: NPX4:TQQK:ZIOS:O6MG:BCJC:R5JB:U6BD:YELM:52VJ:Q7O4:GCKH:R2BI
Docker Root Dir: /SAM/DOCKER
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Comment by justincormack** [comment]
It is possible this has changed in Docker 1.13, I do remember there were some changes in `runc` to how the pivot root process worked, but it may not make a difference for this use case.

**Comment by cpuguy83** [comment]
I think this is from https://github.com/docker/docker/blob/master/pkg/chrootarchive/chroot_linux.go#L88

**Comment by jbb100** [comment]
@justincormack Thanks for good information. I'll try to upgrade my docker.

@cpuguy83 Yes. I think so.
But I don't know how can I reproduce this error.
Do you have any idea?

**Comment by cpuguy83** [comment]
@jbb100 `mount --make-rprivate` would be the equivalent.

**Comment by jbb100** [comment]
@justincormack @cpuguy83 Thanks for your answers~

I solved the problem with security solution engineer.

Maybe this security solution assumed "mount" as chroot command.

Thanks again.

Have a good day~

**Comment by rokumar-redknee** [comment]
@jbb100 
I am facing similar kind of permission denied problem, could you please write steps, how did you solve this one.
