### ISSUE TITLE
Docker daemon running, user in docker group, but docker commands can't access daemon 

### ISSUE THREAD

**Issue by avidane1** [docker/docker#30879]
Docker daemon is running yet no docker commands can access it. Restarting doesn't help. User is part of docker group. Sudo/regular user seems to be don't care. See command transcript below. 

-------------------

avidane@abc:~/my_Image$ docker build -t my_image .
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

avidane@abc:~/my_Image$ sudo service docker restart
[sudo] password for avidane: 
docker stop/waiting
docker start/running, process 12925

avidane@abc:~/my_Image$ ps faux | grep docker
avidane  12990  0.0  0.0  17252  2264 pts/10   S+   09:48   0:00              \_ grep docker
root     12925  2.3  0.1 509924 40968 ?        Ssl  09:48   0:00 /usr/bin/docker daemon -g /home/docker --dns 10.4.4.10 --dns 8.8.8.8 --dns 8.8.4.4 --bip 10.10.10.1/24 -H 127.0.0.1:4243

avidane@abc:~/my_Image$ docker build -t my_image .
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

avidane@abc:~/my_Image$ groups | grep docker
domain^users dialout sudo **docker** 

avidane@abc:~/my_Image$ docker -v
Docker version 1.10.3, build 20f81dd

avidane@abc:~/my_Image$ docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

avidane@abc:~/my_Image$ sudo docker info
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

**Comment by AkihiroSuda** [comment]
DOCKER_HOST seems unset?

**Comment by AkihiroSuda** [comment]
Or it would be better to just remove `-H 127.0.0.1:4243` from the configuration

**Comment by cpuguy83** [comment]
Yep, you need to either set `DOCKER_HOST=tcp://127.0.0.1:4243` or use `docker -H tcp://127.0.0.1:4243`

**Comment by cpuguy83** [comment]
Closing for bookkeeping sake, but please feel free to discuss.

**Comment by avidane1** [comment]
Many thanks, adding:

export DOCKER_HOST=tcp://127.0.0.1:4243

Solved the issue. However, trying the other, apparently better, solution of fixing the config file, I couldn't find any config file under /etc/docker/ - where is dockerd taking these parameters from?

**Comment by cpuguy83** [comment]
@avidane1 Depends on what distro you are running under.
Could be in `/etc/default/docker`, or in a systemd unit file.

**Comment by avidane1** [comment]
I'm on Ubuntu:14.04, and /etc/default/docker is the right place. Thanks!
