### ISSUE TITLE
Docker 1.13 - Create / Mount volume with stack and docker-volume-drivers

### ISSUE THREAD

**Issue by CyrilPeponnet** [docker/docker#30895]
**Description**

Is there a known limitation about creating volumes with docker-volume-driver like `netshare`:

```
version: "3"
services:
  test:
    image: busybox
    deploy:
      replicas: 1
    volumes:
      - share:/test
    command: ls /test/ | wc -l


volumes:
  share:
    driver: nfs
    driver_opts:
      share: server:/share
```

I know I can do that for a service with the `--mount` option but I cannot find a way to do the same thing within a stack.

**Steps to reproduce the issue:**
See https://github.com/ContainX/docker-volume-netshare/issues/101

**Describe the results you received:**
VolumeDriver.Mount is not called.

**Describe the results you expected:**
VolumeDriver.Mount should be called.

**Output of `docker version`:**

```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Fri Feb  3 08:23:32 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Fri Feb  3 08:23:32 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 12
 Running: 0
 Paused: 0
 Stopped: 12
Images: 3
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local nfs
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: w9c9xm112phf7c8flofl0xsag
 Is Manager: true
 ClusterID: 68yhc9s8cq8hnmndnio278ly7
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.222.3
 Manager Addresses:
  192.168.222.3:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: N/A (expected: 2f7393a47307a16f8cee44a37b262e8b81021e3e)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.8.17-coreos-r1
Operating System: Container Linux by CoreOS 1313.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.8 MiB
Name: localhost
ID: JLCZ:CKQ6:LQD4:BGIR:RPG4:VPNU:BG6U:4QSZ:3ZI3:GVUT:VP54:AOM6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 31
 Goroutines: 128
 System Time: 2017-02-10T02:46:16.593189182Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

CoreOS Alpha.

**Comment by cpuguy83** [comment]
Yes I think the task is scheduled to any node in the cluster vs the volume create happening on one.
Support for the full mount syntax is still pending.

Presumably here, the `share` volume gets created with the local volume driver when the task lands on the node.

**Comment by CyrilPeponnet** [comment]
Ok, so the only way for me to get it working is to use bind mounting and make sure that the mount points are available on all of my nodes (or use constraints to force the placement).

**Comment by cpuguy83** [comment]
@CyrilPeponnet If you have a multi-host aware volume driver, then it would work as is.

**Comment by cpuguy83** [comment]
Going to close for bookkeeping purposes this since it's not really an issue and is being resolved by #30597. But feel free to continue to discuss!

Thanks!

**Comment by CyrilPeponnet** [comment]
@cpuguy83 Thanks, can you define a multi host aware volume driver? Or point me to one :) nothing fancy I just need to access nfs shared storage. I'll appreciate :)

**Comment by cpuguy83** [comment]
Here's a list to check out: https://docs.docker.com/engine/extend/legacy_plugins/#/volume-plugins

**Comment by thaJeztah** [comment]
You can find a list of plugins here; but keep in mind that those aren't updated yet to the "V2" format (so you cannot `docker plugin install` them) https://docs.docker.com/engine/extend/legacy_plugins/#/volume-plugins

**Comment by thaJeztah** [comment]
oh, sorry, @cpuguy83 beat me to it :D

**Comment by CyrilPeponnet** [comment]
Yeah I know that list the difficulty is to find one that can handle the mount with stacks as for now only the --mount option seems handled by most of them. 

I can still deploy a fake service that will mount it on nodes then refer to this volume as external.

**Comment by CyrilPeponnet** [comment]
Well no luck so far, I was hopping it would work:

```
core@localhost ~ $ docker service create --mode share --name global --mount type=volume,volume-opt=o=addr=10.0.12.4,volume-opt=device=:/nfs_share,volume-opt=type=nfs,source=share,target=/data  --restart-condition none busybox tail -f /dev/null
qj6ig3oiwcpx64r5bw5p9hs8d

core@localhost ~ $ docker service ps global --no-trunc
ID                         NAME                              IMAGE                                                                                   NODE       DESIRED STATE  CURRENT STATE            ERROR                                                                 PORTS
uy0kpvp0m6b061fzj1xb02x8p  share.lqdhl0p5vfrthoa7n6jiezw3n  busybox:latest@sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e  localhost  Shutdown       Rejected 12 seconds ago  "SELinux relabeling of  is not allowed: "no such file or directory""
```

Not sure what I'm missing here.

**Comment by thaJeztah** [comment]
@CyrilPeponnet you'll probably have to either create a _volume_ in advance, or you use `type=bind`

**Comment by cpuguy83** [comment]
That's what the global service is for.

`"SELinux relabeling of  is not allowed: "no such file or directory""` is interesting.
I'm not sure where that's coming from. There also seems to be something missing from the message `relabeling of [] is not allowed`

**Comment by CyrilPeponnet** [comment]
Should I open another ticket for that?

**Comment by cpuguy83** [comment]
@CyrilPeponnet I think this is an issue with trying to apply an selinux label to an nfs mount.
There needs to be support in the nfs server and I think you need to pass an option to the nfs mount call... https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/SELinux_Users_and_Administrators_Guide/sect-Managing_Confined_Services-NFS-Configuration_Examples.html

**Comment by CyrilPeponnet** [comment]
Well it works fine with a docker volume create:

```
core@localhost ~ $ docker volume create --driver local --opt type=nfs --opt o=addr=10.0.10.4,ro --opt device=:/share --name foo
foo

core@localhost ~ $ docker run -i -t -v foo:/test busybox ls /test | wc -l
Unable to find image 'busybox:latest' locally
latest: Pulling from library/busybox
Digest: sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
Status: Downloaded newer image for busybox:latest
17
```

But not while creating a service.

**Comment by cpuguy83** [comment]
You did use different options there.
These are doing the same thing though, one by you and one by the swarm agent on the node the task lands on.

**Comment by CyrilPeponnet** [comment]
I just added more debug in the message above @cpuguy83

**Comment by CyrilPeponnet** [comment]
Not that I have the same issue using a docker-driver-volume (netshare), the volume created by the 

```
docker service create --mode global --name share --mount type=volume,volume-opt=share=10.0.10.4/share,volume-driver=nfs,src=share,dst=/data  --restart-condition none busybox ls /data/
```

```
core@localhost ~ $ docker volume inspect share
[
    {
        "Driver": "nfs",
        "Labels": {},
        "Mountpoint": "/var/lib/docker-volumes/netshare/nfs/share",
        "Name": "share",
        "Options": {
            "share": "10.0.10.4/share"
        },
        "Scope": "local"
    }
]
```

Is readable by a 

```
core@localhost ~ $ docker run -i -t -v share:/test busybox ls /test | wc -l
17
```


but the task still failling with selinux error. Something smells fishy.

**Comment by CyrilPeponnet** [comment]
Even when I try to attach another service to an existing volume it fails:

```
docker service create --mode global --mount type=volume,src=share,dst=/test --restart-condition none busybox ls /test/
```

Same Selinux error.

**Comment by thaJeztah** [comment]
@CyrilPeponnet did you create the volume on every node?

**Comment by CyrilPeponnet** [comment]
@thaJeztah I only have one node for testing...

**Comment by CyrilPeponnet** [comment]
```
core@localhost ~ $ docker node ls
ID                           HOSTNAME   STATUS  AVAILABILITY  MANAGER STATUS
lqdhl0p5vfrthoa7n6jiezw3n *  localhost  Ready   Active        Leader
core@localhost ~ $ docker volume create --driver local --opt type=nfs --opt o=addr=10.0.10.4,ro --opt device=:/share --name foo
foo
core@localhost ~ $ docker inspect foo
[
    {
        "Driver": "local",
        "Labels": {},
        "Mountpoint": "/var/lib/docker/volumes/foo/_data",
        "Name": "foo",
        "Options": {
            "device": ":/share",
            "o": "addr=10.0.10.4,ro"
            "type": "nfs"
        },
        "Scope": "local"
    }
]
core@localhost ~ $ docker run -i -t -v foo:/test busybox ls /test | wc -l
17
core@localhost ~ $ docker service create --replicas 1 --mount type=volume,src=foo,dst=/test --restart-condition none busybox ls /test/
qkgyah73mucz9juptkqxuta9w
core@localhost ~ $ docker service ps qk
ID            NAME               IMAGE           NODE       DESIRED STATE  CURRENT STATE           ERROR                             PORTS
o6s3aw4qtecx  serene_mahavira.1  busybox:latest  localhost  Shutdown       Rejected 7 seconds ago  "SELinux relabeling of  is not…
```

**Comment by CyrilPeponnet** [comment]
I made a test with a bind mount of a nfs folder mounted on the nodes by hand, it works fine for run, services, and stack. So something is definitely wrong with volumes for services and stacks (even if those volumes are working fine with docker run cmd).

**Comment by CyrilPeponnet** [comment]
Actually even with a simple volume I have the issue...

```
core@localhost ~ $ docker volume create  --name foo
foo
core@localhost ~ $ docker run -i -t -v foo:/test busybox ls /test
core@localhost ~ $ docker run -i -t -v foo:/test busybox touch /test/bla
core@localhost ~ $ docker run -i -t -v foo:/test busybox ls /test
bla

core@localhost ~ $ docker service create --replicas 1 --mount type=volume,src=foo,dst=/test --restart-condition none busybox ls /test/
co1m93dlthz2zm5r0mijq097w
core@localhost ~ $ docker service ls
ID            NAME          MODE        REPLICAS  IMAGE
co1m93dlthz2  lucid_newton  replicated  0/1       busybox:latest
core@localhost ~ $ docker service ps co
ID            NAME            IMAGE           NODE       DESIRED STATE  CURRENT STATE           ERROR                             PORTS
xaoibh3k7nem  lucid_newton.1  busybox:latest  localhost  Shutdown       Rejected 7 seconds ago  "SELinux relabeling of  is not…
```

**Comment by CyrilPeponnet** [comment]
So... I made another test with a simple volume with docker 1.13 for mac and it works fine. 

Looks like the 'fishy' thing is in my coreos alpha environment... any pointer will be appreciated.

Thanks.

**Comment by CyrilPeponnet** [comment]
@cpuguy83 I traced the issue back to https://github.com/opencontainers/runc/blob/master/libcontainer/label/label_selinux.go#L144

Where Path is empty at some point. 

Not sure if it's called from https://github.com/docker/docker/blob/5381f9f726e50a392d6623973d232b63290789f9/daemon/volumes.go#L196 or not. 

I'm confused to tell if this issue is runc side, docker side, or coreos side. For sure a path is missing in docker but I don't get how it's possible.

**Comment by thaJeztah** [comment]
Make sure that the correct versions of runc and containerd are installed, see the output of docker info;

```
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: N/A (expected: 2f7393a47307a16f8cee44a37b262e8b81021e3e)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
```

**Comment by CyrilPeponnet** [comment]
@thaJeztah you are right... somehow coreos is using different runc / containerd / init version. After deploying 1.13.1 and replaced coreos binaries with the one from docker it works fine now.

**Comment by CyrilPeponnet** [comment]
Edit in fact it works because it's started without --selinux option as soon as I put it it fails.

**Comment by CyrilPeponnet** [comment]
@thaJeztah @cpuguy83 

If you guys have an idea... selinux is permissive, I tried to run audit in log mode to check denied avc but nothing is logged.

What's puzzle me is that the `path` passed as arg to .Relabel is empty. I cannot find a way to debug this deeper (like a trace mode for tasks for instance).

**Comment by CyrilPeponnet** [comment]
it works fine under docker 1.12.6 with selinux enabled. I can create a volume then refer to it from a service under a swarm mode without issues. Starting 1.13 it's no longer working.

**Comment by cpuguy83** [comment]
I think I've found the issue: see opencontainers/runc#1339

**Comment by cpuguy83** [comment]
Basically in docker we have a check to see if `label.Relabel` returns `ENOTSUP`, but the label package is wrapping the error and messing up our error check.

**Comment by thaJeztah** [comment]
@cpuguy83 is this the issue you were looking into with relabelling?

**Comment by CyrilPeponnet** [comment]
I opened https://github.com/docker/docker/issues/31137 to track this issue.
