### ISSUE TITLE
Do we have an update or management strategy for dependency (demand-based) ?

### ISSUE THREAD

**Issue by xulike666** [docker/docker#30902]
**Description**

I find out some dependencies in this docker repo have been already out of date 
while some of them have been ahead of theirs stable release（may be a potential crisis）. 

**Steps to reproduce the issue:**

Azure/go-ansiterm
Microsoft/hcsshim
Microsoft/go-winio
Sirupsen/logrus
davecgh/go-spew
docker/libtrust
gorilla/context
gorilla/mux
kr/pty
mattn/go-shellwords
tchap/go-patricia
vdemeester/shakers
docker/go-connections
RackSec/srslog
imdario/mergo
docker/libnetwork
docker/go-events
armon/go-radix
armon/go-metrics
hashicorp/go-msgpack
hashicorp/memberlist
hashicorp/go-multierror
hashicorp/serf
docker/libkv
vishvananda/netns
vishvananda/netlink
BurntSushi/toml

**Comment by AkihiroSuda** [comment]
They are managed via https://github.com/LK4D4/vndr

They are just updated on-demand, but I don't see any crisis here.

**Comment by thaJeztah** [comment]
Yes, we vendor dependencies and pin then to a specific tag or commit to make sure builds are reproducible (see https://github.com/docker/docker/blob/master/vendor.conf)

If you see a specific reason to update one of those dependencies (e.g. a security update or a bug that's fixed and affects docker), please open a pull request 

I don't think there's something to be addressed here, so i'll clues this  issue, but feel free to continue the conversation after i closed
