### ISSUE TITLE
when using wget in a dockerfile the /etc/hosts of the server is not used only dns

### ISSUE THREAD

**Issue by esginteg** [docker/docker#30913]
run wget in Dockerfile with host in /etc/hosts and not in dns fail

if i do 

cat Dockerfile
from oraclelinux
RUN yum clean all && yum update -y && yum install -y wget
ADD infloop /usr/local/bin/infloop
RUN wget http://termix:/soft/java/jdk-7u99-linux-x64.rpm
CMD infloop

the build fail
despite host termix is in /etc/hosts and not in corporate dns
and /etc/nsswitch.conf has
hosts:      files dns myhostname

if i do

 cat Dockerfile.ip
from oraclelinux
RUN yum clean all && yum update -y && yum install -y wget
ADD infloop /usr/local/bin/infloop
RUN wget http://12.44.97.33:/soft/java/jdk-7u99-linux-x64.rpm
CMD infloop

it works

**Steps to reproduce the issue:**
see above

**Describe the results you received:**

Step 4/5 : RUN wget http://termix:/soft/java/jdk-7u99-linux-x64.rpm
 ---> Running in f70f8ba313d4
--2017-02-10 12:55:11--  http://termix/soft/java/jdk-7u99-linux-x64.rpm
Resolving termix (termix)... failed: Name or service not known.

**Describe the results you expected:**

build succeeds

**Output of `docker version`:**

docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**Output of `docker info`:**

 docker info
Containers: 14
 Running: 0
 Paused: 0
 Stopped: 14
Images: 108
Server Version: 1.13.1
Storage Driver: btrfs
 Build Version: Btrfs v4.4.1
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: fondation.eservglobal.fr
ID: T62N:NMNV:SXYD:X7EB:YC27:HJIA:UQ3Z:I3EQ:AQAK:DCN2:R5SG:LMLQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

environment:
physical on centos 7.3

**Comment by joequery** [comment]
Are you referring to `/etc/hosts` on the host machine or within the container itself?

**Comment by jmzwcn** [comment]
from oraclelinux
RUN yum clean all && yum update -y && yum install -y wget
ADD infloop /usr/local/bin/infloop
**RUN wget** http://termix:/soft/java/jdk-7u99-linux-x64.rpm //here this cmd will run in **container**
CMD infloop

**Comment by esginteg** [comment]
i am referring to the /etc/hosts on the host machine
 

    Le Vendredi 10 février 2017 15h55, Joseph McCullough <notifications@github.com> a écrit :
 

 Are you referring to /etc/hosts on the host machine or within the container itself?—

**Comment by cpuguy83** [comment]
This is expected behavior
The container gets its own `/etc/hosts`.
See #30383 for adding the `--add-host` functionality from `run` to `build`.

Thanks!

**Comment by esginteg** [comment]
Thank you! 

    Le Lundi 13 février 2017 17h09, Brian Goff <notifications@github.com> a écrit :
 

 Closed #30913.—
