### ISSUE TITLE
Error "invalid tar header" while importing an image saved within a STDOUT stream to a tar file

### ISSUE THREAD

**Issue by chepchepcirkus** [docker/docker#30919]
debian_version 8.7
Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: false

Issue

```
docker save mysql > mysql.tar
docker load < mysql.tar
```
**=> Error processing tar file(exit status 1): archive/tar: invalid tar header**

although this way works

```
docker save --output=mysql.tar mysql
docker load < mysql.tar
```
**=> Loaded image: mysql:latest**

**Comment by yongtang** [comment]
I am not able to reproduce with `1.13.1`. Maybe it is because the mysql image or tar file is generated from earlier versions of docker?

**Comment by thaJeztah** [comment]
Should probably not make a difference. Difference is if the tar is piped or directly written to a file.

I have also not been able to reproduce this issue
