### ISSUE TITLE
3 suggestions for docker volume driver API

### ISSUE THREAD

**Issue by ghostplant** [docker/docker#30928]
1) Volume over Secure NAS/NFS always require either password or SSL keyfile. However, exposing password in volume options is not safe. So it is better to allow volume driver to read from a dynamically updated SSL keyfile / password file, such as: `docker volume create -d abc --opt file=/path/to/key.pem`
Currently, plugin driver is inside a container whose file location is the the location from external (outside docker) host.
The ideal way: `docker run -it --rm --volume-driver xxx --default-opt azure-key=$(pwd)/pub/a.pem ..`

Otherwise, it might as well use nfs mount from local driver as well since all of them are not safe.

2) Volume API should provide default mount approach for those volumes which are not specified from execution command, such as: docker volume create -d xxx --default-opt type=tmpfs,o=ro.
Otherwise, lots of local volumes will be created locally and containers can easily hack the local storage space with `dd` as well as reducing local storage performace. All containers may suffer from disk out of space before it is going to prune.

3) Docker daemon should pass an attribution to plugin-driver API `/Plugin.Create` whose value should be **identical**. It is used for volume driver to mount **anonymous volume** volumes in an **identical** way. Currently, this command always passes a different req.NAME to driver, making drivers unable to reuse a previous volume instance, so the session will be totally erased.

**Comment by fntlnz** [comment]
Hello @ghostplant - thanks for your interesting suggestions. Since those are about three different topics, can you please open three separate issues?
That will allow us to threat them as separate entities and discuss about each one in a more linear way.

I'm closing this but please feel free to open the new ones, I actually have to say something about the 1st for instance
