### ISSUE TITLE
Docker Container Ping works without loss even without network connected

### ISSUE THREAD

**Issue by Shabirmean** [docker/docker#30923]
**Description**

I have a container running in my MacBook Pro (OS Siera 10.12.3) and I tried pinging the google server (8.8.8.8) and the ping works fine with no packet loss. 

Whilst the pinging is still happening I disconnected my machine from the network and still the ping works without any packet loss.

However, when I do a "curl" or apt-get update it fails as expected since there is no network connectivity. 

Also is there any blog or documentation where I can see how internet access is allowed for the **bridge0** network? I don't see **docker0** listed when I do **ifconfig** on my mac and I don't see any interface with the default gateway (172.18.0.1) for the containers. I am trying to understand the internals of how the container is accessing the internet (when the connectivity is enabled of course).

Thank You

**Steps to reproduce the issue:**
1. Start a container
2. Ping some reachable machine or IP from within container
3. Disconnect host machine from the network

**Describe the results you received:**
Ping continues without packet loss

**Describe the results you expected:**
Request timeout

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
wpa046072:~ shabirmean$ docker info
Containers: 3
 Running: 3
 Paused: 0
 Stopped: 0
Images: 3
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: QJU7:MXAI:S5XD:NNWB:DBZ4:2RBH:4ADF:ZCPJ:33HH:AUN5:SBVS:3JBJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 53
 Goroutines: 62
 System Time: 2017-02-10T22:47:55.299061934Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: shabirmean
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by justincormack** [comment]
Hi, this is a Docker for Mac specific issue - I am fairly sure there is already an issue at https://github.com/docker/for-mac/issues but otherwise can you open one, it is a known issue (I thought it had been fixed, sorry). I am going to close here is it is not a generic Docker issue.

**Comment by Shabirmean** [comment]
@justincormack  - Thanks for the response. It's still open under - https://github.com/docker/for-mac/issues/57
Besides, I receive no response for "traceroute" too, with/without the network enabled.
