### ISSUE TITLE
I reload Docker in win10, it's welcome interface and set the interface are white.

### ISSUE THREAD

**Issue by harrydengchao** [docker/docker#30961]
The effect is as follows, is the official website to download the latest stable version：
![image](https://cloud.githubusercontent.com/assets/13941171/22869611/6b3e7b7a-f1db-11e6-8691-675265de936a.png)

However, the service is running normally
PS C:\Users\Administrator> docker -v
Docker version 1.13.1, build 092cba3

Is there any solution?

**Comment by AkihiroSuda** [comment]
Please open an issue at https://github.com/docker/for-win ?

**Comment by harrydengchao** [comment]
@AkihiroSuda OK
