### ISSUE TITLE
Error re: context deadline exceeded when deploying voting app to a swarm

### ISSUE THREAD

**Issue by londoncalling** [docker/docker#30988]
### Description

We've received feedback from users working through the [voting app example in the docs](https://docs.docker.com/engine/getstarted-voting-app/), on the following problem in [deploy step](https://docs.docker.com/engine/getstarted-voting-app/deploy-app/#/deploy-the-app): 

There seems to be a bug regarding the deployment. If you enter all commands and eventually

`docker@manager:~$ docker stack deploy --compose-file docker-stack.yml vote`

it will eventually output

`Error response from daemon: rpc error: code = 4 desc = context deadline exceeded`

### Steps to reproduce the issue:

Walk through the [voting app example](https://docs.docker.com/engine/getstarted-voting-app/) from the docs.

### Expected Results

Expected to not get the error and see the app deployed with output similar to this:

```
docker@manager:~$ docker stack deploy --compose-file docker-stack.yml vote
Creating network vote_default
Creating network vote_backend
Creating network vote_frontend
Creating service vote_result
Creating service vote_worker
Creating service vote_visualizer
Creating service vote_redis
Creating service vote_db
Creating service vote_vote
```

### Related issues

@friism suggested this is Swarm issue.

@ManoMarks and I tested this and could not reproduce it.

See the docs issue [Feedback for: engine/getstarted-voting-app/create-swarm.md ](https://github.com/docker/docker.github.io/issues/1511) for full description of the issue, links to related issues we found, details on environments, and full users feedback.

cc: @mstanleyjones , @johndmulhausen , @nebrass

**Comment by nebrass** [comment]
Bug solved in
```
Version 1.13.1 (15353)
Channel: Stable
```

**Comment by gianarb** [comment]
Hello  @londoncalling can you confirm that you are not using the latest version suggested by @nebrass ? Thanks

**Comment by londoncalling** [comment]
Hi @gianarb I've run through the sample building several times, most recently I believe on on Docker for Windows beta 41, Docker for Windows stable 1.13.1, and same versions on Docker for Mac. I could not replicate the problem.

**Comment by thaJeztah** [comment]
@londoncalling if we're no longer are able to reproduce, should we close this?

**Comment by thaJeztah** [comment]
@gianarb adding some context; @londoncalling is a tech writer in our docs team.

@londoncalling; @gianarb is a Docker Captain, and recently became a curator for the docker/docker repo (helping out with triage, and managing issues, PRs) \o/

**Comment by londoncalling** [comment]
@thaJeztah yes, I'm going to close both issues. If it pops up again we can re-open.
