### ISSUE TITLE
all docker commands hang on Amazon Linux

### ISSUE THREAD

**Issue by rluncasu** [docker/docker#30987]
Hi,

The docker service is running but every docker command I issue hangs (including docker info).
Not much to tell you about how to reproduce it, it worked fine until it stopped working(it was during peak usage, for about 30 mins jenkins, running on that machine kept the cpu at 100%).

I've restarted the docker service, I've uninstalled and reinstalled using yum but to no avail.

cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2016.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.09"
PRETTY_NAME="Amazon Linux AMI 2016.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

**Comment by thaJeztah** [comment]
We currently don't have packages for Amazon Linux, and the version of docker for Amazon Linux is built and shipped by Amazon. Have you tried opening a support ticket with Amazon?

I'm not sure we'd be able to look into this, as there's not a lot of information to go on, and this is not a distro that's currently supported. First thing to look for would be to check the logs for the docker daemon (`dockerd`), and your system log, to see if anything stands out

**Comment by rluncasu** [comment]
I stopped the docker service then ran the dockerd manually. This is what I'm seeing when it tries to start:
```
sudo /usr/bin/dockerd
INFO[0000] libcontainerd: new containerd process, pid: 19351
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
FATA[0000] open /var/run/docker/libcontainerd/containerd/5bb6c06c70e67c1bcc6859f9d901256598bcea45bf56027fce193d7582058917/state.json: no such file or directory
INFO[0006] libcontainerd: new containerd process, pid: 19358
WARN[0000] containerd: low RLIMIT_NOFILE changing to max  current=1024 max=4096
FATA[0000] open /var/run/docker/libcontainerd/containerd/5bb6c06c70e67c1bcc6859f9d901256598bcea45bf56027fce193d7582058917/state.json: no such file or directory
```

**Comment by rluncasu** [comment]
Got it working again by removing everything "docker" in /var/run then reinstalling docker using yum.
Thanks @thaJeztah for pointing me to ```dockerd```.

**Comment by edovale** [comment]
I ran into this same problem and was able to get docker back up by deleting everything under /var/run/docker/libcontainerd/containerd/
I did not have to reinstall docker; after deleting the content of that folder docker would start normally.

**Comment by tslug** [comment]
I get a similar failure:

time="2017-04-20T18:08:50.983757746Z" level=info msg="libcontainerd: new containerd process, pid: 2619"
time="2017-04-20T18:08:52.134255302Z" level=fatal msg="open /var/run/docker/libcontainerd/containerd/c6f915bafa827f6f0086dabcd77e007cdb97afa7c3caa71e6657719101e6d704/state.json: no such file or directory"

Using edovale's solution fixes it, but I could not figure out what is triggering this failure mode in the first place.  All I know is that my server crashed, and on reboot, these files were preventing containerd from starting.

I've analyzed the system logs pretty thoroughly, and the source of the crash is also mysterious.  It just stopped responding after a bit.  The CPU and I/O usage up until then was all very light according to the AWS monitors, but it's on a t2.micro server with only 1Gb of RAM, and I've definitely noticed that it can run out of memory if you're not careful.  Still, no complaints from any services that I could find.

As a workaround, I'm going to add "rm -f /var/run/docker/libcontainerd/containerd/" to the preamble of the dockerd start script for now, but it would be good to know if there's a more permanent fix for this.

**Comment by dmodules** [comment]
the solution of rluncasu worked for me also!

**Comment by yuriipolishchuk** [comment]
Fixed by `rm -rf /var/run/docker` and `yum install docker`
