### ISSUE TITLE
running docker commands in exited container

### ISSUE THREAD

**Issue by joernhees** [docker/docker#30999]
Let's say you want to debug an exited container without actually running its default `CMD`.

Currently, you can achieve this by `docker commit ...` and a subsequent `docker run --entrypoint ...`. While this is possible, it's not the easiest to understand, a lot to type and leaves new images around.

Why not simply allow `docker start --entrypoint ...` or even `docker run --stopped-container=...`?

**Comment by thaJeztah** [comment]
This was discussed on a couple of occasions, but not accepted, you can find some of the discussion on this pull request; https://github.com/docker/docker/pull/19746

I'll have to close this issue because of that, but feel free to continue the conversation
