### ISSUE TITLE
Docker checkpoint command not found

### ISSUE THREAD

**Issue by aarthipa** [docker/docker#30996]
Hi,
Im using Ubuntu 16.04, Docker 1.12 and CRIU 2.10. 
I am able to perform checkpoint/restart with native criu. But I cannot do the same with docker.

root@ubuntu:~# docker checkpoint --help
docker: 'checkpoint' is not a docker command.
See 'docker --help'.

Please find the complete details below.

root@ubuntu:~# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 3
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.35
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.945 GiB
Name: ubuntu
ID: CL5I:NEY7:VCHY:YCX6:4A76:EKYR:2V36:2FLH:OOXA:BFG2:JODH:YGMR
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8

root@ubuntu:~# docker -v
Docker version 1.12.6, build 78d1802, experimental

root@ubuntu:~# criu --version
Version: 2.10
GitID: v2.10-32-g65214e4

root@ubuntu:~# uname -a
Linux ubuntu 4.4.35 #1 SMP Sun Feb 12 22:03:51 PST 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by catinthesky** [comment]
From code level checking,  the "checkpoint" command comes after version v1.13.0.
Also, give command information like applying in which version might helps in this regard, say in page like:
https://docs.docker.com/engine/reference/commandline/checkpoint/.

**Comment by aarthipa** [comment]
Thanks. I was able to upgrade to 1.13. 

Also, I updated the following config file to enable experimental.
/etc/init/docker.conf
exec "$DOCKERD" $DOCKER_OPTS --raw-logs -H fd:// --experimental=true

However I got the following message.
root@ubuntu:~# docker checkpoint
only supported with experimental daemon

Am I missing something?

**Comment by thaJeztah** [comment]
The `/etc/init/docker.conf` file is not used by the official binaries (and not used if your system is using systemd, which includes ubuntu 16.04)

The recommended way to set daemon options is to use a daemon.json configuration file, see https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file

To enable experimental options, create the configuration file /etc/docker/daemon.json, if it doesn't exist, and set the experimental option; if this is the only option you're setting, it should look like this;

```json
{
  "experimental": true
}
```

after saving the file, restart the docker service (`sudo systemctl restart docker`)

**Comment by albers** [comment]
@thaJeztah a bit unrelated, but: If I try to configure `-H` in daemon.json, I get 

> unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: hosts: (from flag: [fd://], from file: [unix:///var/run/docker.sock 10.0.47.11:2376 127.0.0.1:2376])

because /lib/systemd/system/docker.service sets `-H`: `ExecStart=/usr/bin/dockerd -H fd://`

How do I set `-H` in daemon.json?

**Comment by thaJeztah** [comment]
@albers that's a known issue; the `daemon.json` does not allow you to set an option that's already been set as a flag. We're still considering options ("override" when set through `daemon.json`, "merge" options if set on both).

The `fd://` option is used for socket-activation, and can only be set through systemd. For now, the best way to add an additional `-H`, is to use a systemd drop-in file (see https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options), for example;

create a directory for your drop-in files;

```bash
mkdir -p /etc/systemd/system/docker.service.d
```

Create a drop-in file (e.g. ` /etc/systemd/system/docker.service.d/docker-host.conf`);

```
[Service]
ExecStart=
ExecStart=/usr/bin/dockerd -H fd:// -H tcp://10.0.47.11:2376 -H 127.0.0.1:2376
```

Then reload the systemd configuration, and restart docker;

```bash
sudo systemctl daemon-reload
sudo systemctl restart docker
```

All other options can be set through `daemon.json`, because they're not set as a flag.

**Comment by albers** [comment]
@thaJeztah Thanks very much for explaining. I created a PR that adds this information to the `daemon.json` docs.
Should `fd://` be used instead of `unix:///var/run/docker.sock` or is it a different thing (not sure I understand the term "socket-activation" properly)?

**Comment by thaJeztah** [comment]
> Should fd:// be used instead of unix:///var/run/docker.sock or is it a different thing  (not sure I understand the term "socket-activation" properly)?

Socket activation is a systemd feature; it allows you to automatically start the `docker` service (daemon) when you connect to the `/var/run/docker.sock` socket (there's actually a separate service / systemd-unit that handles that, see [`docker.socket`](https://github.com/docker/docker/blob/v1.13.1/contrib/init/systemd/docker.socket)). When connecting to that socket, systemd detects that you're trying to connect, starts the `dockerd` daemon, and forwards the socket to the daemon. The `fd://` socket is the socket connection that's managed by systemd. Given that it's a systemd-specific option, it's not possible to define `fd://` in the `daemon.json`, and that's the reason it has to be added in the systemd unit-file. (hope I have all the terms correct, but that's the general working of the feature)

On distros that use RPM as a package manager there were some differences in the mechanics, and socket activation resulted in the "Live Restore" feature to not work. For that reason, socket activation is not used on those platforms.

**Comment by thaJeztah** [comment]
@aarthipa I think your question should be answered with the comments in this issue, so I'll go ahead and close this issue, but let us know if you still have problems to enable the experimental features.

**Comment by albers** [comment]
Thanks @thaJeztah!

**Comment by aarthipa** [comment]
Thanks @thaJeztah. Its works. The explanations were great.
