### ISSUE TITLE
ENJOYING_THIS_PROJECT="SayThankYou"

### ISSUE THREAD

**Issue by pascalandy** [docker/docker#31008]
Here is the place to say thank you to folks who are working hard on this project.

« One of the greatest ways to show your appreciation to open source projects you enjoy is to open an issue that let people say thank you »

_Disclaimer: I don't have any kind of connexion or personal interest with maintainers(s) of this project. Pure gratitude here._

Cheers!

**Comment by pascalandy** [comment]
Thank you Docker!! Since 1.13 this is a rock solid product
_\m| 💯

**Comment by joequery** [comment]
I could not replicate the issue, as I have no heart. :P

**Comment by thaJeztah** [comment]
:blush: thank _you_ as well for contributing - reporting issues and feature requests is equally, if not more, important!

**Comment by thaJeztah** [comment]
p.s. @joequery 

> as I have no heart. :P

Fixed that for you

![img_0577](https://cloud.githubusercontent.com/assets/1804568/22938016/49efe094-f28f-11e6-88f8-7cef61eba5d1.PNG)

**Comment by nschoe** [comment]
Indeed, that's a great idea @pascalandy .
Thanks docker devs, I always say good things about you in my articles :P

Keep up the work! (I wish I knew Go to be able to submit PRs!)

Thanks again.

**Comment by thaJeztah** [comment]
Thanks everyone! I'll close this issue for house keeping :smile:
