### ISSUE TITLE
Experimental docs are out dated

### ISSUE THREAD

**Issue by tswift242** [docker/docker#31009]
**Description**

The dockerd docs don't mention the new experimental flag and what features that enables (https://docs.docker.com/engine/reference/commandline/dockerd/), and the README in the repo (https://github.com/docker/docker/tree/master/experimental) is missing a lot of the new experimental features added in 1.13, e.g. see https://sreeninet.wordpress.com/2017/01/27/docker-1-13-experimental-features/.

Also, the experimental README  says "Experimental features are not ready for production. They are provided for test and evaluation in your sandbox environments.". That doesn't seem to match what I've heard from maintainers that experimental features are (now) considered behaviorally stable; just the API/CLI might change. E.g. see https://github.com/docker/docker/issues/26451#issuecomment-249294540

**Comment by justincormack** [comment]
cc @mstanleyjones @thaJeztah

**Comment by mstanleyjones** [comment]
Upstream PR in `docker/docker` at https://github.com/docker/docker/pull/31021
