### ISSUE TITLE
Docker image shares same layer can't be saved by two clients simultaneously

### ISSUE THREAD

**Issue by JackyChen255** [docker/docker#31017]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**System and Docker version**
[root@JackDocker ~]# docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

[root@JackDocker ~]# cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)

**Description**

I commit the same container two times to get two new images. The container is created from centos image and don't change any data. Then from two clients, I try to use curl to simultaneously download these two images. But one download fails. The curl output reports "HTTP/1.1 404 Not Found". And in Docker server, it reports. "DEBU[344839] Assembling tar data for 1de19895e0af89cc07c539056172c52b538a5640d985ed81f7f8e067fddbff4f
ERRO[344839] Handler for GET /v1.26/images/get returned error: open /var/lib/docker/devicemapper/mnt/1de19895e0af89cc07c539056172c52b538a5640d985ed81f7f8e067fddbff4f/rootfs/tmp/Ahello.txt: no such file or directory"

**Steps to reproduce the issue:**
1. Commit container twice
[root@JackDocker ~]# docker ps -a
76519999ff47        centos              "/bin/bash"              3 weeks ago         Exited (137) 3 weeks ago                        tiny_shirley
[root@JackDocker ~]# docker commit 76519999ff47
sha256:992afced032709407e57e715ed91d679746741dac9b9ed2e2bf1245027286278
[root@JackDocker ~]# docker commit 76519999ff47
sha256:8f0fc18194beafdf36fef3c90d2d5b9e210d2bbfacea54c607dc2ecc5eaf3bb3

2. Use curl to download these two images simultaneously from two clients. But one download failed with 404 error.
[root@AAA]# curl -XGET -vs 172.24.25.184:4243/v1.26/images/get?names=8f0fc18194be > /tmp/1.tar
* About to connect() to 172.24.25.184 port 4243 (#0)
*   Trying 172.24.25.184...
* Connected to 172.24.25.184 (172.24.25.184) port 4243 (#0)
> GET /v1.26/images/get?names=8f0fc18194be HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.24.25.184:4243
> Accept: */*
>
< HTTP/1.1 200 OK
< Api-Version: 1.26
< Content-Type: application/x-tar
< Docker-Experimental: false
< Server: Docker/1.13.1 (linux)
< Date: Tue, 14 Feb 2017 20:36:02 GMT
< Transfer-Encoding: chunked
<
{ [data not shown]
* Connection #0 to host 172.24.25.184 left intact

[root@BBB tmp]#  curl -XGET -sv 172.24.25.184:4243/v1.26/images/get?names=992afced0327 > /tmp/1.tar
* About to connect() to 172.24.25.184 port 4243 (#0)
*   Trying 172.24.25.184...
* Connected to 172.24.25.184 (172.24.25.184) port 4243 (#0)
> GET /v1.26/images/get?names=992afced0327 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.24.25.184:4243
> Accept: */*
>
**< HTTP/1.1 404 Not Found**
< Api-Version: 1.26
< Content-Type: application/json
< Docker-Experimental: false
< Server: Docker/1.13.1 (linux)
< Date: Tue, 14 Feb 2017 20:36:02 GMT
< Content-Length: 166
<
{ [data not shown]
* Connection #0 to host 172.24.25.184 left intact

**Describe the results you received:**
One image download failed. And when Docker engine runs in debug mode, it shows below error message.

DEBU[344839] CreateV1ID {"container_config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null},"created":"2017-02-14T20:33:55.824777925Z","layer_id":"sha256:ff61b0c09e5485261ce79a87c11accda3b8afc51920837fc1a4924fbcc0a9748","parent":"sha256:ddfde0ce914aebb87ee6a5c4ae346d5aa9a09adaa7bc89bec17f984ed1331c31"}
DEBU[344839] CreateV1ID {"container_config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":null},"created":"2017-02-14T20:33:55.824777925Z","layer_id":"sha256:84536107022ec06d756ab5bbf08e15f2b5fb3864ec6e281e8c2399ddfd7463e6","parent":"sha256:5bbb1c3e2d1803c7109ace24cfaf659acbf89c121899fb5f5d32166852a15359"}
DEBU[344839] CreateV1ID {"architecture":"amd64","config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":{"456/tcp":{}},"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":["/bin/bash"],"Image":"","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{"build-date":"2016-03-31","license":"GPLv2","name":"CentOS Base Image","vendor":"CentOS"},"StopSignal":"SIGTERM"},"container":"76519999ff478131eeb905ffd578603c5e742dbdf380a873e425fca121884e6c","container_config":{"Hostname":"76519999ff47","Domainname":"","User":"","AttachStdin":true,"AttachStdout":true,"AttachStderr":true,"ExposedPorts":{"456/tcp":{}},"Tty":true,"OpenStdin":true,"StdinOnce":true,"Env":null,"Cmd":["/bin/bash"],"Image":"centos","Volumes":null,"WorkingDir":"","Entrypoint":null,"OnBuild":null,"Labels":{"build-date":"2016-03-31","license":"GPLv2","name":"CentOS Base Image","vendor":"CentOS"},"StopSignal":"SIGTERM"},"created":"2017-02-14T20:33:55.824777925Z","docker_version":"1.13.1","layer_id":"sha256:514a2a573af7c5adb3b8afacce69db110a820664f4830f43ee2f4107ecbcf0f3","os":"linux","parent":"sha256:ba66c805459e2e7e9ab1526cb38378e44d2fa8276e005730e1573c6d04d5a6bb"}
DEBU[344839] Assembling tar data for 1de19895e0af89cc07c539056172c52b538a5640d985ed81f7f8e067fddbff4f
**ERRO[344839] Handler for GET /v1.26/images/get returned error: open /var/lib/docker/devicemapper/mnt/1de19895e0af89cc07c539056172c52b538a5640d985ed81f7f8e067fddbff4f/rootfs/tmp/Ahello.txt: no such file or directory**
DEBU[344839] Assembling tar data for 1de19895e0af89cc07c539056172c52b538a5640d985ed81f7f8e067fddbff4f

**Comment by thaJeztah** [comment]
ping @tonistiigi @aaronlehmann

**Comment by JackyChen255** [comment]
Any update? Could you assign this issue to someone please? @thaJeztah @tonistiigi @aaronlehmann

**Comment by tonistiigi** [comment]
I've confirmed this in `overlay2`.

**Comment by tonistiigi** [comment]
Actually only managed to reproduce once, so didn't have a chance to debug this. @JackyChen255 is it flaky for you as well or consistent. Is there a specific timing that would make it easier to show up?

**Comment by JackyChen255** [comment]
@tonistiigi I can easily reproduce it, although can't always reproduce it. Run "docker commit containerID" twice in Docker host to commit two images. Then download these two images from different machines at the same time. One download fails, and the other download suceeds.
1: [root@AAA tmp]# curl -XGET -sv 172.24.25.184:4243/v1.26/images/get?names=992afced0327 > /tmp/1.tar
2: [root@BBB Base]# curl -XGET -vs 172.24.25.184:4243/v1.26/images/get?names=8f0fc18194be > /tmp/1.tar

By the way, here is my docker info. Docker uses devicemapper in my setup.
[root@CCC~]# docker info
Containers: 20
 Running: 0
 Paused: 1
 Stopped: 19
Images: 9
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-253:1-1448245-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.183 GB
 Data Space Total: 107.4 GB
 Data Space Available: 16.78 GB
 Metadata Space Used: 3.015 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2015-12-01)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.703 GiB
Name: JackDocker
ID: 54QB:D3VV:QLKZ:SVLB:GGCM:J7LI:C6O5:BREC:FBBX:V4TO:QSMX:OC63
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 23
 Goroutines: 27
 System Time: 2017-02-13T17:17:44.363485299-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
