### ISSUE TITLE
No license for bsphere/le_go library

### ISSUE THREAD

**Issue by elegantinfrastructure** [docker/docker#31020]
**Description**

There appears to be no license for the logentries log driver vendored as github.com/bsphere/le_go.  I filed a [github issue upstream](https://github.com/bsphere/le_go/issues/14) but have not received a reply yet.

Technically this means you can't distribute this code with Docker, but if upstream responds I'm sure they will assign it a BSD or Apache license and everything will be OK.

**Steps to reproduce the issue:**

n/a

**Describe the results you received:**

n/a

**Describe the results you expected:**

n/a

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

n/a 

**Output of `docker info`:**

n/a

**Additional environment details (AWS, VirtualBox, physical, etc.):**

n/a

**Comment by cpuguy83** [comment]
Thanks for the report.
A license is now added in https://github.com/bsphere/le_go/commit/7a984a84b5492ae539b79b62fb4a10afc63c7bcf
