### ISSUE TITLE
Please support NanoCPUs option in container update API endpoint

### ISSUE THREAD

**Issue by vincentwoo** [docker/docker#31032]
Right now container updating supports setting the `CpuPeriod` and `CpuQuota` options. Since `--cpus`, which sets `NanoCPUs` seems to be the new way to automatically set period and quota on container creation, I think they should be present in update as well!

*opening an issue for this as requested in https://github.com/docker/docker/pull/27958#issuecomment-279928336`*

**Comment by allencloud** [comment]
I found in docker 1.13.1, there is:
```
root@ubuntu:~# docker run --help | grep cpu
      --cpu-count int                         CPU count (Windows only)
      --cpu-percent int                       CPU percent (Windows only)
      --cpu-period int                        Limit CPU CFS (Completely Fair Scheduler) period
      --cpu-quota int                         Limit CPU CFS (Completely Fair Scheduler) quota
      --cpu-rt-period int                     Limit CPU real-time period in microseconds
      --cpu-rt-runtime int                    Limit CPU real-time runtime in microseconds
  -c, --cpu-shares int                        CPU shares (relative weight)
      --cpus decimal                          Number of CPUs (default 0.000)
      --cpuset-cpus string                    CPUs in which to allow execution (0-3, 0,1)
      --cpuset-mems string                    MEMs in which to allow execution (0-3, 0,1)
root@ubuntu:~# docker update --help | grep cpu
      --cpu-period int              Limit CPU CFS (Completely Fair Scheduler) period
      --cpu-quota int               Limit CPU CFS (Completely Fair Scheduler) quota
      --cpu-rt-period int           Limit the CPU real-time period in microseconds
      --cpu-rt-runtime int          Limit the CPU real-time runtime in microseconds
  -c, --cpu-shares int              CPU shares (relative weight)
      --cpuset-cpus string          CPUs in which to allow execution (0-3, 0,1)
      --cpuset-mems string          MEMs in which to allow execution (0-3, 0,1)
root@ubuntu:~#
```

So, there are there flags which are not supported in `docker update` about CPU:
```
--cpu-count int                         CPU count (Windows only)
--cpu-percent int                       CPU percent (Windows only)
--cpus decimal                          Number of CPUs (default 0.000)
```

**Comment by vincentwoo** [comment]
Sorry, I'm talking more about the runtime remote API than about CLI options (though those are important too). Here's the reference for update: https://docs.docker.com/engine/api/v1.26/#operation/ContainerUpdate. The docs there show NanoCPUs as an available option, but it does not appear to do anything when used on docker 1.13.

**Comment by vincentwoo** [comment]
Also, I have to remark (though this is an aside) it seems very strange that on create you pass options like

```javascript
HostConfig: {
  CpuPeriod: whatever
}
```

but on update you simply pass

```json
CpuPeriod: whatever
```

seems weird that cpu resource controls were moved to HostConfig on create but not on update

**Comment by yongtang** [comment]
#dibs  Will take a look at the update of `--cpus`.

**Comment by yongtang** [comment]
@vincentwoo @allencloud Added a PR #31148 to try to address the issue of `docker update --cpus`. Please take a look.
