### ISSUE TITLE
can not find  `--read-only` option for `service create` and `service update` 

### ISSUE THREAD

**Issue by erxian** [docker/docker#31036]
**Description**

Hi, 
     When I  check  `docker service update` command documents , I find the docs introduce an option named `--read-only`. However when I input command  `docker service update --help`, I can not find the `read-only` option. 

Then I check  `service create` document and command,  the mismatches also exits towards `--read-only` option.

So, why `--read-only` option is unavailable in CLI ?

The documents locates in https://github.com/docker/docker/blob/master/docs/reference/commandline/service_update.md 
https://github.com/docker/docker/blob/master/docs/reference/commandline/service_create.md

**Output of `docker version`:**
```Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by AkihiroSuda** [comment]
It is available in master (1.14)
https://github.com/docker/docker/pull/30162
