### ISSUE TITLE
[overlay2] df says there is some space left, but get "No space letf on device" error

### ISSUE THREAD

**Issue by CaoShuFeng** [docker/docker#31038]
**Description**

**Steps to reproduce the issue:**
1. set storage driver to overlay2
/usr/bin/dockerd --storage-driver=overlay2
2. make sure your host have enough free disk space, like 20G.
3. run [this script.](http://paste.openstack.org/show/598987/)

**Describe the results you received:**
1. In my scripts all these small files needs about 4G disk space.
I get "no space left" error even if I have20G free disk space.

2. Also "df" command says I have some space, but I can't save files to disk.
http://paste.openstack.org/show/598989/

**Describe the results you expected:**
1. overlay2 should not take so much disk space.
2. df command should get the right output.

**Output of `docker version`:**

```
Client:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:37:17 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.5
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   7392c3b
 Built:        Fri Dec 16 02:37:17 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 4
Server Version: 1.12.5
Storage Driver: overlay2
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null overlay host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.9.0
Operating System: Fedora 24 (Workstation Edition)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.713 GiB
Name: lvm-1disk
ID: SXQI:44GV:BJHV:YCHT:DKI5:P6KC:MMQL:YBOG:4GY6:7B7I:V2YH:DANJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```
Note that I use linux kernel 4.9.0
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
I guess this is just because no inode space is left (df -i )

**Comment by CaoShuFeng** [comment]
Yes there is no inode left.
But is this normal?

**Comment by CaoShuFeng** [comment]
I get no such error when I use btrfs storage driver.

**Comment by yongtang** [comment]
We use Amazon Linux on AWS and if the EC2 instance is created with the default disk size (8G) then the inode would be full pretty soon. It happens, depending on your disk.

**Comment by CaoShuFeng** [comment]
OK, so I would close this issue.
