### ISSUE TITLE
docker run -v does not recognize absolute path (seems to add leading whitespace)

### ISSUE THREAD

**Issue by leilers** [docker/docker#31045]
**Description**

I am trying to run my docker container with a mounted volume. I used the [jbpm-workbench-showcase](https://hub.docker.com/r/jboss/jbpm-workbench-showcase/)-image and tried using the persistent git-repository as described on it's DockerHub-page. Therefore I used the

`docker run [...] -v /home/***/jbpm-workbench-docker/wb-git:/opt/jboss/wildfly/bin/.niogit [...]` 

command to start my container.

As a result, the docker-daemon complained about being unable to execute the create command, because " /home/***/jbpm-workbench-docker/wb-git" contains invalid characters for a local volume name, even though it is an absolute path on my host system.

**Steps to reproduce the issue:**
1. Pull the [jbpm-workbench-showcase](https://hub.docker.com/r/jboss/jbpm-workbench-showcase/)-container (6.5.0.Final-1)
2. Run the container using `docker run -p 8080:8080 -p 8001:8001 -v /home/***/jbpm-workbench-docker/wb-git:/opt/jboss/wildfly/bin/.niogit -d --name jbpm-workbench jboss/jbpm-workbench-showcase:latest`

**Describe the results you received:**

When running the command shown above, I receive to following error message:

```
docker: Error response from daemon: create  /home/***/jbpm-workbench-docker/wb-git: " /home/***/jbpm-workbench-docker/wb-git" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intented to pass a host directory, use absolute path.
See 'docker run --help'.
json: cannot unmarshal array into Go value of type types.ContainerJSON

```

**Describe the results you expected:**

I expected the container to start up normally and mount the specified folder into the given path of the container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 15
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 5.825 GiB
Name: marl
ID: FAKJ:CSC6:ZI4P:5XKQ:4PJL:K7ZV:7LSZ:NNQ4:7GJQ:W6MN:DI4L:LCUP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker runs directly on an Ubuntu 16.04 host (no additional virtualization)

**Comment by cpuguy83** [comment]
Can you give a simple example, with hopefully without a redacted user name that reproduces this issue?

**Comment by leilers** [comment]
I failed to reproduce the error on a simpler case. It looks like there is another problem in my bash-script which produced the docker run command. Hard coding all the paths on the command-line actually works as expected.

Sorry to bother you.

**Comment by cpuguy83** [comment]
Thanks, do let us know if you can reproduce later!
