### ISSUE TITLE
I am trying to create a base image using "scratch" in redhat linux. This is the instruction that I am using : FROM scratch ADD mkdir dir/repos  and it is throwing this error :  exec: "/bin/sh": stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by Pdharti** [docker/docker#31042]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by cpuguy83** [comment]
Can you please reformat this?
The title should be a brief description and the body should contain what's going on, preferably with the issue template filled out.

This is completely illegible as is.

Closing for now but can re-open when you update.
Thanks!
