### ISSUE TITLE
 exec: "/bin/sh": stat /bin/sh: no such file or directory

### ISSUE THREAD

**Issue by Pdharti** [docker/docker#31044]
Hi I am trying to create a base image using "scratch" in my redhat linux

Following is the instruction file that I am using:
FROM scratch
ADD mkdir dir/repos

cmd: >docker build -t repos

This is throwing this error:
Step 1 : FROM scratch
 --->
Step 2 : RUN mkdir /dir1
 ---> Running in f5a7c25254b8
exec: "/bin/sh": stat /bin/sh: no such file or directory
Container command not found or does not exist.

I also restarted docker daemon.And any of thr forum questionnaire was of no use.
Kindly update me on this

>>Output of `docker version`:<<
Docker version 1.10.3, build 79ebcd8-unsupported

>>Output of `docker info`:<<

Containers: 7
 Running: 0
 Paused: 0
 Stopped: 7
Images: 7
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:0-135927573-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.637 GB
 Data Space Total: 107.4 GB
 Data Space Available: 36.21 GB
 Metadata Space Used: 4.743 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Execution Driver: native-0.2
Logging Driver: journald
Plugins:
 Volume: local
 Network: bridge null host
 Authorization: rhel-push-plugin
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 2
Total Memory: 3.702 GiB
Name: icl-awsec2-vm01.nam.nsroot.net
ID: WT33:WGQ3:RZNA:74EB:X6C5:TLTF:FKHX:TMSP:BE2S:3KIJ:EMDC:DOMR
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Registries: icl-awsec2-vm01.nam.nsroot.net:5000 (insecure), docker.io (secure)

**Comment by cpuguy83** [comment]
`Step 2 : RUN mkdir /dir1`

This looks different than what you specified above as `ADD mkdir dir/repos`. Are you sure it's the same dockerfile? Also seems a bit odd to try to `mkdir` from `ADD`, looks like a mistake.

In addition, the `scratch` image has no tooling at all in it, it's a completely empty filesystem. A tool like `mkdir` would not exist, and likewise using the shell syntax of `RUN mkdir foo` would not work because it tries to run this in `/bin/sh -c <cmd>`, which also does not exist in `scratch`.

**Comment by Pdharti** [comment]
I see, Yes that was a typo. I meant ADD mkdir dir1/repos*

I am beginner in docker, Can you suggest what do I need to do to create a base image just for a testing purpose.

**Comment by cpuguy83** [comment]
@Pdharti First I would start with https://docs.docker.com/engine/reference/builder/

Unless you are going to use a static binary or have some rootfs for the container that you want to use, you don't want `scratch`.
You can start off with something familiar like `debian`, `ubuntu`, or `centos`... or for something more minimal `alpine`, of if you don't need a package manager simply `busybox`.
