### ISSUE TITLE
Docker Windows Container fails to run in priviledged mode

### ISSUE THREAD

**Issue by Xandroid4Net** [docker/docker#31059]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
Use the commands below to provide key information from your environment:
You do NOT have to include this information if this is a FEATURE REQUEST
-->

**Description**

When using docker-compose up with the yml file below, container will run in priviledged mode.

```
version: "2.1"

services:
  web:
    build: .
    command: nodemon -L --debug=5858

    privileged: true
    tty: true
    ports:
      - "3000:3000"
      - "5858:5858"
networks:
  default:
    external:
      name: nat
```

dockerfile for base node image

```
FROM microsoft/windowsservercore

ENV NPM_CONFIG_LOGLEVEL info  

RUN powershell -Command "wget -Uri https://nodejs.org/dist/v6.9.5/node-v6.9.5-x64.msi -OutFile node.msi -UseBasicParsing"

RUN msiexec.exe /q /i node.msi

CMD [ "node" ]  
```

dockerfile for hapi server with serialport

```
FROM node:695

WORKDIR /app

RUN npm install --silent --progress=false -g nodemon@1.10.2

COPY package.json /app/package.json
RUN npm install 


COPY . /app

CMD ["npm.cmd", "start"]
```

Steps to reproduce the behavior

1. docker build -t node . (the first dockerfile from above)
2. docker tag node:latest node:695
3. docker-compose build
4. docker-compose up

**Describe the results you received:**

```
When docker-compose up is run the initialization fails with the following error

PS C:\Users\honeyws\Documents\ComApiNodeWindows> docker-compose up
Removing comapinodewindows_web_1
Recreating f8442170a78f_comapinodewindows_web_1

ERROR: for web  Cannot start service web: container c1e3bd481a189a4f68566e4dd470af1ef385288ec7e831633e39363809358613 enc
ountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x
2) extra info: {"ApplicationName":"","CommandLine":"nodemon -L --debug=5858","User":"","WorkingDirectory":"C:\\app","Env
ironment":{"NPM_CONFIG_LOGLEVEL":"info"},"EmulateConsole":true,"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStd
ErrPipe":false,"ConsoleSize":[0,0]}
ERROR: Encountered errors while bringing up the project.
PS C:\Users\honeyws\Documents\ComApiNodeWindows>
```

**Describe the results you expected:**
 Container should start in priviledged mode

**Additional information you deem important (e.g. issue happens only occasionally):**
Diagnostic id:  ID 097756B2-58F4-436C-901D-FFC79D6EA8B6/2017-02-15_15-24-44

originally reported:
https://github.com/docker/for-win/issues/501

**Output of `docker version`:**
```
PS C:\Users\honeyws\Documents\ComApiNodeWindows> docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 pro

**Comment by jhowardmsft** [comment]
This is fully expected - there is no support for privileged containers on Windows in the platform. The best place to provide this feedback is by adding it to https://windowsserver.uservoice.com/forums/304624-containers/. For that reason, I'm closing this here.

@patricklang FYI.

**Comment by thaJeztah** [comment]
If it's not supported, we should produce a proper error here. I'm reopening

**Comment by gbdadx** [comment]
i use things that make my life better... thank you , but this mess is your problem ...
