### ISSUE TITLE
`docker save` with a windowsservercore image fails on file integrity checksum of Events_Normal.rbs

### ISSUE THREAD

**Issue by mattdanskey** [docker/docker#31053]
**Description**
I've been unable to use `docker save` successfully on an image based on `microsoft/windowsservercore` -- or even been able to save that image itself. I have been able to save `microsoft/nanoservercore` successfully.

I originally filed docker/for-win#499 and was directed to file this issue here. It does have similarities to docker/docker#25893 , but involves a different file.

**Steps to reproduce the issue:**
1. `docker pull microsoft/windowsservercore:10.0.14393.823`
2. `docker save -o repro.tar microsoft/windowsservercore:10.0.14393.823`

**Describe the results you received:**
Attempting to save results in the following message: 
>Error response from daemon: file integrity checksum failed for "Files/ProgramData/Microsoft/Diagnosis/Events_Normal.rbs"

**Describe the results you expected:**
Able to run `docker save` with an image based on `microsoft/windowsservercore`

**Additional information you deem important (e.g. issue happens only occasionally):**
`docker save` for the windowsservercore image worked on a Windows Server 2016 machine running Docker 1.13.1-cs1, build 8709b81

I've tried removing and re-downloading the image, but it seems that a partial image that `docker images -a` does not list is still on my machine, meaning the majority of the image wasn't re-downloaded, as noted below:

> PS C:\> docker pull microsoft/windowsservercore:10.0.14393.823
10.0.14393.823: Pulling from microsoft/windowsservercore
3889bb8d808b: Already exists

I wonder if a fix involves re-downloading that layer that Already exists that I haven't been able to get rid of.

I'll also note here that I started out with an older version of the windowsservercore image that exhibits the same issue.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 1.13.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 5
Total Memory: 9 GiB
Name: win10pro-dev
ID: ANK7:R6E4:IYD5:XU53:JUSF:ZAXE:6RF3:E4PA:2NUS:2EXT:5UGX:HZ7B
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 17
 System Time: 2017-02-15T09:24:20.3689043-08:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running inside of Parallels

**Comment by friism** [comment]
Strictly speaking, I don't think hyper-v is supported when nested inside of another hypervisor like parallels.

**Comment by jhowardmsft** [comment]
.823 was pulled - likely you really do only have half an image. The latest is 10.0.14393.693 as of today (I believe 3B update will be released tomorrow). I've just tried this on .693 successfully. If this repros using .693, please can you re-open. For this reason, I'm closing this issue.
