### ISSUE TITLE
README-short.txt support for automated builds

### ISSUE THREAD

**Issue by wouterds** [docker/docker#31077]
Not really an issue, more of a suggestion / feature request.

It would make sense to support `README-short.txt` for automated builds as well imo.

**Comment by cpuguy83** [comment]
Thanks, I'll pass this along.
Since this is not anything to do with the docker-engine I'm going to close this.

Thanks again.

**Comment by wouterds** [comment]
Couldn't find a place for Docker Hub itself. Thanks in advance @cpuguy83!

**Comment by cpuguy83** [comment]
Indeed.
