### ISSUE TITLE
does anyone know how to use docker secrets through the compose file format ?

### ISSUE THREAD

**Issue by sandys** [docker/docker#31079]
can we use docker secrets through compose file v3 (swarm) ? I cant find anything in the documentation or the code

**Comment by justincormack** [comment]
cc @dnephin @shin-

**Comment by vdemeester** [comment]
@sandys documentation is being updated on that subject : see https://github.com/docker/docker.github.io/pull/1662

**Comment by thaJeztah** [comment]
closing, because docs were updated
