### ISSUE TITLE
Docker engine does not listen on TCP 4789

### ISSUE THREAD

**Issue by demaniak** [docker/docker#31081]
**Description**

Essentially, overlay networking is not working correctly.

After bringing up a stack with `docker stack deploy -c docker-compose.yml my-app`, containers can not access each other. 

When inspecting the (externally created) network with `docker network inspect my-net`, the containers that are listed as attached seems to depend on which node the command is ran.

If app1 is running on node2, then app1 is listed. Running the same check on node3, app1 is NOT listed, but whatever container (of the stack) that happens to be running on node3, IS listed.

No ports are blocked between hosts (verified).

Keeping the [required ports in mind](https://docs.docker.com/engine/swarm/swarm-tutorial/#/open-protocols-and-ports-between-the-hosts) I SUSPECT the problem is that docker engine is not actually listening on TCP port 4789.
 Output from `netstat -tulpn`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::9000                 :::*                    LISTEN      -               
tcp6       0      0 :::2377                 :::*                    LISTEN      -               
tcp6       0      0 :::7946                 :::*                    LISTEN      -               
tcp6       0      0 :::30000                :::*                    LISTEN      -               
tcp6       0      0 :::80                   :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 ::1:6010                :::*                    LISTEN      -               
tcp6       0      0 ::1:6011                :::*                    LISTEN      -               
tcp6       0      0 :::443                  :::*                    LISTEN      -               
tcp6       0      0 :::9092                 :::*                    LISTEN      -               
udp        0      0 0.0.0.0:4789            0.0.0.0:*                           -               
udp        0      0 0.0.0.0:68              0.0.0.0:*                           -               
udp6       0      0 :::7946                 :::*                                - 
```

**Steps to reproduce the issue:**
1. Setup up a docker native swarm cluster
2. create overlay network with `docker network create --opt encrypted --driver overlay my-net`
3. setup a docker-compose.yml (version 3) with services that attached to my-net
2. Deploy a system with `docker deploy stack -c docker.compose.yml my-app`
3. run `docker network inspect my-net`from various hosts in the swarm, confirm attached containers

**Describe the results you received:**
Only the container(s) that is running on the hosts where `docker network inspect my-net` is run is listed as attached to the `my-net` network.
Inter-container communication is not working (app1 can not talk to app2).

**Describe the results you expected:**
ALL containers in the stack should be attached to the `my-net` network, and inter container communication should work.

**Additional information you deem important (e.g. issue happens only occasionally):**
Simple applications (single service) seems to work fine, BUT these were also started up manually with `docker service` commands (NOT the `docker stack deploy -c compose-file` option).

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 4
 Running: 4
 Paused: 0
 Stopped: 0
Images: 21
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 133
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 5dkcgp8wsxwgxpn9vnn8qh1y7
 Is Manager: true
 ClusterID: 66qz3qxb9wwlcvvir7fizp13f
 Managers: 3
 Nodes: 7
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.200.120
 Manager Addresses:
  192.168.200.120:2377
  192.168.200.221:2377
  192.168.220.61:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: SwarmLow-11
ID: S2BB:F2EI:PADF:CX7W:X3Q7:DSUJ:6KMO:FJ3Z:MQKV:MS3X:B6ED:UGQD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
OS Distro:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
Kernel version:
```
4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Swarm info
- 7 nodes
- 2 data centers
- reported situation above is identical on all hosts in the swarm.

**Comment by aboch** [comment]
@demaniak 

> If app1 is running on node2, then app1 is listed. Running the same check on node3, app1 is NOT listed, but whatever container (of the stack) that happens to be running on node3, IS listed.

A network inspect of an overlay network will only show the locally connected containers

> Keeping the required ports in mind I SUSPECT the problem is that docker engine is not actually listening on TCP port 4789.

That is a bug in the documentation. It only needs UDP/4789.

For the connectivity issue,given you are using encrypted networks, make sure the ESP packets traffic is allowed across all of your hosts.

**Comment by demaniak** [comment]
Thanks for the info @aboch .

Hm, the overlay inspection behavior is then definitely NOT what I would have expected. But if that it is how it works currently, at least I can scratch that of the problem/symptom list.

I will verify ESP packet traffic situation, but I have so far been repeatedly assured that any and all traffic is allowed to traverse the network.

**Comment by demaniak** [comment]
Ok, seems the issues as reported (TCP 4789) is a non-issue, I will close this issue for now.

Thanks.

**Comment by aboch** [comment]
To isolate the issue, try to redeploy on a non-encrypted network and see if it works.

If that was the issue, then double check esp packets are allowed or if the --advertise-addr and --listen-addr were properly specified on the nodes (I am suggesting this because it seems your swarm is across datacenters)

**Comment by demaniak** [comment]
Hi @aboch thanks, yes I have done exactly that last night: recreated overlay network without the encryption  option, and lo and behold, things are WORKING.

Also, yes, the swarm is straddling two data centers.

A query about the ESP packets has been raised, waiting for an answer from the hosting provider.

Do you maybe know of some sort of semi-automated docker swarm diagnostic script/container/command that could possible help find networking related issues in a swarm? That I think would be a very handy thing to have...

**Comment by aboch** [comment]
Ok, so if your overlay network is between two datacenters and you properly passed the public IP as ` --advertise-addr` for swarm init and join, then you will be affected by #30727 after the dataplane encryption keys rotate. The fix will be included in next release.

Also, seeing your instance is ubuntu, it may have ufw running and itself block the esp packets. If so, make sure it allows them in and out:

```
sudo ufw allow from any proto esp
sudo ufw allow to any proto esp
```

**Comment by demaniak** [comment]
I spot checked ufw - status is `inactive` on all of them. Which is probably not actually a good idea, but for now at least we can rule that out.

I will have to double check the `--advertise-addr` situation - this swarm was initialize a while ago.

Good news indeed about #30727 then! 
And that seems to explain previous problems I had in this swarm.
