### ISSUE TITLE
Missing stack/compose support for `--endpoint-mode` option when creating a service.

### ISSUE THREAD

**Issue by jlhawn** [docker/docker#31096]
**Description**

I want to use `docker stack deploy ...` to create some services which use the round-robin DNS endpoint mode. It doesn't look like it's possible. The only way to do it is to use `docker service create ...`.

Docker Version: 1.13.1

**Comment by allencloud** [comment]
I searched in the source code, and it is not supported yet.

#dibs

**Comment by dnephin** [comment]
Carried in #31795
