### ISSUE TITLE
Docs: provide `docker stack ps` examples

### ISSUE THREAD

**Issue by anusha-ragunathan** [docker/docker#31133]
`docker stack ps` docs are sparse in examples.
https://github.com/docker/docker/blob/master/docs/reference/commandline/stack_ps.md#examples

It would be good to have concrete examples similar to `docker service ps` and use them in the filtering logic. https://github.com/docker/docker/blob/master/docs/reference/commandline/service_ps.md#examples

**Comment by AnishShah** [comment]
I would like to work on this! #dibs

**Comment by AnishShah** [comment]
#dibs

**Comment by yuexiao-wang** [comment]
@AnishShah Hi, do you fix this issue ?

**Comment by AnishShah** [comment]
@yuexiao-wang go ahead

**Comment by yuexiao-wang** [comment]
Done

**Comment by yuexiao-wang** [comment]
Have created a PR and PTAL

**Comment by yuexiao-wang** [comment]
@anusha-ragunathan PR is merged
