### ISSUE TITLE
Docker + docker-machine + VirtualBox not mounting host files under Linux 4.9

### ISSUE THREAD

**Issue by f1nnix** [docker/docker#31163]
**Description**

I'm trying to mount host folder to docker container under Linux 4.9 Virutalbox 5.1.14, but no files are mounted. The same setup // actions under macOS work fine.

**Versions**

    [user@local test]$ docker --version
    Docker version 1.13.1, build 092cba3727

    [user@local test]$ docker-machine version
    docker-machine version 0.9.0, build HEAD
    
    [user@local test]$ uname -a
    Linux local 4.9.9-1-MANJARO #1 SMP PREEMPT Thu Feb 9 23:12:06 UTC 2017 x86_64 GNU/Linux

VirtualBox Graphical User Interface Version 5.1.14 r112924

**Steps to reproduce the issue:**

    [user@local test]$ docker-machine create --driver=virtualbox m0

    [user@local test]$ docker-machine ls
    NAME   ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
    m0     *        virtualbox   Running   tcp://192.168.99.100:2376           v1.13.1   
    
    [user@local test]$ ls
    dir0  dir1  dir2  dir3  dir4
    
    [user@local test]$ docker run --rm -it -v `pwd`:/data busybox sh
    data/ #

**Describe the results you expected:**

    /data # ls
    dir0  dir1  dir2  dir3  dir4

**Describe the results you received:**

    /data # ls -la
    total 4
    drwxr-xr-x    2 root     root            40 Feb 19 08:26 .
    drwxr-xr-x   20 root     root          4096 Feb 19 08:26 ..

So, no files are mounted inside selected machine => container.

If this bug is related more to machine, than to Docker, feel free to close or move it.

Thanks.

**Comment by f1nnix** [comment]
FYI, I've found a workaround: manually mount desired folders to machine in VM config, and reboot, but that's awkward.

**Comment by justincormack** [comment]
Yes you want to open an issue with machine or virtualbox, this is not an
engine issue.
