### ISSUE TITLE
Error: No such service: ucp-agent

### ISSUE THREAD

**Issue by msavdert** [docker/docker#31168]
**Description**

I am getting the following error while trying to uninstall the docker ucp.

$ docker run --rm -it \
  -v /var/run/docker.sock:/var/run/docker.sock \
  --name ucp \
  docker/ucp uninstall-ucp --interactive

INFO[0000] Your engine version 1.13.1-cs1, build 8709b81 (3.10.0-514.el7.x86_64) is compatible 
INFO[0000] We're about to uninstall from this swarm cluster. UCP ID: 6BID:R7QS:O5OZ:3MX5:3LDN:2UM7:AA4H:UX5G:MJEK:UOHL:V2AV:5LCB 
WARN[0000] WARNING: After uninstalling, you will not be able to join new nodes to the  
WARN[0000] cluster until UCP is reinstalled or all nodes are removed from the current swarm. 
WARN[0000] WARNING: UCP must be reinstalled prior to expiration of your certificates, 
WARN[0000] or the cluster will experience problems.     
Do you want proceed with the uninstall? (y/n): y
FATA[0000] **Error: No such service: ucp-agent**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.1-cs1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:32:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1-cs1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:32:02 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
$ docker info
Containers: 8
 Running: 6
 Paused: 0
 Stopped: 2
Images: 12
Server Version: 1.13.1-cs1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: likikti3440spjnij1stnpppj
 Is Manager: true
 ClusterID: jmga31ro7rf5vz2dm4k2glje1
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.44.44
 Manager Addresses:
  172.31.44.44:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 991.2 MiB
Name: ip-172-31-44-44.eu-west-1.compute.internal
ID: PCWN:OS2N:CFMX:CWZY:ATUN:2CRX:UPRY:VGMW:JR2W:BX4B:WBAZ:NCM2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

I am running ec2 servers on  AWS.

**Comment by duglin** [comment]
@msavdert prior to trying to uninstall, if you do `docker service ls` do you see the `ucp-agent` service running?

**Comment by msavdert** [comment]
@duglin Thanks for the quick response. I found a workaround like this. I removed all ucp containers with docker rm -f . After i had a clean setup as below, it improved.

docker run --rm -it --name ucp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  docker/ucp install \
  --host-address <host-address> \
  --interactive

**Comment by duglin** [comment]
@msavdert hmm ok I guess.  Can we close this issue then?

**Comment by msavdert** [comment]
Yes. Thank you.

**Comment by duglin** [comment]
ok will do - thanks
