### ISSUE TITLE
"docker system prune" doesn't handle "enter" key without a Y or N letter

### ISSUE THREAD

**Issue by tpoindessous** [docker/docker#31187]
**Description**

The `docker system prune` doesn't handle the "enter" key, if I don't type a Y ou N letter first (or any letter).

**Steps to reproduce the issue:**
1. Launch `docker system prune`
2. when "Are you sure you want to continue? [y/N]" line is displayed, type the "enter" key

**Describe the results you received:**

I see a newline and the docker command is still waiting for a key.

**Describe the results you expected:**

I want exiting from the command

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 13
 Running: 12
 Paused: 0
 Stopped: 1
Images: 70
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 73
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 3
Total Memory: 3.855 GiB
Name: moby
ID: Q2V4:ECV7:F3WV:PZFB:WCQ6:G44F:UY5T:SRAG:MYFD:W4IL:TU7X:NXYB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 184
 Goroutines: 174
 System Time: 2017-02-20T15:01:35.772298515Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Username: sk5thomas
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Thanks for reporting! This issue should be fixed in "master", and is scheduled to be reported in an upcoming release (see https://github.com/docker/docker/pull/30769). As a workaround, you can type the `y` or `n` key instead.

**Comment by shakefu** [comment]
This is also happening with `docker image prune` FYI.

**Comment by cpuguy83** [comment]
Closing since this is fixed on master.
