### ISSUE TITLE
Allow wildcards such as *,? for docker exec

### ISSUE THREAD

**Issue by ericcurtin** [docker/docker#31196]
Sometimes I find if I have 10 containers running I find I want to run a command on all containers while they are running. I can achieve this via ansible kinda but it is not ideal. It would be useful if docker supported this.

For example say I have 10 containers running:

docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS              PORTS               NAMES
bc2c540d224b        el632-build         "linux32 init"      About a minute ago   Up 55 seconds                           crash7
1be1d003b13c        el632-build         "linux32 init"      8 minutes ago        Up 8 minutes                            crash6
480dbd255045        el632-build         "linux32 init"      13 minutes ago       Up 13 minutes                           crash5
170431727bf4        el632-build         "linux32 init"      18 minutes ago       Up 18 minutes                           crash4
de9cbc1c1f06        el632-build         "linux32 init"      22 minutes ago       Up 22 minutes                           crash3
68dfa15d4f4e        el632-build         "linux32 init"      27 minutes ago       Up 27 minutes                           crash2
d0cf29ae6228        el632-build         "linux32 init"      31 minutes ago       Up 31 minutes                           crash1
7ba320f34897        el632-build         "linux32 init"      36 minutes ago       Up 36 minutes                           crash0

That I could run:

docker exec -it crash* some command

And it would run on all ten containers. Or say if I had 6 containers named:

crashpro0
crashpro1
crashpro2
crashitg0
crashitg1
crashitg2

and I could run:

docker exec -it crash*0 some command

to run on crashpro0 and crashitg0. Just an idea, I know I would find this quite useful. Maybe this is just me! And if by default it executed this command on a max of 5 containers in parallel by default it would be ideal for my common use case.

**Comment by ericcurtin** [comment]
I use this with ansible to achieve this https://github.com/ericcurtin/d-tools/blob/master/d-dns

**Comment by AkihiroSuda** [comment]
What is the usecase of this?

**Comment by ericcurtin** [comment]
If I have multiple containers running and want to run a command on all of them. I could do something like:

docker exec -it * grep "error" /var/log/someloggingfile

to execute the command on all containers during runtime. I do this kind of thing quite frequently and yes you can easily write scripts to do this kind of thing. But if docker supported this natively that would be really cool!

**Comment by AkihiroSuda** [comment]
I think this usecase should be covered by logging driver.

**Comment by ericcurtin** [comment]
That's just a single example, if I want to run any sort of command on multiple devices this is useful. Say I wanted to change a configuration on all running containers:

docker exec -it * sed -i "s/configurationA/configurationB/g" /etc/conffile.conf

Yeah sure you can build new images, but sometimes you don't want to do this as it is a lot quicker to change the files while the container is running. It may be a temporary change.

I could keep listing scenarios where this is useful, these are just the simple ones off the top of my head!

**Comment by thaJeztah** [comment]
I don't think this is something we'd want to implement. `docker exec` is really implemented as a debugging feature, and not something to use in the main workflow. Containers should be designed to be stateless where possible, and not contain stateful data (including logs). Configuration files can either be bind-mounted in, or part of the image (if it's general configuration).

It should be fairly easy to do this though, with the existing features, e.g.;

```bash
for cid in `docker ps --filter name=c -q`; do docker exec -it "$cid" sh -c 'echo hostname is:; hostname'; done
hostname is:
5af017ecb43c
hostname is:
1b625fb399bb
hostname is:
2abf8854faeb
```

**Comment by thaJeztah** [comment]
Given that there's a feature freeze on `docker exec` (see https://github.com/docker/docker/blob/master/ROADMAP.md#21-docker-exec), I think we should close this

**Comment by ericcurtin** [comment]
Cool with me. Yeah I understand it is fairly easy to script this with existing features, I already do. Just an idea more than anything!

**Comment by thaJeztah** [comment]
No problem, thanks for suggesting the feature! We just need to really outweigh the pros/cons of adding features. There's a saying; _"No is temporary, Yes is forever"_; which basically means that "rejecting" a feature can be reconsidered in future (if there's enough reasons to implement it), but once a feature is "in", we'll have to maintain it forever.

I'll close this issue, but feel free to continue the conversation.

**Comment by ericcurtin** [comment]
This would be useful for docker rm also...

rm startofword* - works
git rm startofword* - works

docker rm startofword* - docker takes this literally (Error response from daemon: No such container: startofword*)

Would be nice if "docker rm" also recognised wildcards like you expect. I'm sure the docker gurus have bigger fish to fry at the minute. Hence the closure of the issue. I'll keep quiet now, just want to keep this here for future reference in case this gets considered sometime.

**Comment by theAkito** [comment]
My use-case is that there are naming conventions with Rancher/Kubernetes, when pods are deployed.
So if I create an nsf-provisioner workload, the container gets called something like 
```
k8s_nfs-provisioner_nfs-provisioner-0_nfs-provisioner_......
```
The point now is, the prefix
```
k8s_nfs-provisioner_
```
will always remain the same.

So now imagine I have an alias like this:
```
alias dc-nfs='docker exec -it k8s_nfs-provisioner* bash '
```
It would always work, no matter what the container's actual name is.
However, in this status quo, I have to fiddle around with choosing the right container name, even though I could save these precious 10 seconds for actually doing something senseful with my Kubernetes cluster, like progressing to add a new feature to it.

**Comment by thaJeztah** [comment]
@theAkito something like this should probably work:


```bash
docker exec -it $(docker ps -aq --filter name=k8s_nfs-provisioner_) bash
```

**Comment by theAkito** [comment]
> 
> 
> @theAkito something like this should probably work:
> 
> ```shell
> docker exec -it $(docker ps -aq --filter name=k8s_nfs-provisioner_) bash
> ```

A pretty hacky way, but seems fine. Thanks for the tip, I'll try it out. 😃

**Comment by thaJeztah** [comment]
> A pretty hacky way, but seems fine. Thanks for the tip, I'll try it out. 😃

You're welcome! Not sure if it's really "hacky"; it's a bit of the [unix philosophy](https://en.wikipedia.org/wiki/Unix_philosophy), where chaining commands is common (just in this case the commands you're chaining happen to be both `docker` commands)

**Comment by ericcurtin** [comment]
Hmm, almost all the Unix tools even in the early days allowed [globbing ](https://en.wikipedia.org/wiki/Glob_(programming)) though ;) So it seems un-Unix like to me

I don't do:

`cat $(ls *.txt)`

to cat all *.txt files in the current directory. I'm sure static analysis tool shellcheck might even recommend against that, you simply do:

`cat *.txt`

**Comment by thaJeztah** [comment]
The tricky bit in this case is that `docker exec` only supports a single container (not multiple) and `--filter` (or globing names) could easily return multiple results, which is what would make the UX confusing at least (e.g. there's also no globbing on `docker run`)
