### ISSUE TITLE
Connecting via hibernate tomcat container to mysql container

### ISSUE THREAD

**Issue by Pierpaolo1992** [docker/docker#31191]
Hi, i've [this](http://stackoverflow.com/questions/42341922/connecting-tomcat-container-to-mysql-container-jdbcconnectionexception-unable?noredirect=1#comment71846423_42341922) problem here, using docker containers on Linux instead of XAMPP on Windows.

My problem is: why, in Linux, there is so lot latency? 

Ps: i've connected also the two containers via a user defined network (`docker network create --driver=bridge mynet`) , then i modified my hibenate.cfg.xml file pointing to localhost:3006/at_db (instead of mysqlphp:3306/at_db) but i have connection refused.

Why is so difficult porting my web-app from windows (xampp) to two separate containers? My teacher said me that probably it's a DNS resolution problem, how what kind of problem and how to solve it?

**Comment by friism** [comment]
@Pierpaolo1992 sorry to hear you're having problems using Docker. This repository is for tracking bugs and issues with the core Docker engine. If you're looking for help using Docker, Stackoverflow or the [Docker Forums](https://forums.docker.com/) are better resources.

**Comment by thaJeztah** [comment]
I'll go ahead and close the issue here; when asking on the forum, make sure to provide more information as well (docker version / docker info, and exact steps to take to reproduce your situation)

**Comment by Pierpaolo1992** [comment]
I'm sorry, but i still have this problem. I think is a DNS resolution problem in Docker using Hibernate. I've wrote on docker forum but no response.

**Comment by orangebook** [comment]
May be you need to see about  windows's host file and edit it
