### ISSUE TITLE
docker 1.13.1 on centos 7.2 bash command completion problem 

### ISSUE THREAD

**Issue by slawekgh** [docker/docker#31214]
after installing 1.13.0 and 1.13.1 bash autocompletion stopped working on centos machines 

upgrade via method:

tee /etc/yum.repos.d/docker.repo <<-'EOF'
[dockerrepo]
name=Docker Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
EOF

yum -y install docker-engine

**Comment by thaJeztah** [comment]
I'm not able to reproduce this on a fresh install.

Was this a new machine, or an upgrade from an older version? Silly question perhaps, but do you have the `bash-completion` package installed on that machine? Also, did you log out / log in again after installing, to be sure the latest completion scripts were loaded?

The completion script can be found in `/usr/share/bash-completion/completions/docker`


/cc @albers

**Comment by slawekgh** [comment]
[root@cent301 ~]# ls -l /usr/share/bash-completion/completions/docker
-rw-r--r--. 1 root root 84202 02-08 01:08 /usr/share/bash-completion/completions/docker

[root@cent301 ~]# cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core)

**Comment by slawekgh** [comment]
it is a little bit old centos machine (and cannot be uograded)

**Comment by albers** [comment]
Does completion work if you manually initialize it with
```bash
source /usr/share/bash-completion/completions/docker
```

**Comment by slawekgh** [comment]
[root@cent301 ~]# source  /usr/share/bash-completion/completions/docker
[root@cent301 ~]# docker p[tab]
-bash: _get_comp_words_by_ref: command not found
-bash: [: 1: unary operator expected
-bash: [: 1: unary operator expected
-bash: [: -eq: unary operator expected
^C

**Comment by albers** [comment]
@slawekgh `_get_comp_words_by_ref` is a function provided by the the _bash-completion_ package.
The error message indicates that this package is either not installed, outdated or not configured for your current shell. Docker's completion has been using this function for ages.

Are you really sure Docker's bash completion worked on this box before you upgraded Docker?

**Comment by slawekgh** [comment]
Thanks for hint with outdated bash-completion :-) 
After removing and reinstalling bash-completion it works fine now 

maybe seems that my previous version of docker (1.12.1) worked fine with old bash-completion but new version (1.13.1) works with new one ?

**Comment by albers** [comment]
@slawekgh Glad to hear the issue is resolved for you.

> maybe seems that my previous version of docker (1.12.1) worked fine with old bash-completion but new version (1.13.1) works with new one ?

I don't think so. There were no fundamental changes in the completion script from 1.12. to 1.13. Both use `_get_comp_words_by_ref`. Maybe you accidentally deactivated bash completion in your login script, and reinstalling made it available again.

**Comment by slawekgh** [comment]
"reinstalling made it available again" - I think that was a reason
