### ISSUE TITLE
Is there a image with virtualgl and turbovnc?

### ISSUE THREAD

**Issue by xiaoxinyi** [docker/docker#31221]
I want to connect the container via `vnc`.  And application in the container both use `Opengl` and GPU. 

- `tightvnc` enable GPU but disable `Opengl`.
-  `tigervnc` enable `Opengl` but disable GPU. 

Google said `virtualgl` and `turbovnc` can solve the problem.

 Up to now, I can't find a built image in dockerhub.

**Comment by cpuguy83** [comment]
Hello,

This is an issue tracker for the docker project.
If you would like to engage with the Docker community please see forums.docker.com or the community slack.

Thanks!
