### ISSUE TITLE
[Feature] Shortcode to remove dangling images

### ISSUE THREAD

**Issue by brunocascio** [docker/docker#31227]
Like `docker volume prune` but for images: `docker images prune`. 

`docker rmi $(docker images -q -f dangling=true)` is too loooong.

**Comment by cpuguy83** [comment]
This already exists, exactly as you have it.

Thanks!

**Comment by thaJeztah** [comment]
It's already there;

    docker image prune

Also, there's 

    docker system prune

Which allows you to remove containers, images, networks and volumes in a single go

**Comment by brunocascio** [comment]
Ohhh, sorry!

Thanks! 💃

**Comment by thaJeztah** [comment]
The confusing bit is `image` vs `images` (plural); the new "per category" commands are all singular, but the `images` command was already there for a long time, so that's kept for backward compatibility.
