### ISSUE TITLE
Dockerfile: FROM image name supports build arg

### ISSUE THREAD

**Issue by hmdhasani** [docker/docker#31225]
I am looking for sth like this:

ARG registry
FROM registry/ubuntu:16.04

**Comment by cpuguy83** [comment]
I don't think it would make sense to use a generic build arg for this.
If we want to parameterize from, then it should be done as a specific case.

**Comment by cpuguy83** [comment]
Also I think likely this is a dup.

**Comment by hmdhasani** [comment]
@cpuguy83 Thank you for your attention buy why you think so? I mean it's just an arg like other args and also adding a special case can make syntax more complex.

another use case is this:

ARG version
FROM ubuntu:$version

**Comment by hmdhasani** [comment]
I searched for a similar issue before creating this but unfortunately I could not found any issue.

**Comment by thaJeztah** [comment]
The original issue was opened before `ARG` was implemented, so that issue proposes using `ENV` for this; https://github.com/docker/docker/issues/18119. Let me rename that issue to mention both `ENV` and `ARG`

**Comment by thaJeztah** [comment]
Let me close this issue to prevent the discussion from diverging, but thanks for opening this feature request. Please subscribe to the linked issue to keep informed on updates. Also feel free to comment here after I closed
