### ISSUE TITLE
Behind corporate proxy and getting error: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host

### ISSUE THREAD

**Issue by youngl98** [docker/docker#31235]
**Description**

Hi,  I see numerous threads regarding people facing the error:
```
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host
```
I am having the same error, but I am behind the corporate proxy.  I haven't found a thread that is particular to my situation...

**Steps to reproduce the issue:**
1. Run docker hello-world
```
$ docker run hello-world                                                   
Unable to find image 'hello-world:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.65.1:53: no such host.
See 'docker run --help'.
```

**Describe the results you received:**

Please see above

**Describe the results you expected:**

I expect hello-world to work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info           
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 11
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: FFOF:TSRB:T5DO:JJRB:LI7P:PONZ:T35S:VORY:MGJG:C5JT:JKYY:BPNI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-02-21T20:05:45.806164214Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 sl55ovnapq01.visa.com
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

I am running Docker for Mac Version on Mac os x `10.11.6` and as stated above behind corporate proxy
```
1.13.1-beta42 (15350)
Channel: beta
2ffb2b4915
```
Here are the proxy settings
```
$ echo $http_proxy              
http://XXXXXXX.visa.com:80

younglee at xxxxxxx in ~ 
$ echo $https_proxy
https://xxxxxx.visa.com:443
```

**Comment by youngl98** [comment]
One more data point

I had to manually configure the http proxy settings from the Preferences -> Proxies -> Manual proxy configuration.  Prior to this, I always had the "Use system proxy" working for me.

After I manually configured the proxy, hello-world works now.

**Comment by thaJeztah** [comment]
> I had to manually configure the http proxy settings from the Preferences -> Proxies -> Manual proxy configuration. Prior to this, I always had the "Use system proxy" working for me.

If this is a regression, can you reopen this in the docker for mac issue tracker? https://github.com/docker/for-mac/issues, the GUI for Docker for Mac is not part of this repository, and issues with that should be reported in that issue tracker.

I'll close the issue here, but feel free to comment after that

**Comment by cvanderhaar** [comment]
Easy solution is to right click on the Whale in the notifications and go to settings and add you proxy there....working
