### ISSUE TITLE
Docker 1.13.1 server fails to start on Oracle Linux 6.7 despite the documentation implying it is supported

### ISSUE THREAD

**Issue by craigbarrau** [docker/docker#31239]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

Docker service fails to start successfully on Oracle Linux 6.6
```
uname -a
Linux oracle.vagrantup.com 3.8.13-98.el6uek.x86_64 #2 SMP Mon Jul 27 10:55:12 PDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
cat /etc/oracle-release 
Oracle Linux Server release 6.7
```

**Steps to reproduce the issue:**

Simplest way to get the exact same VM that I tested with is:
1. Install Vagrant & VirtualBox
2. Install VBox Guest Additions. Simplest way is via`vagrant plugin install vagrant-vbguest`
3. Download Vagrant box from Atlas `vagrant init terrywang/oraclelinux-6-x86_64; vagrant up --provider virtualbox`

Versions of Vagrant / VirtualBox below:

```
vagrant version
Installed Version: 1.9.1
Latest Version: 1.9.1
 
You're running an up-to-date version of Vagrant!
```

```
VBoxManage -v
5.0.32r112930
```

1. Access Oracle Linux 6.7. Machine
2. Run the steps in the documentation at https://docs.docker.com/engine/installation/linux/oracle/ i.e.
```
 sudo yum install -y yum-utils
 sudo yum-config-manager \
    --add-repo \
    https://docs.docker.com/engine/installation/linux/repo_files/oracle/docker-ol6.repo
 sudo yum makecache fast
sudo yum -y install docker-engine
 sudo service docker start
```

**Describe the results you received:**

1. Try to create container `sudo docker run hello-world`
Observe:
```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```
2. Try to restart service `sudo service docker restart`
Observe:
```
Stopping docker:                                           [FAILED]
Starting docker:	.                                  [  OK  ]
```
3. Try to create container again `sudo docker run hello-world`
Observe:
```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

**Describe the results you expected:**

`docker run hello-world` should work successfully

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:39:52 2017
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker info`:**

N/A service is not up...
`docker info` yields this:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Oracle Linux 6.6 on Vagrant + VirtualBox

**Comment by thaJeztah** [comment]
docker requires kernel 3.10 or up, so it's likely you may be running into that.

**Comment by cpuguy83** [comment]
Can you provide the logs from the startup procedure? What happens if you just `sudo dockerd -D`?

**Comment by thaJeztah** [comment]
@cpuguy83 it probably refuses to start, see: https://github.com/docker/docker/pull/22066

**Comment by thaJeztah** [comment]
It's possible to override the check with;

    DOCKER_NOWARN_KERNEL_VERSION=1

but no idea why it would succeed on one VM, and fail on the other

Let me close this issue, but feel free to continue the discussion

**Comment by craigbarrau** [comment]
Thanks @thaJeztah !
