### ISSUE TITLE
Service stuck in "Preparing"  sometimes in swarm mode

### ISSUE THREAD

**Issue by rathir** [docker/docker#31246]
Docker version:

Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:50:17 2017
 OS/Arch:      linux/amd64
 Experimental: false

I could collect following logs by enabling debug for Docker daemon

**Service ps output**
```
ID            NAME       IMAGE                  NODE              DESIRED STATE  CURRENT STATE             ERROR  PORTS
j4cwjt0b7l1y  kafka-2.1  kafka:latest  ucpclus2-ucpnode  Running        Preparing 39 minutes ago         
```

**On  Swarm manager:**
```
time="2017-02-22T03:54:59.555252559Z" level=debug msg="assigning to node vd24jhl2a4lywagr001jth1vt" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.762606539Z" level=debug msg="task status updated" method="(*Dispatcher).processUpdates" module=dispatcher state.transition="ASSIGNED->ACCEPTED" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.873437736Z" level=debug msg="task status updated" method="(*Dispatcher).processUpdates" module=dispatcher state.transition="ACCEPTED->PREPARING" task.id=j4cwjt0b7l1ytvna01lw0l47q 
```

**On Swarm worker:**

```
time="2017-02-22T03:54:59.640074803Z" level=debug msg=assigned module="node/agent" task.desiredstate=RUNNING task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.640380913Z" level=debug msg="state changed" module="node/agent" state.desired=RUNNING state.transition="ASSIGNED->ACCEPTED" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.640590720Z" level=debug msg="state changed" module="node/agent/taskmanager" state.desired=RUNNING state.transition="ASSIGNED->ACCEPTED" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.660242458Z" level=debug msg="(*Agent).UpdateTaskStatus" module="node/agent" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.772181195Z" level=debug msg="(*Agent).UpdateTaskStatus" module="node/agent" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.793039273Z" level=debug msg="state changed" module="node/agent/taskmanager" state.desired=RUNNING state.transition="ACCEPTED->PREPARING" task.id=j4cwjt0b7l1ytvna01lw0l47q 
time="2017-02-22T03:54:59.846289203Z" level=debug msg="(*Agent).UpdateTaskStatus" module="node/agent" task.id=j4cwjt0b7l1ytvna01lw0l47q 
```
Not sure exactly on steps to reproduce this. It seems this happens when bunch of services are started simultaneously.  Looking for ideas on how to debug this further.

**Comment by thaJeztah** [comment]
Have you tried if upgrading to 1.13.1 resolves the issue? Also, can you provide;

- the output of `docker info`
- if possible, the exact steps to reproduce (i.e., is it always with the same service, what options were  used to create the service?)

**Comment by rathir** [comment]
I don't see this issue after upgrading to 1.13.1.  Earlier, I was seeing pretty often.
Tried few times.  Closing the issue.

**Comment by 1605200517** [comment]
Note - I have observed this on a machine with more resources but after 15 minutes all services got running. Maybe if there are not enough resources, there should be a (configurable) timeout for the preparing phase.

**Comment by ryechus** [comment]
I'm having the same problem intermittently. The machine I am using has plenty of resources. Is there anything other than `docker info` that I can use to investigate what's going on?

**Comment by visualex** [comment]
@ryechus same problem in swarm for several years already, 
I have seen a service in swarm take 8h to update, can anyone shed any light on how to inspect what is going on during this time? thanks!!
