### ISSUE TITLE
Provide 1.12.* packages for Fedora 25

### ISSUE THREAD

**Issue by dlespiau** [docker/docker#31256]
The issue is about providing Fedora 25 rpms for docker 1.12.* . The fedora 24 repository have both 1.12.* and 1.13.*, providing the same releases for Fedora 25 should be (hopefully!) straightforward.

It'd be super nice if docker 1.12.* could be available for fedora 25. A lot of projects need a slightly older version of docker at the moment and we can't install those versions from docker managed repositories.

**Steps to reproduce the issue:**
1. Follow the fedora installation document for fedora 25
2. Can't install any of the 1.12.* versions

**Describe the results you received:**

Only 1.13.* is available in https://yum.dockerproject.org/repo/main/fedora/25/Packages

**Describe the results you expected:**

I should be able to install, say 1.12.1, on Fedora 25.

**Comment by cpuguy83** [comment]
Fedora 25 was not available when 1.12 was released. We only add new distro versions at `.0` currently, and 1.12 is no longer supported.

**Comment by dlespiau** [comment]
Ah well, that's a shame, I was hoping to move you enough to start providing those packages on Fedora 25. I guess we can still try to install the binary release (https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz), but it doesn't feel as integrated.

**Comment by cpuguy83** [comment]
Closing since this won't be added to the 1.12 branch, but feel free to discuss.
Thanks!

**Comment by thaJeztah** [comment]
If you're going to run a 1.12.x version, I recommend using 1.12.6, which contains security fixes
