### ISSUE TITLE
SELinux relabeling of NFS volumes is not allowed since 1.12.3

### ISSUE THREAD

**Issue by yimingkuan** [docker/docker#31255]
**Description**

Using a NFS volume with SELinux enabled for Docker can return the following error when starting a container.

**Steps to reproduce the issue:**
1. `docker volume create -d local --name nfstest --opt type=nfs --opt o=addr=x.x.x.x,rw,actimeo=0,sync --opt device=:/nfs/test` 
2. `docker run --rm -ti -v nfstest:/mnt --name test alpine "/bin/sh"`

**Describe the results you received:**
Received the error `docker: Error response from daemon: SELinux relabeling of /var/lib/docker/volumes/footest/_data is not allowed: "operation not supported".`

**Describe the results you expected:**
Successfully runs the container

**Additional information you deem important (e.g. issue happens only occasionally):**
Seems to be caused by https://github.com/docker/docker/pull/23024 - only affects all Docker engines 1.12.4 onwards

Use `nocopy` for the volume as a workaround to this issue.

Error thrown originates from https://github.com/opencontainers/go-selinux/blob/master/label/label_selinux.go#L145

**Additional environment details (AWS, VirtualBox, physical, etc.):**
RHEL 7.3, NetApp NFS storage.

**Comment by cpuguy83** [comment]
I have opened opencontainers/runc#1339 and opencontainers/go-selinux#4 to address this.

**Comment by adityacs** [comment]
I am facing the same issue. What's the workaround for this issue?

Thanks

**Comment by cpuguy83** [comment]
This is fixed in 17.03.0 and 1.13.1

**Comment by adityacs** [comment]
I am using 1.13.1. still facing same issue

**Comment by cpuguy83** [comment]
@adityacs Can you provide the full error?

**Comment by adityacs** [comment]
@cpuguy83 I get below error.

"SELinux relabeling of  is not allowed: "no such file or directory""

**Comment by cpuguy83** [comment]
@adityacs Is that the complete/full error?

**Comment by adityacs** [comment]
@cpuguy83 Yes that is the full error I am getting.
Also, Just to mention. I am using coreos alpha (1339.0.0) version
Hope it's not any coreos-docker issue.

**Comment by cpuguy83** [comment]
@adityacs Surely there must be some extra context there? Even `Error response from daemon:`?

**Comment by cpuguy83** [comment]
Also, can you provide with what volume spec you are hitting this?

**Comment by adityacs** [comment]
@cpuguy83 Volume options 
--mount type=volume,src=test,dst=/data,volume-driver=convoy.

**Comment by adityacs** [comment]
Any update on this?

**Comment by cpuguy83** [comment]
Can you provide the full error context?
I really don't think you are hitting the same issue as I've confirmed this is fixed in 17.03.

**Comment by adityacs** [comment]
I have a swarm cluster and each of the nodes in the cluster is having an NFS mount. I use convoy driver for handling my volumes. Whenever I create a service with below options
`--mount type=volume,src=test,dst=/data,volume-driver=convoy.`

service gets created without any issue. However, when the container fails and the swarm cluster tries to bring the container up on some other node in the cluster I get the below error. 

`SELinux relabeling of is not allowed: "no such file or directory`

**Comment by cpuguy83** [comment]
@adityacs Are you only seeing this in 1.13 or in 1.12 as well?

**Comment by cpuguy83** [comment]
Could very likely be due to https://github.com/docker/docker/blob/master/daemon/volumes.go#L196-L198

I don't think we need to (or should be) relabel here.

**Comment by adityacs** [comment]
@cpuguy83 No, I am not facing this issue in 1.12
