### ISSUE TITLE
docker cp nests directories, instead of merging

### ISSUE THREAD

**Issue by aijanai** [docker/docker#31251]
**Description**

When issuing docker cp twice in the same directory, the effect is that the dir is not copied over the old one, but rather it's nested.

**Steps to reproduce the issue:**
1. `docker cp friendly_shaw:/wanderio/build/client/ client/`
2. `ls client`
```
ai_ja_nai@aiMacBookPro:~/wanderio-devops/aws/elasticbeanstalkStagingCloner-Frontend$ ls client/
fileA fileB
```
3. `docker cp friendly_shaw:/wanderio/build/client/ client/` (repeact exactly previous command)
4. `ls client`
```
ai_ja_nai@aiMacBookPro:~/wanderio-devops/aws/elasticbeanstalkStagingCloner-Frontend$ ls client/
fileA fileB client
```
**Describe the results you received:**
Now the dir client has been included in the one previously copied

**Describe the results you expected:**
I expected the dir client was just merged (existing files overwritten and new ones added). Particularly, I expected that trailing slashes were honored.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 2
 Running: 0
 Paused: 0
 Stopped: 2
Images: 68
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 154
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.707 GiB
Name: aiMacBookPro
ID: BEFQ:LYRP:E22V:X3WB:5EMX:34AB:OPFP:7ITH:YAPQ:KGQD:I5RM:ORLT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It happens both on AWS and on my laptop.

Thanks

**Comment by thaJeztah** [comment]
I think this is the expected behavior, but it can be tricky to get it right, see: https://github.com/docker/docker/blob/52df69f00d966904ba230dc2e3a0646cc52b7688/docs/reference/commandline/cp.md;

Assuming a path separator of `/`, a first argument of `SRC_PATH` and second
argument of `DEST_PATH`, the behavior is as follows:

- `SRC_PATH` specifies a file
    - `DEST_PATH` does not exist
        - the file is saved to a file created at `DEST_PATH`
    - `DEST_PATH` does not exist and ends with `/`
        - Error condition: the destination directory must exist.
    - `DEST_PATH` exists and is a file
        - the destination is overwritten with the source file's contents
    - `DEST_PATH` exists and is a directory
        - the file is copied into this directory using the basename from
          `SRC_PATH`
- `SRC_PATH` specifies a directory
    - `DEST_PATH` does not exist
        - `DEST_PATH` is created as a directory and the *contents* of the source
           directory are copied into this directory
    - `DEST_PATH` exists and is a file
        - Error condition: cannot copy a directory to a file
    - `DEST_PATH` exists and is a directory
        - `SRC_PATH` does not end with `/.` (that is: _slash_ followed by _dot_)
            - the source directory is copied into this directory
        - `SRC_PATH` does end with `/.` (that is: _slash_ followed by _dot_)
            - the *content* of the source directory is copied into this
              directory


In your case

- `DEST_PATH` exists, and is a directory
- `SRC_PATH` does not end with `/.`  (_slash_ followed by _dot_)

So, the source directory is copied into this directory

From the description, changing this to 

```
docker cp friendly_shaw:/wanderio/build/client/. client/
```

Should probably give the expected result, but let me know if that doesn't resolve the issue

**Comment by aijanai** [comment]
First of all, thanks for the prompt support.

It works.
My mistake was not consulting the manpage, where I would have found all the above, but just the --help section of the command.
Closing.

**Comment by thaJeztah** [comment]
Good to hear it worked!
