### ISSUE TITLE
docker image search missing?

### ISSUE THREAD

**Issue by ronaldpetty** [docker/docker#31269]
In Docker 1.13 I do not see a normalized image search subcommand.  Not sure if this is a feature request, oversight, or as planned. 

1.  docker image search ubuntu

I see the help menu.

I expect the search results.

```
user@ubuntu:~$ sudo docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by thaJeztah** [comment]
Yes, the reason it's not normalized under images is that it's basically searching in a _registry_ for images, not in the local images; there was discussion if a `docker registry search` command would make sense, but that was not yet agreed on. For that reason it was decided to stick with `docker search` for now

**Comment by ronaldpetty** [comment]
Thank you for that.  I think a registry command would make sense to go with login/logout, etc.  But can live with the current state of the world.

**Comment by thaJeztah** [comment]
Thanks for reporting!
