### ISSUE TITLE
Feature request: multiple compose files in docker stack deploy

### ISSUE THREAD

**Issue by andrewmilson** [docker/docker#31267]
Would be nice to specify multiple docker compose files in a docker stack deploy. https://docs.docker.com/compose/production/#/modify-your-compose-file-for-production.

docker stack deploy -c docker-compose.yml -c production.yml newdeployment

**Comment by vingrad** [comment]
+1

**Comment by yongtang** [comment]
I think this issue might be a duplicate of #30504?

**Comment by thaJeztah** [comment]
Yes this looks like a duplicate. let me close this one

**Comment by thanhson1085** [comment]
+1
