### ISSUE TITLE
Swarm ignores "containerslots" label (Docker 1.13.x)

### ISSUE THREAD

**Issue by destebanm** [docker/docker#31284]
**Description**

We are using swarm standalone 1.12.6 and we have just updated docker daemon to 1.13.x

We are using "containerslots" label to limit the number of containers in one node. With docker daemon 1.12.x works fine (when the limit is reached a msg "Unable to find a node that satisfies the following conditions [available container slots] " is received). Nevertheless, after update Docker to 1.13, "containerslots" label seems to be ignored.

**docker info**
Containers: 4
Running: 4
Paused: 0
Stopped: 0
Images: 53
Server Version: 1.13.1
Storage Driver: aufs
Root Dir: /var/lib/docker/aufs
Backing Filesystem: extfs
Dirs: 73
Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
Volume: local
Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
apparmor
seccomp
Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 36
Total Memory: 58.97 GiB
Name: bb-webinarjam53-ip-10-0-42-224
ID: VR3B:TMJE:SUBG:JVB2:6NE2:74EX:HIZW:A6HK:QCSH:KS3X:TZVS:CIC3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
containerslots=2
Experimental: false
Insecure Registries:
127.0.0.0/8
Live Restore Enabled: false

**docker ps**
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
c3db8713764d backend-browser "/bin/sh -c /usr/b..." 3 minutes ago Up 3 minutes 0.0.0.0:25058->5900/tcp backend-browser4886747431306996294
688f5030c2d5 backend-browser "/bin/sh -c /usr/b..." 3 minutes ago Up 3 minutes 0.0.0.0:25057->5900/tcp backend-browser4093339620984908265
2cf0dd396a0f backend-browser "/bin/sh -c /usr/b..." 4 minutes ago Up 4 minutes 0.0.0.0:25056->5900/tcp backend-browser9210555932067756117
8a2a15f562cf swarm "/swarm --log-leve..." 12 minutes ago Up 12 minutes 2375/tcp wizardly_bell

**Comment by destebanm** [comment]
The problem was that we were running the swarm container with --filter=health explicitly:
docker run -d -p 4000:4000 swarm --log-level debug manage --filter=health --strategy binpack -H :4000 --replication --advertise $local_ip:4000 consul://$CONSUL:8500

Doing that, we were losing the other default filters (containerslots,port,etc )

It was not related with docker version

**Comment by zhouchengcom** [comment]
I encountered the same problem， then  rollback to the old version

**Comment by thaJeztah** [comment]
@zhouchengcom if you suspect there's a bug in "standalone swarm", please open an issue in the Swarm issue tracker; https://github.com/docker/swarm/issues
