### ISSUE TITLE
Docker Snap not working correctly

### ISSUE THREAD

**Issue by frimdo** [docker/docker#31299]
**Description**
Docker snap installed in fresh UbuntuCore runnin in qemu-kvm

**Steps to reproduce the issue:**
1. Run clean ubuntu-core-16-amd64.img in qemu-kvm using `qemu-system-x86_64  -m 512 -net user,hostfwd=tcp::10022-:22 -net nic  ubuntu-core-16-amd64.img` command
2. Ssh into it
3. install docker using `snap install docker`
4. run hello world image `sudo docker run hello-world`

**Describe the results you received:**
```
$ sudo docker run hello-world                      
docker: Error response from daemon: Container command '/hello' could not be invoked..
```

**Describe the results you expected:**
```
$ sudo docker run hello-world

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker ID:
 https://cloud.docker.com/

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

**Output of `docker version`:**
```
$ sudo docker --version
Docker version 1.11.2, build v1.11.2-snap-38fd0d3
```

**Output of `docker info`:**

```
$ sudo docker info                 
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 14
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: null host bridge
Kernel Version: 4.4.0-45-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.4 MiB
Name: localhost.localdomain
ID: 7KSM:RQ6A:VDIS:QALK:PSO2:ISXI:WT2Q:ZMXW:TYFR:T7RJ:4A7H:DYCJ
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-02-23T18:42:34.012186269Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```
**Additional informations**
bug is reported on [launchpad.net](https://bugs.launchpad.net/snappy/+bug/1667408) too.
**Additional environment details (AWS, VirtualBox, physical, etc.):**
Fresh UbuntuCore runnin in qemu-kvm

**Comment by cpuguy83** [comment]
Thanks, this package is provided by Canonical and should be addressed there.

**Comment by cpuguy83** [comment]
Closing since this is not really something we can address here.

Feel free to discuss. Happy to help track down what may be causing it.
Daemon logs during this time would be really helpful.

**Comment by frimdo** [comment]
Posted it here, because guys on #snappy IRC told me the snap package is yours.

**Comment by cpuguy83** [comment]
It is most definitely not.
The only packages we provide are in https://github.com/docker/docker/tree/master/contrib/builder
And we don't even build them all.
