### ISSUE TITLE
v17.03.0-ce-rc1

### ISSUE THREAD

**Issue by ambrons** [docker/docker#31294]
Received an update for docker for mac listed as `v17.03.0-ce-rc1` which is a huge leap from `1.13.1`.  There's no mention of a reversioning of the project on the changelog:

https://github.com/docker/docker/releases

is this a goof?
![screen shot 2017-02-23 at 9 52 28 am](https://cloud.githubusercontent.com/assets/1403700/23263996/dc804366-f9ad-11e6-9df7-0a0af1ccf78f.png)
![screen shot 2017-02-23 at 8 54 10 am](https://cloud.githubusercontent.com/assets/1403700/23263995/dc7fcdaa-f9ad-11e6-8cd1-a9999ffddc8f.png)

**Comment by friism** [comment]
This is because you're on Docker for Mac beta channel which gets you release clients of Docker. You can read more about the versioning update here: https://github.com/docker/docker/pull/31075

**Comment by ambrons** [comment]
@friism thanks for the update.  Yeah I'm on the beta channel I love to play with all the new toys.

I think the miss for me is I'd have included the #31075 in the changelog for the pre-release.  I would have never opened the ticket had it made mention in some way ;-)
