### ISSUE TITLE
Is it possible to inspect training progress with Docker?

### ISSUE THREAD

**Issue by zhenyulin** [docker/docker#31300]
I'm currently using docker/nvidia-docker to run Deep Learning stacks.

I'm currently running the training with `docker exec -it <container_name> bash` to enter the container and use `Ctrl+P` then `Ctrl+Q` to escape from the container after starting the training script.

Using `docker logs <container_name>` will only show the logs when the training is finished, whereas I haven't been able to track the training progress, so that I can planning other tasks on the machine.

Was wondering if there's way to inspect training progress with docker?

**Comment by nathanleclaire** [comment]
This seems more of a nvidia-docker question. cc @thaJeztah to close?

**Comment by thaJeztah** [comment]
Yes, can you ask this question at https://github.com/NVIDIA/nvidia-docker ?

**Comment by zhenyulin** [comment]
Have done. Thanks!
