### ISSUE TITLE
Add load balancing options to docker stack deploy

### ISSUE THREAD

**Issue by ahromis** [docker/docker#31309]
**Description**

Currently all services created with the latest compose format default to VIP load balancing mode. Is there plans to add support to `docker stack deploy` for that to be configurable?

Right now the only way to change to round-robin mode is to update the service after it's been created with `docker stack deploy`.

**Comment by vdemeester** [comment]
I think there is already a PR for supporting that : https://github.com/docker/docker/pull/31112

**Comment by ahromis** [comment]
Cool, looks like that will probably be merged in sometime soon then. I'll go ahead and close this issue. Thanks.
