### ISSUE TITLE
network error

### ISSUE THREAD

**Issue by timchenxiaoyu** [docker/docker#31317]
create swarm service 
the container eth has two ip

126: eth2@if127: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1450 qdisc noqueue 
    link/ether 02:42:0a:00:00:0d brd ff:ff:ff:ff:ff:ff
    inet 10.0.0.13/24 scope global eth2
       valid_lft forever preferred_lft forever
    inet 10.0.0.12/32 scope global eth2
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe00:d/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by aboch** [comment]
This is by design.
One is the Virtual IP of the service, the other the IP of the task.
