### ISSUE TITLE
docker kill doesn't work with signals that have 'Core' dispositions

### ISSUE THREAD

**Issue by bushkov** [docker/docker#31338]
I want to send a signal which would terminate the main process inside a container and produce a core dump. However, it seems that _docker kill_ command doesn't work when it's --signal option is set to signal which have 'Core' disposition - the main process is not terminated. It does work correctly with signals that have 'Term' disposition though.

1. Start a container with the following command: _docker run --name container_name image_name app_name_
2. Send a 'Core' signal (e.g. SIGSEGV) to the main process inside the container with the following command: _docker kill --signal="SIGSEGV" container_name_
3. Check the status of the container with: _docker ps_

**Describe the results you received:**

_docker ps_ gives the _STATUS_ of the container as _Up_

**Describe the results you expected:**

_docker ps_ should give the _STATUS_ of the container as _Exited_ and a core dump should be generated (provided /proc/sys/kernel/core_pattern is configured properly)

**Output of `docker version`:**

Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64

**Output of `docker info`:**

Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: docker-8:3-138212-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 449.4 MB
 Data Space Total: 107.4 GB
 Data Space Available: 3.248 GB
 Metadata Space Used: 1.081 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.146 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-09-28)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp
Kernel Version: 3.10.0-327.22.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 1
Total Memory: 3.703 GiB
Name: host
ID: OKKN:WOBF:UK7L:UCI5:SLTC:6ZRB:6QCG:AEVA:WXUB:FIKL:5NAP:QRCT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

**Comment by thaJeztah** [comment]
Processes usually act different if they're running as PID1, including ignoring certain signals. Could that be the issue here?

/cc @cpuguy83

**Comment by cpuguy83** [comment]
Yep, try this one-liner:

```
docker run -d --name test busybox sh -c "n=0; trap 'echo got SIGSEGV but not gonna do anything' SIGSEGV; while true; do echo sleeping; sleep 3; done"
```

Then you can check `docker logs` after sending the sigsegv

**Comment by bushkov** [comment]
@cpuguy83 Thanks. After trying this small test I got 'trap: SIGSEGV: bad trap' in the logs.

**Comment by cpuguy83** [comment]
@bushkov So it looks like this is working as expected?
As @thaJeztah mentioned, a lot of programs will drop default signal handlers when run as pid 1.
One thing you could do if you don't want to add your own signal handlers, use the `--init` with `docker run`.

**Comment by bushkov** [comment]
Yes, it seems the issue stems from the fact that the main program is run as PID 1.
