### ISSUE TITLE
PORT of a service not mapped, when curl is used from another service 

### ISSUE THREAD

**Issue by navinSing** [docker/docker#31336]
**Description**

PORT of a service not mapped, when curl is used from another service 

**Steps to reproduce the issue:**
1. create a service "abc_service" binds on port  : -p 5555:80 
        // check IP ..    docker exec -it abc_service.1... ifconfig
2. curl -X GET http://localhost:5555/abc  
WORKS 

3. from another helloworld service, with curl installed; 

```
$ docker exec -it helloworld.1... ash 
$ ping 10.255.0.10 
    64 bytes from 10.255.0.8: seq=1 ttl=64 time=0.084 ms

$ curl -X GET http://10.255.0.10/abc 
//  DOESN'T work
also 
 curl -X GET http://abc_service/abc 
//  DOESN'T work
```

**Describe the results you received:**
curl from one container of service was unable to use the internal exposed port  

**Describe the results you expected:**
internal exposed ports should be available to other containers in the swarm 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 1.13.1, build 092cba3

```

**Output of `docker info`:**

```
Containers: 138
 Running: 7
 Paused: 0
 Stopped: 131
Images: 777
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1371
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: q5yltcriyuvoaadd5tkjw2u3v
 Is Manager: true
 ClusterID: pdbyrgob4yig285l6bxtatnb0
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.42.71
 Manager Addresses:
  192.168.42.71:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.19.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.68 GiB
Name: moch
ID: AMOH:WNGZ:LIJU:3PL2:XLRY:SH6V:3LHT:JVWG:3H7R:VFD6:BF7X:POR5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by thaJeztah** [comment]
Can you;

- show the _exact_ steps to reproduce?
  - what options are used to create the service
  - are both services on the same network?
- do you have any daemon options set (e.g. `--iptables=false`?)

**Comment by navinSing** [comment]
what options are used to create the services
docker service create -p 5555:80 -- name abc_service nodeexample:latest
/src/start.js

both services on the same network?
Yes

do you have any daemon options set (e.g. --iptables=false?)
No

Regards,
Shravan

Can you;

   - show the *exact* steps to reproduce?
      - what options are used to create the service
      - are both services on the same network?
   - do you have any daemon options set (e.g. --iptables=false?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/docker/docker/issues/31336#issuecomment-282314694>, or mute
the thread

**Comment by titpetric** [comment]
I'm having similar issues with docker swarm in 1.13. The -p 80:80 switch works as expected, but as soon as I issue `docker service update --no-healthcheck [service]`, docker stops listening on port 80. My workaround was to run `docker service update --health-cmd "exit 0" --health-interval 30s [service]` - in this case the service would stay online and reachable. Will gladly run some tests if you'd like.

**Comment by titpetric** [comment]
Steps to reproduce from a clean 3 node swarm cluster (all managers):

```
root@swarm1:~# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
2jrjw0f0t6k2hbf2w0d41db2x *  swarm1    Ready   Active        Reachable
aet822iruebj35gu4vlkn70bb    swarm3    Ready   Active        Leader
l4bdxu989ktteb61cte66dqbc    swarm2    Ready   Active        Reachable
```

I created a `party-swarm` network like this:

```
docker network create \
  --driver overlay \
  --subnet 10.0.0.0/20 \
  --attachable \
  party-swarm
```

I need a simple redis service for the example app:

```
docker service create --replicas 1 --network party-swarm --hostname redis --name redis -p 6379:6379 redis:3.2-alpine
```

And then I create the app like this:

```
docker service create -e PORT=80 \
 --replicas 10 \
 --network party-swarm \
 --name gotwitter \
 -p 80:80 titpetric/gotwitter
```

At this point the service is reachable on port 80 on all nodes.

```
docker service update --no-healthcheck [service]
```

At this point, dockerd doesn't listen on port 80 anymore.

**Comment by thaJeztah** [comment]
@titpetric can you please open a separate issue? Looks something different

**Comment by titpetric** [comment]
@thaJeztah ok, thanks, will do.

**Comment by thaJeztah** [comment]
> what options are used to create the services
> docker service create -p 5555:80 -- name abc_service nodeexample:latest /src/start.js
> 
> both services on the same network?
> Yes

@navinSing it looks like you create a service without attaching it to a network. Services won't be able to communicate with each other if they're not on the same network, e.g.;


```
docker network create -d overlay my-net

docker service create --name foo --network=my-net nginx:alpine

docker service create --name bar --network=my-net alpine ping foo
```

If you have "experimental" features enabled, you can then use `docker service logs -f` to see if the connection succeeds;

```
docker service logs bar -f                                                                                                                                                          bar.1.tdr605im2r4t@moby    | PING google.com (216.58.212.142): 56 data bytes
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=0 ttl=37 time=0.226 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=1 ttl=37 time=0.263 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=2 ttl=37 time=0.258 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=3 ttl=37 time=0.256 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=4 ttl=37 time=0.249 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=5 ttl=37 time=0.282 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=6 ttl=37 time=0.261 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=7 ttl=37 time=0.278 ms
bar.1.tdr605im2r4t@moby    | 64 bytes from 216.58.212.142: seq=8 ttl=37 time=0.282 ms
```

**Comment by navinSing** [comment]
@thaJeztah 
thanks, yes missed  --network=my-net 
earlier < 1.12 on a single host it was only working without  --network=my-net and failed if we added  --network=my-net 

Thanks
