### ISSUE TITLE
Directory trees of host volumes do not sync correctly inside and outside containers if mounting other file systems after container started

### ISSUE THREAD

**Issue by mgtsai** [docker/docker#31344]
**Description**

**Steps to reproduce the issue:**
1. Create and start a container with a host volume, i.e. `docker run -ti -v /mnt:/testmnt debian:8.4`
2. Create an sub-directory under host volume path outside container, i.e. `mkdir /mnt/usb`
3. Mount another file system under the descendant of the host volume path outside container, i.e. `mount /dev/sdc1 /mnt/usb`

**Describe the results you received:**
Inside the container, the volume directory tree contains only the empty mount point, without any content

```
root@5f442fca9c7c:/# ls -al /testmnt/usb
total 0
drwxr-xr-x 1 root root  0 Feb 24 18:24 .
drwxr-xr-x 1 root root 84 Feb 24 18:24 ..
```

**Describe the results you expected:**
I expect that while `ls -la /testmnt/usb` inside the container, the contents in USB drive should be listed, as in `ls -la /mnt/usb` outside the container

**Additional information you deem important (e.g. issue happens only occasionally):**
If we swap reproduce steps 1 and 2 (mount /dev/usb before docker run), then the contents in USB drive would be shown inside the container (`ls -la /testmnt/usb`), as expected

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:36:34 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 15
 Running: 6
 Paused: 0
 Stopped: 9
Images: 176
Server Version: 1.13.1
Storage Driver: btrfs
 Build Version: Btrfs v3.17
 Library Version: 101
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 62.89 GiB
Name: vm-main
ID: NCVI:A7CP:OPEO:DQJ2:HC32:DYVN:7HKJ:PJSH:3XLY:3ME7:MEK4:YTH3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine

**Comment by cpuguy83** [comment]
`-v /mnt:/testmnt:rslave` ought to take care of that.

**Comment by mgtsai** [comment]
> `-v /mnt:/testmnt:rslave` ought to take care of that.

@cpuguy83 Thanks for your indication.  Since I read the documents on the official web site, and didn't see much description about these volume mounting 'propagation options', and neglected them with misexpecting that 'shared propagation' is the default action (actual one is 'private').

I suggest that the documents on the web site may mention the usage of these volume mounting propagating options with some examples

I'll close this issue since it's clarified and resolved

**Comment by thaJeztah** [comment]
@mgtsai the docs are open source as well; each page should have an "edit" and "feedback" button, so if you have a specific page where you would've expected this information, please open an issue, or perhaps even a pull request to improve
