### ISSUE TITLE
Docker Install appears to fail if you are running a VPN at the time

### ISSUE THREAD

**Issue by programster** [docker/docker#31355]
Docker will appear to fail to install on Ubuntu 16.04 if you are running a VPN at the time.

```
...
Setting up cgroupfs-mount (1.2) ...
Setting up docker-engine (1.13.1-0~ubuntu-xenial) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
dpkg: error processing package docker-engine (--configure):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for libc-bin (2.23-0ubuntu5) ...
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
Errors were encountered while processing:
 docker-engine
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I think this issue is affecting others that I found on [this docker forum post](https://forums.docker.com/t/problem-installing-docker-on-ubuntu-xenial-16-04/9273).

I actualy found the solution buried within [this post](https://github.com/docker/docker/issues/18113) from codekoala, but it looks like that thread closed with the conclusion that people need to delete the `local-kv.db` file which was not the solution for this scenario.

I just wanted to raise the issue in hopes that either the docker installation process could handle a VPN running at the time, or perhaps detect that a VPN is running and alert the user.

**Comment by cpuguy83** [comment]
@programster Can you provide details from the logs? `journalctl -u docker`?

**Comment by yevaud** [comment]
I had the same issue:

With connected VPN:

00:46:14 localhost systemd[1]: Starting Docker Application Container Engine...
00:46:14 localhost dockerd[4869]: time="2017-02-26T00:46:14.370144474+01:00" level=info msg="libcontainerd: new containerd process, pid: 4886"
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.376358439+01:00" level=info msg="[graphdriver] using prior storage driver: aufs"
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.378819496+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.378973245+01:00" level=warning msg="Your kernel does not support swap memory limit"
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.379005312+01:00" level=warning msg="Your kernel does not support cgroup rt period"
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.379014005+01:00" level=warning msg="Your kernel does not support cgroup rt runtime"
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.379317508+01:00" level=info msg="Loading containers: start."
00:46:15 localhost dockerd[4869]: time="2017-02-26T00:46:15.383993416+01:00" level=info msg="Firewalld running: false"
00:46:15 localhost dockerd[4869]: Error starting daemon: Error initializing network controller: list bridge addresses failed: no available network
00:46:15 localhost systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
00:46:15 localhost systemd[1]: Failed to start Docker Application Container Engine.
00:46:15 localhost systemd[1]: docker.service: Unit entered failed state.
00:46:15 localhost systemd[1]: docker.service: Failed with result 'exit-code'.
00:46:15 localhost systemd[1]: docker.service: Start request repeated too quickly.
00:46:15 localhost systemd[1]: Failed to start Docker Application Container Engine.

and after I disabled the VPN:

00:47:56 localhost systemd[1]: Starting Docker Application Container Engine...
00:47:56 localhost dockerd[5855]: time="2017-02-26T00:47:56.122408078+01:00" level=info msg="libcontainerd: new containerd process, pid: 5872"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.135322135+01:00" level=info msg="[graphdriver] using prior storage driver: aufs"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.138419774+01:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.138667902+01:00" level=warning msg="Your kernel does not support swap memory limit"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.138723686+01:00" level=warning msg="Your kernel does not support cgroup rt period"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.138737764+01:00" level=warning msg="Your kernel does not support cgroup rt runtime"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.139190747+01:00" level=info msg="Loading containers: start."
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.145869686+01:00" level=info msg="Firewalld running: false"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.179422103+01:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be use
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.214880719+01:00" level=info msg="Loading containers: done."
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.248691482+01:00" level=info msg="Daemon has completed initialization"
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.248721006+01:00" level=info msg="Docker daemon" commit=092cba3 graphdriver=aufs version=1.13.1
00:47:57 localhost dockerd[5855]: time="2017-02-26T00:47:57.257132155+01:00" level=info msg="API listen on /var/run/docker.sock"
00:47:57 localhost systemd[1]: Started Docker Application Container Engine.

**Comment by cpuguy83** [comment]
```
Error starting daemon: Error initializing network controller: list bridge addresses failed: no available network
```

Seems like while the VPN is loaded none of the hard-coded subnets are available?
You may want to provide a custom subnet for the bridge network with `-bip=<bridge ip>/<subnet bits>`

**Comment by cpuguy83** [comment]
@programster I don't think we can change the install script for this, since it's not really part of the install, it's post-install where it's just starting docker.

It does output:
```
Setting up docker-engine (1.13.1-0~ubuntu-xenial) ...
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
```

Which would indeed point at the logs for this.

**Comment by programster** [comment]
@cpuguy83 the logs say **setting** up and not **starting** up which gives a completely different impression to the user (or at least me). It looks like docker-engine failed to install correctly, rather than failed to start. Indeed after digging further into the logs, I did realise that docker was just failing to start correctly because of my VPN, I was just hoping we might be able to provide a helpful tip to the user after the installation. E.g 

> Docker installed correctly but failed to start. Are you running a VPN? See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by cpuguy83** [comment]
@programster While I agree that would be nice, it would only ever be a guess and probably rarely accurate. The installer won't know that docker failed to start because none of the pre-configured subnets are available for use, and most definitely this is not related to any VPN issue, just that your vpn config is the only otherwise available subnet.

**Comment by programster** [comment]
> ...this is not related to any VPN issue, just that your vpn config is the only otherwise available subnet

I'm just using the default OpenVPN subnet configurations for the server and client. I think this is why myself and others have been affected. I'm just going to put a warning on all my "install docker" tutorials, as that is all that I can do for others.

**Comment by aboch** [comment]
@programster 

For your tutorial, be aware the issue is caused by the gateway redirect route the VPN clients install.
That route masks (overlaps with) all the docker predefined address pools, therefore docker thinks none of them is good to be assigned to the default bridge network.

**Comment by programster** [comment]
@aboch thanks for clarifying that :)

**Comment by niij** [comment]
@programster Thanks for posting this.  I was about to give up and just boot up a VM for Docker.  Turning off my VPN fixed the issue.

Running Docker while my VPN was on is **not** possible.

OS: Linux Ubuntu 16.04.2
VPN: Private Internet Access
This was after following the Docker installation steps [here](https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/)

**Comment by niij** [comment]
To the Docker Developers: is there a way Docker can notify that VPNs are the issue?  I only found out about this by going through logs, which didn't indicate anything about running a VPN.  Only thanks to @programster was I able to figure out what was up.
