### ISSUE TITLE
Network policy via docker swarm overlay

### ISSUE THREAD

**Issue by jonathan-kosgei** [docker/docker#31361]
Is it possible to implement network policy on a docker swarm overlay network?

**Comment by cpuguy83** [comment]
There is no way to set policy.
What kind of policy are you wanting to set?

**Comment by jonathan-kosgei** [comment]
@cpuguy83 something similar to what calico does i.e. restricting ingress and egress between containers according to the tags on the containers. I'm anyways looking at contiv so I'll close this.

**Comment by justincormack** [comment]
You just only attach containers to networks if you want them to be able to
communicate. A container not on a network cannot reach it.
