### ISSUE TITLE
COPY issue when copy path of MATLAB to docker 

### ISSUE THREAD

**Issue by premier424** [docker/docker#31371]
I'm trying to rebuild a docker image on Ubuntu 14.04 by adding entire matlab directory to the image. So I modified the Dockerfile by typing:  ``COPY usr /usr/`` while matlab is installed on this linux station at /usr/local/MATLAB. 

When I build the image it goes into an erro: ``lastat usr: no such file or directory`` I don't quite understand why this error occur because the directory ``usr`` really exist. I tried to change the sub-directory under usr but the directory such as ``usr/local`` still cannot be recognized. 

The docker info: 
```Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 31
Server Version: 1.11.2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 132
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 3.19.0-79-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.806 GiB
Name: mrrl-tric-linux
ID: NL6N:3IFD:CICA:V3VE:QDHO:JVSU:5PTJ:3U5N:2YVF:L72L:B77P:VHLN
Docker Root Dir: /var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```
and docker version:
```Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:47:50 2016
 OS/Arch:      linux/amd64
```
Some other issue made a problem in Ubuntu 16.04 and I'm wondering anyone meet the same error in 14.04 and have any any how to solve it? Thanks.

**Comment by catinthesky** [comment]
@premier424,  the problem might be caused by that the "src" folder should exist in the context of build command (under where the Dockerfile exists), https://docs.docker.com/engine/reference/builder/#/copy

**Comment by premier424** [comment]
@GordonTheTurtle , Thanks for your reply. I copy the source folder such as usr folder to the drectory of Dockerfile and the error disappeared.
