### ISSUE TITLE
Problem while running hello-world container on Ubuntu 16.04 32bits

### ISSUE THREAD

**Issue by AzizGayes** [docker/docker#31379]
Hello guys,

I'm running Ubuntu 16.04 32bits. I installed the docker.io package successfully then tried to run the hello-world container.

**I executed these two commands:**

`apt install docker.io`
`docker run hello-world `

**I got this result:**

panic: standard_init_linux.go:178: exec user process caused "exec format error" [recovered]
	panic: standard_init_linux.go:178: exec user process caused "exec format error"

goroutine 1 [running, locked to thread]:
panic(0x835c220, 0x975a42c0)
	/usr/lib/go-1.6/src/runtime/panic.go:481 +0x326
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction.func1(0x975d9974)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:478 +0x2c1
panic(0x835c220, 0x975a42c0)
	/usr/lib/go-1.6/src/runtime/panic.go:443 +0x3fd
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization.func1(0x975d95fc, 0x9751c638, 0x975d9684)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:259 +0xfd
github.com/opencontainers/runc/libcontainer.(*LinuxFactory).StartInitialization(0x97552720, 0x86b87bf0, 0x975a42c0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/libcontainer/factory_linux.go:277 +0x474
main.glob.func8(0x975801e0, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main_unix.go:26 +0x57
reflect.Value.call(0x8302700, 0x842f7c0, 0x13, 0x838d7b8, 0x4, 0x975d9934, 0x1, 0x1, 0x0, 0x0, ...)
	/usr/lib/go-1.6/src/reflect/value.go:435 +0xeeb
reflect.Value.Call(0x8302700, 0x842f7c0, 0x13, 0x975d9934, 0x1, 0x1, 0x0, 0x0, 0x0)
	/usr/lib/go-1.6/src/reflect/value.go:303 +0x8c
github.com/opencontainers/runc/vendor/github.com/urfave/cli.HandleAction(0x8302700, 0x842f7c0, 0x975801e0, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:487 +0x25f
github.com/opencontainers/runc/vendor/github.com/urfave/cli.Command.Run(0x838fcd8, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x840e120, 0x51, 0x0, ...)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/command.go:191 +0xda7
github.com/opencontainers/runc/vendor/github.com/urfave/cli.(*App).Run(0x97572240, 0x9750e070, 0x2, 0x2, 0x0, 0x0)
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/vendor/github.com/urfave/cli/app.go:240 +0x92b
main.main()
	/build/runc-ZfQYYD/runc-1.0.0~rc2/_build/src/github.com/opencontainers/runc/main.go:132 +0xa60

**Output of docker version:**
 
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:37 2017
 OS/Arch:      linux/386

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   78d1802
 Built:        Tue Jan 31 23:35:37 2017
 OS/Arch:      linux/386

**Output of docker info:**

Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 3
Server Version: 1.12.6
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay null bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: i686
CPUs: 2
Total Memory: 1.898 GiB
Name: Aziz-PC
ID: TWVB:O52V:KNL4:6T6B:RAZ6:Q76H:ZTLE:5CMH:SDJT:RX6P:WQD5:Z3CS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8

**Comment by thaJeztah** [comment]
Docker currently requires a 64-bit system to run. The docker.io package is not an official package, and is created and maintained by Ubuntu. If you want to run docker, it's best to upgrade to a system that runs 64-bit, but you may want to open an issue in the Ubuntu issue tracker to have them remove the 32-bit packages, because they likely are just broken.

I'll close this issue, because this is not something we can fix, but feel free to continue the conversation

**Comment by saspol** [comment]
I have same problem running docker on Ubuntu 16 ARM.
Upgrade to 64-bit? Are you joking? Fix this problem plz.
