### ISSUE TITLE
Container cat not start with "...  .pivot_root041682652: no space left on device"

### ISSUE THREAD

**Issue by whc9527** [docker/docker#31385]
Description
I installed a docker on a physical machine, I did not do any configuration on the docker,so the docker max disk space can is 100G. then i used the dd command to create a 200G large file.  When I created to about 100G when the error，after this i want stop and start my container,  When I started, there was a error
`[root@A06-R12-302F0314-I35-122 ~]# docker start flume1.7.0-system
Error response from daemon: Cannot start container flume1.7.0-system: [8] System error: can't create pivot_root dir , error mkdir /export/Data/docker/devicemapper/mnt/c3ba1b9dd4b57c1d399f1e5af0c780baec58d73bcb4755f2988a003ad350a736/rootfs/.pivot_root041682652: no space left on device
Error: failed to start containers: [flume1.7.0-system]
[root@A06-R12-302F0314-I35-122 ~]# `
 
**Describe the results you expected:**
In this case there is no way for me to delete the test file where dd created.

**Output of `docker version`:**

```
Client:
 Version:      1.8.2
 API version:  1.20
 Package Version: docker-1.8.2-7.el7.centos.x86_64
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.8.2
 API version:  1.20
 Package Version: 
 Go version:   go1.4.2
 Git commit:   bb472f0/1.8.2
 Built:        
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 2
Images: 21
Storage Driver: devicemapper
 Pool Name: docker-8:5-12885024546-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 212.3 GB
 Data Space Total: 322.1 GB
 Data Space Available: 109.8 GB
 Metadata Space Used: 108.5 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.039 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Data loop file: /export/Data/docker/devicemapper/devicemapper/data
 Metadata loop file: /export/Data/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.10.0-229.20.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 32
Total Memory: 125.6 GiB
Name: A06-R12-302F0314-I35-122.GZ01.JCLOUD.COM
ID: VWMR:U3CE:WH5B:2DNM:PSQU:HOTD:KVQK:ABYC:INOP:PIZK:TGWP:VDHP
```
uname -a
```
Linux A06-R12-302F0314-I35-122.GZ01.JCLOUD.COM 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cpuguy83** [comment]
You `dd`'d in a container? Can you `docker rm <the container>`?

Also note that you are using a *really* old version of Docker which is unsupported.
That said, it seems like everything is working as expected here since you ate up all the free space docker can't create new containers.

Closing since this doesn't look like a real issue, but feel free to discuss.

**Comment by whc9527** [comment]
@cpuguy83  thanks， Above is a test I do, I would like to know is not a way to mount, delete the file I just created, and then start the container？

**Comment by cpuguy83** [comment]
@whc9527 with devmapper, just mounting would be tricky.
Only way would be remove the container in question.
I would also store this kind of stuff in a volume rather than in the container FS.

**Comment by whc9527** [comment]
@cpuguy83 i get it . thanks very much! 谢谢了！
