### ISSUE TITLE
docker swarm timesout when creating new services.

### ISSUE THREAD

**Issue by rommik** [docker/docker#31429]
Suddenly, Docker Swarm that I had running for over 12 days stopped creating new services.
all existing services are up and running without problems.

Upon digging through the logs , and lots of trial and errors, I discovered this log.

Feb 28 19:54:56 swarm-node-master-1 dockerd[1454]: time="2017-02-28T19:54:56.677259526Z" level=warning msg="unable to pin image vfarcic/go-demo to digest: manifest unknown: manifest unknown
"
Feb 28 19:54:56 swarm-node-master-1 dockerd[1454]: time="2017-02-28T19:54:56.678017212Z" level=error msg="Error creating service go-demo: rpc error: code = 4 desc = context deadline exceede
d"
Feb 28 19:54:56 swarm-node-master-1 dockerd[1454]: time="2017-02-28T19:54:56.678339207Z" level=error msg="Handler for POST /v1.26/services/create returned error: rpc error: code = 4 desc =
context deadline exceeded"

It seems to be consisten with all my manager nodes ( three in total). I have this in their logs but for different services that I attempted to deploy (via stack files and command line).

What is the reason for this " unable to pin image" ?

Docker Version on all nodes is Docker version 1.13.1, build 092cba3

**Comment by thaJeztah** [comment]
looks like a duplicate of https://github.com/docker/docker/issues/31427, and is due to an outage of AWS S3; see https://status.docker.com. The linked issue has some workarounds.

I'll close this issue for housekeeping, and to keep the discussion central, but thanks for reporting
