### ISSUE TITLE
nprocs ulimit inside container compared to host value

### ISSUE THREAD

**Issue by prune998** [docker/docker#31424]
**Description**
When setting a limit on the number of processes inside a container using  /etc/security/limits, the number of processes is taken from the number of processes on the host and not inside the container.

This may not be a bug, but not the exact attended behaviour.

**Steps to reproduce the issue:**

Please check https://gist.github.com/prune998/4a9fd7783b1dbb90b1bdb660ee42f9c2 for a full description.

1. create an empty container
2. create a user inside the container with the SAME UID as your regular user
3. set up an `nproc` limit just below the total process count of your user at the host level
4. su as the new user
5. get a `retry: Resource temporarily unavailable`

Any process started inside a container maps to a user (or an ID) on the host. 
If the user inside the container have the same ID as process already running on the host, the total count of processes equals the addition of the two.

So, if you set a 1024 limit inside the container and you have 1025 user processes on your host, you won't be able to start any new process inside the container.

**Describe the results you received:**
You can't create any process inside the container, reciving a `retry: Resource temporarily unavailable`

**Describe the results you expected:**
You should be able to create as much process as specified in the limit file inside the container.

**Additional information you deem important (e.g. issue happens only occasionally):**
If you want to have the expected behaviour, you have to ensure the user inside the container is using an ID that is not used inside the host.

**Output of `docker version`:**

```
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker info
Containers: 5
 Running: 3
 Paused: 0
 Stopped: 2
Images: 3
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 23
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.434 GiB
Name: sthomas-ubuntu
ID: KNUU:TJ3U:CXHM:BBVQ:UOMN:4IEQ:HCEM:R65K:CZKN:GD7D:XY67:AY6G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
`Linux sthomas-ubuntu 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
`
Ubuntu 16.04LTS

**Comment by cpuguy83** [comment]
This is expected since nproc is not namespaced and is tied to the UID.

If you are on a new kernel (4.3?) you can use the pids cgroup instead.
This is supported on `docker run` via `docker run --pids-limit=N`

Closing since this is behaving as expected.

**Comment by prune998** [comment]
That make sense, thanks !
