### ISSUE TITLE
how to configure docker 1.13

### ISSUE THREAD

**Issue by ikaven1024** [docker/docker#31441]
i have install docker 1.13.1 on my centos7. but i don't find `/etc/sysconfig/docker` anymore when i am going to add insecure registry.
Besides, docker-storage-setup is also missing, is there any tools to change storage driver?

**Comment by cpuguy83** [comment]
These are files provided by the RH-provided package, not the official package.
To configure docker, please use `/etc/docker/daemon.json` (which doesn't exist by default, just create it).
See [the docs for the config file for more info](https://docs.docker.com/engine/reference/commandline/dockerd/#/linux-configuration-file)

Docker does not currently provide an equivelent of `docker-storage-setup`, but see [how to configure devicemapper here](https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/#/configure-direct-lvm-mode-for-production)

**Comment by thaJeztah** [comment]
Looks like the question is answered, so I'll go ahead and close this issue, but feel free to continue the conversation. Please keep in mind that the GitHub issue tracker is not intended as a general support forum, but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)
