### ISSUE TITLE
Can we _really_ specify an "init process"?

### ISSUE THREAD

**Issue by nschoe** [docker/docker#31454]
Hi,
I was reading the docs (to get up-to-date between 1.11 and 1.13) and [here](https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/each-container-should-have-only-one-concern) I found this sentence:

> In addition to the fact that containers can now be spawned with an init process, some programs might spawn additional processes of their own accord. 

So I wonder, can we **really** specify an init process or does this page simply talk about the `CMD`?

The link brings nowhere hlpeful. So if it's just about the `CMD`, could we change the docs (should I click "Edit this page" or "Request dos change"?) because it is misleading :)
I was really hoping that we could _finally_ have an init process :)

Thanks in advance :P

**Comment by cpuguy83** [comment]
Well, looks like the link to the docs page for this is broken (https://docs.docker.com/engine/reference/run/#/specifying-an-init-process) since the heading doesn't seem to be there anymore...

But yes, you can start a container with `--init`, and even configure the daemon to do this by default. This uses tini as the pid 1 in the container.

**Comment by nschoe** [comment]
Okay maybe this is my bad: srust on IRC just pointed me to the `--init` option of `docker run`.
He told me that it runs tini, is there more doc on this on Docker?

**Comment by thaJeztah** [comment]
Looks like the docs published on docs.docker.com are not updated yet with the latest changes. Source for that page can be found here; https://github.com/docker/docker/blob/d7fda019bb7e24f42f8ae1ddecb3fd52df3c48bf/docs/reference/run.md#specify-an-init-process

**Comment by thaJeztah** [comment]
And a default can be set on the daemon, either using the `--init` / `--init-path`  options, or through a `daemon.json` configuration file; https://github.com/docker/docker/blob/340b75dd41d026e6f6072da851930d6802a1ee34/docs/reference/commandline/dockerd.md

**Comment by nschoe** [comment]
That's awesome. I have been waiting for this feature for a long time, nice to know you guys have been working in it.
Congrats!

Shall we close the issue?

**Comment by thaJeztah** [comment]
Yes, I think we can close the issue. To add to the question;

> you even anticipated my next question: making this as default.

We did discuss setting this by default at the time, but for many images/containers, an init process is really not needed. _Ideally_, the image author is the best person to determine if an init process is required or not. So, basically;

- If the image is authored correctly, it has an init process _if needed_ (and vice-versa)
- If you need to run an image that you didn't author yourself, and discover that it's not properly reaping child-processes, then the `--init` flag can be used to insert an init process


I'll close this issue, but feel free to continue the conversation!
