### ISSUE TITLE
windows docker force input a password while change shared drives

### ISSUE THREAD

**Issue by eromoe** [docker/docker#31451]
My home computer doesn't have a password, so I can't set change shared drives.

![image](https://cloud.githubusercontent.com/assets/3938751/23462604/6f5f07ec-fec9-11e6-9729-3cec7f1f9f37.png)

**Comment by thaJeztah** [comment]
Hi @eromoe, thanks for reporting; since this issue is specific to the Docker for Windows package, can you report this in that issue tracker? https://github.com/docker/for-win/issues ?

I'll close this issue here, because the GUI for docker for windows is not part of this repository, thanks!
