### ISSUE TITLE
Endless number of messages "Firewalld running: false " in docker log

### ISSUE THREAD

**Issue by liyaka** [docker/docker#31473]
I run the new Docker version 17.03.0-ce, build 60ccb22 in swarm mode on Ubuntu 14.04: 
1 manager + 3 additional nodes. Everything works fine so far, but i see endless messages in `/var/log/upstart/docker.log` on all nodes including manager:
`INFO[0000] Firewalld running: false`                     
`INFO[0000] Firewalld running: false` 
`INFO[0000] Firewalld running: false` 
`INFO[0000] Firewalld running: false` 
`INFO[0000] Firewalld running: false` 
`INFO[0000] Firewalld running: false`

**Comment by KarthikNayak** [comment]
I wonder if its a good idea to only log changes in Firewalld status changes, something like

```diff
diff --git a/vendor/github.com/docker/libnetwork/iptables/firewalld.go b/vendor/github.com/docker/libnetwork/iptables/firewalld.go
index 970931ce9..7f4b7c659 100644
--- a/vendor/github.com/docker/libnetwork/iptables/firewalld.go
+++ b/vendor/github.com/docker/libnetwork/iptables/firewalld.go
@@ -35,6 +35,7 @@ var (
        connection       *Conn
        firewalldRunning bool      // is Firewalld service running
        onReloaded       []*func() // callbacks when Firewalld has been reloaded
+       pErr             error
 )
 
 // FirewalldInit initializes firewalld management code.
@@ -44,6 +45,7 @@ func FirewalldInit() error {
        if connection, err = newConnection(); err != nil {
                return fmt.Errorf("Failed to connect to D-Bus system bus: %v", err)
        }
+       pErr = nil
        firewalldRunning = checkRunning()
        if !firewalldRunning {
                connection.sysconn.Close()
@@ -151,7 +153,10 @@ func checkRunning() bool {
 
        if connection != nil {
                err = connection.sysobj.Call(dbusInterface+".getDefaultZone", 0).Store(&zone)
-               logrus.Infof("Firewalld running: %t", err == nil)
+               if err != pErr {
+                       logrus.Infof("Firewalld running: %t", err == nil)
+               }
+               pErr = err
                return err == nil
        }
        return false
```

**Comment by thaJeztah** [comment]
@KarthikNayak that file is vendored from the libnetwork repository; feel free to open a pull request there for discussion; https://github.com/docker/libnetwork/blob/master/iptables/firewalld.go

**Comment by aaronlehmann** [comment]
This seems like a serious issue. I'm seeing tons of log spam from this in logs that a user gave me for debugging an unrelated issue. Has it been fixed yet? Should I open an issue on libnetwork?

**Comment by aaronlehmann** [comment]
ping @docker/core-libnetwork-maintainers

**Comment by aboch** [comment]
I am afraid the only fix is to remove the message altogether.
Every time we program iptables in a reexec function, that message will be printed.

**Comment by aaronlehmann** [comment]
Would it make sense to move the message to the "debug" log level?

Also, it would be pretty easy to rate-limit the message. Take a look at https://godoc.org/golang.org/x/time/rate. Here is how we use it to rate-limit a log message: https://github.com/docker/docker/blob/master/daemon/cluster/executor/container/adapter.go#L97-L109

**Comment by aboch** [comment]
The message is to let user know at docker boot the iptables rule programming will be pushed via firewalld. Only one instance of the message is needed. Making it debug would defeat the purpose of the message. 

I think it is better to remove the log altogether. The info it provides is not that important. We can always find whether docker used firewalld to program the rules by simply looking at firewalld logs.
