### ISSUE TITLE
docker run fails: Error response from daemon: devmapper: Unknown device "<dev_name>

### ISSUE THREAD

**Issue by juliemathew** [docker/docker#31483]
Issue Description:
**"docker run" command  fails.
This is happening after we changed docker configuration - configured docker host with devicemapper with actual disk as the backend (without loop). Earlier docker host was running with the devicemapper storage driver operating in loop-lvm mode.**
https://docs.docker.com/engine/userguide/storagedriver/device-mapper-driver/

root@master-pwd-vol:/home/ubuntu# docker run -it ppc64le/ubuntu
Digest: sha256:5349f00594c719455f2c8e6f011b32758dcd326d8e225c737a55c15cf3d6948c
Status: Downloaded newer image for ppc64le/ubuntu:latest
**docker: Error response from daemon: devmapper: Unknown device 200088a0cfef0520bc27e5094021d5442593345df6711028807fe896d8d11339.**
See 'docker run --help'.

More details:
root@master-pwd-vol:~ uname -a
Linux master-pwd-vol 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 17:05:51 UTC 201
7 ppc64le ppc64le ppc64le GNU/Linux
root@master-pwd-vol:~

root@master-pwd-vol:~ docker --version
Docker version 1.12.0, build 5507242

root@master-pwd-vol:~  docker info
Containers: 8
 Running: 0
 Paused: 0
 Stopped: 8
Images: 21
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file:
 Metadata file:
 Data Space Used: 1.219 GB
 Data Space Total: 20.4 GB
 Data Space Available: 19.18 GB
 Metadata Space Used: 544.8 kB
 Metadata Space Total: 213.9 MB
 Metadata Space Available: 213.4 MB
 Thin Pool Minimum Free Space: 2.039 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null overlay bridge host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: ppc64le
CPUs: 2
Total Memory: 3.977 GiB
Name: master-pwd-vol
ID: IBGL:BQGE:7BS4:HVU3:EG3A:4YVC:V72C:3MDQ:H7VE:T2AG:B6CL:YMHH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 23
 System Time: 2017-03-02T13:05:40.911404Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
root@master-pwd-vol:~ 

root@master-pwd-vol:~ lsblk
NAME                    MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sr0                      11:0    1  446K  0 rom
vda                     253:0    0   20G  0 disk
├─docker-thinpool_tmeta 252:0    0  204M  0 lvm
│ └─docker-thinpool     252:2    0   19G  0 lvm
└─docker-thinpool_tdata 252:1    0   19G  0 lvm
  └─docker-thinpool     252:2    0   19G  0 lvm
vdb                     253:16   0   20G  0 disk
├─vdb1                  253:17   0   20G  0 part /
└─vdb2                  253:18   0    8M  0 part
root@master-pwd-vol:~

**Comment by cpuguy83** [comment]
Did this already have images?
I'd recommend clearing out `/var/lib/docker` then try again.

**Comment by juliemathew** [comment]
Yes, it has images. We are trying the steps once again after removing the images.

**Comment by juliemathew** [comment]
@cpuguy83 , we removed the docker images , and re-tried the steps. It is successful now. 
Closing this issue.
Thanks for your suggestion!
