### ISSUE TITLE
Docker on Windows 10 - Keep having to reset credentials on shared drive

### ISSUE THREAD

**Issue by smithma01** [docker/docker#31481]
**Description**

**Steps to reproduce the issue:**
1. Share a drive using the docker settings gui in windows 10 pro (x64)
2. Created a docker image that maps a directory to a windows directory on the shared drive.
3. Reboot the windows host and start the image if autostart is not set
4: enter image and go to the shared folder/directory - it is not shared...

**Describe the results you received:**

Directory and folders mapped from host windows machine to Linux image no longer mapped after reboot. I then have to reset the shared drives credentials and re-setup the windows host shared drive. Once done starting the docker image works as expected and the directories are mapped as needed.

**Describe the results you expected:**

I expect for the shared drive to remain shared after a reboot of the host machine.

**Additional information you deem important (e.g. issue happens only occasionally):**

Seems to happen after every reboot

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      linux/amd64
 Experimental: true```

```

**Output of `docker info`:**

```
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 4
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 24
Total Memory: 11.45 GiB
Name: moby
ID: 4LZ7:PMRV:JDGJ:UVXJ:CAC6:YG2O:JJK4:AA6V:QWMJ:5NUP:6IN6:NY3G
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 13
 Goroutines: 22
 System Time: 2017-03-02T11:57:15.7370858Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Windows 10 pro (x64) docker host is running on a physical HP Z600 workstation

**Comment by thaJeztah** [comment]
Thanks for reporting @smithma01 - it looks like this issue is specific to the Docker for Windows package; could you reopen this in that issue tracker? https://github.com/docker/for-win/issues ?
