### ISSUE TITLE
Enhancement request: add docker-ce repository key to sks server pool

### ISSUE THREAD

**Issue by RRAlex** [docker/docker#31493]
`apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 9DC858229FC7DD38854AE2D88D81803C0EBFCD88`

Running the above fails, unlike the previous docker-engine repo key.
Please make it easier to fetch the key in a more distributed manner :)

cheers!

**Comment by riyazdf** [comment]
we've updated keys for CE here (thank you @cyli!)
https://pgp.mit.edu/pks/lookup?search=docker%40docker.com&op=index
https://sks-keyservers.net/pks/lookup?op=vindex&search=docker%40docker.com, http://keyserver.ubuntu.com/pks/lookup?op=vindex&search=docker%40docker.com&fingerprint=on

We've tested the command you posted and it seems to work - is it working for you now @RRAlex?

```
~# apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
Executing: /tmp/tmp.8Zk1be1AMI/gpg.1.sh --keyserver
hkp://p80.pool.sks-keyservers.net:80
--recv
9DC858229FC7DD38854AE2D88D81803C0EBFCD88
gpg: requesting key 0EBFCD88 from hkp server p80.pool.sks-keyservers.net
gpg: key 0EBFCD88: "Docker Release (CE deb) <docker@docker.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
```

**Comment by RRAlex** [comment]
Yep, problem solved! Thanks :-)

**Comment by cpuguy83** [comment]
Thanks!
