### ISSUE TITLE
Ubuntu installer package page not working.

### ISSUE THREAD

**Issue by 4goodapp** [docker/docker#31505]
the page show this 

`
        This XML file does not appear to have any style information associated with it. The document tree is shown below.
      <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>94D12C1F969A68C4</RequestId><HostId>/7Hw+5lbygKvzBsJKQIDWP0qw9RNFFyoApdiepTBHyoiUPXSS86Q3jdDqAEOe325gidIayQM24o=</HostId></Error>`

http://i.imgur.com/XWYPcHh.png

**Comment by thaJeztah** [comment]
this should be fixed now by https://github.com/docker/docker/issues/31987
