### ISSUE TITLE
Published CNI container ports conflict on host

### ISSUE THREAD

**Issue by bradjones1** [docker/docker#31508]
**Description**

Running multiple containers on a single host published on the same port (e.g., `443`) but different public IPs (e.g., `1.2.3.4` and `4.3.2.1`) result in the port also being accessible on the host at `localhost`/`127.0.0.1`, forwarding to one of those containers seemingly at random. This can result in some strange results if, for instance, a Docker Registry is published in this manner, and the second container presents a different service and TLS certificate entirely. When the Docker engine makes requests to the registry, the wrong container answers, prompting errors in container creation and confusion on the part of the admin.

**Steps to reproduce the issue:**
1. Add two services that are bound to different public IPs routed to the host, but using the same port. They should create and operate as expected (that is, answering only on their respective IP/port combinations) from external clients.
2. Make a request from the host to the IPs/ports, or hostnames resolving to them.
3. In all cases, only a single container will answer, resulting in 50% of the requests being effectively routed to the wrong container.

It is worth noting that if multiple containers are published to public ports on ports `80` and `443`, requests from the host may route to one container for one port, and another for the second.

**Describe the results you received:**

Only one container appears to respond to requests when made from the host, for a single port.

**Describe the results you expected:**

The correct container responds to the request based on the IP.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 48
 Running: 47
 Paused: 0
 Stopped: 1
Images: 43
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 636
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local rancher-secrets
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 16
Total Memory: 15.64 GiB
Name: summit
ID: 4CPV:LE2H:VGLA:XY3M:E2FO:2AZL:KUAO:CN62:ERRY:ZYNN:L6AA:7BX3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Physical, Ubuntu 14.04.5, Rancher 1.4.1

Output of `rancher inspect` on two containers bound to the same port (some IPs changed):

```json
"publicEndpoints": [
    {
      "hostId": "1h4",
      "instanceId": "1i12442",
      "ipAddress": "1.2.3.4",
      "port": 80,
      "serviceId": "1s421",
      "type": "publicEndpoint"
    },
    {
      "hostId": "1h4",
      "instanceId": "1i12442",
      "ipAddress": "1.2.3.4",
      "port": 443,
      "serviceId": "1s421",
      "type": "publicEndpoint"
    }
  ],
```

```json
  "publicEndpoints": [
    {
      "hostId": "1h4",
      "instanceId": "1i12565",
      "ipAddress": "4.3.2.1",
      "port": 80,
      "serviceId": "1s433",
      "type": "publicEndpoint"
    },
    {
      "hostId": "1h4",
      "instanceId": "1i12565",
      "ipAddress": "4.3.2.1",
      "port": 443,
      "serviceId": "1s433",
      "type": "publicEndpoint"
    }
  ],
```

**Comment by bradjones1** [comment]
I take it this might be due to hairpinning? https://docs.docker.com/engine/userguide/networking/default_network/binding/

This may just be "the way it is"/works as designed, however if that's the case anyone have suggestions about routing requests from the host to the proper "external" port?

**Comment by thaJeztah** [comment]
ping @aboch PTAL

**Comment by aboch** [comment]
I am assuming the IP address for the service is _not_ being passed to docker as it would in
`docker run -d -p <IP>:<publish port x>:<target port> <image>`

because if I run two containers with the above command publishing on two separate IP addresses, I am not able to reproduce the issue. Docker will listen on two separate tcp  \<IP\>:\<Port x\> sockets and would not accept requests on <127.0.0.1>:<PortX>

Can you post the output of `sudo ss -tpln` ?

**Comment by bradjones1** [comment]
@aboch correct; `ss` and `netstat` both only show ports bound by containers started with the Docker CLI or other system processes. None of the ports exposed by the Rancher CNI are shown.

**Comment by aboch** [comment]
Thanks. So please check with Rancher, how they are ultimately configuring the docker containers.
