### ISSUE TITLE
Ability to remove all containers with `rm --all` option

### ISSUE THREAD

**Issue by dennisgove** [docker/docker#31502]
This is to see if there's interest in this new feature.

I've been finding myself getting into situations where I have a bunch of stopped containers I want to remove. The ability to run `docker rm --all` would be nice syntactic sugar to pasting in each container id/name. 

This is generally only an issue for me when I'm creating and testing new images, or `docker-compose` setups.

I'm happy to develop it if there's interest.

A couple of pertinent thoughts:

1. Should it ask for confirmation?
2. Would a `start --all` or `stop --all` also be useful?

**Comment by dennisgove** [comment]
Turns out I just missed a very easy command that accomplishes this. `docker rm $(docker ps -a -q)`

**Comment by thaJeztah** [comment]
On Docker 1.13 and up (including Docker CE 17.03 which was released today), there's a new set of commands to cleanup containers, images, volumes and networks;

To cleanup all unused images, volumes, networks and stopped containers;

    docker system prune

To cleanup stopped containers;

    docker container prune

Unused volumes

    docker volume prune

Unused images

    docker image prune
