### ISSUE TITLE
get.docker.com installs docker-engine instead of docker-ce

### ISSUE THREAD

**Issue by Silex** [docker/docker#31514]
http://get.docker.com still installs `docker-engine` instead of `docker-ce`.

Is that normal?

**Comment by cpuguy83** [comment]
ping @andrewhsu

**Comment by RRAlex** [comment]
There is a new package name, repository, GPG key, etc.:
https://docs.docker.com/engine/installation/linux/ubuntu/#install-using-the-repository

**Comment by andrewhsu** [comment]
Yes, get.docker.com will install the docker-engine packages in a manner as it always has.

For new installations, it is recommended to use the new repository as pointed out by @RRAlex

**Comment by Silex** [comment]
@RRAlex: I know, hence my question

@andrewhsu: so, does that mean that get.docker.com is deprecated from now on? it's still recommended here: https://docs.docker.com/engine/getstarted/linux_install_help/

Just to be clear, it would not make sense to me that boths ways are recommended. It'd be either `docker-ce` from now on or `docker-engine`, but not both.

**Comment by Silex** [comment]
@andrewhsu: ping :-)

**Comment by thaJeztah** [comment]
Yes, the download.docker.com repository should be used going forward. The get.docker.com repository is maintained to not break existing installs, but eventually no new packages will be published there (I don't think a definitive date was set for that yet).

**Comment by thaJeztah** [comment]
@Silex would you be interested in opening a pull request in the documentation repository to update that page in the documentation?

**Comment by Silex** [comment]
You mean a PR to update https://docs.docker.com/engine/getstarted/linux_install_help ? Sure, but what should be done? Add a deprecate notice or replace the installation method so it uses the new repositories?

**Comment by thaJeztah** [comment]
@Silex yes, that would be great! We should replace it with instructions for the new repositories. Hm, actually; that page does not seem to be linked from the menu, and this page links to the various installation instructions https://docs.docker.com/engine/getstarted/step_one/. How did you arrive on that page? Is it linked somewhere, through search? Perhaps it's an old page and needs to be removed

ping @mstanleyjones do you know about that page?

**Comment by Silex** [comment]
The link is at https://docs.docker.com/engine/getstarted/step_one/#docker-for-linux at line 82 (source https://github.com/docker/docker.github.io/blame/master/engine/getstarted/step_one.md#L82)

**Comment by thaJeztah** [comment]
oh, you're right, hm Wondering if it should link to the general installation instructions instead. I'll leave that decision to @mstanleyjones for now 😊

**Comment by Silex** [comment]
@mstanleyjones: ping

**Comment by mstanleyjones** [comment]
I'm on it.

**Comment by mstanleyjones** [comment]
See https://github.com/docker/docker.github.io/pull/2354. I'll close this issue in favor of that PR.

**Comment by francislavoie** [comment]
I just want to clarify, why is https://get.docker.com/ being deprecated? I just found it yesterday and was very excited to find an officially maintained script to install docker on most distros. I work on a dockerized solution which gets installed on-prem for our customers, it's very disappointing to see that this would get deprecated. I want to give our customers the options of using whatever linux distro they want.

I really hope you reconsider, that script has incredible value for these kinds of use-cases. Being able to script installations much more easily is very important to us. I can't expect some of our customers with a lesser understanding of linux to use the steps here https://docs.docker.com/engine/installation/linux/ if they want to get set up quickly. Those steps are a huge speedbump that the script at https://get.docker.com/ almost entirely removes.

Thanks

**Comment by amoghe** [comment]
IIUC get.docker.io was an automated way of executing whatever the installation instructions are (at the time). So if the installation instructions have changed to use a new repo (and new pkg name), then get.docker.io should be updated to reflect these.

Is/was the contract around get.docker.io different from what I just described?

**Comment by coding-horror** [comment]
I concur with the above. We have "install Docker" as a step in our Discourse install guide and get.docker.com made it easy. Why not just update get.docker.com as needed, so everyone can benefit from an easy one step install? The manual install instructions are way more daunting than the simple get.docker.com one liner.

**Comment by edmorley** [comment]
If the decision ends up being to deprecate get.docker.com, please can the script be modified to output a deprecation warning? Otherwise people will silently install older versions if this ends up being true:

> The get.docker.com repository is maintained to not break existing installs, but eventually no new packages will be published there (I don't think a definitive date was set for that yet).

Many thanks!

**Comment by thaJeztah** [comment]
I echoed these concerns internally, and I think work is in progress for this, but /cc @andrewhsu

**Comment by Silex** [comment]
Hum, http://get.docker.com changed and installs `docker-ce` now.

Is this intended? was this communicated somewhere?

**Comment by mstanleyjones** [comment]
cc/ @andrewhsu

**Comment by Silex** [comment]
The commit that introduced this seems to be https://github.com/docker/docker-install/commit/87d90102ffa62ed157886a397d7ef24a79536fa7

**Comment by thaJeztah** [comment]
The get.docker.com script always installed the latest version of docker, given that the `docker-engine` packages are no longer updated, and have been replaced by the `docker-ce` packages, the script was updated to install those packages.

**Comment by francislavoie** [comment]
Great, that's good to hear.

It's just that there was some very confusing messaging going on about this issue.

**Comment by thaJeztah** [comment]
Apologies for that; plans were to no longer have an install script, and only have the manual installation steps. I put up some fights to convince people that that would be a bad idea, and in the end succeeded :tada: 

For production (i.e.; custom configuration needed, specific version to install, etc.) the manual steps, or a script/playbook customised to your needs is still recommended, but the get.docker.com "express install" is here to stay

**Comment by impredicative** [comment]
Does the https://get.docker.com/ script (and any scripts underlying it) correspond to any files on GitHub?

**Comment by francislavoie** [comment]
@impredicative yep, https://github.com/docker/docker-install/blob/master/install.sh
