### ISSUE TITLE
Process in container stuck when writing log to stderr

### ISSUE THREAD

**Issue by polym** [docker/docker#31540]
**Description**

Last days,  we found some containers weren't working, the process stuck when writing log to stderr!!

![image](https://cloud.githubusercontent.com/assets/2860926/23578214/9e3c46b6-010c-11e7-8b15-6936649de16c.png)

```
cat /var/run/docker/libcontainerd/6ed432dc6f1c5e18463541b2459a3e6cf3a08f22fee55b38886e5432e1f3305c/init-stderr
```
Process run again after `cat init-stderr`. If stop `cat init-stderr`, process stuck again. So, I strace the docker-container-shim. 

![image](https://cloud.githubusercontent.com/assets/2860926/23578227/edaa5d1e-010c-11e7-977f-5480c14fd9bb.png)

**Additional information you deem important (e.g. issue happens only occasionally):**

We find that heka connected many sockets to docker daemon.

**Output of `docker version`:**

```
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:20:08 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 131
Server Version: 1.11.2
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host bridge null
Kernel Version: 4.6.0-1.el6.elrepo.x86_64
Operating System: <unknown>
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 125.9 GiB
Name: DCK-ZJ-FUD-128
ID: JTRG:3WGO:PZV2:3KJG:KUZU:XXGX:ZWH3:Y5UX:TL3W:YWO5:DYON:5F2T
Docker Root Dir: /disk/ssd1/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
hm, couple of things;

- Is this a new install, or has it been running for a longer time?
- What distro are your running on?
- Docker 1.11 is EOL, and no longer maintained; are you able to reproduce on the current version?
- What's running in those containers? Do you have steps to reproduce?
- do the system logs show anything useful?

**Comment by polym** [comment]
@thaJeztah thank you for the fast reply.

> Is this a new install, or has it been running for a longer time?

Running about half a year in the production environment.

> What distro are your running on?

On CentOs6 with kernel 4.6.0. Even so，I don't think distro is related.

> Docker 1.11 is EOL, and no longer maintained; are you able to reproduce on the current version?

I will upgrade docker. Which version is recommended? 

> What's running in those containers? Do you have steps to reproduce?

A simple web server. I will try my best to reproduce.

> do the system logs show anything useful?

`dmesg` didn't show any abnormal logs. /var/log/docker has some logs for other containers.

Now I have no idea to trace the problem，may the thread which read init-stderr be crashed? Something abnormal is that the container which gets all containers' logs, established 1k+ socket connections to docker-daemon. Will it be related?

**Comment by thaJeztah** [comment]
> On CentOs6 with kernel 4.6.0. Even so，I don't think distro is related.

Hm, but RHEL6 is not supported for two years (https://github.com/docker/docker/pull/14746); the last version of docker running on RHEL6 is docker 1.7.1; running it with a custom kernel is completely untested so not recommended for production.

> I will upgrade docker. Which version is recommended?

The current version is 17.03, and was released last week. Older versions as no longer maintained (there's Docker EE, and "commercially supported" versions of docker that does maintain older versions, but they're not supported on RHEL6 as well)

I'm not sure it's gonna be easy to help, unless there's a way to reproduce this in the current version. So that we can debug

**Comment by polym** [comment]
@thaJeztah thanks. I will try to reproduce it on current version.

**Comment by ooooorz** [comment]
We are running kafka connect with docker container. We found the threads are stuck while calling logger appender.  
We checked the {container-id}-json.log, it stopped appending anymore. 

And we found that if we do 
`tail -f /proc/1/fd/1 
`
to consume the console output, the container will be back to normal though we see nothing from the console output.

We don't know how to reproduce the issue. It happened twice to us.
Restart the container will resolve the problem.

**docker info**
>  Containers: 8
>  Running: 7
>  Paused: 0
>  Stopped: 1
> Images: 11
> Server Version: 1.13.1
> Storage Driver: overlay
>  Backing Filesystem: extfs
>  Supports d_type: true
> Logging Driver: json-file
> Cgroup Driver: cgroupfs
> Plugins: 
>  Volume: local
>  Network: bridge host macvlan null overlay
> Swarm: active
>  NodeID: vj9q3sas41r5303wd709nmd83
>  Is Manager: false
>  Node Address: 192.168.1.213
>  Manager Addresses:
>   192.168.1.214:2377
> Runtimes: runc
> Default Runtime: runc
> Init Binary: docker-init
> containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
> runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
> init version: 949e6fa
> Security Options:
>  seccomp
>   Profile: default
> Kernel Version: 3.10.0-514.6.2.el7.x86_64
> Operating System: CentOS Linux 7 (Core)
> OSType: linux
> Architecture: x86_64
> CPUs: 2
> Total Memory: 15.51 GiB
> Name: swarm01
> ID: 6CMM:UU6A:ZOVV:CTAI:67ZA:QDI5:P2Y5:BJPN:RTNH:QKYH:JSTW:YVFY
> Docker Root Dir: /var/lib/docker
> Debug Mode (client): false
> Debug Mode (server): false
> Registry: https://index.docker.io/v1/
> Experimental: false
> Insecure Registries:
>  127.0.0.0/8
> Live Restore Enabled: false

**docker version**
docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false

**sample thread dump**
```
"qtp399534175-21" #21 prio=5 os_prio=0 tid=0x00007f562103c800 nid=0x4d waiting for monitor entry [0x00007f55d35f8000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.apache.log4j.Category.callAppenders(Category.java:204)
	- waiting to lock <0x00000000806b30c8> (a org.apache.log4j.spi.RootLogger)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.log(Category.java:856)
	at org.slf4j.impl.Log4jLoggerAdapter.log(Log4jLoggerAdapter.java:601)
	at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:620)
	at org.eclipse.jetty.util.log.JettyAwareLogger.info(JettyAwareLogger.java:314)
	at org.eclipse.jetty.util.log.Slf4jLog.info(Slf4jLog.java:74)
	at org.eclipse.jetty.server.Slf4jRequestLog.write(Slf4jRequestLog.java:60)
	at org.eclipse.jetty.server.AbstractNCSARequestLog.log(AbstractNCSARequestLog.java:205)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:113)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by polym** [comment]
@ooooorz In my scenario，I killed the abnormal container which was using 1k+ fd, and then solved this problem. Whether did the process in the running containers use many fds?

**Comment by ooooorz** [comment]
@polym I don't think we use many fds

**Comment by yrral86** [comment]
I can reliably reproduce the issue with a wildfly container running a java web application.  We are using docker-compose to run the two applications and a third container to running tests against one of the applications (the tested application makes use of the second application).  The tests start to fail reliably in the same area, so it seems like something is hitting some sort of resource limit.  The application hangs up trying to write to STDOUT.  If I connect to the container and run `cat /proc/1/fd/1`, the hangup goes away and the application continues until I hit ctl-C on the cat process, at which point the hangup returns.  The thread that is trying to write is runnable and is just waiting on the kernel to return from the call to write.  I can't share the application, but if anyone has any clue what to try to debug the situation, I'm happy to help track it down.  I'll add that watching the container output with `docker logs -f containerId` does not prevent the hangup.  When it occurs, the logs just stop.
