### ISSUE TITLE
tainerd

### ISSUE THREAD

**Issue by edovale** [docker/docker#31544]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
guess this was opened by accident, so let me close

**Comment by edovale** [comment]
so sorry. I am not sure how I did this.

**Comment by thaJeztah** [comment]
There's a keyboard shortcut on GitHub; `c` creates a new issue, so typing `containerd<enter>` creates a new issue; depending on how fast the browser was; the issue is titled `ontainerd`, `ntainerd` 😂 

Yup, it happens regularly 😄
