### ISSUE TITLE
Feature request: v2 Docker Compose support + using libcompose

### ISSUE THREAD

**Issue by cdrage** [docker/docker#31541]
Couldn't find any issues related to this.

Implementing docker stack deploy support for v2 as well as using the [docker/libcompose](https://github.com/docker/libcompose) library would be *grand*. 

Meaning we would only need to install one binary (docker) instead of docker + docker-compose to the host system.

Of course, this means we would have to implement https://github.com/aanand/compose-file 's parser into libcompose and then import libcompose into the Docker binary.

**Comment by thaJeztah** [comment]
Unlikely going to happen. Docker Compose now supports the V3 format, and we're working on adding more of the Docker Compose functionality.

/cc @ehazlett @dnephin who may know more

**Comment by dnephin** [comment]
We won't be implementing Compose V2 format, but as swarm mode gains features we will be able to add them to the V3 format.

**Comment by vdemeester** [comment]
As @dnephin @thaJeztah said, it's very unlickely to happen. `docker/libcompose` should support v3 to be "feature-parity" with `docker-compose` but libcompose is not meant to be imported into docker/docker.

**Comment by thaJeztah** [comment]
Let me close this issue, per the discussion above, but feel free to continue the conversation
