### ISSUE TITLE
Provide a way to dynamically link the containers

### ISSUE THREAD

**Issue by farcaller** [docker/docker#3155]
Currently, it is possible to link a container to an already running container, so if the linked container has to restart — all its dependencies have to restart.

Consider the following setup with four containers:
 * _db_
 * _app1_, links to _db_
 * _app2_, links to _db_
 * _frontend_, links to _app1_ and _app2_

They have to be started in order: _db_, _app1_, _app2_, _frontend_.

Now, I want to update the _app1_, so I turn it down. It's still displayed as a link in `docker ps` for _frontend_ (see also #3154).

When time comes, I start a new _app1_, but at this point I somehow need to tell _frontend_ where is the new one _app1_. The simple way to do that is restarting _frontend_ as well, but that might interrupt connectivity to _app2_.

There should be a way to interlink existing containers.

**Comment by abesto** [comment]
+1

This would be great.

**Comment by thaJeztah** [comment]
For those following this issue; there's a work-in-progress proposal for a completely revised network-model in Docker based on plug-ins. Links will (probably - and if I understand correctly) replaced with a new concept, based on "end points". You can follow progress here: https://github.com/docker/docker/issues/9983

**Comment by tehsenaus** [comment]
+1

At the moment if the source container crashes, all dependent containers must be restarted too. A big problem for fault tolerance.

**Comment by cpuguy83** [comment]
@tehsenaus That should no longer be the case, except with the env vars themselves. The `/etc/hosts` entries are kept up to date.

**Comment by tehsenaus** [comment]
@cpuguy83 OK - do you know which version this is fixed in?

**Comment by cpuguy83** [comment]
@tehsenaus Probably 1.3?... I know there was a bug in the updater that got fixed in 1.5, where if you used an alias for the link name (ie `--link crazy_wozniak:db`), it was not updating properly, where as if you used the actual container name for both it was.

So basically 1.5 should work 100% there.

**Comment by tgpfeiffer** [comment]
@cpuguy83 Really, `/etc/hosts` is updated when a linked container is restarted? (Only when it crashes?) Is there any documentation to which extent this holds etc.?

**Comment by cpuguy83** [comment]
@tgpfeiffer https://docs.docker.com/userguide/dockerlinks/#updating-the-etchosts-file
It's always updated any time the linked container is started.

**Comment by netroby** [comment]
How are things going on. This is really problem.

**Comment by cpuguy83** [comment]
@netroby What is a problem exactly?

**Comment by netroby** [comment]
Once docker container been created, how to change the link?

Can it be done like 
```
docker modify my-container-name  --link   db2:db
```

**Comment by knutole** [comment]
Hate to rain on the parade here, but I seem to be having the same problem. 

That is, if I start a `nginx` container like so: `docker run --name nginx --link vile:vile --link wu:wu -p 443:443 -p 80:80 -d systemapic/nginx-server`, the nginx.conf which references `wu` is all good. 

On `docker restart nginx`, however, I get `nginx: [emerg] host not found in upstream "wu:3001" in /etc/nginx/sites-enabled/dev.randomdomain.com.conf:17`. It's as if the restart doesn't include `--link`s at all?

I'm very new to Docker, so could totally be my own wrongdoing. Input appreciated.

Docker version: 
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef

**Comment by cpuguy83** [comment]
@knutole I think nginx caches hostnames

**Comment by knutole** [comment]
@cpuguy83 Thanks. What does that mean in practice though? The container in which `nginx` runs is created anew after restart, right? So that all data in container should be the same? So where does `nginx` store cache? The problem doesn't seem to be with the link `wu` storing wrong IP - the link is not in `/etc/hosts` after restart from what I can understand.

**Comment by cpuguy83** [comment]
@knutole Ok, this is a separate thing. I'd be happy to try to troubleshoot on #docker on IRC, or docker-user mailing list.

**Comment by gauravsingh85** [comment]
Hi 
I have two container "app" and "db" . app is liked to "db". if "db is rebooted . the linking breaks and "app" stopped communicating with "db" unless i reboot "app". this happening because /etc/hosts does not update dynamically .

i see few links posted above non of them have the solution for dynamic updating of /etc/hosts ....... any idea how can i solve this

**Comment by cpuguy83** [comment]
@gauravsingh85 `/etc/hosts` is automatically in this scenario as of docker 1.5

**Comment by gauravsingh85** [comment]
thankyou for the reply 
The container is in Links:null state 
docker inspect app|less
        "Links": null,
        "LxcConf": [],
        "NetworkMode": "bridge",
        "PortBindings": {
            "xxxx/tcp": [
                {
                    "HostIp": "xxxx",
                    "HostPort": "xxxx"
                }
            ]

**Comment by etopian** [comment]
Also what if you want to upgrade the database? You should be able to delete the database container and start a new one with the same name and have links re-established when you restart the client container.

**Comment by etopian** [comment]
@gauravsingh85 use a DNS server.

**Comment by gauravsingh85** [comment]
@cpuguy83 updating to 1.5 or 1.6 does not dynamically updated /etc/resolve the conf

procedure
1) Update docker from 1.4 to 1.5 (later i updated to 1.6 but same result)
2)reboot
3) login in to app container and run ping to db
4)restart db container (systemctl restart db.service)

Result
Ping test failed in app container . app container stooped pinging to db

**Comment by cpuguy83** [comment]
@gauravsingh85 What does db.service do to start the container?

**Comment by gauravsingh85** [comment]
Db.service has command 

ExecStart=/usr/local/bin/docker run --rm --name app --link app-db:db -p 127.0.0.1:XXX:XXX

**Comment by thaJeztah** [comment]
The `-rm` (which sh

**Comment by thaJeztah** [comment]
sorry, bump in the road while typing.

the `-rm` (which should be `--rm`, but that's irrelevant here) could be the issue; will the container actually be *removed* and re-created when the service is restarted?

**Comment by donbora** [comment]
@thaJeztah it did recreated with new ip . i used "docker ps" to keep track of the VM

**Comment by thaJeztah** [comment]
@donbora but is it the same container, or a new container (with the same name)? If the container gets a new ID after the service is restarted, that means that the original "db" container is removed and a new container is created. Because it's a *new* container, there will no longer be a link between the `app` and `db` container; the `/etc/hosts` will also no longer be updated.

**Comment by joakim666** [comment]
I have also noticed this problem with /etc/hosts not getting updated and I also use the --rm switch.

But surely that is a valid use case? E.g. rebuilding the database container with a new version of the database server.

Or like I do, rebuild my api services container and deploy it and expect the backend services running in other containers to be able to access the api container without having to restart them?

**Comment by thaJeztah** [comment]
> But surely that is a valid use case? E.g. rebuilding the database container with a new version of the database server.

@joakim666 Automatic linking to a different container, *just* based on the name could be a potential security risk. Links are established and updated to a *specific* container (-id). If you need to dynamically create links, a discovery service sounds like a better approach (but discussing that further would be beyond the discussion here)

**Comment by aigarius** [comment]
@thaJeztah could you expand on the security risks of linking just based on container name? AFAIK these name can only be user specified on container start.

**Comment by cpuguy83** [comment]
@aigarius No, names are generated by docker as well.
Docker can't assume that the new container is indeed the one replacing the old one.

**Comment by aigarius** [comment]
@cpuguy83 as far as I read in the docs, the user still must remove the old container before the name becomes available. What are the changes that the same name would be reused automatically? Also you could simply document that one should only use linking with user supplied container names in a form that docker would not be able to autogenerate. In that case only a user can start a new container with such name and he can only do so intentionally.

**Comment by joakim666** [comment]
@thaJeztah I understand there might be security considerations but I think the usefulness of linking containers diminishes greatly if it doesn't handle the rebuilding scenario. Sure, one can use some kind of discovery service but that's a lot more complicated than just linking a few containers together.

How about somehow when starting the new container one could provide the container id of the container it replaces? Docker would then know the relationship between the two containers and could update the links accordingly. Though I guess that doesn't improve much over creating a new container with the same name.

**Comment by tgpfeiffer** [comment]
> If you need to dynamically create links, a discovery service sounds like a better approach (but discussing that further would be beyond the discussion here)

@thaJeztah I guess that with a discovery service I could not use icc=false, could I? Like, I would have to allow inter-container communication because I have to be ready to connect anywhere anytime, is that right?

**Comment by mitchcapper** [comment]
I think a flag on starting a container to allow links to be updated would solve the security issue.  If a container is started with said flag then any linked containers that are restarted with the same name are automatically re-linked.  This prevents accidental re-linking as the user has to specifically specify the re-link flag for this mode to be activated.

**Comment by cpuguy83** [comment]
Closing as this is handled by the new built-in service discovery.
The way it works is you'd add `--publish-service <name>` to your run command, and that will be available via DNS.
If you remove and create a new container, assuming you published the service with the same name, it will update accordingly.

**Comment by thaJeztah** [comment]
For those interested, the `--publish-service` feature is part of the experimental builds, more info can be found here: https://github.com/docker/docker/tree/master/experimental  and https://github.com/docker/docker/blob/master/experimental/networking.md

Feedback on this can be posted here; https://github.com/docker/docker/issues/14083

**Comment by shatil** [comment]
Moral of the story:

`--publish-service` was renamed to `--net`. To let containers one another without `--link`:
* Create a network using `docker network create $NETWORK_NAME`
* Create your containers using `docker create --net $NETWORK_NAME`

You can then refer to containers sharing the same network by their hostname (either the `--name` you passed in to `create`/`run`, or `docker inspect --format '{{.Config.Hostname}}' $CONTAINER_ID`).

```
$ docker network create middle_earth
2533f0e8688170dae6a7524d517229b2944b8ae97a90f127811d4026237d9af7

$ docker run --name shire --detach --net middle_earth httpd:2.4
857986782e9cc040c6b421d703e9f1522ed767b57e11c81f8352e07036f4ea16

$ docker run --name mordor --detach --net middle_earth httpd:2.4
5f798add4b8df14c5d8ae7aeecbda85d69eb731a6bbcf01be118c5dced7f1a7c

$ docker exec -t mordor ping -c 2 shire
PING shire (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.087 ms
64 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=0.137 ms
--- shire ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.087/0.112/0.137/0.025 ms

$ docker inspect --format '{{.Config.Hostname}}' shire
857986782e9c

$ docker exec -t mordor ping -c 2 857986782e9c
PING 857986782e9c (172.18.0.2): 56 data bytes
64 bytes from 172.18.0.2: icmp_seq=0 ttl=64 time=0.083 ms
64 bytes from 172.18.0.2: icmp_seq=1 ttl=64 time=0.094 ms
--- 857986782e9c ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 0.083/0.088/0.094/0.000 ms
```
