### ISSUE TITLE
Possible docker 1.12.5 problem with Centos 7.3 upgrade

### ISSUE THREAD

**Issue by RidiculousRichard** [docker/docker#31556]
**Description**

After running yum upgrade (to Centos 7.3) the Centos distribution docker 1.12.5 is unable to complete a docker build due to an oci runtime error apparently due to a missing /var/lib/docker/devicemapper/mnt/..../rootfs directory.
Reverting back to a VM snapshot from ~ two weeks ago when docker was working normally after the snapshot was made and, with or without removing all containers / images / volumes, repeating the yum upgrade yields the same result upon trying docker build.

**Steps to reproduce the issue:**

1. Have a Dockerfile containing:
"""
From alpine

COPY . /
RUN /docker-build/build
CMD ["/bin/sleep","infinity"]
"""
2. Have a docker-build/build file containing:
"""
#!/bin/sh

set -ex

apk update
apk add bash
apk add coreutils
apk add go
apk add git
apk add make
apk add xz
"""
3. Attempt to build the image with docker build -t golang-build:latest .

**Describe the results you received:**

Docker pulled the base alpine normally, says it copied the build script into the image but threw the oci runtime error while executing the build script:

"""
$ docker build -t golang-build:latest .
Sending build context to Docker daemon 4.608 kB
Step 1 : FROM alpine
Trying to pull repository docker.io/library/alpine ... 
latest: Pulling from docker.io/library/alpine
627beaf3eaaf: Pull complete 
Digest: sha256:58e1a1bb75db1b5a24a462dd5e2915277ea06438c3f105138f97eb53149673c4
 ---> 4a415e366388
Step 2 : COPY . /
 ---> 641277111855
Removing intermediate container f49d4e90b877
Step 3 : RUN /docker-build/build
 ---> Running in 56e0411caa59
container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/var/lib/docker/containers/56e0411caa59d37303a221bd06cca92810250db517db7e06e92167cef383696f/secrets\\\" to rootfs \\\"/var/lib/docker/devicemapper/mnt/a8aa9c7063f2d2e4d682096cb0eba25f783e43a14d25088c4ccbb4cd2451bc7d/rootfs\\\" at \\\"/run/secrets\\\" caused \\\"lstat /var/lib/docker/devicemapper/mnt/a8aa9c7063f2d2e4d682096cb0eba25f783e43a14d25088c4ccbb4cd2451bc7d/rootfs/run/secrets: not a directory\\\"\""
invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:54: mounting \\\\\\\"/var/lib/docker/containers/56e0411caa59d37303a221bd06cca92810250db517db7e06e92167cef383696f/secrets\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/a8aa9c7063f2d2e4d682096cb0eba25f783e43a14d25088c4ccbb4cd2451bc7d/rootfs\\\\\\\" at \\\\\\\"/run/secrets\\\\\\\" caused \\\\\\\"lstat /var/lib/docker/devicemapper/mnt/a8aa9c7063f2d2e4d682096cb0eba25f783e43a14d25088c4ccbb4cd2451bc7d/rootfs/run/secrets: not a directory\\\\\\\"\\\"\"\n"
"""

The /var/lib/docker/devicemapper/mnt/a8aa9c7063f2d2e4d682096cb0eba25f783e43a14d25088c4ccbb4cd2451bc7d/ directory does not contain a rootfs directory

$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS               NAMES
56e0411caa59        641277111855        "/bin/sh -c /docker-b"   About a minute ago   Created                                 elegant_bohr

$ docker images -a
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
`<none>`             `<none>`              641277111855        2 minutes ago       3.984 MB
docker.io/alpine    latest              4a415e366388        43 hours ago        3.984 MB

**Describe the results you expected:**

Previously docker built the image and docker images -a would show docker.io/alpine and the build image with the specified name and tag would appear and there would be nothing in docker ps -a

**Additional information you deem important (e.g. issue happens only occasionally):**

Since the yum upgrade to Centos 7.3 I have been unable to do any docker builds due to the problem above.  The name of the container appearing due to the docker build changes on every attempt.  The os user is in the docker group to perform all docker operations as a non-privileged user.

The closest existing issue I could find is https://github.com/docker/docker/issues/28109 but that appears to be a /sys/fs/cgroup problem which is not being reported here.

**Output of `docker version`:**

```
Client:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.5
 API version:     1.24
 Package version: docker-common-1.12.5-14.el7.centos.x86_64
 Go version:      go1.7.4
 Git commit:      047e51b/1.12.5
 Built:           Mon Jan 23 15:35:13 2017
 OS/Arch:         linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 2
Server Version: 1.12.5
Storage Driver: devicemapper
 Pool Name: centos-docker--pool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 60.29 MB
 Data Space Total: 27.92 GB
 Data Space Available: 27.86 GB
 Metadata Space Used: 73.73 kB
 Metadata Space Total: 109.1 MB
 Metadata Space Available: 109 MB
 Thin Pool Minimum Free Space: 2.791 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: null bridge host overlay
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-514.10.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 3.702 GiB
Name: localhost.localdomain
ID: ITFX:BTFW:TKNH:XZ77:LXGN:2SD5:SGPE:ZC3B:COAB:PHMY:O2NR:Y3LZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VirtualBox 5.0.32 running on Windows 7 64bit pro

VM is Centos 7.3
$ rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64

Virtualbox guest additions are installed and appear to be working normally

Disks are not full
$ df
Filesystem              1K-blocks      Used Available Use% Mounted on
/dev/mapper/centos-root  20961280   5822412  15138868  28% /
devtmpfs                  1925036         0   1925036   0% /dev
tmpfs                     1940864        80   1940784   1% /dev/shm
tmpfs                     1940864      8912   1931952   1% /run
tmpfs                     1940864         0   1940864   0% /sys/fs/cgroup
/dev/sda1                  508580    314972    193608  62% /boot
/dev/mapper/centos-home  10475520   1051912   9423608  11% /home
tmpfs                      388176         4    388172   1% /run/user/992
VmShare                 966214652 288862344 677352308  30% /media/sf_VmShare
tmpfs                      388176        24    388152   1% /run/user/1000
$ sudo lvdisplay
  --- Logical volume ---
  LV Path                /dev/centos/root
  LV Name                root
  VG Name                centos
  LV UUID                V3PdeT-eF3c-yd2l-rNNp-mSjE-KBIZ-7hlSdF
  LV Write Access        read/write
  LV Creation host, time localhost.localdomain, 2017-02-10 22:41:57 +0000
  LV Status              available
 ` # open                 1`
  LV Size                20.00 GiB
  Current LE             5120
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:0
   
  --- Logical volume ---
  LV Path                /dev/centos/home
  LV Name                home
  VG Name                centos
  LV UUID                cLdgQy-gRpY-vhiU-73hL-t1xP-2dyO-x1z4Fv
  LV Write Access        read/write
  LV Creation host, time localhost.localdomain, 2017-02-10 22:41:59 +0000
  LV Status              available
  `# open                 1`
  LV Size                10.00 GiB
  Current LE             2560
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:2
   
  --- Logical volume ---
  LV Path                /dev/centos/swap
  LV Name                swap
  VG Name                centos
  LV UUID                PqR0HU-TbW3-Ew4C-gET1-f7aP-OVRB-5xhx5H
  LV Write Access        read/write
  LV Creation host, time localhost.localdomain, 2017-02-10 22:42:00 +0000
  LV Status              available
  `# open                 2`
  LV Size                4.00 GiB
  Current LE             1024
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:1
   
  --- Logical volume ---
  LV Name                docker-pool
  VG Name                centos
  LV UUID                TtSvhh-Yb8c-8yGo-dnHk-tWwm-4ujD-MejUJX
  LV Write Access        read/write
  LV Creation host, time localhost.localdomain, 2017-02-10 23:02:07 +0000
  LV Pool metadata       docker-pool_tmeta
  LV Pool data           docker-pool_tdata
  LV Status              available
  `# open                 0`
  LV Size                26.00 GiB
  Allocated pool data    0.22%
  Allocated metadata     0.07%
  Current LE             6656
  Segments               1
  Allocation             inherit
  Read ahead sectors     auto
  - currently set to     8192
  Block device           253:5

**Comment by RidiculousRichard** [comment]
I was all excited that there was someone around who was looking at this.
Then I eventually twig that Gordon is a bot; and ironically there is just the right expression on the top of it's twitter feed.

**Comment by friism** [comment]
cc @andrewhsu

**Comment by thaJeztah** [comment]
It looks like you're running the Red Hat fork of docker (https://github.com/projectatomic/docker/tree/docker-1.12.5), that fork contains thousands of lines of changes that are not in this repository, and not part of the official packages (https://github.com/docker/docker/compare/v1.12.5...projectatomic:docker-1.12.5). The error about `/run/secrets` looks to be related to their "super secrets patch"; https://github.com/projectatomic/docker/commit/81723f6590cfb9c6a770fd12137405b1be29d9d6

Are you having the same problem if you run the official packages? Installation instructions for the old 1.12.x version can be found here; https://docs.docker.com/v1.12/engine/installation/linux/centos/. And for the current 17.03 release here; https://docs.docker.com/engine/installation/linux/centos/

**Comment by RidiculousRichard** [comment]
I will try the latest version and let you know how that goes

**Comment by RidiculousRichard** [comment]
The docker CE 17.0.3 stable upgrade did work after some teething difficulties.

Could you indulge me with a final question to close this off: How do I confirm docker is still using the Logical Volume docker-pool for storing the docker containers given the disappearance of /etc/sysconfig/docker-storage?

Thank you for your help. 

--------------------------------------------------------------------------------------------------- 

Notes for others that come across the same problem:

I found upgrading docker before updating Centos to be smoother.

I ended up clearing out all containers, images and removed the /var/lib/docker directory to get it working

Like https://github.com/docker/docker/issues/16341 I had an oddity with /etc/sysconfig/docker-storage below.  It used to contain:
"""
 DOCKER_STORAGE_OPTIONS="--storage-driver devicemapper --storage-opt dm.fs=xfs --storage-opt dm.thinpooldev=/dev/mapper/centos-docker--pool --storage-opt dm.use_deferred_removal=true "
"""

$ sudo yum remove docker \
>                   docker-common \
>                   container-selinux \
>                   docker-selinux \
>                   docker-engine
...snip...
warning: /etc/sysconfig/docker-storage saved as /etc/sysconfig/docker-storage.rpmsave
...snip...

Attempting to start the new docker version (17.0.3) fails because of device mapper
$ sudo systemctl start docker
[sudo] password for rmd: 
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.
$ systemctl status -al docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2017-03-05 19:45:43 GMT; 11s ago
     Docs: https://docs.docker.com
  Process: 5813 ExecStart=/usr/bin/dockerd (code=exited, status=1/FAILURE)
 Main PID: 5813 (code=exited, status=1/FAILURE)

Mar 05 19:45:42 dev systemd[1]: Starting Docker Application Container Engine...
Mar 05 19:45:42 dev dockerd[5813]: time="2017-03-05T19:45:42.829955902Z" level=info msg="libcontainerd: new containerd process, pid: 5820"
Mar 05 19:45:43 dev dockerd[5813]: time="2017-03-05T19:45:43.972175232Z" level=warning msg="devmapper: Usage of loopback devices is strongly discouraged for production use. Please use `--storage-opt dm.thinpooldev` or use `man docker` to refer to dm.thinpooldev section."
Mar 05 19:45:43 dev dockerd[5813]: time="2017-03-05T19:45:43.990454985Z" level=error msg="[graphdriver] prior storage driver devicemapper failed: devmapper: Base Device UUID and Filesystem verification failed: devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed"
Mar 05 19:45:43 dev dockerd[5813]: Error starting daemon: error initializing graphdriver: devmapper: Base Device UUID and Filesystem verification failed: devicemapper: Error running deviceCreate (ActivateDevice) dm_task_run failed
Mar 05 19:45:43 dev systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Mar 05 19:45:44 dev systemd[1]: Failed to start Docker Application Container Engine.
Mar 05 19:45:44 dev systemd[1]: Unit docker.service entered failed state.
Mar 05 19:45:44 dev systemd[1]: docker.service failed.

For some unknown reason you can't just rm -fr the /var/lib/docker directory, even after a reboot so move it instead and delete it after a reboot
$ sudo mv /var/lib/docker /var/lib/xdocker

PS: Who precisely is obsessed with McNulty???

**Comment by thaJeztah** [comment]
w.r.t. the `DOCKER_STORAGE_OPTIONS`; their package uses a custom way to set daemon settings, which is not used in the official packages. To set custom daemon options, either use systemd drop in files (see https://docs.docker.com/engine/admin/systemd/#custom-docker-daemon-options), or - the recommended way; use a `daemon.json` configuration file (which works irregardless of the init system used); https://docs.docker.com/engine/reference/commandline/dockerd/#linux-configuration-file
