### ISSUE TITLE
When update a tasks , what's the specific definition of task FAILED ?

### ISSUE THREAD

**Issue by erxian** [docker/docker#31563]
Hi,
    Recently I found there are several flags added into `docker service update` command, one of them is 

  `--update-failure-action`  string,  the description is "action on update failure (pause|continue) (default "pause")"

then I check the docs to figure out the definition of  task failure,  while all information I can get is : "When an update to an individual task,  if at any time during an update the task returns FAILED, the scheduler pauses the update". https://docs.docker.com/engine/swarm/services/#configure-update-behavior 

However, there is no specific description about FAILED, so how can I troubleshoot the problem after received a FAILED?

What I expect is the specific definition of task FAILED .

My docker version:

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:42:29 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by allencloud** [comment]
I think there are two levels of failure, one is for service, the other is more fundamental which is for task?
And I hope to make sure the concept as well. ping @aaronlehmann

**Comment by aaronlehmann** [comment]
@allencloud: Yes, that's the right way to think about it. A paragraph just below in the docs explains this a bit:


> The --update-max-failure-ratio flag controls what fraction of tasks can fail during an update before the update as a whole is considered to have failed. For example, with --update-max-failure-ratio 0.1 --update-failure-action pause, after 10% of the tasks being updated fail, the update will be paused.

**Comment by thaJeztah** [comment]
Given that this is not a bug report or a feature request, I'll close this issue for housekeeping, but feel free to continue the conversation 👍

**Comment by erxian** [comment]
@aaronlehmann thanks for your explain, actually, I'm more curious about what's the definition of a **FAILURE** when updating, instead of just a **FAILED** result. 

For example, if the task container with updated configuration **NOT RUNNING** means failed? Or if the health check of the task container showing **UNHEALTHY** means failed ?

**Comment by aaronlehmann** [comment]
> For example, if the task container with updated configuration NOT RUNNING means failed? Or if the health check of the task container showing UNHEALTHY means failed ?

Ah, yes. If a task terminates within a certain time period of being started by the updater, it's considered to have failed. Having the health check not pass will cause it to terminate, so it's one of the cases that would be considered a failure.

The time period is defined by `--update-monitor`. It defaults to 30 seconds (but we're changing it to 5 seconds in the next version).

**Comment by erxian** [comment]
@aaronlehmann Your words really really helps a lot ! Cause I finally found some clues about `task failed` within the source codes. I'll ramp up on it :)

BTW, I notice that   ` --update-monitor duration    Duration after each task update to monitor for failure (ns|us|ms|s|m|h) (default 0s)`  indicates the default period time if `0s`,  is there a conflict between the above 30 seconds ?

**Comment by aaronlehmann** [comment]
You're right - the CLI help is incorrect here. Would you be interested in opening an issue or PR? This is very similar to https://github.com/docker/docker/issues/29291, which was fixed by https://github.com/docker/docker/pull/29450

**Comment by erxian** [comment]
@aaronlehmann Absolutely, I'll take time to  correct it and ping you later. And thanks again for your patient answers :)
