### ISSUE TITLE
Display tags of the particular image searched via `docker search` command

### ISSUE THREAD

**Issue by borntorock** [docker/docker#31569]
Would be great for users to see the available tags of the particular image searched via `docker search` command. 

Somewhat may be like `docker search tags ubuntu` should display all the tags of the ubuntu image present in docker hub.

**Comment by thaJeztah** [comment]
Thanks for suggesting. This is a duplicate of https://github.com/docker/docker/issues/17238, so let me close this one. Please subscribe to that issue to keep informed on updates 👍
