### ISSUE TITLE
"docker stack deploy">"rpc error: code = 3 desc = name must be valid as a DNS name component"

### ISSUE THREAD

**Issue by JingYang0725** [docker/docker#31564]
[root@master busybox]# docker stack deploy -c docker-compose.yml test
Creating service test_busybox1.24
Error response from daemon: rpc error: code = 3 desc = name must be valid as a DNS name component

[root@master busybox]# cat docker-compose.yml
version: "3"
services:
  busybox1.24:
    image: hub.c.163.com/library/busybox:1.24

Thanks!

**Comment by vdemeester** [comment]
```
λ docker service create --name test_busybox1.24 busybox
Error response from daemon: rpc error: code = 3 desc = name must be valid as a DNS name component
```

@JIngYang0725 the name of your service is not allowed for service name it seems. I guess the `.` is not allowed by the service API and thus by `stack` too.

/cc @dnephin @aaronlehmann

**Comment by JingYang0725** [comment]
@vdemeester Have nothing to do with the name
`[root@master busybox]# docker stack deploy -c docker-compose.yml vdemeester
Creating network vdemeester_default
Creating service vdemeester_busybox1.24
Error response from daemon: rpc error: code = 3 desc = name must be valid as a DNS name component`

**Comment by vdemeester** [comment]
@JingYang0725 I mean the name of the service, `busybox1.24` (with a `.`), not the stack name…

**Comment by JingYang0725** [comment]
Thank you very much! @vdemeester

**Comment by OJFord** [comment]
Although, for what it's worth, the stack name must also not contain `.` (as I just found out - thanks!) 🙂 .

**Comment by akki** [comment]
Also, it cannot end with an `_` as I found out today. Hope that saves someone else's time 😅

**Comment by arseniybanayev** [comment]
Also it must be 63 characters long or less: https://github.com/moby/moby/issues/36487
