### ISSUE TITLE
Cannot pull nanoserver on Windows 10 Pro. I'm getting unknown blob error

### ISSUE THREAD

**Issue by elranu** [docker/docker#31572]
**Description**
Cannot pull nanoserver on Windows 10 Pro. I'm getting unknown blob.

**Steps to reproduce the issue:**
```
docker pull microsoft/nanoserver
```

**Describe the results you received:**
```
docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Pulling fs layer
3ac17e2e6106: Downloading
unknown blob
```

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
C:\dev\Git> docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
C:\dev\Git> docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 973.8 MiB
Name: moby
ID: MX76:WBC5:LEBY:WSD4:ETCO:6DMP:6VRE:F4S7:D4TT:BQF2:LJW4:4DVF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 26
 Goroutines: 35
 System Time: 2017-03-06T12:32:57.6200391Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by AkihiroSuda** [comment]
The server seems linux

**Comment by thaJeztah** [comment]
Yes, to run native windows containers, you need to switch to "Switch to Windows containers..." in the GUI; https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers

I'll close this issue, because this doesn't look like a bug, but feel free to continue the conversation

**Comment by elranu** [comment]
:( ok. Thanks. 
So there is no way to run linux and windows contaners on the same PC at the same time? So If I wanna to develop in a nanoserver and I want also other containers running with some services such as RabbitMQ, Redis, mongo, etc. in linux that is not possible, right?

**Comment by elranu** [comment]
Also the error message should be change. Is a bad error message for possible regular situation.

**Comment by thaJeztah** [comment]
There's a pull request merged to do the opposite on Windows (see https://github.com/docker/docker/pull/24819). There was some discussion about this in https://github.com/docker/docker/pull/28903, but not sure what the final conclusion was

**Comment by simonferquel** [comment]
With Docker for Windows, if you switch back and forth from Linux to Windows containers, we don't stop the engine (we just switch where your client is pointing to). So you can run both Windows and Linux containers at once.

In the future we will provide a better way to indicate which engines are currently started / stopped and where the client points to.
