### ISSUE TITLE
Enhancement: Required Env Variables: Assisting with Container Configuration

### ISSUE THREAD

**Issue by odonnellryan** [docker/docker#3157]
Partially copied from an email to Solomon and a thread in the Google Group: https://groups.google.com/forum/#!topic/docker-user/uKlzScdU1Fk (full discussion can be found here)

*
Goal: To configure containers without any previous knowledge of what's running in the container, and define a standard way in order to configure container internals  programatically (a way to discover and set the required configuration parameters).

Use Case:  Blog App XYZ: Having a prompt to arbitrarily set the root password, mysql password, and even the blog username and password at the moment a container is run. 

Proposal: A way to mark environment variables as required by passing a new command.

Example:

REQ_ENV user "Please specify a username: " 
REQ_ENV password "Please specify a password: " 
CMD useradd $user && passwd $user $password

When someone runs the image built with this dockerfile they could be prompted (in stdin or json) for the username and password field.

1. https://groups.google.com/forum/#!topic/docker-user/FyCWLC38Ueg
2. http://docs.docker.io/en/latest/use/builder/
*

I'd love to hear comments and discuss implementation details!

**Comment by jfrazelle** [comment]
I think can can be accomplished with #3254, `ONBUILD`
or setting the image `ENV` in the Dockerfile and allowing the user to override the env with `-e` on create.
