### ISSUE TITLE
--cpus parameter can not be updated with Windows Server containers and docker inspect alwasy shows CpuCount equals 0

### ISSUE THREAD

**Issue by georgyturevich** [docker/docker#31575]
Hello there,

I am running my test "microsoft/iis" container with following command with "--cpus 16" limitation:
```
docker run -d  --name gt_test_iis --cpus 16 microsoft/iis ping -t localhost
```

Looks like "--cpus" works fine and when I run my `simulate_cpu_load.ps1` script:
```
ForEach ($Number in 1..16){
   start-job -ScriptBlock{
      $result = 1; foreach ($number in 1..2147483647) {$result = $result * $number}
   }
}
```

I got only about 16% CPU on my 64 cpus virtual machine. 

When I wanted to change CPU limits online I tried `docker update` and got expected error (as --cpus flag is not described there https://docs.docker.com/engine/reference/commandline/update/#options):
```
PS> docker update --cpus 1 gt_test_iis
unknown flag: --cpus
See 'docker update --help'.
```

But on the API documentation page for "docker update" ( https://docs.docker.com/engine/api/v1.26/#operation/ContainerUpdate ) we have following option `CpuCount`, so from my understanding "docker update" should have "--cpus" parameter.

Another thing I found is that changing the value of `CpuCount` by Web API does not affect running container.

When I tried to invoke it in Powershell console:

```
Invoke-WebRequest -Uri http://hostname:2375/containers/gt_test_iis/update -Method POST -Body '{"CpuCount":1}' -ContentType 'application/json'
```
it returned 200
```
StatusCode        : 200
StatusDescription : OK
Content           : {"Warnings":[]}

RawContent        : HTTP/1.1 200 OK
                    Api-Version: 1.26
                    Docker-Experimental: false
                    Content-Length: 16
                    Content-Type: application/json
                    Date: Mon, 06 Mar 2017 12:32:40 GMT
                    Server: Docker/1.13.1-cs1 (windows)

                    {"Warnin...
Forms             : {}
Headers           : {[Api-Version, 1.26], [Docker-Experimental, false], [Content-Length, 16], [Content-Type, application/json]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : mshtml.HTMLDocumentClass
RawContentLength  : 16
```

but the container continued to consume 16% of CPU load.

I also found that "docker inspect" always shows `"CpuCount": 0,` even it was run with "--cpus 16" or without "--cpus" at all, and it was not changed when I run `Invoke-WebRequest` above.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1-cs1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:05:36 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1-cs1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   8709b81
 Built:        Thu Feb  9 02:05:36 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 248
 Running: 111
 Paused: 0
 Stopped: 137
Images: 1201
Server Version: 1.13.1-cs1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 64
Total Memory: 1.906 TiB
Name: skipped
ID: 62EZ:P3MP:SQ3U:3UET:3JAP:QLAU:X2O4:E5NA:7WAH:BUGN:CAQT:VZ5V
Docker Root Dir: E:\docker_storage_1_13
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 721
 System Time: 2017-03-06T13:49:13.9906709Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
It is x1.x32large AWS instance. But the issue was reproduced on all our Docker 1.13.1-cs1 installations.

**Comment by yongtang** [comment]
Thanks @georgyturevich for the report. There is a PR #31148 pending for `docker update --cpus` however it does not cover Windows.

The flag `--cpus` is mapped to `NanoCPU` in `HostConfig` while `--cpu-count` is mapped to `CpuCount`. `--cpus`/`NanoCPU` is platform independent while `--cpu-count`/`CpuCount` works on Windows only.

I don't have a Windows setup at the moment so not able to give it a try. But I am wondering if you could perform a `docker inspect <container id>` and post the output?

**Comment by darrenstahlmsft** [comment]
This is due to the way that CPU limiting with `--cpus` works on Windows Server Containers. Windows Server Containers (currently) default to 2 virtual CPUs in the platform, and the `--cpus` limits using throttling with the assumption that all host CPUs are available to the container.

You can set the number of virtual CPUs with `--cpu-count` which will let your Windows Server Containers use more than 2 virtual CPUs, and use `--cpu-percent` to limit each of these virtual CPUs if you need more fine grain throttling.

I need to think more on what the correct fix to `--cpus` is for Windows Server Containers, as there could be perf implications depending on how it is implemented.

cc @patricklang FYI
