### ISSUE TITLE
Want a way to remount a volume to a running container

### ISSUE THREAD

**Issue by vipzhicheng** [docker/docker#31591]
I use cloud9 to be my remote webide, one thing I can not figure out is that cloud9 needs a /workspace to be the project dir. I made it as a docker image, and mount it when I execute `docker run`. 

But if I want to switch to another project, I must destroy original container, It's a bad experience, so I want to know if there is a way to remount to a same directory with another host directory. It's like a usb disk feeling, I think it should be possible, but I don't know how.

Does docker cli has this feature, isn't this a good feature for others?

**Comment by cpuguy83** [comment]
This is not possible, nor do I think we should allow it.

One thing you can do is bind mount some other dir, and then add a sub-dir that is bind-mounted to the actual project you want. You'll probably need to bind with the option `rslave` (e.g. `-v /foo:/bar:rslave`) to make this work.

But honestly it seems like cloud9 should be able to host multiple projects for you, I'm not familiar with it...
