### ISSUE TITLE
Swarm - Using some port under one services 

### ISSUE THREAD

**Issue by RotemEmergi** [docker/docker#31603]
Hi !

I am using docker 1.13 on 3 swarm node .
I create 3 diffident jetty services and want that each one of them will listen op port 443:8433.
I use this yaml file : 

>   version: '3'
  networks:
    rotem:
      external: false
  services:
    webapps1:
      image: registry.gitlab.com/rotem/jetty-image:jmx
      networks:
          - rotem
      hostname: webapps1    
      ports:
          - "443:8443"
      volumes:
          - /opt/web/webapps:/var/lib/jetty/webapps
      depends_on:
          - rs1
          - rs2
          - rs3
      deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == swarm-manager]
    webapps2:
      image: registry.gitlab.com/rotem/jetty-image:jmx
      networks:
          - rotem
      hostname: webapps2    
      ports:
          - "443:8443"
      volumes:
          - /opt/web/webapps:/var/lib/jetty/webapps
      depends_on:
          - rs1
          - rs2
          - rs3
      deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == swarm-1]
    webapps3:
      image: registry.gitlab.com/rotem/jetty-image:jmx
      networks:
          - rotem
      hostname: webapps3  
      ports:
          - "443:8443"
      volumes:
          - /opt/web/webapps:/var/lib/jetty/webapps
      depends_on:
          - rs1
          - rs2
          - rs3
      deploy:
        replicas: 1
        placement:
          constraints: [node.hostname == swarm-2]

there is a way that all will answer and work on port   - "443:8443" ? 

Best regards,
Rotem

**Comment by cpuguy83** [comment]
You can use host port mode, but I think what is better in this case is to use a reverse proxy to forward to the correct service.

But also it kind of looks like you are starting the same service 3 times, in which case it would be better to use 1 service with 3 replicas and swarm will handle load balancing between the three.

**Comment by RotemEmergi** [comment]
@cpuguy83  
I put a LB on top of the 3 swarm server and start  to load test the server and monitor the jetty with jmx, jmx-remote,state .
I use at the beginning  1 service with 3 replica it's give me a bad result .

So can you show my an example of  host port mode ?

Thanks a lot !

**Comment by cpuguy83** [comment]
> with 3 replica it's give me a bad result

What sort of bad result?

I don't think the host port mode is supported in the compose format in 17.03, also I'm really sure this is not what you want.

**Comment by RotemEmergi** [comment]
@cpuguy83 
Since i use Prometheus(by using javaagent on jetty) to monitor each jetty instance/task i need to be able to get Prometheus to contact each instance directly otherwise it mess the metrics.

**Comment by cpuguy83** [comment]
@RotemEmergi This seems like a surmountable problem.
This can be gleaned from the service data, or even from a container on the same network you can lookup `tasks.{service_name}`

Example:

```
/ # nslookup tasks.tender_panini
Server:		127.0.0.11
Address:	127.0.0.11#53

Non-authoritative answer:
Name:	tasks.tender_panini
Address: 10.0.0.4
Name:	tasks.tender_panini
Address: 10.0.0.5
Name:	tasks.tender_panini
Address: 10.0.0.3
```
