### ISSUE TITLE
docker cp with windows containers crash with  hcsshim::ActivateLayer failed in Win32

### ISSUE THREAD

**Issue by ogreenz** [docker/docker#31606]
After a fresh installation of docker and pulling the container I cannot copy any file into the container
I get the following:
```
docker run -it microsoft/dotnet-framwork cmd
docker cp D:\x\1.txt <container_name>:c:\1.txt

Error response from daemon: hcsshim::ActivateLayer failed in Win32: 
The process cannot access the file because it is being used by another process. (0x20) id=d1ad2f812e3b7a37da79538611d7fb4496b0a89369b2ba430e08a28d73f1ab50 flavour=1
```
**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      windows/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 5
 Running: 1
 Paused: 0
 Stopped: 4
Images: 2
Server Version: 17.03.0-ce
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 (14393.206.amd64fre.rs1_release.160915-0644)
Operating System: Windows 10 Pro
OSType: windows
Architecture: x86_64
CPUs: 8
Total Memory: 31.91 GiB
Name: wk-ofir
ID: PKF6:LKFA:ROVD:X2LP:I2NL:HJZF:NSGN:BLOM:JDBH:RXA7:F3HQ:B3TK
Docker Root Dir: C:\ProgramData\Docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: -1
 Goroutines: 33
 System Time: 2017-03-07T15:19:34.6735797+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
ping @jhowardmsft @johnstep PTAL

**Comment by thaJeztah** [comment]
I see a similar error message in https://github.com/docker/docker/issues/29832, not sure if there's a relation

**Comment by ogreenz** [comment]
I will say that I found a way around it using a Dockerfile and a COPY command.

**Comment by jhowardmsft** [comment]
This is expected - online filesystem operations cannot be performed on a running `Hyper-V` container. They can on a `Windows Server` container. Windows 10 only supports Hyper-V containers.

**Comment by thaJeztah** [comment]
@jhowardmsft Can we improve the error message, and return a message that it's not supported? The current error is not useful.

**Comment by ogreenz** [comment]
@jhowardmsft  I must agree with @thaJeztah, this error message is completely uninformative that lead me (and possibly others) on a pursuit for something the doesn't / cannot be fixed and wasted a few hours of work.

**Comment by thaJeztah** [comment]
Yes, let me reopen; we should block this action if it's not supported by the platform

**Comment by MattyBoy4444** [comment]
Just to clarify.  cp does NOT work on Windows 10?

Hmmm...  With a docker version from a few months ago I was able to.

**Comment by jhowardmsft** [comment]
It works if the container is not running.

**Comment by MattyBoy4444** [comment]
Sweet thanks!!

**Comment by jhowardmsft** [comment]
Just to clarify - the running/online vs stopped/offline thing is a limitation of Hyper-V containers. Windows 10 only supports Hyper-V containers. Windows Server 2016 supports both Windows Server and Hyper-V containers, and defaults to Windows Server containers. Windows Server containers support both online and offline file-system operations.
