### ISSUE TITLE
Make flag on volume to not report it as dangling

### ISSUE THREAD

**Issue by ambrt** [docker/docker#31617]
Is there possibility to create "stand alone" volume flag that wouldn't be reported as `dangling`.

The reason for this is to be able to  have persistent database-only volume and being able to remove other dangling volumes without loosing the data in database when the containers of database volume are removed.

**Comment by cpuguy83** [comment]
No, tracking this with regard to `docker system prune` here: #29999
There is a PR, #30740, to support filtering by label.

Closing this one.
Thanks!
