### ISSUE TITLE
docker for aws CF upgrade

### ISSUE THREAD

**Issue by hutchic** [docker/docker#31612]
**Description**

Tried upgrading a `Docker for AWS 1.13.0` to `CloudFormation stack to 17.03.0 CE Stable` by using https://editions-us-east-1.s3.amazonaws.com/aws/stable/Docker.tmpl and got the error message:

```
CIDR Block must change if Availability Zone is changed and VPC ID is not changed
```

when the cloudformation tries to update PubSubnetAz3. This is all in AWS us-east

**Comment by thaJeztah** [comment]
Thanks for reporting; could you reopen this in the Docker for AWS issue tracker? https://github.com/docker/for-aws/issues

I'll close the issue here, but feel free to continue the conversation
