### ISSUE TITLE
Unable to run containers with MountFlags=shared and selinux

### ISSUE THREAD

**Issue by kylebyerly-hp** [docker/docker#31615]
**Description**

**Steps to reproduce the issue:**
1. boot coreos-alpha (or beta) node
2. `mkdir /etc/systemd/system/docker.service.d`
3. `echo '[Service]
MountFlags=shared' > /etc/systemd/system/docker.service.d/mountflags.conf`
4. `systemctl daemon-reload`
5. `systemctl restart docker`
6. 
```
$ docker run -it alpine sh
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"sh\": executable file not found in $PATH".
```

**Describe the results you received:**
Unable to run any containers.

**Describe the results you expected:**
Able to run a container

**Additional information you deem important (e.g. issue happens only occasionally):**
I suspect it has something to do with selinux and containerd split, this worked with docker 1.11.2

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Wed Mar  1 23:26:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   092cba3
 Built:        Wed Mar  1 23:26:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 21
 Running: 0
 Paused: 0
 Stopped: 21
Images: 4
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
 selinux
Kernel Version: 4.10.1-coreos
Operating System: Container Linux by CoreOS 1339.0.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.466 GiB
Name: c43
ID: Y4YJ:URUJ:6TD2:O6HK:KMWW:JGK5:5Q4D:WI2D:F7AU:JK4A:RWKI:PL6Y
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Reproducible with https://github.com/coreos/coreos-vagrant

**Comment by cpuguy83** [comment]
Hmm, the official docker packages (ie for ubuntu/debian/ec) uses the default mount flags, which would be shared.
It sounds like this is likely an issue with coreos's build of docker.

**Comment by thaJeztah** [comment]
I suggest reporting this with CoreOS, as this looks to be specific to their configuration. I'll go ahead and close this issue, but feel free to continue the conversation 👍

**Comment by victorgp** [comment]
@kylebyerly-hp did you report this to CoreOS? if so, can you post the link here? i want to keep track

**Comment by maxmanuylov** [comment]
@kylebyerly-hp do you have a solution or workaround? I'm facing the same issue.

**Comment by DuaneNielsen** [comment]
@kylebyerly-hp Hit the same issue in docker 18.09.5  Current docs say set MountFlags=shared but this does not work.

**Comment by thaJeztah** [comment]
For docker 18.09 and up make sure to not specify any MountFlags; see https://docs.docker.com/engine/release-notes/#18091
