### ISSUE TITLE
File cannot be excluded in .dockerignore when parent directory is included as an exception

### ISSUE THREAD

**Issue by diwo** [docker/docker#31630]
**Description**

When building an image using `docker-compose build` along with a `.dockerignore` file, if a directory is included as an exception, files under this directory cannot be excluded afterwards.

**Steps to reproduce the issue:**
Given the following directory structure:
```
$ tree -a
.
├── data
│   ├── file1
│   └── file2
├── .dockerignore
├── Dockerfile
└── docker-compose.yml
```
The following `Dockerfile`:
```
FROM busybox:1.26
COPY data /data/
```
The following `docker-compose.yml`:
```
version: '3'

services:
  compose:
    build: .
```
The following `.dockerignore`:
```
*
!data
data/file1
```
Build the image using `docker-compose build` as well as `docker build`:
```
$ docker-compose -p test build compose
$ docker build -t test_docker .
```

**Describe the results you received:**
The files copied include the file being excluded for the image built using `docker-compose build`, but not for the image built using `docker build`.
```
$ docker run --rm test_compose find /data
/data
/data/file2
/data/file1
$ docker run --rm test_docker find /data
/data
/data/file2
```

**Describe the results you expected:**
`/data/file1` should not be copied to the image built with `docker-compose build`.

**Additional information you deem important (e.g. issue happens only occasionally):**
Possibly related to https://github.com/docker/docker/issues/30018

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: V3CL:X4RL:O5MJ:BSJZ:JRNG:SVCE:672T:XPMF:5EDA:2SXO:NPMX:Y7LV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 28
 System Time: 2017-03-08T00:44:35.903208479Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: diwo
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by diwo** [comment]
Sorry the repro case isn't actually correct, let me edit it

**Comment by diwo** [comment]
Seems to only be an issue with `docker-compose`, I'll create a new issue under that project.

**Comment by tiborvass** [comment]
@diwo Thanks! feel free to link it here when you have it. I'm closing this as it is not actionable on the engine.

**Comment by diwo** [comment]
Related to issue https://github.com/docker/compose/issues/3886
