### ISSUE TITLE
udp port assignment ignored

### ISSUE THREAD

**Issue by stefanfritsch** [docker/docker#31644]
**Description**

I try to expose a udp port in a `docker stack deploy` stack. I have found no docs that say this is not possible. Nevertheless it works with `docker-compose up` but not with `docker stack deploy`.

Thanks
Stefan

**Steps to reproduce the issue:**
1. Use the following docker-compose:

```
version: "3"

services:
  h2o-gate:
    image: stefanfritsch/h2o_statup:1.1
    environment:
      H2O_MEMORY_GB: 1
    ports:
     - "54321:54321"
#     - "54322:54322"
     - "54322:54322/udp"
  h2o:
    image: stefanfritsch/h2o_statup:1.1
    environment:
      H2O_MEMORY_GB: 1
```

2. `docker stack deploy --compose-file docker-compose.yml`

**Describe the results you received:**

(scroll to ports)
```
CONTAINER ID        IMAGE                                                                                                          COMMAND                  CREATED              STATUS                      PORTS
                          NAMES
121b58ade5b3        stefanfritsch/h2o_statup@sha256:9498896c5fe45547c00eb8abd24a67fe55ef2f0b829e5e1f5f0315632b17218f               "/sbin/my_init"          51 seconds ago       Up 45 seconds               54321-54322/tcp
                          h2o_h2o-gate.1.o2b3ka34c5p4vxj9a3sud2n37
2ad3c8ce567a        stefanfritsch/h2o_statup@sha256:9498896c5fe45547c00eb8abd24a67fe55ef2f0b829e5e1f5f0315632b17218f               "/sbin/my_init"          56 seconds ago       Up 50 seconds               54321-54322/tcp
                          h2o_h2o.1.o1zx8sddyykdf4tb697pf64kh
```

**Describe the results you expected:**

This is from `docker-compose up` (scroll to ports): 
```
CONTAINER ID        IMAGE                                                                                                          COMMAND                  CREATED             STATUS                    PORTS
                       NAMES
97988c98afbd        stefanfritsch/h2o_statup:1.0                                                                                   "/sbin/my_init"          6 seconds ago       Up 4 seconds              54321-54322/tcp
                       h2o_h2o_1
3ba3f64ab03f        stefanfritsch/h2o_statup:1.0                                                                                   "/sbin/my_init"          6 seconds ago       Up 3 seconds              0.0.0.0:54321->54321/tcp, 54322/tcp, 0.0.0.0:54322->54322/udp
                       h2o_h2o-gate_1
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false
root@se-dino:/mnt/Container Data/h2o# docker info
Containers: 44
 Running: 26
 Paused: 0
 Stopped: 18
Images: 382
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 851
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 4yim33t7aol05xl29elxo3xvn
 Is Manager: true
 ClusterID: znkbs94838mpg3h1ikhk9a2yi
 Managers: 1
 Nodes: 1
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.3.102
 Manager Addresses:
  192.168.3.102:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 125.8 GiB
Name: se-dino
ID: B765:VAIM:ALFC:NU6H:RCP4:OKY2:5FI4:23VC:AOAZ:IEEN:ID5P:KGEF
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: stefanfritsch
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
When deploying services, the containers _backing_ the service are not individually published, but traffic is routed through the routing mesh / load balancer. If you inspect the _service_ you'll see that the port is published. I simplified your docker-compose file to;

```yaml
ersion: "3"

services:
  h2o-gate:
    image: nginx:alpine
    ports:
     - "80:80/udp"
```

And after deploying as `repro`, I inspected the service (`docker service inspect --pretty repro_h2o-gate`);

```
ID:		k6acx9g3ytfodxinpemq017xs
Name:		repro_h2o-gate
Labels:
 com.docker.stack.namespace=repro
Service Mode:	Replicated
 Replicas:	1
Placement:
ContainerSpec:
 Image:		nginx:alpine@sha256:aa0daf2b17c370a1da371a767110a43b390a9db90b90d2d1b07862dc81754d61
Resources:
Networks: ypwutezizftskqbv2anw8vnm2
Endpoint Mode:	vip
Ports:
 PublishedPort 80
  Protocol = udp
  TargetPort = 80
```

**Comment by thaJeztah** [comment]
You can find more information about networking in Swarm mode here; https://docs.docker.com/engine/swarm/networking/

**Comment by thaJeztah** [comment]
I'll go ahead and close this, because I think there's no bug here, but feel free to continue the discussion if I'm mistaken :blush:

**Comment by stefanfritsch** [comment]
Hi,

sorry this reply took so long.

My problem is that an h2o (machine learning, https://github.com/h2oai/h2o-3 ) server is not connecting properly when started with `docker stack deploy` but works when started with `docker-compose up`. It needs UDP 54322 and I assumed that was the issue. It works when I connect into the overlay network with a separate container so it has to be the port mapping to the host.

I'll try again when I have the time and will look into `docker service inspect`. Currently networking in `docker stack deploy` seems a bit flaky anyway so it might be that.

Thanks a lot for your reply,

Stefan

**Comment by rbdiang** [comment]
@thaJeztah I am having same issue with not being able to expose a udp port in a swarm cluster.  The 1 node cluster is installed on a disconnected network so I can't copy all of my configuration to this but I will do my best to hand jam the relevant information:

```
docker -v 
18.03.0-ce build 0520e24
```
my-compose.yml:
```
version: "3.3"
services:
  logspout:
    image: bekt/logspout-logstash
    restart: on-failure
    environment:
      ROUTE_URIS: logstash://10.2.0.3:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  logstash:
    image: logstash/logstash-oss:6.1.2
    ports:
    - "5000:5000/udp"
    volumes:
    - ./logstash/:/usr/share/logstash/pipeline/logstash.conf
```

```
docker stack deploy -c my-compose tn
docker service inspect tn_logstash -f '{{.Endpoint.Ports}}'
[{ udp 5000 5000 ingress}]
```

The configure above does not work:  service logspout produces following log message:
`...logstash: could not write:write udp 10.0.0.15:52087-> 10.2.0.3:5000: write: **connection refused**

However this configuration works if I use the service name:port as in the following:
```
...
  logspout:
    image: bekt/logspout-logstash
    restart: on-failure    environment:
      ROUTE_URIS: logstash://logstash:5000
...

```

**Comment by thaJeztah** [comment]
@rbdiang what’s the 10.2.0.3 IP address? How did you get that?

**Comment by rbdiang** [comment]
That is the IP of the  eth0 interface on the physical host of the 1 node swarm cluster. It is same IP that displays when generating a swarm worker join token

**Comment by berlinguyinca** [comment]
same issue here.

**Comment by thomaskchan** [comment]
Having a similar issue trying to deploy a tftpd server (69/udp) via swarm.

Works fine with ports being "mode: host" but does not work with "mode: ingress".  Not having any routing issues with other swarm stacks using tcp, just this one using udp.

The port does appear to be open via nmap udp query, but the traffic does not reach the container (or the container is unable to respond back).

**Comment by anshupitlia** [comment]
I'm facing similar issue with tftp server. 69/udp via swarm. 

It is receiving request but not transferring data.
