### ISSUE TITLE
make DefaultPropagationMode value configurable

### ISSUE THREAD

**Issue by ismailyenigul** [docker/docker#31646]
**Description**
DefaultPropagationMode is rprivate.

https://github.com/docker/docker/blob/b248de7e332b6e67b08a8981f68060e6ae629ccf/volume/volume_propagation_linux.go
// DefaultPropagationMode defines what propagation mode should be used by
// default if user has not specified one explicitly.
// propagation modes
**const DefaultPropagationMode = mounttypes.PropagationRPrivate**

I need a docker configuration parameter that changes default setting(ie rshared)

The reason:

I am using https://cloud.docker.com to manage my docker instances.
My project requires that docker container must access to NFS share on host system.
Docker cloud expect that host volume must be available before starting instance.
But I need to create instance based on docker image id. So I have to mount NFS after deploying docker instance. I create a  directory (ie /mnt/user1-myworkspace1)  under a partition has rshared mount option.

I create a docker instance from docker cloud like following(just settings ports and volume mapping)

docker run -d -p 8079 -p 8080 -p 8081 -p 8082 --name ide -v /mnt/user1-myworkspace1:/home/ubuntu/workspace myapp/ide

docker run -d -p 8121 -p 8080 -p 8381 -p 8082 --name ide -v /mnt/user2-myworkspace1:/home/ubuntu/workspace myapp/ide

Then I mount NFS share of the user to  /mnt/user1-myworkspace1)
 mount  NfsIP:/user1-myworkspace1 /mnt/user1-myworkspace1

But docker cloud creates instance with rprivate propagation 

"Mounts": [
            {
                "Source": "/mnt/user1-myworkspace1",
                "Destination": "/home/ubuntu/workspace",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }

When I login in to container with 

docker exec -it instanceID bash

I do not see any files under workspace directory. I am expecting to see files comes from NFS share. but rprivate mode does not allow me.

I can create an instance from docker cli with rshared option to solve this problem.
docker run -d -p 8079 -p 8080 -p 8081 -p 8082 --name ide -v /mnt/user1-myworkspace1:/home/ubuntu/workspace:rshared myapp/ide

But in this case, I can't use docker cloud (https://cloud.docker.com) to manage my containers.

And docker cloud does not provide me an option to choose default Propagation value(rshared).
It provides only ro/rw options.

**Describe the results you expected:**
I would like to change default propagation of docker engine  in a config file or startup parameter.
OR I would like to have a  propagation option in docker cloud volumes settings while creating a new container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

$ docker info
Containers: 6
 Running: 1
 Paused: 0
 Stopped: 5
Images: 3
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 37
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.8-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: 4VXI:H4WY:5NBU:SWTQ:RKTA:REOZ:6ANT:DFLF:AGGN:XG67:PRQ5:GV35
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 30
 System Time: 2017-03-07T23:23:50.355115217Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

on Azure and installed by docker-cloud

**Comment by thaJeztah** [comment]
I don't think we should make this configurable to work around a limitation of docker cloud. Perhaps you can open a topic on https://forums.docker.com/c/docker-cloud, or contact support@docker.com

**Comment by cpuguy83** [comment]
+1 to @thaJeztah, this should not have changeable configuration.

Also it seems like you want rslave not rshared unless you are going to be mounting things inside the container. `rslave` tells the mountpoint in the container to receive any mount changes from the parent. `rshared` would only be needed if you are going to mount things from inside the container that should be allowed to propagate back to the host.

You also probably ought to look at using either a plugin, or even specifying the mount options for the nfs share as a local volume rather than bind-mounting in host dirs.

Closing, but feel free to discuss further.
Thanks!
