### ISSUE TITLE
MacOS Sierra. Docker asks access to passwords in my keychain.

### ISSUE THREAD

**Issue by cherurg** [docker/docker#31642]
Hi!

I've update Docker today. I use MacOS Sierra. Now it asks random passwords from my keychain. Why does Docker need my passwords?

![screen shot 2017-03-08 at 12 40 38](https://cloud.githubusercontent.com/assets/6004013/23702706/b0fe470c-03fc-11e7-888b-bb3ec25f5bed.png)
![screen shot 2017-03-08 at 12 38 31](https://cloud.githubusercontent.com/assets/6004013/23702712/b569751e-03fc-11e7-99b3-0074de28f43b.png)

**Comment by cpuguy83** [comment]
ping @justincormack

I've seen this too where it asks for a passwd in the keychain that it shouldn't need... for that matter it shouldn't even need registry credentials.

**Comment by thaJeztah** [comment]
Yes, @vdemeester is working on this

**Comment by vdemeester** [comment]
@cherurg the issue is being tracked here : https://github.com/docker/docker/issues/31517.

**Comment by cherurg** [comment]
@vdemeester i see. Thank you! 
Sorry for troubling

**Comment by vdemeester** [comment]
@cherurg no problemo 😉
