### ISSUE TITLE
Same issue as #20221 but not resolved

### ISSUE THREAD

**Issue by DonRichards** [docker/docker#31657]
**Description**
After freshly installing Docker on my computer for the first time. I ran the following command and got an error.

**Steps to reproduce the issue:**
```bash
$ docker run docker/whalesay cowsay boo

docker: Error: error contacting notary server: dial tcp: lookup notaryserver on 8.8.8.8:53: no such host.
See 'docker run --help'.
```

**Describe the results you received:**
Tried to follow step by step instructions on how to make and build a Dockerfile and this was my result

```bash
$ docker build -t docker-whale .
Sending build context to Docker daemon

error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.26/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&t=docker-whale&ulimits=null: Error: error contacting notary server: dial tcp: lookup notaryserver on 8.8.8.8:53: no such host

```

**Describe the results you expected:**
I think this is implied. Something other than an error I guess. 

**Additional information you deem important (e.g. issue happens only occasionally):**
OS Version: macOS 10.12.3

**Output of `docker version`:**

```bash
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```bash
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: LCS5:H2LC:4HPF:B3AC:GDJC:42KP:VUL4:LVPN:6VFR:B7AL:VFEQ:NXQ4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 16
 Goroutines: 26
 System Time: 2017-03-08T17:14:36.183493826Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
N/A

**Comment by thaJeztah** [comment]
I suspect you've tried the "Docker content trust" tutorial (https://docs.docker.com/engine/security/trust/trust_sandbox/) and still have the `DOCKER_CONTENT_TRUST` enabled (check the output of `env` in your terminal to see if that environment variable is set). 

If that variable is set, the docker client will try to reach the notary server, but since you did a fresh install, that is no longer there. You need to unset that environment variable (`unset DOCKER_CONTENT_TRUST`) and/or remove if from your `~/.profile` file if it's set there

**Comment by thaJeztah** [comment]
I'll go ahead and close, because this is not a bug, but feel free to continue the conversation, happy to help if needed.

**Comment by DonRichards** [comment]
It was never installed on this computer. I was originally using this tutorial https://docs.docker.com/engine/getstarted/step_four/#step-2-build-an-image-from-your-dockerfile

But to simplify the issue I demonstrated the same error with a basic function. Any Dockfile I create and point to a container fails because it never resolves the location.

**Comment by DonRichards** [comment]
Just doing `docker pull docker/whalesay` causes the same error. 
There is no ~/.profile file and during my troubleshooting I just added the `DOCKER_CONTENT_TRUST` but I went and unset it with the same result.
