### ISSUE TITLE
Reason for “no such container” messages in Docker daemon log

### ISSUE THREAD

**Issue by kinghuang** [docker/docker#31655]
**Description**

While looking at the Docker daemon logs for space issues (#31628), I realized that my daemon logs are mostly filled with error messages about “no such container”. For example, in the current logs from one of my swarm nodes, 47774/48309 lines (98.9%) are about “no such container”. Here's an excerpt.

```
Mar 08 09:23:41 itpocnode01.ucalgary.ca dockerd[1242]: time="2017-03-08T09:23:41.865075686-07:00" level=error msg="Handler for GET /containers/caf715b6168ffbe0bfa6273b6c3da88424a0902d653edda385fd29209793022f/json returned error: No such container: caf715b6168ffbe0bfa6273b6c3da88424a0902d653edda385fd29209793022f"
Mar 08 09:23:41 itpocnode01.ucalgary.ca dockerd[1242]: time="2017-03-08T09:23:41.865953477-07:00" level=error msg="Handler for GET /containers/a787c1e51e5ef67b60e6f52bcf2625d7b554a6ff40751978c837fc5ab3fb0d66/json returned error: No such container: a787c1e51e5ef67b60e6f52bcf2625d7b554a6ff40751978c837fc5ab3fb0d66"
Mar 08 09:23:41 itpocnode01.ucalgary.ca dockerd[1242]: time="2017-03-08T09:23:41.866665518-07:00" level=error msg="Handler for GET /containers/20588589287c176b5497deea67a9d1188fd5735e36e63d914c4866fb1cf2b8b9/json returned error: No such container: 20588589287c176b5497deea67a9d1188fd5735e36e63d914c4866fb1cf2b8b9"
Mar 08 09:23:41 itpocnode01.ucalgary.ca dockerd[1242]: time="2017-03-08T09:23:41.867397933-07:00" level=error msg="Handler for GET /containers/5dac55ccbf84d1707295b7124a8cb02f077607856761a3c03cb64a8bb5474084/json returned error: No such container: 5dac55ccbf84d1707295b7124a8cb02f077607856761a3c03cb64a8bb5474084"
Mar 08 09:23:41 itpocnode01.ucalgary.ca dockerd[1242]: time="2017-03-08T09:23:41.868129294-07:00" level=error msg="Handler for GET /containers/6afa66a774f3fdf996fdb8cd2b7c814e86f1089feba3c9924074b4ad7db885fa/json returned error: No such container: 6afa66a774f3fdf996fdb8cd2b7c814e86f1089feba3c9924074b4ad7db885fa"
```

How do I debug the reason for this? Docker daemon logs attached below.

[docker.txt](https://github.com/docker/docker/files/828258/docker.txt)

**Steps to reproduce the issue:**
Not sure how to reproduce this.
1. Run a 4 node swarm. 
2. Observe Docker daemon logs.

**Describe the results you received:**

My daemon logs are mostly filled (over 98%) with "no such container" error messages.

**Describe the results you expected:**

I don't expect my logs to be filled with "no such container" error messages continuously.

**Additional information you deem important (e.g. issue happens only occasionally):**

This is on a 4 node swarm. All four are exhibiting similar output in their Docker daemon logs.

**Output of `docker version`:**

```
-bash-4.2$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
-bash-4.2$ docker info
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 25
Server Version: 17.03.0-ce
Storage Driver: devicemapper
 Pool Name: docker-thinpool
 Pool Blocksize: 524.3 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: 
 Metadata file: 
 Data Space Used: 19.49 GB
 Data Space Total: 65.28 GB
 Data Space Available: 45.79 GB
 Metadata Space Used: 5.898 MB
 Metadata Space Total: 683.7 MB
 Metadata Space Available: 677.8 MB
 Thin Pool Minimum Free Space: 6.527 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: active
 NodeID: 3vz5vqb96ab3yh6mrhhbnf5ki
 Is Manager: true
 ClusterID: 9p9qjvvrp991zitpixlm8dpm5
 Managers: 4
 Nodes: 4
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 10.45.32.40
 Manager Addresses:
  10.45.32.40:2377
  10.45.32.41:2377
  10.45.32.42:2377
  10.45.32.43:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: itpocnode01.ucalgary.ca
ID: OM7K:NNN7:75VJ:I34C:W5ZS:TCYH:ZGPH:SRXP:HINS:7O2W:IZQ4:QIGD
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

All four 4 nodes are on RHEL 7.3.

**Comment by thaJeztah** [comment]
You probably have a container, or service running that's monitoring docker, for example, a cAdvisor container, or kubernetes. Such a service may be periodically accessing the docker API to inspect container status, but (for some reason) is using outdated information, so tries to inspect containers that no longer exist.

This is not a bug in docker, because docker itself does not automatically make those API calls

**Comment by thaJeztah** [comment]
I'll go ahead and close, because this is not a bug, but feel free to continue the conversation.

**Comment by kinghuang** [comment]
Thanks, @thaJeztah! I've got cAdvisor running. I'll try stopping it on all the nodes.

**Comment by thaJeztah** [comment]
I've seen other reports, so perhaps there's an issue with cAdvisor, causing it to either cache container ID's, or a bug that makes it determine the container ID's the wrong way

**Comment by sauravmndl** [comment]
I am getting same issue at the time of docker inspect call through API. Using docker 1.12.3
@thaJeztah Yes, I am doing the docker inspect call frequently (4 times in every 3 minutes). Is that overload to docker daemon? What is the benchmark?
Info: I am using volume driver also. Could you please put some light on this?

**Comment by thaJeztah** [comment]
@sauravmndl if you see this message, it's because something that calls the API tries to call inspect for a container that doesn't (or no longer) exists; it's not about "speed" / "overload" in this case, just an API call using a container-id that's incorrect

**Comment by sauravmndl** [comment]
@thaJeztah The operation I do:  first create the container and then start, all using swarm API.  In two scenarios I get the error:
1. The create and start becomes successful but after that when I inspect using swarm API I get following error in swarm log
time="xxxx" level=error msg="HTTP error: No such container d3ee1a5ba94d6649653dc4e65697721aef58665100761678fa7908bfbf9ffb6e" status=404
AND following error in docker log
time="xxxx" level=error msg="Handler for GET /v1.24/containers/d3ee1a5ba94d6649653dc4e65697721aef58665100761678fa7908bfbf9ffb6e/json returned error: No such container: d3ee1a5ba94d6649653dc4e65697721aef58665100761678fa7908bfbf9ffb6e"

2. Create is not successful, but actually in docker node I can see the corresponding container. This API call return "Container created but refresh didn't report it back" Following are some code snippet from swarm which also does a container check after create.
 
https://github.com/docker/swarm/blob/c684b4b5a17d3269839d9d6029511634dd1da052/cluster/engine.go#L1034
https://github.com/docker/swarm/blob/c684b4b5a17d3269839d9d6029511634dd1da052/cluster/engine.go#L793
https://github.com/docker/swarm/blob/c684b4b5a17d3269839d9d6029511634dd1da052/cluster/engine.go#L850

**Comment by thaJeztah** [comment]
Ok, so this looks more like an issue in swarm, not docker; what do you mean with;

> Create is not successful, but actually in docker node I can see the corresponding container.

- what was the reason the container failed to be created?
- If you are on that node, and `docker ps -a`, you see the container?
- Can you `docker inspect` the container on that node directly (through the `docker` cli, and _not_ using the swarm api?)

**Comment by sibasankarp** [comment]
Dear Friends,

I am trying to setup devstack multi node deployment. When i try to pull docker images using kolla-ansible pull, i am getting the below error. I am stuck please help me to resolve the issue.

failed: [localhost] (item={'value': {u'haproxy': {u'placement_api_external': {u'mode': u'http', u'enabled': True, u'external': True, u'listen_port': u'8780', u'port': u'8780'}, u'placement_api': {u'mode': u'http', u'enabled': True, u'external': False, u'listen_port': u'8780', u'port': u'8780'}}, u'group': u'placement-api', u'dimensions': {}, u'volumes': [u'/etc/kolla//placement-api/:/var/lib/kolla/config_files/:ro', u'/etc/localtime:/etc/localtime:ro', u'kolla_logs:/var/log/kolla/', u''], u'container_name': u'placement_api', u'image': u'kolla/centos-source-placement-api:rocky', u'enabled': True}, 'key': u'placement-api'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "action": "pull_image",
            "api_version": "auto",
            "auth_email": null,
            "auth_password": null,
            "auth_registry": null,
            "auth_username": null,
            "cap_add": [],
            "command": null,
            "detach": true,
            "dimensions": {},
            "environment": {
                "KOLLA_CONFIG_STRATEGY": "COPY_ALWAYS"
            },
            "graceful_timeout": 10,
            "image": "kolla/centos-source-placement-api:rocky",
            "labels": {},
            "name": null,
            "privileged": false,
            "remove_on_exit": true,
            "restart_policy": "unless-stopped",
            "restart_retries": 10,
            "security_opt": [],
            "state": "running",
            "tls_cacert": null,
            "tls_cert": null,
            "tls_key": null,
            "tls_verify": false,
            "tty": false,
            "volumes": null,
            "volumes_from": null
        }
    },
    "item": {
        "key": "placement-api",
        "value": {
            "container_name": "placement_api",
            "dimensions": {},
            "enabled": true,
            "group": "placement-api",
            "haproxy": {
                "placement_api": {
                    "enabled": true,
                    "external": false,
                    "listen_port": "8780",
                    "mode": "http",
                    "port": "8780"
                },
                "placement_api_external": {
                    "enabled": true,
                    "external": true,
                    "listen_port": "8780",
                    "mode": "http",
                    "port": "8780"
                }
            },
            "image": "kolla/centos-source-placement-api:rocky",
            "volumes": [
                "/etc/kolla//placement-api/:/var/lib/kolla/config_files/:ro",
                "/etc/localtime:/etc/localtime:ro",
                "kolla_logs:/var/log/kolla/",
                ""
            ]
        }
    },
    "msg": "Unknown error message: Tag rocky not found in repository docker.io/kolla/centos-source-placement-api"
}

**Comment by thaJeztah** [comment]
@sibasankarp please don't hijack closed issues with a completely unrelated question. (looking at your issue, looks like you're attempting to pull a `:rocky` tag from Docker Hub, but the image does not have such a tag; https://hub.docker.com/r/kolla/centos-source-placement-api/tags
