### ISSUE TITLE
I cannot push to docker hub

### ISSUE THREAD

**Issue by spencescu** [docker/docker#31650]
**Description** I cannot push an image to docker hub. I have an account and am able to login to hub.docker.com.

**Steps to reproduce the issue:**
1. Create a local image (my-image)
2. Tag it to spencescu/my-image:latest
3. docker login hub.docker.com (otherwise it defaults to docker.io and the login fails)
4. docker push spencescu/my-image:latest

**Describe the results you received:**

[ec2-user@ip-172-31-44-102 Docker]$ docker push spencescu/my-image:latest
The push refers to a repository [docker.io/spencescu/my-image]
3f0f8ca14e50: Preparing
447473a4d9fc: Preparing
47234d0a52a9: Preparing
21cfa55b9f35: Preparing
5eb5bd4c5014: Preparing
d195a7a18c70: Waiting
af605e724c5a: Waiting
59f161c3069d: Waiting
4f03495a4d7d: Waiting
unauthorized: authentication required

**Describe the results you expected:**

I was expecting the push to work

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Fri Jan  6 22:16:21 2017
 OS/Arch:      linux/amd64

**Output of `docker info`:**

[ec2-user@ip-172-31-44-102 Docker]$ docker info
Containers: 30
 Running: 0
 Paused: 0
 Stopped: 30
Images: 6
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-202:1-394721-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.662 GB
 Data Space Total: 107.4 GB
 Data Space Available: 3.82 GB
 Metadata Space Used: 6.074 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.141 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 4.4.51-40.58.amzn1.x86_64
Operating System: Amazon Linux AMI 2016.09
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.2 MiB
Name: ip-172-31-44-102
ID: AFHC:IBBQ:TAUQ:CE3N:LSPH:N2VR:7EY7:STY6:5JBS:O5RX:7EOA:XFUI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
[ec2-user@ip-172-31-44-102 Docker]

**Additional environment details (AWS, VirtualBox, physical, etc.):**

AWS

**Comment by thaJeztah** [comment]
The problem here is that when you login using `hub.docker.com`, the credentials are stored under a different index in the configuration file;

When doing `docker login`;

```json
cat ~/.docker/config.json
{
	"auths": {
		"https://index.docker.io/v1/": {
			"auth": "REDACTED"
		}
	}
}
```

When using `docker login hub.docker.com`;

```json
cat ~/.docker/config.json
{
	"auths": {
		"hub.docker.com": {
			"auth": "REDACTED"
		}
	}
}
```

When pushing an image, docker will request the correct credentials based on that index, and `hub.docker.com` will not be used.

Can you explain what problems you're seeing when logging in without specifying `hub.docker.com` ?

**Comment by spencescu** [comment]
When logging in w/o specifying hub.docker.com I get the below. When
specifying it, the login works.

[ec2-user@ip-172-31-44-102 Docker]$ docker login
Login with your Docker ID to push and pull images from Docker Hub. If you
don't have a Docker ID, head over to https://hub.docker.com to create one.
Username: shpences@gmail.com
Password:
Error response from daemon: Get https://registry-1.docker.io/v2/:
unauthorized: incorrect username or password

**Comment by thaJeztah** [comment]
You need to login with your username not your email; can you try logging in with your username?

**Comment by spencescu** [comment]
It worked that way - thank you so much!

**Comment by thaJeztah** [comment]
You're welcome! Let me go ahead and close this issue, but feel free to continue the conversation if needed
