### ISSUE TITLE
Long running docker instance has many CLOSE_WAIT and can't idetify protocol fds

### ISSUE THREAD

**Issue by cofyc** [docker/docker#31660]
**Description**

**Steps to reproduce the issue:**
1. Deploy many containers
2. When some process are in some unkillable states
3. Kill these containers

**Describe the results you received:**

Request timed out, and docker cannot release its net socket fd.

```
docker  8925 root  337u  sock                0,8      0t0   47494363 can't identify protocol
docker  8925 root  338u  sock                0,8      0t0   47478892 can't identify protocol
docker  8925 root  339u  sock                0,8      0t0   47465307 can't identify protocol
docker  8925 root  340u  sock                0,8      0t0   47494388 can't identify protocol
docker  8925 root  341u  sock                0,8      0t0   47450385 can't identify protocol
docker  8925 root  342u  sock                0,8      0t0   47490649 can't identify protocol
docker  8925 root  343u  sock                0,8      0t0   47487617 can't identify protocol
docker  8925 root  344u  sock                0,8      0t0   47465420 can't identify protocol
...
docker  8925 root *027u  IPv6           57864376      0t0        TCP 192.168.224.170:4444->192.168.224.22:56546 (CLOSE_WAIT)
docker  8925 root *028u  IPv6           57859473      0t0        TCP 192.168.224.170:4444->192.168.224.22:51419 (CLOSE_WAIT)
docker  8925 root *029u  IPv6           57867780      0t0        TCP 192.168.224.170:4444->192.168.224.22:51420 (CLOSE_WAIT)
docker  8925 root *030u  IPv6           57874562      0t0        TCP 192.168.224.170:4444->192.168.224.22:56126 (CLOSE_WAIT)
docker  8925 root *031u  IPv6           57865892      0t0        TCP 192.168.224.170:4444->192.168.224.22:56127 (CLOSE_WAIT)
docker  8925 root *032u  IPv6           57864402      0t0        TCP 192.168.224.170:4444->192.168.224.22:10664 (CLOSE_WAIT)
docker  8925 root *033u  IPv6           57864403      0t0        TCP 192.168.224.170:4444->192.168.224.22:10663 (CLOSE_WAIT)
docker  8925 root *034u  IPv6           57874659      0t0        TCP 192.168.224.170:4444->192.168.224.22:35490 (CLOSE_WAIT)
...
```

**Describe the results you expected:**

Request timed out, docker can release its net socket fd.

**Additional information you deem important (e.g. issue happens only occasionally):**

Some user processes are in brackets in `ps`, e.g.:

```
# ps -opid,command --pid 506188
    PID COMMAND
 506188 [sh]
```

**Output of `docker version`:**

```
# docker version
Client:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   20f81dd-unsupported
 Built:        Mon Apr 25 00:23:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   20f81dd-unsupported
 Built:        Mon Apr 25 00:23:10 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
# docker info
Containers: 20
 Running: 20
 Paused: 0
 Stopped: 0
Images: 70
Server Version: 1.10.3
Storage Driver: aufs
 Root Dir: /disk1/docker/lib/aufs
 Backing Filesystem: extfs
 Dirs: 537
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Plugins: 
 Volume: local
 Network: host null
Kernel Version: 4.2.0-27-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 251.8 GiB
Name: nqgpu4
ID: CYIF:THAJ:LDC2:3O6Z:WK4Z:IO7Q:FCN2:PSZE:JVMC:2E2T:GZ2O:UVUO
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by thaJeztah** [comment]
Docker 1.10 is quite old now, and no longer maintained; also, your seem to be running a custom build of an unofficial package (`20f81dd-unsupported`); if you have a system to test on, could you try if you're still able to reproduce this on the current release?

**Comment by thaJeztah** [comment]
Also, what kind of processes are running in your container? There was a bug in aufs that caused some JAVA processes to get stuck; that issue is resolved in newer kernel versions, see https://github.com/docker/docker/issues/18180#issuecomment-193708192

**Comment by cofyc** [comment]
@thaJeztah

Yes, these stuck processes are JAVA programs. If there is no workaround, we plan to upgrade docker & linux kernel.

Which linux lts version you suggest in production?

**Comment by thaJeztah** [comment]
You probably don't have to upgrade ubuntu, just the kernel. But if you're planning on updating, Ubuntu 16.04 is more up to date, and has support for seccomp-filtering, so more secure. Ubuntu 16.04 uses `systemd` (instead of upstart) by default, so you may have to get used to that.

**Comment by thaJeztah** [comment]
Let me close this issue for now, but let us know how it went
