### ISSUE TITLE
Docker run --cidfile fails with absolute paths on Windows

### ISSUE THREAD

**Issue by DHager** [docker/docker#31680]
When using the `docker run --cidfile` on Windows, instead of creating the file is says "The system cannot find the path specified" when the path is absolute.

### Set-up

* On Windows 7.
* Using Docker 1.12.2 build bb80604.
* Using Docker Quickstart Terminal.
* Current directory does not already contain `foo.cid` in each case.

### Expected behavior sample

The following attempt works as expected, executing and leaving behind `foo.cid` in the test directory with the container-hash inside.
    
    cd /c/Users/Bugreport/ ;    
    docker run --cidfile "foo.cid" hello-world;

### Failing behavior sample

This version is only different in that the path to `foo.cid` is absolute.
    
    cd /c/Users/Bugreport/ ;
    docker run --cidfile "/c/Users/Bugreport/foo.cid" hello-world;

Unexpectedly, it fails with output to STDERR of:

    C:\Program Files\Docker Toolbox\docker.exe: Failed to create the container ID file: open /c/Users/Bugreport/foo.cid:
    The system cannot find the path specified..
    See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.

This same error message is given whether or not `foo.cid` exists in the target directory.

## `docker version`

    Client:
     Version:      1.12.2
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   bb80604
     Built:        Tue Oct 11 17:00:50 2016
     OS/Arch:      windows/amd64
    
    Server:
     Version:      1.12.3
     API version:  1.24
     Go version:   go1.6.3
     Git commit:   6b644ec
     Built:        Wed Oct 26 23:26:11 2016
     OS/Arch:      linux/amd64

### `docker info`

    $ docker info
    Containers: 9
     Running: 1
     Paused: 0
     Stopped: 8
    Images: 18
    Server Version: 1.12.3
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Backing Filesystem: extfs
     Dirs: 55
     Dirperm1 Supported: true
    Logging Driver: json-file
    Cgroup Driver: cgroupfs
    Plugins:
     Volume: local
     Network: null overlay bridge host
    Swarm: inactive
    Runtimes: runc
    Default Runtime: runc
    Security Options: seccomp
    Kernel Version: 4.4.27-boot2docker
    Operating System: Boot2Docker 1.12.3 (TCL 7.2); HEAD : 7fc7575 - Thu Oct 27 17:23:17 UTC 2016
    OSType: linux
    Architecture: x86_64
    CPUs: 1
    Total Memory: 995.8 MiB
    Name: default
    ID: 5GWO:CLTY:TJFD:Q26D:66I6:Z6VM:E7PA:ZJFG:7GKI:F4QO:5KNY:TPUR
    Docker Root Dir: /mnt/sda1/var/lib/docker
    Debug Mode (client): false
    Debug Mode (server): true
     File Descriptors: 17
     Goroutines: 30
     System Time: 2017-03-09T07:43:13.140644631Z
     EventsListeners: 0
    Registry: https://index.docker.io/v1/
    Labels:
     provider=virtualbox
    Insecure Registries:
     127.0.0.0/8

**Comment by DHager** [comment]
For anyone with the same problem, my current workaround in bash is to put in a step that converts the path like so:

    CID_PATH="/c/Users/Bugreport/foo.cid";
    REL_CID_PATH=$(realpath --relative-to="." "$CID_PATH");

**Comment by friism** [comment]
This is a problem with Toolbox and/or running in the cygwin bash shell. Absolute paths work fine from powershell:

```
docker run --cidfile C:\code\blerg.cid hello-world
```

**Comment by DHager** [comment]
For a while I wondered whether the word "open" in the error was a mistake, and that the argument getting passed in was somehow `"open /c/foo"`, but that seems to be a red-herring. I'm no familiar with Go, but the [code that makes the message](https://github.com/docker/docker/blob/254fc83cba90ed79c78f4cb0cb33aeeaff492798/cli/command/container/create.go#L143) is just converting the error from [os.Create()](https://golang.org/pkg/os/#Create) into a string, and the type `*PathError` is defined as a struct of (operation, path, cause), which would explain how "open" got in there.

**Comment by jhowardmsft** [comment]
OK, so this is an issue with path-conversion from bash, not in docker. Hence closing.

**Comment by DHager** [comment]
@jhowardmsft I just don't understand why `docker.exe` is the only application that seems to have this problem (it also happens when specifying a `Dockerfile`)... while other executables such as `file`, `grep`,  or even `notepad.exe` understand absolute paths.

Do you think I should open a new issue in the [docker/toolbox](https://github.com/docker/toolbox) project instead?

**Comment by friism** [comment]
Hm, it actually works for me on Windows 10 in minGW bash shell:

```
friism@LAPTOP-G8D4BRBC MINGW64 /c/code/tmp
$ docker run --cidfile "/c/code/tmp/blerg.cid" hello-world

Hello from Docker!
...
friism@LAPTOP-G8D4BRBC MINGW64 /c/code/tmp
$ cat blerg.cid
7cfe62a5652e8277aa944df28c05e462cba0538dcf149a1d2fe533f11d117576
```
