### ISSUE TITLE
Can't build images with labels that contains space inside of quotes

### ISSUE THREAD

**Issue by roy-codefresh** [docker/docker#31697]
**Description**
Can't build images with label that contains space ( ) between quotes(') in it's value.

**Steps to reproduce the issue:**
1. run command `docker build --label "key='first second'"`

**Describe the results you received:**
I get the following error:
```Error response from daemon: Syntax error - can't find = in "second''". Must be of the form: name=value```

**Describe the results you expected:**
I expect the build to run regularly and the resulted image to have a label with key named `key` and value `'first second'`.

**Additional information you deem important (e.g. issue happens only occasionally):**
This problem happen to me after upgrading to docker 17.03 from docker 1.12. This
bug didn't occur to me on docker 1.12.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: $$
 Running: $$
 Paused: $$
 Stopped: $$
Images: $$
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 299
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: codefresh
ID: WMNW:DC75:4663:BZTY:6B6I:SE2Z:M4SU:YGKB:H3TM:HW3H:N2N5:SQKL
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 181
 Goroutines: 229
 System Time: 2017-03-09T16:22:18.613208789Z
 EventsListeners: 2
Username: roycodefresh
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 $$$$$$$$$$$$$
 $$$$$$$$$$$$$
Live Restore Enabled: false
```

**Comment by justincormack** [comment]
cc @dnephin

**Comment by dnephin** [comment]
Do you actually want the key to be `'first second'` (with single quotes) and not `first second` ?

```
--label "key=first second"

        "Labels": {
                "key": "first second"
         }
```

It does look like there is an issue when spaces and single quotes are combined in the label value. It's not a CLI issue though. I was able to confirm the API receives the expected value. The dockerfile builder is parsing it and getting confused. I'll try and track that down.

**Comment by dnephin** [comment]
I think I've found the bug. The implement of `--labels` creates a single quoted string, and then passes it to parse, which breaks the parsing because of the extra single quotes. 

I'm going to rewrite it to just create the `Node`s directly and avoid the extra parsing. Working on a fix now.

**Comment by dnephin** [comment]
I found the PR which broke this: #27174. Preserving that behaviour is going to be difficult.

**Comment by bogdang989** [comment]
I get the same bug when using double brackets "First Second ", while everything works with single brackets 'First Second'

**Comment by thaJeztah** [comment]
@bogdang989 which version of docker are you running? I just tried this (on 17.05.0);


```bash
docker run \
  --label=one='first second' \
  --label=two="first second" \
  --label=three=first\ second \
  --name example \
  hello-world
```


```bash
docker inspect --format='{{json .Config.Labels}}' example | jq .
{
  "one": "first second",
  "three": "first second",
  "two": "first second"
}
```

Which seems to be ok

**Comment by thaJeztah** [comment]
oh, never mind, looking at `docker run`, not `docker build`; let me try

**Comment by thaJeztah** [comment]
Seems to work as well;

```bash
docker build -t example --label=one='first second' --label=two="first second" --label=three=first\ second -<<EOF
FROM scratch
EOF
```

```bash
docker inspect --format='{{json .Config.Labels}}' example:latest
{
  "one": "first second",
  "three": "first second",
  "two": "first second"
}
```

**Comment by bogdang989** [comment]
Sorry, forgot to mention that it is from Dockerfile.
It is really weird as I am unable to reproduce this now.
At first, LABEL description="a b" returned an error, so I changed it to: 
LABEL description='a b' and it worked.
Now I build again with LABEL description="a b" and it works.
I did not update anything in the meantime so I am really confused. Feel free to ignore this.
