### ISSUE TITLE
Identify Windows Docker Container from Inside.

### ISSUE THREAD

**Issue by samartinucci** [docker/docker#31695]
**Description**

Currently we have an internal software that might be installed on Windows Docker Containers (namely microsoft/windowsservercore) and from inside the running container we might have a way to identify that we are inside a Docker container and more than that, we need to retrieve the Container ID.

Currently on Unix we have the option to read /proc/1/cgroup, although on Windows we have nothing similar (registry, files or environment variables), the closest we can get from having it is reading the hostname in case it's not overrided.

**Steps to reproduce the issue:**
1. Start a Windows based Docker image and connect to it

docker run -ti microsoft/windowsservercore cmd

**Describe the results you received:**

I've tried to lookup everywhere for entries, although all the queries bellow have failed:

Registry Lookup:

REG Query HKLM /f fa34683b9433 /s
REG Query HKEY_CURRENT_USER /f fa34683b9433 /s
REG Query HKEY_USERS /f fa34683b9433 /s
REG Query HKEY_CURRENT_CONFIG /f fa34683b9433 /s
findstr /spin /c:"fa34683b9433" *
set
systeminfo

**Describe the results you expected:**

I would've expect to find the container ID somewhere and something that would help me to identify that it corresponds to a Docker container.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.24)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      windows/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 18
Server Version: 1.13.1
Storage Driver: windowsfilter
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: l2bridge l2tunnel nat null overlay transparent
Swarm: inactive
Default Isolation: process
Kernel Version: 10.0 14393 (14393.693.amd64fre.rs1_release.161220-1747)
Operating System: Windows Server 2016 Datacenter
OSType: windows
Architecture: x86_64
CPUs: 1
Total Memory: 3.75 GiB
Name: EC2AMAZ-ELQ79K9
ID: JUIH:37Q4:2GV2:KDZI:DNMS:MVFV:PSXJ:2NOT:HFGY:KU6N:X2ZE:ZX6D
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

My Docker Host is running on AWS

**Comment by cpuguy83** [comment]
Sounds like a dup of #8427?
Also note this is being iterated on here: #26331 

Closing since this request is tracked in the other issue.
