### ISSUE TITLE
docker create image without pulling an already available image

### ISSUE THREAD

**Issue by s2zaman** [docker/docker#31732]
I don't want to use any online available docker images.
Is it possible to skip **only** the `FROM` command from `Dockerfile`, so that i create my .NET **sampleApp**'s image and push that to docker-hub.

**reason of posting the question here**
_This github seemed to me as a sharp support platform, that is why i posted this question here_ :) 

Thanks guys.

**Comment by dimaspivak** [comment]
Every Dockerfile must have a `FROM`. You can always reference a locally-available image, though, in which case it would be used without pulling from the internet.

**Comment by cpuguy83** [comment]
As @dimaspivak mentioned, `FROM` is required, otherwise there is nothing to base off of.
If you want to provide your own rootfs, you can do so with `FROM scratch`.

**Comment by s2zaman** [comment]
Thanks guys, got it  !
