### ISSUE TITLE
ERROR: Error response from daemon: datastore for scope "global" is not initialized

### ISSUE THREAD

**Issue by matheusgontijo** [docker/docker#31748]
I create successfully a swarm, with two nodes. However when I use `docker-compose build && docker-compose up` in order to start my project it crashes erroring out this:

`ERROR: Error response from daemon: datastore for scope "global" is not initialized`

It's a very very simple process:

`docker run swarm create`

**swarm hash**:
`1477bcd7778d083e02a80c352d4f1b87`

`docker-machine create -d virtualbox --swarm --swarm-master --swarm-discovery token://1477bcd7778d083e02a80c352d4f1b87 myswarmmaster`

`docker-machine create -d virtualbox --swarm --swarm-discovery token://1477bcd7778d083e02a80c352d4f1b87 myremotenode1`

`eval $(docker-machine env --swarm myswarmmaster)`

`docker-compose build && docker-compose up`

And then I get the error:
`ERROR: Error response from daemon: datastore for scope "global" is not initialized`

By the way this is the entire content of my `docker-composer.xml`

```
version: '2'
services:
    debian:
        image: debian
```

I'm running Docker version `1.12.6` on `Fedora 25`.

**Comment by matheusgontijo** [comment]
Any clue? @mavenugo @thaJeztah 
Appreciate all efforts to help me out!

**Comment by cpuguy83** [comment]
In order to create overlay networks (default when creating networks on classic swarm) you must set the correct options on the daemon, specifically: `--cluster-store`, and `--cluster-advertise`.
This is because overlay networks on classic swarm requires use of an external K/V store.

If you use the new swarm-mode in 1.12, none of this is required.

Closing as it is a non-issue.

**Comment by matheusgontijo** [comment]
Thanks @cpuguy83! Answer very helpful!

I have two question tho:

1) It's not clear for which version I'm using, would you help me saying if I'm over version 1.12 please?

```
$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:21:51 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:21:51 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

2) You mentioned I'm using the **classic swarm**. How can I make sure I'm using **swarm-mode** instead?

**Comment by cpuguy83** [comment]
17.03 is the latest release.

To use swarm-mode: https://docs.docker.com/engine/swarm/#swarm-mode-cli-commands
