### ISSUE TITLE
(Content trust enabled) No prompt for passphrase when 'push' a docker image from a host. The image has been 'push' to registry from different host already

### ISSUE THREAD

**Issue by chunglam1999** [docker/docker#31777]
**Description**
With content trust enabled:
DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
DOCKER_CONTENT_TRUST=1
When the container first push image to notaryserver:4443, it will prompt to enter passphrase. Create second  container, first push docker images, not prompt for passphrase. The second container does not have root.json and targets.json from Notary yet, so it should be prompt to enter the passphrase.
I am using Content Trust Sandbox:
https://docs.docker.com/engine/security/trust/trust_sandbox/

Please refer to Description above
**Steps to reproduce the issue:**
1. Add trustsandbox1 to  the docker-compose.yml as follows:
```yaml
  trustsandbox1:
     image: docker:dind
     networks:
       - sandbox
     volumes:
       - notarycerts:/notarycerts
     privileged: true
     container_name: trustsandbox1
     entrypoint: ""
     command: |-
         sh -c '
             cp /notarycerts/root-ca.crt /usr/local/share/ca-certificates/root-ca.crt &&
             update-ca-certificates &&
             dockerd-entrypoint.sh --insecure-registry sandboxregistry:5000'
```

2. docker-compose up
3. 

```bash
docker exec -it trsutsandbox sh
>DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
>DOCKER_CONTENT_TRUST=1
>docker pull docker/trusttest
>docker tag docker/trusttest sandboxregistry:5000/test/trusttest:latest
>docker push sandboxregistry:5000/test/trusttest:latest
Prompt to enter password paraphase
3. docker exec -it trustsandbox1 sh
>DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
>DOCKER_CONTENT_TRUST=1
>docker pull docker/trusttest
>docker tag docker/trusttest sandboxregistry:5000/test/trusttest:2.6
>docker push sandboxregistry:5000/test/trusttest:2.6
```

Not prompt to enter passphrase

**Describe the results you received:**
The container trustsandbox1 should prompt for password when push image for the first time

**Describe the results you expected:**
The container trustsandbox1 did prompt for passphrase when push image for the first time

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
~ # docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Mar  2 01:11:00 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

1.trustsandox:

```
~ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.1.12-61.1.28.el7uek.x86_64
Operating System: Alpine Linux v3.5 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.466 GiB
Name: 2d8a00393b7d
ID: K5M7:EV4R:Z7QP:SSN6:XFWG:JZNY:74LZ:WH6G:7ZQS:TGEO:24SF:RHYV
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 sandboxregistry:5000
 127.0.0.0/8
Live Restore Enabled: false
```
2. trustsandbox1

```
/ # docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 17.03.0-ce
Storage Driver: vfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.1.12-61.1.28.el7uek.x86_64
Operating System: Alpine Linux v3.5 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.466 GiB
Name: a7c912e5d59e
ID: 3JMR:GTXZ:6KXF:QQT3:Y7T7:EEJ7:NKY3:5ZMA:MKRU:5NGU:T7U6:A5C6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 sandboxregistry:5000
 127.0.0.0/8
Live Restore Enabled: false
```

trustsandbox:

```
~ # docker tag docker/trusttest sandboxregistry:5000/test/trusttest:2.6
~ # docker push sandboxregistry:5000/test/trusttest:2.6
The push refers to a repository [sandboxregistry:5000/test/trusttest]
5f70bf18a086: Pushed 
c22f7bc058a9: Pushed 
2.6: digest: sha256:44947a3cd3295125c5beb643f1029e475701b748814c42fe75501ba06e10453c size: 734
Signing and pushing trust metadata
You are about to create a new root signing key passphrase. This passphrase
will be used to protect the most sensitive key in your signing system. Please
choose a long, complex passphrase and be careful to keep the password and the
key file itself secure and backed up. It is highly recommended that you use a
password manager to generate the passphrase and keep it safe. There will be no
way to recover this key. You can find the key in your config directory.
Enter passphrase for new root key with ID a0548d4: 
Repeat passphrase for new root key with ID a0548d4: 
Enter passphrase for new repository key with ID 08b6786 (sandboxregistry:5000/test/trusttest): 
Repeat passphrase for new repository key with ID 08b6786 (sandboxregistry:5000/test/trusttest): 
Finished initializing "sandboxregistry:5000/test/trusttest"
```

trustsandnox1:

```
/ # docker tag docker/trusttest sandboxregistry:5000/test/trusttest:2.7
/ # docker push sandboxregistry:5000/test/trusttest:2.7
The push refers to a repository [sandboxregistry:5000/test/trusttest]
5f70bf18a086: Pushed 
c22f7bc058a9: Pushed 
2.7: digest: sha256:44947a3cd3295125c5beb643f1029e475701b748814c42fe75501ba06e10453c size: 734
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
https://docs.docker.com/engine/security/trust/trust_sandbox/

**Comment by thaJeztah** [comment]
ping @riyazdf ptal

**Comment by riyazdf** [comment]
@chunglam1999: thanks for the report.  In your second push, I don't see `Signing and pushing trust metadata` in the output - are you certain that `DOCKER_CONTENT_TRUST=1`?

for example, it should look something like this:
```
/ # DOCKER_CONTENT_TRUST=1 docker push sandboxregistry:5000/test/trusttest:2.7
The push refers to a repository [sandboxregistry:5000/test/trusttest]
5f70bf18a086: Pushed 
c22f7bc058a9: Pushed 
2.7: digest: sha256:<DIGEST> size: <SIZE>
Signing and pushing trust metadata
... <CONTINUED> ...
```

**Comment by chunglam1999** [comment]
Yes, I check the 'env' and
DOCKER_CONTENT_TRUST_SERVER=https://notaryserver:4443
DOCKER_CONTENT_TRUST=1

also the root.json and targets.json are created.

**Comment by riyazdf** [comment]
@chunglam1999: just to be clear, this is for `trustsandbox1` (second host) right?  If so, could you please post the debug output for the following command from that host?

```
DOCKER_CONTENT_TRUST=1 docker -D push sandboxregistry:5000/test/trusttest:2.7
```

**Comment by chunglam1999** [comment]
/ # docker tag docker/trusttest sandboxregistry:5000/test/trusttest:2.7
/ # DOCKER_CONTENT_TRUST=1 docker -D push sandboxregistry:5000/test/trusttest:2.7
The push refers to a repository [sandboxregistry:5000/test/trusttest]
5f70bf18a086: Pushed 
c22f7bc058a9: Pushed 
2.7: digest: sha256:44947a3cd3295125c5beb643f1029e475701b748814c42fe75501ba06e10453c size: 734
Signing and pushing trust metadata
DEBU[0001] reading certificate directory: /root/.docker/tls/notaryserver:4443 
DEBU[0001] 200 when retrieving metadata for root        
DEBU[0001] entered ValidateRoot with dns: sandboxregistry:5000/test/trusttest 
DEBU[0001] found the following root keys: [3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf] 
DEBU[0001] found 1 valid leaf certificates for sandboxregistry:5000/test/trusttest: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for sandboxregistry:5000/test/trusttest 
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=sandboxregistry:5000/test/trusttest) 
DEBU[0001] checking trust-pinning for cert: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001]  role has key IDs: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] verifying signature for key ID: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] root validation succeeded for sandboxregistry:5000/test/trusttest 
DEBU[0001] updating TUF client                          
DEBU[0001] Loading timestamp...                         
DEBU[0001] 200 when retrieving metadata for timestamp   
DEBU[0001] timestamp role has key IDs: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] verifying signature for key ID: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] successfully verified downloaded timestamp   
DEBU[0001] Loading snapshot...                          
DEBU[0001] no snapshot in cache, must download          
DEBU[0001] 200 when retrieving metadata for snapshot.25b0b8d23bfbf36402c3d57ed45a52394a788af15ac2198a2bca9c5fd6dc3df4 
DEBU[0001] snapshot role has key IDs: 470804101072fec5cf34d7979eb63c1c6d90530e2e1ae851f08a6342b97e52ee 
DEBU[0001] verifying signature for key ID: 470804101072fec5cf34d7979eb63c1c6d90530e2e1ae851f08a6342b97e52ee 
DEBU[0001] successfully verified downloaded snapshot.25b0b8d23bfbf36402c3d57ed45a52394a788af15ac2198a2bca9c5fd6dc3df4 
DEBU[0001] Loading targets...                           
DEBU[0001] no targets in cache, must download           
DEBU[0001] 200 when retrieving metadata for targets.2c778b3f7dbaea28c448e7ed74f10fb74c01b4abf0d02989436ebb82b4d4a0b1 
DEBU[0001] targets role has key IDs: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] verifying signature for key ID: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] successfully verified downloaded targets.2c778b3f7dbaea28c448e7ed74f10fb74c01b4abf0d02989436ebb82b4d4a0b1 
DEBU[0001] entered ValidateRoot with dns: sandboxregistry:5000/test/trusttest 
DEBU[0001] found the following root keys: [3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf] 
DEBU[0001] found 1 valid leaf certificates for sandboxregistry:5000/test/trusttest: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for sandboxregistry:5000/test/trusttest 
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=sandboxregistry:5000/test/trusttest) 
DEBU[0001] checking trust-pinning for cert: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001]  role has key IDs: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] verifying signature for key ID: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] root validation succeeded for sandboxregistry:5000/test/trusttest 
DEBU[0001] entered ValidateRoot with dns: sandboxregistry:5000/test/trusttest 
DEBU[0001] found the following root keys: [3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf] 
DEBU[0001] found 1 valid leaf certificates for sandboxregistry:5000/test/trusttest: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for sandboxregistry:5000/test/trusttest 
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=sandboxregistry:5000/test/trusttest) 
DEBU[0001] checking trust-pinning for cert: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001]  role has key IDs: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] verifying signature for key ID: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] root validation succeeded for sandboxregistry:5000/test/trusttest 
DEBU[0001] updating TUF client                          
DEBU[0001] Loading timestamp...                         
DEBU[0001] 200 when retrieving metadata for timestamp   
DEBU[0001] timestamp role has key IDs: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] verifying signature for key ID: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] timestamp role has key IDs: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] verifying signature for key ID: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] successfully verified downloaded timestamp   
DEBU[0001] Loading snapshot...                          
DEBU[0001] snapshot role has key IDs: 470804101072fec5cf34d7979eb63c1c6d90530e2e1ae851f08a6342b97e52ee 
DEBU[0001] verifying signature for key ID: 470804101072fec5cf34d7979eb63c1c6d90530e2e1ae851f08a6342b97e52ee 
DEBU[0001] successfully verified cached snapshot        
DEBU[0001] Loading targets...                           
DEBU[0001] targets role has key IDs: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] verifying signature for key ID: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] successfully verified cached targets         
DEBU[0001] Making dir path: /root/.docker/trust/tuf/sandboxregistry:5000/test/trusttest/changelist 
DEBU[0001] Adding target "2.7" with sha256 "44947a3cd3295125c5beb643f1029e475701b748814c42fe75501ba06e10453c" and size 734 bytes.
 
DEBU[0001] Making dir path: /root/.docker/trust/tuf/sandboxregistry:5000/test/trusttest/changelist 
DEBU[0001] entered ValidateRoot with dns: sandboxregistry:5000/test/trusttest 
DEBU[0001] found the following root keys: [3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf] 
DEBU[0001] found 1 valid leaf certificates for sandboxregistry:5000/test/trusttest: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for sandboxregistry:5000/test/trusttest 
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=sandboxregistry:5000/test/trusttest) 
DEBU[0001] checking trust-pinning for cert: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001]  role has key IDs: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] verifying signature for key ID: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] root validation succeeded for sandboxregistry:5000/test/trusttest 
DEBU[0001] entered ValidateRoot with dns: sandboxregistry:5000/test/trusttest 
DEBU[0001] found the following root keys: [3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf] 
DEBU[0001] found 1 valid leaf certificates for sandboxregistry:5000/test/trusttest: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] found 1 leaf certs, of which 1 are valid leaf certs for sandboxregistry:5000/test/trusttest 
DEBU[0001] checking root against trust_pinning config%!(EXTRA string=sandboxregistry:5000/test/trusttest) 
DEBU[0001] checking trust-pinning for cert: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001]  role has key IDs: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] verifying signature for key ID: 3851b486202e232c959d1e395ae38fd27a8485af55ba0ff6924aa47ac0797ddf 
DEBU[0001] root validation succeeded for sandboxregistry:5000/test/trusttest 
DEBU[0001] 200 when retrieving metadata for root        
DEBU[0001] updating TUF client                          
DEBU[0001] Loading timestamp...                         
DEBU[0001] 200 when retrieving metadata for timestamp   
DEBU[0001] timestamp role has key IDs: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] verifying signature for key ID: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] timestamp role has key IDs: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] verifying signature for key ID: 56c4d13e25bdeb38cb8a01aaf0baa53e9fa4e0bafe5d4b39a0d769ef570c4f0b 
DEBU[0001] successfully verified downloaded timestamp   
DEBU[0001] Loading snapshot...                          
DEBU[0001] snapshot role has key IDs: 470804101072fec5cf34d7979eb63c1c6d90530e2e1ae851f08a6342b97e52ee 
DEBU[0001] verifying signature for key ID: 470804101072fec5cf34d7979eb63c1c6d90530e2e1ae851f08a6342b97e52ee 
DEBU[0001] successfully verified cached snapshot        
DEBU[0001] Loading targets...                           
DEBU[0001] targets role has key IDs: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] verifying signature for key ID: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] successfully verified cached targets         
DEBU[0001] changelist add: 2.7                          
ERRO[0001] couldn't add target to targets: could not find necessary signing keys, at least one of these keys must be available: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2 
DEBU[0001] error attempting to apply change #0: create, on scope: targets path: 2.7 type: target 
DEBU[0001] Error applying changelist                    
Failed to sign "sandboxregistry:5000/test/trusttest":2.7 - could not find necessary signing keys, at least one of these keys must be available: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2
Error: could not find signing keys for remote repository sandboxregistry:5000/test/trusttest, or could not decrypt signing key: could not find necessary signing keys, at least one of these keys must be available: 2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2

**Comment by chunglam1999** [comment]
The 2.7 images is 'pushed' sandboxregistry:5000 according to 'docker image' output
/ # docker images
REPOSITORY                            TAG                 IMAGE ID            CREATED             SIZE
docker/trusttest                      latest              cc7629d1331a        21 months ago       5.03 MB
sandboxregistry:5000/test/trusttest   2.7                 cc7629d1331a        21 months ago       5.03 MB

**Comment by chunglam1999** [comment]
The targets.json file at the host that has error when 'push':
{"signed":{"_type":"Targets","delegations":{"keys":{},"roles":[]},"expires":"2020-03-12T22:12:51.211079194Z",                                     
"targets":{"2.6":{"hashes":{"sha256":"RJR6PNMpUSXFvrZD8QKeR1cBt0iBTEL+dVAboG4QRTw="},"length":734}},"version":2},i                                
"signatures":[{"keyid":"2b9ab2dbc5518832b7e4093f355a3a0f67c83690693adb07daf9f990404e58d2","method":"ecdsa",i                                      
"sig":"Ur2M5K+t+DGCRWv3MDQg+VBvhSxo16+Y+y/1MO4jN4fTqzktnKEU4Vu8frOMJLo43XjICBlC615zpqjAR15yPw=="}]}

**Comment by riyazdf** [comment]
@chunglam1999: the error from notary indicates that you don't have the signing keys available on the host.  Do you have the signing private keys in `~/.docker/trust/private` on the `trustsandbox1` host?
Note that for pushing the same image across multiple hosts, you'll have to either share keys or setup delegation roles.

Also note that the signed metadata is pushed to notary after the image itself is pushed to the registry, so your finding that the tag is available is expected.  As a result, a normal docker pull will succeed but a trusted pull (`DOCKER_CONTENT_TRUST=1 docker pull ...`) will fail.  `notary list` will not show the tag in its output since it is not signed.

**Comment by chunglam1999** [comment]
I do not have the signing private keys in ~/.docker/trust/private:
~/.docker/trust/private # ls
~/.docker/trust/private # pwd
/root/.docker/trust/private
How can I populate the 'share key' as you mentioned? 

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Also, for the first host the keys existed:
~/.docker/trust/private # ls
root_keys  tuf_keys
~/.docker/trust/private # vi root_keys/
~/.docker/trust/private # cd root_keys/
~/.docker/trust/private/root_keys # ls
02ee3ff643305f1f4b21456f35f5de36a6c6e5d329b43a33d6eecfa1a15791a9.key
~/.docker/trust/private/root_keys # cd ..
~/.docker/trust/private # ls
root_keys  tuf_keys
~/.docker/trust/private #

**Comment by riyazdf** [comment]
Hi @chunglam1999: notary uses private keys to sign its metadata.  These keys are generated at initialization time for a repository.  This means that if you'd like to push signed metadata for the same repository across multiple hosts, each host must have private signing keys.

I encourage you to take a look at the Docker Content Trust [docs for managing keys](https://docs.docker.com/engine/security/trust/trust_key_mng/) as well as the notary [key management docs](https://docs.docker.com/notary/advanced_usage/#manage-keys) for more info.

As for allowing your other host to push to the same repo, here are two workflows that should work:

- One way to allow your other host to push signed content to the same repository is to copy the `targets` key for the repo (located in `~/.docker/trust/private/tuf_keys/<repository_name>/`) to the same location on the other host.

- Another way to allow your other hosts to push signed content is to set up [delegation roles](https://docs.docker.com/notary/advanced_usage/#work-with-delegation-roles).  With delegation roles, you do not need to copy any keys around - each host can use its own key for signing.

I think this should resolve your issue, but please let us know if you run into any further issues and if anything can be better elaborated in the docs (we accept PRs!)

**Comment by chunglam1999** [comment]
@riyazdf  Really appreciate your help.
I do copy the root_keys to other host and it works.  
If I use the delegation roles, do I use both the root passphrase and the repo passphrase or just the repo passphrase.

**Comment by riyazdf** [comment]
@chunglam1999 - glad to help!

if you use delegation roles, each key used in a delegation role can have its own separate passphrase such that each user can keep their own individual passphrase private.
