### ISSUE TITLE
HELP: Docker service scale kill my container

### ISSUE THREAD

**Issue by Fabryprog** [docker/docker#31783]
Hello, i have package my application into a docker image and i'm using it into docker swarm.

I had a serious problem: my enterprice application do "something" into shutdown phase (commit and close database connection, close mqtt connection, close active session, etc etc..). 

Today i stop my application with docker service scale command and it isn't stopped normally but docker kill it.

There is another command to "softly" shutdown a service?

**Comment by aluzzardi** [comment]
@Fabryprog Docker will "softly" shutdown your application by sending a `SIGTERM` to it and wait 15 seconds for it to shutdown properly. If it doesn't shutdown within 15 seconds, it will kill it.

You can override the default 15 seconds by using:
```
      --stop-grace-period duration       Time to wait before force killing a container (ns|us|ms|s|m|h)
```

**Comment by thaJeztah** [comment]
Does that answer your question, @Fabryprog ?

**Comment by Fabryprog** [comment]
Yeah... it's working! thanks a lot!

**Comment by thaJeztah** [comment]
Great!
