### ISSUE TITLE
Can Docker run on Android?

### ISSUE THREAD

**Issue by LightVolk** [docker/docker#31781]
Can Docker run on Android? And if no, can you add this support?

**Comment by thaJeztah** [comment]
No, it doesn't run on Android, and is not something that's being worked on. Adding a new platform is a huge undertaking, and would need volunteering from the community to look into possibilities. I'm not aware of anyone looking into this.

I'll close this issue for now, because this is not on the roadmap, but feel free to comment after I closed

**Comment by justincormack** [comment]
It definitely used to be the case that shipped Android kernels did not have
the right kernel settings for running containers. This might have changed
though in more recent releases.

**Comment by justincormack** [comment]
I checked the recommended Android kernel config, and it still does not have namespace support, so a port is currently not feasible.

**Comment by nguyendv** [comment]
@justincormack Where I can check the required kernel config to run Docker on? I'm thinking building a custom Android kernel to allow Docker. Thanks.

**Comment by mikailcetinkaya** [comment]
@nguyendv what is your status . Can you get configs  or do you need help ?

**Comment by jockerxlj** [comment]
@justincormack have you found the  kernel config for docker? I am suffering the same problem and have no idea to find kernel config for docker. Thanks.

**Comment by thaJeztah** [comment]
A "rough" check would probably be https://github.com/moby/moby/blob/master/contrib/check-config.sh, but I'm not sure if it checks for everything that's needed

**Comment by jockerxlj** [comment]
@thaJeztah  Thinks for  your reply, I will try it.

**Comment by CaiJingLong** [comment]
I recently saw a message that Android's kernel might return to the Linux mainline.
Once this becomes a reality, will docker be able to run on Android in the future?
