### ISSUE TITLE
"docker pull" incorrectly requests login information, but only when asking for a specific digest

### ISSUE THREAD

**Issue by adrianludwin** [docker/docker#31799]
**Description**

I'm seeing unexpectedly different behaviour for `docker pull` for an unauthorized request depending on whether I'm asking for a specific digest or not. If I'm unauthorized, I would like the request to simply fail, and this is what happens if I specify a tag or no tag/digest.

However, if I specify a digest, `docker pull` prompts me for a login, even though I've already logged in. This makes `docker pull` unusable in a non-interactive context.

Here's the output when I'm not authorized:

```
aludwin@docker-bot-1:~$ docker pull gcr.io/aludwin/golang:latest
Pulling repository gcr.io/aludwin/golang
Error: Status 403 trying to pull repository aludwin/golang: "Unable to access the repository: aludwin/golang; please verify that it exists and you have permission to access it."

aludwin@docker-bot-1:~$ docker pull gcr.io/aludwin/golang
Using default tag: latest
Pulling repository gcr.io/aludwin/golang
Error: Status 403 trying to pull repository aludwin/golang: "Unable to access the repository: 
aludwin/golang; please verify that it exists and you have permission to access it."

aludwin@docker-bot-1:~$ docker pull gcr.io/aludwin/golang@sha256:7a1834c045aaf720214d07f1612da4dd5fb5863208e91b0bcb66e927f045b460

Please login prior to pull:
Username (oauth2accesstoken): ^C
```

When I _am_ authorized, all of these variants succeed as expected.

**Steps to reproduce the issue:**
1. Log into a registry (I've only tried gcr.io, but I'm assuming this is a client issue)
2. Try to pull an image you don't have authorization to access, both with a tag and with a digest.
3. Observe a fast failure with a useful error message with a tag, and an unhelpful request to log in with a digest.

**Describe the results you received:**

Different client behaviour depending on whether I'm pulling based on a tag or a digest.

**Describe the results you expected:**

Identical behaviour for tags and digests.

**Additional information you deem important (e.g. issue happens only occasionally):**

This was running in a Google Compute Engine (GCE) instance in one project, trying to access an image in the Google Container Registry (GCR) for another project. If I grant the service accounts from the first project access to storage in the second, everything succeeds; I was testing the case where the service accounts were incorrectly configured.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:05:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:05:01 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 0
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 19
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-39-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.656 GiB
Name: docker-bot-1
ID: H5SA:2YLQ:TS7P:GSAG:EAZW:GZ2F:PXGJ:Z5SD:O4NB:5NJY:3CTR:ERWH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

See above.

**Comment by thaJeztah** [comment]
ping @dmcgowan @aaronlehmann

**Comment by adrianludwin** [comment]
I'm imagining there's something about [this block](https://github.com/docker/docker/blob/e10f9db26d7db8396d6f70419ecd1aa081190069/cli/command/image/pull.go#L71) that's responsible but I don't know the code well enough to speculate as to what the problem might be.

**Comment by aaronlehmann** [comment]
I suspect this is issue is specific to the registry you're using. When you request an image by tag, the client first needs to resolve that tag to a digest. It appears this HTTP request returns a 403 errror, but the HTTP request to fetch the manifest for the digest you enter directly does not. Can you reproduce this with a different registry such as Docker Hub?

**Comment by jonjohnsonjr** [comment]
Pulling in a non-interactive context looks like it should work unless [this check in ConfigureAuth](https://github.com/docker/docker/blob/e9c0de0de65182915d1cd205f06f5c903c20a29f/cli/command/registry.go#L97) is not working.

As to why you're getting different behavior for tags vs digest, I suspect it's related to [this fallback path](https://github.com/docker/docker/blob/e10f9db26d7db8396d6f70419ecd1aa081190069/distribution/pull_v2.go#L336).

**Comment by adrianludwin** [comment]
Thanks all, I'll investigate further in a few days and get back to you.

**Comment by alegou** [comment]
I can confirm that this does not happen on dockerhub:

```
agoulti@instance-1:~$ sudo docker pull alegou/test@sha256:14aea6cc3fd31e3c4e3f454c585a11028781a465727a47403f6931019e3dd472
Error response from daemon: repository alegou/test not found: does not exist or no pull access
agoulti@instance-1:~$ sudo docker pull alegou/testUsing default tag: latest
Error response from daemon: repository alegou/test not found: does not exist or no pull access
agoulti@instance-1:~$ sudo docker pull alegou/test:latest
Error response from daemon: repository alegou/test not found: does not exist or no pull access
```



I can also confirm that it works in (some?) non-interactive context.

Based on [this info](https://rosettacode.org/wiki/Check_output_device_is_a_terminal), I take it that piping the output to cat should make the context non-iteractive:

```
agoulti@instance-1:~$ cat pull.go
package main
 
import (
    "os"
    "fmt"
    "golang.org/x/crypto/ssh/terminal"
)
 
func main() {
    if terminal.IsTerminal(int(os.Stdout.Fd())) {
        fmt.Println("Hello terminal")
    } else {
        fmt.Println("Who are you?  You're not a terminal.")
    }
}
agoulti@instance-1:~$ go run pull.go
Hello terminal
agoulti@instance-1:~$ go run pull.go | cat
Who are you?  You're not a terminal.
```

However, if I put the pull request in a script and pipe it to "cat", it asks to log in anyway:

```
agoulti@instance-1:~$ cat pull.sh
sudo docker pull gcr.io/<my-repo>/whale@sha256:14aea6cc3fd31e3c4e3f454c585a11028781a465727a47403f6931019e3dd472
agoulti@instance-1:~$ ./pull.sh

Please login prior to pull:
Username: ^C
agoulti@instance-1:~$ ./pull.sh | cat

Please login prior to pull:
Username: ^C
```

It does, however, fail fast if the stdin is redirected

```
agoulti@instance-1:~$ sudo ./pull.sh </dev/null 

Please login prior to pull:
Error: Cannot perform an interactive login from a non TTY device
```

**Comment by adrianludwin** [comment]
Thanks, we'll file this to GCR then.
