### ISSUE TITLE
download.docker.com IPV6 support

### ISSUE THREAD

**Issue by aparcar** [docker/docker#31817]
---------------------------------------------------
GENERAL SUPPORT INFORMATION
---------------------------------------------------

The official Docker repository does not support IPV6.

---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**

We use an _deb Proxy_, as dowload.docker.com uses https all traffic is simply forwarded. 
The _deb Proxy_ is reached via IPV6 and so tries to forward to https://download.docker.com via IPV6.
The request fails as there is [no IPv6](https://ip6.nl/#!download.docker.com)

**Steps to reproduce the issue:**

Use IPV6 _deb Proxy_, forwards https traffic

**Describe the results you received:**

Updating Docker packages fails

**Comment by thaJeztah** [comment]
ping @andrewhsu @friism

**Comment by andrewhsu** [comment]
We'll look into it and see if we can an ipv6 address for it.

**Comment by aparcar** [comment]
Looks good, thanks!

**Comment by thaJeztah** [comment]
Thanks for reporting @aparcar!
