### ISSUE TITLE
Stack deploy stopped working as expected

### ISSUE THREAD

**Issue by rommik** [docker/docker#31828]
I am not sure if this is the right place to post. If there's a better channel to escalate this issue, please let me know and I'll be happy to do it.

I have a swarm of about 15 physical nodes. I've been deploying a stack of three services on them for the past 2 hours without any issues. 
The stack is composed of (mongo from docker hub, and two apps from private docker hub)
Suddenly, the deployment stopped and 1 our of three services does not run.  It is always one of the two private services.

I inspected the /var/log/syslog but I don't see any errors. What else can I do to trouble shoot?

![image](https://cloud.githubusercontent.com/assets/5719781/23920920/f48966de-08d2-11e7-8aef-086fa2eed9f6.png)

Could this be related to https://github.com/docker/docker/issues/31698 ? However, I don't see the errors in the logs.

**Comment by rommik** [comment]
It seems I've reached a limit to how many containers I can deploy? Is it possible that the issue is in one of networks that is shared by all containers? For example, I have proxy network shared by one container in each stack.

I have over 50 stacks already running.

The way I figured our it is by removing another stack and my example in the screenshot immediately worked. However, when I attempted to restore the other stack, it experienced the same issue.

**Comment by tonistiigi** [comment]
@rommik Please follow the issue template https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md . Include daemon logs from the affected nodes(in debug mode if possible) and the steps you used to produce the problem and steps that you used to verify it.

cc @sanimej in case some of these network warnings points to anything

**Comment by rommik** [comment]
@tonistiigi thank you for your reply.  My issue is related to https://github.com/docker/docker/issues/31019
