### ISSUE TITLE
CONTRIBUTORS.md symlink

### ISSUE THREAD

**Issue by cblecker** [docker/docker#31825]
As of https://github.com/tools/godep/pull/522 , "AUTHORS" and "CONTRIBUTORS" files are considered legal/licence files that are pulled down with godep. Right now when vendoring docker, this matches https://github.com/docker/docker/blob/master/project/CONTRIBUTORS.md and pulls down this symlink, however the document it links to (https://github.com/docker/docker/blob/master/CONTRIBUTING.md) isn't pulled down as it's named differently. This causes godep to vendor a broken symlink during a `godep save`.

Is it possible to either:
- Rename the project/CONTRIBUTORS.md symlink to CONTRIBUTING.md to match the file it links to
- Remove the project/CONTRIBUTORS.md symlink entirely
- Change project/CONTRIBUTORS.md to regular markdown file, with a link to CONTRIBUTING.md

Any of those options should ensure that godep doesn't vendor a broken symlink.

Thank you!

**Comment by tonistiigi** [comment]
Seems like a godep issue. They should not save broken symlinks but their targets.

**Comment by thaJeztah** [comment]
I'm not sure the symlink serves much use though. The README already has a link to CONTRIBUTING.MD (https://github.com/docker/docker/blame/9055eb0ce48b663013891d35dbd67978930ac0cb/project/README.md#L8), so personally, I'd be okay with any of the proposed solutions if it solves the situation
