### ISSUE TITLE
Registry mirrors config loss when docker update

### ISSUE THREAD

**Issue by fewspider** [docker/docker#31838]
```
Version 17.03.0-ce-mac2 (15654)
Channel: stable
1d7d97bbbd
```
![2017-03-15 13 40 55](https://cloud.githubusercontent.com/assets/3256161/23935137/1465819c-0985-11e7-9738-3ad77bf3343d.png)

**Comment by vdemeester** [comment]
@fewspider I think the issue should belong to https://github.com/docker/for-mac/ 👼 
/cc @jeanlaurent @ebriney

**Comment by djs55** [comment]
I believe this is a duplicate of https://github.com/docker/for-mac/issues/1354

The fix is in master and so future upgrades shouldn't have this problem -- I'm sorry for the inconvenience. Thanks for your report!

**Comment by thaJeztah** [comment]
Let me go ahead and close this one, as we have https://github.com/docker/for-mac/issues/1354 for tracking

**Comment by fewspider** [comment]
thanks
