### ISSUE TITLE
Swarm nodes status pending when using the swarm image

### ISSUE THREAD

**Issue by mangelov95** [docker/docker#31855]
**Description**

I just updated to Docker 17.03 (was running 1.12 before) and at the moment my swarm cannot be properly initialised - the status of the nodes is always set to pending, while they are being okay and there are no error statements in the log.

**Steps to reproduce the issue:**
1. Start a swarm-manager from the swarm image.
2. Start 2 swarm nodes, connected to the swarm-manager
3. Execute `docker info` on the swarm-manager.

**Describe the results you received:**

I always get `Status: Pending` shown for my nodes.

**Describe the results you expected:**

The status to be healthy, since the nodes worked before.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 17.03.0-ce, build 60ccb22
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: swarm/1.2.5
Role: primary
Strategy: spread
Filters: health, port, containerslots, dependency, affinity, constraint
Nodes: 2
 (unknown): hub-swarm-node-4.xxx:2376
  └ ID: 
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ UpdatedAt: 2017-03-15T15:25:12Z
  └ ServerVersion: 
 (unknown): hub-swarm-node-5.xxx:2376
  └ ID: 
  └ Status: Pending
  └ Containers: 0
  └ Reserved CPUs: 0 / 0
  └ Reserved Memory: 0 B / 0 B
  └ Labels: 
  └ UpdatedAt: 2017-03-15T15:25:12Z
  └ ServerVersion: 
Plugins: 
 Volume: 
 Network: 
Swarm: 
 NodeID: 
 Is Manager: false
 Node Address: 
Kernel Version: 4.4.0-66-generic
Operating System: linux
Architecture: amd64
CPUs: 0
Total Memory: 0 B
Name: 99af15b7d254
Docker Root Dir: 
Debug Mode (client): false
Debug Mode (server): false
WARNING: No kernel memory limit support
Experimental: false
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
ping @dongluochen PTAL

**Comment by dongluochen** [comment]
@mangelov95 What discovery method do you use? Can you turn on swarm debug logs with `swarm --debug -l debug manage ...` and send the logs? 

I'm not sure if this is related to docker-17.03.0-ce or not. I can set up a cluster with nodes docker-17.03.0-ce.

**Comment by mangelov95** [comment]
@dongluochen Thanks for the help, I solved the problem! I enabled the logs as you said and I saw that it doesn't find the hosts, so I had to bind the /etc/hosts file inside the container. I'm not sure if I had to do that previously, I don't remember. I'll close this issue now.

**Comment by thaJeztah** [comment]
Instead of bind-mounting `/etc/hosts`, you can also add entries to the cotnainers hosts file through the `--add-host` flag
