### ISSUE TITLE
dockerd should allow for both TLS and non-TLS ports

### ISSUE THREAD

**Issue by jamshid** [docker/docker#31872]
**Description**
I thought I could add `-H tcp://0.0.0.0:2375 --tlsverify=false` (swapping the order made no difference) to the end of the command line in /etc/systemd/system/docker.service.d/10-machine.conf, but both ports 2376 and 2375 still end up requiring TLS. 

It would be good if dockerd could listen on two ports, one TLS and the other non-TLS.

I'm using this as a workaround but would like to do this without another container. Also, the socat workaround _might_ be triggering this: https://github.com/docker/docker/issues/31438.
```
docker run -d --restart always -p 2375:2375 --volume=/var/run/docker.sock:/var/run/docker.sock --name=docker-http -m 50m sequenceiq/socat
```

I want this because I'm running jenkins in a container and want jenkins jobs to be able to run docker commands. I can't map /var/run/docker.sock because the container runs as user jenkins, not root. And I'd rather not write the docker server's ca.pem, key.pem, cert.pem into the container.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 94
 Running: 12
 Paused: 0
 Stopped: 82
Images: 2596
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-67-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 31.31 GiB
Name: 61
ID: PZJW:CVPM:HPPS:7LRV:UZXE:RQPI:4ALK:7HR3:OSX2:OTAN:T4SJ:A7WM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Labels:
 provider=generic
Experimental: false
Insecure Registries:
 192.168.2.61:5000
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
I get the use-case for the "jenkins" container. Just curious if your example is your actual setup, because `0.0.0.0:2375` would allow unprotected access to the daemon from anywhere; there's not much use of still having a `0.0.0.0:2376` as well.

> I thought I could add -H tcp://0.0.0.0:2375 --tlsverify=false (swapping the order made no difference)

Yes, that's correct, the `-H` and `--tlsverify` flags have no one-on-one "relation", so the `--tlsverify` flag would apply to all `-H` options.

If we would want to implement this, we'd probably need to use the CSV syntax (similar to what's used for the `--mount` flag), e.g. 

    --listen addr=tcp://127.0.0.1:2375,tlsverify=false \
    --listen addr=tcp://0.0.0.0:2376,tlscacert=/foo/bar,tlscert=/foo/baz,.....

@diogomonica any suggestions?

**Comment by justincormack** [comment]
You can add the `jenkins` user to the `docker` group and then it can access a shared docker socket (make sure the group numbers match).

**Comment by jamshid** [comment]
Thanks, will try jenkins group change.

Not using new docker swarm yet but hopefully that's compatible. 

Yeah having both TLS and non-TLS ports is not good security, but was thinking maybe I'd put non-TLS on a internal ip. Really should make jenkins allow upload of docker server credentials, or maybe could  docker "secrets" for the docker server credentials?

**Comment by diogomonica** [comment]
As a path forward as an infosec community, nothing should ever support non-TLS.

**Comment by thaJeztah** [comment]
secrets are currently only for services, not for `docker run`, but you can bind-mount the keys if needed; changing the group is probably a good solution though

**Comment by jamshid** [comment]
Okay. I guess even if I change jenkins to a service, whether a docker client key is provided to jenkins by secrets or by mapping in a volume, anyone with access to the docker server can `docker exec` into the jenkins container and access the key.

Anyway, after some reading (https://github.com/jenkinsci/docker/issues/263), trial and error I was able to get a docker client in a jenkins container working with a mapped socket (`-v /var/run/docker.sock:/var/run/docker.sock`) using: 
```
FROM jenkins:2.32.2
...
# Force jenkins user to have permission to user docker.sock if mapped in. Used comments
# in https://github.com/jenkinsci/docker/issues/263 but had to add the chown, otherwise
# /var/jenkins_home is owned by root (despite base Dockerfile having doing same chown?!).
USER 0
CMD if DOCKER_GID=$(stat -c '%g' /var/run/docker.sock) ; then \
    groupadd -for -g ${DOCKER_GID} docker && \
    usermod -aG docker jenkins || exit 1 ; fi ; \
    chown -R jenkins "$JENKINS_HOME" /usr/share/jenkins/ref ; \
    su -p jenkins -c 'env HOME=~jenkins USER=jenkins LOGNAME=jenkins PATH=/usr/local/bin:/usr/bin:/bin /usr/local/bin/jenkins.sh'
```

Thanks for the help feel, free to close this if non-TLS (or different TLS settings for different interfaces/ports?) is not planned.

**Comment by thaJeztah** [comment]
Let me go ahead and close this for housekeeping, but feel free to continue the conversation 👍
