### ISSUE TITLE
Upgrade to 1.12.6-cs results in dockerd unresponsive

### ISSUE THREAD

**Issue by thiagoalves** [docker/docker#31885]
**Description**

When docker is upgraded from 1.12.3-cs4 to 1.12.6-cs9 (or cs10), dockerd hangs in specific situations.

**Steps to reproduce the issue:**
1. Create a Ubuntu 16.04 box (I have used EC2 r3.large instance, ami-f4cc1de2, us-east-1)
2. Install docker-engine 1.12.3-cs4
```
curl -fsSL 'https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e' | sudo apt-key add -

add-apt-repository \
   "deb https://packages.docker.com/1.12/apt/repo/ \
   ubuntu-$(lsb_release -cs) \
   main"

apt-get update

apt-get install --no-install-recommends \
    apt-transport-https \
    curl \
    software-properties-common

apt-get -y install docker-engine=1.12.3~cs4-0~xenial
```
3. Run 100 containers and try to run docker ps a few times. It will run fast.
```
for i in {1..100}; do docker run -d -it --restart=always --name poc_$i talves/health_poc; done
```
then
```
time docker ps -qa | wc -l
```
4. Upgrade to 1.12.6-cs10
```
apt-get -y install docker-engine
```
5. Try to run one container (the command will run forever)
```
docker run -d -it --restart=always --name poc_1_12_6 talves/health_poc
```
6. Try to run docker ps (it will take ages)
```
time docker ps -qa | wc -l
```
7. Downgrade to cs4
```
apt-get install docker-engine=1.12.3~cs4-0~xenial
```
8, Repeat steps 5 and 6. They will work fine. If you upgrade to 17.03-ce, it will also work fine

**Describe the results you received:**
Fast response of dockerd, regardless of docker version

**Describe the results you expected:**
Docker 1.12.3 and 17.03 are fast, but 1.12.6-cs9 and cs10 are very slow under certain conditions

**Additional information you deem important (e.g. issue happens only occasionally):**
I am using a custom docker image for tests, but you will get similar results if you use other images with healthcheck enabled:

`docker run -d -it --restart=always --health-cmd='curl --fail http://localhost/ || exit 1' --health-interval 10s --health-timeout 1s --health-retries 3 --name poc_0 php:7.0-apache`

**Output of `docker version`:**
```
Client:
 Version:      1.12.6-cs10
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   54bb958
 Built:        Mon Mar  6 03:49:00 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6-cs10
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   54bb958
 Built:        Mon Mar  6 03:49:00 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 101
 Running: 48
 Paused: 0
 Stopped: 53
Images: 1
Server Version: 1.12.6-cs10
Storage Driver: devicemapper
 Pool Name: docker-202:1-275400-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 1.279 GB
 Data Space Total: 107.4 GB
 Data Space Available: 5.401 GB
 Metadata Space Used: 13.53 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.134 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.110 (2015-10-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: host null bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor seccomp
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 14.94 GiB
Name: ip-10-69-11-232
ID: NQHR:6JJ6:REF6:6GMR:5PTF:QB4Z:EANI:PYUH:UMFI:Q2TH:ZC4Z:YUVM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
EC2 r3.large instance, ami-f4cc1de2, us-east-1

**Comment by thaJeztah** [comment]
ping @mlaventure PTAL

**Comment by cpuguy83** [comment]
When you get a hang, can you send `SIGUSR1` to the docker daemon and there should be a stack trace in the daemon logs.

Thanks!

**Comment by mlaventure** [comment]
@thiagoalves can you also provide the daemon logs (on top of the stacktrace requested by @cpuguy83), there may be an issue during startup.

Is `live-restore` enabled?

**Comment by thiagoalves** [comment]
@cpuguy83 Logs with stack dump: https://s3.amazonaws.com/temp-talves/dockerd.log

@mlaventure The behavior is the same regardless of `live-restore`. The logs above are with `live-restore` disabled

**Comment by MichaelMackus** [comment]
+1

I also just got an unresponsive docker daemon (i.e. all docker commands stall indefinitely) after upgrading to 1.12.6. 

```shell
sh-4.2# docker --version
Docker version 1.12.6, build 7392c3b/1.12.6
```

**Comment by thiagoalves** [comment]
Ok. I have done a lot of extra tests and the results are:

- `1.12.3-cs4`: works for a while, then performance starts to degrade due to `dockerd` using too many FDs until it crashes
- `1.12.6-cs10`: totally unusable
- `17.03-0-ee` upgraded from `cs4` (using `aufs`): works fine
- `17.03-0-ee` (fresh install with `overlay2`): works fine - performance seems to be slightly better than `aufs`

The only caveat with EE is that it leaves a lot of hanged "ExecIDs", but this is not degrading performance anymore. I think it will be fixed by #30984

**Comment by cpuguy83** [comment]
@thiagoalves @mlaventure Looks like somethings hung in containerd.
The stack trace you provided shows docker is trying to call `AddProcess` (from a `docker exec` request) and the call just never finishes.

Also since the logs are filled with `context deadline exceeded`, it would seem indeed this is the case.

<details>

```
goroutine 56190 [select]:
google.golang.org/grpc/transport.(*Stream).Header(0xc821776d20, 0xc821776d20, 0x0, 0x0)
	/usr/src/docker/vendor/src/google.golang.org/grpc/transport/transport.go:221 +0x242
google.golang.org/grpc.recvResponse(0x7f12d81a0e80, 0x2b0b120, 0x0, 0x0, 0x0, 0x0, 0x7f12d81a0eb8, 0xc8203e2800, 0x7f12d81a0ee0, 0xc8203e2820, ...)
	/usr/src/docker/vendor/src/google.golang.org/grpc/call.go:54 +0x4e
google.golang.org/grpc.Invoke(0x7f12d81777d8, 0xc82226cc90, 0x1ed5af0, 0x15, 0x1bfc860, 0xc821d22300, 0x1ba3280, 0x2b0b120, 0xc82038fd90, 0x0, ...)
	/usr
Mar 16 17:46:16 ip-10-69-11-35 dockerd[1172]: /src/docker/vendor/src/google.golang.org/grpc/call.go:178 +0xae6
github.com/docker/containerd/api/grpc/types.(*aPIClient).AddProcess(0xc82007e670, 0x7f12d81777d8, 0xc82226cc90, 0xc821d22300, 0x0, 0x0, 0x0, 0xc8231e3280, 0x0, 0x0)
	/usr/src/docker/vendor/src/github.com/docker/containerd/api/grpc/types/api.pb.go:963 +0xec
github.com/docker/docker/libcontainerd.(*client).AddProcess(0xc820059500, 0x7f12d81777d8, 0xc82226cc90, 0xc8206d8880, 0x40, 0xc823c82e40, 0x40, 0x0, 0x0, 0xc8231e31b0, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/libcontainerd/client_linux.go:98 +0x97c
github.com/docker/docker/daemon.(*Daemon).ContainerExecStart(0xc820331860, 0x7f12d81777d8, 0xc82226cc90, 0xc823c82e40, 0x40, 0x0, 0x0, 0x7f12d8178f10, 0xc8226f0e80, 0x7f12d8178f10, ...)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/exec.go:207 +0x1162
github.com/docker/docker/daemon.(*cmdProbe).run(0xc820a1a561, 0x7f12d81777d8, 0xc82226cc90, 0xc820331860, 0xc8206a70e0, 0x45f1e1, 0x0, 0x0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/health.go:88 +0x8b6
github.com/docker/docker/daemon.monitor.func1(0x7f12d81aa9f8, 0xc820a1a561, 0x7f12d81777d8, 0xc82226cc90, 0xc820331860, 0xc8206a70e0, 0xc822277500, 0xed05cc667, 0x2bdabab6, 0x2ae6ee0)
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/health.go:160 +0x82
created by github.com/docker/docker/daemon.monitor
	/usr/src/docker/.gopath/src/github.com/docker/docker/daemon/health.go:175 +0x4af
```

</details>

**Comment by mlaventure** [comment]
@thiagoalves I do not see containerd stacktrace in the logs, did you send a `SIGUSR1` to `docker-containerd` too?

**Comment by thiagoalves** [comment]
@mlaventure Sorry, completely forgot about it. Fortunately the issue is reproducible, so here's a new log with stack traces for `dockerd` and `docker-containerd`

https://s3.amazonaws.com/temp-talves/dockerd-containerd.log

Thank you

**Comment by mlaventure** [comment]
@thiagoalves this is the healthcheck context issue, it's fixed in 1.13.0 and I'm guessing in the most recent version of `cs`

**Comment by thaJeztah** [comment]
@cpuguy83 do you know which version of cs this is fixed in? ^^

**Comment by mlaventure** [comment]
@thiagoalves it looks like the trace got truncated in your log, also the one from `docker-containerd` is missing from it?

Could you try and retrieve them? 

Thanks

**Comment by thiagoalves** [comment]
@mlaventure Please try https://s3.amazonaws.com/temp-talves/1703.log.gz

**Comment by mlaventure** [comment]
@thiagoalves sorry for the delay, I went on PTO.

The second log have the same issue unfortunately, the complete traces are missing from it.

**Comment by cpuguy83** [comment]
@thiagoalves Thanks.
Since we won't be making any patches to 1.12 and 17.03 is working I think it makes sense to close.

If you do find the issue come up on 17.03 (or any other issue of course!) please open a new issue.
Thanks again! 🙇
