### ISSUE TITLE
Enable NUMA support for docker swarm

### ISSUE THREAD

**Issue by yonger1516** [docker/docker#31887]
Background
=========
Some distributed applications(MS,bigdata and so on)have CPU intensive workload, which need bind each container/replica to a specific NUMA node to gain a better performance.

Currently
=========
1.can't find cpuset and cpuset-mem options in swarm service create/update command
2.can't assign different options for different replica within the same service

As a PAAS tool, I think Docker should enable such infrastructure performance features.

**Comment by thaJeztah** [comment]
Thanks for opening; we have an "epic" to track options that are not (yet) available for services; https://github.com/docker/docker/issues/25303.

For this particular option, there's already an issue here; https://github.com/docker/docker/issues/30477

I'll close this one as it's a duplicate, and to keep the discussion central; you can subscribe to the linked issue to stay informed on updates. Feel free to comment though 👍
