### ISSUE TITLE
`ARG` should be scoped to `FROM`

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#31892]
Currently, when using multiple `FROM` statements in the `Dockerfile` all the previous commands are reset after a `FROM` statement. But `ARG` statement behaves like a global and leaks to the next `FROM`. Only the values passed by the user should be global, the `ARG` definitions should be local to the `FROM` statement.

The leaking arg means that change in arguments in one block also invalidates all the commands in another block.

```
FROM busybox
ARG foo=bar
RUN env
FROM busybox
ARG baz=bar
RUN env
```

Currently, last command will print both `foo` and `baz` while it should only show `baz`.

When https://github.com/docker/docker/pull/31352 gets merged that means that `ARG` defined before first `FROM` should only be used for replacing a `FROM` value itself. If the same arg is needed in one of subblocks it just needs to be redefined. There is no change for user as they still need to only pass the value once.

This may seem like an obscure thing nobody will encounter in practice atm but it will become much more relevant after https://github.com/docker/docker/issues/31067#issuecomment-287126021

@dnephin

**Comment by duglin** [comment]
I think that's a subtlety that will be lost on lots of people and we'll get a lot of issues on it. I think resetting things on 2+ FROMs makes sense, but I don't think we should reset it on the first.

```
ARG foo
FROM $foo
ARG foo
RUN echo I built with $foo
```

instead of just:
```
ARG foo
FROM $foo
RUN echo I built with $foo
```
is kind of annoying. When the majority of cases will only have a single FROM I think we should optimize for them.

**Comment by tonistiigi** [comment]
@duglin First, the syntax you are describing is not valid at all atm so we can't say that users are confusing these cases. They are also different from the history array as any `ARG` before `FROM` is not commited and not part of image history. We can't also optimize for the first `FROM` as

```
arg foo=latest
from busybox:latest
from busybox:$foo
```

is perfectly valid use case. Only thing we could do is count the number of `FROM` statements but I think that would be more complicated to the user than just the rule to redefine the var.

Also from practical cases, it is quite unlikely that you would actually need the arg that defines an image name for the `FROM` statement somewhere inside the image. I would even say that simple

```
ARG foo=latest
FROM busybox:$foo
RUN env
```

should not put `foo` in the env. Because if I do `docker build --build-arg foo=v1.0` and it matches the same image that I previously build with name `busybox:latest` it should not invalidate the cache.

**Comment by duglin** [comment]
> On Mar 16, 2017, at 2:21 PM, Tõnis Tiigi <notifications@github.com> wrote:
> 
> Also from practical cases, it is quite unlikely that you would actually need the arg that defines an image name for the FROM statement somewhere inside the image

I disagree since as I was playing with the other PR earlier today I was unable to verify which image was actually used in the FROM, I had “FROM ubuntu:$tag” , because the value of “tag” is not saved any place. So its very possible that someone might add that “RUN echo ubuntu:$tag > /image.version” type of thing to their build so they can a record of their build saved in the image.

**Comment by duglin** [comment]
You realize this would be so much easier if people didn't have to specify ARG at all :-)

**Comment by tonistiigi** [comment]
> So its very possible that someone might add that “RUN echo ubuntu:$tag > /image.version” type of thing to their build so they can a record of their build saved in the image.

@duglin I'm not saying that we should forbid it. It may be useful for debugging situations like you describe here. There is a very easy workaround if you need it. Redefine `ARG`, everything will start to work and there will be an item in the history array that shows that this arg was defined and if the default value was used or not. Instead of invalidating the cache and showing incomplete history array for all users that don't need the debugging case.

**Comment by thaJeztah** [comment]
Should we revisit the decision to use `ARG` for overriding the `FROM`, and have a dedicated option for that? The whole logic starts to get really complicated (`ARG` before `FROM` is allowed, but not in history, but `ARG` _after_ is, and exists until the next `FROM`). I'm starting to worry that we end up with some odd behavior that we regret in a while, and cannot get rid of

**Comment by tonistiigi** [comment]
@thaJeztah I'm not sure how dedicated option helps with any of this. In fact it makes it worse as you can't do 

```
arg foo=latest
from busybox:latest
from busybox:$foo
```

I made the current fix for this on top of #31352 but it doesn't really depend on it. I could fix it without it as well but I haven't seen better solutions for that problem.

**Comment by thaJeztah** [comment]
@tonistiigi was thinking of going as far as allowing `FROM` to be overridden without having to define an `ARG`. This would also make the UX consistent (not having each Dockerfile author invent a new name for the ARGS). We'd need a syntax for overriding multiple `FROM` though, in that case

**Comment by tonistiigi** [comment]
@thaJeztah So user sets it as `--build-arg` but it isn't defined in `Dockerfile`? It's not the worst(if you can still set the default) but I don't see why we need the special case. If people prefer that it's fine by me.

**Comment by dweomer** [comment]
I feel like there is value in letting top-level `ARG` entries bleed into subsequent stages. Working with this experimental feature as of RC2, I was surprised that this was not the case. In other words, I expected that `ARG` entries defined within a stage would be limited to that stage whereas `ARG` at the top of the `Dockerfile`, aka before any `FROM`, could be used in any stage.

If we do not want to allow for this kind of bleed-through, maybe it would make more sense to change the `FROM` syntax to support Bourne-style variable expansion? Something like:

```
FROM alpine:${ALPINE:=latest}
RUN # ...
```

**Comment by dnephin** [comment]
The default value defined by an `ARG` before from **does** bleed into subsequent stages, you just have to be explicit about which stages use it. For example

```
ARG something=defaultvalue
FROM busybox as base
ARG something # this will default to defaultvalue not ""
```

This is important because otherwise a change in **any** ARG before FROM would invalidate the cache of every stage.

I guess the docs I added in #32486 don't make that totally clear. So we should update the docs.

**Comment by dweomer** [comment]
Thanks @dnephin, I missed that in my testing as I was missing the explicit enlistment of the globally scoped `ARG` into the stage via re-declaration. The repetition seems unfortunate but your build cache argument makes perfect sense.
