### ISSUE TITLE
Docker CE install fails on problem with audit-libs-python dependency

### ISSUE THREAD

**Issue by kinghuang** [docker/docker#31893]
**Description**

I'm trying to install Docker CE on RHEL 7.3. Yum is reporting an error with `audit-libs-python`.

**Steps to reproduce the issue:**

1. Follow the instructions on [Get Docker for CentOS](https://docs.docker.com/engine/installation/linux/centos/), for Docker CE.
2. Execute `sudo yum install docker-ce`.

**Describe the results you received:**

The installation fails due to the following:

```
Error: Package: audit-libs-python-2.6.5-3.el7.x86_64 (prod-64-7)
           Requires: audit-libs(x86-64) = 2.6.5-3.el7
           Installed: audit-libs-2.6.5-3.el7_3.1.x86_64 (@rhel-x86_64-server-7)
               audit-libs(x86-64) = 2.6.5-3.el7_3.1
           Available: audit-libs-2.3.3-4.el7.x86_64 (prod-64-7)
               audit-libs(x86-64) = 2.3.3-4.el7
           Available: audit-libs-2.4.1-5.el7.x86_64 (prod-64-7)
               audit-libs(x86-64) = 2.4.1-5.el7
           Available: audit-libs-2.6.5-3.el7.x86_64 (prod-64-7)
               audit-libs(x86-64) = 2.6.5-3.el7
```

**Describe the results you expected:**

I expected the Docker CE engine to be installed.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**

This is on a new RHEL 7.3 VM. I'm using the CentOS instructions, since the RHEL instructions only cover Docker EE.

**Comment by kinghuang** [comment]
Sorry, it's a local problem. Closing issue.

**Comment by jiayiyang** [comment]
hello, i have the same problem, could you please tell how to fix this?
