### ISSUE TITLE
docker engine fails to re-start (Log shows panic: runtime error: invalid memory address)

### ISSUE THREAD

**Issue by msterin** [docker/docker#31903]
**Description**

Docker engine hangs on restart (or VM reboot) when it has a managed plugin installed and this plugin has volumes created in a docker session. 

During the hang, `journalctl` shows the engine has  tried and failed to reach the plugin socket, then after retries it crashed (`panic: runtime error: invalid memory address`)  and systemd tried to restart it, with the same result.

Stopping the engine , removing `/var/lib/docker/volumes/metadata.db` and restarting the engine cures the crash and hang. However it is not usable in testing or production.

_It feels like the engine is trying to pick something (volume labels ?) from metadata file **before** it initialized the plugin, and does not handle failure very gracefully_

We see it on Docker 17-ce and 1.13 for docker-volume-vsphere managed plugin . 
Docker-engine seems to have a similar issue with legacy plugin but  handles it  a bit better - after a delay (~15 sec) it starts but the legacy plugin in question is blocked and the volumes from this plugin are not shown in `docker volume ls`

 Log and  more details below. 

**Steps to reproduce the issue:**

0. Pre-reqs: VMWare ESX with a Docker host VM  inside. (Ubuntu 16.04 Mini) and docker-volume-vsphere [VIB](https://github.com/vmware/docker-volume-vsphere/releases/download/0.12/vmware-esx-vmdkops-0.12.3f64805.vib)  installed. 
  0.1 See https://github.com/vmware/docker-volume-vsphere/ for more info 
1. Install managed plugin (test  build is cnastorage/docker-volume-vsphere:0.12)
2. docker volume create -d cnastorage/docker-volume-vsphere:0.12 myVolume 
3. `systemctl restart docker` or `reboot -f`

**Describe the results you received:**

With managed plugin: 
* Docker hangs. Log shows the engine tries to reach plugin, fails to find the socket, retries, gives up, crashes and systemd tries to restart it with the same results. Forever.
With legacy plugin:
* Docker starts, but with no plugin. Log shows the engine tries to reach plugin, fails to find the socket, retries, gives up, ignores pugin and starts. So volumes from the plugin are not visible to docker anymore. 

**Describe the results you expected:**
I expected it to keep working after restart

**Additional information you deem important (e.g. issue happens only occasionally):**

It happens in 100% of tries we did. I think it is new for 1.13.

stopping the engine removing `/var/lib/docker/volumes/metadata.db` and starting the engine bring it fully back to life

**Output of `docker version`:**

```
Docker version 17.03.0-ce, build 3a232c8
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-67-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.3 MiB
Name: ubuntu-1
ID: IMDX:C5I6:HUNQ:ZKHX:DOC5:F5S2:RFNN:JDUZ:DNNA:V7DU:PL5R:Q6CC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

* VMWare ESXi 6.5 under VMWare Fusion on Mac. 
* Ubuntu mini 6.04 under ESXi

**Log**
**Engine log with managed plugin**

```
Mar 16 13:10:34 ubuntu-1 systemd[1]: Starting Docker Application Container Engine...
Mar 16 13:10:34 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:34.223383042-07:00" level=info msg="libcontainerd: new containerd process, pid: 5994"
Mar 16 13:10:35 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:35.244112731-07:00" level=warning msg="libcontainerd: client is out of sync, restore was called on a fully synced container (bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c)."
Mar 16 13:10:35 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:35.364063762-07:00" level=info msg="[graphdriver] using prior storage driver: aufs"
Mar 16 13:10:35 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:35.367215603-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Capabilities: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Capabilities: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 1s"
Mar 16 13:10:36 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:36.368393938-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Capabilities: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Capabilities: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 2s"
Mar 16 13:10:38 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:38.369457591-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Capabilities: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Capabilities: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 4s"
Mar 16 13:10:42 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:42.370994272-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Capabilities: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Capabilities: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 8s"
Mar 16 13:10:50 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:50.372720683-07:00" level=warning msg="Volume driver msterin/docker-volume-vsphere:0.12 returned an error while trying to query its capabilities, using default capabilties: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Capabilities: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory"
Mar 16 13:10:50 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:50.374940966-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Get: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Get: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 1s"
Mar 16 13:10:51 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:51.376780723-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Get: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Get: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 2s"
Mar 16 13:10:53 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:53.378527746-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Get: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Get: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 4s"
Mar 16 13:10:57 ubuntu-1 dockerd[5991]: time="2017-03-16T13:10:57.380242472-07:00" level=warning msg="Unable to connect to plugin: /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock/VolumeDriver.Get: Post http://%2Frun%2Fdocker%2Fplugins%2Fbed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c%2Fvsphere.sock/VolumeDriver.Get: dial unix /run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock: connect: no such file or directory, retrying in 8s"
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x94cd9b]
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: goroutine 50 [running]:
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: panic(0x16dc220, 0xc420010060)
Mar 16 13:11:05 ubuntu-1 dockerd[5991]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: github.com/docker/docker/volume/store.lookupVolume(0xc420408390, 0x22, 0xc42048a928, 0x3, 0x4ad287, 0xc42000e9c0, 0xc420344000, 0x8000)
Mar 16 13:11:05 ubuntu-1 dockerd[5991]:         /usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/store.go:522 +0x2cb
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: github.com/docker/docker/volume/store.(*VolumeStore).restore.func2(0xc42048a930, 0xc42000f620, 0xc420013630, 0xc42048a928, 0x3, 0xc420408390, 0x22, 0xc4204083c0, 0xc420408420)
Mar 16 13:11:05 ubuntu-1 dockerd[5991]:         /usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/restore.go:36 +0xf8
Mar 16 13:11:05 ubuntu-1 dockerd[5991]: created by github.com/docker/docker/volume/store.(*VolumeStore).restore
Mar 16 13:11:05 ubuntu-1 dockerd[5991]:         /usr/src/docker/.gopath/src/github.com/docker/docker/volume/store/restore.go:70 +0x1cb
Mar 16 13:11:05 ubuntu-1 systemd[1]: docker.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Mar 16 13:11:05 ubuntu-1 systemd[1]: Failed to start Docker Application Container Engine.
Mar 16 13:11:05 ubuntu-1 systemd[1]: docker.service: Unit entered failed state.
Mar 16 13:11:05 ubuntu-1 systemd[1]: docker.service: Failed with result 'exit-code'.
Mar 16 13:11:05 ubuntu-1 systemd[1]: Starting Docker Application Container Engine...
```

When it is happening. `/run/docker/plugins/bed87fb48b005d0e797cd1b45343f1a709e798d9e559fa2dd73721242a590e3c/vsphere.sock` indeed does not exist (checked with `ls``)

**Engine log with legacy plugin**

```
```Mar 16 21:55:05 sc-rdops-vm18-dhcp-57-89 dockerd[1185]: time="2017-03-16T21:55:05.980160846Z" level=warning msg="Unable to locate plugin: vsphere, retrying in 1s"
Mar 16 21:55:06 sc-rdops-vm18-dhcp-57-89 dockerd[1185]: time="2017-03-16T21:55:06.981606215Z" level=warning msg="Unable to locate plugin: vsphere, retrying in 2s"
Mar 16 21:55:08 sc-rdops-vm18-dhcp-57-89 dockerd[1185]: time="2017-03-16T21:55:08.982284873Z" level=warning msg="Unable to locate plugin: vsphere, retrying in 4s"
Mar 16 21:55:12 sc-rdops-vm18-dhcp-57-89 dockerd[1185]: time="2017-03-16T21:55:12.983038844Z" level=warning msg="Unable to locate plugin: vsphere, retrying in 8s"
Mar 16 21:55:20 sc-rdops-vm18-dhcp-57-89 dockerd[1185]: time="2017-03-16T21:55:20.983862179Z" level=error msg="Handler for POST /v1.25/volumes/create returned error: create xyz: create xyz: Error looking up volume plugin vsphere
```

and the docker engine starts without registering the (legacy) plugin.

**Related to**

https://github.com/vmware/docker-volume-vsphere/issues/1039

//CC @pdhamdhere @lachnerd

**Comment by anusha-ragunathan** [comment]
the panic happens https://github.com/docker/docker/blob/1.13.x/volume/store/store.go#L522. Possibly because when we try printing `v.DriverName()`

**Comment by cpuguy83** [comment]
🤦‍♂️

**Comment by msterin** [comment]
So the crash is a bug in error print. 

What about the issue which caused the need to error print - why the engine is trying to communicate to the plugin before initializing plugin ?

**Comment by msterin** [comment]
Ah, never mind. Looks like the engine tries to complete initialization including all volume mounts for restart-able workloads, that call out plugin which tries to communicate right back to the Docker API while this API is not ready yet. We added this to make out code resilient to  our own crashes and it does not seem to be compatible with the engine init sequence.

**Comment by anusha-ragunathan** [comment]
Volumes are restored *after* plugins are restored. During daemon initialization (NewDaemon), `plugin.NewManager` is called before `configureVolumes`

1. Restore plugins
NewDaemon -> NewManager -> reload -> restorePlugin.

2. Restore volumes
NewDaemon -> configureVolumes -> store.New -> restore

So, if the plugin is started successfully, then volumes that the plugin created should be restored fine. If the plugin doesnt start, then engine has an exponential backoff (1,2,4,8 seconds) and gives up restoring the volume. It should *not* hang forever. Also, I dont observe the hung behavior in the logs.

The daemon panic was with a log message and its being fixed.

**Comment by msterin** [comment]
@anusha-ragunathan - is Docker client API supposed to be fully functional during `1. Restore plugins NewDaemon -> NewManager -> reload -> restorePlugin.` phase ? We do try to get volumes info from Docker at this point.  This is what we see hanging - which is why we don't reply to plugin engine pinging us for volume info on phase 2.

**Comment by anusha-ragunathan** [comment]
@msterin : Docker engine API is fully functional only *after* the initialization is complete. Restore is in the middle of the initialization.

**Comment by msterin** [comment]
@anusha-ragunathan and how do I know if the init is complete , from within the plugin code ? 
I mean, I can hit the API and manage my own timeout... is there a better way ? Thanks !

**Comment by anusha-ragunathan** [comment]
plugin API is meant to manage the plugin lifecycle, not the docker engine lifecycle. In order to determine if the engine has initialized, you should query `systemd` or `upstart` or whatever system init management software is being used to manage docker service.

**Comment by msterin** [comment]
I am not querying plugin API. I am querying docker client API (github.com/docker/docker/tree/master/client). At any rate, I got it (`Docker engine API is fully functional only after the initialization is complete. Restore is in the middle of the initialization.`). Thanks

.

**Comment by anusha-ragunathan** [comment]
`plugin API is meant to manage the plugin lifecycle` was a response to your question on `how do I know if the init is complete from within the plugin code`

**Comment by thaJeztah** [comment]
@anusha-ragunathan os this one fixed by https://github.com/docker/docker/issues/32098 ?

**Comment by anusha-ragunathan** [comment]
@thaJeztah : Yes, the daemon panic should indeed by fixed
