### ISSUE TITLE
Docker Toolbox for Windows (cygwin) proposals

### ISSUE THREAD

**Issue by Alf666** [docker/docker#31929]
I hope it's the right place to report such issues.

I have two changes to offer to the start.sh script to make it compliant with cygwin :

First after the big text block. Under Windows, the launching shortcut places the working directory in the "Docker Toolbox" dir. But if it's called from a cygwin shell, this does not apply.
So I suggest adding :
cd "$(dirname "${BASH_SOURCE[0]}")"

Second, to make it start fine with cygwin, all that is needed is to add the following three lines after the block which defines the VBOXMANAGE path (STEP="Looking for vboxmanage.exe") :

if [ -n ${CYGWIN_PATH} ]; then
    VBOXMANAGE=`echo ${VBOXMANAGE}|sed 's/\\\/\//g'`
fi

In the end, the only problem that remains is to install and use winpty. But it should be for another post. This one's only aim is to render start.sh compliant with cygwin.

**Comment by thaJeztah** [comment]
Thanks for suggesting, unfortunately it's not the right location; can you open this in the Docker Toolbox issue tracker instead? https://github.com/docker/toolbox/issues

Thanks!

**Comment by Alf666** [comment]
As I mentioned : "I hope it's the right place to report such issues." So thanks and Sorry.

**Comment by thaJeztah** [comment]
No worries, no harm done! :+1:
