### ISSUE TITLE
Daemon outputs only to stderr

### ISSUE THREAD

**Issue by darrenstahlmsft** [docker/docker#31927]
**Description**

All output from the Docker Daemon is on stderr. It's been like this for a long time, so this issue is more of a discussion if this is the correct behaviour than an issue. This is a slight inconvenience on Windows when attempting to redirect the daemon output to a file.

Is there a particular reason that it is output to stderr rather than stdout?

**Steps to reproduce the issue:**
1. `dockerd > stdout 2> stderr`

**Describe the results you received:**

```
$ sudo dockerd > stdout 2> stderr
$ cat stdout
$ cat stderr
time="2017-03-17T13:43:55.374185400-07:00" level=info msg="libcontainerd: new containerd process, pid: 26105"
time="2017-03-17T13:43:55.401719265-07:00" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=65536
time="2017-03-17T13:43:56.376746015-07:00" level=info msg="[graphdriver] using prior storage driver: aufs"
time="2017-03-17T13:43:56.422300241-07:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
time="2017-03-17T13:43:56.422457803-07:00" level=warning msg="Your kernel does not support swap memory limit"
time="2017-03-17T13:43:56.422489715-07:00" level=warning msg="Your kernel does not support cgroup rt period"
time="2017-03-17T13:43:56.422497518-07:00" level=warning msg="Your kernel does not support cgroup rt runtime"
time="2017-03-17T13:43:56.422766023-07:00" level=info msg="Loading containers: start."
time="2017-03-17T13:43:56.428612998-07:00" level=info msg="Firewalld running: false"
time="2017-03-17T13:43:56.544798310-07:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
time="2017-03-17T13:43:56.586924702-07:00" level=info msg="Loading containers: done."
time="2017-03-17T13:43:56.649531465-07:00" level=info msg="Daemon has completed initialization"
time="2017-03-17T13:43:56.649591888-07:00" level=info msg="Docker daemon" commit=60ccb22 graphdriver=aufs version=17.03.0-ce
time="2017-03-17T13:43:56.655241887-07:00" level=info msg="API listen on /var/run/docker.sock"
time="2017-03-17T13:45:47.757254970-07:00" level=info msg="Processing signal 'interrupt'"
time="2017-03-17T13:45:47.769260692-07:00" level=info msg="stopping containerd after receiving terminated"
```

**Describe the results you expected:**

I'd expect that it not all be output to stderr. Either both stdout and stderr, or just stdout, but it seems odd to put info logs on stderr.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

/cc @jhowardmsft

**Comment by fntlnz** [comment]
Tried to understand what happened:
Here's the incriminated part: https://github.com/docker/docker/blob/c1b04a8d6ed90d4dad4162432a111dcd3a9b5a0b/cmd/docker/docker.go#L163

Looking at that seems that the stderr has been introduced when daemon and client binaries have been splitted like one year ago, in fact, before https://github.com/docker/docker/commit/9b00817dc692458f9e27e375a870ecd0dcbd0b75 the stderr thing was not there.

Also, logrus documentation had `os.Stderr` in their examples in the same period: https://github.com/docker/docker/blob/9b00817dc692458f9e27e375a870ecd0dcbd0b75/vendor/src/github.com/Sirupsen/logrus/README.md#example


So the possibilities are:
- Something went wrong one year ago and docker is logging in stderr
- docker is logging to stderr for a reason (maybe @thaJeztah know that reason)

**Comment by fntlnz** [comment]
Investigated more, actually this commit introduced the use of stderr as output for logging https://github.com/docker/docker/commit/d8c3090dd9abe3f0d95f99c9d8c7660922e9a719

**Comment by fntlnz** [comment]
More findings related to this:
https://github.com/docker/docker/blob/master/contrib/init/sysvinit-debian/docker#L115
https://github.com/docker/docker/blob/master/contrib/init/sysvinit-redhat/docker#L59

**Comment by thaJeztah** [comment]
Looks to be part of https://github.com/docker/docker/pull/10864 (also see https://github.com/docker/docker/pull/10864#issuecomment-77093419, not sure if it's relevant), which was carried in https://github.com/docker/docker/pull/11566

ping @tiborvass ptal
