### ISSUE TITLE
When using multiple volumes only one is exposed in df command

### ISSUE THREAD

**Issue by itzikb-redhat** [docker/docker#31936]
**Description**

When running the following command
$ sudo docker run --rm  -it -v /tmp/tmp1:/data1 -v /tmp/tmp2:/data2  --name img1 myimg /bin/bash
And running df -h
Only one of the volumes is exposed

root@7f8edeaa41f9:/# df -h
Filesystem                                                                                         Size  Used Avail Use% Mounted on
/dev/mapper/docker-253:1-1196036-c2be1fb09ae48d642a774fe103ea30b80b7a54aef74d63f724dccd149e1b578a   10G  157M  9.9G   2% /
tmpfs                                                                                              5.8G     0  5.8G   0% /dev
tmpfs                                                                                              5.8G     0  5.8G   0% /sys/fs/cgroup
tmpfs                                                                                              5.8G  116K  5.8G   1% /data1
/dev/mapper/luks-c7479a17-480d-4504-a6d8-be5666f87494                                               30G   24G  4.4G  85% /etc/hosts
shm                                                                                                 64M     0   64M   0% /dev/shm

When running mount of ls -l / the directories are there

**Steps to reproduce the issue:**
Showed on the description

**Output of `docker version`:**
Docker version 1.10.3, build e03ddb8/1.10.3

**Output of `docker info`:**
ontainers: 17
 Running: 0
 Paused: 0
 Stopped: 17
Images: 49
Server Version: 1.10.3
Storage Driver: devicemapper
 Pool Name: docker-253:1-1196036-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 4.834 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.346 GB
 Metadata Space Used: 8.106 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.109 (2015-09-22)
Execution Driver: native-0.2
Logging Driver: journald
Plugins: 
 Volume: local
 Network: bridge null host
Kernel Version: 4.8.13-100.fc23.x86_64
Operating System: Fedora 23 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 0
CPUs: 4
Total Memory: 11.43 GiB
Name: ---
ID: ---
Username: ---
Registry: https://index.docker.io/v1/
Registries: docker.io (secure)

**Comment by gianarb** [comment]
Hello thanks for your report.

I am trying to reproduce your issue:
```
10:46 $ docker run --rm -it -v /tmp/tmp1:/data1 -v /tmp/tmp2:/data2 --name img1 alpine /bin/sh
/ # df -h
Filesystem                Size      Used Available Use% Mounted on
none                     45.6G      5.8G     37.4G  13% /
tmpfs                     7.8G         0      7.8G   0% /dev
tmpfs                     7.8G         0      7.8G   0% /sys/fs/cgroup
/dev/nvme0n1p4           72.8G      7.8G     61.3G  11% /data2
/dev/nvme0n1p4           72.8G      7.8G     61.3G  11% /data1
/dev/nvme0n1p3           45.6G      5.8G     37.4G  13% /etc/resolv.conf
/dev/nvme0n1p3           45.6G      5.8G     37.4G  13% /etc/hostname
/dev/nvme0n1p3           45.6G      5.8G     37.4G  13% /etc/hosts
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                     7.8G         0      7.8G   0% /proc/kcore
tmpfs                     7.8G         0      7.8G   0% /proc/timer_list
tmpfs                     7.8G         0      7.8G   0% /proc/timer_stats
tmpfs                     7.8G         0      7.8G   0% /proc/sched_debug
tmpfs                     7.8G         0      7.8G   0% /sys/firmware
```
It's working fine but I am using:
```
Server Version: 17.03.0-ce-rc1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
```
Do you have the same problem with an `alpine` image? Can you try with the latest versin of Docker?
Thanks

**Comment by itzikb-redhat** [comment]
@gianarb With alpine latest it works

**Comment by cpuguy83** [comment]
So we can close?
Sounds like it's dependent on the userspace tooling in the image.

**Comment by itzikb-redhat** [comment]
@cpuguy83 I guess yes.
