### ISSUE TITLE
Can not pull image

### ISSUE THREAD

**Issue by huangyanxiong01** [docker/docker#31938]
**Description**
when run `sudo docker search mongo` output result.But docker can not pull image
```
NAME                           DESCRIPTION                                     STARS     OFFICIAL   AUTOMATED
mongo                          MongoDB document databases provide high av...   3060      [OK]       
mongo-express                  Web-based MongoDB admin interface, written...   129       [OK]       
```

**Steps to reproduce the issue:**
1.sudo docker search mongo
2.sudo docker pull mongo:3.0
3.

**Describe the results you received:**
```shell
FATA[0003] Get https://registry-1.docker.io/v1/repositories/library/mongo/tags: dial tcp 50.17.62.194:443: connection refused
```

**Describe the results you expected:**
pulled mongodb image

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-100-generic
Operating System: Ubuntu 14.04.5 LTS
CPUs: 4
Total Memory: 7.548 GiB
Name: 10-19-91-150
ID: 2SHZ:R5UW:3MMO:CJNY:A4DP:SI7F:3CI6:6XMG:CWN6:CFPT:TKFF:5RBV
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

**Comment by thaJeztah** [comment]
I am not able to reproduce this (tried on both the current, 17.03 version, and docker 1.6.2); I see you're located in China; I suspect the GFW may be blocking requests 😞, and not sure much we can do about that.

**Comment by huangyanxiong01** [comment]
It may be because of GFW reasons, but the use of `tcping` test network is no problem
```
tcping 50.17.62.194 443 

//result
50.17.62.194 port 443 open
```

**Comment by thaJeztah** [comment]
Hm, it's odd, I just noticed in your output that it's trying to pull from the V1 registry endpoint;

    https://registry-1.docker.io/v1/repositories/library/mongo/tags

And V1 registry was shut down in 2015 https://blog.docker.com/2015/10/docker-hub-deprecation-1-5/

Can you try updating to a current version of docker, and see if you still have the same issue?

**Comment by huangyanxiong01** [comment]
Thank you!
I'll try it!
