### ISSUE TITLE
Docker unusable if container's storage becomes full

### ISSUE THREAD

**Issue by Telokis** [docker/docker#31931]
**Description**
I am trying to setup a filesystem size limit on my containers.
The users of my application will have a container dedicated to store their data and I don't want them to overflow my system.
To have a look at what happens once a container is full, I ran `yes > big_file`. I let it run for a while and once it got about 10G in size, I tried to duplicate it using `cp`.
The command crashed and I wasn't even able to use `ls`. I tried removing `big_file` but `rm` kept telling me `rm: cannot remove 'big_file': Input/output error`.
So I closed the container and tried to remove it but I got an error once again.
`docker Error response from daemon: Driver devicemapper failed to remove root filesystem f14bbbda3aa4a91f6d9ea10537731e4edab249ab63011513cbd9e02d08c28438: devicemapper: Error running DeleteDevice dm_task_run failed`
At this point, I didn't know what to do so, after browsing the web, I completely removed the `devicemapper` directory.
Alright, the issue is fixed but that behavior is not useful at all. Setting a filesystem limit which breaks everything if it is reached is as bad as no limit at all.

**Steps to reproduce the issue:**
1. `docker run -it --storage-opt size=11G debian /bin/bash`
2. `yes > big_file` until the file is around 8G
3. `cp big_file big_file2`

**Describe the results you received:**

**Describe the results you expected:**
I expected an error like `unable to write` so that I would have had to remove `big_file` and everything would have been fine again.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:52:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:52:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-914044-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 161 MB
 Data Space Total: 107.4 GB
 Data Space Available: 14.16 GB
 Metadata Space Used: 643.1 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.59 GiB
Name: ns388934.ip-176-31-100.eu
ID: 63DC:SOQW:AGBN:HEQ4:47CR:E6BB:KL5W:SBQX:YLVY:GLT7:3VBI:6WA4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
ping @rhvgoyal @shishir-a412ed PTAL

**Comment by Telokis** [comment]
Alright, for a reason I have no idea about, the issue doesn't happen anymore...
Now I get a proper `No space left on device` when trying to copy the files.
Sorry for the inconvenience.
