### ISSUE TITLE
docker pull failing with x509: unhandled critical extension

### ISSUE THREAD

**Issue by aanc** [docker/docker#31949]
**Description**

TLS/x509 error when pulling images : `tls: failed to parse certificate from server: x509: unhandled critical extension`
When doing a `docker pull ubuntu` (or any other image), I get the following error message :

**Steps to reproduce the issue:**
1. `docker pull ubuntu`

**Describe the results you received:**

```
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/0e/0ef2e08ed3fabfc44002ccb846c4f2416a2135affc3ce39538834059606f32dd/data?Expires=1490023704&Signature=JaS9is5nvWfJV8Wn8i1Sd454l~EMcRb7zUnXVCai~55Rem7073rs-txD7JKCRtxbEP3l~p~AcO41wVr5gwXAPhQMNinuSSTBB-f1Kc5~2Jcv0p-7jNqASfmPsCg0lkBVwWAwunx5UxYxz7gy8N11bLerXiWpoDw~3olcfWonFRU_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: tls: failed to parse certificate from server: x509: unhandled critical extension
```

**Describe the results you expected:**

all layers successfully pulled

**Additional information you deem important (e.g. issue happens only occasionally):**

- "Hardened" version of RHEL 7 (OS image provided by security team and provisioned automatically)
- Behind HTTPS proxy w/ authentication

`/etc/systemd/system/docker.service.d/proxy.conf` :

```
[Service]
Environment="HTTP_PROXY=https://username:password@proxy.eu.company.corp:3128/" "NO_PROXY=*.company.corp,localhost,127.0.0.1"

```

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:10:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.10.1.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.3 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.51 GiB
Name: serverid.cloud.company.corp
ID: U673:DPJ3:K5DB:RJWB:LZYT:JW3G:IED5:B3CO:3CV6:TKMC:TWIN:AAJZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 21
 System Time: 2017-03-20T16:14:48.110943522+01:00
 EventsListeners: 0
Http Proxy: https://user:password@proxy.company.corp:3128/
No Proxy: *.company.corp,localhost,127.0.0.1
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

VM

I tried to add `dseasb33srnrn.cloudfront.net` certificate by downloading it and adding it to `/etc/pki/ca-trust/source/anchors/` and running `update-ca-trust extract`
I also tried the same with certificates from https://curl.haxx.se/docs/caextract.html

Thanks in advance for your help

**Comment by thaJeztah** [comment]
ping @cyli @dmcgowan PTAL

**Comment by aanc** [comment]
Additional information that may be useful : 

- The proxy is breaking the TLS stream. I tried adding the proxy's certificate, but it did not fix the issue
- I am able to download a layer with an internet browser using the same proxy

I don't know what to try next, thanks in advance for your help

**Comment by dmcgowan** [comment]
This error would be indicative of an error throw by the Go lang parser. Having a look at the code my guess is it was throw by this section https://golang.org/src/crypto/x509/x509.go#L1165.  Might be worth checking the certificate to see if you have this https://tools.ietf.org/html/rfc5280#section-4.2.1.10 which would cause Go to fail to parse (any excluded subtree or included subtree with no name).

**Comment by aanc** [comment]
The issue seems resolved now, as servers can now pull images correctly. I don't know exactly how it got resolved though.
Docker config stayed exactly the same, so I think docker was not responsible of the issue.
I'll update this issue if I find the root cause.

Issue can be closed, sorry for the inconvenience.

**Comment by thaJeztah** [comment]
Thanks for reporting back @aanc, I'll go ahead and close then; happy it's resolved 👍
