### ISSUE TITLE
Toolbox giving VirtualBox error

### ISSUE THREAD

**Issue by vaibhavswarnkar** [docker/docker#31959]
I'm trying to install and run docker on my Windows 10 Home machine with docker toolbox but during setup I'm getting below error:

`2bb0.7f0: Log file opened: 5.1.18r114002 g_hStartupLog=0000000000000074 g_uNtVerCombined=0xa0383900
2bb0.7f0: \SystemRoot\System32\ntdll.dll:
2bb0.7f0:     CreationTime:    2016-12-11T11:56:28.913448800Z
2bb0.7f0:     LastWriteTime:   2016-11-11T10:13:03.409595100Z
2bb0.7f0:     ChangeTime:      2017-03-16T15:05:30.849791800Z
2bb0.7f0:     FileAttributes:  0x20
2bb0.7f0:     Size:            0x1cc888
2bb0.7f0:     NT Headers:      0xd8
2bb0.7f0:     Timestamp:       0x5825887f
2bb0.7f0:     Machine:         0x8664 - amd64
2bb0.7f0:     Timestamp:       0x5825887f
2bb0.7f0:     Image Version:   10.0
2bb0.7f0:     SizeOfImage:     0x1d1000 (1904640)
2bb0.7f0:     Resource Dir:    0x168000 LB 0x67988
2bb0.7f0:     ProductName:     Microsoft® Windows® Operating System
2bb0.7f0:     ProductVersion:  10.0.14393.479
2bb0.7f0:     FileVersion:     10.0.14393.479 (rs1_release.161110-2025)
2bb0.7f0:     FileDescription: NT Layer DLL
2bb0.7f0: \SystemRoot\System32\kernel32.dll:
2bb0.7f0:     CreationTime:    2016-07-16T11:42:16.155721400Z
2bb0.7f0:     LastWriteTime:   2016-07-16T11:42:16.155721400Z
2bb0.7f0:     ChangeTime:      2016-10-09T01:41:35.006489900Z
2bb0.7f0:     FileAttributes:  0x20
2bb0.7f0:     Size:            0xaade8
2bb0.7f0:     NT Headers:      0xf0
2bb0.7f0:     Timestamp:       0x57899a29
2bb0.7f0:     Machine:         0x8664 - amd64
2bb0.7f0:     Timestamp:       0x57899a29
2bb0.7f0:     Image Version:   10.0
2bb0.7f0:     SizeOfImage:     0xab000 (700416)
2bb0.7f0:     Resource Dir:    0xa9000 LB 0x528
2bb0.7f0:     ProductName:     Microsoft® Windows® Operating System
2bb0.7f0:     ProductVersion:  10.0.14393.0
2bb0.7f0:     FileVersion:     10.0.14393.0 (rs1_release.160715-1616)
2bb0.7f0:     FileDescription: Windows NT BASE API Client DLL
2bb0.7f0: \SystemRoot\System32\KernelBase.dll:
2bb0.7f0:     CreationTime:    2017-03-15T17:02:14.001286700Z
2bb0.7f0:     LastWriteTime:   2017-03-04T07:22:41.598640500Z
2bb0.7f0:     ChangeTime:      2017-03-16T16:12:17.859517200Z
2bb0.7f0:     FileAttributes:  0x20
2bb0.7f0:     Size:            0x21c780
2bb0.7f0:     NT Headers:      0xf8
2bb0.7f0:     Timestamp:       0x58ba59e1
2bb0.7f0:     Machine:         0x8664 - amd64
2bb0.7f0:     Timestamp:       0x58ba59e1
2bb0.7f0:     Image Version:   10.0
2bb0.7f0:     SizeOfImage:     0x21d000 (2215936)
2bb0.7f0:     Resource Dir:    0x201000 LB 0x560
2bb0.7f0:     ProductName:     Microsoft® Windows® Operating System
2bb0.7f0:     ProductVersion:  10.0.14393.953
2bb0.7f0:     FileVersion:     10.0.14393.953 (rs1_release_inmarket.170303-1614)
2bb0.7f0:     FileDescription: Windows NT BASE API Client DLL
2bb0.7f0: \SystemRoot\System32\apisetschema.dll:
2bb0.7f0:     CreationTime:    2016-07-16T11:42:21.577586000Z
2bb0.7f0:     LastWriteTime:   2016-07-16T11:42:21.577586000Z
2bb0.7f0:     ChangeTime:      2016-10-09T01:41:24.754889400Z
2bb0.7f0:     FileAttributes:  0x20
2bb0.7f0:     Size:            0x18960
2bb0.7f0:     NT Headers:      0xc8
2bb0.7f0:     Timestamp:       0x57899bd2
2bb0.7f0:     Machine:         0x8664 - amd64
2bb0.7f0:     Timestamp:       0x57899bd2
2bb0.7f0:     Image Version:   10.0
2bb0.7f0:     SizeOfImage:     0x19000 (102400)
2bb0.7f0:     Resource Dir:    0x18000 LB 0x400
2bb0.7f0:     ProductName:     Microsoft® Windows® Operating System
2bb0.7f0:     ProductVersion:  10.0.14393.0
2bb0.7f0:     FileVersion:     10.0.14393.0 (rs1_release.160715-1616)
2bb0.7f0:     FileDescription: ApiSet Schema DLL
2bb0.7f0: NtOpenDirectoryObject failed on \Driver: 0xc0000022
2bb0.7f0: supR3HardenedWinFindAdversaries: 0x0
2bb0.7f0: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox'
2bb0.7f0: Calling main()
2bb0.7f0: SUPR3HardenedMain: pszProgName=VBoxHeadless fFlags=0x0
2bb0.7f0: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox'
2bb0.7f0: SUPR3HardenedMain: Respawn #1
2bb0.7f0: System32:  \Device\HarddiskVolume3\Windows\System32
2bb0.7f0: WinSxS:    \Device\HarddiskVolume3\Windows\WinSxS
2bb0.7f0: KnownDllPath: C:\WINDOWS\System32
2bb0.7f0: '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
2bb0.7f0: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe)
2bb0.7f0: supR3HardNtEnableThreadCreation:
2bb0.7f0: supR3HardNtDisableThreadCreation: pvLdrInitThunk=00007ffb22139fa0 pvNtTerminateThread=00007ffb22166b20
2bb0.7f0: supR3HardenedWinDoReSpawn(1): New child 31b8.31b4 [kernel32].
2bb0.7f0: supR3HardNtChildGatherData: PebBaseAddress=0000000000446000 cbPeb=0x388
2bb0.7f0: supR3HardNtPuChFindNtdll: uNtDllParentAddr=00007ffb220c0000 uNtDllChildAddr=00007ffb220c0000
2bb0.7f0: supR3HardenedWinSetupChildInit: uLdrInitThunk=00007ffb22139fa0
2bb0.7f0: supR3HardenedWinSetupChildInit: Start child.
2bb0.7f0: supR3HardNtChildWaitFor: Found expected request 0 (PurifyChildAndCloseHandles) after 0 ms.
2bb0.7f0: supR3HardNtChildPurify: Startup delay kludge #1/0: 265 ms, 31 sleeps
2bb0.7f0: supHardNtVpScanVirtualMemory: enmKind=CHILD_PURIFICATION
2bb0.7f0:  *0000000000000000-ffffffffffd5ffff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00000000002a0000-000000000027ffff 0x0004/0x0004 0x0020000
2bb0.7f0:  *00000000002c0000-00000000002a9fff 0x0002/0x0002 0x0040000
2bb0.7f0:   00000000002d6000-00000000002cbfff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00000000002e0000-00000000001e4fff 0x0000/0x0004 0x0020000
2bb0.7f0:   00000000003db000-00000000003d7fff 0x0104/0x0004 0x0020000
2bb0.7f0:   00000000003de000-00000000003dbfff 0x0004/0x0004 0x0020000
2bb0.7f0:  *00000000003e0000-00000000003dbfff 0x0002/0x0002 0x0040000
2bb0.7f0:   00000000003e4000-00000000003d7fff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00000000003f0000-00000000003edfff 0x0004/0x0004 0x0020000
2bb0.7f0:   00000000003f2000-00000000003e3fff 0x0001/0x0000 0x0000000
2bb0.7f0:  *0000000000400000-00000000003b9fff 0x0000/0x0004 0x0020000
2bb0.7f0:   0000000000446000-0000000000442fff 0x0004/0x0004 0x0020000
2bb0.7f0:   0000000000449000-0000000000291fff 0x0000/0x0004 0x0020000
2bb0.7f0:   0000000000600000-ffffffff80c1ffff 0x0001/0x0000 0x0000000
2bb0.7f0:  *000000007ffe0000-000000007ffdefff 0x0002/0x0002 0x0020000
2bb0.7f0:   000000007ffe1000-000000007ffd1fff 0x0000/0x0002 0x0020000
2bb0.7f0:   000000007fff0000-ffff800acc4dffff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00007ff633b00000-00007ff633adcfff 0x0002/0x0002 0x0040000
2bb0.7f0:   00007ff633b23000-00007ff633885fff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00007ff633dc0000-00007ff633dc0fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633dc1000-00007ff633e2ffff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e30000-00007ff633e30fff 0x0080/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e31000-00007ff633e75fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e76000-00007ff633e76fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e77000-00007ff633e77fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e78000-00007ff633e7cfff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e7d000-00007ff633e7dfff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e7e000-00007ff633e7efff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e7f000-00007ff633e82fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633e83000-00007ff633ecafff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0:   00007ff633ecb000-00007ff145cd5fff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00007ffb220c0000-00007ffb220c0fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb220c1000-00007ffb221c7fff 0x0020/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb221c8000-00007ffb2220bfff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb2220c000-00007ffb22214fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb22215000-00007ffb22222fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb22223000-00007ffb22223fff 0x0004/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb22224000-00007ffb22226fff 0x0008/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb22227000-00007ffb22290fff 0x0002/0x0080 0x1000000  \Device\HarddiskVolume3\Windows\System32\ntdll.dll
2bb0.7f0:   00007ffb22291000-00007ff644541fff 0x0001/0x0000 0x0000000
2bb0.7f0:  *00007ffffffe0000-00007ffffffcffff 0x0001/0x0002 0x0020000
2bb0.7f0: VBoxHeadless.exe: timestamp 0x58c95b23 (rc=VINF_SUCCESS)
2bb0.7f0: '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
2bb0.7f0: '\Device\HarddiskVolume3\Windows\System32\ntdll.dll' has no imports
2bb0.7f0: supR3HardNtChildPurify: Done after 311 ms and 0 fixes (loop #0).
2bb0.7f0: supR3HardNtEnableThreadCreation:
31b8.31b4: Log file opened: 5.1.18r114002 g_hStartupLog=0000000000000008 g_uNtVerCombined=0xa0383900
31b8.31b4: supR3HardenedVmProcessInit: uNtDllAddr=00007ffb220c0000 g_uNtVerCombined=0xa0383900
31b8.31b4: ntdll.dll: timestamp 0x5825887f (rc=VINF_SUCCESS)
31b8.31b4: New simple heap: #1 0000000000700000 LB 0x400000 (for 1904640 allocation)
31b8.31b4: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume3\Program Files\Oracle\VirtualBox'
31b8.31b4: System32:  \Device\HarddiskVolume3\Windows\System32
31b8.31b4: WinSxS:    \Device\HarddiskVolume3\Windows\WinSxS
31b8.31b4: KnownDllPath: C:\WINDOWS\System32
31b8.31b4: supR3HardenedVmProcessInit: Opening vboxdrv stub...
31b8.31b4: supR3HardenedWinReadErrorInfoDevice: 'Not signed with the build certificate.: \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe'
31b8.31b4: Error -5657 in supR3HardenedWinReSpawn! (enmWhat=3)
31b8.31b4: NtCreateFile(\Device\VBoxDrvStub) failed: Unknown Status -5657 (0xffffe9e7) (rcNt=0xe986e9e7)
VBoxDrvStub error: Not signed with the build certificate.: \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0: supR3HardenedWinCheckChild: enmRequest=2 rc=-5657 enmWhat=3 supR3HardenedWinReSpawn: NtCreateFile(\Device\VBoxDrvStub) failed: Unknown Status -5657 (0xffffe9e7) (rcNt=0xe986e9e7)
VBoxDrvStub error: Not signed with the build certificate.: \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
2bb0.7f0: Error -5657 in supR3HardenedWinReSpawn! (enmWhat=3)
2bb0.7f0: NtCreateFile(\Device\VBoxDrvStub) failed: Unknown Status -5657 (0xffffe9e7) (rcNt=0xe986e9e7)
VBoxDrvStub error: Not signed with the build certificate.: \Device\HarddiskVolume3\Program Files\Oracle\VirtualBox\VBoxHeadless.exe
`

I've been struggling with this and can't figure out the solution. How to resolve this?

**Comment by AkihiroSuda** [comment]
https://www.virtualbox.org/ticket/16318 seems related to this issue.


I suggest closing this issue, because the issue does not seem to related to Docker

**Comment by AkihiroSuda** [comment]
Let me close this issue, as commented above
