### ISSUE TITLE
FROM with private image doesn't work

### ISSUE THREAD

**Issue by nkovacs** [docker/docker#31950]
**Description**

FROM fails with access forbidden when using a private image on gitlab.com. docker pull works.

**Steps to reproduce the issue:**
1. Create a private project on gitlab.com
2. `docker login registry.gitlab.com`
3. Build and push an image into their docker registry
4. Delete the local image you built
5. Create a Dockerfile with `FROM <the private image you pushed>`
6. Try to build the second image

**Describe the results you received:**
Sending build context to Docker daemon 2.048 kB
Step 1/1 : FROM registry.gitlab.com/nkovacs/private-image-test
Get https://registry.gitlab.com/v2/nkovacs/private-image-test/manifests/latest: denied: access forbidden

**Describe the results you expected:**
The build should succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**
`docker pull registry.gitlab.com/nkovacs/private-image-test` works, and then I can build the image.
Docker 1.12.6 also works.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:05:01 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 08:05:01 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 1
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-41-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.63 GiB
Name: bela
ID: 4GRW:YQKG:GIOT:2C26:ACNI:RNWR:V4R6:DHZ3:3X3Q:F24C:D23B:ASWO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 14
 Goroutines: 21
 System Time: 2017-03-20T17:18:20.741212224+01:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
I am not able to reproduce this against Docker Hub. Are you using a credentials-helper, for authentication?

Would it be possible to put the daemon in debug mode, and check if the logs contain anything useful?
You can put the daemon in debug mode by creating a file named `/etc/docker/daemon.json` on the host that the daemon runs on. In that file;

```json
{debug:true}
```

Then you can `systemctl reload docker` to put the daemon in debug mode.

**Comment by nkovacs** [comment]
Yes, I forgot to mention that I'm using secretservice. I can't reproduce it without a credentials helper.
I'll try the debug output.

**Comment by nkovacs** [comment]
I was using docker-credential-secretservice 0.3.0, but upgrading to 0.5.0 fixes it.
Thanks.

**Comment by thaJeztah** [comment]
Cool, good to hear!
