### ISSUE TITLE
Docker host is not forwarding UDP packets selectively.

### ISSUE THREAD

**Issue by davidcsi** [docker/docker#31963]
Docker host is not forwarding UDP packets selectively.
We have a homer-docker running, and we have 4 boxes sending udp packets to 1 of 2 containers inside. Packet from 2 boxes arrive properly, but the other 2 are not forwarded. We see the packets arriving at the host interface, but not being forwarded to the container.

I've read it might be related to conntrack, and i've flushed the tables to no avail.With conntrack -E (show events) I see the 2 working boxes' packets coming in, but it doesn't show the other 2.

I've checked iptables, no funny stuff going on there.

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**
Packets from 2 specific boxes are not being forwarded.

**Describe the results you expected:**
all udp packets should be forwarded.

**Additional information you deem important (e.g. issue happens only occasionally):**
conntrack -F or both docker and host reboot doesn't help.

**Output of `docker version`:**

```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:38:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 11
 Running: 2
 Paused: 0
 Stopped: 9
Images: 2
Server Version: 1.13.1
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.797 GiB
Name: qap-arch-homerapp1
ID: VVDV:JKZ4:JCMA:HBO4:X73R:XMLG:A5NW:LP4T:P6UT:TIZ4:ABW3:2TN5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
both host and docker are:
CentOS Linux release 7.3.1611 (Core)

**Comment by thaJeztah** [comment]
Are you able to provide basic steps to reproduce?

**Comment by davidcsi** [comment]
This seems to have been related to an iptables entry marked as "NOTRACK" in an intent to workaround the known conntrack issue.
We can close this for the moment.
Thanks for your help.
