### ISSUE TITLE
Add support for Selinux labels and AppArmor profiles to swarm mode.

### ISSUE THREAD

**Issue by abdshah94** [docker/docker#31965]
Proposal
Add --security-opt  as a parameter to docker service create for Selinux and AppArmor.

Background
As in docker run, docker service create should also have some parameter like --security-opt for Selinux and AppArmor security modules. So that containers' resource access can be confined.

**Comment by thaJeztah** [comment]
Thanks for suggesting, but it looks like this is a duplicate of https://github.com/docker/docker/issues/25209 (I see you're already participating in that discussion). I'll close this one to prevent the discussion from diverging, but feel free to comment after I closed
