### ISSUE TITLE
Configure namespaced kernel parameters use docker service 

### ISSUE THREAD

**Issue by zhangxuelai** [docker/docker#31961]
**Description**

We can configure namespaced kernel parameters while using docker run,for example:
```
docker run --sysctl kernel.msgmax=12345 someimage
```
is there any way to modify kernel parameters when using docker service create ?

**Output of `docker version`:**

```
Docker version 1.13.0, build 49bf474
```

**Output of `docker info`:**

```
Containers: 6
 Running: 3
 Paused: 0
 Stopped: 3
Images: 10
Server Version: 1.13.0
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local local-persist
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 7wnwxhcm35b2l5neeg8gq3hnd
 Is Manager: false
 Node Address: 172.16.2.138
 Manager Addresses:
  172.16.2.136:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.6.1.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.514 GiB
Name: node-172162138
ID: WEM6:UIPX:ABJW:W7UY:RCLW:HUZD:CHVE:KARL:5FCX:TSWA:KCZS:AWJO
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 id=172162138
Experimental: false
Insecure Registries:
 registry.hello.com:5000
 127.0.0.0/8
Registry Mirrors:
 http://registry.hello.com:5555
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

physical

**Comment by thaJeztah** [comment]
No, this is currently not yet supported; see this issue https://github.com/docker/docker/issues/25303, where we track options that are available for `docker run` but not (yet?) available for `docker service`.

We're already tracking / discussing this functionality in https://github.com/docker/docker/issues/25209, so let me close this issue to prevent the discussion from diverging, but thanks for opening. You can stay informed on updates using the "subscribe" button  on that issue.

Closing this one, but feel free to comment after I closed
