### ISSUE TITLE
Docker EE AWS stuck at creating CloudFormation Stack, failing to receive resource signals.

### ISSUE THREAD

**Issue by adrrrrrrrian** [docker/docker#31979]
**Description**

**Steps to reproduce the issue:**
1. Apply for Docker EE (AWS) 30 days trial;
2. Click the link which directs you to AWS CloudFormation page, and use this template(https://s3.amazonaws.com/awsmp-fulfillment-cf-templates-prod/7bfd682c-ff64-45a8-90b6-c0c4f405d3a1.93b19484-7f00-4c3b-9240-837da4d4a44a.template) to create a stack;
3. The only thing I touched in the setting is the SSH key, DDC password and Docker EE License Number.

**Describe the results you received:**
It always stuck at creating auto scaling group for a very long time, and eventually will get this error message: **Failed to receive 3 resource signal(s) for the current batch.** And roll back.

**Describe the results you expected:**
I should be able to create the stack.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(NOT APPLICABLE IN THIS CASE)
```

**Output of `docker info`:**

```
(NOT APPLICABLE IN THIS CASE)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I am using Docker EE AWS version.

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by thaJeztah** [comment]
Thanks for reporting; can you reopen this in the Docker for AWS issue tracker? That way it can be looked at by the team working on Docker for AWS;
https://github.com/docker/for-aws/issues

I'll close the issue here but feel free to comment after I closed 👍
