### ISSUE TITLE
log-opts ignored in daemon.json

### ISSUE THREAD

**Issue by M-Pixel** [docker/docker#31975]
Every few days, my server's drive fills up to capacity with log files, despite having configured the following `daemon.json`.

```json
{
        "log-driver": "json-file",
        "log-opts": {
                "max-size": "1g",
                "max-file": "10"
        }
}
```

**Steps to reproduce the issue:**
1. Paste the above into `/etc/docker/daemon.json`
2. Run a container that spams out logs at a rapid pace. In my case, it's Resilio Sync, however it could be reproduced with something that forwards `/dev/random` to stdout.
3. Wait.

I would expect there to be at most 10 logs of 1GB each per container, but I end up with 100s of GBs of logs from a single container (found in `/var/lib/docker/[NAMESPACE]/containers/[CONTAINER ID]/[LOG NAME].json`).

Other settings in my `daemon.json` (`userns-remap`) are working properly, so I'm certain that this is not an issue of wrong `daemon.json` location or any other failure at that level.

**Output of `docker version`:**
```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**
```
Containers: 11
 Running: 7
 Paused: 0
 Stopped: 4
Images: 17
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/500000.500000/aufs
 Backing Filesystem: extfs
 Dirs: 228
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-67-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 7.702 GiB
Name: mandomantal
ID: NPVT:ZZ5A:G5NH:FHTT:ISCM:2KEB:SNE2:XRU3:M7MT:YCAE:W4TW:W2NN
Docker Root Dir: /var/lib/docker/500000.500000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Physical machine exclusively running Ubuntu Server 16.04.2 LTS.

**Comment by cpuguy83** [comment]
Testing on master and this seems to work ok.
Can you paste the inspect output from the container?
Was this container created before you set the log opts?

**Comment by trasch** [comment]
Same here, I have set these options globally in daemon.json. All containers have already been created before I have changed the logging options.

The relevant part from the container's inspect output:
```json
"LogConfig": {
    "Type": "json-file",
    "Config": {}
},
```

**Comment by cpuguy83** [comment]
@trasch Already created containers are not updated when the daemon default config changes.

**Comment by trasch** [comment]
@cpuguy83 Thanks for the clarification! (It is somewhat unexpected though... :) )

**Comment by cpuguy83** [comment]
@trasch I both agree and disagree. When it was being decided on I argued in favor of allowing to change the defaults of existing containers, but lost.

**Comment by M-Pixel** [comment]
Thank you! Spot on @cpuguy83 
After recreating the container, the `LogConfig.Config` of the `inspect` output changed from `{}` to `{ "max-file": "10", "max-size": "1g"}.

**Comment by colinmollenhour** [comment]
Just spent over an hour searching for this info, so I think it would be nice if it was documented..

**Comment by thaJeztah** [comment]
@colinmollenhour I agree it may be good to document; are you interested in opening a pull request? If it's for the CLI reference docs that should be in this repository. For the "logging drivers" section, probably in the https://github.com/docker/docker.github.io repository

**Comment by colinmollenhour** [comment]
Created PR #2714 with documentation updates.
