### ISSUE TITLE
Generate index pages for download.docker.com

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#31987]
The apt.dockerproject.org and yum.dockerproject.org repositories have index pages, allowing people to navigate the repositories, and easily find the RPM's / deb packages.

download.docker.com does not have index pages, which leads to a lot of confusion (e.g. https://github.com/docker/docker/issues/31940), because trying to browse the repository shows 403 access denied and an ugly XML error message.

It also makes it difficult to find out which packages are available, and which architectures are supported (also see https://github.com/docker/docker.github.io/issues/2085)

ping @andrewhsu @dmp42 PTAL

**Comment by andrewhsu** [comment]
Understood. I'll work towards getting those index up soon.

**Comment by andrewhsu** [comment]
Directories are now browsable for the linux repos for docker-ce: https://download.docker.com/linux/

**Comment by jasonnyan** [comment]
There is an error with the following index:

From instruction for package installation:
[https://docs.docker.com/engine/installation/linux/ubuntu/#install-from-a-package](https://docs.docker.com/engine/installation/linux/ubuntu/#install-from-a-package)

Click this link:
[https://download.docker.com/linux/ubuntu/pool/stable-17.03/amd64/](https://download.docker.com/linux/ubuntu/pool/stable-17.03/amd64/)

Error (as shown in iexplore):
404 Not Found
•Code: NoSuchKey
•Message: The specified key does not exist.
•Key: linux/ubuntu/pool/stable-17.03/amd64/index.html
•RequestId: EB24CFD173CEAD6B
•HostId: VdkPH8m6XMFPhYXJ2tRRQxVtnGPNLpsASSjvu3BlgRRRGjSGky4c+of5bMIFKZrgml44z4+7ar0=

An Error Occurred While Attempting to Retrieve a Custom Error Document
•Code: NoSuchKey
•Message: The specified key does not exist.
•Key: error.html

**Comment by thaJeztah** [comment]
Looks like that should be https://download.docker.com/linux/ubuntu/dists/xenial/pool/stable/amd64/ (for xenial)

**Comment by jasonnyan** [comment]
Agreed, then it looks like this issue can be closed & follow-up actions:
Update link @ https://docs.docker.com/engine/installation/linux/ubuntu/#install-from-a-package

**Comment by mstanleyjones** [comment]
Thanks @andrewhsu !
