### ISSUE TITLE
Deprecation notice mentions Docker 1.16

### ISSUE THREAD

**Issue by aaronlehmann** [docker/docker#31985]
I encountered this message in the log:

```
Command "daemon" is deprecated, and will be removed in Docker 1.16. Please run `dockerd` directly
```

I think this needs to be updated to refer to a different version number.

**Comment by thaJeztah** [comment]
Message is located here https://github.com/docker/docker/blob/b826bebda0cff2cc2d3083b954c810d2889eefe5/cmd/docker/daemon_unix.go#L27

I thought we had a PR for that, but I cannot find it 🤔

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker/pull/31988
