### ISSUE TITLE
MACVLAN - unable to communicate (ingress) with physical LAN

### ISSUE THREAD

**Issue by voobscout** [docker/docker#31995]
The setup in a few words - A container inside dual NIC coreos machine running on KVM host needing to have an 'external' Physical LAN IP inside 10.99.0.0/24.

**Steps to reproduce the issue:**

on docker host:

``` bash
docker network create \
       --driver macvlan \
       --subnet 10.99.0.0/24 \
       --gateway 10.99.0.1 \
       -o parent=eth1 \
       management
```

Continue to create and start a container:

``` bash
docker create -ti \
       --name macvlan-test \
       --cap-add NET_ADMIN \
       --cap-add NET_RAW \
       --cap-add NET_BROADCAST \
       --net default \
       debian /bin/bash -l

docker network connect --ip 10.99.0.100 management macvlan-test

docker start macvlan-test
```

**Describe the results you received:**

It is my understanding that at this point it should be possible to communicate with LAN directly from inside the container.
In this instance we try reaching a real machine on 10.99.0.220 (target), that is accessible from everywhere else:

``` bash
docker exec -ti macvlan-test ping 10.99.0.220

# PING 10.99.0.220 (10.99.0.220): 56 data bytes
# 92 bytes from 0e2f0da43c8a (10.99.0.100): Destination Host Unreachable
# 92 bytes from 0e2f0da43c8a (10.99.0.100): Destination Host Unreachable
```

Yet, while capturing traffic on 10.99.0.220 (target), it is clearly possible to see arp broadcasts and replies, which apparently never reach the container macvlan-test.

``` bash
tshark -i eth1

# 02:42:0a:63:00:fa -> Broadcast    ARP 42 Who has 10.99.0.220?  Tell 10.99.0.100
# 5a:00:00:5d:ad:c4 -> 02:42:0a:63:00:fa ARP 42 10.99.0.220 is at 5a:00:00:5d:ad:c4
```

It becomes even weirder - While we have that previous 'exec' session running, let's start another capture inside the container itself:

``` bash
docker exec -ti macvlan-test tshark -i eth1

# 02:42:0a:63:00:fa -> Broadcast    ARP 42 Who has 10.99.0.220?  Tell 10.99.0.100
# 02:42:0a:63:00:fa -> Broadcast    ARP 42 Who has 10.99.0.220?  Tell 10.99.0.100
```

So, the packets get out to LAN, but don't get back into container.

**Describe the results you expected:**

Inside the container I was sincerely hoping to see something like

``` bash
docker exec -ti macvlan-test ping 10.99.0.220

64 bytes from 10.99.0.220: icmp_seq=0 ttl=64 time=0.217 ms
64 bytes from 10.99.0.220: icmp_seq=1 ttl=64 time=0.094 ms
```

**Output of `docker version`:**

```
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Tue Mar 14 21:10:49 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   d5236f0
 Built:        Tue Mar 14 21:10:49 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 1.12.6
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: macvlan overlay null host bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp selinux
Kernel Version: 4.9.9-coreos-r1
Operating System: Container Linux by CoreOS 1298.6.0 (Ladybug)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 996.8 MiB
Name: matchbox.gsm-port.com
ID: QFZE:3MA3:HREF:OSMW:GHLU:NR3C:5DX6:4P3M:XEQQ:NX2P:VB7D:DCJ6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

To clarify even further - all of this happens inside KVM, ie. the physical LAN is actually a virt-bridge and the rest of the KVM guests have connectivity among themselves and to docker host, yet the connectivity fails to be extended back into containers.

**Comment by cpuguy83** [comment]
You should be able to communicate with the LAN via the default bridge device so long as routing is allowed.
The macvlan is for exposing the container directly to the outside world w/o going through a bridge.

What does the routing table look like inside the container?

**Comment by voobscout** [comment]
```
docker exec -ti macvlan-test ip route

default via 172.20.0.1 dev eth0 
10.99.0.0/24 dev eth1  proto kernel  scope link  src 10.99.0.200 
172.20.0.0/16 dev eth0  proto kernel  scope link  src 172.20.0.4

docker exec -ti macvlan-test iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         

Chain FORWARD (policy ACCEPT)
target     prot opt source               destination         

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

```
container has connectivity to outside, containers on same docker network see each other, their arp requests are being answered by LAN hosts, but never seen inside macvlan network.

I triple checked every access control is off, including host iptables/ebtables and everything else i could think of.

I am not even sure how to debug this, where should it be possible to isolate the issue to? There's nothing weird going on with host os, it's about 10 lines coreos cloud-init, with most lines being the public ssh key. A single systemd unit running this macvlan-test container that simply refuses to work as it should.

**Comment by cpuguy83** [comment]
Can you check `ip route get 10.99.0.220`?

**Comment by voobscout** [comment]
I did it before submitting this issue, it was my first thought...
```
ip route get 10.99.0.220
10.99.0.220 dev eth1  src 10.99.0.100
```

**Comment by cpuguy83** [comment]
ping @mavenugo

**Comment by voobscout** [comment]
[Here](https://github.com/voobscout/docker-coreos-vultr) is a painless way to reproduce the issue.

**Comment by voobscout** [comment]
Apparently it is an issue with vultr.com and not docker or coreos. I am closing this.

After trying to reproduce it on my local KVM instance, everything worked as it should. there is connectivity among containers on different kvm hosts via a bridged interface, the issue appears only when vultr.com is used.

**Comment by thaJeztah** [comment]
Thanks for the update @voobscout!
