### ISSUE TITLE
Docker push not compressing properly?

### ISSUE THREAD

**Issue by frankh** [docker/docker#32000]
**Description**

Pushing a docker image pushes significantly more data than pulling

**Steps to reproduce the issue:**
1. build an easily compressible image (e.g. https://github.com/frankh/docker-compress-test)
2. docker push it
  * Note how much it uploads. In my case, it's ~40MB
3. delete the image and docker pull
  * Note how much it downloads. In my case, ~40KB

**Describe the results you received:**

Pushing pushes significantly more data than pulling

**Describe the results you expected:**

Pushing and pulling move roughly the same amount of data

**Output of `docker version`:**

Docker version 17.03.0-ce, build 60ccb22

**Output of `docker info`:**

```
Containers: 34
 Running: 2
 Paused: 0
 Stopped: 32
Images: 1355
Server Version: 17.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 977c511eda0925a723debdc94d09459af49d082a
runc version: a01dafd48bc1c7cc12bdb01206f9fea7dd6feb70
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.12-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: CXWS:GVKV:ICYK:NJ7L:26LZ:DOYO:OBL4:NDAW:4TLZ:J2TJ:XML7:VDR2
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 33
 Goroutines: 40
 System Time: 2017-03-22T10:22:34.60882776Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Username: frankh
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker for mac (also reproducible on other platforms)

**Comment by cpuguy83** [comment]
This could be due to the progress reader using an uncompressed stream but the actual pusher is getting the compressed stream.

progress reader:
https://github.com/docker/docker/blob/master/distribution/push_v2.go#L420

compression:
https://github.com/docker/docker/blob/master/distribution/push_v2.go#L424

ping @aaronlehmann

**Comment by frankh** [comment]
@cpuguy83 I did think about that, but the speed matches what I would expect for the upload speed (Compressing and uploading 40MB of zeros should be very quick)

**Comment by aaronlehmann** [comment]
@cpuguy83: That's correct. It's this way because we don't know how big the compressed version will be, so it's not possible to show a progress bar based on the compressed output.

**Comment by thaJeztah** [comment]
Should we add a description to the docs, to explain that progress bars are shown during `docker push`, which show the uncompressed size, and that the actual amount of data that's pushed will be less? https://github.com/docker/docker/blob/master/docs/reference/commandline/push.md

**Comment by aaronlehmann** [comment]
Sure

**Comment by tripdubroot** [comment]
#dibs
