### ISSUE TITLE
Changes to CSS (Static folder) files are not getting updated - This questions on github has been unanswered of over a year

### ISSUE THREAD

**Issue by aswinckr** [docker/docker#32083]
https://stackoverflow.com/questions/35691388/docker-error-css-file-in-mapped-volume-fails-to-update

Please find link to the issue. I'm facing the same problem

**Comment by cpuguy83** [comment]
Are you using nginx+sendfile (or httpd+sendfile?)?

Closing this issue since it's not really a Docker issue. Consider hopping on the community slack for support issues.

**Comment by aswinckr** [comment]
I'm using gunicorn and i have configured --reload in my docker-compose.yml file. py and html files from my source code gets updated but static files like css doesnt

**Comment by thaJeztah** [comment]
Probably same issue as https://github.com/docker/docker/issues/18246, which is a limitation of VirtualBox file sharing, and marked as a won't fix there https://www.virtualbox.org/ticket/10660

What platform are you running on? If you're on Mac OS, have you tried Docker for Mac?

**Comment by aswinckr** [comment]
@thaJeztah forgive me i'm relatively new to docker. I'm using flask for python for developing my web application and im using `docker-compose up`for serving my source files to localhost. I have set --reload flag on my docker-compose.yml file, which works well if any changes in html and py files as mentioned above but i guess css files are getting cached or something.

**Comment by cpuguy83** [comment]
@aswinckr Has nothing to do with Docker.
This is Python's HTTP server (or whatever you happen to be using) being incompatible with virtualbox's shared filesystem. This is due to it's usage of `sendfile` http://man7.org/linux/man-pages/man2/sendfile.2.html which virtualbox shared folders do not support.
