### ISSUE TITLE
Proposal: add a way to specify build target by name

### ISSUE THREAD

**Issue by tonistiigi** [docker/docker#32104]
Follow-up proposal to #32063

Take the example from #32063 .

```
FROM ubuntu AS build-env
RUN apt-get install make
ADD . /src
RUN cd /src && make

FROM busybox
COPY --from=build-env /src/build/app /usr/local/bin/app
EXPOSE 80
ENTRYPOINT /usr/local/bin/app
```

When this Dockerfile is executed the last image is built and tagged. The first image is built but remains untagged and is reused for the cache. There may be cases where you want to build and tag `build-env` instead. In this case, it should be possible to specify the target you are interested in `docker build --target=build-env .`.

It the builder has finished building the block with name `build-env` it can stop and finish processing. Later we can make this smarter, analyze what blocks depend on each other and skip the ones that don't need to be processed.

@tiborvass @dmcgowan @simonferquel @dnephin @vdemeester @duglin

**Comment by ijc25** [comment]
Perhaps consider also the ability to tag several images without needing to restrict which images are built. If you had lots of phases you could build to a mid point but still want to tag several, so it interacts with the proposal here.

e.g. something like `docker build -t build-env=buildtag -t myapp .` (where `-t myapp` is implicitly the final image which was built) would be similar in effect to `docker build --target=build-env -t buildtag . && docker build -t myapp .` I think.

**Comment by tonistiigi** [comment]
@ijc25 I think it would make more sense if the builder (internally) always tries to solve one target. It should just be smart enough that if multiple targets need to be built concurrently, everything is properly shared and synchronized. That wouldn't make `-t build-env=buildtag` syntax completely impossible, just in that case `CLI` would invoke 2 build jobs and there would be no difference in functionality compared to doing `docker build` twice.

**Comment by cpuguy83** [comment]
@tonistiigi This is good to close now, I think?

**Comment by tonistiigi** [comment]
@cpuguy83 Why?

**Comment by cpuguy83** [comment]
Oh, nevermind, i thought this was for the `AS` syntax.

**Comment by sethfowler** [comment]
This seems like a major convenience just from the point of view of debugging multi-stage builds. Not having actually used that feature yet, I'm not totally sure, but it seems like there's no easy way to build and tag an intermediate image in a multi-stage build with a script, so it will be hard to e.g. write automated tests that verify it's correct.
