### ISSUE TITLE
Connect to Docker host from container

### ISSUE THREAD

**Issue by Telokis** [docker/docker#32101]
#1143 and #8395 are closed but not resolved.
Not a single of the workarounds found there has been working for me. (No joke, I've tried a *lot* of them)

I do need a way to connect to a service running on my host from within a container. I don't want a hacky workaround, this is not reliable. I want an effective solution working for Windows and Linux at least.

This may be link to that : even though I can access the internet from within my container (using wget, for example), I can't access my own host ip. It keeps hanging indefinitely an doesn't show anything.
I tried a lot of different ways but none worked.

**Comment by mavenugo** [comment]
@Telokis pls add all the basic details that the new issue template would have prompted you to. Such as `docker version`, `docker info`, and other details on what service you are trying to access, reproduction steps etc...

**Comment by Telokis** [comment]
Docker version:
```
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:52:25 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 06:52:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

Docker info:

```
Containers: 5
 Running: 5
 Paused: 0
 Stopped: 0
Images: 37
Server Version: 1.13.1
Storage Driver: devicemapper
 Pool Name: docker-8:1-914044-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 3.049 GB
 Data Space Total: 107.4 GB
 Data Space Available: 6.394 GB
 Metadata Space Used: 4.719 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.143 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.137 (2016-11-30)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1
runc version: 9df8b306d01f59d3a8029be411de015b7304dd8f
init version: 949e6fa
Kernel Version: 4.6.0-1-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.59 GiB
Name: ***
ID: 63DC:SOQW:AGBN:HEQ4:47CR:E6BB:KL5W:SBQX:YLVY:GLT7:3VBI:6WA4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: ninetainedo
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

* Went inside a container (any container, using exec or `/bin/bash` directly)
* Tried to curl/wget/telnet `mydomain.com`
* Domain is resolved but container doesn't connect to it.
* Domain is (obviously) working fine when I access it from anything other than a container.

**Comment by mavenugo** [comment]
@Telokis I thought `docker info` carried the `userland-proxy` configuration as well. Apparently not.
Can you pls confirm if you use `--userland-proxy=false` when launching the daemon ?

**Comment by Telokis** [comment]
How can I know that? I don't even remember launching the daemon, it's been a long time I think. Maybe I can restart it to include this command line option? `sudo service docker stop`?

**Comment by mavenugo** [comment]
@Telokis no. pls dont restart the daemon :) I was just checking if you knew it. am just trying to isolate the condition. When i tried in my local daemon, both with and without userland-proxy things works as expected. So we have to collect more data I think.

**Comment by Telokis** [comment]
Alright.
What I find really odd is that I can access anything but my own server. It's as if Docker blocked that specific case inside my iptables

**Comment by Telokis** [comment]
Anyone, please?

**Comment by Telokis** [comment]
However, this works fine when tested on my local Windows computer.

@thaJeztah @olleolleolle
