### ISSUE TITLE
Port redirecting binding to IPv6 but not IPv4 interfaces, 2017

### ISSUE THREAD

**Issue by hesco** [docker/docker#32117]
**Description**

When I expose a port with `-p 80:80` the port is open on IPv6, but not IPv4.  
I see that cpuguy closed this issue only a couple of days ago, here:
https://github.com/docker/docker/issues/2174. 

If anyone has summarized the 3-4 year old ;tldr (but skimmed some) thread on that issue, I would appreciate a link.  I am setting up tests in my local environment to explore ideas at that url, and will close this issue out with my notes if I get this resolved by doing that.  

If folks think this is something new, I'd like to hear that as well, please.  

-- Hugh 

**Steps to reproduce the issue:**
The entry from my build log shows me:

```
20170325_220949 -- /usr/bin/docker run -d     \
    --net=ymdweave \
    --ip 10.0.1.22 \
    --dns=68.64.241.98 --dns=68.64.241.102  \
   --dns-search=zone1.weave.local \
    --memory=4gb \
    --restart=always \
    --privileged=true \
    --name=ida4 \
    -h ida4.yourmessagedelivered.com \
    -p 80:80/tcp \
    -v /data/var/log/haproxy:/var/lib/haproxy/dev \
    -v /data/etc/haproxy:/etc/haproxy \
    ymd_haproxy:0.1.0
```

**Describe the results you received:**

`netstat -anp | grep :80` gives me:  

```
tcp6       0      0 :::80                   :::*                    LISTEN      28662/docker-proxy
```

`docker inspect` shows:

```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "954db9ac841429a5d92e24635bdc35789c08b5d05e31f9393dba7adf011a0164",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "80"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/954db9ac8414",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "ymdweave": {
                    "IPAMConfig": {
                        "IPv4Address": "10.0.1.22"
                    },
                    "Links": null,
                    "Aliases": [
                        "66ecfb232a4c"
                    ],
                    "NetworkID": "0aa859f7d27a49ec9492c05fde587fe7fbe074b06765004a81cd036d6a421ce3",
                    "EndpointID": "75ffa254ca7cf3311cb0ad93e68d9e47bcc79ad1dc1d8770d5b584e16eb71f08",
                    "Gateway": "",
                    "IPAddress": "10.0.1.22",
                    "IPPrefixLen": 20,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "52:7a:f4:27:96:21"
                }
            }
        }
    }
]
```

**Describe the results you expected:**

I expected port 80 to be open to each of the IPv4 addresses attached to any physical interface on the host machine (in this case a publicly routable IP on eth0, and the IP on the private network provided by my switch at eth1).  

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:02:53 2016
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Containers: 26
 Running: 10
 Paused: 0
 Stopped: 16
Images: 515
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 583
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: weavemesh null overlay host bridge
WARNING: No kernel memory limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options:
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 23.6 GiB
Name: dessalines002
ID: HB3U:B5SF:M6IS:UMPC:GTNF:CDA2:MRUV:PWIB:2N6H:FRFD:T3B4:OP5J
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

bare-metal in remote rack, 2x quad-core, 24gb ram

**Comment by hesco** [comment]
I was able to reproduce this issue on a fresh install.  Again I see:

```
root@dessalines013:~# docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS                NAMES
d3bc0d5fb73d        ymd_haproxy:0.1.0   "/sbin/my_init"     5 seconds ago       Up 4 seconds        0.0.0.0:80->80/tcp                   ida4.example.com

root@dessalines013:~# netstat -anp | grep :80
tcp6       0      0 :::80                   :::*                    LISTEN      19645/docker-proxy
```

tcp6, but no tcp for the IPv4 interface.  

```
# iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             multiport sports 8139:8140 /* 08140 puppet client ingress  */ state RELATED,ESTABLISHED
ACCEPT     udp  --  anywhere             anywhere             multiport dports 60001:60010 /* 60001 allow mosh connections */

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-ISOLATION  all  --  anywhere             anywhere
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             anywhere             multiport dports 8139:8140 /* 08140 puppet client egress  */ state NEW

Chain DOCKER (1 references)
target     prot opt source               destination
ACCEPT     tcp  --  anywhere             172.17.0.2           tcp dpt:http

Chain DOCKER-ISOLATION (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
```

This is what docker gave me, before I touched iptables with any of my custom code.

**Comment by wenjianhn** [comment]
This is happening because by default, AF_INET6 sockets will actually work for both IPv4 and IPv6. 
See http://unix.stackexchange.com/questions/237731/why-are-ipv4-tcp-connections-showing-as-tcp6

**Comment by cpuguy83** [comment]
The summary is here: https://github.com/docker/docker/issues/2174#issuecomment-289049493
Please, kindly read it before opening a new issue, I exactly explained what's going on and how it's not an issue.

**Comment by amitsehgal** [comment]
I have same issue and i still think its a docker. My port mapping is 18337 (0.0.0.0:18337->51005/tcp)


tcp6       0      0 :::61420                :::*                    LISTEN      -
tcp6       0      0 :::111                  :::*                    LISTEN      -
tcp6       0      0 :::36598                :::*                    LISTEN      -
tcp6       0      0 :::22                   :::*                    LISTEN      -
tcp6       0      0 ::1:25                  :::*                    LISTEN      -
tcp6       0      0 :::18337                :::*                    LISTEN      -
tcp6       0      0 :::2375                 :::*                    LISTEN      -

docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:54:03 2017
 OS/Arch:      linux/amd64
 Experimental: false

I can connect to any other port i open outside docker.

nc -l 12345
[centos@dcos-bootstrap-5mwdpwfivlbv ~]$ telnet xxx.xxx.xx.xx 12345
Trying xxx.xxx.xx.xx...
Connected to xxx.xxx.xx.xx.
Escape character is '^]'.

**Comment by hesco** [comment]
And it turns out that I had a residual rule in my FORWARD table shunting the traffic off to an IP not bound to anything.  So I flushed the iptables and restarted the docker daemon and can now access the haproxy service running on a container at the public IP bound to my docker host.  

Guess that was a never-mind.

**Comment by manju369** [comment]
For me, working after setting SELinux to **disabled** mode, I am running my docker service on Centos 7 OS

Check  by executing this command ``` sudo setenforce 0```
