### ISSUE TITLE
Swarm API, Cannot create a service with secret

### ISSUE THREAD

**Issue by Fabryprog** [docker/docker#32160]
Hello,

I have a service with secret parameters and i cannot create it using docker swarm API

Can you expose secret params into docker swarm API (POST /services/create)?

Thanks

**Comment by thaJeztah** [comment]
Could you provide some more information? 

- output of `docker version`
- output of `docker info`
- exact steps to reproduce (e.g. the API request you're making)

Please keep in mind that the GitHub issue tracker is not intended as a general support forum,
but for reporting bugs and feature requests. For other type of questions, consider using one of;

- https://forums.docker.com
- the [Docker community Slack channel](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/)
- [StackOverflow](https://stackoverflow.com)

**Comment by Fabryprog** [comment]
Hello i have 17.03.0-ce docker version. 

However you can check my issue using your eyes. Into this page
https://docs.docker.com/engine/api/v1.27/#operation/SecretCreate
isn't any information regard secrets

can you help me?

**Comment by thaJeztah** [comment]
I'm not sure I understand the question; what information are you missing?

<img width="831" alt="screen shot 2017-03-30 at 16 52 26" src="https://cloud.githubusercontent.com/assets/1804568/24510398/6218fb18-1569-11e7-888a-9a9ca8e0fae6.png">

<img width="557" alt="screen shot 2017-03-30 at 16 52 41" src="https://cloud.githubusercontent.com/assets/1804568/24510397/62105904-1569-11e7-9ec6-931c2007c170.png">

**Comment by Fabryprog** [comment]
@thaJeztah i am sorry but i had copy a wrong link. Sorry, look at this link: https://docs.docker.com/engine/api/v1.27/#operation/ServiceCreate

**Comment by Fabryprog** [comment]
Hello, There are any news?

**Comment by vdemeester** [comment]
@Fabryprog there is a `Secret` "information" in the `ServiceCreate` Section, under `TaskTemplate > ContainerSpec` :ang

**Comment by Fabryprog** [comment]
Finally!

When i open this issue there aren't!
Tnkx
