### ISSUE TITLE
Cannot use client API due to dependencies vendoring

### ISSUE THREAD

**Issue by ndeloof** [docker/docker#32182]
**Description**

I'm trying to write some code relying on docker codebase for client API

But I just can't get it to compile as I get a type mismatch on golang.org/x/net/context parameter to ContainerCreate function :

```
    have (“golang.org/x/net/context”.Context, ...)
    want (“github.com/docker/docker/vendor/golang.org/x/net/context”.Context, ...)
```

And also, using this vendored reference is not allowed by the language

```
    use of vendored package not allowed
```

this seems to be a pretty common issue (see https://github.com/vulcand/vulcand/issues/281 for sample) 

**Steps to reproduce the issue:**
1. create a go project to use "github.com/docker/docker/client" 
2. invoke client.CommonAPIClient.ContainerCreate(context.Background(), config, hostConfig, networkingConfig, name)
3. try to compile it

**Describe the results you received:**
compilation failure

**Describe the results you expected:**
can use docker client API from another project

**Comment by thaJeztah** [comment]
IIRC, this is if the vendoring tool doesn't strip nested vendor-directories, also see https://github.com/docker/docker/issues/29362, https://github.com/docker/docker/pull/27912

/cc @LK4D4 @vdemeester

**Comment by ndeloof** [comment]
It seems this error was introduced by my IDE. Creating a minimal project to demonstrate this just don't suffer this issue. Closing this issue until I'm sure there's an actual issue with this.

**Comment by vdemeester** [comment]
@ndeloof thanks for the issue. Could be considered a duplicate from https://github.com/docker/docker/issues/30454 or https://github.com/docker/docker/issues/29362 (and probably others). It could also be considered a Go issue as it is how vendoring in Go works. 

In order to use `docker/docker`, you need to strip the nested vendor folder.

**Comment by vdemeester** [comment]
@ndeloof lol you closed it before I even finished my answer 😅

**Comment by ndeloof** [comment]
😸  don't want you spend to much time if I actually made a mistake on my dev environment setup
