### ISSUE TITLE
Proposal: Option to not remove container without force

### ISSUE THREAD

**Issue by jlk** [docker/docker#32184]
In some scenarios, a user may want to capture the state of a container at termination - be that logs or other ephemeral files in the container - before container destruction. Two potential reasons for doing so is for forensic purposes, or for troubleshooting.

One method to achieve this would be to add an option "--require-force-rm" to DOCKER_OPTS which would disable removal of a container by default unless the config.ForceRemove is set to true in ContainerRm(). This would allow the API itself to not be modified, but would slightly change the meaning of the API, so maybe that's not the best way. I'm open to suggestions there. --require-force-rm would be false by default so consumers of the API would see no change unless it's enabled.

This might be considered functionality for an orchestration system, but at least at first glance it seems to make more sense to have in the Docker Engine.

**Comment by cpuguy83** [comment]
@jlk This doesn't seem right. Won't people just start using `-f` by default?

This could be handled with an authz plugin today. I don't think we need to add a specific feature for it.

**Comment by jlk** [comment]
@cpuguy83 I'm thinking more of the automated use case than humans. eg a container fails a health check in Swarm Mode cluster, so it's killed/recreated. Centralized logs get some of the use case, but I could see wanting to have a snapshot of the filesystem for investigation.

Hadn't thought of the authz approach, but that could be one way to do it.

Will go back to drawing board on this for now. Thx for comments.

**Comment by cpuguy83** [comment]
@jlk containers are kept around when the task is killed. There's a task-history setting, actually.
