### ISSUE TITLE
Compose long port syntax does not work with `docker stack deploy`

### ISSUE THREAD

**Issue by EdeMeijer** [docker/docker#32202]
**Description**

I am using Docker in swarm mode along with a docker compose file for defining my services. One of my services, the main nginx instance, is pinned to a single public server and should only listen on that server. In order to prevent it to be accessible from all nodes through the mesh network, I want to use use a port binding in `host` mode so that it only binds to the one node it runs on. According to the Docker compose file reference there is a long syntax to support this (https://docs.docker.com/compose/compose-file/#long-syntax). However, when using the long syntax and trying to deploy the cluster with `docker stack deploy`, I get an error. It looks like `docker stack` cannot parse the long syntax which was introduced in docker compose file v3.2.

**Steps to reproduce the issue:**
1. Install Docker 17.03.1-ce
2. Set up a swarm using swarm mode
3. On the swarm master, prepare a `docker-compose.yml` file like this
```yaml
version: '3'

services:
  nginx:
    image: nginx:1.11.9
    ports:
      - target: 80
        published: 80
        mode: host
    deploy:
      replicas: 1
```
4. Then run
```
docker stack deploy --compose-file ./docker-compose.yml test
```
**Describe the results you received:**
```
services.nginx.ports.0 must be a string or number
``` 
**Describe the results you expected:**

I expected the service to be created successfully with port 80 bound only on the node it runs on.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:17:43 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 7
 Running: 7
 Paused: 0
 Stopped: 0
Images: 59
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 442
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: qs3lt2criv7jhcvzesd67yms1
 Is Manager: true
 ClusterID: 3xl0jvi89my70ey73ov1yxwf8
 Managers: 3
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: (moderated)
 Manager Addresses:
  (moderated):2377
  (moderated):2377
  (moderated):2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-37-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859 GiB
Name: (moderated)
ID: QCC5:DWAZ:3X4N:KXXF:XY4U:KCUB:4RCL:OYJT:LTXK:IZOI:SX6B:4YDJ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running a cluster consisting of 3 master nodes on VPSes on Ubuntu 16.10.

**Comment by cpuguy83** [comment]
This will be in 17.04.
Thanks!

**Comment by EdeMeijer** [comment]
Great, looking forward to it.

**Comment by mtahiue** [comment]
still not working with 17.04

```
$ docker --version
Docker version 17.04.0-ce, build 4845c56

docker-stack.yml contains :
        ports:
          - mode: host
            target: 80
            published: 8080

$ docker stack deploy --compose-file docker-stack.yml --with-registry-auth testapp
services.testapp-nginx.ports.0 must be a string or number
```

**Comment by danidee10** [comment]
I don't understand docker's Release and Version numbers anymore (it was on 1.1x and all of a sudden jumped to 17.x)

But docker version reports `17.05.0-ce` and i'm still facing this bug

@EdeMeijer is there something i can do to get this working? or it's not fixed yet

Thanks

**Comment by thaJeztah** [comment]
@danidee10 it's added to the docker-compose schema version 3.2; setting that version should make it work;

```yaml
version: '3.2'

services:
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    deploy:
      replicas: 1
```

**Comment by danidee10** [comment]
Thanks @thaJeztah it works! 😄. Another problem is how do you bind the ports to `127.0.0.1` instead of `0.0.0.0` I've tried the short syntax with `"127.0.0.1:xxxx:xxxxx"` This used to work on version 2 of `docker-compose` but now swarm mode ignores the explicit setting and publishes `0.0.0.0` instead.

I guess i should open another issue for this, but i feel it's a simple thing I'm missing to get this working.

**Comment by thaJeztah** [comment]
Binding to a specific IP-address is not (yet?) supported for services

**Comment by danidee10** [comment]
Okay, is there any attempt to add this, so i can monitor the progress?

**Comment by mhicauber** [comment]
related to [https://github.com/moby/moby/issues/25303](url)

**Comment by kayjtea** [comment]
Using version 3.3 of docker-compose.yml appears to fix this problem.

```
version: '3.3'

services:
  
...
```

**Comment by kedarX** [comment]
@thaJeztah does the long syntax for ports support ENV variable interpolation? If yes, what version onwards?
see's below version with 3.3 compose and docker v17.06.xx
```
services.myservice.ports.0.target must be a integer
```
