### ISSUE TITLE
get.docker.com script does not install docker-engine properly without lsb-release

### ISSUE THREAD

**Issue by andrewhsu** [docker/docker#32210]
**Description**

Install of `docker-engine` via curl script on a debian stretch environment without `lsb-release` package already installed will fail.

**Steps to reproduce the issue:**

```
bash$ docker pull debian:stretch
bash$ docker run --rm -it debian:stretch bash
bash# apt-get update
bash# apt-get install -y curl
bash# curl -fsSL https://get.docker.com/ | sh
...
Err:5 https://apt.dockerproject.org/repo debian-9/main amd64 Packages
  403  Forbidden
Hit:7 http://deb.debian.org/debian stretch-updates InRelease
Reading package lists... Done
W: The repository 'https://apt.dockerproject.org/repo debian-9 Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch https://apt.dockerproject.org/repo/dists/debian-9/main/binary-amd64/Packages  403  Forbidden
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package docker-engine
```

**Describe the results you received:**

a dockerless environment

**Describe the results you expected:**

docker

🐛

**Comment by andrewhsu** [comment]
perhaps another case statement for https://github.com/docker/docker/blob/master/hack/install.sh#L368

**Comment by thaJeztah** [comment]
oh, yes, I noticed that a while back, there may be an issue about it, let me check

**Comment by thaJeztah** [comment]
yup, dup of https://github.com/docker/docker/issues/30456 😇

**Comment by thaJeztah** [comment]
looks like https://github.com/docker/docker/pull/30480 was meant to resolve this though, and I see the online script is updated with that change

**Comment by vieux** [comment]
@thaJeztah looks like https://github.com/docker/docker/pull/32211 is missing

**Comment by thaJeztah** [comment]
oh, I see it now, we do that check twice / different approaches there 🤔

**Comment by vieux** [comment]
@thaJeztah yes one when you have the `lsb_release` binary, and one where you simply cat / sed a file in `/etc/`
