### ISSUE TITLE
Docker installation on windows server 2016 standard

### ISSUE THREAD

**Issue by niranjank19** [docker/docker#32249]
**Description**
I am working on Docker installation for windows server 2016 standard. 
<!--PS C:\> docker pull microsoft/nanoserver
Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Downloading
58f68fa0ceda: Downloading
unknown blob
PS C:\> docker pull microsoft/iis
Using default tag: latest
latest: Pulling from microsoft/iis
3889bb8d808b: Retrying in 1 second
503d87f3196a: Downloading
ea440dc770db: Download complete
46f765ced05f: Download complete
640f08987e57: Download complete
a81c4ca315a9: Download complete
unknown blob

**Steps to reproduce the issue:**
1. docker pull microsoft/nanoserver
2.
3.

**Describe the results you received:**

Using default tag: latest
latest: Pulling from microsoft/nanoserver
bce2fbc256ea: Downloading
58f68fa0ceda: Downloading
unknown blob
**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
`````PS C:\> docker version
Client:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0-dev
 API version:  1.24
 Go version:   go1.5.3
 Git commit:   8e92415
 Built:        Thu May 26 17:08:34 2016
 OS/Arch:      windows/amd64


**Output of `docker info`:**

```
(paste your output here)
`PS C:\> docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.12.0-dev
Storage Driver: Windows filter storage driver
 Windows:
Logging Driver: json-file
Plugins:
 Volume: local
 Network: nat null
Kernel Version: 10.0 14393 (14393.953.amd64fre.rs1_release_inmarket.170303-1614)
Operating System: Windows Server 2016 Standard
OSType: windows
Architecture: x86_64
CPUs: 4
Total Memory: 7.999 GiB
Name: PPUABIMDOCT01
ID: OOO5:ETM2:AJTL:BGVD:POS7:MWN6:ABKY:XDFE:BE54:7AHZ:DR7M:BGWF
Docker Root Dir: C:\ProgramData\docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Windows server 2016 standard running on a VMware virtual platform

**Comment by AkihiroSuda** [comment]
I guess this was opened by mistake, so I'm closing this.

If you are trying to reporting an issue, please fulfill the issue template

https://github.com/docker/docker/blob/master/.github/ISSUE_TEMPLATE.md
