### ISSUE TITLE
yum update PYCURL ERROR 22 on Docker Testing

### ISSUE THREAD

**Issue by rvernica** [docker/docker#32281]
**Description**

I followed the `curl ... sh` instructions to get the Docker Testing repository setup. I get an error when I do `yum update`. I am behind a web proxy.

**Steps to reproduce the issue:**
1. `curl -fsSL https://test.docker.com/ | sh`
2. `yum update`

**Describe the results you received:**

```
> yum update
Loaded plugins: fastestmirror
Setting up Update Process
Loading mirror speeds from cached hostfile
 * base: mirror.scalabledns.com
 * epel: mirror.oss.ou.edu
 * extras: centos.mirrors.wvstateu.edu
 * updates: mirror.oss.ou.edu
https://yum.dockerproject.org/repo/testing/centos/6/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 403 Forbidden"
Trying other mirror.
To address this issue please refer to the below knowledge base article

https://access.redhat.com/solutions/69319

If above article doesn't help to resolve this issue please open a ticket with Red Hat Support.

Error: Cannot retrieve repository metadata (repomd.xml) for repository: docker-testing-repo. Please verify its path and try again
```

**Additional information you deem important (e.g. issue happens only occasionally):**

```
> cat /etc/yum.repos.d/docker-testing.repo
[docker-testing-repo]
name=Docker testing Repository
baseurl=https://yum.dockerproject.org/repo/testing/centos/6
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

I tried replicing `https` with `http` but I got the same result. The Docker Main repository works fine.

```
cat /etc/yum.repos.d/docker-main.repo
[docker-main-repo]
name=Docker main Repository
baseurl=https://yum.dockerproject.org/repo/main/centos/6
enabled=1
gpgcheck=1
gpgkey=https://yum.dockerproject.org/gpg
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Phisical machine.
```
> cat /etc/centos-release
CentOS release 6.8 (Final)
> uname -a
Linux ... 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by thaJeztah** [comment]
this is expected;Docker support for RHEL 6 and CentOS 6 ended 2 years ago; the laters version of docker released for that was docker 1.7.1

please upgrade to a newer version of CentOS, and kernel 3.10 or above

I'll close this issue because this is expected, but feel free to continue the conversation
