### ISSUE TITLE
image cross-registry(with same storage backend) push invalid

### ISSUE THREAD

**Issue by duyanghao** [docker/docker#32287]
there are two domains for my two private registries,one called `domainA.registry.com`,another called `domainB.registry.com`,and strange things happen when i do following:

step1: push image `domainA.registry.com/base/centos` to `domainA.registry.com` registry

step2: tag image `domainA.registry.com/base/centos` to `domainB.registry.com/base/centos`

step3: push image `domainA.registry.com/base/centos` to `domainA.registry.com` registry **again**

```
4edc282e31bc: Layer already exists 
f7480871b9b6: Layer already exists 
e0adf57f111b: Layer already exists 
3d83bd2b9b03: Layer already exists 
fcd8893b6e56: Layer already exists 
0bbdf08ef355: Layer already exists 
bce7ba704c29: Layer already exists 
e9592dae4084: Layer already exists 
8bd3d51225cb: Layer already exists 
b0fb6f901071: Layer already exists 
ddb2a40049bb: Layer already exists 
f28739495df3: Layer already exists 
c621d5395079: Layer already exists 
a2d0924ca4d2: Layer already exists 
367b9c52c931: Layer already exists 
3567b2f05514: Layer already exists 
292a66992f77: Layer already exists 
641fcd2417bc: Layer already exists 
78ff13900d61: Layer already exists 
v0.1: digest: sha256:2abb84adc12fc96901473a86fab97becb9724de6118f941983c59090ec5ac6ac size: 8226
```

step4: push image `domainB.registry.com/base/centos` to `domainB.registry.com` registry

```
4edc282e31bc: Pushed 
f7480871b9b6: Pushed 
e0adf57f111b: Pushed 
3d83bd2b9b03: Pushed 
fcd8893b6e56: Pushed 
0bbdf08ef355: Pushed 
bce7ba704c29: Pushed 
e9592dae4084: Pushed 
8bd3d51225cb: Pushed 
b0fb6f901071: Pushed 
ddb2a40049bb: Pushed 
f28739495df3: Pushed 
c621d5395079: Pushed 
a2d0924ca4d2: Pushed 
367b9c52c931: Pushed 
3567b2f05514: Pushed 
292a66992f77: Pushed 
641fcd2417bc: Pushed 
78ff13900d61: Pushed 
v0.1: digest: sha256:2abb84adc12fc96901473a86fab97becb9724de6118f941983c59090ec5ac6ac size: 8226
```
Why it is still pushing the same existed digest if the two registries share the same storage backend?

Additional information:
registry version:2.3.0(**backend with aws s3**)
docker version:1.12.5

the two registries have same configuration

Refs:
https://github.com/docker/distribution/issues/2234

**Comment by thaJeztah** [comment]
If I understand correctly, this should be fixed by https://github.com/docker/docker/pull/26564, and https://github.com/docker/docker/pull/31720 in the upcoming docker 17.05 release

ping @miminar @jonjohnsonjr @dmcgowan correct?

**Comment by miminar** [comment]
I believe so - especially with the latter PR.

**Comment by thaJeztah** [comment]
Thanks for looking @miminar 

@duyanghao I'll go ahead and close this issue for housekeeping, but let us know if you still see this issue after docker 17.05 has been released!
