### ISSUE TITLE
[Suggest] add some “trigger function” to docker events

### ISSUE THREAD

**Issue by mangobowl** [docker/docker#32292]
Is there any plan to add some “trigger function” to docker events? I think it should be very useful.
for example:
If healthcheck report the status of one container is "unhealthy", then this event trigger docker to restart the container automatically.
Sorry for my poor english, but i hope you can understand what i said above :)

**Comment by cpuguy83** [comment]
@mangobowl This is what swarm-mode does.

**Comment by mangobowl** [comment]
@cpuguy83 Swarm-mode will only restart an "exited" container, but the "unhealthy" container (reported by HEALTHCHECK) may be just stuck in something  (e.g. an infinite loop), which is not "exited", so it won't be restarted in swarm-mode.

**Comment by cpuguy83** [comment]
Unhealthy swarm tasks are killed and re-created.

```Dockerfile
FROM busybox
HEALTHCHECK --retries=1 CMD [ "sh", "-c" '-f /tmp/bar || exit 1' ]
```

```
$ docker service create --name test test top
ycleg17g1brkhiye5im0zj9mm
$ docker service ps test
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE          ERROR                              PORTS
73vfql1s70f2        test.1              test                moby                Ready               Ready 1 second ago
o489nk98w6so         \_ test.1          test                moby                Shutdown            Failed 3 seconds ago   "task: non-zero exit (143): do…"
```

The task was killed after 30s (which is how long it took to report unhealthy).

**Comment by mangobowl** [comment]
@cpuguy83 I tested that in swarm-mode, and it worked as you said above, tks!
