### ISSUE TITLE
Lose local images after Docker for Mac upgrade

### ISSUE THREAD

**Issue by designt** [docker/docker#32303]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

After I upgrade Docker for Mac from the previous version to the actual version I "lose" My Local Images in Kinematic and I also do not see any images with  docker images command.

⮀  ⮀ docker images                                                    ⮂
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
 / ⮀  ⮀  ⮀

**Steps to reproduce the issue:**
Upgrade from previous version

**Describe the results you received:**
no local images

**Describe the results you expected:**
keep previous images

**Output of `docker version`:**

Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:00:50 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**
                                              ⮂
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.13-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: 4TEX:ELVL:Q74W:VTUY:R2LF:OLRX:VBFE:E4KL:R2WF:Y2CO:TM7Q:JECA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 17
 Goroutines: 29
 System Time: 2017-04-02T09:14:37.427566242Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):
Docker for Mac

**Comment by justincormack** [comment]
Can you open this on https://github.com/docker/for-mac/issues as it is Docker for Mac specific; please include a diagnostic ID.

**Comment by thaJeztah** [comment]
let me close the issue here, but feel free to comment after I closed
