### ISSUE TITLE
docker build: error pulling image configuration

### ISSUE THREAD

**Issue by LucianoVandi** [docker/docker#32316]
**Description**

If I try to build or pull an image the process stuck on "Pulling fs layer". 

I'm running docker for Mac on a OS X El Capitan 10.11.6

**Steps to reproduce the issue:**
1. docker build -t custom-img:v0.0.1 .

**Describe the results you received:**
```
Sending build context to Docker daemon 3.072 kB
Step 1/11 : FROM debian:jessie
jessie: Pulling from library/debian
6d827a3ef358: Pulling fs layer
error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/8c/8cedef9d7368741f8539f3c984dee7c3a5953ef69178585e6da188255e12223d/data?Expires=1491224314&Signature=FBjlS9oiNeIQTxKbZTxIMRuH1rbHHUj53sGpTOJ4nm2MNbPYg3hVUeRx~iMHsQ-fhCmHzLGklilBB8abMigJdj0hPeUVLwHYVYAlZuva2yOZID6Lfb1eQkQNHNFXP8xpfw6QBDdqtwF38Q33zCitCcav47mvbYFSchu-OZxkZW4_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: dial tcp: lookup dseasb33srnrn.cloudfront.net on 10.0.2.3:53: read udp 10.0.2.15:40870->10.0.2.3:53: i/o timeout
```

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 16:58:30 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 0
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.57-boot2docker
Operating System: Boot2Docker 17.03.1-ce (TCL 7.2); HEAD : 4c264fa - Tue Mar 28 21:11:51 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8 MiB
Name: default
ID: FSVE:OL2S:JNLC:IZLS:YUKD:FE3J:ZUAO:J7X2:WBN6:RN6L:GE6M:MO5O
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 22
 System Time: 2017-04-03T12:46:05.097845393Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Output of `VBoxManage --version`:**
5.1.18r114002

**Comment by thaJeztah** [comment]
This looks like a networking issue, possibly in your local setup

> I'm running docker for Mac on a OS X El Capitan 10.11.6

From the output of your `docker info` it looks like you're actually still using Docker Toolbox / Boot2Docker. Docker for Mac does not require virtualbox to run, but instead uses an XHyve / HyperKit based VM to run Docker in.

Is there a specific reason you're using VirtualBox, or is this because you previously had Docker Toolbox installed?

If the latter, you can uninstall Docker Toolbox (and VirtualBox); with Docker for Mac there's also no need to set environment variables to connect to the daemon (which is what the Docker Quickstart terminal does); any shell would work, and connect you to docker

**Comment by LucianoVandi** [comment]
@thaJeztah thanks for suggestion. 

Never installed Docker before on this machine. I've downloaded the dmg from this link: https://docs.docker.com/docker-for-mac/install/#download-docker-for-mac

**Comment by thaJeztah** [comment]
Did you use `docker-machine` to create a machine?

**Comment by LucianoVandi** [comment]
Yes you're right, used it... So, I can run build and docker-compose without creating a docker-machine?

**Comment by thaJeztah** [comment]
Yes, `docker-machine` can still be used to create _additional_ machines (e.g. running locally on VirtualBox, or remotely on a cloud-provider), but to run Docker, all you need is Docker for Mac, no VirtualBox needed.

There have been some VirtualBox bugs that caused networking to go bad, so possibly that's related in this case.

Let me go ahead and close this issue, but feel free to continue the conversation
