### ISSUE TITLE
Error while replicating service on overlay network

### ISSUE THREAD

**Issue by vaibhav-gadgil-sp** [docker/docker#32317]
I have total 3 docker host machines configured at my end. Out of 3, 2 machines are Ubuntu machines and 1 is a Windows Server 2016 machine.
I have initialed my 1 Ubuntu machine as a Swarm manager and other 2 have joined this Swarm as a worker node. node ls command returns the correct result.
I have created an overlay network on Swarm manager and have confirmed that the scope of this network is my Swarm.
Once this is done I am trying to start a simple nginx service on my manager and trying to replicates it on other 2 nodes. The service is running successfully on other Ubuntu worker node but it's failing to run on Windows Server 2016 machine with the error : "HNS failed with error : Catas…"

Below are the results of the commands

ocker node ls
ID                           HOSTNAME         STATUS  AVAILABILITY  MANAGER STATUS
hcm8zis4t1vl5sud0edxjhym0    Ubuntu-Vaibhav   Ready   Active
k2q84lym4kqr4hssihqgkpekh *  Ubuntu-Vaibhav   Ready   Active        Leader
l72utxfot3tph4l29jkw4ugko    WIN-K9C4BAG48RV  Ready   Active

docker service ps n3pd8bxapr9i
ID            NAME            IMAGE         NODE             DESIRED STATE  CURRENT STATE              ERROR                             PORTS
2ivxnfzu7y4p  my-nginx.1      nginx:latest  Ubuntu-Vaibhav   Running        Running about an hour ago
h59tmny9jcei  my-nginx.2      nginx:latest  Ubuntu-Vaibhav   Running        Running 55 minutes ago
zfk1jbqrn6xs   \_ my-nginx.3  nginx:latest  WIN-K9C4BAG48RV  Shutdown       Rejected 55 minutes ago     "HNS failed with error : Catas…"
r0cc4ph6ap3v   \_ my-nginx.3  nginx:latest  WIN-K9C4BAG48RV  Shutdown       Rejected 55 minutes ago     "HNS failed with error : Catas…"
lgbnr1voxgvp  my-nginx.3      nginx:latest  Ubuntu-Vaibhav   Running        Running 55 minutes ago

One more difference I have observed is the network ls command has same results on my Ubuntu machines but shows very different results on my windows server 2016 machine:

On both Ubuntu --> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
f1fb13d4c100        bridge              bridge              local
a9c857e1503f        docker_gwbridge     bridge              local
86bad92f20c4        host                host                local
y7yhbr5tllk4        ingress             overlay             swarm
3817dd735b02        none                null                local
1c5qg3aelnkh        overnet             overlay             swarm

On Windows Server 2016 --> docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
3828e6ea1e97        nat                 nat                 local
4a3b37c76ec6        none                null                local

Please suggest what I am missing here?

Also when I run the network inspect command on Swarm manager, then Windows Server machine is not listed in the peers section. Only 2 Ubuntu machines are listed. But node ls command clearly shows that the Windows Server machine has joined as worker node to the Swarm.

**Comment by thaJeztah** [comment]
Overlay networking is not yet supported on Windows Server 2016 (only on Windows 10 Creators Update IIUC), so swarm mode will not function properly.

In addition, mixed (windows/linux) swarm setups are not supported; the error you're seeing is because docker attempts to pull the same image as is running on the Ubuntu machines, but on a Windows machine. That image is Linux-only, and won't run on a Windows machine, causing it to fail.

Mixed Windows/Linux setups are being discussed in this issue; https://github.com/docker/docker/issues/31348, but there's no date yet when this will become available.

I'm closing this issue because these are known limitations, but feel free to continue the conversation.
