### ISSUE TITLE
multiple enviroment variables makes docker service update randomly force restart

### ISSUE THREAD

**Issue by vayasin** [docker/docker#32344]
**Description**

When using multiple enviroment variables (more than one) to create a service will cause "docker service update" to randomly force a restart of the service.

**Steps to reproduce the issue:**
1. create a docker swarm 
2. create a service
`docker service create --name="redis" --env="val1=one" --env="val2=two" redis`
3. execute an service update
`docker service update redis`
on random occasions this will result in docker restarting the running container. (about 1 in 10 times)

**Describe the results you received:**
 docker randomly restarting the running container. (about 1 in 10 times)

**Describe the results you expected:**
docker service update should not trigger a restart in this situation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 13
 Running: 10
 Paused: 0
 Stopped: 3
Images: 27
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 457
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: 1z65oqzst0golngjawjge2uhd
 Is Manager: true
 ClusterID: 5mzfdmwvdbewra00c6hkcknm0
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 172.31.14.157
 Manager Addresses:
  172.31.14.157:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-71-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795 GiB
Name: ip-172-31-14-157
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Running in AWS on EC2 t2.large instances.

**Comment by thaJeztah** [comment]
I think this was meant to be fixed by https://github.com/docker/docker/pull/29732 (which is in 17.03.1; https://github.com/docker/docker/blob/v17.03.1-ce/cli/compose/convert/service.go#L118)

**Comment by aaronlehmann** [comment]
@thaJeztah: #29732 only applies to stacks. `service update` needs a similar fix. It converts the env vars to a map and back (see `updateEnvironment`).

**Comment by thaJeztah** [comment]
ah! makes sense

**Comment by dnephin** [comment]
This is why it makes more sense to do it on the server, instead of the client!
