### ISSUE TITLE
docker limited number of tcp connection

### ISSUE THREAD

**Issue by chrishaly** [docker/docker#32356]
**Description**

I have did a tcp connect test, start a tcp server in a host, and start other host run containers in containers connect to tcp server.

when total number of connections (sum all connectoin number of all containers) almost reach to 65535 (eg:  64512 just now), the other tcp connection throw exception "connection timeout".

I tried to use 3 hosts without docker to connect tcp server each 60K connections is ok, it said that the tcp server do 180K connections is ok.

**Steps to reproduce the issue:**
1. start tcp server in host A
2. start container C1 in host B
3. start 60K connection to tcp server in C1
4. start container C2 in host B
5. start 60K connection to tcp server in C2

**Describe the results you received:**

total tcp connection more less than 120K

**Describe the results you expected:**

each 60K connection in two container total 120K connection made.

**Additional information you deem important (e.g. issue happens only occasionally):**

host configurations:

in host
```
root@debian:~# ulimit -n
800000

net.ipv4.ip_local_port_range = 5000     65535
net.ipv4.tcp_mem = 8388608      12582912        16777216
net.ipv4.netfilter.ip_conntrack_max = 1000000
net.netfilter.nf_conntrack_max = 1000000
net.netfilter.nf_conntrack_count = 64515
net.nf_conntrack_max = 1000000

                   total       used       free     shared    buffers     cached
Mem:          986M       808M       178M       8.5M       5.0M       132M
-/+ buffers/cache:       670M       316M
Swap:         1.0G       872K       1.0G
```

in container
```
 ulimit -n
800000

net.ipv4.ip_local_port_range = 1024     65535
net.ipv4.netfilter.ip_conntrack_max = 1000000
net.netfilter.nf_conntrack_max = 1000000
net.netfilter.nf_conntrack_count = 6653
```

**Output of `docker version`:**

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

**Output of `docker info`:**

```
Containers: 1
Images: 15
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 17
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 986.9 MiB
Name: debian
ID: GEUG:DUKW:FDXQ:DFUP:GOI7:S4YO:GIH7:RX55:SQ6Z:ZZFQ:MEXB:2EHP
WARNING: No memory limit support
WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, physical, etc.): VMware

**Comment by cpuguy83** [comment]
Many of the kernel "sysctl" settings are namespaced in the container. You'll need to tweak these values, which you need to be privileged to do.
Later versions of Docker provide configuration options to set these so you don't have to do it while you are in the container (and thus have bypass all security).

Docker 1.6 is 2 years old now.

**Comment by chrishaly** [comment]
First, thanks for your reply.

I've tried 17.03.1-ce, got the same result.

I've suppose that caused by nf_conntrack, but I found some article said nf_conntrack is not namespaced. Are there solution to resolve this issue, I think it's not only me meet this difficult.

This issue puzzled me for some days, searched lots of post with no right answer.

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Mon Mar 27 17:07:28 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 6
 Running: 2
 Paused: 0
 Stopped: 4
Images: 15
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 27
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 986.9 MiB
Name: debian
ID: GEUG:DUKW:FDXQ:DFUP:GOI7:S4YO:GIH7:RX55:SQ6Z:ZZFQ:MEXB:2EHP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No memory limit support
WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by cpuguy83** [comment]
http://stackoverflow.com/questions/410616/increasing-the-maximum-number-of-tcp-ip-connections-in-linux

**Comment by cpuguy83** [comment]
Also, are you connecting directly to the containers or going through port forwards?

**Comment by chrishaly** [comment]
Start 3 VirtualMachine: A, B, C
Run Tcp Server in A without docker install.

for client I did 2 test.

**Test 1**
B, C without docker install.
In B and C: Run Tcp Test Client to connect TcpServer with 60K connection.
Result is: each  60K connection made success, total 120K connection made in Tcp Server (Virtual Machine A).

**Test 2**
B with docker install.
configurate ulimit, ip_local_port_range
In B host not in docker: Run Tcp Test Client to connect TcpServer with 60K connection.
after 60K connection made
In B run docker with command line "docker run -it -v /chris:/chris --privileged --ulimit nofile=800000:800000 debian2 /bin/bash", in Container Run Tcp Test Client to connect TcpServer with 60K connection, only 4.5K connection made and connection timeout exception threw.

Made changes to start 60K connection in container first, 60K connection was made success. then start 60K connection in host B (not in container), only 4.5K connection made.

**Comment by chrishaly** [comment]
**Test 3**

B with docker install.
configurate ulimit, ip_local_port_range

In B run docker to start Container1 with command line "docker run -it -v /chris:/chris --privileged --ulimit nofile=800000:800000 debian2 /bin/bash", in Container1 Run Tcp Test Client to connect TcpServer with 60K connection, 60K connection made success.

In B run docker to start Container2 with command line "docker run -it -v /chris:/chris --privileged --ulimit nofile=800000:800000 debian2 /bin/bash", in Container2 Run Tcp Test Client to connect TcpServer with 60K connection, only about 5.4K connection made and connection timeout exception threw.

all the test ip_local_port_range was setted to  net.ipv4.ip_local_port_range = 5000     65535 or net.ipv4.ip_local_port_range = 1024     65535

**Comment by cpuguy83** [comment]
What is `net.core.somaxconn` set to?
For me the default in a container is 128, but on the host it's 1024.

**Comment by chrishaly** [comment]
they are all 128 in host and container

**Comment by chrishaly** [comment]
after setted them to 1024 issue remains the same.

**Comment by 4m3ndy** [comment]
Why this issue is closed, I'm facing the same problem, I'm using nginx as reverse proxy for a phusion passenger container, I get 504 timeout error after a set of tcp connections.

Any Advices ?

**Comment by bradleyd** [comment]
I am seeing the same issue.  Any resolution?

**Comment by alexvy86** [comment]
I know this is an old and closed thread but it seems like OPs problem is that he was simply running out of outbound ports to establish connections from host B to host A? The symptoms he describes (being able to establish the first 60k from either the host or a container, and then the other one only being able to establish 5.4k additional ones) and the total of 65.4k being similar enough to 65,535, make me think that was the problem.

**Comment by omniscopy** [comment]
> Why this issue is closed, I'm facing the same problem, I'm using nginx as reverse proxy for a phusion passenger container, I get 504 timeout error after a set of tcp connections.
> 
> Any Advices ?

Hi there. Were you able to find the way of solving this issue?
