### ISSUE TITLE
17.03.x dockerd/docker hanging

### ISSUE THREAD

**Issue by CWX-iggy** [docker/docker#32363]
After upgrading to 17.03.1-1, `systemd` (i.e. `dockerd`) hangs.
`journalctl` output
```
COMMAND=/usr/bin/systemctl start docker.service
Apr 05 10:31:15 archie sudo[2721]: pam_unix(sudo:session): session opened for user root by XXXXX(uid=0)
Apr 05 10:32:18 archie systemd[1]: docker.service: State 'stop-sigterm' timed out. Killing.
Apr 05 10:32:18 archie systemd[1]: docker.service: Killing process 1914 (dockerd) with signal SIGKILL.
Apr 05 10:32:18 archie systemd[1]: docker.service: Main process exited, code=killed, status=9/KILL
Apr 05 10:32:18 archie systemd[1]: docker.service: Unit entered failed state.
Apr 05 10:32:18 archie systemd[1]: docker.service: Failed with result 'timeout'.
Apr 05 10:32:18 archie systemd[1]: Starting Docker Application Container Engine...
Apr 05 10:32:18 archie dockerd[2728]: time="2017-04-05T10:32:18.883504470+10:00" level=info msg="libcontainerd: new containerd process, pid: 2744"
Apr 05 10:32:19 archie dockerd[2728]: time="2017-04-05T10:32:19.885994777+10:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
Apr 05 10:32:19 archie dockerd[2728]: time="2017-04-05T10:32:19.894157081+10:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Apr 05 10:32:19 archie dockerd[2728]: time="2017-04-05T10:32:19.894379902+10:00" level=warning msg="Your kernel does not support cgroup rt period"
Apr 05 10:32:19 archie dockerd[2728]: time="2017-04-05T10:32:19.894398887+10:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Apr 05 10:32:19 archie dockerd[2728]: time="2017-04-05T10:32:19.894752335+10:00" level=info msg="Loading containers: start."
```
Additionally, all docker commands are also hanging.  
[strace.txt](https://github.com/docker/docker/files/894862/strace.txt)

Have tried killing the `docker.pid`, `docker.sock` and removing all docker data in `/var/lib/docker` and rebooting - with no joy. `rm -fR /var/lib/docker` was also unable to remove `overlay2` (process in use).
Downgrading to 17.03.0-1 doesn't fix the issue.
Kernel is @ 4.10.6-1-ARCH

Not sure if this is relevant, but I'm also getting MCE errors at about the same time docker stopped working.
[mcelog.txt](https://github.com/docker/docker/files/895137/mcelog.txt)

**Comment by cpuguy83** [comment]
Can you send `SIGUSR1` to the dockerd process and collect the stack dump mentioned in the logs?
The details requested in the issue template would also be extremely helpful.

Thanks!

**Comment by CWX-iggy** [comment]
[docker.log.txt](https://github.com/docker/docker/files/901366/docker.log.txt)
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------
**Description**
`systemctl start docker.service` hangs 

**Steps to reproduce the issue:**
Self explanatory

**Describe the results you received:**
Process hangs. Have to press `Ctrl-C` to exit. `journalctl -xe | grep docker` shows:
```
-- Subject: Unit docker.service has begun start-up
-- Unit docker.service has begun starting up.
Apr 06 13:14:23 archie dockerd[7143]: time="2017-04-06T13:14:23.169437821+10:00" level=info msg="libcontainerd: new containerd process, pid: 7158"
Apr 06 13:14:24 archie dockerd[7143]: time="2017-04-06T13:14:24.185133090+10:00" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Apr 06 13:14:24 archie dockerd[7143]: time="2017-04-06T13:14:24.185562981+10:00" level=warning msg="Your kernel does not support cgroup rt period"
Apr 06 13:14:24 archie dockerd[7143]: time="2017-04-06T13:14:24.185595500+10:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Apr 06 13:14:24 archie dockerd[7143]: time="2017-04-06T13:14:24.186291850+10:00" level=info msg="Loading containers: start."
```

**Describe the results you expected:**
Returns user control to command prompt.

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens consistently now. Am unable to enable the `systemd` unit as it causes the machine to hang on boot. If I create a `docker-machine`, I am able to issue all `docker` commands (e.g. `docker ps`, `docker run`, `docker info`) without it hanging. The `systemd` unit was working for about a week, up until the most recent docker and linux version bumps.

**Output of `docker version`:**
hangs

**Output of `docker info`:**
hangs

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Archlinux 4.10.8-1-ARCH
systemd 232
Dell XPS 15 9650 (2017)

**Comment by cpuguy83** [comment]
Output of `docker info` and `docker version` would also really help.
Also looks like the dump is truncated.

**Comment by CWX-iggy** [comment]
Neither command returns any output. The process just hangs there.

**Comment by cpuguy83** [comment]
🤦‍♂️ lol, of course they are.

**Comment by CWX-iggy** [comment]
docker version is `17.03.1-ce`

**Comment by cpuguy83** [comment]
Were you able to get the untrunacted stack dump?

There should be a `BEGIN` and an `END`

**Comment by CWX-iggy** [comment]
Unfortunately, `journalctl` doesn't seem to be logging it for some reason now.

**Comment by CWX-iggy** [comment]
Reinstalled Archlinux. No longer an issue.
