### ISSUE TITLE
ImagePull in golang client v17.03.1-ce fails with 'repository name must be canonical'

### ISSUE THREAD

**Issue by JorritSalverda** [docker/docker#32372]
**Description**

When trying to pull a docker image using the golang client method *ImagePull* it fails with a *repository name must be canonical* error.

The code for pulling the image follows the example at https://docs.docker.com/engine/api/ and looks like this:

```go
cli, err := client.NewEnvClient()
if err != nil {
  log.Fatal(err)
}

_, err = cli.ImagePull(context.Background(), "node:7.8.0-alpine", types.ImagePullOptions{})
if err != nil {
  log.Fatal(err)
}
```

I've brought in the following packages:

```
github.com/docker/docker/api/types@v17.03.1-ce
github.com/docker/docker/api/types/container@v17.03.1-ce
github.com/docker/docker/api/types/reference@v17.03.1-ce
github.com/docker/docker/client@v17.03.1-ce
```

The application code runs inside a privileged container running on Google Container Engine version 1.5.6. The container itself inherits from public container `docker:17.03.1-ce-dind` in which the docker daemon is started with

```
dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay2
```

Running the docker command with `exec.Command` like below works fine, so doesn't seem to be an issue with the docker daemon itself, but with the golang client library.

```go
dockerPullCmd := exec.Command("docker", "pull", "node:7.8.0-alpine")

// run and wait until completion
if err := dockerPullCmd.Run(); err != nil {
 if exiterr, ok := err.(*exec.ExitError); ok {
   if status, ok := exiterr.Sys().(syscall.WaitStatus); ok && status.ExitStatus() > 0 {
     stat.ExitCode = status.ExitStatus()
     return stat, err
   }
 } else {
   return stat, err
 }
}
```

Any ideas what's wrong? 

**docker version**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**docker info**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.21+
Operating System: Alpine Linux v3.5 (containerized)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 25.47 GiB
Name: agent-estafette-174941936-z60ks
ID: 6AUQ:7BSE:IHEG:BHOP:PSOF:3ZBT:HQYE:VUCV:JW3B:DEIR:I4SU:OGGI
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Comment by thaJeztah** [comment]
Hm, could you try if it works with `docker.io/library/node:7.8.0-alpine` ?

**Comment by JorritSalverda** [comment]
@thaJeztah that works! 

Are there any helpers in the client library that are able to determine whether it's canonical and I need to add this prefix? Or even a function that adds it if it;s missing?

**Comment by thaJeztah** [comment]
Well, looking at the moment why your original example didn't work :blush: I _do_ know there's some special handling in a couple of places for the "official" images (because, e.g. `node` is actually `library/node` on Docker Hub, so `docker.io/library/node`.

I just built docker with a small patch to debug what the docker client uses there;

```patch
diff --git a/client/image_pull.go b/client/image_pull.go
index a72b9bf7f..9d1af2264 100644
--- a/client/image_pull.go
+++ b/client/image_pull.go
@@ -7,6 +7,7 @@ import (

        "golang.org/x/net/context"

+       "fmt"
        "github.com/docker/distribution/reference"
        "github.com/docker/docker/api/types"
 )
@@ -20,6 +21,8 @@ import (
 // - if not in trusted content, ref is used to pass the whole reference, and tag is empty
 // - if in trusted content, ref is used to pass the reference name, and tag for the digest
 func (cli *Client) ImagePull(ctx context.Context, refStr string, options types.ImagePullOptions) (io.ReadCloser, error) {
+       return nil, fmt.Errorf("refStr: %s", refStr)
+
        ref, err := reference.ParseNormalizedNamed(refStr)
        if err != nil {
                return nil, err
```

Running `docker pull docker pull node:7.8.0-alpine` with that binary produces;

    refStr: node:7.8.0-alpine

So, not I'm not sure what it's expecting there. I must say that that was on "master", so let me try if the 17.03.1 tag is different there

**Comment by thaJeztah** [comment]
Hm, no building from 17.03.1 gives the same, let me try if someone else knows what could be the issue here.

**Comment by JorritSalverda** [comment]
Meanwhile I'll see if bringing in the whole `github.com/docker/docker` at version `v17.03.1-ce` might fix it. I use govendor to bring in the vendor packages, but it might not bring in references at the correct version.

**Comment by thaJeztah** [comment]
I think it's a vendoring issue; the error `repository must be canonical` was added in the distribution package that is vendored in 17.04, but wasn't yet in 17.03;

https://github.com/docker/docker/blob/v17.04.0-ce-rc2/vendor/github.com/docker/distribution/reference/reference.go#L59-L60


https://github.com/docker/docker/blob/17.03.x/vendor/github.com/docker/distribution/reference/reference.go#L38-L56

So it looks like during vendoring, it pulled the wrong version. You can find the versions we use for vendoring in https://github.com/docker/docker/blob/master/vendor.conf

And currently use this tool for vendoring; https://github.com/LK4D4/vndr

**Comment by thaJeztah** [comment]
Let me go ahead and close this issue for housekeeping, but feel free to continue the conversation; let me know if it worked out!

**Comment by JorritSalverda** [comment]
Clearing all vendor packages and re-adding it with the following command fixed my issue:

```
govendor fetch -tree github.com/docker/docker@v17.03.1-ce
```

Thanks for your help getting to the bottom of this. Let's hope the future of golang has better/easier vendoring for us in stock :)

**Comment by thaJeztah** [comment]
> Let's hope the future of golang has better/easier vendoring for us in stock :)

Yes, definitely, it can be a big PITA

Good to hear it's resolved!
