### ISSUE TITLE
AWS Cloudformation Custom VPC is not allowing correct CIDR ranges.

### ISSUE THREAD

**Issue by composer22** [docker/docker#32386]
Cloudformation script that is supposed to recognize a users VPC and subnets is not designed correctly to pick up IP ranges within these VPC and subnets.

see https://docs.docker.com/docker-for-aws/

and under . . .

> Deploy Docker Community Edition (CE) for AWS (edge) 
> uses your existing VPC

this . . .

https://editions-us-east-1.s3.amazonaws.com/aws/edge/Docker-no-vpc.tmpl

config is hardcoded on line 371 as:
```
        "VpcCidrs": {
            "pubsubnet1": {
                "cidr": "172.31.0.0/20"
            },
            "pubsubnet2": {
                "cidr": "172.31.16.0/20"
            },
            "pubsubnet3": {
                "cidr": "172.31.32.0/20"
            },
            "pubsubnet4": {
                "cidr": "172.31.48.0/20"
            },
            "vpc": {
                "cidr": "172.31.0.0/16"
            }
        }
```
yet prompts for vpc and subnets.

This need to either pick up the CIDR ranges from the subnets or allow the user to edit these variables to match.

Also doesn't allow for private subnets.  Should allow managers, workers or both to be hidden under separate private subnets.

Please forward or let me know where I can post this ticket if not here.

thanks.

**Comment by thaJeztah** [comment]
Oh, can you post this in the Docker for AWS issue tracker? That will have the right people on board 👍 

https://github.com/docker/for-aws/issues

Let me close the issue here, but feel free to continue the conversation (thanks for reporting!)
