### ISSUE TITLE
Manager in limbo state

### ISSUE THREAD

**Issue by lancemind** [docker/docker#32385]
**Description**

**Steps to reproduce the issue:**
1.  docker swarm join --token managerjointoken master:2377

**Describe the results you received:**
Host is visible in 'docker node ls' but is not listed as a manager:
```
docker node ls
ID                           HOSTNAME           STATUS  AVAILABILITY  MANAGER STATUS
80taczhfa2hyfll7px10au0qn    ip-172-31-113-85   Ready   Active
c60gaydy84caqv00f0k7t06z1    ip-172-31-113-146  Ready   Active        Reachable
hk58kc9hu42bnpc6b1r9gkxw1 *  ip-172-31-111-174  Ready   Active        Leader
iwdy3oq7im2qfdbvtot8355q1    ip-172-31-113-37   Ready   Active        Reachable
j62nxlyk1um2g80kbzzxhrhl9    ip-172-31-112-181  Ready   Active   <---- This host
lgqnkj8ey4mt5d4mugxd6diog    ip-172-31-111-36   Ready   Active
o7g8a9c9klzky6q7oa4po64aw    ip-172-31-111-44   Ready   Active        Reachable
p2wu1tz2pq8zwqqcelc72znmd    ip-172-31-112-14   Ready   Active
qi11kmml51szyshn12zqu55nk    ip-172-31-111-74   Ready   Active
ta54no3rjdanp3sma7lf7xh0e    ip-172-31-113-60   Ready   Active
```

Attempting to promote the node results in:

    docker node promote j62nxlyk1um2g80kbzzxhrhl9
    Node j62nxlyk1um2g80kbzzxhrhl9 is already a manager.

Attempting to demote the node returns:

    docker node demote j62nxlyk1um2g80kbzzxhrhl9
    Error response from daemon: rpc error: code = 5 desc = can't find manager in raft memberlist

Attempting to leave the swarm returns:
docker swarm leave
Error response from daemon: You are attempting to leave the swarm on a node that is participating as a manager. The only way to restore a swarm that has lost consensus is to reinitialize it with `--force-new-cluster`. Use `--force` to suppress this message.

**Describe the results you expected:**
A functional and healthy manager node.

**Additional information you deem important (e.g. issue happens only occasionally):**
I've had multiple node failures and this is the first time the node wasn't replaced seemlessly.

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce-rc2
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   2f35d73
 Built:        Wed Mar 29 07:52:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce-rc2
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   2f35d73
 Built:        Wed Mar 29 07:52:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.04.0-ce-rc2
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: j62nxlyk1um2g80kbzzxhrhl9
 Error: rpc error: code = 4 desc = context deadline exceeded
 Is Manager: true
 Node Address: 172.31.112.181
 Manager Addresses:
  172.31.111.174:2377
  172.31.111.44:2377
  172.31.113.146:2377
  172.31.113.37:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-66-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 7.795GiB
Name: ip-172-31-112-181
ID: XZU5:FVPB:JWCA:RATJ:WXBP:QSZM:GB5M:UDH4:6FKC:XR5Y:EAM4:HINZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: userminddeployer
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Swarm cluster running on EC2 instances.

**Comment by thaJeztah** [comment]
ping @dongluochen @aaronlehmann

**Comment by thaJeztah** [comment]
@lancemind do you have logs of both the master, and the node that's trying to join?

when you say "replacing the node", are you (e.g.) copying the `/var/lib/docker` directory from the old node to the new node before joining? Or is it a completely fresh install?

**Comment by lancemind** [comment]
By replace I mean a new EC2 instance with a clean install of docker.

Which logs do you mean?  dockerd events in syslog?

**Comment by thaJeztah** [comment]
Yes, dockerd logs; ideally in debug mode, but I assume that's not an option unless it's repeatable

**Comment by lancemind** [comment]
I've been sitting on this too long I'm afraid, the log events from the join have since rolled.  Here's the events from the machine as they are now.
[manager.txt](https://github.com/docker/docker/files/900962/manager.txt)
[master.txt](https://github.com/docker/docker/files/900961/master.txt)

**Comment by thaJeztah** [comment]
Thanks! I see some possible issues in the logs, but I'll have to defer that to the SwarmKit team, which may be better at telling if it's related.

**Comment by aaronlehmann** [comment]
If this happens again, it might be helpful to get a stack dump from the affected manager. Sending SIGUSR1 (`kill -USR1 <pid>`) to the Docker daemon causes it to dump this to disk, and log the file path.

I didn't see any obvious reason in the logs, but I see a few other bad things going on that I'm going to address.

**Comment by lancemind** [comment]
Just as an FYI I just had another manager die (gotta love AWS) and the next one successfully joined the swarm as a manager so it doesn't appear to be systemic.

**Comment by bmitch3020** [comment]
I ran into this myself today when my managers was a different version of docker (17.04 vs others at 17.03). Downgrading the one manager having issues resolved the issue.

**Comment by aluzzardi** [comment]
/cc @aaronlehmann ^^

This is an area we need much better testing.

We recommend upgrading all managers first then workers.
Upgrading managers can take as much time as needed, just don't do anything "disruptive" in between (promotions, using new features only supported by a few managers, ...).

We want to:
1) Test automatically
2) Succeed, if possible
3) Prevent you from doing things we know aren't going to work

Flagging this as testing

**Comment by bmitch3020** [comment]
FYI, during my own limbo state yesterday, the debugging logs were extremely active with the following:

```
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.262402716-06:00" level=debug msg="certificate issued" method="(*Server).signNodeCert" module=ca node.id=0v37yr6pxe9k4udpi87wpywhg node.role=MANAGER
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.275512311-06:00" level=debug msg="node certificate updated" cert.cn=0v37yr6pxe9k4udpi87wpywhg cert.role=MANAGER method=issueRenewCertificate
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.277097368-06:00" level=debug msg="certificate issued" method="(*Server).signNodeCert" module=ca node.id=0v37yr6pxe9k4udpi87wpywhg node.role=MANAGER
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.290518252-06:00" level=debug msg="node certificate updated" cert.cn=0v37yr6pxe9k4udpi87wpywhg cert.role=MANAGER method=issueRenewCertificate
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.291960437-06:00" level=debug msg="certificate issued" method="(*Server).signNodeCert" module=ca node.id=0v37yr6pxe9k4udpi87wpywhg node.role=MANAGER
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.305015867-06:00" level=debug msg="node certificate updated" cert.cn=0v37yr6pxe9k4udpi87wpywhg cert.role=MANAGER method=issueRenewCertificate
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.307501539-06:00" level=debug msg="certificate issued" method="(*Server).signNodeCert" module=ca node.id=0v37yr6pxe9k4udpi87wpywhg node.role=MANAGER
Apr 11 12:00:00 ***host2.***.*** dockerd[1479]: time="2017-04-11T12:00:00.320415584-06:00" level=debug msg="node certificate updated" cert.cn=0v37yr6pxe9k4udpi87wpywhg cert.role=MANAGER method=issueRenewCertificate
```

`***host2` is one of my existing 17.03.1 swarm masters, and `0v37yr6pxe9k4udpi87wpywhg` was the 17.04 node that was trying to join the swarm as a master.

It's possible this was also causing overlay networking issues in our swarm (some, but not all, container to container connections between two nodes were timing out). I've been trying several times today to recreate the overlay networking issues without luck, and this limbo node was the last thing changed. Perhaps the excessive thrashing triggered another race condition. If so, you may want to bump the priority on handling this scenario better and include an exponential backoff in there.

**Comment by aaronlehmann** [comment]
ping @cyli

**Comment by cyli** [comment]
The field `Role` was added to `Node` in 17.04, but was not present in 17.03.  Because the CA in this case is a 17.03 manager, it doesn't set `Node.Role`.  When the `node.go` code receives a node update from the dispatcher, it checks to see if the `Node.Role` matches its current role it thinks it is, which it never does because it will always be `WORKER`, even though the 17.03 CA thinks that the node is a manager.

**Comment by thaJeztah** [comment]
also in 17.05 branch through https://github.com/docker/docker/pull/32627
