### ISSUE TITLE
'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified.

### ISSUE THREAD

**Issue by okproject** [docker/docker#32411]
**Description**

**Steps to reproduce the issue:**
1. It is not possible to explain reproduce steps.
2.
3.

**Describe the results you received:**
Unable to start: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 'MobyLinuxVM' failed to start. (Virtual machine ID D2E07033-FBE5-44E7-AE9D-3FB958CD608A)

'MobyLinuxVM' failed to start worker process: An invalid HANDLE was specified. (0xC0000008). (Virtual machine ID D2E07033-FBE5-44E7-AE9D-3FB958CD608A)
at Start-MobyLinuxVM, <No file>: line 287
at <ScriptBlock>, <No file>: line 382
   at Docker.Backend.ContainerEngine.Linux.DoStart(Settings settings)
   at Docker.Backend.ContainerEngine.Linux.Restart(Settings settings)
   at Docker.Core.Pipe.NamedPipeServer.<>c__DisplayClass8_0.<Register>b__0(Object[] parameters)
   at Docker.Core.Pipe.NamedPipeServer.RunAction(String action, Object[] parameters)

**Describe the results you expected:**
It should be start normally

**Additional information you deem important (e.g. issue happens only occasionally):**
Everything started to happen after installed comodo internet security pro

**Output of `docker version`:**

```
Version 17.04.0-ce-win7 (10981)
Channel: edge
b598153

Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 06:06:36 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.

```

**Output of `docker info`:**

```
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.28/info: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Docker Linux on Windows 10 pro x64 on Macbookpro 2015mid  - 16gb ram , samsung ssd , i7

**Comment by friism** [comment]
@okproject can you please run diagnostics and re-open the issue here: https://github.com/docker/for-win/issues/new

**Comment by thaJeztah** [comment]
Let me close here; thanks in advance!
