### ISSUE TITLE
Error creating cluster component when using the legacy Docker Swarm

### ISSUE THREAD

**Issue by mangelov95** [docker/docker#32414]
**Description**

Hello, when I'm using Docker 17.03 and I want connect it to a swarm using the old method - using the `swarm` image and a consul KV store. I have set the options `--cluster-store` and --cluster-advertise` to my docker daemon and that way I get the error:

`Error creating cluster component: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode`

This didn't happen before, when I was using 1.12. I guess `swarm mode` in the error is talking about the new Docker Engine swarm mode, however I'm not using that at all.

**Steps to reproduce the issue:**
1. Install Docker Engine 17.03  
2. Add `cluster-store` and `cluster-advertise` options with appropriate values to the docker daemon.
3. Try to create a swarm container to connect to an existing swarm using the `join --addr` options

**Describe the results you received:**

A message in the systemd log:

`level=fatal msg="Error creating cluster component: --cluster-store and --cluster-advertise daemon configurations are incompatible with swarm mode"`

**Describe the results you expected:**

Everything to be working

**Additional information you deem important (e.g. issue happens only occasionally):**

I am installing and configuring Docker using Salt and I'm also spawning containers using Salt and docker-py.

**Output of `docker version`:**

```
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 11:02:43 2017
 OS/Arch:      linux/amd64
```

**Output of `docker info`:**

```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
Can you try starting the daemon without those options set? Even though you don't use swarm mode, it looks like it's enabled, so you'd have to `docker swarm leave --force` to disable swarm mode

Alternatively (and assuming there's nothing important running on that machine currently), you can remove the `/var/lib/docker/swarm` directory, which contains the swarm state, and dara

**Comment by mangelov95** [comment]
Yes, that worked...so even if I purge and reinstall the `docker-engine` package the swarm initiated stays active, since its config details are in a different place? I did remember that I `init`-ed a swarm before, just to try it. Thank you very much for the help!

**Comment by thaJeztah** [comment]
Correct; the `/var/lib/docker` directory is not removed when uninstalling https://docs.docker.com/engine/installation/linux/ubuntu/#uninstall-docker

Good to hear it's resolved! Let me close this issue
