### ISSUE TITLE
get.docker.com fails on Debian 8 unprivileged

### ISSUE THREAD

**Issue by tabakhase** [docker/docker#32424]
**Description**

Installing docker-engine via `curl -fsSL https://get.docker.com/ | sh` fails when run from a nonprivileged user.
`ERROR: This command can only be used by root.`

**Steps to reproduce the issue:**
1. have a fresh Debian 8
2. switch to a nonprivileged - but sudo enabled user ("debian" from openstack)
3. run `curl -fsSL https://get.docker.com/ | sh` 

**Describe the results you received:**
`ERROR: This command can only be used by root.`
from `echo "$docker_key" | apt-key add -` in 

**Describe the results you expected:**
should use sudo call as needed and succeed.

**Additional information you deem important (e.g. issue happens only occasionally):**
error exists since: https://get.docker.com/
Last-Modified:Wed, 05 Apr 2017 23:50:48 GMT

**Output of `docker version`:**

```
unable to install
```

**Output of `docker info`:**

```
unable to install
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Openstack spawned via docker-machine (0.10)

**Comment by junjuew** [comment]
I'm seeing the same problem on ubuntu as well.

**Comment by jordonbaade** [comment]
Same issue here, Ubuntu 16.04.  Totally killed my planned evening to learn Docker. :(

**Comment by thaJeztah** [comment]
@jordonbaade the recommended installation path is the manual procedure, as explained in https://docs.docker.com/engine/installation/linux/ubuntu/. The `install.sh` script is only to get you "going fast".

**Comment by achekulaev** [comment]
Why is this issue closed despite unresolved? 
Is this an official feedback that get.docker.com is not going to be officially supported going forward?

**Comment by achekulaev** [comment]
I would expect there to be auto-tests. This script is a go-to point for many.

**Comment by benjamb** [comment]
Could this be re-opened until the fix is deployed to https://get.docker.com/ ?

docker-machine (0.8.2, build e18a919, not sure about later) currently fails to provision ubuntu (and likely other) instances.

**Comment by thaJeztah** [comment]
We close issues when a fix is merged.

> I would expect there to be auto-tests. This script is a go-to point for majority.

There are automated tests in place; I'm not sure why this issue was not picked up by those; possibly they're executed as root on the test-boxes, but I cannot tell for sure

**Comment by benjamb** [comment]
Is there a place where such infrastructure issues are tracked then?  Since the issue doesn't quite fit under docker/machine (although this probably should be curl-ing the script).

It appears one has already been created for this particular problem: https://github.com/docker/machine/issues/4051

**Comment by guikcd** [comment]
This also break docker-machine.

**Comment by thaJeztah** [comment]
Oh, sorry, didn't see your comment; the script was updated on get.docker.com, but may still be in the CDN cache, so it's possible the updated version is not yet available in all locations

**Comment by jordonbaade** [comment]
Just trying to learn how to use Docker @thaJeztah -- realize there are probably more manual ways to get it taken care of, but I'd expect the official 'quick start' script to not be just completely broken and for our concerns to be brushed off.

**Comment by jordonbaade** [comment]
Just refreshed the script, additions have been added -- will test docker-machine now.

**Comment by jordonbaade** [comment]
Works!  Thanks @thaJeztah

**Comment by thaJeztah** [comment]
great!
