### ISSUE TITLE
Feature Req: docker stack deploy into API

### ISSUE THREAD

**Issue by composer22** [docker/docker#32476]
I've looked through tickets, code, google, but do not see any procedure for calling dockerd through the latest API and running a similar command as:
```
docker stack deploy -c docker-compose-stack.yml foo
```

I'd like to be able to build my own service running in a container then call the hosts docker service (if appropriate) to deploy into swarm mode. I'd like to do this without something hacky like SSHing back into the host and running a shell. That would unnecessary require additional pem and account configuration on the host.

If you know a work around or a best practice, please advise. Else this should be added as a feature to the API.

**Comment by vdemeester** [comment]
@composer22 `docker stack` is client-side for now, that's why it doesn't appear in the API.
/cc @thaJeztah @dnephin is there a roadmap issue on that ?

**Comment by thaJeztah** [comment]
Yes, this is the roadmap issue; https://github.com/docker/docker/issues/26876

Let me close  this one, so that the discussion doesn't diverge, but thanks for suggesting, @composer22
