### ISSUE TITLE
New Docker Swarm cluster will not create a service using a volume driver

### ISSUE THREAD

**Issue by kacole2** [docker/docker#32480]
**Description**

After creating a new docker swarm cluster and attempting to create a service using a volume driver, the deployment hangs. You will get a service ID in return but then sits in a pending state
indefinitely. I'm required to deploy a stateless service (as if the cluster has to initialize first) and then deploy the service using a volume driver. 

This has been tested using VirtualBox and ScaleIO environments with consistent results with REX-Ray. Using a local volume (`--mount type=volume,target=/data`) has no issues. The issue is only present when using Swarm with a volume driver and not running a normal docker container with a volume driver.

**Steps to reproduce the issue:**
1. Create new 3 new machines (this is going to be using virtualbox. This should yield same results on AWS)
```
$ docker-machine create -d virtualbox vbox01 && docker-machine create -d virtualbox vbox02 && docker-machine create -d virtualbox vbox03
```
2. When using the VirtualBox SOAP API service for the first time, disable authentication:
```
$ VBoxManage setproperty websrvauthlibrary null
```
3. Start the VirtualBox SOAP API to accept API requests from the REX-Ray service in a new terminal window:
```
$ vboxwebsrv -H 0.0.0.0 -v
```
4. Install REX-Ray as a service. If using in AWS, you can try using the [official AWS REX-Ray EBS plugin](https://hub.docker.com/r/rexray/ebs/) or continue installing as a service. 
```
$ docker-machine ssh vbox01 "curl -sSL https://dl.bintray.com/emccode/rexray/install | sh" && docker-machine ssh vbox02 "curl -sSL https://dl.bintray.com/emccode/rexray/install | sh" && docker-machine ssh vbox03 "curl -sSL https://dl.bintray.com/emccode/rexray/install | sh"
```
5. Add the REX-Ray configuration file (change REX-Ray config file if deploying to AWS as service using the [REX-Ray configuration generator](http://rexrayconfig.codedellemc.com/)) :
```
$ docker-machine ssh vbox01 "sudo tee -a /etc/rexray/config.yml << EOF
libstorage:
  service: virtualbox
  integration:
    volume:
      operations:
        mount:
          preempt: true
virtualbox:
  endpoint: http://192.168.99.1:18083
  volumePath: /Users/$USER/VirtualBox/Volumes
  controllerName: SATA"
```
```
$ docker-machine ssh vbox02 "sudo tee -a /etc/rexray/config.yml << EOF
libstorage:
  service: virtualbox
  integration:
    volume:
      operations:
        mount:
          preempt: true
virtualbox:
  endpoint: http://192.168.99.1:18083
  volumePath: /Users/$USER/VirtualBox/Volumes
  controllerName: SATA"
```
```
$ docker-machine ssh vbox03 "sudo tee -a /etc/rexray/config.yml << EOF
libstorage:
  service: virtualbox
  integration:
    volume:
      operations:
        mount:
          preempt: true
virtualbox:
  endpoint: http://192.168.99.1:18083
  volumePath: /Users/$USER/VirtualBox/Volumes
  controllerName: SATA"
```
6. Start the REX-Ray Service:
```
$ docker-machine ssh vbox01 "sudo rexray start" && docker-machine ssh vbox02 "sudo rexray start" && docker-machine ssh vbox03 "sudo rexray start"
```
7. Create the Docker Swarm Cluster
```
$ VBOX01IP=$(docker-machine ssh vbox01 "ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p' | grep 99")
$ docker-machine ssh vbox01 "docker swarm init --advertise-addr $VBOX01IP --listen-addr $VBOX01IP"
$ VBOXSWARMTOKEN=$(docker-machine ssh vbox01 "docker swarm join-token -q worker")
$ docker-machine ssh vbox02 "docker swarm join --token $VBOXSWARMTOKEN $VBOX01IP:2377" && docker-machine ssh vbox03 "docker swarm join --token $VBOXSWARMTOKEN $VBOX01IP:2377"
```
8. Precreate the volume (optional):
```
$ docker-machine ssh vbox01 "sudo rexray volume create pgdata --size=8"
```
9. Try and deploy a container requiring a volume driver:
```
$ docker service create --replicas 1 --name pg -e POSTGRES_PASSWORD=mysecretpassword \
--mount type=volume,target=/var/lib/postgresql/data,source=pgdata,volume-driver=rexray \
--constraint 'node.role == worker' postgres
```

You will get a result that never deploys to a node:
```
docker@vbox01:~$ docker service ps pg
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
n1u32wpwk3gt        pg.1                postgres:latest                         Running             Pending 38 seconds ago
docker@vbox01:~$
```

10. Remove the service and deploy a stateless service
```
docker@vbox01:~$ docker service rm pg
pg
docker@vbox01:~$ docker service create --name red --replicas 3 redis
ipcvdwlh05b01ei7jngwfbvte
docker@vbox01:~$ docker service ps red
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE            ERROR               PORTS
xpe6ptx3fdmh        red.1               redis:latest        vbox03              Running             Running 38 seconds ago
y5ub03cnckve        red.2               redis:latest        vbox01              Running             Running 13 seconds ago
asmhkc564lxv        red.3               redis:latest        vbox02              Running             Running 38 seconds ago
docker@vbox01:~$
```

11. Now remove the redis service and redploy the postgres service with a volume driver and it works.
```
docker@vbox01:~$ docker service rm red
red
docker@vbox01:~$ docker service create --replicas 1 --name pg -e POSTGRES_PASSWORD=mysecretpassword \
> --mount type=volume,target=/var/lib/postgresql/data,source=pgdata,volume-driver=rexray \
> --constraint 'node.role == worker' postgres
nwb6q66fawmmb0bc7zyq84lx7
docker@vbox01:~$ docker service ps pg
ID                  NAME                IMAGE               NODE                DESIRED STATE       CURRENT STATE           ERROR               PORTS
kelft7bf55l9        pg.1                postgres:latest     vbox03              Running             Running 3 seconds ago
```

**Describe the results you received:**

Docker Swarm is not able to create an initial service using a volume driver until a stateless service has been deployed to all hosts first.

**Describe the results you expected:**

I expect Docker Swarm to create the service using a volume driver once the swarm cluster has been created.

**Additional information you deem important (e.g. issue happens only occasionally):**

1. Refer to information in https://github.com/codedellemc/rexray/issues/781

2. I've tried enabling experimental flag in docker to see the Swarm log but there are no logs being created.  (https://github.com/docker/docker/tree/master/experimental):
```
sudo vi /etc/docker/daemon.json
{
    "experimental": true
}
```

**Output of `docker version`:**

This symptom has been seen since as far back as 1.12.1
```
docker@vbox01:~$ docker version
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:45:47 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
docker@vbox01:~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.04.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local rexray
 Network: bridge host macvlan null overlay
Swarm: active
 NodeID: lru2q97d6mivop1ctl0wv90p3
 Is Manager: true
 ClusterID: jpygx3amq2s5sxq1j5m6g8lbi
 Managers: 1
 Nodes: 3
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
 Node Address: 192.168.99.106
 Manager Addresses:
  192.168.99.106:2377
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.59-boot2docker
Operating System: Boot2Docker 17.04.0-ce (TCL 7.2); HEAD : c69677f - Thu Apr  6 16:26:16 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.8MiB
Name: vbox01
ID: ONLX:FBGF:LDZ4:FTYU:7SN6:MJ4G:JQCB:HXGN:IKAL:7K6W:SAJM:MTJL
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 157
 System Time: 2017-04-10T17:41:10.923769415Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Results are seen using VirtualBox and ScaleIO on VirtualBox and ScaleIO on VMware. Have not tested on AWS using REX-Ray.

**Comment by thaJeztah** [comment]
This is probably due to "lazy loading" of legacy (non-managed) plugins; when deploying a task, swarm looks for nodes that support the specified volume-driver, however, the volume-driver is not loaded until a volume with that driver was created on the node. Support for "managed" plugins in swarm mode is actively being worked on, and should resolve this.

/cc @anusha-ragunathan if my interpretation of the issue at hand is correct/likely 😅

**Comment by anusha-ragunathan** [comment]
@thaJeztah , your explanation is correct.

But the observation of "Docker Swarm is not able to create an initial service using a volume driver until a stateless service has been deployed to all hosts first." is incorrect. Steps 9 and 11 are identical and there's nothing that a stateless service deployment does to plugin discovery.

Is there a volume on `vbox03` created using this driver, after the initial service creation? That would trigger the lazy load of the plugin and explain why the service creation succeeds the second time around.

**Comment by kacole2** [comment]
@anusha-ragunathan @thaJeztah 
yes, steps 9 and 11 are identical. It shows that trying to do it in step 9 fails. step 10 deploys as service without a volume driver. then try to do it once again in step 11 and it succeeds. 

REX-Ray is talking to a backend storage platform (whether it's AWS EBS Volumes, ScaleIO Volumes, VirtualBox Media, etc). The volumes ARE NOT being created on the nodes themselves. We are talking about centralized storage.

**Comment by kacole2** [comment]
I can confirm this issue is not present when using the managed plugin. only legacy plugins.

**Comment by anusha-ragunathan** [comment]
@kacole2 : I think the reason step 10 matters in this case, is because the `redis` image creates a volume called `/data`. Deploying such a service indirectly results in probing all drivers which activates the plugin and hence step 11 succeeds. If you tried deploying a `busybox` service in step 10, I think step 11 would continue to not deploy the service.

**Comment by anusha-ragunathan** [comment]
Close issue, since this behavior is expected of v1plugins.
