### ISSUE TITLE
iso squashfs unpack.

### ISSUE THREAD

**Issue by necrose99** [docker/docker#32494]
From scratch
some url .... rootfs.squashfile  / 
(at tar.gz , tar.xz , etc unpacks)  however no dice on squashfiles, on dockerhub;  for the moment requires conversion. 
then dropbox or etc, then dockerhub.  

unsquashfs -f -d *.squashfs | tar -cvpJf backup.tar.xz --exclude=~/rootfs.tar.xz --one-file-system ~/ 
Not sure it'd work but point made.  normally I dump to/tmp/isoname/  and repack , 

 unpack a squashfile to / insted of the bother of converting. 
however I'll suffer the conversion .. for now...   drop to dropbox /dockerhub  , just would be a plus 

**Option for Squashfs files to be treated like tarballs would be a plus.** 

other future state possible ? 
From ISOFILE 
ISOURL="" 
squashfs="my.squashfile  @ > / 
#### Unpack squashfs from iso to root discard rest. 
also might be a plus. for rebaking iso's .. custom respins etc.

**Comment by AkihiroSuda** [comment]
Is this a question? feature request? issue report?

**Comment by necrose99** [comment]
it would be a plus to use a _squashfs file_ as a **_supported  archive_** , it would be a future  feature enhancement request. 

just was noting I tested on dockerhub , still have to convert to standard tar.xz , gz etc ...

**Comment by cpuguy83** [comment]
Really 👎 Adding adding support for another compression format. Supporting `xz` is already really bad since we have to exec out to do it.

**Comment by thaJeztah** [comment]
I have to agree with @cpuguy83 here; we can't support every compression format that exists

I'll go ahead and close this issue, but feel free to discuss
