### ISSUE TITLE
Docker tag <sha256> no longer works in 17.04.0-ce

### ISSUE THREAD

**Issue by samuraisam** [docker/docker#32517]
**Description**

Pull request [21002](https://github.com/docker/docker/pull/21002) seems to have regressed in 17.04.0-ce

**Steps to reproduce the issue:**

Using docker 17.03.1 running `docker tag <sha256> <tagname>` works as expected and tags the repository.

Using docker 17.04.0-ce running `docker tag <sha256> <tagname>` results in the following:

```
docker: Invalid repository name (97ed62d4dc30d1f53b903dac1e90c8fee4a77a30f0099b42f34f67cb5b17018c), cannot specify 64-byte hexadecimal strings.
```

Once I rolled back to 17.03.1 it worked as expected.

**Docker version**

Docker version is 17.04.0-ce on ubuntu-trusty

**Comment by thaJeztah** [comment]
ping @dmcgowan @aaronlehmann PTAL
