### ISSUE TITLE
API: expose `docker cp` option: `--follow-link`

### ISSUE THREAD

**Issue by elgalu** [docker/docker#32535]
#### Docker API

Expose or document `docker cp` option: [--follow-link](https://github.com/docker/docker/blob/40dbbd3f9b631a0745e596072675729018378a75/docs/reference/commandline/cp.md#cp)

To be used by the [Java docker client](https://github.com/spotify/docker-client/issues/720#issuecomment-293340950)

**Comment by cpuguy83** [comment]
This looks like a client side feature that would need to be implemented by your client. Note this is not part of the docker client library, but rather the CL which wraps the client library.

It does not look appropriate to have in the API.

**Comment by elgalu** [comment]
I see. Ping @johnflavin
