### ISSUE TITLE
How to configure/run single service/container on a node

### ISSUE THREAD

**Issue by tommyz0123** [docker/docker#32568]
How can one configure a node to run a single service/container?  For performance reasons, we want to run a single container in a node in the swarm.  Is this possible?

**Comment by cpuguy83** [comment]
Hello,

This is not really the best place to ask questions like this since this is our issue tracker.
#docker on IRC, the community slack, or forums.docker.com would be much more suitable.

That said I'm not sure I understand the question.

Closing since this is not an issue.
