### ISSUE TITLE
Docker daemon is not running after upgrading to linux-4.10

### ISSUE THREAD

**Issue by juncgu** [docker/docker#32560]
Hi, 

My ubuntu machine was previously with linux-3.13.0.  Docker worked well at that time.
Recently, I upgraded the kernel to 4.10, and reinstalled Docker following (https://docs.docker.com/engine/installation/linux/ubuntu/). 

However, it always reports "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?" when I execute Docker commands.

Also, I tried "sudo serivce docker stop;  sudo service docker start", and 
"sudo rm -rf /var/lib/docker/aufs; sudo service docker start". They didn't work.

Can anyone give any hints? Thank you.

**Comment by cpuguy83** [comment]
What's in the docker logs? Note 4.10 is very new. I'd recommend sticking with 4.9, which is what we use for docker4mac/docker4windows.

**Comment by juncgu** [comment]
Thanks.
I can't execute "docker logs" (also ""Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?").

I try to start Docker daemon with "nohup dockerd -H unix:///var/run/docker.sock". 
But getting the following errors:
time="2017-04-12T08:54:05.161010040-06:00" level=info msg="libcontainerd: new containerd process, pid: 19166"
time="2017-04-12T08:54:05.186308966-06:00" level=warning msg="containerd: low RLIMIT_NOFILE changing to max" current=1024 max=4096
time="2017-04-12T08:54:06.165517296-06:00" level=error msg="[graphdriver] prior storage driver aufs failed: driver not supported"
Error starting daemon: error initializing graphdriver: driver not supported

**Comment by cpuguy83** [comment]
> Error starting daemon: error initializing graphdriver: driver not supported

Presumably this is because you were using AUFS before the upgrade and now you don't have the kernel module loaded.

I'm going to go ahead and close because it doesn't look like a real issue, but feel free to discuss (or transfer to slack!).
Thanks!
