### ISSUE TITLE
how can i run a command on docker container by using docker engin api in go lang?

### ISSUE THREAD

**Issue by luoyunpeng** [docker/docker#32592]
Hi, docker,
  i just learn go lang for a little time, and i want to manager docker contianer in go lang, i have create and start docker container with go successfully, but when i want to execute a command on this container like "docker exec .......", refer to https://github.com/docker/docker/blob/master/client/container_exec_test.go, i always got error, and i still can not find the solution.

could you show me the demo?
Thanks,
Elliot

**Comment by qq690388648** [comment]
Can you show your code and the error message you got?

**Comment by luoyunpeng** [comment]
Thanks for reponse, i just try a lot times in different way, and it works, it can execute the cmd in container, code as following
####
execResponse,err := dockerClient.ContainerExecCreate(context.Background(), containerName ,types.ExecConfig{User: "root",Cmd: []string{cmd,ip+"  ",containerName },Privileged: true})

	if err!=nil {
		panic(err)
	}

	dockerClient.ContainerExecStart(context.Background(),execResponse.ID,types.ExecStartCheck{Detach: true, Tty:false})
####
if you have bette idea, please share with me,
Thanks again,
