### ISSUE TITLE
incremental mkdir command not working in dockerfile

### ISSUE THREAD

**Issue by jvmauricio** [docker/docker#32593]
bash command mkdir incremental command not working in dockerfile.

**Steps to reproduce the issue:**

1. Create docker file with `RUN mkdir -p /path/to/dir/dirname{1..8}`
2. Run Dockerfile

**Describe the results you received:**

SSH inside container and check that the dirname1 - 8 is not generated but the directory "dirname{1..8}" is.

**Describe the results you expected:**

"dirname1" - "dirname8" will be created

**Additional information you deem important (e.g. issue happens only occasionally):**

running command `mkdir -p /path/to/dir/dirname{1..8}` inside container creates the directories as expected. 

**Output of `docker version`:**

```
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Mon Apr  3 18:07:42 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Output of `docker info`:**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 12
Server Version: 17.04.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: 
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-64-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 990.6MiB
Name: ip-172-31-3-246
ID: CEKV:HRHQ:GDY4:J4FA:LHIM:AWB7:LXSM:QCLD:WAFB:IQYB:RHQ3:BJSA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: jvmauricio
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

tested on running on EC2 freetier t2.micro instance with ubuntu-xenial-16.04-amd64-server-20170221 (ami-16efb076) OS.

**Comment by qq690388648** [comment]
I thought it depends on the image you used, what's image you used?

**Comment by jvmauricio** [comment]
> I thought it depends on the image you used, what's image you used?

I used ubuntu:trusty for my base image.

**Comment by qq690388648** [comment]
OK, I tried ubuntu:trusty image and get the same result with you, but when used the centos:latest image, the directory "dirname1" - "dirname8" was created successfully.

**Comment by jvmauricio** [comment]
@qq690388648 thanks for testing. I haven't tried building it with other images.  will this be an issue on Docker or the image?

**Comment by qq690388648** [comment]
I find it's the difference between `bash` and `sh`, so you can write the Dockerfile as `RUN /bin/bash -c "mkdir -p /path/to/dir/dirname{1..8}"` to get the result you want.
Thanks @CodeJuan https://github.com/CodeJuan

**Comment by AkihiroSuda** [comment]
closing, this is expected behavior
