### ISSUE TITLE
privilege escalation when starting the daemon with user namespaces enabled

### ISSUE THREAD

**Issue by HamidEDD** [docker/docker#32624]
**Description**

My Docker daemon is running under user-namespace (--userns-remap default:default) in order avoid container creation with root privileges or using the host netns,pid or even preventing the use of "--privileged" params when creating containers.
After several tests, I realized that  a simple user can get around that, and then start a cotnainer with all privileges.

**Steps to reproduce the issue:**
1. dockerd -D --userns-remap default:default
2. docker run -itd  --privileged --userns=host --pid=host  --network=host ubuntu bash
3. tada !! I'm root I can do everything on the host ! 

**Describe the results you received:**
Docker create a container with all privileges 

**Describe the results you expected:**
When we ask docker daemon to run containers under user-namspace mode.  --userns=host must be incompatible exactely like --privileged,--pid=host ,--network=host  in this mode. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.03.1-ce
 API version:  1.27 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Fri Mar 24 00:45:26 2017
 OS/Arch:      linux/amd64
 Experimental: false

```

**Output of `docker info`:**

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/100000.100000/aufs
 Backing Filesystem: extfs
 Dirs: 7
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
 userns
Kernel Version: 4.4.0-72-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: gateway
ID: MGZZ:SBTP:AY6M:L4B4:LTMJ:PD4K:IXCF:HUYZ:LXUI:Q4K5:N2IY:XAKR
Docker Root Dir: /var/lib/docker/100000.100000
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by thaJeztah** [comment]
User namespaces is a feature you set on the _container_ and prevents that _container_ from running as root on the host, but doesn't protect you from someone having access to the remote API to do other things. Anyone with access to the remote API effectively has _root_ permissions on the host that the docker daemon runs on, see [Docker daemon attack surface](https://docs.docker.com/v1.13/engine/security/security/#docker-daemon-attack-surface)

To implement more fine-grained control over what actions are allowed over the remote API, you can consider implementing an [authorization plugin](https://docs.docker.com/v1.13/engine/extend/plugins_authorization/)

Given that this is not a bug, I'm closing this issue, but feel free to continue the discussion.

Also if you've found or suspect a security issue in docker, please disclose responsibly, as described in the contributing.md; https://github.com/docker/docker/blob/v17.04.0-ce/CONTRIBUTING.md#reporting-security-issues

**Comment by nicdesousa** [comment]
As per @thaJeztah's suggestion:
[https://github.com/nicdesousa/docker-userns-enforcement-plugin](https://github.com/nicdesousa/docker-userns-enforcement-plugin) provides a simple authorization plugin that denies the use of `--userns=host`.
