### ISSUE TITLE
Don't see gateway IP address when running docker network inspect bridge

### ISSUE THREAD

**Issue by anandg112** [docker/docker#32648]
**Description**
Hello there, I am trying to get the IP address of a gateway by running the "docker network inspect bridge" command but I don't see anything below 'subnet'

**Steps to reproduce the issue:**
1. Run "docker network inspect bridge" command
2.
3.

**Describe the results you received:**
[
    {
        "Name": "bridge",
        "Id": "44dfd92f714ecbdbe43b5be65ec351ac9d0b654b25867ffcec64bc5b5ec373f9",
        "Created": "2017-04-14T18:09:33.797105171Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.17.0.0/16"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Containers": {
            "13a890eabf78dd47606d7b885f642931cb37c83fe15bbd144b0a304d5442b75e": {
                "Name": "node-db",
                "EndpointID": "153acb81cbbf462f3e83880d79293c3338effe419c9ec95ed04400ddd07fa6a3",
                "MacAddress": "02:42:ac:11:00:03",
                "IPv4Address": "172.17.0.3/16",
                "IPv6Address": ""
            },
            "e601f474e13e8d15e6f95bdf8693e27a7c5810023459263e065d52dd3e543325": {
                "Name": "node-app",
                "EndpointID": "13a47573150bbc43e062812c5e4449ca65e8fc1e45b9536523aa08622610ae08",
                "MacAddress": "02:42:ac:11:00:02",
                "IPv4Address": "172.17.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {
            "com.docker.network.bridge.default_bridge": "true",
            "com.docker.network.bridge.enable_icc": "true",
            "com.docker.network.bridge.enable_ip_masquerade": "true",
            "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0",
            "com.docker.network.bridge.name": "docker0",
            "com.docker.network.driver.mtu": "1500"
        },
        "Labels": {}
    }
]

**Describe the results you expected:**

I would like to receive the IP address of gateway but currently it is not there.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by schmichael** [comment]
Why was this closed? 17.09.0-ce is missing the `Gateway` field while `17.05.0-ce` and `17.06.2-ce` both have it.
