### ISSUE TITLE
docker doesn't free up host spaces while building containers

### ISSUE THREAD

**Issue by jiaofan** [docker/docker#32664]
**Description**
Docker doesn't free up host spaces while building containers

**Steps to reproduce the issue:**
1. modify Dockerfile
2.building docker image for 5-10 times
3.test docker image

**Describe the results you received:**
Filesystem              1K-blocks     Used Available Use% Mounted on
/dev/mapper/centos-root  52403200 52220604    182596 100% /
devtmpfs                  8114176        0   8114176   0% /dev
tmpfs                     8002632        0   8002632   0% /dev/shm
tmpfs                     8002632     9220   7993412   1% /run
tmpfs                     8002632        0   8002632   0% /sys/fs/cgroup
/dev/mapper/centos-home 253443164    33256 253409908   1% /opt
/dev/xvda1                 508588   160624    347964  32% /boot
tmpfs                     1600528        0   1600528   0% /run/user/1003
overlay                  52403200 52220604    182596 100% /var/lib/docker/overlay/e6fae59c059d5bba3152790192799addb60b917f53e30a6a6199fd3132dc4a12/merged
shm                         65536        0     65536   0% /var/lib/docker/containers/d764f666a2f77b47d4aea5b5777a057b81d1ce0f5a0f0c2885991a562c0d0376/shm

============================
[INFO] Building zip: /var/tmp/sdnfw-parent/distribute/target/distribute-4.2.1-SNAPSHOT.zip
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] sdnfw-parent ....................................... SUCCESS [  1.873 s]
[INFO] sdnfw-distribute ................................... FAILURE [01:36 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:41 min
[INFO] Finished at: 2017-04-15T00:00:46+00:00
[INFO] Final Memory: 25M/514M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.4:single (default-assembly) on project distribute: Failed to create assembly: Error creating assembly archive zip: IOException when zipping virtuoranc/nsjava/jre/lib/amd64/libprism_sw.so: No space left on device -> [Help 1]
[ERROR]

**Describe the results you expected:**
The build process has been used for our non-docker environment for a couple of years.
The expected is everything is built successfully.

**Additional information you deem important (e.g. issue happens only occasionally):**
Host OS is CentOS 7.2:
Linux u445.nms.fnc.fujitsu.com 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

It appears the large amount of docker files are hidden as my script
#!/bin/sh

filename='bigfiles'
find / -maxdepth 6 -type f -size +100M > $filename
count=`cat bigfiles | wc -l`

if [ $? -ne 0 ]
then
  date >> $filename
fi

only found 2:

/proc/kcore
/usr/lib/locale/locale-archive

**Output of `docker version`:**
Client:
 Version:      17.04.0-ce
 API version:  1.28
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:55:10 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.04.0-ce
 API version:  1.28 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   4845c56
 Built:        Wed Apr  5 18:55:10 2017
 OS/Arch:      linux/amd64
 Experimental: false

```
(paste your output here)
```

**Output of `docker info`:**
[fjiao@u445 /]$ docker info
Containers: 51
 Running: 0
 Paused: 0
 Stopped: 51
Images: 0
Server Version: 17.04.0-ce
Storage Driver: overlay
 Backing Filesystem: xfs
 Supports d_type: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary:
containerd version: 422e31ce907fd9c3833a38d7b8fdd023e5a76e73
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-327.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.26GiB
Name: u445.nms.fnc.fujitsu.com
ID: RD2J:CQK2:YAKV:ZTZI:CMBC:VAH3:NIJL:EX33:VPCQ:LWWW:OPV3:BS3N
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 22
 System Time: 2017-04-17T07:08:44.18719033-07:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: overlay: the backing xfs filesystem is formatted without d_type support, which leads to incorrect behavior.
         Reformat the filesystem with ftype=1 to enable d_type support.
         Running without d_type support will not be supported in future releases.
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by jiaofan** [comment]
docker ps --all showed me a lot of exited containers

**Comment by thaJeztah** [comment]
You can easily cleanup those containers with `docker container prune` (and related, `docker system prune`)
