### ISSUE TITLE
Machine stuck in iowait using device mapper

### ISSUE THREAD

**Issue by pwaller** [docker/docker#3280]
I've made a public container called `scraperwiki/go` using [`hack/dind`](https://github.com/dotcloud/docker/blob/master/hack/dind) and the principles in [this `Dockerfile`](https://github.com/jpetazzo/dind/blob/master/Dockerfile).

The image works on my local machine. It does not work on EC2, I get the behaviour described below. The main difference I'm aware of is that my local machine has AUFS installed where EC2 does not.

I get a prompt by running `docker run -t -i -privileged scraperwiki/go dind bash`.

When I try to start `docker -d &`, I get the following output, then nothing:

```
[/var/lib/docker|2621c420] +job initapi()
[/var/lib/docker|2621c420.initapi()] Creating server
```

If I subsequently try to use it, it freezes. The whole machine goes into 100% IO wait for longer than 5 minutes. I observe a `mkfs.ext4` running, and if I `strace` it (and wait long enough), I observe:

```
lseek(3, 4508418048, SEEK_SET)          = 4508418048
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 
32768) = 32768
lseek(3, 4508450816, SEEK_SET)          = 4508450816
write(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 
32768
```

And nothing more, just those two lines. I've waited ten minutes and nothing more has appeared. If I try to run anything (e.g, "ps aux") inside the `dind` container, it freezes.

After all of the above, the host machine has 1.4GB of free disk space.

/cc @jpetazzo

**Comment by testn** [comment]
I still see the issue. Building a docker image on RHEL is much slower than one on Ubuntu due to device mapper.

**Comment by crosbymichael** [comment]
Lets close this for now as the comments above and if anyone is still having the issue please open a new report with your specific problem and configuration.

**Comment by fiorix** [comment]
I'm still having this problem using device mapper on kvm virtual machines, it's running very slow. By looking at the current master branch I see `lazy_itable_init=0` (mentioned by @djmaze) is still in the code:

    docker $ grep -ri lazy_itable_init=0 *
    daemon/graphdriver/devmapper/deviceset.go:		err = exec.Command("mkfs.ext4", append([]string{"-E", "nodiscard,lazy_itable_init=0,lazy_journal_init=0"}, args...)...).Run()
    daemon/graphdriver/devmapper/deviceset.go:			err = exec.Command("mkfs.ext4", append([]string{"-E", "nodiscard,lazy_itable_init=0"}, args...)...).Run()
