### ISSUE TITLE
User defined layer mount options

### ISSUE THREAD

**Issue by bodenr** [docker/docker#3433]
I'm trying to dockerize an application which requires direct I/O support (```O_DIRECT``` on the ```open()``` sys call) via docker aufs storage driver. Based on the ubuntu aufs docs (http://manpages.ubuntu.com/manpages/precise/man5/aufs.5.html) it appears aufs should (some strings attached) support this by using the ```dio``` mount option.

However based a lil docker code inspection it does not appear there is anyway to specify additional fs layer mount options for container --- correct?

Has there been any discussion on supporting additional user mount options for layers?

For example supporting an option to pass in additional mount ops with the docker ```run``` command so I could do something like this: ```docker run -s=dio...```

FYI -- Here's the strace snip from my dockerized app failing on ```open()``` for direct I/O:
```
open("/sapmnt/data/mnt00001/hdb00001/datavolume_0000.dat", O_RDWR|O_DIRECT) = -1 EINVAL (Invalid argument)
```

**Comment by cpuguy83** [comment]
So dio support was added here: #10534
Closing since this seems to be what you were really getting at in your issue.

If the mentioned PR does not fully resolve the issue, please ping here so we can look at addressing it.  Thanks!
