### ISSUE TITLE
Dockerfiles and shell behavior

### ISSUE THREAD

**Issue by jamtur01** [docker/docker#3466]
There are currently two syntaxes for ``CMD`` and ``ENTRYPOINT`` (ignoring the interactions between the two instructions like passing options from ``CMD`` to ``ENTRYPOINT``).

1. The exec format (JSON-style):

```
CMD ["executable", "flag" ]
```

2. The shell format

```
CMD /bin/true flag
```

Having both behaviors is confusing and unintuitive. We should settle on a single behavior preferably by having a lexer that recognizes and can parse appropriate shell commands and their flags from a variety of shells in either instruction.

As part of implementing this lexer we should deprecate existing behaviors carefully as this is a large breaking change. I'd suggest:

1. Major release with new syntax generates deprecation warning if old syntax is used.
2. Next major release removes old syntax and throws error message if used.

c.f. #1149 #2266

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
