### ISSUE TITLE
VOLUME ownership behavior is unstable

### ISSUE THREAD

**Issue by yss44** [docker/docker#3484]
VOLUME ownership behavior is unstable when build with Dockerfile.
Here is my tests.

Test1

Dockerfile
```
FROM base
MAINTAINER yss44

VOLUME ["/data"]

CMD ["/bin/bash"]
```
Result
```
$ docker build -t yss44/volumetest .
$ docker run -t -i yss44/volumetest
root@995d3546f0f3:/# ls -la /data
total 8
drwx------  2 root root 4096 Jan  7 15:12 .
drwxr-xr-x 39 root root 4096 Jan  7 15:12 ..
```

```
$ docker run -t -i -v /data yss44/volumetest
root@bf43f2bc7fb2:/# ls -la /data
total 8
drwx------  2 root root 4096 Jan  7 15:16 .
drwxr-xr-x 39 root root 4096 Jan  7 15:16 ..
```

These tests are the save behavior,but last one something wrong.

```
$ mkdir `pwd`/data
$ docker run -t -i -v `pwd`/data:/data yoshiso/testv
root@5d4cf9da211a:/# ls -la /data
total 4
drwxr-xr-x  1 1000 1000   68 Jan  7 15:17 .
drwxr-xr-x 39 root root 4096 Jan  7 15:18 ..
```

##Test2

Changing volume directory owner in Dockerfile.

Dockerfile
```
FROM base
MAINTAINER yss44

VOLUME ["/data"]

RUN useradd yss44
RUN chown yss44 /data

CMD ["/bin/bash"]
```
Result
```
$ docker run -i -t yss44/volumetest2
root@d49889465052:/# ls -la /data
total 8
drwx------  2 root root 4096 Jan  7 15:20 .
drwxr-xr-x 45 root root 4096 Jan  7 15:20 ..
```

```
$ docker run -i -t -v /data yss44/volumetest2
root@3868c798966b:/# ls -la /data
total 8
drwx------  2 root root 4096 Jan  7 15:22 .
drwxr-xr-x 45 root root 4096 Jan  7 15:22 ..
```

These tests are also the same behavior, but last test behaves different.

```
$ docker run -i -t -v `pwd`/data:/data yss44/volumetest2
root@77a811695a0c:/# ls -la /data
total 4
drwxr-xr-x  1 yss44 yss44   68 Jan  7 15:17 .
drwxr-xr-x 45 root  root  4096 Jan  7 15:22 ..
```

Which behavior is correct?

Environment

Host OS
Ubuntu 12.04

$ docker version

    Client version: 0.7.3
    Go version (client): go1.2
    Git commit (client): 8502ad4
    Server version: 0.7.3
    Git commit (server): 8502ad4
    Go version (server): go1.2
    docker infoLast stable version: 0.7.3

$ docker info

    Containers: 56
    Images: 257
    Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Dirs: 369
    Username: yoshiso
    Registry: [https://index.docker.io/v1/]
    WARNING: No swap limit support

**Comment by jfrazelle** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
This is a dup for sure...

#8647 #3639
