### ISSUE TITLE
configurable Ctrl-p+Ctrl+q

### ISSUE THREAD

**Issue by avilella** [docker/docker#3519]
Feature request:

Configurable keyboard shortcuts:

http://stackoverflow.com/a/20863838/719016

**Comment by lichuan** [comment]
+1 I use emacs , but I must type ctrl-p twice!!!!!!!!!!!!!!!!!!!! +1 +1 +1

**Comment by cadina** [comment]
+1 from emacs user

**Comment by sobolews** [comment]
+1 for emacs and bash

**Comment by thmttch** [comment]
+1

Please make this configurable! It very painfully captures standard screen keys, and requires a full custom docker binary to change.

**Comment by danil** [comment]
+1 emacs rocks

**Comment by lowlifer** [comment]
+1 seriously!!

**Comment by Jason-Green-Aver** [comment]
+1 Even setting aside my love of emacs, once you've learned ctrl-p within bash, you never want to use the up arrow again.

**Comment by jisqyv** [comment]
+1 This is getting annoying!

**Comment by pielgrzym** [comment]
+1 - default keybinding are making docker attach a horrible experience.

**Comment by jamespharaoh** [comment]
+1 this is super annoying, i use ctrl+p all the time

**Comment by voobscout** [comment]
+1

**Comment by cathay4t** [comment]
+1

**Comment by elanelango** [comment]
+1

**Comment by cadejscroggins** [comment]
+1

**Comment by serbaut** [comment]
+1

**Comment by jimlar** [comment]
+1

**Comment by msteffen** [comment]
+1, though my roommate just asked: "Why don't you just run an ssh server in the docker container, and then ssh in with a real shell and use that?"

I haven't tried it, but for those trying to develop with emacs inside a docker container, this might work.

**Comment by k-bx** [comment]
Yes, ssh would definitely work.

**Comment by trogdoro** [comment]
+1

**Comment by laijs** [comment]
+1

**Comment by crquan** [comment]
:+1:

**Comment by aromatt** [comment]
+1

**Comment by k-bx** [comment]
@GordonTheTurtle the purpose of writing +1 is to notify authors that this feature is highly desired. We all feel uncomfortable to write these +1 button, but we have no other option.

If you want to help us having a better way to vote, please go to https://github.com/isaacs/github/issues/9 and write your +1 there.

**Comment by filcuc** [comment]
+1 emacs experience is broken

**Comment by askb** [comment]
+1 I use ctrl+q all the time to exit from an app or terminal.

**Comment by moul** [comment]
:+1:

**Comment by diwo** [comment]
Please *STOP* bumping this issue if you have nothing to contribute to the discussion. Each time a person +1 this issue, dozens of people get notified via email. Thank you.

**Comment by crquan** [comment]
no, I'd like to express the pressure that there should be a solution; this #3519 was open since Jan 2014 and actually the issue exists even earlier than that, and is still bothering me everyday, so bad experience of Double Ctrl-P for a previous command in bash

@diwo if you don't like you have an option to opt out this thread. I am going to put my +1 again, till someday Docker can have a solution for this.

**Comment by trogdoro** [comment]
I agree - IMO the more people that bump this the better. It seems like a
simple thing for them to implement, to make this key configurable. They've
done a ton of great work on improving the client, implementing much more
sophisticated fixes. Seems like we just need to get this sufficiently on
their radar.

--Craig

**Comment by vdemeester** [comment]
Note that there is an actual PR on that : #15666.

**Comment by tobami** [comment]
+1. My co-workers are crying me a river because of this. It would make their Docker-lifes so much better to get them Ctrl-P back!

**Comment by matelakat** [comment]
+1

**Comment by gergpetr** [comment]
+1 .. it would be a great to have feature.

**Comment by vdemeester** [comment]
@matelakat @gergpetr #15666 is in code-review so, hopefully it will land into 1.10 :wink:

**Comment by k-bx** [comment]
@vdemeester thanks for PR. windows test is failing btw

**Comment by ryerh** [comment]
+1 for vim/ctrlp plugin

**Comment by abraithwaite** [comment]
Please do this.

**Comment by thaJeztah** [comment]
@abraithwaite if you took two minutes to actually look, you'd have seen that  this issue is closed, and that  https://github.com/moby/moby/pull/15666 implemented this more than a year ago; did you _try_ before commenting?

**Comment by abraithwaite** [comment]
My bad!  I saw the green "New Issue" button to the right at the top and got confused.

Apologies for wasting your time.
