### ISSUE TITLE
ADD caching and git clones

### ISSUE THREAD

**Issue by microadam** [docker/docker#3556]
Hello,

ADD caching is not working quite how I would expect.

If I clone a git repo containing a Docker file which has an ADD command of a single file and do 'docker build .' then the image is built and caches are primed.

Subsequent runs of 'docker build .' always use the cache like I would expect them to.

However, if I clone the exact same repo on the same machine using the same instance of docker (but obviously into a different location), and then run 'docker build .' then my ADD cache is NOT used. All other caches are (RUN etc).

My test case is the following:

```
cd ~
git clone git@github.com:microadam/docker-node-hello.git one
cd one
docker build .
docker build .
cd ..
git clone git@github.com:microadam/docker-node-hello.git two
cd two
docker build .

```

Is this intended behaviour?

**Comment by exocom** [comment]
Just ran into this while setting up drone CI. It would be nice if the cache feature would just look at a hash of the blob data and not time stamps. Is there any reason for not using just a hash? 

@microadam - Thank you so much for your post! I had actually read that when I initially setting up my CI, but I missed the section about the cache breaking with a fresh clone. I've added your bash script for setting the timestamp on package.json and I am now enjoying super speedy builds!

**Comment by jfrazelle** [comment]
closing see https://github.com/docker/docker/issues/3556#issuecomment-63250410

**Comment by duglin** [comment]
FYI there are other issues out there asking for ways to tell Docker to include (or to exclusively use) the mtime (e.g. https://github.com/docker/docker/issues/4351 ) keep an eye on those....
