### ISSUE TITLE
add -add flag to docker run

### ISSUE THREAD

**Issue by proppy** [docker/docker#3578]
It would be nice to have a new flag to allow adding a file (not mounting) inside the container before running it.

This could deprecate the `insert` command that is weirdly limited to URL and bring the CLI experience in line what what you can do in a `Dockerfile`

**Comment by jfrazelle** [comment]
@proppy hiiii! is this still relevant? do you think we still need it :)

**Comment by proppy** [comment]
@jfrazelle yes, there is still no clean way to add a set of files to a container and commit from the CLI/API, w/o a Dockerfile or messing with stdin.

**Comment by duglin** [comment]
@proppy is it ok if we close this with the assumption that #13171 will solve your issue?

**Comment by proppy** [comment]
Sure.

**Comment by duglin** [comment]
thanks!
