### ISSUE TITLE
Documentation about how to setup "daemon startup parameters" nonexistent

### ISSUE THREAD

**Issue by tianon** [docker/docker#3630]
Each init system has a slightly different way to setup the "default flags" for the Docker daemon.  For example, OpenRC (Gentoo) uses "/etc/conf.d/docker", while Upstart/SysV (Ubuntu/Debian) uses "/etc/default/docker", and systemd prefers you copy the unit scripts.

This need is prompted by getting now two separate PRs to add a "configuration file" for the systemd unit file from people looking to just modify the daemon startup arguments (which upstream systemd does not recommend doing, as described well in those threads): #3307 and #3627.  There are some good links and good suggestions in each that ought to be added to a section somewhere, and I'd propose it just be a general section about "Configuring Daemon Startup Flags" or something like that, and leave it as an exercise to the reader to figure out which system they're using, perhaps also mentioning the most common system for our supported platform (Ubuntu), and any others that are similarly obvious (like OpenRC being for Gentoo), where for systemd, all bets are off on which distro (since it's available in so many as an option or even as the default).

**Comment by jfrazelle** [comment]
Just making sure, this hasn't been done yet right @SvenDowideit @tianon

**Comment by tianon** [comment]
Correct.

**Comment by tianon** [comment]
@thaJeztah this one is pretty much covered now, especially with some of the newer articles, right?

**Comment by thaJeztah** [comment]
@tianon absolutely! Thanks for the reminder :)

**Comment by arthurlogilab** [comment]
@tianon could you reference the "newer articles" here ? For those facing the same problem ?

**Comment by arthurlogilab** [comment]
where is the fix for this issue ?

**Comment by vdemeester** [comment]
@arthurlogilab I think @tianon reference, at least, this one https://docs.docker.com/engine/articles/systemd/

**Comment by arthurlogilab** [comment]
@vdemeester thanks this documentation should be referenced in the ubuntuinstall page, particularly on http://docs.docker.com/engine/installation/ubuntulinux/#configure-a-dns-server-for-use-by-docker
