### ISSUE TITLE
possible to rm a container that is being used by other containers via -volumes-from

### ISSUE THREAD

**Issue by tavisrudd** [docker/docker#3634]
When this occurs it renders the child container unusable unless one commits the container's image and runs a new container from it without -volumes-from.

```
$ docker run -v /mnt/vol -name data_container busybox touch /mnt/vol/base
$ docker run -name child  -i -volumes-from data_container ubuntu ls -al /mnt{/vol,}
/mnt:
total 12
drwxr-xr-x  3 root root 4096 Jan 16 21:54 .
drwxr-xr-x 29 root root 4096 Jan 16 21:54 ..
drwx------  2 root root 4096 Jan 16 21:52 vol

/mnt/vol:
total 8
drwx------ 2 root root 4096 Jan 16 21:52 .
drwxr-xr-x 3 root root 4096 Jan 16 21:54 ..
-rw-r--r-- 1 root root    0 Jan 16 21:52 base

$ docker start -a child
/mnt:
total 12
drwxr-xr-x  3 root root 4096 Jan 16 21:54 .
drwxr-xr-x 29 root root 4096 Jan 16 21:54 ..
drwx------  2 root root 4096 Jan 16 21:52 vol

/mnt/vol:
total 8
drwx------ 2 root root 4096 Jan 16 21:52 .
drwxr-xr-x 3 root root 4096 Jan 16 21:54 ..
-rw-r--r-- 1 root root    0 Jan 16 21:52 base
child

$ docker rm data_container
data_container
### the previous command should not have been possible
$ docker start -a child
Error: start: Cannot start container child: Container 7c90924874615b82fb8385310ee2fc45b035cdce32ad14740d031f25417a7e59 not found. Impossible to mount its volumes
2014/01/16 13:54:22 Error: failed to start one or more containers
```

**Comment by JulienBreux** [comment]
:+1: :bug:

**Comment by FGRibreau** [comment]
:+1: please fix this

**Comment by antham** [comment]
:+1:

**Comment by remy-theroux** [comment]
:+1:

**Comment by MarcFRICOU** [comment]
:+1:

**Comment by Cowa** [comment]
:+1: :boar:

**Comment by sdemonti** [comment]
:+1:

**Comment by nevezide** [comment]
:+1:

**Comment by Jaconil** [comment]
:+1:

**Comment by mguihal** [comment]
:+1:

**Comment by cpuguy83** [comment]
Closing this because this is fixed, and has been for a long time.
When you use volumes-from the container stores the volume references itself.
If you are having an issue, it is a separate issue from what was reported here.

**Comment by stephenlee1121** [comment]
:+1:

**Comment by FGRibreau** [comment]
@cpuguy83 As a user I should not be able to remove a volume container that is currently used by a --volume-from from another container, even if I can recreate it easily with docker create. It's still a bug

**Comment by Freyskeyd** [comment]
It shouldn't be possible to remove a linked container too..

**Comment by cpuguy83** [comment]
@FGRibreau It doesn't matter if you can remove it or not, the volume reference is stored in other containers. The volume still exists, etc.

@Freyskeyd That's a completely separate issue, and really it is addressed by the new networking/services functionality.

**Comment by JulienBreux** [comment]
@cpuguy83 Thx!

**Comment by FGRibreau** [comment]
> @FGRibreau It doesn't matter if you can remove it or not, the volume reference is stored in other containers. The volume still exists, etc.

So I should learn a new command to recreate the old volume from the volume reference right? 
While in the first place docker could have saved me from this mistake right?
... Am I the only one who think it goes against everything we learnt about UX?

**Comment by cpuguy83** [comment]
@FGRibreau, no new command... `docker run --volumes-from` will still work...
We can't keep from you from accidentally deleting a container.
In this case, the container is not what's important, it's the volumes, and you still have the volumes, you can still `--volumes-from` to get those volumes.

We also now have named volumes so you can specify the exact volume you wanted, and will soon have a top-level volume management command/api.

**Comment by thaJeztah** [comment]
@FGRibreau there's no need to reconstruct the volume, because the volume is still there.

The current way this works is actually very useful to upgrade/replace a container with a newer version. A short "workflow" to illustrate the concept;

```bash
docker run --name mydb mysql:5.5.43

# a newer version becomes available
docker rename mydb mydb-previous

# create and start a new container to replace the old one
docker create --volumes-from=mydb-previous --name=mydb mysql:5.5.44
docker stop mydb-previous && docker start mydb

# after verifying all is working correctly
docker rm mydb-previous
```

**Comment by kirkstrobeck** [comment]
@thaJeztah wouldn’t work with [scaling](https://docs.docker.com/compose/compose-file/#container-name)

> Because Docker container names must be unique, you cannot scale a service beyond 1 container if you have specified a custom name. Attempting to do so results in an error.

**Comment by thaJeztah** [comment]
@kirkstrobeck you're referring to docker-compose; also, scaling a MySQL container and reusing the same volume is probably a bad idea, because you end up having two (or more) MySQL servers writing to the same data-directory.

Note that we now have volume management (`docker volume create`, `docker volume ls`, etc.), so using data-only containers, and volumes-from has become redundant in most cases.
