### ISSUE TITLE
docker run can exit silently on ENOMEM

### ISSUE THREAD

**Issue by garthk** [docker/docker#3666]
Seen under [memory pressure](https://gist.github.com/garthk/8032bd32ea7c0e85753b): `docker run` exiting before its contained process, failing to show either:

* the contained process' dying moments (it was due to crash because `ENOMEM`)
* any distress of its own

Running `docker ps` quickly enough showed the container still running. 

Running `docker logs` showed the contained process' dying moments.

**Comment by jfrazelle** [comment]
closing because no response but feel free to ping me if you are still seeing it

**Comment by garthk** [comment]
Yeah, I'm OK with that. Sorry for letting it lie fallow.
