### ISSUE TITLE
Feature request: Link-sharing between docker instances

### ISSUE THREAD

**Issue by lyschoening** [docker/docker#3737]
A very typical use-case is having services/containers that need to communicate with another on multiple hosts. Links & container naming already simplifies this process on a single machine. I see two possible ways to implement this feature over the network:

1. some kind of mechanism by which Docker instances can discover names and addresses of containers run by other Docker instances on different hosts and making those links available to local instances. 
2. a command for manually injecting a remote container by giving the address of a remote Docker instance and a container name to link from the remote instance. 

In both cases, the links should work the same as host-local links, i.e. tunnels should be created automatically when a link is established.

**Comment by jfrazelle** [comment]
I think we can close this as being included in https://github.com/docker/docker/issues/8951
