### ISSUE TITLE
CPU soft lockup on docker daemon restart.

### ISSUE THREAD

**Issue by poe** [docker/docker#3744]
We are running Docker version 0.7.6, build bc3b2ec on dell hardware.  

We have seen this problem on both Ubuntu 12.04 (kernel 3.8.0-35-generic) and 13.10 (kernel 3.11.0-15-generic)

Containers seem to continue running fine, but as soon as we do a pull, restart or ps sometimes it crashes the system.  The server will respond to pings, but not ssh or other traffic.  

Here is the relevant kern.log:  (in this case from 12.04)
Jan 21 22:52:12 ourserver kernel: [109267.001138] aufs
> test_add:261:docker[16740]: uid/gid/perm
> /var/lib/docker/aufs/diff/539c0211cd76cdeaedbecf9f023ef774612e331137ce7ebe4ae1b61088e7edbe
> 0/0/0555, 0/0/0755
> Jan 21 22:52:40 ourserver kernel: [109294.459832] BUG: soft
> lockup - CPU#4 stuck for 22s! [docker:2374]
> Jan 21 22:52:40 ourserver kernel: [109294.460022] Modules
> linked in: veth(F) xt_nat(F) xt_tcpudp(F) xt_addrtype(F)
> iptable_filter(F) xt_conntrack(F) aufs(F) ipt_MASQUERADE(F)
> iptable_nat(F) nf_conntrack_ipv4(F) nf_defrag_ipv4(F) nf_nat_ipv4(F)
> nf_nat(F) nf_conntrack(F) ip_tables(F) x_tables(F) bridge(F) stp(F)
> llc(F) vesafb(F) ext2(F) bonding(F) xfs(
> F) coretemp(F) libcrc32c(F) kvm_intel(F) kvm(F) ghash_clmulni_intel(F)
> aesni_intel(F) ablk_helper(F) cryptd(F) lrw(F) aes_x86_64(F) xts(F)
> gf128mul(F) joydev(F) gpio_ich(F) shpchp(F) dcdbas(F) microcode(F)
> mei(F) lpc_ich(F) mac_hid(F) wmi(F) acpi_power_meter(F) lp(F)
> parport(F) hid_generic(F) usbhid(F) hid(F) ses(F) enclosure(F) ahci(F)
> libahci(F) megaraid_sas
> (F) tg3(F) ptp(F) pps_core(F)
> Jan 21 22:52:40 ourserver kernel: [109294.460051] CPU 4
> Jan 21 22:52:40 ourserver kernel: [109294.460054] Pid: 2374,
> comm: docker Tainted: GF       W    3.8.0-35-generic
> #50~precise1-Ubuntu Dell Inc. PowerEdge R620/0GFKVD
> Jan 21 22:52:40 ourserver kernel: [109294.460055] RIP:
> 0010:[<ffffffff811b3e72>]  [<ffffffff811b3e72>] d_lookup+0x52/0x60
> Jan 21 22:52:40 ourserver kernel: [109294.460061] RSP:
> 0018:ffff882ff801dbd8  EFLAGS: 00000202
> Jan 21 22:52:40 ourserver kernel: [109294.460062] RAX:
> ffff882ff6e91740 RBX: ffff882ff1d7e6e8 RCX: ffff882ff801dc67
> Jan 21 22:52:40 ourserver kernel: [109294.460063] RDX:
> 0000000000000011 RSI: ffff882ff801dd20 RDI: ffff88181f008240
> Jan 21 22:52:40 ourserver kernel: [109294.460064] RBP:
> ffff882ff801dbf8 R08: ffffc90000002000 R09: ffff882ff801dd20
> Jan 21 22:52:40 ourserver kernel: [109294.460065] R10:
> ffff882ff6245026 R11: 0000000000000001 R12: 0000000000000000
> Jan 21 22:52:40 ourserver kernel: [109294.460066] R13:
> ffff882ff801dca0 R14: ffff882ff801dc30 R15: ffffea005e0eb6c0
> Jan 21 22:52:40 ourserver kernel: [109294.460068] FS:
> 00000000029cb880(0063) GS:ffff88181fa40000(0000)
> knlGS:0000000000000000
> Jan 21 22:52:40 ourserver kernel: [109294.460069] CS:  0010
> DS: 0000 ES: 0000 CR0: 0000000080050033
> Jan 21 22:52:40 ourserver kernel: [109294.460070] CR2:
> 00000000029cb840 CR3: 00000017e508b000 CR4: 00000000001407e0
> Jan 21 22:52:40 ourserver kernel: [109294.460071] DR0:
> 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
> Jan 21 22:52:40 ourserver kernel: [109294.460072] DR3:
> 0000000000000000 DR6: 00000000ffff0ff0 DR7: 0000000000000400

**Comment by jfrazelle** [comment]
is this still an issue with the latest version or master, you can download with https://master.dockerproject.com

**Comment by d136o** [comment]
I think we just experienced a similar failure. Our EC2 instance r3.2xlarge became unresponsive. From amazon's cloudwatch we can see that something is eating up 25% of the alloted vcpu cores. 

Some hours earlier we pulled a docker image, but otherwise it's a somewhat underutilized host.

The syslog is here: https://gist.github.com/d136o/8e429f092b196d8022f9

**Comment by hvisage** [comment]
any progress/advice on this issue?
I have similar case with frequently spawned short running dockers 
http://pastebin.com/EPmnzkjD

**Comment by wmealing** [comment]
Just repeating once again,not a docker issue, talk to your OS vendor.

**Comment by LK4D4** [comment]
Doesn't look that we can do something here. Also it wasn't reported recently.
