### ISSUE TITLE
Entrypoint params ignored with shell syntax

### ISSUE THREAD

**Issue by gravis** [docker/docker#3751]
(From: https://groups.google.com/d/msg/docker-user/tnscIyLxXVA/GbYKA0NfRLkJ)

I have troubles using an Entrypoint in my dockerfile. I'd like to 
provide a simple psql client as a container : 

```
FROM       debian:wheezy 
RUN        apt-get update 
RUN        apt-get -y dist-upgrade 

RUN        DEBIAN_FRONTEND=noninteractive apt-get install -y -q 
postgresql-client 
# pb occurs with or without CMD: 
CMD        ["--help"] 
ENTRYPOINT /usr/bin/psql --host=$DB_PORT_5432_TCP_ADDR --username=docker 
```

Of course, this container is used with a link named "db". 
Anyway, it seems impossible to pass args, like the documentation says: 

"The ENTRYPOINT instruction adds an entry command that will not be 
overwritten when arguments are passed to docker run, unlike the 
behavior of CMD. This allows arguments to be passed to the entrypoint. 
i.e.docker run <image> -d will pass the “-d” argument to the 
ENTRYPOINT." (http://docs.docker.io/en/latest/use/builder/#dockerfile-entrypoint). 

I understand here that I can pass the "-d" arg in docker run, and it 
be added _after_ my entrypoint command line. Note that the json 
notation of the entrypoint doesn't allow to use 
```$DB_PORT_5432_TCP_ADDR```, but that's another issue. 

Whatever I do: 

```
docker run -rm -link pg:db -e PGPASSWORD=docker 
docker:5000/postgresql-client foo 
docker run -rm -link pg:db -e PGPASSWORD=docker 
docker:5000/postgresql-client bar 
docker run -rm -link pg:db -e PGPASSWORD=docker 
docker:5000/postgresql-client --help 
...
``` 

I always get the same error message, which can be only raised if no 
args are passed to the entrypoint command. 

Am I missing something? I'm using docker stable: 

```
Client version: 0.7.6 
Go version (client): go1.2 
Git commit (client): bc3b2ec 
Server version: 0.7.6 
Git commit (server): bc3b2ec 
Go version (server): go1.2 
Last stable version: 0.7.6 
````

Thanks 

(By the way, about the en var is not expanded, there's a PR #3735 open already.)

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/3751

**Comment by jfrazelle** [comment]
i meant https://github.com/docker/docker/issues/3466
