### ISSUE TITLE
Build and run in one command

### ISSUE THREAD

**Issue by drewcrawford** [docker/docker#3763]
I use Docker as a development environment, and so often I'm doing something like this

```bash
$ vi my_awesome_file.py
$ docker build -t some-unique-name .
$ docker run some-unique-name
```

This is fine, but it requires me to come up with `some-unique-name` that I must put type correctly each time (or create a per-project script to do this).

It would be nice if there was some `docker build-and-run` like command that would have the effect of calling build and then running the image that was built.

**Comment by cpuguy83** [comment]
Seems like docker-compose handles the OP's use-case perfectly.

**Comment by prologic** [comment]
:+1:

**Comment by thaJeztah** [comment]
> Seems like docker-compose handles the OP's use-case perfectly.

Actually, there's thoughts on removing "build" from docker-compose; https://github.com/docker/compose/issues/1455

**Comment by odigity** [comment]
:+1: to what @drewcrawford said.  I just started using docker, and running build and run commands after each file edit is quite tedious.

**Comment by calavera** [comment]
Hi,

I'm going to close this old issue. There are tools that can provide this type of feature, like docker-compose, but you can also do `$ docker build -t foo . && docker run foo`.

**Comment by petersenna** [comment]
@calavera  I would like to build and run in a single and native docker command too. Something like $ docker build-and-run would be awesome. It would save me time, lots of time.

**Comment by odigity** [comment]
How about an 'up' command like Vagrant?  A vagrant user would associate that with "do everything it takes to get this running, including the build step", which I think is better than no prior mental association at all.

And if it didn't require specifying a tag, but intelligently ran the container it just also built without you having to name it, then the new user experience would be as easy as:

1) git clone <repo>
2) cd <repo>
3) docker up

**Comment by odigity** [comment]
BTW -- I've since wrapped all my long command lines in a set of shell scripts in my project's bin/ dir.  Has made of world of difference being able to do:

1) bin/dbstart
2) bin/build
3) bin/dev

On a new project to launch a named DB container, build the app container, and run the app container in dev mode (cmd -> /bin/bash) linked to DB container.

Still think a combined command would be useful, though.

**Comment by thaJeztah** [comment]
@odigity perhaps you should consider a Makefile for that; see for reference [the one in this repository](https://github.com/docker/docker/blob/master/Makefile) that, for example, allows you to do `make docs`, to build an image with the documentation in it, runs it and starts a web server to preview the documentation

However, a lot of what you're describing is "orchestration" and really [docker compose](https://docs.docker.com/compose/) is meant for that; `docker-compose up` will build your images, start, configure and link your containers, etc.

**Comment by odigity** [comment]
@thaJeztah -- Thanks for the tip; haven't made time to check out Compose yet, maybe I should.

BTW-I'm a Ruby guy.  I would use the following before resorting to make, in order:  :)

1) plain ruby
2) plain bash
3) Rake (I'm not a huge fan, but it's sometimes useful, and still better than Make)

**Comment by grosser** [comment]
FYI tiny ruby script to do just that https://github.com/grosser/dotfiles/blob/master/bin/docker-brd
