### ISSUE TITLE
Port redirection and IPv6 addresses

### ISSUE THREAD

**Issue by trkoch** [docker/docker#3788]
From what I understand, thanks to advanced port redirects it's possible to bind to a specific socket (i.e. IP address + port). If no port is specified all adresses are bound, and from my oberservation this includes all IPv6 interfaces. But how to bind to a single IPv6 address and no IPv4 addresses at all? The spec 

`[([<host_interface>:[host_port]])|(<host_port>):]<container_port>[/udp]`

does not appear to account for colons in the `<host_interface>`. As a result I'm getting an 'Invalid format to parse.' error from utils.go.

$ docker run -p fd6f:6672:dfac::1ff:fe00:1:22 -t -i <user>/<image>
2014/01/27 17:38:11 Invalid format to parse.  fd6f:6672:dfac::1ff:fe00:1:22 should match template ip:hostPort:containerPort

Is it just the port spec parser that is preventing what I'm trying here?

--
$ uname -a
Linux docker 3.8.0-35-generic #50~precise1-Ubuntu SMP Wed Dec 4 17:25:51 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client version: 0.7.6
Go version (client): go1.2
Git commit (client): bc3b2ec
Server version: 0.7.6
Git commit (server): bc3b2ec
Go version (server): go1.2

Host is Ubuntu 12.04.3 LTS.

**Comment by MalteJ** [comment]
ping

**Comment by chrisnew** [comment]
Anything new here? I really could use this feature now. :) I'm currently stuck enhancing docker-proxy and portmapping to get them allowing IPv6. (I also already implemented SNAT and per container set global IPv6 address.)

**Comment by jfrazelle** [comment]
https://github.com/docker/docker/pull/8947 has been merged so I believe this can be closed.
You can try it out via the binaries at master.dockerproject.com, and the docs are at http://docs.master.dockerproject.com/articles/networking/#ipv6
