### ISSUE TITLE
docker client not passing signals to dockerd

### ISSUE THREAD

**Issue by polvi** [docker/docker#3793]
We'd like a signal to the docker client to trigger a stop, so if the docker client is killed, it cleans up the containers. 

Filing bug per @crosbymichael request for how to reproduce. 

```
$ docker run -sig-proxy=true busybox sleep 3000
 
(other terminal)
$ docker ps
e8767eed1283        busybox:latest      sleep 3000          28 seconds ago      Up 28 seconds                           insane_pasteur      
$ ps aux|grep 'busybox sleep'
  782 docker   docker run -sig-proxy=true  busybox sleep 3000
$ kill 782
$ docker ps
e8767eed1283        busybox:latest      sleep 3000          45 seconds ago      Up 45 seconds                           insane_pasteur   

... still running ...

$ kill -9 782
$ ps aux | grep 782 
$

... docker run (client) has been killed ... but the container is still running.   

$ docker ps
e8767eed1283        busybox:latest      sleep 3000          3 minutes ago       Up 3 minutes                            insane_pasteur     
```  

#1249 appears to have the functionality needed to fix this, but that appears to have been removed. Is there any other way to get this functionality?

**Comment by jfrazelle** [comment]
have you tried docker attach I have used that to manage containers with upstart before or will the new restart policies handle this?

**Comment by jonathanperret** [comment]
It looks like until the kernel can be convinced to not treat PID 1 as special, we're stuck with not being able to stop `cat`, `tail`, `dd`, `tar`… in a "normal" way.

In the meantime, a minuscule process manager such as https://github.com/krallin/tini provides a practically drop-in workaround. Here's that `sleep` again:

```
$ docker run --rm ubuntu:14.04 sleep 3000
^C^C^C^C^C^C^C^C^C^C <-- nothing happens.
```

Now using @krallin's `ubuntu-tini` image:

```
$ docker run --rm krallin/ubuntu-tini:14.04 sleep 3000
^C <-- exits right away
$
```

This scenario of running a simple command that expects default signal handling, i.e. exit on `SIGINT`, `SIGTERM`, `SIGPIPE`… seems common enough that maybe Docker should provide an easy way to run them as non-PID 1 ? It seems in fact that's what #3240 was trying to achieve…

**Comment by LK4D4** [comment]
#26061 expected to fix this

**Comment by pufferbatterie** [comment]
This is a WORKAROUND to SIGINT for tail.
It takes 1 second if you can tolerate sleep 1 on your CPU.

entrypoint.sh:
```
#!/bin/bash
trap 'echo "got sigterm" ; exit 0' SIGTERM
tail -f /logs/cron.log &
while true; do sleep 1; done
```

**Comment by pufferbatterie** [comment]
This is a WORKAROUND for tail.
It SIGINTS after a second if you can tolerate sleep 1 on your CPU.

entry.sh
```
#!/bin/bash

trap 'echo "got sigterm" ; exit 0' SIGTERM
tail -f /logs/cron.log &
while true; do sleep 1; done
```

**Comment by nielsbom** [comment]
Just for people coming across this issue years later: [dumb-init](https://github.com/Yelp/dumb-init) is a process supervisor you can wrap around a lot of programs which correctly handles signals.
