### ISSUE TITLE
ADD does not respect WORKDIR

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#3936]
(see the ``Dockerfile below``)

so, ``add1`` is lost (really why didn't that error out as insane?), ``add2`` and ``add3`` are in the root - did we drop the `.` silently?

and the most frustrating, ``add4`` is relative, but doesn't go into ``WORKDIR``

I'm going to add ``<dest>`` is the absolute path to which the source will be copied, but it would be nice to clean this up so that anything that isn't intended to work errors out, and (hopefully) have ADD respect WORKDIR :)

-------

``
FROM busybox

RUN echo "root?" > test1.txt
RUN mkdir /test2
WORKDIR /test2
RUN echo "test2" > test2.txt
#ENTRYPOINT ["/usr/bin/pwd"]

ADD add1 .
ADD add2 ./
ADD add3 ./add3_rename
ADD add4 add4
``

``
Uploading context 10.24 kB
Uploading context 
Step 1 : FROM busybox
 ---> e9aa60c60128
Step 2 : RUN echo "root?" > test1.txt
 ---> Using cache
 ---> 121e83a634b4
Step 3 : RUN mkdir /test2
 ---> Using cache
 ---> 8ee100283bfd
Step 4 : WORKDIR /test2
 ---> Using cache
 ---> 9e468377d365
Step 5 : RUN echo "test2" > test2.txt
 ---> Using cache
 ---> 3975fd30a1f4
Step 6 : ADD add1 .
 ---> Using cache
 ---> 240c83752177
Step 7 : ADD add2 ./
 ---> Using cache
 ---> ab1f1a1e9eaa
Step 8 : ADD add3 ./add3_rename
 ---> Using cache
 ---> d2456542a584
Step 9 : ADD add4 add4
 ---> Using cache
 ---> bc11538ed7b2
Successfully built bc11538ed7b
``

``
sven:~/src/docker/dockerfiles/tmp (master *)$ docker run -t -i -rm test sh

BusyBox v1.19.3 (Ubuntu 1:1.19.3-7ubuntu1.1) built-in shell (ash)
Enter 'help' for a list of built-in commands.

/test2 # ls -al
total 12
drwxr-xr-x    2 root     root          4096 Feb  5 02:28 .
drwxr-xr-x   38 root     root          4096 Feb  5 03:03 ..
-rw-r--r--    1 root     root             6 Feb  5 02:28 test2.txt
/test2 # ls -al ..
total 14152
drwxr-xr-x   38 root     root          4096 Feb  5 03:03 .
drwxr-xr-x   38 root     root          4096 Feb  5 03:03 ..
-rw-r--r--    1 root     root           192 Feb  5 03:03 .dockerenv
-rwx------    1 root     root      14430407 Feb  3 02:06 .dockerinit
-rw-r--r--    1 1000     1000             5 Feb  5 02:52 add2
-rw-r--r--    1 1000     1000             5 Feb  5 02:52 add3_rename
-rw-r--r--    1 1000     1000             5 Feb  5 02:52 add4
drwxr-xr-x    2 root     root          4096 Mar 12  2013 bin
drwxr-xr-x    4 root     root          4096 Feb  5 03:03 dev
drwxr-xr-x    2 root     root          4096 Feb  5 03:03 etc
drwxr-xr-x    2 root     root          4096 Dec 11 01:41 lib
lrwxrwxrwx    1 root     root             3 Mar 12  2013 lib64 -> lib
dr-xr-xr-x  195 root     root             0 Feb  5 03:03 proc
lrwxrwxrwx    1 root     root             3 Mar 12  2013 sbin -> bin
dr-xr-xr-x   13 root     root             0 Feb  5 03:03 sys
-rw-r--r--    1 root     root             6 Feb  5 02:28 test1.txt
drwxr-xr-x    2 root     root          4096 Feb  5 02:28 test2
drwxr-xr-x    2 root     root          4096 Mar 12  2013 tmp
drwxr-xr-x    2 root     root          4096 Dec 11 01:41 usr
``

**Comment by jfrazelle** [comment]
closing because #9635 was merged
