### ISSUE TITLE
VOLUME(S)-FROM in dockerfiles; equivalent of docker run's -volumes-from

### ISSUE THREAD

**Issue by tavisrudd** [docker/docker#3949]
Use Case:

My build process for Gentoo images requires the /usr/portage tree. At ~800M it is larger than most of my final images and I don't want it included in the images as it is not needed post-build. As docker files don't support, and are philosophically incompatible with, bind-mounts from the host, I currently manage my build process with `docker run` and /usr/portage declared as a volume then bind-mounted from the host.  

It would be preferable to stick /usr/portage and other build time dependencies in a data image/container and then declare `VOLUMES-FROM build-deps-container-or-image` as a step in a dockerfile. This would allow host-independent use of build-time deps and is, thus, preferable to allowing escalated privileges or bind-mounts in dockerfiles.
 
I think some of the use cases in #1916 would be compatible with this.

It's probably preferable to implement this with the volumes coming from a base image rather than from a base container. 

Options:
1) VOLUMES-FROM that is semantically equivalent to `docker run -volumes-from`. Unfortunately, this and the original -volumes-from option limit you to the volume paths declared in the base container.
2) VOLUMES-FROM-IMG with configurable source and target paths and the source being an image not a container. `VOLUMES-FROM-IMG base-image base-image-dir:[container-dir] ...`.
3) VOLUME-FROM-IMG with the same semantics as (2) but only a single volume allowed per line.

The volume mount should persist through all subsequent docker build commands to the end of the build process. The resulting image, however, would not contain any additional metadata beyond what `VOLUME` already creates.

I discussed this with @shykes on twitter (https://twitter.com/solomonstre/status/417450365823381504) but couldn't find the issue he mentions. Apologies if this is a duplicate.

**Comment by spudtheimpaler** [comment]
There are many similar threads discussing this and alternatives. Is there a current favourite for implementation of this or similar functionality?

Basically, I want to have access to a volume-only image at build time. Nothing else fancy...

**Comment by lucasjellema** [comment]
Being able to use VOLUME-FROM in the Dockerfile at build time would be very convenient. I wholeheartedly everyone asking for this option. There are so many circumstances where files and data are only required to go through the provisioning and installation process and not afterwards - all that stuff should not be included in the container or image. Being able to access it from some external volume during the build seems a great solution to this.

**Comment by James1912** [comment]
A big +1

**Comment by jeremyherbert** [comment]
#3156 as well

I have another use case for this which I believe has not been mentioned: I'd like to sandbox some proprietary software in docker. The installers together make up about 22GB. 

I'm not allowed to host this software anywhere for legal reasons, and it's not possible to download it on the fly (you need to log in to a website and go through multiple javascript filled pages, including agreeing to an export control license). I also don't want to copy the 22GB file into the docker instance as this will just balloon the disk space requirements unnecessarily.

**Comment by dreamcat4** [comment]
***+1***

**Comment by dreamcat4** [comment]
Another way would be to extend `VOLUME` with a `--flag`. e.g.

    FROM base_image
    VOLUME --from builder_image

To be more consistent with what is being done for other Dockerfile commands such as `ADD`, `COPY`, etc.

**Comment by orzel** [comment]
Mounting volume from another image from within a Dockefile is definitely something needed, I agree.

**Comment by gioppoluca** [comment]
+1 from me also

**Comment by rubicks** [comment]
:+1: The workflow around the [google/cloud-sdk docker image](https://registry.hub.docker.com/u/google/cloud-sdk/) is another use case that would benefit from this proposed feature.

**Comment by deem0n** [comment]
VOLUME-FROM +1

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by nalipaz** [comment]
Since this has been closed for almost a year I thought I would try to see if anyone found a resolution to the original request using this issues suggested solution (a plugin via docker plugin api)? I don't yet see a plugin to fulfill the needs outlined in this thread.

**Comment by PhantomYdn** [comment]
I didn't find any solution... Anything in roadmap?

**Comment by bwv988** [comment]
👍 for VOLUME-FROM :)

**Comment by eaglet3d** [comment]
Isn't a docker volume data container just another storage source?  Why is it that a Dockerfile can create a VOLUME association with a local directory but is unable to associate a docker volume data container?

**Comment by lramage94** [comment]
+1 for VOLUME-FROM

**Comment by paigeadelethompson** [comment]
+9999999999999999999999999999999999999999 for VOLUME-FROM
