### ISSUE TITLE
Error messages not being formatted properly when registry API returns pretty-printed JSON

### ISSUE THREAD

**Issue by josephschorr** [docker/docker#3951]
If a registry or index returns a *pretty-printed* JSON block, then the result is the following:

```
docker push localhost/somenamespace/test
The push refers to a repository [localhost/somenamespace/test] (len: 1)
Sending image list
2014/02/05 16:52:13 push: }
```

Output for non-pretty printed response:
```
docker push localhost/somenamespace/test
The push refers to a repository [localhost/somenamespace/test] (len: 1)
Sending image list
2014/02/05 16:56:16 push: Error: Status 403 trying to push repository somenamespace/test: {"error": "You do not have permission to create repositories in namespace \"somenamespace\""}
```

docker version:
Client version: 0.8.0
Go version (client): go1.2
Git commit (client): cc3a8c8
Server version: 0.8.0
Git commit (server): cc3a8c8
Go version (server): go1.2
Last stable version: 0.8.0

**Comment by jfrazelle** [comment]
@jlhawn @dmcgowan does this still apply?

**Comment by dmcgowan** [comment]
@jfrazelle this should no longer apply, that error message is now outputted using the logging library.  An example error would now appear like

`FATA[0006] Failed to ....`

**Comment by jfrazelle** [comment]
So I can close?
