### ISSUE TITLE
docker pull progress bar is useless

### ISSUE THREAD

**Issue by bradfitz** [docker/docker#4022]
Running docker pull on an image with many layers shows a dozen progress bars and ETAs, all useless.

It should show a progress bar of the total size of all layers.

Uploading context 3.584 kB
Uploading context
Step 0 : FROM wasabeef/android
Pulling repository wasabeef/android
e688e6c18784: Pulling dependent layers
539c0211cd76: Download complete
c2e151cf3c95: Download complete
f2f91b21e1ec: Downloading [=====================================>             ] 192.8 MB/255.2 MB 25s

Later:

Pulling repository wasabeef/android
e688e6c18784: Pulling dependent layers
539c0211cd76: Download complete
c2e151cf3c95: Download complete
f2f91b21e1ec: Download complete
06cc47e758b1: Download complete
8c68070e87ed: Downloading [=============================================>     ]  59.7 MB/66.26 MB 2s

Later:

Pulling repository wasabeef/android
e688e6c18784: Pulling dependent layers
539c0211cd76: Download complete
c2e151cf3c95: Download complete
f2f91b21e1ec: Download complete
06cc47e758b1: Download complete
8c68070e87ed: Download complete
fbe62bc0bf74: Download complete
8963671c3f7a: Downloading [===============>                                   ] 3.441 MB/11.16 MB 5s

etc

**Comment by jfrazelle** [comment]
```
jessie at debian in ~/docker on master
$ docker pull debian:sid > file

jessie at debian in ~/docker on master [?]
$ cat file
debian:sid: The image you are pulling has been verified
af26f221e0e7: Pulling fs layer
09c0c850c2f4: Pulling fs layer
511136ea3c5a: Already exists
09c0c850c2f4: Download complete
af26f221e0e7: Download complete
af26f221e0e7: Pull complete
09c0c850c2f4: Pull complete
Status: Downloaded newer image for debian:sid
```
with latest version.
going to close but you can ping me if you are upset, or thing this is wrong.

**Comment by bradfitz** [comment]
Thanks! I noticed the new behavior recently and was pleasantly surprised.

**Comment by jfrazelle** [comment]
yayyyy you are the one person who is not coming after me with a pitchfork
for closing their issue <3

**Comment by exarkun** [comment]
Thanks for your efforts here jfrazelle.  However, note that the original issue description includes this:

> Running docker pull on an image with many layers shows a dozen progress bars and ETAs, all useless.

Resolving this by removing the progress bars when stdout is not a tty is ... well, I don't think it's really a resolution.  However, I do see that several folks in the comments on this issue latched onto a separate concern, that the progress bars produce gross output when stdout is not a tty, and that problem has apparently now been resolved, so I see how you might want to close this issue.

However, considering what the original issue reported was, I think this should be re-opened.  Failing that, the original problem should be re-reported in a new issue.

Which would you prefer?

**Comment by jfrazelle** [comment]
Welll, if you try with the latest version from master.dockerproject.com, I
do also believe the original issue has been fixed.

**Comment by jfrazelle** [comment]
If you try and think otherwise let me know and I will reopen.

**Comment by exarkun** [comment]
If that's the case, my apologies for the noise.  I don't regularly run master@HEAD and it wasn't clear from your comment that the originally reported behavior was also fixed (I think the example you gave only demonstrated the changed stdout-is-tty behavior).

**Comment by jfrazelle** [comment]
no worries I should have also mentioned that

**Comment by cfoust** [comment]
I don't think this was fixed and I'm confused as to why it was closed. The progress bar behavior still isn't useful when you have an image with lots of layers. `docker pull [image] | cat` doesn't fix the problem either, it's still confusing for the user. Are there any efforts to improve Docker's progress bar or is there a workaround?

**Comment by cpuguy83** [comment]
@cfoust Somewhere along the discussion it looks like "less than helpful" output and "doesn't work because of no TTY" got mixed up here.

In any case, if you'd still like to see something like this, I think this would need to go into https://github.com/docker/cli

Thanks!
