### ISSUE TITLE
Dockerfile FROM ../relative/path

### ISSUE THREAD

**Issue by bradfitz** [docker/docker#4027]
Feature request....

Our project, Camlistore, vendors all our dependencies in-tree, so we can sync to any point in time and get a hermetic build.

We would also like to check in all our Dockerfiles, rather than exclusively using index.docker.io.

But if we keep the Dockerfiles in-tree, we can't use FROM to form a tree of common layers.

It would be nice if we could use FROM in a Dockerfile to refer to a relative path. For instance, if it begins with "./" or "../", then don't treat it as a index.docker.io-namespaced identifer, and use the filesystem instead.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
