### ISSUE TITLE
Option to override container name

### ISSUE THREAD

**Issue by schickling** [docker/docker#4212]
It would be nice if there was an option to force overriding of container names, so you won't get messages like: `Error: create: Conflict, The name xxx is already assigned to yyy`.

The current workflow looks something like this: `docker run -name test ubuntu`, delete test container, run command again.

A much more convenient solution would be something like this:

`docker run -name -force-name test ubuntu`

**Comment by cpuguy83** [comment]
Container renaming was just merged here #8570 which would be another way to address this issue.

**Comment by vbatts** [comment]
yes. That effectively does this.
```
docker rename foo foo.old
docker run --name foo me/myapp
```

**Comment by wieczorek1990** [comment]
+1

**Comment by thaJeztah** [comment]
@wieczorek1990 just curious, what are you "+1"-ing? Docker rename has been around since docker 1.5, so wondering what's missing.

**Comment by wieczorek1990** [comment]
I would like to be able to pass a parameter to docker run that deletes the
old container if I passed an existing name.

**Comment by thaJeztah** [comment]
@wieczorek1990 don't think that will ever be supported, basically, that's https://github.com/docker/docker/issues/2733; I tried to explain why we won't be implementing that in this comment https://github.com/docker/docker/issues/2733#issuecomment-194850988

**Comment by wieczorek1990** [comment]
I kind of understand that you want to have the minimal subset of commands, but people always seek shortcuts/automation (that's why we write code, right?), so maybe we should have a rc or config dotfile to store aliases?

**Comment by thaJeztah** [comment]
Bash already offers that, so I think that would be duplicating functionality that's already there. Aliases can be very personal, and depending on [your use case and preference](https://github.com/jfrazelle/dotfiles/blob/master/.dockerfunc)
