### ISSUE TITLE
stdin truncated at line 1

### ISSUE THREAD

**Issue by garthk** [docker/docker#4253]
Logstash in a container sees only the first line of standard input fed to it… but only when I try it under OS X. Details:

* OS X to boot2docker 0.5.4 VM via `tcp://`: truncated if the job is logstash
* OS X to boot2docker 0.5.4 VM via `tcp://`: works if the job is `wc -l`
* OS X to distant Ubuntu VM via `tcp://M.N.O.P:4243': works for logstash and `wc -l`
* Ubuntu to local Ubuntu via domain socket: works for logstash and `wc -l`

This might be a `boot2docker` problem, but I'm having trouble figuring out precisely *how*.  Any ideas? `Dockerfile` and scripts in [gist 9107359].

 [gist 9107359]: https://gist.github.com/garthk/9107359

**Comment by jfrazelle** [comment]
closing for lack of more info, this seems fine on latest build but please ping me if this has been closed in error, happy to repoen

**Comment by garthk** [comment]
@cpuguy83 seems to work now. Thanks.

```
$ seq 1 10 | docker run -rm -i logstash-9107359 wc -l
Warning: '-rm' is deprecated, it will be replaced by '--rm' soon. See usage.
10
```
