### ISSUE TITLE
Failed container start does not work with host integration

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#4306]
When a container fails to start upstart is not aware that the failure occurred.

For instance, I recently had a container that was trying to start via upstart that was depending on a link from another container, but that linked container wasn't started, so docker refused to start this one.
Upstart thought the job started fine, running status on the upstart job said the job was running, but container was not, logs from the docker daemon shows the failure due to the linked container not running.

**Comment by JulianGindi** [comment]
Has anyone been able to reproduce this? Is it worth looking into some more?

**Comment by jfrazelle** [comment]
@cpuguy83 can you reproduce
