### ISSUE TITLE
Declare container dependencies

### ISSUE THREAD

**Issue by recht** [docker/docker#4307]
It would be very helpful if it was possible to declare dependencies in a Dockerfile. For example, if a container requires you to link postgresql, which has `EXPOSE 5432`, have the depending file contain something like `EXPECT postgresql:5432` and have the run command fail if such a link has not been provided.
Currently, you have to know the dependencies by looking at the various start scripts, which is not always easy.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/2167

**Comment by jfrazelle** [comment]
also https://github.com/docker/docker/issues/5332

**Comment by thaJeztah** [comment]
also dup of https://github.com/docker/docker/issues/7247
