### ISSUE TITLE
VBox & Docker NAT/Bridge issues

### ISSUE THREAD

**Issue by RickMoynihan** [docker/docker#4329]
I have a simple Dockerfile like this deriving from `ubuntu:13.04` with few dependencies:

     FROM ubuntu:13.04
     MAINTAINER Rick Moynihan "foo@example.com"

     # install prerequisites
     RUN sed -i 's/main$/main universe/' /etc/apt/sources.list && apt-get update

     RUN apt-get update && apt-get clean

     RUN apt-get install -y python-dev curl wget zip

     ADD twenty-meg-file /tmp/twenty-meg-file

When I then try and issue curl commands to upload the `twenty-meg-file` from inside the container it fails (non deterministically).

     root@2d889713fbb4:/tmp# curl -f -X POST -H "Content-Type: application/rdf+xml" -d @/tmp/twenty-meg-file http://192.168.0.190:3030/junk/data
     curl: (56) Recv failure: Connection reset by peer

Normally it fails, sometimes it succeeds.  When I run the following command outside the docker (in my vagrant instance or on my physical host (OSX darwin)) it passes everytime.

The HTTP server reports the error as being: "Premature end of file." both these errors seem to indicate that somewhere the (virtual) networking stack is abruptly closing the socket before the transfer is complete.

I also see this same error inside my dockers when creating the same post via a different library (e.g. pythons HTTP requests API):

I am running dockers inside a Vagrant 1.4.3 VM, which is running ubuntu precise.  Precisely:

      vagrant@precise64:~$ uname -a
      Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux

My docker version is:

        vagrant@precise64:~$ docker version
        Client version: 0.8.1
        Go version (client): go1.2
        Git commit (client): a1598d1
        Server version: 0.8.1
        Git commit (server): a1598d1
        Go version (server): go1.2
        Last stable version: 0.8.1

Any help appreciated.

Oh, and many many thanks for docker! :-)

**Comment by mhworth** [comment]
@unclejack I tried this again today using the latest version of boot2docker and docker, and it seems to have worked. As far as I'm concerned, we can close this.

**Comment by unclejack** [comment]
@mhworth Have you been testing this for a while? Did you run into this again since the last time you checked and commented?

Has anyone else seen this with the latest virtualbox or on any other system?

**Comment by mhworth** [comment]
@unclejack I've been testing it periodically every month or so. Sometime between the end of November and now it fixed itself. Unfortunately I wasn't being particularly systematic, so I'm not sure exactly what changed to make it work now.

**Comment by unclejack** [comment]
@jfrazelle These two issues aren't the same.

**Comment by jfrazelle** [comment]
ah ok thanks reopened other

**Comment by Stavros** [comment]
I 've also experienced system hangs (CPU stall) with Virtualbox and Docker coexisting in the same host when starting a VM while I have running containers. 

Debian wheezy + Docker + Virtualbox

Tried:
diff. kernels >3.10
networking features disable (iptables, ipv6)
change vm's settings (nat, bridged, vt-d/x)

w/ no luck!

Workaround1: start a Vbox VM before any container (thanx @vivia)
Workaround2: Migrate to Centos 6/7 :S

I dare not to test what @dougmoscrop experienced: "but it also happens when I SSH in to the VBox machine and make a request directly against the Docker container."

S.

**Comment by cpuguy83** [comment]
Closing since it sounds like this is no longer an issue.

@Stavros your issue seems unrelated to the issue discussed here.

**Comment by rohanjoseph** [comment]
i have boot2docker installed on my windows which has the virtual box  and i have docker0 , eth0,eth1 in the vm the NIC. I am trying to connect the container witht these the ip's provided in it. here is my command docker run -d -p <ip>:<port>:<port> <docker image name> after this when i try to access this in the chrome on my desktop i am not able to see anything. can anyone help me
