### ISSUE TITLE
Add container env variable for its own ip address

### ISSUE THREAD

**Issue by danielwegener** [docker/docker#4352]
Some processes need to know the ip address on which they will be be reachable (in my current example, its the graylog-server that exposes this address through an node advertising endpoint). It fails to detect its own _public_ IP since even the virtual interface (172...) is flagged as loopback-interface.

A Workaround is to add something like 
```ENTRYPOINT export CONTAINER_ADDR=`hostname --ip-address` && ...```
to the Dockerfile.

It would be really nice to have the _public_ reachable IP (e.g. _linked_ or _exposed_ iterface) as an environment variable by default - the name `CONTAINER_ADDR` is just a proposal and tbd.

**Comment by jfrazelle** [comment]
closing as duplicate https://github.com/docker/docker/issues/7472
