### ISSUE TITLE
Inconsistency of volume deletion between 'docker run -rm' and 'docker rm'

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#4356]
When using 'docker run -rm', volumes are deleted (v=1 in the DELETE request).

However, when running 'docker rm', volumes are not deleted by default, as matches the remote API behavior.

Especially as it is now default, I see the necessity of 'docker run -rm' deleting volumes by default. However, this behavior is not well-documented and inconsistent with 'docker rm'.

It may be necessary to change the default of 'docker rm', or simply improve the documentation as to highlight the behavioral differences.

**Comment by cpuguy83** [comment]
Closing since we now have the volume API which can help facilitate cleanup.
Also not generally a good idea to go deleting volume data when a container is removed by default since the data is expected to live beyond the life of the container.
