### ISSUE TITLE
Document local CA management for secure private registry connections

### ISSUE THREAD

**Issue by ewindisch** [docker/docker#4372]
Better than using an "allow insecure ssl" option,  it is far more preferable and secure to advise users to manage their local CAs through their OS' certificate bundle.

The behavior used by Docker is inherited from golang's crypto/x509 package (see: http://golang.org/src/pkg/crypto/x509/)

In short, each OS has a different file (or multiple files) that container CA bundles. These files are, according to the x509 package:

    Ubuntu/Debian - "/etc/ssl/certs/ca-certificates.crt",
    Fedora/RHEL - "/etc/pki/tls/certs/ca-bundle.crt",
    OpenSUSE - "/etc/ssl/ca-bundle.pem",
    OpenBSD - "/etc/ssl/cert.pem",
    MacOS - KeyChain
    Windows - http://support.microsoft.com/kb/295663

Documentation should explain why it is better to update these files (rather than ignore certificates) and provide guidance on establishing a proper and secure configuration.

**Comment by benhosmer** [comment]
Would it make sense to add this new documentation to this: https://github.com/docker/docker/blob/master/docs/sources/articles/https.md or create a new article? I fought with this for a while setting up a private registry and being my own certificate authority.

**Comment by cpuguy83** [comment]
Closing since this is documented here: https://docs.docker.com/engine/security/certificates/#/understanding-the-configuration

It's not the OS specific key stores, but it is the custom store that people can use in `/etc/docker/certs.d`...  feel free to comment if you think I'm off here.
