### ISSUE TITLE
VOLUME instruction prevents a container from starting

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#4393]
If you create a volume that is already a file in the image, ``docker build`` happily completes, but you cannot run it.

```
sven:~/src/docker/tmp$ more Dockerfile

FROM    busybox
ADD     Dockerfile /data
VOLUME  ["/data"]
sven:~/src/docker/tmp$ docker build -t test .
Uploading context  2.56 kB
Uploading context
Step 0 : FROM busybox
 ---> 769b9341d937
Step 1 : ADD Dockerfile /data
 ---> 8ac230d38b08
Step 2 : VOLUME ["/data"]
 ---> Running in d9b8056add13
 ---> abc3d9d282e6
Successfully built abc3d9d282e6
sven:~/src/docker/tmp$ docker run -t -i -name -run_test test bash
2014/03/01 08:27:08 Error: start: Cannot start container 7d8242dd731f8ff0cd89e4f2ac59e5c5eb786e4defc589a531cda116d8fa3a55: readdirent: not a directory
```

**Comment by jfrazelle** [comment]
@cpuguy83 @SvenDowideit is this still an issue?

**Comment by cpuguy83** [comment]
Fix is is #10112 

Fix is a combo of volumes now getting created @ container creation, and adding a check to see if there is already a file there and erroring out.

The error on start was coming from when the execdriver was actually trying to mount over the file.

**Comment by rgbkrk** [comment]
When using the nginx container, I've run into this being an issue when I can't put a new nginx config over the previous, as [outlined in the official nginx image readme](https://registry.hub.docker.com/_/nginx/):

```
/some/nginx.conf:/etc/nginx/nginx.conf:ro
```

**Comment by kirkins** [comment]
I'm also facing this issue while trying to follow the nginx readme. Did you ever find a solution?

**Comment by rgbkrk** [comment]
I just worked around it.

**Comment by Antibioticvz** [comment]
Any solutions?

**Comment by rgbkrk** [comment]
My workaround (way back when) was to switch to building a docker image on deploy and doing an `ADD`: https://github.com/jupyter/tmpnb-deploy/pull/15/files
