### ISSUE TITLE
"Impossible to mount its volumes" when (auto)restarting container with -volumes-from

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#4423]
Hi,

I'm using 0.8.1 with devicemapper. I have a mysql container with a data volume attached with -volumes-from. Several containers use links against this to access the database.

Therefor on reboot docker correctly tries to restart the mysql container first but it fails:

    [debug] runtime.go:159 Container 7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33 was supposed to be running but is not.
    [debug] runtime.go:161 Restarting
    [debug] deviceset.go:230 activateDeviceIfNeeded(7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33)
    [/var/lib/docker|6028185e] +job allocate_interface(7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33)
    [/var/lib/docker|6028185e] -job allocate_interface(7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33) = OK (0)
    [/var/lib/docker|6028185e] +job release_interface(7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33)
    [/var/lib/docker|6028185e] -job release_interface(7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33) = OK (0)
    [debug] deviceset.go:844 [devmapper] UnmountDevice(hash=7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33, mode=0)
    [debug] deviceset.go:881 [devmapper] Unmount(/var/lib/docker/devicemapper/mnt/7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33)
    [debug] deviceset.go:886 [devmapper] Unmount done
    [debug] deviceset.go:754 Waiting for unmount of 7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33: opencount=0
    [debug] deviceset.go:659 [devmapper] deactivateDevice(7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33)
    [debug] devmapper.go:509 [devmapper] removeDevice START
    [debug] devmapper.go:519 [devmapper] removeDevice END
    [debug] deviceset.go:714 [deviceset docker-252:0-5767278] waitRemove(docker-252:0-5767278-7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33)
    [debug] deviceset.go:725 Waiting for removal of docker-252:0-5767278-7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33: exists=0
    [debug] deviceset.go:737 [deviceset docker-252:0-5767278] waitRemove(docker-252:0-5767278-7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33) END
    [debug] deviceset.go:679 [devmapper] deactivateDevice END
    [debug] deviceset.go:898 [devmapper] UnmountDevice END
    [debug] runtime.go:293 Failed to register container 7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33: Container 7c4643ef8df7ef1c23b312ef207faacc5a8958adc4a3af15db81dbbc220d4d33 not found. Impossible to mount its volumes

With this failing, all other containers depending on that fail as well.

Here is the `docker inspect` output for that container: https://gist.github.com/discordianfish/ce4edf3861482d44a7c5

My first thought was that maybe the volume container wasn't loaded but it was just a few lines before that error:

    [debug] runtime.go:284 Loaded container f6ad2764975c7127348dfae08785053ecd2fcf4567e827257f852f7fe2266dbe

Restarting the container manually works fine. After that, I can restart all depending containers as well. So it seems this is either limited to the start up or a race condition (maybe #4036?).

**Comment by MetalArend** [comment]
Is there maybe any progress on this issue?

**Comment by cpuguy83** [comment]
Closing as this doesn't seem relevant anymore.

**Comment by MetalArend** [comment]
Is that because devicemapper is not the default anymore, or is there another issue that solved this that could be referenced?

**Comment by cpuguy83** [comment]
@MetalArend This was probably due to a bug in how volumes-from was handled in the past. Should not happen anymore.
