### ISSUE TITLE
IPv6 support for index

### ISSUE THREAD

**Issue by bernhardschmidt** [docker/docker#4451]
Docker 0.8.0 (on Debian testing) cannot connect to the index using IPv6. It is running on an IPv6-only VM where IPv6-enabled applications can connect to IPv4-only services using NAT64 (http://en.wikipedia.org/wiki/NAT64). In fact the machine is using the public NAT64 of Andrews and Arnold (http://aa.net.uk/kb-broadband-ipv6-nat64.html).

Please enable docker to run dual-stacked towards the index (even if the suckers at Amazon don't support it yet on EC2, the client may need it)

```
root@web:~# wget -O /dev/null https://index.docker.io/v1/search?q=wheezy
--2014-03-04 16:08:45--  https://index.docker.io/v1/search?q=wheezy
Resolving index.docker.io (index.docker.io)... 2001:8b0:6464:0:666:616:36e0:7759, 2001:8b0:6464:0:666:616:36ea:87fb, 54.234.135.251, ...
Connecting to index.docker.io (index.docker.io)|2001:8b0:6464:0:666:616:36e0:7759|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: ‘/dev/null’

    [ <=>                                                                                                  ] 2,085       --.-K/s   in 0.1s    

2014-03-04 16:08:46 (20.6 KB/s) - ‘/dev/null’ saved [2085]

root@web:~# ping6 index.docker.io
PING index.docker.io(ec2-54-234-135-251.compute-1.amazonaws.com) 56 data bytes
64 bytes from ec2-54-234-135-251.compute-1.amazonaws.com: icmp_seq=1 ttl=35 time=99.0 ms
^C
--- index.docker.io ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 99.040/99.040/99.040/0.000 ms
root@web:~# docker.io search wheezy
2014/03/04 16:09:40 Error: search: Get https://index.docker.io/v1/search?q=wheezy: dial tcp 54.224.119.89:443: network is unreachable
```

**Comment by jfrazelle** [comment]
seeing as we have ipv6 support _in_ docker I think it is up to the hub to update now eh @kencochrane

**Comment by jfrazelle** [comment]
So since this is a hub issue this needs to filed with the hub at support@docker.com or forums.docker.com so they can track it

**Comment by FelixWeis** [comment]
Unfortunately it is still not possible to load docker images on machines that only support IPv6. There are actually some cloud providers that give you a discount if you do not allocate an IPv4 address. You can use those IPv6-only machines for backend tasks (postgres, redis, mysql, ...) and IPv4+IPv6 machines as frontend.

Until there is an **AAAA** record for **index.docker.io** and **apt.dockerproject.org** here is my workaround (you will need at least 1 IPv4+IPv6 capable machine tough)

### Installing docker on a IPv6-only machine:
1. use [`apt-mirror`](https://apt-mirror.github.io/) to create a copy of `http://apt.dockerproject.org`, serve it with the v4+v6 machine (nginx will serve well)
2. get the script from https://get.docker.com/ and modify the `/etc/apt/sources.list.d/docker` part to point to your mirror
3. profit!

### Getting docker hub images onto the IPv6-only:
- ssh into the IPv4+IPv6 machine (use `ssh -A` to forward you ssh-agent)
- run a docker-registry locally:
````
docker run -d -p 5000:5000 --name registry registry:2
`````
- pull, retag, and upload the image
```
docker pull nginx
docker tag nginx localhost:5000/nginx
docker push localhost:5000/nginx
````
- ssh from the IPv4+IPv6 into the IPv6-only machine with port forwarding
````
ssh -R 5000:127.0.0.1:5000 admin@ipv6-only 
````
- on the IPv6-only box you can now pull and run the image:
````
docker pull localhost:5000/nginx
docker run -d -p 80:80 localhost:5000/nginx
````
