### ISSUE TITLE
Add a Security best practices to the docs

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#4485]
see https://groups.google.com/forum/#!topic/docker-user/-VWmjLTgbHc

**Comment by jfrazelle** [comment]
i think @ewindisch has added something right?

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/pull/9855 but they can always be improved with a PR

**Comment by ewindisch** [comment]
Thanks. Yes, I added some flavor to the docs and with our expanded security team are working on new docs, blogs posts, and whitepapers.

**Comment by jfrazelle** [comment]
wowww shinyyy I await the PR
