### ISSUE TITLE
docker push to registry with an mdns domain

### ISSUE THREAD

**Issue by dstywho** [docker/docker#4527]
Was unsuccessful pushing to a registry that had an mdns domain.

(this didn't work) docker push docker-registry.local:5000/fedora-puppet-sever 
2014/03/07 07:15:20 Invalid Registry endpoint: Get http://docker-registry.local:5000/v1/_ping: dial tcp: lookup docker-registry.local: no such host

(this worked)docker push 10.14.16.131:5000/fedora-puppet-sever

**Comment by jfrazelle** [comment]
seems to be a problem with either your setup od boot2docker hosts so please open there if this is still an issue
