### ISSUE TITLE
container load metrics from cpuacct.stat

### ISSUE THREAD

**Issue by andrea-spoldi** [docker/docker#4530]
Hi,
 I red throughout this blog post : 
http://blog.docker.io/2013/10/gathering-lxc-docker-containers-metrics/

about gathering containers' metrics.

I wonder how, based upon cpuacct.stats "user" and "system" metrics, how can I say a container is actually full loaded .

Anyone went deeper in it ?

Thanks.

A

**Comment by crosbymichael** [comment]
#9984 was merged so you can now receive cpu, memory, io, network and more via the docker api
