### ISSUE TITLE
"Error: Can't set task name" after restarting docker (0.9.0)

### ISSUE THREAD

**Issue by rutsky** [docker/docker#4639]
After upgrading to 0.9.0 on Ubuntu 13.10 (with docker PPA) I'm getting following error:
```
# docker --version
Docker version 0.9.0, build 2b3fdf2
# docker run busybox ls
2014/03/13 12:20:39 Error: Can't set task name /dev/mapper/docker-252:1-541528-pool
```

**Comment by unclejack** [comment]
*devicemapper issues review session with @vbatts*

@phemmer Can you provide more information about this, please? We need `uname -a` and `docker info`.
Any other information regarding how you've managed to get Docker to throw this error would also be useful and appreciated.

**Comment by phemmer** [comment]
I think this was a random error, not easily reproducible. Unfortunately I stopped using devicemapper a month or so ago because of all the issues with it. Sorry :-(

**Comment by jfrazelle** [comment]
I am going to close then but feel free to ping me with more info on reproducing

**Comment by leifmadsen** [comment]
Not sure if this was the solution, but on my system it seems if you run docker with the default `OPTION="--selinux-enabled"` on a system that SElinux is disabled on, I run into this type of error. Commenting it out from the `/etc/sysconfig/docker` file seemed to have resolved (after a restart).

**Comment by HuffMoody** [comment]
@koterpillar dmsetup mknodes worked for me!

**Comment by tbl0605** [comment]
@HuffMoody  thank you for the tip, `dmsetup mknodes` worked also for me on ubuntu 16.04 with docker 1.11.1 !

**Comment by matiasfessia** [comment]
@koterpillar :1  worked!! with:
docker 1.12.1
ubuntu 16.04
kernel 4.8.0
and a lot of problem with the integred graphic card :(
Thanks!

**Comment by thaJeztah** [comment]
@matiasfessia since you're on a very recent kernel, using the `overlay2` storage driver may be a good alternative; it performs a lot better than devicemapper.

**Comment by arno01** [comment]
Possibly found the cause of the error, please see it in my post here https://github.com/docker/docker/issues/22371#issuecomment-258712905
