### ISSUE TITLE
/var/lib/docker on nodev has problems (obviously) so ought to be warned about

### ISSUE THREAD

**Issue by tianon** [docker/docker#4685]
If you try to use a root that's mounted with "nodev", "nosuid", or "noexec", you'll have some pretty big problems with your containers (obviously).

In my case, I was trying to use a btrfs directory that was mounted via udisks2 inside my GUI file manager, but hadn't noticed that it was mounted with "nodev".  Once I ran a container, I couldn't do things like `apt-get install` because they tried to write to "/dev/null" which was on a nodev filesystem so obviously wouldn't work.

What I'd propose is that any of these problematic mount options become a warning at daemon startup.

**Comment by crosbymichael** [comment]
Since `/dev/` is always mounted in a tmpfs and decoupled from the rootfs mount options this shouldn't be an issue anymore ;)
