### ISSUE TITLE
Add capability to specify portallocator port range

### ISSUE THREAD

**Issue by vania-pooh** [docker/docker#4736]
According to this: https://github.com/dotcloud/docker/blob/v0.9.0/networkdriver/portallocator/portallocator.go port range used to expose container ports to outside world is hardcoded. This doesn't seem to be good. It would be great to be able specify this port range as a configuration option in a file or as command argument.

**Comment by jfrazelle** [comment]
we have https://github.com/docker/docker/pull/8412 does that solve the problem

**Comment by vania-pooh** [comment]
@jfrazelle let's then close this issue.
