### ISSUE TITLE
docker logs -f is not following logs anymore

### ISSUE THREAD

**Issue by jamtur01** [docker/docker#4801]
Client version: 0.9.0
Go version (client): go1.2.1
Git commit (client): 2b3fdf2
Server version: 0.9.0
Git commit (server): 2b3fdf2
Go version (server): go1.2.1

I have a daemonized container:

   $  docker run -d ubuntu /bin/sh -c "while true; do echo hello world; sleep 1; done"

I run docker logs -f and would expect to follow the logs and have "hello world" echo'ed. Instead I see:

    $ docker logs -f ab1d6c9e6ee4
    hello world 
    hello world 
    hello world
    $

If I run the command again I see 1-10 hello world's echo'ed on the terminal before the command exits.

**Comment by jfrazelle** [comment]
closing, this has been fixed, but feel free to ping me if you are still seeing the issue on the lastest version of docker

**Comment by akpankit** [comment]
i am having same issue again, it followed the logs for first 2 days and then it stopped. Everytime i do follow it returns random chunks of the logs and exits with prompt. Re-making container fixes eat but this is happening every 3-4 days, its frustrating.
