### ISSUE TITLE
Trusted builds - don't build every dockerfile in repo

### ISSUE THREAD

**Issue by brainsiq** [docker/docker#4806]
If I setup two trusted builds from the same repository, but looking at different locations for Dockerfiles (see https://github.com/microslondon/dockerfiles) then both files get built every time a push occurs.

It looks as though it might also be rebuilding when the README.md is also changed.

I think if you supply a Dockerfile location in the trusted builds configuration then it should only rebuild when that specific file is updated.

**Comment by jfrazelle** [comment]
closing as duplicate of https://github.com/docker/docker/issues/7480
