### ISSUE TITLE
Mark container as needing to run with --privileged

### ISSUE THREAD

**Issue by dlewanda** [docker/docker#4852]
I apologize if this was covered elsewhere, but I couldn't find any reference to anything like it. I'd like to be able to set a flag in the Dockerfile that doesn't allow the container to run if --privileged=true is not set. We have some containers that should never be run without --privileged and it would be helpful to be reminded of that and bail out rather than start up half-baked.

**Comment by jfrazelle** [comment]
ping @dlewanda  does using an entrypoint command solve your issue?

**Comment by dlewanda** [comment]
Sorry, I changed jobs and have been out of the project that was using privileged containers for about 6 months. I would have to recreate the scenario and get back to you, but I don't know when I'll have an opportunity.
 

     On Wednesday, February 25, 2015 1:48 PM, Jessie Frazelle <notifications@github.com> wrote:
   

 ping @dlewanda does using an entrypoint command solve your issue?—

**Comment by jfrazelle** [comment]
ok no prob

**Comment by jfrazelle** [comment]
I think this will help with this one https://github.com/docker/docker/issues/6839 as well as https://github.com/docker/docker/pull/8955 https://github.com/docker/docker/pull/9882 so closing as dup
