### ISSUE TITLE
Supervisor works when call service docker stop?

### ISSUE THREAD

**Issue by trungtan** [docker/docker#5137]
Hi everyone,

I'm trying to manage processes inside a container using supervisor.

I expected supervisor was able to foward all SIGTERM to it's sub-processes (apache, memcache, mysql...) .

With my Dockerfile below, supervisord run with PID 1 and it managed all its sub-processes. When I stop the running container, all sub-processes shut down probably with SIGTERM in their logs (e.g: /var/log/apache2/error.log).

The problem is when I restart docker service, I've seen sub-processes don't receive SIGTERM, they don't clean their pid files too.

Anyone in my case? Is that the way supervisor works, or because of my wrong configuration? Any other ways to restart docker service with all sub-processes shutdown properly?

Thank you.

```
FROM ubuntu:12.04

MAINTAINER trungtanbui@gmail.com

RUN echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y supervisor

RUN touch  /etc/supervisor/conf.d/supervisord.conf && \
    echo "[supervisord]" >> /etc/supervisor/conf.d/supervisord.conf && \
    echo "nodaemon=true" >> /etc/supervisor/conf.d/supervisord.conf

RUN apt-get install -y memcached apache2 htop

# start memcached
RUN touch /etc/supervisor/conf.d/memcached.conf && \
	echo "[program:memcache]" >> /etc/supervisor/conf.d/memcached.conf && \
	echo "command=/usr/bin/memcached -m 64 -p 11211 -u memcache -l 127.0.0.1 -DFOREGROUND" >> /etc/supervisor/conf.d/memcached.conf && \
	echo "autostart=true" >> /etc/supervisor/conf.d/memcached.conf && \
	echo "autorestart=true" >> /etc/supervisor/conf.d/memcached.conf

# start apache2
RUN touch /etc/supervisor/conf.d/apache2.conf && \
	echo "[program:apache2]" >> /etc/supervisor/conf.d/apache2.conf && \
	echo 'command=/bin/bash -c "source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND"' >> /etc/supervisor/conf.d/apache2.conf && \
	echo "autostart=true" >> /etc/supervisor/conf.d/apache2.conf && \
	echo "autorestart=true" >> /etc/supervisor/conf.d/apache2.conf

EXPOSE 8080:80

CMD ["/usr/bin/supervisord"]
```

**Comment by sumkincpp** [comment]
For similar configuration with ubuntu:14.04 image and latest docker (1.4.1) I've got it working.
Supervisord was running in foreground(nodaemon=true).

@trungtan haven't you resolved that issue? I've tried to build your Dockerfile but have no success due to broken ubuntu updates.

**Comment by jfrazelle** [comment]
this should work on the latest version of docker, I have noticed a few images on hub using supervisord
