### ISSUE TITLE
Ubuntu packages should not have version number in the name

### ISSUE THREAD

**Issue by stucki** [docker/docker#5228]
Why do the Ubuntu packages provided by Docker contain the version number in the package name?

This has several drawbacks:
* Two packages are needed: "lxc-docker" which is a meta-package just depending on the latest version, and "lxc-docker-x.y.z" which contains the actual data.
* New versions are not automatically upgraded like the rest of a system, because new packages need to be installed. "apt-get upgrade" won't work, you need to run "apt-get dist-upgrade" to install the latest version.
* Configs of old versions remain installed:
```
$  dpkg -l | grep docker
ii  lxc-docker                             0.10.0                                                                  Linux container runtime
ii  lxc-docker-0.10.0                      0.10.0                                                                  Linux container runtime
rc  lxc-docker-0.6.4                       0.6.4                                                                   lxc-docker is a Linux container runtime
rc  lxc-docker-0.6.5                       0.6.5                                                                   lxc-docker is a Linux container runtime
rc  lxc-docker-0.6.6                       0.6.6                                                                   lxc-docker is a Linux container runtime
rc  lxc-docker-0.6.7                       0.6.7                                                                   Linux container runtime
rc  lxc-docker-0.7.1                       0.7.1                                                                   Linux container runtime
rc  lxc-docker-0.7.2                       0.7.2                                                                   Linux container runtime
rc  lxc-docker-0.7.6                       0.7.6                                                                   Linux container runtime
rc  lxc-docker-0.8.0                       0.8.0                                                                   Linux container runtime
rc  lxc-docker-0.8.1                       0.8.1                                                                   Linux container runtime
rc  lxc-docker-0.9.0                       0.9.0                                                                   Linux container runtime
rc  lxc-docker-0.9.1                       0.9.1                                                                   Linux container runtime
```

Unless there is a good reason to use this non-standard approach, I recommend to use a unique package name and simply increment the version number of it.

**Comment by jfrazelle** [comment]
i added the label invalid until reprepo is fixed upstream, seemed appropriate

**Comment by andrewpollock** [comment]
I think the big difference between the example of the Linux kernel package and Docker is that the Linux kernel image packages are intended to be installed side by side and as such don't introduce any file conflicts with each other. That isn't the case with here.

I've spent a bit of time this afternoon looking at if there's a more appropriate way to express the dependencies between the lxc-docker meta package and the versioned lxc-docker-X.Y.Z packages, and I don't think there is a way to actually do it.

From my understanding of reading this bug history, you're allowing the deficiencies in the way you're managing your package repository to bleed into the way you're packaging your software. The (rather bad, IMO) side-effect is that you're making it impossible for your customers to properly upgrade your software using distribution-standard mechanisms.

I'll continue trying to find a solution by adjusting the package relationships between the meta package and the versioned packages, but I don't have a lot of confidence in it being possible.

I think having the lxc-docker-virtual-package virtual package also just further confuses the issue.

**Comment by stucki** [comment]
Looking at the past comments again, I wonder about this:

Quote @tianon:
> I agree in principle that after Docker 0.9.1 is out, nobody should want 0.7.0, but the reality isn't there. There are a ton of users who regularly install the older versions, including and especially to get an older client to connect to some older daemons that they can't upgrade yet.

Do you think this still applies? I don't think so (and never did).
Ever since I'm working with Docker I never had a single reason to go back to an older version. So, what's that scenario and how many users will really need it?

Unfortunately, waiting for reprepro doesn't help us much because it seems there's no further work done regarding this patch. So what about a more manual way: provide all outdated packages in an archive folder which is browsable for users? This would allow someone to download an old version and install it manually using `dpkg -i <filename>.deb`.

**Comment by stucki** [comment]
If you agee then I can take care of adding the changes to the release script. Let me know!

**Comment by tianon** [comment]
It might make sense to split out our repos into one-repo-per-major-version,
like some projects do, but that makes it harder for users to just "get the
latest" unless we also manage a "latest" alias.

**Comment by stucki** [comment]
You could create multiple repositories for that if really needed. But I still find that too complicated and I still doubt if someone really needs an older version. Even if, then he could also just install the "docker.io" package which is shipped with Ubuntu out of the box.

**Comment by stucki** [comment]
Any feedback here? I just did an ```apt-get upgrade``` on my Ubuntu 14.04 with the result that the Docker 1.6.0 upgrade was skipped because of this issue.

**Comment by pdevine** [comment]
I have a patch which looks through the git tags for each of the older docker versions and then creates conflicts on each of those packages.  This lets `apt-get upgrade` work properly.  It's a little hacky, but it's the only way that I could think of (short of changing the name of the package) to get the ubuntu package to behave somewhat sanely.

If anyone is interested I'll create a pull request.

**Comment by fedir** [comment]
I just made a test :

    $ docker -v
    Docker version 1.2.0, build fa7b24f

    $ sudo aptitude install lxc-docker

    $ docker -v
    Docker version 1.6.2, build 7c8fca2

So, with "install" it works. Normally, should work with "upgrade" also.

**Comment by stucki** [comment]
Well, you're trying with aptitude, I have used apt-get. Even if it works fine with aptitude, that doesn't solve the problem for apt-get users. Afaik, aptitude is not installed by default on Ubuntu...

```
$  sudo apt-get upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  lxc-docker
The following packages will be upgraded:
  efibootmgr firefox firefox-locale-de firefox-locale-en grub-common [...]
14 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Need to get 0 B/44.1 MB of archives.
After this operation, 198 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
```

**Comment by mattdr** [comment]
@jfrazelle Any chance this is fixed with the move to 'docker-engine'?
https://blog.docker.com/2015/07/new-apt-and-yum-repos/

**Comment by cpuguy83** [comment]
Yp, indeed it is.
Closing.

**Comment by stucki** [comment]
Thanks guys! Finally!! :+1:

**Comment by thaJeztah** [comment]
:tada:
