### ISSUE TITLE
 Private Repos from CLI? - UX p2-3

### ISSUE THREAD

**Issue by henrydesignmap** [docker/docker#5237]
The workflow to create a repo usually happens from the CLI, except in the case of private repos. Would it be possible to call out that a repo is public vs private from the CLI?

What I think would be good is if we could implement the following improvements on Docker itself:

* Add a flag ``docker push --private=true <repo>`` so a private repository can be created without initializing it on the index first

or even:

* Default to private.
* Fail if the user has no private repositories allotted -- with a friendly notice that the user can do ``docker push --public`` to push to a private repository.

**Comment by termie** [comment]
-subscribe-

**Comment by cpuguy83** [comment]
This one is weird because a private repo is specifically a feature of DockerHub and not of the registry itself.
I think it would be best to error out if the repo doesn't already exist (or at least have a setting on hub accounts to enable such a thing).

**Comment by cpuguy83** [comment]
I've moved this to: docker/hub-feedback#346
Closing since it doesn't really belong in engine.

Thanks!
