### ISSUE TITLE
LXC exec driver:  lxc-start: failed to open log file "/var/lib/lxc/{container-id}/{container-id}.log" : No such file or directory

### ISSUE THREAD

**Issue by wking** [docker/docker#5242]
With the LXC exec driver (`-e lxc`) and Docker v0.9.1, I'm getting errors like:

    lxc-start: failed to open log file "/var/lib/lxc/{container-id}/{container-id}.log" : No such file or directory

Joh [bumped into this with Docker v0.5.0 and v0.6.1][1], but the suggested solution was to install iproute2 in the image (maybe not directly related to the lxc error?).  The containers seem to run fine despite the lxc-start failure, but it makes me jumpy ;)

It looks like it happens in most of my builds:

    Step 0 : FROM wking/gentoo-syslog:20140410
     ---> 871337e144df
    Step 1 : MAINTAINER W. Trevor King <wking@tremily.us>
     ---> Using cache
     ---> 0b9a1f954a32
    Step 2 : RUN emerge -v layman
     ---> Running in 3c7d1a6ce1af
    lxc-start: failed to open log file "/var/lib/lxc/3c7d1a6ce1af336da03fcb7d01ea6cf6c4013a191e0946376073ac0cf48f617d/3c7d1a6ce1af336da03fcb7d01ea6cf6c4013a191e0946376073ac0cf48f617d.log" : No such file or directory
    …

and also with direct `run`s:

    $ docker.io run -t -i wking/gentoo /bin/bash
    lxc-start: failed to open log file "/var/lib/lxc/bd9ee5cf0ec97da2e06fdac832e606c1e227ee4076a06c253c2044e445f6f067/bd9ee5cf0ec97da2e06fdac832e606c1e227ee4076a06c253c2044e445f6f067.log" : No such file or directory
    bd9ee5cf0ec9 / # 

As expected, emerging sys-apps/iproute2 doesn't seem to fix the problem:

    $ docker.io run -t -i wking/gentoo-portage /bin/bash
    lxc-start: failed to open log file "/var/lib/lxc/c84637dc2dc77c4d033806c531f2b05a570dfb0c7f3fcebe8b0fe2f9471629ba/c84637dc2dc77c4d033806c531f2b05a570dfb0c7f3fcebe8b0fe2f9471629ba.log" : No such file or directory
    c84637dc2dc7 / # emerge -v iproute2

    These are the packages that would be merged, in order:

    Calculating dependencies... done!
    [ebuild  N     ] net-firewall/iptables-1.4.20  USE="ipv6 -netlink -static-libs" 535 kB
    [ebuild  N     ] sys-apps/iproute2-3.8.0  USE="berkdb iptables ipv6 -atm -minimal" 399 kB

    Total: 2 packages (2 new), Size of downloads: 933 kB
    …
    c84637dc2dc7 / # exit
    $ docker.io commit -m 'with iproute2' c84637dc2dc7 wking/gentoo-iproute2
    # docker.io run -t -i wking/gentoo-iproute2 /bin/bash
    lxc-start: failed to open log file "/var/lib/lxc/9ac87e5c212d8a555669d8f6c75d98864758ea7f56c93671794f2ca7e3e09c43/9ac87e5c212d8a555669d8f6c75d98864758ea7f56c93671794f2ca7e3e09c43.log" : No such file or directory
    9ac87e5c212d / # 

The host system is Debian unstable with docker.io-0.9.1~dfsg1-2 and lxc-1.0.0.8.

[1]: https://groups.google.com/forum/#!msg/docker-user/yXOt3qISHXU

**Comment by jfrazelle** [comment]
can you try again with lxc 1.0.7 and the latest version of docker thanks

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen
