### ISSUE TITLE
Do not display empty TOC

### ISSUE THREAD

**Issue by creack** [docker/docker#5288]
When there is nothing to show in TOC, maybe we could hide it or display the main title?

Example on contribution:
![screen shot 2014-04-17 at 3 56 00 pm](https://cloud.githubusercontent.com/assets/521701/2737901/8a524fe0-c683-11e3-89a3-1fa97a2726d4.png)

/cc @SvenDowideit @ostezer @jamtur01

**Comment by surfjedi** [comment]
#11648

**Comment by surfjedi** [comment]
#dibs

**Comment by nhsiehgit** [comment]
@jfrazelle I believe this is closed by: https://github.com/docker/docker/pull/8528

**Comment by jfrazelle** [comment]
awesome thanks! sorry @surfjedi
