### ISSUE TITLE
[DISCUSS] add link metadata to Dockerfile

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#5332]
This is meant to be a discussion.  Currently, if you try to build a UI for docker you end up with what I think is a usability issue with links.  When you create a container from an image, the container may be looking for links of a certain name but that information is not know unless you created the image yourself, or it's in some documentation somewhere.  All you can do from a UI perspective is allow people to specify a containers and link names, but the name may or may not be correct.

What I propose is that somehow we allow the Dockerfile to say what links its looking for.  Minimally we just need the name.  One example could be

```
FROM ubuntu
...
LINKS ["mysql", "graphite"]
```

All that will do is indicate the container is looking for a link named "mysql" and "graphite."  Then the user interface will be able to query the image json from the index/registry and display a better UI for linking containers.  If this sounds fine, I can implement this, as all we are doing is just adding some metadata to the json but not really operating on it in any fashion.

**Comment by jfrazelle** [comment]
just associating this with https://github.com/docker/docker/pull/9882 so we dont forget

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
