### ISSUE TITLE
docker kill doesn't free network resources

### ISSUE THREAD

**Issue by kruxik** [docker/docker#5376]
If I kill together-linked docker containers in different order then they where created/started an orphan network device is there for couple of minutes (until it times out).

If I kill docker containers in the exact order I created/started them, the issue doesn't occur.

I use `docker kill` sometimes when container is 100% read-only (doesn't create any data) to quickly stop it.

**Comment by jfrazelle** [comment]
@kruxik can you reproduce on the latest version and if so can you give exact steps to reproduce

**Comment by kruxik** [comment]
@jfrazelle Nope, the last production version (1.5.0) is not affected by this issue. I have checked this 5-6 times and no problem has occurred so far.

**Comment by jfrazelle** [comment]
Awesome thanks I am going to close then but if anyone else sees it lmk
