### ISSUE TITLE
ICC sometimes breaks when starting many containers at once

### ISSUE THREAD

**Issue by mattymo** [docker/docker#5384]
It's quite hard to provide an example for devs to reproduce this, but my environment is this:
1 core VM in VirtualBox with 1.5gb memory on SSD

80% of the time when deploying several containers from source and then starting them (each with exposed ports), nothing breaks. However, sometimes ICC ends up broken.

I've discovered this is fixed if I add this rule:
iptables -A POSTROUTING -t nat -o docker0  -j MASQUERADE

**Comment by jfrazelle** [comment]
@mattymo is this still an issue on the latest version?

**Comment by jfrazelle** [comment]
Looks like we are now adding an equivalent of thise Masqerade rule, closing, but feel free to ping me if you feel this was closed in error
