### ISSUE TITLE
Add flag to allow adding additional paths to the build context

### ISSUE THREAD

**Issue by dustinlacewell** [docker/docker#5390]
`docker build` should support a runtime flag that allows a build to incorporate paths outside of the build context in an explicit manner.

Let's imagine you have 5 different images that all share a bit of code. Currently you have a few options:

* Duplicate the code for all the build contexts (now you have to maintain several 'forks' this code)
* Write a pre-build system for Docker's build system (just... no)
* Utilize local bind mounts so Docker cannot even know you're importing data from outside the build context (requires bind targets to already exist, messes up git and other methods of transferring the repository. you can't easily move it.)
* Build the shared code into a base image and inherit from this image.

There are some annoying aspects to this last solution. If you modify the shared code, you incur a bit of pain in rebuilding all of the child images. If your child images have apt-get dependencies or the host performs builds slowly you can spend a bit of your time waiting around. If you're *iterating* on this shared code, you probably feel real pain.
 
With a flag to allow the builder to *explicitly* expose paths of the host, one could simply symlink the shared code into the build context for each of the images. It would require explicit awareness from whoever is performing the build. I am thinking, it being explicit lightens the security surrounding the concern of allowing out-of-context data from entering the build, say from a rogue Dockerfile trying to ADD your /etc/passwd, etc.

**Comment by ThomasSteinbach** [comment]
+1
I am building Ansible playbooks during the image build. Ansible assumes additional context information under /etc/ansible/roles. Currently I run the docker build command within a shell script, that is copying the roles directory into the build context and removes it after the build. Allowing to add additional paths to the build context would look much nicer.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
