### ISSUE TITLE
Dealing with a strictly controlled firewall

### ISSUE THREAD

**Issue by timstoop** [docker/docker#5434]
Hi,

We'd like to use Docker in a setup where the firewall is strictly controlled by ferm via puppet. The trouble we're running into is that ferm needs all rules in its own config, any changes performed by external applications (like docker) will get removed by ferm when it reloads. Which is a bit of a problem when you've bound ports to docker containers.

Aside from disabling ferm entirely (which is sadly not an option in this environment), I see only three ways around that, all of them require changes in docker:

1. Fixed IP addresses for docker containers, so we know in advance which port on which IP address needs to be masqueraded and we can add it to the ferm config statically.

2. Add an option to docker that makes it reload it's firewall config and set it up anew. This would be slightly problematic, since it would break already running connections, but at least it would allow me to get the config.

3. Make docker 'request' the firewall changes from some script that automagically creates the required ferm config and adds it in the ferm.d directory. Docker would invoke a script and sent its information in some format (json?) to the stdin of the script.

The first one is probably preferred, since it allows us to take the config change into account in config management (and thus, in version control). But maybe I'm overlooking already implemented solutions for this? On IRC it was recommended to simply open all the ports, but that's not an option.

I'd appreciate some input to this problem.

**Comment by jfrazelle** [comment]
All the iptables rules are in a Chain called docker, you could run a `iptables-save` and `iptables-restore` to bring them back up.

Also you can used assign a `fixed-cidr`.

See the networking articles here: http://docs.master.dockerproject.com/articles/networking/

**Comment by leucos** [comment]
@timstoop you could use [pre/post ferm hooks](http://ferm.foo-projects.org/download/2.3/ferm.html#Hooks) for this, and call helper scripts:

```
# !/bin/bash
# pre_script
iptables -S DOCKER -t nat > /etc/saved_rules/nat_DOCKER
iptables -S DOCKER > /etc/saved_rules/filter_DOCKER
iptables -S DOCKER-ISOLATION > /etc/saved_rules/filter_DOCKER-ISOLATION
```

```
# !/bin/bash
# post_script
for table in nat filter; do
  for chain in /etc/saved_rules/${table}_*; do
    iptables-restore -n ${table}_${chain}
  done
done
```

Not tested, might work :)
