### ISSUE TITLE
Dropped events

### ISSUE THREAD

**Issue by shykes** [docker/docker#5456]
`docker events` can lose messages if they are sent too rapidly. This is because of a race condition in the way listeners are traversed and checked for availability.

/cc @vieux

**Comment by cpuguy83** [comment]
@LK4D4 Can this be closed now since the events stuff was re-written?

**Comment by thaJeztah** [comment]
ping @LK4D4 can this be closed? https://github.com/docker/docker/issues/5456#issuecomment-119317492

**Comment by aanm** [comment]
>I don't see any races in events now, but there is problem that if we have bad listener who don't want to recv message we stop entire publishing process for 100ms.

Isn't a better way to deal with that? I mean, why should a bad listener break the whole environment?

**Comment by LK4D4** [comment]
@aanm it's not breaking environment, it's slightly slows it :) Another way is to evict slow listener or spawn each in it's own goroutine.
@thaJeztah yes, this can be closed, thanks.
