### ISSUE TITLE
Feature Request: Support rapid developer edit debug cycle with new "docker dev"

### ISSUE THREAD

**Issue by mdelder** [docker/docker#5499]
With discussions with Solomon, a proposal arose to support a new developer centric function focused on fast iteration. 

I would like to use docker to not only to containerize an application but also develop it. Today, the cycle of running a docker build for each source code change is an impedance to productivity. 

The new proposed function would:

- Define new CLI "docker dev" command. 
- "docker dev" would use a Dockerfile to bring up a running instance and leave open a shell to provide access to STDIN, STDOUT, or "tail -f" an application log to my current console opinion the host OS. 
- When the developer hits CTRL+C, the container would terminate and restart the container processes and return the prompt. 
- The Dockerfile would include directives to mount one or more directories of source code for interpreted languages or directories with built Objects like Java .classes. 
- As the developer makes changes and wants to test or debug the change, the fast restart from CTRL+C would not only restart the running process (python interpreter, IBM Liberty Java web application, etc) but also ensure currency from the mounted directories of deployable artifacts. 
- Finally, when the developer wants to capture the current state, they might enter an additional keystroke CTRL+S to automatically commit the current running state to a new container, the equivalent of a docker build.

**Comment by cpuguy83** [comment]
Hmm, seems like this belongs in something higher-level than docker... all the building blocks are there.
I think this one should be closed.

**Comment by unclejack** [comment]
@cpuguy83 This has been discussed for a long time (as early as mid of 2013) and it needs to be implemented.

**Comment by cpuguy83** [comment]
@unclejack I'd argue that it is implemented, between `docker run -v $(pwd):/container/path` and `docker exec`.
Also docker-compose.

**Comment by calavera** [comment]
> Hmm, seems like this belongs in something higher-level than docker... all the building blocks are there.
> I think this one should be closed.

I agree. Closing.
