### ISSUE TITLE
Sending signals to docker container with lxc-stop is useless for LXC 1.0.0 and above

### ISSUE THREAD

**Issue by elgris** [docker/docker#5651]
Hello guys!
First of all, thanks for Docker! Unfortunately, LXC version 1.0.0 and above brings some problems that may be worth mentioning in documentation.

Basically, it doesn't allow docker to forward signals to running containers.
Docker's function `stop` and `kill` use following line of code:
https://github.com/dotcloud/docker/blob/master/daemon/execdriver/lxc/driver.go#L244

As per LXC documentation, `lxc-stop` doesn't provide any parameter that passes signal to container. Instead, `lxc-stop -k` just kills the process with default stop signal (I assume it's SIGKILL):
https://github.com/lxc/lxc/blob/master/doc/lxc-stop.sgml.in#L103
https://github.com/lxc/lxc/blob/6168ff15aac16bcccbcf22b4ba915870844e96a4/src/lxc/commands.c#L600

Thus, despite documentation for `docker stop` says that it sends SIGTERM signal, in fact, container receives SIGKILL signal generated by underlying `lxc-stop -k` call.

Also, it seems `--signal` argument of `docker kill` becomes useless - you can set any signal, but container will receive SIGKILL.

Could you please advise, is there any workaround for this situation?
At the moment I have to stick to LXC v.0.9.0 just because I need to stop my container with SIGTERM signal. With 0.9.0 `docker stop` works just fine, with 1.0.3 it sends SIGKILL instead of SIGTERM.

**Comment by jfrazelle** [comment]
can you please try with the latest version of docker and lxc 1.0.7

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen

**Comment by tomasz-kuzemko** [comment]
https://github.com/docker/docker/blob/master/daemon/execdriver/lxc/driver.go#L524 problem is that last argument to `lxc-stop` which is `strconv.Itoa(sig)` is simply ignored by `lxc-stop`. With `-k` option it always sends SIGKILL. It seems there is no way to specify what signal should be sent. To best support behaviour promised by `docker stop`, it should call `lxc-stop -n <id> -t <timeout>` which first sends SIGTERM and after timeout - SIGKILL.
