### ISSUE TITLE
OSX complains about docker causing excessive wakeups

### ISSUE THREAD

**Issue by imavroukakis** [docker/docker#5654]
Under OSX 10.9.2 I frequently see this in my system log
```
May  7 13:49:16 spazstik kernel[0]: process docker[1132] caught causing excessive wakeups. Observed wakeups rate (per sec): 2520; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45102
May  7 13:49:16 spazstik ReportCrash[1137]: Invoking spindump for pid=1132 wakeups_rate=2520 duration=18 because of excessive wakeups
May  7 13:49:17 spazstik spindump[1138]: No microstackshots found
```

This is usually while building images and is followed by increased fan activity as the cores start burning a little hotter. Is this a byproduct of OSX trying to micromanage resources?

**Comment by jfrazelle** [comment]
is this still a problem with the latest release, and if it is a boot2docker specific problem can you please open an issue on that repository

**Comment by jfrazelle** [comment]
closing as stale, but ping me or open on boot2docker if still an issue
