### ISSUE TITLE
migrating from lxc-docker package to docker.io breaks docker

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#5688]
(on a just installed 14.04)

curl https://get.docker.io | sh
sudo apt-get install docker.io

(the second removes our package, and installs the ubuntu one)

leaves us with `service --status-all` listing 2 services: `docker` and `docker.io`

which makes me think our lxc-docker package is not cleaning up quite well enough.

rebooting at this point leaves us with a happily working Docker 0.9.1

then `ln -s /usr/bin/docker.io /usr/bin/docker` and rebooting causes things to go bad.

on my system, there is only one docker daemon running, but its un-contactable.

`service docker stop` does nothing, as its not running
`service docker.io stop` stops the rogue daemon, and then 
`service docker.io start` makes everything happy again.

similarly, after stopping which ever service is  running, 
`service docker start` works.

so its probably _just_ something that happens if you start 2 daemons at almost the same time.

**Comment by jfrazelle** [comment]
@SvenDowideit so is this a docs problem where we need to explain it better or...

**Comment by mika** [comment]
JFTR, since docker.io v1.3.1~dfsg1-2 in Debian the docker.io symlink no longer exists.

**Comment by jfrazelle** [comment]
debian folks are smart hehe
