### ISSUE TITLE
Change the behavior when using "run -h" option

### ISSUE THREAD

**Issue by ghartz** [docker/docker#5695]
Current behavior:

"docker run --rm -i -t -h ilovedocker ubuntu bash" will create a CT with hostname "ilovedocker" but with a random "--names" like "elegant_ptolemy".

Desired behavior:

when -h is specified make the same "--names" as "-h" if "--names" is empty

Alternate behavior:

"docker ps" show hostname too

**Comment by jfrazelle** [comment]
I don't think we do want the relationship closing but feel free to give use cases as to why they should be related
