### ISSUE TITLE
error using chpasswd with host networking and ubuntu:14.04 image

### ISSUE THREAD

**Issue by sameersbn** [docker/docker#5704]
when using chpasswd command on the ubuntu:14.04 image with and without host networking yields different results.

without host networking there is not issue using the chpasswd command
```bash
docker run -i -t --rm  ubuntu:14.04 bash
echo "root:secretpasswod" | chpasswd
```
with host networking the chpasswd command doesn't work 
```bash
docker run -i -t --rm --net='host' ubuntu:14.04 bash
echo "root:secretpasswod" | chpasswd
chpasswd: (user root) pam_chauthtok() failed, error:
System error
chpasswd: (line 1, user root) password not changed
```

**Comment by jfrazelle** [comment]
this is fixed on master 
```
jessie at debian in ~
$ docker run -i -t --rm  ubuntu:14.04 bash
root@02dbaa0ea2ba:/# echo "root:secretpasswod" | chpasswd
root@02dbaa0ea2ba:/# exit
exit

jessie at debian in ~
$ docker run -i -t --rm --net='host' ubuntu:14.04 bash
root@debian:/# echo "root:secretpasswod" | chpasswd
root@debian:/# exit
exit

```

**Comment by teraproc** [comment]
I met the same issue in the latest ubuntu:14.04 image as follows. Any idea?

root@olnode1:~# docker run -i -t --rm --net='host' ubuntu:14.04 bash
root@olnode1:/# echo "root:secretpasswod" | chpasswd
chpasswd: (user root) pam_chauthtok() failed, error:
System error
chpasswd: (line 1, user root) password not changed
root@olnode1:~# docker -v
Docker version 1.7.1, build 786b29d

**Comment by JonasT** [comment]
Just having this happen with kernel 4.14 and docker 1.13.1. Are there any workarounds? I'm not using host networking either...

**Comment by AlexeyPlodenko** [comment]
For those coming from the search engines...

In my case the password was too simple and needed to use a stronger one, using the capital and small letters, digits and symbols. For ex, P2sswrd!!!
