### ISSUE TITLE
-p <outside>:<inside> with --net container:<name> does not work

### ISSUE THREAD

**Issue by thockin** [docker/docker#5725]
Naively I would expect this to work, but it does not.

```
# #First create a "normal" container, mapped to host port 1001
# docker run -d --name mynet -p 1001:1001 ubuntu bash -c "while true; do echo 'hello from mynet' | nc -l -p 1001 -q 0; done"
a8821db6b120c9eb5fa21ea1f82d1b47e43cb076cf073c4f707d72d9905832ee

# #Prove it works
# nc localhost 1001
hello from mynet

# #Create a container which uses the same network namespace
# docker run -d --name helper --net container:mynet -p 1002:1002 ubuntu bash -c "while true; do echo 'hello from helper' | nc -l -p 1002 -q 0; done"
01f5e70230d36b1b83a101ba037d68a1fa9062e12ab7c2bf7c978f7a24872488

# #Observe that the host port is not mapped, though the port is open inside
# nc localhost 1002
localhost [127.0.0.1] 1002 (?) : Connection refused
# docker inspect mynet | grep IPAddr
        "IPAddress": "172.17.0.2",
# nc 172.17.0.2 1001
hello from mynet
# nc 172.17.0.2 1002
hello from helper
```

**Comment by jfrazelle** [comment]
this is also related https://github.com/docker/docker/issues/9340

**Comment by cpuguy83** [comment]
This now gives a proper error: `Conflicting options: port publishing and the container type network mode`

Closing, thanks!

**Comment by eMPee584** [comment]
Well, the nice descriptive error message does not help with this legit use case: attaching an ad-hoc DB admin GUI container to an ansible-managed DB container and making it accessible via SSH tunnel to investigate db issues.. as in
`docker run -it --rm --publish 7799:8080 --network=container:matrix-postgres adminer sh`
How else could this be done, not changing the already running container to publish that port?

**Comment by cdaringe** [comment]
@eMPee584, any progress? (sorry others, for issue noise 🤦 )
