### ISSUE TITLE
Parametrized Dockerfiles

### ISSUE THREAD

**Issue by agrafix** [docker/docker#5793]
Consider the following scenario: You want to build multiple docker images containing two programs (A and B; B depending on A) in different Version configurations (eg. A 1.0 with B 2.2; A 2.5 with B 2.2; A 2.5 with B 2.5; ...). Currently you'd need some script containing a Dockerfile template and then generate lot's of Dockerfiles for this. I propose this solution:

* A `VAR` command in Dockerfiles, with the following syntax: (default is required)

    VAR varname default

* Variable interpolation in Dockerfile commands

    RUN echo "Version $$VARNAME$$"

* Set the Variables using a `-v` flag in `docker build`

    docker build -v localVersion:1.2 -t "agrafix/releaseImage:1.2" .

**Comment by cpuguy83** [comment]
Dockerfile's now expand envvars for all commands.  Is this sufficient?  Can we close this?

**Comment by duglin** [comment]
I don't think it does cover it - see https://github.com/docker/docker/pull/9176 - I think that discussion is related to what @agrafix wants.

**Comment by agrafix** [comment]
Yes, #9176 does look very promising!

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
