### ISSUE TITLE
Moving a file from the host system to a container via docker cp

### ISSUE THREAD

**Issue by jamtur01** [docker/docker#5846]
The `docker cp` command can currently copy a file from the container to the host. It should also be able to do the reverse.

Ping @crosbymichael

**Comment by jlhawn** [comment]
I've been working on this and other general improvements to `docker cp` over in this PR: https://github.com/docker/docker/pull/9871

Here's the description of it:

# Improve `docker cp`

This command currently uses the following HTTP API endpoint:

	POST /containers/(id)/copy

This endpoint only supports copying files/directories from a container to the
client. Its behavior is also odd in that `DEST` is always treated as a
directory. It would be preferrable to have the same behavior as standard Unix
utilities like `cp` and `scp`.

## New API Endpoints

This endpoint may be split into two separate API endpoints to handle copying
files or directories to and from a container:

	GET /containers/(id)/copy?path=/container/path

This endpoint has similar behavior to the current `copy` endpoint and is used
to copy data from the container to the client. The difference is that it will
correctly handle the case when the source is a file or is a directory and ends
with a trailing path separator, including the directory or only its contents.

	PUT /containers/(id)/copy?srcPath=/local/path&dstPath=/container/path

This endpoint may be used for copying data from the client to a destination
path inside a container.

Use of these 2 endpoints together would allow for a client to copy files or
directories from one container to another, but this would require transfering
an archive through the client. For this purpose, a 3rd endpoint can be used:

	PUT /containers/(id)/copy-across?dstContainer=id&srcPath=/path1&dstPath=/path2

Any container paths which are not absolute are considered relative to the
container's working directory.

## CLI Usage

### copy from a container to the client

	docker cp CONTAINER:PATH LOCALPATH

Copies a file or directory at PATH in the specified `CONTAINER` to a
`LOCALPATH` on the client.

### copy from the client to a container

    docker cp LOCALPATH CONTAINER:PATH

Copies a file or directory at `LOCALPATH` to `PATH` in the specified
`CONTAINER`.

### copy from one container to another

    docker cp SRC_CONTAINER:SRC_PATH DST_CONTAINER:DST_PATH

Copies a file or directory at `SRC_PATH` in `SRC_CONTAINER` to `DST_PATH` in
the `DST_CONTAINER`.

## Behavior of `docker cp SOURCE DEST`

The behavior has been changed to be similar to a combination of `mkdir -p` and
`cp -r`:

- `SOURCE` specifies a file
    - `DEST` does not exist
        - the file is saved to a file created at `DEST`
    - `DEST` exists and is a file
        - the file is overwritten with the contents of the source file
    - `DEST` exists and is a directory
        - the file is saved to this directory using the basename from `PATH`
- `SOURCE` specifies a directory (no trailing path separator)
    - `DEST` does not exist
        - `DEST` is created as a directory and the source directory is copied
          into this directory
    - `DEST` exists and is a file
        - Error condition: cannot copy a directory to a file
    - `DEST` exists and is a directory
        - the source directory is copied into this directory
- `SOURCE` specifies a directory (with trailing path separator)
    - `DEST` does not exist
        - `DEST` is created as a directory and the source directory's contents
          are copied into this directory
    - `DEST` exists and is a file
        - Error condition: cannot copy a directory to a file
    - `DEST` exists and is a directory
        - the source directory's contents are copied into this directory

**Comment by yeahimfreaky** [comment]
-1

**Comment by RoelVdP** [comment]
+1 for a straightforward copy host>container. This is basic functioanlity, as remram44 mentioned; volumes are overkill. At times you want to just start a container from a base OS image, and copy in a single file. 

In our use case, it's a file from another directory (so using build + ADD would not work as ADD is limited to the build directory, and it's also overkill to create a new build/image just for a single file-copy-in). Storing that particular file in the build directory is not a solution either, as it is needed in our master tree, so unless one starts symlinking (though there is issues with that too) or duplicating the file (no-no) there is no good solution. 

The exec is a nice workaround,but imho a simple cp command host>container is basic functionality, and it's missing atm.

**Comment by RoelVdP** [comment]
@jlhawn  - very nice Josh!

**Comment by RoelVdP** [comment]
The only exec workaround that work for was (and no -i needed);
cat $FILE | sudo docker exec $CONTAINER_ID sh -c 'cat > /SOMEFILE'

**Comment by gdm85** [comment]
This has been a missing feature since day 1 (and hurting here too), if you are looking for a replacement (until it's implemented in Docker) feel free to peek at the script I made:

https://github.com/gdm85/docker-cli-tools/blob/master/scripts/docker-inject

**Comment by tarator** [comment]
+1 a simple cp is sometimes necessary...

**Comment by Hyunho** [comment]
+1

**Comment by tkedwards** [comment]
+1

**Comment by RoelVdP** [comment]
It's already implemented https://github.com/docker/docker/pull/10198 (for 1.6)

**Comment by RoelVdP** [comment]
This issue can be closed?

**Comment by jlhawn** [comment]
@RoelVdP it should be closed automatically once #10198 is approved and merged by the project maintainers.

**Comment by docbill** [comment]
Cool.   It looks like this patch is EXACTLY what we wanted.   I will be
very happy when then makes it into the release.  :)

**Comment by tobegit3hub** [comment]
The workaround way by `docker exec` is inefficient when the file is large. +1 for the PR to extend `docker cp`.

**Comment by docbill** [comment]
It looks like https://github.com/docker/docker/pull/13171 is likely to be approved.   One of the things that is problematic with the docker exec solution, is I find sometimes docker exec kills the container when exiting.   As such is best avoided for running services.

**Comment by cpuguy83** [comment]
@docbill `docker exec` should not kill a container upon exiting (note, I'm +1 for the PR to add the `docker cp` functionality).

**Comment by alzarei** [comment]
This is a very a much appreciated feature for development. Although it is not the best practice for deployment! Please let the experienced users for themselves!!

**Comment by ArtworkAD** [comment]
+ 1

e.g. use case: copy mongo dump from host to mongo container in order to restore the data

**Comment by ebuchman** [comment]
+1

This would especially be useful for data-only containers, where you might want to copy in a new configuration or private key.

**Comment by thaJeztah** [comment]
@ebuchman for secrets (private keys etc.) you might want to subscribe to https://github.com/docker/docker/issues/13490, which is all about that.

**Comment by warden** [comment]
+1 to merge and set milestone.

**Comment by deathemperor** [comment]
+1 I need it like right now at this moment

**Comment by baldwinSPC** [comment]
+1 This would be handy. I need it as well for a production app we're building.

**Comment by missedone** [comment]
+1 on this as it's really must have feature for me, for now as a workaround, i transfer the file via stdin of "docker exec" REST API call, but it's not convenient
please milestone this, thanks

**Comment by thaJeztah** [comment]
The pull requests implementing this are [currently on the roadmap](https://github.com/docker/docker/wiki/Engine-1.8.0/9576fc453a8e8880446f1e3c70b422c6ea08257d) for 1.8; see https://github.com/docker/docker/pull/14058 and https://github.com/docker/docker/pull/13171. (That's no guarantee that they will make it though)

**Comment by jlhawn** [comment]
:tada: be sure to try out the Release Candidate for Docker 1.8 when it comes out!

**Comment by duglin** [comment]
Congrats Josh!!!

-Doug

**Comment by erikh** [comment]
+1 congrats. Been watching this thing for a long time now. :)

-Erik

**Comment by sunnycmf** [comment]
:+1: congrats!
