### ISSUE TITLE
Docker btrfs "no space left on device" when "processing triggers for libc-bin" in Ubuntu 14.04 host & container

### ISSUE THREAD

**Issue by sqs** [docker/docker#5900]
When installing Docker in Docker on an Ubuntu 14.04 or Amazon Linux AMI 201403 host with the command `RUN curl -s https://get.docker.io/ubuntu/ | sh` in a Dockerfile with docker running on btrfs, all disk space on the btrfs partition is exhausted during the apt-get "processing triggers for libc-bin" step. I've tried this on 80GB brand new btrfs partitions, and that install step should not need 80GB.

**EC2 repro script included (see bottom)**

STEPS TO REPRODUCE:
1. Launch a new EC2 instance with Ubuntu 14.04, 64-bit, m3.large.
2. Log in with `ssh -i /path/to/key.pem ubuntu@ec2-hostname`.
3. Copy [this script](https://gist.github.com/sqs/8413803a15f8b6a9d3f3) to the EC2 instance and run it.
4. Wait ~3 minutes, and you'll see this output:

```
Setting up lxc-docker-0.11.1 (0.11.1) ...
 * Starting Docker: docker
   ...done.
Processing triggers for ureadahead (0.100.0-16) ...
Setting up lxc-docker (0.11.1) ...
Processing triggers for libc-bin (2.19-0ubuntu6) ...
2014/05/19 01:59:47 write /mnt/btrfs/subvolumes/d294ed5ca61d325fef4d67c4c6d18ecad7f885f0ce51ffdd2ed3649fa7aa50ff/var/lib/docker/devicemapper/devicemapper/data: no space left on device
```

This issue does not occur when using the 'FROM ubuntu:12.04' base image (the build steps complete successfully).

My environment is:

```
  $ uname -a although the issue also occurred on 3.10.35-43.137.amzn1.x86_64
  Linux ip-10-100-171-20 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

```
  $ docker version although the issue also occurred on 0.8 and 0.11.1
  Client version: 0.9.1
  Go version (client): go1.2.1
  Git commit (client): 3600720
  Server version: 0.9.1
  Git commit (server): 3600720
  Go version (server): go1.2.1
```

Here's a script to reproduce the issue on vanilla EC2. The instructions are at the top of the script. https://gist.github.com/sqs/8413803a15f8b6a9d3f3

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/8354

**Comment by bitliner** [comment]
It is happening on my laptop with kernel `Linux bitliner-laptop 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`

ubuntu 14.04

docker-info
```
Containers: 0
Images: 691
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 691
Execution Driver: native-0.2
Kernel Version: 3.13.0-37-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 4
Total Memory: 7.257 GiB
Name: bitliner-laptop
ID: VQZJ:63LB:7DUF:IF7Y:JEMF:VNKB:PXVJ:PA4A:6M5W:BUIH:633N:DHP7
Username: bitliner
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

docker version
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

**Comment by thaJeztah** [comment]
@bitliner according to the info you included, you're running with `aufs`, not `btrfs`, so that's probably not related.
