### ISSUE TITLE
Extremely long SSH first handshake when using Ubuntu:trusty as a host

### ISSUE THREAD

**Issue by mgcrea** [docker/docker#5901]
I'm having a weird issue with SSH. Basically it worked flawlessly on OSX with boot2docker, but I'm having some issues with ubuntu:trusty as a host:

I'm using a supervisord+ssh setup to be able to access any container (ubuntu:trusty base image, using local IPs without exposed ports: `ssh root@172.17.0.2`). On my ubuntu host, I get a minute wait after every container restart before being able to SSH inside the machine, only for the first handshake:

```bash
root@host:/home/mgcrea# docker restart transmission
transmission
root@host:/home/mgcrea# time ssh docker exit
Warning: Permanently added '172.17.0.2' (ECDSA) to the list of known hosts.

real	1m3.403s
user	0m0.008s
sys	0m0.002s
root@host:/home/mgcrea# time ssh docker exit
Warning: Permanently added '172.17.0.2' (ECDSA) to the list of known hosts.

real	0m0.312s
user	0m0.007s
sys	0m0.002s
root@host:/home/mgcrea# 
```

Had to disable PAM on the child image as it was causing issues (SSH disconnects), the same image worked flawlessly with boot2docker on OSX. Switching host OS is not an option. Thanks!

**Comment by jfrazelle** [comment]
can you try with the latest version of docker

**Comment by mgcrea** [comment]
@jfrazelle I have not encountered this issue in a while. I guess it must have been fixed somehow.
