### ISSUE TITLE
libcontainer: nsinit exec does not work for an existing container

### ISSUE THREAD

**Issue by vmarmol** [docker/docker#5926]
I've been looking into using "nsinit exec" on an existing container and have run into a couple of issues that make it now work almost all of the time (and I *think* it doesn't do what you expect when it does):

1. Setns of certain namespaces (including MNT) fail on a multi-threaded application. This behavior is documented and enforced by the kernel. This causes returns of EINVAL which many report seeing. This is made especially difficult in Go since the Go runtime by default starts multiple threads. We may need to have a different (non-Go) binary do this portion for us unfortunately (unless there is some thread-limiting Go magic I don't know of :) ).

2. 3-7% of the time os.OpenFile() returns redundant FDs for `/proc/<pid>/ns/<ns>`. I have been able to repeat this reliably. This does NOT happen if you use syscall.Open(), I am still tracking down just exactly why this breaks.

3. I think we're unsharing the namespaces without need, we should only need to setns(). I've been mostly blocked by the two issues above so I've only observed this one by reading code. I *think* the issue is there, but it may just be in my head.

I'm looking and fixing all three of these issues and getting nsinit exec working reliably. The first issue may require a bit more discussion if it requires a non-Go binary.

**Comment by jfrazelle** [comment]
should this be opened on libcontainer?

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen
