### ISSUE TITLE
please add support for socks5 proxy

### ISSUE THREAD

**Issue by yunfan** [docker/docker#5989]
hi, i live behind the GFW, and unfortunately the cdn-registry-1 has been block at my location.

 i hope you could add support for socks5 proxy , i knew you have HTTP_PROXY support, 

but i think socks5 proxy are more popular and convenient, cause everyone could simply use `ssh user@host -D 9999` to launch a simple proxy server at once

**Comment by pstinghua** [comment]
+1

**Comment by gldamao** [comment]
+1  
That would be very useful.

**Comment by thaJeztah** [comment]
Just linking in case it's useful; another issue related to GFW; https://github.com/docker/docker/issues/11093 (possibly useful tip as well here: https://github.com/docker/docker/issues/11093#issuecomment-80863259)

**Comment by GeorgeZhai** [comment]
+1
Thanks

**Comment by WangBo994** [comment]
+12306

**Comment by intothephone** [comment]
+1

**Comment by utyagi24** [comment]
+1 #$%$!

**Comment by win-t** [comment]
+1,
I need this,

Thanks

**Comment by hailiang** [comment]
+1

**Comment by RomainSF** [comment]
+6

**Comment by VPaulV** [comment]
+1 
Thank you.

**Comment by UserTaken** [comment]
+1 I have a Systemd unit file in place for a permanent SSH tunnel that I would like to be used by Docker.

**Comment by thaJeztah** [comment]
@UserTaken perhaps you are interested in creating a PR to describe this? Thinking of an extra section in https://github.com/docker/docker/blob/master/docs/articles/systemd.md (similar to the proxy example/section)?

**Comment by smiller171** [comment]
`+1`

**Comment by UzxMx** [comment]
+1

**Comment by raintean** [comment]
+1

**Comment by paladin74** [comment]
+1
desire for freedom

**Comment by gitchs** [comment]
+1

**Comment by smiller171** [comment]
:+1:

**Comment by curtiszimmerman** [comment]
+1 this machine could kill fascists.

**Comment by mmobini** [comment]
+1

**Comment by bluesalt** [comment]
+1

**Comment by gaocegege** [comment]
It's useful!

**Comment by nathanleclaire** [comment]
Submitted a PR to support this: https://github.com/docker/docker/pull/18373

Try it out!

**Comment by smiller171** [comment]
thanks @nathanleclaire !

**Comment by KellerFuchs** [comment]
@nathanleclaire Awesome.
I will give it a spin and check for on-network leakage (I plan to use it over Tor); does it avoid doing DNS queries?

**Comment by nathanleclaire** [comment]
@KellerFuchs I'm not 100% sure.  My PR routes the requests from the Docker client to the Docker API through the SOCKS proxy by controlling the low-level `net.Dial`, so I would expect that if there were a DNS lookup as part of that (e.g. if you request API at `host.mydomain.com:2376`) it should go through the proxy as well.  However, I'm not an expert on networking and any analysis of leakage is encouraged.

**Comment by nathanleclaire** [comment]
@KellerFuchs I think actually it will not route DNS requests, because the Golang `Dialer` does not support `socks5h` so far, just `socks5`.  I've filed an issue here: https://github.com/golang/go/issues/13454

**Comment by KellerFuchs** [comment]
Awesome, thanks.

**Comment by cpuguy83** [comment]
Closed by #20366

**Comment by samos123** [comment]
@cpuguy83 could you tell how we enable socks5 proxies? I saw that you closed the ticket but didn't find any reference to docs or configurations on how to enable here nor in #20366 . Thanks!

**Comment by nathanleclaire** [comment]
@samos123  Use `http_proxy` environment variable, along the lines of:

```console
$ HTTP_PROXY=socks5://localhost:5000 docker info
```

**Comment by xbaran** [comment]
+1

**Comment by cpuguy83** [comment]
@xbaran +1 for what? This is already added.

**Comment by thaJeztah** [comment]
@xbaran adding "+1" doesn't help, this is already implemented for 1.11; see https://github.com/docker/docker/pull/20366

**Comment by tom-bowles** [comment]
Setting the environment variable for the execution of the `docker` command line utility, as described by @nathanleclaire, doesn't appear to work. I had to add it to the docker daemon.

**Comment by nathanleclaire** [comment]
`HTTP_PROXY` and `ALL_PROXY`, if set where the `docker` client executable is invoked will dictate how the client attempts to contact the server (docker daemon). As you noted, if you need a proxy for image pulls, etc., you have to configure the daemon's environment to support this.

**Comment by windowsair** [comment]
How to use it in image？ For example use it in "docker run centos: latest"@nathanleclaire

**Comment by nathanleclaire** [comment]
@windowsair You can't configure it in an image level setting, it's something that gets set to dictate the behavior of the `docker` CLI client.

**Comment by smiller171** [comment]
@nathanleclaire couldn't you do `$ HTTP_PROXY=socks5://localhost:5000 docker run centos:latest` to get it to pull that one image from the right host? You could then utilize aliases if you need to do that frequently I think

**Comment by nathanleclaire** [comment]
@smiller171 If you mean will `HTTP_PROXY=<authority> docker pull` pull the image through that proxy, then no, it won't. (Unless the code is doing something excessively clever since last time I was there)

The Docker _daemon_ pulls the images. The Docker _client_ (the binary you are invoking when you type `docker run`, `docker pull`, etc.) will send requests to the Docker daemon to indicate what actions should be taken. Those API (HTTP-ish) requests will be routed / proxied according to the environment variables set where it is invoked but the Docker daemon has its own settings. See https://docs.docker.com/engine/admin/systemd/ for info how to configure.

**Comment by windowsair** [comment]
@nathanleclaire About the docker cilent, document seems to only mention the HTTP and HTTPS proxy.It supports socks5? Thanks a lot

**Comment by smiller171** [comment]
@windowsair You're asking about the traffic from the container going over the proxy? AFAIK this would need to be configured either in the container, or configuring a Docker network that forces all traffic over the proxy.

These settings are for configuring how the client talks to the daemon, or how the daemon talks to the registry.
