### ISSUE TITLE
Non-docker iptables rules are always removed

### ISSUE THREAD

**Issue by gdm85** [docker/docker#6002]
Scenario: docker daemon with --iptables=false --ip-forward=true --icc=false
After a container is created I added some iptables rules to/from another container.

When this container is killed and removed, those rules have disappeared.

I would expect (stale) iptables rules to stay there because docker did not create them in first place. Is this correct behaviour when --iptables is false?

**Comment by jfrazelle** [comment]
I think this should be fixed now that https://github.com/docker/docker/pull/7003 was merged @gdm85 can you make sure?

**Comment by gdm85** [comment]
@jfrazelle not sure when, but at some point it has been added this (reasonable) error when one tries to start docker daemon with arguments as OP:

```
You specified --iptables=false with --icc=false. ICC uses iptables to function. Please set --icc or --iptables to true. 
```

Thus somehow it's no more possible to verify this problem ;)
