### ISSUE TITLE
Respect Shell Globs when running Docker cp...or make a sensible error.

### ISSUE THREAD

**Issue by huslage** [docker/docker#6013]
I was trying to copy some files out of a container with globs.
```
[ec2-user@ip-172-31-17-218 ~]$ sudo docker cp jenkins:/opt/jenkins/data/com* .
2014/05/23 16:28:40 Tarball too short
[ec2-user@ip-172-31-17-218 ~]$ sudo docker cp jenkins:/opt/jenkins/data/* .
2014/05/23 16:28:51 Tarball too short
[ec2-user@ip-172-31-17-218 ~]$ sudo docker cp jenkins:/opt/jenkins/data/ .
```
`Tarball too short` is sort of meaningless....I didn't know I was using tar. There were files matching the `com*` pattern. There were files and directories matching the `*` pattern.

**Comment by jfrazelle** [comment]
@jlhawn does this work with your cp patch

**Comment by jlhawn** [comment]
@jfrazelle nope, file globs are an extra feature

**Comment by jfrazelle** [comment]
cool made it a black belt

**Comment by cpuguy83** [comment]
The issue with this case is specifically that `*` is being interpreted by your shell before the docker client ever sees it.
When quoted, the error is ok: 
```
$ docker cp $(docker ps -lq):'/tmp/*' .
Error response from daemon: lstat /mnt/sda1/var/lib/docker/overlay/d7e7e7be1a08e595d95ee18f3ec0745d9570f63dc077866759f859ba6bc51817/merged/tmp/*: no such file or directory
```

Closing this since there is already an open issue about supporting shell globs in the API.
