### ISSUE TITLE
`docker login` - stop users from using urls with the protocol

### ISSUE THREAD

**Issue by thedeeno** [docker/docker#6032]
I recently setup a private docker registry and was bitten for a few hours by this issue.

When using `docker login` it's possible to login to a private registry with a command like `docker login https://myregistry.com`. If you do this, the command will respond with success and the ~/.dockercfg file will be updated to include the new key/values. Despite this positive feedback a user will have inadvertently broken the docker client's authentication system.

When using `docker push` it appears impossible to use a repository/tag in the following format: `docker push https://myregistry.com/myimage`. The `https://` is rejected as invalid. So, naturally, a user will next try to `docker push myregistry.com/myimage` but this too will be rejected, but quietly! No image will be pushed to the private repository and no error will be reported. It takes an inspection of the front-end proxy logs to see that the first put request the client made was 401 denied. This creates many questions for someone setting this up for the first time and it's not obvious where to begin troubleshooting.

After investigation, it looks like the docker client only attempts to find credentials in `~./dockercfg` with the key matching a given repository. So even though we actually logged in earlier with `https://myregistry.com` the docker client will never find it, since it only looks for the key `myregistry.com`.

Deleting `./dockerfg` and logging in again with the url `myregistry.com` (without the https://) will resolve this issue and allow us to authenticate. Great! Unfortunatley, since we removed the explicit `https` it's reasonable to fear that http will be used and passwords sent in clear text. Fortunately, after inspecting the source it appears only https will be used. Also great!

The docker client should have prevented me from using the protocol in the url from the beginning. I can see many ways to fix this: raise error if user uses the bad format, or make AuthConfig smarter, etc.

**tldnr;**

Docker client breaks when users log into private registries using a url formatted like "https://myregistry.com". It's fixed by re-logging in with a url like: "myregistry.com". The user should be not be allowed to use the bad url format.

**Comment by jfrazelle** [comment]
closing @thedeeno please let me know if this is still a prob with the latest version
