### ISSUE TITLE
permission denied if chown after chmod

### ISSUE THREAD

**Issue by snarlysodboxer** [docker/docker#6047]
This runs, it gives a 0 Exit status:
```
FROM ubuntu:trusty

RUN adduser --disabled-password --gecos "" davidamick
RUN mkdir /home/davidamick/testDir
RUN echo "hello world" > /home/davidamick/testDir/testFile

###
RUN chown -R davidamick. /home/davidamick
RUN chmod 700 /home/davidamick/testDir
RUN chmod 600 /home/davidamick/testDir/testFile
###

USER davidamick
ENTRYPOINT ["/bin/bash"]
CMD ["-l", "-c", "touch /home/davidamick/testDir/testFile"]
```
However if I simply change the chown command to be just after the chmod commands like this:
```
FROM ubuntu:trusty

RUN adduser --disabled-password --gecos "" davidamick
RUN mkdir /home/davidamick/testDir
RUN echo "hello world" > /home/davidamick/testDir/testFile

###
RUN chmod 700 /home/davidamick/testDir
RUN chmod 600 /home/davidamick/testDir/testFile
RUN chown -R davidamick. /home/davidamick
###

USER davidamick
ENTRYPOINT ["/bin/bash"]
CMD ["-l", "-c", "touch /home/davidamick/testDir/testFile"]
```
then running it fails with:
```
touch: cannot touch '/home/davidamick/testDir/testFile': Permission denied
```
I have confirmed the this with several other things too, for example changing the command like so:
```
CMD ["-l", "-c", "ls -ahlR /home/davidamick/testDir"]
```
as well as just running bash interactively and manually attempting to touch/list the files that were chown-ed.
It also does not seem to be related to bash or the environment (that I know of,) since I discovered this issue while doing this:
```
FROM ubuntu:trusty

RUN apt-get update && apt-get install -y ssh
RUN mkdir /var/run/sshd

RUN adduser --disabled-password --gecos "" davidamick
ADD my_pubkey /home/davidamick/.ssh/authorized_keys

###
RUN chmod 700 /home/davidamick/.ssh
RUN chmod 600 /home/davidamick/.ssh/authorized_keys
RUN chown -R davidamick. /home/davidamick
###

ENTRYPOINT ["/usr/sbin/sshd"]
CMD ["-d"]
```
which produced the sshd debug error:
```
debug1: Could not open authorized keys '/home/davidamick/.ssh/authorized_keys': Permission denied
```
and all it took for it to start working was to move the chown command above the chmod commands.

Is this a bug or am I missing something here? Thanks all.

UPDATE: with my host info:
Ubuntu 12.04
```
uname -a
Linux my-hostname 3.8.0-39-generic #58~precise1-Ubuntu SMP Fri May 2 21:33:40 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
```
docker version
Client version: 0.11.0
Client API version: 1.11
Go version (client): go1.2.1
Git commit (client): 15209c3
Server version: 0.11.0
Server API version: 1.11
Git commit (server): 15209c3
Go version (server): go1.2.1
Last stable version: 0.11.1, please update docker
```
```
docker info
Containers: 76
Images: 364
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 516
Execution Driver: native-0.2
Kernel Version: 3.8.0-39-generic
WARNING: No swap limit support
```

**Comment by mitchcapper** [comment]
I can also confirm this is still happening 
Containers: 27                                                             
Images: 140                                                                
Storage Driver: aufs                                                       
 Root Dir: /var/lib/docker/aufs                                            
 Dirs: 194                                                                 
Execution Driver: native-0.2                                               
Kernel Version: 3.16.0-28-generic                                          
Operating System: Ubuntu 14.04.1 LTS                                       
CPUs: 1

**Comment by mitchcapper** [comment]
Certainly only with aufs.  The main problem with this is with file build complexity.  If a dockerfile up the chain does a chmod (or say an package install command does) you cannot fix the permissions on the file/folder by any means (minus a move and move back as root which works).   In addition even without a chroot involved a chmod after chmod does not work (so chmod a folder 700 then back to 755 and no one but root can ls it).  Below are two examples, a very simple one of the original problem and a second one showing all the oddities (for example if the folder was chmodded 711 then a chown is done the user can write to the folder they own but not list the contents).
Here is a simpler example of the problem (on aufs you will get permission denied on ls'ing the contents of test):
```
FROM busybox
RUN adduser -D bob
RUN mkdir /tmp/test
RUN chmod 700 /tmp/test
RUN chown bob.bob /tmp/test
USER bob
CMD ls -l /tmp /tmp/test
```
docker build -t test . && docker run -t -i test
```
/tmp:
total 8
drwxr-xr-x    2 root     root          4096 May 22  2014 ldconfig
drwx------    2 bob      bob           4096 Jan  3 19:37 test

/tmp/test:
ls: can't open '/tmp/test': Permission denied
```

Now to show the real craziness:
```
FROM busybox
RUN adduser -D bob
RUN mkdir /tmp/chmod_fail /tmp/write_allowed_no_ls /tmp/write_fail
RUN chmod 700 /tmp/chmod_fail /tmp/write_fail
RUN chmod 755 /tmp/chmod_fail
RUN chmod 711 /tmp/write_allowed_no_ls
RUN chown bob.bob /tmp/write_allowed_no_ls /tmp/write_fail
USER bob
CMD touch /tmp/write_allowed_no_ls/file;touch /tmp/write_fail/file;ls -l /tmp /tmp/chmod_fail /tmp/write_allowed_no_ls /tmp/write_allowed_no_ls/file
```
docker build -t test . && docker run -t -i test
```
touch: /tmp/write_fail/file: Permission denied
-rw-r--r--    1 bob      bob              0 Jan  3 20:27 /tmp/write_allowed_no_ls/file

/tmp:
total 16
drwxr-xr-x    2 root     root          4096 Jan  3 20:26 chmod_fail
drwxr-xr-x    2 root     root          4096 May 22  2014 ldconfig
drwx--x--x    2 bob      bob           4096 Jan  3 20:27 write_allowed_no_ls
drwx------    2 bob      bob           4096 Jan  3 20:26 write_fail

/tmp/chmod_fail:
ls: can't open '/tmp/chmod_fail': Permission denied
total 0

/tmp/write_allowed_no_ls:
ls: can't open '/tmp/write_allowed_no_ls': Permission denied
```

As mentioned a simple move  and move back however works, take the first example and add one line to the docker file:
```
FROM busybox
RUN adduser -D bob
RUN mkdir /tmp/test
RUN chmod 700 /tmp/test
RUN chown bob.bob /tmp/test
RUN mv /tmp/test /tmp/test2 && mv /tmp/test2 /tmp/test
USER bob
CMD ls -l /tmp /tmp/test
```
and now it works just fine.

**Comment by mitchcapper** [comment]
and while I posted the info here is the version:
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8

**Comment by jfrazelle** [comment]
@mitchcapper can you please try with the latest version of docker

**Comment by jfrazelle** [comment]
could this be related to https://github.com/docker/docker/issues/783

**Comment by jfrazelle** [comment]
it seems to have the same comments and problems as #783 https://docs.docker.com/release-notes/#known-issues

**Comment by mitchcapper** [comment]
@jfrazelle  yes it still occurs. I assume once #10390 gets merged in and the dirperm1 opt is available it will go away.  Is there a reason this is thought to be fixed otherwise?

**Comment by tomaspinho** [comment]
This is still an issue on v1.12.1 with ubuntu 16.04 as both host and container.

chmod THEN chown:

```
jenkins@2caebbe69010:~$ ls -la
total 32
drwxr-xr-x 12 jenkins jenkins 4096 Jan  3 16:08 .
drwxr-xr-x 11 root    root    4096 Jan  3 16:07 ..
-rw-r--r--  1 jenkins jenkins  220 Aug 31  2015 .bash_logout
-rw-r--r--  1 jenkins jenkins 3771 Aug 31  2015 .bashrc
drwx------  2 jenkins jenkins 4096 Jan  3 16:07 .cache
-rw-r--r--  1 jenkins jenkins  655 Jun 24  2016 .profile
drwx------  2 jenkins jenkins 4096 Jan  3 16:08 .ssh
jenkins@2caebbe69010:~$ touch .cache/test
jenkins@2caebbe69010:~$ touch .ssh/test  
touch: cannot touch '.ssh/test': Permission denied
```

chown THEN chmod:

```
jenkins@f45e9a4b3a7a:~$ ls -la
total 28
drwxr-xr-x 10 jenkins jenkins 4096 Jan  3 16:27 .
drwxr-xr-x 11 root    root    4096 Jan  3 16:27 ..
-rw-r--r--  1 jenkins jenkins  220 Aug 31  2015 .bash_logout
-rw-r--r--  1 jenkins jenkins 3771 Aug 31  2015 .bashrc
drwx------  2 jenkins jenkins 4096 Jan  3 16:27 .cache
-rw-r--r--  1 jenkins jenkins  655 Jun 24  2016 .profile
drwx------  2 jenkins jenkins 4096 Jan  3 16:24 .ssh
jenkins@f45e9a4b3a7a:~$ touch .cache/test
jenkins@f45e9a4b3a7a:~$ touch .ssh/test
```

**Comment by thaJeztah** [comment]
@tomaspinho possibly an issue in the aufs kernel module; see https://github.com/docker/docker/issues/20240#issuecomment-244639386, and https://github.com/docker/docker/issues/24660

**Comment by tomaspinho** [comment]
@thaJeztah thanks, but it's easier to just change the Dockerfile, as monkeypatching kernel modules is not an option in my environment. Just left this as docs for other people that may be facing the same
