### ISSUE TITLE
NetworkDevice entry for libcontainer container.json file

### ISSUE THREAD

**Issue by jhspaybar** [docker/docker#6088]
I'd like to add support for taking over individual network devices such as physical devices on the host.  I know --net=host currently allows for using a physical device, but this doesn't namespace either.  This change would allow for placing an existing device into a container with as many IPs as needed, a specific hardware address and an arbitrary name.  When the nsinit process ended the device would need to be named back to what it was previously called.

I'm hoping to gather any feedback or info if others have started this work before I dive in.

**Comment by jfrazelle** [comment]
shouldnt this be opened on libcontainer?

**Comment by thaJeztah** [comment]
ping @vmarmol ^^ for libcontainer

**Comment by jfrazelle** [comment]
closing you can reopen on libcontainer

**Comment by jfrazelle** [comment]
also see https://github.com/docker/docker/issues?q=is%3Aopen+is%3Aissue+label%3A%2Fsystem%2Fnetworking I think there are a few about custom networks
