### ISSUE TITLE
Feature: make Docker itself a linkable service

### ISSUE THREAD

**Issue by progrium** [docker/docker#6093]
I think that Docker TCP should always be available as a linkable service called `docker` for containers to access. The `-v /var/run/docker.sock:/var/run/docker.sock` pattern is used way too much for containers that interact with Docker, and this is an elegant solution. It then becomes:

    $ docker run --link docker:docker myimage bash

This also means containers can use TCP instead of the domain socket, which is currently a little buggy: https://github.com/fsouza/go-dockerclient/issues/101#issuecomment-44454713 (turns out to be https://github.com/dotcloud/docker/issues/5421)

Regardless of TCP or Unix socket, making it easy to run containers with access to Docker is important for the development of the Docker ecosystem. This also helps standardize how containers access Docker ... as opposed to the container specifying where the socket file has to exist (in busybox, it can't just be /var/run/docker.sock due to an issue mounting volumes on paths that are symlinks).

**Comment by jfrazelle** [comment]
So there was a PR for this if anyone is interested and it was closed for this reason which I think is understandable https://github.com/docker/docker/pull/9135

**Comment by calavera** [comment]
Thanks for the clarification @jfrazelle! Closing the issue.
