### ISSUE TITLE
ADD to support symlinks in the <src> argument

### ISSUE THREAD

**Issue by kolypto** [docker/docker#6094]
(from #1676)

In a Dockerfile, when `ADD`ing files, symlinks are not followed. Okay, it's insecure to follow symlinks, moreover -- some might want to put a symlink as a symlink!

What I suggest is that `ADD` follows intermediate symlinks: e.g. 

```
ADD a/b/c /path/to/
```

should work fine, if `a` or `b` or `c` is a symlink, since it needs not to be transferred

**Comment by tiborvass** [comment]
@kolypto in your example: `ADD a/b/c /path/to/` pretending `a`, `b`, and `c` are all symlinks, it should follow `a` and `b`, but not `c`, and creating `/path/to/c` that is a symlink.

**Comment by rifelpet** [comment]
+1 for symbolic links for the reasons given above.  Having multiple `Dockerfile`s in one repo that need to share common files outside of the build context would be a lot easier with symlinks.

**Comment by jfrazelle** [comment]
@tiborvass don't we have symlinks support?

**Comment by tiborvass** [comment]
@jfrazelle we have a non-consistent (files vs directories) unspecified behavior.

This is what @tianon and I want. From https://github.com/docker/docker/pull/8420#issuecomment-70124951:
> copying a symlink should not follow the symlink, it should simply copy the symlink (duh). Only follow a symlink if there is a / after it.

**Comment by tristanz** [comment]
+1 for @tav's suggestion.  This would solve the multiple container in a single repo problem very nicely.

**Comment by urquilla** [comment]
+1

**Comment by lmorris** [comment]
+1

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by jberkus** [comment]
I'm going to give another use-case where we need this feature.

I'm currently working on a dockerfile & docker-compose project for testing a distributed database project.  As such, we want to include the git repo for the distributed database in the docker-compose folder, so that we can do builds and tests, even of code which hasn't been pushed.   However, I can't nest git repos, git submodules are too restrictive (and don't work with unpushed code, anyway).  Since ADD won't follow symlinks, I'm left without any way to fulfill this use case.

**Comment by mamoit** [comment]
+1

**Comment by ms-xy** [comment]
+1 very needed, as stated a couple times above it's currently not possible to wrap Docker into existing build processes which rely symbolic links.
Either that or allow a command line flag to ADD relative paths, this could solve the issue as well.

**Comment by kolis** [comment]
+1

**Comment by NamPNQ** [comment]
Use volume instead of add

**Comment by ms-xy** [comment]
>  The host-dir can either be an absolute path or a name value. If you supply an absolute path for the host-dir, Docker bind-mounts to the path you specify. If you supply a name, Docker creates a named volume by that name.
(Quoted from the documentation)

So not really an option either.

**Comment by kolis** [comment]
@NamPNQ volume instead of add is not possible if you wish to build a standalone container

**Comment by Alino** [comment]
+1 please reconsider, I totally need an option to force following symlinks. You could put a warning that it is only for users who know what they are doing.

**Comment by mattastica** [comment]
@Alino @ms-xy encountered this as well, a very simple solution:

```bash
tar -czh . | docker build -t your-project-tag . -
```

This tars it up and the `-h` forces the dereference of all symlinks. It then pipes it to dockers build (-). The corresponding symlink folder on the docker image will contain the contents of the source of the links.

**Comment by mattastica** [comment]
Just saw that @phemmer posted the same solution :8ball: above in case you didn't see it.

**Comment by Alino** [comment]
@mattastica thank you, that could work on my local machine, but I cannot do this with "automated build" on docker hub. As soon as I push to github, dockerhub automatically builds that repo, however I cannot use the command above to perform the build.

**Comment by ms-xy** [comment]
@mattastica it also doesn't work with docker-compose as far as I know ...

**Comment by crwd-mivanov** [comment]
solved it with `mount --bind some-shared-dir shared`

**Comment by redbaron** [comment]
solved it with `mount --bind some-shared-dir shared`

**Comment by bmurphy1976** [comment]
@redbaron unfortunately that doesn't work if you need to check the symlinks into source control.  I recommend using the `tar -czh . | docker build -` method.  I've had no issues (so far) doing it that way.

**Comment by catsclaw** [comment]
This feature is _badly_ needed. I have a repo with multiple workers (each in a subdirectory, with a Dockerfile for each), and a set of common configuration files in a subdirectory of the root, symlinked into each worker.

My options are to either write a script which copies the configs into the local directories before running docker build (inelegant at best), running the build from the root which copies all 250 Meg of files into the context (slow and annoying), or using the `tar -czh . | docker build -t your-project-tag -` hack. I'm using the hack.

**Comment by XOfSpades** [comment]
I would also love a feature to symlink my config files. In my case I define a volume in my Dockerfile where the executable jar files search for an application.conf file. Inside a common sbt project they are located at some specified folder which I would like to symlink to that (local) volume when running it locally.

**Comment by iBobik** [comment]
Next use case:
I have a repository with a docker-compose.yml, subfolders with Dockerfiles and subfolder with app sources what are needed in services builds. Only way I know is to use (if I do not want to have duplicate git submodules):
COPY ../app /var/www
But it is forbidden by this stupid policy.

Jan Pobořil
http://honza.poboril.cz/

18. 11. 2016 v 10:42, Bernhard <notifications@github.com>:

**Comment by thaJeztah** [comment]
@iBobik `docker build` is performed on the _daemon_. When running `docker build .`, the docker client;

- creates a tar-archive of the current directory (skipping files and directories excluded through `.dockerignore`)
- uploads the tar archive to the daemon
- the daemon extracts the archive
- evaluates each line in the Dockerfile
- any `ADD` or `COPY` is relative to the extracted archive

Allowing relative paths would require the _client_ to evaluate the Dockerfile (note that the client may be on a different platform and architecture, for example a "Windows" or "Mac" client connected to a remote Linux daemon), and copy all files/directories referred in the Dockerfile.

Apart from that complexity (if even possible), there's a lot of risks involved; moving the directory containing the Dockerfile to a different location would potentially copy the wrong content. 

There is a different, related issue still open here; https://github.com/docker/docker/issues/18789

**Comment by ms-xy** [comment]
@thaJeztah the thing is, we are well aware of the risks.
A feature being risky doesn't necessarily make it less useful. For all I care make it only available by using an ugly several words long command line flag - or more drastically have it only optionally compiled in. But make it available.

Take for example, privilege elevation to root or even logging in as root on a Linux system is a daily practice for many. It's easy to do something stupid and destroy your system or make it vulnerable to remote attackers. Yet it is *necessary* and nobody will start an argument about it.
For the sake of sane project development I would wish that the Docker developers would not try to keep up policies in an attempt to prevent people from deliberately shooting themselves in the foot. There's already 1000 and 1 ways to do that without Docker.

The Docker client already has to tar it up, whether it is Linux, Windows, Mac, doesn't matter. Scanning for the two commands ADD and COPY in a Dockerfile should be well in the capability of a light weight client and doesn't need special privileges.

**Comment by justincormack** [comment]
You can do this by just doing `tar --dereference -cf - . | docker build -` - this does not require changes to docker build itself. Using tarball input to `docker build` lets you do anything like this you require.

**Comment by ms-xy** [comment]
Except that it does not work with docker-compose. So either a change in docker-compose or docker.

**Comment by panga** [comment]
+1

**Comment by conradjones** [comment]
use the mount trick it works great.

example gitlab-ci.yml
```
variables:
  IMAGE_NAMESPACE: "myimages"
  DOCKER_REPOSITORY: "docker-repo.domain.com"

before_script:
  - IP=$(ip route | grep docker0 | grep kernel | awk '{ print $9; }')

build_dns:
  script:
    - IMAGE_NAME=dns
    - IMAGE_FOLDER=./docker/dns
    - sudo mkdir -p $CI_PROJECT_DIR $CI_PROJECT_DIR/docker/$IMAGE_NAME/scripts
    - sudo mount --bind $CI_PROJECT_DIR $CI_PROJECT_DIR/docker/$IMAGE_NAME/scripts
    - sudo docker build --build-arg APT_CACHE=$IP -t $IMAGE_NAMESPACE/$IMAGE_NAME $IMAGE_FOLDER
    - sudo docker tag $IMAGE_NAMESPACE/$IMAGE_NAME $DOCKER_REPOSITORY/$IMAGE_NAMESPACE/$IMAGE_NAME
    - sudo docker push $DOCKER_REPOSITORY/$IMAGE_NAMESPACE/$IMAGE_NAME
  after_script:
    - sudo umount $CI_PROJECT_DIR/docker/$IMAGE_NAME/scripts
    - sudo rm -rf $CI_PROJECT_DIR/docker/$IMAGE_NAME/scripts
```

**Comment by jdmarshall** [comment]
Unfortunately the mount trick does not help OS X users.

And the docker-compose angle is often missed in these "should we or shouldn't we" discussions.  It'd be nice to have a more cohesive strategy for dealing with docker features that are added or work differently than docker-compose

**Comment by richfromm** [comment]
Another use case:
source of git repo is in NFS home directory
build goes in a "build" subdir which is gitignore'd
for efficiently, build is a symlink to a local dir in /var/tmp
so if the Dockerfile is referencing any files created by the build, with ADD or COPY, it doesn't work

**Comment by pixelpax** [comment]
@thaJeztah, I really appreciate you laying out the details of implementation difficulty-- I now understand why this is non-trivial. Clearly, automatically attempting to resolve symlinks by crawling the context of a Dockerfile is out of the question. 

Without a very thorough understanding of Docker's guts, I have some ideas regarding a workaround and I'd be happy to take a look at implementing it if you approve and point me in the right direction. 

A build option:

`docker image build --resolve-symlink <PATH_TO_SYMLINK>`

Which would do the following:

1. Pack up a context .tar as usual
2. Display a warning to the user about the security risks and inconsistencies made possible by this action; possibly make them aware of a more strategic approach to sharing resources across projects 
3. Use avfs or a similar tool to mix the pointed-to-files into the .tar 
4. When the daemon receives the archive, it will process it as usual and build the image.

**Comment by ORESoftware** [comment]
@phemmer any idea if your solution will work on MacOS?

I tried this:

`tar -czh ${symlinked_dir} | docker build -t ${image_tag} . -`

and it said

`"docker build" requires exactly 1 argument(s).`

**Comment by tianon** [comment]
Drop the extra ".":

tar -czh ${symlinked_dir} | docker build -t ${image_tag} -

**Comment by ORESoftware** [comment]
thanks, but I thought that the dot . was to specify that the Dockerfile is in the current directory? or maybe that was my mistake.

**Comment by ORESoftware** [comment]
hmm yeah, my symlinked_dir contains node_modules..I have .dockerignore ignoring node_modules, but with this tar command it appears to be copying node_modules over to the image.

**Comment by rocketraman** [comment]
Another use case: a monorepo with two Node.JS projects:

```
monorepo/project-a
monorepo/project-b
```

`project-a` has a dependency on `project-b` -- in order to make the Node.JS build always use a predictable (dare I say, repeatable?) version of `project-b`, `project-a` declares its dependency on `project-b` via

```
"project-b": "file:../project-b"
```

Now, I can't build the Dockerfile for `project-a`, which contains an `npm ci --production`, because `project-b` isn't part of it's context. I can't include the entire monorepo in the context for `project-b` because there is a ton of unrelated stuff in the monorepo and sending gigabytes of context to Docker for `project-a` just to get `project-b` is dumb and ridiculously slow.

I can't include `node_modules` from *outside* Docker in the context, and just copy it into the Dockerfile rather than doing `npm ci --production`, because `node_modules` contains symlinks also, and this sucks anyway.

I don't want to make the dependency in `project-a` a library dependency because then my node build is not repeatable for a given branch of the code, which may require the specific version of that library that is checked out in the monorepo.

The tar trick works but a) the command line needs to exclude the stuff in `.dockerignore` manually and b) this makes the whole thing non-cross-platform and complicates docker builds in CI systems.

The build is already non-repeatable because I run `npm install` inside the Dockerfile and who the hell knows what stuff is going to get pulled in when that happens (and I am *aware* of that non-repeatability and accept it, and work around it by tagging docker builds appropriately so I can go back to a particular build without having to rebuild the Dockerfile). Therefore, Docker's misguided attempt to save me from myself is just annoying.
