### ISSUE TITLE
Add information about exporting volume list to docs

### ISSUE THREAD

**Issue by metalivedev** [docker/docker#6114]
Operators need to know where the data in "volumes" is stored on the host so that they can monitor size, perform backups, migrate data, etc.

Here is one way to dump the bindmounts on a container:

```
# Create a test container with volumes
$ docker run --name testvol -v /vol-anon -v /tmp/vol:/vol-named ubuntu true

# Ok, let's see where those volumes went...
$ docker inspect --format={{.Volumes}} testvol
map[/vol-anon:/var/lib/docker/vfs/dir/1ed44639019c10269718628da26d792857c01dc0d383169841855db83c2d6904 /vol-named:/tmp/vol]
```

I think this would be a helpful addition to http://docs.docker.io/use/working_with_volumes/

**Comment by afewremarks** [comment]
#dibs

**Comment by nhsiehgit** [comment]
Hi @afewremarks 
Can you please add a `closes` or `fixes` keyword so its easy for tracking the fix? Thanks!

(closed by https://github.com/docker/docker/pull/11688 ?)
@jfrazelle
