### ISSUE TITLE
Let users specify custom network bridge for individual containers

### ISSUE THREAD

**Issue by vishh** [docker/docker#6155]
It would be great if docker supports network connectivity between groups of containers. Container in a group can communicate with each other but cannot talk to other containers in other container groups.

Upon discussing this issue with @crosbymichael, letting users specify the bridge to use as part of docker run will help solve this issue - "docker run --net bridge:docker0;  docker run --net bridge:mystack1"

Any thoughts?

**Comment by niieani** [comment]
I have a situation where I'd like to give some of the containers direct access to the network and public IPs - thus bridge them with my host's network while other containers would use the docker0 bridge. This is what I used to do with LXC containers and a similar option in docker would seem to be able to solve this issue for me - unless there's a simpler way of achieving what I want?

Thanks!

**Comment by vitzx** [comment]
Hello,
Could you please share an update on this? I'm looking at running 2000+ containers on the same host and using multiple bridges seems like a reasonable way to go (?)
Thank you.

**Comment by cpuguy83** [comment]
@vitzx Coming soon. This is possible with the experimental build now.

**Comment by mavenugo** [comment]
@vitzx @cpuguy83 yes, this is available today in experimental build (https://github.com/docker/docker/blob/master/experimental/networking.md) and will be made available in docker 1.9 release.

**Comment by vitzx** [comment]
@mavenugo @cpuguy83 Thanks
Sorry, couldn't find a way to run on multiple bridges.. Going back to the first post:

> Upon discussing this issue with @crosbymichael, letting users specify the bridge to use as part of docker run will help solve this issue - "docker run --net bridge:docker0; docker run --net bridge:mystack1"

Is something like **docker run --net bridge:br0 ...;  docker run --net bridge:br1 ...** possible with the experimental build? How do I achieve that? Thank you.

PS
Please also let me know if this is not the right place for posting such questions?

**Comment by mavenugo** [comment]
@vitzx in the experimental build, use the following commands in order to get you multiple bridge networks.

```
docker network create -d bridge br0
docker network create -d bridge br1
docker run -it --publish-service=s1.br0 busybox
docker run -it --publish-service=s2.br1 busybox
```

Kindly note that once these containers are run in separate bridge networks, they are isolated and they cannot talk to each other.

**Comment by vitzx** [comment]
@mavenugo Many thanks

> Kindly note that once these containers are run in separate bridge networks, they are isolated and they cannot talk to each other.

Understood, but do I need to do anything extra to make sure both can reach to the outside world and to/from the host? Is that supposed to work?

Observing this at the moment:
```bash
root@docker1:[~]:# docker network ls
NETWORK ID          NAME                TYPE
3958dab363bc        bridge              bridge
9022ef4c6d06        br0                 bridge
cc53986576ed        br1                 bridge
6af2aed6203c        none                null
988f1de10363        host                host
root@docker1:[~]:# docker network info 9022ef4c6d06
Network Id: 9022ef4c6d060065693e55737bf9c7a26b217dd6c1ccb6e457bb26d055fa2889
Name: br0
Type: bridge
root@docker1:[~]:# docker network info cc53986576ed
Network Id: cc53986576ed4a2422181ad17dae8df1a3b1bda62a0f70a467d2c6c06fb37ec6
Name: br1
Type: bridge
root@docker1:[~]:# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
a194fe8c1e0e        ubuntu:14.04        "/bin/bash"         32 minutes ago      Up 32 minutes                           foo-1
0c9e05cea7fc        ubuntu:14.04        "/bin/bash"         32 minutes ago      Up 32 minutes                           foo-0

root@docker1:[~]:# brctl show
bridge name	bridge id		STP enabled	interfaces
br0		        8000.4a8e34394393	no	veth478d794
							                vethb4fd3cc
br1		        8000.22c4bbcb557a	no	veth5fd484d
							                vetha0dccf2
docker0		8000.0242d33f6306	no

root@docker1:[~]:# ip add show br0 | grep -w inet
    inet 172.16.0.1/16 scope global br0
root@docker1:[~]:# ip add show br1 | grep -w inet
    inet 172.16.0.2/16 scope global br1

root@docker1:[~]:# docker exec -t foo-0 ifconfig eth0 | grep -w inet
          inet addr:172.16.0.5  Bcast:0.0.0.0  Mask:255.255.0.0
root@docker1:[~]:# docker exec -t foo-1 ifconfig eth0 | grep -w inet
          inet addr:172.16.0.6  Bcast:0.0.0.0  Mask:255.255.0.0

root@docker1:[~]:# docker exec -t foo-0 route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.16.0.1      0.0.0.0         UG    0      0        0 eth0
172.16.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0
root@docker1:[~]:# docker exec -t foo-1 route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.16.0.2      0.0.0.0         UG    0      0        0 eth0
172.16.0.0      0.0.0.0         255.255.0.0     U     0      0        0 eth0

root@docker1:[~]:# docker exec -t foo-0 ping -c 2 172.16.0.1
PING 172.16.0.1 (172.16.0.1) 56(84) bytes of data.
64 bytes from 172.16.0.1: icmp_seq=1 ttl=64 time=0.652 ms
64 bytes from 172.16.0.1: icmp_seq=2 ttl=64 time=0.084 ms

--- 172.16.0.1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 999ms
rtt min/avg/max/mdev = 0.084/0.368/0.652/0.284 ms
root@docker1:[~]:# docker exec -t foo-1 ping -c 2 172.16.0.2
PING 172.16.0.2 (172.16.0.2) 56(84) bytes of data.
From 172.16.0.6 icmp_seq=1 Destination Host Unreachable
From 172.16.0.6 icmp_seq=2 Destination Host Unreachable

--- 172.16.0.2 ping statistics ---
2 packets transmitted, 0 received, +2 errors, 100% packet loss, time 1006ms
pipe 2

root@docker1:[~]:# docker --version
Docker version 1.9.0-dev, build b0dc111, experimental
```

**Comment by vitzx** [comment]
@mavenugo Many thanks

> Kindly note that once these containers are run in separate bridge networks, they are isolated and they cannot talk to each other.

Understood, but do I need to do anything extra to make sure both can reach to the outside world and to/from the host? Is that supposed to work?

What I'm seeing is that one of the containers can, and another cannot, please let me know if I should provide more information:

```bash
root@docker1:[~]:# docker exec -t foo-0 ping -c 1 172.16.0.1
PING 172.16.0.1 (172.16.0.1) 56(84) bytes of data.
64 bytes from 172.16.0.1: icmp_seq=1 ttl=64 time=0.447 ms

--- 172.16.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.447/0.447/0.447/0.000 ms
root@docker1:[~]:# docker exec -t foo-1 ping -c 1 172.16.0.2
PING 172.16.0.2 (172.16.0.2) 56(84) bytes of data.
From 172.16.0.6 icmp_seq=1 Destination Host Unreachable

--- 172.16.0.2 ping statistics ---
1 packets transmitted, 0 received, +1 errors, 100% packet loss, time 0ms

root@docker1:[~]:# docker --version
Docker version 1.9.0-dev, build b0dc111, experimental
```

172.16.0.1 and 172.16.0.2 are configured on br0 and br1 respectively and configured as gw for containers..

**Comment by mavenugo** [comment]
@vitzx 
> 172.16.0.1 and 172.16.0.2 are configured on br0 and br1 respectively and configured as gw for containers..

that should not be possible. by default, 2 different bridge networks should be allocated from different subnets and hence having br1 and br2 in the same 172.16.0.0 subnet seems incorrect. Can you please confirm ?

And yes, by default the containers in these networks should have external connectivity and host reachability by default.

**Comment by vitzx** [comment]
@mavenugo 
> that should not be possible. by default, 2 different bridge networks should be allocated from different subnets and hence having br1 and br2 in the same 172.16.0.0 subnet seems incorrect. Can you please confirm ?

I see; yes, that was the issue. Works as expected when allocating different subnets to the bridge networks.

Many thanks for the help and clarifications!

**Comment by mavenugo** [comment]
thanks @vitzx for the confirmation. @vishh if you think this satisfies the requirement, I think we can close this issue.

**Comment by vishh** [comment]
@mavenugo: Good to see this feature finally land! This issue can be closed now :)
