### ISSUE TITLE
user xattrs should be supported with graphdriver/devmapper

### ISSUE THREAD

**Issue by harshavardhana** [docker/docker#6189]
~~~
# docker pull centos
# docker run -i -t centos /bin/bash

bash-4.1# touch file 
bash-4.1# setfattr -n user.attr -v 1 file
setfattr: file: Operation not permitted
~~~

This is acceptable on a regular Linux box as stated below without special privileges 
~~~
harsha@sysrq:~$ setfattr -n user.xattr -v 1 addressbook
harsha@sysrq:~$ getfattr -d -m . .addressbook 
# file: .addressbook
user.xattr="1"
~~~

As i figured this is due to the fact that device mapper mount 'ext4' and ext4 requires explicit flag of "user_xattr" to be passed on to mount options (not needed on XFS) 

Simple fix below should fix this
~~~
-       mountOptions := label.FormatMountLabel("discard", mountLabel)
+       mountOptions := label.FormatMountLabel("discard,user_xattr", mountLabel)
+
~~~

**Comment by jfrazelle** [comment]
@harshavardhana did you get around to opening a PR for this

**Comment by jfrazelle** [comment]
I now see https://github.com/docker/docker/pull/6190#issuecomment-68907817, @vbatts any comments

**Comment by vbatts** [comment]
On 25/02/15 18:25 -0800, Jessie Frazelle wrote:
>I now see https://github.com/docker/docker/pull/6190#issuecomment-68907817, @vbatts any comments

i'm personally all for this feature. It may be more possible now that you have stood up the jenkins instance. The biggest questions around user.xattrs were that of compatibility _across_ docker daemons (i.e. a _new_ type of testing: i built X on fedora w/ devicemapper and it pulls and runs as expected on ubuntu w/ aufs)

**Comment by LK4D4** [comment]
@vbatts sorry to ping you. Do you know what's going on here?

**Comment by vbatts** [comment]
@LK4D4 It's been literally years since looking into supporting user namespaced xattrs. Some software depends on it, and IIRC the fact that they may not be portable across docker daemons, then it was decided against. I could be wrong though

**Comment by LK4D4** [comment]
Yeah, it was very long time. Going to close this as inactive. We can always open new if there will be interest.
