### ISSUE TITLE
Registry & Index Spec, Push Image Step 10 not accurate

### ISSUE THREAD

**Issue by ekristen** [docker/docker#6201]
https://github.com/dotcloud/docker/blob/master/docs/sources/reference/api/registry_index_spec.md

Step 10 of the push doesn't seem to be accurate. I've written a custom open source index with authentication support and step 10's body is always content length of 2 and does not container the image ids, checkums, or tags. 

Docker does call the index with a PUT but its contents is always empty. 

Are the docs wrong or is the Docker daemon not following the registry/index spec correctly.

I've tested this with registries 0.6.7-0.7.0 and docker 0.7 and newer. Currently using docker 0.10.0.

**Comment by jfrazelle** [comment]
the specification is here https://github.com/docker/docker#under-the-hood if you want to change something you can always make a PR

just realized you also have https://github.com/docker/docker/issues/7939, im going to close this one so there is only one point of discussion
