### ISSUE TITLE
switch to http timeout for registry

### ISSUE THREAD

**Issue by proppy** [docker/docker#6263]
`registry.go` should implement timeout logic on the http request, instead of using a custom Dialer to the `net.Conn`.

This way you can control the timeout of the read *and* the write instead or just read deadline (and risk to fail long running write).

Related #6254

**Comment by jfrazelle** [comment]
@proppy does this still apply? want to make a patch ;)

**Comment by proppy** [comment]
That's @vieux's call, he ended up fixing it differently: https://github.com/docker/docker/pull/6260

**Comment by jfrazelle** [comment]
ping @vieux 

@proppy do you not like the implementation bc then I can label as improvement :)

**Comment by proppy** [comment]
yes, I like the sounds of 'improvement' :+1:

**Comment by jfrazelle** [comment]
\o/

**Comment by ctiwald** [comment]
#dibs

**Comment by ctiwald** [comment]
Hey @jfrazelle -- can you clarify the improvement here? Very difficult to figure out what's up, given the changes that have been made to the code already.

**Comment by tkopczynski** [comment]
I tried to look into this issue but I think it doesn't apply any more because current code uses timeouts quite explicitly. But if there's something to be done here, I'm happy to work on this.

**Comment by thaJeztah** [comment]
Yes, this is a really old issue now, and I think the changes in docker 1.10 (up- and download manager; https://github.com/docker/docker/pull/18353, and timeouts here https://github.com/docker/docker/pull/19743) should fix this.

I'll close this issue, but feel free to comment if additional improvements can be made
