### ISSUE TITLE
Feature Request: Syslog support in docker

### ISSUE THREAD

**Issue by lra** [docker/docker#6321]
Hi,

I think it'd be really useful to have docker send its output to syslog, with an option.
There are some hacks out there to circumvent the problem, but it's all heavy (for large amount of logs) or hacky.
- http://jasonwilder.com/blog/2014/03/17/docker-log-management-using-fluentd/
- https://blog.logentries.com/2014/03/the-state-of-logging-on-docker/

So for now solutions are:
- run syslog in the container (I like having 1 process/container)
- mount a volume (breaks the isolation)
- parse some json on the host (not efficient)
- send docker's output to syslog using a supervisor or piping it into logger (best option so far, but I'd rather not have to)

Am I missing something obvious? =)

Is there some reason that prevents a docker option to log to syslog? Or is it just waiting to be done by someone? ;)

Thanks!

**Comment by cpuguy83** [comment]
Closing since #11458 was merged.

**Comment by lra** [comment]
Cool stuff

**Comment by grayhemp** [comment]
Some new ideas around it https://github.com/docker/docker/issues/13726. Could you guys please take a look?
