### ISSUE TITLE
Dynamically adjust resource limits

### ISSUE THREAD

**Issue by dineshs-altiscale** [docker/docker#6323]
On the fly tuning of memory and CPU limits gives granular control needed by cluster managers like Hadoop/YARN.

**Comment by hqhq** [comment]
Since we already have a proposal here, I suggest we should reconsider https://github.com/docker/docker/pull/11442

**Comment by tobegit3hub** [comment]
Agree with @hqhq . I know docker would not like to expose the usage of cgroups. But anyway, it should support users to take advantage of cgroups with better interfaces if they're using cgroups to manage containers. @cpuguy83

**Comment by hqhq** [comment]
There are different opinions between maintainers, kind like stuck here, so I'd like to ping @crosbymichael @shykes hope we can get some progress here, I can redo #11442 , just think this feature is really useful and necessary.

**Comment by karanganju** [comment]
+1 for dynamic resource limits!

**Comment by argakon** [comment]
+1

**Comment by thaJeztah** [comment]
A continuation of the original "docker set" PR was recently approved, and is being worked on here; https://github.com/docker/docker/pull/15078 (thanks @hqhq!) I think that PR will resolve this issue, so I'll add it to the description.

**Comment by sindusistla** [comment]
Why Dynamic resource allocation not supported by Docker?  Even though there is Update command in Docker REST API, the resources should be updated manually. Is there any way that the existing resources of the host machine can be utilized with maximum efficiency by scaling the resources of the Containers Up and down depending on the current utilization of Containers? (The concept I wanted to get clarified is Autonomic Vertical Scaling, is it supported by Docker ?)

**Comment by cpuguy83** [comment]
@sindusistla This can be implemented on top of Docker, but is not implemented within Docker itself.

**Comment by sindusistla** [comment]
@cpuguy83  Thank you for the reply. 
Is there any specific reason for not being implemented in the Docker, as I thought it would be very flexible to have dynamic resource allocation. Especially for builds running without supervision?

**Comment by cpuguy83** [comment]
@sindusistla It's a very complicated problem that is mostly bound by rules of the application being run.

**Comment by sindusistla** [comment]
Any near future plans to implement it?  
I'm actually doing some research in this area of dynamic resource allocation.

**Comment by cpuguy83** [comment]
Not in the runtime portion for sure.... honestly not likely at all.

**Comment by cpuguy83** [comment]
More likely if the swarmkit/swarm-mode API doesn't provide enough detail to higher-level abstractions that we'd add the needed detail there so that other tools can be built on top.
