### ISSUE TITLE
Docker fails with 127.0.0.1 in resolv.conf

### ISSUE THREAD

**Issue by alexlarsson** [docker/docker#6388]
If the host resolv.conf has a nameserver in 127.0.0.1 this will not work in the container, as it will mean the container-local loopback inside the container.

Using a 127.0.0.1 dns proxy is not unusual. For instance, fedora plans to add one by defaul in Fedora 22, in order to support dnssec better. See https://fedoraproject.org/wiki/Changes/Default_Local_DNS_Resolver for details.

I think docker needs to rewrite the resolv.conf file in order to handle this. Some possible solutions:
* If 127.0.0.1 is in resolv.conf, forward the port form the container loopback to the host loopback
* Set up a fixed resolv.conf in the container that points to some fixed ip in the container network range. Then forward this to whatever the host resolv.conf says.

**Comment by jfrazelle** [comment]
ping @estesp I think this should be fixed right

**Comment by estesp** [comment]
Yes, replacing localhost DNS has been fixed for quite awhile--replaced with Google DNS as noted in prior comments.

For those that **want** to take advantage of a localhost resolver on the host, there are various ideas in the comments above, but at this point there has been no strong interest to try and make Docker handle the iptables/pass-through work to get DNS requests from container -> localhost on Docker daemon/host.  Clearly "127.0.0.1" as a resolver in the containers `/etc/resolv.conf` is not viable as that just means the container network namespace localhost itself; which is why it gets replaced if it exists.

**Comment by pjps** [comment]
iptables(8) DNAT comes handy to enable containers to communicate with the local resolver on the host.

1. Enable local 'lo' routing via 'docker0' bridge interface. (it is off by default)
    ```# sysctl -w net.ipv4.conf.docker0.route_localnet=1```

2. Enable local resolver to accept requests from 172.17.0.0/16 docker sub-network.
   ```unbound(8):  # vi /etc/unbound/unbound.conf -> access-control: 172.17.0.0/16 allow```
    ```ndjbdns(8):  # touch /etc/ndjbdns/ip/172.17```

3. Use iptables(8) destination nat(DNAT) feature to divert DNS traffic from 'docker0' to 'lo' interface.
   ```# iptables -t nat -I PREROUTING -p UDP -s 172.17.0.0/16 --dport 53 -i docker0 -j DNAT --to-destination 127.0.0.1:53```

Thank you.

**Comment by rhatdan** [comment]
Might be better to open a new issue rather then here. But I will leave that to the docker maintainers to decide.

@jfrazelle @crosbymichael @jpetazzo @tianon

**Comment by pjps** [comment]
Yes, I just wrote to @jfrazelle little while back about the same.

**Comment by pjps** [comment]
New issue -> https://github.com/docker/docker/issues/14627

**Comment by CharlieR-o-o-t** [comment]
There is another bug appeared after [PR](https://github.com/docker/libnetwork/pull/1595). 

I use cached DNS resolver at my hostmachine. And there are custom DnsSearch params for each container. 

My container resolv.conf looks like this:
```/etc/resolv.conf
search foo.com
nameserver 127.0.0.11
options timeout:2 ndots:0
```

Hostmachine resolv.conf
```
nameserver 127.0.0.1
nameserver <my_dns_server_ip>
nameserver <my_dns_server_ip2>
```

components/engine/vendor/github.com/docker/libnetwork/sandbox_dns_unix.go:218
```
	if len(sb.config.dnsList) > 0 || len(sb.config.dnsSearchList) > 0 || len(sb.config.dnsOptionsList) > 0 {
...
		// After building the resolv.conf from the user config save the
		// external resolvers in the sandbox. Note that --dns 127.0.0.x
		// config refers to the loopback in the container namespace
		sb.setExternalResolvers(newRC.Content, types.IPv4, false)
```

With dnsOpt/dnsSearch container always trying to reach DNS (127.0.0.1) inside container NS. Workaround needed in this part. My opinion is that loopback dns usage should be always used at hostmachine namespace. I can prepare PR if you agree with that.
