### ISSUE TITLE
User `Username or email` instead of requiring username and email in the same time

### ISSUE THREAD

**Issue by victorlin** [docker/docker#6400]
```
docker push foo/bar
The push refers to a repository [foo/bar] (len: 1)
Sending image list

Please login prior to push:
Username: foo
Password: 
Email: 
```

it's kinda annoying to enter email after entering username and password, I am not registering a new account here, why I have to enter my email? Although the .cfg file can save the logging information for me, I have multiple accounts for different usage, need to login different accounts sometimes. I think it's absolute not necessary to ask user both username and email with password.

I suggest what it should be is something like

```
Username or email: 
Password:
```

This is a more reasonable design.

**Comment by vieira** [comment]
I think we can improve this behaviour if we attempt to login after the password is typed and only when this fails do we ask for the extra information needed to register the user (for now, the e-mail address).

A better option would be to have some endpoint in the hub api that we can invoke to check if a user exists and based on that decide which path to follow (either login or register).

What do you think?

I can take this one.

**Comment by vieira** [comment]
I think we can improve this behaviour if we attempt to login after the password is typed and only when this fails do we ask for the extra information needed to register the user (for now, the e-mail address).

A better option would be to have some endpoint in the hub api that we can invoke to check if a user exists and based on that decide which path to follow (either login or register).

What do you think?

I can take this one.

**Comment by JonathonReinhart** [comment]
*Cue Jeopardy Theme*

**Comment by thaJeztah** [comment]
This is being worked on in this proposal; https://github.com/docker/docker/issues/18668 and pull request; https://github.com/docker/docker/pull/16183.

**Comment by ripcurld00d** [comment]
@thaJeztah -- I think this issue can be closed because #16183 resolves it.

**Comment by thaJeztah** [comment]
@ripcurld00d it's not been resolved yet, because that PR was closed without merging; there's still changes required in Docker Hub for that; also see https://github.com/docker/docker/issues/18668

**Comment by meetmatt** [comment]
You can simulate empty email entry by using "yes" program like this:

yes | docker login -u username -p password private-registry

Works like a charm for in my deploy script :)
