### ISSUE TITLE
Proxy does not recover from errors like `too many open files`

### ISSUE THREAD

**Issue by amuino** [docker/docker#6402]
Under some circumstances, the system might run out of file descriptors to forward a request to the container.

What we are seeing in this scenario is this message on the `docker.log`

    2014/06/13 09:11:30 Stopping proxy on tcp/[::]:6003 for tcp/172.17.0.244:5000 (accept tcp [::]:6003: too many open files)

After that, even if the problem with open files is solved, the proxy never recovers, even if the host and the container keep runing.

The only solution we have found is to detect the affected container and `docker restart` it.

The problem was detected with Docker 1.0 in a GCE instance when running `ab -n 1000 -c 600 http://localhost:6003` against a ruby webserver. The issue seems to be caused by the large number of TCP sockets being created (judging by the output of `lsof`).

**Comment by jfrazelle** [comment]
I believe there have been improvements for this and there are a bunch of other issues open surrounding the userland proxy so closing as dup
