### ISSUE TITLE
After restart containers not running but still in 'docker ps' output

### ISSUE THREAD

**Issue by devzero** [docker/docker#6435]
After a system reboot, 3 out of 10 of my containers came back online in a state where the processes aren't running but they are listed in the 'docker ps' output.  Oddly the docker ps listing for the containers doesn't show any port mappings even though there were before the reboot.  I can't stop them, kill them or rm -f them because it gets a 'no such process' error.

This is on ubuntu 14.04 with docker info:
Containers: 35
Images: 231
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 301
Execution Driver: native-0.2
Kernel Version: 3.13.0-29-generic
WARNING: No swap limit support

and docker version:
Client version: 0.11.1
Client API version: 1.11
Go version (client): go1.2.1
Git commit (client): fb99f99
Server version: 0.11.1
Server API version: 1.11
Git commit (server): fb99f99
Go version (server): go1.2.1
Last stable version: 1.0.0, please update docker

Here is an excerpt from my docker logs of me trying to stop kill and start one of these containers:

2014/06/15 02:24:44 POST /v1.11/containers/nzbdrone/kill?signal=KILL
[8327e6bc] +job kill(nzbdrone, KILL)
Cannot kill container nzbdrone: no such process
[8327e6bc] -job kill(nzbdrone, KILL) = ERR (1)
[error] server.go:1011 Error: Cannot kill container nzbdrone: no such process
[error] server.go:90 HTTP Error: statusCode=500 Cannot kill container nzbdrone: no such process
2014/06/15 02:25:08 GET /v1.11/containers/json
[8327e6bc] +job containers()
[8327e6bc] -job containers() = OK (0)
2014/06/15 02:25:20 POST /v1.11/containers/deluge/stop?t=10
[8327e6bc] +job stop(deluge)
2014/06/15 02:25:20 Failed to send SIGTERM to the process, force killing
Cannot stop container deluge: no such process
[8327e6bc] -job stop(deluge) = ERR (1)
[error] server.go:1011 Error: Cannot stop container deluge: no such process
[error] server.go:90 HTTP Error: statusCode=500 Cannot stop container deluge: no such process
2014/06/15 02:25:24 POST /v1.11/containers/nzbdrone/stop?t=10
[8327e6bc] +job stop(nzbdrone)
2014/06/15 02:25:24 Failed to send SIGTERM to the process, force killing
Cannot stop container nzbdrone: no such process
[8327e6bc] -job stop(nzbdrone) = ERR (1)
[error] server.go:1011 Error: Cannot stop container nzbdrone: no such process
[error] server.go:90 HTTP Error: statusCode=500 Cannot stop container nzbdrone: no such process
2014/06/15 02:25:37 POST /v1.11/containers/nzbdrone/start
[8327e6bc] +job start(nzbdrone)
[8327e6bc] -job start(nzbdrone) = OK (0)
2014/06/15 02:25:41 GET /v1.11/containers/json
[8327e6bc] +job containers()
[8327e6bc] -job containers() = OK (0)
2014/06/15 02:25:59 POST /v1.11/containers/nzbdrone/stop?t=10
[8327e6bc] +job stop(nzbdrone)
2014/06/15 02:25:59 Failed to send SIGTERM to the process, force killing
Cannot stop container nzbdrone: no such process
[8327e6bc] -job stop(nzbdrone) = ERR (1)
[error] server.go:1011 Error: Cannot stop container nzbdrone: no such process
[error] server.go:90 HTTP Error: statusCode=500 Cannot stop container nzbdrone: no such process
2014/06/15 02:26:05 DELETE /v1.11/containers/nzbdrone
[8327e6bc] +job container_delete(nzbdrone)
Impossible to remove a running container, please stop it first or use -f
[8327e6bc] -job container_delete(nzbdrone) = ERR (1)
[error] server.go:1011 Error: Impossible to remove a running container, please stop it first or use -f
[error] server.go:90 HTTP Error: statusCode=406 Impossible to remove a running container, please stop it first or use -f
2014/06/15 02:26:10 DELETE /v1.11/containers/nzbdrone?force=1
[8327e6bc] +job container_delete(nzbdrone)
2014/06/15 02:26:10 Failed to send SIGTERM to the process, force killing
Could not stop running container, cannot remove - no such process
[8327e6bc] -job container_delete(nzbdrone) = ERR (1)

**Comment by jfrazelle** [comment]
can you please try with the latest version of docker

**Comment by jfrazelle** [comment]
after the restart policies in 1.2.0 this is not reproducable please update and ping me if you are still seeing it after using those policies
