### ISSUE TITLE
KILL/TERM

### ISSUE THREAD

**Issue by harry-wheildon** [docker/docker#6446]
**Summary**: `docker stop` sends `SIGKILL` after a timeout period which could be disastrous to many applications.

**Proposed Solution**: Change `docker stop` to not send `SIGKILL`

**Workaround**: Use `docker kill -s TERM <container>`, which only sends `SIGTERM` to the container.

========

**Original**:

The "docker stop" help section mentions that it performs a SIGTERM, waits a predefined amount of time, and then sends a SIGKILL to the process if it hasn't died in that amount of time.

Let's assume that we're running MySQL in a container. "docker stop CONTAINER_ID" sends a SIGTERM, and MySQL starts cleaning up, flushing everything to disk and making sure everything's neat and tidy. The system is running slow, so it's taking a while, but MySQL is doing the job it was told to do. Suddenly, the grace period elapses and docker sends a SIGKILL, which it can't catch. MySQL dies without completing the clean up. When the container is bought back up, we suddenly have corrupt tables and administrators are running around and people are getting fired.

Maybe dramatised a bit, but I was wondering if this could be rethought? If a container doesn't die properly, we shouldn't be breaking out the howitzers to make sure it does. We should be emitting a warning message if the container is taking too long to die, giving the user the option to SIGKILL if they want, with a warning that they may be corrupting data.

Just because everyone in the industry seems to think SIGKILLing is okay to do by default, doesn't mean we should be.

For "docker kill", we should change the default signal to TERM. This mirrors more closely the default option for for the shell built-in "kill" in Linux, as opposed to the more deadly KILL (which requires passing an option [-9] to kill).

**Comment by jfrazelle** [comment]
@cpuguy83 do you know what the solution would be here? can we triage

**Comment by cpuguy83** [comment]
**Summary**: `docker stop` sends `SIGKILL` after a timeout period which could be disastrous to many applications.

**Proposed Solution**: Change `docker stop` to not send `SIGKILL`

**Workaround**: Use `docker kill -s TERM <container>`, which only sends `SIGTERM` to the container.

**Comment by jfrazelle** [comment]
cool you rule @cpuguy83

**Comment by Batmat** [comment]
At the very very least, docker should issue a log to the guy issuing the docker stop the timeout has been reached and a kill -9 is being send. I'm pretty sure actuall quite few people (compared to the mass of people using Docker) know about this. 

A log would at least push users to find this issue, and the workaround (or pass a bigger -t, anyway). Until some weeks ago, I wasn't even aware of the SIGKILL my containers were receiving. So I wasn't even worrying.

Cheers

**Comment by Batmat** [comment]
Btw, could/shouldn't a label like "needs-attention" or something more important be put on this issue? 

In fact, as stated above, this behaviour can be disastrous to the *data*, so I wonder if this could deserve more attention.

Thanks

**Comment by MichaelBitard** [comment]
I think this issue #12315 I created is related to this one. I give an example where you actually lose data.

**Comment by cyphar** [comment]
I recently found out about a fairly disastrous issue with `SIGTERM` and `PID 1` that is fairly relevant to this discussion. The kernel automatically installs a `SIG_IGN` handler for `PID 1` for a whole bunch of signals (including `SIGTERM`). So really, `docker stop` will only trigger clean up operations for services that don't explicitly define a `SIGTERM` handler.

**Comment by cpuguy83** [comment]
Closing this since as stated before, `docker kill -s TERM` will send only SIGTERM to the container. Additionally you can use this to define your own workflow for how to deal with something not exiting on TERM.
I don't see the `docker stop` API changing since you can just use `kill`
