### ISSUE TITLE
Docker build does not use Proxy from Docker Daemon

### ISSUE THREAD

**Issue by f0** [docker/docker#6454]
Hi, 
i have set a proxy for the docker daemon in my systemd start file, this works well, i can search and pull from the puplic index 
But if i try to build a Dockerfile, the proxy setting is not used, i need to set the proxy in the Dockerfile, but this is not a good idea as it is not portable.

docker 0.11.1 and 1.0.0
regards f0

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/4962
