### ISSUE TITLE
container removed, where were those volumes?

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#6504]
A lot of times people will remove a container, but maybe need access to the data that was in it's volume.
Problem is even though the volume data is still in tact (at least by default), there is no way to figure out which dir contains the data you wanted since there is no high-level view of volumes.

Adding this as part of the push to improve volumes, #6496

**Comment by cpuguy83** [comment]
Closing since this is really resolved by using named volumes, and/or external volumes via plugin.

**Comment by thaJeztah** [comment]
@cpuguy83 lost track a bit in all the changes; is there going to be a UX for listing those named volumes as well?

**Comment by cpuguy83** [comment]
I think the plan is to ressurect #8484
I would image this would only work for local volumes + whatever volumes a container is actually using... which is ok since docker shouldn't really be worrying about external stuff.

**Comment by thaJeztah** [comment]
@cpuguy83 sgtm! already thought I missed a PR somewhere in the process :smile:

**Comment by thaJeztah** [comment]
(omg, I just realised I instantly knew the #8484 PR, just by looking at the number)
