### ISSUE TITLE
Track image origin & last use time.

### ISSUE THREAD

**Issue by phemmer** [docker/docker#6523]
It would be useful to have a way of obtaining when an image was last used. The primary use case for this is to determine which images can be removed from a server.
On a server which gets a lot of usage, it can rapidly acquire a lot of images. To keep the drive from filling, old images which are no longer in use need to be removed. However we only want to remove images which haven't been used in a while.

Additionally as part of the same objective, it would be useful to also know where the image came from. Or more specifically, if also exists on a registry somewhere. This way images which can easily be pulled down again can be deleted more frivolously.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/6523, feel free to add any additional things there

**Comment by jfrazelle** [comment]
sorry meant https://github.com/docker/docker/issues/4237
