### ISSUE TITLE
Race condition, network interfaces

### ISSUE THREAD

**Issue by Attil** [docker/docker#6549]
Hello,
I've found a race condition that happens when I start a Docker instance. It seems Docker can set up network interfaces too late. It happened when I tried to launch a mumble server - murmur, using command
`docker run -t -i -p 64738:64738 a337fcd9ad07 murmurd`
Docker tried to execute it before setting up interfaces and of course, the server didn't listen on the expected port correctly. I have found a temporary workaround, using this command:
`docker run -t -i -p 64738:64738 a337fcd9ad07 /bin/bash -c "sleep 2;murmurd"`

**Comment by jplock** [comment]
Is there a better work around for this besides https://gist.github.com/dcreager/16223c48d9801656d132?  I ran into this today with Docker 1.7.0

**Comment by fkautz** [comment]
@crosbymichael 
```
we just have to make sure there are not any unforeseen side effects to polling the interfaces." 
```
Did we ever work this out? Also, are these side effects in the kernel or in libcontainer?

**Comment by cpuguy83** [comment]
Is this still a problem?

**Comment by aboch** [comment]
@cpuguy83 I think this can no longer happen in docker. The container will be given a go to be started only after `initializeNetworking` is done. So after libnetwork took care of creating, programming and bringing up the network interfaces.

**Comment by cpuguy83** [comment]
👍 Awesome. Thanks @aboch 
Closing.

If anyone is still having issues with this, please let us know!
