### ISSUE TITLE
Expressing containers OPTS in Dockerfile

### ISSUE THREAD

**Issue by philips** [docker/docker#6560]
In our upstart and systemd init files in contrib we increase the NOFILE limit to a very large number. This value gets passed to every container. However, this can be a [dangerous for containers](http://www.outflux.net/blog/archives/2014/06/13/5-year-old-glibc-select-weakness-fixed/) with old glibc's.

I am going to send a patch to add a runtime flag to set the ulimits but a container should be able to express its needs in this case. To just start a conversation how about we introduce a "OPTS" command to the dockerfile such as:

```
OPTS LimitNOFILE=1024
```

We also need somethin at runtime and @crosbymichael suggested doing something with the `--opts` flag.

IRC Convo: https://gist.githubusercontent.com/anonymous/5853fa83ef35fa66a877/raw/d808665b009bc67f2f3570f392ddb67959550b76/gistfile1.txt

**Comment by jfrazelle** [comment]
ooo we have a pr for ulimits now, have you seen https://github.com/docker/docker/pull/9437 @philips

**Comment by philips** [comment]
Yea! This is at runtime only. It would be great if the container could express what it is able to do too so the user doesn't silently break an app.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
