### ISSUE TITLE
Docker gives out IP addresses already in use

### ISSUE THREAD

**Issue by damm** [docker/docker#6561]
Hi,

I am trying to get my Docker containers (in a datacenter) to be on a specific link and have it hand out IP addresses that are not in use.  So docker is running like ```docker -d -b=br0```

The subnets I have tried are below:

_10.0.0.1/24_
_10.1.10.1/24_
_172.16.0.1/24_ 

There is nothing special in my configuration my forward delay is 1 on the bridge (I used to set 9).

* Switches Involved.
 + Cisco SG-300 24 port
 - Cisco SG-200 24 port

Rapid STP is enabled so basically what happens is it flaps the ip between the ports assuming it.  This makes it impossible to docker build on 2 servers at once (apt-get update usually fails)

I don't care what IP is given out; I just don't want it to give out an IP already in use.

**Comment by jfrazelle** [comment]
I believe we can close this now @LK4D4? right?

**Comment by LK4D4** [comment]
@jfrazelle I hope so :)

**Comment by damm** [comment]
I personally don't think this issue should be closed; so I will open another issue.

**Comment by jfrazelle** [comment]
sorry about that it is hard to tell sometimes. Feel free to open another
