### ISSUE TITLE
new docs theme has lost the next&prev navigation links

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#6606]
which is a bit of a shame

**Comment by ankushagarwal** [comment]
@spf13 : I don't think this is a novice/beginner issue, neither a kind/writing. It requires understanding and making changes to the https://github.com/docker/docs-base project to autogenerate next/prev navigation links in the docs

**Comment by spf13** [comment]
Fair point. We probably need a new label for what kind this is. I'll move it to intermediate in the meantime.

**Comment by ankushagarwal** [comment]
I think that this issue belongs here : https://github.com/docker/docs-base/issues

**Comment by spf13** [comment]
@ankushagarwal I agree. No way to easily move it though. We just need to recreate it over there and then close this. @SvenDowideit Do you agree?

**Comment by SvenDowideit** [comment]
@spf13 yup, moved as https://github.com/docker/docs-base/issues/7
