### ISSUE TITLE
/proc/1/environ is unavailable in a container that is not priviledged

### ISSUE THREAD

**Issue by damm** [docker/docker#6607]
Hi,

@tianon originally suggested me to read this awhile back; I noticed as of 1.0.1 that I cannot access this file unless the container is privileged.

Anyway we can restore this access or point me to a different way to get the environment variables? (In this case the container is init and upstart calls a upstart job that needs to parse this file to figure out it's linking)

Thanks!

**Comment by jfrazelle** [comment]
ping @crosbymichael status on this?

**Comment by damm** [comment]
My interests were resolved after knowing that it requires a privileged container; there are bugs with certain kernel versions that make this different.

**Comment by rthille** [comment]
I'm seeing a similar issue where after a process makes the setresuid call it can't read it's own environment, and root can't read it either.

**Comment by damm** [comment]
@rthille how about filing a new issue with more information on this? you can reference this issue of course.

A few other issues have been referenced previously; so if it's happening again a fresh issue might get new eyes.

**Comment by rthille** [comment]
I'll work up a small program to confirm what I'm seeing tomorrow and file a new issue. Thanks.

**Comment by rthille** [comment]
Never mind, my "bug" turned out to be exactly this issue, I was just testing improperly.
