### ISSUE TITLE
Delete default bridge on server shutdown

### ISSUE THREAD

**Issue by dhammika** [docker/docker#6608]
Cleanup docker0 bridge on daemon shutdown.

**Comment by jfrazelle** [comment]
Ok I am going to close because of what Michael posted on #6609, It will not be ideal for people whose daemon may have just stopped all of a sudden.
> We introduce the risk of the bridge IP changes, other services listening on the bridge, etc. I'm not sure any advantages that we gain by doing this.
If you want this on your set up I would encourage you to add it to you init script.
