### ISSUE TITLE
init.d service start error: could not open session

### ISSUE THREAD

**Issue by pkhabi** [docker/docker#6615]
I have been trying to install qpid in a docker centos container. Install goes well but service start fails with error - could not open session .
Looks like this is because init.d is trying to initialize the qpid service with a non root user using 'runuser'.
(runuser -s /bin/bash ${QPID_USER} -c "${QPID_BIN_DIR}/$prog --config ${QPID_CONF_DIR}/qpidd.conf --check > $pidfile")

I know Dockerfile has an option to select a user and run command ( eg, USER qpid) but my qpid installation is part of larger custom software installation hence Dockerfile is not an option now. What I am trying to do is to install the customer software in the container and then create an image out of the resulting container.

I tried to run the base container with --privileged but getting error mentioned here

Not sure if --privileged is the right way to overcome 'could not open session' issue.

PS: I posted the question in the docker-user mailing list but thought of opening an issue here as well.

**Comment by jfrazelle** [comment]
I think like @tiborvass said 
>  if you would like to use the USER Dockerfile directive from the command line, you can do docker run --user.
Anyone know any other solutions that would work here?

**Comment by jfrazelle** [comment]
closing as I believe this to be a misunderstanding with how to use docker, and issue is stale, feel free to ping me if the solutions here do not fix the problem
