### ISSUE TITLE
Stopping the daemon fails and process becomes defunct

### ISSUE THREAD

**Issue by Tranquility** [docker/docker#6618]
I experience that on a machine where I start builds with the ruby docker-api library. After running some builds I can no longer stop the daemon and need to reboot the system because the process is still listening on port 4244 so I can not start it again.

The distro is debian wheezy.

I am starting it with these options:
`DOCKER_OPTS="-D -H tcp://127.0.0.1:4244 -H unix:///var/run/docker.sock"`

And here is the output of docker info:

```
Containers: 79
Images: 476
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 636
Execution Driver: native-0.2
Kernel Version: 3.13.0-0.bpo.1-amd64
Debug mode (server): true
Debug mode (client): false
Fds: 36
Goroutines: 31
EventsListeners: 0
Init Path: /usr/bin/docker
WARNING: No memory limit support
WARNING: No swap limit support
```

**Comment by jfrazelle** [comment]
Closing, I no longer think this is an issue on the latest version

**Comment by jfrazelle** [comment]
ping me if you feel otherwise
