### ISSUE TITLE
add data fields to container logs

### ISSUE THREAD

**Issue by opennomad** [docker/docker#6663]
I'm currently harvesting the docker logs on the host. The JSON format makes it great for importing via logstash and I seem to be able to rotate/purge them as well.

One thing that would make it even better if additional fields were available.

I was thinking along the lines of adding some environment variables that could be added as a field to the logs. For example

DOCKER_LOG_VERSION=0.7
DOCKER_LOG_NAME=indexer

could then be added to the logs in JSON format adding '{ "docker_log_version" : "0.7", "docker_log_name" : "indexer" }'. In essence any variable that starts with a certain prefix would show up as a field in the JSON logs.

That would be a great value add for pushing to logstash.

I'm happy to give this a shot if this makes sense.

**Comment by cpuguy83** [comment]
I think this is generally handled by the logging drivers, and the addition of the --log-opt for customizing drivers.
wdyt?

**Comment by opennomad** [comment]
yeah, i think the logging driver should do the trick. Thanks!
