### ISSUE TITLE
Implement --cap and --namespace flags for better control

### ISSUE THREAD

**Issue by crosbymichael** [docker/docker#6687]
We discussed this and think it would be best to not use something like `--opts` to be able to add and remove individual capabilities and namespaces for containers.  We would rather use a dedicated flag and make sure that these features work across libcontainer and lxc.  So our proposal is to add these two flags and provide a warning when elevating privileges for a container so that a user is aware of that they are doing.

### Caps
http://linux.die.net/man/7/capabilities

1. In addition to the default caps that are keep for a container add the `NET_ADMIN` cap to a container.
```bash
docker run --cap +NET_ADMIN crosbymichael/redis
```
2. Remove the MKNOD capability from the default cap set that is kept
```bash
docker run --cap -MKNOD crosbymichael/redis
```

3. Drop MKNOD and add NET_ADMIN and SYS_ADMIN
```bash
docker run --cap -MKNOD --cap +NET_ADMIN --cap +SYS_ADMIN crosbymichael/redis
```

Any additional caps that are retained for a container should produce an error on stderr when running the container to let the user know they have elevated the privileges for a container. 

### Namespaces

There are a few reasons why you want to modify the namespaces applied to a container.  If you are running a monitoring application in a container you may want to not drop into your own PID namespace so that you can see all your parents PID.  

1. Do not create a PID namespace
```bash
docker run --namespace +PID -ti crosbymichael/htop
```

Changing the default namespace profile should result in a warning to the user.

### Privileged

Using the privileged flag should result in a warning on stderr just like the two new flags above.  

### Development

We can discuss some of the details in this issue but if you would like to work on any of the changes please let me know.  

I think all three of these changes, caps, namespaces, and privileged warning can be done separately.  Ideally the privileged warning code can be merged in first so we have the warning pipeline to work with on the other prs.  Caps should be easy to implement.  Namespaces will be a little more challenging because it may consist of some runtime/libcontainer changes to support the different configuration.  

Suggestions?

**Comment by ewindisch** [comment]
--cap-add and --cap-drop was included with Docker 1.2.  No --namespace flag has been added

**Comment by LK4D4** [comment]
@phemmer We have support for dropping and specifying paths for namespaces in libcontainer.  This can be added with dozen lines of code in docker. But having way to override namespaces in docker is sort of UX decision, so this is probably depending on @shykes.

**Comment by phemmer** [comment]
Perhaps my use case would help here. What I'm trying to do is mount something within a volume in one container, and then share the volume (containing the mount) with another container. Because of the mount namespace, when the volume is shared with another container, it appears empty. If I could disable the mount namespace, I could work around this.

**Comment by rhatdan** [comment]
Currently you can disable network,UTC and IPC namespace.

 --net=host, --ipc=host

I have submitted a patch to disable the PID namespace --pid=host

Usernamespace is not enabled yet.  That leaves mount, but kind of the definition of docker is using the MNT Namespace for handing of the image content.  Not sure how you disable that and still have docker.  libcontainer allows you to disable/enable all combinations.

**Comment by phemmer** [comment]
Well I images would break left and right if the root (`/`) isn't the root of the image, but we can fall back to a simple `chroot` to solve that issue.

**Comment by SvenDowideit** [comment]
imo it would be cool to have it tho - perhaps its a way for a container to union on top of another host dir / container, and in the process, we make even lighter weight containers. :)

**Comment by rhatdan** [comment]
Even if you shared / or /usr you would probably still want to have applications write to locations that are different per container /var and /tmp for example.

But if you want just to have namespaces, why not just use the unshare command.

**Comment by crosbymichael** [comment]
This is complete with `--pid`
