### ISSUE TITLE
Support `docker run --rm=5m (or --rm-after=5m)` to facilitate running docker on something like coreos+fleet

### ISSUE THREAD

**Issue by boombatower** [docker/docker#6688]
When running a daemon on coreos using fleetctl it can be cumbersome to try and manage cleaning up the leftover containers after the service has been terminated or migrated to a new host.

Using `docker run --rm` does not work well since it would remove the container any time the service is restarted by either user intervention or a crash. Instead having a way to cleanup once the service is gone would be best (perhaps this should be a fleet feature instead/as well), but having the option to remove the container after a period of non-use would be handy.

Implementation wise, once container exists sleep for time period, awaken see that container has been idle for >= sleep time, and remove. Otherwise, if it was reactivated it should not removed.

Alternatively, I suppose one could setup a cron on the host machine to prune using docker ps and docker rm script to prune. Would be slick then if docker rm supported something like `docker rm --before="6m ago"` or date, etc.

Thoughts?

**Comment by jfrazelle** [comment]
there are lots of filters now and fun ways to do this so closing

**Comment by jfrazelle** [comment]
nm i see this wants a new flag

**Comment by schmunk42** [comment]
Would be great if we could filter like @vbatts mentioned

    docker ps --filter 'running>1h'

We need this to run improved cleanup task in our CI

**Comment by cpuguy83** [comment]
Hmm... It sounds like while the requested feature is not implemented the use-case is now supported on master.
`--rm` has now been moved to the daemon, and handles cases like `docker restart`.

WDYT? Can we close this one?

**Comment by crosbymichael** [comment]
@cpuguy83 I would rather not have something like this at all.  There are some usability issues that this would introduce. 

As far as fulfilling the need for better cleanup; we are currently working on data management commands in #26108 that should help with the original request and also provide better viability into where space is being consumed.
