### ISSUE TITLE
Volumes pretty much always need a data-container

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#6698]
When using volumes, the usefullness of the volume is limited without coupling it with a data-container.
The reason for this is the tie between a container and the volume... when the container goes away so does the possibility of actually using the data in that volume again, unless you'd happened to copy the host path of that volume.

**Sumary**: referencing a volume is impossible when last container is removed

**Proposed Solution**: Provide volume management API/UI.  This has started to be implemented in #8484

**Comment by jfrazelle** [comment]
is this still true? I personally don't think they do

**Comment by cpuguy83** [comment]
@jfrazelle Yep. Either data-containers or binds.

**Comment by jfrazelle** [comment]
so can we triage as we need to update the docs around this?

**Comment by cpuguy83** [comment]
Closing since the volumes re-factor pretty much handles this by using named volumes... and of course external volume drivers.

**Comment by thaJeztah** [comment]
For those following this; top level volume management is now implemented in https://github.com/docker/docker/pull/14242, which was just merged, and will be in **docker 1.9**

If you want to test it before that, nightly builds, build from master can be found at https://master.dockerproject.org
