### ISSUE TITLE
Inspect should include terminating signal

### ISSUE THREAD

**Issue by Sirupsen** [docker/docker#6711]
It'd be useful if the Inspect output included which signal the container was terminated by it's daed.

**Comment by jfrazelle** [comment]
actually I think we do this?

**Comment by jfrazelle** [comment]
oh we have exit code

**Comment by jdavidson091** [comment]
Is this issue still relevant or useful for people? Looking to help out for a first ticket and I could pick it up. If so, what would even be a good name for the field designating a "terminating signal"? Thanks.

**Comment by jdavidson091** [comment]
#dibs for now

**Comment by runcom** [comment]
ping @jdavidson091 you still working on this?

**Comment by vdemeester** [comment]
``docker inspect`` returns :

```json
// […]
    "State": {
        "Running": false,
        "Paused": false,
        "Restarting": false,
        "OOMKilled": false,
        "Dead": false,
        "Pid": 0,
        "ExitCode": 1,
        "Error": "",
        "StartedAt": "2015-06-27T11:46:30.27160302Z",
        "FinishedAt": "2015-06-27T11:46:30.428905958Z"
    },
//  […]
```

``ExitCode`` is in there, this issue might be already fixed isn't it ?

**Comment by LK4D4** [comment]
@vdemeester I don't think that issue was about `ExitCode` :)

**Comment by vdemeester** [comment]
@LK4D4 yeah I talk about it with @runcom on irc, my bad :3.

**Comment by calavera** [comment]
Sup, this is happening in #15307.
