### ISSUE TITLE
Systemd crashes immiditelly if PID 1 with systemd non privileged patches applied

### ISSUE THREAD

**Issue by offlinehacker** [docker/docker#6730]
I was trying to run our distro nixos which uses systemd in docker and got the following error with entrypoint:

```
CMD ["/bin/init"]
```

When systemd tries to exec itself, so replacing init script with systemd, systemd crashes. This is bracktrace from systemd:

```
#0  0x00007ff44f7e3d10 in __pause_nocancel () from /nix/store/94n64qy99ja0vgbkf675nyk39g9b978n-glibc-2.19/lib/libpthread.so.0
#1  0x000000000048595d in freeze ()
#2  0x000000000049aa2e in main ()
```

Systemd start succesfuly if started as PID>1, but this is not a solution.

**Comment by jfrazelle** [comment]
can not reproduce with systemd 215 and latest docker
