### ISSUE TITLE
docker run exit code consisency

### ISSUE THREAD

**Issue by rhatdan** [docker/docker#6734]
I found other issues that talked about this but I did not find one that addressed it exactly.  

The problem is differentiating between an exit code from 

docker run blowing up versus the command being run by docker run blowing up.

We could follow the chroot standard.
  Exit status:

     125 if 'chroot' itself fails
     126 if COMMAND is found but cannot be invoked
     127 if COMMAND cannot be found
     the exit status of COMMAND otherwise

**Comment by pikeas** [comment]
+1, this would be extremely useful

**Comment by rhatdan** [comment]
@duglin Have you made any progress, or I can get one of my engineers to work on this.

**Comment by duglin** [comment]
I was waiting for the official "+1" from a maintainer but if one of your guys wants to jump on it, go for it.

**Comment by duglin** [comment]
Nope that's not related to this at all.

**Comment by jfrazelle** [comment]
status on this anyone?

**Comment by rhatdan** [comment]
We have not worked on it.  But I can raise it's priority.

**Comment by duglin** [comment]
@rhatdan let me know when you do start it - its still on my todo list too....

**Comment by gdm85** [comment]
+1 this would be a nice improvement for integration

**Comment by cyphar** [comment]
Upon reviewing this again, I think the best method would be to have the exit code for the `docker run` command be Docker-related errors (i.e. errors that occurred during the Docker-related operations of running the process) and that you should poll the API (or run `docker exit-code <container>` or some such) to get the exit code of the container. The only issue is that this isn't really backwards compatible (unless we make it so that `docker run` returns `0` iff the process returned `0` and there were no Docker errors and `docker run` returns `1` otherwise (unless there were Docker errors)).

**Comment by rhatdan** [comment]
We have started working on this again, basically looking at returning 127 most of the time when a 

docker run/exec/start fails as opposed to a command failing within the container.  Once we have this, we could look at trying to see if we can figure out 126 errors where we could not find the PID 1 command.

**Comment by cyphar** [comment]
@rhatdan What happens if the `PID 1` command returns `127`, or is that non-standard behaviour we are ignoring?

**Comment by gdm85** [comment]
Just for reference/ideas, there's plenty of existing implementations that one could draw inspiration from.
In general normalizing any non-zero exit status to a Docker-defined value seems reasonable.

Quoting the man page EXIT STATUS sections of some Linux/BSD commands:

xargs
-------------
```
xargs exits with the following status:
       0 if it succeeds
       123 if any invocation of the command exited with status 1-125
       124 if the command exited with status 255
       125 if the command is killed by a signal
       126 if the command cannot be run
       127 if the command is not found
       1 if some other error occurred.
```

man parallel
-------------
```
If --halt-on-error 0 or not specified:

       0     All jobs ran without error.

       1-253 Some of the jobs failed. The exit status gives the number of failed jobs

       254   More than 253 jobs failed.

       255   Other error.

       If --halt-on-error 1 or 2: Exit status of the failing job.
```

sudo
------
```
Upon successful execution of a program, the exit status from sudo will simply be the exit status of the program that was executed.

     Otherwise, sudo exits with a value of 1 if there is a configuration/permission problem or if sudo cannot execute the given command.  In the latter case the error string is printed to the standard
     error.  If sudo cannot stat(2) one or more entries in the user's PATH, an error is printed on stderr.  (If the directory does not exist or if it is not really a directory, the entry is ignored and no
     error is printed.)  This should not happen under normal circumstances.  The most common reason for stat(2) to return “permission denied” is if you are running an automounter and one of the directories
     in your PATH is on a machine that is currently unreachable.
```

sh
--
```
     Errors that are detected by the shell, such as a syntax error, will cause the shell to exit with a non-zero exit status.  If the shell is not an interactive shell, the execution of the shell file will
     be aborted.  Otherwise the shell will return the exit status of the last command executed, or if the exit builtin is used with a numeric argument, it will return the argument.
```

**Comment by rhatdan** [comment]
@cyphar Yes that is a problem, but as shown above multiple tools that exec other tools have followed this standard and they have the same problem.

The main goal is to scripting tools/testing tools to easily tell the difference between the tool failing and the command failing.

**Comment by runcom** [comment]
there's a PR for this now #14012

**Comment by shahmalhar** [comment]
I am still getting  "exit status 126" issue, did anybody figured it out?

**Comment by ghafran** [comment]
I got this "exit status 126" because I was mounting a volume and overriding the script that was the entrypoint. I moved the script outside of the directory and it worked. Hope that helps.
