### ISSUE TITLE
Mounting /var is not really safe

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#6745]
If you use `/var` or `/var/lib` as a volume using device mapper or aufs, you will get the root mounts of other containers on your server.  So if you create container A, then container B with `-v /var:/test`, then delete container A it will fail.  You can reproduce with the following:

```sh
docker run -d -it --name first ubuntu bash
docker run -d -it --name second -v /var:/test ubuntu bash

while ! docker kill first; do
    sleep 1
done

docker rm first
```

You will get the below output (using devicemapper)
```
Error response from daemon: Cannot destroy container first: Driver devicemapper failed to remove root filesystem ff5a580bdcecd2db06972692f4e2cfb0c6607890cc0c0757ff3172295572fac0: Device is Busy
2014/06/27 16:29:54 Error: failed to remove one or more containers
```

It seems we should somehow address this.  Either by not rbind by default and maybe make it a flag?  Or possibly there is someway that if specifies a parent of /var/lib/docker we mount /var/lib/docker in without rbind?  I don't really know.

**Comment by jfrazelle** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
Yeah I saw this one the other day... not sure how to address it.

**Comment by ibuildthecloud** [comment]
All that is really required to fix this is that volumes be mounted as shared,slave in the container.  I thought at one point Docker was going to default to that, but then it blew up?  I think with 1.10 that you have the ability to control the mount propagation, this bug can be closed.  While `-v /var:...` is still unsafe, there will at least be a safe way to do it with the right combination of arguments.
