### ISSUE TITLE
When container failes to delete because of storage issue, storage is orphaned

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#6746]
I noticed this behaviour while reproducing https://github.com/dotcloud/docker/issues/6745.  This applied to device mapper, but I think it's a higher level logic issue that's not specific to the storage driver (but I could be wrong).

If a container fails to delete because the storage is still in use, the container in docker will be deleted but the storage is not.  The storage is now orphaned.  With device mapper if you run the script included in https://github.com/dotcloud/docker/issues/6745 you will see with `dmsetup ls` that there is an orphan volume.

**Comment by allingeek** [comment]
The issue here is that two resources need to be cleaned up and there is no transaction:

[https://github.com/docker/docker/blob/master/daemon/delete.go#L64-L70]
```
		if err := daemon.Destroy(container); err != nil {
			return job.Errorf("Cannot destroy container %s: %s", name, err)
		}
		container.LogEvent("destroy")
		if removeVolume {
			daemon.DeleteVolumes(container.VolumePaths())
		}
```
Maybe adding a check to see if the volumes are available for removal before destroying the container would be enough.

**Comment by rhvgoyal** [comment]
I sent a pull request for fixing these here. Any feedback or testing results are appreciated.

https://github.com/docker/docker/pull/11137

**Comment by vdemeester** [comment]
This issue might be closed as the PR has been merged, right ?

**Comment by jfrazelle** [comment]
thanks so much for noticing that

**Comment by jfrazelle** [comment]
you would be surprised how many of these linger

**Comment by vdemeester** [comment]
@jfrazelle when I have a little time I'm listing the issue by oldest to see which one are like this one ;-).
