### ISSUE TITLE
Container started with --rm isn't removed after start failure

### ISSUE THREAD

**Issue by qerub** [docker/docker#6757]
First invocation:

```
docker run --rm --name=example --link b0rk:b0rk ubuntu
2014/06/29 11:14:22 Error: Could not find entity for b0rk
```

Second invocation:

```
$ docker run --rm --name=example --link b0rk:b0rk ubuntu
2014/06/29 11:14:50 Error: Conflict, The name example is already assigned to 7e0e4f5268a8. You have to delete (or rename) that container to be able to assign example to a container again.
```

This hit me with surprise. I expected the first run to leave no garbage because of `--rm`. If this is the desired behaviour it should be documented on https://docs.docker.com/reference/run/.

This should also be handed on the daemon side not client side.

**Comment by remmelt** [comment]
That would help me out as well.

**Comment by jfrazelle** [comment]
https://github.com/docker/docker/pull/11570 covered the first part of this, now we just need to handle the code on the daemon side.

**Comment by runcom** [comment]
I could do the daemon side validation too if this is ok!

**Comment by jfrazelle** [comment]
yes for sure!

**Comment by runcom** [comment]
#dibs then! I'll look for anything like trying to run a container with the same name and the like and remove the container if such situations arise in the daemon. Also I was thinking, if container removal should be handled daemon side, would it be ok to put an `AutoRemove` flag in `runconfig/HostConfig` struct and then moving existing client removal in the daemon? @jfrazelle

**Comment by jfrazelle** [comment]
yeah sounds good in HostConfig, then we can remove all the clientside removal code

**Comment by runcom** [comment]
That's my plan! :smiley_cat:

**Comment by jfrazelle** [comment]
perfect :D

**Comment by runcom** [comment]
working on this now :)

**Comment by pwaller** [comment]
:+1: for handling removal daemon side. That's a big win. Is there a plan on how to implement this? Will we see the container get removed if the docker client is killed, for example?

**Comment by runcom** [comment]
@pwaller could you explain further what you mean by if the docker client is killed?

**Comment by pwaller** [comment]
If you do `kill -9 $(pid of 'docker run')`, does the container get rm'd?

**Comment by pwaller** [comment]
In order to respond to that, the only way I'm aware of, is to respond to the socket being closed, along the lines of what #9774 does.

**Comment by runcom** [comment]
ok then yes I think this would be supported when daemon side container removal is implemented (something like what you did in that PR, it's still wip btw)

**Comment by nanoz** [comment]
#12444 could also be fixed with this PR

**Comment by thaJeztah** [comment]
This should now be fixed by https://github.com/docker/docker/issues/15230
