### ISSUE TITLE
docs sidebar highlights the wrong heading

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#6767]
as clicking on a sub heading is not a server round trip, the highlight is on the wrong element. 

I propose to remove it, rather than trying to be too clever.
![sidebar-highlight-fail](https://cloud.githubusercontent.com/assets/28492/3425729/9a555c9e-000c-11e4-9bad-97d594298a75.png)

**Comment by jfrazelle** [comment]
looks fixed to me, closing but @SvenDowideit reopen if i missed something
