### ISSUE TITLE
Unable to run Docker 1.0 inside LXC

### ISSUE THREAD

**Issue by shovon** [docker/docker#6783]
A lot of people (including me) had no issues running LXC containers inside an LXC container, but I'm unable to run Docker 1.0 inside an LXC container. Not sure if it's an issue with Docker itself, or an issue with Docker's use of libcontainer.

The content of the `config` file associated with the host LXC container that I'm testing with is as follows:

```
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# Container specific configuration
lxc.rootfs = /var/lib/lxc/dockerception/rootfs
lxc.mount = /var/lib/lxc/dockerception/fstab
lxc.utsname = dockerception
lxc.arch = amd64

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:ce:da:87

lxc.aa_profile = unconfined
lxc.cgroup.devices.allow = b 7:* rwm
lxc.cgroup.devices.allow = c 10:237 rwm
```

And then, when ssh'd in to the LXC container, running `docker -d` yields the following and an exit code of `1`:

```
2014/06/30 20:33:54 docker daemon: 1.0.1 990021a; execdriver: native; graphdriver: 
[c32d6fbe] +job initserver()
[c32d6fbe.initserver()] Creating server
[c32d6fbe] +job serveapi(unix:///var/run/docker.sock)
2014/06/30 20:33:54 Listening for HTTP on unix (/var/run/docker.sock)
[c32d6fbe] +job init_networkdriver()
[c32d6fbe.init_networkdriver()] creating new bridge for docker0
[c32d6fbe.init_networkdriver()] getting iface addr
[c32d6fbe] -job init_networkdriver() = OK (0)
2014/06/30 20:33:54 WARNING: mountpoint not found
Error loading docker apparmor profile: exit status 243 (/sbin/apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: docker
)
[c32d6fbe] -job initserver() = ERR (1)
2014/06/30 20:33:55 )
```

Any idea what's going on?

This is what `uname -a` outputed:

```
Linux dockerception 3.13.0-29-generic #53-Ubuntu SMP Wed Jun 4 21:00:20 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

For [`sudo`] `docker version`:

```
Client version: 1.0.1
Client API version: 1.12
Go version (client): go1.2.1
Git commit (client): 990021a
2014/06/30 21:03:37 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

And for [`sudo`] `docker -D info`

```
2014/06/30 21:04:23 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

**Comment by VictorArgote** [comment]
I am trying to run docker inside a LXC container. I have followed all the steps described here, i get the docker daemon running using the LXC driver. I can run docker commands like pull, ps, images, etc. But when trying to start a container 'docker start containername' i get this error:

```
Error response from daemon: Cannot start container CONTAINERNAME: Process could not be started
FATA[0005] Error: failed to start one or more containers
```

docker info (inside lxc container):

```
Containers: 1
Images: 24
Storage Driver: vfs
Execution Driver: lxc-1.1.0.rc4
Kernel Version: 3.18.0-999-generic
Operating System: Ubuntu Vivid Vervet (development branch) (containerized)
CPUs: 4
Total Memory: 3.849 GiB
Name: devdesktop0
ID: ACI2:2T6Q:WHUO:ZPE5:YIY4:HEHN:OIYK:YUEQ:2LCA:5NEA:L2MS:QONC
WARNING: No swap limit support

```
docker version(inside lxc container):
```
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
Server version: 1.4.1
Server API version: 1.16
Go version (server): go1.3.3
Git commit (server): 5bc2ff8
```

lxc config file:

```
# Template used to create this container: /usr/share/lxc/templates/lxc-ubuntu
# Parameters passed to the template:
# For additional config options, please look at lxc.container.conf(5)

# Common configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf

# Container specific configuration
# lxc.start.auto = 1
# lxc.start.delay = 3
lxc.aa_allow_incomplete = 1
lxc.rootfs = /var/lib/lxc/devdesktop0/rootfs
lxc.mount = /var/lib/lxc/devdesktop0/fstab
lxc.utsname = devdesktop0
lxc.arch = amd64

# Network configuration
lxc.network.type = veth
lxc.network.link = br0
lxc.network.flags = up
lxc.network.hwaddr = 00:16:3e:xx:xx:xx

# Docker Inside
# lxc.mount.auto = cgroup
# lxc.aa_profile = lxc-container-default-with-nesting

lxc.aa_profile = unconfined
lxc.cgroup.devices.allow = b 7:* rwm
lxc.cgroup.devices.allow = c 10:237 rwm
```

I have docker running on the LXC host too. I stop the docker daemon on the LXC host but i still get the same problem.

docker -d (native driver):

```
INFO[0000] +job serveapi(unix:///var/run/docker.sock)
INFO[0000] +job init_networkdriver()
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock)
[cd589644.init_networkdriver()] WARNING: unable to enable IPv4 forwarding: open                                                                                              /proc/sys/net/ipv4/ip_forward: read-only file system
INFO[0000] -job init_networkdriver() = OK (0)
INFO[0000] WARNING: Your kernel does not support cgroup swap limit.
FATA[0000] Error loading docker apparmor profile: exit status 243 (/sbin/apparmo                                                                                             r_parser: Unable to replace "docker-default".  Permission denied; attempted to l                                                                                             oad a profile while confined?
Warning failed to create cache: docker
)
```

**Comment by jfrazelle** [comment]
we do this to build and test docker on lxc so I know it works

ping @ashahab-altiscale is there something he is missing?

**Comment by ashahab-altiscale** [comment]
@VictorArgote Can you run the lxc container(the host for the docker container) with --logpriority DEBUG, and paste the debug output?

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen

**Comment by haarts** [comment]
Reproducing: 

1. Get a host with Ubuntu 14.04.
2. Install LXC. Version 1.0.5
3. Create a container. Let's say a Ubuntu 15.04 one. `lxc-create -t download -n YOURNAME -- -d ubuntu -r vivid -a amd64`
4. Edit the `/var/lib/lxc/YOURNAME/config` file and add the lines `lxc.cgroup.devices.allow = a`, `lxc.mount.auto = cgroup` and `lxc.aa_profile = unconfined` (throwing all security overboard)
5. Start the container. `lxc-start -n YOURNAME -d`
6. Attach to it. `lxc-attach -n YOURNAME`
7. Install that latest  and greatest docker. `curl -sSL https://get.docker.com/ubuntu/ | sudo sh`
8. Notice that docker won't start. Read why in `/var/log/upstart/docker`
9. Install apparmor. `apt-get install apparmor`. Notice the `Permission denied` error, see also point 10.
10. Running `docker -d` now works. Using `service docker start` yields yet another error in the log: `/sbin/apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?`
11. I _can_ create a container now with the manually started Docker instance. `docker run -i -t ubuntu /bin/bash`

I think this is still broken and this ticket should be reopened.
I've installed `cgroups-lite` too to no avail, using Ubuntu 14.04 as the LXC container didn't work.
Also removing all the security is rather blunt.

I'm wondering why the docker package doesn't depend on apparmor and cgroup-lite BTW.

**Comment by mclarkson** [comment]
I'm having the same problem as @VictorArgote - docker native does not work under lxc (unconfined). It would be really great to have native docker running in lxc for our build and test. 

I also get the error for 'docker -d':
```
# docker -D -d
INFO[0000] WARNING: Your kernel does not support cgroup swap limit. 
FATA[0000] Error loading docker apparmor profile: exit status 243 (/sbin/apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?
Warning failed to create cache: docker
```
With, apparmor kern.log on the host showing:
```
Mar 11 11:14:40 ip-172-31-24-158 kernel: [ 2822.854520] type=1400 audit(1426072480.823:49): apparmor="STATUS" operation="profile_replace" info="not policy admin" error=-13 profile="unconfined" pid=4740 comm="apparmor_parser"
```
I cheated and made /sbin/apparmor_parser just return success error status(0), then 'docker -d' starts:
```
# docker -d
INFO[0000] Loading containers: done.                    
INFO[0000] docker daemon: 1.5.0 a8a31ef; execdriver: native-0.2; graphdriver: vfs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)
```
But, 'docker run' then fails with 'operation not permitted':
```
# docker run --rm hello-world
...
Cannot start container 9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7: write /sys/fs/cgroup/devices/lxc/ubtr1/docker/9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7/devices.allow: operation not permitted
INFO[0044] -job start(9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7) = ERR (1) 
ERRO[0044] Handler for POST /containers/{name:.*}/start returned error: Cannot start container 9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7: write /sys/fs/cgroup/devices/lxc/ubtr1/docker/9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7/devices.allow: operation not permitted 
ERRO[0044] HTTP Error: statusCode=500 Cannot start container 9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7: write /sys/fs/cgroup/devices/lxc/ubtr1/docker/9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7/devices.allow: operation not permitted 
FATA[0000] Error response from daemon: Cannot start container 9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7: write /sys/fs/cgroup/devices/lxc/ubtr1/docker/9bdcebbc01f62fd241951ea01fcbe2d0bf935cbc9185675e1a4e9508d50787f7/devices.allow: operation not permitted 
```
'docker -d -e lxc' works fine:
```
# docker -D -d -e lxc
INFO[0000] docker daemon: 1.5.0 a8a31ef; execdriver: lxc-1.0.7; graphdriver: vfs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)     
# docker run --rm hello-world
Hello from Docker.
This message shows that your installation appears to be working correctly.
...
```

CONFIG DETAILS:

docker info (inside lxc container):
```
Containers: 5
Images: 7
Storage Driver: vfs
Execution Driver: lxc-1.0.7
Kernel Version: 3.13.0-46-generic
Operating System: Ubuntu 14.04.2 LTS (containerized)
CPUs: 1
Total Memory: 992.5 MiB
Name: ubtr1
ID: 4MG2:RO3L:UY2H:NCD2:HBZA:L7K4:UNFS:AUY7:PMPP:7JB3:XLWM:BGTM
WARNING: No swap limit support
```
docker version(inside lxc container):
```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```
lxc config file:
```
# Template used to create this container: /usr/share/lxc/templates/lxc-download
# Parameters passed to the template: -d ubuntu -r trusty -a amd64
# For additional config options, please look at lxc.container.conf(5)

# Distribution configuration
lxc.include = /usr/share/lxc/config/ubuntu.common.conf
lxc.arch = x86_64

# Container specific configuration
lxc.rootfs = /var/lib/lxc/ubtr1/rootfs
lxc.utsname = ubtr1

# Network configuration
lxc.network.type = veth
lxc.network.flags = up
lxc.network.link = lxcbr0
lxc.network.hwaddr = 00:16:3e:b7:de:32

#lxc.aa_profile=lxc-container-default-with-nesting
#lxc.aa_allow_incomplete = 1
lxc.aa_profile = unconfined
lxc.cgroup.devices.allow = b 7:* rwm
lxc.cgroup.devices.allow = c 10:237 rwm
```

**Comment by mclarkson** [comment]
Thanks @haarts, for the 'lxc.cgroup.devices.allow = a'. I also needed 'lxc.cap.drop =' to get it to work without any errors (or cheats).

Is there any way to make this more secure?

**Comment by haarts** [comment]
@mclarkson and your `lxc.cap.drop =` removed the errors with me too! God, I love the internet. 

[This](https://www.stgraber.org/2014/01/01/lxc-1-0-security-features/) blog post is relevant to the security of the containers and mentions both Capabilities and Cgroups.

I think I'm on track figuring out what the correct Cgroup configuration options are. I found that whole business with major/minor numbers rather confusing. But I think I [figured it out](https://www.stgraber.org/2014/01/01/lxc-1-0-security-features/).

**Comment by mclarkson** [comment]
@haarts. That would be great. With the cap drop, docker info now shows devicemapper as the vfs, so that's nice and fast now, but docker does warn about this so not sure how safe it is. I had a thought also that the docker containers themselves are still as secure as before. By the way, your 'figured it out' link is the same as the 'This blog post' link.

**Comment by haarts** [comment]
(fixed the link)

**Comment by VictorArgote** [comment]
Hi @mclarkson  

Were you able to run docker inside a LXC container, i have used your config but not working for me, i get docker daemon running but i am not able to start any container:

```
docker start [container_name]
Error response from daemon: Cannot start container [container_name]: Container is not running
FATA[0005] Error: failed to start one or more containers
```

```
docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

```
docker info
Containers: 2
Images: 26
Storage Driver: vfs
Execution Driver: lxc-1.1.0.rc4
Kernel Version: 3.18.0-999-generic
Operating System: Ubuntu Vivid Vervet (development branch) (containerized)
CPUs: 4
Total Memory: 3.849 GiB
Name: devdesktop0
ID: ACI2:2T6Q:WHUO:ZPE5:YIY4:HEHN:OIYK:YUEQ:2LCA:5NEA:L2MS:QONC
WARNING: No swap limit support
```

**Comment by mclarkson** [comment]
@VictorArgote. This is all I need to do after a default 'lxc-create -t download ...'
```
cat >>/var/lib/lxc/$HOST/config <<EnD
lxc.aa_profile = unconfined
lxc.cgroup.devices.allow = a
lxc.cap.drop =
EnD
```
Then populate/mount '/sys/fs/cgroup' directories with cgroupfs_mount. Works well for me on Trusty with 1.0.7 and 1.1.0. I've not tried 1.1.1 yet.

I think LXC defaults to using lxcfs in certain circumstances, which doesn't help docker. Make sure 'cat /proc/1/mountinfo' shows actual cgroup mounts. For example:
```
141 167 0:25 / /sys/fs/cgroup/cpu rw,relatime - cgroup cgroup rw,cpu,release_agent=/run/cgmanager/agents/cgm-release-agent.cpu
```
I think the key to get docker working is to make sure that /sys/fs/cgroup has the right stuff in it - the right stuff, with the right permissions, and that they are actually cgroup mounts rather than tmpfs mounts (or whatever lxcfs does).

**Comment by echinthaka** [comment]
@mclarkson can you please explain how you did "Then populate/mount '/sys/fs/cgroup' directories with cgroupfs_mount."?

**Comment by IlyaSemenov** [comment]
@echinthaka, for example, on Proxmox 4.0 you do it like this:

    root@pve:/usr/share/lxc/config/common.conf.d# mv 00-lxcfs.conf 00-lxcfs.conf.disabled

and then restart your LXC instance.

**Comment by jam01** [comment]
@mclarkson @IlyaSemenov So this conf is preventing the container from mounting the cgroups? This worked for me and allowed me to user Docker. But after making that change all my other LXCs stopped working properly. 

1. What's the consequence of disabling that to other containers?
2. Is there a way to allow only the docker LXC to mount the cgroups?

Or am I misunderstanding something?

**Comment by ckhung** [comment]
I have the same problem as @jam01 . My solution is to leave /usr/share/lxc/config/common.conf.d/00-lxcfs.conf alone, and add the following to /etc/pve/lxc/$HOST.conf instead:
```
lxc.hook.mount =
lxc.hook.post-stop =
```
