### ISSUE TITLE
API Architecture Concerns

### ISSUE THREAD

**Issue by sirwolfgang** [docker/docker#6794]
While trying to automatically digest the api with ActiveRecord I ran into an issue with the number first hash keys. rails/activeresource#138
```
"Ports":{
  "4500/tcp":[
    {
      "HostIp":"0.0.0.0",
      "HostPort":"4500"
    }
  ]
}
```
It seems to me that ActiveRecord is/will not be the only thing thats going to have this issue. While this will not effect everything, I do think its of some importance to have an API layer that is easily digestible and programmatically object mappable. 

Something kinda like this?
```
"Ports":{
  "tcp":[
    {
      "SourcePort":"4500",
      "HostIp":"0.0.0.0",
      "HostPort":"4500"
    }
  ]
}
```

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/5893 and +1 we all would like a redesigned API
