### ISSUE TITLE
Use LXC go bindings rather than shell out

### ISSUE THREAD

**Issue by dineshs-altiscale** [docker/docker#6804]

**Comment by unclejack** [comment]
Given the complexity of the problem with linking libraries, do we need to keep this open? It doesn't seem like the issues block this today are going to be solved in the near future.

**Comment by runcom** [comment]
As LXC is being deprecated as per https://github.com/docker/docker/blob/master/docs/misc/deprecated.md#lxc-built-in-exec-driver I'm closing this. Feel free to reopen it if it's a mistake.
