### ISSUE TITLE
mkimage-yum: Copy /etc/rpm/platform

### ISSUE THREAD

**Issue by thomassuckow** [docker/docker#6809]
/etc/rpm/platform affects the packages that yum installs and therefore should be copied into the target

```
cp /etc/rpm/platform "$target"/etc/rpm/platform
```

By copying this file, it also means that an x86 container can use yum.

**Comment by justyntemme** [comment]
Opened PR to fix the issue, if I put the command in the wrong place in the script please let me know and i Iwill fix asap.

**Comment by andrewhsu** [comment]
Curious to know what is the original desire that is driving the request to put `/etc/rpm/platform` into the docker image that is created by `mkimage-yum.sh`?

This is a really old issue, but I've verified with the latest code from `master` branch today that it can create a proper image within the latest CentoOS 7 host operating system environment without `/etc/rpm/platform` in the host environment and without `/etc/rpm/platform` in the docker image:
```
$ sudo ./mkimage-yum.sh test
...
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
test                7.2.1511            0c1c79f46c54        24 minutes ago      245 MB
$ docker run --rm --entrypoint=/usr/bin/yum test:7.2.1511 -y install libjpeg-turbo
...
Installed:
  libjpeg-turbo.x86_64 0:1.2.90-5.el7                                           

Complete!
```

I have a feeling this issue may no longer be needed if it was a problem to work around in the past.

**Comment by thomassuckow** [comment]
It was to have x86 centos/rhel install the correct packages. I was using it test software on x86 RHEL 5 in a docker container. We've since stopped using x86 OS's almost entirely so I haven't had a need to push this.

**Comment by thaJeztah** [comment]
Thanks @thomassuckow, given the above, I think we should close this issue, unless there's strong demand from people to have it.
