### ISSUE TITLE
Enable SSL by default for TCP connections

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#6816]
tls and tlsverify should be on by default, with auto-generated keys if none provided, for TCP connections, and only allow non-tls with --insecure-but-i-know-what-im-doing

**Comment by jfrazelle** [comment]
i think this has been handled right @cpuguy83

**Comment by cpuguy83** [comment]
@jfrazelle Not really.

**Comment by chrisseto** [comment]
If this has not already been address, I'd like to take a shot at this.

**Comment by mike1729** [comment]
Is this still open?

**Comment by cpuguy83** [comment]
Still open.

**Comment by mike1729** [comment]
#dibs

**Comment by calavera** [comment]
I don't think we should do this. People still need to distribute and manage whatever certificate we generate. There is no difference with them generating the certificates manually. I'm going to close it.
