### ISSUE TITLE
Path is parsed as JSON in docker inspect and API

### ISSUE THREAD

**Issue by amuino** [docker/docker#6830]
When the command is parseable as JSON, the resulting JSON type is returned by inspect and API.

Example: `true` converted to boolean
```
$ docker run busybox true; docker inspect `docker ps -l -q` | grep \"Path\"
    "Path": true,
```

Example: `99` converted to a number
```
$ docker run busybox 99; docker inspect `docker ps -l -q` | grep \"Path\"
    "Path": 99,
```

Example: `{"a": "map"}` converted to a Hash (for fun)
```
$docker run busybox '{"a": "map"}'; docker inspect `docker ps -l -q` | grep -A 2 \"Path\"
    "Path": {
        "a": "map"
    },
```

**Comment by jfrazelle** [comment]
this issue was fixed, so closing, the other comments on here on the other hand are improvements to the jobs api etc.
