### ISSUE TITLE
docker help and man pages are not in sync with the command line reference documentation

### ISSUE THREAD

**Issue by wallrj** [docker/docker#6833]
Here's an example which has caused me some confusion recently:

The `docker-run` man page doesn't mention that an `IMAGE:TAG` combination is allowed
 * https://github.com/dotcloud/docker/blob/master/docs/man/docker-run.1.md#synopsis

Nor does the command line help:
 * https://github.com/dotcloud/docker/blob/master/api/client/commands.go#L1899

While the command line reference documentation does mention this:
 * https://github.com/dotcloud/docker/blob/master/docs/sources/reference/run.md#general-form

It would be nice if the command line help and man pages could be kept in sync with the command reference docs.
Perhaps they should be combined.

**Comment by jfrazelle** [comment]
looks like this has been taken care of, and as far as automating this is covered by #2583, closing
