### ISSUE TITLE
API/Docs: POST /images/create incomplete and misleading

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#6837]
The docs don't make it very clear that this endpoint does two things which require two different set of parameters:

- Pull from registry: fromImage, tag
- Create from local file: fromSrc, repo

And it's unclear/undefined what happens if fromImage or repo includes a tag.

Beside that, fromImage and repo are both image names ('fully qualified' if you want). Calling them 'image' here but 'repo' there is confusing.
Guess it's up for discussion if the api should be changed, but at least this should get documented.

Another thing are the responses: What happens if another client is already pulling an image? Which response code will it return?

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/5722
