### ISSUE TITLE
Adding arbitrary metadata to containers

### ISSUE THREAD

**Issue by rjnagal** [docker/docker#6839]
Following up from contributors' meeting today:

It would be nice to be able to store user-defined metadata for each container and be able to query on it.  Higher-level tools and schedulers can use this metadata to better manage containers on a machine.

Something along the lines of
 $ docker run --name foobar --metadata='key1:"value1"'
 $ docker metadata foobar
 $ docker metadata -a (for all containers)

There are multiple existing issues around metadata, but we couldn't find one thats about arbitrary metadata/labels applied to a container (#2336 talks about metadata originating from within the container). 

We talked about using environment variables, but we need metadata that needs to be dynamically updated and added after a container start. eg. Scheduling metadata can be applied when a container is stopped or restarted. 

Calling it a label seems to collide with image labels that are static. Using metadata can be confusing too, as containers already have metadata.

Any thoughts on what we'd like to see here (or not)?

**Comment by bfirsh** [comment]
A pull request: https://github.com/docker/docker/pull/9882

**Comment by thaJeztah** [comment]
@jfrazelle should this be closed, now that a design approval was given on https://github.com/docker/docker/issues/9882 ?

**Comment by jfrazelle** [comment]
up to @rjnagal

**Comment by rjnagal** [comment]
#9882 is the real deal. Happy to close this one out :)

**Comment by thaJeztah** [comment]
Thanks @rjnagal!
