### ISSUE TITLE
Decoupling daemon and container life cycle / long running init

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#6851]
Hi,

right now the container life cycle is coupled with the daemon, that means if you restart the daemon, all containers have to be restarted. This is a big issue for many services like data stores, caches but also critical services like load balancers etc.
After some discussion over the time it was decided to solve that by introducing a long running init and I've created this ticket to refer to it in discussions and track the progress.

**Comment by jdassonvil** [comment]
Any update on this issue ? So far we've experienced uneven instability with the docker daemon and losing all containers along with the daemon is not acceptable for our production standard :(

**Comment by cpuguy83** [comment]
@jdassonvil It's still being worked on, mostly by @shykes I think...

But if your daemon is crashing, please file an issue with the details.  It should not be crashing. And make sure you are using --restart=always on the containers you want to make sure are up after daemon restart.

**Comment by discordianfish** [comment]
It's also unacceptable to have to restart all containers if you update Docker.

**Comment by anandkumarpatel** [comment]
+1

**Comment by tobegit3hub** [comment]
+1 for the correct direction

**Comment by cpuguy83** [comment]
This is now complete. In docker 1.12 you can set the `--live-restore` to be able to restart docker without killing all containers (and of course re-attach once it's back up).

**Comment by erikh** [comment]
\o/

**Comment by erikh** [comment]
sincere props to michael and the team who helped put this together; I know
this was a lot of hard work.

**Comment by crosbymichael** [comment]
thx!

**Comment by discordianfish** [comment]
Woohoo thanks for making this happen!
