### ISSUE TITLE
mounting aufs leaves ro dir empty (devicemapper backend)

### ISSUE THREAD

**Issue by lez** [docker/docker#6875]
Hi,

I tried to mount a dir as an aufs inside a docker container.
I had the `ro_directory` with some files in it. I created an empty `aufs_rw` directory, and mounted it:
`mount -t aufs -o rw,dirs=/aufs_rw=rw none /ro_directory`

*Expected behaviour:* /ro_directory keeps its contents and I can write into that directory (and the change appears in /aufs_rw).
*Actual behaviour:* the /ro_directory became empty after aufs was mounted. The rest of the aufs functionality was kept, so when I created a file in /ro_directory, it appeared in the /aufs_rw.

When umounting the aufs, the contents of /ro_directory came back, files in /aufs_rw remained there.

Is aufs supported at all in docker?

system info:
It's a precise 12.04 fresh install.
$ uname -a
Linux lez 3.8.0-39-generic #57~precise1-Ubuntu SMP Tue Apr 1 20:04:50 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

$ docker version
Client version: 0.10.0
Client API version: 1.10
Go version (client): go1.2.1
Git commit (client): dc9c28f
Server version: 0.10.0
Server API version: 1.10
Git commit (server): dc9c28f
Go version (server): go1.2.1
Last stable version: 1.1.0, please update docker

$ docker -D info
Containers: 23
Images: 23
Storage Driver: devicemapper
 Pool Name: docker-8:1-3358791-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 1362.1 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 3.0 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.1
Kernel Version: 3.8.0-39-generic
Debug mode (server): false
Debug mode (client): true
Fds: 16
Goroutines: 25
EventsListeners: 0
Init Path: /usr/bin/docker
WARNING: No swap limit support

**Comment by jfrazelle** [comment]
you have devmapper backend and you are trying to mount aufs?, closing because failed to respond to issue since Jul, but feel free to ping me to reopen if this is still occuring on latest
