### ISSUE TITLE
500 Server Error with POST /container/create

### ISSUE THREAD

**Issue by matejkramny** [docker/docker#6894]
Sent a POST /container/create with an empty body.. Its sending HTTP 500 (server error) back, which isn't correct imho.

Should send something like bad request.

I'd like to help. Where can this be fixed?

**Comment by jfrazelle** [comment]
I believe this is fixed with the latest version of docker, please try and let us know.

**Comment by jfrazelle** [comment]
Closing as fixed in the latest version, if you feel this has been closed in error please ping me
