### ISSUE TITLE
Resume is untested

### ISSUE THREAD

**Issue by dmp42** [docker/docker#6903]
We need unit tests for resume (inc. tests that validate the content is correctly re-assembled).

@unclejack since you are the author of resume and we talked about it, I'm assigning it to you for now - re-assign to me if you can't work on it though.

**Comment by jfrazelle** [comment]
status on this anyone? is this something that should be in v2

**Comment by dmp42** [comment]
@jfrazelle unit tests for byte-range support (both resumable pull and push), yeah.
Might be black-belt++ though.

**Comment by aaronlehmann** [comment]
@dmp42: Is this issue still applicable? v1 pulls only do full downloads, and the recently merged resumable download support for v2 pulls is tested as part of golem.

**Comment by dmp42** [comment]
If v2 resume is tested on the CI, then we can happily close this :)

**Comment by thaJeztah** [comment]
I'll close then, thanks!
