### ISSUE TITLE
`attach` should still print stdout when receiving input non-interactively

### ISSUE THREAD

**Issue by foca** [docker/docker#6917]
I have a container to which I want to pass commands through stdin in a scripted fashion.

When running `docker attach <container> <<<"command"` I can see in `docker logs -f <container>` that it is actually getting the input, and printing some output. However, the `attach` process doesn't print anything to stdout (or stderr).

Is there something I'm missing? I'm running the container with `-t` and `-i`.

**Comment by jfrazelle** [comment]
closing, but let me know if you are able to reproduce on the latest version of docker and the exact steps you used to do so
