### ISSUE TITLE
Specify the IP address associated with the hostname

### ISSUE THREAD

**Issue by dineshs-altiscale** [docker/docker#6935]
Automatically associating the host name specified through `--hostname` to the default interface (172.17.42.x) in `/etc/hosts` breaks applications that need to use an alternate container interface (created through pipework, for example.)

**Comment by jfrazelle** [comment]
/etc/hosts is not read/write so you can modify this file to add your required data. There is also an --add-host flag from #8019 that allows you to add hosts entries that should solve your needs.
