### ISSUE TITLE
Docker Daemon Crashed when it failed to push to registry

### ISSUE THREAD

**Issue by sukrit007** [docker/docker#6978]
While trying to push docker image to the repository, my docker daemon died.  

Here is the output:
http://pastebin.com/6JfENyrL

docker --version
Docker version 1.0.1, build 990021a

Kernel : 3.8.0-35-generic

**Comment by jfrazelle** [comment]
@sukrit007 @lwf can you reproduce on the latest version

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen
