### ISSUE TITLE
Add label when running a container

### ISSUE THREAD

**Issue by gregory** [docker/docker#6997]
we'd then be able to stop them all in one time or remove them all in one time.
docker run --name redis -d  --label db foo/redis 
docker run --name mongodb --label db -d foo/mongodb
docker stop --label=db
docker start --label=db
docker rm -label=db

etc :) what do you guys think?

**Comment by jfrazelle** [comment]
@gregory if its alright with you can we combine yours into https://github.com/docker/docker/pull/9013 so that their are not #6839 numerous of the same issue

**Comment by unclejack** [comment]
This has been implemented by #9882.

**Comment by gregory** [comment]
awesome! thx for the update @unclejack
