### ISSUE TITLE
cli integration / integration tests improvements

### ISSUE THREAD

**Issue by unclejack** [docker/docker#7010]
This issue is meant to track the changes to be made to the cli integration / new integration tests.

The goal is to gather feature requests, discuss changes and add tasks below.
Please don't add tasks below without approval.

Tasks:
- [x] add "expected failure" version of the run commands and cmd
- [x] add more utilities
- [ ] use /tmp for docker build tests
- [x] shorten tests to use utility functions
- [ ] write test writing guidelines, including coding style
- [ ] find solutions for slow tests (like the tests which pull images from the hub)
- [x] rewrite tests which rely on remote servers to use a local server
- [x] figure out the sleep vs top issues

**Comment by jfrazelle** [comment]
I think we are pretty close to removing integration entirely right :D

**Comment by tiborvass** [comment]
@jfrazelle this issue is solely about the integration-cli tests. But yeah we need to also remove the integration folder.

**Comment by jfrazelle** [comment]
sorry reading too many things at once got excited

**Comment by icecrime** [comment]
Not that we're done improving our test campaign, but unfortunately our problems have changed since that issue was opened (not all of them, though) :cry: Thanks, I'm closing!
