### ISSUE TITLE
Container pinning

### ISSUE THREAD

**Issue by Xe** [docker/docker#7017]
Would it be possible to "pin" a container so that it needs to have an extra flag passed to it (something like `--purge`) in order for the container to actually be deleted via `docker rm` or similar commands?

**Comment by cpuguy83** [comment]
Closing b/c @shykes comment here: https://github.com/docker/docker/pull/7523#issuecomment-59592874

Solution is to use labels (which are in 1.6) to tag a container as you see fit and use `docker ps --filter` to filter these out when deleting.
