### ISSUE TITLE
Difference in application behavior on boot2docker vs Fedora

### ISSUE THREAD

**Issue by t0nyhays** [docker/docker#7041]
I am running into an issue running my application in boot2docker, and I don't see the failure when running in Fedora.  When I change the order of instructions in Dockerfile it works in both places.  Sorry for the format here I am not sure of the best way to present all of the info.

t0nyhays/wildfly on DockerHub and GitHub

When it works wildfly starts inside docker

"07:27:44,899 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: WildFly 8.1.0.Final "Kenny" started in 6651ms - Started 184 of 233 services (81 services are lazy, passive or on-demand)"

When it fails

"Caused by: java.io.FileNotFoundException: /opt/wildfly/standalone/log/server.log (No such file or directory)" it is a permissions error on the /opt/wildfly/standalone directory.

>>> OSX

```
bash-3.2$ uname -a
Darwin tonys-mbp 13.3.0 Darwin Kernel Version 13.3.0: Tue Jun  3 21:27:35 PDT 2014; root:xnu-2422.110.17~1/RELEASE_X86_64 x86_64
bash-3.2$ docker version
Client version: 1.1.0
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): 79812e3
Server version: 1.1.0
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): 79812000
bash-3.2$ docker -D info
Containers: 1
Images: 42
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 44
Execution Driver: native-0.2
Kernel Version: 3.15.3-tinycore64
Debug mode (server): true
Debug mode (client): true
Fds: 11
Goroutines: 11
EventsListeners: 0
Init Path: /usr/local/bin/docker
Sockets: [unix:///var/run/docker.sock tcp://0.0.0.0:2375]
Username: t0nyhays
Registry: [https://index.docker.io/v1/]


>>>> Fedora
[root@cicley ~]# uname -a
Linux cicley.ci.neoninternal.org 3.14.8-200.fc20.x86_64 #1 SMP Mon Jun 16 21:57:53 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[root@cicley ~]# docker version
Client version: 1.0.0
Client API version: 1.12
Go version (client): go1.2.2
Git commit (client): 63fe64c/1.0.0
Server version: 1.0.0
Server API version: 1.12
Go version (server): go1.2.2
Git commit (server): 63fe64c/1.0.0
[root@cicley ~]# docker -D info
Containers: 5
Images: 15
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.14.8-200.fc20.x86_64
Debug mode (server): false
Debug mode (client): true
Fds: 18
Goroutines: 28
EventsListeners: 0
Init SHA1: 9a88fe86fcd333ca43c124a5446db84dc23529ff
Init Path: /usr/libexec/docker/dockerinit
```

>>>   Dockerfile that only works on Fedora>>>>>

https://gist.github.com/t0nyhays/c76224f71196d936f544#file-gistfile1-txt

>>>   Dockerfile that works in both >>>>>

https://gist.github.com/t0nyhays/57df8fc4f861b9014a53#file-gistfile1-txt

Only difference being the order of lines 18 & 20.

**Comment by jfrazelle** [comment]
can you try with the latest version of docker and boot2docker and if the problem lies in boot2docker please open an issue on that repo
