### ISSUE TITLE
docker inspect does not show IPv6 addresses

### ISSUE THREAD

**Issue by MalteJ** [docker/docker#7042]
"docker inspect mycontainer" does not show container's IPv6 address:

    "NetworkSettings": {
        "Bridge": "docker0",
        "Gateway": "172.17.42.1",
        "IPAddress": "172.17.0.8",
        "IPPrefixLen": 16,
        "PortMapping": null,
        "Ports": {}
    },

the ifconfig output inside the container:

    root@5f54af0a7db0:/# ifconfig
    eth0  Link encap:Ethernet  HWaddr 96:79:64:33:6f:17
          inet addr:172.17.0.9  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: 2a11:4f8:140:2425:9479:64ff:fe33:6f17/64 Scope:Global
          inet6 addr: fe80::9479:64ff:fe33:6f17/64 Scope:Link
          UP BROADCAST RUNNING  MTU:1500  Metric:1
          RX packets:13 errors:0 dropped:4 overruns:0 frame:0
          TX packets:7 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1490 (1.4 KB)  TX bytes:586 (586.0 B)

It would be nice to have a key "IPv6Address" under "NetworkSettings".

**Comment by GM-Alex** [comment]
Any news on making the global IPv6 inspectable?

**Comment by jfrazelle** [comment]
It will be 1.5 :)

**Comment by GM-Alex** [comment]
@jfrazelle Great! :+1:
