### ISSUE TITLE
allow docker build git:// to build subdirectories

### ISSUE THREAD

**Issue by paultag** [docker/docker#7071]
`docker build -t paultag/postgres git://github.com/paultag/dockerfiles.git#subdir=postgres` (or something like that) ought to DTRT. I'm not seeing much by way of docs for doing this, so if this is implemented, feel free to retitle this to a documentation bug.

**Comment by calavera** [comment]
I've implemented this in #12769. Feedback will be really appreciated.

**Comment by dothebart** [comment]
Hi, I ve been really trying to use this, and I'm failing miserably.

    sudo docker build https://github.com/arangodb-helper/build-docker-containers.git#master:/distros/centos/6/

stracing this leads to:

    [pid 31377] execve("/usr/bin/git", ["git", "clone", "--recursive", "https://github.com/arangodb-helper/build-docker-containers.git#master:/distros/centos/6", "/tmp/docker-build-git705631543"], [/* 14 vars */] <unfinished ...>

which if executed also fails. I've tried `git://`, all variations of the branch from empty, HEAD, master... no success. Specifying all sorts of directory structures like only distros, distros/centos/6/Dockerfile - nothing is working

One of the error messages when trying with git:// looks like this:

    arangodb-helper/build-docker-containers.git#HEAD:/distros is not a valid repository name
    Email support@github.com for help

**Comment by thaJeztah** [comment]
@dothebart did you try without the leading `/` for the folder? This seems to work for me:

```
docker build https://github.com/arangodb-helper/build-docker-containers.git#master:distros/centos/6/
```

**Comment by dothebart** [comment]
Ah, docker version to old - didn't contain this feature. Just updated my workstation...
