### ISSUE TITLE
API/Docs POST: /containers/create explain configuration structure

### ISSUE THREAD

**Issue by dustinlacewell** [docker/docker#7073]
It would be super helpful if the documentation for this endpoint explained or listed a small note about what each of the parameters actually do and what the possible values for properties who's values are objects.

I am aware that this is the same object gleamed from `docker inspect` however to my knowledge this structure isn't precisely described in any part of the documentation. 

For example, the documentation has the following text:

     {
             "Hostname":"",
             "User":"",
             "Memory":0,
             "MemorySwap":0,
             "AttachStdin":false,
             "AttachStdout":true,
             "AttachStderr":true,
             "PortSpecs":null,
             "Tty":false,
             "OpenStdin":false,
             "StdinOnce":false,
             "Env":null,
             "Cmd":[
                     "date"
             ],
             "Image":"base",
             "Volumes":{
                     "/tmp": {}
             },
             "WorkingDir":"",
             "DisableNetwork": false,
             "ExposedPorts":{
                     "22/tcp": {}
             }
        }

I think we should denote what the possible values of the properties such as `ExposedPorts`, `Volumes`, and `Cmd` in the section for this endpoint, or describe the configuration structure elsewhere and link to it from here, and similiar endpoints that utilize it like the inspection endpoint (/containers/(id)/json)

**Comment by thaJeztah** [comment]
I see there's an open ticket for documenting the "output" as well (https://github.com/docker/docker/issues/1366) Just read that a new help is hired https://github.com/docker/docker/issues/254#issuecomment-71093443 @fredlf ? :smile:

**Comment by fredlf** [comment]
@thaJeztah Yes, help is on the way and API docs will be one of the very first things she tackles. We are painfully aware of this backlog!

**Comment by thaJeztah** [comment]
@fredlf no rush, I know there's a judge workload resting on your shoulders. Just politely "pinging" you here-and-there if I think issues could be related or picked up simultaneously.

I *could* try to start on this myself, but would have to do a bit of research, as I don't use the API directly.

**Comment by cpuguy83** [comment]
Closing since these are now documented for the last few API versions.
