### ISSUE TITLE
Docker error at higher core counts on a multi core machine

### ISSUE THREAD

**Issue by golangdjango** [docker/docker#7084]
Hello All,

I am running a Centos Container using docker on a RHEL 65 machine. I am trying to run an MPI application (MILC) on 16 cores. 
My server has 20 cores and 128 GB of memory. 
My application runs fine until 15 cores but fails with the "APPLICATION TERMINATED WITH THE EXIT STRING: Bus error (signal 7)" error when using 16 cores and up. At 16 cores and up these are the messages I see in the logs.

Jul 16 11:29:17 localhost abrt[100668]: Can't open /proc/413/status: No such file or directory
Jul 16 11:29:17 localhost abrt[100669]: Can't open /proc/414/status: No such file or directory
Jul 16 11:29:17 localhost abrt[100670]: Can't open /proc/417/status: No such file or directory

A few details on the container
kernel 2.6.32-431.el6.x86_64
Official centos from docker hub
Started container as
docker run -t -i -c 20 -m 125g --name=test --net=host centos /bin/bash

I would greatly appreciate any and all feedback regarding this. Please do let me know if I can provide any further information.

Regards

**Comment by jfrazelle** [comment]
can you give us the output of `docker info` and `docker version`

**Comment by jfrazelle** [comment]
closing, failure to give more info, ping me if you think this has been closde in error

**Comment by 5tefan** [comment]
I am running into this issue as well. (I think)

The code I am running tries to create 200 files during initialization by calling an external program which reads a template and creates an initial file. A variable number of these, under ~20 are successfully created and then it prints lots of "No such file or directory" errors (many more than 200?). The source of the error is during the creation of the initial files, not reading the template. [This source line](https://github.com/Unidata/netcdf-c/blob/18f4bca367140fc05be78287da26a34ebc3d9286/ncgen/genbin.c#L59) is where the error is occuring. Possibly relevant is also that both the template and the resulting files are in a directory that is mounted from the host with -v. 

Within dmesg log, I was seeing lots of messages like this:
[6175855.887022] Pid 601(my_program) over core_pipe_limit
[6175855.887023] Skipping core dump
Initially, kernel.core_pipe_limit was set to 4, but I set it to 0, however, the problem persists.

Is this related to the warning about using the loopback device in `docker info`?

`docker version`:
++++++++++++++++++
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:
 OS/Arch:      linux/amd64

`docker info`: 
++++++++++++++++++
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 23
Server Version: 1.12.1
Storage Driver: devicemapper
 Pool Name: docker-202:2-2600468885-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 2.418 GB
 Data Space Total: 107.4 GB
 Data Space Available: 105 GB
 Metadata Space Used: 3.813 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.144 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.107-RHEL7 (2016-06-09)
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-327.18.2.el7.x86_64
Operating System: Red Hat Enterprise Linux Server 7.2 (Maipo)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 239.8 GiB
Name: beef
ID: ZCZZ:KPYN:OYUM:HOZ3:DPUO:NDOY:I2DY:MJK3:T63W:5AK7:U373:QOKG
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
Labels:
 provider=generic
Insecure Registries:
 127.0.0.0/8
