### ISSUE TITLE
Docker fails to stop if container ignores signals

### ISSUE THREAD

**Issue by phemmer** [docker/docker#7086]
This is a continuation of #6815 which was closed as the solution in the PR could not be agreed upon.

This is a general issue to track the problem where containers don't stop when signaled, causing the docker daemon to fail to stop.

Simple test:

    docker run -d fedora sleep 100000
    pkill -x docker
    sleep 5
    pgrep -x docker && echo "DOCKER IS STILL RUNNING!"

The `sleep` process fails to exit because of the PID 1 issue, where the default signal handler for PID 1 is set to ignore. Because the container won't exit, the docker process doesn't shut down.

**Comment by thaJeztah** [comment]
@jfrazelle can you check if this can be closed, now that https://github.com/docker/docker/pull/12400 was merged? See https://github.com/docker/docker/pull/12400#issuecomment-103923246

**Comment by runcom** [comment]
ping @phemmer 
from testing with the above commands seems like this has been fixed, could you try this yourself?

**Comment by vdemeester** [comment]
@phemmer @runcom same here, can't reproduce anymore

**Comment by cpuguy83** [comment]
Yep, this should be resolved now.
PID1 is still an issue, but that should be resolved by #26061 which is really being tracked here: #3793 (and probably elsewhere).

Closing, but LMK if I'm doing so in err.
