### ISSUE TITLE
Proposal: Add `--privlieged-complain` mode.

### ISSUE THREAD

**Issue by timthelion** [docker/docker#7118]
**Abstract:** In order to assist in determining which `--cap-add` and `--device` flags must be used for the proper functioning of an image, we introduce `--privileged-complain` mode as an analog to [Apparmor's identical complain mode](http://manpages.ubuntu.com/manpages/trusty/en/man7/apparmor.7.html)

**Motivation:** For the last 3 centuries, we in the Docker community have turned to `--privileged` for all our "it doesn't work in Docker but it works outside docker" needs.  This has worked great, but it has left Docker with gapping security holes and runtime inconsistencies.  As of today, two new flags in Docker, `--cap-add` and `--device` make `--privileged` almost unnecessary.  However, it is quite difficult to determine exactly which capabilities are needed by a `--privileged` container.  We would like to add a `--privlieged-complain` mode which would help people adopt `--cap-add` and `--device` by telling them which `--cap-add` and `--device` flags they need in order for their container to run correctly.

**Current work around:** You can run your docker container with various caps until you find a set that works.  Or, you can simply use `--privleged`.

**Proposal proper:** We would like to add a new flag `--privileged-complain` to `docker run`.

**Ex:**

    docker run -i -t --privileged-complain my-apache-java-service

`--privileged-complain` would work the same as `--privileged`, giving the container full access to all caps and devices.  However it would also write to a complaints file at the path `/var/log/docker/complaints/<image-tag>/<image-id>` every time the running container used a cap or a non-standard device.

For example, after running apache, the complaints file looks like:

````
docker run -i -t --cap-add=cap_net_bind_service --device=/dev/fuse my-apache-java-service
````

The complaints file should look like a valid docker run command, replacing the `--privileged-complain` argument with the caps and devices that were used by the container while it was running.  This will make it very easy for people to determine which caps they need.

**Implementation sketch:** I have not investigated implementation details.

**Comment by cpuguy83** [comment]
@timthelion Thanks for this, however I think this can be accomplished (and probably more easily) by running the image with a shell and then trying to start the process you wanted.
Closing as I don't think this is really feasible or the right place for the daemon to handle.
