### ISSUE TITLE
PROPOSAL: Volume snapshotting

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#7127]
A lot of people have issues with backing up volumes.
This can be done with certain tools and hackery, but is also not completely ideal because just tarring up a volume isn't safe for certain applications, such as database dirs.

It would be extremely helpful, for example, to be able to put a container's volume into a devmapper volume and provide an API for creating a devmapper volume snapshot on that volume.
Essentially every new volume would get it's own devmapper volume for snapshotting purposes.

My original thought here was to just use devmapper to create these for all volumes, but in discussion with others decided enforcing devmapper here may not be ideal... for instance what if someone is using btrfs as their host's FS, this would just cause unneeded overhead.
So providing a way to use any graph driver for volume snapshotting would be ideal with some sane default (perhaps just devmapper or whatever is set as the main graph driver).

**Comment by neilellis** [comment]
+1

**Comment by hansgru** [comment]
+1
with VMWare we use allot of snapshots and it's an extremely useful feature.

**Comment by sroze** [comment]
:+1:

**Comment by cpuguy83** [comment]
Closing as this should be handled by external volumes (plugins), which are now part of the experimental channel.
