### ISSUE TITLE
Attaching stdin doesn't work unless stdout is attached

### ISSUE THREAD

**Issue by stuartpb** [docker/docker#7143]
```
$ echo foo | sudo docker run -i -a stdin ubuntu bash -c "echo start; cat; echo end"
94bf604f4a5b8befdae2d184d907d30140c3129950e9f6f40a01686afde4b4ba
$ sudo docker logs 94bf
```

Expected output:

```
start
foo
end
```

Actual output:

```
start
end
```

`sudo docker run -i ubuntu cat` and `sudo docker run -i -a stdin -a stdout ubuntu cat` both work as expected (outputting "foo") - the problem only manifests when *only stdin* is attached.

This is on Arch Linux.

Version info:

```
Client version: 1.1.1
Client API version: 1.13
Go version (client): go1.3
Git commit (client): dc62f3c
Server version: 1.1.1
Server API version: 1.13
Go version (server): go1.3
Git commit (server): dc62f3c
```

**Comment by amouat** [comment]
Further to this, why is the `-i` necessary? Why doesn't this work?

    echo "hello" | docker run -a stdin -a stdout ubuntu cat

If `-i` is needed to use `-a stdin`, what's the point of `-a stdin`?

Apologies if this isn't relevant or muddies the waters, I thought it might help debugging.

**Comment by calavera** [comment]
I believe this issue has been fixed, at least in Docker 1.6.0.

This is a screenshot of the original command line running with the most recent version:

![1 zsh 2015-04-23 13-56-51](https://cloud.githubusercontent.com/assets/1050/7307298/bf0b02fc-e9c0-11e4-8e3c-b8c12a0abf7b.png)

Please, feel free to reopen the issue if you find the problem again.

**Comment by tonypujals** [comment]
I realized this is a closed issue, but I'm really curious how any of you got your examples to work. Anomalies from previous versions? @stuartpb and @calavera, how are you getting the container ID (and piping it to xargs in the screenshot) when not running detached? And if detached, how can you avoid the conflict with the -a option?

**Comment by amoghe** [comment]
> Further to this, why is the -i necessary?

@amouat were you able to find an explanation for this? If so, could you please share it here.

**Comment by amoghe** [comment]
Turns out that `-a stdin` without `-i` is meaningless (as per https://github.com/moby/moby/issues/30816)

**Comment by amouat** [comment]
Don't ask me, I don't want to go down this rabbit hole again :)
