### ISSUE TITLE
Adding EULAs to images

### ISSUE THREAD

**Issue by flavio** [docker/docker#7153]
Right now it's not possible to associate EULA to images. That prevents the distribution of images based commercial Linux distribution (think about SUSE Linux Enterprise or Red Hat Enterprise Linux) or images containing commercial software.

I work at SUSE. We would like to publish official SLE images on Docker's index, but the lack of this feature is blocking us.

It would be nice to have the EULAs associated to an image displayed upon the initial "docker pull" so that the user can read and accept/refuse them.

I realize that would require quite some changes (Docker server, Docker cli tool and registry at least).

**Comment by thaJeztah** [comment]
Linking this to [Proposal: One Meta Data to Rule Them All => Labels #9882](https://github.com/docker/docker/pull/9882), which will allow adding custom meta-data to images, e.g.

```Dockerfile
LABEL com.suse.eula="Lorem ipsum..."

# Or, if a standard label is decided on for all EULAs
LABEL com.docker.distribution.eula="Lorem ipsum..."
```
which could be a start.

**Comment by LK4D4** [comment]
@thaJeztah what's up here? I know windows and oracle has images, dunno how does that work.

**Comment by thaJeztah** [comment]
For Windows, I guess the license is "in place", because you can only pull/run them on a Windows machine. For RHEL, I noticed that a redirect is in place to pull the actual images from their servers, also (possibly Oracle as well, ping @Djelibeybi ?) you'll get the Image, but you need to add a subscription to actually do anything with them (i.e., to install software from their repositories);

```bash
$ docker run -it --rm rhel7 yum install curl

Loaded plugins: ovl, product-id, search-disabled-repos, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
There are no enabled repos.
 Run "yum repolist all" to see the repos you have.
 You can enable repos with yum-config-manager --enable <repo>
```

**Comment by Djelibeybi** [comment]
@thaJeztah Unlike other enterprise distributions, Oracle Linux is free to download, distribute and use and our Docker image is preconfigured to use our publicly available yum repos. The standard GPL EULA is included within the image (as it would be on a bare-metal install). We don't require a subscription.

**Comment by thaJeztah** [comment]
Thanks @Djelibeybi 

@flavio would a similar approach work for SUSE as well? I guess an EULA can still be included in the description on Docker Hub.

**Comment by flavio** [comment]
@thaJeztah: this is no longer a problem for us. We don't require this feature anymore.

Thanks!

**Comment by LK4D4** [comment]
@flavio thanks for update
Going to close, because not a problem for anyone :)
