### ISSUE TITLE
Traceable Consistent 'Docker' messages for automated testing, QE, debugging 

### ISSUE THREAD

**Issue by ipbabble** [docker/docker#7161]
Currently there seems to be at least two ways to handle error messages:
fmt.Errorf (std golang error handler)
utils.Errorf (part of docker/utils/utils.go )
(are there more?)

There are two issues I'd like to discuss:

1. Consistent use and policy over which gets used where - currently it seems as if utils.Errorf is used in conjunction with utils.Debugf, i.e. used for debugging code rather than production system use. (?) fmt.Errorf gets used for logging errors in normal non-debug (production) env.

2. When lots of infrastructure and applications are logging to stdout/stderr the ability to identify where a message is originating from quickly, e.g. docker, is important. Especially in automated QE and CI/CD environments.  So is there a simple way we can prefix Docker msgs with "Docker" or "docker" and then "Error" etc. ? 
<date><time> Docker-Error: <msg> 

I can see this might become more important as Docker gets used more and more in CI/CD envs.

That's the best way I can word these issues. Perhaps others have strong more articulate  arguments. 

William

**Comment by cpuguy83** [comment]
I think this is really up to whatever is capturing the logs to tag the log messages to something that makes sense for that installation.
On ubuntu upstart is picking up the logs, on systemd journald is (and tags by service).
`utils.Error` is not around anymore and all logging is being done by logrus.

I think we can close this?
