### ISSUE TITLE
top api is not consistent

### ISSUE THREAD

**Issue by enlinxu** [docker/docker#7205]
Hi,
I am quite new to docker, but already impressed about its capability!

One question I have is when I run the /container/id/top api, I got some attributes value back, but not as the ones I see in documentation.

From documentation, I see:
List processes running inside a container
GET /containers/(id)/top

List processes running inside the container id

**Example request**:

    GET /containers/4fa6e0f0c678/top HTTP/1.1

**Example response**:

    HTTP/1.1 200 OK
    Content-Type: application/json

    {
         "Titles":[
                 "USER",
                 "PID",
                 "%CPU",
                 "%MEM",
                 "VSZ",
                 "RSS",
                 "TTY",
                 "STAT",
                 "START",
                 "TIME",
                 "COMMAND"
                 ],
         "Processes":[
                 ["root","20147","0.0","0.1","18060","1864","pts/4","S","10:06","0:00","bash"],
                 ["root","20271","0.0","0.0","4312","352","pts/4","S+","10:07","0:00","sleep","10"]
         ]
    }

But when I run the same api on my dock enabled VM, I got

    "Processes": [
        [
            "root",
            "27467",
            "1449",
            "0",
            "19:39",
            "pts/3",
            "00:00:00",
            "/bin/bash"
        ],
        [
            "root",
            "28010",
            "27467",
            "0",
            "19:46",
            "pts/3",
            "00:11:03",
            "/bin/bash"
        ]
    ],
    "Titles": [
        "UID",
        "PID",
        "PPID",
        "C",
        "STIME",
        "TTY",
        "TIME",
        "CMD"
    ]

which doesn't contain the cpu and mem %. Is there anything I need to enable?

My docker version is 
suse64:~ # docker version
Client version: 1.1.1
Client API version: 1.13
Go version (client): go1.3
Git commit (client): dc62f3c
Server version: 1.1.1
Server API version: 1.13
Go version (server): go1.3
Git commit (server): dc62f3c

Thanks a lot in advance.
Jannle

**Comment by thaJeztah** [comment]
@MHBauer I'm good with updating the examples in the docs, are you interested in creating a PR?

**Comment by MHBauer** [comment]
Absolutely. I am not aware of how important the `top` api is considered, so I don't want to have too in-depth of an example if it's not wanted. I was thinking of 

 - describe that the default is equivalent to running `ps -ef` (at least on unix type machines)
 - show an example
 - describe that because it's basically a pass-through to `ps`, that other arguments will work
 - show an example of other arguments

Is that too much, or am I off base?

**Comment by thaJeztah** [comment]
@MHBauer sounds good to me, but we can always discuss further on the pull request if needed
