### ISSUE TITLE
Docker tty eats my newlines

### ISSUE THREAD

**Issue by trickkiste** [docker/docker#7214]
obecli is a docker container which starts a CLI that I want to send commands to from the host system. I initially created it with "sudo docker run -i -t myuser/obecli".

The following sequence works, when I do it with the native obecli process, but not with docker.

sudo screen -m -d -S obe docker start -a obecli
sudo screen -p 0 -S obe -X stuff $'set input decklink\012'

When i now do "sudo screen -x obe" I see obecli hung and not accepting any new input. No idea why. When I do that without docker, this stuff works just fine!!!

This does not work either:
sudo tmux new -s obe -d "docker start -a obecli"
sudo tmux send -t obe.0 "set input decklink" ENTER
sudo tmux a -t obe

Same result.

**Comment by jfrazelle** [comment]
Closing as fixed on the latest version, feel free to ping me if you feel this has been closed in error
