### ISSUE TITLE
Need reliable way to wait on container initialization

### ISSUE THREAD

**Issue by virtuald** [docker/docker#7228]
Use case is a docker service like https://github.com/progrium/ambassadord in magic omni mode. It has two containers that are required to make it work, and the second is linked to the other containers network via `--net container:xxx`. I could sleep, but that ends up being a nasty race condition, and I get errors like `Cannot start container xxxx: cannot join network of a non running container`.

Perhaps the command could be 'docker ready CONTAINERNAME'.

I'm new to docker, so alternative approaches are welcome. :)  However, this does seem like a necessary piece to have for multiple docker containers to work together in complex ways, so I wouldn't be surprised if there's already a good way to do this.

**Comment by znerol** [comment]
[Related discussion on CoreOS Dev](https://groups.google.com/d/msg/coreos-dev/qbVrYpDUtG8/t88RbGD_assJ) and [another one](https://groups.google.com/d/msg/coreos-dev/wf7G6rA7Bf4/Olmxmo13WKQJ)

**Comment by znerol** [comment]
Also #6791

**Comment by ibukanov** [comment]
For a workaround with systemd see https://github.com/docker/docker/issues/6791#issuecomment-72338100

**Comment by jfrazelle** [comment]
duplicate https://github.com/docker/docker/issues/6791
