### ISSUE TITLE
Proposal: Config file for default command line options

### ISSUE THREAD

**Issue by bfirsh** [docker/docker#7232]
Docker needs a way of specifying options to "docker run" in a file.

You shouldn't have to write all this:

    docker run -i -t --volumes-from=shykes-dev -v /var/run/docker.sock:/var/run/docker.sock -u 0 --name project -h project shykes/devbox bash

Instead, this could be in a file called `.docker/config`:

    [run]
    interactive=true
    tty=true
    volumes-from=shykes-dev
    volume=/var/run/docker.sock:/var/run/docker.sock
    user=0
    name=project
    host=project
    image=shykes/devbox
    cmd=bash

Then you can just run `docker run` in the same directory as that file.

This is a bit like how `.git/config` works, where you can, for example, specify options under a `[log]` section that overrides options on `git log`.

You could also specify what file to use with the `--config` option, like so:

    docker --config=/etc/docker/config run

If you want to disable the config and specify options manually, there could be a `--no-config` option.

Environment variables could be specified by using the `env-file` option.

**Comment by bfirsh** [comment]
Docker Machine has a concept of an "active" machine, where we want the Docker client to be automatically configured to talk to that machine – i.e. having the `-H` and `--auth` flags automatically set.

We could use environment variables, but there's no neat way to do this without a manual step. These are the current instructions after creating a machine:

```
INFO[0078] "test" has been created and is now the active machine. To point Docker at this machine, run: export DOCKER_HOST=$(machine url) DOCKER_AUTH=identity
```

What I would quite like to do is to use a configuration file to set these options. I think the first version could just be the top-level Docker options in an ini-format file. For example in `~/.docker/config`:

```
[general]
host=tcp://10.1.2.3:2376
auth=identity
log-level=debug
```

The naming of the top-level key could do with some thought, but we can rename in the future without much pain. Ideas: `[engine]`, `[client]`?

One concern is automatically generating this file from Machine, which may overwrite a user-written file. I wonder if we need some kind of `config.d` system...

@shykes @crosbymichael @jfrazelle @vieux @thaJeztah @SvenDowideit @tianon thoughts?

**Comment by ehazlett** [comment]
What if instead of overwriting from Machine we just parse and adjust the needed options?

**Comment by thaJeztah** [comment]
*Ideally* I would expect Docker Machine to be able to manage multiple machines and be able to switch to a different machine just by usingDocker Machine, e.g. `machine active production` (or `machine switch production` - I don't like "active" as an instruction, but that's preference). This also works around the current assumption that `bash` is used as shell and would allow machine to run on Windows in future.

I don't think *overwriting* settings is necessary if the ini-file uses inheritance ([example](http://framework.zend.com/manual/1.12/en/zend.config.adapters.ini.html));

```ini
[global]
host = unix:///var/run/docker.sock
auth = identity

[staging : global]
host = tcp://123.456.789

```

each machine can have its own config and inherit settings from the global configuration.

**Comment by bfirsh** [comment]
@thaJeztah Machine already has a concept of an active machine and can switch between them. I don't think we don't want Docker to be aware of Machine. Instead we want Machine to be able to instruct Docker which host it should be talking to.

Two reasons:

1) Loose coupling. Docker doesn't need to be aware of Machine existing.
2) Machines don't have fixed IP addresses, so Machine needs to execute a bit of code to figure out where they are.

**Comment by thaJeztah** [comment]
@bfirsh Yes, you're absolutely right; the actual "switching" should be handled by docker, machine should only *instruct* the docker-client which machine/host to use.

wrt switching hosts (thinking out loud here); I can see this possibly conflicting with using swarm, i.e. if `machine create` automatically switches to the newly created machine, it will reset the host/ip for swarm (when using environment variables for that; the current examples for swarm explicitly use `-H <swarm_ip:swarm_port>`)

**Comment by bfirsh** [comment]
@thaJeztah Yes, that could be a problem. I think environment variables and the `-H` flag should override whatever is in a config file.

**Comment by thaJeztah** [comment]
There's also the case of hosts that are *not* maintained/created by Swarm or Machine. If Docker only keeps track of the *current* host, then switching to another host will overwrite that information. Which brings us back to https://github.com/docker/docker/issues/7232#issuecomment-68545474

A possible solution would be to have Docker keep a *list* of host-configurations and allow switching between them. Machine, Swarm and other software would be able to add/update/remove a configuration in that list.

But that overlaps a lot with the functionality that Machine offers (apart from not offering the actual *creation* and provisioning of new hosts).

**Comment by jfrazelle** [comment]
so is this compose?

**Comment by thaJeztah** [comment]
I think @bfirsh hijacked his own issue, describing a different use case starting from this https://github.com/docker/docker/issues/7232#issuecomment-68545474

I suggest to;
- close this issue; the original use case is covered by compose; adding similar features to Docker itself would only confuse users
- create a new proposal based on the use case described in https://github.com/docker/docker/issues/7232#issuecomment-68545474 and below.

**Comment by duglin** [comment]
where are we on this?

We have a config file that can be used to store additional (common) config properties (like DockerHost).

I'm not sure we should use a "config file" for properties that specific to just one command though.  The example specified in the original comment ( https://github.com/docker/docker/issues/7232#issue-38691574 ) is odd to me - that feels more like using a text file to represent the cmd line flags - I would call that more like a compose yml than a config file.

**Comment by duglin** [comment]
@bfirsh can we close this?
We now have a `~/.docker/config.json` file which can (and is) used to persist some cli options - like ps's filter.  Whether we use it for any particular option can probably be discussed in individual PRs.

**Comment by vdemeester** [comment]
I do agree with @duglin, I think we should close this one :wink:

**Comment by thaJeztah** [comment]
Ok I agree and I'll be the one that did it /o\
