### ISSUE TITLE
Update readme in Docker Hub when Git's README.md gets updated

### ISSUE THREAD

**Issue by Yajo** [docker/docker#7235]
Quoting from https://github.com/kylemanna/docker-openvpn/issues/7#issuecomment-50026499

>  The Docker hub docs say that the README.md should be automatically updated from the repo. I just triggered another build, and it's not updated.

**Comment by jfrazelle** [comment]
hub issues need to be filed with support@docker.com, so sorry it took so long to respond to this issue
