### ISSUE TITLE
Proposal: Image runtime dependencies

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#7247]
Image Runtime Dependencies
--------------------------------------

App deployments usually consist of multiple containers, a database, a caching server, app server, etc.
These are all runtime dependencies but the application defines these dependencies in a way that is only really visible to the developer (in their code)

### Proposal ###

Include a new `DEPENDS` command in the Dockerfile that would be used as such:
```Dockerfile
FROM debian
# install my app

DEPENDS DB:3306 REDIS:6379 SOME_SERVICE
```
With this syntax, the image is declaring the containers it needs to have linked in in order to work.
We are declaring that we need something alaised as "DB" (from the link) which exposes port 3306. (docker run --link mysql:db)... likewise for redis (docker run --link redis:redis).
For "SOME_SERVICE" we are just saying we need this linked in, but we don't need care explicitly about what ports it exposes.

In all of these cases, if a link is not set, or the linked in item does not provide the requested port we would fail the "docker run"
This would also pave the way for a plugin or some other layer above Docker to do some sort of automatic dependency resolution

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by luebken** [comment]
@jfrazelle Do you have a pointer for us where we can discuss the decision of freezing the Dockerfile syntax?
