### ISSUE TITLE
Proposal: expose container name within the container

### ISSUE THREAD

**Issue by EronWright** [docker/docker#7255]
I attach to various containers throughout the day and occasionally become confused about which one I'm in.   I'd like to adjust my bash prompt to show the container name.     

An environment variable with the container name would be ideal, to cover scenarios beyond the one I described.   But any source would do for my purposes.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/8427

**Comment by jfrazelle** [comment]
but yes this would be cool :)

**Comment by jfrazelle** [comment]
also see #3506
