### ISSUE TITLE
ADD instruction disables changes to file permissions and ownership

### ISSUE THREAD

**Issue by plause** [docker/docker#7275]
ADD instruction forces file permissions of downloaded files to 0600 (rw-------) and owned by root.

Any modifications introduced by RUN are ignored, even by 'USER root'.
For example, 'RUN chmod go+r targetfile' or 'RUN chown non-root:non-root targetfile' will not work.

And, under the 'USER non-root', files downloaded by any followed 'ADD <url> <dest>' instructions will always be owned by 'root'.

So, it is impossible to grant read access of the downloaded files to a non-root user inside the container.

**Comment by jfrazelle** [comment]
can you please try with the latest version of docker and if you still see it give exact steps to reproduce

**Comment by plause** [comment]
Docker 1.5.0 has this issue fixed.
Please help me close this issue.

**Comment by plause** [comment]
Docker 1.5.0 has this issue fixed.
