### ISSUE TITLE
Docker in Docker causing reclaimable space disk space and massive disk usage

### ISSUE THREAD

**Issue by Furze** [docker/docker#7285]
We are having issues running docker within docker, where it is using massive amounts of disk space in next to no time. 

To give you an idea, within an hour of using DinD for integration testing we can be using in excess of 45 GB, most of which cannot be reclaimed by administering docker stop, docker rm, docker rmi. When this fails to reclaim the disk space we have tried more drastic measures where we are stopping the docker daemon, removing the /etc/lib/docker directory and then restarting docker - this still doesn't solve the problem. Doing a 'df -h' on the file system still shows the disk space being in use... We have also investigated whether any process / processes have hold of any file handles in this location. Unfortunately there doesn't seem to be any sign of anything holding this disk space. It is almost like the files still exists. The only known way at this point to reclaim the space is to restart the system. 

One thing to note about our environment is that we are using dind to setup a complete application based website with separate images for webserver, appserver, dbserver and msgbroker. We are using dind to set these up within itself using ssh which will remove and replace images where necessary. I believe it is when we are removing these images and replacing them that we are seeing this enormous growth of space usage.

Our files are as follows:
Dockerfile: https://gist.github.com/Furze/2f0ee749b900f6c57265
wrapdocker: https://gist.github.com/Furze/662e11f1404c918055a4
I have not uploaded the authorized_keys file, it just contains our public keys. 

We then run the docker image built with the above docker file with the command:

    'docker run --privileged -e MT_PUBLISH_PORT=$MT_PORT -e FE_PUBLISH_PORT=$FE_PORT --name dind --net="host" -td docker-dind-image`

Once the dind is running we then ssh into it and run

    'docker pull our.registry/docker-webserver:latest && 
    docker pull our.registry/docker-appserver:latest &&  
    docker pull our.registry/docker-dbserver:latest && 
    docker pull our.registry/docker-msgbroker:latest'

We then run these images with the relevant linking. 
the size of the images are as follows:
dbserver = 300MB
brserver = 300MB
appserver = 1GB
webserver = 300MB

    'docker run --name dbserver -td our.registry/docker-dbserver:latest && 
     docker run --name brserver -td our.registry/docker-msgbroker:latest && 
    docker run --name appserver --link brserver:brserver --link dbserver:dbserver -p 127.0.0.1:$MT_PUBLISH_PORT:8080 -td our.registry/docker-appserver:latest && 
    docker run --name webserver --link appserver:appserver -p 127.0.0.1:$FE_PUBLISH_PORT:80 -td our.registry/docker-webserver:latest'

When we update the appserver and webserver for integration testing we do the following:

    'docker stop appserver webserver &&
    docker rm appserver webserver && 
    docker rm- our.registry/docker-appserver:latest our.registry/webserver:latest &&
    docker pull our.regisistry/docker-dbserver:latest && 
    docker pull our.regisistry/docker-msgbroker:latest &&
    docker run --name appserver --link brserver:brserver --link dbserver:dbserver -p 127.0.0.1:$MT_PUBLISH_PORT:8080 -td our.registry/docker-appserver:latest && 
    docker run --name webserver --link appserver:appserver -p 127.0.0.1:$FE_PUBLISH_PORT:80 -td our.registry/docker-webserver:latest'

We then run all the integration tests against this instance. 
This all works fine except for the disk space usage, and recovery.

**Comment by jfrazelle** [comment]
is this still reproducible on the latest version of docker

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen

**Comment by meticulo3366** [comment]
this issue still occurs...

```
ERROR: failed to register layer: rename /mnt/sda1/var/lib/docker/image/aufs/layerdb/tmp/layer-371078504 /mnt/sda1/var/lib/docker/image/aufs/layerdb/sha256/f64ab2ffbd6c6b005abf5965af244e63dde39c59cad1ab7961418033b75756bc: directory not empty
```

```
Docker version 1.10.3, build 20f81dd
```

**Comment by jingpengwu** [comment]
I experienced this too...

`docker -v
Docker version 1.12.1, build 23cf638`
