### ISSUE TITLE
lxc.utsname is not working under lxc-conf options and automatic IP by docker is still generated with --net=none

### ISSUE THREAD

**Issue by Jooho** [docker/docker#7288]
Environment)
- host - fedora 19 (Linux mylap 3.11.8-200.fc19.x86_64 #1 SMP Wed Nov 13 16:29:59 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux)
- guest - REHL 6.5

========
- docker -v

```
Client version: 1.0.0
Client API version: 1.12
Go version (client): go1.2.2
Git commit (client): 63fe64c/1.0.0
Server version: 1.0.0
Server API version: 1.12
Go version (server): go1.2.2
Git commit (server): 63fe64c/1.0.0
```

=============
- docker -D info

```
Containers: 15
Images: 250
Storage Driver: devicemapper
 Pool Name: docker-253:1-534279-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 5851.8 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 15.2 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: lxc-0.9.0
Kernel Version: 3.11.8-200.fc19.x86_64
Debug mode (server): false
Debug mode (client): true
Fds: 23
Goroutines: 27
EventsListeners: 0
Init SHA1: 95d679fc1dde9c94c3af87a6ce8240533ea3274b
Init Path: /usr/libexec/docker/dockerinit
```

======
From docker 1.0, it is not possible to use -h and --net=none together so I can not set hostname with the option -h.
To give static IP to each container, I still use lxc-conf options but with above issue, I try to use lxc-utsname to set hostname. However, it doesn't work and automatic generated IP is also added to container

This is my configuration.
1) docker daemon  :   /usr/bin/docker -d --selinux-enabled -e lxc

2) docker run \
--name="testhost" \
-i -t  $IMAGE \
-P \
--net=none \
--lxc-conf="lxc.network.type=veth" \
--lxc-conf="lxc.utsname=testhost" \
--lxc-conf="lxc.network.ipv4=172.17.42.100/24" \
--lxc-conf="lxc.network.ipv4.gateway=172.17.42.1" \
--lxc-conf="lxc.network.link=docker0" \
--lxc-conf="lxc.network.name=eth0" \
--lxc-conf="lxc.network.flags=up" \

3)In the container
bash-4.1# ifconfig
eth0      Link encap:Ethernet  HWaddr E2:8B:5C:D9:3C:9C  
          inet addr:172.17.42.100  Bcast:172.17.42.255  Mask:255.255.255.0
          inet6 addr: fe80::e08b:5cff:fed9:3c9c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5 errors:0 dropped:0 overruns:0 frame:0
          TX packets:4 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:418 (418.0 b)  TX bytes:328 (328.0 b)
lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)

====================================================
bash-4.1#  vi /etc/hostname
4952aaee4344

====================================================
bash-4.1# vi /etc/hosts
172.17.0.7      4952aaee4344       <===== why it is added
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

====================================================
conclusion)
1) static IP is not added to /etc/hosts
2) automatic IP is added to /etc/hosts
3) hostname do not set what I want

I think it is a bug or enhancement.
http://manpages.ubuntu.com/manpages/karmic/man5/lxc.conf.5.html

**Comment by jfrazelle** [comment]
looks like this was resolved but please ping me if you are still seeing it with exact steps to reproduce

**Comment by Jooho** [comment]
@jfrazelle @ashahab-altiscale  Oh sorry for late response. 
It is working now and found the lxc.utsname is more priority if I use -h together.

Many Thanks! 
By the way, I am a big fan of @jfrazelle ~! ^^
