### ISSUE TITLE
Error attempting to cp directory containing symlink

### ISSUE THREAD

**Issue by sfitts** [docker/docker#7296]
When attempting to cp a directory that contains a symlink (to another file in the same directory), I get the following error:

```
2014/07/29 02:04:06 symlink libzmq.so.3.1.0 libzmq/lib/libzmq.so: read-only file system
2014/07/28 23:28:00 exit status 1
```

Seems like `cp` needs to either skip symlinks or offer something like the -L option.

**Comment by jfrazelle** [comment]
@sfitts do you still see this on the latest version of docker

**Comment by jfrazelle** [comment]
if so can you give steps to reproduce thanks

**Comment by sfitts** [comment]
@jfrazelle -- not sure.  I'm not in a position to update to the current version on Windows right now, but when I get some time I'll let you know.

**Comment by jfrazelle** [comment]
great thanks!

**Comment by thaJeztah** [comment]
@jfrazelle should this be labeled "windows", or is that reserved for the native windows *builds*?

**Comment by jfrazelle** [comment]
also this is a dup of https://github.com/docker/docker/issues/9932

**Comment by mikehaertl** [comment]
I've also seen this on a Linux machine. I've tried to copy the PHP `vendor/` directory from a Yii2 composer installation to the host machine without luck:

```
$ docker cp temp:/var/www/html/vendor .
FATA[0000] invalid symlink "vendor/bin/markdown" -> "../cebe/markdown/bin/markdown"
```

The `composer.json` that was used during image build was:

```
{
        "require": {
                "php": ">=5.4.0",
                "yiisoft/yii2": "2.0.3",
                "yiisoft/yii2-bootstrap": "2.0.3",
                "yiisoft/yii2-swiftmailer": "2.0.3",
                "vlucas/phpdotenv": "1.0.*",
                "codemix/yii2-streamlog": "0.0.1"
        },
        "require-dev": {
                "yiisoft/yii2-debug": "2.0.3",
                "yiisoft/yii2-gii": "2.0.3"
        },
        "config": {
                "process-timeout": 1800
        },
        "extra": {
                "asset-installer-paths": {
                        "npm-asset-library": "vendor/npm",
                        "bower-asset-library": "vendor/bower"
                }
        }
}
```

**Comment by thaJeztah** [comment]
@mikehaertl based on the error-message in your output, this looks like a different issue. My "best guess" here is that the relative path (`../`) is causing Docker to see the symlink to be outside the build-context (but I'm no expert here).

Could you search the issue tracker if a similar issue already exists and (if not) create a *separate* issue. When doing so, please include the minimal steps to reproduce (preferably without using composer, so just a symlink).

It's still possible this is not a bug, but "by design" (there has been a security issue with symlinks breaking out of the build-context), in which case, perhaps it should be explained in the documentation.

**Comment by cyphar** [comment]
@thaJeztah I'm pretty sure I fixed the outside the build context problems in `docker cp` quite a while ago, everything is meant to be scoped to root. I'll take a look.

**Comment by thaJeztah** [comment]
@cyphar it could well be resolved already, that's why I also asked for a repro scenario. I see a new issue is created here; https://github.com/docker/docker/issues/11394. Thanks for watching it!
