### ISSUE TITLE
sig-proxy not working under supervisord

### ISSUE THREAD

**Issue by rgarcia** [docker/docker#7307]
In #503 @shykes says:

> As of 0.6.5 the docker client can now remotely "proxy" most of the application's behavior when attached, including signal handling and standard streams. So supervisord can now realistically pretend that 'docker run' or 'docker start' are the actual application.

However, this is not the behavior I am seeing in a simple test. My `supervisor.conf`:

```
[inet_http_server]
port=0.0.0.0:9001
 
[supervisord]
logfile=out.log
loglevel=info
nodaemon=true
 
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
 
[supervisorctl]
 
[program:docker_container]
command=docker -H tcp://localhost:4243 run --sig-proxy -i ubuntu sleep 1000000
stdout_logfile=./container.log
stderr_logfile=./container.log
```

Running this supervisor config with `supervisord -c supervisor.conf`, I see a container launched. However, sending TERM to the `docker ... run` command via `supervisorctl stop docker_container` kills the `docker ... run` command, but the container remains running.

Relevant environment info:

```
rgarcia@raf-laptop:~$ docker -D info
Containers: 421
Images: 899
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 1741
Execution Driver: native-0.2
Kernel Version: 3.13.0-32-generic
Debug mode (server): false
Debug mode (client): true
Fds: 10
Goroutines: 10
EventsListeners: 0
Init Path: /usr/bin/docker
Sockets: [tcp://localhost:4243]
Username: rgarcia
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
rgarcia@raf-laptop:~$ docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070
```

**Comment by jfrazelle** [comment]
Closing, feel free to ping me if you think this has been closed in error
