### ISSUE TITLE
Getting container memory usage: /var/lib/docker... looks right, /sys/fs/cgroup underreports...

### ISSUE THREAD

**Issue by ericpromislow** [docker/docker#7316]
I have an app that is running at about 50 MB in a non-containerized machine. When I deploy it in a container I see two different memory.stat files:
/sys/fs/cgroup/memory/docker/CTR-ID/memory.stat (recommended, total_rss = rss = 2,920,448

The %MEM fields in docker top aux sum to 2.7 %, giving way too low a value

In /var/lib/docker/aufs/mnt/CTR-ID/rootfs/sys/fs/cgroup/memory I get more likely
values, either from the rss field in memory.stat, or the value of `cat memory.usage_in_bytes` of 1,811,554,304 (On a VM with 2GB allocated).
The %MEM field is around 2.5 %, giving a plausible 45 MB of used memory,
which is consistent with my non-docker deployed app.

The only problem is that /var/lib/docker is root:root 0700 perms.  So I need
to use a setuid helper to get at the memory.usage_in_bytes file. Is this
deliberate?  Are containers vulnerable to attack?  What if /var/lib/docker 
was 0711?

The central question of this note is why the discrepancy between the two memory.stat files?

**Comment by jfrazelle** [comment]
maybe @crosbymichael knows?

**Comment by crosbymichael** [comment]
@unclejack any ideas?

**Comment by unclejack** [comment]
@crosbymichael I'll check this out and comment. I'll assign this temporarily to myself.

**Comment by jfrazelle** [comment]
@unclejack did you find anything

**Comment by unclejack** [comment]
@jfrazelle No, this was unassigned from me and I've lost track of it.

**Comment by jfrazelle** [comment]
ya I saw it was unassigned super weird

**Comment by thaJeztah** [comment]
@ericpromislow are you still seeing this on the current release (1.11)?
