### ISSUE TITLE
docker push and pull should batch HTTP requests for speed

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#7335]
Currently, the `docker push` and `docker pull` commands are slow.  One reason for this is that even a trivial layer (e.g. a `ENV PATH /my/bin`) creates a small (< 1KB) layer.  Each layer is pulled serially.  Over a high latency and high bandwidth link, this causes the entire process to take orders of magnitude longer than it would if all tags / layers were batched together.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/8188
