### ISSUE TITLE
Unable to change root password on Hub

### ISSUE THREAD

**Issue by ahmet2mir** [docker/docker#7347]
I got this error `chpasswd: (line 1, user root) password not changed` with ubuntu trusty. Precise works well.
Build : https://registry.hub.docker.com/u/ahmet2mir/ubuntu/build_id/11387/code/boss2mdjjrw8hx2ssxfgtnf/
The bug occurs only on Hub, not on my computer (trusty too), may this is the same bug https://github.com/docker/docker/issues/5704 ?

**Comment by jfrazelle** [comment]
for issues with the hub specifically please email support@docker.com, sorry I was unable to reproduce locally
