### ISSUE TITLE
EOF when building an image using the API 

### ISSUE THREAD

**Issue by Diego81** [docker/docker#7353]
Hi,

I am trying to build an image using the API through the Unix Socket.
I am using Node and the request module for this: https://www.npmjs.org/package/request
Version of the API is 1.12.

My code looks like this:

```
var buildImage = function(path, callback) {
  fs.createReadStream(path)
    .pipe(request.post(dockerSocket + '/build', function(error, response, body){
      console.log(response.statusCode);
      console.log(body);
      callback();
    }));
};
```

`path` points to the tar containing the Dockerfile and all the files to add to the image.

The output I get is as follows:

```
500
EOF
```

This is what I see in the docker logs:

```
2014/07/31 18:57:09 POST /build
[ead65634] +job build()
EOF
[ead65634] -job build() = ERR (1)
```

Any idea/suggestion?

Thanks in advance!

**Comment by jfrazelle** [comment]
@alrunner4 can you let us know if this is still relevant on the latest version you can download the binaries from master.dockerproject.com

**Comment by jfrazelle** [comment]
seems fine to me when testing so closing but let me know if you believe otherwise
