### ISSUE TITLE
Docker push using remote api result 'is already in progress"

### ISSUE THREAD

**Issue by jhzzzz** [docker/docker#7369]
I have tag a image to local registry: 
docker tag 590fa59c6dc3 172.16.79.21:80/jhzhang-test

Then i using docker remote API to push the image (api version: v1.11), 

1. First time, it return after about several seconds, response is null.
2. Try push again, this time response is: 

HTTP/1.1 500 Internal Server Error Content-Type: text/plain; charset=utf-8 Date: Fri, 01 Aug 2014 08:47:53 GMT Content-Length: 57 push 172.16.79.21:80/jhzhang-test is already in progress

3. Try again after a while, result is:

HTTP/1.1 200 OK Content-Type: application/json Date: Fri, 01 Aug 2014 08:54:06 GMT Transfer-Encoding: chunked {"status":"The push refers to a repository [172.16.79.21:80/jhzhang-test] (len: 1)"} {"status":"Sending image list"} {"status":"Pushing repository 172.16.79.21:80/jhzhang-test (1 tags)"} {"status":"Image 511136ea3c5a already pushed, skipping"} {"status":"Image b74728ce6435 already pushed, skipping"} {"status":"Image 3aa646e4f1d2 already pushed, skipping"} {"status":"Image 3460b1ba3f7d already pushed, skipping"} {"status":"Image 3933d6efb2a6 already pushed, skipping"} {"status":"Image e3288b42529a already pushed, skipping"} {"status":"Image c499ff5e8c87 already pushed, skipping"} {"status":"Image c529b1552e5a already pushed, skipping"} {"status":"Image d61b194a01f5 already pushed, skipping"} {"status":"Image 641283160ec4 already pushed, skipping"} {"status":"Image 42f3351dd9a3 already pushed, skipping"} {"status":"Image 95fea9b65ee9 already pushed, skipping"} {"status":"Image 976600925f6e already pushed, skipping"} {"status":"Image 9080f765ea3d already pushed, skipping"} {"status":"Image caf00af1e6bd already pushed, skipping"} {"status":"Image 590fa59c6dc3 already pushed, skipping"} {"status":"Pushing tag for rev [590fa59c6dc3] on {http://172.16.79.21:80/v1/repositories/jhzhang-test/tags/latest}"}

**Comment by jfrazelle** [comment]
closing as failure to give more info but please ping me if you come back with the requested information
