### ISSUE TITLE
[userland proxy]: docker memcached does not always reply to a stats command

### ISSUE THREAD

**Issue by gonvaled** [docker/docker#7371]
Please see here:

http://stackoverflow.com/q/25079897/647991

**Comment by unclejack** [comment]
ping @crosbymichael @icecrime @jfrazelle @erikh @LK4D4 Do we still need to keep this open?

**Comment by LK4D4** [comment]
@unclejack Yes, userland proxy still here and it is still pretty bad.

**Comment by unclejack** [comment]
The user land proxy is going to be removed. Since removing the user land proxy will fix this problem, I'm going to close this in favor of #11185 because the solution to #11185 is the complete removal of the user land proxy.
