### ISSUE TITLE
docker login against private registry assumes Account activation

### ISSUE THREAD

**Issue by matthughes** [docker/docker#7376]
I'm running docker-registry behind nginx with http auth.

When I do a successful docker login, my users are greeted with:

status = "Account created. Please see the documentation of the registry " + serverAddress + " for instructions how to activate it."

There is no activation step with my registry.  I'm not even sure what that means, but the docker client assumes I want it.  I'd love to be able to override / remove this message so as not to confuse my users.

**Comment by jfrazelle** [comment]
@shin- just making sure this is still an issue, if so I have triaged accordingly

**Comment by shin-** [comment]
Yeah, it's still an issue. Labels look accurate.

**Comment by karanSinghChauhan** [comment]
Greetings

I have also seeing similar issue in my private registry. 

"Account created. Please see the documentation of the registry " + serverAddress + " for instructions how to activate it."

Is any workaround ? Thanks

**Comment by mike1729** [comment]
#dibs

**Comment by cpuguy83** [comment]
I think this is done, isn't it?

**Comment by thaJeztah** [comment]
Account creation is no longer possible through docker login, and I can't find a reference to this text in the code anymore, so I'll close
