### ISSUE TITLE
Proposal: docker push --description w/ registry support

### ISSUE THREAD

**Issue by erikh** [docker/docker#7381]
This feature would allow pushing with a description. It would supplant #6667 and #6900.

It would need support in the registry -- the point here is that `COMMENT` or `DESCRIPTION` is not a singleton in the dockerfile or across multiple images, resulting in a convoluted API response and potentially undefined behavior in interpreting the API.

The feature is modeled after 'git commit -m foo' but would happen at push time and describe the whole *repository* as opposed to each image.

--description could take a file (e.g., README.md) or simply a string as input, I haven't thought of which one would be better at this point, so please weigh in.

/cc @shykes @rhatdan @tianon @ewindisch @SvenDowideit

**Comment by jfrazelle** [comment]
I think we can close this as a dup of https://github.com/docker/docker/issues/769 no?

**Comment by jfrazelle** [comment]
@erikh just let me know otherwise, trying to consolidate some things
