### ISSUE TITLE
Lost external net access from containers (VPN and --privileged involved)

### ISSUE THREAD

**Issue by carver** [docker/docker#7417]
My docker containers don't get external net access anymore, neither are the ports externally addressable.  I was trying to set up a container that runs over a VPN, while the main host traffic doesn't.  The container seemed to be working (and sending traffic through the VPN) for a while and then stopped (perhaps after the host went into standby, or running a `docker kill`).  I've intentionally avoided rebooting the host to make sure I can continue to reproduce.

Any help is appreciated, including something like: "here's another way to route your container traffic through a vpn, besides trying to connect from inside the container".

Net access still works on the host (`ping` or `curl` google.com succeeds) but has stopped working in the container (hangs indefinitely).

I had been running containers before with:
`docker run --net="bridge" --privileged -p 8112:8112 my-container /start-service.sh`

where start-service.sh had something like:
```
/etc/init.d/openvpn start
service
```

Now IP access into and out of the container seems cut off (can't curl/ping from inside the container to the outside and port access from outside-in hangs, too).  This is true even with a more simple `docker run` without --net or --privileged set.

Here is some [docker diagnostic info](https://github.com/docker/docker/issues/2174#issuecomment-45179767)
```
host:~# docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070

host:~# telnet localhost 8112
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

host:~# netstat -ntlp | grep 8112
tcp6       0      0 :::8112                 :::*                    LISTEN      1955/docker


host:~# DOCK_IP=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' $(docker ps | awk '/:8112/{print $1}'))

host:~# telnet $DOCK_IP 8112
Trying 172.17.0.12...
telnet: Unable to connect to remote host: Connection timed out

host:~# iptables -t nat -nxvL

Chain PREROUTING (policy ACCEPT 36 packets, 11916 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
   39850 16435700 DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 33 packets, 11820 bytes)
    pkts      bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 131 packets, 12866 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
   20853  6555008 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 126 packets, 11996 bytes)
    pkts      bytes target     prot opt in     out     source               destination         
    8382  1200605 MASQUERADE  all  --  *      *       172.17.0.0/16       !172.17.0.0/16       

Chain DOCKER (2 references)
    pkts      bytes target     prot opt in     out     source               destination         
       0        0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:58846 to:172.17.0.12:58846
       0        0 DNAT       tcp  --  !docker0 *       0.0.0.0/0            0.0.0.0/0            tcp dpt:8112 to:172.17.0.12:8112

```

**Comment by jfrazelle** [comment]
@carver did you try @discordianfish suggestion?

**Comment by jfrazelle** [comment]
closing as dup of #7779
