### ISSUE TITLE
Error response from daemon: wait: no such container: [containerid]

### ISSUE THREAD

**Issue by dpup** [docker/docker#7419]
Environment details:
- CoreOS
- AWS
- Fleet/Systemd based services
- The container has apache, running a simple PHP/MySQL website 

It looks like this happens under high CPU load.  The service ends off in a failed state.  If I use `fleetctl journal` I see this:

```
Aug 05 16:03:38 [ip] systemd[1]: apache.service: main process exited, code=exited, status=1/FAILURE
Aug 05 16:03:38 [ip] docker[1874]: 2014/08/05 16:03:38 Error response from daemon: wait: no such container: [container-id]
```

Guidance on debugging and preventing this issue would be helpful.

**Comment by jfrazelle** [comment]
we need more output, `docker version` and `docker info` would be a start plus logs from the daemon

**Comment by dpup** [comment]
I can close, I can't remember which version was running back then.  It was whatever the stable CoreOS build was.
