### ISSUE TITLE
Issue about "docker dead but subsys locked" start docker 

### ISSUE THREAD

**Issue by justlooks** [docker/docker#7439]
when i test tomcat deploy in docker , i find i can not start container ,so i restart my OS use command "init 6"  ,but i find i can not start docker anymore,BTW , i use docker in kvm guest ,OS is Centos6.5

# service docker force-reload
Stopping docker:                                           [FAILED]
Starting docker:                                           [  OK  ]
# service docker status
docker dead but subsys locked

but i can use docker -d to start the docker!

# docker version
Client version: 1.0.0
Client API version: 1.12
Go version (client): go1.2.2
Git commit (client): 63fe64c/1.0.0
Server version: 1.0.0
Server API version: 1.12
Go version (server): go1.2.2
Git commit (server): 63fe64c/1.0.0

---------------------------------------------------
my build Dockerfile

# example for change yum
FROM docker:5000/centos:base
MAINTAINER Alex Kim <alex_kim@mediaadx.com>
RUN rm /etc/yum.repos.d/*
RUN wget -O- ftp://192.168.10.207/yum.repod/epel.repo > /etc/yum.repos.d/epel.repo

# install jdk
RUN yum install -y java-1.7.0-openjdk

# configure for tomcat
RUN yum install -y tomcat
EXPOSE 8080
CMD service tomcat start && tail -f /var/log/tomcat/catalina.out

my start command

# docker rm tomcat
tomcat
[root@docker tomcat]# docker run -d -P --name tomcat docker:5000/centos65:tomcat
45d7fb0906e187a8808aecfc84a48a0352ab8f3b33a42e9f642acd8c50e74319
2014/08/06 14:34:50 Error: Cannot start container 45d7fb0906e187a8808aecfc84a48a0352ab8f3b33a42e9f642acd8c50e74319:  (exit status 1)

# docker logs -f $(docker run -d -p 8080:8080 --name tomcat docker:5000/centos65:tomcat)
2014/08/06 14:38:29 Error: Cannot start container 41a80f8916c0a65a8daef3083b9ad5dff27eff0d9873ec324182560be10b3d38: port has already been allocated

**Comment by jfrazelle** [comment]
closing, but @justlooks if you are able to reproduce on the latest version, please give the full steps and ping me thanks

**Comment by Almaral-Engineering** [comment]
Could anyone solve this? I am facing the same issue
