### ISSUE TITLE
Proposal: Add "PRIVATE" to the Dockerfile to prevent resulting images from being pushed public inadvertantly

### ISSUE THREAD

**Issue by capoferro** [docker/docker#7444]
RE: #7420, suggestion by @cpuguy83 

There are some images that we know we never want to push publicly. Adding `PRIVATE` to the Dockerfile would be some defense against allowing an image built from that Dockerfile from being pushed to the public Docker registry. 

As it stands, a sleepy or inexperienced developer could mistag an image and accidentally release their image to the wild (in fact, this has already happened at least once where I work). Adding `PRIVATE` would cause said developers to have to modify the Dockerfile before pushing public, making it a more intentional act.

**Comment by jfrazelle** [comment]
duplicate https://github.com/docker/docker/issues/7940

**Comment by thaJeztah** [comment]
There's also a new PR that allows blocking registries; https://github.com/docker/docker/issues/10411
