### ISSUE TITLE
Add docs about setting group/GID with USER command

### ISSUE THREAD

**Issue by jemc** [docker/docker#7447]
The `USER user` command in Dockerfiles does the equivalent of `su user -c command` for all future `RUN command` commands.

I propose adding the `GROUP group` command, which would do the equivalent of `sg group -c command` for all future `RUN command` commands.

`newgrp` is a command that works a lot like `su` without a `-c` command, and sets the gid for future commands in the shell, but due to the way docker works, this is cleared between each command in the Dockerfile, so something like the following does _NOT_ work:

```
USER user
newgrp group
```

Instead, my hope would be to be able to do something like:

```
USER user
GROUP group
```

**Comment by jfrazelle** [comment]
ping @SvenDowideit

**Comment by pdxdan** [comment]
#dibs

**Comment by nhsiehgit** [comment]
Hi @pdxdan 
Please add a `closes` or `fixes` on the closing PR to make tracking the fixes easier. Thanks!

(closed by https://github.com/docker/docker/pull/11697 ?)

**Comment by vdemeester** [comment]
Agreed with @nhsiehgit, I think this issue should be closed, the pull request has been merged (but there was no ``closos`` or ``fixes``).

**Comment by thaJeztah** [comment]
@nhsiehgit @vdemeester thanks! I think this can be closed, yes, because https://github.com/docker/docker/pull/11697 was merged.
