### ISSUE TITLE
Support joining any network namespace

### ISSUE THREAD

**Issue by mrunalp** [docker/docker#7455]
If docker supports joining any network namespace, then network topology could be left to higher level orchestration. This allows for flexibility in docker deployments. The user could setup the network by creating a new network namespace via ip netns, customize as required and then just pass it to docker with something like --net=netns:/var/run/netns/mycustomnet1. 

The advantage is that docker does not have to worry about supporting all the different types of bridges/switches/custom protocols that users might want to use.

**Comment by cpuguy83** [comment]
Closing as this is no longer relevant (and ultimately rejected in the aforementioned PR).
Docker provides a backend api for configuring network namespaces that can be hooked into via plugins in github.com/docker/libnetwork as of docker 1.9.
