### ISSUE TITLE
Detect non-tty and output download percentage without using escape codes

### ISSUE THREAD

**Issue by lzlarryli** [docker/docker#7456]
Docker output image download progress using ASCII escape codes, even to non-ttys. For example, Vagrant cannot display docker download progress due to this (https://github.com/mitchellh/vagrant/issues/4243). It would be nice if docker sends percentage only to non-ttys, making it easier to integrate with other tools.

**Comment by sorpaas** [comment]
Same problem here in a git hook.

**Comment by jfrazelle** [comment]
looks like this was resolved cannot reproduce on latest version
