### ISSUE TITLE
Docker on Ubuntu Breaks KVM

### ISSUE THREAD

**Issue by actionmystique** [docker/docker#7462]
Installing Docker on Ubuntu 14.04:
- creates a new bridge "docker0"
- deletes virbr0

Now, I am unable to create the last bridge again.
What must be done to solve or workaround that issue?

**Comment by unclejack** [comment]
@actionmystique I've got Ubuntu 14.04 and I'm not sure what happened when you've run into this problem. I've got virbr0, docker0 and lxcbr0 on a system and it's all working properly.

Is this still a problem? Can you please provide the exact steps? I'm going to close this issue until it's confirmed that this is actually a problem.

**Comment by actionmystique** [comment]
I've removed Docker in the meantime. It seems that Docker has improved its installation procedure over the past 6 months.
