### ISSUE TITLE
Multiple builds in one GitHub Repo and automatic builds on push

### ISSUE THREAD

**Issue by rhuss** [docker/docker#7480]
When I use a GitHub [repo](https://github.com/ConSol/docker-appserver) which holds multiple automated build config and have marked the builds on hub.docker.io as "active", then as soon as I change a single repo's file **all** configured builds will be started.

Therefore I switched off "active" builds but now have to start them by hand which is tedious if the number of repos is large.

Wouldn't it be possible to react on a GitHub push only when a file below the configured path has been affected by a commit ?

**Comment by jfrazelle** [comment]
I opened this internally as an issue on the hub, you are not alone in this problem :)

**Comment by jfrazelle** [comment]
actually ok so all hub issues need to be filed with support@docker.com or forums.docker.com because technically this is not an issue with docker iteslf. But dont get me wrong i really really really want this. I have 40+ images in a repo and they all push at once, but also make your voice heard to the places suggested so they know its more that just me :)

**Comment by jfrazelle** [comment]
also the issue i opened interally is still opened :/

**Comment by mikehaertl** [comment]
@jfrazelle Is there any news on this? Or any workaround we can try?

I've not used automated builds very much, but if I remember correctly, the automated build could also be triggered manually through an API. And I think, it's possible to specify exactly which tag I want to build there. So if we could turn off, that an image is automatically built on each push, this could be a workaround. Still it woulde be quite cumbersome.

**Comment by rhuss** [comment]
@mikehaertl @jfrazelle  BTW, I moved on to this discussion https://forums.docker.com/t/automated-build-only-on-monitored-github-folder-change/257 which seems reasonable close to this issue.
