### ISSUE TITLE
Sidebar in docs doesn't work as anticipated (or as it worked once upon a time)

### ISSUE THREAD

**Issue by nathanleclaire** [docker/docker#7487]
Before some of the sweeping 1.0 changes, the sidebar on docs.docker.com used to act differently than it does in two ways:

1.  It "followed" you down the page as you scrolled down (`position: absolute`?) with the section that you were currently in highlighted.  This is nice for quickly getting your bearings if you're just returning to a tab, etc.
2.  The sidebar links, when clicked on, don't snap to exactly the position on the page that the hash URL refers to.  Instead it seems there is a bit of "margin" (not the CSS property) on the top of the viewport.

See:

![screen shot 2014-08-08 at 9 35 03 am](https://cloud.githubusercontent.com/assets/1476820/3859560/0700666e-1f1a-11e4-96ef-1aa5fbbab012.png)

cc @SvenDowideit @fredlf @ChristopherBiscardi

**Comment by jfrazelle** [comment]
@nathanleclaire can we close?

**Comment by nathanleclaire** [comment]
We still don't have the "sticky" sidebar which lights up the correct section as you scroll down like it used to, which makes me sad, but I have a feeling even if the issue stays open that will not get implemented.  So I will close :)

**Comment by ChristopherBiscardi** [comment]
@nathanleclaire yea, it makes me sad too :/ Some of our docs have [extraordinarily long sidebar menus](http://docs.docker.com/reference/commandline/cli/) as well. There's a loose plan to redo the docs IA and design, but it won't be until we have some design docs done that are currently in-progress.

**Comment by fredlf** [comment]
@ChristopherBiscardi I have a schema for a new docs IA. It's a little out of date, but generally good to go. It has been vetted by several stakeholders. I have zero band-width to implement it, but it is on my backlog. If you have been working on this on the side, we need to sync up to avoid duplicating effort.

**Comment by thaJeztah** [comment]
@ChristopherBiscardi @fredlf if there's something I can assist with there, let me know.

**Comment by fredlf** [comment]
Thanks, @thaJeztah . Once this work gets underway I'm sure we'll need help.

**Comment by thaJeztah** [comment]
@fredlf just give me a shout :)
