### ISSUE TITLE
Proposal: 'vethprefix' argument for run

### ISSUE THREAD

**Issue by maran** [docker/docker#7510]
In order to properly do bandwidth accounting with my existing iptables solution I need to be able to track bandwidth on a per container basis. By enabling a specific vethprefix I can use a physdev match using a wildcard to have a fault tolerant way of tracking the bandwidth.

I'm sure other use-cases exist since I think I remember LXC having the same option.

I already got a working solution, I just want to know if there is any interest in merging this back into master.

**Comment by dnephin** [comment]
It looks like `/var/lib/docker/execdriver/native/<container id>/state.json` doesn't exist any more for docker 1.6. Is there another way I can lookup the veth pair names? I couldn't find anything in directories under `/var/lib/docker` with the container name

**Comment by LK4D4** [comment]
@dnephin it is in `/var/run/docker/execdriver/native/` now.

**Comment by dnephin** [comment]
@LK4D4 Thanks for the quick response!

I looked in that directory, but the latest file I see is from April 3rd (and I've run many containers since then, and have one running now). I'd guess that's about when I upgraded to Docker 1.5 maybe?

**Comment by maran** [comment]
I am trying to figure out the veth prefix for 1.9.1 but it seems it is (re)moved. Can somebody point me to the new location if any?

**Comment by cpuguy83** [comment]
Is this really needed? You can get network stats from the API.

**Comment by thaJeztah** [comment]
Following the discussion https://github.com/docker/docker/issues/20224, and https://github.com/docker/docker/issues/17064#issuecomment-183160829, I think we should close?

**Comment by aboch** [comment]
@thaJeztah Agree, based on the discussion in that thread, it looks like a viable solution is provided which no longer requires the feature proposed in this issue. I think this should be closed now.

**Comment by LK4D4** [comment]
I'm closing this based on discussion.
