### ISSUE TITLE
Provide direct download link for .deb files

### ISSUE THREAD

**Issue by virtuald** [docker/docker#7565]
We're running docker in an offline environment, and it would be nice if the ubuntu/debian page provided a direct link to the .deb files. Currently, it's a bit of a pain to figure out the right link and obtain the deb file that way.

**Comment by ericso** [comment]
I would like this as well. For various reasons, I cannot connect to the get.docker.com apt source and need to manually install the .deb file.

**Comment by thaJeztah** [comment]
Relates to https://github.com/docker/docker/issues/7974?

**Comment by cpuguy83** [comment]
This is done via github releases.
Can also discover versions via https://releases.dockerproject.org/
