### ISSUE TITLE
way to inform volume to create file not directory

### ISSUE THREAD

**Issue by tomfotherby** [docker/docker#7607]
From docker v 0.10.0 [changelog](https://github.com/dotcloud/docker/blob/master/CHANGELOG.md#0100-2014-04-08):

> Allow --volumes-from to be individual files.

I have a script I use to modify the `.bash_aliases` *file*, I run it a bit like this:

    docker run  -v ~/.bash_aliases:/toprocess  mydomain/mycontainername setup

The problem is that on some hosts the `~/.bash_aliases` file does not exist when I run the command. In this case Docker creates a **folder** called `.bash_aliases`, which breaks my script because it expects a *file*.

When bind-mounting non-existence host files/folders, I think docker should look for a trailing `/` and if found create a empty *folder*, if not found create a empty *file*.

Alternatively, maybe docker should throw a error instead of creating anything on the host.

----

(obviously the workaround for this problem is easy, bind mount the whole home folder rather than a individual bash_aliases file)

----

My host info (asked for in [guidelines for contributing](https://github.com/dotcloud/docker/blob/master/CONTRIBUTING.md)):

* host OS: Ubuntu 14.04.
* `uname -a`: `Linux Pochama 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux`
* docker version: 
```
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070
```
* docker info:
```
Containers: 198
Images: 2044
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 2440
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Username: tomfotherby
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**Comment by jfrazelle** [comment]
this is the case with all volumes iirc, ping @cpuguy83

**Comment by cpuguy83** [comment]
This could be resolved by checking if the file exists before trying to bind-mount it (ie, outside Docker), or doing something like `touch ~/.bash_aliases` first.

**Comment by cpuguy83** [comment]
Closing because this is something I do not think we will support.
Your script can check if the file exists ahead of time and create as needed.
Trying to guess if someone wants a file or dir is a bit too much magic and prone to error.

Thanks for submitting!
