### ISSUE TITLE
OAuth Doc Persists Despite Merged PR

### ISSUE THREAD

**Issue by hollietealok** [docker/docker#7630]
http://docs.docker.com/v1.1/reference/api/docker_io_oauth_api/

This is no longer a valid doc and it needs to be removed, per this PR: https://github.com/docker/docker/pull/7193

**Comment by jfrazelle** [comment]
@SvenDowideit status on this

**Comment by thaJeztah** [comment]
@jfrazelle looks like this is fixed, if I visit that page, I get a redirect page;

    This documentation has been removed. Redirecting you to the relevant
    pull request on GitHub.
    https://github.com/docker/docker/pull/7193

**Comment by thaJeztah** [comment]
Oh, shucks. Looks like I got confused; this link redirects:
http://docs.docker.com/reference/api/docker_io_oauth_api/ 

but this one doesn't:
http://docs.docker.com/v1.1/reference/api/docker_io_oauth_api/

**Comment by jfrazelle** [comment]
@svendowedit can you take care of this is it a matter of deleting the pages?

**Comment by SvenDowideit** [comment]
Done.

notes for later:

```
export BUCKET BUCKET=beta-docs.docker.io
export AWS_CONFIG_FILE=$(pwd)/awsconfig
aws s3 --profile $BUCKET ls s3://$BUCKET
aws s3 --profile $BUCKET rm s3://$BUCKET/v1.0/reference/api/docker_io_oauth_api/index.html
aws s3 --profile $BUCKET rm s3://$BUCKET/v1.1/reference/api/docker_io_oauth_api/index.html
```

**Comment by thaJeztah** [comment]
Ah great! Do you think it would it be possible to create something similar to the https://github.com/docker/docker/blob/master/docs/s3_website.json file to mark files as "to be invalidated/removed" upon merge? (Possibly too much work for something that only happens occasionally)

**Comment by SvenDowideit** [comment]
yeah - next time it happens maybe :)

**Comment by thaJeztah** [comment]
Yeah, it isn't needed often, the instructions just looked complicated :smile:
