### ISSUE TITLE
Using an Integer HostPort in PortBindings when starting a container through the API fails

### ISSUE THREAD

**Issue by jfrumar** [docker/docker#7651]
I am using the [Dockerode](https://github.com/apocas/dockerode) npm module to interface with the Docker API on a local machine.

If I specify an integer PortBindings value when calling the API to start an existing container (i.e. POST /containers/(id)/start), it fails to take effect. For instance, if my passed config is:
```javascript
{ "Binds":["/var/lib/mongo/data:/data/db"],"PortBindings":{"27017/tcp":[{"HostPort":27017}]} }
```
then it fails, but if it is:
```javascript
{ "Binds":["/var/lib/mongo/data:/data/db"],"PortBindings":{"27017/tcp":[{"HostPort":"27017"}]} }
```
then it works (notice the 27017 is a string in the second version). This was confusing because I expected that the port number, being a native integer, would be valid and correct. 

I had to cast my Integer to a String in order to have it take effect (but not before spending a large amount of time narrowing down the issue).

**Comment by jfrazelle** [comment]
theres a few issues on updating api docs so closing
