### ISSUE TITLE
Docker Remote API: Documentation is missing and misleading

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#7669]
Many fields in the response objects that I actually get in my local calls do not exist in Remote API v1.13 documentation.

And documentation is so bad that there are no types specified.

e.g. it just says:

     "PortSpecs":null,

what is the type of this field? It is just a null in JSON response.

That doesn't make sense. Docs are very vague and it's almost impossible to write a correctly working client without reading other clients and keep testing every single corner case (e.g. you gotta reproduce a case where portspecs is not null by creating a container etc).

This is crazy and will not help things move forward very well.

**Comment by jfrazelle** [comment]
also see https://github.com/docker/docker/issues/2583

**Comment by ahmetalpbalkan** [comment]
Closing this for the sake of #15188.
