### ISSUE TITLE
Docker Remote API: URL inconsistencies

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#7671]
Here are some calls and their endpoints:

* List images: `/images/json`
* Get image: `/images/{{image}}/json`
* Get image history `/images/{{image}}/history`

First of all having `json` in the URL does not make sense. Either get that json/xml information from `Accept-Type` header or a query string like `?output=json` (or even worse, use `.json` extension at the end of the URI).

By having URLs like I listed above you just made `history` a same-level or same-type of  thing as `json`, which is not correct. (and "get image history" does not end with `.../json` either.)

If this would be my API I would go for:

* List images: `/images`
* Get image: `/images/{{image}}`
* Get image history `/images/{{image}}/history`

I just looked at these 3 calls in the entire API and found that problem, I will be updating this issue as I go.

Fixing this would be a breaking API change, just leaving this here for future reference.

**Comment by jfrazelle** [comment]
can we combine all these into one issue @ahmetalpbalkan

**Comment by ahmetalpbalkan** [comment]
Closing this for the sake of #15188.
