### ISSUE TITLE
--cap-add/--cap-drop does not work with lxc execution driver and "privileged" capabilities

### ISSUE THREAD

**Issue by danbeaulieu** [docker/docker#7687]
# docker run -it --cap-add=SYS_ADMIN ubuntu /bin/bash
2014/08/22 18:33:03 drop capabilities operation not permitted
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --log-priority options.

 # docker run -it --cap-drop=all --cap-add=NET_ADMIN matlab_online/worker:latest /bin/bash 
2014/08/22 18:42:39 drop capabilities operation not permitted
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --log-priority options.

 # docker run -it --cap-drop=all --cap-add=CHOWN matlab_online/worker:latest /bin/bash 
root@f84dc6c26591:/#

It appears I am unable to --cap-add any capabilities that were not already in the unprivileged whitelist.

It also appears I am unable to drop capabilities via lxc-conf, which may be related:

 # docker run -it --privileged=true --lxc-conf="lxc.cap.drop=sys_admin" ubuntu /bin/bash 
2014/08/22 18:34:30 operation not permitted
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --log-priority options.

 # uname -a
Linux ubuntu-14 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

 # docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f

 # docker -D info
Containers: 9
Images: 46
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 64
Execution Driver: lxc-1.0.5
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04.1 LTS
Debug mode (server): false
Debug mode (client): true
Fds: 10
Goroutines: 10
EventsListeners: 0
Init Path: /usr/bin/docker

**Comment by crosbymichael** [comment]
@ashahab-altiscale Yes, thanks for updating us.  

@danbeaulieu this has been fixed thanks to @ashahab-altiscale
