### ISSUE TITLE
Proposal: ENVFILE instruction : Allow to create multiple environment variables from a file

### ISSUE THREAD

**Issue by coolsvap** [docker/docker#7688]
Use case: Allow ENV to import a file containing variables to be exported

Issue: I am currently trying to create a container image for my application which on its installation generates a text file with all the exports that are needed by it. This file can be sourced and used ahead to perform operations using the application. 
Currently I am not able to source the file with RUN source filename, instead I have to do a ENV operation.

Please find the reference Dockerfile at [1] and its build output at [2]

I think the ENV instruction can be extended to have file as parameter.

[1] https://github.com/coolsvap/docker-source-issue/blob/master/Dockerfile
[2] https://registry.hub.docker.com/u/coolsvap/docker-source-issue/build_id/13901/code/blbeyqt8cekrqrngp8hbaqa/

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
