### ISSUE TITLE
Short (80 chars) and long (Markdown-formatted) descriptions for images

### ISSUE THREAD

**Issue by dhrp** [docker/docker#769]
This is a ticket to discuss a new format for the container image description(s). The topic was brought up before in #556 and dotcloud/docker-index#45.

The proposal:
* One 80 character field (short description), plain, no tabs, no newlines.
* One big field (long description), allowing either Markdown or ReST (In which I would favor Md)

Doing so would allow the docker client to show easily readable search results (descriptions). The docker index can easily show rich descriptions, and the Docker client could show it, for example when an exact match is given: e.g. ``docker search dhrp/sshd`` will give the full text.

In dotcloud/docker-index#45 @johncosta pointed out a good usecase which requires a longer, more structured description. And amongst other things #556 shows we need to fix the description shown in the client. 

**Questions**

1. What do we do with the docker file? Does it also contain these two description fields? None? Just the short description?
2. How do we handle tags? Does every tag has its own description or do we allow different descriptions for different tags.
3. How do we get people to add descriptions? (#596).
4. Do we use Markdown or ReST for the long description?

/cc @johncosta @kencochrane @vieux

**Comment by thaJeztah** [comment]
Just a thought; can we use labels for this? I.e.;

`com.docker.distribution.description="My fantastic image!"`

**Comment by thaJeztah** [comment]
Talked briefly with @stevvooe on this, and the registry V2 manifest specification has a provision for this.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
