### ISSUE TITLE
lxc driver restart does not set network settings in json

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#7693]
When using `docker restart` with the LXC driver, network settings are not re-populated in the inspect output
This only happens with LXC.

<pre>
docker info
Containers: 15
Images: 204
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 234
Execution Driver: lxc-1.0.5
Kernel Version: 3.13.0-32-generic
Operating System: Ubuntu 14.04.1 LTS
WARNING: No swap limit support
</pre>

**Comment by jfrazelle** [comment]
@cpuguy83 can we close

**Comment by cpuguy83** [comment]
Yep, we're good.
