### ISSUE TITLE
Matching container tags with GitHub / BitBucket tags when pushing for automated builds

### ISSUE THREAD

**Issue by thomasfr** [docker/docker#7697]
On hub.docker.com when adding an automated build it would be an big timesaver if there would be an option to automatically add the same tag to the container as the current pushed tag on GitHub / BitBucket. Maybe this can be achieved with a simple placeholder for the tagname?
![Image of Yaktocat](https://dl.dropboxusercontent.com/s/5rpu8evl5700h03/2014-08-23%20at%2019.05.png?dl=0)
cheers

**Comment by jfrazelle** [comment]
please file feature requests for hub to support@docker.com or forums.docker.com

**Comment by thomasfr** [comment]
Done
