### ISSUE TITLE
docker set cpuset error when use lxc driver

### ISSUE THREAD

**Issue by freax007** [docker/docker#7715]
I run docker use lxc driver(my docker version: 1.0, lxc: 0.90, OS: centos 6.5). but run a container failure when I set cpuset, the error message as follow.
docker run --net=none --privileged=true --cpuset="0,1" -m 512m -it centos-mini /bin/bash
lxc-start: Permission denied - write /cgroup/cpuset/lxc/c9d82fec23b4a43e4cd1c200a7ba1453afe34378c4d489f3e932afd88968e87b/cpuset.cpus : Permission denied
lxc-start: Error setting cpuset.cpus to 0,1 for lxc/c9d82fec23b4a43e4cd1c200a7ba1453afe34378c4d489f3e932afd88968e87b

lxc-start: failed to setup the cgroups for 'c9d82fec23b4a43e4cd1c200a7ba1453afe34378c4d489f3e932afd88968e87b'
lxc-start: failed to spawn 'c9d82fec23b4a43e4cd1c200a7ba1453afe34378c4d489f3e932afd88968e87b'

I found  /cgroup/cpuset/lxc/cpuset.cpus is empty
#cat /cgroup/cpuset/cpuset.cpus 
0-31
#cat /cgroup/cpuset/lxc/cpuset.cpus

it works if i set /cgroup/cpuset/lxc/cpuset.cpus value. I think cpuset.cpus should inherit the parent.

**Comment by jfrazelle** [comment]
@ashahab-altiscale can you let me know if this is ok to close as well, or @freax007 can you try with master (binaries at master.dockerproject.com) with lxc v1.0.7

**Comment by jfrazelle** [comment]
closing as this does not seem to be a problem with lxc 1.0.7 and the latest versin of docker
