### ISSUE TITLE
layersize vs json size?

### ISSUE THREAD

**Issue by shayke** [docker/docker#7718]
I noticed on one layer that the layersize is different than what's inside the json Size:

└─511136ea3c5a Virtual Size: 0 B
  ├─1c9383292a8f Virtual Size: 192.5 MB
  │ └─9942dd43ff21 Virtual Size: 192.7 MB
  │   └─d92c3c92fa73 Virtual Size: 192.7 MB
  │     └─0ea0d582fd90 Virtual Size: 192.7 MB
  │       └─cc58e55aa5a5 Virtual Size: 225.4 MB
  │         └─c4ff7513909d Virtual Size: 225.4 MB Tags: ubuntu:trusty

cat /var/lib/docker/graph/cc58e55aa5a53b572f3b9009eb07e50989553b95a1545a27dcec830939892dba/layersize
32674350

grep "Size" /var/lib/docker/graph/cc58e55aa5a53b572f3b9009eb07e50989553b95a1545a27dcec830939892dba/json
"Size":36802927}

Why there is a difference? I understand that layersize is used for `docker images --tree` but what does the size inside the json represents?

**Comment by jfrazelle** [comment]
here is some information about "virtual size" http://docs.docker.com/reference/commandline/cli/#images
