### ISSUE TITLE
docker serach all images  for private registry

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#7719]
hi

I think the code
"validRepo := regexp.MustCompile(`^([a-z0-9-_.]+)$|\s{0}`)
  if !validRepo.MatchString(name) {
      return fmt.Errorf("Invalid repository name (%s), only [a-z0-9-_.] are allowed", name)
  }"
is better than the code
"validRepo := regexp.MustCompile(`^([a-z0-9-_.]+)$`)
  if !validRepo.MatchString(name) {
       return fmt.Errorf("Invalid repository name (%s), only [a-z0-9-_.] are allowed", name)
   }"

because the docker-registry support xxx/v1/search for query the all images in the private registry，if the name="", docker should return the all images in the private registry. and there is not many images in a private registry.

thanks

**Comment by jfrazelle** [comment]
we decided we did not want to have a way to search all the images see https://github.com/docker/docker/pull/8155
