### ISSUE TITLE
Cannot pull image, 'authentication required'

### ISSUE THREAD

**Issue by SaschaMoellering** [docker/docker#7720]
Hi,

I installed Docker an EC2 using AWS Linux and I get 

Pulling repository ubuntu
2014/08/25 11:01:00 Authentication is required.

if I try to pull the ubuntu-image (sudo docker pull ubuntu). I already changed the timezone, but it's still not working. My Docker version is Docker version 1.1.2, build d84a070/1.1.2.

Thanks and Regards,
Sascha

**Comment by jfrazelle** [comment]
looks like it was resolved let me know if you think otherwise
