### ISSUE TITLE
enable --device flag to handle all devices in a given directory

### ISSUE THREAD

**Issue by brauner** [docker/docker#7721]
This is closely related to #7701. The new `--device` flag is a really good idea. If I wanted to add 3D support in my container I could do so by granting it access via the `--device` flag:

```
docker run --device=/dev/dri/card0:/dev/dri/card0 --device=/dev/dri/controlD64:/dev/dri/controlD64 -i -t --rm /bin/bash
```

But `--device` is not able to handle all devices in a given directory. If it would be feasible to implement I would vote for `--device` to not just only handle single devices files but also directories that contain device files. Hence, given that only `card0` and `controlD64` reside in that directory the above call should be equivalent to:

```
docker run --device=/dev/dri/:/dev/dri -i -t --rm /bin/bash
```

When I do this now I will get an error message like: 

```
2014/08/24 10:05:40 Post http:///var/run/docker.sock/v1.14/containers/1c92e198d279d782f76722e8f3a1b318013e072b3342c21ea92fa96ebb27b2a5/start: EOF
```

**Comment by jfrazelle** [comment]
closed by https://github.com/docker/docker/pull/10745#event-271179342
