### ISSUE TITLE
client/daemon version mismatch incorrect behavior

### ISSUE THREAD

**Issue by phemmer** [docker/docker#7746]
Right now the remote API does not allow running clients with a newer API version than the daemon.

```
$ docker ps
2014/08/26 14:21:03 Error response from daemon: client and server don't have same version (client : 1.13, server: 1.12)
```

This message is misleading/incorrect. The code in question is [daemon.go:1057](https://github.com/docker/docker/blob/c4a190db0c7020ee39672421d1bbca3678f86683/api/server/server.go#L1057), which is checking to see that the client API is **newer** than the server API, not different. That code would happily allow running a client which is older than the server.

This brings me to the next point, why does it allow running an older client, but not a newer one?
This is extremely irritating to work with as I have to keep a separate client which is older than all the remote servers I end up working with.
The remote API changes between versions are usually so trivial, that in my opinion, this restriction is not warranted.

Can we either:
1. Fix the message to indicate that the client API is newer than the server API.
2. Remove the restriction altogether and just display a warning.

I would much prefer # 2.

**Comment by CCTJNII** [comment]
+1 for reverse compatibility.

**Comment by ahmetalpbalkan** [comment]
Reverse compatibility is way too complicated to achieve and requires tons of tests. Our response structs are not versioned or anything and Remote API already handles default/empty values very poorly.

In #11486 I am proposing a workaround to override the API version string used through an environment varible e.g `DOCKER_API_VERSION=1.15 ./docker -H myolddockerhost.com:4243 ps`

**Comment by draghuram** [comment]
I created PR #13567 to fix the error message.

**Comment by thaJeztah** [comment]
@phemmer can this be closed now that #13567 was merged?

**Comment by Bharathkumarraju** [comment]
Hi Guys i am getting error like this eventhough my docker version showing same api version for client and server?

# docker version
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Jul 20 00:06:39 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Jul 20 00:06:39 2017
 OS/Arch:         linux/amd64


 # python
Python 2.7.5 (default, Aug 29 2016, 10:12:21)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> client = docker.APIClient(base_url='unix://var/run/docker.sock')
>>> print client.version()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/docker/api/daemon.py", line 177, in version
    return self._result(self._get(url), json=True)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 226, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/api/client.py", line 222, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("client is newer than server (client API version: 1.30, server API version: 1.24)")
>>> quit()
 #

**Comment by thaJeztah** [comment]
Removed @Bharathkumarraju's comment as  it was posted on https://github.com/moby/moby/issues/21930 as well, and I answered there https://github.com/moby/moby/issues/21930#issuecomment-334081937
