### ISSUE TITLE
Generated hostnames should start with a letter

### ISSUE THREAD

**Issue by tgpfeiffer** [docker/docker#7756]
The IDs generated from Docker for containers are also used as hostnames within the containers. These IDs are hexadecimal strings, therefore they can start with digits and occasionally consist only of digits. As explained in <https://bugzilla.redhat.com/show_bug.cgi?id=1059122>, a digit-only hostname is a valid hostname as per RFC 1123, but there seems to be a certain overlap with the allowed format of IPv4 addresses.

Also, there may be libraries around that still consider hostnames invalid that start with a digit. For example, for me the setup of a Cloudera Hadoop node fails exactly on those containers whose ID starts with a digit because a heartbeat does not succeed. As these format checks are usually very deep in the call stack, I think it would be a good thing for Docker to adher to the [robustness principle](http://en.wikipedia.org/wiki/Robustness_principle) and to restrict itself to hostnames starting with a non-digit character.

**Comment by jfrazelle** [comment]
our hostnames are valid https://github.com/docker/docker/pull/8194#issuecomment-57379360

**Comment by tgpfeiffer** [comment]
@crosbymichael By "we do ensure" did you mean "such a check is already in place" or "we will add such a check"?
