### ISSUE TITLE
container-level view of iptables setup

### ISSUE THREAD

**Issue by astraw** [docker/docker#781]
It would be cool if "docker inspect" or "docker port --verbose" (or both) gave info about how the iptables were set up for a particular container.

This would be particularly useful because docker the routing is kernel level and thus many tools for looking at userspace cannot be used to figure out what a container is listening to. For example, my usual "lsof | grep TCP" fails to show what the container is listening to and even misleadingly suggests it's only localhost.

(And once containers can be assigned to listen only on specific interfaces, this will be more useful.)

**Comment by JulianGindi** [comment]
I'm going to take a crack at this, I'll let you guys determine if it's compelling enough to include once I'm finished.

**Comment by cpuguy83** [comment]
Is this needed? Docker reports which ports are exposed by the container, forwarding ports, etc.

**Comment by cpuguy83** [comment]
Closing due to no response and inspect output ought to be enough.
Also iptables is now just one small part of the networking strategy with libnetwork now merged.
