### ISSUE TITLE
Find volumes without containers and restore them

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#7811]
i think recreate containers for all volumes that are there and got no container anymore will help a lot

so you can see them via docker ps and delet again with -v

**Comment by jfrazelle** [comment]
@cpuguy83 i think this might be a duplicate of something but idk

**Comment by cpuguy83** [comment]
Not explicitly no, but handled by #8484

**Comment by thaJeztah** [comment]
@frank-dspeed I think #8484 (which implements https://github.com/docker/docker/issues/8363) covers your use case. If you agree, this issue can be closed, so that the discussion can be continued on #8484

**Comment by thaJeztah** [comment]
For those following this; volume management is now implemented in https://github.com/docker/docker/pull/14242, which was just merged, and will be in **docker 1.9**

If you want to test it before that, nightly builds, build from master can be found at https://master.dockerproject.org
