### ISSUE TITLE
mkimage.sh regression, please add proxy support

### ISSUE THREAD

**Issue by suntong001** [docker/docker#7853]
The `mkimage.sh debootstrap` is supposed to replace the defunct `mkimage-debootstrap.sh`. However, one key feature missing from `mkimage.sh` is the capability of specifying proxy servers. It is vitally important for those people who are behind some proxy servers, or for those people that are using caching servers to cache Debian packages instead of downloading them over and over again when building each docker image.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/4962
