### ISSUE TITLE
Proposal: Add a way of forking/cloning containers

### ISSUE THREAD

**Issue by kuon** [docker/docker#7859]
It would be very useful to be able to do something like:

    docker clone -e SOMEVAR=foo --name=newcontainer my_container
    docker clone --image=someimage --replace my_container

The first one would start a new container named "newcontainer" with the same settings as my_container except of the environment variable `SOMEVAR` would be overridden over "my_container".

The second one (which is the main feature for me) would allow "upgrading a container". At present if you update an image, pull it, you need to remove the old container, and start a new one with the same arguments (env vars, ports...). Of course this can be done with some orchestration tool, but when you are testing around, it would be nice to be able to do it directly.

Something like:

    docker update --image=newimage my_container

Could work, but I like the clone idea, and the flexibility of replacing or not the currently running container.

**Comment by icecrime** [comment]
I believe this is solved with the newly introduced `docker service` commands and support for rolling updates.
