### ISSUE TITLE
Documentation update for interface level counters

### ISSUE THREAD

**Issue by BrettTrotter** [docker/docker#7866]
Based on https://docs.docker.com/articles/runmetrics/#interface-level-counters but scripted/refined and working on Ubuntu 14.04. The main thing needed in the documentation a comment for 14.04 showing the path to the cgroup device is /sys/fs/cgroup/devices/docker/$CID*/tasks instead of /sys/fs/cgroup/devices/$CID*/tasks, but here's a script to show the interface stats in one command.

```
#!/bin/bash
if [ $# -ne 1 ]; then
  echo "usage: $0 {container_id}"
  exit 1
fi

SHORT_CID=$1
CID=$(docker inspect --format="{{.Id}}" ${SHORT_CID} 2>/dev/null)
if [ $? -ne 0 ]; then
  echo "No container: ${SHORT_CID}"
  echo "Are you running with sudo?"
  exit 2
fi


TASKS=/sys/fs/cgroup/devices/docker/$CID/tasks
PID=$(head -n 1 ${TASKS})
NETNS_PATH=/var/run/netns/${CID}

mkdir -p /var/run/netns
ln -sf /proc/$PID/ns/net ${NETNS_PATH}
ip netns exec ${CID} netstat -i

unlink ${NETNS_PATH}
```

**Comment by thaJeztah** [comment]
I think this can be closed, because https://github.com/docker/docker/pull/15885 was merged
