### ISSUE TITLE
Invoking Dockerfile commands from a script

### ISSUE THREAD

**Issue by pomke** [docker/docker#7880]
Hello, I'm writing a small shell script called DHELPER which I can use from my Dockerfiles to simplify a few issues, it has a few subcommands. One that I'm trying to add is INSTALL, which would work like this:

```Dockerfile
# My docker image
FROM pomke/base
MAINTAINER pomke <pomke@pomke.com>

# install some services
RUN DHELPER INSTALL example.com/nginx/Dockerfile
RUN DHELPER INSTALL example.com/munin/Dockerfile

# .. do my own stuff here
```

The DHELPER INSTALL command fetches a dockerfile, strips out FROM and MAINTAINER etc commands and would execute ADD, RUN, WORKDIR etc commands in place, as if they were included in my current dockerfile.

So I'm trying to work out of there is a way I can invoke Dockerfile commands from a script of my own, within the context of a building image.

Thanks!

\- Pom

**Comment by jfrazelle** [comment]
hmm  could this be solved with ONBUILD

@tiborvass did you have something in mind i see you are assigned

**Comment by tiborvass** [comment]
This is similar to #7277 (although more precise in what it would be doing). We could close this as a dupe but that other issue has two distinct threads that are somewhat related (I intend to add a long comment on that one).

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
