### ISSUE TITLE
Lots of CLOSE_WAIT connection using the TCP API.

### ISSUE THREAD

**Issue by paparent** [docker/docker#7888]
Hi,

I don't know if it's related to any of those: #2126 #2127 #2952

We are using TCP to remote control docker. In our hosts (the server), we have plenty CLOSE_WAIT socket. The issue listed above seems to be client issue, but here it's the server.

```
$ sudo netstat -tanpl | grep CLOSE_WAIT | grep docker | wc -l
14306

$ docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): d84a070
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): d84a070
```

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/6318
