### ISSUE TITLE
Docs: Unable to zoom docs on iPhone

### ISSUE THREAD

**Issue by metalivedev** [docker/docker#7907]
According to a user, viewing http://docs.docker.com/userguide/ on an iPhone leads to pages that are zoomed way in and can't be zoomed back out, requiring users to pan around to read any of the content.

**Comment by jfrazelle** [comment]
is this still applicable?

**Comment by metalivedev** [comment]
It is still not pretty on Android browser version 4.3-776638, but it is zoomable.

**Comment by codykrieger** [comment]
This is very much still a problem on iPhones.

**Comment by jfrazelle** [comment]
ah ok cool, just checking in on a status update :D thanks all

**Comment by ChristopherBiscardi** [comment]
@jfrazelle yep, still busted. We're in the process of building out some new ui stuffs, which would then be uses for docs as well.

**Comment by moxiegirl** [comment]
@SvenDowideit  This seems to be fixed with that user contribution to docs/base  --- the guy that added support for mobile to the CSS.  What do you think?

**Comment by SvenDowideit** [comment]
its not ideal, but its better - lets close for now
