### ISSUE TITLE
Proposal: Improve presentation of tags on https://registry.hub.docker.com

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#7919]
(This is not a *Docker* issue, but I don't think the registry *website* has a separate issue tracker)

The presentation of tags on the registry could use some loving care. I'm using the debian repository 
as an example (https://registry.hub.docker.com/_/debian/tags/manage/)

#### Improve sorting

The sort-order is confusing, because *alfabetical* sorting is used, not *natural* sort, causing
tag `6.0.10` to become *before* `6.0.8`;

    latest
    6
    6.0
    6.0.10
    6.0.8
    6.0.9
    ...

#### Add an 'aliases' column

Many repositories tag the same image under multiple names. Without showing the image-id of each
tag, it's not possible to see which tags are actually the same image.

Some distros use *named* and numbered releases (e.g. `Debian wheezy` being `Debian 7.4`, `Ubuntu 
Trusty` being `Ubuntu 12.04`). Unless familiar with the 'naming' of those distros, this is 
confusing (is 'wheezy' newer than 'jessie`?)

#### Add 'Size'

Allows the user to *see* the filesize of an image before deciding to download a repo or image. 
This is especially important, because *canceling* `docker pull` is currently not possible.

#### Add 'Image ID' and 'Build date'

Allows the user to check if a local image needs updating (and 'validate' the image id?).

#### Bonus points; show pull command for selected tag

The Docker Hub Registry currently shows instructions how to pull the *repository*;

    Pull this repository `docker pull debian`

When clicking a specific tag, this could be changed to 'how to pull the selected tag';

    Pull this image `docker pull debian:tagname`

The resulting output will be like this;

Tag     | Aliases              | Size   | Image ID     | Build date
--------|----------------------|--------|--------------|-----------------------
latest  | 7, 7.6, wheezy       | 85 Mb  | b0a528bf0519 | 2014-01-03 20:39:02
6       | 6.0, 6.0.10, squeeze | 79 MB  | 25daec02219d | 2014-01-03 20:39:02
6.0     | 6, 6.0.10, squeeze   | 79 MB  | 25daec02219d | 2014-01-03 20:39:02

**Comment by jfrazelle** [comment]
where do feature requests for hub go? it feels weird to close this

**Comment by jfrazelle** [comment]
ping @kencochrane there should be a public place

**Comment by metalivedev** [comment]
We don't (and can't) support the Hub via GitHub. It is not an open source project. Please send feature requests and issues to support@docker.com. If you would like to start a thread and show support for a specific feature request, you could do that on forums.docker.com.

Expanding on the "can't" part: the more queues the support team has to watch, the higher the probability of something falling through the cracks. We stay on top of our support queue and try to review threads in the forums when possible.

**Comment by jfrazelle** [comment]
thanks for explaining @metalivedev totally understandable, I will let @thaJeztah choose the course of action ;)

**Comment by thaJeztah** [comment]
Ooh, completely forgot this one.

I'll close this and create a support ticket at "docker support"
