### ISSUE TITLE
readonly root inside container

### ISSUE THREAD

**Issue by alberts** [docker/docker#7923]
Fedora has supported the concept of a readonly root for a long time as way of making a system more stateless.

We have used this with boot-from-initramfs deployments to make sure that no service accidentally writes somewhere it shouldn't. I think this could also be useful within containers to make sure that services that run in the container are properly configured to either write data to tmpfs-backed temporary directories or to r/w volumes shared from outside with --volume and nowhere else.

The main Fedora script is here: https://git.fedorahosted.org/cgit/initscripts.git/tree/systemd/fedora-readonly

A writeup of how it works: https://warewolf.github.io/blog/2013/10/12/setting-up-a-read-only-rootfs-fedora-box/

In a Docker context, I think the main things that would carry over are flags for docker run:

- roroot=true|false (mount root of container read-only)
- rwtab=somefile (files and directories that should be bind-mounted so they are writable to a tmpfs)
- statetab=somefile (files that should be writable to persistent storage
- statemount=/some/dir (path to a directory passed through with --volume for state files)
- rwoptions= (mount options for the tmpfs, size= is the main useful one)

Does this sound like something that's interesting to support in Docker? If so, I could start looking at putting together the start of a pull request.

**Comment by scf37** [comment]
Read-only containers are more secure as well.

**Comment by discordianfish** [comment]
@crosbymichael Is this something we want and just nobody has implemented it? If so, I can do that.

**Comment by crosbymichael** [comment]
@discordianfish it's implemented ( in libcontainer ), we just need some agreement on the flag.  

Let me discuss with my fellow maintainers and see if we can get this sorted out and in for 1.5

**Comment by crosbymichael** [comment]
I think this will probably depend on `tmpfs` mounts also because `/tmp` will probably have to go into tmpfs

**Comment by crosbymichael** [comment]
@discordianfish go ahead and implement --readonly if you have time.  For it to be in docker 1.5 it needs to be done this week, if you don't have time I can implement it.

**Comment by discordianfish** [comment]
@crosbymichael I would love to implement it, but have no time this week. So if you have time, go for it.
