### ISSUE TITLE
Can not use -volumes-from <parent> if parent has a host volume mounted (/var/run/docker.sock) in my case

### ISSUE THREAD

**Issue by dpittner** [docker/docker#7925]
When starting a second container using volumesFrom, the command fails. Issue seems to be that the first container has a host mount (docker socket). The container logs report:

`lxc-start: No such file or directory - failed to mount '/var/run/docker.sock' on **'/usr/lib64/lxc/rootfs///var/run/docker.sock'**
lxc-start: failed to setup the mount entries for 'cf0912058a5a241eb750c936da500b47c4152320a7dc2995ea2f08ce6bd88d19'
lxc-start: failed to setup the container
lxc-start: invalid sequence number 1. expected 2
lxc-start: failed to spawn 'cf0912058a5a241eb750c936da500b47c4152320a7dc2995ea2f08ce6bd88d19'
lxc-start: The container failed to start.
lxc-start: Additional information can be obtained by setting the --logfile and --log-priority options.`

In order to reproduce the issue, you may perform the following steps:

```
docker run -d -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/resource ubuntu /bin/bash
docker run -i -t --rm -volumes-from <id of first container> ubuntu /bin/bash
```

Fails with a error similar to one mentioned above.

I'm currently getting around this by running docker inspect on the first container, selectively only mounting /resource to the second container. But that's a hack to me.

Please find the system information below:

docker version
Client version: 1.1.2
Client API version: 1.13
Go version (client): go1.2.2
Git commit (client): d84a070/1.1.2
Server version: 1.1.2
Server API version: 1.13
Go version (server): go1.2.2
Git commit (server): d84a070/1.1.2

 docker -D info
Containers: 17
Images: 211
Storage Driver: devicemapper
 Pool Name: docker-253:0-1967318-pool
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 19108.1 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 18.8 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: lxc-1.0.5
Kernel Version: 2.6.32-431.23.3.el6.x86_64
Debug mode (server): false
Debug mode (client): true
Fds: 88
Goroutines: 99
EventsListeners: 0
Init SHA1: 808ba4d09a4b931f5f745154bea886f252a1aef4
Init Path: /usr/libexec/docker/dockerinit
Sockets: [tcp://0.0.0.0:4243 unix:///var/run/docker.sock]

**Comment by cpuguy83** [comment]
ping @dpittner

**Comment by cpuguy83** [comment]
@ashahab-altiscale confirmed behavior on lxc with the ubuntu image mounting to /var/run/docker.sock
Mounting to `/run/docker.sock` works.

This all works with native exec driver.

**Comment by cpuguy83** [comment]
busybox does not reproduce this issue, btw.

**Comment by icecrime** [comment]
As notified in our [deprecation notice](https://github.com/docker/docker/blob/d023d5a8a24c18e912162c2f4c724cfb21028301/docs/misc/deprecated.md#lxc-built-in-exec-driver), Docker 1.10.0 will drop support for the LXC exec driver (#17700).

Thank you for the report, I'm now closing this.
