### ISSUE TITLE
Hub and Registry API Spec Clarification -- It appears to just be wrong.

### ISSUE THREAD

**Issue by ekristen** [docker/docker#7939]
Registry 0.8.0 and the Hub and Registry Spec v1.2 do not match up for pushing images. I haven't tested pulling images yet.

Can you clarify which version of the spec goes with which version of the registry?

As far as I can tell steps are wrong.

For pushing an image I'm seeing this request GET /v1/repositories/dockerfile/nginx/layer/27cf784147099545/access, yet there is no documentation talking about an access endpoint, and the built in no-auth index apart of the registry code doesn't event reference an access endpoint.

The behavior I see is the following. This is version 0.8.0 of the registry and 1.2.0 of the docker client/daemon

(this flow here does not include the registry actions, just the actions I am seeing on the index/hub)

1. GET /v1/_ping
2. PUT /v1/repositories/:namespace/:repo
3. GET /v1/repositories/:namespace/:repo/images
4. GET /v1/repositories/:namespace/:repo/images
5. GET /v1/repositories/:namespace/:repo/layer/:image/access

At step 5 it fails with `2014/09/08 12:11:34 HTTP code 400 while uploading metadata: {"error": "Image depends on an unauthorized parent"}`

Thanks.

**Comment by jfrazelle** [comment]
@steeve will this all be replaced by v2

**Comment by dmp42** [comment]
@jfrazelle : I guess you meant @stevvooe 
And answer is yes.

**Comment by ekristen** [comment]
Is v2 documentation available anywhere? I'd like to be able to update my project sooner than later.

Thanks!

**Comment by stevvooe** [comment]
@ekristen All specs for v2 registry are here: https://github.com/docker/distribution/tree/master/doc/spec. Albeit, I am not sure if it will help directly with the current issue.

I'm usually around #docker-distribution on IRC if you need clarification.

**Comment by cpuguy83** [comment]
This seems no longer relevant, should we close?

**Comment by thaJeztah** [comment]
Agreed, I'll close this
