### ISSUE TITLE
Need Ability to set Host on Build!

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#7966]
Software often needs a hostname to work example i got a install script that complains about

INFO - Hostname  is not fully qualified.
Please enter a fully qualified hostname (for example, host.example.com): INFO - Hostname 347a3d6eaa91 is not fully qualified.
^Cfrank@server2:~$ 

and there is no way to change the hostname on build hostname host don't works any bind mount reason for sure

and echo into /etc/hostname don't works probally same problem

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/10324
