### ISSUE TITLE
implement **before** for images remote api endpoint

### ISSUE THREAD

**Issue by munglerizer** [docker/docker#7967]
As issue #7903 was closed without discussion. I am opening a revised version taking into account the last/only comment.

Much the same as the containers endpoint:
```
Query Parameters:
-   **before** – Show only images created before RepoTag
```
The reason for this request is that it would make cleaning up images much easier on machines that are tasked with building docker images but don't run the containers. The output of 'GET /containers/json?all=1&before=...' is blank on these machines. but /var/lib/docker is full of images.

I could then feed the results of this into the delete endpoint:

DELETE /images/(name)

This would leave the current latest image intact with all ancestors but remove older images (or untag them)

From the previously raised issue, I agree that if the remote api is preferred over the cli (and evidently rcli) then it should not be implemented there. But this operation appears to still be missing from the api and would be very good to have for large scale image/container producers.
If there is another way to achieve this end result, could an example be provided before this issue is closed and locked, thank you in advance.

**Comment by jfrazelle** [comment]
this could be added as a `--filter`

**Comment by termie** [comment]
+1

**Comment by adowner** [comment]
An alternative to the above if you use a 'latest' tags on your images. You can remove all the images that are not tagged as latest, therefore maintaining a cache (good for build machines) whislt keeping things trim.

docker images | tail -n +2 | awk '$2 !~ "latest" {print $1 ":" $2}'

**Comment by zelahi** [comment]
#dibs, 

If there was still any interest on having this implemented, I would like to work on it =)

**Comment by tkopczynski** [comment]
Is anyone working on this?
If this feature is still needed, I'd like to take it.

**Comment by vdemeester** [comment]
@tkopczynski I'm not sure…

**Comment by munglerizer** [comment]
@zelahi you claimed this issue, but there has been no updates since. Has anything changed?

**Comment by zelahi** [comment]
Ahh sry go ahead and take it over. I havent been able to work on it

**Comment by tkopczynski** [comment]
@vdemeester I guess that you're not sure whether it should be implemented?

**Comment by Fredjet** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  fredjet15@gmail.com
    Domain ventureacceleration.com has exceeded the max emails per hour (61/50 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext4.iad.github.net ([192.30.252.195]:51717 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by eaglepeak.ovasp.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aarpN-0008It-4A
	for fred@ventureacceleration.com; Tue, 01 Mar 2016 16:27:33 -0500
Date: Tue, 01 Mar 2016 13:26:40 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1456867600;
	bh=jv9iY9wqxT/1CjYr1WTI8QuMjMgs2YjLCrb1IxtIL1U=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ZNKsLQe8AuXbYYOTbS4t9sy6Tw6cm5Oa9X0dTpsA2EaHt4+XJC1JNGsO/qKRv3U41
	 sCiPpV1zAOXvMHdifSffRauX3ewgj8FRVyNLE3yjNNyrMKpi/Cnjr5mSRHNarHL55q
	 94gO3QDMCqrKBEvHIJ+L1Qyxnqw3j8nvZOsGM4FM=
