### ISSUE TITLE
Docker fails to detect btrfs support if dkms is installed

### ISSUE THREAD

**Issue by mbert** [docker/docker#7970]
Platform: CentOS 7.0 (x86_64), minimal system with VirtualBox Linux guest additions and dkms (from EPEL) installed.

Docker versions: 1.2 (from CentOS 7.0 distribution) and 0.9 (various git snapshots)

Steps to reproduce: run 'docker -d --selinux-enabled=false -s brtfs'

Effect: docker process dies with 'driver not supported' message

Docker can be run with no storage backend specified in the command line. The problem disappeared after I uninstalled dkms.

**Comment by jfrazelle** [comment]
@mbert are you still seeing this problem

**Comment by jfrazelle** [comment]
closing as stale please ping me with steps to reproduce on latest

**Comment by mbert** [comment]
Sorry for coming back to you late. Unfortunately I am no longer working on the project in which I ran into this problem - thus I have no longer access to the environment needed to reproduce this error.
