### ISSUE TITLE
Remove all Hacks out of Debbootstrap or any Baseimage

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#7977]
Docker needs sometimes some nice hacks in baseimages but they are individual applying hacks in the docker base image has many disadvanteges over not having them directly in.

Some one who whants to base on that Baseimage whats logical becaus the way how docker works he don't need to maintain the source ! he don't needs to analyze the repo for hacks made and by pass them as example the gz list hack: issu #5639 

it breakes compatiblity with the ubuntu distribution tools like apt-show-versions that can't handle gz at present so every one who uses that image and whants to get normal compatiblity needs to revert that hack

thats not acceptable baseimage should be baseimages to base on and place own needed hacks on it

Else its hard to suggest whats original whats hacked what do you think?

**Comment by jfrazelle** [comment]
closing as apt-show-versions bug is an issue _not_ in docker itself and we have reasons for the way it works today as clearly shown above
