### ISSUE TITLE
Add the same files content but docker still invalidate the cache

### ISSUE THREAD

**Issue by phuongnd08** [docker/docker#8007]
I'm combining docker with mina deploy (which is similar to capistrano). The idea is that every deploy, mina will create a snapshot of current code base to a new release folder. And from that release folder I build the docker image. I can see that even the file being added doesn't change at all, but when docker being run from a new release folder, it rebuild everything, which make the deploy process a pain in the ass.

**Comment by jfrazelle** [comment]
I can not reproduce with latest @phuongnd08 if you are still seeing this send us the exact steps to reproduce and dockerfile
