### ISSUE TITLE
Expose the entire Build API through REST and introspection

### ISSUE THREAD

**Issue by thedrow** [docker/docker#8032]
Currently it is only possible to build a docker image from a tarball containing a Dockerfile using the REST API.
There's no reason why we shouldn't be able to build a docker image entirely using the REST API.
This will enable integrations with multiple configuration management tools like Salt and Puppet which already have superior and less error prone provisioning capeabilities.
How hard would it be to achieve this?
It would involve exposing all commands in https://github.com/docker/docker/blob/master/builder/dispatchers.go if I understand correctly.

**Comment by thedrow** [comment]
Any updates on this one?
I know that we have ```docker exec``` but that only helps us not having to run the provisioner inside the container which is not enough. I'd like to fully utilize the build caching mechanism that docker provides us with.

**Comment by tiborvass** [comment]
I'm closing this since #13171 was merged which was the last blocker for implementing #14298.

@jlhawn implemented an experimental client-side builder: https://github.com/jlhawn/dockramp which uses the new APIs in #13171.

Hope this helps :)
