### ISSUE TITLE
docker run -t causes stderr messages to be sent to stdout.

### ISSUE THREAD

**Issue by rhatdan** [docker/docker#8040]
Bugzilla https://bugzilla.redhat.com/show_bug.cgi?id=1121689 

Description of problem:
The handling of stdout/stderr stream is not correct in tty mode (works fine in non-tty mode). You can see it on the example bellow. (`ls non_existing_file` prints into stderr stream)

Version-Release number of selected component (if applicable):
docker-1.1.1-1.el7.x86_64

How reproducible:
Always

Steps to Reproduce:
TTY:
[root@localhost ~]# docker run -t -a stderr fedora ls non_existing_file
[root@localhost ~]# docker run -t -a stdout fedora ls non_existing_file
ls: cannot access non_existing_file: No such file or directory
NON-TTY:
[root@localhost ~]# docker run -a stderr fedora ls non_existing_file
ls: cannot access non_existing_file: No such file or directory
[root@localhost ~]# docker run -a stdout fedora ls non_existing_file

Actual results:
In tty mode the output is visible only when STDOUT is attached, in non-tty mode it's visible in STDERR

Expected results:
In booth modes the output should be in STDERR stream.

Additional info:
When I use `ls /` it prints the info correctly into STDOUT in booth modes.

**Comment by xiaods** [comment]
Today i ran into this case, in my usecase, docker 1.4.1,  we directly use  below command:
docker run  fedora ls non_existing_file, then it will bind to stdout and stderr.

**Comment by jfrazelle** [comment]
since this by design because of blockers w pty I think this can be fixed when someone updates docs and possibly adds warning

**Comment by devopsko** [comment]
#dibs

**Comment by nhsiehgit** [comment]
Hi @devopsko,

Please remember to add the keyword tags `closes` or `fixes` once you PR to help make tracking the fixes easier. Thanks!
