### ISSUE TITLE
Can't commit a container inside which Docker has been installed: no space left on device

### ISSUE THREAD

**Issue by mpetazzoni** [docker/docker#8043]
Hi all,

I just stumbled upon an issue with committing containers while going through the process of building a Docker image. I have been through that process in the past and it worked, so this sounds like a regression (post 0.9, unfortunately can't be more precise at this point).

The problem is that Docker is installed inside the container, and this creates a `/var/lib/docker/devicemapper/devicemapper/data` file that is 100G big (a fake file of course, but not in the eyes of `docker commit` it seems). When exiting the container and then committing it, it will start using up all the available disk space on the host and eventually fail with a `no space left on device` error.

If I manually remove `/var/lib/docker` from within the container, the `docker commit` succeeds. Note that this problem does not appear when Docker is installed in non-privileged mode, supposedly because Docker cannot start at the end of the install to create the devicemapper file. So this doesn't happen unless you use `RUNP apt-get install lxc-docker`, or installing Docker from within a container started with `--privileged`.

I think this is a problem with `docker commit` and whatever it does to create the image, which I'm guessing is not much more than making a tarball of some sort out of the rootfs of the container. Maybe some missing options to the tar command being used to avoid tripping itself on a "fake" 100GB file?

Host is Ubuntu Trusty, running Docker 1.2.0 on a 3.13.0-35 kernel.

**Comment by vbatts** [comment]
ok, so DinD has tricky caveats and while it stays as a goal and we work toward it, there are plenty of permutations that are yet to be confirmed as supported. With devicemapper allocating a block device by default there are things, like space allocation, that can go awry. I'll go ahead and close this, but encourage the conversation to continue so we can get a working example of DinD with devicemapper. Some resources/configurations you'll want to look at is the `dm.loopdatasize` and `dm.loopmetadatasize` storage options (https://github.com/docker/docker/blob/master/daemon/graphdriver/devmapper/README.md) or some other combination of configurations. Until then, happy hunting.
