### ISSUE TITLE
Index host cert config used even when layer pulling redirected off that host

### ISSUE THREAD

**Issue by dpiddy** [docker/docker#8045]
Say I'm running docker-registry at index.example.org, with my own CA for SSL. I've placed my root CA cert at `/etc/docker/certs.d/index.example.org/ca.crt`. This gets `docker pull` talking to my registry.

If I'm also running the registry with `STORAGE_REDIRECT=True` to have clients pull images directly from S3 via redirects, the cert config in `/etc/docker/certs.d/index.example.org` is then used again when connecting to foobar.s3.amazonaws.com. That means I need to add cert info for S3 to that directory as well.

I would expect the cert config for talking to foobar.s3.amazonaws.com to be handled by `/etc/docker/certs.d/foobar.s3.amazonaws.com`, if it exists.

**Comment by jfrazelle** [comment]
can you please open this issue on docker/registry seeing as it is a registry specific issue, sorry for the delay is response
