### ISSUE TITLE
make `docker images repository:tag`  work

### ISSUE THREAD

**Issue by jbeda** [docker/docker#8048]
I'm scripting the docker command line client and I want to check to see if an image is already built.  I'm doing this with `docker images myrepo:mytag`.  However, this doesn't find the image.  It appears as this will only match on repo and not the full name of the image.

**Comment by jfrazelle** [comment]
this shouldn't be that hard if a newcomer want something to contribute ;)

**Comment by tianon** [comment]
@jbeda just as another solution to the specific problem you reported (besides the proposal to make `docker images repo:tag` actually work, which is definitely necessary), you could use `docker inspect repo:tag > /dev/null 2>&1`, like we do in some of Docker's own build scripts (https://github.com/docker/docker/blob/b52a2cfdf1aabf15a4a1a630b3899ae373516517/project/make/.ensure-busybox#L4 and https://github.com/docker/docker/blob/b52a2cfdf1aabf15a4a1a630b3899ae373516517/project/make/.ensure-emptyfs#L4)

Also, `docker images repo | awk 'NR>1 && $2 == "tag" { print $1":"$2 }'` should work too:
```console
$ docker images ubuntu | awk 'NR>1 && $2 == "trusty" { print $1":"$2 }'
ubuntu:trusty
$ docker images ubuntu | awk 'NR>1 && $2 == "lolwut" { print $1":"$2 }'
$ 
```

**Comment by buddhamagnet** [comment]
#dibs

**Comment by buddhamagnet** [comment]
Happy to have a crack at this one!

**Comment by nhsiehgit** [comment]
Hi @buddhamagnet,
When you get a PR in please remember to add a `closes` or `fixes` keyword to help make tracking the fixes easier. Thanks!
