### ISSUE TITLE
Docker commands "easily" conflict with hashes

### ISSUE THREAD

**Issue by dvarrazzo** [docker/docker#8069]
I have been trying to restart my docker database for a while, but `docker restart db` was instead attaching me to a different running container.

Took me a while to figure it out but:

    CONTAINER ID        IMAGE                 COMMAND...
    dbca59fd042c        abc/quuux:latest      "/bin/bash" ...
    ba6fd772757b        abc/qwer:latest       "foo" ...
    ...

instead taking `db` as a name it was taking it as the prefix of one of the running image!

Ok, it happens only once over 256 to the people calling one of their docks "db", but still... Doesn't taking two chars leave too much space open to random effects on the hashes? Shouldn't the names have precedence over the hashes? I had to stop and remove the offending container to be able to restart the database.

Discuss...

**Comment by termie** [comment]
+1

**Comment by estesp** [comment]
This issue is fixed by PR #9705, but apparently didn't get marked as solved.
