### ISSUE TITLE
MySQL dump import takes a long long time (innoDB)

### ISSUE THREAD

**Issue by rkl-** [docker/docker#8119]
This is not the fist time we see this behaviour. The version we had tested is 1.2.0, build fa7b24f, on Ubuntu linux 12.04, but my workmate can confirm the same on Fedora 20.

We imported a 1.7 GB large MySQL dump and it took 87 minutes! On the same machine in a virtual box with just one cpu core enabled it took less than 20 minutes!

We are absolutely stumped why. Actually the MySQL stuff is the only phenomenon that we can observe, the rest like Apache is faster than in virtual box.

**Comment by SamSaffron** [comment]
I have an exact repro here as well ... innodb crawls ... MyISAM flies . 

It does feel like a docker bug and https://github.com/docker/docker/issues/12170 does not seem to resolve it. 

rootfs is just terribly slow with innodb will see if I can create a standalone repro.

**Comment by SamSaffron** [comment]
note ...@crosbymichael o_direct is working fine in the container exhibiting the slowness ... its got to be something else ... will see if it is filesystem related

**Comment by ChiperSoft** [comment]
@SamSaffron I'm experiencing this problem today. Did you ever find a solution?

**Comment by SamSaffron** [comment]
@ChiperSoft unfortunately only solution I had was to run myisam on host, which is fine for import work I do, we don't host anything on mysql

**Comment by netzkollektiv** [comment]
I'm having the same problem in Debian Jessie: InnoDB is ridiculously slow in a docker container - and fast outside. This happens with both kernels:
```
linux-image-3.16.0-4-amd64 (using aufs)
linux-image-4.8.0-0.bpo.2-amd64 (using overlayfs)
```
I'm using the official MySQL image, which is using a volume for /var/lib/mysql:
```
        "Mounts": [
            {
                "Name": "9838d031197e217c7e899b09e90c396fd542055afcc18610b3095ce4abbd7039",
                "Source": "/var/lib/docker/volumes/9838d031197e217c7e899b09e90c396fd542055afcc18610b3095ce4abbd7039/_data",
                "Destination": "/var/lib/mysql",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            }
```

I played with InnoDB settings and with the following settings it is getting much faster, but adjusting these does not solve the root of the actual problem:

```
[mysqld]
innodb_flush_log_at_trx_commit = 0
innodb_flush_method = O_DIRECT
```

Does anyone have a real solution for this?

**Comment by thaJeztah** [comment]
I'm trying to see if there's an easy way to reproduce / test this issue,
and to see the performance difference between mysql on the host, or in a
container. Here's what I did;

Install mysql on the host

```bash
$ apt-get update && apt-get install -y mysql-server

$ mysql --version

mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper
```

get a test database dump

```bash
$ mkdir -p repro-8119 && cd repro-8119
$ git clone https://github.com/datacharmer/test_db .
```

First try on the host;

```bash
$ time mysql < employees.sql

INFO
CREATING DATABASE STRUCTURE
INFO
storage engine: InnoDB
INFO
LOADING departments
INFO
LOADING employees
INFO
LOADING dept_emp
INFO
LOADING dept_manager
INFO
LOADING titles
INFO
LOADING salaries
data_load_time_diff
00:01:11

real	1m10.678s
user	0m3.336s
sys	0m0.472s

$ systemctl stop mysql
```

Try again on docker (using the same version of mysql as is installed on the host)

```bash
$ docker pull mysql:5.7.16
$ docker run -d --rm -v `pwd`:/test_db/ -e MYSQL_ALLOW_EMPTY_PASSWORD=yes --name repro-8119 mysql:5.7.16
```

On `aufs`;

```bash
$ docker exec -t repro-8119 bash -c 'cd /test_db/ && time mysql < employees.sql'

INFO
CREATING DATABASE STRUCTURE
INFO
storage engine: InnoDB
INFO
LOADING departments
INFO
LOADING employees
INFO
LOADING dept_emp
INFO
LOADING dept_manager
INFO
LOADING titles
INFO
LOADING salaries
data_load_time_diff
00:01:16

real	1m15.357s
user	0m3.168s
sys	0m0.540s

$ docker stop repro-8119
```

Trying on overlay2 (_should_ not make a difference, because the data is in a volume)

```bash
$ echo '{"storage-driver":"overlay2"}' > /etc/docker/daemon.json
$ systemctl restart docker
$ docker pull mysql:5.7.16
$ docker exec -t repro-8119 bash -c 'cd /test_db/ && time mysql < employees.sql'

INFO
CREATING DATABASE STRUCTURE
INFO
storage engine: InnoDB
INFO
LOADING departments
INFO
LOADING employees
INFO
LOADING dept_emp
INFO
LOADING dept_manager
INFO
LOADING titles
INFO
LOADING salaries
data_load_time_diff
00:01:13

real	1m12.980s
user	0m3.212s
sys	0m0.704s
```

This was on a fresh Ubuntu 16.10 node on DigitalOcean, running 1.13.0-rc5

```
Client:
 Version:      1.13.0-rc5
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 01:02:41 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0-rc5
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   43cc971
 Built:        Thu Jan  5 01:02:41 2017
 OS/Arch:      linux/amd64
 Experimental: false

Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.13.0-rc5
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 13
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 51371867a01c467f08af739783b8beafc154c4d7
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.8.0-30-generic
Operating System: Ubuntu 16.10
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: ubuntu-2gb-ams3-01
ID: BTOA:YN7Y:RBY4:MEBY:FRLE:CKGC:4JKL:SKF6:ONTY:SJGP:IB4V:2EQM
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

@netzkollektiv from my limited attempt, I was not able to reproduce the problem; if you have a way to reproduce, could you open a new issue with details? If there _is_ an issue at hand, it would be worth looking into, but it would definitely help if we had a way to reproduce.

One thing I _did_ notice is that the mysql container creates a `/tmp` directory, which does not appear to be a volume (or tmpfs);

```
$ docker diff repro-8119
C /run/mysqld
A /run/mysqld/mysqld.pid
A /run/mysqld/mysqld.sock
A /run/mysqld/mysqld.sock.lock
A /test_db
C /tmp
```

And `/tmp` is set as tempdir for mysql;

```
SHOW VARIABLES LIKE '%tmp%';
+----------------------------------+----------+
| Variable_name                    | Value    |
+----------------------------------+----------+
| default_tmp_storage_engine       | InnoDB   |
| innodb_tmpdir                    |          |
| internal_tmp_disk_storage_engine | InnoDB   |
| max_tmp_tables                   | 32       |
| slave_load_tmpdir                | /tmp     |
| tmp_table_size                   | 16777216 |
| tmpdir                           | /tmp     |
+----------------------------------+----------+
7 rows in set (0.00 sec)
```

**Comment by ChiperSoft** [comment]
I did finally find a workaround by defining an explicit volume in my docker-compose for mysql to store itself in. With this in place I was able to import a 200MB db from another container without any issue.

```yml
volumes:
  mysqldata:
    driver: local

services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysqldata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data:/data
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    ports:
      - "3306:3306"
```

**Comment by thaJeztah** [comment]
@ChiperSoft you mean the volume for `/var/lib/mysql` or the `/data` volume?

**Comment by ChiperSoft** [comment]
@thaJeztah the `mysqldata` named volume that's mapped to `/var/lib/mysql`.  `/data` is irrelevant, I should have omitted it.

**Comment by thaJeztah** [comment]
Interesting, because the `mysql` image already has a volume defined there, so a volume will always be mounted (only an "anonymous"/ randomly named one if no `-v` flag is set

**Comment by ChiperSoft** [comment]
My understanding is that the built in volume can be wiped out if the container is rebuilt. That's undesirable if your database is sufficiently large.

**Comment by thaJeztah** [comment]
Right, yes, that's true; was just looking at the initial issue mentioned here (performance in general)

**Comment by japita-se** [comment]
tried to update the image?
For this problem, I changed from mysql 5 to mariadb 10.
