### ISSUE TITLE
Docker (or some middleware) caches DNS lookups

### ISSUE THREAD

**Issue by gdm85** [docker/docker#8126]
There is an incorrect behaviour in how DNS lookups are handled in Docker (or some library thereof, although couldn't find a cache in [Go's net source](http://golang.org/src/pkg/net/dnsclient_unix.go))

Please check this testcase:
https://gist.github.com/gdm85/e02b1c2d0eb7ada5b590

**Warning:** will restart Docker!

Problem is that - even if there is no running DNS cache (dnsmasq or similar) - Docker is somehow remembering an /etc/hosts entry even if it was afterwards changed.

**Comment by jfrazelle** [comment]
is this still reproducable on the latest version of docker

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen

**Comment by gdm85** [comment]
@jfrazelle somehow Docker is no more affected by overrides in /etc/hosts, ignoring them
