### ISSUE TITLE
File corruption inside docker image

### ISSUE THREAD

**Issue by djl197** [docker/docker#8162]
All,
I am using a Dockerfile to build myself and Ubuntu 12 container.
I am based on the phusion baseimage and during the build I run svn export to download some large files from our SVN repo.
This works fine on a real machine, and also inside a Vagrant machine.
However within Docker I regularly get:
stderr: bzip2: FILENAME.tar.bz2: data integrity (CRC) error in data

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

I am 100% sure the files are not corrupted so it can only be:
HTTP downloads inside my containers are corrupting data,
or
Filesystem is unstable.

Does anyone have anything I can try to get more debug to try and resolve this issue?

I have attached system info below:

uname -a:
Linux MACHINENAME 3.13.0-35-generic #62~precise1-Ubuntu SMP Mon Aug 18 14:52:04 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

docker version:
Client version: 1.1.0
Client API version: 1.13
Go version (client): go1.2.1
Git commit (client): 79812e3
Server version: 1.1.0
Server API version: 1.13
Go version (server): go1.2.1
Git commit (server): 79812000

docker -D info
Containers: 3
Images: 51
Storage Driver: aufs
 Root Dir: /home/docker/aufs
 Dirs: 57
Execution Driver: native-0.2
Kernel Version: 3.13.0-35-generic
Debug mode (server): false
Debug mode (client): true
Fds: 11
Goroutines: 10
EventsListeners: 0
Init Path: /usr/bin/docker
Sockets: [tcp://0.0.0.0:4243 unix:///var/run/docker.sock]
WARNING: No swap limit support

**Comment by jfrazelle** [comment]
closing, but @djl197 if you are able to reproduce with the kernel vbatts suggested and the latest version of docker lmk and we can reopen
