### ISSUE TITLE
failure to start when setting -b=docker1

### ISSUE THREAD

**Issue by nhatnguyen26** [docker/docker#8174]
Hi docker,
I ran into a problem with my docker setup. So I created my own bridge called docker1 at the moment.
Then I went inside /etc/default/docker and add DOCKER_OPTS="-b=docker1" which work fine at that step.
However, whenever I restart my host machine, docker will not run on start up, I have to do "sudo service docker start" every single time. I tried to add "-d" into DOCKER_OPTS but it will not work.
My host is Ubuntu 14.04 using the latest version of docker, lxc-docker.

**Comment by jfrazelle** [comment]
@nhatnguyen26 are you still seeing this on the latest version of docker

**Comment by jfrazelle** [comment]
closing as stale please ping me with exact steps to reproduce on the latest version and I will reopen
