### ISSUE TITLE
'attach --no-stdin=false' implies the wrong state, should be --no-stdin=true

### ISSUE THREAD

**Issue by air** [docker/docker#8183]
The [way attach currently works (1.2.0) is](http://docs.docker.com/reference/commandline/cli/#attach):

> --no-stdin=false    Do not attach STDIN

This is the opposite meaning. For 'Do not attach STDIN' you would expect one of

1. `--stdin=false`
1. `--no-stdin=true`
1. `--no-stdin`

Recommendation: Given that `docker run` uses flags like `-a stdin` I would deprecate the current flag and use option 1 above.

**Comment by duglin** [comment]
close?

**Comment by tiborvass** [comment]
@duglin @jfrazelle @SvenDowideit @fredlf 

Seems to me like @air is right... `--no-stdin=false` means `--stdin=true`, which is the contrary of `Do not attach STDIN`. :(

**Comment by jfrazelle** [comment]
duplicate https://github.com/docker/docker/issues/9406
