### ISSUE TITLE
'docker push' should figure out which images to push in one pass

### ISSUE THREAD

**Issue by wking** [docker/docker#8188]
At somewhere around a second per layer-attempt, this is just silly:

    Pushing tag for rev [fbfaa6e4936f] on {https://cdn-registry-1.docker.io/v1/repositories/wking/gentoo-openrc/tags/latest}
    The push refers to a repository [wking/gentoo-syslog] (len: 1)
    Sending image list
    Pushing repository wking/gentoo-syslog (1 tags)
    6500a7bbc835: Image already pushed, skipping 
    50deaa9560b4: Image already pushed, skipping 
    35d81e7b8526: Image already pushed, skipping 
    c13686ec3c49: Image already pushed, skipping 
    96b283b060c2: Image already pushed, skipping 
    …

Maybe we need an endpoint so the client can say “I'm about to push these images: [6500a7bbc835, 50deaa9560b4, …]” and the registry can say, “actually, I already have some of those, you only need to push: […]”.

**Comment by jfrazelle** [comment]
ping @dmcgowan @jlhawn @steeve @dmp42

**Comment by dmp42** [comment]
@jfrazelle I don't think there is a point in making this happen for v1.

I would close this issue (for the reasons I pointed out in https://github.com/docker/docker/issues/8188#issuecomment-62758748 - the desire for this arose from the fact the performance sucks, and this is what should be fixed, and what is fixed by the new protocol).

**Comment by Maxim-Filimonov** [comment]
@dmp42 as this one is now closed and push is still ridiculously slow is there an issue to track work on the new protocol?

**Comment by dmp42** [comment]
@Maxim-Filimonov are you having issues with a private registry? what storage backend is it using? what version of docker are you using? are you using a v2 registry?

I would suggest you file an issue on https://github.com/docker/distribution - providing the informations listed in https://github.com/dmp42/distribution/blob/docs-rework/CONTRIBUTING.md#reporting-an-issue-properly

**Comment by Maxim-Filimonov** [comment]
@dmp42 I'm not sure which registry version is used by hub.docker.com. That is the registry we push to.

**Comment by dmp42** [comment]
@Maxim-Filimonov Hub runs both versions.
Which one is used depends on docker version (1.6 goes to registry 2, older versions go to registry 1).

Definitely interested in hearing feedback about your experience with it.

There is a lot to explain about the design choices that were made (security and ACL simplicity over pure push performance is a conscious choice, and also emphasis on pull performance over push), and also about what is going to be done to enhance the performance on push now that the ground is laid down for the new protocol.

I would definitely recommend you reach on irc #docker-distribution (@stevvooe or me) if you want to discuss this, or indeed opening an issue on https://github.com/docker/distribution with your use case that should be optimized.

Thanks for taking the time to discuss this.
