### ISSUE TITLE
lxc driver does not populate raw devices in privileged mode

### ISSUE THREAD

**Issue by Lupul** [docker/docker#8218]
When starting a docker container in privileged mode using the native driver (libcontainer)
/dev gets populated with all the disk devices /dev/sd* /dev/md* 
but the same does not happen when using lxc exec driver
(i can create them afterwards using mknod /dev/$device b $x $y or use --device
but that would be very hackishand a PITA to keep in sync when adding or removing partitions)

How can I fix this so that device nodes get created automaticaly ?

ps: container is a tgt iscsi server and I stil use lxc driver because i assign static ip adreses using lxc-conf lxc.network... etc

Thank you
debug info:
1)
```
Linux eu-os03-controller 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
2)
```
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```
3)
```
Containers: 6
Images: 28
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 40
Execution Driver: lxc-1.0.5
Kernel Version: 3.13.0-35-generic
Operating System: Ubuntu 14.04.1 LTS
Debug mode (server): false
Debug mode (client): true
Fds: 10
Goroutines: 10
EventsListeners: 0
Init Path: /usr/bin/docker
WARNING: No swap limit support
```

**Comment by jfrazelle** [comment]
can you try with lxc 1.0.7 and docker latest

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen
