### ISSUE TITLE
docker don't connects to itself no debuging ability.

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#8236]
Result of ps aux
root      1075  0.0  0.0 521208 19996 ?        Sl   18:15   0:00 docker-current -d -H unix:///var/run/docker.sock --dns 172.17.42.1

Docke Sock Permissions
srw-rw----  1 root          0 Sep 25 18:15 docker.sock

result of docker -H unix:///var/run/docker.sock ps
2014/09/25 18:50:59 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?

Now i would wish i could see if docker realy has problems to access that socket? even as root or what happens?

**Comment by jfrazelle** [comment]
@frank-dspeed can you give exact steps to reproduce on the latest version

**Comment by jfrazelle** [comment]
closing as stale I will reopen if you give exact steps to reproduce with the latest version
