### ISSUE TITLE
Proposal: Dockerfile QUESTION and ANSWER verbs

### ISSUE THREAD

**Issue by erikh** [docker/docker#8272]
This proposal would add two verbs: `QUESTION`, for the purposes of issuing
questions to the user, and `ANSWER`, for the purpose of answering existing
questions.

In `docker build` we use several mechanisms to control input and output
including the environment, `ADD` and `COPY`, etc. What we do not have is a way
to get foreign input during `docker build` -- largely because it creates an
inconsistent build.

`QUESTION` solves this by keeping the build consistent outside of the input. This
allows Dockerfile builders to ask a question which may be presented to the user
if there is no `ANSWER` in the Dockerfile for it already. It also enforces the
reliability of the input to keep builds consistent; if there is no answer,
the question is asked before builds can proceed.

`QUESTION`s can live in Dockerfiles or as ONBUILD statements to another
Dockerfile. `QUESTION`s can always be answered by `ANSWER` statements and any
unanswered `QUESTION` is yielded to the builder as a query, expecting their
response.

`QUESTION`s have an associated key and that is used to relate `ANSWER`s, as
well as provide a templating mechanism within the dockerfile. `ANSWER`s can be
used in Dockerfile variable interpolation, but not in the system environment,
making it ideal for secrets or other I/O that should not live in the running
container.

`QUESTION` and `ANSWER` never have any effect on `docker run`.

`docker build` could also have an `--answer` flag which could be used like
`docker run -e` to populate the environment, but just with build answers
instead, ensuring automated runs.

This would require the builder system to have more interactive properties in
the API, and this should be considered when deciding whether or not to accept
this proposal.

#### Basics:

```
FROM busybox
QUESTION TODAY How are you today?
RUN echo ${TODAY}
```

`docker build .` will ask the building user, "How are you today?", prepping it
as an `ANSWER` for the rest of the run.

#### OnBuild Example:

```
FROM busybox
ONBUILD QUESTION TODAY How are you today?
```

`docker build -t questioner .`

```
FROM questioner
ANSWER TODAY Great! Thanks for asking!
RUN echo ${TODAY}
```

Will answer "How are you today?" with "Great! Thanks for asking!" and then echo
it in the `RUN` statement. Nothing will be asked of the user.

#### Real-World Example

```
FROM busybox
QUESTION SSH_AUTH_SOCK Enter the name of your SSH agent auth socket:
RUN SSH_AUTH_SOCK=${SSH_AUTH_SOCK} git clone git@github....
```

This would ask what the SSH auth socket is to the end user building the image.
Then, the auth socket is templated in on a once-run RUN command which clones
the source code of a repository. The auth socket is not persisted in the
environment and no prescience is necessary to build the image.

/cc @tiborvass @aanand @bfirsh @shykes

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
