### ISSUE TITLE
Changes to tip of systemd break libcontainer build

### ISSUE THREAD

**Issue by jmyounker** [docker/docker#8278]
Systemd has changed the interface to their Connection class in the file /Users/jeff/dev/src/github.com/coreos/go-systemd/dbus/methods.go

This in turn breaks libcontainer's call's to theConn.StartTransientUnit in the file
docker/vendor/src/github.com/docker/libcontainer/cgroups/systemd/apply_systemd.go.

The libcontainer calls need to be updated so that they match the new signature.

**Comment by unclejack** [comment]
@crosbymichael Is this still a problem? Can we close this? It really looked like something you'd have to take a look at before closing.

**Comment by crosbymichael** [comment]
This has been resolved and the go-systemd dep is vendored to the specific commit/tag that we use.

**Comment by jmyounker** [comment]
The problem was resolved within a few days.  I wasn’t aware the ticket was still opened.

-jeff
