### ISSUE TITLE
Proposal: Support HTTP basic auth in the docker client

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#8283]
Some people (like myself) guard their Docker instance behind a HTTP server with proxy pass and have basic HTTP authentication (username/password) on it.

Today, docker client does not support an authentication like this:

```sh
$ export DOCKER_HOST=tcp://username:pass@domain.com:port
$ docker info
Invalid bind address format: username:pass@domain.com:port
```

However it works perfectly with remote API clients which support basic auth (like [Docker.DotNet](https://github.com/ahmetalpbalkan/Docker.DotNet)).
This can be easily fixed by making use of [url.Userinfo](http://golang.org/pkg/net/url/#Userinfo) and accepting this pattern as well. HTTP client for Remote API should already be making use of this username/password in the URL as it is the Go net/http package.

I thought of passing username/password to `docker` client as arguments, however that's more tedious both to user and the `-h` output will get bigger for the common case. Credentials can just happen in either DOCKER_HOST env var (like above) or `-H` parameter.

I'm planning to send out a PR soon if no objections?

**Comment by ianmiell** [comment]
FWIW a use case:
I'm working on a repo here: https://github.com/ianmiell/docker-authenticate
which dockerizes http auth access. 
It seems a neat way of temporarily giving some level of trusted access to your docker daemon to other users who have network access without restarting or messing with your docker daemon directly.

**Comment by ahmetalpbalkan** [comment]
Probably not so much needed. Closing.
