### ISSUE TITLE
COPY and ADD do not support filenames with whitespace.

### ISSUE THREAD

**Issue by erikh** [docker/docker#8318]
This is because we use a whitespace-delimited parser there. We should probably support the JSON argument representation here. I don't think this will be a complicated code change.

/cc @shykes

**Comment by fommil** [comment]
damn, I just hit this in docker 1.3.3 (Debian Jessie). Any workarounds?

**Comment by duglin** [comment]
Kind of a hack but try using a wildcard in place of the spaces
-Doug

**Comment by fommil** [comment]
I was copying images into the `VirtualBox VMs` folder, I just changed the setting for which directory the images are stored in, but nice hack that I'll keep in mind.

**Comment by gramster** [comment]
Wildcard doesn't work if you're talking about the target. A directory will get created with wildcard characters literally in its name.

**Comment by dmlf** [comment]
Same problem here

Workaround :

**Prepare a tarball** 

`tar cvf my.whitespace.files.bundle.tar my\ file\ with\ whitespaces`
or
`tar cvf my.whitespace.files.bundle.tar my\ folder\ tree/
`

**Adapt Dockerfile**

```
[...]
WORKDIR /workdir
COPY  my.whitespace.files.bundle.tar  /workdir
RUN tar xf  my.whitespace.files.bundle.tar  
[...]
```

**Comment by ChristopherLClark** [comment]
Oh god. What do I need to do? It's just a file with a space called `First Run`

**Comment by Flo0806** [comment]
Hello!

Yes, it is fixed: [Here](https://docs.docker.com/engine/reference/builder/#copy) is the link to the official docs.

![image](https://user-images.githubusercontent.com/10813063/206791648-90ef648c-03d3-4493-903f-d562bdcc9b80.png)

So you see they have updated the `COPY` command. With the brackets you can use filenames with whitespaces.

Greetings!
