### ISSUE TITLE
Docker progress bar should be disabled when run without a tty

### ISSUE THREAD

**Issue by coryking** [docker/docker#8342]
Currently, the progress bar looks all kinds of bad when run inside something like jenkins.  Hundreds of lines of "Downloading".  When run without a tty, docker should not show the progress bar.  Perhaps there should be a way to disable it from the command line as well.

As an example, here is how wget does it:
```
 --progress=type
           Select the type of the progress indicator you wish to use.  Legal indicators are "dot" and "bar".

           The "bar" indicator is used by default.  It draws an ASCII progress bar graphics (a.k.a "thermometer" display) indicating the status of retrieval.  If the output is not a TTY, the
           "dot" bar will be used by default.
```

This issue came out of the following: https://github.com/docker/docker/issues/4022

**Comment by jfrazelle** [comment]
@dqminh is right this is fixed

**Comment by evictor** [comment]
Any plans for implementing dot progress? That would be great for non-TTY...

**Comment by sobi3ch** [comment]
Bump

**Comment by thaJeztah** [comment]
@sobi3ch see https://github.com/docker/cli/pull/882 (and https://github.com/moby/moby/issues/13588)
