### ISSUE TITLE
btrfs storage runs out of space

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#8354]
Hi,

it looks like running docker on btrfs for some time causes it to run out of space, even with continues cleanup and a low number of images and containers.
I'm not sure if this is a bug or just a matter of design but there need to be documentation how to handle that.

**Comment by unclejack** [comment]
It doesn't seem to be an issue any more with recent kernels. Using a recent kernel (newer than 3.17) should avoid such issues. Cleaning up unused images is also a very good idea.

I'll close this now since it doesn't seem to be a problem with recent kernels.
