### ISSUE TITLE
Make it possible to disable userland proxy

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#8356]
Hi,

I think we don't need the userland proxy. Please correct me if I'm wrong.
I assume the userproxy is there because someone assumed that it's not possible to redirect traffic on the loopback interface to the container IPs on the bridge. I don't think that's the case and we basically just need to set route_localnet:

    route_localnet - BOOLEAN
	Do not consider loopback addresses as martian source or destination
	while routing. This enables the use of 127/8 for local routing purposes.
	default FALSE

Will verify that as soon as I find time.

**Comment by gdm85** [comment]
I have narrowed down docker-proxy to be one of the (if not the single) largest cause of non-determinism for my multi-container deployments. I am all for this.

**Comment by jfrazelle** [comment]
Ya we can't do it though because hairpin nat and 2.6.x kernels :( it was sooooo close

**Comment by discordianfish** [comment]
@jfrazelle I thought hairpin nat was added. What is the problem with 2.6.x kernels? We don't even support 2.6 anymore: https://docs.docker.com/installation/binaries/#check-kernel-dependencies
And even if we need it for some older kernels, can't we just introduce a global flag to disable the proxy?

**Comment by phemmer** [comment]
@discordianfish See #9269 and #9134

**Comment by mattheworiordan** [comment]
:+1: for allowing hairpin NAT on kernels that support it.  I appreciate lowest common denominator is often necessary, but currently we have lots of traffic from one container going to another through the public interface 0.0.0.0 and this unnecessarily going through the Docker proxy.

**Comment by RX14** [comment]
Do we really need the proxy to be using 11MB of ram... **per port**!

**Comment by unclejack** [comment]
The user land proxy is going to be removed. Since removing the user land proxy will fix this problem, I'm going to close this in favor of #11185 because the solution to #11185 is the complete removal of the user land proxy.
