### ISSUE TITLE
UDP packets from the docker instance get dropped for no good reason

### ISSUE THREAD

**Issue by pooya** [docker/docker#8357]
On the host machine I run a udp server:
$ nc -u -l 5141

And inside the instance, I try to connect to the server:
#nc -u host 5141 

The first message sent from the client (inside the instance) to the server is received and printed. However, the second one does not make it through and the nc session terminates:

bash-4.2# nc -u host 5141                                                                                         
hi
hi
Ncat: Connection refused.
bash-4.2# 

uname -a:
Linux host 3.10.0-123.6.3.el7.x86_64 #1 SMP Wed Aug 6 21:12:36 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

docker version:
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3
Git commit (client): fa7b24f/1.2.0
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3
Git commit (server): fa7b24f/1.2.0

docker info:
Containers: 2
Images: 260
Storage Driver: devicemapper
 Pool Name: docker-8:3-1074704475-pool
 Pool Blocksize: 64 Kb
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 7272.2 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 17.5 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.6.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Debug mode (server): false
Debug mode (client): true
Fds: 32
Goroutines: 63
EventsListeners: 0
Init SHA1: e58f67ff218af924828651cb8c824545342040d3
Init Path: /usr/libexec/docker/dockerinit

**Comment by fcofdez** [comment]
I'm having this issue as well.

Base image: 
ubuntu:14.04

**Comment by jfrazelle** [comment]
I cannot reproduce on latest docker but if you can please ping me on this issue with the docker info, docker info, uname -a, and how you reproduce

**Comment by lylepratt** [comment]
This issue is related to the MTU size and that is probably why you have not been able to reproduce it. We have been seeing this A LOT on Google Compute Engine, which has an abnormal MTU size limit (1460 bytes). This is definitely a legitimate issue! Related bug: https://github.com/docker/docker/issues/15618

**Comment by thaJeztah** [comment]
@lylepratt does setting the [`--mtu=<size>` option](https://docs.docker.com/articles/networking/#docker0) on the daemon help in your case?

**Comment by jhockel** [comment]
Hi I realize this was a while ago but I am looking at this same issue now. 

I am able to send/receive multiple packets if i set the `host` ip to my host's ip in the docker network, however I run into the same issue of only receiving a single packet if i use my host ip of 192.168.--.---. 

Any idea why this would be the case?
