### ISSUE TITLE
Feature Request: Pull down all images from organization

### ISSUE THREAD

**Issue by lynchc** [docker/docker#8361]
I created an organization on docker hub and I would like to be able to pull all images from that org.

docker pull [org name] just returns a 404

**Comment by dudleycodes** [comment]
Modified @gaastonsr's solution to work work with images that contain a "-" and "_" in their name. Also pulls all tagged images (not just `latest`).
```
docker search ORGNAME | grep -o -E '^[[:alnum:]]+/[^[:blank:]]+' | xargs -L 1 -P 1 docker pull -a
```
