### ISSUE TITLE
docker pull "another client is already pulling" message should report progress

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#8385]
`docker pull` will print out messages if another client is already pulling:
> Repository registry.mesos-vpcqa.otenv.com/opentable-singularity already being pulled by another client. Waiting.

It is frustrating to wait for an indeterminate period of time, not knowing if 'another client' is actually pulling, how much time / transfer is left, or if something is just stuck.  The UI would be much better if the `docker pull` would then report the same progress information as is printed out by the original client, so that you can monitor it.

**Comment by jmreicha** [comment]
+1

**Comment by tommasop** [comment]
+1

**Comment by tulpar008** [comment]
:+1: +1

**Comment by kylepragerattensity** [comment]
+1 Experiencing this right now.

**Comment by wilk** [comment]
+1 right now

**Comment by AntoineFinkelstein** [comment]
:+1:

**Comment by hbin** [comment]
Looking forward to it

**Comment by pacuna** [comment]
+1

**Comment by cpuguy83** [comment]
See an implementation of this in #10683

**Comment by samsabed** [comment]
@cpuguy83 , @dmcgowan what are your thoughts on PR #12874

**Comment by termie** [comment]
+1

**Comment by mies** [comment]
+1 :+1:

**Comment by lindseybateman** [comment]
+1

**Comment by ikudriavtsev** [comment]
+1

**Comment by smarigowda** [comment]
I have the same issue

**Comment by hepin1989** [comment]
+1

**Comment by dragonfax** [comment]
+1

**Comment by gaomingyang** [comment]
+1

**Comment by thaihau** [comment]
+1

**Comment by andrefreitas** [comment]
Same issue here.

**Comment by gen4sp** [comment]
same

**Comment by werevolff** [comment]
+1

**Comment by joegoggins** [comment]
+1

**Comment by thaJeztah** [comment]
To all people "+1"-ing here; this has been implemented, see https://github.com/docker/docker/pull/15489 and will be in the next (1.9) release

**Comment by kiscod** [comment]
+1

**Comment by thaJeztah** [comment]
@kiscod did you actually read my comment above?

I'm locking the conversation on this issue
