### ISSUE TITLE
docker commit randomly fails with Error mounting 'X' on 'Y': no such file or directory

### ISSUE THREAD

**Issue by iserko** [docker/docker#8396]
I have had issues committing an image using Docker with devicemapper on Ubuntu 14.04.
It fails quite randomly, so I assume it must be a race condition. Similar to #4036 ?

The following is the result of me running my test script 4 times (2 successes and 2 failures). The test script is after the results.

    % ./test_docker.sh
    + set -e
    + docker rm test-container
    test-container
    + docker run --name test-container ubuntu:trusty touch /testfile
    + docker commit test-container someotherrepo/test:1234
    2014/10/04 23:15:41 Error response from daemon: Error getting container 483a584c3849c7f719f30d9900860c9def0a3ee7d942d9aa99dc2bc06a7ce474 from driver devicemapper: Error mounting '/dev/mapper/docker-9:0-100665344-483a584c3849c7f719f30    d9900860c9def0a3ee7d942d9aa99dc2bc06a7ce474' on '/mnt/md0/docker/devicemapper/mnt/483a584c3849c7f719f30d9900860c9def0a3ee7d942d9aa99dc2bc06a7ce474': no such file or directory
    % ./test_docker.sh
    + set -e
    + docker rm test-container
    test-container
    + docker run --name test-container ubuntu:trusty touch /testfile
    + docker commit test-container someotherrepo/test:1234
    330d98020fe97cc1e1b221495dc318134a0df507cb34c727bd751971d74e6bcc
    % ./test_docker.sh
    + set -e
    + docker rm test-container
    test-container
    + docker run --name test-container ubuntu:trusty touch /testfile
    + docker commit test-container someotherrepo/test:1234
    fbbc8e6a10f046df6e356f3f6e0de4e6d9410005f1a7447e8d9ae92eac27ad6b
    % ./test_docker.sh
    + set -e
    + docker rm test-container
    test-container
    + docker run --name test-container ubuntu:trusty touch /testfile
    + docker commit test-container someotherrepo/test:1234
    2014/10/04 23:16:09 Error response from daemon: Error getting container e2ef43868a878626db97d7d017df0414fcca44d16959b5499bbfe129dd70eef7 from driver devicemapper: Error mounting '/dev/mapper/docker-9:0-100665344-e2ef43868a878626db97d7d017df0414fcca44d16959b5499bbfe129dd70eef7' on '/mnt/md0/docker/devicemapper/mnt/e2ef43868a878626db97d7d017df0414fcca44d16959b5499bbfe129dd70eef7': no such file or directory

test_docker.sh

    #!/bin/sh
    set -x
    set -e
    docker rm test-container
    docker run --name test-container ubuntu:trusty touch /testfile
    docker commit test-container someotherrepo/test:1234

uname -a

    Linux hostname 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

docker version

    Client version: 1.2.0
    Client API version: 1.14
    Go version (client): go1.3.1
    Git commit (client): fa7b24f
    OS/Arch (client): linux/amd64
    Server version: 1.2.0
    Server API version: 1.14
    Go version (server): go1.3.1
    Git commit (server): fa7b24f

docker -D info

    Containers: 11
    Images: 160
    Storage Driver: devicemapper
     Pool Name: docker-9:0-100665344-pool
     Pool Blocksize: 64 Kb
     Data file: /mnt/md0/docker/devicemapper/devicemapper/data
     Metadata file: /mnt/md0/docker/devicemapper/devicemapper/metadata
     Data Space Used: 9382.6 Mb
     Data Space Total: 194556.0 Mb
     Metadata Space Used: 18.0 Mb
     Metadata Space Total: 10236.0 Mb
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-36-generic
    Operating System: Ubuntu 14.04.1 LTS
    Debug mode (server): false
    Debug mode (client): true
    Fds: 62
    Goroutines: 43
    EventsListeners: 0
    Init Path: /usr/bin/docker
    WARNING: No swap limit support

docker running with following options:

    /usr/bin/docker -d -H unix:///var/run/docker.sock -H tcp://0.0.0.0:2375 \
        --storage-opt dm.datadev=/dev/direct-lvm/data \
        --storage-opt dm.metadatadev=/dev/direct-lvm/metadata \
        --storage-opt dm.fs=xfs

Also `/mnt/md0` (where Docker is installed to) is XFS

**Comment by vbatts** [comment]
closing this as a duplicate. See my comment https://github.com/docker/docker/issues/4036#issuecomment-69244813
