### ISSUE TITLE
Feature request: Push while building

### ISSUE THREAD

**Issue by jakajancar** [docker/docker#8433]
It would be nice if layers of a build could begin being pushed while the image is still building.

**Comment by cpuguy83** [comment]
But what if the build fails?

**Comment by MHBauer** [comment]
Similar to #17982

**Comment by thaJeztah** [comment]
Agreed, I'm going to close this issue in favor of https://github.com/docker/docker/issues/17982, which has more activity at the moment, please continue the discussion there.

Thanks for opening this feature request, @jakajancar :+1: (and thanks for spotting the duplicate @MHBauer )
