### ISSUE TITLE
Inconsistent exit status when container is killed

### ISSUE THREAD

**Issue by dkatona** [docker/docker#8442]
I've come across a weird behaviour regarding exit status when container is killed after migrating from docker 0.9 to 1.2. We are using lxc-driver on kernel 2.6.32-431.29.2.el6.x86_64
* docker 0.9 + lxc-0.9.0-2 - exit status **137**
* docker 1.2 + lxc-1.0.5 + exec-driver=lxc - exit status **0** (same as success)
* docker 1.2 + lxc-1.0.5 + exec-driver=native - exit status **-1**

I think it should be consistent through all exec drivers at least in one docker version, now I am not able to distinguish between successful and killed container with lxc exec driver.

**Comment by jfrazelle** [comment]
cannot reproduce with lxc 1.0.7 and latest verison of docker
