### ISSUE TITLE
Proposal: Support templates for application config

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#8446]
Some applications support calling out to the underlying OS to grab details for configuration or programatically building, however many do not support this (within their configurations).
One of the reasons people use Chef/Puppet/Salt, etc. is for templating configurations, something that Docker makes a little bit harder to do.

## Propsoal
Support template drivers, to begin with just go-template since that is easy and would not require any extra host dependencies.
In the future people could create drivers for other templating engines. 
Templates get processed at runtime.

### New `docker run` flag: `--template`
Semantics:
`docker run --template /path/to/template`
Using this mode, `/path/to/template` would be a template file and also the actual path of where the final config would be stored.  This mode would only process the template the first time since it will be replaced by the output of that template.

`docker run --template /path/to/template:/path/to/config`
In this mode, a template file is stored in a separate location from the actual config.  The config would be re-built at each start invocation.

To use a template stored on the host:
`docker run -v /path/to/template:/path/in/container --template /path/in/container:/path/to/config`

### New Dockerfile command: TEMPLATE
```Dockerfile
FROM nginx
ADD nginx.conf.templ /tmp/
TEMPLATE /tmp/nginx.conf.templ /etc/nginx/nginx.conf
```
This is a no-op command used only for runtime.
This would have the same semantics as `--template` from `docker run` where the 2nd argument is optional.

**Comment by pghalliday** [comment]
If i understand the use case correctly, I currently achieve this using environment variables and an `ENTRYPOINT` script that generates server configuration files using `sed`. It seems a bit brute force though and I think gets run everytime `docker run` is called (which is usually only once unless I'm debugging). Also it should be noted that the templating is running on the container and not the host.

My specific use case was for a JIRA server container. Here I wanted to specify the `proxyPort` and `proxyName` configurations inside the JIRA `server.xml` but these parameters depend on the environment and configuration of an nginx proxy `container`. This were details I wanted to plug together using a `fig.yml` file

**Comment by mickep76** [comment]
I think the same idea would be very useful during "docker build", if you could template files based on either input like YAML/JSON/TOML or ENV variables. There are many use-cases where you build similar images with just configuration differences, especially when you want **immutable** configuration for specific deployments.

Also this would be very useful inside the Dockerfile itself to support Go Text Template.

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by marquesmps** [comment]
I've used confd in the past to create application config files, you can read them from different backends, like redis, environment variables, etc: https://github.com/kelseyhightower/confd
It uses go templates, could be useful to create the config files templates, and then store them in docker configs.

**Comment by thaJeztah** [comment]
For substituting environment variables during build, [`envsubst(1)`](https://linux.die.net/man/1/envsubst) would probably work

@marquesmps if you want to use templated `docker config` and `docker secret`s, have a look at https://github.com/moby/moby/pull/33702, which is supported in current versions of Docker
