### ISSUE TITLE
RestartPolicy parameter for "containers/create" does not appear to work

### ISSUE THREAD

**Issue by jgarverick** [docker/docker#8458]
Recently I've been working on the Docker.DotNet project, which is a .NET wrapper for the Docker Remote API.  I have been trying to get the ```containers/create``` POST to work with the ```RestartPolicy``` object included in the payload.  Upon initial glance, it seems like the ```RestartPolicy``` object needs to be a property of the ```Config```.  The explanation in the API documentation (right below the sample request) implies that it should be a separate object from the ```Config``` object.  When the ```containers/<name>/json``` method is called on a container after using the example structure to create the container, the ```HostConfig``` is where the ```RestartPolicy``` object appears, and anything that I included in the create request does not appear in the ```HostConfig```.  Is there a more complex structure that should be passed when calling ```containers/create```, like:
```
{
  "Config": {
    "Image": "python:latest"
    ...
   },
   "HostConfig": {
   "RestartPolicy":{
       "Name": "on-failure",
       "MaximumRetryCount": 3
    } 
   }
}
```
Or, is the example structure listed on the Remote API site correct and the RestartPolicy object simply isn't used yet?  Any clarification you could provide would be appreciated.  Thanks!

**Comment by duglin** [comment]
@jgarverick Is this still an issue or can we close it?

**Comment by jgarverick** [comment]
I'm sorry!  This is all set.  I'm closing it out.

**Comment by oliver006** [comment]
The docs regarding this are still a mess.

https://docs.docker.com/reference/api/docker_remote_api_v1.16/#create-a-container 
says that I can provide RestartPolicy but it's never picked up once I start the container.

https://docs.docker.com/reference/api/docker_remote_api_v1.16/#start-a-container 
doesn't say anything about being able to provide start parameters but if I provide RestartPolicy it's applied to the container. However, the rest of my parameters that I provided during `create` (like port mappings) are discarded. 
Want me to open a new ticket for that or re-open this one?

**Comment by cpuguy83** [comment]
@oliver006 How are you providing the RestartPolicy on create?

FYI, the docker CLI uses this exact API.

**Comment by oliver006** [comment]
@cpuguy83 ha, my bad, I had RestartPolicy at the top-level, not inside HostConfig. It works as expected, sorry about the confusion.
