### ISSUE TITLE
Images are being cached even if there are changes

### ISSUE THREAD

**Issue by pelcasandra** [docker/docker#8477]
I have on Docker an automatic build for an image based on ubuntu with some custom configurations to re-use then as base image on other specific Dockerfiles for particular projects. This works okay. 

I made a change to it, committed to github which then started and did the automatic build on Docker. 

From one of these other projects, I'm calling at the beginning of the Dockerfile `FROM myuser/myimage` but its not getting the last image with the changes, but rather it keeps caching the old one. 

Should this be automatically?

**Comment by jfrazelle** [comment]
closing, @pelcasandra if you provide the requested information and a way to reproduce on the latest version of docker, i am happy to reopen
