### ISSUE TITLE
Allow Dockerfile to specify stop signal

### ISSUE THREAD

**Issue by SamSaffron** [docker/docker#8485]
runit blocks all signals except for INT, CHILD and CONT https://github.com/pilcrow/runit/blob/master/src/runit.c#L68 ( http://smarden.org/runit/runit.8.html ) 

docker stop is only capable of sending a SIGTERM. 

So there is no way to shut down cleanly a docker image that booted using runit.

It would be nice if you could specify custom "stop" signal which is more appropriate. 

For example for a postgres container a fast shutdown using INT is probably better than a slow shutdown that could be interrupted by a SIGKILL. 

When starting a container you should be allowed to specify which signal "stop" should use.

So:

```
docker run --stop-signal INT -n test ubuntu /bin/bash
docker stop test  # sends a SIGINT to process #1 in the contaner
```

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.

**Comment by icecrime** [comment]
Done in #15307: will ship in Docker 1.9.0.
