### ISSUE TITLE
dns resolve fails with incorrect SELinux context

### ISSUE THREAD

**Issue by porjo** [docker/docker#8499]
Using docker 1.2.0 (Fedora 20 RPM)

Starting docker with non-standard path to data e.g.

```
/usr/bin/docker -d -H fd:// --selinux-enabled -g /data/docker
```

Everything seems fine except DNS lookups don't work e.g.

```sh
$ docker run -ti ubuntu /bin/bash
root@5c9838b4a5b3:/# ping www.google.com
ping: unknown host www.google.com
root@5c9838b4a5b3:/# ls -al /etc/ | grep resolv.conf
ls: cannot access /etc/hostname: Permission denied
ls: cannot access /etc/hosts: Permission denied
ls: cannot access /etc/resolv.conf: Permission denied
-??????????  ? ?    ?          ?            ? resolv.conf
```

If I go back to using `/var/lib/docker` DNS resolution works as expect.

==

Output from `docker info`:

```
$ docker info
Containers: 1
Images: 10
Storage Driver: devicemapper
 Pool Name: docker-253:4-3538947-pool
 Pool Blocksize: 64 Kb
 Data file: /data/docker/devicemapper/devicemapper/data
 Metadata file: /data/docker/devicemapper/devicemapper/metadata
 Data Space Used: 313.0 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 0.9 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.16.2-201.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
```

Output from `docker inspect 5c9838b4a5b3`

http://pastebin.com/tcVCZ9Fv

**Comment by jfrazelle** [comment]
ping @rhatdan

also @porjo are you able to reproduce on the latest version of docker

**Comment by rhatdan** [comment]
These should all be fixed in docker-1.4 or greater.  Probably fixed in docker-1.3

**Comment by rhatdan** [comment]
Docker does not know anything about the "correct" selinux label.  If you move the content of any confined processes data you have to tell SELinux about it.

The correct procedure should be
```
mkdir /data/docker
semanage fcontext -a -t docker_var_lib_t '/data/docker(/.*)?'
restorcon -R -f /data/docker
```

Or even better
```
mkdir /data/docker
semanage fcontext -a -e /var/lib/docker /data/docker
restorcon -R -f /data/docker
```
Finally why didn't you just mount the disk for /data on top of  /var and then have normal labeling.

**Comment by porjo** [comment]
> why didn't you just mount the disk for /data on top of /var then have normal labeling.

...says the SELinux expert :wink: 

I've confirmed using Docker 1.5.0 that this issue no longer occurs. Thanks all.

**Comment by jfrazelle** [comment]
woohooo!
