### ISSUE TITLE
docker inspect ambigious

### ISSUE THREAD

**Issue by docbill** [docker/docker#8504]
I'm having problems with the docker inspect command, in that it has undefined behavior when a docker image and a docker container has have the same name.   In my particular case I have both a container and an image name staging-prod-db.   When I run "docker inspect staging-prod-db".  Sometimes it reports on the image, and other times it reports on the container.   The results seem to vary randomly.   If I'm running it manually I can avoid problems by just using the container or image id respectively.   But it is making it extremely difficult to write scripts that work consistently.

I would propose for backwards compatibility leave the existing behavoir as is, but add a command line parameter that can specify if it is an image or container being inspected.

**Comment by jfrazelle** [comment]
@docbill have you tried on the latest version of docker is this still an issue

**Comment by termie** [comment]
+1

**Comment by cpuguy83** [comment]
`docker inspect` now inclues a `--type` option to specify either an image or a container.
Closing.
