### ISSUE TITLE
in container, subdirectory has 700 mode but owner cannot read it

### ISSUE THREAD

**Issue by billsmith** [docker/docker#8514]
(Summary) I have a Dockerfile the creates a Linux user ("buguser") and creates a subdirectory under the user's home directory.  The entrypoint for the container is a script. It runs as root, but runs a command as buguser.  The command gets a permission error when it tries to read the subdirectory I mentioned above.  I have not been able to reproduce this outside of a container.

Here is the Dockerfile:

    FROM debian:wheezy
    RUN apt-get update
    RUN useradd -d /home/buguser -m buguser
    RUN mkdir /home/buguser/dotssh
    RUN touch /home/buguser/dotssh/a_file
    RUN chmod 700 /home/buguser/dotssh
    ADD run.sh /home/buguser/run.sh
    ENTRYPOINT ["/home/buguser/run.sh"]

and here is the script:

    #!/bin/bash -vx
    chown -R buguser:buguser /home/buguser
    find /home/buguser -ls
    find /home/buguser|xargs ls -nd
    su buguser -c "id;ls -l /home/buguser/dotssh"

When I run the script, I get this:

    chown -R buguser:buguser /home/buguser
    + chown -R buguser:buguser /home/buguser
    find /home/buguser -ls
    + find /home/buguser -ls
        21    4 drwxr-xr-x   6 buguser  buguser      4096 Oct 11 19:59 /home/buguser
        22    4 -rwxrwxr-x   1 buguser  buguser       161 Oct 11 19:55 /home/buguser/run.sh
        57    4 drwx------   2 buguser  buguser      4096 Oct 11 19:59 /home/buguser/dotssh
        61    0 -rw-r--r--   1 buguser  buguser         0 Oct 11 19:58 /home/buguser/dotssh/a_file
        58    4 -rw-r--r--   1 buguser  buguser       220 Dec 30  2012 /home/buguser/.bash_logout
        59    4 -rw-r--r--   1 buguser  buguser      3392 Dec 30  2012 /home/buguser/.bashrc
        60    4 -rw-r--r--   1 buguser  buguser       675 Dec 30  2012 /home/buguser/.profile
    find /home/buguser|xargs ls -nd
    + find /home/buguser
    + xargs ls -nd
    drwxr-xr-x 6 1000 1000 4096 Oct 11 19:59 /home/buguser
    -rw-r--r-- 1 1000 1000  220 Dec 30  2012 /home/buguser/.bash_logout
    -rw-r--r-- 1 1000 1000 3392 Dec 30  2012 /home/buguser/.bashrc
    -rw-r--r-- 1 1000 1000  675 Dec 30  2012 /home/buguser/.profile
    drwx------ 2 1000 1000 4096 Oct 11 19:59 /home/buguser/dotssh
    -rw-r--r-- 1 1000 1000    0 Oct 11 19:58 /home/buguser/dotssh/a_file
    -rwxrwxr-x 1 1000 1000  161 Oct 11 19:55 /home/buguser/run.sh
    su buguser -c "id;ls -l /home/buguser/dotssh"
    + su buguser -c 'id;ls -l /home/buguser/dotssh'
    uid=1000(buguser) gid=1000(buguser) groups=1000(buguser)
    ls: cannot open directory /home/buguser/dotssh: Permission denied

Docker version 1.2
Kernel version 3.13.0-37-generic

**Comment by jfrazelle** [comment]
Seems like this has been resolved, closing

**Comment by estesp** [comment]
Also, in case people end up here and want to know more--there is also a PR underway to add the `dirperm1` option to the AUFS driver to workaround this old quirk in the AUFS layer+permissions logic; see #10390 for more info.
