### ISSUE TITLE
forwarding traffic to wrong backend on fresh daemon

### ISSUE THREAD

**Issue by zyndiecate** [docker/docker#8537]
Hello fellows. Recently I have discovered weird behaviour of traffic forwarding between containers as described on [serverfault.com](http://serverfault.com/questions/635078/netcat-closes-established-connection-between-docker-containers). 

I found a bug were I have a freshly reloaded/started docker daemon and 3 containers. They receive the first available IP-Adresses of the docker0 bridge, started with x.x.x.2, followed by x.x.x.3 and x.x.x.4. Here is the exact setup.

```bash
# start container one
$ docker run --rm -ti -p 80 --name one ubuntu /bin/bash
root@1024a82726cc:/# hostname -i
172.17.0.2

# start container two, bound to the hosts ip, linked with container one
$ docker run --rm --link one:one -p 192.168.33.10::80 -ti --name two ubuntu /bin/bash
root@e8ec8fc18e08:/# hostname -i
172.17.0.3

# start container three
$ docker run --rm -ti -p 80 --name three ubuntu /bin/bash
root@3750870e8c59:/# hostname -i
172.17.0.4
```

Now when I try to communicate from container three to container two, I see the following error in the daemon log. The weird thing here is, the docker daemon tries to proxy the request to x.x.x.2, but it should try to proxy to x.x.x.3!

```bash
# container three tries to request container two, but connection will be closed immediately 
$ nc -v 192.168.33.10 49153
Connection to 192.168.33.10 49153 port [tcp/*] succeeded!
$

# docker daemon log
2014/10/13 13:23:29 Can't forward traffic to backend tcp/x.x.x.2:80: dial tcp x.x.x.2:80: connection refused
```

I figured out that has something to do with the first container started. So my workaround is as followed. If I have the same setup, but start AND stop/remove a container, and the containers IP-Adresses in my setup starts with x.x.x.3, followed by x.x.x.4 and x.x.x.5, the traffic forwarding works as expected. 

I have verified that issue on coreos as well as on ubuntu using `Docker version 1.2.0, build fa7b24f`. `Docker version 1.1.0, build 79812e3` does NOT have that bug!

Some more environment information of the ubuntu host
```bash
# docker info
$ docker info
Containers: 4
Images: 567
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 581
Execution Driver: native-0.2
Kernel Version: 3.2.0-23-generic
Operating System: <unknown>
Username: zyndiecate
Registry: [https://index.docker.io/v1/]

# docker version
$ docker -v
Docker version 1.2.0, build fa7b24f

# host information
$ uname -a
Linux precise64 3.2.0-23-generic #36-Ubuntu SMP Tue Apr 10 20:39:51 UTC 2012 x86_64 x86_64 x86_64 GNU/Linux
```

Some more environment information of the coreos host
```bash
# docker info
$ docker info
Containers: 3
Images: 10
Storage Driver: btrfs
Execution Driver: native-0.2
Kernel Version: 3.16.2+
Operating System: CoreOS 459.0.0

# docker version
$ docker -v
Docker version 1.2.0, build fa7b24f

# host information
$ uname -a
Linux core-01 3.16.2+ #2 SMP Fri Oct 3 07:45:37 UTC 2014 x86_64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz GenuineIntel GNU/Linux

# coreos version
$ cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=459.0.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 459.0.0"
```

**Comment by jfrazelle** [comment]
@zyndiecate can you try with the latest version of docker

**Comment by zyndiecate** [comment]
Cannot reproduce anymore, but I see things like this in docker daemon log

```
Feb 26 18:35:30 core-01 dockerd[1612]: [0e450244.allocate_port(9226f727ee9fb21b5ac85a21517e8f2c1e485fd146dc74deb2617b123768bc62)] Failed to allocate and map port: Error starting userland proxy: listen tcp 172.17.8.101:49153: bind: address already in use, retry: 1
```

env info
```bash
# docker version
core@core-01 ~ $ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.3.3
Git commit (client): a8a31ef-dirty
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.3.3
Git commit (server): a8a31ef-dirty

# coreos version
core@core-01 ~ $ cat /etc/lsb-release
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=604.0.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 604.0.0"

**Comment by jfrazelle** [comment]
then I think we can close this and defer to https://github.com/docker/docker/issues/10096

**Comment by jfrazelle** [comment]
thanks for checking in on it, seriously saves us so much time :D
