### ISSUE TITLE
Proposal: Support custom cgroups

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#8551]
Containers are mostly the combination of capabilities, namespaces, and cgroups.  Docker already has custom capabilities support with `--cap-add` and `--cap-drop`.  Custom namespace support is halfway there already with `--net=*` and `--ipc=*` is being worked on.  The last piece of the puzzle is to be able to control is cgroups.

I propose that the cgroup paths be added to the HostConfig such that on start custom cgroup paths can optionally be used instead of the cgroups that Docker would setup.  This would allow component outside of docker to control, create, and manage the cgroups but then the Docker container would just join them.

One could find many use cases for this I assume, but initially this feature can be used to better tie together cgroups managed by systemd.  The background of this is rooted in a hack (https://github.com/ibuildthecloud/systemd-docker) that I've put together to better managed Docker under systemd.  `systemd-docker` does various things that are useful that better integrates Docker with systemd and most of it should probably stay as a project outside of Docker.  One critical piece that makes `systemd-docker` work today is that it moves the running processes from one cgroup to the service's cgroup.  This is what makes it a hack and also not 100% reliable.  If Docker could just support the ability to use a custom cgroup, then `systemd-docker` could become a production worthy stop gap solution until a superior integration between systemd and docker existed natively.

**Comment by thockin** [comment]
+1

**Comment by rjnagal** [comment]
Having a way to expose the parent cgroup to use to create new cgroup under would go a long way in solving the issues @bgrant0607 pointed out. If the container cgroups are not tied directly to where docker daemon runs, it would help a lot in better protecting critical system daemons. libcontainer already accepts parent as a parameter. I think the actual work required to make this happen would be minimal.

**Comment by vishh** [comment]
+1. Ping @crosbymichael

**Comment by crosbymichael** [comment]
What do you think the user facing API should look like? API and flags for solving your issues?

**Comment by vishh** [comment]
@crosbymichael: For many of the use cases mentioned above, adding a `--parent_cgroup=/<cgroup_path>` flag to `docker run` is what is needed. With this option set, docker would  create container cgroups under the hierarchy mentioned in `--parent_cgroup`.
To provide differentiated quality of service, this option would let users group low priority containers into a bucket and cap the total amount of resources the low priority containers can consume. This option can be used to place resource restrictions across a [Pod](https://github.com/docker/docker/issues/8781). In the case of systemd, the service cgroup hierarchy can be used to group docker containers into a logical systemd cgroup.

**Comment by crosbymichael** [comment]
And that's it? Nothing else required?

**Comment by thockin** [comment]
I think that is pretty much right.  What else were tiu expecting to see?

**Comment by nelcy** [comment]
+1

**Comment by timothysc** [comment]
+1, this simplifies process tracking for cluster managers.

**Comment by vishh** [comment]
@crosbymichael: We will need another flag to alter the `oom_score_adj` on containers to offer differentiated QOS.

**Comment by bgrant0607** [comment]
Let's keep the `oom_score_adj` issue separate -- please file a separate issue, since I don't see one. The cgroup parent alone will solve several problems for us.

**Comment by tnachen** [comment]
+1 as well.
I think one nice to have for all systems integrating with docker, is that the cgroup path for a container is also available via docker inspect, therefore it's at a set place to look up.

**Comment by thockin** [comment]
FWIW, we should mention that this will remove the ability to examine the
/docker cgroup and see all containers.  I'm OK with that.

**Comment by vishh** [comment]
@crosbymichael: Can we get a +1 for this feature? I can send out a PR soon. This is an important feature that will help improve system reliability a lot for kubernetes.

**Comment by crosbymichael** [comment]
@vishh yes, I will bring it up with the other maintainers today

**Comment by jackphel** [comment]
+1

**Comment by vishh** [comment]
Ping @crosbymichael!

**Comment by vishh** [comment]
I plan to post a PR soon since no concerns have been expressed for this feature.

**Comment by jfrazelle** [comment]
I think that is awesome @vishh I am +1 :)

**Comment by jfrazelle** [comment]
anything to get rid of systemd cgroups :P

**Comment by bgrant0607** [comment]
I discussed this with @crosbymichael at the last DGAB meeting, and my understanding is that we have the go-ahead for this.

**Comment by crosbymichael** [comment]
+1 for `--cgroup-parent`

**Comment by ConnorDoyle** [comment]
+1, this will strengthen the multi-tenancy story when running Kubernetes as a Mesos framework and `--cgroup-parent` should be sufficient for our use case.

**Comment by mohitsoni** [comment]
+1 for ```--cgroup-parent```

**Comment by jdef** [comment]
+1 for `--cgroup_parent`

**Comment by crosbymichael** [comment]
merged in #11428

**Comment by vishh** [comment]
Thanks for the quick review everyone :)
If the integration tests happen to flaky, ping me and I can fix them. There
should be enough logs now to identify any issue.

**Comment by thockin** [comment]
w00t!  This is a good one.  Thanks everyone.

**Comment by vmarmol** [comment]
Yay cgroups! :D That was one of the fastest feature merges I've seen.

**Comment by vishh** [comment]
This issue has been fixed via #11428

**Comment by ConnorDoyle** [comment]
:+1:

**Comment by bgrant0607** [comment]
Awesome, thanks a lot.

**Comment by jdef** [comment]
+1

On Thu, Mar 19, 2015 at 7:41 PM, Brian Grant <notifications@github.com>
wrote:

> Awesome, thanks a lot.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/8551#issuecomment-83809748>.
>



-- 
James DeFelice
585.241.9488 (voice)
650.649.6071 (fax)
