### ISSUE TITLE
Proposal: Support custom PID namespace

### ISSUE THREAD

**Issue by ibuildthecloud** [docker/docker#8568]
Currently you can do `--net=host` or `--net=container:id`.  I propose we add `--pid=host` or `--pid=container:id` so that you can control what PID namespace is setup.  The obvious use cause for such a thing is to run some monitoring tool that looks at processes in a container.  A simple example is to run `htop` against the host or another container.

The technical implications of this proposal is that Docker will need to track the processes of the container and kill them based on the cgroup.  Today if you stop/kill a container Docker will ensure the container PID 1 is killed.  Once the PID 1 is killed, Linux will kill all other processes in the PID namespace.  To support this behaviour I propose that Docker mimics the same behaviour with cgroups.  This means that Docker stop/kill the container PID as it does today.  Once the process is gone Docker should iterate all other processes in the cgroup and do a SIGKILL, as that is effectively what Linux does when a processes PID namespace goes away.

**Comment by phemmer** [comment]
This was implemented in #10080

**Comment by crosbymichael** [comment]
done with `--pid`.

Thanks for the update @phemmer

**Comment by ibuildthecloud** [comment]
@crosbymichael Hate to be pedantic, but this shouldn't be closed as `--pid=container:id` doesn't exist yet.  This could be closed if we never plan to implement it, but I think there is still a use case.

**Comment by crosbymichael** [comment]
@ibuildthecloud what is the use case?

**Comment by thaJeztah** [comment]
People looking for `--pid=container:id`; There's a new issue created for that here: https://github.com/docker/docker/issues/10163
