### ISSUE TITLE
V1.2.0 - Import is rejecting repository:tag formatted string.

### ISSUE THREAD

**Issue by M0E-lnx** [docker/docker#8572]
Trying to import an image from a compressed .tar.xz file.  This used to work perfectly fine on 1.1.2, but does not work anymore on 1.2.0

This is the command i'm trying:  `cat MyFile.tar.xz | docker import - my-image:1.0`

This returns an error saying 
`2014/10/14 15:41:28 Invalid repository name (my-image:1.0), only [a-z0-9-_.] are allowed`

If it helps, I have also tried `myimage:1.0` and `myimage:10` and all return the same error.

**Comment by unclejack** [comment]
This has been fixed. Please upgrade Docker.
