### ISSUE TITLE
WHATSNEW docs missing in Docker Remote API 1.15

### ISSUE THREAD

**Issue by ahmetalpbalkan** [docker/docker#8615]
What is new in Docker Remote API 1.15?

By not having a changelog and putting changes to the older API docs you make client library developers' lives harder. Can you please have a sane list of whatsnew in each version of API?

Also, can you please **not touch the old API docs**? When you seal a version with a number and change the API in it later on, there is no way a client developer can figure out what has changed as nobody will archive&diff the HTML. (#8458) This is a very serious issue. In v1.14 somebody edited docs and put some v1.15 stuff in there and we blamed ourselves for not seeing the changed part in the first place but it turned out this wasn't the case.

**Screenshot:**
![](http://cl.ly/image/1R0K3A1e3P30/Image%202014-10-16%20at%201.18.11%20PM.png)

**Comment by jfrazelle** [comment]
this was fixed
