### ISSUE TITLE
Build modifications to VOLUME directories are allowed to silently succeed

### ISSUE THREAD

**Issue by McKayDavis** [docker/docker#8647]
If a RUN command makes modifications in a directory that was previously marked with a VOLUME statement, the modifications will have no effect.  This is because the dir is overwritten when the image is run with the archived VOLUME contents.  

Currently, the build continues with no warning that the changes will not be visible when the image is run.

Can 'docker build' recognize an image diff as conflicting with a declared VOLUME and stop the build (or at least log an explanatory warning message)?

To see an example, build this Dockerfile with and without the VOLUME line commented:

```
FROM debian:wheezy

# Create a file and verify it exists
RUN mkdir /voldir
RUN touch /voldir/file.txt
RUN ls -al /voldir/file.txt

# Uncomment the line below to finish the build 
# (and expose the unexpected behavior)
VOLUME ["/voldir"]

# Q: Can the docker build process recognize that the following
# RUN command attempted to chang a VOLUME dir and that that change
# will *NOT* be reflected in the container when the resulting image is run?
RUN rm /voldir/file.txt

# Some users may expect the following RUN command to fail and 
# stop the docker build, but it will succeed if the VOLUME line above is on."
RUN ls -al /voldir/file.txt

RUN echo /voldir/file.txt still exists!
```

**Comment by jfrazelle** [comment]
@cpuguy83 is there any status on this, should it be labeled as bug or improvement

**Comment by cpuguy83** [comment]
I consider it a bug.

**Comment by jfrazelle** [comment]
going to close as dup of https://github.com/docker/docker/issues/3639#issuecomment-76148320, @cpuguy83 yell at me / reopen if im wrong
