### ISSUE TITLE
Docs on Dockerfiles use word "repository" without any explanation of the concept

### ISSUE THREAD

**Issue by JonasT** [docker/docker#8648]
Hi guys,

**Basic problem:**
the doc section on Dockerfiles is rather confusing, because it doesn't really explain an important concept: why is the dockerfile named "Dockerfile" similar to "Makefile", and what does that mean for the folder is it in? Why is it not just a "buildmyimage" file and that's it? Why a whole folder around it, what is it for?

**Current situation:**
The docs make a basic attempt at explaining it here: http://docker.readthedocs.org/en/v0.5.3/use/builder/ 1. Usage: "To build an image from a source repository, create a description file called Dockerfile at the root of your repository."

However, the docs completely drop the ball clarifying this. What is a repository here? Is that something special with special other files that are automatically used? Does it need a specific layout?

Even worse, if you are sufficiently confused to click "Working with repositories" in the navigation to clear this up, that section introduces a confusing online image thing where the basic concept of what a single repository is *in practise on my hard disk as a basic folder* is entirely missing.

**Proposal:**
http://docker.readthedocs.org/en/v0.5.3/use/builder/ 1. Usage: "To build an image from a source repository, create a description file called Dockerfile at the root of your repository."

Change to: "To build an image from a source repository, create a description file called Dockerfile at the root of your repository, which is just the basic folder containing all sorts of other resources you might need and later reference from your Dockerfile to include and use for your image as needed."

Or whatever you see fit. But please add a proper explanation!

**Disclaimer:**
I started reading the docker docs a few hours ago, so I might be misunderstanding basic concepts. But this really seemed confusing to me, so it would be neat if you could look into it - unless the explanation is already there and I was just too blind to stumble across it.

**Comment by jfrazelle** [comment]
@fredlf @SvenDowideit is this still an issue

**Comment by MHBauer** [comment]
#dibs 
as a newbie, here's my shot.

**Comment by JonasT** [comment]
Many thanks @MHBauer I really like that you chose to introduce the ```build context``` term instead of my suggestion, since that is what the tool also mentions when "uploading" during a ```docker build``` run. You fixed two things in one. :-) good job
