### ISSUE TITLE
Proposal: Improvement for automated builds using parameters

### ISSUE THREAD

**Issue by lloydwatkin** [docker/docker#8677]
I originally raised this as feedback for docker hub but have been told that it needs to be added to docker itself. 

I am using automated builds on docker hub (which are great). The problem I see is that in order to build an automated tagged release I need to create a tag where I checkout the tag itself in the dockerfile, e.g.
```bash
git clone https://github.com/buddycloud/buddycloud-server-java.git
git checkout v0.18.0
```

Additionally if I'd like to build two different branches (say we have a 'stable' and 'development' branch) I have to maintain two slightly different `Dockerfile` files (and ensure I don't overwrite one with another when merging) to ensure that the automated builds build the correct code.

My suggested solution was to pass the git commit hash into the docker file run script, these values being gathered from env (if running locally) or the github/bitbucket hook notification. I could then update my docker file as follows:

```bash
git clone https://github.com/buddycloud/buddycloud-server-java.git
git checkout $GIT_COMMIT_HASH
```

Which would mean that whatever branch/tag/commit the docker hub gets informed about via a hook it will always build the right version (locally you could get your env value to HEAD).

Its been pointed out to me that env variables are a no-no as builds need to be repeatable, which I completely understand. What am therefore proposing is that we add something I'm calling 'arguments' which can be overwritten at build time, but the `Dockerfile` sets a default, e.g.:

```bash

@COMMIT=HEAD

RUN git clone https://github.com/buddycloud/buddycloud-server-java.git
RUN cd buddycloud-server-java && git checkout @COMMIT
```

When building my image I could then do something like:

```bash
docker build -t buddycloud/media-server -a COMMIT=cc1e74996d6284d340f71ca5381594af8d88472f .
```

Which would solve my automated build woes (provided the hub would then set the value for me.

**Comment by jmreicha** [comment]
:+1:

@lloydwatkin looking to do pretty much the exact same thing.

**Comment by clarete** [comment]
Maybe the build-time variables merged a few days ago could be helpful: https://github.com/docker/docker/pull/15182

**Comment by cpuguy83** [comment]
Yep, closing as this is solvd by `--build-arg` which will be in the 1.9 release.
Thanks!

**Comment by sjfloat** [comment]
OP said:
> Which would solve my automated build woes (provided the hub would then set the value for me.

Is this the case then? Does the hub do this?
