### ISSUE TITLE
"docker pull library-image:tag" doesn't pull all aliases

### ISSUE THREAD

**Issue by tianon** [docker/docker#8689]
Looks like v2 didn't get #8193 like it should've:
```console
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
$ docker pull mongo:2.6
mongo:2.6: The image you are pulling has been verified
511136ea3c5a: Pull complete 
5a7d9470be44: Pull complete 
feb755848a9a: Pull complete 
1627d948a24f: Pull complete 
fa822d72bf37: Pull complete 
49b4737cc97a: Pull complete 
eb6f031b83d2: Pull complete 
b251ce5098a8: Pull complete 
b4ddce5f31a3: Pull complete 
839e041c9eec: Pull complete 
52422a1b50e1: Pull complete 
5d63fb31d79d: Pull complete 
60d391ff57d4: Pull complete 
97d8b6dd3b57: Pull complete 
Status: Downloaded newer image for mongo:2.6
$ docker images mongo
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
mongo               2.6                 97d8b6dd3b57        5 days ago          391.4 MB
$ docker pull stackbrew/mongo:2.6
Pulling repository stackbrew/mongo
97d8b6dd3b57: Download complete 
511136ea3c5a: Download complete 
5a7d9470be44: Download complete 
feb755848a9a: Download complete 
1627d948a24f: Download complete 
fa822d72bf37: Download complete 
49b4737cc97a: Download complete 
eb6f031b83d2: Download complete 
b251ce5098a8: Download complete 
b4ddce5f31a3: Download complete 
839e041c9eec: Download complete 
52422a1b50e1: Download complete 
5d63fb31d79d: Download complete 
60d391ff57d4: Download complete 
Status: Image is up to date for stackbrew/mongo:2.6
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
mongo               2.6                 97d8b6dd3b57        5 days ago          391.4 MB
stackbrew/mongo     2                   97d8b6dd3b57        5 days ago          391.4 MB
stackbrew/mongo     2.6                 97d8b6dd3b57        5 days ago          391.4 MB
stackbrew/mongo     latest              97d8b6dd3b57        5 days ago          391.4 MB
stackbrew/mongo     2.6.5               97d8b6dd3b57        5 days ago          391.4 MB
```

**Comment by thaJeztah** [comment]
Would it be possible to get a status update on this? 

If this is a "won't fix" (because of registry V2), I think the feature should be removed entirely.

I'm happy to make a PR to update the docs, add a note to the change-log and can have a look at reverting the changes that implemented this feature.

**Comment by bobrik** [comment]
If we're not having this in v2 then let's make v1 faster too: https://github.com/docker/docker/issues/8141#issuecomment-72667264

**Comment by dmcgowan** [comment]
@bobrik curious what your use case is that requires this feature? Getting the tag list will definitely be faster in v2, just in v2 we have no concept of considering two tags equivalent.

**Comment by bobrik** [comment]
@dmcgowan follow the link and read the math behind my use case. I want to use docker in production, but I can't.

**Comment by dmcgowan** [comment]
I saw the math, I was confused about is whether you are requesting this feature for v2 (pull all aliases) or mentioning that the existence of this feature in v1 is causing a performance issue.  My original question was asking what your use case for needing aliases is.  I understand that if pulling the tags is slow that is a problem, and likely should be separated out from this discussion.

**Comment by bobrik** [comment]
I don't need aliases te be in sync. I was trying to say that since in v2 there will be no such feature, it should be disabled in v1 too. That would fix one of my problems.

Sorry for confusion, I just tried to raise awareness to avoid performance issues in the future (and preferably in the present too).

I can create a separate issue to discuss disabling tag fetching in v1 if that could happen.
