### ISSUE TITLE
zsh completion: doesn't work when single character options are combined

### ISSUE THREAD

**Issue by mkoskar** [docker/docker#8701]
Test case:

```
docker run -t -i <TAB>
```
will start completion on `image` whereas

```
docker run -ti <TAB>
```
will start completion on `external command`.

Tested with `zsh 5.0.7-1` and `_docker (version: 0.3.0)` of ed7934fd63ed52ad0086aaac62203e58e304bcb7.

**Comment by jfrazelle** [comment]
seems to be fixed
