### ISSUE TITLE
Proposal: Show complete docker run command a container was started with

### ISSUE THREAD

**Issue by 7oku** [docker/docker#8705]
Hi folks, 

not sure if this was mentioned already, but wouldn't it be cool to get the complete command incl. parameters of a running container instance with which it was started? 

Something like "docker showcmd containerID" reporting "docker run -d --volumes-from ...." would be awesome in case your shell history is missing it. I am aware of "docker inspect", but you need to puzzle all items from here together again into a command. 

Would you have intention to include this feature?

Cheers
7oku

**Comment by jfrazelle** [comment]
not everyone runs command from the cli, there is also the api, seems not possible
