### ISSUE TITLE
Unwanted ports bound when running a docker image

### ISSUE THREAD

**Issue by migueln** [docker/docker#8709]
Hi,

I've created a new repository by committing an existing (but not running) container to a new name (e.g. mysoft). 

The problem is that when I run it as:

docker run -t -i mysoft /bin/bash

The ports that I used to bind to the older container / image by using the '-p' parameter are exposed in this new container. 

Is this the expected behavior?. How can I get rid of it and run my new repo/image without exposing any of these older ports?.

Miguel

**Comment by codeon-nat** [comment]
UNEXPOSE would be nice to have. When I "inherit" from another container and change the port, the old one  (here 9000/tcp) still shows up

<pre>1c4c9c9fdf08        mulle/mediawiki:wheezy   "/usr/sbin/php5-fpm    17 hours ago        Up 17 hours         **9000/tcp**, 172.17.42.1:9001->9001/tcp       mediawiki</pre>

**Comment by AshleyAitken** [comment]
I agree UNEXPOSE is needed, even UNEXPOSE ALL (or something to that effect).

**Comment by thaJeztah** [comment]
See this issue https://github.com/docker/docker/issues/3465 (and PR https://github.com/docker/docker/pull/8177) for `UNSET`-ing properties inherited from a parent image.

I think this should be closed as a dup of https://github.com/docker/docker/issues/3465

**Comment by AshleyAitken** [comment]
Thank you @thaJeztah

**Comment by cpuguy83** [comment]
Closeing since it's really a dup for UNSET
