### ISSUE TITLE
sometimes screen session causes hijack to detect STDIN/STDOUT closures wrong and fails to 'attach' to instance

### ISSUE THREAD

**Issue by xarses** [docker/docker#8719]
$ uname -a
Linux aw-linux 3.16-2-amd64 #1 SMP Debian 3.16.3-2 (2014-09-20) x86_64 GNU/Linux
(Debian Sid)

$ docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.2
Git commit (client): c78088f
OS/Arch (client): linux/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.2
Git commit (server): c78088f

$ docker -D info
Containers: 7
Images: 12
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 28
Execution Driver: native-0.2
Kernel Version: 3.16.0-2-amd64
Operating System: Debian GNU/Linux jessie/sid
Debug mode (server): false
Debug mode (client): true
Fds: 31
Goroutines: 45
EventsListeners: 0
Init SHA1: 740b7b44bf085ebcee3e61f12352c45ae6329812
Init Path: /usr/lib/docker.io/dockerinit
Username: xarses
Registry: [https://index.docker.io/v1/]
WARNING: No memory limit support
WARNING: No swap limit support

steps to reproduce:

screen
# screen starts
for e in {1..9} ; do screen ; done
# in window 9  ^A9
docker -D run -ti ubuntu bash
[debug] hijack.go:110 [hijack] End of stdin
                                           [debug] hijack.go:102 [hijack] End of stdout
                                                                                       [debug] commands.go:2224 End of CmdRun(), Waiting for hijack to finish.

expected results:

$ docker -D run -ti ubuntu bash
root@bda5aef355e7:/#

running docker inside the screen instance with a single window, or a window created with META-C (^AC) or windows 0, 1 in the loop method have this issue, only windows 2-9

as far as i can tell this seems like it comes from https://github.com/docker/docker/blob/master/api/client/hijack.go#L102 for 'run' or L110 for 'attach'

**Comment by jfrazelle** [comment]
a lot of fixes to hijack were added in 1.4 and 1.5, closing, but if you are still able to reproduce please give the exact steps to do so on the latest version and we will reopen

**Comment by xarses** [comment]
no longer reproduces, below from positive result
```
$ docker -D run -ti ubuntu bash
root@f1e649a572fb:/# exit
DEBU[0001] [hijack] End of stdout                       
                                                        DEBU[0001] End of CmdRun(), Waiting for hijack to finish. 
```

**Comment by daixiang0** [comment]
Reproduce
```
[root@test makeimage]# time  docker -D run --privileged -it 192.168.20.41:5000/ci/client
DEBU[0041] [hijack] End of stdout                       

real    0m42.097s
user    0m0.021s
sys 0m0.035s
```
My host is CentOS Linux release 7.4.1708 (Core), docker version is 17.06.2-ce, build cec0b72
Dockerfile:
```
FROM centos7.3

MAINTAINER skydata_ci

RUN yum install -y bzip2 md5sum make gcc sysstat net-tools lsof sar scp expect nmap time rsync hostname git openssh-server openssh-clients java-1.8.0-openjdk.x86_64 java-1.8.0-openjdk-devel.x86_64 which 
RUN yum install -y sudo
RUN yum install -y iproute psmisc

RUN mkdir /var/run/sshd
RUN ssh-keygen -A
RUN echo export PS1=\"[\\u@\\h \\W]\\$ \" >> /root/.bash_profile
COPY .ssh /root/.ssh
COPY scala-2.12.2.tgz /root/scala-2.12.2.tgz
RUN tar zxf /root/scala-2.12.2.tgz
```
I want to use it as ssh client and always in running state but no as expected.
