### ISSUE TITLE
/etc/hosts not updated for aliased links

### ISSUE THREAD

**Issue by mgood** [docker/docker#8721]
The new updating of /etc/hosts when the linked container is restarted looks like a really nice feature, but there seems to be a bug when an alias is used with the link name.

The code appears to update the entry in /etc/hosts based on the name of the container, rather than its alias within the parent container.

So this works: `docker run --link foo:foo` because the container name and alias are the same.  When the "foo" container is restarted the hosts entry for "foo" is updated.

However, `docker run --link foo:bar` does not work with the host updating.  When the "foo" container is restarted, the code looks for "foo" in the /etc/hosts file, and since it's not there it doesn't change the hosts file.  It should be looking instead for "bar" in /etc/hosts, since that's the alias used within this container.

The test case included with #7677 runs docker with the args `"--link", "c1:c1"` so it doesn't check this case when the link is given another alias.

**Comment by dodobas** [comment]
This is still a problem, aliased linked containers do not update /etc/hosts

**Comment by chrisnew** [comment]
Just encountered the same issue. Aliased links are missing after restart of linked container. Even stop and start of the container doesn't work. Container needs to be re-created.

**Comment by cpuguy83** [comment]
confirmed on 1.4.1

**Comment by cpuguy83** [comment]
And also on master.

**Comment by chrisnew** [comment]
Oh, I forgot to add: I'm also on master.

**Comment by LK4D4** [comment]
I'll take a look, thanks for report!

**Comment by LK4D4** [comment]
Yup, it never worked. Code is just wrong :)

**Comment by chrisnew** [comment]
Glad you found out what's wrong! Can't wait to have it back working. :)

**Comment by chrisnew** [comment]
Thanks guys, works perfectly now!

**Comment by erikh** [comment]
my b; sorry.
