### ISSUE TITLE
docker restart a container will change the port mapping

### ISSUE THREAD

**Issue by cc272309126** [docker/docker#8723]
Hi，

after docker restart containerid，it will allocate a new port to the container，Is there a way hold the port for a container？or this is feature for docker?
reproduce steps
1，docker run -d  -p 8080 imageid 
2，docker restart containerid
3，compare the container the mapping port，you will found that the port is changed。

ps: on docker 1.2.0 after restart the container twice，the port will lost. but this issue can not be reproduced on docker docker-1.3.0-dev.  
thanks

**Comment by gdm85** [comment]
I have also been hit by this bug, and it's a deployment blocker for me.

Although in production one will want to use fixed port mappings, there are scenarios (development, testing, staging) where you **want** containers to survive a daemon/host reboot and keep their port mapping, if not just to not destroy the work-flow of all involved people that are still using the containers.

**Comment by gdm85** [comment]
I have implemented stateful hostconfig save/restore in my [docker-fw](https://github.com/gdm85/docker-fw/) utility, feel free to give it a shot.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/7158 which is why it gets another port

**Comment by jfrazelle** [comment]
also https://github.com/docker/docker/issues/9047 for reference
