### ISSUE TITLE
/etc/hosts is empty on run?

### ISSUE THREAD

**Issue by pocesar** [docker/docker#8741]
After updating to 1.3.0, when using `--link db:db`, and then doing a `ping db` inside the container, it shows `unknown host db`, I checked the content of hosts using `cat /etc/hosts` and it's empty. when checking the docker mounted hosts in `/var/lib/docker...`, it's showing the docker container IP there. 

```
172.17.0.7      4ceb9a0c1a1c
ff02::2 ip6-allrouters
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
172.17.0.5      db
```

now my app can't connect to db because it cannot resolve it. I installed it on Ubuntu Trusty 64 bits on an EC2 instance if that's important

**Comment by cpuguy83** [comment]
This is because of making a volume on `/etc`
Closing since this should be resolved by #10615
