### ISSUE TITLE
Ubuntu Proxy Setup

### ISSUE THREAD

**Issue by sesteva** [docker/docker#8754]
Looking at docs there is no instruction on how to run it behind a proxy.
https://docs.docker.com/installation/ubuntulinux/

Reading on forums, the instruction is to update /etc/default/docker to export the proxy setup.

     export http_proxy="http://127.0.0.1:3128/"
     export https_proxy="http://127.0.0.1:3128/"
     export HTTP_PROXY="http://127.0.0.1:3128/"
     export HTTPS_PROXY="http://127.0.0.1:3128/"

Then we restart/start docker

     sudo service docker start

Inside a container, if I run 'apt-get', npm install, bower install I cant get through the proxy.

Not sure what I m missing.

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/pull/10748
