### ISSUE TITLE
Extensions to ADD primitive in Dockerfile

### ISSUE THREAD

**Issue by ericvh** [docker/docker#8758]
Why doesn't Dockerfile ADD support unpacking tarballs retreived remotely?  I was trying to setup an ARM64 Ubuntu Dockerfile, but having the ubuntu-core tarball locally seems like overkill.

Also, currently I have to add and then chmod an executable when using a dockerfile.  Seems like it would make sense to be able to do this in a single operation from a intermediate image perspective.

**Comment by jfrazelle** [comment]
unpacking by default would be a security hole
