### ISSUE TITLE
Remove a remote tag

### ISSUE THREAD

**Issue by sjackman** [docker/docker#8759]
I'd like to delete the tags `sjackman/linuxbrew:core` and `sjackman/linuxbrew:ubuntu`. I don't see how to do that from the [web interface](https://registry.hub.docker.com/u/sjackman/linuxbrew/tags/manage/) or the Docker CLI.

**Comment by tomfotherby** [comment]
I would also like to be able to delete tags from the hub but can't get it working. This is what I tried:

    curl -X DELETE --header Referer:curl -k -s --user tomfotherby:blah https://index.docker.io/v1/repositories/blah1/blah2/tags/2014-07-21_4ba8999_1c79e97

    <h1>Forbidden <span>(403)</span></h1>
    <p>CSRF verification failed. Request aborted.</p>

You could save ALOT of space on your servers if you fix this.

**Comment by mcandre** [comment]
+1

**Comment by thaJeztah** [comment]
I think this is being worked on; see https://github.com/docker/distribution/issues/422. Given that the "closed source" Docker Hub is based on the open source version, I expect it to arrive there as well after it's been implemented.

so for those interested, subscribe to that issue.

**Comment by tomfotherby** [comment]
Because the API doesn't provide a delete, I went to do my periodic manual cleanup which involves clicking the little cross next to unused tags on the docker hub page a few hundred times. But today the tags management page in docker hub (`https://registry.hub.docker.com/u/user/repo/tags/manage/`) isn't showing the usual huge list of pages of tags, I see only 1 page (30 ish rows). Has something changed? Are Docker reaping old tags now? (or is it just that the pagination is no longer shown?)

**Comment by thaJeztah** [comment]
@tomfotherby could you send that question to support@docker.com, because that's really a question for the team supporting Docker Hub, and the maintainers of the open source project have no insight in that.

There's also a public beta for upcoming changes in docker hub. Perhaps you can if that brings improvement in this area; https://hub-beta.docker.com

**Comment by thaJeztah** [comment]
Reading through this issue and the discussion again, I don't think there's anything the open source project can do here; all issues seem to be related to Docker Hub, for which issues are handled via support@docker.com (or https://support.docker.com).

For the open source registry, this is being worked on in https://github.com/docker/distribution/issues/422.

For that reason, I'm going to close this issue. Feel free to comment here if you disagree or think I've closed this by mistake.

**Comment by tomfotherby** [comment]
> @tomfotherby could you send that question to support@docker.com, because that's really a question for the team supporting Docker Hub

I emailed support@docker.com

> Dear Docker Hub Support Team,
> 
> When I view the tags of one of my private repos ( https://registry.hub.docker.com/u/me/myrepo/tags/manage/ ) I see a massive list of 1003 tags. The pagination on this page has gone since dockercon 2015. I would like to delete unused tags via a API call.
> 
> I'm trying this:
> 
>     curl -X DELETE -k -s --user tomfotherby:secret https://index.docker.io/v1/repositories/me/myrepo/tags/mytag
> 
> but I get a CSRF error. Is there a way to to remove tags from the hub pragmatically? beacuse I can't remove 1003 old tags by hand using the website.

----

The response:
 
>> Unfortunately, we do not recommend using API calls to delete tags. It has abnormal effects over repository. Those API calls are only for Private Registry. We will release V2 Endpoint later this year, which would be more stable and easy to use.
>> 
>> For now, you can list the tags you want to delete, put them in a file and send it to me and I will delete those for you.

**Comment by thaJeztah** [comment]
Thanks for adding that information, and taking the time to contact support @tomfotherby :+1: :heart: !

**Comment by thiagozs** [comment]
+

**Comment by yveshwang** [comment]
+1

**Comment by keithdwilliams** [comment]
+1

**Comment by jgkamat** [comment]
+1, we cannot remove tags anymore via the web-ui, so we need some way to remove tags (besides deleting the repo).

**Comment by rraheja** [comment]
+1
For private repos with collaborators, deleting and re-creating the repository every time a rogue tag makes its way to the hub is impractical.

**Comment by KotieSmit** [comment]
+1

**Comment by gwsu2008** [comment]
+1

**Comment by ruffsl** [comment]
+1! 
Why is this not in the :whale: web UI?
I'd really like to remove deprecated tags to avoid user confusion.

**Comment by StudioEtrange** [comment]
+1 and subscribed

**Comment by adambiggs** [comment]
+1

**Comment by Zarquan** [comment]
+1
Why is this not in the web UI ?

**Comment by sjwhyte** [comment]
+1

**Comment by thaJeztah** [comment]
For those wanting in in the Web UI on Docker Hub; Docker Hub is closed source, and managed by a different team; feedback for Docker Hub can be provided in a separate issue tracker, and there's already an issue open for this; https://github.com/docker/hub-feedback/issues/68

**Comment by ruffsl** [comment]
Ah, thank you @thaJeztah for linking the issue! 
I'll fallow this as well.

**Comment by AlexDultsev** [comment]
+1

**Comment by strarsis** [comment]
+1 for this in web ui

**Comment by alph486** [comment]
@strarsis You should be able to do this in the "tags" section of the web ui now.

**Comment by arangamani** [comment]
@alph486 Are you sure? I don't see any option to delete tags in the UI.

**Comment by alph486** [comment]
![screen shot 2015-12-31 at 12 51 01 pm](https://cloud.githubusercontent.com/assets/1747773/12067297/363a95a0-afbd-11e5-8f88-149f5a4350d4.png)

Available for me.

**Comment by arangamani** [comment]
Interesting. May be I don't have enough privileges to see that.
![screen shot 2015-12-31 at 10 52 40 am](https://cloud.githubusercontent.com/assets/1133812/12067315/a7ce9e70-afac-11e5-808f-55b4057fe1ec.png)

**Comment by alph486** [comment]
Hm. Do you pay or have a free account for public repos? There may also be some A/B testing going on....

**Comment by arangamani** [comment]
It is a paid account in our organization and I have maintainer privileges.

**Comment by alph486** [comment]
hmm...  ¯\_(ツ)_/¯ . I can see from @thaJeztah the conversation is moved over to https://github.com/docker/hub-feedback/issues/68 where some people have also noted they have a new icon. Might be worth asking there.

**Comment by thaJeztah** [comment]
@arangamani you can always open a ticket through support@docker.com, which is intended for support questions for the paid services.
