### ISSUE TITLE
Docker memory limit (-m/--memory) does not check child process

### ISSUE THREAD

**Issue by soichih** [docker/docker#8769]
Hello. 

When I specify memory limit via -m or --memory option (like "docker run --memory 1000m") This option sets the maximum amount of memory that any processes running inside a container can use, but it doesn't prevent a container from spawning many child processes that consume more than specified amount of memory in *total*.

For example, if I run a script that spawns 100 processes with each consuming 500M, the container as a whole consumes 50G of memory. With "--memory 1000M" set, Docker does not prevent this from happening since each child processes are only using 500M. Docker only kills process if it exceeds 1000M.

Is this an expected behavior? If so, it really doesn't seems that Docker (or LXC in general) has good way to enforce maximum amount of memory used by container as a whole. Is there a workaround to this problem?

**Comment by soichih** [comment]
I don't think #8479 is related.

Here, I am reporting that, -m option only applies to individual processes that run inside the container - and not the aggregate. You can have 100s of process that each consumes up to specified amount of memory and Docker will happily run them.

**Comment by mindscratch** [comment]
@soichih I commented on your [blog](http://soichi.us/archives/11), but thought I'd add my observation here for everyone else.

I tried this experiment using Docker 1.3.2 on CentOS 6 (2. this morning and had different results. I started the container (which had the bash script start multiple instances of the test.py program), I used top to monitor both python processes. What I saw was that the total resident memory usage for the two python processes did not exceed 1G (I started docker using --memory 1000M).

I modified the bash script to sleep for more than 30 seconds and I eventually saw the output confirming both python processes generated a 1G string, however, the second python process was only able to finish creating its 1G string after the first process exited.

It seems to me that Docker is working as expected.

**Comment by fishtek** [comment]
+1 
I also have this issue and think this issue should be reopened.

[I posed a question over on the docker mailing list a day or so ago but haven't heard anything back.](https://groups.google.com/forum/#!msg/docker-user/agFQbz2_07k/KZ0wyWUAwHwJ)

I think this is either a bug or the documentation needs to be clarified.

My message above to the mailing list describes the couple steps I used (even borrowed the nice stress image @jfrazelle has on docker hub) to reproduce it, and seems to me confirms what @soichih was seeing as well.  Such that only the individual child process in the container that exceeds the limit set with the --memory flag in the docker run command is actually killed.  

Honestly I would still be 'ok' if when a single child process in the container exceed the limit the entire container was killed, but even that isn't the case.  Of course ideally the aggregate memory of the processes in the container would be evaluated against the limit set.

**Comment by taviLaies** [comment]
This issue should definitely not be closed. 
Knowing whether we can rely on the memory limit or not is extremely important when multiple containers need behave on the same host.

**Comment by optimus-kart** [comment]
hi guys what was the conclusion for this. I am using docker 19.03 and I am still seeing this issue

**Comment by jarda-wien** [comment]
I tested this very behaviour and found out that the limits apply to the whole container and not a single process.
However, if you have multiple processes running inside a container, normal OOM rules apply as to which of the processes will be killed (usually the one with the highest ram usage). If OOM kills a process other than PID1, the container is NOT stopped and may keep running even if the main application is dead.

This is of course only if you don't follow the PID1 best practice.

`Docker version 18.09.7, build 2d0083d`
