### ISSUE TITLE
Accessing docker file-system from host device as $USER

### ISSUE THREAD

**Issue by xando** [docker/docker#8776]
Not really an issue, though looking for some guidance. 

A disclaimer: I'm not using docker as a production thing, all things described bellow are only for development purposes. I know that docker wasn't designed to be used that way. Anyways ... 

I've added my user to docker group.  
Running docker with 
`docker run -i -t ubuntu /bin/bash`
creates a container with filesystem located here 
`/var/lib/docker/devicemapper/mnt/45b2269a4e6100bbc85cf5ab87b912f3711695853fd076d15b8993ee1cb396ac/rootfs/tmp/` 

Since I'm using docker to the development purposes, sometimes I need to change things inside the container file-system. My expectation was, since the user is inside the docker group I would be able to do it. Each time i got 'Permission denied' from the shell. Even changing file-system rights to with `sudo chown :$USER <cointer fs>`, still I'cant access the container file system with the `$USER`.

**Comment by fatih** [comment]
Are there any other solutions for this problem? I too want to have access to the filesystem as a non-root user. Currently it's owned by `root`. So any solutions would be helpful :)

**Comment by jfrazelle** [comment]
volumes could help?

**Comment by cpuguy83** [comment]
@xando This actually looks like SELinux could be restricting your access to the files (assuming so since you are using devicemapper here).

But yes, volumes would be the useful for this use-case.

Closing as this is a non-issue.
