### ISSUE TITLE
Proposal: support of -u|--user for docker exec

### ISSUE THREAD

**Issue by fgutmann** [docker/docker#8798]
When using `docker exec` for a container which is using `USER something` in the Dockerfile, the command is also executed as this user.

Would it be possible to support the `-u | --user` option for `docker exec` like it is for `docker run`?

This would come in handy for executing commands that need root access in running containers.

**Comment by crosbymichael** [comment]
I think it makes sense to allow this.

**Comment by pandrew** [comment]
Yes, i really see the need for this during trouble shooting containers.

**Comment by lemval** [comment]
While agreeing with @fgutmann about starting a second container to get to all the data, that doesn't mean that I can modify the processes in the first container started. So @icecrime raises an interesting topic. While the USER specified runs the processes, it cannot modify certain files without elevation to root. So currently you aren't able to modify for example the proxy settings or routing in a running container. This kind of tampering can be a security issue. I'm glad you aren't able to elevate, but that doesn't mean it isn't a usefull option.
So I would suggest to add it, but only allow it if the docker process itself is started in development mode (--development_mode=true) and ignore the elevation if docker is started in production mode.

**Comment by ankushagarwal** [comment]
Can this be closed, given #12025 has merged this feature?

**Comment by praveengh** [comment]
Is there a way to use the -u option with the full login environment of the specified user ?

**Comment by thaJeztah** [comment]
@praveengh unlikely; not all containers have a shell, so adding such a flag would make assumptions about the container that we cannot make. Also `docker exec` is really a debugging tool, so we don't want to add more features if not really necessary (and there's already a way to do this, as you showed)

**Comment by cdancy** [comment]
@thaJeztah is there support for `user` through the remote API? [Poking around](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#/exec-create) I don't see anything. Am I missing something?

**Comment by cpuguy83** [comment]
@cdancy doc is likely out of date.

**Comment by cdancy** [comment]
@cpuguy83 or @thaJeztah is the proper syntax out somewhere? Can't seem to find within the source that admittedly I'm not the most familiar with its structure and layout.

**Comment by cpuguy83** [comment]
@cdancy It's probably `"User": "<user>:<group>"`

**Comment by thaJeztah** [comment]
You're correct; it looks like that PR went in without docs review,
and only the CLI docs were updated, but not the API docs
https://github.com/docker/docker/pull/12025

I'll open a PR to fix
