### ISSUE TITLE
apache could not auto start in container when a system host reboot

### ISSUE THREAD

**Issue by adrianmak** [docker/docker#8810]
i build a container manually, from base docker image and add apache service inside of it.
I commit the added service with a new docker image.

I started a docker container with command line
sudo docker run -i -t --name apache2 -p 80:80 -v /var/www/html:/var/www/html ubuntu/apache:14.04.1 /usr/sbin/apache2ctl -D FOREGROUND

and it works, and host could access the default web

I read this post http://docs.docker.com/reference/commandline/cli/#start   to auto start a docker container.

I created /etc/init/apache2  file
    description "Apache2 server"
    author "Me"
    start on filesystem and started docker
    stop on runlevel [!2345]
    respawn
    script
       /usr/bin/docker start -a apache2
    end script

After a system reboot, and sudo docker ps -all
it shown
af31eb2b01ab        ubuntu/apache:14.04.1   "/usr/sbin/apache2ct   Less than a second ago   Exited (-1) Less than a second ago
                   apache2

i could not access the web server. It seems apache didnt started

in the host, ps -ef  , I could not see apache processedd

**Comment by jfrazelle** [comment]
you need to use `--restart always` on docker run so your containers restart
