### ISSUE TITLE
When building an image: When image does not exist we get: Invalid repository name (<image id>), cannot specify 64-byte hexadecimal strings

### ISSUE THREAD

**Issue by timthelion** [docker/docker#8824]
As of https://github.com/docker/docker/pull/7609, when we build an image and place a non-existant image id in the FROM line, we get `Invalid repository name (<image id>), cannot specify 64-byte hexadecimal strings` rather than a more informative: "image does not exists" error.

**Comment by jfrazelle** [comment]
well this is because currently you can't pull by image id, so we assume they are trying to, I think it would slow things down if we had to check it it is a real imageid when really it is just going to error out anyways

i think https://github.com/docker/docker/issues/4106 is the solution here
