### ISSUE TITLE
official rpm package for docker

### ISSUE THREAD

**Issue by mlehner616** [docker/docker#8825]
Since this project is moving pretty quickly, would it be possible to get an official docker yum/deb repository for the most common linux types (i.e. Ubuntu/Debian, Fedora/CentOS). Even EPEL-testing is well behind the front of the releases from the project. 

This is particularly painful when a show stopper bug comes up such as https://github.com/docker/docker/issues/6476 and we need to update to freshly baked version.

**Comment by jfrazelle** [comment]
we already have a deb and are working on an rpm https://github.com/docker/docker/pull/10784

**Comment by jfrazelle** [comment]
we have rpms now and a yum repo coming soon
