### ISSUE TITLE
Preserve / improve consistency in CLI UI

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#8829]
**Summary**: 
There is no standardised "naming" for (sub)commands on the CLI (e.g. plural vs singular, create vs add), sometimes leading to inconsistencies.  

**Proposed solution**:
A design document should be written, describing the (naming) conventions to follow for commands and the UX in general.

----

A number of new features are currently proposed via PRs for addition to Docker. These features add new commands to the CLI and I have noticed that the UI for those commands (and *existing* commands) is inconsistent.

While there still a chance to change those proposals before they are merged, I think it would be a good thing to review those PRs and reach consensus on what the UI should look like to be consistent.

I've created a (far from complete) overview of some *existing* and *proposed* commands;

Entity | Action | Command | Notes
--- | --- | --- | ---
Container | list | `docker ps`
Device | list | - | (not supported)
Host | list | `docker hosts` | no sub command. see https://github.com/docker/docker/issues/8681
Image | list | `docker images` | no sub command (`ls`)
Links | list | `docker links list` | see https://github.com/docker/docker/issues/7468
Volume | list | `docker volumes ls` | see https://github.com/docker/docker/pull/8484
Container | delete | `docker rm (id)`
Device | delete | `docker device remove (id)` | see https://github.com/docker/docker/pull/8826
Host | delete | - | (not supported?)
Image | delete | `docker rmi (id)`
Links | delete | `docker links remove (id)`
Volume | delete | `docker volumes rm (id)`
Container | create | `docker create` | no "containers" before "create"
Device | create | `docker device add` | note: *singular* "device", others are "plural"
Host | create | `docker hosts create` | `run` [is proposed as alternative](https://github.com/docker/docker/issues/8681#issuecomment-60349475)
Link | create | `docker links add` |
Volume | create | `docker volumes add`

- The `ls` and `list` subcommands could be omitted dropped for `volumes` and `links` to be in line with the existing `images` command. 
- The subcommand for "delete" should either be "remove" or "rm" for all entities.
- The subcommand for "create" could be renamed from "add" to "create" to be in line with the existing `docker create` command (not sure, I actually like "add")
- All entities / top-level commands should be either plural or singular (rename `device` to `devices`?)

Now that the "links" (https://github.com/docker/docker/issues/7468), "volumes" (https://github.com/docker/docker/pull/8484), "hosts" (https://github.com/docker/docker/issues/8681) and "devices" (https://github.com/docker/docker/pull/8826) changes are still a proposal, I think the creators those proposals should discuss a consistent UI before they're implemented to keep things consistent.

For the *existing* commands I understand that most frequently used commands are deliberately left short for convenience, perhaps "long" versions (`docker images rm`?) could be added to make the UI more consistent.

(This is a follow up on a comment I placed here https://github.com/docker/docker/pull/8484#issuecomment-60827328)

**update**
Added the "hosts" proposal to the list and sorted the list a bit

**Comment by jfrazelle** [comment]
I'm trying to think of what an actionable item from this is, perhaps some sort of design doc

**Comment by thaJeztah** [comment]
@jfrazelle added; https://github.com/docker/docker/issues/8829#issue-47090184. @bfirsh are you still "in charge" of UX-design? I can *start* a PR, but it could be difficult for me if design needs to be discussed further / decided on.

**Comment by jfrazelle** [comment]
Actually sorry I was thinking about this last night, I think all the information here is super valuable so I was thinking we can just keep it w maybe label content and cli :)

**Comment by ewindisch** [comment]
Bump? I can't believe this is still open. @jfrazelle whatever the "output" is, it seems to be blocking for other issues, see: https://github.com/docker/docker/pull/8826.  It's frustrating to have good PRs blocked on bikeshedding.

**Comment by duglin** [comment]
Trying to a little bit of it slowly, here:  https://github.com/docker/docker/issues/13509

**Comment by dnephin** [comment]
We can create aliases (or hidden aliases) for the old names and move the commands to new names. That is quite easy to do with cobra. I have a prototype of this on a branch: 

* https://github.com/dnephin/docker/blob/cli-new-command-structure/cmd/docker/docker.go#L61-L113
* https://github.com/dnephin/docker/blob/cli-new-command-structure/api/client/container/cmd.go

Ex: `docker ps`, `docker container ls` (with alaises for `docker container list` and `docker container ps`) would all be the same commands.

**Comment by vdemeester** [comment]
@dnephin That would be really cool :angel: :heart_eyes_cat:

**Comment by dnephin** [comment]
PR up #26025

**Comment by SwitchedToGitlab** [comment]
Way to go guys, you took the one thing that Docker did well and absolutely ruined it.

>  the main reasoning of this is for _consistency_.

If you wanted to consistency, you should have focused on consistency for the thousands of professionals that use this daily instead of ripping the rug out from underneath them randomly. This entire issue thread just has me shaking my head at just how flippant and reckless Docker is with their user experience. This is sad, shameful and not the way a project should be managed.

**Comment by cpuguy83** [comment]
@SwitchedToGitlab To what are you referring? There was no change to existing commands in this change. Also note this was merged over 2 years ago.

**Comment by erikh** [comment]
dem trolls dem trolls dem... MIGHTY TROLLS

**Comment by thaJeztah** [comment]
Also interested in the issue that was caused; the change at the time;

- kept all existing commands untouched (but added an environment variable to hide some of them if desired)
- added new aliases for the existing commands (eg now `docker container run` as alias for `docker run`)
- new commands going forward following the new pattern (`docker <object> <verb>`)
