### ISSUE TITLE
How to set an enviroment variable on an existing container?

### ISSUE THREAD

**Issue by Boran** [docker/docker#8838]
One can pass environment vars into new containers when building them with "docker run":
docker run -e "FOO=bar" ...

But how can one do that for an existing container, there is no -e option for docker run.
I wish to be able to restart a container with a new environment setting, but do not wish to actually recreate the container (as it has lots of manual changes in there).

One option might be to commit the container to an image and create a new container based on that image. Seems a very roundabout way though.

have I missed something?

**Comment by antonbormotov** [comment]
I am looking for that as well,
I can change environment variables, go into container (for example, docker-bash tool), and export vars with export command or unset them. But in this way, when I exit from container, docker recovers old vars and their values.

**Comment by tiborvass** [comment]
@Boran @antonbormotov I believe commit is the right way here since you essentially want to keep a modified state of a container.

If your program is smart enough to have a way to source some file upon being notified, you could `docker exec sh -c echo 'foo=bar' > /root/.bashrc'` and notify the program to source it.

/cc @jfrazelle @tianon

**Comment by Boran** [comment]
The container name and and hostname within are also cast in stone.
I guess it is a conceptual issue that one just has to live with. Thanks for the suggestion.
One can close this issue from my point of view.

**Comment by pykiss** [comment]
I find it very usefull. +1

**Comment by bletvaska** [comment]
Yes. It will be very useful. At the moment, my workaround is this:

docker exec -i CONTAINER_ID /bin/bash -c "export VAR1=VAL1 && export VAR2=VAL2 && run_cmd"

**Comment by onbjerg** [comment]
@bletvaska How does that work?

**Comment by bletvaska** [comment]
before the command `run_cmd` is executed, the environment variables `VAR1` and `VAR2` are set.

**Comment by onbjerg** [comment]
But will this update the env variables "forever"? I mean, if I run this and then 5 days later change some variable in run_cmd, will it still work? Or is it a one-off command?

**Comment by bletvaska** [comment]
@onbjerg it is a one-off command. if you want to make this change permanent in the container, you have to commit your changes as was mentioned earlier.

**Comment by nemanjan00** [comment]
I found a solution... You just stop docker daemon and change container config in 
    /var/lib/docker/containers/[container-id]/config

**Comment by Boran** [comment]
didn't work for me.
```
docker run --name test1 busybox echo hello world
docker inspect test1
vi /var/lib/docker/containers/a1942d99c06a3e9d7c2229d2d6e3ab2370ceb427db488326088d615c0e89f8d5/config.json
(change test1 to test2 in the config)
start docker

docker start test2
Error response from daemon: no such id: test2
Error: failed to start containers: [test2]
```

**Comment by nemanjan00** [comment]
You did not stop docker daemon before editing config and start it after. :)

**Comment by Boran** [comment]
Yes, change an env variable works, confirmed. 
But not changing the conatiner name (which is irrelevant since docker now has a rename function any way).

**Comment by doronl** [comment]
This is a very annoying limitation

**Comment by thaJeztah** [comment]
For those interested, there's an open PR for changing properties of running/existing containers, but it has not yet been decided on; https://github.com/docker/docker/pull/15078

**Comment by peerasan** [comment]
Thanks /var/lib/docker/containers/[container-id]/config.json
At lease..... We can change

**Comment by pascalandy** [comment]
Folks,

Here was my challenge:
How can I pass enviroment variable from the host into a container while running a bash script. ?

I didn't find the answer easily ... but here it is!
The beauty of this setup is that it run via a bash script and the prompt don't have to go within the postgresql-master container. The script then upload ENV_BKP_NAME on S3 (via another container).

---

```
echo Generate a unique file name for this backup
ENV_BKP_NAME="$(date +%Y-%m-%d_%Hh%Mm%S)_pg-master.sql"

echo Transfer the env_var into postgresql-master container
docker exec -it postgresql-master sudo -u postgres bash -c \ export
declare -x VAR_BKP_NAME=$ENV_BKP_NAME
     
echo Time to backup ... pg_dumpall"
docker exec -it postgresql-master sudo -u postgres bash -c \
    "cd /var/lib/postgresql/backup \
    && pg_dumpall -U postgres --clean --oids --verbose > $VAR_BKP_NAME \
    && echo Message within postgresql-master container... \
    && echo ... backup $TMP_BKP_NAME is completed"
```

Cheers!
Pascal [Twitter](twitter.com/_pascalandy )

**Comment by yaitskov** [comment]
Now the config file is overwritten even after docker is stopped. :(

**Comment by derMart** [comment]
I do not understand why this issue is closed?
PR https://github.com/docker/docker/pull/15078 just supports resource configs for now.
As pointed out by @yaitskov the workaround editing the config file even does not work anymore at all.
The comment by @Boran in Jan 2015 points out a lot of arguments on which I would not conclude to close this issue. 

"I _guess_ it is a conceptual issue that one just has to live with." is not a closing argument either.

1. Is this a conceptual issue hard to change? 
2. Would it be possible and valueable to change even if not easy? 

I would answer the second question with yes, so from my point of view it is not ok to close this issue.

**Comment by nemanjan00** [comment]
ENV variables are not meant to be changed. 
If you want to change ENV variables, you deploy or commit and start with new ENV variables...

**Comment by Boran** [comment]
For me it's ok to close this, it's a conceptual issue.
When working with containers one has to learn to use the "immutability".

**Comment by eddo888** [comment]
docker exec -ti -e LINES=$LINES -e COLUMNS=$COLUMNS $container bash

**Comment by doronl** [comment]
The problem is that when you stop a container it actually kills all the processes, than when you do start it run the processes again from scratch,  reading the old env values from somewhere, why can't I override them?  @nemanjan00 this is IMO a pure technical issue and there are some cases when commit to image and run again as new container is very cumbersome and annoying.

**Comment by michael-wise** [comment]
I've encountered this roadblock several times. For the more less experienced programmers, docker is a great tool, but I wish containers/configurations were more pliable on-the-fly. In this case, setting environment variables for an existing container. Thanks.

**Comment by Lewiscowles1986** [comment]
I Just encountered this issue for the nth time. It does seem like a pain but thinking about it, your containers shouldn't contain any state that is not entirely disposable, so docker is helping us help ourselves towards a goal of immutability and documented deploys.

I Suppose it depends what you are using docker for, but I imagine there would be many that would be horrified if their ENV variable for database was changed during runtime without notice to another DB siphoning off user-data.

Just thought I'd put that out there.

**Comment by jpic** [comment]
Is there a method like kube's edit or something to edit docker inspect ?

**Comment by zsly1029** [comment]
@pykiss Thanks for the solution. It  is working!

**Comment by ntlzz93** [comment]
I can't find /var/lib/docker/..... 

`docker container inspect 503cac788f35`
 ```
"Id": "503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11",
        "Created": "2017-09-01T07:14:21.585220331Z",
        "Path": "/docker-entrypoint.sh",
        "Args": [
            "kibana"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 13405,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-04-23T14:06:39.160219761Z",
            "FinishedAt": "2018-04-23T14:01:18.693610061Z"
        },
        "Image": "sha256:8689ff370eef04a1de40fc5242c72a91b6f68e18412692445ad73c9f298b4184",
        "ResolvConfPath": "/var/lib/docker/containers/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11/hostname",
        "HostsPath": "/var/lib/docker/containers/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11/hosts",
        "LogPath": "/var/lib/docker/containers/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11-json.log",
        "Name": "/kibana",
.......
........
```

but when i cd to this location , not found location

> $ cd /var/lib/docker/containers/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11/hosts
> -bash: cd: /var/lib/docker/containers/503cac788f35b05e54a146272edf4904bea6fc4334cc54585b8c5ee07767ad11/hosts: No such file or directory

What's wrong with me?

**Comment by Dahu88** [comment]
@ntlzz93 hosts is probably a file a not a folder

**Comment by ptflp** [comment]
@Boran you can use bash script in entrypoint and receive environments from env file or other your best way, on every start, restart container, entrypoint updates your enviroments.
in dockerfile

```
...
ENTRYPOINT ["/bin/sh -c", "/path/to/your/bash.sh"]
```

in bash.sh

```
#!/bin/bash
export VAR1=VAL1 && export VAR2=VAL2
# Then start your service e.g. apache2
exec apache2 -DFOREGROUND
```

**Comment by willemavjc** [comment]
I know this issue is closed since a while but I'm surprised. Has anyone ever considered using a .profile to solve this?

In case some people still come on this issue which is on Google Search Top10 results, we use .profile here. (See details in this issue: https://github.com/moby/moby/issues/22490#issuecomment-541429688)

**Comment by felipecrs** [comment]
> In case some people still come on this issue which is on Google Search Top10 results, we use .profile here. (See details in this issue: [#22490 (comment)](https://github.com/moby/moby/issues/22490#issuecomment-541429688))

I don't know how `~/.profile` helps since it's not sourced at all unless you use something like `bash -l`.

**Comment by sylentpunk** [comment]
it completely baffles me how 

> ENV variables are not meant to be changed. If you want to change ENV variables, you deploy or commit and start with new ENV variables...

the argument tho is that this *shouldn't* be the case. you should not *have to* offline a container completely to update its configuration. its a config file. config files should be adjustable for specific circumstances as needed in my opinion

**Comment by nemanjan00** [comment]
There are plenty of good reasons why variables can not be universally changed in the runtime:

1) Environment variables propagate down the process tree, so, there would be a need for ability to locate processes that need env variables changed

2) A lot of containers use vars only in entrypoint, to generate config for application before starting it

3) Most of apps only use env vars, to connect to DBs, set local vars, etc.

4) Due to 2 and 3, you lose the biggest advantage of docker, the guarantee application will work the same time every time

5) You lose immutability which is very important for HA

The proper way to change env vars is to deploy new version, by altering docker-compose.yml/dockcer-stack.yml or whatever other mechanism you use for deploying application

**Comment by felipecrs** [comment]
One possibility is to allow changing environment variables, but they would only be effective on container restart.

**Comment by nemanjan00** [comment]
It would be more of rebuild than restart, since restart does persist storage...

**Comment by yangyile1990** [comment]
## 但是我的容器已经启动，该怎样修改启动容器时的环境变量呢
```shell
#首先停止容器
docker stop gitlab
#获取到容器ID
export CONTAINER_ID=`docker inspect --format="{{.Id}}" gitlab`
#检查获取的是否正确
echo $CONTAINER_ID
#修改容器配置所在的位置（默认位置是 sudo vim /var/lib/docker/containers/$CONTAINER_ID/config.v2.json）
sudo vim /media/yangyile/SSDYILE/dockervolume/docker/containers/$CONTAINER_ID/config.v2.json
#在里面搜一下就能找到 "Env" 的配置，编辑即可
#编辑完重启docker服务
sudo systemctl stop docker
sudo systemctl stop docker.socket 
sudo systemctl start docker.socket 
sudo systemctl start docker
#容器再次启动后验证结果
docker exec gitlab bash -c 'echo $GITLAB_OMNIBUS_CONFIG'
#很明显结果已经生效，而看启动日志也是正常的启动
docker logs --tail 100 gitlab
#感谢这个教程
#https://stackoverflow.com/questions/27812548/how-to-set-an-environment-variable-in-a-running-docker-container
#里面的某个人的指导意见恰好能用于我的情况
```
