### ISSUE TITLE
Trusted Builds: Tag Every Build with Repository SHA-1

### ISSUE THREAD

**Issue by felixhummel** [docker/docker#8841]
This would make review and pinning versions trivial.

Example workflow:

- find Nginx on the Docker hub, e.g. https://registry.hub.docker.com/u/dockerfile/nginx/
- follow "Source Project Page" link to github, e.g. https://github.com/dockerfile/nginx
- review code at specific revision, e.g. [8f2eed24c36a0305d8d187228e8d52505da830d9](https://github.com/dockerfile/nginx/blob/8f2eed24c36a0305d8d187228e8d52505da830d9/Dockerfile)
- pull image with tag, e.g. `docker pull dockerfile/nginx:8f2eed24c36a0305d8d187228e8d52505da830d9`

This way you can be sure that you get exactly the version you wanted, given you trust both Github and Docker, Inc.

**Comment by stp-ip** [comment]
I use something similar to example/nginx:2015-01-01_8f2eed so that builds can be ordered by build date etc.

**Comment by cpuguy83** [comment]
@felixhummel `dockerfile` is **not** from Docker, Inc.

Also, I'm closing this since it's not a Docker issue.
For issues/feature requests for DockerHub, please send to support@docker.com
