### ISSUE TITLE
Get metrics from docker daemon

### ISSUE THREAD

**Issue by tobegit3hub** [docker/docker#8842]
I have found the tutorial to get metrics from cgroup in https://docs.docker.com/articles/runmetrics/.

It would be great for us to get the metrics of containers from docker client. Is that possible to implement something like `docker metrics $ip`? I know somebody has implemented this but not in trunk.

**Comment by wojons** [comment]
Let me know if there is anything I can do to help with this. It will be great to get this info from over the api.

**Comment by SvenDowideit** [comment]
@tobegit3hub @monsterzz @wojons I think what is really needed is a full Proposal - ie, a PR with the propsed documentation changes showing how it'll work.

**Comment by tobegit3hub** [comment]
@SvenDowideit Great! Looking forward to this feature and let us know if we can do something.

**Comment by discordianfish** [comment]
See the linked proposal: #9130 and let me know if something is still missing. From my perspective the next step would be to get this proposal acknowledged so we can start implementing it.

**Comment by crosbymichael** [comment]
@discordianfish I think you proposal add a few other features.  

I'm going to go through each of these and see if I can get the container metrics ( resource usage ) implemented in the API as the first step.

**Comment by crosbymichael** [comment]
#9984 was merged so this is resolved.  Hope you like it!

**Comment by tobegit3hub** [comment]
Great :+1:
