### ISSUE TITLE
Support cgroup command to change properties dynamically

### ISSUE THREAD

**Issue by tobegit3hub** [docker/docker#8843]
I noticed that someone has implemented the feature to update the properties dynamically. They do this like `docker cgroup 8abc71d344c memory.limit_in_bytes=1g`.

The feature is great for us if we want to use cgroup with docker client.

**Comment by calavera** [comment]
Hi,

we had a discussion about this feature yesterday, and we decided to not allow to dynamically update properties. Thanks for letting us know about your use case, we really appreciate it and took it into consideration.

I'm closing this issue. Thank you!

**Comment by tobegit3hub** [comment]
We're using docker to run application in PaaS platform. Our customers may change the usage of CPU or memory dynamically. Please let us know why you make this decision. If docker doesn't support this, we have to extend docker by using pure cgroup api.

**Comment by calavera** [comment]
See #11442

**Comment by tobegit3hub** [comment]
Get it. Thanks @calavera
