### ISSUE TITLE
remote API to pull inconsistent

### ISSUE THREAD

**Issue by xavs** [docker/docker#8844]
The API to pull an image is a bit inconsistent.
IE POST /images/create?fromImage=xxx.xx/asd/qwe
When the pull fails it still returns http status 200, and the response body seems like some sort of pseudo-json like
{"status":"Pulling repository aaa.com/ns/name"}
{"errorDetail":{"message":"Error: image ns/name not found"},"error":"Error: image ns/name not found"}

where it should probably be like 
{"status":"Pulling repository aaa.com/ns/name",
"errorDetail":{"message":"Error: image ns/name not found"},"error":"Error: image ns/name not found"}

and the response status probalby a 422

"The 422 (Unprocessable Entity) status code means the server understands the content type of the request entity (hence a 415(Unsupported Media Type) status code is inappropriate), and the syntax of the request entity is correct (thus a 400 (Bad Request) status code is inappropriate) but was unable to process the contained instructions."

**Comment by gtaylor** [comment]
I noticed this as well, when playing with docker-py. Was hoping to see if this was intended behavior or not. The docs don't mention any codes aside from 2xx and 500 for this particular API call.

**Comment by jfrazelle** [comment]
dup of https://github.com/docker/docker/issues/5722
