### ISSUE TITLE
Proposal: do we need an official spec file in docker source code?

### ISSUE THREAD

**Issue by hqhq** [docker/docker#8852]
Somebody would like to build their own rpm file from docker source code,
but docker don't have a spec file. I saw some other open source project 
offers spec file, like LXC.

So does docker need an official spec file? If it does, I'd like to write a spec
file and send a pull request.

Regards.
Thanks.

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/pull/10658

**Comment by jfrazelle** [comment]
you are more than welcome to add things to those references and send a PR
