### ISSUE TITLE
Remove the spurious \n when using --format with inspect

### ISSUE THREAD

**Issue by vaab** [docker/docker#8853]
I'm doing some heavy parsing jobs using ``--format`` and text/template to produce NUL separated fields that can be safely parsed. (For instance, the Cmd args are often multiline, and require such precaution).

I was astonished to witness the spurious "\n". I don't know any tool that provide a similar templating facility that would dare to force a "\n" at the end. I can think of "git", "find", "printf" ...

Can you remove it ? (it's one line in the source code that should be removed).

**Comment by duglin** [comment]
ping @crosbymichael any thoughts on this?
I'm inclined to agree with @vaab, mainly because of this example:
```
root@docker:~/docker$ printf "%s " $(docker ps -aq)
8335e81db6a1 db6cc9e0afba e4701ef5fc5e ea9901b72f17 0bbec7954518 ef8050df72ec c07d1cce2c8b 61a424c3c478 c5d3ea0b4288 5a23d8917624 24c3c4e05436 67e930bcfbf5 9a34d521542f 32d6f7cfa76d bf1aac6aed1c 49b7eade521b f6f1f70b7c17 1ca10634e80d 043ddf30d020 02beec274126 332a46fec5e1 4c40246ffc10 39d9181c6f95 d49d6660fa66 5b7e41e9b68e 454aa72cd019 646242c68d58 9b61220a4347 50900376f4a2 b93930ddf815 e923cf7eb6fd 7bbf184e44e9 62b2af3daa0b 502427ad8d36 bc9f16f890cb 987945aad907 001ac182ad0d 2614f7ed121a 6cf4d547d47f 188ce95851f3 913950b83a1e fe3246082743 f30112653228 6eac0535b1ba e5f80881235e 94d5e3374460 497835aaa4d1 29872d6a3308 77eb3fc5aa38 7da349e6b840 8521203996cc d4fffefe9fc3 f45ea69a0b49 ff5227dba76f c649cccc5106 c5caa8c67015 2e75ef2a8d58 root@docker:~/docker$
```
Notice there is no \\n between each %s, nor is there a \\n at the end before my prompt is printed.

The only issue with removing the \\n is that its not backwards compatible but we could claim its a bug that's been there for a while.  Or, deprecate it via https://github.com/docker/docker/pull/13900 and remove it in 2 releases.

**Comment by thaJeztah** [comment]
ping @icecrime @crosbymichael for thoughts

**Comment by vaab** [comment]
What is holding from just correcting the bug ?

**Comment by calavera** [comment]
Thanks for your suggestion. As @cpuguy83 mentions, we designed the cli to be human friendly, not machine friendly. Since you already found a workaround, we've decided to close this issue as "won't fix".

**Comment by vaab** [comment]
Very sorry to hear that. By saying "human" friendly or "machine" friendly you probably mean "end user" friendly or "developer" friendly. The ``--format`` option, which involves using go templates syntax, and which is the only thing concerned here is undeniably for developer. It should not add unexpected character in the provided template.

Templating in CLI tools is common, and docker is the only one making this mistake (ie: ``find``, ``date``, ``printf`` ... etc ...) . There are no other case of this anywhere and this is a blatant consistency issue that is easy to correct.

**Comment by hasufell** [comment]
Totally baffled why this is still an issue for an option that is clearly meant for **scripting**, as in **machine friendly**.

**Comment by nepella** [comment]
I also find this to be perplexing: the templating interface is clearly designed for scripting, not direct client use, yet it can't comfortably conform to either? Suppose I want to generate a listing of every IP for every network for a particular container:

    #!/usr/bin/env bash
    set -euo pipefail

    read -r -d '' EXPRESSION <<'EXP' &&:
        {{$name := .Name -}}
        {{- range $net_name, $net := .NetworkSettings.Networks}}
        {{- $name}}{{":"}}{{$net_name}}{{":"}}{{$net.IPAddress}}{{"\n" -}}
        {{- end}}
    EXP

    while IFS=: read box network ip; do
        echo "Box: $box"
        echo "Network: $network"
        echo "IP address: $ip"
        echo "==="
    done < <(sudo docker inspect -f "$EXPRESSION" $(sudo docker-compose ps -q))

The unwanted newlines will add spurious blank records; I can strip these out with `sed` (`sed '/^$/d'`) or a conditional `continue` statement, but it's inelegant.

**Comment by mgutt** [comment]
I think I'm facing the same problem. I used this command to get all Mounts of all running containers and it adds empty new lines where I did not expect them:

```
docker container inspect -f '{{ $containername := .Id }}{{ range .Mounts }}{{ if .Source }}{{ printf $containername }}:{{ .Source }}{{ println }}{{ end }}{{ end }}' $(docker ps -q)
```
