### ISSUE TITLE
Ceph storage driver

### ISSUE THREAD

**Issue by dachary** [docker/docker#8854]
Ceph ( http://ceph.com ) RBD ( http://ceph.com/docs/master/rbd/rbd/ ) volumes provide thin provisionned, clonable, snapshotable block devices and could be used as a docker storage driver ( --storage-driver ). The main incentive for implementing this storage driver is that the RBD volumes are based on a self-healing networked object store ( http://ceph.com/docs/master/rados/ ). If a bare metal machine becomes available, the image can be accessed by a backup machine. An image could be provisionned with
<pre>
rbd create --size 200G name
</pre>
and cloned for a container to write into it with
<pre>
rbd clone
</pre>
and mounted via the kernel rbd driver ( http://ceph.com/docs/master/rbd/rbd-ko/ ) with
<pre>
rbd map
</pre>
See also https://github.com/docker/docker/issues/7249 for **Remote Shared Volumes**

**Comment by glennswest** [comment]
Ceph has a advantage in that we can use local storage to optimize performance. The container itself may be throw away, but attached volumes often contain very useful data, and is what u want to backup. Snapshots here also help alot. So think about it, a bind(DNS) container, all your bind database is in the attached drive, while the bind container is stateless, the data is not. Simliar issue in maria db. Yes, you can have multiple copies, and best practice u do, but in the end, you need to make sure even if everthing is down, you have a way of recovering. Also some things could be useful here. Take a snapshot of a database, attach it to a new container instance and try out a new version.

Also anything "stuck" in one box is not a great thing, it far better if data is always replicated and snapshot on a routine basis. Servers fail, datacenters switch off, and buildings burn. If you look at the stats, a signficant reason IT fails is the failure of IT during disasters, hacks etc. No such thing as too much backup.

**Comment by lorieri** [comment]
+1

**Comment by hustcat** [comment]
Just like device mapper, [RBD](http://ceph.com/docs/master/rbd/rbd-snapshot/) is thin-provisioned. @simon3z 's work is a good start. I also have an interest in RBD-based graph driver, @simon3z , can you make a PR?

**Comment by h0tbird** [comment]
+1 for volume storage

**Comment by geovanisouza92** [comment]
:+1:

**Comment by pierreozoux** [comment]
Is it still current?

**Comment by pandrew** [comment]
Highly interested in this feature as well.

**Comment by pierreozoux** [comment]
I think this is part of docker 1.9 https://github.com/docker/docker/issues/10661
But I'm looking for the doc :/

**Comment by cpuguy83** [comment]
This has been attempted a number of times, but there are issues with statically compiling ceph libs in with Docker.

Being that we now support plugins for graph drivers, I'm tempted to close this as I don't think anything will get merged wrt ceph.

**Comment by unclejack** [comment]
As @cpuguy83 has also stated above, this can't happen as part of the official Docker repository.

Please read my comment: https://github.com/docker/docker/pull/13777#issuecomment-116253478
>The Ceph driver has been requested before and I've also rejected that idea because we'd have to tie it into Docker by linking to Ceph libraries which are version specific. The last thing we need is to link against more foreign C/C++ libraries and produce multiple Docker binaries for all those systems with all the different Ceph versions. It's obvious that we won't get a Ceph PR because we've turned it down for these reasons, so Ceph support can't happen without plugin support for graph drivers.

>These graph driver plugins could live in a separate repository and they could be packaged separately from Docker. The Ceph graph driver would probably be the first one.

There's simply no reasonable way to integrate Ceph support directly into Docker's code base.

There's enough to look after already without Ceph code in Docker. Testing Docker with all versions of Ceph on all distributions, providing packages to link against all those different Ceph versions and recompiling Docker when doing a significant Ceph update isn't going to happen.

The only way to implement Ceph support for the graph storage is through a plugin. An external plugin isn't an issue to be tracked on this issue tracker.

An implementation of a Ceph graphdriver plugin can be found here: https://github.com/hustcat/docker-graph-driver

As there doesn't seem to be any more actionable items on this and individual plugins aren't tracked here which may require keeping this issue open, I'll close it now. Please feel free to continue the discussion on this issue, including any discussion about Ceph plugins.
