### ISSUE TITLE
Allow the docker registry to be configured when starting the docker daemon

### ISSUE THREAD

**Issue by mindscratch** [docker/docker#8855]
Currently, the docker daemon assumes it'll push/pull images from the Docker Registry Hub (http://registry.hub.docker.com/). When hosting a private repository, it's a bit of a hassle to build an image, tag it using the hostname:port of the private registry and then push it.

In an environment where the public Docker Registry Hub will never be used it would be nice to configure the docker daemon to use a different host:port when doing push/pull to avoid having to specify a host:port when pushing and pulling.

**Comment by r04r** [comment]
The maven approach could be taken, where a different server is set as default which will forward all the requests to another repository (the central one) if it cannot resolve them locally.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/8329

**Comment by thaJeztah** [comment]
There's also a new PR opened here https://github.com/docker/docker/pull/10411
