### ISSUE TITLE
Adding ONRUN instruction

### ISSUE THREAD

**Issue by ahmet2mir** [docker/docker#8860]
Sometimes, you need post "run" action when you run your image. 
For example with my image "leed", I need to configure it for DB connection.

You have two choice : 
1/ making this actions in Dockerfile and you must build the image each time (with fig for example)
It's not a proper way, 1 image = 1 container, I lost the advantage of the image

2/ create an init script (and be sure of idempotency) and run the soft at the end
My Dockerfile is not readable and I don't know which command it use, I need to check the script

Solution : Creating ONRUN instruction. 
With ONRUN you just specify the script to use for the first start. You can use a script, or a puppet run, or whatever you want.

Example in Dockerfile:

	FROM ...
	....
	ONRUN init.sh
	CMD ["/usr/bin","sof","param"]

Run it

	docker run -d --name test myimage
	# run init.sh before CMD/ENTRYPOINT

	docker stop test
	docker start test
	# will not run init.sh

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
