### ISSUE TITLE
unix sockets for containers that link on same host

### ISSUE THREAD

**Issue by josh-devops-center** [docker/docker#8864]
Hi,

It would be nice if communication for docker containers linked to each other used unix sockets. Is this possible to enable?

Thanks

**Comment by jfrazelle** [comment]
it's just a different flag but works the same

**Comment by josh-devops-center** [comment]
It would be helpful if you provided a link to the documentation when you close.

**Comment by jfrazelle** [comment]
Sorry I had all the intention of doing to probably forgot to paste http://docs.docker.com/reference/commandline/cli/#run
