### ISSUE TITLE
docker top for host level metrics

### ISSUE THREAD

**Issue by jchauncey** [docker/docker#8875]
So I was wondering what the community thought about the idea of docker top returning the top metrics for all running containers on a host? This would be a great way to debug issues where a docker host is running out of memory and you want to find the offending container.

Seems like the first place to start would be to have an api endpoint that returns the data then implement it for the CLI. The endpoint could just be /containers/top.

Thoughts?

**Comment by crosbymichael** [comment]
With #9984 merged you can get an aggregate view of how much cpu, memory, io, etc containers are running by doing:

```bash
docker stats insurgency1 insurgency2 insurgency3 minecraft-family redis

CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
insurgency1         3.62%               244.4 MB/2.099 GB   11.64%              0 B/0 B
insurgency2         4.65%               135.6 MB/2.099 GB   6.46%               0 B/0 B
insurgency3         3.65%               79.18 MB/2.099 GB   3.77%               0 B/0 B
minecraft-family    14.13%              408.6 MB/2.099 GB   19.47%              0 B/0 B
redis               0.17%               6.558 MB/67.11 MB   9.77%               648 B/648 B
```
