### ISSUE TITLE
[docs] /reference/builder/#volume incorrect render on docs.docker.com site

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker#8885]
This line is rendered incorrectly:

The value can be a JSON array, `VOLUME ["/var/log/"]`, or a plain string with multiple arguments, such as `VOLUME /var/log` or `VOLUME /var/log`
`/var/db`.

But it should be:

The value can be a JSON array, `VOLUME ["/var/log/"]`, or a plain string with multiple arguments, such as `VOLUME /var/log` or `VOLUME /var/log /var/db`.

[Github](https://github.com/docker/docker/blob/master/docs/sources/reference/builder.md#volume) renders it correctly.

(tested on linux, Firefox and Chrome)

**Comment by jfrazelle** [comment]
looks to be fixed http://docs.master.dockerproject.com/reference/builder/#volume

**Comment by TomasTomecek** [comment]
To me it's still broken, both in firefox and chrome: different zoom levels expose it. This css code is breaking it:

```css
code {
    white-space: pre-line;
}
```
