### ISSUE TITLE
Add support for publishing ranges of ports

### ISSUE THREAD

**Issue by md5** [docker/docker#8899]
Given the ability to `--expose` ranges of ports from #8167, it would be useful to be able to publish ranges of ports as well. I'd like to be able to do this:

    docker run -d --publish 10000-20000:10000-20000 myimage

**Comment by vipconsult** [comment]
docker run -help doesn't show the new option for port range

 -p, --publish=[]           Publish a container's port to the host
                               format: ip:hostPort:containerPort | ip::containerPort | hostPort:containerPort | containerPort
                               (use 'docker port' to see the actual mapping)

**Comment by vipconsult** [comment]
one more bug 
http://screencast.com/t/h3KuExeJr8Nj

on every  port it ads new line so docker ps is becomes unreadable.

**Comment by thaJeztah** [comment]
@vipconsult I think the output of ps is being worked on here; https://github.com/docker/docker/pull/10339

**Comment by ColmHally** [comment]
@vipconsult @thaJeztah yeah, I'll be adding published ranges in `ps` output later tonight on #10339

**Comment by dkirrane** [comment]
Are there any limits on port ranges? 
I'm publishing approx. 200 ports 
`docker run -p 7000-7200 -p 8080 webservice`

If I `exec` into the container I can curl to the webservice URL:
`curl http://localhost:8080/my/web/service`

But if I do same from the host ip it just gets stuck loading the page:
`curl http://HOST_IP:8080/my/web/service`

**Comment by thaJeztah** [comment]
@dkirrane is your webservice perhaps only listening on `localhost`? It should be listening on "any" IP-address (ie, `0.0.0.0`)

**Comment by md5** [comment]
@dkirrane your service's ports are being published on random host ports.

Try this:

    docker run -p 7000-7200:7000-7200 -p 8080:8080 webservice

**Comment by md5** [comment]
Be aware that starting a container with a large published range of ports like that is currently quite slow. I didn't dig into it, but I'm assuming the reason is that Docker is creating individual `iptables` rules for each port in the range instead of taking advantage of `iptables`'s native ability to map port ranges.

**Comment by thaJeztah** [comment]
> service's ports are being published on random host ports

^^ oh, correct, wasn't paying attention

**Comment by dkirrane** [comment]
@md5 Ya sorry that was a typo. I've reduced the number of ports & mapped the port-range as described:
`docker run -d -p 7000-7003:7000-7003 -p 7053-7063:7053-7063 -p 8099:8099 -p 9080:9080 -p 9443:9443 --name="my-service" dkirrane/my-service`

Now from the host machine if I curl to my docker service using localhost the page returns. However, when I use the Host IP curl fails

```
alias hostip="ip route show 0.0.0.0/0 | grep -Eo 'via \S+' | awk '{ print \$2 }'"

# Localhost works
curl http://localhost:9080/my/web/service

# Host IP returns connection timesout
curl http://$(hostip):9080/my/web/service
```

**Comment by md5** [comment]
I'm not sure why you're using that method to get your host IP address, but I think you're getting the wrong IP.
