### ISSUE TITLE
[Proposal] Limit or rotate docker container logs

### ISSUE THREAD

**Issue by parisk** [docker/docker#8911]
Stdout, stdin and stderr data of docker containers is being stored in the disk (by default in `/var/lib/docker/containers/{ContainerId}/{ContainerId}-json.log`) and it seems that there is no way to limit this.

This means that if Docker containers run programs of untrusted users, they could fill up the disk into which Docker is installed by just flooding the stdout or stderr pipe with data.

I think it would be extremely useful if there could be a way to limit this.

I can see two different cases of handling this.
  1. Limit the size of logs that a container can produce (I am not sure how this would treat the user's program)
  2. Rotate the log file produced in the disk (this could be totally transparent for the user)

**Comment by gniewkos** [comment]
:+1:

**Comment by bernardopericacho** [comment]
+1

**Comment by miklos-martin** [comment]
:+1:

**Comment by coolljt0725** [comment]
+1

**Comment by mahnunchik** [comment]
+1

**Comment by pires** [comment]
This is crazy, I'm finding logs with 96GB!!! so +1111111111..

**Comment by cpuguy83** [comment]
see #11485

**Comment by vbauer** [comment]
:+1:

**Comment by arangamani** [comment]
:+1:

**Comment by aaronjwood** [comment]
+1

**Comment by imton** [comment]
+1 now that there's log drivers, can this be implemented?

**Comment by chernjie** [comment]
In case your OS support `logrotate`, you can use this [configuration file to rotate your docker logs](https://gist.github.com/chernjie/39a02fb4329129a56316).

**Comment by thaJeztah** [comment]
As mentioned above, an implementation is being worked on in https://github.com/docker/docker/pull/11485. You can check progress on that pull request.

**Comment by draghuram** [comment]
Hi, is there any chance that log roll over functionality makes it to 1.7? I guess the answer may be no since RC1 is already out but I thought I would confirm it any way. Thanks.

**Comment by soichih** [comment]
+1

**Comment by thaJeztah** [comment]
@draghuram I added the linked PR to the 1.8 milestone. Keep in mind that that's no *guarantee* it'll end up on that release :)

**Comment by dexterbt1** [comment]
+1, can't wait to have this up

**Comment by bpesics** [comment]
+1

**Comment by dreamcat4** [comment]
Uhm... so how do we do this then?

```sh
$ docker --version
Docker version 1.8.1, build d12ea79
```

**Comment by cpuguy83** [comment]
See the docs from #11485

**Comment by dreamcat4** [comment]
thanks @cpuguy83 

:)

**Comment by jochenseeber** [comment]
-1

This seems to be a textbook example of "not invented here". Why re-invent log rotation instead of letting the existing and proven logrotate do the job, and just support re-opening log files (see #7333) in docker. Logrotate will always be better at rotating logs, because that's what it's built for.

**Comment by demaniak** [comment]
@jochenseeber - I'm guessing because they are aiming for a measure of cross-platform capability? Windows Server 2016 seems geared to pop out with Docker support - I have no idea what thing will slot into the "logrotate" slot on that platform

**Comment by ricardson** [comment]
+1

**Comment by thaJeztah** [comment]
@ricardson the default (json-file) logging driver allows you to set `--log-opt max-size` and `--log-opt max-files` to limit log file size and rotate logs; is there functionality you're missing? If so can you open a feature request with details? 

I'm locking the conversation on this issue because the options mentioned above are implemented, and commenting on old issues usually leads to those comments being overlooked.
