### ISSUE TITLE
Docker rmi with dangling=true unsafe while images are being pulled

### ISSUE THREAD

**Issue by icksa** [docker/docker#8926]
I was reading the docker documentation (https://docs.docker.com/reference/commandline/cli/), and noticed the following recommendation for batch clean up of dangling images:

```
sudo docker rmi $(sudo docker images -f "dangling=true" -q)
```

I was excited when I saw the dangling=true filter since having large numbers of dangling images was creating problems in our build environment. However, I believe this command is unsafe while pulling images since there there are brief points while images are being pulled when docker considers them dangling. To test this, I ran a script which simply pulls 10 images from our private registry, one after another. While this was running I ran the following command in a separate terminal:

```
while true; do docker rmi $(docker images -q -f "dangling=true"); sleep 1; done
```

I noticed that during the pull process, images were being occasionally deleted. Assuming the pull was successful, I will sometimes tag the image from `<private_registry>/<name>` to just `<name>`. After the end of the pull, all images are listed when I run `docker images`, however when I try to run an affected image, I see something like this:

```
stack@bc03:~$ docker run -ti cassandra
Unable to find image 'cassandra' locally
Pulling repository cassandra
2014/11/03 08:36:01 Error: image library/cassandra not found
```

The image cannot be found since it was retagged to remove the `<private_registry>` part of the name. My hope was that I could run this command automatically every day to clean up any dangling images, but that is not possible since I may accidentally destroy images that are being pulled.

I believe that the dangling=true filter should not show images or components of images that are in the process of being pulled...

**Comment by kostko** [comment]
cc @mitar

**Comment by Mashimiao** [comment]
Hello,
I have sent a PR #11784 trying to fix this issue

**Comment by tiborvass** [comment]
I'm reopening this, since the code that fixed it got removed, and we need an alternative fix and I want this issue to be tracked for 1.10.

**Comment by tonistiigi** [comment]
@tiborvass The pull problem that this issue is desrcibing should be still fixed as there are no intermediate images that could turn up in `dangling=true`. What you are describing is a related issue where parent images could be removed during build, causing the build to error

**Comment by icecrime** [comment]
The issue is solved regarding pull, but still applies to build.

Ping @tiborvass: we should track the build problem in a separate issue.
