### ISSUE TITLE
Problem in HTTPS connection

### ISSUE THREAD

**Issue by alessioguglielmo** [docker/docker#8943]
Hi,
I followed the tutorial to enable HTTPs connection (https://docs.docker.com/articles/https/#daemon-modes) for Docker 1.3, but I've got an error on the client:

Get https://192.168.56.115:2376/v1.15/version: x509: cannot validate certificate for 192.168.56.115 because it doesn't contain any IP SANs

What does that mean?
thanks.
a.g.

**Comment by david-guenault** [comment]
Any news about that ? got the same problem and here is what i did. May be i'm doing things wrong ...

- certificates

```
/usr/bin/openssl req -new -newkey rsa:2048 -days 3650 -nodes -x509 -subj "/C=FR/ST=LR/L=MYCITY/O=MYORG/CN=10.10.0.5" -keyout ca-key.pem -out ca.pem 
/usr/bin/openssl genrsa -out server-key.pem 2048 
/usr/bin/openssl req -subj "/CN=10.10.0.5" -new -key server-key.pem -out server.csr 
/usr/bin/openssl x509 -req -days 3650 -in server.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem 
/usr/bin/openssl genrsa -out key.pem 2048 
/usr/bin/openssl req -subj '/CN=client' -new -key key.pem -out client.csr 
echo extendedKeyUsage = clientAuth > extfile.cnf 
/usr/bin/openssl x509 -req -days 3650 -in client.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out cert.pem -extfile extfile.cnf 
```

- launch docker daemon 

```
sudo /usr/bin/docker -d -D --tlsverify --tlscacert=ca.pem --tlscert=server-cert.pem --tlskey=server-key.pem -H=10.10.0.5:2376
INFO[0000] +job serveapi(tcp://10.10.0.5:2376)          
DEBU[0000] Using graph driver aufs                      
DEBU[0000] Migrating existing containers                
DEBU[0000] Creating images graph       
...
DEBU[0000] Restarting containers...                     
INFO[0000] docker daemon: 1.4.1 5bc2ff8; execdriver: native-0.2; graphdriver: aufs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0) 
```
- launch client 

```
sudo docker -D --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem -H=10.10.0.5:2376 version
Client version: 1.4.1
Client API version: 1.16
Go version (client): go1.3.3
Git commit (client): 5bc2ff8
OS/Arch (client): linux/amd64
FATA[0000] An error occurred trying to connect: Get https://10.10.0.5:2376/v1.16/version: x509: cannot validate certificate for 10.10.0.5 because it doesn't contain any IP SANs 
```

- Last log lines from server 

```
INFO[0000] docker daemon: 1.4.1 5bc2ff8; execdriver: native-0.2; graphdriver: aufs 
INFO[0000] +job acceptconnections()                     
INFO[0000] -job acceptconnections() = OK (0)            
2015/01/30 07:57:23 http: TLS handshake error from 10.10.0.5:50265: remote error: bad certificate
```
- System informations

```
$ uname -a
Linux n54l 3.13.0-44-generic #73-Ubuntu SMP Tue Dec 16 00:22:43 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
openssl version
OpenSSL 1.0.1f 6 Jan 2014
```

**Comment by david-guenault** [comment]
Trying the curl example seems to be working ....

```
/usr/bin/curl --cert cert.pem --key key.pem --cacert ca.pem https://10.10.0.5:2376/images/json
```

**Comment by alessioguglielmo** [comment]
Then I solved the problem, was related to hostname/IP resolving...
You must have an hostname in /etc/hosts that's the same as well as declared in the certification procedure. The hostname must be present in client and server machine

**Comment by david-guenault** [comment]
This does not answer the question why curl work and not docker client ....

**Comment by alessioguglielmo** [comment]
docker needs .docker directory containing CA key, certificate and client private key.
You must then set

$ export DOCKER_HOST=tcp://hostname:2376
$ export DOCKER_TLS_VERIFY=1

Now, if you run 
$ docker ps 
you should see running containers on the server via ''secure'' link

understood?

**Comment by david-guenault** [comment]
Not what i'm talking about. I'm testing tlsverify so the client must auth against the server. If it work with curl client (like i said) it must work with docker client but it is not working.

**Comment by alessioguglielmo** [comment]
Could be a not yet solved bug in Go Language. It doesn't seem support IP specified as CN. Retry the procedure setting your hostname.

**Comment by david-guenault** [comment]
yup it work this way

**Comment by david-guenault** [comment]
my though is client is trying to resolve ip as hostname ... so it fail

**Comment by alessioguglielmo** [comment]
ok, should be a "well-known'' bug in GO, if I remember correctly.

**Comment by david-guenault** [comment]
i think you can close this one ;-)

**Comment by cpuguy83** [comment]
IP Sans get set in tls.ExtraHosts.
Closing since this is not a Docker issue.
