### ISSUE TITLE
allow plus sign in tag names for adding meta data

### ISSUE THREAD

**Issue by tompson** [docker/docker#8944]
I want to create tag names like `myapplication:1.1.0-beta+2c4f57c` but I get the following error:

`2014/11/04 12:52:53 Error response from daemon: Illegal tag name (1.1.0-beta+2c4f57c): only [A-Za-z0-9_.-] are allowed, minimum 2, maximum 30 in length`

Because I want to follow the versioning guidelines of semantic versioning (http://semver.org/) I need to be able to add the + sign in the tag name

**Comment by jfrazelle** [comment]
this is not currently supported by the regex, but I invite you to open a pull request to change it

**Comment by tompson** [comment]
I did in https://github.com/docker/docker/pull/10117

**Comment by jfrazelle** [comment]
After review with @dmp42 we need to wait for support on the hub side first. Then we can tackle this.

**Comment by tompson** [comment]
@jfrazelle did you create an issue for the hub support?

**Comment by jfrazelle** [comment]
Hub is not handled on these issues but I will add a ticket to their tracker :)

**Comment by jfrazelle** [comment]
Added the ticket!

**Comment by tompson** [comment]
@jfrazelle Thanks!

**Comment by tompson** [comment]
@jfrazelle any news on this one?

**Comment by jfrazelle** [comment]
ping @kencochrane

**Comment by tiborvass** [comment]
I don't think this makes sense, I'd much rather support metadata for images rather than abuse tag names.

**Comment by jfrazelle** [comment]
since this is on hub end closing
