### ISSUE TITLE
[DOC] Haskell Docker API tba.

### ISSUE THREAD

**Issue by AnneTheAgile** [docker/docker#8945]
I just found this today; 
 Docker Remote API wrapper for Haskell - a Work in progress ; https://github.com/denibertovic/docker-hs 
The doc page said to add a bug if new API's were discovered :).
https://docs.docker.com/reference/api/remote_api_client_libraries/

**Comment by jfrazelle** [comment]
Adding this would be a easy way for someone looking to get involved with contributing to docker to add to the docs

**Comment by emirozer** [comment]
https://github.com/docker/docker/pull/12399
