### ISSUE TITLE
Proposal: Set owner of files added via ADD/COPY to user set by USER directive

### ISSUE THREAD

**Issue by phylor** [docker/docker#8954]
It would be nice if files added via `ADD/COPY` have the owner set according to the currently applicable `USER` directive.

## Problem
Let's say you use an image which has a `USER` directive set. If you add a file via `ADD` or `COPY`, the file's owner is `root`. You now cannot directly access that file because it is owned by `root`, but you are not `root`.

This is problematic, because you might not be aware of the usage of `USER` in a base image you are pulling from (e.g. an official one). For example, this is the case with the official `tomcat` image. See below for steps to reproduce.

## Reproduce

    mkdir docker-addfilepermission
    cd docker-addfilepermission
    touch test.txt
    echo 'FROM tomcat
    COPY test.txt /usr/local/tomcat/webapps/
    RUN chown tomcat:tomcat /usr/local/tomcat/webapps/test.txt' > Dockerfile

    docker build .

**Output:**

    Sending build context to Docker daemon 3.072 kB
    Sending build context to Docker daemon 
    Step 0 : FROM tomcat
     ---> 44859847ef64
    Step 1 : COPY test.txt /usr/local/tomcat/webapps/
     ---> Using cache
     ---> a2ccb92480a4
    Step 2 : RUN chown tomcat:tomcat /usr/local/tomcat/webapps/test.txt
     ---> Running in 208e7ff0ec8f
    chown: changing ownership of '/usr/local/tomcat/webapps/test.txt': Operation not permitted
    2014/11/01 00:30:33 The command [/bin/sh -c chown tomcat:tomcat /usr/local/tomcat/webapps/test.txt] returned a non-zero code: 1

## Workaround

If you switch to `root` in your Dockerfile, you are able to access the file:

    USER root
    chown tomcat:tomcat /usr/local/tomcat/webapps/test.txt
    USER tomcat

**Comment by tianon** [comment]
Look like this should be closed now based on the discussion in https://github.com/docker/docker/pull/9046 :cry:

**Comment by thaJeztah** [comment]
A PR for a new approach is created here: https://github.com/docker/docker/pull/9934. I created that based on the discussion on #docker-maintainers so that it can be discussed before implementation.

**Comment by jfrazelle** [comment]
closing as dup #9934
