### ISSUE TITLE
 Make the kernel requirement a hard requirement

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#8969]
There is a stalled-closed PR:  #7681  

and an awesome user story - https://forums.docker.com/t/docker-interactive-exec-bash-does-not-show-containers-filesystem/334/4

showing that its important for us to be very obvious about system configurations that appear to be ok, but actually don't work.

Not all consumers of the Docker API have access to the daemon log file - so its possibly better to fail, but perhaps the API needs to report any detectable degredations of Docker-ness.

**Comment by jfrazelle** [comment]
https://github.com/docker/docker/pull/10652 was merged I am going to close
