### ISSUE TITLE
after installed the docker panic: runtime error: index out of range

### ISSUE THREAD

**Issue by TonyWuLihu** [docker/docker#8973]
After I have installed the docker-io on CentOS6.5 and try run docker command , got this error . 

[root@iZ28bz1dcuuZ]# docker
panic: runtime error: index out of range

goroutine 16 [running]:
runtime.panic(0xa02080, 0xfd673c)
	/usr/lib/golang/src/pkg/runtime/panic.c:279 +0xf5
main.main()
	/builddir/build/BUILD/docker-1.2.0/docker/docker.go:99 +0x9ff

goroutine 19 [finalizer wait]:
runtime.park(0x4189e0, 0xfef688, 0xfdaf89)
	/usr/lib/golang/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xfef688, 0xfdaf89)
	/usr/lib/golang/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
	/usr/lib/golang/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
	/usr/lib/golang/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/usr/lib/golang/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall]:
runtime.goexit()
	/usr/lib/golang/src/pkg/runtime/proc.c:1445

goroutine 22 [runnable]:
text/template/parse.lexText(0xc208052900, 0xbcf070)
	/usr/lib/golang/src/pkg/text/template/parse/lex.go:228 +0x381
text/template/parse.(*lexer).run(0xc208052900)
	/usr/lib/golang/src/pkg/text/template/parse/lex.go:198 +0x40
created by text/template/parse.lex
	/usr/lib/golang/src/pkg/text/template/parse/lex.go:191 +0x112

**Comment by unclejack** [comment]
This configuration error seems to have been fixed.
