### ISSUE TITLE
Add a "Known Issues" section to the release notes

### ISSUE THREAD

**Issue by fredlf** [docker/docker#8985]
I'm looking for a way to get a list of bugs or issues that we know about, but aren't fixed yet, that have some impact on the users. The list would get added to the release notes page in the docs. Ultimately, I want to make something similar to this: https://docs.puppetlabs.com/pe/latest/release_notes.html#known-issues. That way, users and other interested parties can go to a single place to see what was built and fixed for a given release. Consolidating known issues on a page makes maintenance much easier and provides a URL to point people to if an issue effects something described elsewhere in the docs.

Here's an example of the sort of thing that would go in this section:

* Due to changes in the registry, `docker pull` will not automatically pull all aliases of an image. For more information, see issue [#8689](https://github.com/docker/docker/issues/8689)

**Comment by thaJeztah** [comment]
Do we still need the "pull all tags" issue? If I understand correctly, that feature may not return in registry V2, in which case it should just be removed from the docs (and code)

I'm happy to make a change to remove those parts from the doc and add a note to the release notes ("feature removed/deprecated").

(Depending on the above), I think this can be closed, as https://github.com/docker/docker/pull/10127 was merged

**Comment by fredlf** [comment]
@thaJeztah I agree that adding KI for older releases would be nice, but would require a ton of historical detective work. After a few iterations, you'll be able to tell what was fixed when by checking release notes for prior releases.

**Comment by jfrazelle** [comment]
yes this is now available on release notes page, but any who comes to this issue is welcome to open a pr and add more to that page if they think it is appropriate

**Comment by fredlf** [comment]
Yes, thanks @jfrazelle!
