### ISSUE TITLE
Creating images with the btrfs driver fills up RAM

### ISSUE THREAD

**Issue by ibab** [docker/docker#9002]
Hi,
After pulling/building images, btrfs occupies massive amounts of RAM.

    $ free -m
    total       used       free     shared    buffers     cached
    Mem:          7430       2076       5353          2          1       1030
    -/+ buffers/cache:       1043       6386
    Swap:            0          0          0

    $ docker pull ipython/scipyserver
    ...

    $ free -m
    total       used       free     shared    buffers     cached
    Mem:          7430       7289        140          1          1       3691
    -/+ buffers/cache:       3596       3833
    Swap:            0          0          0

I'm seeing this on two different Arch Linux machines:

    $ uname -a
    Linux hostname 3.17.2-1-ARCH #1 SMP PREEMPT Thu Oct 30 20:49:39 CET 2014 x86_64 GNU/Linux

Docker info:

    $ docker version
    Client version: 1.3.1
    Client API version: 1.15
    Go version (client): go1.3.3
    Git commit (client): 4e9bbfa
    OS/Arch (client): linux/amd64
    Server version: 1.3.1
    Server API version: 1.15
    Go version (server): go1.3.3
    Git commit (server): 4e9bbfa
    
    $ docker -D info
    Containers: 0
    Images: 53
    Storage Driver: btrfs
    Execution Driver: native-0.2
    Kernel Version: 3.17.2-1-ARCH
    Operating System: Arch Linux
    Debug mode (server): false
    Debug mode (client): true
    Fds: 14
    Goroutines: 20
    EventsListeners: 0
    Init SHA1: 0e7bd7d8d49acc4316b808b5e8692e4b50883867
    Init Path: /usr/lib/docker/dockerinit

The btrfs partition is mounted like this:

    /dev/sda2           	/         	btrfs     	rw,relatime,space_cache	0 0

The RAM usage doesn't show up in top, but can be made visible with slabtop:

    Active / Total Objects (% used)    : 5538765 / 5568356 (99.5%)
    Active / Total Slabs (% used)      : 259447 / 259447 (100.0%)
    Active / Total Caches (% used)     : 76 / 103 (73.8%)
    Active / Total Size (% used)       : 2722303.75K / 2726267.62K (99.9%)
    Minimum / Average / Maximum Object : 0.01K / 0.49K / 15.88K

       OBJS ACTIVE  USE OBJ SIZE  SLABS OBJ/SLAB CACHE SIZE NAME                   
    1927392 1927332  99%    0.96K 120462       16   1927392K btrfs_inode
    1926600 1926600 100%    0.30K  74100       26    592800K btrfs_delayed_node

After rebooting, memory usage is fine and I can use docker as usual.
The memory is also released if I remove the images with `docker rmi` or by deleting the btrfs subvolumes.

I tried reproducing the problem by creating btrfs snapshots with lots of small files, but didn't manage to see the same increase in memory usage, which is why I'm reporting it here.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/8354
