### ISSUE TITLE
[registry] trusted build triggers Illegal Instruction

### ISSUE THREAD

**Issue by steeve** [docker/docker#9003]
Apparently not all EC2 instances are created equal.

When running a previously generated build image on another build, I get this [1]:
```
clang-linux.compile.c++.without-pth bin.v2/libs/date_time/build/clang-linux-darwin/release/link-static/target-os-darwin/threading-multi/gregorian/greg_month.o
Illegal instruction (core dumped) 
"x86_64-apple-darwin14-c++" -c -x c++ -O3 -finline-functions -Wno-inline -Wall  -DBOOST_ALL_NO_LIB=1 -DBOOST_DATE_TIME_STATIC_LINK -DDATE_TIME_INLINE -DNDEBUG -I"." -o "bin.v2/libs/date_time/build/clang-linux-darwin/release/link-static/target-os-darwin/threading-multi/gregorian/greg_month.o" "libs/date_time/src/gregorian/greg_month.cpp"

...failed clang-linux.compile.c++.without-pth bin.v2/libs/date_time/build/clang-linux-darwin/release/link-static/target-os-darwin/threading-multi/gregorian/greg_month.o...
clang-linux.compile.c++.without-pth bin.v2/libs/date_time/build/clang-linux-darwin/release/link-static/target-os-darwin/threading-multi/gregorian/greg_weekday.o
Illegal instruction (core dumped) 
```

Note that `x86_64-apple-darwin14-c++` was also generated via a truted build [2].

[1] https://registry.hub.docker.com/u/steeve/cross-compiler/build_id/23819/code/b394navjjvlxfbm3zm3dgxc/
[2] https://registry.hub.docker.com/u/steeve/cross-compiler/build_id/23819/code/b394navjjvlxfbm3zm3dgxc/ (search for Illegal Instruction)

A solution to this seems to be adding `-march=core2` to ensure a basic instruction set when compiling, and not use the native machine cpu capabilities.

cc @samalba

**Comment by jfrazelle** [comment]
ping @kencochrane is this a hub thing?

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen
