### ISSUE TITLE
tarsum calculation should be resumable

### ISSUE THREAD

**Issue by stevvooe** [docker/docker#9018]
To support chunked or streaming tarsum calculations, it would be desirable to be able to save tarsum state mid-computation. This would allow a tarsum calculation to be saved, then resumed later when the rest of the data is available, similar to other kinds of hash calculations.

The main application for such a change would be to minimize local file buffering and storage layer round trips in the new version of the registry when accepting layer uploads.

Possible API additions include the following methods:

    // State is an opaque representation of a partial tarsum calculation.
    type State <some trivially serializable type, maybe string>

    // ResumeTarSum continues a tarsum calculation on the provided reader using state. The 
    // reader will Seek to the position stored in state and the computation will be resumed.
    ResumeTarSum(rd io.ReadSeeker, state State) (TarSumInterface, error)

And add a state method to `TarSumInterface`:

    type TarSumInterface interface {
        io.Reader
        GetSums() map[string]string
        Sum([]byte) string
        Version() Version

        // State returns an opaque state that can be used to resume a partial tarsum calculation. The
        // returned state is valid even if the tarsum calculation reach io.EOF on the underlying reader.
        State() State
    }

@vbatts @jlhawn

**Comment by jfrazelle** [comment]
can we close? do we even want tar sum anymore?

**Comment by vbatts** [comment]
Seeing that we would like to sunset tarsum, I don't see that we will pursue this feature.

**Comment by stevvooe** [comment]
@vbatts Agreed.

**Comment by jlhawn** [comment]
Hey! So, just for Funzies: https://github.com/jlhawn/tarsum and http://godoc.org/github.com/jlhawn/tarsum

I wrote this about 2-3 months ago but never published it. It's an implementation of TarSum (using sha256) which is resumable and matches the `hash.Hash` interface, so you write to it rather than read through it. All the tests pass too! yay!

**Comment by vbatts** [comment]
Well aren't you just the bees knees. :-)
