### ISSUE TITLE
Error response from daemon: Cannot start container *** file exists

### ISSUE THREAD

**Issue by craigjbass** [docker/docker#9027]
We get these transient failures a lot... and it's frustrating. I would prefer if containers always were successful at being started!

Error response from daemon: Cannot start container a659626bda7bcab0f303bf015bb9a672ee762958928b0e599a633dc06db0bde6: file exists

What are we doing wrong?

**Comment by defunctzombie** [comment]
This is an ongoing issue. Anyone from core team care to help us help you debug this? I have a service deployed to production that fails to restart every few days with a similar error. I will try the `-D` approach on the next failure.

**Comment by jfrazelle** [comment]
well lets see we definitely need some more info :)

docker version
docker info
daemon logs
steps to reproduce

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen

**Comment by defunctzombie** [comment]
I believe this happens if the system runs out of memory and the OOM killer comes around to kill the process. I have not yet tested if this behavior still exists on 1.5
