### ISSUE TITLE
set apparmor profile docker-default: no such file or directory

### ISSUE THREAD

**Issue by WuLonghui** [docker/docker#9059]
Hi,

In my machine(ubuntu 14.04), docker run always failed, after restart docker daemon, it will be fine, but this issue will come back soon.
```
docker run ubuntu env
2014/11/10 11:06:43 Error response from daemon: Cannot start container 41398c949d5e4eae15796f651cf87359a51499e3861f98779e8f326eadc08235: set apparmor profile docker-default: no such file or directory
```

docker version
```
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa
```

docker info
```
Containers: 6
Images: 55
Storage Driver: devicemapper
 Pool Name: docker-253:1-133807-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 14.62 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 11.02 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-27-generic
Operating System: Ubuntu 14.04 LTS
WARNING: No swap limit support
```

Any info is ok,Thanks in advance!!

**Comment by jfrazelle** [comment]
@vbatts is this a duplicate device mapper issue

**Comment by vbatts** [comment]
@jfrazzle it is not. The devmapper issue is on finding the /dev/ device for the container. This looks to be something in apparmor profile. I have not seen this before.

**Comment by vbatts** [comment]
Github android client doesn't complete usernames... @jfrazelle ...

**Comment by jfrazelle** [comment]
lolol no prob

**Comment by jfrazelle** [comment]
@WuLonghui can you try with the master version of docker, you can download binaries from master.dockerproject.com

**Comment by unclejack** [comment]
`Kernel Version: 3.13.0-27-generic` is an ancient version of the `3.13.0-xx` kernel. The current version is `3.13.0-45` right now.

The system needs to be fully updated before this issue can be fixed: `apt-get update && apt-get dist-upgrade -y`. The `apparmor` package should also be installed using `apt-get install apparmor`.

@WuLonghui Please install all updates for your system using the instructions above, install apparmor and check if you're still running into this problem.

**Comment by WuLonghui** [comment]
I tried any times, but it does not work.
I check the code, and then disable apparmor.
```
chmod 6 /sys/module/apparmor/parameters/enabled
echo N > /sys/module/apparmor/parameters/enabled
chmod 4 /sys/module/apparmor/parameters/enabled
```

**Comment by Starefossen** [comment]
I have gotten a ton of these errors lately. Does anyone have a better fix for this?

**Comment by genisd** [comment]
I'm facing this issue right now. Got no idea where it's coming from or how to solve it

**Comment by genisd** [comment]
It turns out that docker expects the apparmor profile to be loaded and enforce.
I had the docker profile symlinked to /etc/apparmor.d/disable/docker

Removing the symlink and restarting apparmor fixed the issue for me

**Comment by jeunito** [comment]
This bit me today. Fix by @genisd worked for me too. Wondering what puts that symlink there.

**Comment by genisd** [comment]
@jeunito  in my case I did it myself. We have dockers that expect apparmor to run and those that expect to be excempt from apparmor

**Comment by helvete** [comment]
Thanks guys for insights. I neede to upgrade kernel to 3.10 at Ubuntu 12.04, this caused apparmor error like @wulonghui suggested. Ignoring all apparmor rules and deactivationg the module itself helped.
