### ISSUE TITLE
VOLUME owner

### ISSUE THREAD

**Issue by tcurdt** [docker/docker#9070]
I am mounting a data volume on an image `docker run --name mongodb --volumes-from mongodb-data ...`. The image should adjust the ownership:

    RUN chown mongodb.mongodb /data/mongodb
    VOLUME /data/mongodb

or

    VOLUME /data/mongodb
    RUN chown mongodb.mongodb /data/mongodb

But neither works. I have to log into the container and execute `chown mongodb.mongodb /data/mongodb` myself for the ownerships to actually be applied.

Documentation in this area really needs work. It just doesn't cover permissions and ownerships at all.

**Comment by aidanhs** [comment]
This is really unintuitive, it'd be good to have some docs.

Ok:
```
$ cat Dockerfile
FROM ubuntu:14.04
RUN mkdir -p /www123/abc && chown -R www-data: /www123 && ls -l /www123
VOLUME /www123/abc
RUN ls -l /www123
$ docker build .
[...]
Step 0 : FROM ubuntu:14.04
[...]
Step 1 : RUN mkdir -p /www123/abc && chown -R www-data: /www123 && ls -l /www123
[...]
total 4
drwxr-xr-x 2 www-data www-data 4096 Feb 20 15:49 abc
[...]
Step 2 : VOLUME /www123/abc
[...]
Step 3 : RUN ls -l /www123
[...]
total 4
drwxr-xr-x 2 www-data www-data 4096 Feb 20 15:49 abc
[...]
```

Not ok:
```
$ cat Dockerfile 
FROM ubuntu:14.04
VOLUME /www123/abc
RUN mkdir -p /www123/abc && chown -R www-data: /www123 && ls -l /www123
RUN ls -l /www123
$ docker build .                                                                                  
[...]
Step 0 : FROM ubuntu:14.04
[...]
Step 1 : VOLUME /www123/abc
[...]
Step 2 : RUN mkdir -p /www123/abc && chown -R www-data: /www123 && ls -l /www123
[...]
total 4
drwxr-xr-x 2 www-data www-data 4096 Feb 20 15:52 abc
[...]
Step 3 : RUN ls -l /www123
[...]
total 4
drwxr-xr-x 2 root root 4096 Feb 20 15:52 abc
[...]
```

Note the perm change.

**Comment by cpuguy83** [comment]
Closing since this really came down to being a duplicate around how `VOLUME` is handled.

**Comment by aidanhs** [comment]
So...do I need to raise a new issue for my comment above?

**Comment by cpuguy83** [comment]
@aidanhs No, it's already captured in a number of places... including #3639
