### ISSUE TITLE
sftp get messages too long when forwarding from host to container using ssh

### ISSUE THREAD

**Issue by cgcgbcbc** [docker/docker#9087]
Since `exec` is introduced with docker 1.3, I can add `command="docker exec -ti <container> bash"` before a ssh key in `~/.ssh/authorized_keys` in host, and the `ssh -i <identity> user@host` works well, but as for `sftp`, it gets `Received message too long 1581478511`, and I also test `scp`, it will pause without any output.

**Comment by jfrazelle** [comment]
Hi I would suggest you checkout forums.docker.com for docker support or #docker on irc I do not think this is a problem with docker itself

**Comment by bendenoz** [comment]
Have been trying to do the same thing... try removing "-t", ie : `` docker exec -i <container> bash ``
for sftp, you should not run bash but /usr/lib/openssh/sftp-server
