### ISSUE TITLE
git fetch-pack hangs inside a docker container

### ISSUE THREAD

**Issue by ktf** [docker/docker#9088]
Hi,

I'm trying to run:

```
git fetch-pack --stateless-rpc --thin https://github.com/ktf/cmsdist.git refs/heads/openloops
```

inside a boot2docker container, running centos6 and I get stalled on a read. Is this a known issue?

**Comment by jfrazelle** [comment]
cannot reproduce on latest, probably bad version of git in container, I do not think this is a issue with docker itself
