### ISSUE TITLE
Multiple parallel loads (even of the exact same image) can easily overwhelm available disk space

### ISSUE THREAD

**Issue by rhatdan** [docker/docker#9094]
Wanted to open a discussion on this from a Red Hat Bugzilla

https://bugzilla.redhat.com/show_bug.cgi?id=1162742

Description of problem:
Loading a single docker image requires double (1.3.0) or triple (1.2.0) it's size to load. Therefore multiple parallel loads (even of the exact same image) can easily overwhelm available disk space.  If docker's storage is located on the "/" filesystem, unpredictable failures are possible.  This is possibly made worse by bugzilla #1132388 (or similar), where temporary load data is not cleaned up until minutes later.

Steps to Reproduce:
1. docker save registry.access.redhat.com/rhel7:0-23 > img.tar
2. for i in $(seq 1 10); do docker load < img.tar & done
3. watch -i 1 -d df

Actual results:
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda2       8.3G  7.9G     0 100% /

Expected results:
Disk doesn't fill up.  When possible, loads that would exceed storage capacity should return an error status/message rather than blindly filling up the disk.

Additional info:
Suggest some kind of queuing/scheduling system where only a fixed number of loads proceed in parallel, the remaining block until the first batch are finished, then proceed only if there is sufficient space (when checking is possible).

Should we only allow 1? 5? X? number of pulls/loads at a time to make sure we don't run out of space and then queue the rest?

**Comment by shishir-a412ed** [comment]
https://github.com/docker/docker/pull/9970

**Comment by crosbymichael** [comment]
This has been merged for 1.5
