### ISSUE TITLE
Proposal: document and implement a set of rules for Proposals 

### ISSUE THREAD

**Issue by monadic** [docker/docker#9114]
The Proposals process is a little opaque to me, and possibly to others.

A set of rules could clarify matters, answering questions such as:

a. What does it take for a Proposal to become part of Docker? 
b. What does it take for a Proposal to be deemed 'dead'?

@erikh asked that we cite: https://github.com/docker/docker/blob/master/CONTRIBUTING.md#design-and-cleanup-proposals 

OK...

To start the ball rolling, here are some proposed rules:

(1) Label all Proposals with one of three 'stages': RFC, Incubated, Final
(2) Maintainers decide when a proposal moves to Incubated or to Final - and will provide a rationale in writing
(3) All Incubated & Final proposals have at least two maintainers officially attached to them as 'proposal sponsors'
(4) A proposal may not become Final unless there is running code demonstrating the claims of the proposal
(5) Maintainers appoint a team to clean up and delete dead proposals.
(6) Proposal authors must state who they work for (or which open source project they represent).

In the discussion please modify this list :-)

In general here are some guidelines on processes like this, that may help people...  I am indebted to @acolyer for providing this input:

A set of rules should demonstrate:

* Openness (who gets to see what, when - this is the easiest of the five!)
* Fairness (what constitutes 'fair'? If a company dedicates more resource, should they have more say? How do individuals or smaller companies get their voice heard?, and so on.)
* Conceptual Integrity (how do you maintain overall coherence with many contributors and ideas? how do you prevent design-rot and bit-rot over time?)
* Velocity (how fast do you want the project to move? how do you trade this off against e.g. a desire for conceptual integrity? how do you keep everyone pulling together for maximum community impact?)
* Boundaries (where do you draw the line between what the project(s) is/are going to do, and what is out of scope? Having clearly delineated scope can save a lot of debate down the line).

There are no 'right' answers to these questions.  The community works it out.

-- alexis

**Comment by jfrazelle** [comment]
closing as https://github.com/docker/docker/pull/9137 but @monadic let me know if you think otherwise, you can also submit a pr to that page
