### ISSUE TITLE
Docker Registry SSL CA cert failing to be read

### ISSUE THREAD

**Issue by sthulb** [docker/docker#9118]
Hi there,

### Background
A registry running behind a reverse proxy (Apache 2.2). The proxy is responsible for terminating SSL on port 443 using TLS. The SSL certificates in use are self-signed and we authenticate with client certificates.

### Problem
In Docker 1.3.0, docker accepted our self signed certificates as long as they had been setup in `/etc/docker/certs.d/registry.host/{client.cert, client.key, registry.host.crt}`.

In Docker 1.3.1, the behaviour has changed to look for `/etc/docker/certs.d/registry.host/ca.crt` (which would be fine, if it actually read the file).

as far as I can conclude, the ca certificate isn't read. I can `curl` my registry using the client certificates and the CA certificate fine.

Instead of a connecting, I'm told to use `--insecure-registry` or put a CA cert in the "correct" place.

**Comment by SvenDowideit** [comment]
another report: https://groups.google.com/forum/#!topic/docker-user/mpDkBojFmWw

**Comment by housebolt** [comment]
Same problem here using OSX boot2docker 1.4.1 build 86f7ec8 on a private repository w/self-signed certificate.

I spent a few hours trying to figure this out and then finally just resorted to appending the CA certificate to the /etc/ssl/certs/ca-certificates.crt file via /var/lib/boot2docker/bootlocal.sh like mentioned above. It worked but is a bit hacky IMO.

Also, I should mention that adding --insecure-registry to EXTRA_ARGS didn't work for me either

**Comment by carn1x** [comment]
I wrote the following shell script to be run on OSX which defines bootlocal.sh on the boot2docker instance:

Step 1 - Create the shell script (e.g.: prepare_boot2docker_ca.sh). It assumes that you have the CA cert which you used to sign your self-signed certificate in the current directory named docker-registry-ca.crt:

<code>
#!/bin/sh
CA_FILE="docker-registry-ca.crt"
# SCP on OSX requires uppercase -P, whilst SSH requires lowercase -p
B2D_KEY="/Users/myusername/.ssh/id_boot2docker"
B2D_HOST="docker@localhost"
# Turn off StrictHostKeyChecking since this needs to be automated.
B2D_SCP="-o StrictHostKeyChecking=no -i ${B2D_KEY} -P 2022"
B2D_SSH="-o StrictHostKeyChecking=no -i ${B2D_KEY} -p 2022 ${B2D_HOST}"
B2D_LIB="/var/lib/boot2docker"
B2D_SH="${B2D_LIB}/bootlocal.sh"
B2D_LIB_CA="${B2D_LIB}/docker-registry-ca.crt"
B2D_CA_DIR="/etc/docker/certs.d/my.registry.com:5000"
DOCKER_IP="1.2.3.4"
DOCKER_HOST="my.registry.com"

scp $CA_SOURCE $CA_FILE
scp ${B2D_SCP} $CA_FILE $B2D_HOST:
ssh ${B2D_SSH} "sudo mv ${CA_FILE} ${B2D_LIB_CA}"
ssh ${B2D_SSH} "sudo sh -c \"cat /dev/null > ${B2D_SH}\""
ssh ${B2D_SSH} "echo \"#!/bin/sh\"                                                                       | sudo tee -a ${B2D_SH}"
ssh ${B2D_SSH} "echo \"mkdir -p ${B2D_CA_DIR}\"                                                          | sudo tee -a ${B2D_SH}"
ssh ${B2D_SSH} "echo \"sudo cp ${B2D_LIB_CA} ${B2D_CA_DIR}/ca.crt\"                                      | sudo tee -a ${B2D_SH}"
ssh ${B2D_SSH} "echo \"sudo tee -a /etc/ssl/certs/ca-certificates.crt < ${B2D_LIB_CA} > /dev/null 2>&1\" | sudo tee -a ${B2D_SH}"
ssh ${B2D_SSH} "echo \"sudo cp ${B2D_LIB_CA} /etc/ssl/certs\"                                            | sudo tee -a ${B2D_SH}"
ssh ${B2D_SSH} "echo \"echo \\\"${DOCKER_IP} ${DOCKER_HOST}\\\" | sudo tee -a /etc/hosts\"               | sudo tee -a ${B2D_SH}"
ssh ${B2D_SSH} "sudo chmod +x ${B2D_SH}"
ssh ${B2D_SSH} "sudo ${B2D_SH}"
</code>

Step 2: Run it:

<code>
$ sh prepare_boot2docker_ca.sh
</code>

Step 3: Restart boot2docker instance:

<code>
$ boot2docker restart
</code>

**Comment by sthulb** [comment]
It would be awesome if we could get a fix for this. My registry pretty much only "secured" by iptables at the moment.

**Comment by jfrazelle** [comment]
ping @dmcgowan @dmp42 I think this is a docs issue?

**Comment by sthulb** [comment]
@jfrazelle how so?

**Comment by jfrazelle** [comment]
I pinged registry team who should know better sorry

**Comment by dmp42** [comment]
Ok: does using the script from https://github.com/docker/docker/issues/9118#issuecomment-67638304 work and fix the issue?

Seems to me indeed like the documentation need some love. Either way, probably @tiborvass can shed some light on this?

**Comment by sthulb** [comment]
It didn't fix it for me.

**Comment by dmp42** [comment]
@sthulb can you confirm you are specifying the port in the path?

`/etc/docker/certs.d/registry.host/ca.crt` (in your initial comment)

vs. (should be)

`/etc/docker/certs.d/registry.host**:PORT**/ca.crt`

**Comment by sthulb** [comment]
I tried 443 in the path.

**Comment by tiborvass** [comment]
@sthulb ping me on IRC (tibor) next week I'll see what I can do.

**Comment by sthulb** [comment]
@tiborvass wilco! Thanks!

**Comment by olibob** [comment]
I just ran in this issue with a self signed certificate.

- access via a browser: OK (accepting the self signed cert)
- access via `curl --cacert` : OK
- access via `docker login` : NOK
- access via `docker login` after  #9118 (comment) : NOK

So close!

**Comment by sthulb** [comment]
I've started to do some debugging for this. 

I can confirm that the CA cert is being read, and added to `x509.CertPool`, which in tern is passed to `tls.Config`. The connection is terminated with: `local error: no renegotiation.` (which is triggered by the Go stdlib)

**Comment by sthulb** [comment]
I've been debugging this all morning, I've started by pulling out the request code from the registry to isolate the cause.

Gist: https://gist.github.com/sthulb/ab6f3c25afd555400df1

In my debugging, I've found out that it's a bug in Go and probably won't be fixed any time soon. 

Go issue: golang/go/5742

@tiborvass I guess you can close this issue if you want.

**Comment by tiborvass** [comment]
I'm not 100% sure, but it is indeed likely that it's not a docker issue. I'll keep the issue open until we have certainty.

**Comment by huslage** [comment]
I don't see how we would be forcing a renegotiation if go doesn't even support it in the first place. How would we hit a bug that we can't cause, exactly? Or am I missing something?

**Comment by tiborvass** [comment]
@huslage with a reverse-proxy that supports the feature.

**Comment by huslage** [comment]
Then the docker daemon wouldn't be terminating the TLS at all right? This issue doesn't seem to mention a proxy anywhere so I'm just confused.

**Comment by huslage** [comment]
Got it. So we don't support something else terminating SSL for us unless it doesn't do renegotiation. This seems to then be a config issue on the proxy more than a bug with docker itself. Correct?

**Comment by tiborvass** [comment]
@huslage quite likely, we'll see as the investigation goes.

**Comment by matthughes** [comment]
FWIW This does work for me in 1.5.0 on Ubuntu.  It wasn't with 1.3.1.

**Comment by bluefeet** [comment]
I just ran into this issue as well:

```
: docker -v
Docker version 1.6.0, build 4749651
: boot2docker version
Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9
```

```
: docker login https://docker.example.com/v2/
Username: aran
Password: ...
Email: aran@example.com
FATA[0015] Error response from daemon: invalid registry endpoint https://docker.ziprecruiter.com/v2/: https://docker.example.com/v2/ does not appear to be a v2 registry endpoint. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry docker.ziprecruiter.com` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/docker.example.com/ca.crt
```

I did copy my certificate into `/etc/docker/certs.d/docker.example.com/ca.crt` and it made no difference.  Very frustrating, especially after reading this thread.  I'll try the script hack, but this seems like the kind of thing that should just work if the CA is already installed on the system as others have said.  Also, I hesitate getting other developers onto docker if they have to hack their systems so much to use the private registry.

**Comment by matthughes** [comment]
@bluefeet Try dropping /v2/.  I don't believe that is valid.  Client is going to try to append /v2/ first and then /v1/.  You're probably getting double /v2/v2/

**Comment by bluefeet** [comment]
I did try that, but it gives me a `404`:

```
FATA[0019] Error response from daemon: (Code: 404; Headers: 
map[Content-Type:[text/plain; charset=utf-8] Content-Length:[19] 
Connection:[keep-alive] Docker-Distribution-Api-Version:[registry/2.0] 
Server:[nginx] Date:[Thu, 23 Apr 2015 15:04:17 GMT]])
```

Which is also what the registry daemon gives me when I hit the same URL with my browser.

**Comment by bluefeet** [comment]
I tried `boot2docker ssh` and creating a `/var/lib/boot2docker/profile` with:

```
#!/bin/sh
EXTRA_ARGS="--insecure-registry"
```

And then:

```
: docker login https://docker.example.com/
Username: aran
Password: ...
Email: aran@example.com
FATA[0017] An error occurred trying to connect: Post 
https://192.168.59.103:2376/v1.18/auth: tls: oversized record received with length 20527
```

Seems adding the profile file, per https://github.com/boot2docker/boot2docker/blob/master/doc/FAQ.md, actually breaks things.  Every docker command I run produces that error.  That FAQ, btw, seems to say that there should already be a profile file, but there was not one on my boot2docker vm.  And its definitely the 1.6.0 VM, says so when I ssh in.

**Comment by sunadm** [comment]
I just ran into this issue as well:

<pre><code>Client version: 1.6.0
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 4749651
OS/Arch (client): linux/amd64
Server version: 1.6.0
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 4749651
OS/Arch (server): linux/amd64</code></pre>

<pre><code>docker push myregistry.com:5000/dianjia_virgo:0.7
FATA[0014] Error response from daemon: v1 ping attempt failed with error: Get https://myregistry.com:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry myregistry.com:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/myregistry.com:5000/ca.crt</code></pre>

the same configuration works well at another machine, just linux kernel different.
and ..... in this machine 12days ago , it's works well too...

**Comment by sunadm** [comment]
aha, I found a reason causes this problem, that is Proxy

If you setup Docker client works under proxy, then Docker client may cannot pass the ca.crt to Registry Server.

So, when I commented the line like following from /etc/default/docker, all things works fine again:

<pre><code>export http_proxy=...</code></pre>

**Comment by lunarfs** [comment]
Had a similar problem, in our case the DNS server had changed, but docker cached the old server, restarting docker server after changing the DNS server resolved the issue.

**Comment by fjmanso** [comment]
problem in http_proxy, confirmed.
Now, now can we add a NONPROXY in ubuntu?
in SLES 12 I do the following
#cat > /etc/systemd/system/docker.service.d/http-proxy.conf<<EOS
[Service]
Environment="HTTP_PROXY=http://my_proxy.com:80/" "NO_PROXY=localhost,127.0.0.0/8,my_local_registry1.com,my_local_registry2.com"
EOS

In Ubuntu I do not know how to do that under /etc/default/docker

Any help?

**Comment by phpguru** [comment]
I cannot make the simplest examples for running docker with `--insecure-registry` work at all on CentOS 6.5, after hours of experimentation, fiddling, upgrading to the latest versions. No proxy, just following the docs for running a registry.

~~~
[root@docker ~]# ps aux | grep docker
root      9322  0.0  0.3 334548 14752 ?        Sl   09:43   0:00 docker -d --insecure-registry docker-registry:5000
[root@docker ~]# docker run hello-world
INFO[0007] POST /v1.18/containers/create                
INFO[0007] +job create()                                
No such image: hello-world (tag: latest)
INFO[0007] -job create() = ERR (1)                      
ERRO[0007] Handler for POST /containers/create returned error: No such image: hello-world (tag: latest) 
ERRO[0007] HTTP Error: statusCode=404 No such image: hello-world (tag: latest) 
Unable to find image 'hello-world:latest' locally
INFO[0007] POST /v1.18/images/create?fromImage=hello-world&tag=latest 
INFO[0007] +job pull(hello-world, latest)               
INFO[0007] +job resolve_repository(hello-world)         
INFO[0007] -job resolve_repository(hello-world) = OK (0) 
INFO[0007] +job trust_update_base()                     
INFO[0007] Trust graph fetch failed: Get https://dvjy3tqbc323p.cloudfront.net/trust/official.json: x509: certificate signed by unknown authority 
INFO[0007] -job trust_update_base() = OK (0)            
Pulling repository hello-world
Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate signed by unknown authority
INFO[0007] -job pull(hello-world, latest) = ERR (1)     
FATA[0000] Get https://index.docker.io/v1/repositories/library/hello-world/images: x509: certificate signed by unknown authority 
[root@docker ~]# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
~~~

**Comment by dmp42** [comment]
@phpguru 

`docker run hello-world` has nothing to do with your private registry. It will fetch an image from the hub.

Furthermore, certificate verification fails for both Cloudfront and index.docker.io, which points to a clear problem in your host root CA store.

Ping @dmcgowan

**Comment by phpguru** [comment]
@dmp42 I've definitely screwed things up! No question. The thing is, I'm trying to use docker commands on a box that I intend to use to host the docker registry, and managed to (a) fail to run the registry correctly (b) fail to find documentation on how to run the registry even in test mode without https (c) break docker almost completely following info online that appears to offer solutions. I tried to use a self-signed cert and act as CA to no avail, just wishing it was all clear and simple. This was, naturally, after failing to get --insecure-registry flag to work at all.

**Comment by dmp42** [comment]
@phpguru I would recommend you start fresh, and follow the new version of the documentation available here:

https://github.com/docker/distribution/blob/master/docs/index.md

and more specifically:

https://github.com/docker/distribution/blob/master/docs/deploying.md

Do all the steps, and you should get there.

And buying a cheap certificate for your domain may save you a lot of trouble :)

**Comment by waynew** [comment]
I just ran into this problem and it turned out it was because I was missing the common name in my self-signed cert. That may or may not be relevant to the problems that others are having.

**Comment by aqtcole** [comment]
I can reproduce as well with a self-signed cert:

```
[ec2-user@ip-10-106-24-229 ~]$ docker pull 10.106.24.170:5002/my-thing
FATA[0000] Error response from daemon: v1 ping attempt failed with error: Get https://10.106.24.170:5002/v1/_ping: x509: cannot validate certificate for 10.106.24.170 because it doesn't contain any IP SANs. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.106.24.170:5002` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.106.24.170:5002/ca.crt 
[ec2-user@ip-10-106-24-229 ~]$ curl --cacert /etc/docker/certs.d/10.106.24.170\:5002/ca.crt https://10.106.24.170:5002/v2/
{
  "errors" : [ {
    "status" : 401,
    "message" : "Unauthorized"
  } ]
}[ec2-user@ip-10-106-24-229 ~]$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.3.3
Git commit (client): 7c8fca2/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): 7c8fca2/1.6.2
OS/Arch (server): linux/amd64
```

So ca.crt is in the place docker wants it, and it works with curl, but not docker. The CN of the cert is 10.106.24.170.

**Comment by sawalls** [comment]
It looks like there are a lot of different bugs being discussed here.
I just wanted to say for posterity that if @jfrazelle's workaround in https://github.com/docker/docker/issues/9118#issuecomment-65712962 DID help you, then the bug you want to watch is: #12756.

The TLS renegotiate / proxy thing seems totally different.

**Comment by matthewjosephtaylor** [comment]
No new discussion on this since Aug 20.  The docker daemon doesn't seem to be reading the ca.crt file.  Had to use the --insecure-registry to get self-signed certs to work.  Is this being worked on at all?

**Comment by gmdodd** [comment]
So for me, I install Docker Tools on OSX with virtualbox. It runs fine until I restart the virtualbox default image. Then I get the X509 certificate error. 

Is the current solution to use a real certificate for my domain for the registry?

**Comment by phpguru** [comment]
@gmdodd I've had that issue. Check your VirtualBox version and docker version, and if you've edited your ~/.bash_profile to create environment vars, they may be outdated (I got this when I was doing a lot of testing between boot2docker, vagrant-docker-box and docker quick start terminal since they all use slightly different IPs.) Try to ssh into the VM, or poke around the quick start terminal and find the generated keys, then get them on your host/local and ensure the paths are correct in your environment. For Docker QuickStart Terminal, I have the following:

~~~
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/<my_username>/.docker/machine/machines/default"
export DOCKER_MACHINE_NAME="default"
~~~

I can force certificate errors if the certs generated by Docker are not in that path, or not readable. HTH!

**Comment by gmdodd** [comment]
Thanks - I'll give that a try - when i've hit this problem, I've been cleaning house, re-installing the Docker toolkit and recreating all my containers and images using a script - its pretty easy, but i'd like to figure out what is going on, thanks for the pointers - i'll let you know how i get on.

**Comment by phemmer** [comment]
So what is the problem we want this issue to track? I was looking through the issue list to find something interesting to work on, but I can't figure out what this one is actually for.
I see several things:
* a documentation issue in regards to intermediate certs. (which I'd argue belongs in https://github.com/docker/distribution since it's a server configuration issue).
* some sort of boot2docker issue (not sure what since I've never used boot2docker).
* an issue with tls renegotiation.
* an issue with IPs being in the cert CN.

**Comment by aqtcole** [comment]
@phemmer the problem is that docker error messages instruct you to place the certificate at /etc/docker/certs.d/\<host\>/ca.crt but docker actually ignores this file. If the documentation says the same thing then that is a secondary issue along with any other issue.

**Comment by phemmer** [comment]
@aqtcole The issue you reported here is [https://github.com/docker/docker/issues/9118#issuecomment-130471494] is the already covered issue with IPs being in the CN. Docker is not ignoring the file.

**Comment by aqtcole** [comment]
Thanks @phemmer. To the best of my recollection I experienced the same issue after naming my host, but that was with docker 1.6. I just tried with docker 1.7 and I cannot reproduce the issue (with a hostname -- did not try with a bare IP). So imo this issue can be closed. What do you say @sthulb?

**Comment by HuKeping** [comment]
I can confirm @tiborvass 's solution

> FYI, If I want to pull myregistry:5000/busybox, I have to put the cert in /etc/docker/certs.d/myregistry:5000/ca.crt (note the :5000).

This `:5000` is required.

**Comment by sthulb** [comment]
@aqtcole: So, I'm kind of happy to close this bug after ~1 year. 

My original problem was to do with TLS renegotiation issues in Golang (https://github.com/golang/go/issues/5742). At the time, Golang didn't implement renegotiation because there wasn't a standard for it. I'm happy for this issue to be closed, as the fix will come in Go it's self and not Docker.

I guess this issue has evolved into something else, the path thing mentioned by numerous different people works for sure.

**Comment by tiborvass** [comment]
@sthulb thank you very much :)

**Comment by aliok** [comment]
I still have this problem on my Mac. 

I am sorry, it would probably take 2 hours to read everything in this thread. Could someone verify these:

* no fix yet with the proper solution (having CA certificate in `/etc/docker/certs.d/***/ca.crt`)
* workaround is adding the CA certificate as trusted in the docker-machine VM
* passing the `--insecure-registry the-domain:12345` flag also works (although I don't know where)

Thanks

**Comment by aliok** [comment]
Maybe it helps people who came across this issue while Googling:

I made it working by using the `--insecure-registry` option. In Docker daemon machine I had to append following to `/var/lib/boot2docker/profile`

    EXTRA_ARGS="$EXTRA_ARGS --insecure-registry https://the-domain:5043"

Unlike suggested by Docker daemon, it didn't work without `https` written in that line.

**Comment by tinganho** [comment]
I also ran into this problem.

Don't forget to `chmod` your CA certificate correctly. At least it worked for me. Would be awesome if there where any error for that. :rose: 

```
chmod 400 /etc/docker/certs.d/myregistry:5000/ca.crt
```
