### ISSUE TITLE
Proposal: Hooks for before/after actions in docker build/run

### ISSUE THREAD

**Issue by victorcampos** [docker/docker#9125]
Adding hooks for simple script execution as before/after tasks seems a step in the way I've thought could simplify a common workflow: before building an image I need sometimes to copy configuration files and run build scripts depending on the type of environment I'll deploy to.

At the moment I'm using a mix of shell and python scripts, every project deployed with Docker has some kind of copy of a common set of these scripts (the wrapper script around `docker build` is one of them) and a simple before/after hook mechanism could greatly simplify this scenario.

I'm aware of confd and some cluster management tools but they're overly complicated for most of my use cases, I'm also aware of plugins' proposal at #8968 and probably this kind of hook could be implemented as a plugin from that proposal (the messaging bus/system seems to be able to support before/after command runs messages), but I thought that a simpler mechanism can exist before full support for plugins is built-in.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/6982
