### ISSUE TITLE
docker client can't read from both "docker private registry" and "online docker registry" if custom ssl certificate are used

### ISSUE THREAD

**Issue by adeelahmadch** [docker/docker#9166]
Docker version 1.2.0, build 2a2f26c/1.2.0
docker registry 0.8.1

i setup docker private registry on cenots7 and created my custom ssl cert. when I try to access my docker registry using https I get x509: certificate signed by unknown authority. i found a solution for this by placing the cert file under "/etc/pki/tls/certs" then do "update-ca-trust" and "service docker restart" now it started to read my certificate.i can login and pull and push to docker private registry. 

now when i tries to read from online docker registry(https://index.docker.io/v1/search?q=centos) i get "Error response from daemon: Get https://index.docker.io/v1/search?q=centos: x509: certificate signed by unknown authority". i exported docker.io cert from firefox brower and put it under "/etc/pki/tls/certs" then do "update-ca-trust" and "service docker restart" but same error. it looks like docker client cant decide which cert to use for which repository. 

Any ideas how we can fix x509: certificate signed by unknown authority for online docker registry while using your own docker private registry.

**Comment by jfrazelle** [comment]
ping @dmp42 @dmcgowan @jlhawn

**Comment by dmp42** [comment]
Private registries with self-signed certificates configuration is described here: `https://docs.docker.com/reference/commandline/cli/#insecure-registries`

I'm closing this for now - let me know if the provided instructions work, or if you still have an issue there.
