### ISSUE TITLE
.dockerignore should a support including ignored content

### ISSUE THREAD

**Issue by maxandersen** [docker/docker#9171]
If the only thing you want in your dockerfile is the Gemfile of a project it is tedious to use .dockerignore to exclude everything manually.

With .gitignore there is support for including things allowing you to do:

```
/*
!/Gemfile
!/Gemfile.lock
```
Having similar for dockerignore would be very nice.

more background: http://stackoverflow.com/questions/5533050/gitignore-exclude-folder-but-include-specific-subfolder

**Comment by langri-sha** [comment]
:+1: for adding the ability to inverse ignore patterns with `!`; really finding it unexpected and awkward that such support is missing :pensive:!

**Comment by apheleia** [comment]
+1

**Comment by wyaeld** [comment]
@maxandersen I'm curious... how are you using Docker with ruby that you end up ignoring anything except the Gemfile & lock?  Thats not a pattern I think I've seen before

No critique on the proposed change, consistency is good... at the time I know just getting something into docker was the overriding priority.

**Comment by langri-sha** [comment]
@wyaeld I believe this happens with images for applications which use package managers, when you want to eagerly resolve all the dependencies required to run the application's process with the container once the image is pulled by the host

**Comment by maxandersen** [comment]
@wyaeld I basically just want a docker image with all the dependencies fetched and configured. 

The actual content of the project I mount as a volume and no need to have the docker image contain this content as duplicated.

**Comment by hairyhenderson** [comment]
+1! This has been a huge pain point for me recently. Given so many other parallels with git, it'd be great (and much less confusing) if `.dockerignore` had the same syntax as `.gitignore`

**Comment by buddhamagnet** [comment]
#dibs

**Comment by duglin** [comment]
@buddhamagnet you may want to check on the status of https://github.com/docker/docker/pull/10349

**Comment by buddhamagnet** [comment]
Ah OK! Out of interest I started with the ReadDockerIgnore function in utils.go as it seemed more specific to this issues. Oh well!

**Comment by duglin** [comment]
I haven't looked into that PR (yet) but if you think there's a better approach feel free to chime-in over there!

**Comment by etki** [comment]
Another soul waiting for feature +1

**Comment by duglin** [comment]
Actually, its already in - see #12245

**Comment by mrcoles** [comment]
What version of docker is this in? It shows up as a feature [in the docs](https://docs.docker.com/reference/builder/#dockerignore-file), but not mention of when/what version it’s in?

**Comment by mrcoles** [comment]
OK—I found it: [1.7.0 (2015-06-16)](https://github.com/docker/docker/blob/master/CHANGELOG.md#170-2015-06-16)

**Comment by kayabendroth** [comment]
Awesome.  :thumbsup:

**Comment by tugberkugurlu** [comment]
> +1 on making .dockerignore act the same as .gitignore. After all, I think this is what people expect?

@thaJeztah is this the case today? I am seeing a lot of weirdness while trying ignore a folder and its entire content.
