### ISSUE TITLE
Proposal - Build multiple images from a single repository

### ISSUE THREAD

**Issue by icecrime** [docker/docker#9198]
_Sorry for this not being a doc first proposal: I’d like to go through the design before proceeding with the documentation itself (it introduces a new magic file, hence probably a whole new documentation page)._
### Issue statement

Docker needs to provide a repeatable and well defined mechanism for repositories which builds into multiple image. Existing proposals:
- #7284
- #2112

These have been opened for some time, and have reached the point where tempers flaring and amount of noise overwhelms the signal. The thinking behind this new proposal was driven by the following remarks collected from previous debates:
1. We want `docker build` to behave consistently, [without repository-specific knowledge](https://github.com/docker/docker/issues/2112#issuecomment-39763037)
2. Through 1, we want to allow Docker Hub [automated builds](https://github.com/docker/docker/issues/2112#issuecomment-60597439) to use this new feature
3. We do not want a repository from which _n_ images are built to contain [_n_ `Dockerfile`s at its root](https://github.com/docker/docker/issues/2112#issuecomment-47986440)
4. We should provide an easy fix for this common problem, and it seems to me that new `Dockerfile` verbs are more difficult to introduce
### Proposal

We introduce a new magic file at the root of the repository to act as the `Dockerfile` of all `Dockerfile`s:
- It could be named `DockerfileIndex` (as I believe `Dockerfiles` is too error prone and confusing)
- It has precedence over a regular `Dockerfile`, meaning that a `docker build` invoked in a directory containing both a `Dockerfile` and a `DockerfileIndex` interprets the `DockerfileIndex` only
- Its content is a simple list of `Dockerfile`s' relative paths

```
Dockerfile                  # Build the default Dockerfile located at the root
./SubDirectoryA/Dockerfile  # Build SubDirectoryA
./SubDirectoryB/Dockerfile  # Build SubDirectoryB
```

With the above `DockerfileIndex`, the invocation of `docker build -t basename:tag .` at the root of the repository is equivalent to the following sequence of commands:

```
docker build -t basename:tag .
cd SubDirectoryA && docker build -t basename/SubDirectoryA:tag .
cd SubDirectoryB && docker build -t basename/SubDirectoryB:tag .
```

Notes:
- The first command only exists because the default `Dockerfile` is itself listed on the first line of the `DockerfileIndex` (there is nothing specific to this `Dockerfile` nor to the root)
- With the V2 registry, an image name is not restricted to a “two-components” path anymore, so “username/image/subimage” is a valid identifier (and in our case, this scoping sounds reasonable)
- The sequence of commands is provided only as a mean to illustrate the behavior: this doesn't imply that `DockerfileIndex` interpretation would occur on the client side with multiple `build` API calls
- As the sequence of commands implies, each build context is scoped to the location of the `Dockerfile`: this is Docker current behavior, and I also strongly believe it is the least astonishing one.
#### Different builds with a single context

To allow for multiple builds using a same context, we require multiple `Dockerfile` in a **single** directory: these different `Dockerfile` would be disambiguated using suffixes, such as `Dockerfile.A` and `Dockerfile.B`. Given `DockerfileIndex`:

```
Dockerfile.A
Dockerfile.B
```

Invocation of `docker build -t basename:tag .` would result in images `basename/A:tag` and `basename/B:tag` to be created. Image name is scoped by `Dockerfile` location first and filename suffix second, which means that `SubDirectoryA/Dockerfile.Type1` build would produce image `basename/SubDirectoryA/Type1`.
### Possible extensions

These probably doesn’t have to come in a first version:
- Ability to trigger a specific sub-build from the `DockerfileIndex` location through the use of an additional `docker build` flag (`--only` was suggested).
### History
- 2014-17-11: add context specification, clarify cascading tag, promote "same context builds" to a first class use case

**Comment by jberkus** [comment]
+1 on allowing specific Dockerfiles.  The rest seems like overkill.

**Comment by SimenB** [comment]
Any news here?

**Comment by thaJeztah** [comment]
Yes, this was implemented in https://github.com/docker/docker/pull/9707, which is in Docker 1.5 and up, so this can be closed
