### ISSUE TITLE
Output of df -T path is not existing in Docker v1.0.1 with CentOS 6.5 base image

### ISSUE THREAD

**Issue by sylentprayer** [docker/docker#9199]
See console log:

bash-4.1# df -T
Filesystem           Type   1K-blocks     Used Available Use% Mounted on
rootfs               rootfs  10190136  1457608   8191856  16% /
/dev/mapper/docker-8:6-12461592-43c36fb7a027f261053f77251fd3a98f6a49349f1c2caf0cd25bde001113659e
                     ext4    10190136  1457608   8191856  16% /
tmpfs                tmpfs    4026704        0   4026704   0% /dev
shm                  tmpfs      65536        0     65536   0% /dev/shm
/dev/disk/by-uuid/049fe1d2-5c6b-4eed-9d60-2ddc3b182400
                     ext4   259383580 28856736 217327844  12% /.dockerinit
/dev/disk/by-uuid/049fe1d2-5c6b-4eed-9d60-2ddc3b182400
                     ext4   259383580 28856748 217327832  12% /etc/resolv.conf
/dev/disk/by-uuid/049fe1d2-5c6b-4eed-9d60-2ddc3b182400
                     ext4   259383580 28856764 217327816  12% /etc/hostname
/dev/disk/by-uuid/049fe1d2-5c6b-4eed-9d60-2ddc3b182400
                     ext4   259383580 28856764 217327816  12% /etc/hosts
bash-4.1# ls /dev/mapper/docker-8:6-12461592-43c36fb7a027f261053f77251fd3a98f6a49349f1c2caf0cd25bde001113659e
ls: cannot access /dev/mapper/docker-8:6-12461592-43c36fb7a027f261053f77251fd3a98f6a49349f1c2caf0cd25bde001113659e: No such file or directory
bash-4.1# ls /dev/mapper/  
control
bash-4.1# 

There is no file docker-8:6-12461592-43c36fb7a027f261053f77251fd3a98f6a49349f1c2caf0cd25bde001113659e in /dev/mapper. This is causing Vertica DB installation failure.

**Comment by unclejack** [comment]
@vbatts Have you seen anything like this?

**Comment by vbatts** [comment]
i'm not sure why vertica db would be have check that would cause this failure, unless they're attempting to assert something about the mounted block device.

But, this is expected behavior. The `mount -T` is pulling information from `/proc/self/mountinfo` or similar, which the kernel has for the pid. But since `/dev` is specially constructed, the block device is not present in the container's `/dev`.

This is _not_ a devicemapper thing. Same will be true of other storage drivers. Here is a btrfs example of the same.
```
vbatts@valse ~ (master *) $ docker run -it centos bash 
[root@80746842abf5 /]# mount
/dev/mapper/fedora_dhcp129--32-docker on / type btrfs (rw,noatime,seclabel,ssd,discard,space_cache,commit=90)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,seclabel,mode=755)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,seclabel,size=65536k)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime,seclabel)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=666)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime,seclabel)
/dev/mapper/fedora_dhcp129--32-docker on /etc/resolv.conf type btrfs (rw,noatime,seclabel,ssd,discard,space_cache,commit=90)
/dev/mapper/fedora_dhcp129--32-docker on /etc/hostname type btrfs (rw,noatime,seclabel,ssd,discard,space_cache,commit=90)
/dev/mapper/fedora_dhcp129--32-docker on /etc/hosts type btrfs (rw,noatime,seclabel,ssd,discard,space_cache,commit=90)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
proc on /proc/sys type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/sysrq-trigger type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/irq type proc (ro,nosuid,nodev,noexec,relatime)
proc on /proc/bus type proc (ro,nosuid,nodev,noexec,relatime)
tmpfs on /proc/kcore type tmpfs (rw,nosuid,seclabel,mode=755)
[root@80746842abf5 /]# ls /dev/mapper/fedora_dhcp129--32-docker
ls: cannot access /dev/mapper/fedora_dhcp129--32-docker: No such file or directory
[root@80746842abf5 /]# cat /proc/self/mountinfo 
245 206 0:39 /btrfs/subvolumes/80746842abf5695276c64bed6a8c5041fc521a464211c81948893b7c8b1c3894 / rw,noatime - btrfs /dev/mapper/fedora_dhcp129--32-docker rw,seclabel,ssd,discard,space_cache,commit=90
246 245 0:96 / /proc rw,nosuid,nodev,noexec,relatime - proc proc rw
247 245 0:112 / /dev rw,nosuid - tmpfs tmpfs rw,seclabel,mode=755
248 247 0:117 / /dev/shm rw,nosuid,nodev,noexec,relatime - tmpfs shm rw,seclabel,size=65536k
249 247 0:63 / /dev/mqueue rw,nosuid,nodev,noexec,relatime - mqueue mqueue rw,seclabel
250 247 0:151 / /dev/pts rw,nosuid,noexec,relatime - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=666
251 245 0:157 / /sys ro,nosuid,nodev,noexec,relatime - sysfs sysfs ro,seclabel
252 245 0:39 /containers/80746842abf5695276c64bed6a8c5041fc521a464211c81948893b7c8b1c3894/resolv.conf /etc/resolv.conf rw,noatime - btrfs /dev/mapper/fedora_dhcp129--32-docker rw,seclabel,ssd,discard,space_cache,commit=90
253 245 0:39 /containers/80746842abf5695276c64bed6a8c5041fc521a464211c81948893b7c8b1c3894/hostname /etc/hostname rw,noatime - btrfs /dev/mapper/fedora_dhcp129--32-docker rw,seclabel,ssd,discard,space_cache,commit=90
254 245 0:39 /containers/80746842abf5695276c64bed6a8c5041fc521a464211c81948893b7c8b1c3894/hosts /etc/hosts rw,noatime - btrfs /dev/mapper/fedora_dhcp129--32-docker rw,seclabel,ssd,discard,space_cache,commit=90
255 247 0:11 /11 /dev/console rw,nosuid,noexec,relatime - devpts devpts rw,seclabel,gid=5,mode=620,ptmxmode=000
207 246 0:96 /sys /proc/sys ro,nosuid,nodev,noexec,relatime - proc proc rw
208 246 0:96 /sysrq-trigger /proc/sysrq-trigger ro,nosuid,nodev,noexec,relatime - proc proc rw
209 246 0:96 /irq /proc/irq ro,nosuid,nodev,noexec,relatime - proc proc rw
211 246 0:96 /bus /proc/bus ro,nosuid,nodev,noexec,relatime - proc proc rw
212 246 0:112 /null /proc/kcore rw,nosuid - tmpfs tmpfs rw,seclabel,mode=755
```

**Comment by jfrazelle** [comment]
cannot reproduce on latest, ping if so and how and we will repoen
