### ISSUE TITLE
resolv.conf not updated when using docker start

### ISSUE THREAD

**Issue by brauner** [docker/docker#9202]
When I run a container from an image in **network 1** via

    docker run -it -h resolv ubuntu /bin/bash

then exit the container and start the container in **network 2** via

    docker start -i resolv /bin/bash

then `resolv.conf` does not get updated and I cannot connect to the internet in network 2. So it seems that `docker start` does not update `resolv.conf` to the current network. If I change it manually then everything works as expected and I can connect to the internet.

    [chb@conventiont ~]$ docker version
    Client version: 1.3.1
    Client API version: 1.15
    Go version (client): go1.3.3 
    Git commit (client): 4e9bbfa
    OS/Arch (client): linux/amd64
    Server version: 1.3.1
    Server API version: 1.15
    Go version (server): go1.3.3
    Git commit (server): 4e9bbfa

    [chb@conventiont ~]$ uname -a
    Linux conventiont 3.17.3-1-ARCH #1 SMP PREEMPT Fri Nov 14 23:13:48 CET 2014 x86_64 GNU/Linux

So far I solve this by setting an explicit generic and almost always reachable `nameserver` via the `--dns=` flag when I start the container. But can `docker start` be made to update `resolv.conf`?

**Comment by jfrazelle** [comment]
@estesp this should be fixed now right?

**Comment by estesp** [comment]
yes, the original reported issue is resolved.  A `start` will update resolv.conf from the host's copy if it has changed since the container exited.  What did not get implemented is any live-update (discussed in the above comments), but the original problem is resolved by the merged PR.
