### ISSUE TITLE
WIP - Enable test-integration-cli for client-side only platforms

### ISSUE THREAD

**Issue by icecrime** [docker/docker#9217]
As written today, `test-integration-cli` expect:
* To be running inside a container (cf. [`project/make.sh`](https://github.com/docker/docker/blob/master/project/make.sh#L30-L39))
* To have a **local** daemon to talk to (cf. [`project/make/test-integration-cli`](https://github.com/docker/docker/blob/master/project/make/test-integration-cli#L26-L32))

Some platforms only support the client-side of Docker, yet we would obviously want integrations tests to cover them. Before diving into implementation, I'd like to be sure we agree on the proper way to achieve this. I'm thinking:
* Use the existing `DOCKER_CLIENTONLY` variable in some way for test execution, for example as a mean to exclude `docker_cli_daemon_test.go` from the run
* Take `DOCKER_HOST` environment variable into consideration for every interactions with the daemon: this *does* mean that you can end up polluting a running daemon with test data if you're not careful
* Go through individual tests to check which rely on the assumptions of a local daemon running, if any

Ping @tianon as maintainer: do you have objection and/or suggestions on the proper way to do this?
Ping @ahmetalpbalkan who surely will be interested

**Comment by jfrazelle** [comment]
so close right?

**Comment by ahmetalpbalkan** [comment]
@jfrazelle for windows, yeah!

**Comment by unclejack** [comment]
@icecrime @ahmetalpbalkan Can we close this?

**Comment by ahmetalpbalkan** [comment]
Yes I think so.

**Comment by LK4D4** [comment]
Let's close then.
