### ISSUE TITLE
Missleading documentation

### ISSUE THREAD

**Issue by bluehallu** [docker/docker#9235]
http://docs.docker.com/userguide/dockerrepos/#find-public-images-on-docker-hub

I tried the same steps except searching for node, and sure, I get the main top-level node result. The docs however seem to indicate this is image results I'm seeing, but they seem to be repositories. In fact, when I continue to the next step and run docker pull node, docker tries to download all images in the repo, clearly not what you expect from reading the documentation. 

Also, there doesn't seem to be a clear way to list all images in the node repo from the command line. I only realised "docker pull node:latest" is what I was looking for from looking at the node repo website on the docker hub.

**Comment by mikebrow** [comment]
#dibs

**Comment by calavera** [comment]
Fixed by #15760.
