### ISSUE TITLE
Shell friendly environment files

### ISSUE THREAD

**Issue by mattmb** [docker/docker#9240]
Both me and a colleague came up against this recently. We had assumed that the `--env-file` that we passed to `docker run` would be equivalent format to an environment file that could be sourced in bash.

However, currently it looks like it's just a split on the `=` ?
https://github.com/docker/docker/blob/master/opts/envfile.go#L26-L27

It would be cool if we could have one file that both bash and Docker could interpret with the same quotes/escaping structure. Anyone got any thoughts?

**Comment by vaijab** [comment]
@duglin could you explain how #8251 makes it easier to solve this issue?

I think `--env-file` behaves differently from shell. For example:

`docker run -e FOO='bar'` - the quotes around `bar` will get eaten up by the shell.
```bash
~> docker run -ti --rm -e FOO='bar' fedora:21 env 
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=439722bec399
TERM=xterm
FOO=bar
HOME=/root
```

The second example gives different results, however the intention is the same.
```bash
~> cat myenvfile
FOO='bar'

~> docker run -ti --rm --env-file=myenvfile fedora:21 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=bacdfc97654e
TERM=xterm
FOO='bar'
HOME=/root
```
The above `FOO` variable value is quoted, which is totally different from the first example and I think that's an issue.

**Comment by duglin** [comment]
Sorry if I wasn't clear. What I meant to say is that once #8251 is merged then the code as part of that PR should be available to be reused to support what you're looking for.

**Comment by supernovae** [comment]
This bit my butt recently.. If i have some free time i'll look into the code but i find it abominable that passing values through -e behaves differently than passing them with an env file.

**Comment by xiaods** [comment]
i don't know this feature is  in effect, anyone need it?

**Comment by xiaods** [comment]
ping @icecrime

**Comment by icecrime** [comment]
@xiaods Good catch :+1: Thanks :-)
