### ISSUE TITLE
idempotent create command

### ISSUE THREAD

**Issue by kr** [docker/docker#9253]
I wish `docker create` were idempotent like `docker start`, and that `docker run` could also work this way somehow. What I want is to make sure a container is running: if it's not running, run it, and if it is running, just let it continue (and don't report an error).

I attempted (poorly) to describe this on twitter:

https://twitter.com/krarick/status/535300342317973505

Basically I wish I could issue a single `docker run -d` command and have it act like `launchctl start`.

I can do what I want with the current CLI:

```
set -e

if ! docker inspect -f 1 foo &>/dev/null
then docker create --name foo bar
fi
docker start foo
```

Ideally I would like to get the same behavior when I write:

```
set -e

docker create --idempotent --name foo bar
docker start foo
```

which could then be further condensed:

```
docker run -d --idempotent --name foo bar
```

I'm just surprised this isn't a more common situation and that docker doesn't already do this conveniently in one command.

cc @kelseyhightower

**Comment by duglin** [comment]
I'm not hearing a lot of support for doing this.
Given that you could just do `docker rm -f foo`,
and ignore the exit code, prior to your `docker create` I think there's a workaround.  Granted, #13855, would make it easier, but that was rejected too :-( 
Going to close this, if you really want to push for it you can reopen it and we can discuss.
