### ISSUE TITLE
`docker images` virtual size wrong concerning hardlinks

### ISSUE THREAD

**Issue by vbatts** [docker/docker#9283]
If you have image layers that include hardlinks, then the virtual size sums each file regardless, so the size will appear larger than the image is on disk, and larger than the tar archive will be.

https://github.com/docker/docker/pull/8984 attempted to fix, but there were complications.

**Comment by jfrazelle** [comment]
wdyt @vbatts is white-belt appropriate

**Comment by vbatts** [comment]
Sure thing. It's doable in a day or so. I had quirky tests fail last on my
last effort. Perhaps someone else will be smarter about their approach.

**Comment by sharidas** [comment]
#dibs

**Comment by vbatts** [comment]
Cool! Feel free to ping me as you have questions

**Comment by sharidas** [comment]
@vbatts Sure

**Comment by thaJeztah** [comment]
@sharidas any update? are you still working on this?

**Comment by pydima** [comment]
#dibs

**Comment by vbatts** [comment]
@pydima cool!
I would be neat to see how much is allocated as well, like `st_blocks * st_blksize` in contrast to just `st_size`
