### ISSUE TITLE
Docker logs an EOF and fails to start

### ISSUE THREAD

**Issue by rferreira** [docker/docker#9309]
os: ubuntu 14.04 LTS
docker version: Docker version 1.2.0, build fa7b24f
kernel: Linux ip-10-138-85-107 3.13.0-35-generic #62-Ubuntu SMP Fri Aug 15 01:58:42 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Hi there folks, we run lots of docker and we seem to see this error from time to time where the docker service fails to start for no apparent reason with this in the log file: 
```
2014/11/24 15:16:29 docker daemon: 1.2.0 fa7b24f; execdriver: native; graphdriver: 
[e55bf75d] +job serveapi(tcp://0.0.0.0:2375)
[info] Listening for HTTP on tcp (0.0.0.0:2375)
[info] /!\ DON'T BIND ON ANOTHER IP ADDRESS THAN 127.0.0.1 IF YOU DON'T KNOW WHAT YOU'RE DOING /!\
2014/11/24 15:16:29 EOF
```
No further indication of what's wrong is given. 

Here's an strace of startup: 
https://gist.github.com/rferreira/fe3404201c2e0f1f78d1

Any help would be greatly appreciated!

**Comment by rhvgoyal** [comment]
@SvenDowideit @vbatts  

I am seeing following on my system with latest docker.
time="2015-01-29T15:29:52-05:00" level="info" msg="docker daemon: 1.4.1-dev c12fb48-dirty; execdriver: native-0.2; graphdriver: devicemapper"

So looks like problem does not exist anymore.

@vbatts 

I guess we should close this issue?

**Comment by rhvgoyal** [comment]
At least the logging error seems to be fixed where graphdriver was not displaying properly. If original problem still persists, does not look like it is devmapper issue though. 

If that's the case, we should atleast remove devicemapper label.

**Comment by vbatts** [comment]
With out having pinned the issue precisely, we have cleaned up code that could be related to this. I'm going to close this issue. If it crops up again, we can revisit.
