### ISSUE TITLE
Removing an image fails when the base image is in two repositories

### ISSUE THREAD

**Issue by jsternberg** [docker/docker#9313]
This is related to #1926. We started mirroring the ubuntu image into our own private repository so we could keep docker builds internal to our infrastructure and change the underlying image if necessary.

When I build an image using either the original ubuntu image or our mirrored one and then try to remove the built image, it gives the same error message as that original ticket.

```bash
$ docker pull ubuntu:14.04
$ docker tag ubuntu:14.04 example.org/ubuntu:14.04
$ cat > Dockerfile <<EOF
FROM ubuntu:14.04
RUN true
EOF
$ docker build -t docker-rmi-test .
$ docker rmi docker-rmi-test
Error response from daemon: Conflict, cannot delete image 5506de2b643be1e6febbf3b8a240760c6843244c41e12aa2f60ccbb7153d17f5 because it is tagged in multiple repositories, use -f to force
2014/11/24 11:36:49 Error: failed to remove one or more images
```

The original image (`docker-rmi-test`) gets removed correctly, but the error message is still received. Using `-f` causes it to do the right thing, but it seems dangerous to solve the problem by using `-f`.

**Comment by jfrazelle** [comment]
I cannot reproduce this on the latest version, but let me know if and how you can and I will reopen
