### ISSUE TITLE
1.2 restart policies broke pre-1.2 behavior, conflate options

### ISSUE THREAD

**Issue by matthughes** [docker/docker#9319]
There is a hole IMO in the 1.2+ restart policies.  Pre 1.2, you only had the -r flag to the daemon which restarted all previously running containers.

With 1.2+, you can specify restart policy per container using:
* --restart=always
* --restart=on-failure
* --restart=on-failure:limit

In my use case, I'm hesitant to recommend the first two as they could lead to an infinite restart loop.  However, on-failure containers have a weird behavior in that they won't boot at startup *unless they last stopped because of a failure.*

```
vagrant@vagrant-ubuntu-trusty-64:/vagrant/sample-docker-configs$ docker run --restart=on-failure:2 --name failure centos /bin/bash -c "sleep 5; exit 2"
vagrant@vagrant-ubuntu-trusty-64:/vagrant/sample-docker-configs$ docker run --restart=on-failure:2 -d --name nginx nginx

vagrant@vagrant-ubuntu-trusty-64:/vagrant/sample-docker-configs$ docker ps -a
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                      PORTS               NAMES
a7e3463c84aa        nginx:latest        "nginx -g 'daemon of   4 seconds ago       Up 3 seconds                443/tcp, 80/tcp     nginx
84a5702f84ce        centos:latest       "/bin/bash -c 'sleep   36 seconds ago      Exited (2) 24 seconds ago                       failure

vagrant@vagrant-ubuntu-trusty-64:/vagrant/sample-docker-configs$ sudo service docker restart
docker stop/waiting
docker start/running, process 8951

vagrant@vagrant-ubuntu-trusty-64:/vagrant/sample-docker-configs$ docker ps
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS              PORTS               NAMES
84a5702f84ce        centos:latest       "/bin/bash -c 'sleep   46 seconds ago      Up 1 seconds                            failure
```

This doesn't make much sense to me.  'nginx' was running when the daemon was restarted; 'failure' was not.  Yet only 'failure' gets restarted at boot time.  Why would 'on-failure' flag affect whether container starts at daemon start time at all?  Why doesn't 'always' have a retry limit?  

The current option set / behavior seem to conflate three distinct questions:

* should we restart only in case of failure or no matter how the container exits?
* how many times should we attempt restarting?
* should we start container at daemon startup

I propose this new option set:

```
--restart=[noreturn|always|on-failure][:limit][:noboot|boot]
```

This preserves backwards compatibility from a command viewpoint yet neatly addresses the three concerns.  Note that 'limit' can be specified for both always and on-failure.  And you can sepcify whether to start at daemon boot (I'd vote for boot being the default behavior to preserve 1.2 semantics).

**Comment by gdm85** [comment]
Agree with OP, see also #8821

**Comment by gdm85** [comment]
@matthughes see also https://github.com/docker/docker/issues/9678#issuecomment-71102191

Also related: #9526.

**Comment by jfrazelle** [comment]
im going to close as #9526 #9678 #8821 all cover same thing
