### ISSUE TITLE
Docker load fails to load xz-compressed image

### ISSUE THREAD

**Issue by jperville** [docker/docker#9327]
The ability to `docker load` xz-compressed images has been broken with docker 1.3.2 (it was working until docker 1.3.1 included). Loading a gzip-compressed version of the same image still works, so the breakage is xz-specific.

Error message is `Error: Untar exit status 1 exec: "xz": executable file not found in $PATH`, even if the xz command is installed as `/usr/bin/xz`.

With docker 1.3.2:
```sh
vagrant@docker-ubuntu-1404:~$ file /docker-images/busybox-trusty.tar.xz 
/docker-images/busybox-trusty.tar.xz: XZ compressed data
vagrant@docker-ubuntu-1404:~$ docker --version
Docker version 1.3.2, build 39fa2fa
vagrant@docker-ubuntu-1404:~$ sudo docker load --input=/docker-images/busybox-trusty.tar.xz
2014/11/25 02:13:39 Error: Untar exit status 1 exec: "xz": executable file not found in $PATH
vagrant@docker-ubuntu-1404:~$ which xz
/usr/bin/xz
```

With docker 1.3.1:

```sh
vagrant@client-ingest-ubuntu-1404:~$ file /docker-images/busybox-trusty.tar.xz 
/docker-images/busybox-trusty.tar.xz: XZ compressed data
vagrant@client-ingest-ubuntu-1404:~$ docker --version
Docker version 1.3.1, build 4e9bbfa
vagrant@client-ingest-ubuntu-1404:~$ sudo docker load --input=/docker-images/busybox-trusty.tar.xz
vagrant@client-ingest-ubuntu-1404:~$ which xz
/usr/bin/xz
```

**Comment by EwanValentine** [comment]
I'm still getting this... 20GB vm with 18GB left free. 

Docker version 1.6.0, build 4749651

Boot2Docker-cli version: v1.6.0
Git commit: 9894ae9

**Comment by murali44** [comment]
I'm seeing similar issues when I use docker load. I'm using docker 1.6.0.

Error: Untar exit status 1 no such file or directory

Error: Untar exit status 1 lchown /usr/bin/unzip: no such file or directory

Error: Untar exit status 1 lchown /usr/lib/x86_64-linux-gnu/libgphoto2/2.5.3.1/stv0674.so: no such file or directory

**Comment by jfrazelle** [comment]
@murali44 are you on boot2docker as well

**Comment by murali44** [comment]
@jfrazelle no, I'm not. I'm just running docker on an Ubuntu machine. I tried both 1.5 and 1.6.

I'm trying to load multiple docker images from a tar file using the docker load command.

**Comment by EwanValentine** [comment]
Re-sizing the docker VM, doesn't seem to re-size /dev/sda1, which in my case was still full. So I just removed looooads of old, un-used containers that were still running on there and re-built the containers I actually wanted to use.

**Comment by jfrazelle** [comment]
I cannot reproduce locally or on test server, @murali44 can you check if its your disk size too
