### ISSUE TITLE
inconsistent and confusing naming of images

### ISSUE THREAD

**Issue by TomasTomecek** [docker/docker#9331]
For quite some time I'm stuck with proper naming. Here's the thing:

Let's say we have image `registry.example.com/fedora:21`. It's clear it is tagged as `21`. We also do know that name of the image (according to `man docker-tag`) is `fedora`. How about `registry.exaple.com/fedora`? `docker images` says it's repository. Okay then.

And finally, how you call `registry.example.com/fedora:21`? Is it tag? No, it's not! Tag is the stuff after colon. Is it image? It is actually, but isn't image actually the physical representation of several layers of directories with metadata on filesystem?

Let's check manpages:

1. _docker build_  
`-t, --tag="" Repository name (and optionally a tag) to be applied to the resulting image in case of success`  
Could this be even more confusing? How it could be tag, when tag part may not even be in there.  
2. _docker tag_  
`TAG     Note that here TAG is a part of the overall name or "tag".`  
What? I don't get it at all. Is this saying that _tag_ is the whole name or not? Why is the `TAG` explained using the word itself?  
3. _docker run_ — overall naming is just `IMAGE`, except `IMAGE The image name or ID.`: isn't _image name_ the part between registry part and tag?

I'm sure you won't change CLI API. I just want to know, what the proper naming guidelines are, because manpages didn't answer it for me.

**Comment by jfrazelle** [comment]
@SvenDowideit do the docs reflect this now

**Comment by thaJeztah** [comment]
dup or related to [Docs on Dockerfiles use word "repository" without any explanation of the concept #8648](https://github.com/docker/docker/issues/8648)
