### ISSUE TITLE
API 1.15 - Exec#start returns 200 when Exec instance does not exist

### ISSUE THREAD

**Issue by tduffield** [docker/docker#9341]
I came across this when working on the Ruby docker-api gem. If you attempt to start a random Exec instance the response will be a 200. Shouldn't this be a 404?

https://gist.github.com/tduffield/21a64cd272962b4345fe

**Comment by jfrazelle** [comment]
@tduffield can you make sure this is still an issue with the latest version of docker, thanks

**Comment by cpuguy83** [comment]
Confirmed exec start returns 404 now. Closing.
