### ISSUE TITLE
Feature request: docker ps -f "with_volumes=false"

### ISSUE THREAD

**Issue by marksteve** [docker/docker#9350]
I only care about containers with volumes most of the time.

**Comment by vdemeester** [comment]
#dibs I'll try to work on this :)

**Comment by cpuguy83** [comment]
What if instead we require an extra flag to remove containers that are the last reference to a volume?

**Comment by vdemeester** [comment]
@cpuguy83 I'm not sur to see what you mean. You would add a flag to ``ps`` (instead of a filter) or to ``rm`` ?

**Comment by cpuguy83** [comment]
@vdemeester As in, requiring `docker rm -v` in order to delete a container that is the last reference to a volume.

Ooo, also... docker 1.6 includes labels. Instead of the request here, you can filter by label, and just make sure to label your data containers.

**Comment by vdemeester** [comment]
Yeah, for the label, I was think about that. I'm gonna dig a bit more in the ``rm`` command to see what could be done (or should not :P)

**Comment by vdemeester** [comment]
Wouldn't it be better to to the opposite ; I mean something like a "keep the container that are the last reference to a volumen" ?

Because otherwise it would change the default behavior of the ``rm`` command and thus probably break a lot of tools/scripts that are based on it.

**Comment by cpuguy83** [comment]
Yes, it will be a minor breaking change, but also a good one otherwise people have data just dangling around and no real way to access it or even know what said data is.

**Comment by vdemeester** [comment]
ok then, I'll take a look at that then :)

**Comment by cpuguy83** [comment]
Here is an existing proposal: #10497

**Comment by jameseggers** [comment]
@thaJeztah is this still something that needs to be fixed?

**Comment by thaJeztah** [comment]
@jameseggers I don't think it has been implemented, but I wonder if we still need this. At the time this issue was created, volumes could only be referenced via a container that has the volume attached. However, now that we have volume management commands (`docker volume create`, `docker volume ls`), volumes can still be managed, even if there's no container using them.

@marksteve is this still relevant to you, and if so, could you provide a use-case?

**Comment by zelahi** [comment]
If there is still a need for this issue I would like to work on it =)

**Comment by thaJeztah** [comment]
@zelahi I'm not sure it's still needed, I'm interested to hear if there's still a use case now that we have the `docker volume` commands. If there's no real use case, I'd rather not implement it to prevent cluttering the code-base with unused features.

Thanks very much for the offer though! Let's see if there's still a use case, then we can decide if we implement it or not.

**Comment by thaJeztah** [comment]
ping @cpuguy83 do you think we still need this, now that we have, e.g. `docker volume ls`?

**Comment by vdemeester** [comment]
and we also have the volume filter so I would think we could close this one ;)

**Comment by thaJeztah** [comment]
agreed, let's close this
