### ISSUE TITLE
Enhance the docker (daemon) logging

### ISSUE THREAD

**Issue by kencochrane** [docker/docker#936]
Right now it is really hard to debug what is going on inside of docker when you are trying to work with it. If you are using upstart you can find some logs in /var/log/upstart/dockerd.log, and you can run docker in debug mode, to get a little more detail but sometimes it isn't enough.

It would be nice to make the docker logs more consistant. Ideally we would by default add logs to /var/log/docker/dockerd.log, and allow people to pass in parameters to override the default log file location and name. 

It would be nice to have different configurable log levels as well: DEBUG, INFO, ERROR, etc.

It would be really nice if we could break out logs by different parts of the system (API, etc), but one file is fine for now. 

Hopefully once we make this infrastructure changes, then we can add more logging statements to the code base. 

really cool future feature, would be the ability to stream the docker logs via the API, so that you can collect those logs in one place and watch more then one server at once.

I would love to hear what people think about this idea?

**Comment by cpuguy83** [comment]
@blalor "docker logs --timestamps"

**Comment by cpuguy83** [comment]
So in 1.4 you can set both the logging level and the there are timestamps attached.
And logs go to stdout, so you tell it to send logs wherever you want.

Does this address this issue?

**Comment by cpuguy83** [comment]
Closing since this imo is generally resolved.
if that's not the case, please open a new issue with specific details on what might be lacking from the current logging format for the daemon.

Thanks!

**Comment by mausch** [comment]
Do timestamps have to be enabled somewhere? I'm running docker 1.8.3 and I don't see any timestamps in /var/log/upstart/docker.log ...

**Comment by cpuguy83** [comment]
@mausch It depends.
If the output has a TTY allocated, then the format is different than without a TTY.

**Comment by mausch** [comment]
@cpuguy83 Thanks for the quick response! This is a default install of Docker on Ubuntu. I don't think any TTY is attached to the daemon... The log format I'm getting is `ESC[34mINFOESC[0m[165381] POST /v1.20/images/create?fromImage=rabbitmq&tag=latest`

**Comment by cpuguy83** [comment]
@mausch Yeah, for some reason a TTY is detected there.
W/o a TTY it uses a json format with timestamps and such.
Not sure what upstart is doing here.

**Comment by mausch** [comment]
@cpuguy83 That's where the docker daemon logs go in a default install on Ubuntu 14.04... Just to confirm, timestamps should be enabled by default, correct? I'll see if I can repro on a clean box and create a new github issue. Cheers.

**Comment by tedyoung** [comment]
@mausch Can you make sure to point to that issue? On a clean Ubuntu install, 1.8.3's daemon is using the apparent "tty" format, e.g.:

```
DEBU[4102] Calling GET /containers/json                 
INFO[4102] GET /v1.20/containers/json                   
```

(I have a "-D" in my DOCKER_OPTS in the /etc/default/docker file).

**Comment by drags** [comment]
This is due to docker running under upstart in Ubuntu 14.04, and how upstart handles logging: http://upstart.ubuntu.com/cookbook/#console-log

Can confirm that in the docker-engine_1.9.0 package for ubuntu 14.04 this is still logging in the TTY format (without timestamps)
