### ISSUE TITLE
Add supplemental UNIX groups to a container at 'docker run' time

### ISSUE THREAD

**Issue by thockin** [docker/docker#9360]
Similar to #7447, but different.

Request: the ability to add supplemental groups to a container without changing the current GID.

The use case is kubernetes pods with shared volumes - different containers in the pod can set different USER directives in their Dockerfiles, but they want to share on-disk files.  How we handle this internally is to allocate a GID per pod, and put all containers into that group, making the volume mode g+s for that GID.

Would docker folks be amenable to a --extra-group flag (and requisite plumbing)?

@vishh @jnagal @vmarmol

**Comment by crosbymichael** [comment]
@thockin what extra flags would be required?  Would a simple `--group` flag be enough?

**Comment by tianon** [comment]
@crosbymichael wouldn't it be more consistent with caps if we had two flags?
```
  --cap-add=[]               Add Linux capabilities
  --cap-drop=[]              Drop Linux capabilities
```
(ie, `--group-add` and `--group-remove` or something like that)

**Comment by tianon** [comment]
(especially since right now, `-u user` or `-u uid` already implies supplementary groups handling that would be interesting to get more control over, especially in the `-u user:group`/`-u uid:gid` cases where we explicitly empty the supplementary groups)

**Comment by mrunalp** [comment]
I have created a PR -- https://github.com/docker/libcontainer/pull/322. I will modify it depending on what is agreed upon here.

**Comment by thockin** [comment]
Is there a use for group-remove?  --group-add or --add-group or
--extra-group are all fine with me.  We should be clear whether this
accepts GIDs only, or whether I can say a name and have it be looked up in
the group file (and is that the host's group file or the container's? I
assume container).

**Comment by mrunalp** [comment]
I think at docker level it could be the name if required and then it could be passed down as gid to libcontainer.

**Comment by thockin** [comment]
Yeah, it just needs to be clearly documented :)

**Comment by tianon** [comment]
I guess the use case for removing is pretty limited since you can just use the `user:group` syntax instead and then add only the groups that matter. :+1:

**Comment by thockin** [comment]
This has been in libcontainer for a month now - is anyone carrying it forward to the CLI and API?

**Comment by mrunalp** [comment]
@thockin I have started work on this. I will have a PR ready in a day or two.

**Comment by mrunalp** [comment]
Sent a PR -- https://github.com/docker/docker/pull/10717

**Comment by edicogelon11** [comment]
#40007
