### ISSUE TITLE
Problem with shell script (maybe variable/network)

### ISSUE THREAD

**Issue by luan-cestari** [docker/docker#9363]
Hi,

I was making a fork of an oracle image to run an script to populate an schema but I got an very unsuspected behavior from the bash which docker runs from the one that I can use inside the container. The dockerfile is this one 
https://github.com/lightblue-platform/lightblue-dockerfiles/blob/6e7ea3cacd2e47f67ad5884f124e1cfcf703aad0/oracle-image/docker-oracle-xe-11g/Dockerfile (I'm mentioning an commit so you guys don't see any other change that I might do). So this Dockerfile will call https://github.com/lightblue-platform/lightblue-dockerfiles/blob/6e7ea3cacd2e47f67ad5884f124e1cfcf703aad0/oracle-image/docker-oracle-xe-11g/populate.sh which it is the shell script that I got this problem. The problem is about the variable that I create inside this script which for one of them (NREADY) works fine (I can set a value and change and etc) but for another one (NLIS) I just can't change it (or maybe the command that it get its value is cached or even the tnsping command can't reach the localhost). This is so weird that I can't almost believe that it is a bug but I tried very very hard to see if it is a silly mistake. I logged into (using nsenter) the container and ran the same script which worked fine, then I ran each line of the script on the command line to see if I could get any issue and it also worked fine, then I tried many things (the commit have the latest one which I try to unset the variable to see if I could get it to work), but none of them worked. I also used the /proc/PID/fd/{1|2|255} to take a look on the output/error/the script loaded, but it all seems right. Do you guys know why I would have this behavior? Thank you very much in advance.

[lcestari@localhost docker-oracle-xe-11g]$ uname -a
Linux localhost.localdomain 3.17.2-200.fc20.x86_64 #1 SMP Tue Nov 4 18:04:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[lcestari@localhost docker-oracle-xe-11g]$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa/1.3.1
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa/1.3.1
[lcestari@localhost docker-oracle-xe-11g]$ docker -D info
Containers: 103
Images: 712
Storage Driver: devicemapper
 Pool Name: docker-253:0-1447067-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 27.21 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 43.28 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.85 (2014-04-10)
Execution Driver: native-0.2
Kernel Version: 3.17.2-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
Debug mode (server): false
Debug mode (client): true
Fds: 19
Goroutines: 35
EventsListeners: 0
Init SHA1: b2de099a6b4ce9d739752a196ef798a0ff6a6c76
Init Path: /usr/libexec/docker/dockerinit

**Comment by jfrazelle** [comment]
@luan-cestari how did it go, is this still an issue

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen
