### ISSUE TITLE
Wrong cgroup `cpuacct,cpu` on container process

### ISSUE THREAD

**Issue by grossws** [docker/docker#9365]
Evaluating ibuildthecloud/systemd-docker project (it's a docker run wrapper that migrates container to appropriate systemd unit slice to allow systemd monitor container instead of docker client) I've found strange problem on CentOS 7.0. 

This wrapper tries to get info from `cpuacct,cpu` cgroup which is absent. I tested same code on my ArchLinux box and on CoreOS (alpha, 509.1.0) and it works. All three systems have same `cpu,cpuacct` cgroup but no `cpuacct,cpu` which were present in error log.

Looking at `systemd-docker` wrapper source I found that it takes cgroup info from `/proc/<pid>/cgroup`. And on CentOS 7.0 it contains incorrect `cpuacct,cpu` cgroup:
```
[root@localhost ~]# cat /proc/21992/cgroup 
10:hugetlb:/
9:perf_event:/
8:blkio:/system.slice/docker-0bd31f558c426d46f30778cefbc727282e4f257537b42b361ea5d03a44f4febe.scope
7:net_cls:/
6:freezer:/system.slice/docker-0bd31f558c426d46f30778cefbc727282e4f257537b42b361ea5d03a44f4febe.scope
5:devices:/system.slice/docker-0bd31f558c426d46f30778cefbc727282e4f257537b42b361ea5d03a44f4febe.scope
4:memory:/system.slice/docker-0bd31f558c426d46f30778cefbc727282e4f257537b42b361ea5d03a44f4febe.scope
3:cpuacct,cpu:/system.slice/docker-0bd31f558c426d46f30778cefbc727282e4f257537b42b361ea5d03a44f4febe.scope
2:cpuset:/
1:name=systemd:/system.slice/docker-0bd31f558c426d46f30778cefbc727282e4f257537b42b361ea5d03a44f4febe.scope
[root@localhost ~]# ls /sys/fs/cgroup/
blkio  cpu  cpuacct  cpu,cpuacct  cpuset  devices  freezer  hugetlb  memory  net_cls  perf_event  systemd
```

On ArchLinux (systemd 217, docker 1.3.1/1.15), CentOS 6.5 (docker 1.1.2/1.13), CoreOS 509.1.0 (systemd 215, docker 1.3.2/1.15) container process has correct cgroup `cpu,cpuacct`.

See also: ibuildthecloud/systemd-docker#15.

Steps to reproduce:
* start some container `docker run -d --name test --rm busybox /bin/sh -c 'while true; do date; sleep 5; done'`
* obtain it's pid `docker inspect -f '{{ .State.Pid }}' test`
* take a look at its cgroups: `cat /proc/<pid>/cgroup`
* take a look at cgroups present in the system: `ls /sys/fs/cgroup`

Environment:
```
[root@localhost ~]# uname -a
Linux localhost.localdomain 3.10.0-123.9.3.el7.x86_64 #1 SMP Thu Nov 6 15:06:03 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

[root@localhost ~]# docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.3
Git commit (client): 2a2f26c/1.2.0
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.3
Git commit (server): 2a2f26c/1.2.0

[root@localhost ~]# docker -D info
Containers: 1
Images: 17
Storage Driver: devicemapper
 Pool Name: docker-253:1-201895152-pool
 Pool Blocksize: 64 Kb
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 326.6 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 1.1 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.9.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
Debug mode (server): false
Debug mode (client): true
Fds: 12
Goroutines: 10
EventsListeners: 0
Init SHA1: d1dac0c5b2d548aaad59205c7eae02fe57b6f104
Init Path: /usr/libexec/docker/dockerinit
```

**Comment by jfrazelle** [comment]
ping @ibuildthecloud :)

**Comment by grossws** [comment]
JFYI, still actual an 1.3.2/1.15

**Comment by jfrazelle** [comment]
what about on 1.5

**Comment by thaJeztah** [comment]
@grossws is this still an issue? have you been able to test on docker 1.5 or the 1.6 release candidate? (https://github.com/docker/docker/pull/11635#issuecomment-90205104)

**Comment by grossws** [comment]
@thaJeztah, @jfrazelle, still and issue on 1.6-rc5:

```
[root@localhost ~]# ./docker-1.6.0-rc5 inspect -f '{{ .State.Pid }}' test
10883
[root@localhost ~]# cat /proc/10883/cgroup 
10:hugetlb:/
9:perf_event:/
8:blkio:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
7:net_cls:/
6:freezer:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
5:devices:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
4:memory:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
3:cpuacct,cpu:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
2:cpuset:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
1:name=systemd:/system.slice/docker-10824577d0d1d1e21ad4a8c3c08803584b76cc01ae2c33ccf9b071a55da7e21a.scope
```

```
[root@localhost ~]# ./docker-1.6.0-rc5 -D info
Containers: 1
Images: 4
Storage Driver: devicemapper
 Pool Name: docker-253:1-68112462-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 313.3 MB
 Data Space Total: 107.4 GB
 Data Space Available: 40.04 GB
 Metadata Space Used: 868.4 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.10.0-123.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 1
Total Memory: 458.4 MiB
Name: localhost.localdomain
ID: NMKI:SG6H:HFOC:SRZA:FD4G:EGBC:MA52:VWZQ:E6ET:BQET:XSZJ:A3TQ
Debug mode (server): false
Debug mode (client): true
Fds: 19
Goroutines: 29
System Time: Sun Apr 12 00:06:30 UTC 2015
EventsListeners: 0  
Init SHA1: b70e69f43ba7665d9c66511a4a1d7b0266c4c756
Init Path: /root/docker-1.6.0-rc5
Docker Root Dir: /var/lib/docker

[root@localhost ~]# ./docker-1.6.0-rc5 version
Client version: 1.6.0-rc5
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): fc4825d
OS/Arch (client): linux/amd64
Server version: 1.6.0-rc5
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): fc4825d
OS/Arch (server): linux/amd64
```

**Comment by grossws** [comment]
Sorry, seems like this is upstream problem (from rhel/centos), some other processes has such wrong cgroup. I think, docker containers receive this cgroup from docker daemon because `docker -d` itself has it from systemd parent.

**Comment by thaJeztah** [comment]
@grossws thanks for reporting back! If you find the resolution (upstream), feel free to add some info here for people arriving here via Google.

**Comment by tnachen** [comment]
Also what's the issue # upstream? We're running into this problem with Mesos as well and trying to find more information.

**Comment by grossws** [comment]
Sorry, I haven't submitted it to RedHat since I have no subscription. So, no upstream ticket id. I can submit it to CentOS tracker next week. Feel free to submit it yourself if you want to.

**Comment by Stroppel** [comment]
fixed this problem for my environment via --exec-opt native.cgroupdriver=cgroupfs
The solution is described in https://github.com/docker/docker/issues/16256

There the discussion states that the Problem comes due to a version Change in Systemd on debian. Would assume that centos 7 has the same version.

**Comment by thaJeztah** [comment]
Also note that we recently merged a PR to use `cgroupfs` as default for docker 1.10; https://github.com/docker/docker/pull/17704 there's still some discussion on that though.
