### ISSUE TITLE
Ubuntu pre-Trusty install instructions should call for Trusty 14.04 LTS HWE (kernel and xorg)

### ISSUE THREAD

**Issue by nealmcb** [docker/docker#9370]
The instructions for Precise installs seem out-of-date.  http://docs.docker.com/installation/ubuntulinux/ says to install the raring (13.10) Hardware Enablement (kernel and xorg, aka HWE), rather than the Trusty Tahr 14.04 LTS HWE, which has been available since August.  The Raring HWE will not be supported by Ubuntu any more, as described at https://wiki.ubuntu.com/Kernel/LTSEnablementStack#A12.04.3_.2B-_13.04_Hardware_Enablement_Stack_Policies_and_Procedures point 10.

I haven't tested this yet, but assuming this works, I think it should be changed.

PS Thanks for Docker!!

**Comment by unclejack** [comment]
This has been fixed by #10652.
