### ISSUE TITLE
Unable to understand behaviour of /images/create endpoint

### ISSUE THREAD

**Issue by koyadume** [docker/docker#9371]
I believe this endpoint is equivalent of docker pull command. Docker pull command will download an image for a given name and tag if the image is not available locally. 

However in case of /images/create endpoint its downloading many more images than it should download. Another confusion is fromImage and repo parameters. E.g. if I want to pull ubuntu image with 14.10 tag then i should pass ubuntu as the value of repo parameter and 14.10 as value of tag parameter. But that does not seem to work. This seems to work only after passing ubuntu as value of fromImage parameter but that will downloads all the tagged images under ubuntu repo instead of the tag which has been passed to tag parameter.

Here is the output of some commands in my local setup which confirms this -

========================================================================
shailendra@shailendra-ubuntu:~$ sudo docker images
[info] GET /v1.15/images/json
[57c0b651] +job images()
[57c0b651] -job images() = OK (0)
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
apt_cacher_ng       latest              51a101306f81        13 days ago         253.4 MB
jenkins             latest              459cea0cc31f        2 weeks ago         661.8 MB
ubuntu              14.10               277eb4304907        4 weeks ago         228.5 MB
shailendra@shailendra-ubuntu:~$ curl -v -X POST http://localhost:5555/images/create?repo=ubuntu&tag=14.10
[2] 1817
shailendra@shailendra-ubuntu:~$ * Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 5555 (#0)
>[info] POST /images/create?repo=ubuntu
[57c0b651] +job import(, ubuntu, )
Get http://: http: no Host in request URL
 POST /images/create?repo=ubuntu HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:5555
> Accept: */*
>
< [57c0b651] -job import(, ubuntu, ) = ERR (1)
HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 26 Nov 2014 21:26:56 GMT
< Transfer-Encoding: chunked
<
{"status":"Downloading from http://"}
{"errorDetail":{"message":"Get http://: http: no Host in request URL"},"error":"Get http://: http: no Host in request URL"}
* Connection #0 to host localhost left intact
^C
[2]+  Done                    curl -v -X POST http://localhost:5555/images/create?repo=ubuntu

=============================================================================
shailendra@shailendra-ubuntu:~$ curl -v -X POST http://localhost:5555/images/create?fromImage=ubuntu&tag=14.10
[2] 1819
shailendra@shailendra-ubuntu:~$ * Hostname was NOT found in DNS cache
*   Trying ::1...
* Connected to localhost (::1) port 5555 (#0)
>[info] POST /images/create?fromImage=ubuntu
[57c0b651] +job pull(ubuntu, )
 POST /images/create?fromImage=ubuntu HTTP/1.1
> User-Agent: curl/7.37.1
> Host: localhost:5555
> Accept: */*
>
[57c0b651] +job trust_update_base()
[57c0b651] -job trust_update_base() = OK (0)
[57c0b651] +job trust_key_check(/library/ubuntu)
[57c0b651] -job trust_key_check(/library/ubuntu) = OK (0)
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Wed, 26 Nov 2014 21:27:27 GMT
< Transfer-Encoding: chunked
<
{"status":"The image you are pulling has been verified","id":"ubuntu:12.04"}
......
.....

==============================================================================
shailendra@shailendra-ubuntu:~$ sudo docker images
[info] GET /v1.15/images/json
[57c0b651] +job images()
[57c0b651] -job images() = OK (0)
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
ubuntu              15.04               76f2fd412141        24 hours ago        116.6 MB
ubuntu              vivid               76f2fd412141        24 hours ago        116.6 MB
ubuntu              trusty              86ce37374f40        24 hours ago        192.7 MB
ubuntu              14.04               86ce37374f40        24 hours ago        192.7 MB
ubuntu              latest              86ce37374f40        24 hours ago        192.7 MB
ubuntu              14.04.1             86ce37374f40        24 hours ago        192.7 MB
ubuntu              precise             120acb8ad8a3        24 hours ago        128.2 MB
ubuntu              12.04               120acb8ad8a3        24 hours ago        128.2 MB
ubuntu              12.04.5             120acb8ad8a3        24 hours ago        128.2 MB
apt_cacher_ng       latest              51a101306f81        13 days ago         253.4 MB
jenkins             latest              459cea0cc31f        2 weeks ago         661.8 MB
ubuntu              utopic              277eb4304907        4 weeks ago         228.5 MB
ubuntu              14.10               277eb4304907        4 weeks ago         228.5 MB

=============================================================================

Not sure why this endpoint expects a POST request when documentation does not mention anything about request body.

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/5722
