### ISSUE TITLE
Do Not pull all image aliases for id

### ISSUE THREAD

**Issue by dustinlacewell** [docker/docker#9373]
In https://github.com/docker/docker/issues/8141 the issue was raised that Docker wasn't pulling all tag aliases that pointed to the same image. For example, if you were to pull "debian:latest" it wouldn't pull any tags that aliased that layer.

https://github.com/docker/docker/pull/8193 is the pull request that changed this behavior.

This isn't great for me. In a highly automated scenario where an image is pulled down on a host, this new behavior complicates removing that pulled image. If some automation knows that it wants to pull "foo/bar:baz" and then later RMI that image, it cannot do so naively since there is always the potential that Docker has tagged that image with extra tags even though you have not asked it to. 

Since the automation only knows about "baz" it will have to always iterate over the images and ensure that no other dangling tags exist. This is non-ideal for behavior that worked perfectly for this use-case before. 

If we must support both use-cases then perhaps a flag somewhere can allow the client to specify the behavior.

**Comment by jfrazelle** [comment]
closing as dup of #8689 and they arent going to implement it in v2 anyway
