### ISSUE TITLE
Document Docker container attach WebSocket endpoint

### ISSUE THREAD

**Issue by parisk** [docker/docker#9374]
As of [Docker Remote API v1.15](http://docs.docker.com/reference/api/docker_remote_api_v1.15/#attach-to-a-container), the WebSocket endpoint for attaching to a container's TTY has not been documented, [while it exists](https://github.com/docker/docker/blob/master/api/server/server.go#L916).

I suppose that it would be really helpful to have this kind of information into the Docker docs.

**Comment by resouer** [comment]
should be closed now: http://docs.docker.com/reference/api/docker_remote_api_v1.15/#attach-to-a-container-websocket
