### ISSUE TITLE
Docker events for images - include new image download, image update events

### ISSUE THREAD

**Issue by ranjanparth** [docker/docker#9376]
Docker events are limited as of now to untag and delete. For the purposes of inventory management as well as trouble shooting, it would be good to include additional events for image download as well as image updates. Ranjan

**Comment by duglin** [comment]
Just tried this on the latest docker and I see both "pull" and "push" events in the event stream now. I think we can close this. If you still think we're missing events can you please reopen it with the list?  thanks!
