### ISSUE TITLE
dpkg-buildpackage fails on aarch64

### ISSUE THREAD

**Issue by ikitayama** [docker/docker#9380]
After applying a patch from http://paste.ubuntu.com/8576906/, I tried dpkg-buildpackage command
below:
  
itaru.kitayama@r1-a12:/tmp/docker.io-1.2.0~dfsg1$ dpkg-buildpackage -b -us -uc
dpkg-buildpackage: source package docker.io
dpkg-buildpackage: source version 1.2.0~dfsg1-1ubuntu2~test1
dpkg-buildpackage: source distribution utopic
dpkg-buildpackage: source changed by Michael Hudson-Doyle <michael.hudson@canonical.com>
dpkg-buildpackage: host architecture arm64
 dpkg-source --before-build docker.io-1.2.0~dfsg1
 fakeroot debian/rules clean
dh clean --buildsystem=golang --with=golang,systemd,bash-completion
   dh_testdir -O--buildsystem=golang
   dh_auto_clean -O--buildsystem=golang
   dh_clean -O--buildsystem=golang
 debian/rules build
dh build --buildsystem=golang --with=golang,systemd,bash-completion
   dh_testdir -O--buildsystem=golang
   dh_auto_configure -O--buildsystem=golang
   debian/rules override_dh_auto_build
make[1]: Entering directory '/tmp/docker.io-1.2.0~dfsg1'
ln -sf "$(readlink -f libcontainer)" "/tmp/docker.io-1.2.0~dfsg1/obj-aarch64-linux-gnu/src/github.com/docker/"
./hack/make.sh dynbinary-gccgo
# WARNING! I don't seem to be running in the Docker container.
# The result of this command might be an incorrect build, and will not be
#   officially supported.
#
# Try this instead: make all
#

bundles/1.2.0 already exists. Removing.

---> Making bundle: dynbinary-gccgo (in bundles/1.2.0/dynbinary-gccgo)
# _/tmp/docker.io-1.2.0~dfsg1/dockerinit
/usr/lib/gcc/aarch64-linux-gnu/4.9/libgo.a(net.o): In function `net.lookupPort':
(.text+0x62cc): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/aarch64-linux-gnu/4.9/libgo.a(syscall.o): In function `syscall.Ustat':
(.text+0x88a8): warning: ustat is not implemented and will always fail
Created binary: /tmp/docker.io-1.2.0~dfsg1/bundles/1.2.0/dynbinary-gccgo/dockerinit-1.2.0
# github.com/docker/docker/archive
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:173:6: error: reference to undefined field or method ‘Xattrs’
   hdr.Xattrs = make(map[string]string)
      ^
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:174:6: error: reference to undefined field or method ‘Xattrs’
   hdr.Xattrs["security.capability"] = string(capability)
      ^
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:268:29: error: reference to undefined field or method ‘Xattrs’
  for key, value := range hdr.Xattrs {
                             ^
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:268:29: error: reference to undefined field or method ‘Xattrs’
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:268:29: error: reference to undefined field or method ‘Xattrs’
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:268:6: error: invalid type for range clause
  for key, value := range hdr.Xattrs {
      ^
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:268:6: error: invalid type for range clause
obj-aarch64-linux-gnu/src/github.com/docker/docker/archive/archive.go:268:2: error: range clause must have array, slice, string, map, or channel type
  for key, value := range hdr.Xattrs {
  ^
debian/rules:40: recipe for target 'override_dh_auto_build' failed
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory '/tmp/docker.io-1.2.0~dfsg1'
debian/rules:106: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by jfrazelle** [comment]
can you  try with master

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen
