### ISSUE TITLE
Firewalld support

### ISSUE THREAD

**Issue by jpopelka** [docker/docker#9395]
Hello,

Because Docker creates its own firewall rules, a restart of firewall managing service means, that all previously added Docker firewall rules are flushed. Would it be great if Docker knew how to react to it and recreate the rules again ?

Most distributions use iptables service, but for example RHEL-7 and Fedora use Firewalld [1] service/daemon by default. It has a D-Bus interface and it's possible to detect that it's been restarted/reloaded.

I already have some patches we can start with, I'll create pull request shortly.
It's my first go code so please have some patience with me.

Thank you !

[1] http://www.firewalld.org/

**Comment by clnperez** [comment]
Hi @jpopelka. I'm having trouble getting upstream docker to start (using Fedora 21), and git bisect narrowed it down to commit 8301dcc6d702a97feeb968ee79ae381fd8a4997a. I stopped firewalld and docker starts up fine. Restarted it, and docker hangs on start (sudo systemctl start docker). Have you seen anything like this?

**Comment by LK4D4** [comment]
@clnperez Whoa, that's pretty bad. Would you mind to create new issue for this? Also maybe there is some logs from docker process.

**Comment by jpopelka** [comment]
@clnperez No, I haven't seen this. Some debug messages from docker ('-D') and firewalld (--debug) would be helpful. You can stop firewalld service (systemctl stop firewalld) and run it with debug enabled like 'firewalld --nofork --nopid --debug' and then check if you see anything suspicious when you (re)start docker.

**Comment by ajostergaard** [comment]
@jpopelka I thought you might be interested in #13433.

**Comment by jfrazelle** [comment]
we have this now
