### ISSUE TITLE
docs: add information about using regular init system

### ISSUE THREAD

**Issue by smartinsightsfromdata** [docker/docker#9403]
This should be similar to https://github.com/docker/docker/issues/1024
I am using:
OSX yosemite
docker 1.3.1
boot2docker 1.3.2
I use as a **centos** base from sequenceiq: https://github.com/sequenceiq/hadoop-docker 
I try to install R and RStudio.  R does not give any problem, but this is what I get from RStudio:
###
Install       1 Package(s)
Total size: 276 M
Installed size: 276 M
Downloading Packages:
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : rstudio-server-0.98.1091-1.x86_64                            1/1 
groupadd: group 'rstudio-server' already exists
rsession: no process killed
**initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused**
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
  Verifying  : rstudio-server-0.98.1091-1.x86_64                            1/1 
Installed:
  rstudio-server.x86_64 0:0.98.1091-1                                           
Complete!
###
At the end of all the components load, I get:

Step 31 : RUN echo rstudio | passwd --stdin rstudio
 ---> Running in 6bd3038eec99
/usr/share/cracklib/pw_dict.pwd: No such file or directory
PWOpen: Invalid argument
##
Please note that the error message referring to ubuntu does not help to understand what is the issue.

Thanks in advance for any help.

**Comment by unclejack** [comment]
@SvenDowideit @fredlf This is another occurrence of the endless discussion around the lack of the regular init process. Perhaps some documentation around this specific difference between a regular system and containers would be useful?

**Comment by SvenDowideit** [comment]
agreed :/

**Comment by smartinsightsfromdata** [comment]
@unclejack @SvenDowideit @jfrazelle Hi

Apologies, but I am still at a loss to understand if anything can be done to fix this?

The fact that the question is still open makes me think that nothing much has happened?
