### ISSUE TITLE
Docs: Remove defaults for (boolean)flags/options that expect no value

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#9406]
Related: https://github.com/docker/docker/issues/9393, https://github.com/docker/docker/issues/5545

The way that default values for boolean flags/options is documented is confusing for some people and choosing a simpler notation could take away that confusion.

For example;

    -v, --version=false               Print version information and quit

Could be interpreted as;

"To print version information, run `docker --version=false`", whereas it *should* be used;
`docker --version`.

*Technically*, it could be used as `docker --version=true`, but I doubt many people will find
that useful, so *not* documenting this seems reasonable to me.

### Proposed change

Change the documentation (and help) for flags/options that *don't* require/expect a value, and 
remove the default value. Flags that *do* accept a value should still mention this.

The documentation will look like this;

    -v, --version               Print version information and quit

### Other software

I did a quick check how other software handles this. Some examples are below;

    # MySQL:
     -V, --version       Output version information and exit.
     --select-limit=#    Automatic limit for SELECT when using --safe-updates.
     
     --server-arg=name   Send embedded server this as a parameter.

    # GIT
    usage: git [--version] [--help] [-C <path>] [-c name=value]    

    # Fig
    Options:
      --version                 Print version and exit
      -f, --file FILE           Specify an alternate fig file (default: fig.yml)
      -p, --project-name NAME   Specify an alternate project name (default: directory name)

    # SubVersion (svn checkout)
    Valid options:
      -r [--revision] ARG      : ARG (some commands also take ARG1:ARG2 range)
                                 [edited]
      -q [--quiet]             : print nothing, or only summary information

**NOTE**
This proposal does *not* intent to change the way flags are working right now, 
only change the way it is *documented*. Changing the behavior of flags and renaming
was proposed in the past (https://github.com/docker/docker/pull/5760, https://github.com/docker/docker/pull/5764) and voted against / rejected, so please do not bring that up here again.

**Comment by amouat** [comment]
Fully agree with changing the documentation to this format, I found it very confusing when trying to write some reference materials.

Also note the usage information on boolean flags is wrong afaict, so it's not just me that's confused. https://github.com/docker/docker/issues/10517

**Comment by bboreham** [comment]
Note [this change](https://go.googlesource.com/go/+/51d66601c45572484ed20f3a2be6f67d648b5f22) to the Go flag package to stop mentioning "=false" when that's what the flag defaults to.

**Comment by thaJeztah** [comment]
@bboreham thanks for the heads up, that *does* look a lot better!
