### ISSUE TITLE
Proposal: allow ANSI colors in docker ps

### ISSUE THREAD

**Issue by agonzalezro** [docker/docker#9417]
Hi,

I've been trying to create a pull request to add a new flag to the `docker ps` command. I was trying to add `-c/--colors` to show:

- red for the exited containers.
- green for the running ones.
- yellow for the restarting.

The PR was kinda easy, but the problem is that `text/tabwriter` from the Golang standard library doesn't seem to allow the special chars needed, for example: `\x1b[0m`. With "doesn't allow" I mean that the colors are added to the output, but the length of them is added as well and those ANSI codes are invisible which makes the output look weird:

![Imgur](http://i.imgur.com/ktcJqKu.png)

Perhaps this is going to be an issue in the future and the library should be changed? I couldn't manage to escape the lengths with the current situation and I don't think that it's possible (I double checked with some people and they agree). If you think that there is a solution without changing the library or that the change doesn't worth a change of library, please, let me know.

**Comment by azbarcea** [comment]
@duglin this make a lot of sense. I would expect something like ```git``` has the ```color.ui=true```. Starting this with ```docker ps``` is a great idea. I wonder why this thread didn't get a lot of traction ?!?

**Comment by derimagia** [comment]
See grc which now has docker support (Pretty popular general color-izer)

https://github.com/garabik/grc

I made some tweaks to the colors for docker-ps, please let me know if you see any issues:

https://github.com/garabik/grc/pull/27

**Comment by agonzalezro** [comment]
It's pretty cool @derimagia, thanks!

**Comment by samoht** [comment]
See https://github.com/docker/docker/pull/22162

**Comment by samoht** [comment]
@jfrazelle what do you recommend to replace `text/tabwriter`?

**Comment by jfrazelle** [comment]
Well you would need something to support colors but this would need to be
approved first before getting started and honestly IMO it's a large change
that will cause a bikeshed of what should be what color and more for
maintainers to maintain

On Wednesday, April 20, 2016, Thomas Gazagnaire <notifications@github.com>
wrote:

> @jfrazelle <https://github.com/jfrazelle> what do you recommend to
> replace text/tabwriter?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/9417#issuecomment-212353238>
>


-- 


Jessie Frazelle
4096R / D4C4 DD60 0D66 F65A 8EFC  511E 18F3 685C 0022 BFF3
pgp.mit.edu <http://pgp.mit.edu/pks/lookup?op=get&search=0x18F3685C0022BFF3>

**Comment by samoht** [comment]
In #22162 I've just added the ability to add color in the `--format` string so everyone could add an alias to `docker ps` with its favorite colors.

**Comment by thaJeztah** [comment]
We discussed this feature on https://github.com/docker/docker/pull/22162, and decided that we're not going to implement this; it's too much of a "nice to have", and there are existing solutions that allow colorizing the output (see https://github.com/docker/docker/issues/9417#issuecomment-202234604 above).

Thanks for suggesting though! And sorry that it's not accepted
