### ISSUE TITLE
About  container PRECESS NAME'S issues

### ISSUE THREAD

**Issue by lao-cunzhang** [docker/docker#9419]
HI'

    we  use Centos  for  machine, and  ubuntu14.10  for container  images.

[root@CWEB~]# docker version
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.3
Git commit (client): 2a2f26c/1.2.0
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.3
Git commit (server): 2a2f26c/1.2.0

     now, we found container's  precess  USER NAME  may  used  by  machine system USER_NAME so that  PRECESS USER  not  right.
     
The container  /etc/passwd follow  info:
more /etc/passwd 
dockerweb:x:1000:1000::/home/dockerweb:/bin/bash

the machine  system /etc/passwd  follow info:
more /etc/passwd 
inter:x:1000:1000::/home/inter:/bin/bash

we  start  container  , the  PRECESS NAME  should  be  “dockerweb” ,But  in fact  it's “inter”.  

mail:star.liupeng@gmail.com

thanks.

**Comment by jfrazelle** [comment]
closing please let us know the exact steps to reproduce
