### ISSUE TITLE
More graceful daemon restarts

### ISSUE THREAD

**Issue by Sirupsen** [docker/docker#9433]
Currently when restarting the daemon (e.g. for an upgrade) our `docker run` processes just fail with:

```
2014-12-01_15:18:44.23585 2014/12/01 15:18:44 Cannot connect to the Docker daemon. Is 'docker -d' running on this host?
```

Which'll terminate the containers in a non-graceful way. This makes Docker upgrades non-trivial when you have many hosts, we essentially have to write our own wrapper which is even worse if you're using the official Debian package you have to override `.postinst` or install with `--no-triggers` and do the restart yourself. We have a script that stops all our containers gracefully (essentially `docker stop`), takes the node out of rotation (custom) and then restarts the daemon and starts the containers again. Overriding the `init` script doesn't really seem to be an option either, since it seems like something that'd change fairly often upstream.

The default seems extremely unsafe.

Don't know who to tag here, @crosbymichael @jfrazelle maybe you'll know? This is hurting us again as we want to test the RC in production.

**Comment by nicocesar** [comment]
@LK4D4 where do you get the 5 seconds and 10 seconds delays? could you  point me out to the code?. for my usecase will be great to be hours instead of seconds (we use it for batch gnome processing at curoverse.com)

**Comment by runcom** [comment]
@nicocesar now the daemon just wait 15 seconds in total here https://github.com/docker/docker/blob/master/docker/daemon.go#L172 (and on error also)

**Comment by LK4D4** [comment]
Okay, I checked. Processes which not dies with SIGTERM, still alive after daemon stopping, but they'll be brutally killed with SIGKILL on next daemon start.

**Comment by thaJeztah** [comment]
@LK4D4 does https://github.com/docker/docker/pull/12400 change that behavior?

**Comment by cpuguy83** [comment]
Yes, today (on master only) the daemon will sig TERM, wait 10 seconds, then kill.
Anything that is somehow still around on daemon start is also killed.

I think we're good to close this?

**Comment by thaJeztah** [comment]
I'm closing this issue, also note that we now allow setting the stop-signal to use for a container, and work is in progress to customize the time before a container is killed, per container https://github.com/docker/docker/pull/22566, and globally https://github.com/docker/docker/pull/23036

Finally, we're working on allowing the daemon to be upgraded without restarting containers, which should land in docker 1.12
