### ISSUE TITLE
yum progress bar doesn't display during build

### ISSUE THREAD

**Issue by djdevin** [docker/docker#9444]
I have a Dockerfile that simply runs a "yum -y update".

It works, but the yum progress bar is nowhere to be found, so there is no indication that anything is happening. I originally thought I had network issues, but then saw my traffic graph shooting up during the "hang".

I believe this is because the progress bars do not display when the output is not a TTY.

This is a minor inconvenience.

Docker version 1.3.1, build 4e9bbfa/1.3.1
centos:centos6

**Comment by unclejack** [comment]
I'm going to close this in favor of #10033 because there are more comments on that issue.

I'm locking this issue to ensure discussion only takes place on #10033. If you see this issue, please go to #10033 instead.
