### ISSUE TITLE
.dockerignore doesn't used during docker hub automated build

### ISSUE THREAD

**Issue by zdm** [docker/docker#9455]
I setup automated build for my bitbucket repo.
But I see, that automatically builded image contains all directories, that described in .dockerignore and shouldn't be added to image file system.
For example, I have following .dockerignore:
```
.hg
.hgignore
.hgsub
.hgsubstate
.hgtags
data
log
resources
```
In automatically builded image all this directories are exists.

When I build this image manually - everything works as expected - directories, listed above, are ignored and not present in image.

**Comment by zdm** [comment]
We can see, what docker version used now, at the beginning of build log.

Now it is 3.2.2.

**Comment by jfrazelle** [comment]
3.2.2 is not a docker version. Do you mean 1.3.2 or 1.2?

**Comment by LK4D4** [comment]
ping @duglin 
Isn't #8748 was fix for this?

**Comment by zdm** [comment]
Yes, you are right. Version is 1.3.3. Sorry.

```
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 3ea0e03
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 3ea0e03
```

**Comment by duglin** [comment]
@LK4D4 #8748 would only fix it if .dockerignore was in .dockerignore but I think they're seeing a more basic issue and I suspect the hub is just using an old docker as @thaJeztah thinks

**Comment by kmike** [comment]
Dockerhub seems to use docker 1.5 now, but .dockerignore still doesn't work.

```
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): linux/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
```

See  https://registry.hub.docker.com/u/scrapinghub/splash/builds_history/16922/  and https://github.com/scrapinghub/splash/issues/183.

**Comment by thaJeztah** [comment]
@kmike the "Server version" in you output refers to your *local* server (i.e., your daemon), not the version running in Docker Hub. It's still possible that the Docker Hub is running an older version, which would explain `.dockerignore` not working.

**Comment by kmike** [comment]
@thaJeztah the excerpt is from these logs: https://registry.hub.docker.com/u/scrapinghub/splash/build_id/4552/code/bfxhfyy8u2fvwcyyh36eg9a/; they can't contain a version of my local daemon.

**Comment by thaJeztah** [comment]
@kmike oh, apologies! I mistakenly assumed you thought "Server" meant the "Docker Hub server". (I don't have permissions to view the link, but I trust it's there). There's all kind of users here, and some don't fully understand the client/daemon.

In that case, yes, that's strange. @dmp42 have an idea?

Also, although interesting, this isn't an issue with *docker*, but with "Docker Hub"; should this be moved elsewhere?

**Comment by kmike** [comment]
No worries, and thanks for responding so fast.

> Also, although interesting, this isn't an issue with docker, but with "Docker Hub"; should this be moved elsewhere?

Agreed, the place doesn't look right. I just googled "dockerignore docker hub" and found this ticket with a description of a similar issue. I can only find a feedback email in hub.docker.com - is it a right way to report such issues?

**Comment by thaJeztah** [comment]
@kmike for issues with Docker Hub, you can send an email to support@docker.com (I think there's a form somewhere too, but I don't have the URL at hand) unfortunately there's no public issue tracker yet.

**Comment by kmike** [comment]
thanks @thaJeztah!

**Comment by kmike** [comment]
FYI: the answer from support team is that it is a known Docker Hub issue, and that at the moment the only work around is to build locally and the push the image.

**Comment by jfrazelle** [comment]
ah since this is a hub issue and not a docker issue closing

**Comment by Gallaecio** [comment]
https://github.com/docker/hub-feedback/issues/511
