### ISSUE TITLE
Improve error message when the image cannot be deleted

### ISSUE THREAD

**Issue by arun-gupta** [docker/docker#9458]
Trying to remove an image as:

~> docker rmi e4f1dbdff18956621aa48a83e5b05df309ee002c3668fa452f1235465d881020
Error response from daemon: Conflict, cannot delete e4f1dbdff189 because the container bafc2b3327a4 is using it, use -f to force
2014/12/02 12:56:53 Error: failed to remove one or more images

Followed the recommendation to use -f switch, and got another error:

~> docker rmi -f e4f1dbdff18956621aa48a83e5b05df309ee002c3668fa452f1235465d881020
Error response from daemon: No such id: c345720579e024df4f6d28d2062fda64b7743f7dbb214136d4d2285bc3afc95b
2014/12/02 12:56:55 Error: failed to remove one or more images

Finally, had to kill all the containers and then the image could be removed.

The error message need to be improved stating that "the image is used in a stopped container" or something similar.

**Comment by jfrazelle** [comment]
The "no such id" error was updated in the latest version, iirc, can you please update and try again?

**Comment by jfrazelle** [comment]
updated in latest, closing, let me know if you feel otherwise

**Comment by jfrazelle** [comment]
for reference https://github.com/docker/docker/pull/9204
