### ISSUE TITLE
run command did not work in the first time

### ISSUE THREAD

**Issue by miichy** [docker/docker#9465]
command:docker run -d -p 0.0.0.0:33307:22 -p 0.0.0.0:5000:5000 -v /home/registry/docker-image:/opt/docker-image -e STORAGE_PATH=/opt/docker-image registry

ps -ef|grep docker did not show the result.
the fifth time ,it works.

why?

**Comment by unclejack** [comment]
@miichy I've seen this problem as well. It was a `docker-registry` bug which was making the registry image stop running right away, not a Docker bug.

`docker logs` was clearly showing the error encountered by the registry. I'm going to close this now. If the problem still exists with the latest registry, the issue should be filed against `docker-registry`.

ping @dmp42
