### ISSUE TITLE
(Tries to) create /.docker

### ISSUE THREAD

**Issue by cgwalters** [docker/docker#9468]
Regression from PR #8112 from what I can tell; basically docker tries to mkdir("/.docker"), which is denied on Project Atomic hosts.

I think this might be the first use of $HOME in the engine, or at least that runs by default.  For Project Atomic we use systemd and docker's working directory is /.  Perhaps we should set WorkingDirectory=/var/lib/docker, but then we'd end up with /var/lib/docker/.docker which would be at least odd.

Downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1169593

**Comment by cgwalters** [comment]
Am I correct in that https://github.com/docker/docker/pull/8265 will go back to specifying the certificate location on the engine command line, and obviate the need for `$HOME` in the engine?

**Comment by crosbymichael** [comment]
This has been fixed by #10234
