### ISSUE TITLE
Bash completion is slow for `docker run`, `docker rmi`

### ISSUE THREAD

**Issue by cr7pt0gr4ph7** [docker/docker#9474]
# In detail (see below for short version)
When doing tab completion for image names for the following commands, there is always a 1 - 2 seconds delay after pressing tab:
* `docker run <tab>`
* `docker rmi <tab>`
* ...

Additionally, a large number of possible completions is generated (389 on my system), consisting of repositories, image names and image ids. Most of these (~350) are intermediate image ids, which should almost never be used by end users anyway.

I'd also argue that there is no real use case for completing image ids. Normal users won't normally be using numeric image ids, except for debugging. If I don't know the image id, seeing multiple image ids with the same prefix won't help me. (The only use case I can think of are sysadmins).

# TL; DR
There are two problems here:
* Slow completion (1 - 2 seconds is definitely to slow for interactive use)
* Too many (non-useful) completions (389 is too much)

I'd argue that there are the following options to fight the problems above:
* Show everything, including intermediate image ids (like `docker images --all`). This is the current situation.
* Show non-intermediate image ids (like `docker images`).
* Only show repositories and tags.
* Only show repositories, and show tags only after the user has typed `:`

I'd vote for making this configurable (e.g. via an environment variable in `.bashrc` or globally via another file), and making the third option the default. The delay as well as the number of generated completions decrease from top to bottom.

# Addendum: Proposal
The configuration option could look like this:
```bash
DOCKER_IMAGE_COMPLETION=(all_images|non_intermediate_images),repositories,tags
```
the default would be:
```bash
DOCKER_IMAGE_COMPLETION=repositories
```

**Comment by albers** [comment]
I do not find completing IDs useful. I'm a not sure about whether or not listing tags is desirable. You might get some suggestions about available tags early, but at the cost of cluttered output. In this respect, a more hierarchical way of drilling down (considering tags only after a colon was typed) might be helpful.

Both decisions strongly depend on how many images / tags are available and your personal preference, so a configurable approach sounds reasonable. I do not know of any other configurable completions, but the environment variable approach sounds promising as it is easy to use, implement and document.

I would prefer two environment variables, though:
 - one for configuring the amount of included image IDs: `DOCKER_COMPLETION_SHOW_IMAGE_IDS=all|non-intermediate|none`, the default being `none`
 - one for whether or not to include tags: `DOCKER_COMPLETION_SHOW_TAGS=yes|no` for which I suggest a default of `no`.

**Comment by pugnascotia** [comment]
#dibs

**Comment by tianon** [comment]
Did we ever find any examples of other completion scripts (especially in the official `bash-completion` set) that have configurable knobs so that we can make sure we're following any existing conventions?

**Comment by pugnascotia** [comment]
I didn't see anything obvious from a previous glance through, but I'll take
another look tomorrow. It would be good to follow conventions.

**Comment by pugnascotia** [comment]
On my Ubuntu 14.04 machine, I found two examples in the main bash completion file, referencing $COMP_KNOWN_HOSTS_WITH_AVAHI (thought that option was disabled) and COMP_KNOWN_HOSTS_WITH_HOSTFILE. Each is just an "if" block, so I think we're good.
