### ISSUE TITLE
[RFC]: Automation to keep docs, bash completions, etc in sync

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#9478]
This is a request for comments to either build our own tooling, or use existing tools to do the following:

- Keep bash completions in sync with the client (when flags are added, etc)
- Keep API docs up to date when the API is updated/ new things are added
- Keep man pages in sync with changes to the client

If anyone has existing tools they think would be good for this, please comment. The problems that we have seen with suggested tools in the past are that they are not easily integrated to our setup and we cannot benefit from all the features they provide. Also we wind up only solving part of the problem. So it ends up feeling like a big, heavy bandaid and is not ideal.

**Comment by albers** [comment]
Assuming that you can trigger bash completion ([example](http://stackoverflow.com/questions/9137245/unit-test-for-bash-completion-script)) and capture its output, there could be a script that extracts the available commands and options from the output of `docker --help` and compares the result with the parsed output of bash completion for `docker` and `docker -`.
Then, it could verify each docker command in the same way.
This would give us a report of differences that could either be resolved or filed as an issue.

**Comment by SvenDowideit** [comment]
bash completion should really be generated _from_ the cli code too :)

TBH, my python script was written at a time when I was under the impression that the Docker project would use python more - it'll get re-written in go some day.

**Comment by albers** [comment]
Of course, but this would give you a very basic and generic completion. To regenerate the full feature set of the current completion, a lot of meta information and a templating mechanism would have to be added. The added tooling would complicate the process of adding new completions.

I think an automated verification step is more realistic and would be sufficient.

**Comment by albers** [comment]
@SvenDowideit see #10572 for parsing docker help output in go.
