### ISSUE TITLE
Comment: State 'docker.loaded' found in SLS 'foo' is unavailable

### ISSUE THREAD

**Issue by mooperd** [docker/docker#9505]
I'm unsure if I am using this correctly but I am seeing the following error:

In my init.sls I have the following:
 
app-container-file:
  docker.loaded:
    - name: gunicorn-app-test
    - source: salt://native/gunicorn-app-test.tar

Produces errors
----------
          ID: app-container-file
    Function: docker.loaded
        Name: gunicorn-app-test
      Result: False
     Comment: State 'docker.loaded' found in SLS 'native' is unavailable
     Started: 
    Duration: 
     Changes:   
----------

docker-py                 0.5.0 (and tried 0.6.0)
Salt                           2014.7.0

**Comment by unclejack** [comment]
@mooperd This isn't salt's issue tracker. Perhaps you should file this issue on https://github.com/saltstack/salt. We can't help you.
