### ISSUE TITLE
docker logs <container id> | grep <some value> doesn't work

### ISSUE THREAD

**Issue by billumina** [docker/docker#9508]
docker logs -f <container id> doesn't cut it with a busy log file. :)

**Comment by simonavril** [comment]
savril@savril-laptop:~/workspace/$ docker logs grave_newton  
    mkdir: cannot create directory '/var/www/foo/application/config': File exists
    savril@savril-laptop:~/workspace/$ docker logs grave_newton | grep File
    mkdir: cannot create directory '/var/www/foo/application/config': File exists
    savril@savril-laptop:~/workspace/$ docker -v
    Docker version 1.4.1, build 5bc2ff8

**Comment by simonavril** [comment]
savril@savril-laptop:~/workspace/$ docker logs grave_newton  
mkdir: cannot create directory '/var/www/foo/application/config': File exists
savril@savril-laptop:~/workspace/$ docker logs grave_newton | grep hello
mkdir: cannot create directory '/var/www/foo/application/config': File exists
savril@savril-laptop:~/workspace/$ docker -v
Docker version 1.4.1, build 5bc2ff8

**Comment by cpuguy83** [comment]
@simonavril This is because your log entry is for stderr, piping works with stdout.
instead do
```bash
docker logs 2>&1 | grep hello
# OR
docker logs 2>/dev/null | grep hello
```

**Comment by simonavril** [comment]
@cpuguy83 Thanks a lot for that.

**Comment by lucasavila** [comment]
try docker logs -f --tail 0 <container>

**Comment by goatwu1993** [comment]
> try docker logs -f --tail 0 container

Why so many thumbs down?

```
docker logs -f container_id 2>&1 | grep "something"
```
This does not work on my app.

```
docker logs -f --tail 0 container_id 2>&1 | grep "something"
```
This DOES work
