### ISSUE TITLE
Cascading restart for linked containers

### ISSUE THREAD

**Issue by JensErat** [docker/docker#9526]
When restarting a container, it _might_ get another IP address. This will break linked containers.

I'd love to have something like `docker restart --cascading [container]`

**Comment by gdm85** [comment]
+1 for killing env vars (on long run)!

I am also having problems with the dynamically allocated port range (which changed and I expected it to not change), but I will eventually open another issue for this

**Comment by gdm85** [comment]
@JensErat see also #8723 and #9678 (with [my comment there](https://github.com/docker/docker/issues/9678#issuecomment-71102191)).

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/issues/10096 https://github.com/docker/docker/issues/9047 https://github.com/docker/docker/issues/7540 https://github.com/docker/docker/issues/2801 dup
