### ISSUE TITLE
Docker Proxy Exceptions

### ISSUE THREAD

**Issue by MitchK** [docker/docker#9531]
We have an internal registry within our corporate network. We need to connect to an internal registry AND connect to the internet for making requests against a public registry, for instance.

How can we have proxy exceptions with Docker?

**Comment by jfrazelle** [comment]
please see docker/distribution#92

**Comment by dmp42** [comment]
@jfrazelle not sure why you linked this one :)

@MitchK use the NO_PROXY environment variable.
