### ISSUE TITLE
ADD in Dockerfile leads to 'unexpected EOF' in Vagrant under Win

### ISSUE THREAD

**Issue by ThomasSteinbach** [docker/docker#9532]
I have a serious error that occurs not in every execution: Inside a vagrant-Ubuntu-machine deployed under Windows 7 I build a Dockerfile containing an *ADD url* statement. Sometimes the download starts slowly, becomes even slower and finally fails with following output: **ERROR: unexpected EOF**.

Here is the related vagrant file...

```
Vagrant.configure("2") do | config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, path: "bootstrap.sh"
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end
```

... here the bootstrap.sh for the vagrant file...

```
#!/usr/bin/env bash
if [ ! -e /usr/lib/apt/methods/https ]; then
	apt-get update
	apt-get install -y apt-transport-https
fi
echo deb https://get.docker.com/ubuntu docker main > /etc/apt/sources.list.d/docker.list
apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
apt-get update
apt-get install -y lxc-docker
```

... and finally the Dockerfile I tried to build inside the VM. The Dockerfile is pruned after the ADD line, to show just the relevant part:

```
FROM java:latest
MAINTAINER Thomas Steinbach

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y unzip
ADD http://downloads.sourceforge.net/project/lportal/Liferay%20Portal/6.2.1%20GA2/liferay-portal-tomcat-6.2-ce-ga2-20140319114139101.zip /tmp/
```

However, sometimes it works, some times not. To reproduce, install Vagrant under Windows, put the first two codeblocks in the appropriate Files (*Vagrantfile* and *bootstrap.sh*) and run following command:
```
vagrant up
```
SSH to the VM, creat the Dockerfile with the content shown above and build it. Maybe you have to retry those steps several times, till the error occurs.

**Comment by jfrazelle** [comment]
i cannot reproduce with the latest docker version, if you try and can, please give us the steps to reproduce
