### ISSUE TITLE
docker and iptable insertions

### ISSUE THREAD

**Issue by fruitl00p** [docker/docker#9549]
Yesterday at DockerconAmsterdam / hackaton i spoke to @shykes about the following issue:
Using UFW on the host running docker to limit access to published ports from a container. Isn't really easily possible due to (partly) the fact that the docker deaemon inserts the iptable rules before UFW is allowed to intercept traffic.
(This question is also discussed on http://serverfault.com/questions/641875/how-to-utilize-ufw-blocking-published-ports-from-docker/644079 and might be related to #1251 and #4737 )

Currently the only real way to allow block outside traffic using UFW on the host to containers within is by injecting new rules into iptables manually every container restart... (``` iptables -I FORWARD 1 -p tcp -i eth0 -s [allowedsourceIP] --dport [containerport] -j ACCEPT``` etc)

Since the documentation doesnt really mention anything about this and because the rules are injected (and not appended by the daemon) this solution feels odd... (but might be easier to implement after #9548)

**Comment by unclejack** [comment]
@fruitl00p #7003 has landed. I'll close this issue now and we can continue to discuss any more changes on this issue.
