### ISSUE TITLE
error while loading shared libraries: libvirt-lxc.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by tshrklr** [docker/docker#9577]
When trying to start libvirtd in ubuntu or even opensuse containers I see this error:

`/usr/sbin/libvirtd: error while loading shared libraries: libvirt-lxc.so.0: cannot open shared object file: Permission denied`

I suspect this issue could be related to https://github.com/docker/docker/issues/4704. I tried building and running my image with the storage-driver option, but that doesn't seem to help.
`docker --storage-driver="devicemapper" run -i -t --privileged --net=host <imagename>`

Docker version 1.3.2, build 39fa2fa
Host: Ubuntu 14.04

**Comment by jfrazelle** [comment]
can you give us the image you are building with, can you also try with the latest version of docker

**Comment by tshrklr** [comment]
For others who see this, either turn apparmor off or create a custom apparmor profile to fix this issue.

**Comment by wznoinski** [comment]
when using docker with Openstack Kolla you may need to aa-disable /usr/sbin/libvirt on the host that runs nova_libvirt container
