### ISSUE TITLE
No source file named，，，

### ISSUE THREAD

**Issue by oxwangfeng** [docker/docker#9580]
when i used the docker-dev image develop docker source，use the gdb tool like that，but，a error like “No source file named " happend.what wrong?

(gdb) pwd
Working directory /go/src/github.com/docker/docker/docker.
(gdb) cd 
README.md  client.go  daemon.go  docker.go  flags.go   
(gdb) cd 
README.md  client.go  daemon.go  docker.go  flags.go   
(gdb) break docker.go:20
No source file named docker.go.
Make breakpoint pending on future shared library load? (y or [n]) n
(gdb) pwd
Working directory /go/src/github.com/docker/docker/docker.

**Comment by oxwangfeng** [comment]
i resolve it

**Comment by loading86** [comment]
hi, i met the same problem, how did you solve it? thanks.
