### ISSUE TITLE
Unable to start Docker due device-mapper problem "Can't set cookie dm_task_set_cookie failed"

### ISSUE THREAD

**Issue by luan-cestari** [docker/docker#9587]
Hi,

I was running out of space on the partition where the docker was installed and I tried something like in this post http://blog.eye48.com/post/98551740424/when-docker-io-eats-up-your-disc-space  (insummary creating symbolic link to my home partition and using thin_check to fix the device-mapper ) after that I wasn't able to start docker. I already remove it and checked if any configuration file was forgot to be removed by I didn't find. I also removed the mounted point  /dev/mapper/docker-* using 'umount' and 'dmsetup remove' but it never come back (so I think that this is related to the docker start). I know that I did something very weird configuration, I was thinking that it could even not be a issue for this repository but I really thought this as a bug as I tried many times to reinstall and I still get stuck on the same place, so it might be something that we could enhance on the project. I tried to find the root cause by myself by I got bit lost on the code (http://fossies.org/linux/misc/docker-1.3.2.tar.gz/docker-1.3.2/daemon/graphdriver/devmapper/devmapper.go   https://github.com/docker/docker/blob/master/pkg/devicemapper/devmapper_wrapper.go). Also, I saw someone on the channel had this problem but it seems that he also couldn't find the answer ( 
https://botbot.me/freenode/docker/2014-08-28/?msg=20537274&page=8 his/her name is vsipuli and the mssage was on 2014-08-28 8:38 ).

Let me know if you need any other information.

The complete error message that I get is:

Dec 09 11:29:55 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
Dec 09 11:29:55 localhost.localdomain docker[32251]: 2014/12/09 11:29:55 docker daemon: 1.3.2 39fa2fa/1.3.2; execdriver: native; graphdriver:
Dec 09 11:29:55 localhost.localdomain docker[32251]: [e488efe9] +job serveapi(fd://)
Dec 09 11:29:55 localhost.localdomain docker[32251]: [info] Listening for HTTP on fd ()
Dec 09 11:29:55 localhost.localdomain docker[32251]: 2014/12/09 11:29:55 Can't set cookie dm_task_set_cookie failed
Dec 09 11:29:55 localhost.localdomain systemd[1]: docker.service: main process exited, code=exited, status=1/FAILURE
Dec 09 11:29:55 localhost.localdomain systemd[1]: Failed to start Docker Application Container Engine.
Dec 09 11:29:55 localhost.localdomain systemd[1]: Unit docker.service entered failed state.

 
Other information that can be helpful that I get before this happened  (but I still using the same kernel and etc).
[lcestari@localhost docker-oracle-xe-11g]$ uname -a
Linux localhost.localdomain 3.17.2-200.fc20.x86_64 #1 SMP Tue Nov 4 18:04:56 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[lcestari@localhost docker-oracle-xe-11g]$ docker version
Client version: 1.3.1
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 4e9bbfa/1.3.1
OS/Arch (client): linux/amd64
Server version: 1.3.1
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 4e9bbfa/1.3.1
[lcestari@localhost docker-oracle-xe-11g]$ docker -D info
Containers: 103
Images: 712
Storage Driver: devicemapper
Pool Name: docker-253:0-1447067-pool
Pool Blocksize: 65.54 kB
Data file: /var/lib/docker/devicemapper/devicemapper/data
Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
Data Space Used: 27.21 GB
Data Space Total: 107.4 GB
Metadata Space Used: 43.28 MB
Metadata Space Total: 2.147 GB
Library Version: 1.02.85 (2014-04-10)
Execution Driver: native-0.2
Kernel Version: 3.17.2-200.fc20.x86_64
Operating System: Fedora 20 (Heisenbug)
Debug mode (server): false
Debug mode (client): true
Fds: 19
Goroutines: 35
EventsListeners: 0
Init SHA1: b2de099a6b4ce9d739752a196ef798a0ff6a6c76
Init Path: /usr/libexec/docker/dockerinit

**Comment by tiankui626** [comment]
printf '250\t32000\t32\t1024' > /proc/sys/kernel/sem

**Comment by luan-cestari** [comment]
Hi @tiankui626 , are you suggesting to change the semaphore parameters to reproduce the problem?

**Comment by vbatts** [comment]
@luan-cestari docker 1.4 includes a lot of transactional cleanup for devmapper. This cookie limit hit by the default semaphore/cookie limit of 1024 has been an issue.
Would it be possible to test this again on recent build?

**Comment by rhvgoyal** [comment]
I had run into the issue of running out of semaphores but that was happening because we were not cleaning up the cookie on error path.

I thought we put a fix for that in. Does this happen with latest docker? If it still happens, may be still there are error paths where we don't call UdevWait() after setting up the cookie.

**Comment by luan-cestari** [comment]
I will try to reproduce it again in the weekend. Do you think that I should try using the version 1.5 ?

**Comment by rhvgoyal** [comment]
i think trying latest version is always a good idea.

**Comment by luan-cestari** [comment]
I couldn't reproduce the issue so far, probably one of the many entrancements or bug fixes did that
