### ISSUE TITLE
A way to ignore metadata changes for ADDed files

### ISSUE THREAD

**Issue by aalexgabi** [docker/docker#9593]
At the beginning of Dockerfile I have ADD addedfile. In a git repository I have two branches: A and B. In each branch I have a different version of addedfile. Each time I switch branch from A to B and then back to A, Docker detects a change in file metadata and rebuilds the image (which takes 15 minutes).

How can I ignore metadata changes?
Is there any quick fix or workaround for this?

**Comment by jfrazelle** [comment]
closing as dup of https://github.com/docker/docker/issues/4351
