### ISSUE TITLE
Images IDs starting with 12 digits < 10 in hexadecimal are reported as Json ints.

### ISSUE THREAD

**Issue by gbin** [docker/docker#9602]
This is an output extract from:
curl --insecure --cert ~/.boot2docker/certs/boot2docker-vm/cert.pem --key ~/.boot2docker/certs/boot2docker-vm/key.pem "https://192.168.59.103:2376/containers/json?all=1"

    [...]
    ,{"Command":"/usr/bin/python2.7 /home/vmagent/python_vm_runtime/vmboot.py","Created":1417715382,"Id":"053e51bd5f9d013bb2401bc99df5603b91e5d0d8c28ab58ecb4682dc0c03d9f2","Image":"e3c1457767f5","Names":["/google.appengine.devoxx2014-1.default.1.0.2014-12-04T174942.258498Z"],"Ports":[],"Status":"Exited (-1) 50 seconds ago"}
    ,{"Command":"/usr/bin/python2.7 /home/vmagent/python_vm_runtime/vmboot.py","Created":1417714659,"Id":"4342203927ca9e3bfc23dc4fe34c9e049e3f0db0877cc945f2b6cbbad2efc4ee","Image":"e3c1457767f5","Names":["/google.appengine.devoxx2014-1.default.1.0.2014-12-04T173739.442328Z"],"Ports":[],"Status":"Exited (-1) 50 seconds ago"}
    ,{"Command":"/usr/bin/python2.7 /home/vmagent/python_vm_runtime/vmboot.py","Created":1417714604,"Id":"a1455500f45896746e07fbdaca5213b610b423549346e2d280e8016b1fd7bc6f","Image":434145776745,"Names":["/google.appengine.devoxx2014-1.default.1.0.2014-12-04T173644.240734Z"],"Ports":[{"IP":"0.0.0.0","PrivatePort":8080,"PublicPort":49195,"Type":"tcp"}],"Status":"Exited (0) 26 seconds ago"}
[...]

See `"Image":434145776745` instead of `"Image":"434145776745"`

It compounds with another problem of overflow on the python docker client so it can give negative numbers.

**Comment by duglin** [comment]
hmm, why didn't git close this one automagically when #9610 was merged?

**Comment by unclejack** [comment]
As @duglin has stated above, this can be closed.
