### ISSUE TITLE
overlayfs - some integration-cli test fails

### ISSUE THREAD

**Issue by cpuguy83** [docker/docker#9612]
I'm seeing 3 integration-cli tests fail when using the overlay graph driver:

TestSaveAndLoadRepoStdout
TestSaveAndLoadRepoFlags
TestSaveDirectoryPermissions

**Comment by LK4D4** [comment]
I am closing this in favor of #9874 because `TestSaveAndLoadRepoStdout` passing now.

**Comment by thaJeztah** [comment]
@LK4D4 I think you forgot to actually *close* it

**Comment by LK4D4** [comment]
@thaJeztah thanks!
