### ISSUE TITLE
devicemapper cleanup

### ISSUE THREAD

**Issue by vbatts** [docker/docker#9614]
per https://github.com/docker/docker/pull/9258#issuecomment-66247203

>We read all the metadata files at startup to create the bitmap, so we take an i/o hit here, but we don't register the devices, but instead lazily re-read them as they are used. Doesn't it make more sense to store them when we read them?
> 
> There are some low hanging fruit in terms of performance in the bitmask. First of all, it could use an array of uint32 rather than bytes which will cause less array ops during a search. Secondly the find-unused-id could be much faster by scanning the array until it finds != 0xffffffff and then using a find-first-zero-bit op.
> 
> Also, given that we now have this in-memory we could be smarter about allocating new device ids to make them dense by quickly reusing low ids. I know that would make the bitmask more efficient, but it may also make the on-disk performance better with the devicemapper thin pool.

**Comment by LK4D4** [comment]
@rhvgoyal Is this fixed or is going to be fixed? Maybe we can close it?

**Comment by rhvgoyal** [comment]
@LK4D4 Some of these are possible imporovements. But nothing says that they are big gains. For now nothing is on my priority list. May be we can close this and open when we are actually changing something or this becomes a serious performance issue.

**Comment by LK4D4** [comment]
@rhvgoyal thank you very much for the answer. I appreciate it.
Closing this.
