### ISSUE TITLE
Duplicate port spec results in unstartable container

### ISSUE THREAD

**Issue by avaer** [docker/docker#9622]
When creating a container that address-binds the same port more than once, that (correctly) fails.

    docker run -t -i -p 127.0.0.1:9090:9091 -p 127.0.0.1:9090:9090 ubuntu bash
    2014/12/11 19:44:54 Error response from daemon: Cannot start container cdcc8ce8aa7539db230847e9df931fa38fa9b8405359d6b31dd9b2196c52d655: Bind for 127.0.0.1:9090 failed: port is already allocated

However ```docker``` willingly creates this bricked container that's unstartable due to binding errors. Note the misleading error message.

    docker start cdc
    Error response from daemon: Cannot start container cdc: Bind for 127.0.0.1:9090 failed: port is already allocated
    2014/12/11 19:52:15 Error: failed to start one or more containers

I guess the best solution would be to detect dupe bindings and error out sooner, and be more accurate with the error message. Save the next guy 10 minutes of port debugging.

**Comment by jfrazelle** [comment]
dupliicate https://github.com/docker/docker/issues/9797
