### ISSUE TITLE
Data container goes stale, won't mount volumes-from

### ISSUE THREAD

**Issue by devinrsmith** [docker/docker#9629]
When I first created the DATA container (backed by localhost storage) everything was working fine. After a while, it stopped mounting. I can remove the data container and recreate it (again since everything is backed by localhost storage), and everything works again for a while.

Any ideas? Am I doing something wrong?

```Shell
$ docker inspect DATA | grep -A 3 -E '"Volumes": {'
    "Volumes": {
        "/root/.m2": "/opt/data/m2"
    },

$ ls -la /opt/data/m2/settings.xml 
-rwxr-xr-x 1 root root 2024 Dec  2 19:56 /opt/data/m2/settings.xml

$ docker run --rm --volumes-from DATA busybox ls -la /root/.m2/settings.xml
ls: /root/.m2/settings.xml: No such file or directory

$ docker rm DATA
DATA

$ docker run --name DATA -v /opt/data/m2:/root/.m2 tianon/true

$ docker run --rm --volumes-from DATA busybox ls -la /root/.m2/settings.xml
-rwxr-xr-x    1 root     root          2024 Dec  2 19:56 /root/.m2/settings.xml
```

```Shell
$ docker -v
Docker version 1.3.2, build 39fa2fa
```

**Comment by devinrsmith** [comment]
```Shell
$ docker -D info
Containers: 17
Images: 121
Storage Driver: devicemapper
 Pool Name: docker-202:0-57921-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 5.823 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 8.503 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.16.7-x86_64-linode49
Operating System: Debian GNU/Linux 7 (wheezy)
Debug mode (server): false
Debug mode (client): true
Fds: 61
Goroutines: 42
EventsListeners: 0
Init Path: /usr/bin/docker
Username: dsmith
Registry: [https://index.docker.io/v1/]
WARNING: No memory limit support
WARNING: No swap limit support
```

**Comment by niloc132** [comment]
I'm seeing the same thing - I've had two data containers just fail to have content any longer. 

As luck would have it, I had both (different containers) wired to have their actual data mapped to the root file system, so losing the container wasn't a big deal and just required re-creating it, without any data loss, but if these can regularly die, I don't see myself changing to *not* map through to the host fs.

```
$ docker -D info
Containers: 10
Images: 152
Storage Driver: devicemapper
 Pool Name: docker-8:17-1048577-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 9.187 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 9.781 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.92 (2014-11-28)
Execution Driver: native-0.2
Kernel Version: 3.17.6-1-ARCH
Operating System: Arch Linux
CPUs: 4
Total Memory: 1.959 GiB
Name: hix
ID: 7QNA:T5UC:K6TJ:ZEVF:7FRA:XYX3:B3YV:R7VE:5CUE:BNKT:7Z6S:LEC3
Debug mode (server): false
Debug mode (client): true
Fds: 37
Goroutines: 33
EventsListeners: 0
Init SHA1: 7f82b25cad873786f2c2d72d9ceecc1d46e0a65b
Init Path: /usr/lib/docker/dockerinit
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
```

**Comment by crosbymichael** [comment]
ping @cpuguy83

**Comment by cpuguy83** [comment]
Maybe this is related to #9768 ?
Have you tried starting the data-containers again?

**Comment by niloc132** [comment]
I'll try the `docker start` next this this manifests, but it doesn't happen as consistently as that bug appears to (and as soon as it happens, I just delete the container and make a new one to get going again). Also, I am running docker only on one box, so I don't think that updating the local docker version is related.

**Comment by devinrsmith** [comment]
@cpuguy83 Just had this happen again to me today. I ran the data-container and that "fixed" it (for now).

**Comment by cpuguy83** [comment]
Are you able to repro? Was there a daemon restart? Some extra info would be super helpful.

Thanks!

**Comment by devinrsmith** [comment]
Yep. I actually upgraded from 1.1.2 to 1.4.1.

**Comment by devinrsmith** [comment]
Happened again after a machine reboot (on 1.4.1).

**Comment by cpuguy83** [comment]
I am unable to reproduce this in test :(

**Comment by devinrsmith** [comment]
Yeah. I'm not sure I can reliably reproduce it :/

**Comment by niloc132** [comment]
I appear to be able to consistently reproduce this on reboot. I'm running the `terrywang/archlinux` image on vagrant, with docker installed, configured, a data container, and a 'real' container.

* Create a data container, mapping through to a directory on the root fs (in vagrant)
* Create, run a container with that data container
* Confirm that files exist in the data container
* Stop, rm the container
* reboot
* re-create, run a container with the data container

At this point the error occurs. Invoking `docker run` on the data container allows the last step to succeed. 

I'll try from a totally fresh env soon, see if I can reliably reproduce again, rather than this system that has been in use for a few weeks.

    vagrant@hix:~$ docker -v
    Docker version 1.4.1, build 5bc2ff8
    vagrant@hix:~$ uname -a
    Linux hix 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux

**Comment by cpuguy83** [comment]
Ok, I can repro now.  This is only happening with bind mounts it seems.

**Comment by devinrsmith** [comment]
Sweet! Thanks.
