### ISSUE TITLE
Read a default tag a file for "docker build"

### ISSUE THREAD

**Issue by jsternberg** [docker/docker#9641]
When you use `docker build` and don't tag it with the `-t` option, it will get built and given no tag. When developing an image, you end up having to put the image name and version in a separate build file as a wrapper around calling `docker build`.

A nice feature would be automatically getting a default tag from a file in the context similar to the `.dockerignore` file. If no tag is specified on the command line, docker could read the tag from this file as a default.

I propose that this file be called `.dockertag` and it should just be a simple one-line file with the tag name.

**Comment by jfrazelle** [comment]
see also https://github.com/docker/docker/issues/5603

**Comment by LK4D4** [comment]
I think this not worth to implement. To easy to workaround and too hard to implement/document.
