### ISSUE TITLE
Docker looking in the wrong place in the cgroups hierarchy

### ISSUE THREAD

**Issue by Keruspe** [docker/docker#9653]
Hi,

Whenever I start a container, docker keeps complaining about my kernel not supporting OOM notifications because `/sys/fs/cgroup/memory/docker/$id/memory.oom_control` doesn't exist.

`/sys/fs/cgroup/memory/system.slice/docker-$id.scope/memory.oom_control` does exist though.

Is there any way to tell docker to look in the right place?

**Comment by resouer** [comment]
That relate to your host OS, related issue https://github.com/docker/docker/issues/9902

So it seems not a bug of Docker? Or do you think Docker should support that path too?

**Comment by Keruspe** [comment]
Well, since this is the new path for the vast majority of linux-based OSes now, I think docker really should support this path.

**Comment by resouer** [comment]
@Keruspe So, did you guys have more details about this issue, like what command and parameters are you running. And anything helpful to reproduce the error?

**Comment by Keruspe** [comment]
Even the official hello world suffices to reproduce

**Comment by chenhanxiao** [comment]
This PR:https://github.com/docker/libcontainer/pull/307
https://github.com/docker/docker/pull/9795
should fix this issue.

It's already upstream and works fine on my machine.

**Comment by Keruspe** [comment]
I confirm this is fixed in docker 1.5
