### ISSUE TITLE
Docker doesn't remove the container if it exit with non-zero exit code when auto remove enabled

### ISSUE THREAD

**Issue by chenchun** [docker/docker#9658]
We are running dockers on a large cluster for a time and found lots of machines with many finished containers with non-zero exit code that have not been removed. We run docker container always with --rm option specified.
I think docker daemon should remove containers even if exit with a non-zero exit code when specified --run option, is it reasonable?

**Comment by jfrazelle** [comment]
there should be some sort of unification right?

**Comment by chenchun** [comment]
I think container should be removed for the above two cases. I also found stop docker daemon will not remove containers specified with --rm.

**Comment by termie** [comment]
+1

**Comment by runcom** [comment]
#dibs

**Comment by runcom** [comment]
as @chenchun pointed out, containers started with `--rm` flag won't be removed if you restart the docker daemon

**Comment by chenchun** [comment]
Thanks for taking this up @runcom . I think containers won't be removed because client can't get enough time talking to the daemon before it dies. I suggest removing containers after daemon restart. Will make a PR soon.

**Comment by runcom** [comment]
@chenchun yes I thought about the 15 seconds delay before stopping the daemon could have been the problem
