### ISSUE TITLE
Can not restart container after stopped container.

### ISSUE THREAD

**Issue by liuyunsh** [docker/docker#9661]
Environment CentOS7
Kernel:
[root@tengzhen ~]# uname -r
3.10.0-123.el7.x86_64
Can reproduce by the following steps.
1, Run some containers from images for few days(maybe 3 days)
2, Stop one of the above, this step will stop container(s) successfully.
3, Start the stopped container with following errors:
![qq 20141214151147](https://cloud.githubusercontent.com/assets/7359431/5426728/945397aa-83a3-11e4-918e-3010cb06a100.jpg)

**Comment by jfrazelle** [comment]
we need more information in order to debug this.

docker info
docker version
daemon logs

how to reproduce

**Comment by defunctzombie** [comment]
Next time I detect that it happens I will capture all of that information.

`how to reproduce` might be a challenge.

Right now my theory is that if docker is running a container with no memory limits (no `-m` flag) then if the process causes memory limits on the machine to be reached (no swap) then some bad things happen.

I am running a container now with `-m` and have not seen this same failure again but it is too early to tell for my testing.

**Comment by thaJeztah** [comment]
@liuyunsh do you still have this issue? If you do, can you add the information that was requested https://github.com/docker/docker/issues/9661#issuecomment-76299314.

**Comment by liuyunsh** [comment]
@thaJeztah ，yes, still have the same issue.
[root@tengzhen ~]# docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): linux/amd64
Server version: 1.5.0-dev
Server API version: 1.18
Go version (server): go1.3.3
Git commit (server): fc0329b/1.5.0

Environment CentOS7
Kernel:
[root@tengzhen ~]# uname -r
3.10.0-123.el7.x86_64

Not sure if still have the problem in new version of docker.

**Comment by thaJeztah** [comment]
@liuyunsh thanks. 

The version of Docker you are running is a version maintained by CentOS, not by Docker. There are a number of known issues with that version, and although I'm not sure this is one of them, you might try installing a "vanilla" version that is maintained by Docker to see if that resolves your issue.

For some background information, and instructions on how to switch to a "vanilla" version, see:
https://github.com/docker/docker/issues/12182#issuecomment-91114210 and https://github.com/docker/compose/issues/424#issuecomment-90689698

**Comment by cpuguy83** [comment]
ping @liuyunsh

**Comment by liuyunsh** [comment]
@cpuguy83 ,any thing I can do for you? @thaJeztah ,thanks. The docker's development is too fast

**Comment by cpuguy83** [comment]
@liuyunsh Are you able to repro this on a vanilla docker install, preferably the latest release?

**Comment by liuyunsh** [comment]
@cpuguy83 ，sorry for late response, I am on vacation during these days.  No, this can not be repro in latest release any more.

**Comment by cpuguy83** [comment]
@liuyunsh Thanks for reporting back!
Closing this since it doesn't seem reproducible anymore!
