### ISSUE TITLE
Pull not downloading properly

### ISSUE THREAD

**Issue by gowthamgutha** [docker/docker#9662]
I have pulled ```tomcat``` and it has been downloading since the past 2.5 hours. But, since a lot of time I could see now change in the progress of downloading the layers.

I doubt that whether it is downloading it or not. Now when I cancel it, my download starts right from the start.

It would be better if Docker stores the downloaded parts and then on a subsequent pull download those which aren't downloaded previously.

My major problem here was there is NO progress at all in download. Is it due to the delay in response time of the Docker registry hub or an error in the program? I ain't sure.

Here is a screenshot.

![capture](https://cloud.githubusercontent.com/assets/2537654/5427559/a470e1ae-83c8-11e4-8bf2-bebe0dfd292b.PNG)

**Comment by unclejack** [comment]
@gowthamgutha The output of `docker info`, `docker version` and `uname -a` need to be provided. We can't help you if we don't have that information.

**Comment by jfrazelle** [comment]
@gowthamgutha can you please provide the requested information

**Comment by jfrazelle** [comment]
closing as stale and failure to provide https://github.com/docker/docker/blob/master/CONTRIBUTING.md#reporting-issues, please ping me if you end up giving the information
