### ISSUE TITLE
docker client doesn't error when given daemon flags

### ISSUE THREAD

**Issue by SvenDowideit** [docker/docker#9677]
```
[sven@t440s ~]$ docker -g /tmp run hello-world
Hello from Docker.
```

which can be quite confusing - https://forums.docker.com/t/how-can-i-change-the-location-of-image/472

**Comment by fgimenez** [comment]
#dibs

**Comment by fgimenez** [comment]
Sorry for claiming this, didn't notice by the labels that someone is already working in the fix

**Comment by runcom** [comment]
@fgimenez pretty sure nobody is working on this :smile: would you have a go?

**Comment by duglin** [comment]
Actually Tibor might be working on this as part of another issue

-Doug

**Comment by runcom** [comment]
@duglin oh okei, the one closed

**Comment by thaJeztah** [comment]
> Actually Tibor might be working on this as part of another issue

Correct, I think this is being worked on by @tiborvass, see https://github.com/docker/docker/pull/10535#issuecomment-98798590
