### ISSUE TITLE
ENV keywork only applies to root user.

### ISSUE THREAD

**Issue by phiroict** [docker/docker#9681]
When running the Dockerfile sequence:  
USER root
<some commands>
USER nonroot
ENV PATH bla
The PATH variable of the root user has been set to the "bla" value, not the nonroot user.
I expect that after the USER x keyword all actions are against that user x, not root. 

(Version 1.4.0-2, From the archlinux standard repo) 
Archlinux : 3.17.6-1-ARCH #1 SMP PREEMPT Sun Dec 7 23:43:32 UTC 2014 x86_64 GNU/Linux

**Comment by duglin** [comment]
Seems to work for me. Using this Dockerfile:
FROM ubuntu

RUN useradd -p please dug
USER dug
ENV foo=bar
RUN whoami && env

I get:
 ---> Running in 9dd373a002af
dug
HOSTNAME=66be2f8db7c1
foo=bar
HOME=/home/dug
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/


Is there some other variant I need to use to see the issue?

**Comment by phiroict** [comment]
Hi Dough, thanks for replying.

I see the correct behaviour on docker 1.4.1 (Like you showed).
We saw this on docker on ubuntu which uses version 0.9.1. After 
upgrading to the 1.4.1 version this is now working ok.
Since it is an old version issue this issue can be closed.

Cheers Philip

**Comment by phiroict** [comment]
No longer present in current docker version.
