### ISSUE TITLE
Proposal: dockerfile keyword: ASSERT

### ISSUE THREAD

**Issue by brownman** [docker/docker#9685]
what we have:
docker has a great feature: ONBUILD

what we need:
how one can be sure that the dockerfile is working?
- build success
- test success!

how to do it:
- implement a new keyword: ASSERT or TEST or ONVISIT or what-ever
- this command should give the client all the answers he ask from his dockerfile.

benefits:
- no need to actually test the dockerfile locally or build a new testing-system 

god bless

**Comment by jfrazelle** [comment]
Hello!
We are no longer accepting patches to the Dockerfile syntax as you can read about here: https://github.com/docker/docker/blob/master/ROADMAP.md#22-dockerfile-syntax

Mainly:
> Allowing the Builder to be implemented as a separate utility consuming the Engine's API will open the door for many possibilities, such as offering alternate syntaxes or DSL for existing languages without cluttering the Engine's codebase

Then from there, patches/features like this can be re-thought. Hope you can understand.
