### ISSUE TITLE
Docker client returns 'invalid argument' and exits when pushing to a repository

### ISSUE THREAD

**Issue by michaelbarton** [docker/docker#9691]
I tried to push to a private registry and got the following output. I am unsure
how to resolve this.

$ docker push ...

    The push refers to a repository ... (len: 1)
    Sending image list
    Pushing repository ... (1 tags)
    Image 511136ea3c5a already pushed, skipping
    Image f10807909bc5 already pushed, skipping
    ...
    Image db8a64f62509 already pushed, skipping
    Image e46b3488b010 already pushed, skipping
    218a8faeee16: Pushing 1.024 kB/1.024 kB
    FATA[0014] invalid argument

$ docker version

    Client version: 1.3.1-dev
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 831d09f
    OS/Arch (client): darwin/amd64
    Server version: 1.3.1-dev
    Server API version: 1.16
    Go version (server): go1.3.3
    Git commit (server): 831d09f

$ docker info

    Containers: 118
    Images: 101
    Storage Driver: aufs
     Root Dir: /mnt/sda1/var/lib/docker/aufs
     Dirs: 337
    Execution Driver: native-0.2
    Kernel Version: 3.16.4-tinycore64
    Operating System: Boot2Docker 1.2.0 (TCL 5.4); master : 8a06c1f - Fri Nov 28 17:03:52 UTC 2014
    CPUs: 8
    Total Memory: 999.6 MiB
    Name: boot2docker
    ID: PDWP:S7ZN:LUOH:XXOR:7PZZ:67XI:PLYW:AIAO:7EM2:OHIP:55FH:B5KR
    Debug mode (server): true
    Debug mode (client): false
    Fds: 21
    Goroutines: 33
    EventsListeners: 0
    Init Path: /usr/local/bin/docker

**Comment by unclejack** [comment]
@michaelbarton Please open an issue against machine. I haven't seen this issue with any recent Docker version. Should there be an issue even in the current code found in master, we can look into it, but that's an issue which should be created by the maintainer of machine.

I'm going to close this now. Please feel free to comment.
