### ISSUE TITLE
Proposal: Docker Compose

### ISSUE THREAD

**Issue by aanand** [docker/docker#9694]
This proposal, deprecating #9459, is for a command-line tool for orchestration of multi-container apps, suitable for development environments, automated CI setups and staging and production deployments, and working fluidly with Docker Machine and Docker Swarm.

Based in large part on feedback to #9459 from the Docker community, we propose the following:

- Compose is a **standalone command-line tool**, rather than built into the Docker client binary.
- The initial release of Compose is **directly based on the Fig codebase**, rather than written from scratch, and focused around cleanup and any backwards-incompatible changes from Fig.
- A roadmap of features for Compose and (if deemed appropriate) the Docker engine, so as to achieve production-suitability and seamless integration with Swarm, is planned.

## Separate tool

The arguments in favour of building Compose directly into the Docker client are based on usability issues we’ve observed with Fig:

- Newcomers to Docker find Fig more immediately easy to understand and relevant to their needs, so it makes sense for them to have that benefit out-of-the-box.
- People are often confused about the distinction between Fig and Docker, so it would be beneficial from a UX perspective if there *were* no distinction.
- Fig is “one more thing to install” that prevents users from getting up and running.
- Problems arise when versions of Fig and Docker are incompatible.

However, there are also usability arguments *against* building it in:

- The various Docker commands become context-sensitive (i.e. they behave differently based on the contents of the current directory) and overloaded with meaning (arguments can either designate literal container names or names in the configuration file).
- Docker users who aren’t interested in Compose’s features will nonetheless have to live with a tool that’s both physically and conceptually larger.

Furthermore, technical and social arguments strongly favour separation: the responsibilities of Compose and those of the current Docker client don’t overlap, and it’s better to avoid conflating non-coupled concerns in one codebase, because:

- It’ll make the codebase even larger.
- It’ll force both projects to share a release cycle, making it harder to experiment on Compose and to make changes to either one.
- It’ll put extra burden on the core maintainers.
- It’ll be harder to find issues and PRs if they all live in the same GitHub repository.

Furthermore, a separate tool will help guide the definition and maintenance of the Docker API(s), keeping the door open for a healthy ecosystem of alternatives.

Finally, it’s still possible to go carefully from a separate tool to an integrated one in the future; extracting a separate tool back out again, however, is much harder.

## Based on Fig

Fig in its current state is a *great* orchestration tool for development/CI, and a *usable* one for simple production deployments. Its codebase is mature and well-understood, and doesn’t carry a lot of technical debt (though there are improvements which can and should be made!)

It would make an excellent starting point - and, given Compose is a new tool, we’d be free to make breaking changes from Fig’s logic for the first release.

## Features roadmap

As well as a number of smaller features that have been requested for Fig (which will still be triaged and implemented where appropriate), several high-level features are needed to get Compose to a state where it’s suitable for multi-host production deploys. Compose’s priorities after the initial release will be identifying, designing and implementing these in collaboration with the community and users. Discussion for many of these is already ongoing on the Fig GitHub project.

**Comment by olalonde** [comment]
As a developer, I think it would be cool if Compose apps could be composed if that makes sense. There could be a Compose registry (like the Docker registry but for composed apps).

For example, I'm currently working on an app composed of:

- 9 independent micro-services (repositories), each backed by a database
- an API gateway

It would be nice if I could have a `fig.yml` for each micro-service repository (which would each be responsible for bringing up their HTTP container + database container). 

My API gateway's `fig.yml` could then simply reference all the other services it depends on without having to know that, for example, micro-serviceY requires a database container. The individual services could also be responsible for how to properly load balance themselves, etc.

It would also enable the creation of a micro-service ecosystem where one can easily declare a micro-service dependency without having to know what internal infrastructure is required to run it.

Does that make any sense?

**Comment by Peeja** [comment]
Yo, dawg.

I'd like to have this too, or something that accomplishes the same thing. The issue with the current design is that neither containers nor multi-container apps are recursive abstractions.

I'd like to be able to treat an entire multi-container app as a single container, so I can compose it with yet more containers. The image for that container could then be hosted in the ordinary Docker registry.

You can actually do that now by running Docker-in-Docker, but it's kind of a hack.

**Comment by thaJeztah** [comment]
Sounds a bit like the templates on http://panamax.io ? Could be interesting, but I'm not sure it is wise to put it on the roadmap so soon?

**Comment by Peeja** [comment]
It's as close to Panamax's templates as it is to a fig.yml. My point is that I'd like to take it a step further: rather than use a *different* abstraction to bundle containers together, why not bundle them into something which is *itself* a container?

Otherwise, Docker feels like a data structure that can only contain scalars.

**Comment by tbatchelli** [comment]
+1 on having composable services as @olalonde mentioned. When many services are being developed concurrently, it's hard and error-prone to keep the "one" file representing the whole system up-to-date.

I would add that not only you should be able to 'import' other 'modules', but that you also should be able to override parts of the imported modules when you do. (e.g. which version of an image to use for part of the module)

**Comment by bfirsh** [comment]
I've added some high level goals for Docker Compose here: https://github.com/docker/fig/pull/804

**Comment by ronin13** [comment]
I use fig a lot to bring up galera/percona xtradb cluster instances here: https://github.com/percona/pxc-docker 

Few thoughts:

 - Even though Fig attempts to follow Docker in its interface, there are a few 
   differences, one that some of my coworkers hit was on when the image recreation was 
   done - fig up, fig scale, fig run, fig build - it is not equivalent across 
   them.

 - The issue with current Python codebase is that, unlike docker, single binary 
   doesn't work. https://github.com/docker/fig/issues/170 is an example of it. 
   Only way to avoid this is to use pip install to install dependencies.

 - There is a need for substitution variables. This is more needed than ever 
   with fig scale. For instance, here 
   https://github.com/percona/pxc-docker/blob/master/docker-pkgs/pxc-release/centos7/fig.yml 
   a single node is bootstrapped but multiple nodes (members) then join. The specification 
   for members is through a single 'members:' service specification. 

    * I have used ${RANDOM} there for lack of a better variable. I also needed 
      something similar for hostname and so on. Hence, substitution variables 
      can help with scale.

 - As mentioned earlier, inheritance/composability is a definite plus. This 
   should also allow for more elegant yml files, ie. avoid repetition of ports 
   here https://github.com/percona/pxc-docker/blob/master/docker-pkgs/pxc-release/centos7/fig.yml

 - The idea of build v/s pull: Currently fig can either pull or build (but not 
   tag) in a yml file but not both, which necessitates another 'build' yml file here 
   https://github.com/percona/pxc-docker/tree/master/docker-pkgs/pxc-release/centos7

**Comment by jokeyrhyme** [comment]
@ronin13 RE: inheritance / composability: https://github.com/docker/docker/issues/735

**Comment by Peeja** [comment]
@jokeyrhyme That kind of composition is good too, but it doesn't let you bundle several images into a single "application" image and then use that image multiple times. Instead, it would make just it easier to build an application image out of the Dockerfiles of its components, and have them run in a one big container. The application's components would no longer be isolated from one another.

**Comment by thaJeztah** [comment]
@Peeja If I understand your idea correctly, you want it to build a "group" / "stack" of containers / images using composer and then being able to commit that stack as a single image (having those containers in it), basically "nested" containers.

Although I get the use case for that, I wonder if it would really offer much advantages. You'll loose the option to "swap out" or upgrade individual containers, and will have to commit / deploy the whole *stack* even if just a single container has to be updated. It's also not efficient if multiple applications share the same image, just in a different configuration / combination. And last, you want to be able to deploy your stack to a cluster (Docker Swarm); having the containers distributed over multiple host.

The current approach in Fig / Docker Compose is to store the *definition* of the application. Docker compose should make it as easy to run *as if* it was a single container, and automatically start, link and distribute the containers.

This also allows multiple applications using the same image, but in different configurations, without "duplicating" those images. (App-A stack = `redis + mysql + NGINX + AppA`, App-B stack = `PostgreSQL + NGINX + Varnish + AppB`).

**Comment by Peeja** [comment]
Yeah, I agree with all of that. I'd just like the result to be recursively composable, as @olalonde was getting at. The best way to do that may be to have Compose be able to refer to app definitions as well as images, and have Compose walk the tree to turn the whole thing into a flat set of linked containers which Swarm can distribute as it sees fit. (Which I think is what you're saying.)

(The Dockerfile solution in #735 doesn't play nicely with Swarm either, incidentally, for the same reason: it becomes one big container. It's a useful feature, but not for building a stack of services like this.)

**Comment by dnephin** [comment]
> The best way to do that may be to have Compose be able to refer to app definitions as well as images

@Peeja this is exactly the idea we're exploring in https://github.com/docker/fig/issues/318

**Comment by thaJeztah** [comment]
@peeja thanks for the extra explanation. I created my comment also with the intent to prevent other people reading this discussion thinking "that's nice - a single image, with all my containers in it", without overthinking the implications and blindly adding +1's.

**Comment by opyate** [comment]
JSON, YAML, TOML... How about [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md)?

**Comment by tlrobinson** [comment]
I think a very nice compromise would be to make "compose" a standalone project called `docker-compose` and modify the docker command to behave like git where if you type "git foo" and the executable "git-foo" exists on your $PATH then it gets executed with the provided command line args. So you could do `docker ps` to get all containers, or `docker compose ps` (or `docker-compose ps`) to get your current application's containers, `docker start name` to start a specific container, or `docker compose start` to start an entire application, etc etc.

**Comment by tcoats** [comment]
@aanand I propose allowing multiple .yml files in a directory and using the name of the file as the name of the group. This would keep the simple fig format and allow more freedom of configuration files and directory layouts.

I've written [tugboat](https://github.com/metocean/tugboat) - a command line tool similar to fig that uses individual .yml files for each group. The .yml file format is identical to fig however the group concept is a first class citizen in the command.

e.g.

ping.yml:
```yml
google:
  image: ubuntu
  command: ping google.com
facebook:
  image: ubuntu
  command: ping facebook.com
```

`tug up ping` will create test_google and test_facebook containers.
`tug up ping google` will create test_google only.
`tug` has other commands: start, stop, rm, down, cull, diff.
`tug ps` shows a high level summary of which groups have running containers.
`tug ps ping` shows a more detailed breakdown for just the `ping` group.

The `tug` tool can be installed with `npm install -g tugboat`. It is written in Node.js but could easily be ported to Go.

The great thing about allowing multiple group .yml files in a single directory is that a project can ship with different groups for different purposes. Another example of this flexibility is that in our production environment we're using a single directory on our servers that contains all the groups we use. This is the authoritative location for all the configuration for our datacenter. The .yml files also bind sub folders of this directory for providing configuration to our docker containers. Host specific configuration is performed with environment variables.

I've also written a [tool and docker container to sync running groups with consul](https://github.com/metocean/tugboat-consul). I've found it's a great way to provide an elastic architecture. The `tugboat-consul` daemon sits on a directory of .yml group files and exposes a directory in the consul key value store with the name of the host. From consul .yml file group names can be added to this directory - the daemon detects the change and issues a `tug up [groupname]` which does a diff against what is currently running. When items are deleted the daemon issues `tug cull [groupname]` as well.

From the consul ui we have a folder that has a list of all our docker capable hosts inside a datacenter. Inside each of these directories we can see what is currently running, and add and remove services dynamically. This is especially useful when we burst. We don't know in advance the hostname of our elastic instances. Once provisioned from our image they show up in consul where we can instruct them what to run.

This is our swarm + compose solution - tugboat + consul.

Thoughts?

**Comment by richardolsson** [comment]
I definitely think having a single file format is preferable over having many. Fragmentation (of documentation, mainly, but also other aspects) can be devastating for any project.

I also like the "Stackfile" name, without the suffix. The "stack" analogy is nicer than the "group" analogy IMO, even though it's less ambiguous and might, strictly speaking, be semantically incorrect for some set-ups (which are not actually stacks).

**Comment by xiaods** [comment]
Just like Dockerfile convention, Stackfile is ok for the purpose. cc @richardolsson

**Comment by aanand** [comment]
All: Docker Compose 1.1.0 RC1 is out: https://github.com/docker/fig/releases/tag/1.1.0-rc1

**Comment by mainiak** [comment]
:+1:

**Comment by noirbizarre** [comment]
Good initiative to have chosen fig as starter for docker-compose but, if I may, I think ``docker-compose`` is a way too long name for a command line tool.
It's all about comfort and readability.
In a script it does not matter, but in an every day developper shell workflow, the difference is noticeable:
```console
fig stop && fig rm --force && fig run -d && fig ps
```
became
```console
docker-compose stop && docker-compose rm --force && docker-compose run -d && docker-compose ps
```
The ``docker`` prefix prevent tab completion to directly give me ``docker-compose`` as ``docker`` is in the list.

I know this is far from being a major point, but it already bothered me since I've switched from fig to docker-compose yesterday.
I thought you should be aware of it.

Why not having a shortcut like:
- dcomp
- compose
- stack or dstack
- ...
Or, why not keep the original projet name: fig ?

**Comment by madwire** [comment]
@noirbizarre I have to agree, its rather annoying

**Comment by noirbizarre** [comment]
@madwire Thanks to support it. I was affraid nobody cares since nobody raised the point !

**Comment by dnephin** [comment]
```!sh
alias fig='docker-compose'
```

**Comment by noirbizarre** [comment]
Yep, that's what I did but it's kind of hackish, no ?
And, it breaks projects still using fig (I have some)

**Comment by Stono** [comment]
ln -s /usr/bin/docker-compose /bin/fig

**Comment by funkyfuture** [comment]
it should be `ln -s … /usr/local/bin/fig`

**Comment by ferdy-galema** [comment]
I think it is silly to use 'fig' as a recommended alias, because this will confuse anyone not familiar with the project's origin.

Since 'compose' and 'dc' already seem to be existing commands and 'dcom' is too Microsofty, I'm in favor of 'dcomp'.

**Comment by olalonde** [comment]
Some inspiration:

- [Crane](http://en.wikipedia.org/wiki/Crane_(machine)): machine used to place containers on cargos

[!crane](http://www.portseattle.org/Cargo/SeaCargo/Facilities/Container-Terminals/PublishingImages/Crane.jpg)

**Comment by thaJeztah** [comment]
>  I'm in favor of 'dcomp'.

That *sounds like* "de-comp" / "de-compose". I don't like the smell of that :)

@olalonde you realize "Crane" is an [existing product](https://github.com/michaelsauter/crane)? Similar to docker-compose, but (iirc) communicates with docker via the CLI in stead of the API

**Comment by ferdy-galema** [comment]
@thaJeztah 
Good point. For now I am using 'doco'.

**Comment by almereyda** [comment]
When I look at crane and fig and (RIP) gaudi, I really want to see this kind of orchestration minimally standardized.

**Comment by olalonde** [comment]
@thaJeztah no I didn't :)

Personally, `dcomp` also make me think of de-compose. `Doco` is not bad but it is very similar to `docco` which is a widely used documentation generator for Javascript (http://jashkenas.github.io/docco/). I think `docko` would be better if anything.

**Comment by wernight** [comment]
"Crane" even taken, sounds really good (and since Fig and Crane and Docker Compose seem to try going the same thing the same way, why not have a good strong official one doing that).

**Comment by madwire** [comment]
@wernight thats what this proposal is about, also fig is docker compose as its undergoing a name change.

**Comment by marcellodesales** [comment]
+1 on Crane!

**Comment by almereyda** [comment]
As in

    docker crane mv sdc:local sdc:almereyda@remote.host.tld --verbose

which initiates a move, for example? Does this require we're all [using ZFS soon](https://github.com/clusterhq/flocker)?

Just want to keep up on the direction we're taking here. Especially also in terms of CoreOS' and `btrfs` plus the APIs to generalize able interfaces like Panamax, ex-Gaudi, Cockpit, [dockerboard](https://github.com/dockerboard/dockerboard/issues/8#issuecomment-73924054) and the likes?

**Comment by alexisvincent** [comment]
In terms of the arguments to keep compose separate from docker cli. Can we not do the following:

- Keep them separate -> All the benefits of a separate codebase.
- Have a 'docker compose / docker up' command which forwards to compose -> better ux
- This could also check compose versions and prompt the user to update compose if outdated.

This type of rig makes more sense to me.

**Comment by aanand** [comment]
Attention, all: work is progressing on Docker Compose, based on the Fig codebase. A release candidate is out.

https://github.com/docker/fig/releases/tag/1.1.0-rc2

**Comment by wernight** [comment]
I found docker-compose requires Docker 1.4+. This wasn't for Fig. Should
probably be written somewhere if that's the case, no?

**Comment by aanand** [comment]
@wernight Compose should work with Docker 1.3 - if it doesn't, please open an issue!

**Comment by jghibiki** [comment]
Another idea for a name: 

    docker shipment

or for short

    docker ship



    docker ship

Rationale: A fig.yml comprises of a "shipment" of services.

**Comment by baptistedonaux** [comment]
@aanand I use Compose 1.1.0-rc2 with 1.3.3. It works

**Comment by bfirsh** [comment]
Compose has now been released and is available here: http://docs.docker.com/compose/

**Comment by bfirsh** [comment]
Thanks all for your feedback!

**Comment by sanchitiks** [comment]
I run the docker-compose up command to up jira and mysql containers while checking containers status using docker-compose ps command its showing that Both containers are in exit state.....

**Comment by thaJeztah** [comment]
@sanchitiks the GitHub issue tracker is not a support forum. If you need support using docker or docker-compose, please ask you question in the #docker-compose or #docker IRC channel, on https://forums.docker.com or the [docker-user group](https://groups.google.com/forum/m/#!forum/docker-user) on Google Groups.

**Comment by JemiloII** [comment]
I'm posting my bit of knowledge here. Don't worry about the tcp ports. Just locate your `docker.sock` file. Mine was in `/run/` others could be in `/var/run` and use that path for `DOCKER_HOST`

`export DOCKER_HOST=/run/docker.sock` worked for me
`export DOCKER_HOST=/path/to/docker.sock` should work for you.
