### ISSUE TITLE
when container stops, docker will not send RST packet to peer

### ISSUE THREAD

**Issue by liyichao** [docker/docker#9727]
A server runs in a container and listens on an exposed port. Client connects to the server.

Then I stop the server container，tcpdump shows that client receives a FIN packet, then client continues to send a packet，which should elicit a RST packet, but there is not. So client keeps sending packet without knowing server has been shutdown.

**Comment by jfrazelle** [comment]
can you give exact commands to reproduce

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen
