### ISSUE TITLE
Restricted subnet for docker0 via "fixed-cidr" option does not work

### ISSUE THREAD

**Issue by bemeyert** [docker/docker#9729]
Hi all, I can't get the docker daemon to work with the options "--bip=172.16.0.1/16 --fixed-cidr=172.16.1.0/24". Routing doesn't work in any of my containers. I can ping the docker0 bridge from inside the containers, but nothing beyond that. I tried that with Archlinux/Docker 1.4 and CentOS 7/Docker 1.3.2. I made sure that the docker0 device didn't exist before starting the docker service. The complete docker command was: `/usr/bin/docker -d -H fd:// --bip=172.16.0.1/16 --fixed-cidr=172.16.1.0/24`
Am I doing something wrong or is this a bug? Thx

**Comment by jfrazelle** [comment]
looks like this was resolved, lmk if otherwise how to reproduce
