### ISSUE TITLE
[docs]: add note about installing apparmor to ubuntu installation docs

### ISSUE THREAD

**Issue by seschwar** [docker/docker#9745]
Description of problem:

After installing the lxc-docker package from the repositories
provided by Docker on Ubuntu 14.04.1 the Docker daemon fails to
start because of the missing executable `/sbin/apparmor_parser`.

`docker version`:

    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8
    OS/Arch (client): linux/amd64
    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

`docker info`:

    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

`uname -a`:

    Linux srv28 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Environment details (AWS, VirtualBox, physical, etc.):

A new physical server with a fresh minimal install of Ubuntu 14.04.1.

How reproducible:

On a custom minimal Ubuntu install without apparmor this is always reproducable. The standard Ubuntu install seems to include apparmor and therefore the problem is not apparent. 

Steps to Reproduce:
1. Follow install instructions: http://docs.docker.com/installation/ubuntulinux/#docker-maintained-package-installation
2. `service docker start`
2. `docker info`

Actual Results:

The Docker daemon fails to start.  `docker info` outputs

    FATA[0000] Cannot connect to the Docker daemon. Is 'docker -d' running on this host? 

and `/var/log/upstart/docker.log` contains

    INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    INFO[0000] +job init_networkdriver()                    
    INFO[0000] -job init_networkdriver() = OK (0)           
    INFO[0000] WARNING: Your kernel does not support cgroup swap limit. 
    FATA[0000] Error loading docker apparmor profile: fork/exec /sbin/apparmor_parser: no such file or directory () 

Expected Results:

The Docker daemon should be up and running.  `docker info`
should output something like

    Containers: 0
    Images: 0
    Storage Driver: aufs
     Root Dir: /var/lib/docker/aufs
     Dirs: 0
    Execution Driver: native-0.2
    Kernel Version: 3.13.0-43-generic
    Operating System: Ubuntu 14.04.1 LTS
    CPUs: 12
    Total Memory: 62.89 GiB
    Name: srv28
    ID: SDXF:XYT2:PAMA:OSYS:2QJD:VIZN:MDUU:PYJK:YJXY:2RCA:4A6F:ZCDL
    WARNING: No swap limit support

and `/var/log/upstart/docker.log` should contains something like

    INFO[0000] +job serveapi(unix:///var/run/docker.sock)   
    INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
    INFO[0000] +job init_networkdriver()                    
    INFO[0000] -job init_networkdriver() = OK (0)           
    INFO[0000] WARNING: Your kernel does not support cgroup swap limit. 
    INFO[0000] Loading containers: start.                   
    INFO[0000] Loading containers: done.                    
    INFO[0000] docker daemon: 1.4.1 5bc2ff8; execdriver: native-0.2; graphdriver: aufs 

Additional info:

Running the following command allows the Docker daemon to start
properly:

    apt-get install apparmor

Thus the lxc-docker package should depend on apparmor which contains the missing executable `/sbin/apparmor_parser`.

**Comment by gdm85** [comment]
I am also affected by this bug.

Somebody had already noticed this issue last year: http://www.tekhead.org/blog/2014/09/installing-docker-on-ubuntu-quick-fix/

**Comment by rollenholt** [comment]
just yun:

        sudo apt-get install apparmor

and then, restatr you docker

**Comment by gdm85** [comment]
@rollenholt the point is that it should be a dependency in the ubuntu package.

**Comment by rollenholt** [comment]
@gdm85 yes, you are right :)

**Comment by jfrazelle** [comment]
see https://github.com/docker/docker/pull/10704#issuecomment-75618240, this should be documented

**Comment by gdm85** [comment]
You need to make two separate packages if you want to officially ship to two different (albeit related) distros; I am pointing out the obviousness of it, in case it was needed :)

It might be useful or also to pack other distro-specific improvements (which now you could only do through hacks).

**Comment by zelahi** [comment]
#dibs,  

Could I take this issue.  From my understanding, what needs to happen is I need to add a small note saying apparmor needs to be installed on ubuntu.  Am I understanding this correctly?

**Comment by thaJeztah** [comment]
Hm, good one: @jfrazelle is this still needed with the new apt repos? I see the app armor as "recommend"; https://github.com/docker/docker/blob/master/hack/make/.build-deb/control#L15

**Comment by jfrazelle** [comment]
hmmm yes we add it but who knows may as well add it to the docs too just so
everyone is happy :)

**Comment by Arabus** [comment]
As long as you do not have separate packages for Ubuntu and Debian this definitively needs to be part of the documentation. Currently the installation for Ubuntu is simply broken until you install the apparmor package in Addititon to docker, which the documentation does not tell you about. 

You might also want to add a scriptlet as part of the post-install, that detects a running interactive terminal session on a ubuntu and derivatives and outputs this hint.

**Comment by thaJeztah** [comment]
Thanks for looking @jfrazelle @Arabus 

Looks like we still need this, @zelahi, so looking forward to your PR :+1:

**Comment by zelahi** [comment]
@Arabus , sry for the  question but what's a scriptlet?

And awesome.  I look forward to this as I would love to work on areas related to security =)

**Comment by zelahi** [comment]
@thaJeztah should we close this issue since its been fixed

**Comment by thaJeztah** [comment]
Ah, yes! Looks like the PR description missed a `closes #...` mention, so GitHub didn't auto close. Thanks!
