### ISSUE TITLE
Turn private registry security off by default, like prior to 1.3.1 

### ISSUE THREAD

**Issue by mingfang** [docker/docker#9748]
We run a private registry inside our secure datacenter to host our applications.
The requirement after 1.3.1 for our registry to use a certificate has caused many problems for us.
Our system considers all communications inside our datacenter secure and therefore we don't benefit from registry certificates.

**Comment by jfrazelle** [comment]
this is not a design goal, you can use --insecure-registry on the daemon, we do not want to advocate, and have default an insecure registry aslso see related https://github.com/docker/docker/issues/8887
