### ISSUE TITLE
Accessing host docker daemon from container

### ISSUE THREAD

**Issue by eknkc** [docker/docker#9760]
Is there a well defined way to have host docker daemon accessible within a container? My current approach is to mount `/var/run/docker.sock` inside the container when I run it, then use the http api on the socket. Is this a safe way?

**Comment by unclejack** [comment]
@eknkc This is only 'safe' if you're not allowing untrusted code and people to do this. You probably want to allow this only for something you're dong on your development box, not on a build server in production.

I believe this question has been answered. I'm going to close the issue now. Please feel free to comment if you have any more questions.
