### ISSUE TITLE
Release notes inconsistent linking among versions

### ISSUE THREAD

**Issue by mhoglan** [docker/docker#9767]
When you are browsing the documentation at https://docs.docker.com/ , the links for the release notes for previous versions is inconsistent or broken.   I was trying to find the Docker 1.2 release notes and had to go on a bit of a hunt to finally get to it.

Starting at the main page
 https://docs.docker.com/  
The LHS link to release notes takes you to the bottom of the page, to the release notes section
https://docs.docker.com/#release-notes

The link there takes you to
https://docs.docker.com/release-notes/
Which has the Docker 1.4 documentation version of Release Notes.  This is missing the previous 1.3, 1.2 and other release notes.  This made me think that the drop down in the top right was how you got other release note versions.

Going to Version v1.3 will take you to
https://docs.docker.com/v1.3/release-notes/
Which has the release notes as of v1.3  which also contains the previous versions of 1.2, 1.1 and 1.0 release notes on the LHS.  Those links take you to the various sections of that v1.3 release notes page.

Going to Version 1.2 from the drop down, you get taken to
https://docs.docker.com/v1.2/release-notes/
Which does not exist.  Same for other versions.

But there does exist a v1.2 release notes page, it is just not a separate page and is a section on the main v1.2 page.
https://docs.docker.com/v1.2/#release-notes

Additionally if you are on the main page for docs
https://docs.docker.com/

Go to v1.3 from the drop down menu, now at
https://docs.docker.com/v1.3/

The release notes link on the LHS takes you to bottom of page
https://docs.docker.com/v1.3/#release-notes

The link in that section takes you to
https://docs.docker.com/release-notes/

Which is the release notes for v1.4 not v1.3 
Drop down menu top right will change to v1.4
Changing it to v1.3 will now take you to 
https://docs.docker.com/v1.3/release-notes/

Hope that describes the different click workflows I had to go through

I think the following should happen:
Release notes for 1.4 should be updated with previous versions (similar to 1.3) if it is suppose to be a comprehensive living release notes document
If not, then each previous version should get a separate release notes page in their respective areas so the drop down selector when on the release notes page works for them.

**Comment by thaJeztah** [comment]
ping @SvenDowideit were you still working on this?

**Comment by SvenDowideit** [comment]
yes, but slowly - we're gathering requirements for an overhaul of the docs build pipeline, and it will be dealing with versioned documentation for each tool.

**Comment by LK4D4** [comment]
@thaJeztah Do you know if it was fixed?

**Comment by thaJeztah** [comment]
I don't think it was done in the archived docs, but there's both GitHub releases (https://github.com/docker/docker/releases/tag/v1.12.1), and the global changelog https://github.com/docker/docker/blob/master/CHANGELOG.md. I think that release notes were actually dropped from the documentation, so this can be closed
