### ISSUE TITLE
About init process for docker

### ISSUE THREAD

**Issue by vankhoa011** [docker/docker#9773]
Follow by this link:

https://github.com/phusion/baseimage-docker#inspecting

I still confuse about init process. If i use supervisord to monitor the services, Do I have any problem with that ?

About signal linux, I try to make supervisord which is first service ( PID 1 ). And I try to stop the container, It did very fast. That means It didn't wait 10s to send SIGKILL the service. So, everything will be okie.

So the supervisord can resolve the problem about init process ?

Thank you in advance.

**Comment by unclejack** [comment]
@vankhoa011 This PR https://github.com/docker/docker/pull/9984 has added support for getting container stats.

This isn't a forum where questions should be asked, it's a bug tracker. This isn't a bug and your questions have been answered, including the original question one and the following ones. I'm going to close this issue now.
