### ISSUE TITLE
Unable to copy existing file from container if it shares name with binded volume

### ISSUE THREAD

**Issue by akrpic77** [docker/docker#9787]
Unable to copy file /temp.a from a container when binded volume /temp is present. 
Tested also with other filenames and paths, seems like `docker cp` can't find container's file 
if it shares begining of the name with binded volume.

Environment:

    $ docker --version
    Docker version 1.4.1, build 5bc2ff8
    $ uname -a
    Linux ak-devel 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt2-1~bpo70+1 (2014-12-08) x86_64 GNU/Linux

Reproduce with:

    $ CT=$(docker run -d -v /tmp:/temp debian sleep infinity)
    $ docker exec $CT touch /temp.a
    $ docker cp $CT:/temp.a .
    FATA[0000] Error response from daemon: Could not find the file /temp.a in container 24d546ffe7f697cc9567df1767a0965ce605ce453e5dcd4bc4aa86a3dc1c6cd3
    $ docker exec $CT ls -l /temp.a
    -rw-r--r-- 1 root root 0 Dec 23 13:49 /temp.a
    $ docker exec $CT mv /temp.a /Temp.a
    $ docker cp $CT:/Temp.a .
    (no error - file copied)

**Comment by jfrazelle** [comment]
@cpuguy83 was this fixed?

**Comment by cpuguy83** [comment]
Fixed but not merged.
It's part of @jlhawn's `cp` rewrite.

**Comment by vdemeester** [comment]
@cpuguy83 @jfrazelle I think it's fixed now (as @jlhawn `cp` rewrite is merged).

**Comment by cpuguy83** [comment]
Yep, thanks!
