### ISSUE TITLE
If container failed on start, then there will be goroutine leak

### ISSUE THREAD

**Issue by LK4D4** [docker/docker#9797]
example:
```
nc -l -p 6379
docker run -p 6379:6379 busybox true
```
After each run we will have +6 goroutines - this is attach jobs which was called before start by docker client. This goroutines never dies, even if you remove container. I noted that this issue appears only when failure is before actual process start.

**Comment by acbodine** [comment]
Related, possible duplicate #9622

**Comment by runcom** [comment]
The following patch reduce goroutine from 6 to 5, however the issue here seems to be with streams in general :/ I don't know if it helps, I'll make a PR if it does
```
diff --git a/daemon/container.go b/daemon/container.go
index 4e44621..b33c28a 100644
--- a/daemon/container.go
+++ b/daemon/container.go
@@ -897,7 +897,10 @@ func (c *Container) AttachWithLogs(stdin io.ReadCloser, stdout, stderr io.Writer
 			}()
 			stdinPipe = r
 		}
-		<-c.Attach(stdinPipe, stdout, stderr)
+		select {
+		case <-c.Attach(stdinPipe, stdout, stderr):
+		default:
+		}
 		// If we are in stdinonce mode, wait for the process to end
 		// otherwise, simply return
 		if c.Config.StdinOnce && !c.Config.Tty {
```

**Comment by LK4D4** [comment]
Still an issue.
