### ISSUE TITLE
"docker tag -f" is inconsistent

### ISSUE THREAD

**Issue by tianon** [docker/docker#9798]
There are a number of commands that will directly overwrite a tag without so much as a warning, so it's strange that `docker tag` is the only one that fatal errors when you try to do so without `--force`.

To name a few:
- `docker pull`
- `docker build`
- `docker import`
- `docker load`
- `docker commit`

It looks like this was the intentional behavior of `docker tag` since at least as far back as 0.8.0 (since e71dbf4ee5add5736f595948fc20bd01af56a744 has `docker tag -f` as a thing), but it wasn't until #8511 that it actually worked, which only just recently was released in 1.4.0.

Can anyone explain the rationale for what makes `docker tag` so special, especially when the arguments to it are already required to be deliberately specified (just like all those other commands listed above)?

**Comment by jfrazelle** [comment]
idk what do you think we should do :(

**Comment by tianon** [comment]
IMO kill "tag -f" in the name of consistency.

**Comment by thaJeztah** [comment]
Would qualify this a "regression", not an "enhancement". Making `-f` work was an incompatible API change, which isn't allowed if Docker is using [semver](http://semver.org)

**Comment by funkymonkeymonk** [comment]
I would agree this was a regression. This just caused a large number of breaks in our CI environment where tagging the latest successful build "green" now requires an additional argument.

**Comment by termie** [comment]
+1

**Comment by duglin** [comment]
To move things along...  here's a formal proposal of @tianon's idea:
1 - for v1.10 - add text to our docs saying that tag's `-f` option is deprecated - for removal in v1.12
2 - for v1.10 - add "#" to the flag definition so that it doesn't show up in the help text any more - like other deprecated flags
3 - in v1.12 remove it.

thoughts?

**Comment by tianon** [comment]
+1!

**Comment by thaJeztah** [comment]
I think it's good to add the `#` in 1.10 already, the option will still work, but only output a deprecation warning, this will give a bit more exposure to the scheduled deprecation

**Comment by tianon** [comment]
Woooooot, before the 1 year! :smile:

![](http://flyingsquirrelsports.ca/wp-content/uploads/2015/02/11-birthday-party.jpg)

**Comment by thaJeztah** [comment]
haha

darn, that means no cake? :birthday:

**Comment by tianon** [comment]
Oh no, there will definitely be cake! :metal:

**Comment by thaJeztah** [comment]
cool!
