### ISSUE TITLE
Docker Daemon OOM Crash -- [Reproducible via docker run]

### ISSUE THREAD

**Issue by kidambisrinivas** [docker/docker#9799]
Docker daemon has a monotonically increasing memory usage due to logs from a long running process, eventually causing an OOM crash killing the daemon.

On running the following command:

docker run -d debian:wheezy bash -c 'while true; do for i in {1..100};do echo "Just logging!!!!" 1>&2; done; sleep 1; done;'

docker daemon process's memory usage accelerates very quickly.

Is the only way to avoid this is by piping the logs of a log-intensive-long-running process to a file and mounting it on host or to keep truncating the logs in cron using this [new feature](https://github.com/docker/docker/pull/9753)?

Docker version facing this issue at: Docker version 1.4.1, build 5bc2ff8

**Comment by unclejack** [comment]
This is a known issue. Please take a look at #9139.

I'm going to close and lock this issue now so that conversation continues only on #9139. If you're affected or have something to say about this, issue #9139 is the right issue to comment on.
