### ISSUE TITLE
Proposal - Allow for different types of volumes

### ISSUE THREAD

**Issue by icecrime** [docker/docker#9803]
Issue statement
---------------------

Volumes today can come in different flavors, but always with the underlying idea of *persistent data*. The recent submission of a `--tmpfs` PR (#9586) raised interesting questions:
* Is `tmpfs` meaningful on other systems?
* Should this be related to volumes somehow?

This proposal only aims at offering a place to discuss this particular aspect of volumes management and hopefully providing UX input for #8484.

Proposal
------------

A volume should be about **granting special properties to a directory inside a container**. That special meaning depends on the nature of the volume being mounted:
* Persistent
* Bound to a host directory
* Ephemeral
* ...

The key aspect of the proposal is that it allows to discuss *properties* rather than *particular implementation*: `tmpfs` doesn't exist on some systems while the notion of ephemerality is universal.

Proposed UX
------------------

What is true for **all volumes types**:
* Volumes are managed with the set of top-level commands specified in #8484
* The `docker volume create` command has a `--type=(persistent|host|ephemeral|...)` argument
* Volumes are mounted using `docker run -v <volume_name_or_id>:/path/in/container/[:mode]`
* Volumes can be created at container run time using `docker run` command line arguments:
     * Type of the new volume is specified with `--volume-type=(persistent|host|ephemeral|...)`
     * Name of the new volume is specified with the optional `--volume-name` flag

Each type of volume might require **specific parameters** to be passed at creation time (such as the host path in case of a host-bound volume):
* For `docker volume create` args are appended as colon separated values to the `--type` flag
* For `docker run` command args are appended as colon separated values to the `--volume-type` flag
* In both cases, this list of positional arguments is passed to the volume strategy for interpretation

Examples
-------------

The two following examples are equivalent:

````
$ docker volume create --type=host --host-path=/path/to/host/dir/ --name bidule
$ docker run -v bidule:/path/in/container:ro -ti busybox
```
```
$ docker run -v /path/in/container:ro --volume-name=bidule --volume-type host:/path/to/host/dir/ -ti busybox
```

Ping @cpuguy83 @crosbymichael @shykes

**Comment by rhatdan** [comment]
I would suggest that we have at least one hard coded name tmpfs

docker run -v tmpfs:/tmp  ...

Although I would like tmpfs to tar all content of the target directory from the image into memory and then untar it onto the tmpfs.

**Comment by trentm** [comment]
Throwing out a possible `-v ...` syntax:

    -v volume-name-or-path:container-path[:mode-and-volume-params]
    
The "mode-and-volume-params" is the new suggestion. Volume params would
be `key=value` pairs where the keys match the "--key" options to
`docker volume create ...`. Keys other than the common set (name, type, mode)
could be passed to the volume strategy. Your first example becomes:

    docker run -v /path/to/host/dir/:/path/in/container:ro,name=bidule,type=host -ti busybox
    
This could solve the **Specifying multiple volumes in a docker run** question.
    
    docker run \
        -v /path/to/host/dir/:/path/in/container:ro,name=bidule,type=host \
        -v /blah:/path/in/container:type=ephemeral \
        -ti busybox

**Comment by SvenDowideit** [comment]
@icecrime can we combine this proposal with my  #9250 ? I think they're probably duplicates UX wise - mine goes on to suggest we expand the horizons of the vfs drivers :)

**Comment by icecrime** [comment]
Sorry, I still didn't take the time to look into the last comments and related PRs... It's on my TODO list, promise!

**Comment by ibuildthecloud** [comment]
It seems that volumes from a driver should be prepopulated as Docker does that with `-v /foo` today.  This would also address @rhatdan tmpfs comment of prepopulating.

**Comment by rhatdan** [comment]
It is a real shame that we don't have something here yet.  We were working on and proposing this months ago.  It actually is a nice secure way to run read/only containers, but here we are 6 months later and still no way to do it. Sad.

**Comment by cpuguy83** [comment]
@rhatdan We can move forward with this once the top-level volumes command is there. All is getting easier here.
Not sure if this should be an option on the `local` driver, or a driver that is for `tmpfs` (for the tmpfs case).

**Comment by thaJeztah** [comment]
Now that `--tempfs` is merged in https://github.com/docker/docker/pull/13587, and top-level volume management implemented in https://github.com/docker/docker/pull/14242, I think it's safe to close this one.

@ibuildthecloud I agree with pre-populating volumes, I think we can keep that for a separate discussion (I think there are some existing ones)
