### ISSUE TITLE
GNU screen Fails:  Cannot open your terminal '/dev/console' - please check. Non 'root' account 

### ISSUE THREAD

**Issue by WhisperingChaos** [docker/docker#9806]
##### Steps To Reproduce
  * Create an image using the following Dockerfile source:
```
    FROM	   ubuntu:12.04
    RUN apt-get update;  \
        apt-get install -y screen;
    RUN adduser --disabled-password --gecos -- dlw; \
        passwd -d dlw;
    USER dlw
    ENTRYPOINT  /bin/bash
```
  * Execute image: ```  'docker run -i -t <imageGUID>.' ```
  * On resulting container's command line attempt to start:  ```screen```.
Screen will issue the following message:
```Cannot open your terminal '/dev/console' - please check.```
Here are the permissions as displayed by ``` 'ls -al /dev/console' ```:
```
    crw------- 1 root root 136, 7 Dec 24 12:15 /dev/console
```
  * Alter Dockerfile so 'root' becomes default user and explicitly log in 'dlw' (non-root) account:
``` 
FROM	   ubuntu:12.04
RUN apt-get update;  \
    apt-get install -y screen;
RUN adduser --disabled-password --gecos -- dlw; \
    passwd -d dlw;
USER root
ENTRYPOINT  login dlw
````
  * Execute image: ```  'docker run -i -t <imageGUID>.' ```
  * Start: ```screen```.
Screen works as expected.
Here are the permissions as displayed by ``` 'ls -al /dev/console' ```:
```
    crw------- 1 dlw tty 136, 7 Dec 24 12:33 /dev/console
```

##### Environment
  * Using docker version 1.3.1.
  * Ubuntu  12.04.4 LTS

##### Behavior Assessment
An implicit login request, implemented by Dockerfile USER statement, that isn't 'root' doesn't seem to completely prepare a container's permissions to the /dev/console device for the implicit user.  However, an explicit 'login' request (event) triggers the container permissions for '/dev/console' to allow  non-root container accounts access to this device.  Are there potentially other permission issues resulting from this difference between implicit/explicit login requests?

**Comment by unclejack** [comment]
There doesn't seem to be any bug here. This seems like a docs issue.

**Comment by WhisperingChaos** [comment]
@unclejack

Thanks for your comment.

"seem" in your response is the operative in this discussion.  Again, as communicated above, it's difficult to classify this issue without understanding the intended behaviour.  As demonstrated by the example, a difference between USER and login surfaced, as a runtime security concern.  Due to the importance of security, further examination of the issue may be warranted to ensure that both build and run time contexts are "properly" secure.  Also, other container issues may eventually surface because of the differences between how USER and login prepare container environment.

Finally, although labelled as a doc issue, perhaps it might also be considered an enhance/feature request.  For example, if the notion of security within a running container remains relevant, maybe the Dockerfile USER command should be extended to optionally execute the linux login process for either build or run time contexts.

**Comment by stucki** [comment]
Disagree that this is a docs issue. When I run ```docker run``` with ```--user``` then I expect that $USER or `tty` permissions are correct. Currently, only $EUID, $HOME and $UID are different when I run a bash as something else than root (Ubuntu 14.04).

**Comment by unclejack** [comment]
This doesn't seem to be an issue with Docker master. I'll close this.

**Comment by stucki** [comment]
Confirmed, this works now!
