### ISSUE TITLE
Connection error using TLS from Windows CLI with relative path

### ISSUE THREAD

**Issue by keyonir** [docker/docker#9811]
Trying to connect to the docker engine from the Windows CLI using HTTPs generates an error if the .pem files are passed using a relative path to the .exe file.

**With relative path**

docker.exe --tlsverify --tlscacert=ca-public-key.pem --tlscert=client-cert.pem --tlskey=client-key.pem -H tcp://redacted:2376 info

Windows CLI Error:

 ←[31mFATA←[0m[0000] An error occurred trying to connect: Get https://redacted:2376/v1.16/info: remote error: bad certificate

Docker Engine Error: 

http: TLS handshake error from 23.102.xxx.xxx:1337: tls: client didn't provide a certificate

** With absolute path**

docker.exe --tlsverify --tlscacert="C:\Users\jangelfdez\Desktop\ca-public-key.pem" --tlscert="C:\Users\jangelfdez\Desktop\client-cert.pem" --tlskey="C:\Users\jangelfdez\Desktop\client-private-key.pem" -H=redacted:2376 info

Windows CLI message:
*Containers: 1
Images: 0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 2
...*

Docker Engine message.
*
INFO[2990] GET /v1.16/info
INFO[2990] +job info()
INFO[2990] +job subscribers_count()
INFO[2990] -job subscribers_count() = OK (0)
INFO[2990] -job info() = OK (0)
*

**Comment by ahmetalpbalkan** [comment]
@keyonir thanks for reporting, I'm trying to reproduce this but it appears that it works with relative paths as well.

1. Get `docker-1.4.1-dev.exe` from here (built from master) and copy to `c:\junk`
2. Copy `[ca/cert/key].pem` to `c:\junk`
3. (If you have a `%USERPROFILE%\.docker` directory, temporarily rename the folder to something else so it doesn't use default certs by accident)
4. Run `C:\junk>docker-1.4.1-dev.exe --tls --tlscacert=ca.pem --tlscert=cert.pem --tlskey key.pem info` (note that I'm not using --tlsverify as my host doesn't have a valid cert but I don't think this is the issue.)
5. Works on my setup.
6. Try with absolute paths, also works.

**Comment by keyonir** [comment]
It's strange, running the same steps from my first message now in the same environment the result is as expected. I have no modified or changed anything, it was the same virtual machine on Azure that I used 20 days ago and it has been deallocated this time.

In this case, I think that we can close it. Sorry for bothering you :(
