### ISSUE TITLE
Containers restart with different name when host reboots

### ISSUE THREAD

**Issue by hamiltont** [docker/docker#9815]
Please see signalfuse/maestro-ng#102 for more information

If I start a container with restart always and a specific name, and then reboot my server, the container is restarted with a different name. As multiple external libraries use the name to locate the service this is a problem for my setup. This may be a docker feature and not a bug - I'm not sure if there are guidelines  on how names will be handled when restarting

```
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa
____
Containers: 729
Images: 1870
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 3330
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
Username: hamiltont
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

**Comment by hamiltont** [comment]
After a reboot, I run `maestro -f myfile.yaml start` to bring all my containers back online. However, my sonarr container was started with restart always, so docker has already brought it back online before I run this command. Maestro uses the container name to identify if a container is already started, so it does not recognize the container that docker restarted as it has a random name instead of the original name of `sonarr`. For my specific use case, there cannot be two concurrent sonarr containers (the host port is set statically), so maestro fails to create a second sonarr container

**Comment by acbodine** [comment]
Ok, just trying to replicate this issue. Seems to work alright via boot2docker with a named container that has the `--restart=always` flag. Going to try on my linux box.

**Comment by hamiltont** [comment]
Great, thanks for trying. So for your boot2docker volume, rebooting the VM does not change the container name?

**Comment by acbodine** [comment]
Right, and I saw the same thing on my linux box. Only difference is the kernel is a 3.13.0-40 instead of 3.13.0-43 like you have. Im upgrading the kernel to try again.

**Comment by hamiltont** [comment]
Fascinating. If there may be logs on my machine that would help figure out what's happening I'm glad to share

**Comment by acbodine** [comment]
`
$ docker version
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa
`
$ docker info
Containers: 1
Images: 49
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 51
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
`

`
$ docker run -itd --name=foobar --restart=always ubuntu:trusty /bin/bash
38fc791e66bf.......

$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
38fc791e66bf        ubuntu:trusty       "/bin/bash"         52 seconds ago      Up 52 seconds 
`
... reboot system

`
$ docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
38fc791e66bf        ubuntu:trusty       "/bin/bash"         52 seconds ago      Up 52 seconds 
`

**Comment by acbodine** [comment]
If you restart the docker service on your server `sudo service docker restart` do you see the names changing?

If not maybe there is something in the init scripts for Docker on boot. Otherwise, are you sure Maestro isn't doing this?

**Comment by hamiltont** [comment]
For your `docker ps` output, it seems to not include the names column e.g. what's the name of the container before and after the reboot? 

    CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
    38fc791e66bf ubuntu:trusty "/bin/bash" 52 seconds ago Up 52 seconds

I'll try to restart docker daemon and get back

**Comment by acbodine** [comment]
Think those got cut off in the copy paste. Edited.

**Comment by hamiltont** [comment]
Ok, I'm seeing some quite odd behavior, but I can replicate the issue by restarting the daemon. I'm having trouble finding a small working example, but here's a log with my comments. This is raw docker - no maestro used. This was all run top to bottom, I just split it to add comments. 

Check what containers are running
```
$ sudo service docker status                                                                                                                                                                       
docker start/running, process 25179
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS                  PORTS                    NAMES
288ef5745489        hamiltont/sonarr:latest   "mono /opt/NzbDrone/   3 weeks ago         Up Less than a second   0.0.0.0:8989->8989/tcp   grave_euclid
```

Restart and confirm container named grave_euclid
```
$ sudo service docker restart
docker stop/waiting
docker start/running, process 25474
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS                    NAMES
288ef5745489        hamiltont/sonarr:latest   "mono /opt/NzbDrone/   3 weeks ago         Up 9 seconds        0.0.0.0:8989->8989/tcp   grave_euclid
```

Start new container, check names
```
$ sudo docker run -itd --name=foobar --restart=always ubuntu:trusty /bin/bash
2080bb5f0f6899b4fcb8134546d88a7c8736f4fe09e0aefe79f7bb513e10c121
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS                    NAMES
2080bb5f0f68        ubuntu:14.04              "/bin/bash"            5 seconds ago       Up 4 seconds                                 foobar
288ef5745489        hamiltont/sonarr:latest   "mono /opt/NzbDrone/   3 weeks ago         Up About a minute   0.0.0.0:8989->8989/tcp   grave_euclid
```

Restart again, notice name **is no longer correct**
```
$ sudo service docker restart
docker stop/waiting
docker start/running, process 25742
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS              PORTS                    NAMES
2080bb5f0f68        ubuntu:14.04              "/bin/bash"            20 seconds ago      Up 3 seconds                                 foobar
150e80eb68ca        hamiltont/sonarr:latest   "mono /opt/NzbDrone/   3 weeks ago         Up 3 seconds        0.0.0.0:8989->8989/tcp   berserk_stallman
```

Restart again, no change
```
$ sudo service docker restart
docker stop/waiting
docker start/running, process 25927
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED             STATUS                  PORTS                    NAMES
2080bb5f0f68        ubuntu:14.04              "/bin/bash"            42 seconds ago      Up Less than a second                            foobar
150e80eb68ca        hamiltont/sonarr:latest   "mono /opt/NzbDrone/   3 weeks ago         Up Less than a second   0.0.0.0:8989->8989/tcp   berserk_stallman
```

Start new container, restart, notice **name is back to grave_euclid`

I wanted to see if the name change is only triggered when a new container exists, that does seem to have something to do with it. 

```
$ sudo docker run -itd --name=foobar2 --restart=always ubuntu:trusty /bin/bash
a78222f5cc15ecaf305a997b3462f1b697ee3a7438cd709ca6cb64c48c8238fd
$ sudo service docker restart
docker stop/waiting
docker start/running, process 26181
$ sudo docker ps
CONTAINER ID        IMAGE                     COMMAND                CREATED              STATUS              PORTS                    NAMES
a78222f5cc15        ubuntu:14.04              "/bin/bash"            11 seconds ago       Up 3 seconds                                 foobar2
2080bb5f0f68        ubuntu:14.04              "/bin/bash"            About a minute ago   Up 2 seconds                                 foobar
288ef5745489        hamiltont/sonarr:latest   "mono /opt/NzbDrone/   3 weeks ago          Up 2 seconds        0.0.0.0:8989->8989/tcp   grave_euclid
```

I'll work on a smaller example, but for not this is looking odd. 

FWIW this is a personal home server that I don't touch much, there should be no odd startup scripts happening but I'm happy to look for them if someone says where

**Comment by hamiltont** [comment]
Gahh this is freaking me out. Every time I restart the daemon, this one container switches its name. [See here](http://pastie.org/pastes/9815413/text)

**Comment by acbodine** [comment]
So there should be a database called `linkgraph.db` in `/var/lib/docker` on your server where Docker daemon is running. Its an sqlite db so when I run:

"$ sudo sqlite3 linkgraph.db

sqlite> schema edge
CREATE TABLE edge (
        "entity_id" text NOT NULL,
        "parent_id" text NULL,
        "name" text NOT NULL,
        CONSTRAINT "parent_fk" FOREIGN KEY ("parent_id") REFERENCES "entity" ("id"),
        CONSTRAINT "entity_fk" FOREIGN KEY ("entity_id") REFERENCES "entity" ("id")
        );
CREATE UNIQUE INDEX "name_parent_ix" ON "edge" (parent_id, name);

sqlite> select * from edge;
0||/
38fc791e66bf2c10eb8d0e674f33bc0e2e3d159e44c98f5e849b8ff5e037675a|0|foobar
565884422f94571a8d653509fb9947915b7131694b92a273908d8d241a41fed2|0|cocky_bartik
25471e6322d29d9e5e80cc4307cbe8368e625646b5f278811f6efbebfe32a570|0|thirsty_goodall"

As you can see each one of the containers other than `id=0` are referencing `id=0` as their `parent_id`

How does this look on your system?

**Comment by jfrazelle** [comment]
@hamiltont any update on @acbodine's comment

**Comment by jfrazelle** [comment]
closing as stale please ping me with details to reproduce on latest and I will reopen

**Comment by shivampapat** [comment]
I am using Podman on a RHEL-9 machine.
I am facing the same issue that the container when system restarted starts with different name.

Podman: version 3.3.1

I tried to run as 
podman run -d --hostname=constName <container ID>

Expected result after restart :
podman ps.   ---> constName

Actual result:
podman ps ---> different or random name.

AM I missing something here ?

**Comment by shivampapat** [comment]
> closing as stale please ping me with details to reproduce on latest and I will reopen

Cna you please reopen this? Thanks

**Comment by shivampapat** [comment]
ok. Thank you @thaJeztah . 
Sorry didn't check earlier
