### ISSUE TITLE
Abnormal Container Termination 

### ISSUE THREAD

**Issue by ggrandes** [docker/docker#9831]
This is hard to explain, but example better than 1000 words:

###### On Terminal 1 (run)

    host$ sudo docker run --name="test" -i -t ubuntu /bin/bash

###### On Terminal 2 (exec)

    host$ sudo docker exec -it test /bin/bash

###### On Terminal 1 (human type: "exit")

    root@194c15a91851:/# exit
    (hang)

###### On Terminal 2

    root@194c15a91851:/#
    (exit)
    host$

###### On Terminal 3 (show state)

    host$ sudo docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                         PORTS               NAMES
    194c15a91851        ubuntu:latest       "/bin/bash"         About a minute ago   Up About a minute                                  test
    host$ sudo docker kill 194c15a91851
    Error response from daemon: Cannot kill container 194c15a91851: no such process
    FATA[0000] Error: failed to kill one or more containers 

###### On Terminal 2 (restart docker)

    host$ sudo restart docker
    docker start/running, process 5929
    host$ sudo docker ps -a
    CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                         PORTS               NAMES
    194c15a91851        ubuntu:latest       "/bin/bash"         6 minutes ago       Exited (-127) 5 minutes ago                        test

###### On Terminal 1

    (exit)
    FATA[0063] Get http:///var/run/docker.sock/v1.16/containers/194c15a91851bef7887110b45ddb7963ce88599cb3e7fc6d66450aaff766d7d3/json: write unix /var/run/docker.sock: broken pipe. Are you trying to connect to a TLS-enabled daemon without TLS?
    host$

###### Software Versions

    host$ docker version
    Client version: 1.4.1
    Client API version: 1.16
    Go version (client): go1.3.3
    Git commit (client): 5bc2ff8
    OS/Arch (client): linux/amd64
    Server version: 1.4.1
    Server API version: 1.16
    Go version (server): go1.3.3
    Git commit (server): 5bc2ff8
    host$ lsb_release -d
    Description:    Ubuntu 14.04.1 LTS
    host$ uname -a
    Linux host 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by unclejack** [comment]
Confirmed, this issue seems to be fixed.
