### ISSUE TITLE
Docker API port bindings hostIP not adding ip tables rule

### ISSUE THREAD

**Issue by rmb938** [docker/docker#9832]
If I start a container via the api with the host ip included in port bindings docker does not add a iptables rule

```
{"containerId":"e693a5a65e3589aeaa07c86261eff8202c5e8958d1cdafe347c3df3e66fb45ec","Binds":["/mnt/minestack:/mnt/minestack:rw"],"Links":[],"LxcConf":null,"PortBindings":{"25565/tcp":[{"HostIp":"192.168.1.20","HostPort":"25565"}]},"PublishAllPorts":false,"Privileged":false,"Dns":null,"DnsSearch":null,"VolumesFrom":null,"NetworkMode":"bridge","Devices":null,"RestartPolicy":null,"CapAdd":null,"CapDrop":null}
```

However if I run a container via a command it will add the itpables rule.

```
docker run -p 192.168.1.20:25565:25565 -d -v /mnt/minestack:/mnt/minestack minestack/bukkit
```

In both cases docker ps shows that the port should be forwarded properly

```
192.168.1.20:25565->25565/tcp
```

There are no errors returned by the API nor any in the docker logs.

Not to sure if I am just doing something wrong with the API but everything looks right.

**Comment by thaJeztah** [comment]
/ping @rmb938 could you add the requested information?

**Comment by cpuguy83** [comment]
So, the CLI uses the API, it has no special powers here :)

What the CLI is doing is putting anything passed to "-p" in both PortBindings and ExposedPorts.

But yes, this looks like a dup of #9853, so I'll close this one.  Feel free to comment there (or here if you think it's not a dup).

**Comment by featheredtoast** [comment]
Hey, I'm running latest release Docker version 1.5.0, build a8a31ef. Just hit this last week.

docker ps shows the port exposed, but when I look at iptables, the port is not exposed there.

The port is NOT exposed in the dockerfile. When the port IS exposed in the dockerfile, the iptables rule is updated as expected.

The docs suggest that I do not need the EXPOSE directive in the Dockerfile. Further, the silent failure on the iptables, despite docker ps/inspect suggesting that the port is exposed seems like a pitfall.

I am OK with the functionality as is (EXPOSE needed to forward ports), but this should be documented, and/or add some warnings. As-is, this is pretty ambiguous as to what docker should be doing in this case. Anyone want to clarify?
