### ISSUE TITLE
Docker silently ignores port mappings for non-exposed ports

### ISSUE THREAD

**Issue by discordianfish** [docker/docker#9853]
Hi,

it seems like recently Docker stopped exposing ports on images that don't have the right 'EXPOSE' statement which seems like a good idea in general. But it leads to a lot confusing since you can still start a container with arbitrary port mapping, Docker just silently ignores them: You can start the container just fine and it's not even logging anything about not doing the port mapping.
Instead, Docker should error out if someone tries to map a non-exposed port.

This lead me to open #9818 where in fact I just forgot the EXPOSE statement in my Dockerfile.

**Comment by resouer** [comment]
According to result of Docker inspect, Docker will expose the port if you are using `-p`:
```
      "ExposedPorts": {
            "5000/tcp": {},
            "8000/tcp": {}
        },
        "Hostname": "574bed343cda",
        "Image": "training/webapp",
```

In the case above I use `docker run -p xxxx:8000`, but the image of which is training/webapp and you can see port '8000' is not exposed in the [Dockerfile](https://github.com/docker-training/webapp/blob/master/Dockerfile) .

So I think we can just add a warning here instead of raise a error?

**Comment by jfrazelle** [comment]
I cannot reproduce hmmm @unclejack or @tiborvass can you?

**Comment by discordianfish** [comment]
@jfrazelle Can't reproduce it anymore either.. Maybe this was changed since 1.3.3? See also the issue I linked, maybe there was/is in fact a issue with exporting a port, no matter if exposed or not.

**Comment by jfrazelle** [comment]
hmm ok I am going to close I think it was fixed

**Comment by melhindi** [comment]
@liucimin I am seeing the same issue, did you find a solution?

**Comment by Timmmm** [comment]
This happens for me too. The documentation says

> The EXPOSE instruction does not actually publish the port. It functions as a type of documentation between the person who builds the image and the person who runs the container, about which ports are intended to be published.

Which is pretty damn misleading given that the port doesn't get mapped at all without `EXPOSE`.

I am creating my Docker container using `dockerode` like this:

```
  const container = await docker.createContainer({
    Image: "linux_server",
    HostConfig: {
      PortBindings: {
        "22/tcp": [
          {
            HostIp: "127.0.0.1",
            HostPort: "17878",
          },
        ],
      },
    },
  });

  await container.start();
```

With `EXPOSE 22` in the `Dockerfile`, it works (`docker port <container>` lists the port and I can connect). Without it it doesn't work.

**Comment by thaJeztah** [comment]
@Timmmm are you able to reproduce the problem as well when using the `docker` cli? e.g. something like:

```bash
docker run -d -p 127.0.0.1:17878:22 linux_server
```

**Comment by Timmmm** [comment]
@theJeztah No, that seems to work without the `EXPOSE`.

**Comment by alaendle** [comment]
Hi @thaJeztah, I experienced exactly the same behaviour described by @Timmmm - I'm unable to expose ports via create options PortBindings that are not already EXPOSEed in the Dockerfile. Is this really the way things should work? Or should we reopen this issue - or create a new one?
