### ISSUE TITLE
why docker run command under /bin/sh?????

### ISSUE THREAD

**Issue by lichuan** [docker/docker#9861]
why docker run command with default /bin/sh, why? why? why? , I think /bin/bash is good than /bin/sh, if you run under /bin/sh, some command will produce error. please tell me why docker run command with /bin/sh instead of /bin/bash??????

**Comment by SvenDowideit** [comment]
As a specific example - the busybox image doesn't have bash - the boot2docker iso doesn't have bash either `sh` exists and is the default for a reason.

**Comment by unclejack** [comment]
The builder documentation already states that `/bin/sh` is used for commands which look like `RUN foo`.

I'll close this issue since the only reason for keeping it open was to make the needed changes to the docs.

**Comment by odykyi** [comment]
add the first line to your file
```
#!/bin/sh
```
