### ISSUE TITLE
uptime not showing correct number of users

### ISSUE THREAD

**Issue by cglewis** [docker/docker#9864]
Inside of a container (Ubuntu 14.04) when running uptime, I get the following:

```
$ uptime
16:12:13 up 15:48,  0 users,  load average: 0.05, 0.04, 0.05
```

On the Docker host (Ubuntu 14.04) when running uptime, I get the following:

```
$ uptime
16:12:13 up 15:48,  2 users,  load average: 0.05, 0.04, 0.05
```

The container should at least be reporting 1 user, but it seems like if it's already going to mirror the host for all of the other attributes, then it should also mirror the user attribute, no?

**Comment by unclejack** [comment]
@cglewis This is expected.

**Comment by SvenDowideit** [comment]
@unclejack why is it expected? can we document it?
