### ISSUE TITLE
why is 'name' a query parameter (and not capitalized) in the remote api for /containers/create

### ISSUE THREAD

**Issue by mcfiredrill** [docker/docker#9866]
It seems inconsistent for it to not be capitalized, and what are query params doing in a POST request anyway?
https://docs.docker.com/reference/api/docker_remote_api_v1.16/#create-a-container

**Comment by duglin** [comment]
It may be inconsistent with the list of JSON params right before that text, but its pretty consistent with the rest of the query params for other Docker APIs.
btw - its ok to have query params on a POST.

**Comment by duglin** [comment]
can we close this?

**Comment by mcfiredrill** [comment]
Why not have it in the body instead of the query string? Its modifying data right?

**Comment by duglin** [comment]
Dunno - convenience?

**Comment by duglin** [comment]
@mcfiredrill you ok if we close this?

**Comment by mcfiredrill** [comment]
@duglin didn't really get an answer, so no, but nothing actionable is really coming out of this issue.

**Comment by duglin** [comment]
why keep it open then?  :-)

**Comment by nikolas** [comment]
lol
