### ISSUE TITLE
docker don

### ISSUE THREAD

**Issue by frank-dspeed** [docker/docker#9869]
with the new docker 1.4x docker don't uses the term variable right nsenter as also docker exec results now often with new containers when i execute tty applications like nano in can't find right terminal error.

i can work around this with example auto do on every interactiv container session export TERM=vt100 or i add ENV TERM=vt100 in the image but anyway this wasn't so befor befor it always worked!

**Comment by SvenDowideit** [comment]
This is a duplicate of #9299 - in which its noted that to get a terminal setting you need to run with `-t`

closing as dup
