### ISSUE TITLE
How to reproduce the -P flag functionality in the remote API

### ISSUE THREAD

**Issue by jamiehannaford** [docker/docker#9873]
What JSON element do I need to include in the [`/containers/create`](https://docs.docker.com/reference/api/docker_remote_api_v1.16/#create-a-container) API call which mimics the `-P` flag? I tried:

```json
{
	"Image": "foo",
  	"HostConfig": {
  	  	"PublishAllPorts": true
  	}
}
```

but every container (after being created and started) always has the same port:

```json
"Ports": [
  	{
  	  	"PrivatePort": 8080,
  	  	"Type": "tcp"
  	}
]
```

I want each container to be provisioned with its own external port number, forwarding to whichever port required inside the container.

**Comment by mariojunior** [comment]
I'm looking for a solution for it too.
If I stop/start containers using the Rest API, my containers (with self-signed ports mapping before) are losing these ports mapping. I can access the running services into the containers using the internal ip address but not using my localhost:bound_port.

Apparently, the argument -P or -p are available during the creation container phase, but if we stop and start these containers via API the ports just gone.

If we use the 'docker stop/start <container>' on the terminal, that works, but not using the Rest API.

**Comment by jfrazelle** [comment]
on start you need to pass publishAllPorts see https://github.com/docker/docker/issues/7869#issuecomment-54679108
