### ISSUE TITLE
Running integration tests on Overlayfs fail

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#9874]
Tests that fail:
```
--- FAIL: TestSaveAndLoadRepoFlags (0.47s)
	docker_cli_save_load_test.go:266: inspect is not the same after a save / load
--- FAIL: TestSaveDirectoryPermissions (1.02s)
	docker_cli_save_load_test.go:425: failed to find the layer with the right content listing
```
Can reproduce on overlayfs machine with:
```
DOCKER_GRAPHDRIVER=overlay make test-integration-cli
```

**Comment by LK4D4** [comment]
ouch

**Comment by jfrazelle** [comment]
still failing w kernel 3.18.2

**Comment by jfrazelle** [comment]
ping @alexlarsson just in case you may have any ideas on this. It would be greatly appreciated.

**Comment by alexlarsson** [comment]
What backing filesystem was this done on? Some filesystems don't fully support overlayfs. It should work on ext4 though.

**Comment by coolljt0725** [comment]
seems xfs don't fully support overlayfs, we meet some problem when we use overlayfs on xfs

**Comment by unclejack** [comment]
@alexlarsson This is what I was seeing with ext4 as the backing file system: https://gist.github.com/unclejack/26ec6fc2cf3453bb1a2f
The good output is from vfs and the bad one is from overlay.

**Comment by vbatts** [comment]
so, i'm testing this on 4.0.0-rc3 and not seeing _those_ two failures, instead i am seeing:
```
--- FAIL: TestDiffEnsureOnlyKmsgAndPtmx (0.58s)
        docker_cli_diff_test.go:112: "C /etc" is shown in the diff but shouldn't
--- FAIL: TestSaveDirectoryPermissions (2.32s)
        docker_cli_save_load_test.go:420: failed to find the layer with the right content listing
```
