### ISSUE TITLE
Cannot chmod directories created with COPY in Dockerfile

### ISSUE THREAD

**Issue by jberkus** [docker/docker#9879]
I'm pretty sure that this is an updated report of an existing bug, and it may be related to #9608, except that 9608 is marked fixed so I thought I should report it.  I couldn't find the other bug I thought related to this.

Docker: 1.4.1 installed as lxc-docker from ubuntu
Kernel: 3.13.0-37-generic
OS: Ubuntu 14.04
Base Image: Ubuntu:precise
Summary: if a directory is created using COPY in the image build, permissions on the directory (root-only) cannot be changed.

Dockerfile:

COPY setup /setup

Terminal: 

root@6853a5fc183d:/# cd /setup
root@6853a5fc183d:/setup# ls -l
total 16
-rwx--x--x 1 root root 1308 Jan  2 05:37 dbprep.sh
-rwx--x--x 1 root root 1094 Jan  2 20:18 package_install.sh
drwx------ 2 root root 4096 Aug 27  2013 pgbench
drwx------ 5 root root 4096 Jan  2 05:27 postgres
root@6853a5fc183d:/setup# chmod -R +rx *
root@6853a5fc183d:/setup# ls -l
total 16
-rwxr-xr-x 1 root root 1308 Jan  2 05:37 dbprep.sh
-rwxr-xr-x 1 root root 1094 Jan  2 20:18 package_install.sh
drwxr-xr-x 2 root root 4096 Jan  2 20:55 pgbench
drwxr-xr-x 8 root root 4096 Jan  2 20:55 postgres
root@6853a5fc183d:/setup# su - postgres
postgres@6853a5fc183d:~$ cd /setup
postgres@6853a5fc183d:/setup$ cd postgres
-su: cd: postgres: Permission denied
postgres@6853a5fc183d:/setup$

**Comment by phemmer** [comment]
This is likely related to the storage driver. Can you provide the output of `docker info`? (it's good practice to provide `docker info` and `docker version` when reporting issues)

**Comment by jberkus** [comment]
Containers: 2
Images: 37
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Dirs: 41
Execution Driver: native-0.2
Kernel Version: 3.13.0-43-generic
Operating System: Ubuntu 14.04.1 LTS
CPUs: 4
Total Memory: 3.749 GiB
Name: Radegast
ID: YNMB:HM2S:ULL5:5EZN:MF7J:4XPR:74QB:2RM6:OFOK:MQJ3:FPWF:FCQ4
Username: jberkus
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support

FYI, I've seen this issue before, and it's always an Ubuntu container on an Ubuntu host.

**Comment by jfrazelle** [comment]
dup of https://github.com/docker/docker/issues/783 and known issue see https://docs.docker.com/release-notes/#known-issues
