### ISSUE TITLE
After restarting linked container, the ENV variables of recipient doesn't update.

### ISSUE THREAD

**Issue by kalopsia** [docker/docker#9891]
Hello, I've noticed some weird behavior after restarting the linked container. Let's see this simple example:

```
docker run -d --name db training/webapp python app.py
docker inspect -f '{{ .NetworkSettings.IPAddress }}' db
172.17.0.3 # ip of db

docker run -d -P --name web --link db:db training/webapp python app.py
docker exec web cat /etc/hosts
172.17.0.4     4379cf90c3016
127.0.0.1	    localhost
...
172.17.0.3     db

docker exec web env
...
DB_PORT=tcp://172.17.0.3:5000
DB_PORT_5000_TCP=tcp://172.17.0.3:5000
DB_PORT_5000_TCP_ADDR=172.17.0.3
DB_PORT_5000_TCP_PORT=5000
DB_PORT_5000_TCP_PROTO=tcp
DB_NAME=/web/db
...
```
Now, lets restart `db` container and see what was changed in `web` container:
```
docker restart db
docker inspect -f '{{ .NetworkSettings.IPAddress }}' db
172.17.0.6

docker exec web cat /etc/hosts
172.17.0.4     4379cf90c3016
127.0.0.1	    localhost
...
172.17.0.6     db  #OK!

docker exec web env
...
DB_PORT=tcp://172.17.0.3:5000  #IP ADDRESS DOESN'T CHANGE
DB_PORT_5000_TCP=tcp://172.17.0.3:5000
DB_PORT_5000_TCP_ADDR=172.17.0.3
DB_PORT_5000_TCP_PORT=5000
DB_PORT_5000_TCP_PROTO=tcp
DB_NAME=/web/db
...
```
What's going on? May be I do something wrong?

**Comment by thaJeztah** [comment]
I *think* this is a known issue (but thinking of that, if it is, it is something that should be documented). The environment variables for links may even go away in the future because they don't really add much useful information (e.g., you have to *know* the port-number in order to *get* the right name of the environment-variable that contains the port-number :))

I realise this doesn't solve the *issue*, but would it work in your situation to use the hostname that's added in `/etc/hosts` in stead?

**Comment by kalopsia** [comment]
Yeap, using entry in the hosts file is quite enough for me (at least for now)! :)

**Comment by gdm85** [comment]
related to #9526

**Comment by thaJeztah** [comment]
I added some notes to the documentation to explain that the ENV-vars are not automatically updated; https://github.com/docker/docker/pull/10170

Also some additional explanation as to "why" that doesn't work and future changes can be found here; https://github.com/docker/docker/issues/10164#issuecomment-70407731

With those, I suggest to close this issue; updating the ENV-vars is not possible and alternatives will be implemented with the new networking?

**Comment by cpuguy83** [comment]
I'm going to go ahead and close this as it's basically a dup of #3155
Feel free to ping here or on IRC if you have any questions/concerns.

**Comment by gdm85** [comment]
@kalopsia you could use [docker-fw](https://github.com/gdm85/docker-fw/) to start them, then ports would be kept as before the stop. See also #8723

**Comment by kalopsia** [comment]
Thanks)
