### ISSUE TITLE
Cannot start container : accessing a corrupted shared library

### ISSUE THREAD

**Issue by WuLonghui** [docker/docker#9893]
Fail to stat a container:
```
Error response from daemon: Cannot start container 4b9a5585dce9: accessing a corrupted shared library
2015/01/04 22:02:26 Error: failed to start one or more containers
```
What is the issue?

cat /etc/issue
```
Red Hat Enterprise Linux Server release 6.4 (Santiago)
Kernel \r on an \m
```
uname -a
```
Linux 29a75c19-7d39-460b-b8e5-405ec9a58bcc 2.6.32-358.el6.x86_64 #1 SMP Tue Jan 29 11:47:41 EST 2013 x86_64 x86_64 x86_64 GNU/Linux
```

docker version:
```
Client version: 1.2.0
Client API version: 1.14
Go version (client): go1.3.1
Git commit (client): fa7b24f
OS/Arch (client): linux/amd64
Server version: 1.2.0
Server API version: 1.14
Go version (server): go1.3.1
Git commit (server): fa7b24f
```

docker info
```
Containers: 8
Images: 16
Storage Driver: devicemapper
 Pool Name: docker-8:33-524292-pool
 Pool Blocksize: 64 Kb
 Data file: /var/vcap/store/docker/docker/devicemapper/devicemapper/data
 Metadata file: /var/vcap/store/docker/docker/devicemapper/devicemapper/metadata
 Data Space Used: 495.4 Mb
 Data Space Total: 102400.0 Mb
 Metadata Space Used: 1.9 Mb
 Metadata Space Total: 2048.0 Mb
Execution Driver: native-0.2
Kernel Version: 2.6.32-358.el6.x86_64
Operating System: <unknown>
```

**Comment by SvenDowideit** [comment]
you need RHEL 6.5 or higher for Docker to work reliably. please see http://docs.docker.com/installation/rhel/ (or your RHEL support peeps)

**Comment by unclejack** [comment]
Please install all system updates using `yum update` and update. RHEL 6.5 and newer are recommended for Docker.

I'm going to close this issue now since there's nothing to be done in Docker to fix this. A system update will be enough.

**Comment by knovak** [comment]
Just got this same problem, on Red Hat 6.6:

$ sudo docker run -i -t -p 80:80 -p 8071:8071  -v /home/knovak4:/tmp/knovak4 --name=api   knovak/dashb1  /bin/bash   
2015/02/02 18:21:48 Error response from daemon: Cannot start container 1ccecac1092387fe248da930e7310726d353e93b32d20677a34c9ee63299f585: accessing a corrupted shared library

$ cat /etc/issue
Red Hat Enterprise Linux Server release 6.6 (Santiago)

Any suggestion?
