### ISSUE TITLE
how to trouble shooting docker on windows?

### ISSUE THREAD

**Issue by sunstudy** [docker/docker#9895]
now i confront with some really confusing problem when i run docker on windows.

i can run boot2docker only at the first few minutes i reboot my system, and minutes later, i may failed to connect to docker, and my docker instance will be damaged, i don't know what happened, so i come here and ask whether there is  a method to trouble shooting or hack the strange behavior of docker on windows?

some details i find now:

E:\>boot2docker -v status
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
2015/01/04 23:58:30 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
error in run: Failed to get machine "boot2docker-vm": fork/exec C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe: Access is denied.

E:\>boot2docker -v init
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
2015/01/04 23:58:46 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
2015/01/04 23:58:46 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
2015/01/04 23:58:46 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 list vms
error in run: Failed to initialize machine "boot2docker-vm": fork/exec C:\Progra
m Files\Oracle\VirtualBox\VBoxManage.exe: Access is denied.

E:\>boot2docker -v up
Boot2Docker-cli version: v1.4.1
Git commit: 43241cb
2015/01/04 23:59:00 executing: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
 showvminfo boot2docker-vm --machinereadable
error in run: Failed to get machine "boot2docker-vm": fork/exec C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe: Access is denied.

**Comment by jfrazelle** [comment]
Please file this issue in docker/boot2docker
