### ISSUE TITLE
/sys/fs/cgroup/memory/docker directory no longer exists. 

### ISSUE THREAD

**Issue by timjrobinson** [docker/docker#9902]
I recently did an apt-get upgrade on my Ubuntu 14.04 machine which installed docker version 1.3 (it used to be 1.0). I used to be able to see memory values of a container at:

/sys/fs/cgroup/memory/docker/[containerId]

but now it looks like they've moved to:

/sys/fs/cgroup/memory/system.slice/docker-[containerid].scope

Is this a change between docker 1 -> 1.3? I don't see it documented anywhere. Or if not what could have caused this?

**Comment by LK4D4** [comment]
@timjrobinson Looks like now you have systemd :D

**Comment by timjrobinson** [comment]
So turns out my machine wasn't using Ubuntu 14.04, its running Debian Jessie.... things make a lot more sense now. Thanks!
