### ISSUE TITLE
Problem pulling docker repository - no answer from server

### ISSUE THREAD

**Issue by ordinaryhed** [docker/docker#9903]
Hi,

Trying out Docker om osx. 

Gets the following problem when running simple container: 

hed:~ fredrik$ docker run -d -P --name web nginx
Unable to find image 'nginx:latest' locally
Pulling repository nginx
FATA[0270] Get https://index.docker.io/v1/repositories/library/nginx/images: dial tcp: lookup index.docker.io on 10.0.2.71:53: no answer from server 

Have changed the nameserver to 8.8.8.8 but still having the same problem.

Any ideas?

Some info:
os x 10.10.1

hed:~ fredrik$ docker info
Containers: 0
Images: 0
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Dirs: 0
Execution Driver: native-0.2
Kernel Version: 3.16.7-tinycore64
Operating System: Boot2Docker 1.4.1 (TCL 5.4); master : 86f7ec8 - Tue Dec 16 23:11:29 UTC 2014
CPUs: 4
Total Memory: 1.961 GiB
Name: boot2docker
ID: XKFR:ZDGC:INVP:UCXR:WWTH:KPOB:RBC7:2WZ4:S7BY:KMNF:MINP:6BLV
Debug mode (server): true
Debug mode (client): false
Fds: 10
Goroutines: 13
EventsListeners: 0
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker

**Comment by unclejack** [comment]
@ordinaryhed Are you behind the GFW? If you are behind the GFW, this wouldn't surprise me.

**Comment by ordinaryhed** [comment]
After I reinstalled docker and boot2docker using brew docker was working as expected.
