### ISSUE TITLE
Docker build switch "pull=true" not listed in online documentation

### ISSUE THREAD

**Issue by AndyBerman** [docker/docker#9912]
The code block in https://docs.docker.com/reference/commandline/cli/#build should show one of the docker build options as:

--pull=false   Always attempt to pull a newer version of the image

It appears that this was added in Docker 1.4.0, but I don't see it listed in the release notes for that.
It's a great feature that should be documented somewhere.

**Comment by SvenDowideit** [comment]
woah, you're right!
