### ISSUE TITLE
Is there a way to add a volume to container when the docker container is running?

### ISSUE THREAD

**Issue by coolljt0725** [docker/docker#9915]
Hi,all

At some use case,we want to add a volume to docker container when the container is running,in other words we want to add/delete volume to docker container dynamically.Docker don't support this right now,is there a way to do this or will docker support this?

Regards

**Comment by dims** [comment]
@coolljt0725 - watch this PR :) https://github.com/docker/docker/pull/8826

**Comment by jfrazelle** [comment]
duplicate https://github.com/docker/docker/issues/9849
