### ISSUE TITLE
who can i use  container ip+port visit the internal application？

### ISSUE THREAD

**Issue by oxwangfeng** [docker/docker#9921]
how can i do that：
To assign a IP to a container, and let outside access to the inside application of the container through the  IP and application port；
for example：
1.create a container；
2.assign a ip to this container， ip：192.168.1.1；
3.start a application in container，and port is 9999；
4.i want visit the application everywhere through container ip+port，not physical ip+port
who can i do？

**Comment by cc272309126** [comment]
you must create a bridge, and bind the veth of docker to the bridge, and the you can visit the application everywhere through container ip+port. pipework can do this. https://github.com/jpetazzo/pipework. also you can write a shell script by your self.

**Comment by oxwangfeng** [comment]
thank you，i try this，and sucess
