### ISSUE TITLE
The container restart one time less than what was specified in restart policy 

### ISSUE THREAD

**Issue by HuKeping** [docker/docker#9923]
docker run --restart=on-failure:3 redis 

which expected to restart 2 times before giving up just  restart only 4 times.This happened because in function shouldRestart() we use

container.failureCount >= restartPolicy.MaximumRetryCount

to determinate whether it should restart or not. But the failureCount will increase every time the container exit successfully include the first time, is this a logical error?

docker inspect log as below

**Comment by HuKeping** [comment]
This happened  because  we use 

container.failureCount >= restartPolicy.MaximumRetryCount
 
to determinate whether it should restart or not. But  the failureCount will increase every time the container exit successfully include the first time, so failureCount will always equals the (real retrycount + 1)

**Comment by HuKeping** [comment]
docker inspect 20a75e9bf8a4 | grep Count
![image](https://cloud.githubusercontent.com/assets/9958621/5639358/db3f73f0-964f-11e4-839d-a307476a758e.png)

**Comment by tiborvass** [comment]
For future reference, this was closed by #10058
