### ISSUE TITLE
How do I get ``docker run`` command line ?

### ISSUE THREAD

**Issue by abcfy2** [docker/docker#9924]
Hi all,

I want to see the start command line of the container(like docker run -d -e a=b -p 1111:1111 image_name command p1 p2 ...), how to?

But ``docker ps -a`` can only show the name.

Thanks.

**Comment by HuKeping** [comment]
docker inspect  + container_id will give u what u want, but not in a combo line, it's json

**Comment by abcfy2** [comment]
Thank you. I've got it. But it's not human readable. From ``docker inspect`` to find ``docker run`` command is a little hard.

**Comment by icecrime** [comment]
This should help:

    $ docker inspect -f '{{json .Config.Cmd}}' <container_id>

**Comment by HuKeping** [comment]
that's a good way! and if u want it more clear, u can try with this:

$ docker inspect -f '{{json .Config.Cmd}}' <container_id> | python -m json.tool

**Comment by abcfy2** [comment]
That's it ! Thanks. I can also use linux command ``jq`` to format json output.
