### ISSUE TITLE
Disk space leak from volumes after docker daemon restart

### ISSUE THREAD

**Issue by galdosd** [docker/docker#9930]
Steps to reproduce:

1) Start a container with a volume
2) Put some data in the volume
3) Reboot the host, kill -9 the docker daemon, or otherwise uncleanly stop the docker daemon
4) Start the docker daemon again. 
5) If there are any containers still apparently around according to docker ps -a, docker rm those

Possibly Expected result (best case): The amount of disk space used is the same as before
Possibly Expected result (worst case): More space is used due to stranded volumes, but there is a reliable (not undocumented internals) way to garbage collect those stranded volumes, or remount them to a new container to retrieve the data, etc.
Actual result: The disk space from the volume in the container that was running at unclean reboot time is still consumed. Specifically, /var/lib/docker/vfs/dir/(hash) will still exist and all files will still be in there. No amount of docker daemon restarting or anything else will get rid of this, nor will it be possible to find the volume through safe docker means (official client or API). There is just a permanent space leak and the only safe way to clean it up is to ensure all desired images/volumes are backed up elsewhere, stop the docker daemon, rm -rf /var/lib/docker, and restart the daemon, and then restore the images/volumes that were backed up.

Reproducability: 

Very reproducible.
Saw it happen once on 1.3.3 in production (those are the environment details below)
Tried it a single time on my local 1.3.2 install and it immediately reproduced the first time.

Environment info:

The host is running on a physical Dell PowerEdge R620
I'm using docker 1.3.3 but could not find any related patches in 1.4.x

"uname -a; docker version; docker -D info" output follows:

Linux hostname 2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 14:19:04 CST 2014 x86_64 x86_64 x86_64 GNU/Linux
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): d344625
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): d344625
Containers: 9
Images: 159
Storage Driver: devicemapper
 Pool Name: docker-253:6-234940768-pool
 Pool Blocksize: 65.54 kB
 Data file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata file: /var/lib/docker/devicemapper/devicemapper/metadata
 Data Space Used: 16.05 GB
 Data Space Total: 107.4 GB
 Metadata Space Used: 15.2 MB
 Metadata Space Total: 2.147 GB
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 2.6.32-504.1.3.el6.x86_64
Operating System: <unknown>
Debug mode (server): false
Debug mode (client): true
Fds: 25
Goroutines: 35
EventsListeners: 0
Init Path: /usr/bin/docker

My apologies in advance if this duplicates another issue and my searching was just poor. I can also provide more information if needed.

**Comment by cpuguy83** [comment]
If you want to delete the volume, you need to do "docker rm -v", this is by design.
See #8484 for improvements to volumes.

Also see github.com/cpuguy83/docker-volumes for a way to clean these up today.

**Comment by galdosd** [comment]
The trouble with "docker rm -v" is that after an unclean restart, the containers are already gone and can't be found even in "docker ps -a" so AFAIK there is no way to actually use "docker rm -v" in this situation.

However, it sounds like #8484 would take care of this and other volume problems entirely. I'm looking forward to trying it out after it's merged! Thanks for your work on it!

(I would certainly not object to this issue #9930 being closed/rejected now since it sounds like it's mostly a duplicate of a subset of #8484 and related stuff)

**Comment by galdosd** [comment]
Well, AFAIK "docker rm -v" won't actually work in this case, because after the unclean restart the containers are all gone and even "docker ps -a" will not list them, leaving no documented way to find the IDs to put in the command.

With that said I looked at #8484 and seems it solves this issue and many others about volumes. I'm looking forward to trying it out after it is merged; thanks for your work on it!

**Comment by cpuguy83** [comment]
@galdosd I'm pretty sure `kill -9`ing docker should not mess up containers.
