### ISSUE TITLE
Using postgresql with external volume from Mac

### ISSUE THREAD

**Issue by volkanunsal** [docker/docker#9956]
This issue is related to #6848. But rather than mounting the data folder from another container, I am trying to mount it directly from the Mac file system.

```bash
docker run  -v $HOME/postgres_data:/var/lib/postgresql kartoza/postgi
```

This results in a bunch of errors about user permissions:

```
initdb: could not create directory "/var/lib/postgresql/9.3/main/global": Permission denied
2015-01-07 16:33:52 UTC FATAL:  data directory "/var/lib/postgresql/9.3/main" has wrong ownership
2015-01-07 16:33:52 UTC HINT:  The server must be started by the user that owns the data directory.
```

I wonder if I'm tilting at the windmills. Can a directory shared from Mac file system ever have the read/write permissions that postgres apparently needs?

**Comment by volkanunsal** [comment]
Figured it out. I had to change the location of the data directory and update the `postgresql.conf` file as well.

**Comment by eightytwo** [comment]
@volkanunsal: Can you provide more specific information on how you fixed this issue? I am running into the same problem.

**Comment by base698** [comment]
+1 what did you do to fix it?
