### ISSUE TITLE
C++ rest api client

### ISSUE THREAD

**Issue by lasote** [docker/docker#9958]
Hi, 

I have developed a C++11 client for docker. You can find it here: http://www.biicode.com/lasote/docker_client

Can you update the client libraries list? (https://docs.docker.com/reference/api/remote_api_client_libraries)

**Language/Framework** C++
**Name:** lasote/docker_client
**Repository:** http://www.biicode.com/lasote/docker_client (Biicode C++ dependency manager)
**Status:** Active, Beta version

**Comment by MalteJ** [comment]
Hi @lasote 
you may fork the Docker repo, add your lib to https://github.com/docker/docker/blob/master/docs/sources/reference/api/remote_api_client_libraries.md
and send a pull request :-)
Best,
Malte

**Comment by lasote** [comment]
Thanks MalteJ.
