### ISSUE TITLE
Shell form ENTRYPOINT should be more intelligent

### ISSUE THREAD

**Issue by MetaMemoryT** [docker/docker#9959]
Why make the shell form for ENTRYPOINT a second class citizen?

Why not make it accept arguments, and interpret CMD additions?

Then their would be no need to document its deficiencies.

If docker is to become the best syntax to configure systems, it *must* support the most simple and intuitive syntax.

Are their any issues with this change besides backwards compatibility to consider?

**Comment by jfrazelle** [comment]
what do you mean a second class citizen? 

any ideas @tiborvass

**Comment by tiborvass** [comment]
@MetaMemoryT could you give an example of what you're suggesting?

**Comment by MetaMemoryT** [comment]
As specified in the docs https://docs.docker.com/reference/builder/#entrypoint

"shell form" without the limitations currently listed, rather than "the preferred exec form"

**Comment by jfrazelle** [comment]
it is not a second class citizen, it just is listed second under the preferred way of doing it. Projects will always have best practices and ours include this "preferred exec form". The "shell form" still works tho.
