### ISSUE TITLE
Add base filesystem to docker info

### ISSUE THREAD

**Issue by jfrazelle** [docker/docker#9960]
as mentioned in https://github.com/docker/docker/issues/9820 as a nice to have, making this an issue so I don't forget to make the PR

**Comment by estesp** [comment]
@jfrazelle I was thinking of working on this if you aren't--but to verify what I'm thinking: devmapper, aufs, and overlay can have backing FS--btrfs **is** a base FS, so wouldn't make sense to try and reference "backing" FS in that case.

Overlay and aufs both already have checks in `Init()` for a few incompatible FS; I would probably centralize this syscall in graphdriver, which returns just the magic for the backing FS, so it can be used for both reporting and for checking against incompatible FS.

That only leaves one big question--what `FSMAGIC` do we want to "support" in our check, given I assume we want to actually show a useful name, we will need a map.  The entire list is quite large ( https://github.com/torvalds/linux/blob/master/include/uapi/linux/magic.h ) but I assume we might want to just focus on what seems reasonable for Linux installations as a starting point?

**Comment by jfrazelle** [comment]
Your patch is awesome and I think it contains all the common filesystems, of course if anyone has anything else I am sure they will open an issue and we can add ;)
