### ISSUE TITLE
batch execute pushImge execption

### ISSUE THREAD

**Issue by zhangwei1234** [docker/docker#9966]
error log

time="2015-01-08T14:09:17+08:00" level="info" msg="POST /images/jae.registry.com:5000/6e4a635d5205b1e1054df96d74974d09/push?registry=jae.registry.com%3A5000&tag=latest" 
time="2015-01-08T14:09:17+08:00" level="info" msg="+job push(jae.registry.com:5000/6e4a635d5205b1e1054df96d74974d09)" 
Received HTTP code 500 while uploading layer: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
500 Internal Server Error
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

time="2015-01-08T14:09:19+08:00" level="info" msg="-job push(jae.registry.com:5000/1d238eae732b9647730d02cd4b73dfe9) = ERR (1)" 
time="2015-01-08T14:09:19+08:00" level="info" msg="DELETE /images/jae.registry.com:5000/1d238eae732b9647730d02cd4b73dfe9"

**Comment by jfrazelle** [comment]
I think this must have happened when hub was having an outage, be sure to check status.docker.com in future, sorry for any trouble this caused
