### ISSUE TITLE
Missing Server name indication (SNI) for virtual hosting in docker cli

### ISSUE THREAD

**Issue by ibruell** [docker/docker#9969]
I have a webserver (apache-2.4) in front of the docker registry. This webserver uses virtual hosting to support different domains on one server. To determine the correct site with ssl SNI is used. so the client must support it.

Please add SNI Support to the docker cli.

**Comment by lorenz** [comment]
+1

**Comment by seanf** [comment]
I don't think I will have time to implement or test this (I'm very new to Go), but I hope my notes will help someone.

I think this will require changes to `NewRequest` in `utils/http.go` and/or `doRequest` in `registry/registry.go` .  I don't think the [`net/http`](http://golang.org/pkg/net/http/) package can handle SNI, in which case [`crypto/tls`](http://golang.org/pkg/crypto/tls/#Config) is probably needed (by setting `Config`'s `ServerName`).  This will apparently require a custom `Client`/`Transport`, similar to the example of customising `RootCAs` here: http://golang.org/pkg/net/http/#pkg-overview

**Comment by lorenz** [comment]
Actually net/http does support SNI (tested on Ubuntu 14.04 with Go 1.2.1).

**Comment by tendril-dockerhub** [comment]
+1

**Comment by DavidXArnold** [comment]
+1

**Comment by fgimenez** [comment]
#dibs

**Comment by arthurbarros** [comment]
+1
