### ISSUE TITLE
Incorrect display format of size in docker ps -s

### ISSUE THREAD

**Issue by thaJeztah** [docker/docker#9977]
I noticed that sizes shown by `docker ps -s` are formatted incorrect / inconsistent;

    $ docker ps -s
    CONTAINER ID  IMAGE COMMAND CREATED STATUS PORTS   NAMES  SIZE
    024b89ef4d0a  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  1.57 MB
    50163140f98f  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  1.096 MB
    f29c681fb177  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  98.73 kB

As seen above, a dot (`.`) is used both as *decimal* and as *thousands* separator, making it difficult to distinguish a 1+ GB container from a 1.5 MB container (or at least confused me wether it *was* 1GB or 1MB).

I would have expected something like (asuming en_US locale);

    $ docker ps -s
    CONTAINER ID  IMAGE COMMAND CREATED STATUS PORTS   NAMES  SIZE
    024b89ef4d0a  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  1.57 MB
    50163140f98f  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  1,096 MB
    f29c681fb177  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  98.73 kB

Or (right aligned and always show decimals);

    $ docker ps -s
    CONTAINER ID  IMAGE COMMAND CREATED STATUS PORTS   NAMES         SIZE
    024b89ef4d0a  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]      1.57 MB
    50163140f98f  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]  1,096.00 MB
    f29c681fb177  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]     98.73 kB

**Comment by icecrime** [comment]
Naive question perhaps, but what makes you think the `.` in `1.096 MB` is a thousand separator?

I just did a few tests generating files with `dd`, the `.` seems to consistently be a thousand separator:

```
$ docker run --name 1G busybox /bin/sh -c "dd if=/dev/zero of=test bs=1 count=0 seek=1G"
$ docker run --name 512M busybox /bin/sh -c "dd if=/dev/zero of=test bs=1 count=0 seek=512M"
$ docker ps -as
CONTAINER ID        IMAGE               COMMAND                CREATED             STATUS                      PORTS               NAMES               SIZE
4c12fb3d4d94        busybox:latest      "/bin/sh -c 'dd if=/   2 seconds ago       Exited (0) 1 seconds ago                        512M                536.9 MB
6839ad443ec9        busybox:latest      "/bin/sh -c 'dd if=/   32 seconds ago      Exited (0) 31 seconds ago                       1G                  1.074 GB
```

**Comment by thaJeztah** [comment]
Hm (lolz); you are probably right!

The reason I *thought* it was a thousands separator, is there's *three* digits. Whereas the others have two. Due to the numbers being left aligned I interpreted that incorrectly. Living in the Netherlands (where a dot (`.`) is used as a *thousands* separator), probably added to that.

To take away this confusion, Perhaps the precision should be kept to *two* digits consistently, and right aligned;

```
$ docker ps -s
CONTAINER ID  IMAGE COMMAND CREATED STATUS PORTS   NAMES         SIZE
024b89ef4d0a  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]      1.57 MB
50163140f98f  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]      1.10 MB
f29c681fb177  [cut] [cut]   [cut]   [cut]  80/tcp  [cut]     98.73 kB

```

**Comment by icecrime** [comment]
Feel free to submit a patch for this: I'm closing this issue.
