### ISSUE TITLE
`docker wait` can return invalid exit codes

### ISSUE THREAD

**Issue by stevenschlansker** [docker/docker#9979]
POSIX defines process exit codes to be an unsigned 8 bit integer (0-255)
Certain cases can cause `docker wait` to return values out of that range.  For example, by intentionally invoking the OOM killer.  This can cause problems with inspecting the exit code in some shells:

```
root@ip-10-30-38-29:~# docker run -m 4m --name wat -it myjavacontainer java
root@ip-10-30-38-29:~# echo $?
255
root@ip-10-30-38-29:~# docker wait wat
-1
root@ip-10-30-38-29:~# /bin/dash -c 'exit $(docker wait wat)'
/bin/dash: 1: exit: Illegal number: -1
```
I expect `docker wait wat` to return 255, same as the exit code of `docker run`.

**Comment by icecrime** [comment]
That's tricky because the only code path for `wait` returning -1 is when it actually *failed* to wait because of a timeout. So the result cannot be interpreted as a valid exit code, and I think that makes sense.

**Comment by stevenschlansker** [comment]
But the container has already exited -- how could it time out?  Having error codes look exactly the same as a "successful" response (that the wait succeeded) seems like a really poor UI.
Also, running `docker inspect` indicates that it thinks the exit code actually is -1...
```
    "State": {
        "Error": "",
        "ExitCode": -1,
        "FinishedAt": "2015-01-08T18:38:39.834089879Z",
        "OOMKilled": true,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2015-01-08T18:38:39.309034983Z"
    }
```

**Comment by icecrime** [comment]
Hum, sorry but I'm confused. I tried the following which seems to behave correctly:

```
$ docker run --name test busybox sh -c "exit 255"
$ echo $?
255
$ docker inspect -f '{{.State.ExitCode}}' test
255
$ docker wait test
255
```

Can you please give us more elements to reproduce?

**Comment by stevenschlansker** [comment]
@icecrime 
```
root@ip-10-30-38-29:~# docker run -m 4m --name oom-test ubuntu:14.04 perl -e '"4"x(1024*1024*1024);'
root@ip-10-30-38-29:~# docker wait oom-test
-1
root@ip-10-30-38-29:~# docker inspect oom-test
...
    "State": {
        "Error": "",
        "ExitCode": -1,
        "FinishedAt": "2015-01-09T19:20:39.682015835Z",
        "OOMKilled": true,
        "Paused": false,
        "Pid": 0,
        "Restarting": false,
        "Running": false,
        "StartedAt": "2015-01-09T19:20:39.620539547Z"
    }
```

**Comment by icecrime** [comment]
Perfect @stevenschlansker thank you, I'll look into it!
Sorry I didn't initially understood that exiting on OOM was relevant for this issue.

**Comment by estesp** [comment]
It's not necessarily relevant re: OOM; it is the difference between writing a integer as string to stdout versus calling Go's `os.exit(rc)`, which calls sys_exit (syscall) under the covers, which apparently respects the standard that return codes are in the range 0..255, and takes > 255 values modulo 256, meaning `os.Exit(-1)` becomes 255 when you check the `$?`.

For `docker wait`, os.Exit(0) is called (because the docker wait run was successful), but the `ExitCode` read from the container status is written as-is to stdout, so the `-1` is not converted as it would be in the `os.Exit` case during `docker run`.

**Comment by icecrime** [comment]
I'll submit a fix for the issue this afternoon, I just need to sort the
testing aspects.

On Friday, January 9, 2015, Phil Estes <notifications@github.com> wrote:

> It's not necessarily relevant re: OOM; it is the difference between
> writing a integer as string to stdout versus calling Go's os.exit(rc),
> which calls sys_exit (syscall) under the covers, which apparently respects
> the standard that return codes are in the range 0..255, and takes > 255
> values modulo 256, meaning os.Exit(-1) becomes 255 when you check the $?.
>
> For docker wait, os.Exit(0) is called (because the docker wait run was
> successful), but the ExitCode read from the container status is written
> as-is to stdout, so the -1 is not converted as it would be in the os.Exit
> case during docker run.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/docker/docker/issues/9979#issuecomment-69392334>.
>


-- 
Arnaud Porterie

**Comment by estesp** [comment]
This is more for reference on the OOM side of things--given I was just working in the code for OOM (to add the event for oom killed), I actually was tempted to set the exit code to 138 (per this: http://tldp.org/LDP/abs/html/exitcodes.html) to reference that the process was SIGKILLed; that would fix this situation, but "-1" is still the default (initial exit code) it appears (to differentiate from an actual return code from the container's process, I assume).  @icecrime given you are looking at this, let me know if you think it makes sense to have OOM have a specific exit code versus the generic -1.

**Comment by stevenschlansker** [comment]
Shouldn't that be exit code 137?  (128 + 9)
I like using the specific exit code for OOM conditions, makes it easier to debug.

**Comment by icecrime** [comment]
I did choose 137 yes.
