### ISSUE TITLE
Mounting a host folder is broken?

### ISSUE THREAD

**Issue by pchico83** [docker/docker#9981]
Hi, I have a mysql image that defines 2 volumes.
When running it as a container, I want to mount two host folders into the image volumes using the remote API. Before v1.4.0, I was doing it only at starting the container (which looks deprecated). In v1.4.1 I need to define `HostConfig.Binds` both at container creation and also when starting the container.
I would expect to do it only at creation time or when starting the container.
@cpuguy83 Is this by design? Thanks

**Comment by cpuguy83** [comment]
@pchico83 It should only be needed either/or, if you have to do it at both that seems off.
1.4.0 had some issues with binds and volumes-from passed in at start.

At start is _not_ deprecated.

**Comment by pchico83** [comment]
@cpuguy83 These are my experiments in `1.3.3` and `1.4.1`

# 1.3.3

Client version | Mounting At | Result
------------------ | ---------------- | ---------
v1.14 | START | OK
v1.15 | START | OK
v1.15 | CREATE | KO
v1.15 | BOTH | OK

# 1.4.1

Client version | Mounting At | Result
------------------ | ---------------- | ---------
v1.14 | START | KO
v1.15 | START | KO
v1.15 | CREATE | OK
v1.15 | BOTH | OK
v1.16 | START | KO
v1.16 | CREATE | OK
v1.16 | BOTH | OK

Looks like `1.4.1` has fixed mounting at creation time, but has broken mounting at starting time. I can send you the exact API requests I am doing (I didn't test it for `volumes_from`), but we should fix these inconsistencies.

**Comment by cpuguy83** [comment]
I'd need to see an example as these are all tested for.

**Comment by pchico83** [comment]
@cpuguy83 I found the case where this happens. I had a mysql container mounting 2 volumes and I removed the container without removing its volumes. Now, I want to deploy a new mysql container reusing those volumes, which live at:

```
    "Volumes": {
        "/etc/mysql": "/var/lib/docker/vfs/dir/fc53b53ea3720d5c7b5276601f80cc172049793cb25287c5dcbe247844b10b0a",
        "/var/lib/mysql": "/var/lib/docker/vfs/dir/47ecf269f5ffc15ff560c9d95639b250506b53b73d6f58fce2fb78154c736ef8"
    }```

Then, I do:

```
https://10.45.2.11:2375/v1.15/containers/4758a0d88a5b93a268bdd47aa353d0a82317bb56eebc1385d181678bf3307920/start
{'Binds': [u'/var/lib/docker/vfs/dir/387f6dddfd4b2b82442c567a8729cc64b353220874f8e1bb2f5052145a96d0b0:/etc/mysql:rw', u'/var/lib/docker/vfs/dir/202869818d9571a693d39ec97cad1b616762434095769921d61d440f4e3c514b:/var/lib/mysql:rw', u'/var/lib/docker/vfs/dir/47ecf269f5ffc15ff560c9d95639b250506b53b73d6f58fce2fb78154c736ef8:/var/lib/mysql:rw', u'/var/lib/docker/vfs/dir/fc53b53ea3720d5c7b5276601f80cc172049793cb25287c5dcbe247844b10b0a:/etc/mysql:rw']}
``` 

This does not work in 1.4.1 and works in 1.3.3. The other option is to pass these binds at creation and not at starting, which would work in 1.4.1 but not in 1.3.3. I know this might be better by using data containers, but I think we should fix this inconsistency while we don't have #8484 

Note that the issue is only when mounting host folders created by docker in `/var/lib/docker/vfs/dir/`, other host folders look fine.

**Comment by pchico83** [comment]
@cpuguy83 I found the case where this happens. I had a mysql container mounting 2 volumes and I removed the container without removing its volumes. Now, I want to deploy a new mysql container reusing those volumes, which live at:

```
"Volumes": {
   "/etc/mysql":
      "/var/lib/docker/vfs/dir/fc...0a",
   "/var/lib/mysql":
      "/var/lib/docker/vfs/dir/47...f8"
}
```

Then, I do:

```
https://10.45.2.11:2375/v1.15/containers/47...20/start
{
    'Binds': [
        u'/var/lib/docker/vfs/dir/fc...0a:/etc/mysql:rw',
	u'/var/lib/docker/vfs/dir/47...f8:/var/lib/mysql:rw'
     ]
}

``` 

This does not work in 1.4.1 and works in 1.3.3. The other option is to pass these binds at creation and not at starting, which would work in 1.4.1 but not in 1.3.3. I know this might be better by using data containers, but I think we should fix this inconsistency while we don't have #8484 

Note that the issue is only when mounting host folders created by docker in `/var/lib/docker/vfs/dir/`, other host folders look fine.

**Comment by cpuguy83** [comment]
You can pass bind mounts on create or start in 1.3.3, they just won't actually be created until the container is started.

That said, I cannot reproduce this on 1.4.1.

```bash
$ curl -H 'Content-Type: application/json' -XPOST localhost:2375/containers/foo/start -d '{ "Binds": ["/var/lib/docker/vfs/dir/f6cd891e831f181650c69911e65b58e1d639898059d06e3be9253549248da928:/foo"]}'

$ docker inspect -f '{{ json .Volumes }}' foo
{"/foo":"/var/lib/docker/vfs/dir/f6cd891e831f181650c69911e65b58e1d639898059d06e3be9253549248da928"}
```

**Comment by pchico83** [comment]
These are the steps to repro it:

```
docker run -d --name aaa tutum/mysql
docker inspect -f '{{ json .Volumes }}' aaa
   {
      "/etc/mysql":
         "/var/lib/docker/vfs/dir/d4aebcc984652d51bd01fe5874560fe1fce8b8779b4596d440c290290d0a4e73",
      "/var/lib/mysql":
         "/var/lib/docker/vfs/dir/eee566ec7b51f1b8c7f0f1b92a0d61e1cfc445bc00e7e0012686da865b2d82ba"
   }
docker create --name bbb tutum/mysql
curl -H 'Content-Type: application/json' -XPOST localhost:2375/containers/bbb/start -d '{ "Binds": ["/var/lib/docker/vfs/dir/d4aebcc984652d51bd01fe5874560fe1fce8b8779b4596d440c290290d0a4e73:/etc/mysql"]}'
docker inspect -f '{{ json .Volumes }}' bbb
   {
      "/etc/mysql":
         "/var/lib/docker/vfs/dir/d9229725caf411ef79127b62af7157815fb27e0017a2a0835971f4726414c264",
      "/var/lib/mysql":
         "/var/lib/docker/vfs/dir/e5db26a469fb9ebb2ceae0ebf42a271986786e7b2f6ef39a81fc96a25f14752d"
}
```

**Comment by cpuguy83** [comment]
Did you try this on master?  You can grab a pre-compiled binary here: https://master.dockerproject.com

**Comment by pchico83** [comment]
It is still happening in docker 1.5.0

**Comment by cpuguy83** [comment]
@pchico83 see referenced pr

**Comment by pchico83** [comment]
@cpuguy83 Thanks!
