### ISSUE TITLE
Test if the Bridge IP is excluded from the ipallocator address pool

### ISSUE THREAD

**Issue by MalteJ** [docker/docker#9986]
We need a test to ensure the functionality of https://github.com/docker/docker/pull/9975

**Comment by taohu** [comment]
Hi,
I'm working on this, but found a problem that is addressed by #10215.

**Comment by superseb** [comment]
@taohu Are you still working on this? #10215 is merged.

**Comment by fgimenez** [comment]
#dibs

**Comment by fgimenez** [comment]
I guess that this is done after #17012 has been merged, sorry for not including a proper closing comment.

**Comment by thaJeztah** [comment]
@fgimenez oh, yes! Thanks I'll close
